### ISSUE TITLE
Error in py.test  (gaierror)

### ISSUE THREAD

**Issue by ZenXYZ** [mitmproxy/mitmproxy#1000]
##### Steps to reproduce the problem:

1.I run MINT 17.3 in VMware fusion, and install mitmproxy by pip.(0.16)
2.run py.test

##### What went wrong?

2.I got this error:

```
__ ERROR at setup of TestServerIPv6.test_echo ___

cls = <class 'test.netlib.test_tcp.TestServerIPv6'>

    @classmethod
    def setup_class(cls):
        cls.q = queue.Queue()
        s = cls.makeserver()

test/netlib/tservers.py:94: 

test/netlib/tservers.py:101: in makeserver
    return _TServer(cls.ssl, cls.q, cls.handler, cls.addr)
test/netlib/tservers.py:34: in __init__
    tcp.TCPServer.__init__(self, addr)
netlib/tcp.py:834: in __init__
    self.socket.bind(self.address())
name = 'bind', self = <socket._socketobject object at 0x7f7498f212f0>, args = (('localhost', 0),)

    def meth(name,self,*args):
>       return getattr(self._sock,name)(*args)
E       gaierror: [Errno -2] Name or service not known

/usr/lib/python2.7/socket.py:224: gaierror
```

##### Any other comments?

---

Mitmproxy Version:0.16
Operating System: Linux ubuntu 14.04

**Comment by mhils** [comment]
Thanks for the report. This looks like `localhost` is not defined on your system. Can you confirm that? If you point localhost to 127.0.0.1, does it fix the problem?

**Comment by ZenXYZ** [comment]
Thanks for the reply.
I checked my /etc/hosts file, there is a "127.0.0.1 localhost" record there.
"ping localhost" is also fine.
BTW, in python shell, I can bind localhost
`>>> s.bind(('localhost',8080))` <-- no error.

**Comment by mhils** [comment]
Thanks @ZenXYZ. Could you execute
```python
from netlib import tcp
tcp.TCPServer(("localhost",0))
```
in a Python shell and let us know what happens?

**Comment by ZenXYZ** [comment]
got `<netlib.tcp.TCPServer object at 0x7f19d18899d0>`

**Comment by mhils** [comment]
I initially missed that this happens in an IPv6 test. Does the following work for you?
```python
from netlib improt tcp
addr = tcp.Address(("localhost", 0),use_ipv6=True)
s = tcp.TCPServer(addr)
```

**Comment by ZenXYZ** [comment]
Sorry for late reply,
Got same error message,
but after add "localhost" in /etc/hosts, no error!
`::1     localhost ip6-localhost ip6-loopback`
Thank you!
