### ISSUE TITLE
Combine mitmproxy & pathod docs

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#1001]
Since both projects merged, and also the repository structure has changed significantly, it would be a good idea to merge the documentation as well. This means taking the [pathod docs](http://pathod.net/docs/pathod) and add them as a part to the [mitmproxy docs](http://docs.mitmproxy.org/en/latest/). Some parts might be redundant and can be removed. I think the interactive pathod/pathoc language preview feature can be replace entirely by a more extensive example section. Also the links in the README can be fixed after this.

The website [pathod.net](http://pathod.net) should then be a redirect to the [mitmproxy documentation](http://docs.mitmproxy.org/). (@cortesi)

**Comment by mhils** [comment]
:+1:

**Comment by cortesi** [comment]
Docs have been moved over, but require rewrite and massaging for the non-interactive format. I'll redirect the website once the docs are more or less ready.

**Comment by Kriechi** [comment]
@cortesi what is missing to complete this?
As far as I can see, only the interactive language preview widget is missing (which IMHO we don't really need)

http://docs.mitmproxy.org/en/latest/pathod/intro.html (and following) is basically the same content as http://pathod.net/docs/pathod.

The homepage of pathod: http://pathod.net/ is really outdated anyway...
v0.13 and still pointing to the old repository.

I'm in favour of immediately redirecting http://pathod.net -> http://docs.mitmproxy.org/en/latest/pathod/intro.html
