### ISSUE TITLE
Support reading from flow files continuously

### ISSUE THREAD

**Issue by dwfreed** [mitmproxy/mitmproxy#1002]
Basically like tail -f file, keep trying to read from the specified flow file periodically.  This would allow you to do things like have mitmdump running on one machine outputting to a flow file, and mitmproxy reading that flow file on another machine.  Especially useful when running mitmdump as a service on a Linux router in transparent mode, with iptables rules to control which hosts get sent through the proxy (which is my intended usecase).

**Comment by mhils** [comment]
Thanks for the suggestion. Can you point me to other tools that support such a behaviour? In theory, if the underlying file blocks, that should just work.

**Comment by dwfreed** [comment]
First off, I'm dumb; command should be using `<()`, not `$()`.  However, both mitmproxy and mitmdump crash at the same place with the correct command:

```pytb
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/bin/mitmdump", line 9, in <module>
    load_entry_point('mitmproxy==0.16', 'console_scripts', 'mitmdump')()
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/main.py", line 96, in mitmdump
    master = dump.DumpMaster(server, dump_options)
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/dump.py", line 128, in __init__
    self.load_flows_file(options.rfile)
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 899, in load_flows_file
    return self.load_flows(freader)
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 887, in load_flows
    for i in fr.stream():
  File "/usr/local/Cellar/mitmproxy/0.16/libexec/lib/python2.7/site-packages/libmproxy/flow.py", line 1147, in stream
    off = self.fo.tell()
IOError: [Errno 29] Illegal seek
```

This is because the "file" they're trying to read from is a FIFO, which does not support the underlying lseek system call used by `file.tell()`.

**Comment by mhils** [comment]
c17ccead6db98346fa088f7ca035af24694af659 fixes this! :smiley:

refs jbremer/httpreplay/pull/5

**Comment by rugk** [comment]
IMHO this still does no9t fix the issue.
`mitmproxy` should just have an `-f` option to continuously read a file…

Also `<()` is a bash feature not available anywhere.

So this should also work, e.g.:
```sh
$ tail -f ./mitmproxy-flow.cap|mitmproxy --rfile -- -n
usage: mitmproxy [options]
mitmproxy: error: argument --rfile/-r: expected one argument
```

And I've tried usage example in mitmproxy 5.2 and it did not work either (first time it froze the whole `mitmproxy`, second time it crashed):
```sh
$ mitmproxy -r <(tail -f ./mitmproxy-flow.cap) -n
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 55, in reraise
    value = tp()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
```

Should I open a new issue for this?

----

Also, the general behaviour is a feature request:
* If you use `-r` and provide no file path – it should read from STDIN (standard input), just like any other Linux tool
* If you use `-r` and provide a file path, there should be an option `-f` to _follow_ the file and automatically load it.

**Comment by rugk** [comment]
Another crash:
```sh
$ tail -f ./mitmproxy-flow.cap|mitmproxy -n -r -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
    loop()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 55, in reraise
    value = tp()
TypeError: 'NoneType' object is not callable

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
sys:1: RuntimeWarning: coroutine 'Master._shutdown' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by mhils** [comment]
> `mitmproxy` should just have an `-f` option to continuously read a file…

Not really, `--rfile -` is just fine.

> So this should also work, e.g.:
> 
> ```shell
> $ tail -f ./mitmproxy-flow.cap|mitmproxy --rfile -- -n
> usage: mitmproxy [options]
> mitmproxy: error: argument --rfile/-r: expected one argument
> ```

Single instead of double hyphen, but yes:
```
$ tail -f ./mitmproxy-flow.cap | mitmproxy --rfile - -n
```

If that doesn't work we probably have a regression here, which isn't unlikely because that part has been rewritten when we moved it to an addon.

> And I've tried usage example in mitmproxy 5.2 and it did not work either (first time it froze the whole `mitmproxy`, second time it crashed):
> 
> ```shell
> $ mitmproxy -r <(tail -f ./mitmproxy-flow.cap) -n
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/mitmproxy/master.py", line 86, in run_loop
>     loop()
>   File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 286, in run
>     self._run()
>   File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 384, in _run
>     self.event_loop.run()
>   File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1484, in run
>     reraise(*exc_info)
>   File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 55, in reraise
>     value = tp()
> TypeError: 'NoneType' object is not callable

That looks like an unreleated urwid bug, please feel free to open isssue with a proper minimal reproducible example.

> Also, the general behaviour is a feature request:
> 
> * If you use `-r` and provide no file path – it should read from STDIN (standard input), just like any other Linux tool
> * If you use `-r` and provide a file path, there should be an option `-f` to _follow_ the file and automatically load it.

I propose the following: If `-` is passed as the file path, we stream from STDIN. There is no need for an additional option. :)

**Comment by rugk** [comment]
From https://github.com/mitmproxy/mitmproxy/issues/4113#issuecomment-665666744
I'll continue that discussion here, because that is the general feature request issue.

Sorry if it sounded demanding, this was not my intention. Also note reporting bugs is an important thing to do…
So, back to topic… 

> That being said, you don't want to pipe into mitmproxy, that doesn't work well because you need stdin for keyboard input.

Hmm, I'm not really sure, but if that is the case, then we are at this feature request again.

> I propose the following: If - is passed as the file path, we stream from STDIN. There is no need for an additional option. :)

Apparently there is, because I'd like to use the keyboard while reading a file from STDIN.
Or would the only workaround then be using bash's `<()` syntax? If so, I'd consider suboptimal from an UX point of view, because you have to look that up and learn that feature…

**Comment by mhils** [comment]
> Or would the only workaround then be using bash's <() syntax? If so, I'd consider suboptimal from an UX point of view, because you have to look that up and learn that feature…

It's not bash specific, you can use any form of pipe. Bash just happens to have a shortcut for anonymous pipes. And yes, I think pipes are the correct way forward.

**Comment by jaywor1** [comment]
Does reading from `stdin` still work @mhils ? I need it for mitmweb but i have tried it with mitmproxy as well and it doesn't even read the file 

### mitmweb
```
root@mitmweb-01:~# tail -f /var/log/mitmproxy/dump-merged.har | mitmweb --rfile - -n
tail: /var/log/mitmproxy/dump-merged.har: file truncated
[21:00:07.316] Web server listening at http://127.0.0.1:8081/
[21:00:07.414] No web browser found. Please open a browser and point it to http://127.0.0.1:8081/
[21:00:07.414] Cannot load flows: [Errno 2] No such file or directory: '-'
[21:00:07.414] Failed to read -: [Errno 2] No such file or directory: '-'
Traceback (most recent call last):
  File "mitmproxy/addons/readfile.py", line 63, in load_flows_from_path
FileNotFoundError: [Errno 2] No such file or directory: '-'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mitmproxy/addons/readfile.py", line 71, in doread
  File "mitmproxy/addons/readfile.py", line 67, in load_flows_from_path
mitmproxy.exceptions.FlowReadException: [Errno 2] No such file or directory: '-'
Errors logged during startup, exiting...
root@mitmweb-01:~# 
```

### mitmproxy
Really mess-ups terminal and i get this error
```
Invalid filter expression: 'on": "1.1"'
```

I tested the file running it with a `-r` option and it normally loads the file.
