### ISSUE TITLE
Support sending the eventlog to a file by cmdline option

### ISSUE THREAD

**Issue by dwfreed** [mitmproxy/mitmproxy#1003]
I'd like to be able to send the eventlog to a file using a cmdline option.  My usecase is running mitmdump as a service on my Linux router in transparent mode.  Services should not write to stdout/stderr, and what I'll be using to daemonize mitmdump will close stdout/stderr before executing mitmdump anyway.  Even running mitmdump in quiet mode prints errors from the eventlog to the console.

**Comment by dufferzafar** [comment]
Possibly related: #400.

**Comment by dwfreed** [comment]
Arguably a duplicate; I probably should have looked more closely at the issues list before opening this one.

**Comment by dufferzafar** [comment]
Happens with everyone. :smile_cat:
