### ISSUE TITLE
Https connection to non-exisiting url has status code 200 instead of 502

### ISSUE THREAD

**Issue by IchbinkeinReh** [mitmproxy/mitmproxy#1007]
##### Steps to reproduce the problem:
1. Run mitmdump
2. Visit some non-existing host with https (e.g https://abc123.org/) in browser that uses the mitmdump proxy

##### What is the expected behavior?
Status code 502

##### What went wrong?
I get status code 200 with the following content:
```
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>ProtocolException('Server connection to abc123.org:443 failed: Error connecting to "abc123.org": [Errno 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte',)</body>
        </html>
```
When i try to visit a non-existing host with http (e.g. https://abc123.org/) everything works as expected. I get status code 502 with the same content as above.

---

Mitmproxy Version: 0.16
Operating System: Windows 10 64bit

**Comment by mhils** [comment]
Thanks for the report. The current behaviour looks fairly correct to me. Do you see something else?
```
λ curl https://qiwnyinqwey.com/ -x localhost:8080 -v -k
* timeout on name lookup is not supported
*   Trying ::1...
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Establish HTTP proxy tunnel to qiwnyinqwey.com:443
> CONNECT qiwnyinqwey.com:443 HTTP/1.1
> Host: qiwnyinqwey.com:443
> User-Agent: curl/7.46.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*        subject: CN=qiwnyinqwey.com
*        start date: Mar  5 09:18:52 2016 GMT
*        expire date: Mar  7 09:18:52 2019 GMT
*        issuer: CN=mitmproxy; O=mitmproxy
*        SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
> GET / HTTP/1.1
> Host: qiwnyinqwey.com
> User-Agent: curl/7.46.0
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< Content-Length: 276
< Content-Type: text/html
< Connection: close
< Server: netlib 0.17
<
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>ProtocolException('Server connection to qiwnyinqwey.com:443 failed: Error connecting to "qiwnyinqwey.com": [Errno 11001] getaddrinfo failed',)</body>
        </html>* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
```

**Comment by IchbinkeinReh** [comment]
Well, the problem is that mitmproxy first sends:
< HTTP/1.1 200 Connection established
and later then
< HTTP/1.1 502 Bad Gateway
and the browser only recognizes the first status code

**Comment by mhils** [comment]
We confirm the `CONNECT` request so that users can use either server replay or inline scripts to react to requests before we establish an outbound connection. A client not respecting the second 502 is really weird - which browser are we talking about?

**Comment by IchbinkeinReh** [comment]
Ok maybe this is not a bug in mitmproxy. I found that the status code is 200 in Firefox, but Chrome correctly shows 502.

**Comment by mhils** [comment]
Well.. we do disrespect [draft-luotonen-web-proxy-tunneling-01](https://tools.ietf.org/html/draft-luotonen-web-proxy-tunneling-01) a bit:

> the proxy will make a connection to the destination server, and, if successful, send a "200 Connection established" response to the client.

We just always send a `200 OK` as we connect as late as possible to make server replay and inline scripts work. Getting a 502 from the proxy is arguably unexpected after erstablishing a tunnel, but that could come from the real server just as well. 

We _could_ implement an option that enables immediate connects, but I didn't find a good use case that would justify the added complexity.

**Comment by IchbinkeinReh** [comment]
Ok. Thank you. Now i also understand the problem. For me this is not an issue anymore. I was only puzzled because firefox shows status 200. Fortunately the browser which i will use later (phantomjs) doesnt have this problem and shows the correct status code.

**Comment by mhils** [comment]
:+1: 

Closing this for now. :smiley:
