### ISSUE TITLE
MitmProxy decrypt HTTPS not works

### ISSUE THREAD

**Issue by Tomi9575** [mitmproxy/mitmproxy#1010]
Hello All,

Thank you for this tool, this is awesome !

Just i want to decrypt HTTPS, but it's not work ...

I capture well the https flow But it is NOT decrypted , I have placed the certificate into mozilla firefox ... how can I solve this problem ?

thank you in advance.

Mitmproxy Version: 0.16
Operating System: Ubuntu 14.04

**Comment by mhils** [comment]
> I capture well the https flow

If you see the HTTPS flow in mitmproxy, TLS transport encryption has been removed. The content you are seeing may be encryped by additional means.

**Comment by Tomi9575** [comment]
Hello Mhils,

Thanks for you answer, indeed i tried with an other site, and i see everything.

So my problem is resolved, thanks four you reactivity !!
