### ISSUE TITLE
intercept traffic on an OpenVpn Server?

### ISSUE THREAD

**Issue by medyagh** [mitmproxy/mitmproxy#1017]
##### What is the expected behavior?

Can we install mitmproxy on a openvpn server ? so it intercepts traffic to/from the OpenVpn Server?

**Comment by mhils** [comment]
You can run mitmproxy in transparent mode anywhere you want - I think that includes VPN servers, there's not really anything special to them, is there?

**Comment by medyagh** [comment]
do I have to reroute the iptables from eth0 to tun0 ? or I still do the same iptable routings as before?
which are 
```
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80  -j REDIRECT --to-port 8080
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080
```

**Comment by medyagh** [comment]
so the idea is, I want to intercept the traffic of App1 on my phone. but I also don't want to intercept snapchat, but I still I wanna be able to use snapchat (so I don't want to block snapchat traffic) on my phone.

so I am trying to have a mimtproxy server in the cloud that only intercepts and logs App1 traffic but lets other apps go through and come back. do I need openvpn to make this happen ? I have been trying to configure it. the confusing part is the iptable routing complexeties.anyone has done something like this that works ?

**Comment by mhils** [comment]
I think the matter of ignoring traffic is a completely unrelated topic. See http://docs.mitmproxy.org/en/stable/features/passthrough.html!

**Comment by nesttle** [comment]
Trying to aproach same goal here.
Have a server with OpenVPN client connected (interface tun0, not eth0). 
Running mitmproxy -p 8080, but by default uses eth0 interface not tun0.

How to set tun0 as default interface for mitmproxy?

I tried with:

> root@OVPN:~# iptables -t nat -A PREROUTING -i tun0 -p tcp --dport 443 -j REDIRECT --to-port 8080
> root@OVPN:~# iptables -t nat -A PREROUTING -i tun0 -p tcp --dport 80 -j REDIRECT --to-port 8080
> root@OVPN:~# mitmproxy -p 8080

But no luck :/

**Comment by 00cool** [comment]
Hello @nesttle!

Did you find any information on how we can redirect the traffic from OpenVPN to the Mitmproxy? I'm trying to do the same. Thanks!
