### ISSUE TITLE
Cannot seem to find/replace in headers

### ISSUE THREAD

**Issue by absane** [mitmproxy/mitmproxy#1024]
In 0.13 I could find and replace "foo" with "bar" anywhere in the headers using the following snippet:

```
flow.request.headers.replace(context.old, context.new)
```
The point was to make changes like this in headers:

*Before:*
```
Host: foo.com
Cookie: SESSIONID=asdf; domain=asdffoo.com
```
*After:*
```
Host bar.com
Cookie: SESSIONID=asdf; domain=asdfbar.com
```
However, this same snippet does not work in 0.16. Replacing "foo" with "bar" in the body appears to work fine, however.

Has the functionality changed?

Thanks! :)

**Comment by Kriechi** [comment]
I think so yes. What error do you get?
Please take a look at the latest release and the Headers class:
https://github.com/mitmproxy/netlib/blob/v0.16/netlib/http/headers.py#L30

**Comment by absane** [comment]
Thanks for the link. I had a look and I do not see anything in there that allows me to do the find/replace I used to be able to. As for 0.13, I do not know where to find how this is implemented. I am using 0.13 that is built into Kali Linux. The 0.16 instance is on a Debian VPS.

As for an error, I do not see any errors. The script runs. Maybe there is a way to output errors?

**Comment by Kriechi** [comment]
Yes, the implementation has changed.
Please use `headers['foo'] = 'bar' ` or the `headers.set_all` function.
`Headers` should behave like a regular `dict` - so you can iterate through the items to find & replace.

**Comment by absane** [comment]
I see. So, will it be possible to find and replace "foo" with "bar" in something like

From:
Cookie: SESSIONID=asdf**foo**ghjk

To:
Cookie: SESSIONID=asdf**bar**ghjk
?

If so, I think I think I can figure it out (I'm not all that good with Python).. Admittedly it was much easier in 0.13

**Comment by absane** [comment]
Thank you. Though maybe as a feature request it might be nice to add the old functionality back ;)
