### ISSUE TITLE
mitmproxy/mitmdump fail on certain github API calls

### ISSUE THREAD

**Issue by veselov** [mitmproxy/mitmproxy#1025]
##### Steps to reproduce the problem:

1. run mitmdump
2. proxy through to github API (single call is enough)
3. see boom.

This is strange, but I can only see it when I successfully authenticate to github. I can't come up with a sample program and publish the values in the issue (I can provide them to you personally).

##### What is the expected behavior?

not crash?

##### What went wrong?

May be related to #169 

> [vps@palladin]~$ mitmdump 
> 127.0.0.1:34144: clientconnect
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 121, in handle
>     root_layer()
>   File "/usr/lib/python2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 11, in __call__
>     layer()
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 345, in __call__
>     self._establish_tls_with_client_and_server()
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 427, in _establish_tls_with_client_and_server
>     six.reraise(*sys.exc_info())
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 424, in _establish_tls_with_client_and_server
>     self._establish_tls_with_client()
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 433, in _establish_tls_with_client
>     cert, key, chain_file = self._find_cert()
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 566, in _find_cert
>     return self.config.certstore.get_cert(host, list(sans))
>   File "/usr/lib/python2.7/site-packages/netlib/certutils.py", line 341, in get_cert
>     sans),
>   File "/usr/lib/python2.7/site-packages/netlib/certutils.py", line 96, in dummy_cert
>     ipaddress.ip_address(i.decode("ascii"))
> AttributeError: 'NoneType' object has no attribute 'decode'
> 
> mitmproxy has crashed!
> Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
> 127.0.0.1:34144: Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 121, in handle
>     root_layer()
>   File "/usr/lib/python2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 11, in __call__
>     layer()
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 345, in __call__
>     self._establish_tls_with_client_and_server()
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 427, in _establish_tls_with_client_and_server
>     six.reraise(*sys.exc_info())
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 424, in _establish_tls_with_client_and_server
>     self._establish_tls_with_client()
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 433, in _establish_tls_with_client
>     cert, key, chain_file = self._find_cert()
>   File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 566, in _find_cert
>     return self.config.certstore.get_cert(host, list(sans))
>   File "/usr/lib/python2.7/site-packages/netlib/certutils.py", line 341, in get_cert
>     sans),
>   File "/usr/lib/python2.7/site-packages/netlib/certutils.py", line 96, in dummy_cert
>     ipaddress.ip_address(i.decode("ascii"))
> AttributeError: 'NoneType' object has no attribute 'decode'
> 
> 127.0.0.1:34144: clientdisconnect
> 

##### Any other comments?

---

Mitmproxy Version: 0.16
Operating System: Linux, FC22

**Comment by mhils** [comment]
Thanks for the report! This should be fixed on master now :smiley:
