### ISSUE TITLE
ImportError: No module named mitmproxy

### ISSUE THREAD

**Issue by joaolcorreia** [mitmproxy/mitmproxy#1026]
##### Steps to reproduce the problem:

1. Mac OSX, Python 2.7.11 :: Anaconda 2.4.0 

$ python
Python 2.7.11 |Anaconda 2.4.0 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import mitmproxy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mitmproxy
>>> 

##### What is the expected behavior?
I would expect the module to be installed

##### What went wrong?
I installed mitmproxy with sudo pip install mitmproxy and it installed successfully. The binary mitmproxy runs fine but python can't find the module. Any ideas?

Thanks
Joao

**Comment by dufferzafar** [comment]
In version 0.16 (which I'm assuming you've installed) the mitmproxy module is called `libmproxy`.

So, try using: `import libmproxy`

**Comment by joaolcorreia** [comment]
I had to download source and do python setup.py install. It is installed now. Thank you @dufferzafar !
