### ISSUE TITLE
mitmproxy segfaults when analyzing snapchat

### ISSUE THREAD

**Issue by d135-1r43** [mitmproxy/mitmproxy#1028]
##### Steps to reproduce the problem:

1. Start mitmproxy on a Raspberry Pi (ARM)
2. Connect an iPhone with Snapchat installed to that running mitmproxy
3. Start Snapchat
4. mitmproxy segfaults

##### What is the expected behavior?
No seg fault. 

##### Any other comments?
Does not happen when mitmproxy runs on OS X.

---

Mitmproxy Version: 0.10.1
Operating System: Raspibian 8.0, Linux 4.1.18-v7+

**Comment by mhils** [comment]
Is this the same as https://github.com/mitmproxy/mitmproxy/issues/922?

**Comment by d135-1r43** [comment]
As far as I can see no. It does not happen on OS X, terminal is still functional and the shell displays clearly "Segmentation fault".

**Comment by mhils** [comment]
I suspect the OpenSSL version to be the common denominator. Which version is your PI running on? What happens if you update OpenSSL?

**Comment by d135-1r43** [comment]
```
 $ openssl version
 OpenSSL 1.0.1k 8 Jan 2015
```

I currently do not have the possibility to update openssl to another version.

**Comment by mhils** [comment]
Thanks for the feedback. I don't have a Raspberry Pi to reproduce - it would be of great help if we could get a traceback for this ([see here](https://unix.stackexchange.com/questions/132192/running-application-ends-with-segmentation-fault)).
