### ISSUE TITLE
SQLite Flow Storage Format

### ISSUE THREAD

**Issue by dufferzafar** [mitmproxy/mitmproxy#1029]
We currently use a plain text file as a flow storage format and dump the flows as typed netstrings.

It was proposed that we should switch to a SQLite database to store the flows.

**Comment by cortesi** [comment]
This is a change that’s a long time coming, and I’m eager to have it in tree. Let me give some quick words on the motivation for this, the risks, and how I think it should be tackled.

The flat netstrings-based structure we have has served us well, but there are a number of reasons to switch. First, the shape of our data increasingly doesn’t fit an append-only structure with one item per “flow”. We waste a considerable amount of space duplicating information that could be stored just once - server SSL information and TCP connection data, for example. Second, we currently load all flow data into memory, with the persistent store just there as an append-only log. Switching to SQLite will  let us be much smarter about this, letting us avoid loading everything into memory at once, and therefore letting us comfortably handle much larger dump volumes. Third, the link between interactive use and the persistent store is currently awkward. For instance, users might expect to be able to open a dumpfile, delete a flow, and have that reflected in the stored data. That’s not how it works at the moment - we load everything into memory, the user deletes one record from memory, and then would have to dump everything back out to disk manually to see a persistent change. Using SQLite will let us have a much more natural interaction pattern. This would also lead to lots of other workspace-like features that I would personally like to have - notes, annotations, tags and other conveniences that would help in analysis.

There are some risks and issues here. First, SQLite pads its storage files generously, which means that for small numbers of flows a SQLite file would be larger than a tnetstrings file (though highly compressible). Second, database corruption in SQLite, when it happens, is not pretty, and not highly recoverable like the append-only tnetstrings data format is. Third, washing this through the project, especially considering all the ways in which the interaction model could be improved afterwards, is a really big job that will touch all of mitproxy. 

I’d like to proceed quite cautiously with this. The first step should be to abstract the serialization mechanism behind an interface (more or less done, but some cleanup required), and then make a drop-in replacement with SQLite with the same semantics (i.e. treating SQLite as an append-only log, like our current format). When that’s stable, we can begin the task of washing the changes through our interactive components (mitmweb/mitmproxy) - I’d anticipate that the impact on mitmdump will be minimal.

**Comment by cortesi** [comment]
Our thinking here has now evolved. The flow storage format will remain an immutable record with much the same format as it has today. We'll add a state scratch-space where addons and users can annotate flows to cope with dynamic storage needs.

**Comment by ossie-git** [comment]
Has there been any rethinking of this issue?  The problem is if you try to orchestrate all requests across your environment (even if it is just a home environment), the memory usage becomes impractical after a few hours or a day.  So if you want to log for a week or more, you're basically out of luck.  scripts such as [mitmdump-logger](https://github.com/chair6/varnish-wrapper/blob/master/mitmdump-logger.py) do this but they won't decrease the memory being used by mitmproxy
