### ISSUE TITLE
Got ImportError(mitmproxy.models) when using example

### ISSUE THREAD

**Issue by ZenXYZ** [mitmproxy/mitmproxy#1035]
##### Steps to reproduce the problem:

1. version:0.16 on ubuntu 14.04(new machine, clean install)
2. install by pip, and download examples by git
3. Use Transparent mode, intercepting traffic works fine.
4. Try to use -s option with example provided but got error.(no mitmproxy.models module)

##### What went wrong?
Got this error:
```
>>>mitmdump -T -s upsidedownternet.py
mitmdump: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/script/script.py", line 66, in load
    execfile(self.args[0], self.ns, self.ns)
  File "upsidedownternet.py", line 3, in <module>
    from mitmproxy.models import decoded
ImportError: No module named mitmproxy.models
```

##### Any other comments?

---

Mitmproxy Version: 0.16
Operating System: ubuntu 14.04

**Comment by Kriechi** [comment]
Basically the same: https://github.com/mitmproxy/mitmproxy/issues/1026
You are using version 0.16, but examples from the latest git commit - what did you expect?

**Comment by dufferzafar** [comment]
@Kriechi Seeing how many of these similar issues we get, I feel that we should just do a new 0.17 release?
