### ISSUE TITLE
mitmdump uses high memory in long run

### ISSUE THREAD

**Issue by medyagh** [mitmproxy/mitmproxy#1036]
##### Steps to reproduce the problem:

1. run mimtdump in regular proxy mode
2. pass traffic to it for a day

##### What went wrong?

it used all memory and left only 17mb free memory in a 1GB memory VM, which only has mitmdump running on it.

##### Any other comments?

Mitmproxy Version: 0.16
Operating System:Ubuntu 14.04.3 LTS

**Comment by medyagh** [comment]
I just noticed my output file size was 800MB, is there any way to make the outputfile be spliltted into smaller sizes  like 50mb ?

**Comment by dufferzafar** [comment]
I *think* the dump file size will get reduced once #1029 gets solved!

**Comment by mhils** [comment]
@dufferzafar, mitm*dump* should not have an increasing memory profile in any case.

**Comment by medyagh** [comment]
is there a way to make mitmdump to split the fileze when it reaches to a specific size ? like make a new file if it is more than 10 MB ?

**Comment by FrobozzElectric** [comment]
> is there a way to make mitmdump to split the fileze when it reaches to a specific size ? like make a new file if it is more than 10 MB ?

I wonder, would this be possible with mitmproxy and inline scripts?

**Comment by cortesi** [comment]
I'm closing this issue so we can consolidate discussion in #1519.
