### ISSUE TITLE
Splitting HTTP GET requests with mitmproxy

### ISSUE THREAD

**Issue by jonathankua** [mitmproxy/mitmproxy#1037]
Hi all,

I'm not sure if this is the right place to ask for help. I'm new to mitmproxy and I'd like to explore mitmproxy as an option for splitting HTTP GET requests at the proxy level. 
The idea is  similar to that of "download accelerators", where the proxy takes one HTTP GET request (for a chunk of data) from the application/browser and split the request to multiple GET requests for "sub-chunks" of the file. Upon receiving the sub-chunks, the proxy then re-orders and combines them into one chunk and pass it on to the application.

Is it possible for mitmproxy to do that? Does anyone has an existing script/library that can achieve this purpose?
If anyone can point me in the right direction, that would be much appreciated.
Thank you.

Regards,
Jonathan

**Comment by mhils** [comment]
While there is nothing that prohibits you from implementing that, mitmproxy is not really designed to be a download "accelerator" and an implementation would be rathere painful. I'd recommend using a tool like [JDownloader](http://jdownloader.org/) for fast downloads. I'm sorry, but we don't plan to support this feature in the future.

**Comment by jonathankua** [comment]
Hi Maximilian,

Thanks for your prompt reply. It is much appreciated.

Regards,
Jonathan
