### ISSUE TITLE
When replay a request never timeout.

### ISSUE THREAD

**Issue by mindcat** [mitmproxy/mitmproxy#1044]
##### Steps to reproduce the problem:

1. Send a request to server that server receive request but never respond;
2. 
3. 

##### What is the expected behavior?
After 60 seconds the request disconnected and throw Error;

##### What went wrong?
It didn't timeout.

##### Any other comments?
it will be block my script runs.

Could I set timeout when my script replay request?

---

Mitmproxy Version: mitmproxy 0.15
Operating System: Arch Linux

**Comment by mhils** [comment]
Thanks for the report. This is closed in favor of #1095, which tracks implementing timeouts in general.
