### ISSUE TITLE
testing for header value weird behavior

### ISSUE THREAD

**Issue by internety** [mitmproxy/mitmproxy#1051]
##### Steps to reproduce the problem:

below test is always false.
```
def request(ctx, flow):
    if flow.request.headers.get( 'content-type' ) is "application/x-amf" :
```

while this code works as expected:
```
def request(ctx, flow):
    if flow.request.headers.get( 'content-type' ) == "application/x-amf" :
```

Mitmproxy Version: 
0.15

Operating 
System: Linux potpaL 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux

**Comment by dufferzafar** [comment]
@internety I think that's standard Python semantics. Reference: http://stackoverflow.com/a/13650309
