### ISSUE TITLE
Function `start` is never called in inline scripts

### ISSUE THREAD

**Issue by Fuzion24** [mitmproxy/mitmproxy#1052]
using this https://raw.githubusercontent.com/mitmproxy/mitmproxy/master/examples/stub.py on 0.16

![screen shot 2016-03-24 at 5 04 54 pm](https://cloud.githubusercontent.com/assets/772364/14031293/9097c7ae-f1e2-11e5-99d5-5793e8097966.png)

**Comment by giantpune** [comment]
I went back and tried that stub.py script on these releases.  https://hub.docker.com/r/mitmproxy/releases/tags/  It works on 0.12 and 'start' is not called starting at 0.12.1.

**Comment by mhils** [comment]
Does `mitmdump` work for you guys? What happens if you add an inline script after mitmproxy has been started?

**Comment by giantpune** [comment]
yes, with mitmdump, i see start getting called on all versions from 0.12 to 0.16.
