### ISSUE TITLE
Regex matching seems kinda busted? (or perhaps just not intuitive)

### ISSUE THREAD

**Issue by dwfreed** [mitmproxy/mitmproxy#1053]
##### Steps to reproduce the problem:

1. Catch some requests that have JSON responses
2. Try to limit your display to responses that contain an empty list

##### What is the expected behavior?

Something like ~bs '"key"':\[\] should result in matching all bodies that contain "key":[]

##### What went wrong?

No match

##### Any other comments?

I've tried several different variations of quoting and escaping the [] to no avail.  My ultimate goal is to match bodies that contain the key, but whose value is not an empty list, and my responses are all minified JSON.  (So my expression would be something like ~bs '"key"' & ! ~bs '"key":[]' which I've tried, and it tells me Invalid filter expression.)

---

Mitmproxy Version: 0.16
Operating System: OS X Mavericks

**Comment by mhils** [comment]
It looks like there's an issue with the quotation marks - I need to look into it. In the meantime, the following workaround works just fine: 
```
mitmdump '~bs key.:\[\]'
```
```
curl -k -x localhost:8080 https://gist.githubusercontent.com/mhils/c9b70d25504bdb26bd6e/raw/7b66f2ef49adea9f8876ea8cc9c4
786387aabd74/a.json && curl -k -x localhost:8080 https://gist.githubusercontent.com/mhils/c9b70d25504bdb26bd6e/raw/7
b66f2ef49adea9f8876ea8cc9c4786387aabd74/b.json
```

**Comment by dwfreed** [comment]
For what I want to do, it looks like I'm going to have to just write a script, because at this point I'm basically trying to parse JSON with regex so now I've got 2 problems... (relevant: https://xkcd.com/1171/)
