### ISSUE TITLE
mitmproxyy cannot catch anything!

### ISSUE THREAD

**Issue by smileyogurt** [mitmproxy/mitmproxy#1054]
##### Steps to reproduce the problem:

1. Followed the steps in mitmproxy.org to install mitmproxy and cert 
2. config firefox + autoproxy by adding a new proxy "mitmproxy 127.0.0.0 8080"
3. start mitmproxy: mitmproxy -p 8080
4. on firefox, browse a website "http://baidu.com"

##### What is the expected behavior?
suppose to see the network flow

##### What went wrong?
mitmproxy console has NO output at all.

##### Any other comments?
Also tried all other command lines, i.e. "mitmproxy -R xxx", nothing works for me. I never see mitmproxy catching anything. 

Please advice and help!
---

Mitmproxy Version: 0.16
Operating System:  mac

**Comment by Kriechi** [comment]
Please consult the autoproxy documentation to configure it correctly.
Port 8080 is the default - so you should be able to omit it.
Just run `mitmproxy` (without parameters) in your terminal.
Also take a look at http://docs.mitmproxy.org/en/latest/modes.html on how to operate mitmproxy in different modes.

**Comment by smileyogurt** [comment]
I tried other ports,no eWorld. Of courses, I followed the steps ihe web site, other I always cannot catch anything!

**Comment by smileyogurt** [comment]
I tried other ports, the same results. Of courses, I followed the steps in the web site, but I always cannot catch anything!
