### ISSUE TITLE
Does mitmproxy support broadcast

### ISSUE THREAD

**Issue by smileyogurt** [mitmproxy/mitmproxy#1059]
I would like to use a proxy to modify the request URL, broad to different servers and finally assemble the requests to send back. Does mitmproxy support this feature?

**Comment by Kriechi** [comment]
How would this assemble step look like?
I'm not aware of anything in mitmproxy-core that would handle this - but you could try to write a script for it. http://docs.mitmproxy.org/en/stable/scripting/inlinescripts.html

**Comment by smileyogurt** [comment]
Thanks, I will take a look and try it out!
