### ISSUE TITLE
Invalid Wheel filenames

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1065]
##### Steps to reproduce the problem:

1. `pip install https://snapshots.mitmproxy.org/mitmproxy-latest-py2-none-any.whl`

##### What is the expected behavior?

It installs.

##### What went wrong?

```
mitmproxy-latest-py2-none-any.whl is not a valid wheel filename.
```

**Comment by Kriechi** [comment]
I think this defines a valid filename:
```python
r"""^(?P<namever>(?P<name>.+?)-(?P<ver>\d.*?))
((-(?P<build>\d.*?))?-(?P<pyver>.+?)-(?P<abi>.+?)-(?P<plat>.+?)
\.whl|\.dist-info)$""",
```

**Comment by mhils** [comment]
From https://github.com/pypa/pip/blob/ce8999dd0dce4848f109a1b22384ad9050a27998/pip/wheel.py#L616 - this is a really weird regex...

**Comment by mhils** [comment]
I removed the symlink for the wheel in 3b71c19af34689b6c908956b45817864c14d451c.
