### ISSUE TITLE
MITMWEB: search, highlight, intercept not working

### ISSUE THREAD

**Issue by peterglock** [mitmproxy/mitmproxy#1070]
##### Steps to reproduce the problem:

1. On OS X El Capitain, update to latest version `pip install --upgrade mitmproxy`
2. start mitmweb, I'm ignoring domains with certificate pinning `mitmweb -T --wport 8888  -v --host --anticache -p 8080 --ignore '(69\.171\.\d+\.\d+:443)|(31\.13\.\d+\.\d+:443)|(17\.\d+\.\d+\.\d+:443)|(216\.58\.\d+\.\d+:443)|(104\.69\.\d+\.\d+:443)|(108\.174\.\d+\.\d+:443)'`
3. open browser (I tried both Safari and Chrome) and attempt to search, highlight or intercept streams using the selection boxes at the top of the browser window

##### What is the expected behavior?
search - shows list of streams matching expression
highlight - highlights matching streams
intercept - intercepts matching streams

##### What went wrong?
No change in browser window

##### Any other comments?
This was definitely working in 0.13

---

Mitmproxy Version: 0.16
Operating System: OSX 10.11.4 (15E65)

**Comment by mhils** [comment]
Thanks for the report, I believe this is fixed on master already. If you need it ASAP, take a look at https://snapshots.mitmproxy.org. :smiley:

**Comment by peterglock** [comment]
Fixed on 0.17 and tested ok on 0.18
