### ISSUE TITLE
[Docs] Online mitmproxy docs image not displaying correctly on Firefox (low-res)

### ISSUE THREAD

**Issue by bazzinotti** [mitmproxy/mitmproxy#1077]
This could be a https://github.com/snide/sphinx_rtd_theme issue. But I want to report here first since I'm not sure if your docs code could have caused this.

Windows 7 @ screen resolution 1024x768 -  FireFox 45.0.1 - visit http://docs.mitmproxy.org/

##### What is the expected behavior?

(I assume) The mitmproxy docs sidebar image should fully display in the sidebar as shown below

![google_chrome](https://cloud.githubusercontent.com/assets/2224787/14407672/62259c1e-fea0-11e5-8ad1-a66008d8dcb5.png)

##### What went wrong?

Instead, this is shown (and cannot be scrolled)

![firefox](https://cloud.githubusercontent.com/assets/2224787/14407674/750f0e82-fea0-11e5-8d40-28fe9aa03e3d.png)

**Comment by mhils** [comment]
Thanks for the report. We pretty much use the readthedocs theme as is - if you could file this bug upstream, that'd be super great! :smiley:

**Comment by mhils** [comment]
We fixed this by providing a logo that matches the expected size (7208a7543f4ad04cfbf304a66ea857540dbb0989). Still, I think this is a bug in readthedocs.
