### ISSUE TITLE
How to make mitmproxy work with non-standard SSL ports?

### ISSUE THREAD

**Issue by daboss1337** [mitmproxy/mitmproxy#1078]
Is there any way to make mitmproxy work with non-standard ports like SSL on port 31337 for example? I tried to tweak the mitmproxy.conf but the documentation does not contain enough information.

**Comment by mhils** [comment]
If you use the latest mitmproxy release, that should just work out of the box.

**Comment by daboss1337** [comment]
That is awesome. I will test that out, thanks for the information!
