### ISSUE TITLE
no option to stop flow processing once flow inspection is done

### ISSUE THREAD

**Issue by hackers-terabit** [mitmproxy/mitmproxy#1081]
##### Steps to reproduce the problem:

1. inline script with mitmproxy transparent proxy mode
2. inspect/mitm a very large file
3. wait until OOM killer kills mitmproxy (or mitmdump)

##### What is the expected behavior?

#1029 and #1036  exist for similar complaints. 

Those issues address the problem of how flows are stored and processed.

My inline  script only deals with the request and response headers (once each direction)
I expect the inline script interface to have an option where flow caching/memory storage will cease once the necessary operation(s) on the flow is performed. 

##### What went wrong?

This is more of a feature request (or documentation request if the feature already exists)

##### Any other comments?

Is there a better way to contact the developers or is github issue creation the preferred way?
---

Mitmproxy Version:
Operating System:

**Comment by mhils** [comment]
I'm not sure what you really want to accomplish or what your issue is. Are you perhaps looking for `--stream`?
If streaming is not enabled, mitmproxy will always wait until it has received the full flow before sending anything to the client.

**Comment by hackers-terabit** [comment]
mhils - I will retest with --stream and update, please keep this open if at all possible until then.

I didn't know you had slack presence, thank you for updating.
