### ISSUE TITLE
mitmdump filter does not apply to saved dumps

### ISSUE THREAD

**Issue by Pastafarianist** [mitmproxy/mitmproxy#1089]
##### Steps to reproduce the problem:

1. Install `mitmproxy` on Debian Jessie from `git` following the steps from [here](http://docs.mitmproxy.org/en/stable/install.html) and [here](https://github.com/mitmproxy/mitmproxy/blob/master/README.rst#hacking)
2. Run `mitmproxy -w somefile` and connect a device to it as usual
3. Press `oI` and add `.*` to the list of ignore patterns
4. Hit `qq` and see connections from your device still appearing in the interface.

##### What is the expected behavior?

`mitmproxy` interface should behave as if there were no connections going through it, e.g. the interface should not display them and they should not be stored in the dump file.

##### What went wrong?

`mitmproxy` ignored `--ignore` patterns.

##### Any other comments?

$ mitmproxy --version
mitmproxy 0.18

I have built `mitmproxy` with the latest commit being [this one](https://github.com/mitmproxy/mitmproxy/commit/423c076c61140c2e953313793263a4cac71e33ca).

---

Mitmproxy Version: https://github.com/mitmproxy/mitmproxy/commit/423c076c61140c2e953313793263a4cac71e33ca
Operating System: Debian Jessie ARM

**Comment by mhils** [comment]
Are you aware of the limitations mentioned in http://docs.mitmproxy.org/en/latest/features/passthrough.html#how-it-works ?

**Comment by Pastafarianist** [comment]
I was, but I have forgotten. Thank you for reminding me.
Is there any way to ignore HTTP traffic as well? I would like to record only the interaction with a single domain using `mitmdump`.

**Comment by mhils** [comment]
You probably want to use the limit feature to not show it in the UI.

**Comment by Pastafarianist** [comment]
I'm recording flows with `mitmdump -w somefile`. I guess that is not covered by the limit feature?

**Comment by mhils** [comment]
For mitmproxy, you can filter the view using the limit feature (refs #542). For mitmdump, you can specify a filter to record only selected flows: http://docs.mitmproxy.org/en/latest/mitmdump.html#filtering-saved-traffic

**Comment by Pastafarianist** [comment]
Thank you.

For posterity, this is how I solved my problem:

    mitmdump -w mitm_$(date +%Y-%m-%d_%H-%M-%S) --ignore '^(?!domain_regex)' '~d domain_regex'

Both options are required. The first one is responsible for not intercepting unrelated connections (so that, for example, Play Store do not cease to work), and the second one forces `mitmdump` to write only the flows to this domain into the log.

**Comment by Pastafarianist** [comment]
@mhils I've just checked the generated dump file. Everything that was supposed to be omitted from it is still there, the filter seems to apply only to the log which is printed in the terminal.

Is the order of the command line arguments to `mitmdump` relevant? Or perhaps the filter does not apply to flows that are intercepted in real-time, only to the ones which are read from a dump file?

**Comment by mhils** [comment]
@Pastafarianist: This looks like a bug currently - thanks for reporting back.

**Comment by mhils** [comment]
Thanks again. This is fixed on master now.
