### ISSUE TITLE
http2https and https2http broken by cli parser probably

### ISSUE THREAD

**Issue by mogorman** [mitmproxy/mitmproxy#1092]
##### Steps to reproduce the problem:
[:~ mogorman$ mitmproxy -R http2https://mysite.com/
usage: mitmproxy [options]
mitmproxy: error: argument -R/--reverse: Invalid server specification: http2https://mysite.com/

##### What is the expected behavior?
To work as described in the help

##### What went wrong?
command is not parsed 

##### Any other comments?

---

Mitmproxy Version:mitmproxy 0.17
Operating System:macos x

**Comment by mhils** [comment]
Which help are you referring to? We made mitmproxy auto-detect incoming TLS, so the `http[s]2` part is obsolete. :smiley:

**Comment by mogorman** [comment]
hmm? my intended behavior was to access an https site internal on my pc externally over http.  how would i make that happen?

**Comment by mogorman** [comment]
the docs i was referring to was the --help documentation in the command

**Comment by mhils** [comment]
Thanks for the clarification. You can just skip the `http[s]2` part, see 9f92855. :-)

**Comment by mogorman** [comment]
i want the users to connect via http to the https server?  when i connect to the mitmproxy i immediately see the certificate error.

**Comment by mhils** [comment]
If you specify `mitmproxy -R https://mysite.com/`, you can open the page unencrypted at `http://localhost:8080/`. 

You could also open the page at `https://localhost:8080/`, in which case mitmproxy will automatically detect the TLS handshake from the client and establish a secure connection (with its certificates).

**Comment by mogorman** [comment]
that is not the behavior i see.  I open mitmproxy
mitmproxy -R https://mysite.com/
i then navigate to http://localhost:8080/
and then see an https cert error in browser and here is what i see in curl

```
curl -v -v  localhost:8080/boutique
*   Trying ::1...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /boutique HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 MOVED PERMANENTLY
< Server: nginx
< Date: Fri, 22 Apr 2016 12:35:16 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: user_agent_set=desktop; domain=; path=/; secure
< Set-Cookie: browsable_segments=WzM3NjNd; domain=; path=/; secure
< Set-Cookie: default_segments=WzUsMl0=; domain=; path=/; secure
< Location: https://localhost:8080/boutique/
< X-Request-Start: t=1461328516.809
< Lane: WRITE
< Nginx-Cache-Key: /@route/boutique
< X-Request-Start: t=1461328516.809
<
* Connection #0 to host localhost left intact
```

**Comment by mogorman** [comment]
finally got it worrking using the sslstrip example and reverse proxy setting
