### ISSUE TITLE
deleting cookies (stickycookies) does not work

### ISSUE THREAD

**Issue by StevenVanAcker** [mitmproxy/mitmproxy#1096]
##### Steps to reproduce the problem:

1. start mitmdump with stickycookies: mitmdump -t "." and point a browser through it
2. visit https://httpbin.org/cookies/set?aaa=1 to set a cookie
3. visit https://httpbin.org/cookies/delete?aaa= to delete the cookie
4. visit https://httpbin.org/cookies to display the cookies

##### What is the expected behavior?

The expected behavior, according to RFC 6265, is that the cookie is deleted

##### What went wrong?

The cookie is not deleted

##### Any other comments?

The cookie library used by mitmproxy is Cookie.py from python, which is woefully outdated.
It implements RFC 2109 from 1997 and does not (yet?) support RFC 6265 from 2011.

RFC 6265 standardises both "expires" and "max-age" attributes which can be used
for expiration control of cookies. A cookie can be deleted by setting "expires" to a date in the past,
or "max-age" to 0.

A more up-to-date cookie library is probably beneficial here. I'm not sure if there are any
special reasons for depending on Cookie.py?
Is it better to attempt to fix cookie.py, or switch mitmproxy to another cookie library?

---

Mitmproxy Version: latest
Operating System:

**Comment by dufferzafar** [comment]
Correct me if I'm wrong, but the entire point of `stickycookies` is that they don't get deleted, right?

**Comment by StevenVanAcker** [comment]
Ar far as I interpreted stickycookies, they are persistent for the lifetime of the mitmproxy session, but should still follow cookie semantics. If the server requests that a cookie be removed (for instance if the user logs out explicitely), shouldn't mitmproxy then remove them?

**Comment by mhils** [comment]
> If the server requests that a cookie be removed (for instance if the user logs out explicitely), shouldn't mitmproxy then remove them?

This is a good question. I think you are right and we should probably delete cookies if the server instructs us to do so.

> A more up-to-date cookie library is probably beneficial here. I'm not sure if there are any
special reasons for depending on Cookie.py?
Is it better to attempt to fix cookie.py, or switch mitmproxy to another cookie library?

@cortesi: you have cursed a few times about the cookie stuff IIRC. Can we get your expert opinion here? :smiley:

**Comment by cortesi** [comment]
I agree that the cookies should be deleted when we're instructed to do so by the server. Python's built-in Cookie library is fractally terrible, and fails to parse many common cookies seen in the wild. I'd love to get rid of it entirely (which is why we have our own implementation). I'd be in favor of getting rid of it entirely.

**Comment by mhils** [comment]
@Kriechi worked on some parts of this during the Honeynet workshop. I think we now only depend on `http_cookiejar.domain_match` from the stdlib? (which I think is fine)

(Does not touch this issue though)
