### ISSUE TITLE
flow.kill() master arg is required but not exposed "publicly"

### ISSUE THREAD

**Issue by greenbender** [mitmproxy/mitmproxy#110]
If I have a python proxy script and want to 'drop' requests for some 'bad host' it would be nice to be able to kill the flow at the request stage. I assume this is the purpose of the flow.kill() function. The flow.kill() function has a required argument called master. As far as I can tell the only place you can find 'master' in your script is context._master however using this feels a bit dirty since _master is 'private'.

```python
def request(context, flow):
    if flow.request.host.endswith("badhost.com"):
        flow.kill(context._master)
```

Can _master be exposed as public or there is there a way to have master default to a sensible value?

**Comment by mhils** [comment]
Thanks for the report!
You can now call `context.kill_flow(f)`.

Cheers,
Max

**Comment by Cojad** [comment]
since context is no longer part of call of request, the newer version you do like such
```python
from mitmproxy import ctx

def request(flow):
    if flow.request.host.endswith("badhost.com"):
        flow.kill(ctx.master)
```

Personally, I think we should put this into example inline script.
