### ISSUE TITLE
What network interface to use to monitor traffic from local desktop app to local server?

### ISSUE THREAD

**Issue by snoblenet** [mitmproxy/mitmproxy#1104]
I want to intercept the traffic between a desktop Electron app that I am running locally on my Mac while I program it and a copy of my server-side Rails app that I am running locally on my Mac at http://localhost:3000.

I presume the settings I need are:

- Transparent mode
- No certificate required for non-HTTPS
- A `pf.conf` that looks something like `rdr on en2 inet proto tcp to any port 3000 -> 127.0.0.1 port 8080`

However, I don't know what network interface to use instead of `en2` in the above.

What do I use?

At bash, I get:

````
$ networksetup -listallhardwareports

Hardware Port: Display Ethernet
Device: en2
Ethernet Address: 40:6c:8f:55:28:9c

Hardware Port: Display FireWire
Device: fw0
Ethernet Address: 00:0a:27:02:00:4a:f6:31

Hardware Port: Wi-Fi
Device: en0
Ethernet Address: 00:88:65:3b:fa:ca

Hardware Port: Bluetooth PAN
Device: en4
Ethernet Address: 00:88:65:3b:fa:cb

Hardware Port: Thunderbolt 1
Device: en1
Ethernet Address: 32:00:14:05:ba:60

Hardware Port: Thunderbolt Bridge
Device: bridge0
Ethernet Address: 42:6c:8f:55:1e:00

VLAN Configurations
===================
````

**Comment by mhils** [comment]
To be honest, I think you are best off if you can configure your electron app to use an HTTP proxy - this makes things much easier.

If you want to run the whole thing in transparent mode, your main problem will be that you will enter an infinite with the redirect rule posted above. The workaround on Linux is to run mitmproxy as a different user and have per-user iptables rules (see #630). For the interface, I would have guessed `lo0`/loopback, but that does not appear in your list :confused:. The first step should be to get `clientconnect` events in the mitmproxy event log (see *Troubleshooting Transparent Mode* in the [docs](http://docs.mitmproxy.org/en/latest/modes.html#a-custom-gateway)).
Sorry that I can't help any further. Feel free to hop on our Slack channel if you need further help, we have a few OSX users hanging out there.
