### ISSUE TITLE
mitm.it "Visit the Documentation" link 404

### ISSUE THREAD

**Issue by javabrett** [mitmproxy/mitmproxy#1106]
##### Steps to reproduce the problem:

1. Visit http://mitm.it/ direct.
2. Click "Visit the Documentation" link.
3. Arrive at https://mitmproxy.org/doc/index.html which is a 404

I don't know whether the source for `mitm.it` is available.

##### What is the expected behavior?

Link to http://docs.mitmproxy.org

##### What went wrong?

Probably docs moved.

##### Any other comments?

Great product.

---

Mitmproxy Version: N/A
Operating System: N/A

**Comment by mhils** [comment]
Fixed, thanks for the report!

@cortesi: mitm.it is not served from GitHub, is it? Can you update the server please?

**Comment by cortesi** [comment]
I've just moved the mitm.it domain into AWS and backed it onto GitHub. This should be fixed once domains propagate.
