### ISSUE TITLE
No way to prevent hostname-from-client from being auto-added to X.509 SANs

### ISSUE THREAD

**Issue by javabrett** [mitmproxy/mitmproxy#1108]
As at current master (d84fc64), `mitmproxy` will in certain situations generate X.509 certificates for remote sites which are accepted without error by a web-browser, whereas a direct-connection to the same site would trigger TLS errors such as `SSL_ERROR_BAD_CERT_DOMAIN`, `NET::ERR_CERT_COMMON_NAME_INVALID`.  This certificate "enrichment", whilst nicely removing a browser-error seen by a direct-connection, makes `mitmproxy` less transparent, and may prevent or interfere with certain types of testing.  Currently this behaviour cannot be configured; the behaviour should be absent or at least configurable, and preferably non-default.

The error-nilling occurs when accessing a domain via a name which is not the `Subject` `CN`, and also does not match a `subjectAltName` (SAN).  `mitmproxy` currently adds the client-request hostname to the SANs, even when upstream certificate-sniffing is enabled (default), so `mitmproxy` can see that the client's requested hostname does not match, but it is added to the certificate regardless.  This occurs [here](https://github.com/javabrett/mitmproxy/blob/master/mitmproxy/protocol/tls.py#L569).

A good test-case is https://mitm.it/ , which is not-intended to be accessed over HTTPs, and when it is (directly), it serves the main `mitmproxy.org` website, but not before throwing a browser-error, because it is using `mitmproxy.org`'s certificate, which has no SAN for `mitm.it`.  If you `mitmproxy` this connection, the resulting generated certificate will have `mitm.it` as a SAN, and your browser-connection will be error-less.  Normally perhaps a nice thing in removing the error, but I didn't ask `mitmproxy` to do that, and it is sniffing upstream certs by-default, so I expect the cert to be more-or-less identical, other than the `Issuer` of course.

##### Steps to reproduce the problem:

1. Access https://mitm.it/ directly from your browser (no `mitmproxy`), observe CN mismatch warning and not mitm.it in CN or SAN.
2. Access https://mitm.it/ via `mitmproxy` and observe that `mitm.it` appears in the certificate SAN.

##### What is the expected behavior?

* When upstream cert sniffing is enabled, just pass-through the `Subject` `CN` and the `subjectAltName` unmodified by-default.  Consider some _non-default_ runtime options to:
  * Copy the `Subject` `CN` to a `subjectAltName` in the unusual case that there is a `subjectAltName`, but it does not contain the host data in `Subject` `CN`.  Note that this could change the acceptance of the cert in a client strictly adhering to RFC 2818 (Thunderbird 38?).  But can we find such an example certificate on the internet somewhere?
  * Add the client-request hostname to the SANs (creating if necessary, in which case the `CN` also needs to be copied-in), to allow the current error-nullifying behaviour to be restored if desired.
  * Always create `subjectAltName` if absent from (deprecated) `Subject` `CN`.  Probably unnecessary since clients always understand `Subject` `CN`.
* When upstream cert sniffing is disabled with `--no-upstream-cert`, create both `Subject` `CN` (deprecated) and `subjectAltName` using that name.  Although this could result in a different certificate now having `subjectAltName`, there should be no difference to a client.  Hostname error-nullifying is enabled.

##### What went wrong?

Generated cert allows more names than the upstream server cert.

##### Any other comments?

An earlier change made in 375dbe070383caa79d9593a6d7a6b33eb0eb7a4a is correct, and stopped removing a hostname from the SANs, said removal/de-duplication being incorrect.  The relevant RFC 2818 https://tools.ietf.org/html/rfc2818 states:

> 3.1 Server Identity
...
If a subjectAltName extension of type dNSName is present, that MUST be used as the identity. Otherwise, the (most specific) Common Name field in the Subject field of the certificate MUST be used. Although the use of the Common Name is existing practice, it is deprecated and Certification Authorities are encouraged to use the dNSName instead.

That is, if there is a `subjectAltName`, for clients it ought to be read and be assumed authoritative and complete, and not unioned with a later-read `Subject` `CN`.  According to that, Thunderbird 38 as mentioned in the comment would be behaving correctly in ignoring the `Subject`.  Certificates that do not include the `Subject` hostname as a `dnsName` in `subjectAltName` are running-foul of the RFCs.

---

Mitmproxy Version: master (d84fc64)
Operating System: LinuxMint 17.1 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mhils** [comment]
Thanks for the detailed write-up and the RFC pointer - really appreciated.
Nonetheless, I think the current default behaviour resembles what most users appreciate most. Why specifically do you want mitmproxy to be more "transparent" here?
If you are concerned with untrusted upstream certificates, you should enable `--verify-upstream-certs` and mitmproxy will reply with a 502 Gateway Error. Other than that, I don't see any good reasons to let connections fail.

**Comment by cortesi** [comment]
I don't mind which approach we take, as long as we're a) consistent, and b) allow mismatches of this sort to be detected after the fact using serialised data. It may also be worth logging a warning. See my comments on #1109.

**Comment by javabrett** [comment]
@mhils Right, I did wonder for a while whether this was more of a feature (perhaps requiring a documentation-note) rather than a bug, and might become convinced that is the case.  For me it boils-down to what environments and uses you might be willing to deploy `mitmproxy` into for longer-term use, or how comfortable you are to leave it running in certain environments.  As you point-out, `--verify-upstream-certs` is available.

I am new to the code-base, so I was trying to work-out the logic in [tls.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/protocol/tls.py), and equate that with the docs.  In [Upstream Certificates](http://docs.mitmproxy.org/en/latest/features/upstreamcerts.html) it says:

> ... and makes a connection to the upstream server to “sniff” the contents of its SSL certificate. The information gained - the Common Name and Subject Alternative Names - is then used to generate the interception certificate, which is sent to the client so the connection can continue.

The code in tls.py seems to be attempting a mixture of things - it is copying down the key CN and SANs from the upstream certificate to the generated one, like it is trying to make a best-copy of it, but then it performs the auto-fix enhancements mentioned in this issue.  If all we cared about was a working/valid certificate, you could not even bother with the full copying, and just generate a minimally-matching certificate.  Per #1109, if SNI is present that's another case where looking at the upstream certificate is not actually required.  So it boils-down to whether `mitmproxy` is trying to do a best-possible job on generating a best-equivalent certificate, or the fastest possible job detecting and generating a usable/minimal certificate.

My preference is that it could do both, even to the point of being able to copy dates etc. from the upstream certificate, to the point where only the CA signer is different.  This would allow a) exact testing of any client scenario that doesn't rely on a specific upstream CA or certificate-pinning and b) less intrusive long-term use e.g. as a logging-proxy etc., without being concerned that the MITM is obscuring details from you that you might care about, such as expired certificate.  `--verify-upstream-certs` is great, but it doesn't mimic the normal end-user experience - it could be argued it is better or worse ... certainly takes the decision away from an end-user agent :).  I suppose I am also concerned that an upstream attacker/MITM might be able to create a site with any valid certificate, and without the non-default `--verify-upstream-certs` enabled, that site is auto-trusted for any hostname the client requests.

A perhaps-contrived example: I want to debug a client that is suspected of doing something unusual when it encounters an untrusted certificate due to non-matching name.  I can't currently perform that test with `mitmproxy`, because it is auto-fixing the client-requested hostname in the SANs.

It might be that in-future a switch is made-available to support more-exact copying of the upstream certificate (within the bounds of what is technically possible), and for now just the minimal generated-certificate gets created.  Auto-trusting any hostname the client requests still makes me nervous though.

**Comment by mhils** [comment]
Thanks for clarifying. Let's sort stuff by use case:

##### *I want to test my client's TLS implementation*
If you want to test your client, why obscure the connection with an active man-in-the-middle proxy? I would strongly recommend to just test things locally. As a last resort, you could use `--cert`.

##### *I am concerned about untrusted upstream servers...*
In this case, just enable `--verify-upstream-certs`. I would welcome a patch that enables this by default and adds a better error message.
Copying any additional (attacker-spoofable) attributes (e.g. expiry dates) does not improve actual security IMO.

##### *...but I still want to user agent to decide.*
This is precisely what Superfish did, but unfortunately they had a bug in their implementation. Getting this right is incredibly tricky, and I really doubt it would be worth it. I'd rather be black/white here and either provide full certificate checking or no certificate checking.

**Comment by javabrett** [comment]
> If you want to test your client, why obscure the connection with an active man-in-the-middle proxy?

In the past I have been faced with difficult issues with certain problematic or buggy SSL/TLS clients.  For example, an SVN client lib that wasn't sending SNI properly, or an SVN server whose TLS lib wasn't processing SNI properly.  At the time I used Wireshark to complete the diagnosis (and perhaps would again), which was fine, but of course you can only see TLS handshakes and not packet-data.  It would be nice to have `mitmproxy` as another tool in the bag to help diagnose - I can't say with certainty that it would be faster than Wireshark, but it certainly has excellent capture and logging capabilities, plus I can see the tunnelled data from client and server, so I know where we are up to in the conversation.

If additional SANs are added regardless of the upstream SANs, this test would not be possible.  Again, I cannot prove that this would prove a more direct diagnosis than just using Wireshark, because I did not use it at the time.

>  I would welcome a patch that enables this by default and adds a better error message.

Thanks. I guess the end-user acceptance on this depends on how many folks are actively depending on the tool to fix-on-the-fly certificates with mismatched/missing names. If `mitmproxy` has broad use-cases, I'd feel more comfortable with this option as default.

> I'd rather be black/white here and either provide full certificate checking or no certificate checking.

I agree - if we care about the upstream certificate (other than for the purposes of the name-discovery dance) we should validate it completely or not at all, and also replicate it completely, re-signed with our CA.

**Comment by mhils** [comment]
Ok, I guess we are coming to a conclusion:

- If you want mitmproxy to generate certificates that closely mirror the server's certificate, you can do that in an inline script by overriding `_find_cert` (see [examples/tls_passthrough.py](https://github.com/mitmproxy/mitmproxy/blob/master/examples/tls_passthrough.py)).
- For the majority of mitmproxy's users, I think there is no point in replicating certificates as closely as possible and the current approach matches their needs best.
- We probably want to turn on upstream certificate verification by default. Unfortunately, it is quite common that people use mitmproxy with TLS servers that have self-signed or invalid certificates. I created #1111 to tackle this problem.
