### ISSUE TITLE
do you run the examples with mitmdump or mitmproxy

### ISSUE THREAD

**Issue by medyagh** [mitmproxy/mitmproxy#1110]
I see some new examples in the new version, are these examples meant to run with mitmdump or mitmproxy for example is flowwriter.py only for mitmdump ? and is upsidedownternet.py only for mitmproxy ?

**Comment by mhils** [comment]
How do you come to the conclusion that `flowwriter` could be for mitmdump only and `upsidedownternet` could be for mitmproxy only?

**Comment by medyagh** [comment]
because how could mitmdump which only dumps stuff to a file, can take advantage of making pictures upside down ?  and flowwriter is just for dumping stuff in a file...thats more of a mitmdump ?

I think the line between mimtproxy and mitmdump is a thin line and not clear if they can be used instead of each other....

**Comment by mhils** [comment]
`upsidedownternet` is an inline script that changes what is displayed to the client. You can use it with both mitmdump or mitmproxy. 
`flowwriter` illustrates how you can use the FlowWriter to create custom log files, e.g. per client IP. both mitmdump and mitmproxy have a `-w` switch which covers the basic scenario (just dump everything in a single log).
