### ISSUE TITLE
Verify upstream certificates by default.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1111]
Per discussion in #1108 and some other places, I would like to turn on `--verify-upstream-cert` by default, with an easy option to disable it.

Basic Features:
- [ ] Add setting to the mitmproxy options menu.
- [ ] Add `--insecure` command line switch to disable certificate verification. Do we also want to have `-k` for this, to mirror curl's API?

Bonus features:
- [ ] `~/.mitmproxy/trusted.pem` should contain additional certs that are trusted by default.
- [ ] When sending an error to the client, send a detailed error page giving the client the option to add the cert to `~/.mitmproxy/trusted.pem`.
- [ ] Display rejects connections as flows in the UI with an easy option to add certs to `~/.mitmproxy/trusted.pem`. (this requires substantial work at other places)

Caveats:
- In a [user] -- TLS -- [mitmproxy] -- TCP -- [server] configuration, we cannot signal to the client that there's essentially no security. As I see it, this should only affect reverse proxy mode, manually changed requests and mitm.it. As such a configuration is a deliberate choice, we should be good.

If anyone wants to work on this, the first task would be to add this setting to mitmproxy's Options screen and send a separate PR for this! :smiley:

**Comment by s4chin** [comment]
I would like to take this. For the basic features, I think it would go like this:
Remove the `--verify-upstream-cert` and add the `--insecure` option. In the `config.py`, remove the `ssl_verify_upstream_cert` variable and add an `ssl_insecure` variable instead and make changes accordingly.
That way the `ssl_insecure` default value is `False` and we set an `--insecure` option to set it to `True`. Is this the correct approach or you prefer I keep the `ssl_verify_upstream_cert` variable and make changes accordingly?

**Comment by mhils** [comment]
@s4chin: This sounds like an excellent first step. Please go ahead! :smiley:
