### ISSUE TITLE
why ignoring in transparent mode has to be in ip as opposed dns ?

### ISSUE THREAD

**Issue by medyagh** [mitmproxy/mitmproxy#1116]
I have huge problems not being able to ignore domains or ips in transparent mode.
I have tried adding multiple --ignore 1\.2\.3\.4:443--ignore domain\.com and I still see in the logs 
stuff like "client may not trust the proxy's certificate for graph.facebook.com."
I feel like the ignore acts totally differently in transparent mode and not acting as I expect it, is that true ? can I pass multiple --ignore in transparent mode?

how can I effectively and for real ignore multiple domain names in transparent mode?

**Comment by dwfreed** [comment]
In transparent mode, for TLS connections, mitmproxy wouldn't know the domain name until far too late for --ignore to be effective.  Therefore, in transparent mode, --ignore only applies to the IP address of the desired connection and the TLS SNI hostname.  I haven't tried with 0.17, but in 0.16, --ignore graph.facebook.com works just fine.  And yes, you would specify multiple --ignore options to add more items to the list.

**Comment by medyagh** [comment]
the detail I forgot to mention is I use --host and I just read in the docs, 
``` if the --host argument is passed to mitmproxy, we do not have access to this information before the SSL handshake. If the client uses SNI however, then we treat the SNI host as an ignore target.```

what happens if I dont add --host ?  what good --host does for me?

**Comment by medyagh** [comment]
I have tried to ignore all the possible IPS with and without --host ....wont work.I tried in previous versions also.   by the way in the docs I see a conflict
http://docs.mitmproxy.org/en/latest/features/passthrough.html

it says to ignore a single domain, do this:
```
>>> mitmproxy --ignore ^example\.com:443$
```
but doesnt ^ mean NOT in regex.... so it means do NOT ignore example.com ?

I think the ignore document needs a re-write and checking that if it actually works.

**Comment by chrisgavinme** [comment]
@medyagh No, `^` only means not when used at the start of a character class. At the start of the expression it means "start of string". Likewise, `$` means end of string.

**Comment by chrisgavinme** [comment]
Could you clarify what your setup is? I tried `mitmdump -T --ignore graph.facebook.com` (with the client and mitmproxy on the same machine) and it is working okay for me. Is your proxy running on a different machine. Are you using the default gateway method of interception or iptables?

**Comment by mhils** [comment]
Thanks @dwfreed and @chrisgavinme for chipping in.

@medyagh: You already openend an issue for this two months ago, which I closed for inactivity a month ago (#1046). It would be highly appreciated if you could do more research on your own before posting to the issue tracker.

**Comment by medyagh** [comment]
Thanks for the response
@chrisgavinme my mitmproxy is in a different machine, and I connect to it through OpenVPN and then I have the traffic from 80 and 443 from Tun0 forwarded to Eth0 by iptables forwarding rules.

@mhils sorry about duplicate issue, since that issue was form a very earlier version I thought I open a new one for newer version and a new set up which has the same problem.
