### ISSUE TITLE
ServerException instead of ProxyServerError

### ISSUE THREAD

**Issue by lbello** [mitmproxy/mitmproxy#1122]
##### Steps to reproduce the problem:

    >>> from libmproxy.proxy.server import ProxyServer
    >>> from libmproxy.proxy.config import ProxyConfig
    >>> ProxyServer(ProxyConfig(port=80))
    (...)
    ServerException: Error starting proxy server: error(13, 'Permission denied')

##### What is the expected behavior?

According to the documentation:

    >>> ProxyServer?                       
    Type:            type
    String form:     <class 'libmproxy.proxy.server.ProxyServer'>
    File:            /usr/lib/python2.7/dist-packages/libmproxy/proxy/server.py
    Init definition: ProxyServer(self, config)
    Docstring:       <no docstring>
    Init docstring:  Raises ProxyServerError if there's a startup problem.

the expected behavior is 

    >>> ProxyServer(ProxyConfig(port=80))
    (...)
    ProxyServerError: Error starting proxy server: error(13, 'Permission denied')

##### What went wrong?

Maybe the documentation is wrong?

##### Any other comments?

Nope.

---

Mitmproxy Version: 0.15-2
Operating System: Debian Sid.

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by lbello** [comment]
I think the docstring is still there:
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/server.py#L39

**Comment by mhils** [comment]
Thanks. Could you please send a quick PR that updates the docstring?
