### ISSUE TITLE
Regression: can no longer modify flow.response.code

### ISSUE THREAD

**Issue by cellularmitosis** [mitmproxy/mitmproxy#1128]
mitmproxy appears to have lost its ability to modify the HTTP code of a response.  I've confirmed this works correctly on 0.10.1 (Debian/jessie) and is broken on 0.17.

##### Steps to reproduce the problem:

1. Create a script like so:

cat > 500.py
def response(context, flow):
    flow.response.code = 500

2. Run mitmproxy -s 500.py
3. Notice that the response code of your requests isn't being modified.

##### What is the expected behavior?

Every request should 500.

##### What went wrong?

mitmproxy did not modify the HTTP code.

##### Any other comments?

---

Mitmproxy Version: 0.17 and 0.16
Operating System: OS X

**Comment by mhils** [comment]
In the latest version of mitmproxy, the attribute has been renamed to `status_code`: http://docs.mitmproxy.org/en/latest/dev/models.html#netlib.http.Response

We renamed this to mirror the Python `requests` API. Apparently you just missed the versions where we spit out a deprecation warning here, sorry about that.

**Comment by cellularmitosis** [comment]
Sorry I missed this.  Thanks for the pointer to the docs!
