### ISSUE TITLE
Some devices not working properly with mitmproxy

### ISSUE THREAD

**Issue by mortenmoulder** [mitmproxy/mitmproxy#1131]
##### Steps to reproduce the problem:

1. Start mitmproxy with --htpasswd so users can authenticate
2. Enter the proxy and authentication details on the phone
3. Browse around and get HTTP requests logged in the GUI

##### What is the expected behavior?
Expected behavior is every phone should get the requests logged. And when I say logged, I simply mean showing the status code, showing the URL, showing all that good stuff basically. What mitmproxy GUI is made for.

##### What went wrong?
Some devices connect fine, but the data is not being logged in certain applications. Browsers seem to work fine, but other applications does not work on all phones (even though they're the exact same version across all devices).

##### Any other comments?
1. I have a suspicion, that the proxy settings (when applied to the WiFi network), does not have "permission" to change the proxy settings for the whole device. Maybe some applications are whitelisted (like Safari, Google Chrome, etc.).
2. This was tested on various iPhones and Android devices running different ROMs and manufacturers.
3. Check my StackOverflow question for a more in-depth version: http://stackoverflow.com/questions/37154922/mitmproxy-htpasswd-doesnt-work-for-most-people

---

Mitmproxy Version: 0.18
Operating System: Debian 8.4 or Debian 8.3 (tried both)

**Comment by mhils** [comment]
http://docs.mitmproxy.org/en/latest/modes.html#regular-proxy

> Unfortunately, some applications bypass the system HTTP proxy settings - Android applications are a common example. In these cases, you need to use mitmproxy’s transparent mode.

**Comment by mortenmoulder** [comment]
@mhils Transparent mode does not work with any of the 3 authentication modes. --nonanonymous, --singleuser, or --htpasswd.
