### ISSUE TITLE
Build from Dockerfile

### ISSUE THREAD

**Issue by Cphilo** [mitmproxy/mitmproxy#1142]
##### Steps to reproduce the problem:

1. build image from Dockerfile
2. run `mitmproxy/base:latest-onbuild` image
3. docker attach to the docker container

##### What is the expected behavior?
can ssh to the running container.

##### What went wrong?
with `docker ps -a`, the running container exited and can not connect it.

##### Any other comments?

---

Mitmproxy Version:  lastest master branch
Operating System: mac_osx 10.11.1

**Comment by mhils** [comment]
This sounds like you want to take one of the images from https://hub.docker.com/r/mitmproxy/releases/

**Comment by Cphilo** [comment]
yes
