### ISSUE TITLE
Set-cookie headers are getting folded on HTTP2

### ISSUE THREAD

**Issue by KostyaEsmukov** [mitmproxy/mitmproxy#1143]
##### Steps to reproduce the problem:

	>>> from netlib.http.headers import Headers
	>>> h = Headers([['set-cookie', 'fdf'], ['set-cookie', 'htyy']])
	>>> h.items()
	[('set-cookie', 'fdf, htyy')]

##### What is the expected behavior?

	>>> from netlib.http.headers import Headers
	>>> h = Headers([['set-cookie', 'fdf'], ['set-cookie', 'htyy']])
	>>> h.items()
	[('set-cookie', 'fdf'),('set-cookie', 'htyy')]

##### What went wrong?

Take a look here: https://github.com/python-hyper/hyper-h2/blob/b2cbb2f1862ee3cab58f88aee92c0414ec67f4e5/h2/stream.py#L734

.items() method is called on headers, thus set-cookie headers are getting folded on HTTP2.

---

Mitmproxy Version: mitmproxy==0.17

**Comment by mhils** [comment]
Thanks for the great report - we certainly need to pass `headers.fields`.

**Comment by KostyaEsmukov** [comment]
Thank you for your quick response!
This simple patch fixes the problem for me:

	--- protocol/http2.py.orig	2016-05-14 14:32:58.000000000 +0300
	+++ protocol/http2.py	2016-05-14 14:34:42.000000000 +0300
	@@ -61,7 +61,7 @@
	         with self.lock:
	             if is_zombie():
	                 return
	-            self.send_headers(stream_id, headers)
	+            self.send_headers(stream_id, headers.fields)
	             self.conn.send(self.data_to_send())

	     def safe_send_body(self, is_zombie, stream_id, chunks):

Cheers,
Kostya

**Comment by mhils** [comment]
Awesome. Could you submit a quick PR for this?

**Comment by KostyaEsmukov** [comment]
Sure. Is it fine w/o a test case?

**Comment by mhils** [comment]
Yes - we'll have some changes to the HTTP2 tests soon anyway.

**Comment by Kriechi** [comment]
Thanks for catching this! I improved the tests here: https://github.com/mitmproxy/mitmproxy/commit/f4a13d6f9f804b8883e415a1e2eb6beb129e5b7f
