### ISSUE TITLE
No matter which ignore filters are set, "iosapps.itunes.apple.com" always gets through.

### ISSUE THREAD

**Issue by TheDumpap** [mitmproxy/mitmproxy#1145]
##### Steps to reproduce the problem:

1. Connect iPhone to the MITMPROXY
2. Watch the MITMPROXY while iPhone is either on homescreen or in apps
3. There is a HUGE amount of logs about "iosapps.itunes.apple.com", and no ignore filters will ignore it. All the requests are GET requests.
4. After a while with the iPhone connected (10-15s of being on the homescreen), the MITMPROXY gets "killed", and shuts down.

##### What is the expected behavior?
Following the ignore filter, or atleast not shutting down because of the large amount of traffic.

##### What went wrong?
The proxy shuts down after an iPhone connects to it, since there is a huge amount of GET requests to iosapps.itunes.apple.com

##### Any other comments?
I actually don't care about the logs, I just don't want the proxy to close at all.
It doesn't matter if I use mitmdump or mitmproxy

---

**Comment by mhils** [comment]
So, you are describing two issues here.

1. As stated on http://docs.mitmproxy.org/en/latest/features/passthrough.html, in regular mode, explicit HTTP requests are never ignored. I assume you just configured a regular HTTP proxy?
2. We need more details on this.
