### ISSUE TITLE
mitmproxy display "\t" as "?"

### ISSUE THREAD

**Issue by hexucheng** [mitmproxy/mitmproxy#1149]
##### Steps to reproduce the problem:

1. My request's ua has "\t" and mitmproxy display it as "?".
2. 
3. 

##### What is the expected behavior?
Normally "\t" display as blank, like fiddler and charles.

##### Any other comments?

---

Mitmproxy Version:0.17.1
Operating System:OS X 10.11.4

**Comment by mhils** [comment]
Where do you see this? Could you post a screenshot please?
