### ISSUE TITLE
how to save http request to a file?

### ISSUE THREAD

**Issue by leveryd** [mitmproxy/mitmproxy#1153]
I know "mitmdump -w filename",it can save traffic to "filename" file.BUT i want to save data like:

GET /    HTTP/1.1
HOST:  XX.COM

I can use other tool to handle such file.now i do some job below:
```
request=flow.request
if len(request.headers['cookie'])>0:
                                        cookie=request.headers['cookie'][0]
                                if len(request.headers['referer'])>0:
                                        referer=request.headers['referer'][0]
                                args = {'args': [request.url,cookie,referer,"mitm-test-for-get"]}
 ```
is there more avaliable solution?

**Comment by mhils** [comment]
I'm not sure what you want to accomplish? You can view Headers in mitmdump by passing `-d`, or you can use the flow export feature in mitmproxy.

**Comment by cortesi** [comment]
Hi there. This is a "how-to" question that really belongs on our new forums (https://discourse.mitmproxy.org). Please post your question there with a bit more detail on what you're trying to accomplish.
