### ISSUE TITLE
How to set transparent proxy?

### ISSUE THREAD

**Issue by mutepigz** [mitmproxy/mitmproxy#1156]
How to set  transparent proxy?

Mitmproxy Version:  0.18
Operating System:  centos

**Comment by javabrett** [comment]
Have you reviewed [Transparent Proxying](http://docs.mitmproxy.org/en/latest/transparent.html) and [Transparent Proxying -> Linux](http://docs.mitmproxy.org/en/latest/transparent/linux.html)?

**Comment by mhils** [comment]
Thanks, @javabrett! Help with these kinds of issues is always appreciated.
