### ISSUE TITLE
netlib.http.Response vs mitmproxy.models.HTTPResponse

### ISSUE THREAD

**Issue by arnau** [mitmproxy/mitmproxy#1158]
A bit of context:  I got here when migrating from 0.15 to 0.17.  I was trying to import `mitmproxy.models` from a non-inline script and then import this in my actual inline script.  I did work with 0.15's `libmproxy.models` but not with the new structure.

This unexpected situation made me find the following comment in https://github.com/mitmproxy/mitmproxy/blob/bb4f9611f53771103b9b790d7fa3baddb706cfe9/mitmproxy/models/http.py#L28:

> A mitmproxy HTTP request.
> This is a very thin wrapper on top of :py:class:`netlib.http.Request` and
> may be removed in the future.

So I tried to use `netlib.http.Request` instead which works with my import chain but the following happens which is an unexpected outcome for me.

##### Steps to reproduce the problem:

(1). Create the following inline script `a.py` and run `mitmdump --script a.py`.

```python
# a.py
from mitmproxy.models import Headers, HTTPResponse

def request(context, flow):
    flow.reply(HTTPResponse("HTTP/1.1", 204, "foo", Headers(), ""))
```

(2). Then make a proxied request (it is intended the requested service on `localhost:8000` is not available):

```sh
curl -I --proxy http://localhost:8080 -XGET http://localhost:8000
```

(3). Response:

```
HTTP/1.1 204 foo
```

(4). Create the following inline script `b.py` and run `mitmdump --script b.py`.

```python
# b.py
from netlib.http import Headers, Response
def request(context, flow):
    flow.reply(Response("HTTP/1.1", 204, "foo", Headers(), ""))
```

(5). Then make a proxied request (it is intended the requested service on `localhost:8000` is not available):

```sh
curl -I --proxy http://localhost:8080 -XGET http://localhost:8000
```

(6). Response:

```
HTTP/1.1 502 Bad Gateway
Content-Length: 262
Content-Type: text/html
Connection: close
Server: netlib 0.17
```

##### What is the expected behavior?

I expected `mitmproxy.models.HTTPResponse` and `netlib.http.Response` to behave in a similar way.  Ideally both like `mitmproxy.models.HTTPResponse` so I can mock responses to non-existing  services.

Thanks!

---

Mitmproxy Version: 0.17
Operating System: OSX 10.11.4
Python: 2.7.11

**Comment by mhils** [comment]
Well, mitmproxy expects a HTTPResponse, not a netlib.http.Response object - while HTTPResponse is just a thin wrapper around netlib.http.Response, it is still required.
```python
from mitmproxy.models import HTTPResponse
```
works just fine for me, no matter which context. You probably have installed two version of mitmproxy or something of that sort.

**Comment by arnau** [comment]
Ok, I'll try to isolate the error with `mitmproxy.models`, thanks
