### ISSUE TITLE
mitmproxy fails on Akamai HTTP2 demo

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1161]
##### Steps to reproduce the problem:

1. Visit https://http2.akamai.com/demo

##### What is the expected behavior?

All HTTP2 loaded images should load.

##### What went wrong?

Some HTTP2 images load, but most don't

---

Mitmproxy Version: -master
Operating System: OSX

**Comment by Kriechi** [comment]
Very weird...
I'm seeing these errors:
```
ProtocolException('Error in HTTP connection: TcpDisconnect("[(\'SSL routines\', \'SSL_write\', \'protocol is shutdown\')]",)',)`

ProtocolException('Error in HTTP connection: TcpDisconnect("[(\'SSL routines\', \'ssl3_write_pending\', \'bad write retry\')]",)',)
```

which probably cause these:
` << Cannot dis- or reconnect in HTTP2 connections.` and
` << HTTP2 layer should already have a connection.`

**Comment by Kriechi** [comment]
This is a confirmed issue with the Akamai HTTP/2 implementation, and will be fixed soon on their side.
