### ISSUE TITLE
How to set transparent proxy?

### ISSUE THREAD

**Issue by mutepigz** [mitmproxy/mitmproxy#1163]
##### Steps to reproduce the problem:

1. `sysctl -w net.ipv4.ip_forward=1 `
2. `iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080 `
3. `mitmproxy -T –host`
4.visit a website with shadowsocks

##### What is the expected behavior?
i can view the website

##### What went wrong?
i can't view the website,and my browser download the page

##### Any other comments? What have you tried so far?

---

Mitmproxy Version:0.81
Operating System:Ubuntu

**Comment by mhils** [comment]
Did you take a look at http://docs.mitmproxy.org/en/latest/modes.html?

**Comment by mutepigz** [comment]
Yeah,but i can't catch anything again..

**Comment by cortesi** [comment]
Hi there. This is a "how-to" question that belongs on our new forums (https://discourse.mitmproxy.org). Please feel free to post there with more information on what you're doing and the error you're seeing. I'd also recommend using a recent version of mitmproxy (we're up to 0.17.x).
