### ISSUE TITLE
shields.io gives weird pypi results

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1184]
Currently, I see this:

<img width="182" alt="screen shot 2016-06-01 at 4 38 14 pm" src="https://cloud.githubusercontent.com/assets/22544/15698302/4a93012c-2817-11e6-8cc2-517c70585503.png">

The corresponding images for per day shows 0 downloads, and per week says 12. I can't make this make sense in any way. Maybe it's being screwed up because it's the 1st of the month? Are wildly inaccurate download stats better than none? Discuss.

**Comment by mhils** [comment]
1) Wait
2) Remove temporarily?

I'm leaning towards 2.
