### ISSUE TITLE
Read flows from stdin

### ISSUE THREAD

**Issue by thiagoarrais** [mitmproxy/mitmproxy#1204]
Anyone interested on being able to read flows from stdin?

I've tried the usual convention of using a single dash for the filename, but it didn't work. I'd expect `mitmproxy -r /tmp/flows` to be equivalent to `cat /tmp/flows | mitmproxy -r -`, but the latter blows up like this:

    $ cat /tmp/flows | mitmproxy -r -
    # ...
      File "/home/thiago/devel/mitmproxy/venv/lib/python2.7/site-packages/urwid/raw_display.py", line 635, in _getch_nodelay
        return self._getch(0)
      File "/home/thiago/devel/mitmproxy/venv/lib/python2.7/site-packages/urwid/raw_display.py", line 545, in _getch
        return ord(os.read(self._term_input_file.fileno(), 1))
    TypeError: ord() expected a character, but string of length 0 found

    mitmproxy has crashed!
    Please lodge a bug report at:
            https://github.com/mitmproxy/mitmproxy
    Shutting down...

I'm willing to try a PR if there's interest in this (and no obvious restriction, of course).

**Comment by mhils** [comment]
I think this is already implemented on master. :smiley: (https://github.com/mitmproxy/mitmproxy/commit/c17ccead6db98346fa088f7ca035af24694af659)

**Comment by thiagoarrais** [comment]
I've ran this test with master... But I've got test failures. Maybe it's connected.
