### ISSUE TITLE
Headers aren't always case insensitive

### ISSUE THREAD

**Issue by redfast00** [mitmproxy/mitmproxy#1214]
Headers like `Content-Length` should preserve case after going trough mitmproxy, because some versions of PHP don't like lowercase headers (this is a server-side misimplementation of [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), but it would be nice if mitmproxy was able to handle this.).  

Steps to reproduce:
Capture some traffic, replay it with `mitmdump -nc capture_file`. Everything works as intended.
Now replay it, but use a script that replaces the request content. The `Content-Length` header get's changed to `content-lenght`.  

The problem probably lies at [netlib/http/message.py](https://github.com/mitmproxy/mitmproxy/blob/master/netlib/http/message.py#L104)
Mitmproxy Version: latest

**Comment by Kriechi** [comment]
Does this mean it is not possible to use HTTP/2 with PHP?

From RFC750, 8.1.2:
> However, header field names MUST be converted to lowercase prior to their
> encoding in HTTP/2.  A request or response containing uppercase
> header field names MUST be treated as malformed (Section 8.1.2.6).

**Comment by redfast00** [comment]
Probably not with all servers, but with this specific (HTTP/1), PHP server (I have no access to sourcecode), it only works if the header is "properly" capitalized. (I sent the exact same packets with and without capitalization, it only works with).

**Comment by redfast00** [comment]
Just confirmed: changing `content-length` to `Content-Length` on https://github.com/mitmproxy/mitmproxy/blob/master/netlib/http/message.py#L104 fixed the issue. This is however probably not a solution since there is maybe a server which only accepts lowercase header. A good solution would be to preserve case.

**Comment by mhils** [comment]
If you replace `key` in [this line]https://github.com/mitmproxy/mitmproxy/blob/ef462a05d7422ec099cafdd52810fbb77dbad604/netlib/multidict.py#L108) with `fields[0]`, does that fix your issue?
If so, It'd be awesome if you could send a PR for that! :smiley:

**Comment by redfast00** [comment]
@mhils Done! Thanks a lot for your quick resolution of the bug. :smiley:
