### ISSUE TITLE
mitmdump server playback exits prematurely

### ISSUE THREAD

**Issue by lesterfisher** [mitmproxy/mitmproxy#1229]
##### Steps to reproduce the problem:

1. Type command "mitmdump -w temp" in console and then visit a HTTP website.
2. Close capture.
3. Execute "mitmdump -S temp" to replay.

##### What is the expected behavior?
Server-side replay should be performed.

##### What went wrong?
mitmdump hangs, no anything print out and also no crash.

##### Any other comments? What have you tried so far?
mitmdump have an alert like below, but I think it is not related to server side replay.
I searched this issue but nothing found, seems no one report this issue before. I appreciate if you can give me any advice. 

lester@ubuntu:mitm$ mitmdump -S ./temp
ALPN support missing (OpenSSL 1.0.2+ required)!
HTTP/2 is disabled. Use --no-http2 to silence this warning.

---

Mitmproxy Version: mitmdump 0.17
Operating System: ubuntu 14.04 LTS 64-bit

**Comment by Kriechi** [comment]
The warning about missing ALPN support is ok. It simply means you cannot use HTTP/2 in your mitmdump session. If you are not using HTTP/2, you can ignore this.

As for the hanging - hard to tell. Maybe you could provide us a capture file where we can see this problem?

**Comment by lesterfisher** [comment]
Thanks Kriechi. The capture file attached, It quite simple, just captured the traffic when opening www.google.com 

[temp.zip](https://github.com/mitmproxy/mitmproxy/files/313222/temp.zip)

**Comment by lesterfisher** [comment]
@Kriechi

**Comment by mhils** [comment]
Thanks for the report! We need to take a look at this once #1265 is in. :smiley:

**Comment by mhils** [comment]
This doesn't hang for me, but it looks like we are exiting prematurely.

**Comment by dufferzafar** [comment]
`mitmdump -S temp` exits prematurely for me, but `mitmproxy -S temp` works just fine. Weird.
