### ISSUE TITLE
mitmproxy should check LC_CTYPE before LANG when testing console environment

### ISSUE THREAD

**Issue by jeremy-w** [mitmproxy/mitmproxy#125]
When I run mitmproxy 0.9, I see:

```
% mitmproxy --version
mitmproxy 0.9
% mitmproxy
Error: mitmproxy requires a UTF console environment.
Set your LANG enviroment variable to something like en_US.UTF-8
```

But my console environment is UTF-8 already:

```
% locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

When I check the `locale(1)` manpage, it says that `LC_ALL`, if set, overrides `LC_*`, and that `LANG` is just a fallback for unset `LC_*` values. But every possible `LC_*` value other than `LC_ALL` is set, so there is no need to set either `LC_ALL` or `LANG`.

```
% uname -v
Darwin Kernel Version 12.3.0: Sun Jan  6 22:37:10 PST 2013; root:xnu-2050.22.13~1/RELEASE_X86_64
```

**Comment by blikenoother** [comment]
I am facing the same problem:
Error: mitmproxy requires a UTF console environment.
Set your LANG enviroment variable to something like en_US.UTF-8

Tried setting environment variable (export $LANG=en_US.UTF-8) but still the same Error :(

**Comment by mhils** [comment]
`LANG`, `LC_CTYPE` and `LC_ALL` should be UTF8.

Cheers,
Max

**Comment by blikenoother** [comment]
working, thanks :)

**Comment by abit2** [comment]
@mhils where is the file I need to change the LANG LC_TYPE LC_ALL in

**Comment by jeremy-w** [comment]
@abit2: You need to change the process environment. This should work:

```
env LANG="C.UTF-8" mitmproxy
```

**Comment by j1anFen** [comment]
vim /etc/profile
export LANG=C.UTF-8
source /etc/profile

**Comment by colandrea** [comment]
> export $LANG=en_US.UTF-8)

you don't need the $ in $LANG.

**Comment by esakkiraja100116** [comment]
> `LANG`, `LC_CTYPE` and `LC_ALL` should be UTF8.
> 
> Cheers, Max

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

LC_CTYPE="en_US.UTF-8"
```
