### ISSUE TITLE
encoding error : input conversion failed

### ISSUE THREAD

**Issue by rsweerarathna** [mitmproxy/mitmproxy#1260]
Hi,
I'm using mitmdump -T with inline script and parallel decorator. It's printing frequent error on console as "encoding error : input conversion failed due to input error, bytes 0x81 0x18 0x19 0xA0"
But the proxy works as normal with high cpu utilization(more than 100%) when processing requests. 
Any idea what is it?

**Comment by Kriechi** [comment]
Is this related to #657?

**Comment by rsweerarathna** [comment]
what about the CPU utilization? It goes more than 100% when browse using only one connection. a quick spike of CPU when request comes. it's ok for one user. But what will happen when 100 users browsing same time?

**Comment by mhils** [comment]
It would be appreciated if you could answer @Kriechi's question when he's trying to help you. :wink: 

Regarding CPU Utilization: mitmproxy is bound to a single CPU core, so 100% CPU utilization would be pretty surprising unless you're running on a very limited machine. In that case, 100% would not be surprising. Whatsoever, mitmproxy is not designed to proxy a large number of users.
