### ISSUE TITLE
Script hooks are not executed when reading flows.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1262]
##### Steps to reproduce the problem:

1. `mitmdump -r dump -s script`

##### What went wrong?

Only the request script hook is executed.

##### Any other comments? What have you tried so far?

The problem is in `FlowMaster.run_scripts`, where we check for `if not msg.reply.acked`. If the first hook acks the request, things break.

**Comment by cortesi** [comment]
I noticed this issue while reading the code. I'm working on replacing the whole script hook mechanism with something that won't (can't) suffer from this issue, so I wonder if it's worth addressing right now. For what it's worth, the consistent behaviour I've picked here is for all script/addon hooks to be called after the master handler for each event type regardless of whether anything has been acked. This works for 95% of the use cases, and we can workshop how to cope with the other 5% once I have a concrete PR up to discuss.

**Comment by mhils** [comment]
> the consistent behaviour I've picked here is for all script/addon hooks to be called after the master handler for each event type regardless of whether anything has been acked

Sounds about right. I'll work around this for my specific case in the meantime.

**Comment by mhils** [comment]
refs #1265

**Comment by cortesi** [comment]
Fixed in the script refactoring
