### ISSUE TITLE
Intermittent Travis failure

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1271]
##### Steps to reproduce the problem:

1. Make a commit
2. Observe that Travis fails sometimes
3. Rebuild
4. Observe that it succeeds sometimes

##### What is the expected behavior?

Consistent error results

##### What went wrong?

Inconsistent error results.

https://travis-ci.org/mitmproxy/mitmproxy/jobs/138529203

![image](https://cloud.githubusercontent.com/assets/1019198/16169112/1cebe73a-34d7-11e6-9f05-f01f60b7d513.png)

**Comment by Kriechi** [comment]
Got another one:
<img width="830" alt="screen shot 2016-06-25 at 13 01 06" src="https://cloud.githubusercontent.com/assets/114300/16356363/f1815388-3ad4-11e6-92c1-580187f9bf67.png">

**Comment by Kriechi** [comment]
Similar to this one on Appveyor:
<img width="698" alt="screen shot 2016-06-26 at 20 48 58" src="https://cloud.githubusercontent.com/assets/114300/16364095/890700b2-3bdf-11e6-82c3-81fb1a4d3033.png">

**Comment by Kriechi** [comment]
fixed by #1634
