### ISSUE TITLE
How to run mitmdump/mitmproxy in background through terminal

### ISSUE THREAD

**Issue by Aswini999** [mitmproxy/mitmproxy#1289]
##### Steps to reproduce the problem:

 I'm using mitmproxy/mitmdump for http debugging and save responses as har file.

I've used below command through terminal  and it works fine
 `mitmdump -b <host> -p <port> -s "~/mitmproxy-0.17/examples/har_extractor.py ./result_file" `

But when I tried to run this background by using '&' at the end, command is working but file not saved.
 `mitmdump -b <host> -p <port> -s "~/mitmproxy-0.17/examples/har_extractor.py ./result_file" & `

##### What is the expected behavior?
* I need to Start mitmproxy in background
* Capture the traffic
* Save as har file
* Stop mitmproxy (Kill process)

And I need to run  these steps through ruby script. I'm calling shell commands in ruby script.
 

##### What went wrong?

Not able to save file when run in background.
Unable to Kill process when run in foreground

Mitmproxy Version: mitmproxy 0.17
Operating System: MAC OSX EI Capitan (10.11.2)

**Comment by mhils** [comment]
Thanks for the report. I don't think this is a mitmproxy issue though.

**Comment by woshizoufeng** [comment]
Maybe you can use other tools to do it. Such as pm2.
