### ISSUE TITLE
Unknown hosts not ignored

### ISSUE THREAD

**Issue by Kernald** [mitmproxy/mitmproxy#1290]
##### Steps to reproduce the problem:

1. Ignore an host impossible to resolve with your current DNS server
2. Make a request to this DNS name

##### What is the expected behavior?
The request is ignored and not displayed

##### What went wrong?
The request is displayed as failed: `Server connection to rx-v579:80 failed: Error connecting to "rx-v579": [Errno 8] nodename nor servname provided, or not known`

##### Any other comments? What have you tried so far?
I have an application on my Android phone making requests to my AVR. Which is not exposed outside of my LAN. When I'm at the office, I have requests to this domain all day long and can't ignore them.

I tried to ignore `rx-v579` and some regex variants, with no luck.

---

Mitmproxy Version: 0.17.1
Operating System: OS X 10.11.4

**Comment by mhils** [comment]
Thanks. Which proxy mode is that? Is the request TLS-encrypted? Can you provide a simple curl statement to reproduce the issue?

**Comment by Kernald** [comment]
It's in "default" proxy mode: the only option was the ignored hosts. The requests were plain HTTP requests. I'll try with curl as soon as I have a laptop handy.

**Comment by Kernald** [comment]
So, I just made a simple test. Being home, the `rx-v579` host shown in the original issue has a DNS entry, so I made the test with the non-existing host `rx-v`, but the issue is exactly the same.

1. I start `mitmproxy` on port 8090.
2. I add to the ignore list `rx-v` (without port or anything, just `rx-v`).
3. I run this `curl` command: `http_proxy=http://localhost:8090 curl http://rx-v/test`. It's giving me this HTML, which I don't have without using mitmproxy:
```
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>ProtocolException('Server connection to rx-v:80 failed: Error connecting to "rx-v": [Errno 8] nodename nor servname provided, or not known',)</body>
        </html>
```

At this point, I have an entry in mitmproxy:
```
>> GET http://rx-v/test
       ← Server connection to rx-v:80 failed: Error connecting to "rx-v": [Errno 8] nodename nor servname provided, or not known
```

**Comment by Kernald** [comment]
Alright, more information on that: the fact that the host is unknown doesn't seem to be the root of the problem. If I'm adding `rx-v579` to the ignore list, then making a request to `rx-v579` (same `curl` call as earlier, but with the correct hostname), `rx-v579` being an actual host on my network and returning a 200 OK for this request, I can see the entry on mitmproxy. Maybe the fact that the request is directed to an hostname instead of a FQDN is confusing mitmproxy?

**Comment by mhils** [comment]
It looks like you are running in the limitations listed in http://docs.mitmproxy.org/en/stable/features/passthrough.html#how-it-works ?

**Comment by Kernald** [comment]
I don't understand exactly what is an explicit HTTP request? But yeah, that's probably this.

**Comment by mhils** [comment]
explicit in the sense that it's explicitly considering a proxy.
Would mitmproxy's "Limit" feature to just hide the flow in the UI solve your issue? If so, we should improve the documentation here.

**Comment by Kernald** [comment]
That's indeed more clearer, thanks. `limit = !(~d rx-v579)` is exactly what I was looking for 👍

**Comment by mhils** [comment]
refs #542

**Comment by mhils** [comment]
Thanks!
