### ISSUE TITLE
Third-party viewers

### ISSUE THREAD

**Issue by kballenegger** [mitmproxy/mitmproxy#130]
*This is not so much an issue as a question I cannot find an answer for in the documentation.*

I'm trying to build a third-party viewer. My use case is this: I routinely use `mitmproxy` to inspect requests whose request and response body is encrypted and base-64 encoded.

Currently, I have a program that will decrypt the request and print the JSON body. I'd like to automate it in some fashion with `mitmproxy`.

I've read through the code in `contentview.py`, and it seems like I could somehow hook into the view / mode system. I see a comment which implies some form of support for third-party viewers:

```python
 # Third-party viewers can fail in unexpected ways...
```

https://github.com/cortesi/mitmproxy/blob/master/libmproxy/console/contentview.py#L462

So… my question is:

1. Would a custom viewer be the best option here? I want the request proxied as is, the decryption is only so that I can inspect it.
2. What would be the best way to write a custom viewer?
3. Could that custom viewer then call the json viewer, for prettification?

**Comment by mhils** [comment]
Thanks to @zbuc's work in #833, you can now add content views in inline scripts! We can finally close the second-oldest open mitmproxy issue. :relaxed:
