### ISSUE TITLE
TlsProtocolException

### ISSUE THREAD

**Issue by NajiMir** [mitmproxy/mitmproxy#1309]
When I was getting a page on assetscdn.stackla.com through mitmdump, I got the following exception: 

`127.0.0.1:45960: TlsProtocolException('Cannot establish TLS with assetscdn.stackla.com:443 (sni: None): TlsException("SSL handshake error: Error([(\'SSL routines\', \'SSL23_GET_SERVER_HELLO\', \'sslv3 alert handshake failure\')],)",)',)`

It looks like the SNI is None which raises the above exception. Is there any fix for this problem?

---

Mitmproxy Version: mitmdump 0.15
Operating System: Ubuntu 140.0.4

**Comment by Kriechi** [comment]
Thanks for the report.
You mentioned using mitmproxy 0.15 - could you please try to update to the latest version, many things changed and got improved since then. You can follow the installation instructions to get the most recent release: http://docs.mitmproxy.org/en/stable/install.html
