### ISSUE TITLE
Cannot connect to twitter with http2.

### ISSUE THREAD

**Issue by mike820324** [mitmproxy/mitmproxy#1310]
##### Steps to reproduce the problem:

1. Use firefox to connect to mitmproxy with socks mode.
2. Connect to https://twitter.com

##### What is the expected behavior?
Twitter will response with 200 OK.

##### What went wrong?
Twitter response with 400 bad request

##### Any other comments? What have you tried so far?
If disable http2 the behavior will be normal.

---

Mitmproxy Version: 0.17.0
Operating System: Max osx 10.10

**Comment by Kriechi** [comment]
Thanks for the report - I can reproduce the problem.
However, I'm a bit puzzled - no obvious reason why this fails. All headers are an exact match, and TLS setup seems to work properly as well...

**Comment by mike820324** [comment]
Thanks for the quick reply, myy friend and I are also invetigating on this issye too, we will update if we find out something useful.

**Comment by Kriechi** [comment]
I checked the TLS specifics - everything seems to match as well. Same cipher, same key bits, same ALPN, same TLS version.

**Comment by Kriechi** [comment]
I got a minimal example which still works with our codebase - by using the underlying things directly (no proxy):

```python
import pprint
import netlib.tcp
import h2
import hyperframe
from h2.connection import H2Connection
from netlib.http.http2 import framereader

client = netlib.tcp.TCPClient(("twitter.com", 443))
client.connect()
client.convert_to_ssl(sni='twitter.com', alpn_protos=[b'h2'])

h2_conn = H2Connection(client_side=True, header_encoding=False)
h2_conn.initiate_connection()
client.wfile.write(h2_conn.data_to_send())

headers = [
    (':authority', "twitter.com"),
    (':method', 'GET'),
    (':scheme', 'https'),
    (':path', '/'),
]
h2_conn.send_headers(
    stream_id=1,
    headers=headers,
    end_stream=True,
)
client.wfile.write(h2_conn.data_to_send())
client.wfile.flush()

########

while True:
    raw = b''.join(framereader.http2_read_raw_frame(client.rfile))
    frame, length = hyperframe.frame.Frame.parse_frame_header(raw[:9])
    frame.parse_body(memoryview(raw[9:]))
    pprint.pprint(frame)

    events = h2_conn.receive_data(raw)
    for event in events:
        if isinstance(event, h2.events.ResponseReceived):
            pprint.pprint(event.headers)
```

This gives me this output:
```
SettingsFrame(Stream: 0; Flags: None): 000400010000
SettingsFrame(Stream: 0; Flags: ACK):
HeadersFrame(Stream: 1; Flags: END_HEADERS): 8858ada8eb10649cbf4a...
[(':status', '200'),
 ('cache-control',
  'no-cache, no-store, must-revalidate, pre-check=0, post-check=0'),
 ('content-encoding', 'gzip'),
 ('content-length', '31153'),
 ('content-type', 'text/html;charset=utf-8'),
 ('date', 'Sun, 03 Jul 2016 09:22:40 GMT'),
 ('expires', 'Tue, 31 Mar 1981 05:00:00 GMT'),
 ('last-modified', 'Sun, 03 Jul 2016 09:22:40 GMT'),
 ('pragma', 'no-cache'),
 ('server', 'tsa_b'),
 ('set-cookie',
  'fm=0; Expires=Sun, 03 Jul 2016 09:22:30 GMT; Path=/; Domain=.twitter.com; Secure; HTTPOnly'),
 ('set-cookie',
  '_twitter_sess=BAh7CSIKZmxhc2hJQzonQWN0aW9uQ29udHJvbGxlcjo6Rmxhc2g6OkZsYXNo%250ASGFzaHsABjoKQHVzZWR7ADoPY3JlYXRlZF9hdGwrCMchEbBVAToMY3NyZl9p%250AZCIlM2M5NGRjZTI1YWMxOGI2ZjIyYWRmYjNmZTMzNGNiNWE6B2lkIiVjNGVi%250AYjc3MDY3MzJlNTIxMTIwMzM5YWQ4MWU0ODNkZQ%253D%253D--03b89bc34287041fdecd389615f7fc654edc1c12; Path=/; Domain=.twitter.com; Secure; HTTPOnly'),
 ('set-cookie',
  'guest_id=v1%3A146753776070981391; Domain=.twitter.com; Path=/; Expires=Tue, 03-Jul-2018 09:22:40 UTC'),
 ('status', '200 OK'),
 ('strict-transport-security', 'max-age=631138519'),
 ('x-connection-hash', 'e6347e66f7bd35d188c1b173cdd88615'),
 ('x-content-type-options', 'nosniff'),
 ('x-frame-options', 'SAMEORIGIN'),
 ('x-response-time', '184'),
 ('x-transaction', '003cd51c008f403c'),
 ('x-twitter-response-tags', 'BouncerCompliant'),
 ('x-ua-compatible', 'IE=edge,chrome=1'),
 ('x-xss-protection', '1; mode=block')]
DataFrame(Stream: 1; Flags: None): 1f8b08000000000002ff...
<and a few more data frames>
```



So now we not it is not a fundamental problem in our low-level code. netlib, hyper-h2, and pyopenssl seems to be ok. So we must look for some very subtle change during proxy operation.

**Comment by Kriechi** [comment]
Got it!

Twitter seems to suffer from the same problem as Akamai #1161 (probably related codebase / infrastructure).
Sending a `END_STREAM` flag with the HeadersFrame works. But sending it with an empty DataFrame after the headers, fails with HTTP error 400. This is clearly a violation of RFC 7540 in their implementation.

/cc @Lukasa

**Comment by Kriechi** [comment]
A fix is almost available, we only need to wait for https://github.com/python-hyper/hyper-h2/pull/240 to be released in the h2 2.4.0. Then it is only a few lines of change in mitmproxy to fix this, by replicating the request frame-by-frame from the user to the server.

**Comment by Lukasa** [comment]
Cool, I'll see if I can ping a Twitterer.

**Comment by fsareshwala** [comment]
Hi guys, I am an Twitter engineer. Thank you for reporting this bug. We've fixed this on our end so that we're compliant with the HTTP 2 spec. I've confirmed that things are working properly with the script that @Kriechi posted above. I've also ensured that passing traffic through mitmproxy while connecting to twitter.com.

Please let me know if you're seeing anything different. Thanks again!

**Comment by Lukasa** [comment]
Thanks @fsareshwala!

**Comment by Kriechi** [comment]
Great! Many thanks to @fsareshwala!
