### ISSUE TITLE
Can not login to facebook/google with http2 

### ISSUE THREAD

**Issue by mike820324** [mitmproxy/mitmproxy#1311]
##### Steps to reproduce the problem:

1. Use firefox and connect to mitmproxy with socks mode.
2. Connect to https://www.facebook.com or https://accounts.google.com .
3. Try to login.

##### What is the expected behavior?
Should get 200 OK and login to the website.

##### What went wrong?
Get 302 redirect from both sites and redirect to the original login site.

##### Any other comments? What have you tried so far?
The behavior will be normal if we disable http2.

---

Mitmproxy Version: 0.17.0
Operating System: osx 10.11

**Comment by mhils** [comment]
Hi @mike820324,

Thanks for the reports. We'll look into it. 

I just stumbled upon https://github.com/mike820324/microProxy - great work! There's certainly some stuff in there which would be great for mitmproxy as well. I know that building your own stuff is always tempting, but if you want, we're always open for changes to the project. In any case, feel free to join us on [Slack](https://slack.mitmproxy.org/) if you want to chat! :smiley:

**Comment by Kriechi** [comment]
I just checked accounts.google.com - it seems to work just fine for me. I can enter my email, then I get asked for my 2-factor auth token, then I got a random security update check, and then I was redirected to  `https://myaccount.google.com/?pli=1` where I am fully signed in.

Testing facebook is inconclusive for me (no account). But I did enter a random email and an (probably) wrong password, and I got redirected to a "wrong password, please try again" page.

**Comment by mike820324** [comment]
@Kriechi I'll check it out again to see if I can still reproduce the problem.

@mhils Thank you. mitmproxy is a wonderful and incredible tool which help me a lot. The only difference between mitmproxy and microProxy is the separation of proxy and viewer into different process and using pyzmq pub/sub as the message channel which can give more control and flexible to the ui development. Maybe I should create a issue or discuss this idea on slack.

**Comment by mike820324** [comment]
It seems like the issue has been solved in the latest version according to 
https://discourse.mitmproxy.org/t/cookies-disabled-for-google-account/57/9

Moreover, I have also tested the mitmproxy with the master branch, and it works as expected. I think this issue can be closed.

Just curious, what is the change between 0.17.1 to master that fix this issue.
