### ISSUE TITLE
Script Reloader fails crashes on Ubuntu on Windows 10

### ISSUE THREAD

**Issue by kuza55** [mitmproxy/mitmproxy#1340]
##### Steps to reproduce the problem:

1. Install mitmproxy on ubuntu on windows 10
2. run mitmdump

##### What is the expected behavior?
mitmdump runs

##### What went wrong?
mitmdump crashes because inotify is not supported on ubuntu on windows 10

##### Any other comments? What have you tried so far?
I set use_relader=False in mitmdump.py to fix this for myself.

**Comment by mhils** [comment]
Thanks for the useful report! :smiley:
Coincidentially, I disabled the native observers due to other issues two weeks ago, so this should already be fixed by this.
https://github.com/mitmproxy/mitmproxy/blob/427ba886182563a83f71dc966b139e504f25ad39/mitmproxy/script/reloader.py#L7-L10
