### ISSUE TITLE
virtualenv --always-copy fails 

### ISSUE THREAD

**Issue by ntulele** [mitmproxy/mitmproxy#1346]
##### Steps to reproduce the problem:
I attempted to follow the  [Hacking instructions]:
1. Attempt to execute dev.sh -- or more specifically, the virtualenv setup portion: `virtualenv venv --always-copy`

##### What is the expected behavior?
Successful virtualenv setup

##### What went wrong?
Many "Operation not permitted" errors

```
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 1129, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 355, in copyfile
    copyfileordir(src, dest, symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 327, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_AE.so',  "[Errno 1] Operation not permitted: '/Users/paul.poling/mitmproxy/venv/lib/python2.7/lib-dynload/_AE.so'"),
. . . ~100 more "Operation not permitted" errors 
```
##### Any other comments? What have you tried so far?
`virtualenv venv`  works, so it's only the "always-copy"  that's failing.  
_Should I expect issues due to my virtualenv using symlinks instead of copies?_

Permissions on files in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7 are 744 and owned by root, e.g.:
`-rwxr-xr-x  1 root  wheel  77248 Mar 12 00:06 /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_AE.so`

I tried executing as sudo, but that caused permissions issues later on.  

I don't have another clean Mac env to test on, so I'm unsure if this is just an issue with my python install -- perhaps I did sudo pip install at some point, which is evidently incorrect for El Capitan.

---
Mitmproxy Version: master @ 427ba
Operating System: OSX El Capitan 10.11.4

**Comment by Kriechi** [comment]
Thanks for your bug report. 
Unfortunately this is an issue with El Capitan and System Integrity Protection. Please try and use python from homebrew instead.
https://github.com/gevent/gevent/issues/679#issuecomment-152893140
