### ISSUE TITLE
How to enter in regex filter?

### ISSUE THREAD

**Issue by macdonjo** [mitmproxy/mitmproxy#1359]
##### Steps to reproduce the problem:

1. Type: ~d regex
2. Notice that it doesn't filter anything.

##### What is the expected behavior?
It's supposed to filter.

How do I filter with this? I see the instructions, but I don't know how I can enter this filter in?

![image](https://cloud.githubusercontent.com/assets/2490900/16863251/c5cd63f4-4a1e-11e6-9c29-d26f43383e91.png)

**Comment by mhils** [comment]
I'm not sure what you want to accomplish. Do you want to filter the view?  In this case you want to set a limit, not an interception pattern.

refs #542

**Comment by dufferzafar** [comment]
@mhils I think @macdonjo started just typing `~d regex`, they have to type the `l` key first, and then the filters.

**Comment by macdonjo** [comment]
Thanks to both of you. #542 did answer that, and @dufferzafar is correct. Thanks for everything. GREAT tool!

**Comment by dufferzafar** [comment]
@mhils right below the "Filter expressions" header, we could add a line: "You need to press `l` to get into the filter mode" or something.

**Comment by bidiu** [comment]
Need help here. How do I get into filter mode? `l` won't do the work for me somehow.

**Comment by iamfreee** [comment]
@bidiu you have to use the `f` for filter mode, then type your filter expression.

**Comment by YukiGibson** [comment]
`f` is deprecated, use `--view-filter`
