### ISSUE TITLE
Tutorial about game center, typo?

### ISSUE THREAD

**Issue by macdonjo** [mitmproxy/mitmproxy#1360]
I’ll beat your game center score on any game http://docs.mitmproxy.org/en/stable/tutorials/gamecenter.html?highlight=phone

The score in the plist is 0, but the text says 55. Is this a typo? Kind of confusing.

**Comment by mhils** [comment]
Yes, this looks like a type. Can you send a PR that fixes this? :smiley:

**Comment by DrakeCaraker** [comment]
I submitted a PR fixing the issue!

**Comment by cortesi** [comment]
Closing. Thanks for the patch - these small cleanups really make a difference.

**Comment by macdonjo** [comment]
Hey, sorry, I didn't know what PR stood for. I forgot to reply saying that.

**Comment by cortesi** [comment]
@macdonjo "PR" is a Pull Request. That is, a patch fixing the issue. Hope to see a PR for something else from you soon. :)
