### ISSUE TITLE
exception from netlib - reason not well formated get request

### ISSUE THREAD

**Issue by dervagabund** [mitmproxy/mitmproxy#1366]
##### Steps to reproduce the problem:
I had a problem with a client that sent a "wrong" GET request: GET <absoluteurl> HTTP/1.1 with 2 spaces between <absoluteurl> and HTTP/1.1

##### What went wrong?
exception from netlib/http/http1/read.py on line 247 because split in line 232
 method, path, http_version = line.split(b" ")
seems to be wrong. I have fixed it for me be changing the split to
 method, path, http_version = line.split()

Then it worked.

Best regards,
Thomas

**Comment by Kriechi** [comment]
Thanks for the report - I think it is a good idea to be more liberal in what we accept (slight non-conformity to RFC should be ok). This issue will be fixed in #1367 - are these the changes you applied?
