### ISSUE TITLE
You are using an outdated version of pyOpenSSL

### ISSUE THREAD

**Issue by loretoparisi** [mitmproxy/mitmproxy#1384]
I get this error
```shell
macbookproloreto:~ admin$ mitmproxy
You are using an outdated version of pyOpenSSL: mitmproxy requires pyOpenSSL 0.14 or greater.
Your pyOpenSSL 0.13.1 installation is located at /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL
macbookproloreto:~ admin$ 

```

for 

```shell
macbookproloreto:~ admin$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34
```

**Comment by Kriechi** [comment]
Thanks for your bug report @loretoparisi.
How did you install mitmproxy? It seems like you are using the OSX system python - which usually has problems with OpenSSL, due to the fact, that Apple decided to deprecate it on their platform.

Please try installing the latest Python with homebrew, or try a pre-packaged mitmproxy for OSX: 
https://github.com/mitmproxy/mitmproxy/releases/tag/v0.17.1

**Comment by loretoparisi** [comment]
@Kriechi basically for my understanding the problem is `El Capitan` and the `System Integrity Protection (SIP)` that prevents to upgrade libraries like`PyOpenSSL` as [downside](http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11). So I have to disable this `rootless` as explained [here](http://teilin.net/using-mitmproxy-to-reverse-engineer-applications/):

```text
To disable rootless, you need to restart the computer and hold CMD + R while booting. Then in the Utilities menu, select the terminal. IN the terminal, type csrutil disable. Then restart again. To enable rootless again, just replace disable with enable.
```

Luckily, thanks to `virtualenv` this can be avoided following the good tutorial [Setting up mitmproxy on OSX El Capitan](http://teilin.net/using-mitmproxy-to-reverse-engineer-applications/) that can be done in these simple steps:

```shell
$ xcode-select --install
$ git clone https://github.com/mitmproxy/mitmproxy.git
$ cd mitmproxy
$ ./dev.sh
$ . venv/bin/activate 
(venv)mitmproxy admin$ mitmdump --version
mitmdump 0.18
(venv)mitmproxy admin$ mitmproxy --version
mitmproxy 0.18
```
