### ISSUE TITLE
mitmproxy with modify_response_body.py produces a ScriptException.

### ISSUE THREAD

**Issue by Cykey** [mitmproxy/mitmproxy#1386]
##### Steps to reproduce the problem:

1. Start mitmproxy with the `-s` option, like this for example: 

    `./mitmproxy -s "./examples/modify_response_body.py abc def"`

##### What went wrong?

```
davidsmbp:mitmproxy-0.17.1-osx cykey$ ./mitmproxy -s "./examples/modify_response_body.py abc def"
Script load error: Traceback (most recent call last):
  File "site-packages/mitmproxy/flow.py", line 694, in load_script
  File "site-packages/mitmproxy/script/script.py", line 89, in load
  File "site-packages/mitmproxy/script/script.py", line 118, in run
  File "site-packages/mitmproxy/script/script.py", line 113, in run
ScriptException: start() takes no arguments (2 given)
```

---

Mitmproxy Version: 0.17.1
Operating System: osx

**Comment by mhils** [comment]
Hi!

It looks like your inline script is from master, but you are using the latest stable release from mitmproxy. Can you please select the right tag on GitHub and try again?

![image](https://cloud.githubusercontent.com/assets/1019198/17031301/2bcfd91c-4f28-11e6-85f9-1f9a0e7832e2.png)

**Comment by Cykey** [comment]
Whoops, works now. Sorry about that!

**Comment by mhils** [comment]
No Problem! :smiley:
