### ISSUE TITLE
mitmproxy has crashed! NameError: global name 'http_cookies' is not defined

### ISSUE THREAD

**Issue by shrikantkaramkar** [mitmproxy/mitmproxy#1389]
##### Steps to reproduce the problem:

1. Open mitmproxy
2. capture a call 
3. go to response
4. To edit the cookies press c

##### What is the expected behavior?
It should display all available cookies

##### What went wrong?
mitmdump crashed

##### Any other comments? What have you tried so far?

---

Mitmproxy Version:
Operating System:

**Comment by mhils** [comment]
I don't find a single reference of `http_cookies` on master, so I suppose this is fixed.
