### ISSUE TITLE
Status bar state confusion

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1394]
##### Steps to reproduce the problem:

1. `mitmproxy`
2. `n g enter e`

##### What is the expected behavior?
Event log should show.

##### What went wrong?
I'm also getting a `Quit (yes, no)?` prompt.

---

Mitmproxy Version: master
Operating System: Ubuntu 14.04 x64

**Comment by dufferzafar** [comment]
You don't even have to press `n g enter`. I see the same prompt when I press `e`.
