### ISSUE TITLE
cookies: support multi-cookie, comma-separated header variant

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1434]
At the moment, we only support strictly compliant cookies, where each cookie is in a separate header. The justification for this we give in the module docstring is that "violations of RFC6265 that makes the parsing problem indeterminate are much more common than genuine occurences of the multi-cookie variants". However, a recent sample from Netograph shows old-style cookies in ~9% of sites, with many high-profile sources like DoubleClick. There's no way around it - we simply must correctly parse this variant.

**Comment by Kriechi** [comment]
Do you have a few examples of the cookies you are seeing with Netograph?

**Comment by dufferzafar** [comment]
Here is one that @cortesi shared: https://gist.github.com/dufferzafar/91f6b7a329a9d61dd0556e314b627226
