### ISSUE TITLE
Wait for lxml release with wheels

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1444]
For the next mitmproxy release, we want to recommend Python 3.5 by default. While this is not ultimately blocking, it would be ideal to have a lxml release with Python 3.5 wheels on PyPI for this.  I did some work to make that happen in https://github.com/lxml/lxml/pull/200, so this hopefully can be resolved rather soon.

**Comment by cortesi** [comment]
We're blocked upstream by this, and I'd like to get 0.18 out the door. Since 0.18 is our last Python2/3 release, we can cope with not having lxml wheels. I'm moving this to the 1.0 milestone
