### ISSUE TITLE
mitmproxy install problem

### ISSUE THREAD

**Issue by shrikantkaramkar** [mitmproxy/mitmproxy#1455]
I am trying to install mitmproxy by: `sudo pip install mitmproxy`
Getting error:
```
 mitmproxy --version
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 7, in <module>
    from mitmproxy.main import mitmproxy
  File "/Library/Python/2.7/site-packages/mitmproxy/main.py", line 5, in <module>
    from six.moves import _thread  # PY3: We only need _thread.error, which is an alias of RuntimeError in 3.3+
ImportError: cannot import name _thread
```

OS: OSX 10.10.5
Python version: `Python 2.7.10`

Tried to remove this error but did not get access.

**Comment by mhils** [comment]
This particular issue was fixed by `six 1.5.0`. We require at least `six 1.10.0`, so it looks like you still have an old version of six hanging around in your system. There's not much we can do here, sorry - this is not a mitmproxy-specific problem.

**Comment by shrikantkaramkar** [comment]
on my system, current version of six is `six-1.10.0`

**Comment by mhils** [comment]
`python -c "from six.moves import _thread"` works fine for me with six-1.1.0.
