### ISSUE TITLE
Add Replace from file to Replacement Editor

### ISSUE THREAD

**Issue by dufferzafar** [mitmproxy/mitmproxy#1458]
We have a replacement editor (press `o` then `R` in mitmproxy) that allows us to add replacement patterns for flows. 

There's also a `--replace-from-file` cmdline option that gets the replacement text from a local file.

But this functionality can't be used from the replacement editor itself. 

---

A user tried to enter the path to file in the Replacement text field: https://discourse.mitmproxy.org/t/emulate-charles-proxys-map-local/116

**Comment by arjun23496** [comment]
Is anyone currently working on this issue ? If no, may I work on this ?

**Comment by dufferzafar** [comment]
@arjun23496 I don't think anyone is working so feel free to take it up, but before you start I think it'll be nice if you discuss your ideas with the dev team over at Slack.

**Comment by cortesi** [comment]
Fixed by #2120
