### ISSUE TITLE
Error in HTTP connection

### ISSUE THREAD

**Issue by neurobin** [mitmproxy/mitmproxy#1462]
##### Steps to reproduce the problem:

1. Run mitmproxy/mitmdump
2. Visit http://ip-check.info/?lang=en
3. Click on the START TEST! link

##### What is the expected behavior?
Shouldn't show errors

##### What went wrong?

These are the errors I got in a session:

```python
127.0.0.1:40514: ProtocolException("Error in HTTP connection: HttpException('Invalid request scheme: ftp',)",)

127.0.0.1:40534: ProtocolException("Error in HTTP connection: HttpException('Invalid request scheme: ftp',)",)

127.0.0.1:40546: ProtocolException("Error in HTTP connection: HttpException('Invalid request scheme: ftp',)",)

127.0.0.1:40472: ProtocolException('Error in HTTP connection: TcpDisconnect("(32, \'EPIPE\')",)',)

127.0.0.1:40606: ProtocolException('Error in HTTP connection: TcpDisconnect("(32, \'EPIPE\')",)',)
```

---

Mitmproxy Version: 0.18 (latest pull from master branch)
Operating System: Xubuntu 16.04 LTS
Python 3.5.1+
Pip 8.1.2

**Comment by mhils** [comment]
Thanks for the report. The ip-check.info website tries to do FTP requests, which mitmproxy does not support natively. We don't plan to support FTP anytime soon, so I'm closing this for now.
