### ISSUE TITLE
Add API to programatically create new requests.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1473]
Original discussion: https://discourse.mitmproxy.org/t/are-there-any-script-examples-for-creating-a-get-post-put/134

It would be great if we'd have a dedicated API to make new requests from scripts, e.g. `master.new_request()` or something along those lines. This would probably just call `new_request` and then `replay_request`, but this seems useful enough to spell out explicitly.

**Comment by arjun23496** [comment]
When I try to import master from mitmproxy error occurs saying that it cannot import master from mitmproxy. I tried to load the script dup_and_replay.py in examples which imports master from mitmproxy, it also shows error. Any help would be appreciated. I am new at this so thank you in advance

**Comment by Kriechi** [comment]
Unfortunately #1534 introduced a problem with the test suite, so we had to revert it.
Therefore I'll reopen this issue to keep track of it.

**Comment by ujjwal96** [comment]
Hi, I'd like to work on this. I'm still figuring out the source code so, I'll be glad if you can help me a little.
Do you need this to be in mitmproxy.master ?

**Comment by anikravesh** [comment]
is there any update on this?

**Comment by idujmic** [comment]
Has this been resolved?

**Comment by mhils** [comment]
Kind of. You can invoke commands from within mitmproxy addons, so you can call `view.flows.create` and then `replay.client` for example :)
