### ISSUE TITLE
Script error: __init__() takes at least 6 arguments (5 given)

### ISSUE THREAD

**Issue by shrikantkaramkar** [mitmproxy/mitmproxy#1475]
I am using redirect_request.py to redirect multiple urls.
On executing this py I am getting following error:

Script error:
__init__() takes at least 6 arguments (5 given)
I am using following mitm method to redirect:

from mitmproxy.models import HTTPResponse
from netlib.http import Headers

def request(flow):
    # pretty_host takes the "Host" header of the request into account,
    # which is useful in transparent mode where we usually only have the IP
    # otherwise.

    # Method 1: Answer with a locally generated response
    if flow.request.pretty_host.endswith("example.com"):
        resp = HTTPResponse(
            b"HTTP/1.1", 200, b"OK",
            Headers(Content_Type="text/html"),
            b"helloworld"
        )
        flow.reply.send(resp)
mitmproxy version: 0.17
OS: MAC OSX Yosemite 10.10.5

**Comment by shrikantkaramkar** [comment]
I added following in the Httpresponse to meet the parameters criteria but still getting same error:
```
                                timestamp_start=flow.request.timestamp_start,
                                timestamp_end=flow.request.timestamp_end,
                                is_replay=False
```

**Comment by mhils** [comment]
```python
λ mitmdump -s examples/redirect_requests.py 
```

```python
λ curl -x localhost:8080 example.com
helloworld
```

works fine for me on master.
