### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'

### ISSUE THREAD

**Issue by hynguyen2610** [mitmproxy/mitmproxy#1476]
##### Steps to reproduce the problem:

I am following http://docs.mitmproxy.org/en/stable/features/setheaders.html to set header for a page in mitmdump.

1. I want to set "Host" request header of page https://tinhte.vn to "127.0.0.1., so I run the mitmdump command with --setheader, this in my proxy computer.
mitmdump -R https://tinhte.vn --setheader :~q:Host:127.0.0.1
2. In my victim computer, I browse to https://tinhte.vn (page above)
3. I got the error `AttributeError: 'NoneType' object has no attribute 'alpn_protocols'`

##### What is the expected behavior?
The page will load successful in victim browser with HOST request header is set to "127.0.0.1"

##### What went wrong?
Mitmdump crash with this message:
```
192.168.6.179:49564: clientconnect
Traceback (most recent call last):
  File "/home/hynguyen/mitmproxy/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/home/hynguyen/mitmproxy/mitmproxy/proxy/modes/reverse_proxy.py", line 15, in __call__
    layer()
  File "/home/hynguyen/mitmproxy/mitmproxy/protocol/tls.py", line 372, in __call__
    self._client_hello.alpn_protocols or
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
192.168.6.179:49564: Traceback (most recent call last):
  File "/home/myname/mitmproxy/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/home/myname/mitmproxy/mitmproxy/proxy/modes/reverse_proxy.py", line 15, in __call__
    layer()
  File "/home/hynguyen/mitmproxy/mitmproxy/protocol/tls.py", line 372, in __call__
    self._client_hello.alpn_protocols or
AttributeError: 'NoneType' object has no attribute 'alpn_protocols'
```

##### Any other comments? What have you tried so far?
Nope

---

Mitmproxy Version: 0.18
Operating System: LinuxMint 18

**Comment by mhils** [comment]
Thanks for the report!

Repro:
```
λ mitmdump -R https://example.com
λ curl localhost:8080
```

There are a couple of places in tls.py where we reference `_client_hello` that should be fixed. Also, this definitely needs a regression test.
