### ISSUE TITLE
Why did i can't capture AppStore HTTPS traffic with mitmproxy?

### ISSUE THREAD

**Issue by jimzhao2012** [mitmproxy/mitmproxy#149]
AppStore in my iPhone4 (iOS6.1.3) can't capture;
but AppStore in iPod(iOS 5.1.1) can capture;
why? how can i do, then i can capture HTTPS request in iOS 6.1.3?

**Comment by pythonwood** [comment]
@cortesi @timesking  it is greatful and helpful if done.

**Comment by rriemann** [comment]
For future reference: This helped me to unpinn the certificate check of the apple iOS app on iPhone: 13.3:

https://zeroinfosec.com/2020/05/07/the-only-way-to-bypass-ssl-pinning-on-ios-13/
