### ISSUE TITLE
Add max replacements/count argument to flow.replace

### ISSUE THREAD

**Issue by LopoEvil** [mitmproxy/mitmproxy#1495]
##### Steps to reproduce the problem:

```python
 regex1 = r'\d+\#\d+\#\d+\#\d+\#(\d+)\#\d+\#\d+\#\d+\#\d+\#'
 re.compile(regex1)
 flow.response.replace(regex1, r'444#5555#66#77#\1#0#0#0#0#', 10)
```

![notepad _2016-08-20_11-17-57](https://cloud.githubusercontent.com/assets/15959479/17833044/07dee18a-66c8-11e6-8bf7-dfb50aef2ee7.png)

##### What is the expected behavior?

`flow.response.replace(regex1, r'444#5555#66#77#\1#0#0#0#0#', 10)`

The **10** used should be Max Count or Max Replace

##### What went wrong?

In  `flow.response.replace(old, new[, maxreplace])`

is no longer working, all my older scripts are now broken; this used to work fine.

##### Any other comments? What have you tried so far?

I have tried changing my replace to a variable, changing the long regex and replace with something very small and simple.

Work Great on my other servers that run MITMProxy 0.15 and i think 0.16 was working too.

*When i updated to 0.17 or 0.18 it then no longer works and my scripts are broken.

---

Mitmproxy Version:  0.17 and 0.18
Operating System:  Ubuntu 14.04 and 16.04

**Comment by dufferzafar** [comment]
I think the problem is not with replace, but in your script. The syntax has changed a bit.

```
import re

# Notice that the context parameter is no longer needed
def response(flow):
    flow.response.replace("this", "that")
```

I've tested that this works with latest code from master!

**Comment by LopoEvil** [comment]
@dufferzafar 

Thank you for the reply,

Sorry, but that did not help :(

Thank you for letting me know that it is no longer needed, but this did not allow;
flow.response.replace("this", "that", **COUNT**) to work.

the normal replace works, but the "COUNT" Does not; this is my issue with version 0.17 and 0.18
- on all the older version eg. 0.15 and 0.16; COUNT works great!

for example, there are a 100 Zip codes and you only want to change the first one; it would be something like:
flow.response.replace("[0-9]{5}", "12345", 1) = Replace the First Occurrence of a 5 digit number.
Now Only flow.response.replace("[0-9]{5}", "12345") Works; Replacing ALL 5 digit numbers.

This is my issue, I hope this help explain it better... :)
 
Thank you again.

**Comment by mhils** [comment]
We'd be happy to accept a PR that reintroduces the count argument. Other than that, `response.content = response.content.replace("foo","bar")` may just be what you are looking for anyways.

**Comment by LopoEvil** [comment]
@mhils 

Thank you for your reply.

I would love to add a Personal Request to reintroduce the COUNT argument.

I was not sure if this is/was a BUG or if it was taken out, changed for some reason; No idea why this would be removed.

I was thinking of using re.sub() or some other python commands to have it's MAX COUNT function work within the .py script, but was not able to succeed.

For now I'm stuck using Version 0.16, but hopefully down the line I could use the latest Versions.

I'm open to other suggestion or examples on a workaround for Replace the FIRST Occurrence of a Regex in the BODY of a Response.

Thank you all.
