### ISSUE TITLE
Divide by Zero error

### ISSUE THREAD

**Issue by mkagenius** [mitmproxy/mitmproxy#1501]
Its in `netlib/strutils.py`

This line # around 126 :
```python
    for i in six.iterbytes(s[:100])
) / len(s[:100]) > 0.3
```

if s is empty, it gives this error in the mitmproxy, (doesn't crash though due to recent improvements in mitmproxy i guess..)

**Comment by mhils** [comment]
Thanks. This looks easy to fix, so if anyone wants to get started on mitmproxy development, I'd be happy to see a PR with fix + added test in test/netlib/test_strutils.py! :smiley:
