### ISSUE TITLE
har_dump throwing error when body content has weird characters 

### ISSUE THREAD

**Issue by mkagenius** [mitmproxy/mitmproxy#1502]
##### Steps to reproduce the problem:

1. Use har_dump.py as script
2. Browser lot of things
3. Eventually you will errors like this

```
Error: Script error: Traceback (most recent call last):
  File "/Users/manish/Work/mitmproxy/mitmproxy/builtins/script.py", line 146, in run
    return func(*args, **kwargs)
  File "har_dump.py", line 96, in response
    response_body_decoded_size = len(flow.response.content)
  File "/Users/manish/Work/mitmproxy/netlib/http/message.py", line 115, in get_content
    return encoding.decode(self.raw_content, ce)
  File "/Users/manish/Work/mitmproxy/netlib/encoding.py", line 56, in decode
    repr(encoding),
ValueError: AssertionError when decoding "\x87-\x00 with 'br'
```

##### What is the expected behavior?
Not throw error

##### What went wrong?
These characters are weird, i hate them

##### Any other comments? What have you tried so far?
none

---

Mitmproxy Version: Head (1.8 i guess)
Operating System: mac

**Comment by Schamper** [comment]
From local testing, #1515 seems to solve this.
