### ISSUE TITLE
mitmdump should display "ready" message after start.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1505]
##### Steps to reproduce the problem:

2. `mitmdump`

##### What is the expected behavior?

mitmdump should print some notification that it is running and ready to receive traffic.

##### What went wrong?

mitmdump just displays nothing, it looks like it hangs.

##### Any other comments? What have you tried so far?

Ideally we'd only show that if mitmdump is invoked in a tty?

---

Mitmproxy Version: 0.18
Operating System: Win10 x64

**Comment by Kriechi** [comment]
ref: #302
