### ISSUE TITLE
  Could not find a version that satisfies the requirement mitmproxy>=0.18

### ISSUE THREAD

**Issue by loretoparisi** [mitmproxy/mitmproxy#1507]
Could not find a version that satisfies the requirement mitmproxy>=0.18 (from -r requirements.txt (line 1)) (from versions: 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.10, 0.10.1, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13, 0.14.0, 0.15, 0.16, 0.17)
No matching distribution found for mitmproxy>=0.18 (from -r requirements.txt (line 1))

where

```shell
$ cat requirements.txt 
mitmproxy>=0.18
```

**Comment by dufferzafar** [comment]
That is because 0.18 has not been released yet. 😛 

https://pypi.python.org/pypi/mitmproxy

**Comment by loretoparisi** [comment]
@dufferzafar thanks!
