### ISSUE TITLE
"zombie stream" exception while loading twitter.com

### ISSUE THREAD

**Issue by jgherb** [mitmproxy/mitmproxy#1508]
`[ip]:[port]: clientconnect
[ip]:[port]:: 
    GET https://twitter.com/push_service_worker.js HTTP/2.0
    :authority: twitter.com
    [user_agent]
    accept-language: en-US,en;q=0.5
    accept-encoding: gzip, deflate, br
    service-worker: script
    [cookies]
    pragma: no-cache
    cache-control: no-cache

 << 200  3k
    cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0
    content-encoding: gzip
    content-length: 3533
    content-type: application/javascript;charset=utf-8
    date: Thu, 25 Aug 2016 12:44:49 GMT
    etag: 146cdcb3dfe4cfbe78b0381ef41f0ce6
    expires: Tue, 31 Mar 1981 05:00:00 GMT
    last-modified: Thu, 25 Aug 2016 12:44:49 GMT
    pragma: no-cache
    server: tsa_o
    set-cookie: fm=0; Expires=Thu, 25 Aug 2016 12:44:39 GMT; Path=/; Domain=.twitter.com; Secure; HTTPOnly
    set-cookie: _twitter_sess=[session id]; Path=/; Domain=.twitter.com; Secure; HTTPOnly
    status: 200 OK
    strict-transport-security: max-age=631138519
    x-connection-hash: 54fa38e56afa79d4d1238249f1d18bfd
    x-content-type-options: nosniff
    x-frame-options: SAMEORIGIN
    x-response-time: 105
    x-transaction: 00732d8a00ba9b70
    x-twitter-response-tags: BouncerCompliant
    x-ua-compatible: IE=edge,chrome=1
    x-xss-protection: 1; mode=block

[ip]:[port]: ProtocolException("Error in HTTP connection: Http2ProtocolException('Zombie Stream',)",)
`

**Comment by Kriechi** [comment]
Thanks for the report.
This is actually not a problem but a artifact of closed connections.
The next release will have a better log message and improved handling.
