### ISSUE TITLE
Support SameSite Cookie Attribute

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#1512]
I think we have to make a few changes to support the SameSite cookie attribute:
`netlib/http/cookies.py` and probably in the HAR code as well.

https://www.chromestatus.com/feature/4672634709082112
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by mhils** [comment]
What kind of changes do we need to do for this?

**Comment by Kriechi** [comment]
We need to add the new attribute to https://github.com/mitmproxy/mitmproxy/blob/master/netlib/http/cookies.py#L29-L32.
And then probably just some tests to ensure our parser manages the new attribute and passes it correctly when re-assembling.
I'm not sure about HAR though.

**Comment by dufferzafar** [comment]
@Kriechi The lines you linked to are *only* used by the HAR dumper (& no other parts of mitm) and the [HAR spec](http://www.softwareishard.com/blog/har-12-spec/#cookies) doesn't mention the SameSite attribute, so I'm not too sure what we need to do here.

Apart from that our cookie parser is quite dumb (rightfully so, I think) in that it has no concept of what attributes are allowed in a cookie/set-cookie header, so I don't think there'd be any problems wrt parsing SameSite stuff.

**Comment by Kriechi** [comment]
@dufferzafar alright - thats a good thing!
However, I think it is a bit misleading - only because right now the code in netlib/http/cookies is only used by HAR dumper - somebody else might use the same functions without knowing...
