### ISSUE TITLE
Decoding an empty string fails with "deflate" and "br"

### ISSUE THREAD

**Issue by Schamper** [mitmproxy/mitmproxy#1520]
##### Steps to reproduce the problem:

```
In [15]: from netlib import encoding

In [16]: encoding.decode('', 'deflate')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-074267748746> in <module>()
----> 1 encoding.decode('', 'deflate')

/home/ames/dev/mitmproxy/netlib/encoding.pyc in decode(encoded, encoding, errors)
     54             type(e).__name__,
     55             repr(encoded)[:10],
---> 56             repr(encoding),
     57         ))
     58 

ValueError: error when decoding '' with 'deflate'
```

##### What is the expected behavior?

Return an empty string. `gzip` works as expected:
```
In [18]: encoding.decode('', 'gzip')
Out[18]: ''
```

##### What went wrong?

`deflate` and `br` are unable to decode empty strings.

##### Any other comments? What have you tried so far?

Not sure what the preferred way of solving this is. Possibly a check to return an empty string if an empty string is attempted to be decoded?

---

Mitmproxy Version: master (0.18)
Operating System: Ubuntu 16.04

**Comment by dufferzafar** [comment]
@Schamper If this happens *only* for empty strings, then yeah we could just return an empty string back.

**Comment by Kriechi** [comment]
Actually I think brotlipy can handle empty strings just fine (at least the latest version 0.5.1):

```python
>>> import brotli
>>> brotli.decompress(b"")
b''
```

**Comment by Kriechi** [comment]
Ah yes, the problem is with empty __strings__. Empty __byte arrays__ work just fine.
Did you experience this problem somewhere while running mitmproxy, or just by using the mitmproxy/netlib API?

**Comment by Schamper** [comment]
It happened at least once while using it normally (which caused me to investigate). I don't have a URL or anything for you to replicate though, sorry.
