### ISSUE TITLE
Mitmproxy Slogan

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1521]
We need a better project slogan. This should be a short, pithy way of describing what mitmproxy does. The problem is that mitmproxy does so much that it's hard to be specific without rattling off a long list of supported protocols. Let's discuss.

To get things started, one possibility is to keep the slogan very simple:

> mitmproxy: a man-in-the-middle proxy

And then list our protocol support prominently on the webpage, readme, etc:

> Supports HTTP, HTTP2, Websockets and generic TCP connections. Intercepts traffic encrypted 
> with SSLv3, TLS 1.0, TLS 1.1, and TLS 1.2.

**Comment by Kriechi** [comment]
Since HTTP/1.0/1.1/2.0 and WebSockets are the core of the WWW, I'd like to propose:

> mitmproxy: a man-in-the-middle proxy for the world wide web

**Comment by ravidamani** [comment]
With a slogan it is best to be short and focus on the clear differentiator. Everyone will know it does HTTP as well.
MITMProxy - A HTTP2 SSL Proxy

**Comment by slobo** [comment]
mitmproxy: intercept, edit and replay web requests

**Comment by Cojad** [comment]
http(s) traffic debugging and manipulating as you wish.
