### ISSUE TITLE
Please support python-cryptography 1.5

### ISSUE THREAD

**Issue by sdelafond** [mitmproxy/mitmproxy#1527]
The test suite currently fails with that version:

AttributeError: '_cffi_backend.CDataGCP' object has no attribute 'cert_info'

**Comment by Kriechi** [comment]
We merged cryptography 1.5 support just two days ago: #1513

**Comment by sdelafond** [comment]
All right, so I'll just wait for a new tag/release and then I can upload to Debian :)
