### ISSUE TITLE
Handle print() statements for inline scripts

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1530]
print() statements in inline scripts should be suppressed, and produce into ctx.log.warn() calls instead.

**Comment by jgomo3** [comment]
Doing a simple search at github of `print(` a lot of candidates appear. To understand what you propose to do, tell me, Is [this](https://github.com/mitmproxy/mitmproxy/blob/6792cc1de90b02b89da9ae80704ea237c5486e66/mitmproxy/tools/main.py#L6) a good candidate? It is a `print` to `sys.stderr`. And what about [this](https://github.com/mitmproxy/mitmproxy/blob/711078ba3f63257df745bb3edd80a85717e94b20/mitmproxy/utils/version_check.py#L19)? It seems a legit use of print, although it could be write as a file write, given the file object is an argument.

I think a better question I could ask is: Which are those inline scripts?

**Comment by mosajjal** [comment]
If I may, I could add another suggestion/question here. Why not use python's built-in logger instead of print? That way the log level can be changed as well

**Comment by adepasquale** [comment]
How about something like http://stackoverflow.com/questions/19425736/how-to-redirect-stdout-and-stderr-to-logger-in-py :question:

**Comment by mhils** [comment]
I think this issue is about redirecting anything that gets sent to `sys.stdout` to `ctx.log.warn`. This would probably look roughly like to this:

```python
class StreamLog:
    def __init__(self, log: Callable):
        self.log = log
    def write(self, buf):
        self.log(buf)

stdout_replacement = StreamLog(ctx.log.warn)
with contextlib.redirect_stdout(stdout_replacement):
    # invoke addon
```

A possible integration between Python's built-in logger and `ctx.log` is out of scope for this issue.
