### ISSUE TITLE
Construct 2.5.5 changed API

### ISSUE THREAD

**Issue by dwfreed** [mitmproxy/mitmproxy#1533]
Construct 2.5.5 decided to change the `length_field` argument to `lengthfield` which breaks mitmproxy (both release and HEAD):

```pytb
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 7, in <module>
    from mitmproxy.main import mitmproxy
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/main.py", line 7, in <module>
    from . import version, cmdline
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/cmdline.py", line 11, in <module>
    from .proxy import config
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/__init__.py", line 3, in <module>
    from .server import ProxyServer, DummyServer
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/proxy/server.py", line 12, in <module>
    from ..protocol import Kill
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/__init__.py", line 30, in <module>
    from .tls import TlsLayer
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/protocol/tls.py", line 11, in <module>
    from ..contrib.tls._constructs import ClientHello
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/contrib/tls/_constructs.py", line 69, in <module>
    PascalString("name", length_field=UBInt16("length")),
TypeError: __init__() got an unexpected keyword argument 'length_field'
```

I filed construct/construct#92 to get this fixed.  Reported by @jackmiller334 in the IRC channel.

**Comment by arekbulski** [comment]
There are more changes to come. Look at https://github.com/construct/construct/issues/80.

**Comment by mhils** [comment]
@mitmproxy maintainer here. It would be very welcome if you could push a patch release that reverts that change. If you do want to rename it, we would be very grateful if you could do so in a major or minor, but not a patch release!

**Comment by EdwinOtten** [comment]
YFI: this bug exists in the version that's on the _universe_ repository.
I just started using mitmproxy today so I'm not sure if that is common.

**Comment by mhils** [comment]
Edwin, which OS is that?

**Comment by EdwinOtten** [comment]
Ubuntu (16.04). I installed mitmproxy earlier today so the issue might be on my side (not having latest version?).

I tried `pip uninstall mitmproxy` a few seconds ago and then `install` again, not sure if that is sufficient?

**Comment by arekbulski** [comment]
I apologize everyone for the hussle.

**Comment by mhils** [comment]
No problem. Thanks for the super fast fix! :blush:

**Comment by mhils** [comment]
Ubuntu should be fine as well, I don't see anything above 2.5.1 in their repos!

**Comment by yan12125** [comment]
Arch Linux bumps construct to 2.6.2 pre-release, which breaks mitmproxy. ([Arch bug report](https://bugs.archlinux.org/task/50691)) Is there a patch for the new construct API?

**Comment by arekbulski** [comment]
Did I already say I apologize everyone for the hussle? :disappointed:

**Comment by yan12125** [comment]
If I understand it correctly, the API change in construct was accidentally made on 2.5 branch and soon reverted and postponed to the 2.6 branch. Now Arch's python2-construct bumps to 2.6.2, and mitmproxy becomes broken. It's an issue of mitmproxy, not construct, so I'm asking here instead of https://github.com/construct/construct/issues/92. Sorry if I wasn't clear and make you think I'm talking about construct. No, I'm seeking for a patch in mitmproxy.

By the way, if the patch wasn't already there, maybe catching the ```TypeError``` and retrying with the new argument name works?

**Comment by yan12125** [comment]
PS: Just looked into construct/construct#80, thanks for API cleanups in construct!

**Comment by Kriechi** [comment]
@yan12125: I'm not sure how you come to the conclusion that "mitmproxy is broken".
The latest mitmproxy v0.17 depends on `construct>=2.5.2, <2.6` - as specified here: 
https://github.com/mitmproxy/mitmproxy/blob/v0.17.1/setup.py#L67
So, if ArchLinux tries to run mitmproxy 0.17 with construct 2.6.2, this is clearly a packaging problem.

You have to wait until we release a new mitmproxy version which *might* bump the construct dependency. Doing a hot-patch just for ArchLinux is probably not a good idea and certainly makes nobodies live easier.

**Comment by Kriechi** [comment]
@arekbulski no worries! 
Releasing new versions can be tricky with many pitfalls (which we know a few ourself)!

Thanks for responding so quickly and fixing/reverting the API. 👍 
Now we only have to deal with a bit of fallout after the fact. 😉

**Comment by yan12125** [comment]
I see. Will go back to Arch and suggest downgrading the package.

**Comment by mhils** [comment]
@felixonmars: Thanks for fixing the arch package so quickly, your mitmproxy distribution speed totally rocks! :tada:

**Comment by arekbulski** [comment]
Construct just went into beta 2.7.1 having name-less fields. There is around 20 bugs to be fixed and **I could really use some help.**

**Comment by arekbulski** [comment]
Construct 2.8 is out of beta. You should definately check it out, folks. :smile:
