### ISSUE TITLE
proxapp.py from examples does not work

### ISSUE THREAD

**Issue by xrd** [mitmproxy/mitmproxy#1538]
##### Steps to reproduce the problem:

1. Install mitmproxy
2. Run `mitmproxy -s examples/proxyapp.py`
3. See error below:

```bash
$ mitmproxy -s examples/proxyapp.py 
Script load error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/flow.py", line 694, in load_script
    s.load()
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/script/script.py", line 89, in load
    return self.run("start", self.args)
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/script/script.py", line 118, in run
    sys.exc_info()[2]
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/script/script.py", line 113, in run
    return f(self.ctx, *args, **kwargs)
ScriptException: start() takes no arguments (2 given)
```

##### What is the expected behavior?

mitmproxy should start a webserver listening inside the mitmproxy process.

##### What went wrong?

Complains of bad argument error.

##### Any other comments? What have you tried so far?

I can run mitmproxy successfully without the script.

---

Mitmproxy Version: mitmproxy 0.17
Operating System: Ubuntu
Linux 2abe27cac38e 4.4.17-boot2docker #1 SMP Mon Aug 15 17:12:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu:16.04 (Docker image).

**Comment by mhils** [comment]
You are looking at the examples from master, but you are running mitmproxy
0.17. We have a few changes incoming, so if you (1) use the examples from
the 0.17 tag or (2) use mitmproxy from master things should work again. 🙂

**Comment by xrd** [comment]
Doh. Thanks, that worked!
