### ISSUE TITLE
pathod.net index page outdated (says current version is 0.13)

### ISSUE THREAD

**Issue by timmc** [mitmproxy/mitmproxy#1539]
http://pathod.net/ says:

> **source**
> Current release: pathod 0.13
> GitHub: github.com/mitmproxy/pathod

...but pathod is now at least 0.17 and integrated into the mitmproxy repo itself.

I'd submit a PR, but it looks like that page is no longer managed the way I remember.

**Comment by Kriechi** [comment]
ref #1001

**Comment by cortesi** [comment]
I'll redirect the pathod page to mitmproxy when we release 0.18. There's a little bit more work to be done on the pathod docs in mitmproxy before we can do that.

**Comment by Kriechi** [comment]
0.18 was released a couple of days ago. Any update on this?

**Comment by cortesi** [comment]
It's under way - I'm doing a domain transfer as part of this, so we're just waiting for that to propagate.

**Comment by cortesi** [comment]
Finally completed.
