### ISSUE TITLE
WebSocket Messages should be shown to the user.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1547]
##### Steps to reproduce the problem:

1. Run mitmproxy
2. Visit https://www.websocket.org/echo.html
3. Send some messages

##### What is the expected behavior?

The Websocket activity should be reflected in the UI.

##### What went wrong?

There is no UI indication that any activity is ongoing after the initial 101 Upgrade.

##### Any other comments? What have you tried so far?

Similar to our TCP mode, the easiest thing to do for now is just to display messages in the event log. Do we just want to do the same for now in builtins/dumper and console/master for now?

---

Mitmproxy Version: master
Operating System: Win10 x64

**Comment by Kriechi** [comment]
ref #1518

mitmdump already logs frames.
