### ISSUE TITLE
can't import ~/.mitmproxy/mitmproxy-ca-cert.pem to firefox

### ISSUE THREAD

**Issue by dsultanr** [mitmproxy/mitmproxy#156]
I'm trying to import cert in firefox 23.0

doing everything like here: http://mitmproxy.org/doc/certinstall/firefox.html

in section "Click "View Certificates", "Import", and select the certificate file:"
after selecting file mitmproxy-ca-cert.pem nothing happens

file choose dialog disappears and I see list of CA's again, mitmproxy not there

tried also to import into "Your certificates" there - but here I'm choosing .p12 file instead of .pem, dialog asks password and after empty password gives error:

"Failed to decode the file.  Either it is not in PKCS #12 format, has been corrupted, or the password you entered was incorrect."

all this on os x 10.8.4

also tried on windows - same problem

uploaded pem file here https://www.dropbox.com/s/v68aiymbe7voiqm/mitmproxy-ca-cert.pem

what am I doing wrong?

**Comment by hynguyen2610** [comment]
When you visit mitm.it, you will see four symbols for Android, Windows, iOS and * (Other). I can't import the Windows one to Firefox, the solution is using the fourth (* Other), just click it, tick all the checkbox and click OK

**Comment by gerchicov-bp** [comment]
@dsultanr 2017 year - I have the same issue. How to solve it? mitmproxy installed via `brew`

**Comment by ujjwal96** [comment]
@gerchicov-bp Did you try clicking the "Other" option?

**Comment by gerchicov-bp** [comment]
@ujjwal96 the problem is need to install .p12. How if it requires password and you don't write it anywhere?

**Comment by lzj78** [comment]
@gerchicov-bp I had the same problem today. And I solved it by choosing the .pem file from the "...Users\<Username>\.mitmproxy" folder in the firefox Authorities-Tab. After that I had a mitmproxy entry in the Authorities list and HTTPS connections worked.

**Comment by gerchicov-bp** [comment]
@lzj78 First of all my goal is mobile safari, not firefox. But .p12 requires password even on mac.

I chose all .pem files from this directory (via browser on device) so I hadn't to install .p12 file and the last .pem file (but as I understand I don't need it). Result - safari requests approval for website's certificate in 50% cases and denies access to website at all in other 50% cases. So I didn't even try the requests in my own app.

And finally mitmproxy generates these files including .p12 but doesn't post a password or doesn't say how to get it (if it is pc-dependent). WTF?

**Comment by JoelPagliuca** [comment]
Hey, I'm getting same behaviour described by the original post, no error message from Firefox though.

MacOS 10.13 Firefox 60.02

the proxy works on Chrome/Chrome on Android
