### ISSUE TITLE
Reverse-proxy should create cert for requested host name

### ISSUE THREAD

**Issue by sabberworm** [mitmproxy/mitmproxy#1560]
##### Steps to reproduce the problem:

1. Run `mitmdump -R http://host1.example.com -p 8080`
2. Edit `/etc/hosts` to let `host2.example.com` point to the host/interface running mitmdump, e.g. `127.0.0.1`
3. Connect to `https://host2.example.com:8080` using a browser that has the mitmproxy root CA installed

##### What is the expected behavior?

`mitmdump` should create a certificate for the SNI host that the client requested, `host2.example.com`.

##### What went wrong?

`mitmdump` sends a certificate that is valid for the configured upstream host name, `host1.example.com`.

##### Any other comments? What have you tried so far?

This behaviour change could also be implemented behind a command-line option to not break existing workflows.

---

Mitmproxy Version: `mitmdump 0.17`
Operating System: `alpine:3.4` docker image

**Comment by mhils** [comment]
Thanks for the detailed report. We actually add the SNI host as `subjectAlternativeName`:
```
λ mitmdump -R http://example.com
λ curl https://localhost:8080 --cacert ~/.mitmproxy/mitmproxy-ca-cert.cer  -vv
* Rebuilt URL to: https://localhost:8080/
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* successfully set certificate verify locations:
*   CAfile: /root/.mitmproxy/mitmproxy-ca-cert.cer
  CApath: /etc/ssl/certs
* SSLv3, TLS Unknown, Unknown (22):
* SSLv3, TLS handshake, Client hello (1):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Server hello (2):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, CERT (11):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Server finished (14):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv2, Unknown (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Finished (20):
* SSLv2, Unknown (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv2, Unknown (22):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=example.com
*        start date: 2016-09-20 02:32:22 GMT
*        expire date: 2019-09-22 02:32:22 GMT
*        subjectAltName: localhost matched
*        issuer: CN=mitmproxy; O=mitmproxy
*        SSL certificate verify ok.
```

Are there cases where that is not enough?

**Comment by sabberworm** [comment]
Oh, I didn’t realize that. I did not inspect the certificate closely and simply looked at the subject name. I was actually starting to dig through the code yesterday so I would have figured it out eventually…
