### ISSUE TITLE
Identify Pushed H2-Flows

### ISSUE THREAD

**Issue by worenga** [mitmproxy/mitmproxy#1561]
In previous versions, one could identify pushed flows by checking for the custom `x-mitmproxy-pushed` header 

However, in https://github.com/mitmproxy/mitmproxy/commit/1c4e1e049cbe5357b1f0191c616ea92e09c5e36b it was removed. Is there a way to classify in a script whether or not a flow has been pushed by the server?

**Comment by Kriechi** [comment]
The reasoning behind removing this header was, that we wanted to make as little changes as possible to the data sent through the proxy. Adding a new header just for identifying pushed streams seemed to big of a change to us.

I think the best way it to add a new hook when we receive a pushed stream on the proxy, before we forward the pushed stream to the client. 
A different approach would be to create a new flag for a flow or request, which indicates the same property.

Feel free to propose new ideas or even submit a PR! 😄

**Comment by mhils** [comment]
This seems to be a relatively important flow property we should indicate somehow. I see a couple of ways to accomplish that:

1. HTTP Header as before. 
2. Like 1, but remove the header right before sending the flow to the client and then re-add it.
3. Subclass HTTPFlow to HTTP2Flow, which has an added pushed attribute. Do we have other HTTP2-specific stuff that would justify this?
4. Add unstructured "metadata" attribute to flows. I personally dislike that one.

Irrespective of that, having a separate hook that gets triggered once we receive a push promise sounds smart. What's the event order right now? I assume they all get triggered once we receive the actual request from the client?

**Comment by Kriechi** [comment]
As mentioned I don't like 1. and 2.
About 3.: Right now I can't think of anything else that might be interesting to put into a HTTP2Flow.
About 4.: Yeah - same here. But wasn't this on the table a while ago during the refactoring of scripts/addons?

**Comment by Kriechi** [comment]
fixed by #1686
