### ISSUE TITLE
Publish mitmproxy 0.17.1 on pypi for Python3

### ISSUE THREAD

**Issue by migueleliasweb** [mitmproxy/mitmproxy#1569]
After a lot o struggle running ```'pip install mitmproxy```` I discovered that the version from pip is outdated (somehow) on python3.

A quick check was:

````
$ python --version
Python 3.4.3
$ pip install mitmproxy==
Collecting mitmproxy==
  Could not find a version that satisfies the requirement mitmproxy== (from versions: 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.10, 0.10.1, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13, 0.14.0, 0.15)
No matching distribution found for mitmproxy==
````

Another check, this time for python2.7:

````
$ python --version
Python 2.7.11
$ pip install mitmproxy==9999
Collecting mitmproxy==9999
  Could not find a version that satisfies the requirement mitmproxy==9999 (from versions: 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.10, 0.10.1, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13, 0.14.0, 0.15, 0.16, 0.17)
No matching distribution found for mitmproxy==9999
```

Can you update the version on pypi for python3 ?

Ps: For now i'm developing with ````pip install git+https://github.com/mitmproxy/mitmproxy.git@v0.17.1```

**Comment by Kriechi** [comment]
Unfortunately mitmproxy 0.17.1 is not supported on Python 3.
So publishing 0.17.1 for Python 3 on pypi will not help anybody.

We are working hard to make mitmproxy work with Python 3.5 - and have a mostly working code base on git-master at the moment. The next release is planned to officially support Python 2.7 and 3.5.

**Comment by migueleliasweb** [comment]
Well...i didn't know that.

It's ok. Ill wait anxiously for the new release. =]

**Comment by mhils** [comment]
You are more than welcome to test the current master branch on Python 3, we're relatively close to a release. :)
