### ISSUE TITLE
Upgrade Construct Dependency

### ISSUE THREAD

**Issue by arekbulski** [mitmproxy/mitmproxy#1570]
I thought that I would let you know. 2.8 is out of beta and there are **significant** changes. First of all, fields are name-less and the `"name" / Bytes(2)` syntax is used. Secondly, pretty much EVERY class redesigned so nothing works exactly as it used to. (It works better.) I wanted to know if you are going to transition, if and how.

In 2.10 there will be cython depenedncy. All you will need to do is `sudo apt-get install python{,3}-cython` but that is just a heads up on my part. 

Please voice any concerns openly.

**Comment by arekbulski** [comment]
Forgot to add, I will be writing a regex tool in foreseeable future that more or less translates to new syntax. I will write a short but expressive tutorial on how to translate manually. I could use some help doing the regex expressions tho, I dont speek regex any better than l33t.

**Comment by mhils** [comment]
Thanks for the heads up!
Do you expect any more API changes in the near future? I think we're happy to migrate (after the next mitmproxy release) to any version that is directly pip-installable and has a sufficiently stable API.

Speaking about migration, is that as simple as transitioning to the `/` syntax or are there more complex changes involved?

**Comment by arekbulski** [comment]
Well, the API is not set in stone just yet. Right now there 1 tiny pending change. But I think we are close to achieving that.

I will put out a concise tutorial on how to transition but it will take a whole god made day to write it. It will be posted in this tread when it is out, probabl in few days.

**Comment by arekbulski** [comment]
**BETA NOTICE:**  Tutorial is almost done, only tunneling is missing. For those interested, you can take a look at http://construct.readthedocs.io/en/latest/transition.html

**Comment by arekbulski** [comment]
@mhils After few days, it looks like the API changes are still ongoing. Nothing major like purging the names but few classes were added or some semantics changed. I think it would be a good idea to wait a bit before moving such a huge project. Changes are small but easier to just wait.

**Comment by arekbulski** [comment]
@mhils Could you tell me when you are about to start the transition? And in case it wasnt obvious, you can always post questions in Issues section. I expect many people to be at least a bit confused by all the changes that I introduced in 2.8 so just post when you encounter a problem.

**Comment by arekbulski** [comment]
I think the Construct API is stable enough from now on. If anything breaks on your side, just post it immediately. Tutorial is at http://construct.readthedocs.io/en/latest/transition.html

**Comment by Kriechi** [comment]
I'm giving this a try - however I'm running into problems with TunnelAdapter.
@arekbulski how would this part look like with the new API?

https://github.com/mitmproxy/mitmproxy/blob/741c2b7b66cbfb60cdf466063cdba3972b2ce2ee/mitmproxy/contrib/tls/_constructs.py#L71-L91
https://github.com/mitmproxy/mitmproxy/blob/741c2b7b66cbfb60cdf466063cdba3972b2ce2ee/mitmproxy/contrib/tls/_constructs.py#L113-L116

You can find my current (non-working) work here:
http://github.com/Kriechi/mitmproxy/blob/ee054fc326cabc39f36e421a29229f3d83e64a3a/mitmproxy/contrib/tls/_constructs.py

**Comment by arekbulski** [comment]
What is it supposed to do? Tunnels are now mainly used for compression. I dont think this was the usage intended?

**Comment by Kriechi** [comment]
We are trying to parse TLS handshake data. The problem at the moment is trying to parse TLS extensions [see RFC here](https://tools.ietf.org/html/rfc5246#section-7.4.1.4):

```
      struct {
          ExtensionType extension_type;
          opaque extension_data<0..2^16-1>;
      } Extension;

      enum {
          signature_algorithms(13), (65535)
      } ExtensionType;
```

And the ALPN extension [see RFC here](https://tools.ietf.org/html/rfc7301#section-3.1)
```
   enum {
       application_layer_protocol_negotiation(16), (65535)
   } ExtensionType;

   The "extension_data" field of the
   ("application_layer_protocol_negotiation(16)") extension SHALL
   contain a "ProtocolNameList" value.

   opaque ProtocolName<1..2^8-1>;

   struct {
       ProtocolName protocol_name_list<2..2^16-1>
   } ProtocolNameList;
```

And the SNI extension [see RFC here](https://tools.ietf.org/html/rfc6066#section-3):
```
       struct {
          NameType name_type;
          select (name_type) {
              case host_name: HostName;
          } name;
      } ServerName;

      enum {
          host_name(0), (255)
      } NameType;

      opaque HostName<1..2^16-1>;

      struct {
          ServerName server_name_list<1..2^16-1>
      } ServerNameList;
```

**Comment by arekbulski** [comment]
I dont know this syntax (too busy atm to read into it). Right now it seems to me that this is plain and simple structs and ints and strings? SNI seems to have a switch?

**Comment by mhils** [comment]
Let me try to translate: I think @Kriechi is asking how we can implement length-prefixed sequences. More specifically, TLS has extensions which are sent as follows:

```
[length-of-all-extensions][extension1][extension2][other (non-extension) data]
```
How can we translate [this](https://github.com/mitmproxy/mitmproxy/blob/741c2b7b66cbfb60cdf466063cdba3972b2ce2ee/mitmproxy/contrib/tls/_constructs.py#L113-L116) to construct 2.8.x?

**Comment by arekbulski** [comment]
Use a `Prefixed` and `OpenRange` inside it?
http://construct.readthedocs.io/en/latest/tunneling.html#working-with-bytes-subsets
