### ISSUE TITLE
Provide a better error message for proxy mode misconfigurations

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1580]
##### Steps to reproduce the problem:
1. `mitmproxy -T`
2. `curl -x localhost:8080 example.com`
##### What is the expected behavior?

mitmproxy should provide a warning that you want to run either transparent mode or configure an explicit proxy.
##### What went wrong?

mitmproxy complains about "Invalid HTTP request form (expected: relative, got: authority)"
##### Any other comments? What have you tried so far?

We should just detect this very specific case (expected: relative, got: authority) and provide a better error message for it.

See #1579 for a confused user. :stuck_out_tongue:

---

Mitmproxy Version: master
Operating System: Ubuntu 16.04

**Comment by wchill** [comment]
Seems like one just needs to throw in another "if" check and raise with a more appropriate exception? If so, I can take care of this.

**Comment by kalyan-kumar** [comment]
I would like to work on this issue.
