### ISSUE TITLE
Issue w/ trusted SSL intermediate certs in Safari

### ISSUE THREAD

**Issue by rofreg** [mitmproxy/mitmproxy#1585]
##### Steps to reproduce the problem:

1. Get a trusted SSL certificate issued by Comodo (let's say it's for `www.rofreg.com`), and convert it into a .pem file that includes all intermediate certs
2. Update your `/etc/hosts` file to redirect `www.rofreg.com` to `127.0.0.1`
3. Run `mitmproxy --cert=your_cert.pem -R https://www.example.com`
4. Open `https://localhost:8080` in Safari

##### What is the expected behavior?

The page should load without any SSL issues.

##### What went wrong?

Safari does not trust the intermediate certificates, and the request is blocked.

##### Any other comments? What have you tried so far?

This one is baffling me pretty good, but I've confirmed that the exact same .pem file DOES work in Safari when served up by a plain Rails server. My hunch is that something is going wrong with the intermediate certs in the .pem file, such that they don't get properly delivered during the handshake, but I'm not yet familiar enough with mitmproxy to know where I should start looking. Any thoughts? I'd be happy to dig into this further myself (especially since I have a valid .pem file that can reproduce the problem), just hoping for some guidance :)

---

Mitmproxy Version: 0.18
Operating System: OS X 10.11.6

**Comment by mhils** [comment]
Potentially stupid question, but did you put the intermediary certs at the end of the PEM file?

(See: http://docs.mitmproxy.org/en/stable/certinstall.html#using-a-custom-certificate)

**Comment by rofreg** [comment]
Yep! Private key first, followed by `www.rofreg.com` cert, followed by intermediate certs in ascending order (e.g. from leaf to root).

**Comment by mhils** [comment]
Ok, not sure why this is happening then, sorry.
I would try and set [SSLKEYLOGFILE](http://docs.mitmproxy.org/en/stable/dev/sslkeylogfile.html), capture the traffic with WireShark and see what mitmproxy actually sends. We don't do much besides calling pyOpenSSL's [use_certificate_chain_file](https://github.com/mitmproxy/mitmproxy/blob/d068000f16cb44b7277de04ba20bd1fc62e4a956/netlib/tcp.py#L826).

**Comment by rofreg** [comment]
Cool – thanks for the tips! Hopefully that'll help me dig into this further over the next few days. I'll let you know if I find anything!

**Comment by mhils** [comment]
You're welcome - feel free to drop by on Slack if you have any ad hoc questions!

**Comment by rofreg** [comment]
Aha, made some progress! 

Wireshark confirmed that mitmproxy is actually returning a *different* intermediate certificate than the one specified in the .pem file. After doing some more investigation, it looks like this may be a conflict between the two different calls to `load_verify_locations` made on lines [544](https://github.com/mitmproxy/mitmproxy/blob/d068000f16cb44b7277de04ba20bd1fc62e4a956/netlib/tcp.py#L544) and [845](https://github.com/mitmproxy/mitmproxy/blob/d068000f16cb44b7277de04ba20bd1fc62e4a956/netlib/tcp.py#L845). If you comment out line 544 (and temporarily overwrite the function on line 529 to always return `True`), then the SSL handshake goes through successfully without any SSL errors.

I'm about to head to bed, but I'll look into this more in the coming days. My guess is that the default intermediate certs loaded on line 544 are effectively overriding the manually-specified cert in my .pem file, and thus mitmproxy ends up returning a combination of certs that is invalid against the default OS X keychain.

**Comment by mhils** [comment]
Fixed by #1590 - thanks again!
