### ISSUE TITLE
Organize Examples

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1586]
##### Steps to reproduce the problem:
1. Visit https://github.com/mitmproxy/mitmproxy/tree/master/examples for the first time. 
2. Be overwhelmed. (@mitmproxy/devs may not be able to reproduce this)
##### What went wrong?

Our examples directory has grown organically and I feel there are too many too complex examples in there that scare users away. It's not really clear where to start.
##### What is the expected behavior?

We should guide users to the simpler, more frequently used examples like add_header.py, filt.py, modify_response_body.py or redirect_requests.py and hide the more complex ones.
##### Any other comments? What have you tried so far?

I would propose to split the examples folder into "beginner" and "complex" and (after this, in a second PR) add a README in the examples folder that guides the user. The beginner examples don't have to be trivial, but they should have a high usefulness/complexity ratio.

I'd be more than happy if a new contributor wants to pick that up and let us know which examples are helpful for mitmproxy beginners and which aren't! :smiley:

**Comment by thiagoarrais** [comment]
I'm interested in taking a look at this. I'm just starting. Anyone else here?

**Comment by l33tLumberjack** [comment]
I would be willing to lend a hand. I think the first thing we can do is rebuild this readme.md right now it kind of sucks.

**Comment by thiagoarrais** [comment]
Yeah... And maybe split a README for each folder that @mhils suggested...

**Comment by thiagoarrais** [comment]
I've also noticed that not all examples are covered in the current `README`. It would be nice to have a simple description for each one. On the other hand, I've also noticed that some files seem to have been created for reference by the docs. Maybe this makes the descriptions unnecessary....

**Comment by l33tLumberjack** [comment]
I noticed that too and am working on the project in my fork now

**Comment by mhils** [comment]
Hey guys, 

Thanks for picking this up! 😃 If you want to coordinate, you are more than welcome to join us on Slack and discuss things there. Other than that, the only advice I can give is to make the PRs as small as possible. 😉

**Comment by l33tLumberjack** [comment]
Made pull request #1600 to submit my contributions to the codebase

**Comment by thiagoarrais** [comment]
That is nice. I'll make a PR that fixes the references in `docs` tomorrow.

If you don't beat me to it, of course.

:-D

**Comment by l33tLumberjack** [comment]
By all means take care of that one.

**Comment by thiagoarrais** [comment]
Did it!

**Comment by arekbulski** [comment]
I looked at upsidedownintenet and got overwhelemed, by its simplicity that is.
