### ISSUE TITLE
View TLS version in Details

### ISSUE THREAD

**Issue by fiery-** [mitmproxy/mitmproxy#1589]
Is there any way to view TLS version in the Details tab? 

I use mitmproxy 0.17.1 and Details tab shows certificate info and TLS timings, but not TLS version. Many sites enforce TLS 1.2 (or 1.1) and finding which version is in use is essential for debugging.

I'm not sure if that is possible, but if client -> proxy connection uses one TLS version and proxy -> server another, please add both versions in Details tab. BTW, this would be a very helpful feature if older clients (i.e. TLS 1.0) are able to connect to newer servers (TLS 1.2).

Thanks,

**Comment by mhils** [comment]
Thanks for the feedback! This sounds like a useful feature to have.

This is so closely related to #582 that I'll just close this issue here and merge it into the other one if you don't mind. :smiley:
