### ISSUE TITLE
HTTP2 issue with Amazon Cloudfront

### ISSUE THREAD

**Issue by ravidamani** [mitmproxy/mitmproxy#1595]
Amazon Cloudfront has recently added HTTP2 support. Sorry, if this isn't an issue with mitmproxy and is with Amazon Cloudfront.

##### Steps to reproduce the problem:

1. Make a request to https://s.yo.tv/v2/WCF/uk.svc/GS2?sT=201609240013&nNs=1&s=k9Ia4cM790llrCuBshmvDQ==&t=n&sL=1535&a=a.js
2. Works directly in Android app with HTTP 1.1 and HTTP 2. Works with HTTP 1.1 using mitmproxy but fails with HTTP 2.
3. Cloudfront returns error - The request could not be satisfied

We've tried multiple URLs that also use Cloudfront and get the same error. 

---

Mitmproxy Version:0.17.1
Operating System: MacOX

**Comment by cortesi** [comment]
Hi there. I've confirmed that the URL above works with the current master and Firefox as a client. There may be some difference in your setup, so could you please test with the current master? Alternatively, you can wait a few days until we release 0.18.

**Comment by ravidamani** [comment]
Thank you for the fast response. We did a build from source and it fixed the issue. Great work!
