### ISSUE TITLE
Interception does not work

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1605]
##### Steps to reproduce the problem:

1. `mitmproxy -i '.*'`
2. `curl -x localhost:8080 example.com`

##### What is the expected behavior?

Request should be intercepted

##### What went wrong?

Request is not intercepted.

##### Any other comments? What have you tried so far?

https://discourse.mitmproxy.org/t/is-intercept-working-in-the-head-of-master/186

---

Mitmproxy Version: master
Operating System: Win10 x64

**Comment by akhilakamai** [comment]
I am facing the same issue, some of the requests from my device are not being intercepted by mitm ( or maybe it's intercepting it but not being displayed
