### ISSUE TITLE
Log could not be imported (cyclic?) 

### ISSUE THREAD

**Issue by mkagenius** [mitmproxy/mitmproxy#1611]
In the file, 
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/protocol/http_replay.py

line 101 & 104 (two places)
```python

from ..proxy.root_context import Log
self.channel.tell("log", Log("Connection killed", "info"))
```

but this should be controller.Log, i guess, and no need to import anything

---

Mitmproxy Version: master, head
Operating System: mac

**Comment by mhils** [comment]
Fantastic find, thanks! :smiley:
