### ISSUE TITLE
flowbasic exaple doesn't work

### ISSUE THREAD

**Issue by jsnjack** [mitmproxy/mitmproxy#1612]
##### Steps to reproduce the problem:

1. Run https://github.com/mitmproxy/mitmproxy/blob/master/examples/flowbasic example

##### What is the expected behaviour?
Working example

##### What went wrong?
```
    from mitmproxy import flow, controller, options
ImportError: cannot import name options
```

##### Any other comments? What have you tried so far?

---

Mitmproxy Version: 0.17
Operating System: Fedora 24

**Comment by mhils** [comment]
Hi!

It looks like your inline script is from master, but you are using the latest stable release from mitmproxy. Can you please select the right tag on GitHub and try again?

![image](https://cloud.githubusercontent.com/assets/1019198/17031301/2bcfd91c-4f28-11e6-85f9-1f9a0e7832e2.png)

**Comment by jsnjack** [comment]
@mhils thanks! my bad :blush:
