### ISSUE TITLE
Better control of long output in mitmdump

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1623]
Comments re #1621. Being able to see the full URL in the terminal is too valuable to lose entirely. A better version of this would:

• Add a command-line flag to turn on full-width output (a la ``ps --ww`).
• Use the terminal width to determine the cutoff. See `click.get_terminal_size()`. 
• Maybe make the cutoff marker clearer by making it a different colour.

**Comment by mhils** [comment]
> Add a command-line flag to turn on full-width output

Would you like to have a separate switch for that or shall we just make `-d` do that as well? I'm not sure if a dedicated switch would be relevant to a large enough share of users to justify it. I'm not particularly strong on this though.

**Comment by cortesi** [comment]
I don't mind, as long as there's a knob for this.  We already have a bit of a case of flag-itis, so just using -d might be the way to go.  Showing full URLs could be detail level #1.

**Comment by kalyan-kumar** [comment]
Shouldn't this issue be closed now?

**Comment by mhils** [comment]
yes, thanks!
