### ISSUE TITLE
any way to improve the proxy performance?

### ISSUE THREAD

**Issue by yuankui** [mitmproxy/mitmproxy#1643]
##### Steps to reproduce the problem:
1. proxy with mitmproxy with http/socks5
2. set the proxy in chrome
3. response is very slow
4. proxy with charles
5. set the proxy in chrome
6. response is very fast
##### What is the expected behavior?

expect the mitmproxy works almost the same proxy speed, at least now so much slower than charles
##### What went wrong?

when use mitmproxy, web pages took much more time to complete all the requests
##### Any other comments? What have you tried so far?

---

Mitmproxy Version: mitmproxy 0.18.1
Operating System: OS X 10.11.6 (15G1004)

**Comment by Kriechi** [comment]
Hi,

thanks for your report. A couple of questions to get this rolling:
Do you have any numbers or measurements to define "much more time" and "very fast"?
What is your setup, how many users or connections do you want to handle?

Did you use streaming? The default setting is to buffer the complete response in the proxy before sending it to the client. Maybe this might speed things up for you?

**Comment by acheshkov** [comment]
i have a website consisting of about 100 JS files. i use scripting method to load the files from localhost. 
And this scheme work so slow that it impossible to use :(
