### ISSUE TITLE
OSX: core dump on exit

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1645]
##### Steps to reproduce the problem:
1. Run mitmproxy console
2. Muck about with some flows - it's not clear if there's a specific triggering action
3. Exit mitmproxy
4. Observe that core has been dumped with the following error:

`illegal hardware instruction (core dumped)  mitmproxy`

The backtrace shows:

```
* thread #1: tid = 0x0000, 0x0000000110402f60, stop reason = signal SIGSTOP
  * frame #0: 0x0000000110402f60
    frame #1: 0x00000001101fa5a2 _openssl.abi3.so`SSL_free + 49
    frame #2: 0x000000011024b79a _openssl.abi3.so`_cffi_f_SSL_free + 138
    frame #3: 0x000000010f077065 .Python`PyCFunction_Call + 276
    frame #4: 0x000000010f03ed46 .Python`PyObject_Call + 101
    frame #5: 0x000000010f03be65 .Python`PyObject_CallFunctionObjArgs + 190
    frame #6: 0x00000001103e7d56 _cffi_backend.cpython-35m-darwin.so`gcp_finalize + 54
    frame #7: 0x000000010f06eda8 .Python`dict_dealloc + 120
    frame #8: 0x000000010f0847c7 .Python`subtype_dealloc + 662
    frame #9: 0x000000010f06eda8 .Python`dict_dealloc + 120
    frame #10: 0x000000010f0847c7 .Python`subtype_dealloc + 662
    frame #11: 0x000000010f06eda8 .Python`dict_dealloc + 120
    frame #12: 0x000000010f08ced3 .Python`subtype_clear + 145
    frame #13: 0x000000010f10e1eb .Python`collect + 1855
    frame #14: 0x000000010f10daa3 .Python`_PyGC_CollectNoFail + 43
    frame #15: 0x000000010f0edb90 .Python`PyImport_Cleanup + 982
    frame #16: 0x000000010f0f784c .Python`Py_Finalize + 98
    frame #17: 0x000000010f0f7dd7 .Python`Py_Exit + 13
    frame #18: 0x000000010f0fa34a .Python`handle_system_exit + 318
    frame #19: 0x000000010f0f9fc0 .Python`PyErr_PrintEx + 41
    frame #20: 0x000000010f0f9659 .Python`PyRun_SimpleFileExFlags + 908
    frame #21: 0x000000010f10d36d .Python`Py_Main + 3301
    frame #22: 0x000000010f030e3f python3.5`___lldb_unnamed_function1$$python3.5 + 224
    frame #23: 0x00007fffb9297255 libdyld.dylib`start + 1
```

---

Mitmproxy version: 0.19
Python version: 3.5.1
Platform: Darwin-16.0.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12 ('', '', '') x86_64

**Comment by cortesi** [comment]
Appears to be related to #1535. @Kriechi - I see on that issue you mention reporting this upstream on IRC. Did you end up getting results?

**Comment by Kriechi** [comment]
Unfortunately no results.
But I think this problems most definitely comes from an open (dangling?) socket that is being garbage collected / removed, instead of cleaned up the nice way.

**Comment by cortesi** [comment]
Yes, I agree. It's nevertheless a problem that cryptography crashes here, and it would benefit us if it was more reliable. Would you mind lodging an upstream ticket anyway so we can track this? I'll put looking at our termination to see if we can clean things up better on my todo list.

**Comment by mhils** [comment]
Somewhat related: I recently learned about https://docs.python.org/3/library/faulthandler.html - it feels like it would be useful to have that enabled by default in mitmproxy?

**Comment by Kriechi** [comment]
Should be fixed by latest cryptography release.
