### ISSUE TITLE
README is not rendered properly on PyPI

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1651]
#### Steps to reproduce the problem:

1. Open https://pypi.python.org/pypi/mitmproxy
2. Notice that README is broken.

#### Any other comments? What have you tried so far?

PyPI is super restrictive about restructuredText, we probably have some validation errors. Might make sense to have that checked on CI if possible without too much effort.

**Comment by RitwikGupta** [comment]
With this commit, the README passes a reST validator.
