### ISSUE TITLE
Replace mitmproxy.utils.lrucache with functools.lru_cache

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1652]
We have a custom Least Recently Used Cache implementation in mitmproxy, because `functools.lru_cache` did not exist before Python 3.2. It's time to just take that out and replace it with `functools.lru_cache`. The API is quite similar, so that should not be too hard to do and a good beginner task! :smiley:

**Comment by SahilC** [comment]
Hey, I'm working on a PR for this. I had a small doubt. Do you know whom I can talk to?

**Comment by mhils** [comment]
Feel free to just ask here or ping any of us on Slack! :)

**Comment by Kriechi** [comment]
fixed by #1663
