### ISSUE TITLE
Remove lxml dependency

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1657]
Installing lxml is more or less painful on all the platforms we support. In particular, I tried for months to get the lxml maintainers to provide wheels for Windows, but to no avail. 
We only use lxml for indenting the XML/HTML content views [here](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/contentviews.py). It would be interesting to see if we can just replace that with a more naive implementation that does indentation, so that we don't have to carry lxml with us.

As an additional benefit, doing this in Python instead of C should make the whole thing considerably safer.

refs #845

**Comment by jpmllr89** [comment]
Could you just use the xml package instead?
Sorry if this is a stupid question.  I'm a novice at this.

**Comment by mike820324** [comment]
As for the html document, I think [html5lib](https://github.com/html5lib/html5lib-python) would be a nice alternative. It's a pure python implementation.

**Comment by mhils** [comment]
Which package are you talking about? I'm open for any solution, as long as
it fulfills two requirements:

- Easier to install than lxml
- Reasonably fast (that's where BeautifulSoup fails)

**Comment by jpmllr89** [comment]
Gotcha.
I'm going to try to give it a shot.

**Comment by cortesi** [comment]
A few things to keep in mind here:

- We really only need indentation for the HTML viewer, so full parsing of the document might not be necessary.
- At the moment, if a large HTML page is viewed with the HTML viewer, mitmproxy hangs for a bit, even with lxml. If we're re-assessing the HTML parser improving this is a key goal, and we certainly shouldn't go to a solution that worsens things (as I expect html5lib to do). One plan we have is to make viewers smarter by allowing them to progressively calculate representation data. It's easy to imagine a "progressive indenter" for HTML that only parses as far as it must, and keeps state so it can resume if later portions of the file are requested. We'd probably have to write this by hand - I'm not sure if there's pre-rolled implementation that does this out there. See the discussion in #1662 for some further context.

**Comment by Kriechi** [comment]
What about the builtin xml? http://stackoverflow.com/a/6480796

**Comment by Kriechi** [comment]
html5print also looks interesting: https://github.com/berniey/html5print#python-api

**Comment by dufferzafar** [comment]
@Kriechi html5print actually uses Beautiful Soup to do the [heavy-lifting](https://github.com/berniey/html5print/blob/master/html5print/html5print.py#L108-L109).

**Comment by MatthewShao** [comment]
I found a link which did a comparison on  [Python HTML Parsers Performance](http://www.ianbicking.org/blog/2008/03/python-html-parser-performance.html) , but it seems that some graphs on the origin post has missed, so I found another in [Chinese translation](http://simple-is-better.com/news/406), you could see the graphs there.
Hope this helps.
