### ISSUE TITLE
Regular expressions are not working from the command line, and when loaded from a file.

### ISSUE THREAD

**Issue by cyan1de** [mitmproxy/mitmproxy#1658]
First thing is very simple, when im using mitmproxy, command like:`mitmproxy -T —port 8081 —replace :~s:content:replace` is not working.I replaced the word "content",restarted mitmproxy many times, but nothing has changed.

Second thing.
When im using option --replace-from-file with regex `<script((?!<script).|\n)*?to\x3A.*?\x22(.*?)\x22(.|\n)*?new\s(.|\n)*?</script>` websites that use http protocol do not work.
And some https websites to...when im trying to access to yandex.ru for example.
But in this case,i do not have redirect to https://yandex.ru/ 
When I delete a regular expression, it works.

Mitmproxy version: 0.18.1
Python version: 3.5.2
Platform: Linux-2.6.32-642.3.1.el6.x86_64-x86_64-with-centos-6.8-Final
SSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
Linux distro: CentOS 6.8 Final

**Comment by mhils** [comment]
The following works just fine for me (in transparent mode as well):
```
λ mitmdump --replace :~s:Example:Mitm
λ curl -x localhost:8080 example.com | grep Mitm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1264  100  1264    0     0  17653      0 --:--:-- --:--:-- --:--:-- 17802
    <title>Mitm Domain</title>
    <h1>Mitm Domain</h1>
```

Can you provide a similarly simple example exhibiting the issue you are seeing?
