### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cadir

### ISSUE THREAD

**Issue by t4mo** [mitmproxy/mitmproxy#1665]
##### Steps to reproduce the problem:

I was using the python development agent to make an error.

pip install mimtproxy
1. 
from mitmproxy import flow, proxy
from mitmproxy.proxy.server import ProxyServer
**
 config = proxy.ProxyConfig(
        port=8080,
        # use ~/.mitmproxy/mitmproxy-ca.pem as default CA file.
        cadir="./ssl/",
    )
    state = flow.State()
    server = ProxyServer(config)
    m = MyMaster(server, state)
    m.run()
2. python  test.py
3. Remind：
    cadir="./ssl/",
TypeError: **init**() got an unexpected keyword argument 'cadir'
##### System information

python2.7
centos6.5
mitmproxy 0.1.8

**Comment by aipengjie** [comment]
I has same problem, how to slove it?

**Comment by mhils** [comment]
Hi!

It looks like your inline script is from master, but you are using the latest stable release from mitmproxy. Can you please select the right tag on GitHub and try again?

![image](https://cloud.githubusercontent.com/assets/1019198/17031301/2bcfd91c-4f28-11e6-85f9-1f9a0e7832e2.png)

Other than that, you probably want to use our scripting interface and not subclass from FlowMaster.
