### ISSUE TITLE
You broken my plugin by change `def request(context, flow):` =(

### ISSUE THREAD

**Issue by mindcat** [mitmproxy/mitmproxy#1672]
Where is the def request(**context,** flow):

**Comment by mhils** [comment]
We simplified the API with 0.18 - sorry about that. What do you need the context for?

**Comment by mindcat** [comment]
@mhils 
I am using that:
context.log
context.duplicate_flow
context.replay_request
context._master.replay_request

**Comment by mindcat** [comment]
context.duplicate_flow the duplicated flow it can't replays, so I wrote that
```
flow = context.duplicate_flow(flow);
context._master.replay_request(flow)
```

**Comment by mhils** [comment]
Here's the new syntax:
```python
from mitmproxy import ctx

ctx.log("foo")
ctx.master.duplicate_flow(...)
```

**Comment by mindcat** [comment]
Thanks, I will try that =D

**Comment by mindcat** [comment]
@mhils Oops, where is "context.kill_flow"?

**Comment by mhils** [comment]
`flow.kill(ctx.master)` 😉

**Comment by mindcat** [comment]
#1678 Its completed broken my plugin that what I was wrote by Python 2 and this =X
@mhils
