### ISSUE TITLE
Move interception into separate addon

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1674]
The logic for when we intercept and the corresponding option are currently duplicated between console and web:

[mitmproxy/tools/web/master.py#L181](https://github.com/mitmproxy/mitmproxy/blob/eda1b39a744ebfddfc6d3b7b87fb957d936f7f2b/mitmproxy/tools/web/master.py#L181)
[mitmproxy/tools/console/master.py#L662](https://github.com/mitmproxy/mitmproxy/blob/eda1b39a744ebfddfc6d3b7b87fb957d936f7f2b/mitmproxy/tools/console/master.py#L662)

**Comment by cortesi** [comment]
The interception functionality should be part of ``addons.State``.

**Comment by cortesi** [comment]
Update - I'm in the process of killing addons.State and replacing it with addons.View. In this new scheme, it _does_ make sense for intercept-on-match-pattern to be a simple addon of its own.
