### ISSUE TITLE
/examples/nonblocking.py is broken.

### ISSUE THREAD

**Issue by mindcat** [mitmproxy/mitmproxy#1678]
##### Steps to reproduce the problem:

1. Load the /examples/nonblocking.py script
2. access though mitmproxy, view some web pages.
3. press E to see errors

##### System information
```
╭─mindcat@mindcat-linux-pc /tmp  
╰─➤  mitmdump --sysinfo
Mitmproxy version: 0.18.1
Python version: 3.5.2
Platform: Linux-4.7.4-pf-x86_64-with-arch
SSL version: OpenSSL 1.0.2h  3 May 2016
Linux distro: arch  
```

**Comment by mindcat** [comment]
@mhils You didn't have proper fix the ```ctx.log == None``` =S

**Comment by mhils** [comment]
As mentioned in f26a375, you don't want to use mitmproxy.ctx from a different thread. `ctx.log` being None is a symptom of that.
