### ISSUE TITLE
Run 'basicflow' from 'examples/' fails at importing 'logging'

### ISSUE THREAD

**Issue by strin** [mitmproxy/mitmproxy#1682]
##### Steps to reproduce the problem:

1. go to `examples/`
2.run `python basicflow`

you'll get an error that says cannot import Handlers from logging.

##### Any other comments? What have you tried so far?

This is because there's also another file called 'logging.py' in 'examples/'

**Comment by mhils** [comment]
Thanks! Would you like to send a PR that renames logging.py to log.py or so? 😃

**Comment by Kriechi** [comment]
fixed by d56bbb9
