### ISSUE TITLE
Serialise/deserialise Options

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1699]
We need to add serialization and de-serialization for Options. This will let us move away from ConfigArgParser and give us a better configuration format.

Here's one comparison of the options out there:

https://gist.github.com/njsmith/78f68204c5d969f8c8bc645ef77d4a8f

There's some additional interesting context here:

https://github.com/avakar/pytoml/issues/15

At this point, I think it's a tossup between yaml and toml. I'm slightly leaning towards toml.

**Comment by MatthewShao** [comment]
Vote for TOML, it is similar to JSON, which is intuitive to most developers. And it is a lot lightweighter than YAML.
```... the complete parser is 300 lines of code (plus another 100 lines for the TOML writing support). (Compare to PyYAML, which is >4200 lines of code.)```

**Comment by cortesi** [comment]
One feature that would be nice to have is the ability to re-write an existing config without losing comments, changing structure, etc. This would let us, for instance, save out options changes from mitmproxy console without annoying users. Rust's toml library has this "format preserving" feature:

https://github.com/joelself/tomllib

**Comment by cortesi** [comment]
Here's a Python toml library that retains formatting:

https://github.com/jumpscale7/python-consistent-toml

Development momentum is zero, though, so we might have to be willing to maintain it if we use it.

**Comment by cortesi** [comment]
Here's a format and comment preserving parser for YAML, which seems to be well-maintained and active:

https://bitbucket.org/ruamel/yaml

**Comment by cortesi** [comment]
I've now had a look around, and while I prefer toml as a format, I think we should go with Yaml because of the libraries available - in particular, I think we should go with the ruamel.yaml library. There's nothing comparable for toml - in fact, it seems all the Python toml libraries have issues of various sorts.

**Comment by cortesi** [comment]
Done
