### ISSUE TITLE
Documentation for using mitmproxy as a library

### ISSUE THREAD

**Issue by yifeikong** [mitmproxy/mitmproxy#1717]
Hi, I really need to use mitmproxy as a library other that write scriptlet for mitmproxy, but I can't find any documentation on that, and the examples in the `examples` folder seems to be buggy and lack of update.

Thanks for your attention!

**Comment by Kriechi** [comment]
Hi @yifeikong!
Thanks for raising this issue - the mitmproxy is a always a work-in-progress and there are still undocumented corners. Could you maybe briefly explain what you want to do, and why you really need to mitmproxy as library? Maybe a regular script using mitmproxy hooks is enough for your use case?

**Comment by yifeikong** [comment]
My use case is that I need to build a long-running-proxy to intercept some responses and store the responses in a database. First, I tried to write a scriptlet for mitmdump, but it seems that mitmdump stops working and hangs for no reason after a day or two. So I figured I could use mitmproxy as a library and write my own daemon process so that I could add my own logic of when to restart the proxy. I searched the web for using mitmproxy as a library, and saw some outdated articles talking about libmproxy or libmitmproxy, but nothing works.

**Comment by mhils** [comment]
>  First, I tried to write a scriptlet for mitmdump,

Assuming that you are talking about mitmproxy addons/scripts, this is the recommended approach. If you have problems with long-running processes, that'd be a bug. If you need to work around that, I'd recommend some external montoring/restarting on top of mitmproxy.
