### ISSUE TITLE
mitmdump doesn't seem to work when bound to localhost

### ISSUE THREAD

**Issue by virtuald** [mitmproxy/mitmproxy#1718]
##### Steps to reproduce the problem:

```
$ mitmdump -b 127.0.0.1 -R https://example.com -p 1234 -s "script.py arg"
Proxy server listening at http://127.0.0.1:1234
127.0.0.1:49415: clientconnect
127.0.0.1:49415: GET https://example.com/page
 << Server connection to example.com:443 failed: Error connecting to "example.com": [Errno 49] Can't assign requested address
```

##### Any other comments? What have you tried so far?

Works when bind argument isn't specified. Doesn't work on Windows either.

##### System information

Mitmproxy version: 0.18.2
Python version: 2.7.11
Platform: Darwin-15.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.11.6 ('', '', '') x86_64

**Comment by mhils** [comment]
Fixed by @dwfreed in #1735!
