### ISSUE TITLE
redirect_requests.py doesn't work( cannot import name 'http')

### ISSUE THREAD

**Issue by Cojad** [mitmproxy/mitmproxy#1719]
Loading script: redirect_requests.py
Script error: Traceback (most recent call last):
  File "redirect_requests.py", line 4, in <module>
    from mitmproxy import http
ImportError: cannot import name 'http'

##### Steps to reproduce the problem:
1. simply execute script from examples(clone from github master)  
mitmdump -s redirect_requests.py.
##### Any other comments? What have you tried so far?
I tried both python 2.4.7/3.5 but in vain.
##### System information
Mitmproxy version: 0.18.2
Python version: 3.5.2
Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.6
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Linux distro: debian 8.6

**Comment by Kriechi** [comment]
Please use the correct example for the mitmproxy version you have installed.
In your case, this is the correct link: https://github.com/mitmproxy/mitmproxy/blob/0.18.x/examples/redirect_requests.py

**Comment by Cojad** [comment]
Thanks for point out that master isn't the newest 0.18x release. I wan't expecting this. But I see now. That really helps!
