### ISSUE TITLE
Proxy-Authentication does not work with HTTPS sites

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1722]
##### Steps to reproduce the problem:

1. `mitmdump --nonanonymous`
2. `curl -x localhost:8080 -k -U foo:bar http://example.com` (works)
3. `curl -x localhost:8080 -k -U foo:bar https://example.com` (doesn't)

##### Any other comments? What have you tried so far?

The problem is an invalid handling of `http_authenticated`.

**Comment by mhils** [comment]
This is still an issue after the latest changes.

**Comment by martyn-w** [comment]
Just to note that we have experienced exactly the same issue with MITMProxy 0.18.2, but not with 0.17.1. The problem seems to be the use of "transparent mode" in the low-level http interaction between the proxy and the upstream server; even when non-transparent mode is selected.

For example:

    # MITMProxy 0.17.1

    $ mitmdump --version
    mitmdump 0.17.1
    $ mitmdump --cadir ~/path/to/certificates --nonanonymous

    (another terminal) $ curl -x "http://foo:bar@127.0.0.1:8080" "https://www.google.co.uk/"

    127.0.0.1:45260: clientconnect
    127.0.0.1 GET https://www.google.co.uk/
     << 200 OK 10.1kB
    127.0.0.1:45260: clientdisconnect


Compared with:


    $ mitmdump --version
    mitmdump 0.18.2
    $ mitmdump --cadir ~/path/to/certificates --nonanonymous
    Proxy server listening at http://0.0.0.0:8080

    (another terminal) $ curl -x "http://foo:bar@127.0.0.1:8080" "https://www.google.co.uk/"
            <html>
                <head>
                    <title>401 Unauthorized</title>
                </head>
                <body>Authentication Required</body>
            </html>Zippy:~ martyn$ 


    127.0.0.1:45262: clientconnect
    127.0.0.1:45262: clientdisconnect
