### ISSUE TITLE
--host option and pretty_host should also use ":authority" header for HTTP2 requests

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#1726]
##### Steps to reproduce the problem:

1. Connect to https://http2.akamai.com/demo for HTTP2 tests
2. pretty_host = IP_ADDRESS, but :authority header contains http2.akamai.com
3.

##### System information

./mitmdump --sysinfo
Mitmproxy version: 0.18.2
Python version: 3.5.2
Platform: Darwin-16.1.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.1 ('', '', '') x86_64

**Comment by mhils** [comment]
Which client are you using to perform your requests?

**Comment by tomlabaude** [comment]
I used Chrome 54.0.2840.71 (64-bit) on macOS

**Comment by Kriechi** [comment]
Tested with latest curl, Firefox, and Chrome:

Using this script:
```python
def request(f):
    print(f.request.pretty_host)
```

and running: 
`mitmdump -s test.py`

always prints:
`http2.akamai.com`

**Comment by mhils** [comment]
Did you test in transparent mode?

**Comment by Kriechi** [comment]
Good point!
I'm able to reproduce this now. Will take a look how this affects HTTP/2-related code.

**Comment by Kriechi** [comment]
@tomlabaude can you please try to test with PR #1791 if this solves your problem?

**Comment by mhils** [comment]
2.0.0 now has `request.host_header` and fixes this. 🎉
