### ISSUE TITLE
Crash on www.evernote.com

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#1728]
##### Steps to reproduce the problem:

1. Launch mitmdump without argument, ./mitmdump

2. Set HTTPS proxy as a general system proxy on Mac

2. On Chrome, visit https://www.evernote.com -> it crashes with traceback:
```
127.0.0.1:55955: GET https://www.evernote.com/
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "site-packages/mitmproxy/main.py", line 108, in mitmdump
  File "site-packages/mitmproxy/dump.py", line 89, in run
  File "site-packages/mitmproxy/controller.py", line 142, in run
  File "site-packages/mitmproxy/controller.py", line 163, in tick
  File "site-packages/mitmproxy/controller.py", line 253, in wrapper
  File "site-packages/mitmproxy/addons.py", line 85, in __call__
  File "site-packages/mitmproxy/addons.py", line 81, in invoke
  File "site-packages/mitmproxy/builtins/dumper.py", line 229, in response
  File "site-packages/mitmproxy/builtins/dumper.py", line 211, in echo_flow
  File "site-packages/mitmproxy/builtins/dumper.py", line 203, in _echo_response_line
  File "site-packages/mitmproxy/builtins/dumper.py", line 46, in echo
  File "site-packages/click/termui.py", line 420, in secho
  File "site-packages/click/utils.py", line 259, in echo
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 57: surrogates not allowed
mitmdump returned -1
```

##### Any other comments? What have you tried so far?
3. It doesn't happen on https://evernote.com

##### System information

```
./mitmdump --sysinfo
Mitmproxy version: 0.18.2
Python version: 3.5.2
Platform: Darwin-16.1.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.1 ('', '', '') x86_64
```

**Comment by tomlabaude** [comment]
At some point, I had another SSLv3 alert, but I didn't succeed to find the steps to get it again.
Not a crash, but might help

From logs:
127.0.0.1:55937: clientconnect
127.0.0.1:55937: CONNECT www.evernote.com:443
 << Cannot establish TLS with client (sni: www.evernote.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)",)
127.0.0.1:55937: clientdisconnect

**Comment by Kriechi** [comment]
I just tested it with current master and the `v0.18.2` tag, and it works without throwing an error.
Do you still get this error?

**Comment by tomlabaude** [comment]
Actually I retested it and get successful "CONNECT www.evernote.com:443".

I don't know how I succeeded to get "GET https://www.evernote.com/" instead of CONNECT
Any idea? Could it be a manual proxy + transparent redirection? I'll try to reproduce my buggy config

**Comment by nesttle** [comment]
Same here on X.X.X.X:443
version 0.18.2

**Comment by julo15** [comment]
I see this fairly easily on a Google Pixel (Android 7.1.1) using mitmproxy 0.18.2 and 1.0.2. A lot of https traffic gets through successfully, but I also see a lot of hits on the issue as well.

If I open Chrome on the device and do any search from www.google.com, I see the issue:

>192.168.0.107:45898: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')],)",)

@Kriechi Do you have any advice on how to investigate this further?

**Comment by julo15** [comment]
Ah, figured it out. The issue I was hitting was this: https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html

It didn't fix hitting www.google.com, but it did fix my app trying to hit my server endpoint. Because my app had `targetSdkVersion 25`, I had to add a `android:networkSecurityConfig` file to my android manifest, as described in the link above. (Targeting Android 23 also addressed the issue.)
