### ISSUE TITLE
Add HTTP upstream

### ISSUE THREAD

**Issue by pauldraper** [mitmproxy/mitmproxy#1731]
I want to accept requests as an HTTPS proxy and forward them to an HTTP proxy.

Currently, `-U` always forwards the request as if the upsteam were an HTTPS proxy.

---

EDIT: put another way, I want to use mitmproxy as an HTTPS proxy that strips the SSL/TLS for a HTTP proxy.

**Comment by pauldraper** [comment]
I came up with inline script:

```
import argparse
from mitmproxy import exceptions
from mitmproxy.proxy import config

class HttpUpstreamProxy:
    def __init__(self, upstream):
        self.upstream = upstream

    def request(self, flow):
        if 'X-Forwarded-Proto' not in flow.request.headers:
            flow.request.headers['X-Forwarded-Proto'] = self.upstream.scheme
        flow.request.scheme = self.upstream.scheme
        flow.request.data.host = self.upstream.address.host
        flow.request.port = self.upstream.address.port

def start():
    parser = argparse.ArgumentParser()
    parser.add_argument('upstream', type=config.parse_server_spec)
    args = parser.parse_args()
    return HttpUpstreamProxy(args.upstream)
```

```
mitmdump -p 3080 -s 'http_upstream.py http://upstream:port'
```

This could works for HTTPS as well, but it currently does for some reason. (HTTP is my use case though.)

**Comment by mhils** [comment]
Just to clarify, you are asking for a mode where mitmproxy translates incoming HTTPS requests to HTTP 
and sends them to an upstream proxy? 
What's your use case for this?
