### ISSUE TITLE
Writing into file has impact on inline scripts

### ISSUE THREAD

**Issue by phackt** [mitmproxy/mitmproxy#1750]
##### Steps to reproduce the problem:

1. Working with with flowwriter.py template for version v0.18.2
2. mitmproxy --script "./flowwriter.py ./test.log" --eventlog
3. full command is *mitmproxy --anticache --host --anticomp --noapp --script "./flowwriter.py ./requests.log" --script ./sslstrip.py --eventlog*

##### Any other comments? What have you tried so far?
flowwriter.py is not working in conjunction with an other script and with wb mode (nothing written in file).

It seems that this is a buffering matter, an f = open(path, "ab") will do the trick on my side, without any decoded(flow.request) function **and without any other script loaded.** Unfortunately the f = open(path, "wb", 0) is not doing the trick if i do not want to be in an append mode. But as mentioned another problem is that loading this script (flowwriter.py), or any file writing method (option -a, -w), will cause any other scripts unstable (like reloading several times) (ex: --script "./flowwriter.py ./requests.log" --script ./sslstrip.py). The same behavior occurs with **mitmdump** with **--script ./sslstrip.py -a ./requests.log**, but everything works fine (mitmproxy and mitmdump) if i do not write into files for logging.

Regards,

_____
**EDIT**
a last thing:
mitmproxy --script "./sslstrip.py" --eventlog -a requests.log ==> **Does not work as expected**
(go on http://www.ameli.fr/, click on "Mon compte ameli", HttpReadDisconnect('Server disconnected',) error)
  
mitmproxy --script "./sslstrip.py" --eventlog ==> **Works as expected**
(go on http://www.ameli.fr/, click on "Mon compte ameli", page is well displayed)

Thanks,
##### System information
Mitmproxy version: 0.18.2
Python version: 2.7.12+
Platform: Linux-4.8.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Linux distro: Kali kali-rolling kali-rolling

$ whereis mitmproxy
mitmproxy: /usr/bin/mitmproxy /usr/share/man/man1/mitmproxy.1.gz

**Comment by phackt** [comment]
It seems that this is a buffering matter, an f = open(path, "ab") will do the trick on my side and without the decoded(flow.request). Unfortunately the f = open(path, "wb", 0) is not doing the trick if i do not want to be in an append mode.

Regards,

**Comment by phackt** [comment]
a last thing:
mitmproxy --script "./sslstrip.py" --eventlog -a requests.log ==> **Does not work as expected**
mitmproxy --script "./sslstrip.py" --eventlog ==> **Works as expected**

Thanks,

**Comment by mhils** [comment]
I'm sorry, but I'm having a really hard time to understand what your issue is.

```mitmproxy --script "./sslstrip.py" --eventlog -a requests.log``` and ```mitmproxy --anticache --host --anticomp --noapp --script "./flowwriter.py ./requests.log" --script ./sslstrip.py --eventlog``` work for me as expected on the lastet master.

**Comment by phackt** [comment]
Hello Maximilian, 

I understand thanks for your time, that's why in parallel i asked on the forum for help (https://discourse.mitmproxy.org/t/inline-script-loaded-several-times-with-mitmproxy-mitmdump-log-option/238). With option -a requests.log, the script seems to be loaded several times and behaves abnormally (cf the test mentioned on the forum). I was dealing with the tagged version v0.18.2, so let me test ASAP on the latest master, if everything works i will wait for next release.

Thanks again,

**Comment by phackt** [comment]
@mhils Hi Maximilian, just one question how is it possible de debug an inline script? If we have any issue, the script does not show any error! In the former version the Error was thrown and displayed in the eventlog. So i will be able to debug any script if needed, Thanks a lot again.

**Comment by mhils** [comment]
Errors should be displayed in the event log - there was a bug in 0.18, but 0.18.2 works for me. If not, please file a separate report.

**Comment by phackt** [comment]
Ok i will let you know, thanks.
