### ISSUE TITLE
Cannot install on Windows with Python 3.5

### ISSUE THREAD

**Issue by smsenesac** [mitmproxy/mitmproxy#1756]
##### Steps to reproduce the problem:

1. Install Python 3.5 on Windows
2. pip install mitmproxy

    Building lxml version 3.6.0.
    Building without Cython.
    ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.

##### Any other comments? What have you tried so far?

I attempted to install a binary version of lxml but it will not work because the oldest lxml version available for Python 3.5 on Windows is 3.6.4 but mitmproxy required 3.6.0.

**Comment by mhils** [comment]
Hi Stephen,

Sorry about that. The lxml situation is a mess, but we can't do anything about it other than wait for the maintainer to upload the wheels we built for him to PyPI. You can manually install https://snapshots.mitmproxy.org/misc/lxml-3.6.0-cp35-cp35m-win32.whl for now (or grab the artifacts from https://ci.appveyor.com/project/mhils/lxml).

`pip install <lxml wheel url> mitmproxy` (in a single command!) should work.

>the oldest lxml version available for Python 3.5 on Windows is 3.6.4

I suppose you are referring to the unofficial builds at http://www.lfd.uci.edu/~gohlke/pythonlibs/ or did I miss something?

**Comment by smsenesac** [comment]
Yeah, that's where I had found the 3.6.4 binaries.  Thanks for the quick reply and I'll check that out in the morning!

**Comment by smsenesac** [comment]
That fixed it for me, thanks!

**Comment by mhils** [comment]
Glad this worked! 

FWIW, we hope to ultimately resolve this in #1657, which seems to be easier to do than to get the lxml maintainers to push prebuilt wheels to pypi.
