### ISSUE TITLE
Correct way to retry response on 503 in script?

### ISSUE THREAD

**Issue by fotinakis** [mitmproxy/mitmproxy#1758]
Env: mitmdump 0.18.2 (trying to migrate a script from 0.16)

Hello!

I'm trying to understand how I might use `replay_request` or something else to add proxy-level retries on certain errors, such as when a flaky backend throws a 503 error.

I've tried this:

```bash
$ mitmdump -p 8080 --no-http2 -s myscript.py
```

**myscript.py:**
```python
from mitmproxy import ctx

def response(flow):
    # Retry once if the backend responded with 503:
    if flow.response.status_code == 503:
        f = ctx.master.duplicate_flow(flow)
        ctx.master.replay_request(f, block=True)
```
...but this seems to deadlock, I think because I don't understand the way the main thread processes flows (or how exactly to replace the current flow.response).

Can you point me in the right direction here?

**Comment by mhils** [comment]
Hi,

> ...but this seems to deadlock, I think because I don't understand the way the main thread processes flows (or how exactly to replace the current flow.response).

You may find http://docs.mitmproxy.org/en/stable/scripting/overview.html#concurrency useful :smiley:

```python
    def replay_request(self, f, block=False):
        """
        Replay a HTTP request to receive a new response from the server.
        Args:
            f: The flow to replay.
            block: If True, this function will wait for the replay to finish.
                This causes a deadlock if activated in the main thread.
        Returns:
            The thread object doing the replay.
        Raises:
            exceptions.ReplayException, if the flow is in a state
            where it is ineligible for replay.
        """
```
In a nutshell, when you call `replay_request` you are in a script handler. The request replay functionality itself tries to calls into the `request/response/...` hooks as well, but the master is currently busy with waiting for the replay functionality to finish. You end up with a classic deadlock.

There are two ways to fix this: Annotate your function with `@concurrent` or remove the `block=True` parameter. Given your use case, the latter does not make much sense (you want to work with the response), so `@concurrent` should be the way to go :smiley:

**Comment by fotinakis** [comment]
Thanks @mhils! I did end up trying `@concurrent` a few days ago and it did work as you described—most of the time. :) There seemed to be a race condition that would cause the error: `AttributeError: 'NoneType' object has no attribute 'replay_request'`, referring to `ctx.master` being null for some reason on the replay_request line (this would happen 1 in 20 times, otherwise it would work). The only place I could find `master` being set to null is here: https://github.com/mitmproxy/mitmproxy/blob/b636e4353a4804f92c8a3d56250874f7b081b691/mitmproxy/master.py#L59 — but I'm not sure how handlecontext() fits in the flow.

I don't have the original script I used to get it to exercise the race, but here's what I remember doing:

```python
from mitmproxy import ctx

index = 0

@concurrent
def response(flow):
    global index
    index += 1
    if index < 20:
        f = ctx.master.duplicate_flow(flow)
        ctx.master.replay_request(f, block=True)
    if index >= 20:
        response.body = 'GOT IT'
```

Then, running `curl -x localhost:8080 http://foo.com` would die after a few replays.

**Comment by mhils** [comment]
Uh - right. This area is a bit under construction right now - we basically want to avoid that users call master from a different thread (which `@concurrent` spawns) unless they know what they are doing. `.replay_request()` is safe, but other functions might not be.

A hacky workaround right now is to use `from mitmproxy.ctx import master` so that you don't loose your master reference. We'll hopefully have a better API for this at some point.

**Comment by fotinakis** [comment]
Ah, great! I'll try that, thanks.

**Comment by fotinakis** [comment]
Here's what ended up working, feel free to let me know if something looks off here.

Notably: it seems that the `response` hook fires for every replayed request (which is the opposite of what I read you talk about on the [forums](https://discourse.mitmproxy.org/t/replay-request-does-not-seem-to-trigger-request-or-response-scripts/32)), so I had to add a `_num_retries` tracker to prevent infinite recursion.

I also had to do `flow.response = new_flow.response`, which I'm not sure if that's correct way to override the top-level response.

```python
@concurrent
def response(flow):
  if flow.response.status_code == 503:
    retry_number = getattr(flow, '_num_retries', 0)

    if retry_number < MAX_REQUEST_RETRIES:
      new_flow = master.duplicate_flow(flow)
      setattr(new_flow, '_num_retries', retry_number + 1)
      master.replay_request(new_flow, block=True)
      flow.response = new_flow.response
    else:
      syslog.syslog(syslog.LOG_ERR, 'Permanent 503 from: %s' % flow.request.url)
```

Thanks for the help!

**Comment by maximusfox** [comment]
> 
> 
> Here's what ended up working, feel free to let me know if something looks off here.
> 
> Notably: it seems that the `response` hook fires for every replayed request (which is the opposite of what I read you talk about on the [forums](https://discourse.mitmproxy.org/t/replay-request-does-not-seem-to-trigger-request-or-response-scripts/32)), so I had to add a `_num_retries` tracker to prevent infinite recursion.
> 
> I also had to do `flow.response = new_flow.response`, which I'm not sure if that's correct way to override the top-level response.
> 
> ```python
> @concurrent
> def response(flow):
>   if flow.response.status_code == 503:
>     retry_number = getattr(flow, '_num_retries', 0)
> 
>     if retry_number < MAX_REQUEST_RETRIES:
>       new_flow = master.duplicate_flow(flow)
>       setattr(new_flow, '_num_retries', retry_number + 1)
>       master.replay_request(new_flow, block=True)
>       flow.response = new_flow.response
>     else:
>       syslog.syslog(syslog.LOG_ERR, 'Permanent 503 from: %s' % flow.request.url)
> ```
> 
> Thanks for the help!

How to make script like this on 5.x version?
