### ISSUE TITLE
vim-like left/right navigation between flowlist and flowview in mitmproxy

### ISSUE THREAD

**Issue by eboda** [mitmproxy/mitmproxy#1761]
What do you guys think about navigating left/right with <kbd>h</kbd> / <kbd>l</kbd> between flowlist and the tabs in flowview.

Basically, when you are in the flowlist and have one flow selected, you could hit <kbd>l</kbd> to bring you to the flowview for that item (instead of using <kbd>Enter</kbd>).  Then, once inside the flowview the navigation would be as it is now, except for when you are on the Request tab and hit <kbd>h</kbd>, which would bring you back to the flowlist (instead of going back to the Details tab).

Maybe it's just me, but I think it is more natural and would allow faster navigation then with <kbd>Enter</kbd> and <kbd>q</kbd>. Even though we could of course keep the actions for <kbd>Enter</kbd> and <kbd>q</kbd> the same, just add the new ones in addition.

What do you guys think?

**Comment by mhils** [comment]
Thanks for the suggestion! :smiley:

For non-vim users, I feel that enter is vastly more intuitive than `l`, so I think that's something we want to keep. I'm generally open to adding h/l shortcuts, but we should consider that those would be (1) duplicating what enter/q already does and (2) take up two keys which we could bind differently otherwise. This does not mean we shouldn't do it, but I think these are some good reasons to keep the current status.

@mitmproxy/devs, what do you think?

**Comment by Kriechi** [comment]
Not sure if they aren't already used? At least the help (press `?`)  mentions it already.

**Comment by mhils** [comment]
They are used to switch between the flowview tabs, yes.

**Comment by eboda** [comment]
A good alternative would be to allow remapping of default key bindings via a config file. Would you in general be open to a new feature like that?

**Comment by mhils** [comment]
My personal opinion is that this adds more complexity than value, so I'm a bit 👎 on this. Then again, I'm also someone who almost always uses the default keybindings, so I'm probably not the target audience.

@cortesi or @Kriechi may have stronger and potentially more positive opinions on this - feel free to chime in. 😄

**Comment by J-F-Liu** [comment]
What I like to have:
Press Enter show the flowview, and press Backspace return to flowlist.
In flowview, press Left arrow switch to previous tab, press right arrow switch to next tab.

**Comment by mhils** [comment]
Closing this in favor of #1524. Thanks again for the feedback.
