### ISSUE TITLE
android emulator http-proxy

### ISSUE THREAD

**Issue by kobster1** [mitmproxy/mitmproxy#1771]
1. Installed Whatsapp on android emulator
2. Installed mitmproxy
3. started Android emulator using adb with the http-proxy flag,
4. Tried browsing via emualtor browser works fine i can see the requests in mitmproxy, when I try registering Whatsapp/Viber I enter my phone number and press continue and then I get a "No internet connection" error.

So i tried port 80 as well as port 8080 as my http-proxy for the emulator still no success with Whatsapp/Viber but like i said I can browse the web from with in the emulaotr and see the requests in mitmproxy its just Whatsapp and Viber that I;ve tried and that did not work.

##### System information
Mitmproxy version: 0.18.2
Python version: 2.7.6
Platform: Linux-4.2.0-27-generic-x86_64-with-Ubuntu-14.04-trusty
SSL version: OpenSSL 1.0.1f 6 Jan 2014
Linux distro: Ubuntu 14.04 trusty

Emulator versions tested on:
Android 4.3.1 API 18 
Android 6.0 API 23

please help!!!!

**Comment by Kriechi** [comment]
Unfortunately for us, these apps use certificate pinning, which means they don't accept our custom CA. There is not much we can do.
https://security.stackexchange.com/questions/122981/does-whatsapp-use-certificate-pinning
