### ISSUE TITLE
cloudflare sites won't run

### ISSUE THREAD

**Issue by networksys** [mitmproxy/mitmproxy#1772]
##### Steps to reproduce the problem:
Turn on mitmdump and go to:
https://blog.cloudflare.com/introducing-strict-ssl-protecting-against-a-man-in-the-middle-attack-on-origin-traffic/
You'll get a 400 error.

##### Any other comments? What have you tried so far?
Is that error related to certificate pinning? Is there a possibility to auto detect Cloudflare sites and ignore them for proxying. A way would be to read the cloudflare header and ignore if it appears but what if other CDN providers have that protection too?

##### System information
Mitmproxy version: 0.19
Python version: 3.5.2
Platform: Windows-7-6.1.7601-SP1
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 7 6.1.7601 SP1 Multiprocessor Free

**Comment by Kriechi** [comment]
As far as I understand it, this protection only covers the second hop - which is unrelated to the client connection and mitmproxy.

I recently uncovered something similar with Akamai (e.g. www.microsoft.com), which sends back a 403 and a `Set-Cookie`. Retrying the same connection+request WITH this cookie then succeeds. 

Actually your example works for me:
```
$ curl --version
curl 7.51.0 (x86_64-apple-darwin15.6.0) libcurl/7.51.0 OpenSSL/1.0.2j zlib/1.2.8 nghttp2/1.16.1
```
<img width="1171" alt="screen shot 2016-11-21 at 22 30 31" src="https://cloud.githubusercontent.com/assets/114300/20501428/320c9b3a-b03a-11e6-8635-58b3975cd8fb.png">

**Comment by networksys** [comment]
![badrequest](https://cloud.githubusercontent.com/assets/20482243/20521772/2151a6c8-b0ad-11e6-9227-1853c65c2cd1.PNG)
Same with --no-http2 option

**Comment by networksys** [comment]
![ubuntu](https://cloud.githubusercontent.com/assets/20482243/20521960/09efc78e-b0ae-11e6-8fc8-1c467cc83aab.PNG)
At ubuntu it works. Seems to be a windows issue. Will try to replace the certificate from the ubuntu machine to the windows machine

**Comment by networksys** [comment]
Windows:
```
E:\>curl -x http://localhost:8080 --verbose -L http://blog.cloudflare.com/introd
ucing-strict-ssl-protecting-against-a-man-in-the-middle-attack-on-origin-traffic
/
* About to connect() to proxy localhost port 8080 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET http://blog.cloudflare.com/introducing-strict-ssl-protecting-against-a-man
-in-the-middle-attack-on-origin-traffic/ HTTP/1.1
> User-Agent: curl/7.21.1 (i686-pc-mingw32) libcurl/7.21.1 OpenSSL/0.9.8r zlib/1
.2.3
> Host: blog.cloudflare.com
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 400 Bad Request
< Date: Tue, 22 Nov 2016 11:29:20 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d7e65a58e17f0fd6fb532c35f655678231479814160; expires=Wed,
 22-Nov-17 11:29:20 GMT; path=/; domain=.cloudflare.com; HttpOnly
< Server: cloudflare-nginx
< CF-RAY: 305c0b04413d4829-MNL
<
* Connection #0 to host localhost left intact
* Closing connection #0
```
Linux:
```
E:\>curl -x http://192.168.1.103:8080 --verbose -L http://blog.cloudfl
are.com/introd
* About to connect() to proxy 192.168.1.103 port 8080 (#0)
*   Trying 192.168.1.103... connected
* Connected to 192.168.1.103 (192.168.1.103) port 8080 (#0)
> GET http://blog.cloudflare.com/introd HTTP/1.1
> User-Agent: curl/7.21.1 (i686-pc-mingw32) libcurl/7.21.1 OpenSSL/0.9.8r zlib/1
.2.3
> Host: blog.cloudflare.com
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 301 Moved Permanently
< Date: Tue, 22 Nov 2016 11:33:18 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dccb8a513b4f1b432aeb50f1e1017559d1479814398; expires=Wed,
 22-Nov-17 11:33:18 GMT; path=/; domain=.cloudflare.com; HttpOnly
< Location: https://blog.cloudflare.com/introd
< Server: cloudflare-nginx
< CF-RAY: 305c10d4c40f4835-MNL
<
* Ignoring the response-body
* Connection #0 to host 192.168.1.103 left intact
* Issue another request to this URL: 'https://blog.cloudflare.com/introd'
* About to connect() to proxy 192.168.1.103 port 8080 (#1)
*   Trying 192.168.1.103... connected
* Connected to 192.168.1.103 (192.168.1.103) port 8080 (#1)
* Establish HTTP proxy tunnel to blog.cloudflare.com:443
> CONNECT blog.cloudflare.com:443 HTTP/1.1
> Host: blog.cloudflare.com:443
> User-Agent: curl/7.21.1 (i686-pc-mingw32) libcurl/7.21.1 OpenSSL/0.9.8r zlib/1
.2.3
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
```

**Comment by Kriechi** [comment]
You seem to trigger the DDoS prevention I was talking about.
`< Set-Cookie: __cfduid=d7e65a58e17f0fd6fb532c35f655678231479814160; expires=Wed,
 22-Nov-17 11:29:20 GMT; path=/; domain=.cloudflare.com; HttpOnly`

If you use Firefox or Chrome, the browser should retry the request with this cookie set, then it will succeed. curl does not retry, so it just fails until you pass in that magic DDoS header.

**Comment by networksys** [comment]
I checked the cookie is set. With Linux mitmdump it works, with Windows mitmdump it doesn't work.

![Uploading cookie.PNG…]()

**Comment by Kriechi** [comment]
@mhils maybe you could take a look - this seems to be Windows-only.

**Comment by networksys** [comment]
it doesn't seem to be the cookie as you can see the same request goes through in Linux and not in Windows.

**Comment by mhils** [comment]
@networksys: Are you on the _latest_ master?

I don't hit the 400 Bad Request, but I did fix a bug related to ALPN-handling.

**Comment by networksys** [comment]
yes I'm on latest master

**Comment by networksys** [comment]
just pulled master. My master was older than a week. Thanks. You rock guys :)

**Comment by goors** [comment]
i am still having this problems with site on cloudflare. for example ios aps that are hitting api on cloudflare.

```
::ffff:192.168.0.16:58045: serverconnect
  -> ('havana.b92.net', 443)
::ffff:192.168.0.16:58045: Establish TLS with server
::ffff:192.168.0.16:58045: ALPN selected by server: http/1.1
::ffff:192.168.0.16:58045: Establish TLS with client
::ffff:192.168.0.16:58045: ALPN for client: b'http/1.1'
::ffff:192.168.0.16:58045: serverdisconnect
```
and that is all. no response.

**Comment by Kriechi** [comment]
@goors the host http://havana.b92.net/ seems to only respond with a 404 for me - and it doesn't look like it is running on cloudflare. Please create a new issue with a proper description of your problem.
