### ISSUE TITLE
mitmproxy run question

### ISSUE THREAD

**Issue by YangShaoXiong** [mitmproxy/mitmproxy#1773]
##### Steps to reproduce the problem:

1. prompt install success
2.but run "➜  bin mitmdump --version
Traceback (most recent call last):
  File "/usr/local/bin/mitmdump", line 7, in <module>
    from mitmproxy.main import mitmdump
  File "/Library/Python/2.7/site-packages/mitmproxy/main.py", line 7, in <module>
    from six.moves import _thread  # PY3: We only need _thread.error, which is an alias of RuntimeError in 3.3+
ImportError: cannot import name _thread"

**Comment by Kriechi** [comment]
I'm asuming you are on macOS or OSX. Please use the provided binaries to install mitmproxy successfully.

https://github.com/mitmproxy/mitmproxy/releases/tag/v0.18.2
http://docs.mitmproxy.org/en/stable/install.html#installation-on-mac-os-x
