### ISSUE TITLE
unable to use proxy upstream

### ISSUE THREAD

**Issue by ja8zyjits** [mitmproxy/mitmproxy#1776]
##### Steps to reproduce the problem:

1. copy following script
```python

def proxy_address(flow):
    return ("remote_ip", 18002)

def request(flow):
    address = proxy_address(flow)
    if flow.live:
        print("inside")
        flow.live.change_upstream_proxy_server(address)
```
2. run `mitmdump -s "update_mitmproxy.py"`
3. open terminal
```python
>>> import requests
>>> p = {"http":"http://127.0.0.1:8080","https":"http://127.0.0.1:8080"}
>>> response = requests.post("http://www.httpbin.org/post", json={"key":"value"}, proxies=p)
>>> response.json
{u'args': {},
u'data': u'{"key":"value"}',
u'files': {},
u'form': {},
u'headers': {u'Accept': u'*/*',
 u'Accept-Encoding': u'gzip, deflate',
 u'Content-Length': u'19',
 u'Content-Type': u'application/json',
 u'Host': u'www.httpbin.org',
 u'User-Agent': u'python-requests/2.12.1'},
u'json': {u"key":u"value"},
u'origin': u'local_ip', #this is the problem, i need to get the upstream_server ip
u'url': u'http://www.httpbin.org/post'}
```
4. The remote_proxy is working i tested it, but its not being used as an upstream server in this case you see the `origin` is still my local system not the `proxy remote server`

##### Any other comments? What have you tried so far?

* This script is from the examples, is it the right way to do?
* I am trying to do `Browser <------> MITM <------> remote_proxy(forwards and not intercepts the ssl) <------> Server`
*  runing  `mitmdump -s "update_mitmproxy.py" -U http://remote_server:port` this works properly, but i need to be able to dynamically change the upstream server.

##### System information

```Mitmproxy version: 0.18.2
Python version: 2.7.12
Platform: Linux-4.4.0-47-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial```

**Comment by ja8zyjits** [comment]
So I got the error in my case. The devil was in the documentation [this](https://github.com/mitmproxy/mitmproxy/blob/0.18.x/examples/change_upstream_proxy.py#L4) 

>  Usage: mitmdump -U http://default-upstream-proxy.local:8080/ -s change_upstream_proxy.py

Now i use `run mitmdump -s "update_mitmproxy.py" -U "http://localhost:8080"` and the dynamic changing of proxy works with this output

```bash
Loading script: update_mitmproxy.py
Proxy server listening at http://0.0.0.0:8080
logs Proxy server listening at http://0.0.0.0:8080
127.0.0.1:47366: clientconnect
logs 127.0.0.1:47366: clientconnect
logs 127.0.0.1:47366: request
  -> Request(GET www.google.com:80/)
inside
logs 127.0.0.1:47366: Set new server address: ('remote_ip', 18002)
logs 127.0.0.1:47366: serverconnect
  -> remote_ip:18002
logs 127.0.0.1:47366: response
  -> Response(200 OK, text/html; charset=ISO-8859-1, 4k)
127.0.0.1:47366: GET http://www.google.com/
              << 200 OK 4k
logs 127.0.0.1:47366: serverdisconnect
  -> remote_ip:18002
127.0.0.1:47366: clientdisconnect
logs 127.0.0.1:47366: clientdisconnect
```

How shall i do that in the stand alone script like [this](https://github.com/mitmproxy/mitmproxy/blob/0.18.x/examples/flowbasic).
```python
#!/usr/bin/env python
"""
    This example shows how to build a proxy based on mitmproxy's Flow
    primitives.

    Heads Up: In the majority of cases, you want to use inline scripts.

    Note that request and response messages are not automatically replied to,
    so we need to implement handlers to do this.
"""
from mitmproxy import flow, controller, options
from mitmproxy.proxy import ProxyServer, ProxyConfig

def proxy_address(flow):
    return ("remote_ip", 18002)

class MyMaster(flow.FlowMaster):
    def run(self):
        try:
            flow.FlowMaster.run(self)
        except KeyboardInterrupt:
            self.shutdown()

    @controller.handler
    def request(self, f):
        address = proxy_address(flow)
        if f.live:
            print("inside")
            f.live.change_upstream_proxy_server(address)
        print("request", f)

    @controller.handler
    def response(self, f):
        print("response", f)

    @controller.handler
    def error(self, f):
        print("error", f)

    @controller.handler
    def log(self, l):
        print("log", l.msg)


opts = options.Options(
    upstream_server="http://localhost:8080", cadir="~/.mitmproxy/") #setting the default upstream server
config = ProxyConfig(opts)
state = flow.State()
server = ProxyServer(config)
m = MyMaster(opts, server, state)
m.run()
```

I did try to add the default upstream server in the options, according what i read in the code, it is the same as passing `-U` but here it doesn't seem to work

The output
```bash
('log', '127.0.0.1:47346: clientconnect')
('log', '127.0.0.1:47346: request\n  -> Request(GET www.google.com:80/)')
inside
('request', <HTTPFlow
  request = Request(GET www.google.com:80/)
  client_conn = <ClientConnection: 127.0.0.1:47346>>)
('log', "127.0.0.1:47346: Set new server address: ('remote_ip', 18002)")
('log', '127.0.0.1:47346: Set new server address: www.google.com:80') #the server being replaced, but why?
('log', '127.0.0.1:47346: serverconnect\n  -> www.google.com:80')
('log', '127.0.0.1:47346: response\n  -> Response(302 Found, text/html; charset=UTF-8, 261b)')
('response', <HTTPFlow
  request = Request(GET www.google.com:80/)
  response = Response(302 Found, text/html; charset=UTF-8, 261b)
  client_conn = <ClientConnection: 127.0.0.1:47346>
  server_conn = <ServerConnection: www.google.com:80>>)
('log', '127.0.0.1:47346: request\n  -> Request(GET www.google.co.in:80/?gfe_rd=cr&ei=d5g1WJiqCKzv8we8_5LADA)')
inside
('request', <HTTPFlow
  request = Request(GET www.google.co.in:80/?gfe_rd=cr&ei=d5g1WJiqCKzv8we8_5LADA)
  client_conn = <ClientConnection: 127.0.0.1:47346>>)
('log', '127.0.0.1:47346: serverdisconnect\n  -> www.google.com:80')
('log', "127.0.0.1:47346: Set new server address: ('remote_ip', 18002)")
('log', '127.0.0.1:47346: Set new server address: www.google.co.in:80')
('log', '127.0.0.1:47346: serverconnect\n  -> www.google.co.in:80')
('log', '127.0.0.1:47346: response\n  -> Response(200 OK, text/html; charset=ISO-8859-1, 4k)')
('response', <HTTPFlow
  request = Request(GET www.google.co.in:80/?gfe_rd=cr&ei=d5g1WJiqCKzv8we8_5LADA)
  response = Response(200 OK, text/html; charset=ISO-8859-1, 4k)
  client_conn = <ClientConnection: 127.0.0.1:47346>
  server_conn = <ServerConnection: www.google.co.in:80>>)
('log', '127.0.0.1:47346: serverdisconnect\n  -> www.google.co.in:80')
('log', '127.0.0.1:47346: clientdisconnect')
```

From the working output and the non working output we can see that in the `Set new server address` is being replaced in the non working case. I am finding it really difficult to find why it is failing.

Any help would be greatly appreciated.

**Comment by mhils** [comment]
> How shall i do that in the stand alone script like this.

Why do you want to do it in a stand alone script? You usually should be better off writing mitmproxy scripts.

**Comment by ja8zyjits** [comment]
I have 2 reasons

1] if it works with `-U`  in cmd then it must work with the `API` given that both end up using the same module and functions(or base classes).


2] If I need only few functionalities which I can tailor up by using the API then I won't need to run an entire tool right?

Correct me if my above assumptions are wrong.

**Comment by mhils** [comment]
> 1] if it works with -U in cmd then it must work with the API given that both end up using the same module and functions(or base classes).

This is technically true (but strictly speaking not a reason).

> 2] If I need only few functionalities which I can tailor up by using the API then I won't need to run an entire tool right?

There are use cases where you don't want the overhead (or interactivity) of mitmproxy. If this is your case, you should use mitmdump. Any further optimization (subclassing FlowMaster yourself) is mostly negligible. More importantly, by subclassing FlowMaster, you rely on an API that is not intended for public consumption and may change at any point in time. If you want something more stable that is better supported, stay with mitmdump and the scripting interface. :-)

**Comment by ItalianJeep** [comment]
I solved this problem like this:

`class ParseResponse:

    def response(self, flow):
          pass

def start():
    proxy_url = "http://xxxproxy"
    proxy_ip = requests.get(proxy_url).text.strip()
    mode = "upstream:http://%s" % proxy_ip
    print(mode)  # => such as "upstream:http://123.123.123.123:1234"

    myaddon = ParseResponse()
    opts = options.Options(listen_port=9999, mode="upstream:http://%s" % proxy_ip)
   # DO NOT specify parameter listen_host='xxx' here, otherwise the object page cannot open, and I don't know why.
    proxy_config = proxy.config.ProxyConfig(opts)
    master = DumpMaster(opts)
    master.server = proxy.server.ProxyServer(proxy_config)
    master.addons.add(myaddon)

    try:
        master.run()
    except KeyboardInterrupt:
        master.shutdown()

if __name__ == '__main__':
    start()
`
now I can use this inline script to swich secondary proxy dynamicly than to use subprocess to run command line
