### ISSUE TITLE
mitmproxy-0.18.2-osx Error loading Python lib 

### ISSUE THREAD

**Issue by dvska** [mitmproxy/mitmproxy#1779]
##### Steps to reproduce the problem:

1.mitmproxy-0.18.2-osx$ ./mitmdump
Error loading Python lib '/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/_MEIsO6QsF/.Python': dlopen(/var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/_MEIsO6QsF/.Python, 10): Symbol not found: _faccessat
  Referenced from: /var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/_MEIsO6QsF/.Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/fv/8s5nyv5d25x_bdf22mjbktd40000gn/T/_MEIsO6QsF/.Python

##### System information
OS X 10.9.5

**Comment by Kriechi** [comment]
Thanks for the report.
How did you install mitmproxy?
OSX 10.9.5 is quite outdated now, is there any way you could upgrade or test it on a newer system?

**Comment by dvska** [comment]
> How did you install mitmproxy?
Just unpacked from the https://github.com/mitmproxy/mitmproxy/releases/download/v0.18.2/mitmproxy-0.18.2-osx.tar.gz

> OSX 10.9.5 is quite outdated now, is there any way you could upgrade or test it on a newer system?
Yeah, it starts successfully in EL Capitan.

**Comment by Kriechi** [comment]
Unfortunately there is no easy fix for this, as our binaries are created with PyInstaller.
https://github.com/pyinstaller/pyinstaller/issues/1191

You can try using the install-from-source method on OSX 10.9:
https://github.com/mitmproxy/mitmproxy/blob/0.18.x/README.rst#hacking
