### ISSUE TITLE
inline script when running mitmproxy in transparent mode

### ISSUE THREAD

**Issue by masrud** [mitmproxy/mitmproxy#178]
Hi there,
I was wondering if mitmproxy allows rewriting of server response when running in transparent mode.
I have an inline script to modify the code and it works when running like this:
./mitmproxy -s rewrite.py

 however in transparent mode it has no effect. I run it as following:

 ./mitmproxy -T -s rewrite.py

Thanks,
Masi

**Comment by flankerhqd** [comment]
Hi: 
I'm encountering the same issue, the script is not working.

`import mitmproxy
from mitmproxy.models import HTTPResponse
from netlib.http import Headers
import os
def request(context, flow):
	print flow.request.url
	if not flow.request.url.endswith("test.html"):
		return
	print "fuck"
	resp = HTTPResponse([1,1], 302, "Found", ODictCaseless([["Context-Type", "text/html"], ["Location", "http://google.com"]]), "")
	flow.reply(resp)
`
Command line:
`mitmproxy -T -e -s 1.py`

It seems the script is not executing at all, as `print flow.request.url` has no output, confusing me a lot.

**Comment by flankerhqd** [comment]
Version 0.18.2

**Comment by tejasmanohar** [comment]
Same here, but in normal mode too. Nothing is printed at all.
