### ISSUE TITLE
mitmproxy raises exception when editing unicode(Chinese) in query string 

### ISSUE THREAD

**Issue by yifeikong** [mitmproxy/mitmproxy#1798]
##### Steps to reproduce the problem:

1. intercept a url with Chinese query string
2. try to edit the query string with `e` then `q`
3. it crashes

##### Any other comments? What have you tried so far?
It seems to be a simple decode issue

```
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/console/grideditor/base.py", line 245, in get_next
    return GridRow(None, False, self.editor, self.lst[pos + 1]), pos + 1
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/console/grideditor/base.py", line 86, in __init__
    w = self.editor.columns[i].Display(v)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/console/grideditor/col_text.py", line 19, in Display
    return TDisplay(data, self.encoding_args)
  File "/usr/local/lib/python2.7/site-packages/mitmproxy/console/grideditor/col_text.py", line 33, in __init__
    data = data.encode(*self.encoding_args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)
```

**Comment by mhils** [comment]
Thanks. Do you have an exemplary URL? What client are you using?

**Comment by yifeikong** [comment]
http://google.com/?q=测试 would crash the latest mitmproxy from pypi

**Comment by mhils** [comment]
This works for me on master with Python 3.5, so this should be fixed with the next release. Thanks for the report anyway! :smiley:

**Comment by nmweizi** [comment]
1. Mitmproxy version: 3.0.0 (release version)
    Python version: 3.5.3
    Platform: Windows-10-10.0.14393-SP0
    SSL version: OpenSSL 1.1.0e  16 Feb 2017
    Windows version: 10 10.0.14393 SP0 Multiprocessor Free
2. chrome is ok
3. use ie11 is error

There was no hint error, but the server was submitted to the encoding error.
html charset is gb2312.
