### ISSUE TITLE
from libmproxy.protocol.http import decoded error

### ISSUE THREAD

**Issue by cnscyy** [mitmproxy/mitmproxy#1800]
##### Steps to reproduce the problem:

1.I have install mitmproxy using apt-get, when i from libmproxy.protocol.http import decoded, Traceback ImportError: cannot import name decoded.
2.when i install mitmproxy using pip, from libmproxy import controller, proxy, Traceback ImportError: No module named libmproxy
3.

##### System information

Ubuntu 16.4

mitmproxy version: 0.15, linux OS: Ubuntu 16.4

**Comment by cnscyy** [comment]
adium-theme-ubuntu (0.3.4)
androguard (3.0)
arff (0.9)
argcomplete (0.8.1)
argh (0.26.1)
backports-abc (0.5)
backports.ssl-match-hostname (3.4.0.2)
beautifulsoup4 (4.4.1)
blinker (1.3)
brotlipy (0.6.0)
bungiesearch (1.2.1)
certifi (2015.11.20.1)
cffi (1.5.2)
chardet (2.3.0)
click (6.2)
colorama (0.3.7)
ConfigArgParse (0.10.0)
construct (2.5.2)
cryptography (1.2.3)
cssutils (1.0.1)
distribute (0.7.3)
Django (1.7.11)
django-googleplay-api (1.1.2)
EditorConfig (0.12.1)
elasticsearch (5.0.1)
elasticsearch-dsl (5.0.0)
enum34 (1.1.2)
feedparser (5.1.3)
Flask (0.11.1)
grab (0.6.30)
h2 (2.4.2)
hpack (2.1.0)
html2text (2016.1.8)
html5lib (0.999)
hyperframe (4.0.1)
idna (2.0)
ipaddress (1.0.16)
itsdangerous (0.24)
Jinja2 (2.8)
jsbeautifier (1.6.4)
lxml (3.5.0)
MarkupSafe (0.23)
mitmproxy (0.15)
MySQL-python (1.2.5)
mysqlclient (1.3.7)
netifaces (0.10.5)
netlib (0.15.1)
passlib (1.6.5)
pathtools (0.1.2)
Pillow (3.1.2)
pip (8.1.1)
ply (3.7)
Preferences (0.8)
pyasn1 (0.1.9)
pycparser (2.14)
pycurl (7.43.0)
pygit2 (0.23.2)
pyliblzma (0.5.3)
PyMySQL (0.7.2)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyperclip (1.5.11)
pysqlite (1.0.1)
python-dateutil (2.5.3)
python-gitlab (0.16)
pytz (2014.10)
PyYAML (3.11)
requests (2.11.1)
rpm-python (4.12.0.1)
setuptools (20.7.0)
simplejson (3.10.0)
singledispatch (3.4.0.3)
six (1.10.0)
sqlparse (0.1.18)
tornado (4.2.1)
typing (3.5.2.2)
unity-lens-photos (1.0)
urlgrabber (3.9.1)
urllib3 (1.19)
urwid (1.3.1)
uTidylib (0.2)
vboxapi (1.0)
watchdog (0.8.3)
Werkzeug (0.11.11)
wheel (0.29.0)
yum-metadata-parser (1.1.4)

**Comment by Kriechi** [comment]
Please try the latest release of mitmproxy: v0.18.2
Take a look on how to install mitmproxy on Ubuntu:
http://docs.mitmproxy.org/en/stable/install.html#installation-on-ubuntu
