### ISSUE TITLE
Need mitmproxy to use different openssl

### ISSUE THREAD

**Issue by SriVR** [mitmproxy/mitmproxy#1808]
Hi 
I installed mitmproxy in redhat6 and I have two openssl version. I want mitmproxy to use OpenSSL 1.0.2j. what ever I try it keeps throwing me this warning. Could you please help with this issue.

Standard : 
Installed Packages
Name        : openssl
Arch        : i686
Version     : 1.0.1e
Release     : 48.el6_8.3
Size        : 3.9 M
Repo        : installed
From repo   : adn-rhel-x86_64-workstation-6
Summary     : A general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.

The other  one I installed 
/usr/bin> openssl version
OpenSSL 1.0.2j  26 Sep 2016

lrwxrwxrwx   1 root root          26 Dec  1 14:22 openssl -> /usr/local/ssl/bin/openssl

The python3.5 is using openssl 1.0.2j
/usr/bin> python3.5 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2j  26 Sep 2016

mitmdump
Proxy server listening at http://0.0.0.0:8080
ALPN support missing (OpenSSL 1.0.2+ required)!
HTTP/2 is disabled. Use --no-http2 to silence this warning.

/usr/local/bin> mitmdump --sysinfo
Mitmproxy version: 0.18.2
Python version: 3.5.2
Platform: Linux-2.6.32-642.4.2.el6.x86_64-x86_64-with-redhat-6.8-Santiago
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Linux distro: Red Hat Enterprise Linux Workstation 6.8 Santiago

**Comment by Kriechi** [comment]
mitmproxy uses the Python package `cryptography` which uses `pyOpenSSL`. 
The message "ALPN support missing" is only shown if:
`OpenSSL.SSL._lib.Cryptography_HAS_ALPN == False`

Please refer to the installation instructions of cryptography: https://cryptography.io/en/latest/installation/#building-cryptography-on-linux
