### ISSUE TITLE
[RFC] Installers for mitmproxy

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#1815]
Installing mitmproxy is currently not as easy as it could be:

1. `pip` suffers from a lot of issues: New releases of dependencies breaking installations (see e.g. #1533), ~~lxml on Windows (#1444)~~, additional dependencies for compilation on Linux...
2. Each of our mitmproxy/mitmdump/mitmweb binaries contains all dependencies. This greatly adds to distribution size. On linux, mitmproxy,-dump, and -web are at 67mb now due to this.
3. It would be nice if our executables would just end up on the PATH.
4. On Windows, we currently don't have start menu integration. It would be very nice if mitmweb could just be started by clicking on an icon, without opening a command line.
5. There's no way for users to receive (auto-)updates. We need to be careful here of course, as we don't want any form of tracking.

I stumbled upon https://installbuilder.bitrock.com/ today, which could potentially solve a lot of those issues:

- Windows/OSX/Linux installer generation
- The usual installer stuff: Generation of shortcuts, install wizard, uninstaller, ...
- .deb generation for Linux. Having our own .deb repository would (1) solve the update problem for Linux and (2) we could directly specify our compilation dependencies this way
- Auto update and manual update functionality
- Free for open source projects
- We can have PyInstaller in one-dir mode instead of one-file mode (https://pythonhosted.org/PyInstaller/operating-mode.html#how-the-one-file-program-works)

All together, it may be worth to explore this a bit more. @mitmproxy/devs, thoughts?

**Comment by cortesi** [comment]
So, all of this sounds good to me, with some caveats regarding auto-updates. Given that we're a security and privacy project, the bar here is set higher for us than other projects. We cannot do auto-update without explicit user opt-in and a careful explanation of what information we send, what we store on our side. There are also cultural differences between the platforms, which means we should be more careful on Linux than on OSX and WIndows where auto-update is de rigueur.

I've requested an open-source license from  BitRock so we can evaluate things. I'm a bit leery of being tied to a commercial project out of our control, but can be convinced.

**Comment by cortesi** [comment]
Recording the discussion that we had on Slack about our installation strategy. We're going to try the following:

- On Windows, an installer with auto-update is idiomatic. Let's do it.
- On OSX for our console programs, we feel that using brew is the way to go. I feel there are still some things to think about here. One option is to expand the current brew recipe that builds from source, but this means we're tied to upstream dependencies in brew that are out of our control. This is somewhat at odds with our packaging strategy, where we've tried to re-take control of everything in one shot. An alternative is to set up a brew cask that distributes our pre-built binaries. At this point, I'm leaning somewhat to the latter.
- On Linux, we're still in the air. The deb/apt situation is sub-optimal, ties us to a web of dependencies that aren't always updated in a timely fashion. Binary distribution to Linux is not culturally idiomatic, and auto-updaters are uncommon. At the moment the recommended way to install mitmproxy here is pip, but we'd like to move away from that. I wonder if we should just bite the bullet here and focus on a binary distribution, leaving pip for developers and experts.

**Comment by mhils** [comment]
I started working on the Windows installer at https://github.com/mhils/mitmproxy/tree/installbuilder - looks good so far. :smiley:

**Comment by Kriechi** [comment]
I think there have been no major complaints with our 1.0 distribution approach, so I'm closing this for now. If anybody feels things could be improved significantly by going for a completely different approach, feel free to open a new issue!
