### ISSUE TITLE
TLS ServerHello sending extensions not in client's list

### ISSUE THREAD

**Issue by yifanlu** [mitmproxy/mitmproxy#1818]
RFC 5246:
>   extensions
>      A list of extensions.  Note that only extensions offered by the
>      client can appear in the server's list.

However it appears mitmproxy is sending a renegotiation_info extension even though the ClientHello does not have it.

**Comment by mhils** [comment]
We just use OpenSSL under the hoods, so if this is a bug, it's most likely an OpenSSL bug. If you encounter issues in mitmproxy due to this, we'd need more info:

- What problems are you experiencing?
- What's the output of `mitmproxy --sysinfo`?

**Comment by yifanlu** [comment]
I think it is an openssl issue since I'm getting the same problem with sslsplit. I'm not home right now, so I don't have `mitmproxy --sysinfo`. The problem is that the client I'm interfacing with is sending an alert (internal error) during the handshake (after serverhellodone). I checked that the client accepts the certificate so I'm trying to figure out what's causing the error.

**Comment by mhils** [comment]
FWIW, If the alert is encrypted, you can try to set [`SSLKEYLOGFILE`](http://docs.mitmproxy.org/en/stable/dev/sslkeylogfile.html) and use the resulting master keys in Wireshark to view the error. Not sure, but they _should_ be available at this point.

**Comment by yifanlu** [comment]
Thanks. The alert is sent right after server hello so no key exchange happened yet and it's not encrypted. The difficulty is that I'm testing on a proprietary system running it's own TLS stack do it's a pain to debug and therefore I'm just hoping that once everything complies with the standard it would magically work.

**Comment by yifanlu** [comment]
It seems like according to https://tools.ietf.org/html/rfc5746 this behavior is normal. My problem is elsewhere.
