### ISSUE TITLE
mitmproxy API error Cannot establish TLS with client

### ISSUE THREAD

**Issue by Miller1990** [mitmproxy/mitmproxy#1819]
How can I catch connection errors using API mitmproxy for example "<< Cannot establish TLS with client (*********): TlsException("(54, 'ECONNRESET')",)" or "error Cannot establish TLS with client"

thanks

**Comment by mhils** [comment]
I think there is currently no way except for listening to `log` events, which I admit, isn't very nice. What's your use case here?

**Comment by Miller1990** [comment]
I need intereccate the logs to determine which connections have failed handsake or have not accepted the certificate

**Comment by mhils** [comment]
The only way to do this for now is to listen for `log` events. We may revisit that decision in the future.

**Comment by Miller1990** [comment]
Thanks, Marco
