### ISSUE TITLE
Can't connect to reddit with http/2

### ISSUE THREAD

**Issue by MatsWillemsen** [mitmproxy/mitmproxy#1824]
See #1310.
##### Steps to reproduce the problem:

1. Open Firefox with mitmproxy active
2. Go to reddit.com
3. See the error 'Secure Connection Failed'

##### Any other comments? What have you tried so far?

Exactly the same problem as with #1310.

##### System information

Mitmproxy version: 0.19
Python version: 3.5.2
Platform: Darwin-16.1.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.1 ('', '', '') x86_64

**Comment by Kriechi** [comment]
Thanks for reporting this - unfortunately there is not much we can do here.
We can try to nag somebody from the Reddit Ops team - if you know someone over there?

Here is a short example to replicate the bug:
```python
#!/usr/bin/env python3

import certifi
import h2.connection
import h2.events

import errno
import socket
import ssl
import time

SERVER_NAME = 'www.reddit.com'

socket.setdefaulttimeout(2)

c = h2.connection.H2Connection()
c.initiate_connection()

ctx = ssl.create_default_context(cafile=certifi.where())
ctx.set_alpn_protocols(['h2', 'http/1.1'])
ctx.set_npn_protocols(['h2', 'http/1.1'])

s = socket.create_connection((SERVER_NAME, 443))
s = ctx.wrap_socket(s, server_hostname=SERVER_NAME)

s.sendall(c.data_to_send())

# We prioritize stream 3 here, but later we try to open stream 1, which will fail
# This is a violation of https://tools.ietf.org/html/rfc7540#section-5.1
c.prioritize(3, weight=201, depends_on=0, exclusive=False)

headers = [
    (':method', 'GET'),
    (':path', '/'),
    (':authority', SERVER_NAME),
    (':scheme', 'https'),
    ('user-agent', 'custom-python-script'),
]
c.send_headers(1, headers, end_stream=True)

s.sendall(c.data_to_send())


while True:
    data = s.recv(65536 * 256)
    if not data:
        break

    try:
        events = c.receive_data(data)
        s.sendall(c.data_to_send())
    except:
        break

    for event in events:
        print(event)
```

**Comment by MatsWillemsen** [comment]
Thanks, @Kriechi (and @deweerdt), for the quick writeup and fix.

**Comment by Kriechi** [comment]
A bug fix was merged into h2o - and it is up to Fastly (the CDN in front of Reddit) to deploy the fix.

**Comment by Kriechi** [comment]
FYI: Reddit has deployed the fix - and mitmproxy is now able to proxy requests without errors.
