### ISSUE TITLE
Tests from master failing with pyparsing error

### ISSUE THREAD

**Issue by swiftugandan** [mitmproxy/mitmproxy#1825]
##### Steps to reproduce the problem:

1. cloned repo
2. installed and tried to run any of the executables (mitmproxy, mitmdump) ... failed
3. run py.test, failed

##### Any other comments? What have you tried so far?

================================================================================================= ERRORS =================================================================================================
____________________________________________________________________________ ERROR collecting test/mitmproxy/test_cmdline.py _____________________________________________________________________________
test/mitmproxy/test_cmdline.py:2: in <module>
    from mitmproxy.tools import cmdline
mitmproxy/tools/cmdline.py:12: in <module>
    from mitmproxy.addons import view
mitmproxy/addons/view.py:91: in <module>
    matchall = flowfilter.parse(".")
mitmproxy/flowfilter.py:503: in parse
    flt = bnf.parseString(s, parseAll=True)[0]
venv3.5/lib/python3.5/site-packages/pyparsing.py:1607: in parseString
    loc, tokens = self._parse( instring, 0 )
venv3.5/lib/python3.5/site-packages/pyparsing.py:1405: in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
venv3.5/lib/python3.5/site-packages/pyparsing.py:1049: in wrapper
    ret = func(*args[limit[0]:])
E   TypeError: <lambda>() takes 1 positional argument but 3 were given
_____________________________________________________________________________ ERROR collecting test/mitmproxy/test_proxy.py ______________________________________________________________________________
test/mitmproxy/test_proxy.py:7: in <module>
    from mitmproxy.tools import cmdline
mitmproxy/tools/cmdline.py:12: in <module>
    from mitmproxy.addons import view
mitmproxy/addons/view.py:91: in <module>
    matchall = flowfilter.parse(".")
mitmproxy/flowfilter.py:503: in parse
    flt = bnf.parseString(s, parseAll=True)[0]
venv3.5/lib/python3.5/site-packages/pyparsing.py:1607: in parseString
    loc, tokens = self._parse( instring, 0 )
venv3.5/lib/python3.5/site-packages/pyparsing.py:1405: in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
venv3.5/lib/python3.5/site-packages/pyparsing.py:1049: in wrapper
    ret = func(*args[limit[0]:])
E   TypeError: <lambda>() takes 1 positional argument but 3 were given
____________________________________________________________________________ ERROR collecting test/mitmproxy/test_web_app.py _____________________________________________________________________________
test/mitmproxy/test_web_app.py:9: in <module>
    from mitmproxy.tools.web import app
mitmproxy/tools/web/__init__.py:1: in <module>
    from mitmproxy.tools.web import master
mitmproxy/tools/web/master.py:12: in <module>
    from mitmproxy.addons import view
mitmproxy/addons/view.py:91: in <module>
    matchall = flowfilter.parse(".")
mitmproxy/flowfilter.py:503: in parse
    flt = bnf.parseString(s, parseAll=True)[0]
venv3.5/lib/python3.5/site-packages/pyparsing.py:1607: in parseString
    loc, tokens = self._parse( instring, 0 )
venv3.5/lib/python3.5/site-packages/pyparsing.py:1405: in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
venv3.5/lib/python3.5/site-packages/pyparsing.py:1049: in wrapper
    ret = func(*args[limit[0]:])
E   TypeError: <lambda>() takes 1 positional argument but 3 were given
___________________________________________________________________________ ERROR collecting test/mitmproxy/test_web_master.py ___________________________________________________________________________
test/mitmproxy/test_web_master.py:1: in <module>
    from mitmproxy.tools.web import master
mitmproxy/tools/web/__init__.py:1: in <module>
    from mitmproxy.tools.web import master
mitmproxy/tools/web/master.py:12: in <module>
    from mitmproxy.addons import view
mitmproxy/addons/view.py:91: in <module>

##### System information

(venv3.5) osboxes@osboxes:/tmp/mitmproxy$ mitmdump --sysinfo
Traceback (most recent call last):
  File "/tmp/mitmproxy/venv3.5/bin/mitmdump", line 11, in <module>
    load_entry_point('mitmproxy', 'console_scripts', 'mitmdump')()
  File "/tmp/mitmproxy/venv3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/mitmproxy/venv3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
    return ep.load()
  File "/tmp/mitmproxy/venv3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/tmp/mitmproxy/venv3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/mitmproxy/mitmproxy/tools/main.py", line 12, in <module>
    from mitmproxy.tools import cmdline  # noqa
  File "/tmp/mitmproxy/mitmproxy/tools/cmdline.py", line 12, in <module>
    from mitmproxy.addons import view
  File "/tmp/mitmproxy/mitmproxy/addons/view.py", line 91, in <module>
    matchall = flowfilter.parse(".")
  File "/tmp/mitmproxy/mitmproxy/flowfilter.py", line 503, in parse
    flt = bnf.parseString(s, parseAll=True)[0]
  File "/tmp/mitmproxy/venv3.5/lib/python3.5/site-packages/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/tmp/mitmproxy/venv3.5/lib/python3.5/site-packages/pyparsing.py", line 1405, in _parseNoCache
    tokens = fn( instring, tokensStart, retTokens )
  File "/tmp/mitmproxy/venv3.5/lib/python3.5/site-packages/pyparsing.py", line 1049, in wrapper
    ret = func(*args[limit[0]:])
TypeError: <lambda>() takes 1 positional argument but 3 were given

* OS - Linux osboxes 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dwfreed** [comment]
Please provide the output of `pip show pyparsing` with your mitmproxy venv active.

**Comment by swiftugandan** [comment]
(venv3.5) osboxes@osboxes:/tmp/mitmproxy$ pip show pyparsing
Name: pyparsing
Version: 2.1.10
Summary: Python parsing module
Home-page: http://pyparsing.wikispaces.com/
Author: Paul McGuire
Author-email: ptmcg@users.sourceforge.net
License: MIT License
Location: /tmp/mitmproxy/venv3.5/lib/python3.5/site-packages
Requires: 
(venv3.5) osboxes@osboxes:/tmp/mitmproxy$

**Comment by Kriechi** [comment]
Would you mind trying to deleting your venv, and recreating it?
Please also make sure to delete all `*.pyc*`  and `__pycache__` file:
`find . -name "*.pyc" -delete && find . -name __pycache__ -delete`

**Comment by swiftugandan** [comment]
279  deactivate
  280  rm -rf venv3.5
  281  find . -name "*.pyc" -delete && find . -name __pycache__ -delete
  282  ls
  283  ./dev.sh 
  284  . venv3.5/bin/activate
  285  py.test

the test still failed

**Comment by mhils** [comment]
Hm, that's weird. Could you post the output of `tox -e py35` ?
