### ISSUE TITLE
Why HTTP/2 disabled while openssl version is 1.1.0 ?

### ISSUE THREAD

**Issue by hexucheng** [mitmproxy/mitmproxy#1832]
ubuntu 14.04.5

openssl 1.1.0c

mitmproxy 0.18.2

python 2.7.6

cryptography 1.5.3

I always receive the following warning:HTTP/2 disabled. OpenSSL 1.0.2+ required, it's confused me because my openssl version is 1.1.0, can someone tell me why ?

**Comment by mhils** [comment]
Which OpenSSL version do you get with `mitmproxy --sysinfo`?

**Comment by hexucheng** [comment]
1.0.1f，How to tell mitmproxy to use my openssl version ？

**Comment by mhils** [comment]
https://cryptography.io/en/latest/installation/

**Comment by hexucheng** [comment]
I generate openssl.ld like this:
    OPENSSL_1.1.0C_CUSTOM {
        global:
            *;
    };
and execute commands to build openssl 1.1.0c as follows:
    sudo ./config -Wl,--version-script=openssl.ld -Wl,-Bsymbolic-functions -fPIC shared
    sudo make
but it interrupted by error:/usr/bin/ld: duplicate expression `*' in version information, do you know why ?

**Comment by mhils** [comment]
If you have issues installing cryptography, please read through the cryptography docs or (if that does not help) ask the guys at https://github.com/pyca/cryptography.

Thanks!
Max
