### ISSUE TITLE
mitmproxy display "\t" as "?" in request's UA

### ISSUE THREAD

**Issue by hexucheng** [mitmproxy/mitmproxy#1833]
My request's UA has "\t" and mitmproxy display it as "?", usually it display as blank space like fiddler or charles.

<img width="1368" alt="2016-12-10 3 24 13" src="https://cloud.githubusercontent.com/assets/9985186/21061654/366dd14c-be88-11e6-9153-22675532e3f9.png">

**Comment by mhils** [comment]
Thanks! Please use the issue template next time so that we know your mitmproxy version right away.

This still affects master:
```
pathoc -c example.com:80 localhost:8080 'get:/:u"foo\tbar"'
```

**Comment by mhils** [comment]
This seems to be an urwid issue:
```python
import urwid

txt = urwid.Text(u"Hello\tWorld")
fill = urwid.Filler(txt, 'top')
loop = urwid.MainLoop(fill)
loop.run()
```

**Comment by hexucheng** [comment]
mitmproxy version is 0.18.2.

**Comment by kajojify** [comment]
Are there any problems with fixing this issue?

**Comment by kajojify** [comment]
We can just change https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/flowview.py#L156 to
`[(h + ":", v.encode("unicode_escape")) for (h, v) in conn.headers.items(multi=True)]` or 
`[(h + ":", repr(v)[1:-1]) for (h, v) in conn.headers.items(multi=True)]`

If we use pathoc as @mhils suggested `pathoc -c example.com:80 localhost:8080 'get:/:u"foo\tbar"'`:
![2018-01-03 17-06-44](https://user-images.githubusercontent.com/20267977/34525693-813c9c00-f0a8-11e7-9f06-83d62eeed84f.png)

What do you think?
