### ISSUE TITLE
mitmproxy sysinfo: show git tag/ref/commit

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#1848]
It would be nice if `mitmproxy --sysinfo` would also display the current git tag/ref/commit when running from source. Currently only `0.19` is displayed, which makes it a bit undeterministic what code is actually running. We can probably reuse some code from rtool here.

**Comment by mhils** [comment]
👍 

On that note, have we considered merging `--sysinfo` into `--version` ?

**Comment by dwfreed** [comment]
> On that note, have we considered merging --sysinfo into --version ?

doit
