### ISSUE TITLE
mitmproxy crash when viewing 

### ISSUE THREAD

**Issue by azixMcAze** [mitmproxy/mitmproxy#1849]
mitmproxy crash when inspecting some http requests. I saved one of the offending request in a file.

##### Steps to reproduce the problem:

1. Put this in a file and load it in mitmproxy :
> `2209:8:response,654:6:reason,4:Crée,13:timestamp_end,17:1481577761.663623^12:http_version,8:HTTP/1.1,11:status_code,3:201#15:timestamp_start,17:1481577761.655837^7:headers,299:30:6:Server,17:Apache-Coyote/1.1,]35:27:Access-Control-Allow-Origin,1:*,]58:28:Access-Control-Allow-Methods,22:GET, POST, DELETE, PUT,]48:28:Access-Control-Allow-Headers,12:Content-Type,]36:12:Content-Type,16:application/json,]24:14:Content-Length,3:183,]40:4:Date,29:Mon, 12 Dec 2016 21:22:41 GMT,]]7:content,183:{"kind":null,"date":null,"zone":null,"subzone":null,"productId":"dc16bb53-8ecb-475f-9cf2-505ec2198406.json","content":"kind=test&zone=OR1&subzone=OR1&date=2016-12-12%2022%3A22%3A41Z"},}4:type,4:http,5:error,0:~6:marked,5:false!7:version,13:1:0#2:18#1:2#]11:client_conn,215:15:ssl_established,5:false!10:clientcert,0:~13:timestamp_end,17:1481577762.199529^7:address,53:7:address,20:9:127.0.0.1,5:53415#]8:use_ipv6,5:false!}15:timestamp_start,17:1481577761.304023^19:timestamp_ssl_setup,0:~}2:id,36:03f12262-6ea4-4c97-b2f7-8a6abdd1de4a,11:intercepted,5:false!7:request,706:9:is_replay,5:false!4:port,4:8080#12:stickycookie,5:false!13:timestamp_end,17:1481577761.367619^4:path,37:/log_api/api/sessions/666667/products,15:timestamp_start,17:1481577761.365294^7:headers,294:97:6:Accept,84:application/json, application/xml, text/json, text/x-json, text/javascript, text/xml,]37:10:User-Agent,19:RestSharp/105.1.0.0,]53:12:Content-Type,33:application/x-www-form-urlencoded,]23:14:Content-Length,2:62,]24:4:Host,13:10.21.255.200,]36:15:Accept-Encoding,13:gzip, deflate,]]7:content,62:kind=test&zone=OR1&subzone=OR1&date=2016-12-12%2022%3A22%3A41Z,6:method,4:POST,4:host,13:10.21.255.200,17:first_line_format,8:relative,12:http_version,8:HTTP/1.1,6:scheme,4:http,10:stickyauth,5:false!}11:server_conn,426:15:ssl_established,5:false!14:source_address,56:7:address,23:11:10.57.11.92,5:53477#]8:use_ipv6,5:false!}13:timestamp_end,17:1481577762.199249^7:address,57:7:address,24:13:10.21.255.200;4:8080#]8:use_ipv6,5:false!}4:cert,0:~3:sni,0:~15:timestamp_start,17:1481577761.447825^19:timestamp_ssl_setup,0:~10:ip_address,57:7:address,24:13:10.21.255.200,4:8080#]8:use_ipv6,5:false!}3:via,0:~19:timestamp_tcp_setup,16:1481577761.44925^}}`
2. open this flow with the key enter
3. mitmproxy crashes with the following error :

> Traceback (most recent call last):
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/master.py", line 482, in run
>     self.loop.run()
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
>     self._run()
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/main_loop.py", line 376, in _run
>     self.event_loop.run()
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/main_loop.py", line 682, in run
>     self._loop()
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/main_loop.py", line 719, in _loop
>     self._watch_files[fd]()
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/raw_display.py", line 393, in <lambda>
>     event_loop, callback, self.get_available_raw_input())
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/raw_display.py", line 493, in parse_input
>     callback(processed, processed_codes)
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/main_loop.py", line 403, in _update
>     self.process_input(keys)
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/main_loop.py", line 503, in process_input
>     k = self._topmost_widget.keypress(self.screen_size, k)
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/window.py", line 86, in keypress
>     k = super(self.__class__, self).keypress(size, k)
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/container.py", line 1128, in keypress
>     return self.body.keypress( (maxcol, remaining), key )
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/flowlist.py", line 385, in keypress
>     return urwid.ListBox.keypress(self, size, key)
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/urwid/listbox.py", line 987, in keypress
>     key = focus_widget.keypress((maxcol,),key)
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/flowlist.py", line 238, in keypress
>     self.master.view_flow(self.flow)
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/master.py", line 577, in view_flow
>     flowview.FlowViewHeader(self, flow),
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/flowview.py", line 112, in __init__
>     hostheader=self.master.options.showhost
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/common.py", line 463, in format_flow
>     return flowcache.get(raw_format_flow, tuple(sorted(d.items())))
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/utils.py", line 32, in get
>     ret = gen(*args)
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/common.py", line 394, in raw_format_flow
>     resp.append(fcol(f["resp_reason"], ccol))
>   File "/usr/local/Cellar/mitmproxy/0.18.2_1/libexec/lib/python2.7/site-packages/mitmproxy/console/common.py", line 113, in fcol
>     s = six.text_type(s)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 2: ordinal not in range(128)

##### Any other comments? What have you tried so far?

Replacing "Crée" with "Cree" in the file before loading it prevents the crash

##### System information

> Mitmproxy version: 0.18.2
> Python version: 2.7.12
> Platform: Darwin-14.5.0-x86_64-i386-64bit
> SSL version: OpenSSL 1.1.0c  10 Nov 2016
> Mac version: 10.10.5 ('', '', '') x86_64

OSX in French

**Comment by mhils** [comment]
Thanks for the report! This works fine for me on master and will be fixed with the next release. :smiley:
