### ISSUE TITLE
can you upload the source to pypi again?

### ISSUE THREAD

**Issue by cytec** [mitmproxy/mitmproxy#1853]
I'm currently working on a Synology SPK for mitmproxy which will allow users of Synology Devices an easy installation. more info on that toppic can be found here: https://github.com/SynoCommunity/spksrc/issues/2554 Sadly i noticed that you've stopped uploading the source code to pypi with version 0.15. Since spksrc (the framework im using) skips wheel files because pip isn't able to distinguish between the different types of wheels (pure-python, manylinux etc) as a temp fix for debugging i linked to the github release but it would be nice to see the source in pypi again.

Thank you!

**Comment by mhils** [comment]
Hi,

We do not plan to publish source distributions on pypi, as those would be
picked up by pip2. Our next release will be Python 3 only and we prefer to
have a clear "no distribution found" message for Python 2 users then. Sorry.

cytec <notifications@github.com> schrieb am Di., 13. Dez. 2016, 21:04:

**Comment by cytec** [comment]
well i guess we have to go with the github source linking then.
Thanks anyway!

**Comment by mhils** [comment]
If that works for you, that'd be great - thanks. We'd be willing to reconsider things if this poses insurmountable obstacles, but right now the benefits of not having a source distribution clearly outweigh the costs of it, especially given the fact that a source distribution can be easily downloaded from GitHub. Thanks for your understanding!
