### ISSUE TITLE
EINVAL [Error 22] when binding to loopback address

### ISSUE THREAD

**Issue by noxrnet** [mitmproxy/mitmproxy#1854]
mitmproxy and mitmdump error with Errno 22 (EINVAL) when proxying connections if bound to the loopback address (127.0.0.1).

##### Steps to reproduce the problem:

1. Using mitmdump bound to 127.0.0.1
```
# mitmdump -b 127.0.0.1 -p 8000
Proxy server listening at http://127.0.0.1:8000
127.0.0.1:33764: clientconnect
127.0.0.1:33764: GET http://www.example.com/
 << Server connection to www.example.com:80 failed: Error connecting to "www.example.com": [Errno 22] Invalid argument
127.0.0.1:33764: clientdisconnect
```
2. Connecting with wget
```
# http_proxy=http://127.0.0.1:8000 wget http://www.example.com
--2016-12-14 08:29:09--  http://www.example.com/
Connecting to 127.0.0.1:8000... connected.
Proxy request sent, awaiting response... 502 Bad Gateway
2016-12-14 08:29:10 ERROR 502: Bad Gateway.
```
3. However, if you bind to 0.0.0.0 or a specific interface IP address it works as expected:
```
# mitmdump -b 0.0.0.0 -p 8000
Proxy server listening at http://0.0.0.0:8000
127.0.0.1:33766: clientconnect
127.0.0.1:33766: GET http://www.example.com/
              << 200 OK 1k
127.0.0.1:33766: clientdisconnect
```
```
# http_proxy=http://127.0.0.1:8000 wget http://www.example.com
--2016-12-14 08:31:36--  http://www.example.com/
Connecting to 127.0.0.1:8000... connected.
Proxy request sent, awaiting response... 200 OK
Length: 1270 (1.2K) [text/html]
Saving to: ‘index.html.5’

index.html.5                            100%[============================================================================>]   1.24K  --.-KB/s    in 0.001s

2016-12-14 08:31:37 (2.32 MB/s) - ‘index.html.5’ saved [1270/1270]
```
##### System information
Mitmproxy version: 0.18.2
Python version: 2.7.12
Platform: Linux-4.4.0-53-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by dwfreed** [comment]
This is a misfeature in 0.18.2 and older; I fixed it in the 0.18.x branch, but @mhils never made a release, and now the 0.19 release is a couple days away.  If you can't wait, you can grab a snapshot from https://snapshots.mitmproxy.org/v0.19/ or install from git (it's worth noting that 0.19 is the first version that is python 3 only).

**Comment by mhils** [comment]
@Kriechi is tasked with doing the next release, whether that is 0.18.2 or 0.19 :-)

**Comment by mhils** [comment]
(Closing this here as the actual issue is fixed - thanks for the report though!)
