### ISSUE TITLE
Options documentation

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#1866]
We now have a good, centralised account of all mitmproxy's options, along with the associated types. We should use this to generate Options documentation, and add a function to dump all default options in the terminal.

**Comment by vduddu** [comment]
Hey, I am interested to write the documentation for all the options of the tool and add a function to the source code to print them to the screen. Could you just elaborate and confirm the issue once so that I could work accordingly?

**Comment by cortesi** [comment]
```mitmdump --options``` is the canonical options documentation.
