### ISSUE TITLE
mitmproxy-1.0.0-windows-installer.exe Immediately Hangs

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#1885]
##### Steps to reproduce the problem:

Double click on mitmproxy-1.0.0-windows-installer.exe. No elevate prompt requested. Cursor shows busy (hour glass) forever. Same issue from admin mode. Same after reboot.

##### System information

Windows 10 Insider 14986 (slow ring).

**Comment by mhils** [comment]
Thanks for the report. I just tested this again on my system (Win10, non-insider) and on a Windows 7 VM, both machines worked fine. What happens if you invoke `mitmproxy-1.0.0-windows-installer.exe --help` from a command prompt?

**Comment by BSalita** [comment]
I've tested on three computers. All have same SHA256. Tested with antivirus (Windows Defender, WebRoot) both on and off.

A) Windows 10 14896 hangs when invoking mitmproxy-1.0.0-windows-installer.exe. Also with --help switch.

B) Windows 10 non-Insider works great!

C) Windows 10 14896 tablet hangs same as A) above.

Yes, perhaps an incompatibility with 14896 (slow ring).

**Comment by mhils** [comment]
Thanks for testing!

If the first installer screen does not even show up, this is either an InstallBuilder or a Windows Insider issue. We're pretty new to this, but I found https://installbuilder.bitrock.com/docs/installbuilder-userguide/ar01s21.html and built a debug installer: https://uploads.maximilianhils.com/2016-12/mitmproxy-1.0-windows-installer.exe

Could you check if `--debugtrace/--syncdebugtrace debug.txt` or `--enable-debugger` provide anything useful with that?

**Comment by BSalita** [comment]
Issue remains same with either --debugtrace/--syncdebugtrace debug.txt or --enable-debugger. There's no new files created in current directory of install. All combinations of switches hang.

**Comment by mhils** [comment]
Thanks. So if I understand you correctly it just gets stuck right away?
Could you run the installer with [procmon](https://technet.microsoft.com/de-de/sysinternals/processmonitor.aspx) running in the background and check if there's anything happening?
