### ISSUE TITLE
mitmweb: --host Not Working

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#1888]
##### Steps to reproduce the problem:

mitmweb is not respecting --host. All hosts are ips, never domain names. "showhost" is displayed at bottom of mitmweb web page.

##### Any other comments? What have you tried so far?

I had reported this long ago. The issue was switches weren't implemented. Now they are but --host isn't working anyway.

##### System information

Mitmproxy version: 1.0.0
Python version: 3.5.2
Platform: Windows-10-10.0.14393
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 10 10.0.14393  Multiprocessor Free

**Comment by mhils** [comment]
As always, thanks for the great report. We really appreciate having someone who consistently reports good Windows and mitmweb issues 😊

Regarding the actual issue: This needs to be implemented [here](https://github.com/mitmproxy/mitmproxy/blob/27353388157adda3d22000fcf146fe599f4f9a6f/web/src/js/flow/utils.js#L58).

**Comment by AvaisP** [comment]
Hi, I'd like to work on this. I'm still going through the source code though so some more time would be appreciated. Thanks!

**Comment by mhils** [comment]
We now default to displaying pretty_host, but we still need to implement the logic to actually consider `--host`.

**Comment by FrobozzElectric** [comment]
I know this is closed, but I'm still seeing the issue in the most recent release. If I'm to understand the above comment correctly, mitmweb should now be showing pretty_host all the time, but that's not the case for me.

**Comment by kira0204** [comment]
@mhils Is this still an issue?

**Comment by tess7** [comment]
@mhils @kira0204
Hello everybody, I have the same problem reported in this ticket. Is there anything new?

Thanks
Tess

**Comment by kira0204** [comment]
Hi @tess7,
The issue was fixed as we are using `pretty_host` for now. What is the exact issue you are facing? also do post the output of `mitmproxy --version`, thanks
