### ISSUE TITLE
Segfault when using binary

### ISSUE THREAD

**Issue by shark0der** [mitmproxy/mitmproxy#1890]
##### Steps to reproduce the problem:

1. Download mitmproxy-1.0.0-linux.tar.gz from https://github.com/mitmproxy/mitmproxy/releases
2. tar xf mitmproxy-1.0.0-linux.tar.gz
3. Run it:
```
$ ./mitmweb 
[1]    17398 segmentation fault (core dumped)  ./mitmweb
```

##### Any other comments? What have you tried so far?
Installing using `pip3 install https://github.com/mitmproxy/mitmproxy/archive/v1.0.zip` worked.

##### System information (for the pip installed version).
```
Mitmproxy version: 1.0.0
Python version: 3.5.2
Platform: Linux-4.4.0-57-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
```

**Comment by cwalv** [comment]
Seeing this too
```
[4848549.095430] mitmproxy[30409]: segfault at 0 ip 00007fc4ec7f5b96 sp 00007ffd3cd413f8 error 4 in libc-2.23.so[7fc4ec76b000+1bf000]
[4848692.767094] mitmweb[30478]: segfault at 0 ip 00007f7dafc0cb96 sp 00007ffde8bf2ee8 error 4 in libc-2.23.so[7f7dafb82000+1bf000]
```

**Comment by mhils** [comment]
Thanks for the report. @cwalv, which OS are you on?

**Comment by mhils** [comment]
Ugh. Possibly related: https://github.com/pyinstaller/pyinstaller/issues/2232

**Comment by mhils** [comment]
Ok, I think I fixed it. Can you guys check if https://snapshots.mitmproxy.org/v1.0.0/mitmproxy-1.0.0dev0003-0xg3819876-linux.tar.gz works for you?

**Comment by mhils** [comment]
I was able to reproduce this on 16.04, and fortunately the fixed binaries don't exhibit this issue. I updated the release.

Thanks again for the report!
