### ISSUE TITLE
Connection to h2o.examp1e.net failed

### ISSUE THREAD

**Issue by chhsiao90** [mitmproxy/mitmproxy#1891]
It's related to #1498 

##### Steps to reproduce the problem:

1. mitmproxy --http2
2. connect to https://h2o.examp1e.net by ```Firefox```
3. Firefox show that connection failed

##### Any other comments? What have you tried so far?
I know that there are some website that suffer from receiving priority frame over idle/closed stream problem.
But I think that h2o.examp1e.net fixed that problem that I had test it by hyper-h2 client with code post at #1745.
I'm not very familiar about how mitmproxy transform client h2 frame to server,
so I still cannot reproduce by use hyper-h2 client.

##### System information
Mitmproxy version: 1.0.0
Python version: 3.5.2
Platform: Darwin-16.1.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.1 ('', '', '') x86_64

**Comment by Kriechi** [comment]
Thanks @chhsiao90 for reporting this issue.
Here is a script to reproduce the bug:
```python
import certifi
import h2.connection
import h2.events

import errno
import socket
import ssl
import time

SERVER_NAME = 'h2o.examp1e.net'

socket.setdefaulttimeout(2)

c = h2.connection.H2Connection()
c.initiate_connection()

ctx = ssl.create_default_context(cafile=certifi.where())
ctx.set_alpn_protocols(['h2', 'http/1.1'])
ctx.set_npn_protocols(['h2', 'http/1.1'])

s = socket.create_connection((SERVER_NAME, 443))
s = ctx.wrap_socket(s, server_hostname=SERVER_NAME)

s.sendall(c.data_to_send())

c.prioritize(3, weight=201, depends_on=0, exclusive=False)
c.prioritize(5, weight=101, depends_on=0, exclusive=False)
c.prioritize(7, weight=1, depends_on=0, exclusive=False)
c.prioritize(9, weight=1, depends_on=7, exclusive=False)
c.prioritize(11, weight=1, depends_on=3, exclusive=False)

headers = [
    (':method', 'GET'),
    (':path', '/'),
    (':authority', SERVER_NAME),
    (':scheme', 'https'),
]
c.send_headers(1, headers, end_stream=True, priority_depends_on=11, priority_weight=31)

s.sendall(c.data_to_send())


while True:
    data = s.recv(65536 * 256)
    if not data:
        break

    try:
        events = c.receive_data(data)
        s.sendall(c.data_to_send())
    except:
        break

    for event in events:
        print(event)
```

As you can see, this is again related to PRIORITY information being handled improperly.
I don't see a reason why sending such HEADERS should produce an error.

Just to confirm, maybe @Lukasa could offer an opinion if the shown example should yield a valid HTTP/2 request+response, or if the server is allowed to simply terminate the connection with: `'invalid stream id in HEADERS frame'`.

**Comment by Lukasa** [comment]
This appears to be related to the previous h2o issue we had whereby h2o considered PRIORITY frames to automatically open that stream ID. Again, this is a perfectly valid frame sequence as far as I can tell. Should have been resolved by h2o/h2o#1136, so I suspect that this is just a matter of H2O not having seen a release yet.

Best way to check is to try to reproduce against the H2O master branch. I can try this tonight if no one beats me to it.

**Comment by Kriechi** [comment]
The server responds with `('server', 'h2o/2.1.0-DEV')` - not sure though how recent this dev-version might be.

**Comment by Lukasa** [comment]
So, I think it's old. I just built master from what I think is the current tip (25c1ab8e79f86618d8c050e9a186f96e05fdd215), and running your script against it produces no error output on either side. So I think h2o is just running a non-master version of the server.

**Comment by chhsiao90** [comment]
Thanks @Kriechi and @Lukasa !

I had wrong test client that sent priority frame with same stream id before the headers frame,
so I cannot reproduce the problem through the test client.
So for this case, the actual problem is that the server implementation receive headers frame that had lower stream id then the priority frame that had been sent earlier.

If h2o had fixed that and it should just wait for server to update the latest version.
Then there is no problem on this issue.
I'm just afraid that there is some other issue that was not related to priority frame issue.
