### ISSUE TITLE
iOS docs certinstall link no longer valid

### ISSUE THREAD

**Issue by dweinstein** [mitmproxy/mitmproxy#1898]
It appears the link is no longer functional for documentation on iOS cert installation.

possible alternative:

- http://web.archive.org/web/20150920082614/http://kb.mit.edu/confluence/pages/viewpage.action?pageId=152600377
- http://jasdev.me/intercepting-ios-traffic

##### Steps to reproduce the problem:

1. go to http://docs.mitmproxy.org/en/stable/certinstall.html#ios
2. click link for ios http://kb.mit.edu/confluence/pages/viewpage.action?pageId=152600377
3. user presented w/ login prompt for MIT hermes:

<img width="928" alt="screen shot 2016-12-28 at 9 22 33 am" src="https://cloud.githubusercontent.com/assets/794478/21523799/35c4b610-ccdf-11e6-823a-16b5d2324586.png">

**Comment by dweinstein** [comment]
Thoughts on having a native version of the instructions stored/linked directly in the docs so as not to depend on an external resource?

**Comment by mhils** [comment]
@dweinstein: Thanks. We had that, but swapped it out to make maintenance simpler. This is not the first time where external linking bites us with that, and given that this is a rather central feature I feel we should host instructions ourselves again. Anyway, this needs to be fixed. :)
