### ISSUE TITLE
Configuration file does not work for some options

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#1899]
In mitmproxy 0.18, I could have a `--conf` with a line like this:

```
reverse = http://server01.example.net:1181
```

which caused mitmproxy to start in reverse proxy mode.

But I can’t seem to find an equivalent in mitmproxy 1.0:

```
$ mitmproxy --conf tools/mitmproxy/api.yaml 
Traceback (most recent call last):
  File "/home/vasiliy/env/mitmproxy/bin/mitmproxy", line 11, in <module>
    sys.exit(mitmproxy())
  File "/home/vasiliy/env/mitmproxy/lib/python3.5/site-packages/mitmproxy/tools/main.py", line 68, in mitmproxy
    console_options.load_paths(args.conf)
  File "/home/vasiliy/env/mitmproxy/lib/python3.5/site-packages/mitmproxy/optmanager.py", line 245, in load_paths
    self.load(txt)
  File "/home/vasiliy/env/mitmproxy/lib/python3.5/site-packages/mitmproxy/optmanager.py", line 232, in load
    self.update(**data)
  File "/home/vasiliy/env/mitmproxy/lib/python3.5/site-packages/mitmproxy/optmanager.py", line 141, in update
    raise KeyError("No such option: %s" % k)
KeyError: 'No such option: reverse'
```

So I have to specify `--reverse` on the command line every time, which is inconvenient.

**Comment by coryhbrt2** [comment]
If you are talking to me I can give you my # 33776801326 message me and  can assist you on my end. I have access to computer and Internet

**Comment by coryhbrt2** [comment]
3376801326 my #

**Comment by mhils** [comment]
I removed two spam comments in this issue. Regarding your question, something along those lines should work. I'll leave this issue open for documentation.
```
mode = "reverse"
upstream_server = "http://example.com/"
```

**Comment by vfaronov** [comment]
@mhils Doesn’t work for me. With that literal config, I get:

```
$ mitmproxy --conf test1.conf 
mitmproxy: Config error - no keys found.
```

If I rewrite it as a YAML like this:

```
$ cat test1.yaml 
mode: reverse
upstream_server: http://example.com/

$ mitmproxy --conf test1.yaml
```

then mitmproxy starts up in regular mode, and rejects non-proxy requests:

```
$ curl -s localhost:8080/
<html>
            <head>
                <title>400 Bad Request</title>
            </head>
            <body>HttpException('Invalid HTTP request form (expected: authority or absolute, got: relative)',)</body>
        </html>
```

Tried with both 1.0.1 and master.

**Comment by mhils** [comment]
Thanks for looking into this. This seems to be an issue with how we currently handle options. I haven't verified it, but I think we override it [here](https://github.com/mitmproxy/mitmproxy/blob/9a88a2fdea727c6ab4c20926527ef8a4abae0f40/mitmproxy/tools/cmdline.py#L176).

**Comment by mhils** [comment]
This extends to all options with have a `non-None` default value. 
Fixing those should be a relatively easy, so I'm marking this issue as good-first-contribution for cases. 😃 

see also: https://discourse.mitmproxy.org/t/not-all-config-options-applied-via-mitmproxy-mitmproxy-conf/332

**Comment by ujjwal96** [comment]
@mhils I'd like to work on this

**Comment by mhils** [comment]
@ujjwal96: @cortesi started working on related functionality two days ago. Please talk to him first to coordinate.

**Comment by ujjwal96** [comment]
I'll work on a different issue for now then :slightly_smiling_face:

**Comment by cjthompson** [comment]
I've been testing a few configuration options and so far I've noticed that all Boolean config options don't get applied, but others, like strings, do.

For example:
```yaml
console_focus_follow: true
showhost: true
ssl_insecure: true
console_palette: solarized_dark
```

With that config, the palette does get applied on start, but none of the booleans do.

**Comment by mhils** [comment]
We're fixing this in #2100.

**Comment by cortesi** [comment]
This should now be fixed - we've had a complete, principled revamp of how options are managed and applied. See "mitmdump --options" for a full record of all options, their types, and defaults.
