### ISSUE TITLE
Errno 111. Connection refused.

### ISSUE THREAD

**Issue by farmdve** [mitmproxy/mitmproxy#1908]
Hello,

I have setup the following environment. I have a dns proxy server and mitmproxy sitting on one machine. The device(whose traffic is to be captured)'s DNS server is set to my own DNS server. There I spoof all IP addresses to return the (public ip)address of mitmproxy. 

I run mitmproxy as such

> mitmproxy -T --host

When I attempt to visit a website, I get this
![image](https://cloud.githubusercontent.com/assets/7746376/21581914/95112d3a-d04d-11e6-84ef-2ba3f46dd28a.png)

So I see that mitmproxy correctly identified the domain it should connect to, however in the redacted part, the IP mitmproxy connects to is the proxy machine itself. So what can I do here so that it connects to the real domain?

**Comment by mhils** [comment]
Redirection and transparent mode don't mix. You're running in the problem
described in
http://docs.mitmproxy.org/en/stable/modes.html#transparent-proxy. If you
absolutely want to do DNS spoofing, there's a script in the examples folder
to accomplish that. :)

**Comment by fredericgermain** [comment]
For lazy people like me, the cited [example script link](https://github.com/mitmproxy/mitmproxy/blob/main/examples/contrib/dns_spoofing.py)

And I just wanted to use my small message to also say thanks for the awesome mitmproxy :)
