### ISSUE TITLE
mitmproxy won't write MITMPROXY_SSLKEYLOGFILE ssl log file if it's started with sudo

### ISSUE THREAD

**Issue by larryhou** [mitmproxy/mitmproxy#1913]
##### Steps to reproduce the problem:

1. Run in Terminal.app `export MITMPROXY_SSLKEYLOGFILE=~/Downloads/mitm.log`
2. Run in Ternimal.app`sudo mitmproxy -p 8888 --follow`
3. Browse  webpages with `https` enabled, then no related logs would be written in to `~/Downloads/mitm.log`

##### Any other comments? What have you tried so far?

All is fine without `sudo`.

##### System information

Mitmproxy version: 1.0.1
Python version: 3.6.0
Platform: Darwin-16.4.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.3 ('', '', '') x86_64

**Comment by mhils** [comment]
`~` is user-dependent, so if you `sudo`, you'll probably find stuff in /root?

**Comment by larryhou** [comment]
@mhils it's the same if I use `/Users/larryhou/Downloads/mitm.log`, or relative path

**Comment by mhils** [comment]
http://stackoverflow.com/questions/8633461/how-to-keep-environment-variables-when-using-sudo

**Comment by larryhou** [comment]
@mhils `sudo -E mitmproxy -p 8888 --follow --transparent` solve my problem, thanks
