### ISSUE TITLE
Running in python 3.4 asks for typing module

### ISSUE THREAD

**Issue by CMCDragonkai** [mitmproxy/mitmproxy#1914]
0.18.2 asks for typing module even though it is installable in Python 3.4. See this issue: https://github.com/game-recon/obozrenie/issues/4

Shouldn't there be a failure to install on python 3.4 if it cannot work on 3.4?

**Comment by mhils** [comment]
We don't support 3.4 at all - sorry.
AFAIK there's no way to make the installation on 2.7 or 3.4 fail right away with wheels, is there?

**Comment by CMCDragonkai** [comment]
If there's no way to make it fail, perhaps an easy to understand error message upon trying to run it.

**Comment by mhils** [comment]
What do you see if you run `mitmproxy`?
