### ISSUE TITLE
Transparent mode failure: RuntimeError on sierra

### ISSUE THREAD

**Issue by mohitmun** [mitmproxy/mitmproxy#1921]
When I try to run mitmproxy --host -T it gives:

> Warn:  192.168.43.88:50510: Transparent mode failure: RuntimeError("Error getting pfctl state: CalledProcessError(1, ('sudo', '-n', '/sbin/pfctl', '-s','state')))

How can I solve it?

**Comment by mhils** [comment]
Did you follow step six in http://docs.mitmproxy.org/en/stable/transparent/osx.html?

**Comment by mohitmun** [comment]
Yes

**Comment by mhils** [comment]
What's the output of `/sbin/pfctl -s state` for you?

**Comment by mohitmun** [comment]
`pfctl: /dev/pf: Permission denied`

**Comment by mohitmun** [comment]
I modified my sudoer file temorary to give all user to all command. after doing that it stared giving me 

> Transparent mode failure:( could not resolve original destination.)

**Comment by mhils** [comment]
http://docs.mitmproxy.org/en/stable/transparent.html
http://docs.mitmproxy.org/en/stable/howmitmproxy.html

**Comment by wifilinker** [comment]
Running on OS X 10.13.3 and having added `ALL ALL=NOPASSWD: /sbin/pfctl -s state` to the end of `/etc/sudoers`. When i run `/sbin/pfctl -s state` i still get `pfctl: /dev/pf: Permission denied`. I have done the transparent mode instructions through a couple of times, but still get "Could not resolve original destination" error. Any guides to get it running on latest osx?

**Comment by michaelwclark** [comment]
Any luck on this? I'm still having the same issues.
