### ISSUE TITLE
No data capture in proxy

### ISSUE THREAD

**Issue by tehseensagar** [mitmproxy/mitmproxy#1927]
Greetings,

I just setup mitmproxy according to installation doc and ran following cmd.

sysctl -w net.ipv4.ip_forward=1

iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 443 -j REDIRECT --to-port 8080

iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 8080

./mitmproxy -T --host -e

It start but no data show as in opened windows. Any idea what am I doing wrong.

Regards

**Comment by Kriechi** [comment]
What OS / Linux kernel are you using?
Which mitmproxy version are you using?
How does your device setup look like?
Can you see the traffic with tcpdump or wireshark?
