### ISSUE TITLE
mitmdump -  'HTTPRequest' object has no attribute 'body'

### ISSUE THREAD

**Issue by Miller1990** [mitmproxy/mitmproxy#1933]
After updating the mitdump version from version 0.8.12 to version 1.0.2 return me the follow error. I'm using the API  (request, response) of mitmdump.

Thank you

Is possible go back to an olde version ? 

    
 "is_body": flow.response.body.decode('utf-8', errors='ignore').encode('utf-8'),
AttributeError: 'HTTPResponse' object has no attribute 'body'
    mitmdump --version : 1.0.2

**Comment by mhils** [comment]
You are looking for `.content`, `.body` was deprecated quite a while ago.
http://docs.mitmproxy.org/en/stable/scripting/api.html#mitmproxy.http.HTTPRequest
