### ISSUE TITLE
Question regarding certificates.

### ISSUE THREAD

**Issue by farmdve** [mitmproxy/mitmproxy#1943]
I've been reading up on http://docs.mitmproxy.org/en/stable/certinstall.html and there are 4 certificate files.

mitmproxy-ca.pem, mitmproxy-ca-cert.pem, mitmproxy-ca-cert.p12, mitmproxy-ca-cert.cer

Since I am not very familiar with crypto, I wanted to ask, for Windows in particular, if the private key is required in order to install the certificate and for mitmproxy to function correctly?

mitmproxy-ca-cert.p12 is a file that contains both public and private keys, but is the private key really required on Windows to install as a Trusted Root CA, or can I also use mitmproxy-ca-cert.cer which I presume is just the public key?

**Comment by Kriechi** [comment]
The CA has to be installed on each client (in your case a Windows machine).
In that case only the public key is required on the client and needs to be trusted.

The private key is only needed by mitmproxy to generate new certs, e.g., your server machine running mitmproxy.
