### ISSUE TITLE
Use existing urlencoding conventions when re-encoding edited form

### ISSUE THREAD

**Issue by mame82** [mitmproxy/mitmproxy#1946]
mitmproxy 1.0.2 crashes trying to edit form data of facebook ajax POST request to facebook.com/ajax/updatestatus.php

##### Steps to reproduce the problem:

1. run mitmproxy with
```mitmproxy -p <listenport> -T --cadir <dir with cert> --host -f "updatestatus | sl/password" -i updatestatus```
2. Post a message on facebook (acces https://www.facebook.com/ajax/updatestatus.php)
3. Try to edit the intercepted flow body (key e) using form data view (key f)
4. results in crash

Crash trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/master.py", line 292, in run
    self.loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.5/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/window.py", line 84, in keypress
    k = super().keypress(size, k)
  File "/usr/local/lib/python3.5/dist-packages/urwid/container.py", line 1116, in keypress
    return self.footer.keypress((maxcol,),key)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/statusbar.py", line 155, in keypress
    return self.master.ab.keypress(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/statusbar.py", line 108, in keypress
    self.prompt_execute(k)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/statusbar.py", line 133, in prompt_execute
    msg = p(txt)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/statusbar.py", line 31, in __call__
    return self.callback(txt, *self.args)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/flowview.py", line 415, in edit
    self.edit_form(message)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/flowview.py", line 351, in edit_form
    conn
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/master.py", line 352, in view_grideditor
    ge.make_help()
  File "/usr/local/lib/python3.5/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/master.py", line 144, in sig_push_view_state
    self.loop.draw_screen()
  File "/usr/local/lib/python3.5/dist-packages/urwid/main_loop.py", line 578, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/lib/python3.5/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/usr/local/lib/python3.5/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/widget.py", line 1750, in render
    canv = get_delegate(self).render(size, focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/container.py", line 1083, in render
    focus and self.focus_part == 'body')
  File "/usr/local/lib/python3.5/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/listbox.py", line 455, in render
    (maxcol, maxrow), focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/listbox.py", line 337, in calculate_visible
    self._set_focus_complete( (maxcol, maxrow), focus )
  File "/usr/local/lib/python3.5/dist-packages/urwid/listbox.py", line 702, in _set_focus_complete
    (maxcol,maxrow), focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/listbox.py", line 672, in _set_focus_first_selectable
    (maxcol, maxrow), focus=focus)
  File "/usr/local/lib/python3.5/dist-packages/urwid/listbox.py", line 340, in calculate_visible
    focus_widget, focus_pos = self.body.get_focus()
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/grideditor/base.py", line 223, in get_focus
    self.lst[self.focus]
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/grideditor/base.py", line 77, in __init__
    w = self.editor.columns[i].Display(v)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/grideditor/col_bytes.py", line 33, in Display
    return Display(data)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/console/grideditor/col_bytes.py", line 73, in __init__
    escaped = strutils.bytes_to_escaped_str(data)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/utils/strutils.py", line 72, in bytes_to_escaped_str
    raise ValueError("data must be bytes, but is {}".format(data.__class__.__name__))
ValueError: data must be bytes, but is str

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy

```

##### System information
Kali Linux (rollin)
current mitmproxy installed with pip3 (not from distribution package)

**Comment by lymanZerga11** [comment]
Seems quite similar to an issue addressed before #1901

**Comment by mame82** [comment]
According the stacktrace it indeed looks similar...could you reproduce the issue?

**Comment by mhils** [comment]
@mame82, can you still reproduce this on master? This should already be fixed.

**Comment by mame82** [comment]
I'm not able to test this at the moment. I'm going to report back next week

**Comment by mame82** [comment]
Tested the following version of mitmproxy:

```
# mitmproxy --version
Mitmproxy version: 2.0.0 (v1.0.1-45-g0022c810)
Python version: 3.5.3rc1
Platform: Linux-4.3.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
SSL version: OpenSSL 1.1.0c  10 Nov 2016
Linux distro: Kali kali-rolling kali-rolling
```

I can confirm that the crash, editing response body form data, is gone.

But another issue shows up in the exact same case, which is specific to facebook, but the cause seems to be mitmproxy itself:

Changing form fields "xhpc_message" and "xhpc_message_text" in requests to https://facebook.com/ajax/updatestatus.php (Triggered by posting new status) an error is returned from facebook.

Inspecting the POST  data, there's nothing like a checksum or something like that - instead the error is caused by wrong calculation of the new "content-length" request header.

This issue doesn't occur when post data is edited in "raw" mode.

Thus there still seems to be an encoding issue, using the "form" as edit method, which doesn't occur using "raw body" as edit method.

Unfortunately, I have no time to dive deeper into this, but maybe you can reproduce the issue.

My use case is a security talk, editing "raw body" is a working solution, but using "form" edit would be more comprehensible for the audience.

Thanks for your effort.

**Comment by mhils** [comment]
I tried to reproduce this, but no dice. The Content-Length header is always calculated properly for me. What exactly do you do to trigger this?

**Comment by mame82** [comment]
**Unmodified request to facebook.com/updatestatus.php**

Request header:
```
user-agent:       Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0                                                          
accept:           text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8                                                                   
accept-language:  de,en-US;q=0.7,en;q=0.3                                                                                                           
accept-encoding:  gzip, deflate, br                                                                                                                 
referer:          https://www.facebook.com/                                                                                                         
content-type:     application/x-www-form-urlencoded                                                                                                 
content-length:   1443  
..snip...
```

Request body:
```
...snip....
target_type:                    feed
xhpc_message:                   test
xhpc_message_text:              test
...snip...
```

**Modified Request using "raw body edit":**

Request header (2 bytes increased content length):
```
user-agent:       Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0                                                          
accept:           text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8                                                                   
accept-language:  de,en-US;q=0.7,en;q=0.3                                                                                                           
accept-encoding:  gzip, deflate, br                                                                                                                 
referer:          https://www.facebook.com/                                                                                                         
content-type:     application/x-www-form-urlencoded                                                                                                 
content-length:   1445     
...snip....
```

Request body (2 chars added):
```
...snip...
target_type:                    feed
xhpc_message:                   test1
xhpc_message_text:              test1
...snip...

```

HTTP Response:
content cutted out, but facebook accepts the posting    


**Modified request using "form edit" (same testcase):**

Request header (**43 bytes increased content length**)
```
user-agent:       Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0                                                          
accept:           text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8                                                                   
accept-language:  de,en-US;q=0.7,en;q=0.3                                                                                                           
accept-encoding:  gzip, deflate, br                                                                                                                 
referer:          https://www.facebook.com/                                                                                                         
content-type:     application/x-www-form-urlencoded                                                                                                 
content-length:   1486   

```

Request body (same change, 2 chars added):

```
...snip...
target_type:                    feed
xhpc_message:                   test1
xhpc_message_text:              test1
...snip...
```



HTTP Response:
content cutted out, but responds with error.

The response data sent by facebook is encoded with "br", but this shouldn't matter here.


Tested with updated kali and master repo of mitmproxy


```
# mitmproxy --version
Mitmproxy version: 2.0.0 (v1.0.1-45-g0022c810)
Python version: 3.5.3rc1
Platform: Linux-4.8.0-kali2-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
SSL version: OpenSSL 1.1.0c  10 Nov 2016
Linux distro: Kali kali-rolling kali-rolling

```

**Comment by mame82** [comment]
Forget to mention: I use the standard posting funtionality of the facebook webpage with a an authenticated testuser. Interception filter of mitmproxy is set to "updatestatus". I inspected all header fields and additional form data, but none of them depend on "xhpc_message_*" form data. So there's no server side content verification based on these values. As said, editing the two fields mentioned in "raw mode" works without issues. Hope you're able to reproduce this.

**Comment by mame82** [comment]
Anything new on this?

**Comment by nish21** [comment]
I was able to reproduce the error message on Facebook and confirm that the process resulted in a miscalculated content-length header, will look into it further.

**Comment by nish21** [comment]
In fact, the content-length header shows erroneous value even without any editing.
This is the headers from the intercepted flow of "updatestatus"
```
:authority:       www.facebook.com                                                       
user-agent:       Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0   
accept:           text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8        
accept-language:  en-US,en;q=0.5                                                         
accept-encoding:  gzip, deflate                                                          
content-type:     application/x-www-form-urlencoded                                      
referer:          https://www.facebook.com/                                              
content-length:   1437                                                                   
```
I then press 'e' and 'f' (form edit). I don't change anything, i press 'q' and exit the edit mode.
Content-length is changed
````:authority:       www.facebook.com                                                       
user-agent:       Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0   
accept:           text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8        
accept-language:  en-US,en;q=0.5                                                         
accept-encoding:  gzip, deflate                                                          
content-type:     application/x-www-form-urlencoded                                      
referer:          https://www.facebook.com/                                              
content-length:   1478                                                                   
```
Can @mame82 confirm this?

**Comment by Kriechi** [comment]
I'm able to reproduce this:

1. run `mitmproxy`, set intercept to: `example`
2. run `curl -k --proxy localhost:8080 'https://www.example.com/' -H 'Content-Type: application/x-www-form-urlencoded' --data 'foo[bar]'`
3. select new flow in mitmproxy: `Enter`
4. observe `content-length` is 8
5. edit forms data: `e` -> `f`
6. change nothing, just quit: `q`
7. observe `content-length` changed to 13

IMO the `content-length` should not change.

**Comment by mame82** [comment]
@nish21 @Kriechi 

I was able to dive into the root cause(s) of the problem, but a site-package is involved.

The calculation of content-length header for request edited in form mode is done here 
[here](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/http/message.py#L127).
```

    def set_content(self, value):
        if value is None:
            self.raw_content = None
            return
        if not isinstance(value, bytes):
            raise TypeError(
                "Message content must be bytes, not {}. "
                "Please use .text if you want to assign a str."
                .format(type(value).__name__)
            )
        ce = self.headers.get("content-encoding")
        try:
            self.raw_content = encoding.encode(value, ce or "identity")
        except ValueError:
            # So we have an invalid content-encoding?
            # Let's remove it!
            del self.headers["content-encoding"]
            self.raw_content = value
        self.headers["content-length"] = str(len(self.raw_content))
```
This is the cause of the problem described by @Kriechi 

Instead of `'foo[bar]'` self.raw_content contains URL encoded data, which looks like `b'foo%5Bbar%5D'` which is 13 bytes in length. As the content-length of content-type 'application/x-www-form-urlencoded' should be calculated based **on the not URL encoded data** this behaviour is wrong. In context of mitmproxy `raw_content` is meant to hold encoded data and `content` is meant to hold unencoded data.

And this is the next problem: the data in `content` is URL encoded, too. This is caused by by the [following line in request.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/http/request.py#L376).
```

    def _set_urlencoded_form(self, form_data):
        """
        Sets the body to the URL-encoded form data, and adds the appropriate content-type header.
        This will overwrite the existing content if there is one.
        """
        self.headers["content-type"] = "application/x-www-form-urlencoded"
        self.content = mitmproxy.net.http.url.encode(form_data).encode()
```

This behavior could possibly be fixed with something like this (if content-length is calculated based on `self.content` instead of `self.raw_content`):


```
    def _set_urlencoded_form(self, form_data):
        """
        Sets the body to the URL-encoded form data, and adds the appropriate content-type header.
        This will overwrite the existing content if there is one.
        """
        self.headers["content-type"] = "application/x-www-form-urlencoded"
        self.raw_content = mitmproxy.net.http.url.encode(form_data).encode()
        self.content = urllib.parse.unquote(mitmproxy.net.http.url.encode(form_data)).encode()
```

I've played around with the above, but guess what, this isn't the cause of the facebook problem.
In all cases, the calculated content-length header should at last be too large, which is something the endpoint at `https://www.facebook.com/ajax/updatestatus.php` handles well (the same should be true for most of the other web services out there).

The real issue could be found in **urllib.parse.urlencode()** which is triggered by this [code line](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/http/request.py#L376) in request.py, already mentioned.

A POST request body with URL encoded data should look something like this:

`key1=value1&key2=value2&key3=&key4=value4`

If you look closely, key3 hasn't set a value, shown by `key3=`

Now facebook does something different - an unaltered POST request to `https://www.facebook.com/ajax/updatestatus.php` begins like this:

`attachment&backdated_date%5Byear%5D&backdated_date%5Bmonth%5D&backdated_date%5Bday%5D&backdated_date%5Bhour%5D&backdated_date%5Bminute%5D&boosted_post_config&audience&composer_entry_time=6298`

So there are several keys like `attachment`, which have no value. Unfortunately `mitmproxy.net.http.url.encode(form_data)`  appends an equal sign (%3D) to every key, even the ones without a value. The request to facebook gets transformed to something like this:


`attachment%3D&backdated_date%5Byear%5D%3D&backdated_date%5Bmonth%5D%3D&backdated_date%5Bday%5D%3D&backdated_date%5Bhour%5D%3D&backdated_date%5Bminute%5D%3D&boosted_post_config%3D&audience%3D&composer_entry_time=6298`

Now I have changed this behavior in urllib's urlencode():

Old urlencode()

```
...snip...
    if not doseq:
        for k, v in query:
            if isinstance(k, bytes):
                k = quote_via(k, safe)
            else:
                k = quote_via(str(k), safe, encoding, errors)

            if isinstance(v, bytes):
                v = quote_via(v, safe)
            else:
                v = quote_via(str(v), safe, encoding, errors)
            # only append "=" if key has a value
            l.append(k + '=' + v)
...snip...
```

fixed urlencode()

```
...snip...
    if not doseq:
        for k, v in query:
            if isinstance(k, bytes):
                k = quote_via(k, safe)
            else:
                k = quote_via(str(k), safe, encoding, errors)

            if isinstance(v, bytes):
                v = quote_via(v, safe)
            else:
                v = quote_via(str(v), safe, encoding, errors)
            # only append "=" if key has a value
            if len(v) > 0:
                l.append(k + '=' + v)
            else:
                l.append(k)
...snip...
```

To conclude: the facebook problem described by @nish21 and myself is caused by urllib and not mitmproxy itself. For this reason I haven't started a pull request with a fix, although there's a working solution.

A possible patch for mitmproxy would be an own implementation for urllib's urlencode() which I could try to implement if anyone else is interested. But I won't have the time to do the intense testing needed, if the urlencode behavior is changed.

**Comment by mame82** [comment]
To be more clear: Facebook's behavior of not adding "=" to empty form parameters seems to be not standard conform. Changing mitmproxy to do the same could likely break other stuff. A possible solution would be to only change key value pairs in POST data which have been edited by the user, but this would mean rewriting large parts of the current implementation

**Comment by mhils** [comment]
Thanks for looking into this!

> As the content-length of content-type 'application/x-www-form-urlencoded' should be calculated based on the not URL encoded data this behaviour is wrong.

[citation needed]. I'm fairly sure you are wrong here.

> The real issue could be found in urllib.parse.urlencode()

Yes, everything starting from here on in your analysis sounds right. Unfortunately, there is no standard that mandates if an equal sign should be added or not and both versions occur in practice. Making sure that `urlencode(urldecode(x)) == x` holds for all inputs is very hard:

- Some args could with with equal sign, some without. To be precise, we'd need `(key: str, value: str, has_equal_sign: bool)`
- Arguments could also implement different quoting, e.g. some implementations quote `" "` to `"+"`. To be absolutely correct, we'd need `(key: str, value: str, has_equal_sign: bool, quote_mechanism: str)`
- New arguments need to follow the convention of the existing arguments.

All that sounds like a lot of work for edge cases. I would propose to make the assumption that quoting and `"="` handling is consistent within an urlencoded form. We can then "fix" `urlencode` with simple heuristics:

- If `any("=" not in part for part in form_data.split("&"))` (there is at least one arg without equal sign), remove all occurences of `"=&"`.
- Check for existing quoting behaviour and adjust the argument to `urllib.parse.urlencode` accordingly.

We should add the former heuristic first in an isolated PR. Quoting may actually be okay in practice, so we can defer that until issues arise.

**Comment by mhils** [comment]
I'm filing this as an enhancement (and not a bug) as we technically do not violate any specs. As discussed above, this whole issue can be mitigated currently by editing the raw body directly.

**Comment by mame82** [comment]
So I've tried to implement the steps discussed here in [PR 2022](https://github.com/mitmproxy/mitmproxy/pull/2022).

I focused on the initial problem with ""https://www.facebook.com/ajax/updatestatus.php" which works out for me know. I only worked on request.py (ignored response.py and message.py) and only regarded the corner case here, which in the end was even more weird than I thought first (see comments for details).

Checks are still pending and AppVeyor failed, but I have no clue why.

**Comment by mame82** [comment]
Last question: How gets the current master integrated into Kali Linux. I haven't found mitmproxy on the [upstream watch list](http://git.kali.org/gitweb/?p=upstream-watch.git;a=summary). Kali Linux is running mitmproxy 0.18.2 in current release. Do I have to open an issue at offsec for this ?

**Comment by mhils** [comment]
I don't know who maintains the Kali repo. Feel free to ping them and ask for 1.0.x at least :)

Anyhow, the recommended way to install mitmproxy is to use the precompiled binaries from https://github.com/mitmproxy/mitmproxy/releases or (if you require snapshots from master) https://snapshots.mitmproxy.org/.
