### ISSUE TITLE
Feature request: Preserve marked flows when clearing flow list

### ISSUE THREAD

**Issue by danielphillips** [mitmproxy/mitmproxy#1960]
When I'm busy in mitmproxy, I often mark an important flow using `m` to preserve it for easy access; my flow list grows pretty quickly even when I'm using a filter, so I often clear the list using `z` to tidy up.

Up until very recently clearing the list preserved my marked flows, this was very convenient because I could "clean up" my window and keep what's important (my marked flows) around and continue working.

I've installed the latest version (mitmproxy 1.0.2) and I've just noticed that clearing the flow list also removes the marked flows. 

Could I request this be added as a feature if what I've described was occurring by coincidence, or to be fixed if this is a regression. It is a super handy feature for myself, and hopefully others too. 

Thanks

**Comment by mhils** [comment]
This sounds like a reasonable request to me. Maybe we can add this under `Z`?

**Comment by lymanZerga11** [comment]
There is also another issue with the flow list. The marked flows can get randomly rearranged whenever `M` or `z` is pressed, as it iterates through `view._store` which is a dictionary, to refresh the view.

**Comment by mhils** [comment]
@lymanZerga11: Yes, good catch - needs to be replaced with OrderedDict I believe. Can you open a separate issue for this please?

**Comment by lymanZerga11** [comment]
Yeah okay!
