### ISSUE TITLE
Https traffic not being captured by mitmproxy

### ISSUE THREAD

**Issue by kanikagupta17** [mitmproxy/mitmproxy#1962]
##### Steps to reproduce the problem:

1. I am trying to intercept packets of my android phone on an ubuntu 16 machine. All the http:// traffic is intercepted but https:// traffic is Not. It is not even in the event logs. I think it is not recognizing the https traffic. Any ides how to resolve this issue ?

##### Any other comments? What have you tried so far?

Done updating pypy-pyasn1 but the issue persists.

##### System information

    mitmproxy 1.0.2

**Comment by mhils** [comment]
If you don't even see `clientconnect`s for HTTPS in the event log, this is not a mitmproxy issue - your android phone is not sending HTTPS requests to the proxy then.

**Comment by kanikagupta17** [comment]
I have done all suggested changes in the wifi settings of android phone - making linux machine as default gateway and installing trusted certificate from mitm.it. 
Even, i can see https traffic from my phone in Wireshark. Then, what could be the possible reason behind not sending https requests to the mitmproxy or proxy not being able to capture those ?

P.S. - It is working fine with http.
