### ISSUE TITLE
py.test fails with python 3.6

### ISSUE THREAD

**Issue by mosajjal** [mitmproxy/mitmproxy#1966]
##### Steps to reproduce the problem:

1. clone the repo
2. run `dev.sh`
3. run `. venv3/bin/activate.fish`
4. run `py.test`

I had to edit dev.sh and rename `3.5` to `3` for it to run. Is `mitmproxy` incompatible with python3.6? 
running as root makes it freeze (waited for a couple hours)

full log:
http://pastebin.com/M0BrcYK3

Mitmproxy version: 2.0.0 (1.0.1dev0067-0x695cc236)
Python version: 3.6.0
Platform: Linux-4.4.42-1-lts-x86_64-with-arch
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Linux distro: arch

**Comment by mhils** [comment]
Thanks for the feedback - mitmproxy runs fine with Python 3.6, we actually have a PR in the works that just uses "venv" as the virtualenv name (#1964) - you're welcome to check it out and see if that works for you. Other than that, I'm not sure where your errors come from. Shot in the dark, do you have `localhost` mapped to 127.0.0.1 / ::1 in `/etc/hosts`?

**Comment by mosajjal** [comment]
that was the problem! my `localhost` wasn't mapped to my  `127.0.0.1` in `/etc/hosts`! Thanks a lot. Maybe we could add a simple test in `py.test` to check for that?

**Comment by mhils** [comment]
Well.. as you see we do have tests that check just that 😛 

Jokes aside, we should probably use `127.0.0.1`/`::1` where we currently use `localhost`. We don't really cater for IPv4/IPv6-only machines right now either, so all this is probably a bit of work. I'd be happy to merge a PR that does some work in that direction or one that adds a is-localhost-defined check to dev.sh as a workaround. 😃

**Comment by mosajjal** [comment]
let me go ahead and close this topic. If we created a PR for this issue, we'll reference the PR to this issue
