### ISSUE TITLE
mitmproxy not working inside virtualenv, works fine as a regular installation

### ISSUE THREAD

**Issue by mosajjal** [mitmproxy/mitmproxy#1969]
I've tried to install `mitmproxy` from the GitHub repo, `mitmdump` and `mitmweb` worked perfectly, but not `mitmproxy`.  `mitmproxy` runs but doesn't show any traffic captured whatsoever. 

After running `wireshark` and analyzing the traffic, I saw the GET request with destination port of 8080 heading towards `mitmproxy`, but no response is captured by `wireshark` (captured on `any` interface and `loopback` with no luck).

I've installed it using the tutorial provided so I'm confident I've installed it correctly. 

for a test, I've installed the package provided in arch community repository. It works absolutely fine out of the box. So how can I debug what's wrong inside the `virtualenv`?

##### System information

Inside venv:

Mitmproxy version: 2.0.0 (1.0.1dev0067-0x695cc236)
Python version: 3.6.0
Platform: Linux-4.4.42-1-lts-x86_64-with-arch
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Linux distro: arch  

Outside venv:

mitmproxy 1.0.2

**Comment by mhils** [comment]
I think you're hitting an issue on master we discovered yesterday and fixed then. Can you `git pull` and try again? :smiley:

**Comment by mosajjal** [comment]
yup. that fixed it. Sorry for issue spamming. I really tried to fix it myself but couldn't figure it out 😅

shall I close this or are you gonna reference it to a commit ?

**Comment by mhils** [comment]
No problem, that certainly wasn't spam. Fixed in 45ace793d01c9d2d861a12a2d3bea75eccfbccbb!
