### ISSUE TITLE
Use pytest.raises instead of our own tutils.raises

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#1972]
Use `pytest.raises` instead of our own `tutils.raises` implementation which should be feature-compatible. At the moment we use both - with no real distinction or reasoning behind it.

**Comment by mhils** [comment]
I think they aren't exactly feature-compatible as that `tutils.raises` also accepts a `str` as argument and checks the error message for that. The pytest way to do this is decribed [here](http://doc.pytest.org/en/latest/assert.html#assertions-about-expected-exceptions).

**Comment by Kriechi** [comment]
`with raises(ZeroDivisionError, message="Expecting ZeroDivisionError"):` looks pretty much like what we need.

**Comment by mhils** [comment]
I think that just specified the test failure message, not the expected error.

**Comment by cortesi** [comment]
I'd like to retain a compact way to specify that an error should loosely contain a specified string. I find this very useful in testing.

**Comment by Kriechi** [comment]
fixed by #1980
