### ISSUE TITLE
Crash of har_dump.py

### ISSUE THREAD

**Issue by Junkern** [mitmproxy/mitmproxy#1978]
I sometimes get either `b'' is not JSON serializable` or  `Object of type 'bytes' is not JSON serializable`

I used mitmproxy to extract such a flow and uploaded it [here](https://gist.github.com/Junkern/495d4c7c1b572d7749f0291adfb0dd15)

##### Steps to reproduce the problem:

1.
2.
3.

##### Any other comments? What have you tried so far?

It seems, that the error mostly occurs for `POST` and `HEAD` requests. Sometimes with an empty response body, sometimes not. Seldomly a `GET` requests triggers this error

##### System information
mitmproxy 1.0.2
macOs Sierra 10.12.3

Edit: Updated the Gist link to point to a working binary gist

**Comment by mhils** [comment]
Thanks. Could you please upload the flow somewhere else? Gists don't work with binary data, the file is corrupted.

**Comment by Junkern** [comment]
I now used <https://github.com/mbostock/gistup> to upload binary data as a gist.
[Link](https://gist.github.com/Junkern/495d4c7c1b572d7749f0291adfb0dd15)

**Comment by mhils** [comment]
That works, thanks!

**Comment by Junkern** [comment]
A short update from my side: I used the fix from https://github.com/mitmproxy/mitmproxy/pull/1650/files to address this issue. Seems to work as well.

**Comment by ujjwal96** [comment]
@Junkern Does that work in case of an empty response?

**Comment by Junkern** [comment]
I implemented the fix in the har_dump and tested it on the flow with an empty response (the one  I posted above). No error was thrown

**Comment by Junkern** [comment]
Any update? Should I use the fix I posted above or will this issue be fixed in the mitmproxy code?

**Comment by ujjwal96** [comment]
I made a [PR](https://github.com/mitmproxy/mitmproxy/pull/1984) with the fix. If everything is fine it will probably be merged.
