### ISSUE TITLE
Script not unloaded when exception is thrown

### ISSUE THREAD

**Issue by ujjwal96** [mitmproxy/mitmproxy#1985]
##### Steps to reproduce the problem:

1. Don't give an argument to the script
e.g. `mitmdump -s "examples/complex/har_dump.py"`

Exception is thrown but the script keeps working and throws even more exceptions

##### Any other comments? What have you tried so far?
I haven't tried it for any other script, this may be har_dump.py specific issue but I think would affect other scripts as well.
Ideally, the script should be unloaded after throwing an exception

##### System information
Mitmproxy version: 2.0.0 (1.0.1dev0121-0xc540762)
Python version: 3.5.2
Platform: Linux-4.4.0-38-generic-x86_64-with-elementary-0.4-loki
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: "elementary" 0.4 loki

**Comment by Kriechi** [comment]
Yes, this sounds like a reasonable way to handle script errors.

**Comment by MatthewShao** [comment]
I have been looking into this issue and got some idea about:
1. That's reasonable to unload the script if we meet some exceptions at the **start stage**, the most common case, as @ujjwal96 mentioned, is the user forget to give some arguments. In this situation, if we unload the script directly, the user could either restart the program with right arguments or go ahead without the script.
2. However, when we meets an exception in request or response stage,  if we unload the script immediately, I am not sure whether it is good for a developer to debug the script.
So my question is , should we put this unload mechanism only in the start stage or in the `scriptenv`?

I'm happy to hear any idea about this and give a PR once it is settled.
