### ISSUE TITLE
mitmproxy 1.0.2 does not check for expired certs in ~/.mitmproxy

### ISSUE THREAD

**Issue by rtoma** [mitmproxy/mitmproxy#1987]
##### Steps to reproduce the problem:

1. have expired certs in ~/.mitmproxy
2. start mitmdump/proxy
3. try to proxy https and it fails

**Comment by mhils** [comment]
Well.. thanks for being a long-time mitmproxy user! 😃 

@Kriechi actually [added a check](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/check_ca.py) for this two weeks ago, so this should be fixed with the next release.
Thanks for the report anyway, I'll close this here. :)
