### ISSUE TITLE
Can mitmproxy handle SSLv2 ClientHello?

### ISSUE THREAD

**Issue by johnsoft** [mitmproxy/mitmproxy#1990]
I'm trying to intercept connections for an app that sends an SSLv2 ClientHello, then upgrades to TLSv1 for the handshake. It looks to me like mitmproxy can't handle that combination, or maybe I'm doing something wrong.

My command-line looks like this:

    mitmdump -T --tcp '.*' --insecure -v --ciphers-client RC4-MD5

I need `--insecure` because this app doesn't support SNI, and the cipher is just a second easy way to tell whether mitmproxy is doing its job.

### The connection with TLSv1 hello/TLSv1 handshake
This is the one that works as expected. It serves the client a certificate with an organization name of `mitmproxy`, and my one expected cipher. The log looks like this:

```
192.168.56.101:3275: clientconnect
192.168.56.101:3275: serverconnect
  -> 1.2.3.4:443
192.168.56.101:3275: Establish TLS with server
192.168.56.101:3275: Certificate Verification Error for 1.2.3.4:443: hostname 'no-hostname' doesn't match either of '*.example.com', 'example.com'
192.168.56.101:3275: Ignoring server verification error, continuing with connection
192.168.56.101:3275: ALPN selected by server: -
192.168.56.101:3275: Establish TLS with client
192.168.56.101:3275 -> tcp -> 1.2.3.4:443
192.168.56.101:3275 <- tcp <- 1.2.3.4:443
```

### The connection with SSLv2 hello/TLSv1 handshake
This case fails. It serves the client the server's original cert with an organization name of `GeoTrust, Inc.`, and ciphers other than the one I specified. The log looks like this:

```
192.168.56.101:3277: clientconnect
192.168.56.101:3277: serverconnect
  -> 1.2.3.5:443
192.168.56.101:3277 -> tcp -> 1.2.3.5:443
192.168.56.101:3277 <- tcp <- 1.2.3.5:443
```

So mitmproxy can see the connection, but it decides not to do anything with it. I tried `--ssl-version-client TLSv1` on a whim but it had no effect.

Did I screw something up here?

**Comment by mhils** [comment]
SSLv2? My condolences. 😉 

First, you definitely need to pass `--ssl-version-client all`. SSLv2 is disabled by default as it's insecure.
Second, I believe our [`is_tls_record_magic`](https://github.com/mitmproxy/mitmproxy/blob/d133b8baeeefa04fa6bdf43c39be822def013a6b/mitmproxy/proxy/protocol/tls.py#L203) won't detect SSLv2, so we enter tcp mode right away. I don't know how SSLv2 packets are structured, so no idea if this can be fixed in `is_tls_record_magic`. If fixable, I'm happy to take a PR. Otherwise you can probably monkeypatch [`_next_layer`](https://github.com/mitmproxy/mitmproxy/blob/d133b8baeeefa04fa6bdf43c39be822def013a6b/mitmproxy/proxy/root_context.py#L43) for your specific use case.

 Hope that helps. :)

**Comment by johnsoft** [comment]
That definitely looks like the right place to start, thanks!

**Comment by johnsoft** [comment]
Through some miracle I managed to get it working! 👍

It turned out to be a pretty simple solution, but also somewhat hacky, so it's probably not PR-worthy. [Here's a branch for posterity.](https://github.com/johnsoft/mitmproxy/tree/sslv2-clienthello)

Thanks for pointing me to the right place!

**Comment by mhils** [comment]
Happy to hear this worked! :smiley:
Thanks for posting your code. Looks good for the use case, but as you said, probably not ready a PR. 😉

**Comment by stef** [comment]
i also have an sslv2clienthello here, it would be nice if mitmproxy would support that.
here's a screenshot of the offending packet: https://www.ctrlc.hu/%7Estef/sslv2.png
can we reopen this issue please?

**Comment by Kriechi** [comment]
We already support unencrypted HTTP with mitmproxy.

**Comment by stef** [comment]
sslv2 is not unencrypted.

**Comment by Kriechi** [comment]
*sarcasm warning*
Well, it is not encrypted either (anymore). https://drownattack.com/drown-attack-paper.pdf

**Comment by stef** [comment]
i had a smiley at my comment. anyway, drown is not a useful attack in this scenario. it would be nice if mitmproxy would support this natively, because mitming this is much easier, passive and less hostile than executing the drown attack against the server. the target (in scope) in this case being the client and not the out of scope server.

**Comment by Kriechi** [comment]
We are happy to accept PRs, as long as they don't break anything with more important protocols. Given that SSLv2 is pretty niche nowadays. We do not plan to spend time ourself on such an outdated protocol that is superseded so many times. 

Please take a look at the work of @johnsoft here https://github.com/johnsoft/mitmproxy/commit/bd04223e068409bb84fb2facf81656e52b7f2f90.

**Comment by stef** [comment]
btw considering the effort i think supporting sslv2clienthellos is much cheaper in mitmproxy than implementing the drown paper. or can you recommend a drown implementation that would be useful in other projects if the server is also in scope?

**Comment by stef** [comment]
Have you seen the iot shit being dumped on us nowadays? sadly sslv2 is not as niche as you (or me) would like it. and yes, i saw and tested johnsofts workaround which is in this very issue linked by himself above here. it does not work, hence my request to reopen this issue. if i had time to do a PR i would not ask you guys to to have a look at it. anyways thanks for your awesome work with the rest of mitmproxy.

**Comment by stef** [comment]
here is the traceback with johnsofts patch applied:
```
Error: 10.17.17.2:49230: Traceback (most recent call last):
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 119, in handle
    root_layer()
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 424, in __call__
    layer()
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 417, in __call__
    self._establish_tls_with_client_and_server()
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 493, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 579, in _establish_tls_with_server
    alpn_protos=alpn,
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/connections.py", line 246, in establish_ssl
    self.convert_to_ssl(cert=clientcert, sni=sni, **kwargs)
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 692, in convert_to_ssl
    **sslctx_kwargs
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 666, in create_ssl_context
    **sslctx_kwargs)
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 548, in _create_ssl_context
    context.set_verify(verify_options, verify_cert)
  File "/home/s/denv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 752, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/home/s/denv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 226, in __init__
    "int (*)(int, X509_STORE_CTX *)", wrapper)
SystemError: <built-in method callback of CompiledFFI object at 0x6b69891ca3e8> returned NULL without setting an error

Traceback (most recent call last):
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 119, in handle_context
    root_layer()verify(verify_options, verify_cert)
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
    layer()erify_helper = _VerifyHelper(callback)
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 424, in __call__
    layer())(int, X509_STORE_CTX *)", wrapper)
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 417, in __call__tting an error
    self._establish_tls_with_client_and_server()
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 493, in _establish_tls_with_client_and_server
    self._establish_tls_with_server()
Error: 10.17.17.2:49234: Traceback (most recent call last):
    alpn_protos=alpn,
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/connections.py", line 246, in establish_ssl__
    self.convert_to_ssl(cert=clientcert, sni=sni, **kwargs)
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 692, in convert_to_sslall__
    **sslctx_kwargs_tls_with_client_and_server()
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 666, in create_ssl_contextish_tls_with_client_and_server
    **sslctx_kwargs)tls_with_server()
  File "/home/s/denv/lib/python3.6/site-packages/mitmproxy/net/tcp.py", line 548, in _create_ssl_contextsh_tls_with_server
    context.set_verify(verify_options, verify_cert)
  File "/home/s/denv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 752, in set_verifyestablish_ssl
    self._verify_helper = _VerifyHelper(callback) **kwargs)
  File "/home/s/denv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 226, in __init__nvert_to_ssl
    "int (*)(int, X509_STORE_CTX *)", wrapper)
SystemError: <built-in method callback of CompiledFFI object at 0x6b69891ca3e8> returned NULL without setting an error
    **sslctx_kwargs)
mitmproxy has crashed!ib/python3.6/site-packages/mitmproxy/net/tcp.py", line 548, in _create_ssl_context
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
  File "/home/s/denv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 752, in set_verify
    self._verify_helper = _VerifyHelper(callback)
  File "/home/s/denv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 226, in __init__
    "int (*)(int, X509_STORE_CTX *)", wrapper)
SystemError: <built-in method callback of CompiledFFI object at 0x6b69891ca3e8> returned NULL without setting an error

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

**Comment by tehmoon** [comment]
Running into the same issue as @stef. I still trying to debug but I've tried everything I could think of.
I'm using Kali on docker. The package is at `3.0.4` I believe.

HTTP works fine, but TLS doesn't. I can provide more info if needed.

**Comment by fridtjof** [comment]
I had a need for this functionality as well, so I decided to port @whatisaphone's patch to current mitmproxy (as of 2023-12-17).

based off commit f1df4fa47982b994f180d6987db8e28dc0a9b78c (mitmproxy 10.1.6):

[sslv2.patch](https://github.com/mitmproxy/mitmproxy/files/13694460/sslv2.patch)

No support from me, also this is just as hacky as the original patch. Maybe it'll help someone out some day anyway :)

PS: because this is relevant if you're dealing with clients as old as TLS 1.0, the incantation you want to allow all the necessary insecure stuff is:

`--set tls_version_client_min=UNBOUNDED --set tls_version_server_min=UNBOUNDED --set ciphers_client=ALL:@SECLEVEL=0`

(seclevel=0 is critical with openssl 3.0, though this probably already applies even with 1.1. you'll get a very unspecific and misleading error out of openssl instead that'd cost you a lot of time)
