### ISSUE TITLE
Protocol not available

### ISSUE THREAD

**Issue by nekulin** [mitmproxy/mitmproxy#1992]
##### Steps to reproduce the problem:

1. mitmproxy -T --host -p 3000
2. connect proxy
3. get https://google.com 
ProtocolException("Transparent mode failure: OSError(92, 'Protocol not available')",)

**Comment by ujjwal96** [comment]
Did you setup the transparent mode properly, as said in the docs?
I got this error when I did:  
`mitmproxy -T`  
`curl -x localhost:8080 example.com`  
while trying to reproduce another issue

**Comment by nekulin** [comment]
Is there a way to do so that I can go to any https site and track the traffic ? now all sites swear by the certificate

**Comment by ujjwal96** [comment]
Please read the docs. You can install mitmproxy cert by going to http://mitm.it and monitor https traffic as well

**Comment by mhils** [comment]
Also: http://docs.mitmproxy.org/en/stable/modes.html
