### ISSUE TITLE
Cannot bind mitmproxy to IPv6 address

### ISSUE THREAD

**Issue by ujjwal96** [mitmproxy/mitmproxy#1994]
##### Steps to reproduce the problem:

1. `mitmproxy -b ::1`
`Error starting proxy server: gaierror(-9, 'Address family for hostname not supported')`

##### Any other comments? What have you tried so far?
The relevant code is probably hardcoded to IPv4  
https://github.com/mitmproxy/mitmproxy/blob/2316c0fb74efefd76970c685b8f77f45834f1490/mitmproxy/net/tcp.py#L921

Original Discussion:
https://discourse.mitmproxy.org/t/serving-on-ipv6/331

**Comment by Kriechi** [comment]
Looks like we have a few options how to fix this:
`socket.AF_INET6 if ':' in host and hasattr(socket, 'AF_INET6') else socket.AF_INET`

or probably a more complete solution would be:
```python
try:
    info = socket.getaddrinfo(host, port, socket.AF_UNSPEC, socket.SOCK_STREAM)
except socket.gaierror:
    if ':' in host:
        info = [(socket.AF_INET6, socket.SOCK_STREAM, 0, "", (host, port, 0, 0))]
    else:
        info = [(socket.AF_INET, socket.SOCK_STREAM, 0, "", (host, port))]

family, socktype, proto, canonname, sa = info[0]
s = socket.socket(family, socktype, proto)
s.bind((host, port))
```


(see http://www.programcreek.com/python/example/946/socket.AF_INET6)

**Comment by mhils** [comment]
IIRC there's something in stdlib for this. Will check later.

Thomas Kriechbaumer <notifications@github.com> schrieb am So., 5. Feb.
2017, 14:39:

**Comment by hedger** [comment]
I think I fixed that. https://github.com/mitmproxy/mitmproxy/pull/1995

**Comment by mhils** [comment]
The thing from stdlib I was remembering is [`socket.create_connection`](https://docs.python.org/3/library/socket.html#socket.create_connection), which we actually should use for outgoing connections. We can possibly eliminate `tcp.Address` then, which wasn't a really good idea in hindsight.

For listening, I'll reply in #1995.
