### ISSUE TITLE
DNS spoofing example doesn't work anymore

### ISSUE THREAD

**Issue by greenboxal** [mitmproxy/mitmproxy#2012]
##### Steps to reproduce the problem:

1. Use the dns spoof example script
2. Send a request with the correct Host header

##### Any other comments? What have you tried so far?
I needed to do two changes in order to get it working:

Comment around line 152 on `master.py`:
```
                f.request.host = self.server.config.upstream_server.address.host
```

And comment around line 281 `proxy/protocol/http.py`:
```
             if self.config.options.mode == "reverse":
             f.request.headers["Host"] = self.config.upstream_server.address.host
```

Although it works, those changes are absolutely invalid and will break a lot of other stuff.
Seems like that example relied on the host header which is permanently changed before the script is executed when using reverse proxy mode.

##### System information
mitmproxy 1.0.2

**Comment by mhils** [comment]
Which version of the script are you looking at?
https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/dns_spoofing.py recently got some updates thanks to @amm0nite.

**Comment by cxr0514** [comment]
hi, no matter what i do i cant get mitmproxy to do dns.spoof so instead im left wtih having to use ettercap to spoof arp and dns.. can you help.. do i modify the actual script or pass the values to use. can you give a sample of what the syntax should look like? please
