### ISSUE TITLE
getrandom() initialization failed if run on boot

### ISSUE THREAD

**Issue by laurentdinclaux** [mitmproxy/mitmproxy#2013]
##### Steps to reproduce the problem:

I created a systemd startup file:

```
[Unit]
Description=Mitmproxy
After=network.target

[Service]
#Type=simple
Type=idle
EnvironmentFile=/etc/default/mitmproxy
User=mitmproxy
Group=mitmproxy
LimitNOFILE=32768
ExecStart=/usr/local/bin/mitmdump $DAEMON_ARGS --conf=$CONFFILE --cadir=/etc/mitmproxy

[Install]
WantedBy=multi-user.target
```

Whenever I reboot my ubuntu 16.04 VM, mitmdump runs, but throw error for SSL websites:

`Cannot establish TLS with 216.58.204.104:443 (sni: ssl.google-analytics.com): TlsException("SSL handshake error: Error([('', 'osrandom_rand_bytes', 'getrandom() initialization failed.')],)",)`

If I log into ssh and restart the service manually it then runs fine.

##### System information

Ubuntu 16.04 - mitmproxy 1.0.2

**Comment by Kriechi** [comment]
This is more a general Python issue and unfortunately not directly related to mitmproxy.
Fur further information please see:
https://lwn.net/Articles/693189/
https://bugs.python.org/issue26839

You could try and experiment with `systemd-random-seed.service` in your service definition...

**Comment by nesttle** [comment]
Same here,
https://discourse.mitmproxy.org/t/run-mitmdump-from-crontab-solved/373/4

I try with:
`@reboot sleep 60 && script.sh`

Still not working (didn't happen on mitm0.18, but 2.0)
