### ISSUE TITLE
HTTPS not working with authentication

### ISSUE THREAD

**Issue by laurmurclar** [mitmproxy/mitmproxy#2019]
##### Steps to reproduce the problem:

1. `mitmproxy --nonanonymous`
2.  Set a proxy username and password in `System Preferences -> Network -> Wifi -> Advanced -> Proxies` for both HTTP and HTTPS.
![screen shot 2017-02-13 at 19 54 32](https://cloud.githubusercontent.com/assets/9434500/22900943/0b446b4c-f228-11e6-831f-f0bc6989b504.png)
3. Save changes. A dialog appears: 
![Uploading Screen Shot 2017-02-13 at 20.08.40.png…]()
Choose `Always Apply`

3. Open browser and navigate to a HTTPS page eg. `https://www.google.ie/`. This appears:
<img width="1296" alt="screen shot 2017-02-13 at 19 54 53" src="https://cloud.githubusercontent.com/assets/9434500/22900938/04ca0984-f228-11e6-8473-5c8f490b4787.png">

4. Fill in username and password to match those entered earlier. 

5. Get the following error (ERR_SPDY_PROTOCOL_ERROR):
![screen shot 2017-02-13 at 19 55 08](https://cloud.githubusercontent.com/assets/9434500/22901207/d5db43bc-f228-11e6-9384-641aa546d8ba.png)

##### Any other comments? What have you tried so far?

After googling the error, I tried flushing the socket pools at chrome://net-internals/#sockets. I immediately got the same error after trying to access a HTTPS site again.

Previously I had been getting two dialog boxes; one requesting credentials for localhost:8080 and then another requesting credentials for google.ie:443 (or whatever site) directly after the localhost one.

Not sure if it matters, but the proxy credentials in my keychain:
<img width="1393" alt="screen shot 2017-02-13 at 19 58 15" src="https://cloud.githubusercontent.com/assets/9434500/22901465/ba025db4-f229-11e6-8128-6de1305cc3b3.png">

##### System information

Mitmproxy version: 2.0.0 (1.0.1dev0129-0x919385d)
Python version: 3.6.0
Platform: Darwin-15.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Mac version: 10.11.6 ('', '', '') x86_64

**Comment by laurmurclar** [comment]
Actually, it doesn't seem to be all sites. I can navigate to an app I have on heroku, and then I am asked for credentials for that site (this site does not need credentials): 
<img width="1440" alt="screen shot 2017-02-13 at 20 22 12" src="https://cloud.githubusercontent.com/assets/9434500/22901660/4c26f3d0-f22a-11e6-8289-65be1dee4ad2.png">

But after entering ones which matched the proxy ones, I was able to access the site as normal. 
![screen shot 2017-02-13 at 20 22 30](https://cloud.githubusercontent.com/assets/9434500/22901702/6eba18fa-f22a-11e6-9093-d41e5156ebad.png)
(Don't mind the message, I usually use an inline script to add a header but removed it to see if this was still happening. The message basically just means that the header isn't there)

How mitmproxy looks:
<img width="1440" alt="screen shot 2017-02-13 at 20 24 39" src="https://cloud.githubusercontent.com/assets/9434500/22901773/af33e956-f22a-11e6-8f1a-84277171ea27.png">

**Comment by laurmurclar** [comment]
Okay, so some sites are fine once I enter some credentials into the dialog. A popup still appears every time I visit a new HTTPS site for the first time. HTTP seems fine (obviously except when the site tries to make requests to HTTPS endpoints such as twitter).

**Comment by laurmurclar** [comment]
Could be related to #1722

**Comment by mhils** [comment]
Thanks for the fantastic writeup! 👍 

@Kriechi: Does one have to configure a "Secure Web Proxy" on OSX? Is that OSX terminology for "HTTP CONNECT" or is that for the [Chrome "Secure Web Proxy"](https://www.chromium.org/developers/design-documents/secure-web-proxy) where TLS is established with the proxy itself?

Other than that, this indeed looks related to #1722. Let's see that we get that fixed ASAP.

**Comment by Kriechi** [comment]
AFAIK: I think this settings just means "use this proxy for HTTP requests" and "use the other proxy for HTTPS requests". So, no, macOS uses the same terminology as Chrome for something different.

**Comment by laurmurclar** [comment]
Worth mentioning that Safari on my iPhone 6 also gives me a million dialogs, as well as Safari on the Mac mentioned above
