### ISSUE TITLE
vcruntime140.dll missing when running on windows

### ISSUE THREAD

**Issue by JosePedroDiasSky** [mitmproxy/mitmproxy#2025]
##### Steps to reproduce the problem:

1. try to run `mitmdump.exe` or `mimtproxy.exe` on windows (tried on Windows 7 64 bits)
2. an error dialog appears complaining about the lack of the `vcruntime140.dll` file.

##### Any other comments? What have you tried so far?

I managed to make it work by installing the Visual C++ Redistributable for Visual Studio 2015, x86 version, from here:
<https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145>

##### System information

mitmproxy release 1.0.2

**Comment by mhils** [comment]
Thanks! This is possibly related to #1763.

**Comment by jpryne** [comment]
Doesn't work.

**Comment by habedi** [comment]
Hi, I had the same problem and after Installing vc_redist.x86.exe that I downloaded from https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe the problem seems to be solved.

**Comment by mhils** [comment]
This should be fixed in the 3.0.x release candidates, so I'm closing this here :)
