### ISSUE TITLE
Support HAR dumping example script in standalone binaries 

### ISSUE THREAD

**Issue by mchr3k** [mitmproxy/mitmproxy#2030]
##### Steps to reproduce the problem:

1. Try to run har_dump.py example with standalone mitmdump binary:

```
mitmdump -s "examples/complex/har_dump.py /tmp/out.har"
Loading script: examples/complex/har_dump.py /tmp/out.har
Script error: Traceback (most recent call last):
File "examples/complex/har_dump.py", line 12, in <module>
import pytz
ImportError: No module named 'pytz'

Proxy server listening at http://0.0.0.0:8080
```
##### Any other comments? What have you tried so far?
I realize that har_dump.py is currently only an example script. However, it would be nice if it worked with the standalone binaries until/if you integrate it into the core of mitmproxy.

I have been able to resolve this by rebuilding locally with a couple of small edits:

```
> sudo apt-get install python3-pip python3-dev libffi-dev libssl-dev libtiff5-dev libjpeg8-dev zlib1g-dev libwebp-dev
> git clone https://github.com/mitmproxy/mitmproxy.git
> cd mitmproxy
> git checkout tags/v1.0.2
(edit two files)
> git diff
diff --git a/release/specs/mitmdump b/release/specs/mitmdump
index 0aeac3c8..fd103525 100644
--- a/release/specs/mitmdump
+++ b/release/specs/mitmdump
@@ -1,3 +1,4 @@
#!/usr/bin/env python
from mitmproxy.tools.main import mitmdump
+import pytz
mitmdump()
diff --git a/setup.py b/setup.py
index fa20e7cf..caf703f9 100644
--- a/setup.py
+++ b/setup.py
@@ -52,7 +52,7 @@ setup(
entry_points={
'console_scripts': [
"mitmproxy = mitmproxy.tools.main:mitmproxy",
- "mitmdump = mitmproxy.tools.main:mitmdump",
+ "mitmdump = mitmproxy.tools.main:mitmdump [examples]",
"mitmweb = mitmproxy.tools.main:mitmweb",
"pathod = pathod.pathod_cmdline:go_pathod",
"pathoc = pathod.pathoc_cmdline:go_pathoc"
> ./dev.sh
> . venv3.5/bin/activate
> tox -e rtool -- bdist
> deactivate
> ls -lh release/build/binaries/linux/
```

I don't think this is the correct fix. Ideally I would like to be able to tell pyinstaller about all of the "examples" dependencies for mitmdump specified in the root setup.py.

Do you have any suggestions about how this could be achieved? That would be one small step towards making HAR dumping better supported by the next release of mitmproxy (see: https://github.com/mitmproxy/mitmproxy/issues/1477 ). 

##### System information

I'm on Ubuntu 16.04 using mitmdump 1.0.2:
```
> mitmdump --version
mitmdump 1.0.2
```

**Comment by mhils** [comment]
Thanks for the report. That's a reasonable but generally tricky request. For example, we just ditched Pillow in mitmproxy (it's now in examples only) which reduces our binary size by 20%. I'd be opposed to adding this again just to have the example work. Then again, har_dumper might just be important enough to warrant a special case. Ideally we could just replace pytz with something that's builtin (I haven't checked how feasible that'd be).

**Comment by mchr3k** [comment]
pytz is only needed for the following line of code:
```
def format_datetime(dt):
    return dt.replace(tzinfo=pytz.timezone("UTC")).isoformat()
```

**Comment by mhils** [comment]
Yes, I guess there are ways to replace this with something from stdlib.

**Comment by mchr3k** [comment]
I think the following trivial change will allow the removal of the pytz dependency. Before:
```
def format_datetime(dt):
    return dt.replace(tzinfo=pytz.timezone("UTC")).isoformat()
```
After:
```
def format_datetime(dt):
    return dt.replace(tzinfo=timezone.utc).isoformat()
```

**Comment by mhils** [comment]
@mchr3k: Thanks. Would you like to submit a PR for this? :smiley:

**Comment by ujjwal96** [comment]
@mchr3k Do you want to submit a PR? Otherwise I have the fix ready
Also, we can get rid of the function completely by doing
`datetime.fromtimestamp(timestamp, timezone.utc).isoformat()`

**Comment by mchr3k** [comment]
I'm happy for you to push the fix if you have it ready 😊
