### ISSUE TITLE
Add PyInstaller indicator to `mitmproxy --version`

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2033]
We currently cannot distinguish if users use our precompiled binaries or if they installed mitmproxy using pip/brew/$packagemanager. It would be very useful to output if we are running the precompiled PyInstaller binary. 

https://pythonhosted.org/PyInstaller/runtime-information.html

**Comment by krsoninikhil** [comment]
Use of precompiled binaries can be detected but how would it distinguish between the other cases, or it just wouldn't be necessary?

**Comment by Kriechi** [comment]
As first step, identifying pyinstaller builds is good enough.
We already distinguish between release versions and git-based installations based on `git describe` and tags.

**Comment by krsoninikhil** [comment]
Sure, thanks!
