### ISSUE TITLE
Add `request.host_header`

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2036]
There are a bunch of places in the codebase where we use a hard-coded `headers["Host"]` that now also have to deal with h2, see for example https://github.com/mitmproxy/mitmproxy/pull/2034. The question is how we handle this best:

1. Rewrite the special h2 headers starting with a colon to their h1 counterparts before we send them to the rest of mitmproxy (and undo that before sending them out). This would fix the symptoms we currently have, but we wouldn't display h2 flows accurately in the UI anymore (and the mapping would not be bijective). Sounds rather unconvincing to me.
2. Add a special `request.host_header` (or `.authority_header`?) property that proxies to the right header and use that instead of `headers["Host"]`.
3. Distinguish between both headers everywhere. Nah.

Unless somebody comes up with a better option, I'd propose we go an implement option 2 to tackle this. Implementation isn't entirely trivial, but I'd propose the following semantics:

- Get with no header present: `None`
- Get with (either `Host` or `:authority`) or matching `Host` and `:authority`: the correct header
- Get with different `Host` and `:authority`: Probably raise an exception?
- Set with existing: Update all the existing ones
- Set without existing: Use http_version and only set one of them. 

@Lukasa @Kriechi @yoavweiss, would that work for everyone?

**Comment by Lukasa** [comment]
I think option 2 is the right call here. I also think that if you have different ones then you should prioritise, rather than throw exceptions: if `:authority` is present it should be assumed to be authoritative, otherwise `Host` is. The reason I say this is that mitmproxy generally wants to tolerate "incorrect" data that its peers might send, and this seems like the sensible approach.

**Comment by Kriechi** [comment]
Yes, even the RFC says that `:authority` should be used in case both are present.
I assume this is then also a public API, so users should use this in their scripts?
Unaware users who just set `Host` then simply have to deal with their own bug?

For reference, https://github.com/mitmproxy/mitmproxy/pull/1791 already tries to solves this partially (now incomplete and not really suitable any more).

**Comment by mhils** [comment]
> Yes, even the RFC says that :authority should be used in case both are present.

Ok, fantastic. Let's do that then!
