### ISSUE TITLE
Fix flaky coverage

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2037]
CI is failing in https://github.com/mitmproxy/mitmproxy/pull/2032 because one line in http2.py apparently has flaky coverage: https://codecov.io/gh/mitmproxy/mitmproxy/compare/337b1c9399e525a23dc188ef5df1667f109b108e...6b22ca7a32252b5c5963704f6276eeac390a3622/changes
We should find out why this is happening and fix it. :)

**Comment by Kriechi** [comment]
Fixed by #2038
