### ISSUE TITLE
Add --keep-host-header

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2039]
##### Steps to reproduce the problem:

1. `mitmdump -R https://httpbin.org/`
2. `curl localhost:8080/headers`

This returns "Host": "httpbin.org" instead of "Host": "localhost", which was what the original curl request sent. We want to add a `--keep-host-header` to disable our automatic host header rewrite [here](https://github.com/mitmproxy/mitmproxy/blob/6a1e03ac6f5fbbfda70200d465cfb2f7cc01d253/mitmproxy/proxy/protocol/http.py#L292-L294). For a discussion of the rationale, see https://github.com/mitmproxy/mitmproxy/pull/2034#issuecomment-280770573.

Once implemented, we should change the dns_spoofing example to use that instead of doing the `requestheaders` dance. First, however, let's keep the PR small and only add the switch.

**Comment by marncz** [comment]
Hello, I'd like to work on that issue as my first contribution to the project

**Comment by krsoninikhil** [comment]
Hi @marncz,
I was working on this and about to submit a PR, please consider other issues.

**Comment by marncz** [comment]
@krsoninikhil no problem, thanks for letting me know :)

**Comment by WHK102** [comment]
Related https://github.com/mitmproxy/mitmproxy/issues/786

**Comment by amoralesc** [comment]
Perhaps obvious to some, but it wasn't immediately clear to me: the correct way to set this option in current versions of mitmproxy is to use the `--set keep_host_header` option when running it from the command line.

```bash
mitmproxy --mode reverse:https://example.com --set keep_host_header
```

Relevant docs [here](https://docs.mitmproxy.org/stable/concepts-modes/#host-header).
