### ISSUE TITLE
certificate import in android 4.4.2 emulator

### ISSUE THREAD

**Issue by josch** [mitmproxy/mitmproxy#204]
Hi,
I was trying to import the mitmproxy certificate into an emulated android 4.4.2 device. But no matter where I put the certificate (tried `/scard/Download`, `/sdcard`, `/mnt/sdcard`, `/mnt/sdcard/Download`, `/storage/sdcard/Download`, `/storage/sdcard`), the certificate import did not show the certificate (but it did show apk files in `/sdcard/Download`).
This means that the instructions given at http://mitmproxy.org/doc/certinstall/android.html are either outdated for android 4.4.2, that this is a problem only appearing in the emulator or that I do something horribly wrong.
Nevertheless, I managed to import the certificate in the end by doing:

```
fname=`openssl x509 -inform PEM -subject_hash_old -noout -in ~/.mitmproxy/mitmproxy-ca-cert.cer`.0
cp ~/.mitmproxy/mitmproxy-ca-cert.cer $fname
openssl x509 -inform PEM -text -noout -in ~/.mitmproxy/mitmproxy-ca-cert.cer >> $fname
adb push $fname /system/etc/security/cacerts/
adb shell chmod 644 /system/etc/security/cacerts/$fname
```

Maybe it would make sense to verify whether I just messed up somewhere or whether the instructions at http://mitmproxy.org/doc/certinstall/android.html indeed need updating and if they do, to also provide this new certificate format.

**Comment by juanchosaravia** [comment]
Thanks @josch and @0xroot  for the explanation! I used the @0xroot' script and I just have to remove 'busybox' in the mount command and it works! THANKS!!!

**Comment by smoothdvd** [comment]
In 7.0 emulator, use `mount -o rw,remount /dev/block/vda /system` to remount fs.
