### ISSUE TITLE
Teach upstream proxy (-U) mode to be able to ignore certain hosts or host/address-patterns

### ISSUE THREAD

**Issue by javabrett** [mitmproxy/mitmproxy#2042]
This is analogous to standard no-proxy functionality for a direct HTTP client - it should be possible to be able to specify hosts, host-patterns or even IP address ranges which `mitmproxy` will then proxy "directly" rather than forwarding via the configured upstream proxy.  There is often no option to this if you are a) forced to work with an upstream proxy in order to access internet-hosts and b) also working with hosts e.g. localhost that are not known-to, or accessible from the upstream proxy.

##### Steps to reproduce the problem:

1. Work with an upstream proxy that you want to proxy requests to most, but not all hosts.
2. Receive some redirect to http://localhost
3. The upstream proxy can't serve that request.  Host "localhost" needs to be excluded from upstream proxying, and should instead be forwarded "direct", in this case, to localhost.

##### Any other comments? What have you tried so far?

I looked at filter-expressions but I don't think those fit.

##### System information

mitmproxy 1.0.2

**Comment by mhils** [comment]
Thanks for the write-up. On the roadmap, but that's nothing that can be easily added with our current setup.

refs #1821
refs #1775

**Comment by javabrett** [comment]
Thanks, this could probably be merged-with, or closed duplicate of #1821.  I'll add a comment over there.  Using env to help configure this might be helpful and conventional.

**Comment by mhils** [comment]
Ok, I'll close this here then if you don't mind. :)

**Comment by uesleivsouza** [comment]
> This is analogous to standard no-proxy functionality for a direct HTTP client - it should be possible to be able to specify hosts, host-patterns or even IP address ranges which `mitmproxy` will then proxy "directly" rather than forwarding via the configured upstream proxy. There is often no option to this if you are a) forced to work with an upstream proxy in order to access internet-hosts and b) also working with hosts e.g. localhost that are not known-to, or accessible from the upstream proxy.
> 
> ##### Steps to reproduce the problem:
> 1. Work with an upstream proxy that you want to proxy requests to most, but not all hosts.
> 2. Receive some redirect to http://localhost
> 3. The upstream proxy can't serve that request.  Host "localhost" needs to be excluded from upstream proxying, and should instead be forwarded "direct", in this case, to localhost.
> 
> ##### Any other comments? What have you tried so far?
> I looked at filter-expressions but I don't think those fit.
> 
> ##### System information
> mitmproxy 1.0.2

Hello, this question is from long time ago, but now I am facing the same situation, and it seems mitmproxy haven't changed about this approach. Did you  find a way to do it? I have to the same, upstream to another proxy but ignore requests to localhost, tks.
