### ISSUE TITLE
Which password use to import certificate into Chrome?

### ISSUE THREAD

**Issue by SashaDesigN** [mitmproxy/mitmproxy#2044]
I`m trying to import .crt file into Chrome certificates list, but it asking me certificate password,

**Comment by mhils** [comment]
There's no password on any of the generated certificates. Which OS is that? Asking for an admin password presumably?

**Comment by SashaDesigN** [comment]
OS Linux/Ubuntu
I try my root password and "test" pass but it doesn't works too

**Comment by SashaDesigN** [comment]
Yes it work without pass) Thanks
