### ISSUE TITLE
TlsException("SSL handshake error: SysCallError(-1, \'Unexpected EOF\')",)',)

### ISSUE THREAD

**Issue by straverso** [mitmproxy/mitmproxy#2049]
Hey,
I am running mitmproxy in my own python script.
I am facing this issue when accessing few websites from Safari.
For instance, https://www.pec.it

The complete error provided by the browser is:

```
502 Bad Gateway
TlsProtocolException('Cannot establish TLS with www.pec.it:443 (sni: www.pec.it): TlsException("SSL handshake error: SysCallError(-1, \'Unexpected EOF\')",)',) 
```

##### Steps to reproduce the problem:

1. Visit https://www.pec.it from Safari, with mitmproxy in the middle.

##### Any other comments? What have you tried so far?

Everything works good using Chrome or Firefox. 
Apparently, tested websites do not support TLSv1.2. 
It happens that as soon as the mitmproxy sends the CHELO message, the server sends back a FIN message and interrupts the connection.

##### System information

Happens on MacOS Sierra Version 10.12.3, Safari Version 10.0.3 (12602.4.8) and mitmproxy  (commit 337b1c9399e525a23dc188ef5df1667f109b108e)

```
$ mitmproxy --version
Mitmproxy version: 2.0.0 (release version)
Python version: 3.5.2
Platform: Darwin-16.4.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.3 ('', '', '') x86_64
```

Thanks,

Stefano

**Comment by Kriechi** [comment]
This url you posted does not even work with curl (without proxy!).
curl 7.52.1 via homebrew on macOS 10.12.3.

Totally unrelated:
Either I missed the 2.0 release, or our `--version` output is buggy, because I doubt that you have `2.0.0 (release version)`. @mhils ideas?

**Comment by straverso** [comment]
Weird, everything works good from my Mac:

```
$ curl -v https://www.pec.it > /tmp/test.html
* Rebuilt URL to: https://www.pec.it/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 62.149.188.176...
* TCP_NODELAY set
* Connected to www.pec.it (62.149.188.176) port 443 (#0)
* TLS 1.0 connection using TLS_RSA_WITH_3DES_EDE_CBC_SHA
* Server certificate: *.pec.it
* Server certificate: Actalis Authentication CA G3
* Server certificate: Actalis Authentication Root CA
> GET / HTTP/1.1
> Host: www.pec.it
> User-Agent: curl/7.51.0
> Accept: */*
>
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 200 OK
< Date: Mon, 20 Feb 2017 21:44:24 GMT
< Server: Microsoft-IIS/6.0
< X-Powered-By: ASP.NET
< X-AspNet-Version: 4.0.30319
< Set-Cookie: ASP.NET_SessionId=152r3txmm05fhqrcdp3zupd2; path=/; HttpOnly
< Cache-Control: private
< Content-Type: text/html; charset=utf-8
< Content-Length: 129005
<
{ [1751 bytes data]
* Curl_http_done: called premature == 0
100  125k  100  125k    0     0   122k      0  0:00:01  0:00:01 --:--:--  123k
* Connection #0 to host www.pec.it left intact
```

My curl version:

```
$ curl --version
curl 7.51.0 (x86_64-apple-darwin16.0) libcurl/7.51.0 SecureTransport zlib/1.2.8
```

**Comment by Kriechi** [comment]
```
$ /usr/local/opt/curl/bin/curl https://www.pec.it -v
* Rebuilt URL to: https://www.pec.it/
*   Trying 62.149.188.176...
* TCP_NODELAY set
* Connected to www.pec.it (62.149.188.176) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to www.pec.it:443
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to www.pec.it:443
$ /usr/local/opt/curl/bin/curl --version
curl 7.52.1 (x86_64-apple-darwin16.3.0) libcurl/7.52.1 OpenSSL/1.0.2k zlib/1.2.8 nghttp2/1.19.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
$ uname -a
Darwin MacBook-Pro.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

Very weird indeed!

**Comment by Kriechi** [comment]
Ah yes - as said, I'm using curl from homebrew, which is a newer version and builds against OpenSSL. Your curl was built with the macOS SecureTransport lib - which seems to behave differently...
Since mitmproxy uses pyOpenSSL for the cryptographic routines, I would expect this to be an OpenSSL-related issue.

**Comment by straverso** [comment]
So, as far as I understand, the problem is related to OpenSSL, thus Mitmproxy (which builds on OpenSSL) fails at loading above web pages. Correct?

**Comment by mhils** [comment]
@straverso: Yes, your understanding is correct.

**Comment by straverso** [comment]
Thanks, but, then, why does everything work good with Chrome or Firefox, but not with Safari? Shouldn't mitmproxy fail with all?

**Comment by mhils** [comment]
Not exactly - one reason might be that Chrome and Firefox send ALPN info to mitmproxy (which mitmproxy forwards), whereas Safari may not send any.

**Comment by Shaked** [comment]
Hey, just found this issue. 

I`m having a similar issue (https://twitter.com/shakedko/status/967639797735899136) and was wondering if it is a mitmproxy issue or a dependency? 

Thank you and sorry for -probably- re asking the same question.
Shaked

**Comment by Shaked** [comment]
@mhils - yes for all domains. No corporate proxy

**Comment by Shaked** [comment]
@mhils - should I open a new issue maybe?
