### ISSUE TITLE
Ignore filters do not seem to have any effect

### ISSUE THREAD

**Issue by danhawkes** [mitmproxy/mitmproxy#2056]
##### Steps to reproduce the problem:

1. mitmproxy -T --host
2. ^O -> Ignore patterns
3. Add regex: `.*`
4. Navigate to `example.com` in browser, requests appear in log.

##### System information

mitmproxy 2.0.0

**Comment by mhils** [comment]
Thanks for the report. What OS is this on?

`mitmdump -T -v --ignore .*` works as expected on Windows, I only see client/server (dis)connect messages, but no requests.

**Comment by danhawkes** [comment]
Hi, thanks for the quick response. 

On osx 10.11.

I think this may be related to adding/removing rules in the GUI rather than the filtering itself. This seems to be reproduceable for me:

- `mitmdump -T --host -v --ignore '.*'` -> (ignore works, nothing is shown)
- `mitmdump -T --host -v`, then add rule via options menu -> (not working, requests still appear)

**Comment by mhils** [comment]
This is fixed on master. Thanks again! 😃
