### ISSUE TITLE
Scripting Include Problems

### ISSUE THREAD

**Issue by michaelschem** [mitmproxy/mitmproxy#2074]
##### Steps to reproduce the problem:

1. Download precompiled version of mitmdump from https://github.com/mitmproxy/mitmproxy/releases as per installation instructions for linux
2. pip3 install ipwhois
3. verify that install worked by running python3 then running `from ipwhois import IPWhois` (import works here)
4. Run mitmproxy with a script as follows `~/mitmdump -s test_includes.py` with the following in test_script.py

`from ipwhois import IPWhois`

getting the following error:

`Script error: Traceback (most recent call last):
  File "../mitm_script.py", line 6, in <module>
    from ipwhois import IPWhois
ImportError: No module named 'ipwhois'`

##### Any other comments? What have you tried so far?
After installing ipwhois or any library to import into my script, the module cannot be found in the included script

##### System information
Linux DarkNetLab 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

(Using the precompiled version I downloaded from link above)
~/mitmproxy --version
mitmproxy 1.0.2

**Comment by Kriechi** [comment]
I think this is a general limitation of pyinstaller. Sorry.
Point 3 here clarifies that a bit: https://github.com/pyinstaller/pyinstaller/wiki/FAQ#misc

**Comment by michaelschem** [comment]
Is pyinstaller what is used to create the prepackaged versions of mitmproxy?

**Comment by mhils** [comment]
yes.

**Comment by michaelschem** [comment]
ok, so if I follow the "Installation from Source on Ubuntu" directions, I should be able to use the library though right?  Cause it's not using pyinstaller there right?

**Comment by mhils** [comment]
yes.

**Comment by mhils** [comment]
😄

**Comment by michaelschem** [comment]
Ok, only problem is I have already installed mitmproxy via `sudo apt-get install` and when I follow those steps it seems to either not overwrite the files or to not reinstall at all because the version of mitmproxy that is in my path is version 0.18.2 as that seems to be the newest available version of mitmproxy on apt-get

**Comment by michaelschem** [comment]
Is there a way to remove 0.18.2?  apt-get purge does not seem to work.  I think the package is messing with my ability to install the new version.
