### ISSUE TITLE
Some requests not getting through on the app and not showing in mitmproxy

### ISSUE THREAD

**Issue by pythonios** [mitmproxy/mitmproxy#2077]
##### Steps to reproduce the problem:
-

##### Any other comments? What have you tried so far?
If I use mitmproxy to read traffic from my android, certain requests will not get through (looks like they are blocked or not executed at all on the app). For example: Want to load a certain area in the app which should load a list, list will not be loaded and also not shown in mitmproxy. As soon as I stop mitmproxy and remove proxy from settings on android the request works again. Some request work but not all (especially important ones do not work). Are there any tips on how to get it to work or what the problem could be?

thanks in advance

##### System information
mitmproxy 0.18.1
macOS

**Comment by mhils** [comment]
Thanks. First, it looks like your mitmproxy is outdated. You may just want to upgrade an try again? Second, do you see anything for those requests in the event log (press `e` to open it in the flow list)?

**Comment by pythonios** [comment]
Hi I updated mitmproxy now on 2.0.0 - in the eventlog is nothing and in the app its loading infinite (like the request does not get through or so). Some requests work but not all. Any help would be appreciated :-)

**Comment by mhils** [comment]
If you don't even see a `clientconnect` message in the event log, no traffic is reaching mitmproxy. One possible reason is that the android app you're looking at generally refuses to work with proxy servers.
