### ISSUE TITLE
Unable to scroll mitmweb details in Firefox

### ISSUE THREAD

**Issue by wdormann** [mitmproxy/mitmproxy#2083]
##### Steps to reproduce the problem:

1. Install Firefox ESR 45.7.0 on Linux
2. Capture with mitmweb
3. Find a message that requires scrolling on the right pane, and attempt to view all content. 

##### Any other comments? What have you tried so far?

This seems very similar to issue #615
Chromium scrolls fine.

##### System information

Mitmproxy version: 2.0.0 (release version) 
Python version: 3.5.2
Platform: Linux-3.10.0-514.6.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
SSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
Linux distro: CentOS Linux 7.3.1611 Core

**Comment by MatthewShao** [comment]
I tried this out and found that in `.flow-detail section`, if we change the css code like this:
```css
section {
    /* display: flex;
     flex-direction: column;*/
    overflow-y: scroll;
}
```
That works for me on Ubuntu with Firefox 51.0.1 and Chrome 52.0.2743.116, don't know if this works on other browsers.

**Comment by mhils** [comment]
@MatthewShao: We only care about Chrome/Firefox for now, so if that fixes things, please submit a PR! 😃

**Comment by pihug12** [comment]
It seems like this fix wasn't commit in the 2.0.x branch as well.

* commit e064439 : 2017-03-04
* release v2.0.1 : 2017-03-14
* release v2.0.2 : 2017-04-28

The bug is still present in this last release.

**Comment by Bjornskjald** [comment]
Still present...

**Comment by kira0204** [comment]
I will take a look at it @mhils tomorrow?
