### ISSUE TITLE
mitmproxy/mitmweb flow order differs from mitmdump flow order

### ISSUE THREAD

**Issue by wdormann** [mitmproxy/mitmproxy#2091]
##### Steps to reproduce the problem:

1. Open an existing mitmproxy flow file in mitmweb
2. Open that same flow file in mitmproxy
3. Compare the order of records

##### Any other comments? What have you tried so far?

It's not clear what the default sort order is in mitmweb.   It's not chronological.  Even if it defaulted to sorting chronologically, there doesn't appear to be a way to revert back to chronological after sorting by any other field.

##### System information

Mitmproxy version: 2.0.0 (release version) 
Python version: 3.5.2
Platform: Linux-3.10.0-514.6.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
SSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
Linux distro: CentOS Linux 7.3.1611 Core

**Comment by mhils** [comment]
Thanks for the report. This seems to be an issue on the Python side already. I did a quick test capture and the API already returns requests 3 and 4 in a different order:

![](https://uploads.maximilianhils.com/2017-03/2017-03-03_19-13-42.png)

**Comment by mhils** [comment]
Looking further into this, both mitmproxy and mitmweb seem to be affected by this, but not mitmdump.

**Comment by wdormann** [comment]
Is it as simple as python dictionaries not being ordered?

**Comment by mhils** [comment]
Not quite - see https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/view.py. I just looked briefly at it, but it seems to me that we sort by the start timestamp there, which is different from the order we have stored flows in (which usually would be around the stop timestamp).

**Comment by mhils** [comment]
In order to have the same default order in all tools, let's add a OrderResponseDone sort order and make that the default.

**Comment by vigneshram93** [comment]
I am working on a fix

**Comment by krsoninikhil** [comment]
Hi @mhils, But it seems that the flow is added to the view as soon as it is requested, so to make default sort order based on response is creating problem (as `f.response` is `None`). To fix this should the timestamp for response done be set to a dummy value (initially) or should we add the flow after getting the response?
Please correct me if I'm getting it wrong.

**Comment by mhils** [comment]
That's at tricky question indeed, didn't consider this. Thinking ahead, we may also want to support e.g. WebSocket frames at some point. Do we want to move them to the bottom again when a message arrives or do we prefer to keep the request order constant? I'm afraid we end up with a lot of flickering if we change order a lot. Maybe the current state is actually the best we can do.

@mitmproxy/devs, thoughts?

**Comment by Kriechi** [comment]
I guess you are talking about WebSocketMessages? We currently don't store WebSocket frames.
We have one WebSocketFlow containing a list of WebSocketMessages.
A WebSocketMessages is more or less just a blob of data being received/sent.
Each WebSocketMessages was transmitted as multiple frames, which get assembled into a WebSocketMessages.

**Comment by tapionx** [comment]
i confirm the issue.
Steps to reproduce:
```mitmdump -w dump```
```mitmproxy -r dump```
here i can see the requests in the correct order
```mitmweb -r dump```
now the requests are all mixed

Being able to inspect the requests in the original order is really important when you need to debug a session
