### ISSUE TITLE
Setup JS Testing Infrastructure

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2093]
I noticed that I'm a bit reluctant to quickly merge mitmweb PRs as our testing situation there is rather terrible and I have to be very careful when reviewing. As a first step to mitigate this, we should set up a Travis CI job that run the jest tests we have in https://github.com/mitmproxy/mitmproxy/tree/master/web/src/js/__tests__. 
Not sure if the existing tests even run - if not, it's okay to mark the travis job to allow failures and then fix the tests in a separate PR.

**Comment by MatthewShao** [comment]
For those who don't know: we are using Jest in mitmweb. You could find out how to run the test at [Getting Start - Jest](http://facebook.github.io/jest/docs/getting-started.html).
@mhils I think we should consider about adding the Jest as a part of gulp, maybe in the `dev` task.

**Comment by mhils** [comment]
gulp: Generally not a bad idea. I wouldn't want this to be part of the `dev` task though as that needs to be as fast as possible. I tend to run `jest --watch` if I am explicitly working with tests. And yes, that needs to be documented in web/README.

Not sure how useful an isolated gulp task it, but I would certainly be open to merging one.
