### ISSUE TITLE
Make the eventlog more sticky

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#2103]
##### Steps to reproduce the problem:

1. Start mitmproxy (console UI).
2. Press E to show the eventlog.
3. Do something to replace the entire view. For example, press ? to show help.
4. Press Q to go back. The eventlog is gone.
5. But apparently its state is still remembered somewhere, because, to show the eventlog again, I have to press E *twice*.

##### Any other comments?

I think it would be better if the eventlog stayed on screen after returning from another view. If not, at least the double-E bug should be fixed.

##### System information

(this is mitmproxy master)

Mitmproxy version: 3.0.0 (release version) 
Python version: 3.5.2
Platform: Linux-4.4.0-64-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by krsoninikhil** [comment]
I had encountered this before. Looking to fix.

**Comment by cortesi** [comment]
See discussion on #2112 for the approach I recommend here.

**Comment by Kriechi** [comment]
Should be fixed via https://github.com/mitmproxy/mitmproxy/pull/2112#issuecomment-300627117
