### ISSUE TITLE
IPv6 IPs are not formatted properly in console output

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2109]
##### Steps to reproduce the problem:

1. `mitmproxy -R http://example.com`
2. `curl https://[::1]:8080`

The output currently looks like this:
```
('::1', 56795, 0, 0): clientconnect
```
But should probably look more like this:
```
[::1]:56795: clientconnect
```

##### System information

Mitmproxy version: 3.0.0.dev (2.0.0dev0064-0xbda3933)
Python version: 3.6.0
Platform: Windows-10-10.0.14393-SP0
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Windows version: 10 10.0.14393 SP0 Multiprocessor Free

**Comment by mhils** [comment]
Also:
```
Proxy server listening at http://:::8081
```

**Comment by madhusai3113** [comment]
@mhils I would like to take a shot at this issue.

**Comment by PiyushGoyal443** [comment]
Is this issue still open?

**Comment by mhils** [comment]
@PiyushGoyal443: If you look closely, you'll see that there's an open PR linked above.
