### ISSUE TITLE
`mitmdump --version` is confusing.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2110]
##### Steps to reproduce the problem:

1. `mitmdump --version`

The output is 
```
Mitmproxy version: 3.0.0.dev (2.0.0dev0064-0xbda3933)
```
for me, stating two conflicting versions. Not sure what we actually want to do here?

**Comment by Kriechi** [comment]
I saw multiple new issues in recent weeks that seem to have mitmproxy-master, but `--version` shows it as `release version`. Thats why I added the `.dev` to our `VERSION` variable.
Gathering the information from git seems to not work reliable, or people are using mitmproxy-master without git (e.g. straight from a tar.gz source or something)

**Comment by mhils** [comment]
Yes. We should also get rid of that "release version" string in its current form, that's pretty misleading.
