### ISSUE TITLE
reverse proxy mode for h2→h2c connections not working

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#2115]
##### Steps to reproduce the problem:

1. Start listening on local port 8081 like this: `nc -vl 8081`
2. Start mitmproxy like this: `mitmdump --http2 --reverse http://localhost:8081`
3. Use [nghttp](https://nghttp2.org/documentation/nghttp.1.html) to make a request like this: `nghttp -v https://localhost:8080/`
4. mitmdump prints:

```
('::ffff:127.0.0.1', 39950, 0, 0): clientconnect
('::ffff:127.0.0.1', 39950, 0, 0): Traceback (most recent call last):
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/server.py", line 118, in handle
    root_layer()
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/modes/reverse_proxy.py", line 13, in __call__
    layer()
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/protocol/http2.py", line 325, in __call__
    self._initiate_server_conn()
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/protocol/http2.py", line 111, in _initiate_server_conn
    self.connections[self.server_conn].initiate_connection()
KeyError: <ServerConnection: localhost:8081>

Traceback (most recent call last):
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/server.py", line 118, in handle
    root_layer()
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/modes/reverse_proxy.py", line 13, in __call__
    layer()
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/protocol/tls.py", line 383, in __call__
    layer()
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/protocol/http2.py", line 325, in __call__
    self._initiate_server_conn()
  File "/home/vasiliy/tmp/env8/lib/python3.5/site-packages/mitmproxy/proxy/protocol/http2.py", line 111, in _initiate_server_conn
    self.connections[self.server_conn].initiate_connection()
KeyError: <ServerConnection: localhost:8081>

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
('::ffff:127.0.0.1', 39950, 0, 0): clientdisconnect
```

Meanwhile, nghttp prints that it has sent a bunch of HTTP/2 frames, but not received any.

Meanwhile, no connections are made to port 8081.

##### Any other comments? What have you tried so far?

I’m not sure what I would *expect* to happen. What I would *like* to happen is that mitmproxy talk cleartext HTTP/2 (direct or upgrading) to port 8081, and talk HTTP/2-over-TLS to nghttp.

If I use a Web browser instead of nghttp, then mitmproxy talks cleartext HTTP/1.1 to port 8081, and talks HTTP/1.1-over-TLS to the browser.

See also #2116.

##### System information

(this is mitmproxy master)

Mitmproxy version: 3.0.0 (release version) 
Python version: 3.5.2
Platform: Linux-4.4.0-65-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by Kriechi** [comment]
Reverse proxy mode for HTTP/2 is currently not implemented. Neither is h2c. Sorry.
However, we should probably fail with a better error message or something.

**Comment by mhils** [comment]
I think this is not about "not implemented", but more about a logic error in https://github.com/mitmproxy/mitmproxy/blob/cb6240974d16e9f2923543fe28c201d39a63f60f/mitmproxy/proxy/protocol/http2.py#L104-L111. This will always KeyError if `self.server_conn.connected()` is not True.

**Comment by vfaronov** [comment]
I took the liberty to edit the title, because reverse proxy mode for h2→h2 definitely does work for me. It’s only when I try to do strange things that I get strange results :)

**Comment by Kriechi** [comment]
h2c is now disabled entirely.
Mixed http proxying is not supported.

**Comment by vfaronov** [comment]
@Kriechi After thinking more about this issue, I think it’s not really about h2c. Imagine I have a plain old HTTP/1.1 server. I can use mitmproxy to wrap it in TLS (indeed, this is mentioned as a use case [in the docs](http://docs.mitmproxy.org/en/latest/modes.html#reverse-proxy)), but I can’t wrap it in HTTP/2 because of this issue.

**Comment by Kriechi** [comment]
Yes you are correct - as stated, mixed proxying is currently not supported.
This means if one endpoint in your chain wants to do HTTP/2, everything as to be HTTP/2. mitmproxy is currently not capable of translating between HTTP/1.1 and HTTP/2 in any direction. For the same reason, mitmproxy does not support the CONNECT method in HTTP/2 at the moment.

**Comment by vfaronov** [comment]
Ah, I see... For some reason, I thought mitmproxy supported HTTP/1.1↔HTTP/2 as long as both were TLS, but apparently I was wrong.

**Comment by Kriechi** [comment]
We are happy to accept PRs if you want to add this as a new feature! 😄 
However I think this would probably make the h2-internals in mitmproxy overly complex for a rarely used feature (I guess?)

**Comment by TuomasKiviaho** [comment]
> However I think this would probably make the h2-internals in mitmproxy overly complex for a rarely used feature (I guess?)

I was trying to do similar TLS offloading like what HAProxy is capable of providing to Jetty (https://www.eclipse.org/jetty/documentation/9.3.x/http2-enabling.html and https://www.eclipse.org/jetty/documentation/9.4.x/http2-configuring-haproxy.html), but apparently that's not possible.

@mhils suggested `force_alpn` at https://discourse.mitmproxy.org/t/using-mitmproxy-to-terminate-tls-for-http-2/404 and that still puzzles me. Would it be possible to make TLS offloading possible (alpn+h2) without even needing h2c.
