### ISSUE TITLE
IPv6: HTTP protocol error in client request: Bad HTTP request line

### ISSUE THREAD

**Issue by rbairwell** [mitmproxy/mitmproxy#2119]
##### Steps to reproduce the problem:

1. Run MITMDump in a Vagrant powered virtual machine which only has an IPv4 address: mitmdump -p 5757
2. Configure Firefox to use it a proxy (Firefox is on a host which has IPv6)
3. Visit http://[2a01:b000:d:dc1::2:cafe]/images-nc/bg.gif?&testdomain=test-ipv6.com&testname=test_ipv6_img
4. Receive unexpected warning/error in mimdump console:
```
10.0.2.2:61356: HTTP protocol error in client request: Bad HTTP request line: b'GET http://[2a01:b000:d:dc1::2:cafe]/images-nc/bg.gif?&testdomain=test-ipv6.com&testname=test_ipv6_img HTTP/1.1'
```
and in Firefox:
```
400 Bad Request

HttpSyntaxException("Bad HTTP request line: b'GET http://[2a01:b000:d:dc1::2:cafe]/images-nc/bg.gif?&testdomain=test-ipv6.com&testname=test_ipv6_img HTTP/1.1'",)
```
[expected a graphic to be returned]

(found when testing http://test-ipv6.com)

##### Any other comments? What have you tried so far?

I do not know the IPv4 limitation of the Vagrant machine running MITMDump is a contributing factor at this point.

##### System information

Mitmproxy version: 2.0.0 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-3.13.0-83-generic-x86_64-with-debian-jessie-sid
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian jessie/sid

**Comment by mhils** [comment]
Thanks. I believe @Kriechi fixed this in #2050. Could you try again with a snapshot binary from https://snapshots.mitmproxy.org/?

**Comment by rbairwell** [comment]
Thanks, that does seem to be working on that case now, however, it's broken:
```
entry["serverIPAddress"] = str(flow.server_conn.ip_address.address[0])
```
(as used on line 150 of https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/har_dump.py )
with the message
```
AttributeError: 'tuple' object has no attribute 'address'
```

**Comment by mhils** [comment]
Thanks, happy to hear that. #2121 should fix the issue you are seeing.

**Comment by rbairwell** [comment]
Yes it does, and just for any one else, the following will allow your code to be compatible with 2.0.0 and the latest snapshot:
````
            if isinstance(flow.server_conn.ip_address,tuple):
                entry["serverIPAddress"] = str(flow.server_conn.ip_address[0])
            else:
                entry["serverIPAddress"] = str(flow.server_conn.ip_address.address[0])
````
