### ISSUE TITLE
Changing palette options has no effect

### ISSUE THREAD

**Issue by ujjwal96** [mitmproxy/mitmproxy#2122]
##### Steps to reproduce the problem:

1. Start mitmproxy
2. Press `O` then `P`
3. Select any option, there is no change

##### System information
Mitmproxy version: 3.0.0 (2.0.0dev0068-0xcb62409) 
Python version: 3.5.2
Platform: Linux-4.4.0-62-generic-x86_64-with-elementary-0.4-loki
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: "elementary" 0.4 loki

**Comment by iharsh234** [comment]
@ujjwal96  , it worked for me. 
But there something strange , When i wasn't in virtual env and not in mitmproxy directory it throws error.
and on terminal it shows:
` master.options.toggler("palette_transparent")`
when we can easily verify that not there for sure . [here](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/palettepicker.py#L62)

**Comment by ujjwal96** [comment]
It isn't working for me :confused: I even tried 1.0.2 binary doesn't work in that either.
The issue you are talking about was solved in https://github.com/mitmproxy/mitmproxy/pull/2069

**Comment by iharsh234** [comment]
Ohh :sweat_smile: you're right.

**Comment by mhils** [comment]
Thanks. We should look into this once #2100 is in.

**Comment by cortesi** [comment]
The deep issue here was that the option manager subscription didn't work correctly if the callable was a bound method. The shallow issue was that the option name had changed. I've fixed both in my option manager branch.
