### ISSUE TITLE
Proxy for SSL connections 

### ISSUE THREAD

**Issue by mancubus77** [mitmproxy/mitmproxy#2125]
I use mitmproxy to collect user-agents information from my network, thus the applications works in monitoring mode without any additional rules. For HTTP it works as expected, but HTTPS traffic doesn't load on some pages due to security issues. Of course client has certificate from MITM:
![image](https://cloud.githubusercontent.com/assets/16170560/23735634/84c98364-04d2-11e7-8dd3-0464c522ec46.png) 
And it's necessary to add the exception, but it's hard to make it every time for new SSL host. I would be grateful for any advices how to overcome this limitation for firefox?

Here is mitmdump -v output:
```
127.0.0.1:55318: clientconnect
127.0.0.1:55318: request
  -> Request(CONNECT s3-ap-southeast-1.amazonaws.com:443)
127.0.0.1:55318: Set new server address: ('s3-ap-southeast-1.amazonaws.com', 443)
127.0.0.1:55318: Parsed Client Hello: sni=s3-ap-southeast-1.amazonaws.com, alpn=['h2', 'http/1.1']
127.0.0.1:55318: serverconnect
  -> s3-ap-southeast-1.amazonaws.com:443
127.0.0.1:55318: Establish TLS with server
127.0.0.1:55318: ALPN selected by server: 
127.0.0.1:55318: Establish TLS with client
127.0.0.1:55318: ALPN for client: http/1.1
127.0.0.1:55318: serverdisconnect
  -> s3-ap-southeast-1.amazonaws.com:443
**127.0.0.1:55318: Client Handshake failed. The client may not trust the proxy's certificate for s3-ap-southeast-1.amazonaws.com.**
127.0.0.1:55318: ClientHandshakeException('Cannot establish TLS with client (sni: s3-ap-southeast-1.amazonaws.com): TlsException("[(\'SSL routines\', \'ssl3_read_bytes\', \'tlsv1 alert unknown ca\')]",)',)
127.0.0.1:55318: clientdisconnect
```

**Comment by mancubus77** [comment]
I've found answer in documentation. Sorry to bother

**Comment by tdonovic** [comment]
Where in the docs did you find the answer?

**Comment by rannmann** [comment]
Since the above poster didn't give the solution:

> Mitmproxy can decrypt encrypted traffic on the fly, as long as the client trusts its built-in certificate authority. Usually this means that the mitmproxy CA certificates have to be installed on the client device.

https://docs.mitmproxy.org/stable/concepts-certificates/
