### ISSUE TITLE
Websocket third party support

### ISSUE THREAD

**Issue by teixeiras** [mitmproxy/mitmproxy#2126]
Question and not a issue:
Hi:
I been looking for an integration using websocket. They should by default be enabled but it's only enabled in mitmweb. If the authentication on web socket is based on cookie, I can deduce, there is no other way to authenticate, without a web request, right?

**Comment by Kriechi** [comment]
WebSocket support should be enabled in all three tools: mitmproxy, mitmdump, and mitmweb.

What do you mean by _authentication_? mitmproxy sees all traffic, including cookies of the initial handshake.
