### ISSUE TITLE
mitmweb event log doesn’t show messages at level higher than info

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#2134]
##### Steps to reproduce the problem:

1. Create the following `script1.py`:

```
import mitmproxy.ctx

def response(flow):
    mitmproxy.ctx.log.info('this is an info')
    mitmproxy.ctx.log.warn('this is a warning')
    mitmproxy.ctx.log.error('this is an error')
```

2. Start mitmweb with this script: `mitmweb -s script1.py`
3. Enable *Options* → *Display Event Log* to show the event log pane.
4. Run a flow through mitmweb, for example: `curl -vx http://localhost:8080 http://httpbin.org/get/`
5. Observe that three messages are printed to the system console (“this is an info”, “this is a warning”, “this is an error”), but only one of them is displayed in the event log pane in mitmweb (“this is an info”).

##### Any other comments? What have you tried so far?

Checking the “debug” checkbox at the top right-hand corner of the event log pane has no effect on this.

##### System information

(this is mitmproxy master)

Mitmproxy version: 3.0.0 (release version) 
Python version: 3.5.2
Platform: Linux-4.4.0-66-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by mhils** [comment]
Thanks!

**Comment by syahn** [comment]
I'm working on!

**Comment by LuD1161** [comment]
@vfaronov @mhils 
I was trying to reproduce this issue but couldn't , I got this :

![image](https://cloud.githubusercontent.com/assets/17861054/24069635/4e4b27c8-0bd2-11e7-9699-5e4a27ba6192.png)

```
Traceback (most recent call last):
  File "/root/mitmproxy/venv/bin/mitmweb", line 11, in <module>
    load_entry_point('mitmproxy', 'console_scripts', 'mitmweb')()
  File "/root/mitmproxy/mitmproxy/tools/main.py", line 117, in mitmweb
    run(web.master.WebMaster, args)
  File "/root/mitmproxy/mitmproxy/tools/main.py", line 75, in run
    master.addons.configure_all(opts, opts.keys())
  File "/root/mitmproxy/mitmproxy/addonmanager.py", line 36, in configure_all
    self.trigger("configure", options, updated)
  File "/root/mitmproxy/mitmproxy/addonmanager.py", line 116, in trigger
    self.invoke_addon(i, name, *args, **kwargs)
  File "/root/mitmproxy/mitmproxy/addonmanager.py", line 107, in invoke_addon
    func(*args, **kwargs)
  File "/root/mitmproxy/mitmproxy/addons/script.py", line 263, in configure
    ctx.log.info("Loading script: %s" % s)
  File "/root/mitmproxy/mitmproxy/log.py", line 25, in info
    self(txt, "info")
  File "/root/mitmproxy/mitmproxy/log.py", line 40, in __call__
    self.master.add_log(text, level)
  File "/root/mitmproxy/mitmproxy/master.py", line 67, in add_log
    self.addons.trigger("log", log.LogEntry(e, level))
  File "/root/mitmproxy/mitmproxy/addonmanager.py", line 116, in trigger
    self.invoke_addon(i, name, *args, **kwargs)
  File "/root/mitmproxy/mitmproxy/addonmanager.py", line 107, in invoke_addon
    func(*args, **kwargs)
  File "/root/mitmproxy/mitmproxy/addons/termlog.py", line 21, in log
    if self.options.verbosity >= log.log_tier(e.level):
AttributeError: 'NoneType' object has no attribute 'verbosity'

```


*My Config file is working fine :*
![image](https://cloud.githubusercontent.com/assets/17861054/24069625/2416ca7a-0bd2-11e7-84f7-8ee137c01ac1.png)

**I may be missing something , please tell me how to reproduce the issue.**

Mitmproxy version: 3.0.0 (2.0.0dev0203-0xc0882496) 
Python version: 3.5.3
Platform: Linux-4.6.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: Kali kali-rolling kali-rolling

**Comment by syahn** [comment]
@LuD1161 It's a bug. See #2178 and edit code like that, and you'll be alright.

**Comment by LuD1161** [comment]
@syahn 
Thanks , it's working fine.
I should have put much effort in searching for the solution
