### ISSUE TITLE
mitmdump: unrecognized arguments: -dd

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2139]
##### Steps to reproduce the problem:

1. `mitmdump -d -nr foo.mitm`

```
mitmdump: error: unrecognized arguments: -d
```

##### System information

Mitmproxy version: 3.0.0 (2.0.0dev0136-0x05e1154)
Python version: 3.5.2
Platform: Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
SSL version: OpenSSL 1.0.2g-fips  1 Mar 2016
Linux distro: Ubuntu 14.04 trusty

**Comment by mhils** [comment]
This is apparently `--flow-detail` now. `mitmdump --help` explains that I should use `--flow-detail LEVEL`, but does not indicate what a valid value for LEVEL would be.

**Comment by LuD1161** [comment]
@mhils 
Is this good ?
![image](https://cloud.githubusercontent.com/assets/17861054/24093358/6fee00e6-0d79-11e7-84c5-84cb5f66008b.png)
