### ISSUE TITLE
Uniquely identify client connections from dumpfiles.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2143]
I'm currently running an issue where I read a saved flow file and I need to match flows to HTTP connections.

The intuitive way to do this would be to compare `f.client_conn == f2.client_conn`, which holds true for live connections but not for saved ones, because each flow has its own distinct ClientConnection object. Possible ways to fix this:

- Add `__eq__` implementation to ClientConnection (either by checking ip tuples + timestamp or by adding a unique id)
- Enhance FlowReader to re-use ClientConnections. I don't like this, but that would be more consistent with the live behavior.
- ???

The same problem applies to ServerConnections.

@mitmproxy/devs: thoughts?

**Comment by mhils** [comment]
Thinking more about this, option 2 would not work without significant changes to how we save flows. Given that connections should be read-only anyway, let's go for implementing `__hash__` and `__eq__`.

**Comment by cortesi** [comment]
A definite +1 for a persistent ID to identify connections, rather than object identity.

**Comment by mhils** [comment]
I was about to push a commit that implements __eq__ and __hash__ based on address and timestamp. you strongly prefer ids?

**Comment by cortesi** [comment]
A persistent ID is analogous to what we do with flows, and leaves us open to vary the attributes of the object without confusion. I think eq and hash could still rely on the persistent ID. This is a somewhat fine distinction: my main point was not to use object identity - that is, re-use ClientConnection objects as I understood your second option.

**Comment by mhils** [comment]
Ok, let's do that.

**Comment by cortesi** [comment]
As an addendum, I'd probably prefer not to implement hash, here. When we need to handle ClientConnection objects, I'd probably rather have an explicit ```d[conn.id] = conn```.
