### ISSUE TITLE
Can't filter by hostname when --host is used

### ISSUE THREAD

**Issue by dequis** [mitmproxy/mitmproxy#2146]
##### Steps to reproduce the problem:

1. mitmproxy -T --host
2. Capture something
3. Press f and filter by something like `~d domain.com` or `~u domain com`

##### Any other comments? What have you tried so far?

Going to detail view to get the resolved IP address and using it for the filter works, but it's uncomfortable when you want to match things like "google.com" (lots of IP ranges, lots of unrelated domains, but many mentioning google)

##### System information

Mitmproxy version: 2.0.0 (release version)
Python version: 3.6.0
Platform: Linux-4.9.11-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.0.2k  26 Jan 2017
Linux distro: arch

**Comment by mhils** [comment]
Thanks for the report. It's probably a good idea to also iterate over the host headers for `~d`. This needs to be fixed in flowfilter.py and filt.peg.
