### ISSUE TITLE
cryptography dependency update?

### ISSUE THREAD

**Issue by DomT4** [mitmproxy/mitmproxy#2154]
The template here wasn't relevant so I cut it, apologies.

`mitmproxy` currently mandates `cryptography <1.8` which when built from source on macOS/OS X El Capitan (10.11) using Xcode 8 results in `Symbol not found: _getentropy` errors. Reported and explained in more detail [here](https://github.com/pyca/cryptography/issues/3332), hence my short summary. These issues were fixed in https://github.com/pyca/cryptography/pull/3354, which was released in the 1.8 branch.

This is also currently causing some "fun" for downstream package managers having to carry their own somewhat hacky patches like [this](https://github.com/Homebrew/homebrew-core/blob/37abcfc55099f635d0e187657a55a1eed36b5ccf/Formula/mitmproxy.rb#L193-L202). The gist of my request is whether `mitmproxy` has plans to/would consider update/updating [cryptography](https://github.com/mitmproxy/mitmproxy/blob/e723a58af5dc4fc7a46958aa9ce8c386a7387450/setup.py#L67) to use the latest release without these issues.

**Comment by Kriechi** [comment]
Thanks for pointing this out!
Usually we are very happy do bump our dependencies - and in the past we got a notification by our tooling. Somehow we missed this one - sorry! It's only been five days since the 1.8 release though... 😄 

I've create PR #2155 to address this.

**Comment by Kriechi** [comment]
Our next release is scheduled for end of April. I'm thinking of backporting this to 2.0.x and doing a v2.0.1. @mitmproxy/devs?

The cryptography 1.8 and 1.8.1 changelog looks rather interesting:
https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#181---2017-03-10

**Comment by mhils** [comment]
If this is helpful to downstream, let's go for it!

**Comment by DomT4** [comment]
Thank you for moving so quickly on this! Really appreciate coming back online this afternoon and finding the whole situation wrapped up 🙇.

**Comment by Kriechi** [comment]
I was just about to write a new comment to notify you about the new release. 👍 
Have fun! Let us know if you need anything else to make your live downstream easier - we are happy to help! Thanks!
