### ISSUE TITLE
No error/warning on setting invalid options

### ISSUE THREAD

**Issue by krsoninikhil** [mitmproxy/mitmproxy#2174]
##### Steps to reproduce the problem:

1. Start with `mitmproxy --set mode=transparen` (with typo in value of mode)
2. Mitmproxy starts in regular mode without giving any error. 

##### Any other comments? What have you tried so far?

If you use `mitmproxy --mode transparen` (with typo in value of mode), it throws error `Invalid mode specification: transparen`.

##### System information

Mitmproxy version: 3.0.0 (1.0.1dev0414-0xe755399d) 
Python version: 3.6.0
Platform: Linux-4.8.13-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Linux distro: arch

**Comment by LuD1161** [comment]
@mhils 
I am still understanding the tool.
Can I start working on this ? 
 .

**Comment by mhils** [comment]
@LuD1161, I would recommend to start with issues tagged as "good first contribution" when you are just getting started. :)

I deliberately did not label this one as suitable - @cortesi is currently changing all the bits around option handling, so this is something he probably wants to look into.
