### ISSUE TITLE
Problems with certs - Error: certificate signature failure

### ISSUE THREAD

**Issue by simov** [mitmproxy/mitmproxy#2179]
Hi,

I'm having problems with the certificates that mitmproxy generates for me:

```bash
sudo cp ~/.mitmproxy/*.* /usr/share/ca-certificates/mitmproxy/
sudo dpkg-reconfigure ca-certificates
```

Then I'm using this [script](https://github.com/lemonsqueeze/urldump/blob/master/urldump) to proxy all requests to mitmproxy.

The error that I'm receiving from a Node app is:

```
{ Error: certificate signature failure
    at TLSSocket.<anonymous> (_tls_wrap.js:1084:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:606:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:436:38) code: 'CERT_SIGNATURE_FAILURE' }
```

The HTTPS requests fail from any other app too. I can verify that all traffic is indeed proxied to mitm, bacause all HTTP traffic is logged using the above script and also if I disable the TLS security in my test Node app the HTTPS requests are logged out too. Unfortunately I can't disable the TLS security for the app that I want to debug.

System information:

```
ubuntu 16.10
mitmproxy 0.15
```

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by simov** [comment]
Same result with:

```
Mitmproxy version: 2.0.1 (1.0.8dev0016-0xd1ff898) 
Python version: 3.6.0
Platform: Linux-4.8.0-40-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: debian stretch/sid 
```

**Comment by mhils** [comment]
Did you delete `/.mitmproxy/` in between?

**Comment by simov** [comment]
Yep, I removed all files and re-generated them by executing `mitmproxy`, then I moved them to `/usr/share/ca-certificates/mitmproxy`, renamed `mitmproxy-ca-cert.cer` to `mitmproxy-ca-cert.crt` and executed `sudo dpkg-reconfigure ca-certificates` the result was:

```
Processing triggers for ca-certificates (20160104ubuntu1) ...
Updating certificates in /etc/ssl/certs...
WARNING: dhparam.pem does not contain a certificate or CRL: skipping
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

**Comment by simov** [comment]
This line `curl -x localhost:8080 --cacert mitmproxy-ca-cert.cer https://example.com/` works only if I run `mitmproxy`.

But when I run this [script](https://github.com/lemonsqueeze/urldump/blob/master/urldump) that uses `mitmdump` internally, the above command throws error:

```
curl: (56) Received HTTP code 400 from proxy after CONNECT
```

**Comment by mhils** [comment]
The script you linked configures mitmproxy as a transparent proxy - in this case, it's not necessary to specify a proxy when invoking curl. On the contrary, we'll complain because HTTP CONNECTs in transparent mode usually indicate a misconfiguration (not sure why curl isn't displaying a full warning). Long story short, if you run the script you linked, `curl --cacert mitmproxy-ca-cert.cer https://example.com/` should work.

**Comment by simov** [comment]
Now the error is:

```
curl: (60) server certificate verification failed. CAfile: mitmproxy-ca-cert.cer CRLfile: none
```

and the same error from my node script:

```
{ Error: certificate signature failure
    at TLSSocket.<anonymous> (_tls_wrap.js:1084:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:606:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:436:38) code: 'CERT_SIGNATURE_FAILURE' }
```

The only thing I changed in that script was to create a new user `sudo adduser mitmproxy` and set it `user=mitmproxy`.
