### ISSUE TITLE
mitmproxy doesn't forward `Expect: 100-continue` headers to the end server

### ISSUE THREAD

**Issue by alinpopa** [mitmproxy/mitmproxy#2180]
##### Quick description

When using mitmproxy, and sending a large POST request using curl (which as well sets the `Expect: 100-continue` header), will strip out the `expect` header, and this will not get to the end server. When using a script to set the `expect` header, the request hangs.

##### Steps to reproduce the problem:

1. Create a minimal http server that is capable of the followings:
- accept POST/PUT requests
- logs out all the request headers, and the request body
2. Start mitmproxy
3. Send a POST request using curl, having a considerable large request body (I've used a json, Content-Length: 2017
4. Notice the final server will not get the `expect` header.

##### Any other comments? What have you tried so far?

Tried to use a script in order to set the `expect` header, but it looks like that the entire flow hangs.
Due to this issue, we've noticed on a production servers (that are relying on this particular 100 Continue feature) that the request body gets truncated. Sure, we fixed this, but was thinking that this 100 Continue thing shouldn't be hidden by mitmproxy, but to be forwarded to the end server.

##### System information

Mitmproxy version: 2.0.1 (release version)
Python version: 3.6.0
Platform: Darwin-16.4.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.3 ('', '', '') x86_64

**Comment by cortesi** [comment]
Dupe for #1721. This is a feature I'd really like, but that's not implemented yet. If you have a use case for it, and felt like working on it, we'd be very happy to talk you through it! :)
