### ISSUE TITLE
Allow live editing of ProxyServer configuration

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#2185]
We can now edit ProxyServer configuration options on the fly, but many options aren't acted on. For instance, we can change whether a server is started, the binding address and port and so forth. 

We need a ProxyServer manager addon that responds to configuration changes by shutting down and restarting the ProxyServer with the new options. This is closely related to the ProxyConfig class, which will probably be the basis for the addon.

**Comment by LuD1161** [comment]
@cortesi 
I would like to work on this.

**Comment by paraschetal** [comment]
Working on it :)

**Comment by paraschetal** [comment]
If someone else wants to work on this, by all means, go ahead. I don't think I'll be able to devote enough time to this right now.

**Comment by LuD1161** [comment]
@cortesi 
I wish to work on it but am unsure of where should I start from.

Is it something related to watchdog ?

**Comment by mhils** [comment]
Fixed now!
