### ISSUE TITLE
mitmproxy: Error starting proxy server: Address already in use

### ISSUE THREAD

**Issue by adforcetestuser1** [mitmproxy/mitmproxy#219]
Hi, I encountered a problem
I´ve installed the mitmproxy on Ubuntu Server 12.04

If i write for example mitmproxy, i get the message 
"mitmproxy: Error starting proxy server: Address already in use"

But, if i write mitmproxy -p 3128 into the terminal he start´s the proxy but don´t track anything.
Please, help me

**Comment by wangofjian** [comment]
I change the listening port,  use "mitmproxy -p 9999" instead ,it works.

**Comment by csicar** [comment]
i my case "mitmproxy" was using the port 8080. look for appications running on that port and close them.
mitmproxy should work afterwards

**Comment by kaushalPal86sq** [comment]
Just in case above solutions didn't work:
Follow the following steps:

1. Get the port your process is listening to:
$ ps ax | grep python

2. Kill the Process
$ kill PROCESS_NAME

**Comment by fabriziobertoglio1987** [comment]
I can not close the application running on 8080. How do I do?
