### ISSUE TITLE
full replace responce via script

### ISSUE THREAD

**Issue by jake491** [mitmproxy/mitmproxy#2192]
I want to replace status code, headers, content of response from server

##### Steps to reproduce the problem:

1. write script (see below)
2. run mitmdump -p 8080 -s myplugin.py
3. open browser and via mitmproxy go to example.com/dir1/?par1=100500 I got a blank screen (load a bit a page)
4. open example.com/dir1/?par1=100500 via curl with mitmproxy and get other bit of page

What is the best practice for replace response from one server to other server.
plugin code:
```
def response(flow):
    new_resp = requests.get('https://google.com')

    new_resp_headers=dict(new_resp.headers.items())
    
    #prepare byte headers
    byte_headers = [(str.encode(k), str.encode(v)) for k, v in new_resp_headers.items()]

    #replace responce
    flow.response.status_code = new_resp.status_code
    flow.response.content = new_resp.content
    flow.response.data.headers = Headers(byte_headers)
```

another way is is 
```
....
    new_resp = Response.make(200,authenticated_responce.content,byte_headers )
    flow.response = new_resp
```

AttributeError: 'Response' object has no attribute 'is_replay'
##### System information
Mitmproxy version: 2.0.0 (release version) 
Python version: 3.5.2

**Comment by mhils** [comment]
This sounds like you are looking for [examples/simple/send_reply_from_proxy.py](https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/send_reply_from_proxy.py).
