### ISSUE TITLE
Replay does not work with HTTP/2 flows.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2197]
##### Steps to reproduce the problem:

1. Replay a HTTP/2 flow.
2. Notice that the server fails because it expects a `host` header, but we only send an `:authority` header.

##### System information

Mitmproxy version: 3.0.0 (2.0.0dev0229-0x0c0c0d3)
Python version: 3.5.2
Platform: Linux-3.4.0+-x86_64-with-Ubuntu-14.04-trusty
SSL version: OpenSSL 1.0.2g-fips  1 Mar 2016
Linux distro: Ubuntu 14.04 trusty

**Comment by Kriechi** [comment]
Are you trying to replay an HTTP/2 request against a HTTP/1 server?
If we would want to support this mixed-protocol-proxying, I guess we have to emulate/set that header (and possible others as well?)

**Comment by mhils** [comment]
Not trying intentionally, but that's what currently happens if you press `r` on a HTTP/2.0 flow. So I'm not necessarily saying we have to translate headers, we could also do the replay using HTTP/2.0. Not sure what's best, but we should do one of those things. :)

**Comment by Kriechi** [comment]
As discussed, the way to fix this is by always replaying via a fresh HTTP/1 connection and setting the correct headers: renaming `:authority` to `Host` (value should be the same), and changing `http_version` of the request.
