### ISSUE TITLE
Teach options to know about a Path type

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#2198]
At the moment, the type we use for Path values is str. We use paths in many options, and we'd like to handle them specially in user interfaces (so we can, for instance, do path completion on tab). 

We should teach optmanager to know about a Path type, which is treated just like a string. Ergonomically, I'd like user to still be able to say ```options.path = "value"``` rather than have to say ```options.path = types.Path("value")```, so it would be good to automatically handle type promotion.

**Comment by vmnguyen** [comment]
I'm working on it

**Comment by nikofil** [comment]
I am also working on this. Could a maintainer tell me if #2209 is a step in the right direction? (I am also thinking of integrating some common `os.path` functions in Path)
