### ISSUE TITLE
Remove watchdog dependency

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#2214]
Taken from the [GSoC 2017 ideas page](https://honeynet.org/gsoc/ideas#mitmproxy-core), because this should really be an issue here.

We currently depend on the watchdog library to watch the filesystem and reload mitmproxy scripts automatically. Due to numerous bugs in watchdog, we have restricted ourselves to using only watchdogs's PollingObserver over time. Watchdog now is a large dependency with platform-specific binary components and multiple subdependencies which we do not really use, so we want reimplement the very small subset that is needed for mitmproxy in pure Python. This makes mitmproxy smaller and we don't have to worry about watchdog breaking mitmproxy installations anymore.

**Comment by Kriechi** [comment]
We should look around a bit, and test existing libraries if they fit our needs, before rolling our own solution.

https://github.com/shaurz/fsmonitor looks promising at first glance.

**Comment by mhils** [comment]
fsmonitor depends on pypiwin32, no thank you. 😉 
We had to disable all platform-specific parts of watchdog over time because they all were broken in one way or another (apparently nobody tests `unwatch()`...). We really should just implement super simple polling where we `stat()` the directory twice per second and be done.

**Comment by Kriechi** [comment]
We can probably start by ~stealing~ using https://github.com/shaurz/fsmonitor/blob/master/fsmonitor/polling.py and
https://github.com/shaurz/fsmonitor/blob/master/examples/filewatch.py
It's MIT licence, so we should be good.

**Comment by cortesi** [comment]
Please leave this one to me - I'm right in the middle of what amounts to a rewrite of the scripts mechanism. I'll be out of the loop for a few days, but should have something over the weekend.

**Comment by cortesi** [comment]
Fixed in #2263
