### ISSUE TITLE
Sticky cookies are improperly formatted.

### ISSUE THREAD

**Issue by kitling** [mitmproxy/mitmproxy#2228]
##### Steps to reproduce the problem:

1. Go to http://www.html-kit.com/tools/cookietester/
2. Click 'Set Test Cookie'
3. Observe that one cookie is sent to the server.
4. Remove the cookie.
5. launch mitmproxy with `mitmproxy -t html-kit\.com` and tell your browser to use it as a proxy
6. Reload the page.
7. Click 'Set Test Cookie'
8. Observe that two 'cookies' are sent to the server.

##### Any other comments? What have you tried so far?
There appears to be a comma in the output of mitmproxy, even though it is surrounded by quotes. It's possible, then that this is a parsing fail on the tool's end caused by a difference in what's sent back for the format of the date. Still, should it really be changing that?

##### System information
Arch Linux, freshly updated.

Mitmproxy version: 2.0.1 (release version) 
Python version: 3.6.0
Platform: Linux-4.10.6-1-ARCH-x86_64-with-glibc2.3.4
SSL version: OpenSSL 1.0.2k  26 Jan 2017

**Comment by mhils** [comment]
Thanks for the report. It looks like we parse it correctly:

```python
>>> from mitmproxy.net.http import cookies
>>> cookies.parse_set_cookie_header("TestCookie_Name_201704075049=TestCookie_Value_035049; Domain=www.html-kit.com; Expires=Sun, 09-Apr-2017 08:50:54 GMT; Path=/")
[
    ('TestCookie_Name_201704075049', 'TestCookie_Value_035049', CookieAttrs[
        ('Domain', 'www.html-kit.com'), 
        ('Expires', 'Sun, 09-Apr-2017 08:50:54 GMT'), 
        ('Path', '/')
    ])
]
```
But for some reason [stickycookie.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/stickycookie.py) includes the attributes in the `Cookie` header. My understanding is that this is very wrong. We definitely should catch that in our tests.

**Comment by kitling** [comment]
So, I've got a hack that seems to fix it. If you replace:
`l.extend([cookies.format_cookie_header(c[name].items(multi=True)) for name in c.keys()])`
with
`l.extend([cookies.format_cookie_header([c[name].items(multi=True)[0]]) for name in c.keys()])`

I don't like this solution, though.

The issue appears to be with how the cookies are stored in the sticky cookie implementation, as well as, to an extent, the `format_cookie_header()` implementation. Sticky cookies stores them as a list of `(key, value)` tuple lists, instead of a list of `(key, value, CookieAttrs[(k,v),(k,v)])` tuples as seems to be used elsewhere. `format_cookie_header()` expects a list of `(key, value)` tuples for each cookie. It is noteworthy that this seems broken at the moment, because the way it should work as currently implemented should give me cookies for every attribute.

The changes I would reccomend would be to have `format_cookie_header()` take a list `(key, value, CookieAttrs[(k,v),(k,v)])` tuples, same as `format_set_cookie_header()` and change the cookie jar in sticky cookies to store cookies in this same format. If there are big issues with this, the hack I mentioned above can be applied.

**Comment by kitling** [comment]
I'm going to go ahead and submit the hack in a pull request, for now.
