### ISSUE TITLE
Cyrillic domains https problem

### ISSUE THREAD

**Issue by ErDmKo** [mitmproxy/mitmproxy#2230]
##### Steps to reproduce the problem:

1. Start http proxy
2. Go to https://фонд-достоинство.рф
3. See the problem Certificate Verification Error for фонд-достоинство.рф: hostname 'фонд-достоинство.рф' doesn't match 'xn----dtbebu0aecead5adket.xn--p1ai'

##### System information

Mitmproxy version: 2.0.1 (release version) 
Python version: 3.6.1
Platform: Darwin-15.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.11.6 ('', '', '') x86_64

**Comment by mhils** [comment]
Thanks for the report! This very much looks like a bug. As a short-term workaround, you can pass `--ssl-insecure` to disable upstream certificate verification. The certificate we generate seems to be okay.

**Comment by iharsh234** [comment]
I want to take this.
I think a message/warning like this

> invalid certificate closing connection , pass `--ssl-insecure `(short = `k `) to disable certification

could be a fix to this.
what say @mhils @Kriechi

**Comment by mhils** [comment]
Definitely no. If the certificate is accepted by all major browsers, it should also be accepted by mitmproxy without turning off all security. If you (or anyone else) wants to tackle this, start here:

- Figure out & document the specified encoding for Subject Alternative Names
- Figure out & document the specified encoding for Server Name Indication
- Figure out & document why they don't match right now.
- Create a test case
