### ISSUE TITLE
Android application complain "unknown CA" in wireshark

### ISSUE THREAD

**Issue by Kailiangying** [mitmproxy/mitmproxy#2231]
I install the update to data mitmproxy from github. I am using mitmproxy as transparent proxy for my android device. I install the mitmproxy certificate on my android as system certificate and run the facebook app. The wireshark on proxy shows "Unknown CA" sent from server. Following is the detail of how I tried. 

##### Steps to reproduce the problem:
I. The proxy is running in transparent mode on an Ubuntu machine on the same network as the Android device
2. I install the CA from: mitm.it from browser in the Ubuntu machine. This approach gives me the user CA. 
3. I then follow the approach here to install same CA as system CA on the  Android device 
http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets
4. When I run the facebook Android app and receive the fake facebook certificate from proxy,  facebook throws ssl alert and shows unknown CA.

##### Any other comments? What have you tried so far?
Any suggestion how should I configure the Android to avoid the failure? 

Thanks for any suggestion. 

##### System information
I also attach the wireshark log for traffic information detail. 
[wiresharkCapture-facebook.pcapng.zip](https://github.com/mitmproxy/mitmproxy/files/904058/wiresharkCapture-facebook.pcapng.zip)

**Comment by mhils** [comment]
Hi,

It's likely that you're hitting [Certificate Pinning](http://docs.mitmproxy.org/en/stable/certinstall.html#certificate-pinning) with the Facebook app. The only way around this is to patch the app or jailbreak your device.
