### ISSUE TITLE
HAR export script problem

### ISSUE THREAD

**Issue by tzvetkov75** [mitmproxy/mitmproxy#2233]
Hi, I have problem making HAR export to work at all 
UBUNTU 16.04. default python 3.5 

Steps
1.  Wrote a flow to file `mitmdump -r ./a.flow` . used the binary 
2.  Tried to convert
`
vesselin@aspirin:~/Downloads/mitmproxy-2.0.1-linux$ mitmdump -s "./src/mitmproxy/examples/complex/har_dump.py test.har" -r ./a.flow 
Loading script: ./src/mitmproxy/examples/complex/har_dump.py test.har
Proxy server listening at http://0.0.0.0:8080
Script error: Traceback (most recent call last):
  File "./src/mitmproxy/examples/complex/har_dump.py", line 152, in response
    HAR["log"]["entries"].append(entry)
KeyError: 'log'
`

Can you help?
Thx
Vesselin

**Comment by ujjwal96** [comment]
Can you tell the mitmproxy version you are using and the version you took the script from?
There have been a few changes since the last release. From the error it looks like the start/load function is not being called in your case.
I wasn't able to reproduce this in the master.

**Comment by tzvetkov75** [comment]
Hi, I am using the latest version 
`
$ mitmdump --version
Mitmproxy version: 2.0.1 (release version) 
Python version: 3.5.2
Platform: Linux-4.4.0-71-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
`

and the script is latest on github

`
$ git log
commit c7b501275205e2cf82055981106336d4a0db252f
Merge: c76620c 7365f18
Author: Maximilian Hils <git@maximilianhils.com>
Date:   Sun Apr 9 01:15:50 2017 +0200
`

**Comment by ujjwal96** [comment]
If you are using 2.0.1 try using this script https://github.com/mitmproxy/mitmproxy/blob/5e99691e2c0039a013c50102ae30a96ab54439eb/examples/complex/har_dump.py

The recursion error is due to https://github.com/mitmproxy/mitmproxy/issues/2216 and is not the problem of har_dump script. I think the generated HAR file will be fine.

**Comment by tzvetkov75** [comment]
Thanks,  it works :+1: 
 I used the exact tag v2.0.1 (5e99691e2c0039a013c50102ae30a96ab54439eb)
