### ISSUE TITLE
Using external libraries with mitmdump

### ISSUE THREAD

**Issue by rikonor** [mitmproxy/mitmproxy#2238]
##### Steps to reproduce the problem:

1. Develop a need to use an external package in your mitmdump script, e.g BeautifulSoup.
2. Realize it's not documented. 😛 

##### Any other comments? What have you tried so far?

The only reference I was able to find online to this issue was on [Discourse](https://discourse.mitmproxy.org/t/issue-importing-beautifulsoup-into-a-script/324).
Although the solution presented there did end up helping me solve the issue - the fact that this is not documented anywhere (as far as I could tell) in the official docs is not great.

I would be happy to submit a PR in the Scripts part of the docs, but I don't think the solution I ended up using is very good - I just ran `/path/to/mitmproxy/libexec/bin/pip3 install <libname>`.

##### System information

Using version 2.0.1 on OSX, installed via homebrew.

**Comment by michaelschem** [comment]
Are you using the precompiled binaries?

**Comment by michaelschem** [comment]
oops, just realized you have the homebrew install.  I had a similar issue with the precompiled binaries as they use a version of python included in the binaries and therefore does not have access to your installed libs.  I fixed this by installing from the source on github.

**Comment by rikonor** [comment]
@michaelschem I actually like the fact that `mitmproxy` uses it's own python environment rather then the global one. This sort of emulates best-practices of using `venv`, `virtualenv`, etc to create reproducible python environments. That said - it should probably be documented somewhere.

**Comment by mhils** [comment]
Thanks for raising this, that's very helpful feedback. 😃 

@Kriechi: How is this supposed to work with homebrew? Is this something we could potentially fix?

In any case, we should really document this for the precompiled binaries at http://docs.mitmproxy.org/en/stable/scripting/overview.html.

**Comment by Kriechi** [comment]
Not sure, maybe @DomT4 or @ilovezfs can comment on this?

**Comment by ilovezfs** [comment]
@tdsmith are we recommending any particular way of doing this with the formulae using virtualenv, or would mitmproxy need to be switched (back) to using the non-virtualenv approach?

**Comment by tdsmith** [comment]
The virtualenv approach doesn't have any affordances for this kind of use (although I wouldn't drop it!).

@rikonor: fwiw the virtualenv is set up by Homebrew and not mitmproxy.

**Comment by rikonor** [comment]
I didn't even realize there's an actual virtualenv in the picture here. I
really do recommend documenting the recommended approach to installing
additional dependencies into your mitmdump scripts. As you can see from my
previous comment, the way I did it is undocumented and also not very
straightforward.

Thanks for taking the time to look into this!

**Comment by Kriechi** [comment]
@ilovezfs is there an official/recommended way of accessing the virtualenv created by homebrew?
Ideally we could add something like this to our README:

```
If you installed via Homebrew, you need to install new packages via the virtualenv:
  > $(brew --prefix mitmproxy)/libexec/bin/pip install my-dependency
```

Is this a supported way of interacting with Homebrew virtualenvs?
Or might this break things we better leave untouched?

**Comment by tdsmith** [comment]
> Is there an official/recommended way of accessing the virtualenv created by homebrew?

There is not.

You're not likely to break anything but it won't be preserved across package upgrades.

**Comment by ilovezfs** [comment]
The only supported way would be to add the relevant packages to the formula as resources, and either always install them or put them behind formula options. There is no supported way of doing it after the fact.

Since we generally don't like adding formula options, the approach of adding the packages to the formula is a bit of a Catch-22 unless the packages make sense for us to always install non-optionally (see the plethora of resources in the `ansible` formula), or unless the packages are added to a full copy of the formula that someone is maintaining in their own tap (https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap).

**Comment by tdsmith** [comment]
If I understand correctly that mitmdump is a script which generally isn't useful without third-party packages being available, one thing we could consider doing is rewriting the shebang for mitmdump and writing a wrapper script such that mitmdump launched by whatever python is in PATH, with the Homebrew-mitmproxy virtualenv added to PYTHONPATH, which is a little hacky but would expose globally installed packages.

**Comment by Kriechi** [comment]
@tdsmith about right - mitmproxy (including mitmdump and mitmweb) in general as the ability to run user scripts using our API. Since we can't predict what fancy Python packages users want to use together with our API, we won't be able to install them via the formulae.

Somehow dealing with PYTHONPATH is probably the direction to go - but messy, and we have to think about our precompiled binaries as well (pyinstaller), maybe we can generalize it so Homebrew and PyInstaller benefit from this...

**Comment by rikonor** [comment]
Not to barge in, and it might possibly not cover edges cases, etc - but wouldn't this all be solved if after installing mitmproxy (via Homebrew) you created (e.g) an alias like `mitmproxy-pip3` allowing users to install packages using `mitmproxy`'s copy of `pip3`? Since these scripts are pretty much always run via `mitmdump -s <script>` then what need is there to allow the user access to them via a normal virtual environment?

**Comment by Kriechi** [comment]
I'm not particularly happy with that, especially since this already works by using:
`$(brew --prefix mitmproxy)/libexec/bin/pip install my-dependency`

The main problem is that packages will vanish when upgrading mitmproxy via homebrew-upgrade.

**Comment by mhils** [comment]
Another user struggling with this: https://github.com/mitmproxy/mitmproxy/issues/2238

**Comment by ilovezfs** [comment]
@Kriechi as @tdsmith said, "You're not likely to break anything but it won't be preserved across package upgrades."

**Comment by michaelschem** [comment]
Why would it not just be the case that if you want to use mitmproxy with external libs, you need to install from source??

**Comment by rikonor** [comment]
At the end of the day - none of this is documented in the docs, which is the biggest problem IMO.

**Comment by clarkewd** [comment]
I also don't see this anywhere in the docs and I don't see a solution above so I don't know why the issue has been closed? 

Yes, the `homebrew` option may work on OSX but what about Windows (or Linux)?

Really love mitmproxy btw.

**Comment by mhils** [comment]
@clarkewd: This is documented nowadays at https://docs.mitmproxy.org/stable/overview-installation/#installation-from-the-python-package-index-pypi. :)

**Comment by charlbury** [comment]
Can I ask then, if I wanted to use the pandas library imported in a ```intercept.py``` script loaded into mitmproxy, I would 

```
pipx install mitmproxy
pipx inject mitmproxy pandas
```

I tried this but when running ```mitmproxy --scripts intercept.py``` it get the error

```
in script intercept.py: No module named 'pandas'
```

If I run a ```pipx list --include-injected```

I get the following

```
venvs are in /Users/sjg/.local/pipx/venvs
apps are exposed on your $PATH at /Users/sjg/.local/bin
manual pages are exposed at /Users/sjg/.local/share/man
   package mitmproxy 10.2.4, installed using Python 3.12.3
    - mitmdump
    - mitmproxy
    - mitmweb
    Injected Packages:
      - pandas 2.2.2 pipx list --include-injected
```

**Comment by mhils** [comment]
This looks correct. Are you absolutely sure that your `mitmproxy` points to the pipx-installed version, and not to some other one?
