### ISSUE TITLE
Where is HTTPRequest.from_stream?

### ISSUE THREAD

**Issue by alexsharoff** [mitmproxy/mitmproxy#2242]
I need a way to parse HTTPRequest from a stream (in-memory text chunk, actually). Google shows that such a method was available previously, but I can't find in mitmproxy v2.0.1. Was it removed? What should I use instead?

**Comment by mhils** [comment]
Hi,

Does `mitmproxy.net.http.http1.read_request` work for you?

**Comment by alexsharoff** [comment]
Seems like it may do the trick, thank you. I'll reply as soon as I test it tomorrow.

**Comment by alexsharoff** [comment]
My tests show that it doesn't read the body if Content-Length is not specified in the headers. Is there any way I can bypass this and force it to treat the remaining stream as the body?

**Comment by alexsharoff** [comment]
OK, I've found a solution to my problem.
I've copied and modified `mitmproxy.net.http.http1.read_request`:
```
def read_request_without_content_length(rfile, body_size_limit=None):
    request = read_request_head(rfile)
    expected_body_size = -1
    if "content-length" in request.headers:
        try:
            expected_body_size = int(request.headers["content-length"])
            if expected_body_size < 0:
                raise ValueError()
        except ValueError:
            raise exceptions.HttpSyntaxException("Unparseable Content Length")
    request.data.content = b"".join(read_body(rfile, expected_body_size, limit=body_size_limit))
    request.timestamp_end = time.time()
    return request
```
This behavior goes against RFC 7230 part 3.3.3., but that's what I need for my task. I'm writing an upload interceptor for Google Drive, btw.
