### ISSUE TITLE
Link to the right branch in the option documentation

### ISSUE THREAD

**Issue by kden** [mitmproxy/mitmproxy#2243]
##### Steps to reproduce the problem:

1. Desired outcome; to add a filter that executes at startup which is the equivalent of typing "f" and then "'!(~d "google" | ~d "gstatic")'" while running mitmproxy.  (These filter is helpful in Android debugging because the emulator makes some calls back to the Google mothership I don't care about.)
2. I decided to try to do this as part of a config file.  I was referred to the code at https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/options.py from the page at http://docs.mitmproxy.org/en/stable/config.html 
3. The closest option I found to "f" was view_filter, which is line 405 in the version of options.py that is current for me (https://github.com/mitmproxy/mitmproxy/blob/b19fefd173637ef20b72da3a0a05715db27c74be/mitmproxy/options.py)
4. I put the following in my ~/.mitmproxy/config.yaml
view_filter: '!(~d "google" | ~d "gstatic")'
5. Starting up mitmproxy gave the error
mitmproxy: Error reading /home/caden/.mitmproxy/config.yaml: 'No such option: view_filter'
I also tried "intercept" and that did not work.
6. On a whim I tried the following in ~/.mitmproxy/config.yaml
filter: '!(~d "google" | ~d "gstatic")'
This seemed to work!

##### Any other comments? What have you tried so far?

I'm not really sure what you will want to do with this information.  I would think probably change line 405 in options.py to say filter instead of view_filter.  But that's just a superficial suggestion.

##### System information

mitmproxy --version
Mitmproxy version: 2.0.1 (release version) 
Python version: 3.5.2
Platform: Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by mhils** [comment]
Thanks. The problem here is that the docs link to master, where we have just re-arranged some of the options. We should change the link to @cortesi's 
```
:src:`mitmproxy/builtins`
```
directive so that we always refer to the correct branch.
