### ISSUE TITLE
Not sure, but feels like Mitmproxy isn't clearing memory

### ISSUE THREAD

**Issue by Mradr** [mitmproxy/mitmproxy#2247]
##### Steps to reproduce the problem:

1. When editing my script, I will hit control + s to save my work. Mitmproxy (or dump) will reload the script this forces my script to load twice over (I have a save feature that will spit out that it is loading and saving). Checking memory, I see that the memory usage of Mitmproxy has double and the CPU usage has went up just a bit. Over time, if I continue to run Mitmproxy without closing it out and save/restarting it again, the memory will hit 80-100% causing the system to be unstable, slow, or full on freeze.

##### Any other comments? What have you tried so far?
Not sure what the problem is 100%, but I've seen this before with python garbage collection. Something not releasing access and so there for never gets garbage collected.

**Comment by mhils** [comment]
Thanks. Do you have a minimal script we can use to reproduce this?
