### ISSUE TITLE
Can’t use a custom certificate since python3

### ISSUE THREAD

**Issue by martin3991** [mitmproxy/mitmproxy#2254]
Hello.
I have problems with using a costum certificate since version 1.0.0 (python3).

##### Steps to reproduce the problem:

(I set up two virtual machines like described [here](http://docs.mitmproxy.org/en/stable/tutorials/transparent-dhcp.html).)
1. On VM1: Create a costum certificate like described in: ["Using a custom certificate"](http://docs.mitmproxy.org/en/stable/certinstall.html#using-a-custom-certificate)
2. On VM1: Start the mitmproxy (in transparent mode) with: mitmdump -T --cert _example.com_=cert.pem
3. On VM2: And on the other virtual machine i opened a browser with the url _example.com_ (e.g. google.com).

The given certificate was always the default certificate created with the ca certificate of the mitmproxy. Also I didn't get any error message from the mitmproxy. I tested it with Version 1.0.0, 1.0.2, 2.0.0, 2.0.1 .

When i do these steps with Version 0.18.2 (and python 2.7) everything works fine.

##### System information
- mitmproxy >=1.0.0
- Python 3.5.2
- Ubuntu 16.04.1 LTS
```
Mitmproxy version: 2.0.0 (release version) 
Python version: 3.5.2
Platform: Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
```

**Comment by mhils** [comment]
Thanks for the report! Does it work for you in non-transparent mode?

**Comment by gianricod** [comment]
Hello
I think i have a similar issue.

mitmweb.exe --cert C:\Users\test\.mitmproxy\mycert.pem

mycert.pem is correctly created  key/cert/ca

But still i get the certs issued by mitmproxy ca

c:\Program Files (x86)\mitmproxy\bin>mitmweb.exe --version
Mitmproxy version: 2.0.1 (release version) Precompiled Binary
Python version: 3.5.3
Platform: Windows-7-6.1.7601-SP1
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 7 6.1.7601 SP1 Multiprocessor Free

Any suggestions?

thanks
gianrico

**Comment by mhils** [comment]
@gianricod: is `mycert.pem` a certificate for a specific site or is it a CA?

**Comment by gianricod** [comment]
Hi

mycert.pem is for a specific site, not a CA.
i found that it works if  fqdn of site accessed is equals to the cert  CN  and not if  fqdn is different from the CN in the cert. In the latter case, the default mitmproxy CA is used.
Is that expected?

**Comment by martin3991** [comment]
@mhils 

1. Why throws the mitmproxy no warning if the given cert is no leaf cert?
2. Can you update the ["Using a custom certificate"](http://docs.mitmproxy.org/en/stable/certinstall.html#using-a-custom-certificate) document, so that it describes the usage of `--cert` of the actual version, please?

**Comment by mhils** [comment]
@gianricod Assuming you specify `--cert *=cert.pem`, cert.pem should always be used. can you confirm that this isn't the case?

> Why throws the mitmproxy no warning if the given cert is no leaf cert?

We probably should - I'm happy to accept a PR!

> Can you update the "Using a custom certificate" document, so that it describes the usage of --cert of the actual version, please?

I don't know what you mean by "usage of --cert of the actual version".

**Comment by martin3991** [comment]
@mhils 

> > Can you update the "Using a custom certificate" document, so that it describes the usage of --cert of the actual version, please?

> I don't know what you mean by "usage of --cert of the actual version".

I mean: Can you update the ["Using a custom certificate"](http://docs.mitmproxy.org/en/stable/certinstall.html#using-a-custom-certificate) document, that it contains the information, that only leaf certificates can be used with `--cert` , and a mini tutorial how to create a leaf certificate and use it with the mitmproxy? (Like its given there for the old versions, where you can use any certificate.)

**Comment by MGabr** [comment]
I'm having the same problem and a leaf certificate created with the commands

`openssl req -new -newkey rsa:2048 -out csr1.pem -keyout cert1.pem -nodes`

`openssl x509 -req -days 365 -CA ca3.pem -CAkey ca3.key -CAcreateserial -CAserial serial -in csr1.pem -out cert1.crt`

`cat cert1.crt >> cert1.pem`

does not work in the python 3 mitmproxy version, but works fine in the python 2 version (0.18.2).

**Comment by mhils** [comment]
@martin3991: 

> that only leaf certificates can be used with --cert

I made it more clear that only leaf certs can be used in https://github.com/mitmproxy/mitmproxy/commit/07cb83597b05b1355a6038d2b1ef96d7e7eb26d3. Thanks again for the feedback! :)

> and a mini tutorial how to create a leaf certificate

It already has that I believe? See "For example, you can generate a certificate in this format using these instructions:".

@MGabr: The steps listed at http://docs.mitmproxy.org/en/stable/certinstall.html#using-a-custom-certificate work for me. You may have issues in Chrome which recently stopped using the Common Name attribute (it requires a Subject Alternative Name), but mitmproxy properly uses the generated cert for me.

**Comment by gianricod** [comment]
>  Assuming you specify --cert *=cert.pem, cert.pem should always be used. can you confirm that this isn't the case?

@mhils  cert.pem seems to be used only when the site corresponding to the specific CN in cert is accessed. In other cases, the mitmproxy ca is used to generate a cert in the fly.

**Comment by mhils** [comment]
@gianricod: I cannot reproduce this with `mitmproxy --cert '*=cert.crt'`.

```
λ curl -x localhost:8080 -k -v https://example.org
* Rebuilt URL to: https://example.org/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Establish HTTP proxy tunnel to example.org:443
> CONNECT example.org:443 HTTP/1.1
> Host: example.org:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
<
* Proxy replied OK to CONNECT request
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: example.com (does not match 'example.org')
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=AU,ST=Some-State,O=Internet Widgits Pty Ltd,CN=example.com
*        start date: Sat, 29 Apr 2017 17:01:44 GMT
*        expire date: Mon, 29 May 2017 17:01:44 GMT
*        issuer: C=AU,ST=Some-State,O=Internet Widgits Pty Ltd,CN=example.com
*        compression: NULL
```

`mitmproxy --version`:
Mitmproxy version: 3.0.0 (2.0.0dev0343-0xbd88733)
Python version: 3.5.2
Platform: Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
