### ISSUE TITLE
Cannot load flows in mitmproxy

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2255]
##### Steps to reproduce the problem:

1. `mitmproxy` -> `L`

```
  File "/mnt/c/Users/user/git/mitmproxy/mitmproxy/tools/console/master.py", line 426, in load_flows_path
    master.Master.load_flows_file(self, path)
AttributeError: type object 'Master' has no attribute 'load_flows_file'
```

##### System information

Mitmproxy version: 3.0.0 (2.0.0dev0283-0x3d7cde0)
Python version: 3.5.2
Platform: Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by cortesi** [comment]
Fixed in master.
