### ISSUE TITLE
Cannot modify HTTP/2 responses

### ISSUE THREAD

**Issue by NuSkooler** [mitmproxy/mitmproxy#2260]
##### Steps to reproduce the problem:
Perhaps I'm missing something here, but I cannot seem to modify HTTP/2 responses. HTTP/1.1 works fine. The following script breaks when the browser attempts to use HTTP/2:

```
def response(flow):
	flow.response.headers['X-Filtered'] = 'true'
```
Invoked with `mitmproxy -T --host -s script.py`.

##### Any other comments? What have you tried so far?
If I additionally add `--no-http2`, the script works correctly. If the browser does not use HTTP/2, everything also works as expected.

##### System information
```
Mitmproxy version: 2.0.1 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.7
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian 8.7 
```

**Comment by mhils** [comment]
Can you be more specific regarding "breaks"? Does it work if you specify the header name as lowercase?

**Comment by NuSkooler** [comment]
@mhils Apologies, I know better than that. By "breaks", I mean the browser (I was using FF at the time) does not receive a response. 

I'm not at my desk right now, but tonight I'll try all lowercase headers and attempt to catch this with `curl -v ...` as well as any `mitmproxy` logs/errors that are output.

**Comment by NuSkooler** [comment]
@mhils It appears the only required fix is as you suggested: lowercase header names. Even when inventing new headers. I'm not sure if this is expected/desired, so I'll leave this open for your discretion.

Thanks!

**Comment by mhils** [comment]
@Kriechi: What's the state on master here? It sounds like it might be useful to perform lowercase-normalization by default, but maybe emit a log statement if we do so.

**Comment by Kriechi** [comment]
This should be fixed already in git-master: https://github.com/mitmproxy/mitmproxy/pull/2055/files
