### ISSUE TITLE
Upgrade to Python 3.6+

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2266]
This issue tracks all roadblocks we need to overcome to make use of Python 3.6-exclusive features. There's not immediate need to upgrade right away, but it's useful to have an overview of what's left nonetheless.

### Windows

✔️ Windows users can just install Python 3.6
✔️ Windows Subsystem for Linux currently contains Ubuntu 16.04, but a `do-release-upgrade` can be used without problems

### macOS

❌  High Sierra only has Python 2.7.10 and no Python 3
✔️ Homebrew is already on Python 3.6.3

### Ubuntu

✔️ Bionic 18.04 (next LTS release in April 2018) will have Python 3.6.3 (or a more recent patch-level)
✔️ Artful 17.10 has Python 3.6.3
❌ Zesty 17.04 has Python 3.5.3
❌ Ubuntu 16.04 LTS is still on 3.5.1

### Debian

✔️ testing: Debian 10 (buster) currently contains Python 3.6.3 -- no release date yet
❌ stable: Debian 9 (stretch) is still on 3.5.3

### Arch Linux

✔️ rolling release: has Python 3.6.3 as `python` package

### Fedora

✔️ Fedora 27 has Python 3.6.3
✔️ Fedora 26 has Python 3.6.3
❌ Fedora 25 has Python 3.5.4

### Kali Linux

✔️ kali-roll has Python 3.6.3 -- rolling release since January 2016
✔️ kali-dev has Python 3.6.3

### PyInstaller

- PyInstaller supports Python 3.6 since PyInstaller 3.3. We still have to upgrade to PyInstaller 3.3. Updating to PyInstaller 3.3.0 ends with a RecursionError within PyInstaller.

**Comment by Kriechi** [comment]
Just to get a complete picture, what are py36-exclusive feature we could benefit from?

**Comment by mhils** [comment]
I think the most useful one is [syntax for variable annotations](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526), which would be very nice for e.g. stateobject and generally type annotations in the codebase. Second, the [formatted string literals](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498) are considerably nicer than `"" % ()` or `"".format()`. So no immediate needs, but generally I think those things are useful. 
Depending on what we do for the proxy core, we _may_ also want async generators, although I really have not looked into this that much.

**Comment by mhils** [comment]
What I'm noticing just now: https://docs.python.org/3/whatsnew/3.6.html#pep-487-simpler-customization-of-class-creation might be a good fit for our addon system.

**Comment by cortesi** [comment]
There are other benefits - our type checking system has a bunch of 3.5 exceptions that could go away. Less tangibly, I often see transient errors in CI tests for 3.5, where 3.6 works consistently.
