### ISSUE TITLE
mitmweb 2.0.1 not working under Chrome 58

### ISSUE THREAD

**Issue by alexandrul** [mitmproxy/mitmproxy#2284]
##### Steps to reproduce the problem:

1. start mitmweb
2. open the mitmweb web page in Chrome 58
3. no visible content

##### Any other comments? What have you tried so far?
It's working fine under Chrome 57.0.2987.133 and Firefox
I was able to show the interface by playing with the answers from http://stackoverflow.com/questions/31211359/ (added the meta tag from http://stackoverflow.com/a/35273628/19756 to the `index.html` template), but I still have some warnings in the console:

> WARNING:tornado.access:404 GET /static/vendor.js.map (10.162.60.254) 0.00ms
WARNING:tornado.access:404 GET /static/app.js.map (10.162.60.254) 0.00ms
WARNING:tornado.access:404 GET /static/vendor.css.map (10.162.60.254) 1.00ms
WARNING:tornado.access:404 GET /static/app.css.map (10.162.60.254) 1.00ms

##### System information
Chrome 58.0.3029.81 (64-bit)

> mitmweb --version
Mitmproxy version: 2.0.1 (release version)
Python version: 3.5.2
Platform: Windows-8.1-6.3.9600-SP0
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Windows version: 8.1 6.3.9600 SP0 Multiprocessor Free

**Comment by mhils** [comment]
Thanks, looks like we need to ship a patch release for this ASAP. I'm getting the following error in Chrome 58:
```
Refused to connect to 'ws://localhost:8081/updates' because it violates the following Content Security Policy directive: "connect-src 'self' ws://* ".
```

**Comment by mhils** [comment]
Adding `"ws:"` as `connect-src` fixes the issue. I believe this is a Chrome bug though, `ws://*` should be valid if I interpret the spec correctly.

**Comment by mhils** [comment]
Ok, I checked and Chrome does follow the spec: `ws://*` does not specify a port, so it actually expands the expression to the default port (`ws://*:80`), which does not match our `ws://localhost:8081/`. The short-term workaround is to run mitmweb on port 80 (`--wport`). We'll push a patch release nonetheless.

**Comment by mhils** [comment]
[2.0.2](https://github.com/mitmproxy/mitmproxy/releases/tag/v2.0.2) is out which fixes this, thanks again for the report!

**Comment by alexandrul** [comment]
Thank you very much for your quick fix.

**Comment by spwert** [comment]
I'm still getting this issue on version 2.0.2, using Chrome Version 58.0.3029.110 (64-bit).

My console output when I try to open the mitmweb UI:

> (unknown) Refused to connect to 'ws://localhost:14549/updates' because it violates the following Content Security Policy directive: "connect-src 'self' ws://* ".
> 
> WrappedWebSocket
> (unknown) Uncaught DOMException: Failed to construct 'WebSocket': Refused to connect to 'ws://localhost:14549/updates' because it violates the document's Content Security Policy.
>     at WrappedWebSocket (<anonymous>:35:21)
>     at WebsocketBackend.connect (http://localhost:14549/static/app.js:223:27)
>     at new WebsocketBackend (http://localhost:14549/static/app.js:215:14)
>     at Object.<anonymous> (http://localhost:14549/static/app.js:171:18)
>     at Object.2../backends/websocket (http://localhost:14549/static/app.js:185:4)
>     at s (http://localhost:14549/static/app.js:1:254)
>     at e (http://localhost:14549/static/app.js:1:425)
>     at http://localhost:14549/static/app.js:1:443

My mitmweb --version output:

> Mitmproxy version: 2.0.2 (release version) Precompiled Binary
> Python version: 3.5.3
> Platform: Windows-10-10.0.10586
> SSL version: OpenSSL 1.0.2j  26 Sep 2016
> Windows version: 10 10.0.10586  Multiprocessor Free

**Comment by mhils** [comment]
Can you (1) double-check that you don't have an old instance running in the background and can you (2) do a full forced page reload (Ctrl-Shift-R in Chrome)?

**Comment by spwert** [comment]
Forced page reload did the trick, thanks!
