### ISSUE TITLE
mitmproxy assumes klipper is running

### ISSUE THREAD

**Issue by ilpianista** [mitmproxy/mitmproxy#2292]
##### Steps to reproduce the problem:

1. Under KDE Plasma 5, perform any request
2. use C to copy flow to clipboard
3. I got this error: `Export to clipboard (content,headers+content,url,as curl command,as python code,as locust code,as locust task)? Cannot find '.setClipboardContents' in object /klipper at org.kde.klipper`

##### System information

Mitmproxy version: 2.0.1 (release version)
Python version: 3.6.1
Platform: Linux-4.10.13-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: arch

Since KDE Plasma 5, klipper is not used by default. Instead the clipboard widget is used which unfortunately doesn't expose a DBus interface. Of course I can manually start klipper to get it working, but who's assuming klipper is running on my system?

**Comment by mhils** [comment]
We just use [pyperclip](https://github.com/asweigart/pyperclip) internally, so this is not a bug in mitmproxy. Can you please file a bug upstream?

Thanks!
Max

**Comment by ilpianista** [comment]
Ah thanks, I found asweigart/pyperclip#26
