### ISSUE TITLE
Cannot kill flows

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2298]
##### Steps to reproduce the problem:

1. Open mitmproxy
2. Press "X" on a flow.
3. Nothing happens.

##### System information

Mitmproxy version: 3.0.0 (2.0.0dev0345-0x97a0072)
Python version: 3.5.2
Platform: Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

**Comment by cortesi** [comment]
Fixed in master. Tested by intercepting a flow, pressing X, observing that it is killed.
