### ISSUE TITLE
Feature request: Python api to pull details of server side ssl certificate

### ISSUE THREAD

**Issue by securisec** [mitmproxy/mitmproxy#2314]
This is not an issue but a feature request. I love how mitmproxy has the detail page that breaks down the ssl/tls certificate, and would love to see a python api that i can leverage to get parts of this data. I tried leveraging ssl lib, but the performance just isnt the same as mitmproxy.

Thanks!

**Comment by mhils** [comment]
Are you perhaps looking for a script like this?
```python
def serverdisconnect(sc):
	print(sc.cert)
```

**Comment by securisec** [comment]
maybe... but maybe not quite... here is a screenshot of the details that i am trying to script as part of my mitmproxy script... thanks for the help @mhils ! 

![image](https://cloud.githubusercontent.com/assets/22226823/25755738/1cd72f3a-3192-11e7-85dd-83cd155a6c9e.png)

**Comment by mhils** [comment]
This should help: https://github.com/mitmproxy/mitmproxy/blob/fdec51d732d23edbea1833a445820603d177f5e6/mitmproxy/tools/console/flowdetailview.py#L46-L90

**Comment by securisec** [comment]
That is perfect! Thanks! keep doing the awesome work that you guys are doing!
