### ISSUE TITLE
SSL Socket option needed

### ISSUE THREAD

**Issue by Supermilkycow** [mitmproxy/mitmproxy#2317]
I was trying to intercept the flow between a client and server using HTTP protocol. Everything was good before client set up another SSL-socket without HTTP header to the server.
Mitmproxy hints: "HTTP protocol error in client request: Bad HTTP request"
Client sent JSON-like data could be decoded by mitmdump like:" { "request":"John" , "name":"foo" }".
Then mitmproxy closed the connection.

So, is there any way to get an option to disable HTTP protocol parser and just forward these socket packets?

**Comment by mhils** [comment]
This should work for you: http://docs.mitmproxy.org/en/stable/features/tcpproxy.html

**Comment by Supermilkycow** [comment]
Thanks!  It works. 
Although I noticed that interception and modification are not available, I still appreciate your decent work. 
I will temporarily make some dirty patches to modify these traffic.

Do you have plans to implement the TCP data inline script hook in the future?

**Comment by mhils** [comment]
You can modify TCP messages in scripts: https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/tcp_message.py
It's very difficult to get right considering TCP fragmentation etc., but should be good enough locally.
