### ISSUE TITLE
"No internet connection" in Android app with using mitmproxy, but works fine with Charles

### ISSUE THREAD

**Issue by mortenmoulder** [mitmproxy/mitmproxy#2318]
##### Steps to reproduce the problem:

**mitmproxy**
1. Install the mitmproxy certificate through http://mitm.it/
2. Start mitmproxy with `mitmproxy -p 8080`
3. Set proxy settings on Android Marshmallow or Nougat
4. Open the application
5. Get prompted with the error

**Charles**
1. Install the Charles proxy certificate through http://chls.pro/ssl
2. Start Charles
3. Set proxy settings on Android Marshmallow or Nougat
4. Open the application
5. See traffic in Charles

##### Any other comments?

I cannot see any traffic from the application in mitmproxy what so ever. Nothing. Could this be because the application blocks the mitmproxy certificate somehow?

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.1
Platform: Darwin-15.0.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.11.1 ('', '', '') x86_64

Also installed and tried on an Ubuntu server.

**Comment by mortenmoulder** [comment]
We discovered something:

Grabbing the URL through Charles then visiting them with a browser works fine. Whenever we turn on mitmproxy again, it will timeout the request and not even show the request in the mitmproxy GUI.

**Comment by mhils** [comment]
Thanks. Which app(s), which device(s), which URL(s)? 😉

**Comment by mhils** [comment]
> Whenever we turn on mitmproxy again, it will timeout the request and not even show the request in the mitmproxy GUI.

This very much sounds like a general misconfiguration.

**Comment by mortenmoulder** [comment]
Which app and URL is not something I can disclose in public unfortunately. Message me on Slack and I'll send the URLs (same username as on github).

Galaxy S7 Edge and OnePlus One devices has been tested 😄

**Comment by mhils** [comment]
Does this problem only affect a single app, or is this a general issue with these devices? Does it affect HTTP, or does it affect HTTPS?

**Comment by mortenmoulder** [comment]
Problem was solved by creating a custom certificate, installing it on the phone, and then giving that certificate to mitmproxy as well. Weird.

**Comment by mirdoraghi** [comment]
@mortenmoulder 
I have the same issue.
How can i create a custom certificate and install it on mitmproxy ?

**Comment by sibelius** [comment]
how to solve this?

**Comment by kwhat** [comment]
This is definitely still a bug.

**Comment by kwhat** [comment]
Guess the solution is use http://chls.pro/ssl and not https://github.com/mitmproxy/mitmproxy 👍

**Comment by scramblr** [comment]
> Problem was solved by creating a custom certificate, installing it on the phone, and then giving that certificate to mitmproxy as well. Weird.

While I appreciate the answer and insight (really, thanks!) - this isn't a reasonable fix for mitmproxy. There's something broken in the cert creation mechanism, so why not fix the issue? This should remain open, as the issue is still present and unsolved.

**Comment by ioio101** [comment]
Funny how it's still not resolved

**Comment by scramblr** [comment]
It's a huge problem for Android testers and forced me to move away from mitmproxy for now.

**Comment by ioio101** [comment]
> It's a huge problem for Android testers and forced me to move away from mitmproxy for now.

I've tested on Charles and Burpsuite, both were working flawlessly. Hope they can fix this soon because I enjoy the lightweight functionality of it.

**Comment by ShayBox** [comment]
Still nothing?

**Comment by M25A** [comment]
@ShayBox @ioio101 @scramblr @kwhat @sibelius I am facing the same problem while having proxy settings done in Android 4.4.2 device alongwith the CA Certificate for MITM. Unable to intercept android apps traffic. 
Please someone guide.

P.S I dont want to use Burpsuite

**Comment by gustavorps** [comment]
> Problem was solved by creating a custom certificate, installing it on the phone, and then giving that certificate to mitmproxy as well. Weird.

Was not solved for me creating a custom certificate. 
I follow these instructions: 
- https://stackoverflow.com/a/41366949
- https://www.suse.com/support/kb/doc/?id=000018152

**Comment by 0neel** [comment]
So I had a similar issue but it was my fault - I installed the certificate as "Wi-fi certificate" when it supposed to be "CA certificate".

<img width="200" src="https://user-images.githubusercontent.com/3177746/111801507-1583ab80-88de-11eb-841c-a95729b96b8b.png"/>

**Comment by shahid-0** [comment]
> So I had a similar issue but it was my fault - I installed the certificate as "Wi-fi certificate" when it supposed to be "CA certificate".
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/3177746/111801507-1583ab80-88de-11eb-841c-a95729b96b8b.png">

I installed it on the CA certificate but still, the issue arises, it shows me no internet but running the browser and doesn't show any request and don't run any online app.

**Comment by kamilrychta** [comment]
On one of the app that we testing starting a mitmproxy server  with '--no-http2' flag did the work.
On a different app with same configuration app returns an error 'no internet connection'.

This issue never occurs with Charles proxy.

**Comment by konkhra** [comment]
As of 2025 the problem still exist in mitmproxy.

I am using Samsung S25 latest android version on Wi-Fi connection, certificate installed in CA certificate. Navigating the internet through any phone's browser I can see traffic in mitmproxy. When opening any android app it's like there's no internet on the phone.

**Comment by ruben2s** [comment]
Same here. Samsung s25. installed in CA. browser works Ok but it still says that there is no connection on the device, and apps do not work.
