### ISSUE TITLE
HttpException('Invalid HTTP request form (expected: authority or absolute, got: relative)',) and missing options.

### ISSUE THREAD

**Issue by farmdve** [mitmproxy/mitmproxy#2321]
As with my previous issue, I have the following setup: 

I have a dns proxy server and mitmproxy sitting on one machine. The device(whose traffic is to be captured)'s DNS server is set to my own DNS server. There I spoof all domains I would like to point to the machine I have setup.

However, I get the following error `HttpException('Invalid HTTP request form (expected: authority or absolute, got: relative)',). 

If I use the -R command line options, which sets up a reverse proxy, e.g proxying to an upstream server, everything works, but this doesn't work for multiple domains.

I am using the dns spoofing script, but it seems like it still doesn't work, I have noticed that modern browsers send the Host header with the domain name(or at least Chrome does), so mitmproxy can absolutely use the Host header to construct the proper requested resource, but it doesn't.

And the `--keep-host-header` argument as described in https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/dns_spoofing.py is completely non-existant.
I am using the latest code, version 3.0.0 according to `mitmproxy --version`.

Any idea what can be done here?

**Comment by mhils** [comment]
> And the --keep-host-header argument as described in https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/dns_spoofing.py is completely non-existant.

I think that is not true for the latest 2.0.x public release 😉 We're changing how options work on master right now, other than that things should work. `--set keep_host_header` should do it on master.

**Comment by DanDevine** [comment]
I'm using 2.0.2 (release version), and getting the following:
$mitmproxy --set keep_host_header -s settings.py
mitmproxy: Invalid replacement specifier: keep_host_header

Can't see the internal Flask app, so my mobile app can't adjust any settings.
