### ISSUE TITLE
Is it possible to rebind the text selection key?

### ISSUE THREAD

**Issue by BetaStrike** [mitmproxy/mitmproxy#2326]
##### Steps to reproduce the problem:

1. Try to select parts of the text in mitmproxy on a mac with a windows keyboard
2. Find out the selection override key is Fn
3. Key does not exist on keyboard but is on laptop keyboard

##### Any other comments? What have you tried so far?

At the time I am kind of just reaching over to the mac itself to hit the fn key, with 10.12 I can't even use karabiner to do some rebind action as it is broken with the new version of osx. So it would be great if I can use a cmd option / config file to make mitmproxy to react to a different key for text selection

##### System information
mackbook pro mid 2014, osx 10.12.4
windows keyboard, with control and command swapped in OS if that changes anything.

**Comment by Kriechi** [comment]
You can disable mouse support, which should at least give you back normal text selection.
But the Fn key is not used by mitmproxy, but comes directly from your Terminal.app (or are you using iTerm2?).

I'm using iTerm2 and can select text by holding down the Alt key. Unfortunately I can't remember where or what I configured in iTerm2.

**Comment by BetaStrike** [comment]
cool thanks, iterm2 did it thanks!
