### ISSUE TITLE
Some sites like facebook.com not working after login

### ISSUE THREAD

**Issue by aniljava** [mitmproxy/mitmproxy#2330]
##### Summary:

Site such as facebook.com does not work after login. ERR_CONNECTION_CLOSED error is shown in chrome. Further details below. Need pointers to debug further.

Problem exists on pip version as well as the latest github trunk.

    Mitmproxy version: 3.0.0 (2.0.0dev0435-0x1c6b33f5) 
    Python version: 3.5.3
    Platform: Linux-4.10.0-20-generic-x86_64-with-Ubuntu-17.04-zesty
    SSL version: OpenSSL 1.0.2g  1 Mar 2016
    Linux distro: Ubuntu 17.04 zesty

##### Steps to reproduce the problem:
Started the proxy as: 

    . venv/bin/activate
    mitmdump 2>&1 > logs.txt

`~/.mitmproxy/config.yaml` is created by copying output of `mitmdump --options` 
change made was `verbosity: 4`

Started chrome with following args:

     --proxy-server=127.0.0.1:8080

Example problem:
1. Visit facebook.com [ok]
2. Login [ok]
3. ERR_CONNECTION_CLOSED [Details 

##### Relevant details from logs.txt

    Proxy server listening at http://127.0.0.1:8080
    127.0.0.1:50786: clientconnect
    127.0.0.1:50788: clientconnect
    127.0.0.1:50788: Set new server address: www.facebook.com:443
    127.0.0.1:50788: serverconnect
      -> ('www.facebook.com', 443)
    127.0.0.1:50788: Establish TLS with server
    127.0.0.1:50788: ALPN selected by server: h2
    127.0.0.1:50788: Establish TLS with client
    127.0.0.1:50788: ALPN for client: b'h2'
    127.0.0.1:50788: HTTP2 Event from client
      -> <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.HEADER_TABLE_SIZE, original_value=4096, new_value=65536), ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=1000), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=6291456)}>
    127.0.0.1:50788: HTTP2 Event from server
      -> <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.HEADER_TABLE_SIZE, original_value=4096, new_value=4096), ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=100), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=65536), ChangedSetting(setting=SettingCodes.MAX_FRAME_SIZE, original_value=16384, new_value=16384), ChangedSetting(setting=SettingCodes.MAX_HEADER_LIST_SIZE, original_value=None, new_value=131072)}>
    127.0.0.1:50788: HTTP2 Event from server
      -> <WindowUpdated stream_id:0, delta:10420225>
    127.0.0.1:50788: HTTP2 Event from client
      -> <WindowUpdated stream_id:0, delta:15663105>
    127.0.0.1:50788: HTTP2 Event from client
      -> <RequestReceived stream_id:1, headers:[(b':method', b'GET'), (b':authority', b'www.facebook.com'), (b':scheme', b'https'), (b':path', b'/'), (b'cache-control', b'max-age=0'), (b'upgrade-insecure-requests', b'1'), (b'user-agent', b'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36'), (b'accept', b'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'), (b'dnt', b'1'), (b'accept-encoding', b'gzip, deflate, sdch, br'), (b'accept-language', b'en-US,en;q=0.8'), (b'cookie', b'datr=__REMOVED_FOR_PRIVACY__; dats=1; sb=__REMOVED_FOR_PRIVACY__; c_user=__REMOVED_FOR_PRIVACY__; xs=__REMOVED_FOR_PRIVACY__; fr=__REMOVED_FOR_PRIVACY__; pl=n; lu=__REMOVED_FOR_PRIVACY__; dpr=1.5')]>
    127.0.0.1:50788: HTTP2 Event from client
      -> <StreamEnded stream_id:1>
    127.0.0.1:50788: HTTP2 Event from client
      -> <PriorityUpdated stream_id:1, weight:256, depends_on:0, exclusive:True>
    127.0.0.1:50788: HTTP/2 PRIORITY frame surpressed. Use --http2-priority to enable forwarding.
    127.0.0.1:50788: HTTP2 Event from client
      -> <SettingsAcknowledged changed_settings:{ChangedSetting(setting=SettingCodes.HEADER_TABLE_SIZE, original_value=4096, new_value=4096), ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=100, new_value=100), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=65536), ChangedSetting(setting=SettingCodes.MAX_FRAME_SIZE, original_value=16384, new_value=16384), ChangedSetting(setting=SettingCodes.MAX_HEADER_LIST_SIZE, original_value=65536, new_value=131072)}>
    127.0.0.1:50788: request
      -> Request(GET www.facebook.com:443/)
    127.0.0.1:50788: HTTP/2 PRIORITY information in HEADERS frame surpressed. Use --http2-priority to enable forwarding.
    127.0.0.1:50788: HTTP2 Event from server
      -> <SettingsAcknowledged changed_settings:{ChangedSetting(setting=SettingCodes.HEADER_TABLE_SIZE, original_value=4096, new_value=65536), ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=100, new_value=1000), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=6291456)}>
    127.0.0.1:50788: HTTP2 Event from client
      -> <SettingsAcknowledged changed_settings:{}>
    127.0.0.1:50788: HTTP2 Event from server
      -> <SettingsAcknowledged changed_settings:{}>
    127.0.0.1:50788: HTTP2 Event from server
      -> <WindowUpdated stream_id:1, delta:10420224>
    127.0.0.1:50788: NoSuchStreamError(2,)
    127.0.0.1:50788: serverdisconnect
      -> ('www.facebook.com', 443)
    127.0.0.1:50788: clientdisconnect

**Comment by aniljava** [comment]
No such issue with Firefox, only chrome.

**Comment by Kriechi** [comment]
Does this also happen when you use `--http2-priority`?
You can circumvent this by using `--no-http2` to disable it.

I guess this is another weird edge case in the HTTP/2 implementation. 
Possible ours, but we found bugs in major services as well in the past...

**Comment by aniljava** [comment]
Problem goes away when using `http2: false` in `config.yaml`
Same with twitter as well.

**Comment by mhils** [comment]
Works for me on master.
