### ISSUE TITLE
mitmproxy dosen't see android connections on transparent mode

### ISSUE THREAD

**Issue by rafalbednarczuk** [mitmproxy/mitmproxy#2339]
##### Steps to reproduce the problem:

1. Install mitmproxy
2. Edit rt_tables: 
```
#
# reserved values
#
255	local
254	main
253	default
0	unspec
#
# local
#
#1	inr.ruhep
100	mitmproxy
```
3. Setup config for transparent proxy
```
rafal@rafalPL:~$ CLIENT_NET=192.168.0.103 /// My machine IP
rafal@rafalPL:~$ TABLE_ID=100
rafal@rafalPL:~$ MARK=1
rafal@rafalPL:~$ sudo iptables -t mangle -A PREROUTING -d $CLIENT_NET -j MARK --set-mark $MARK
rafal@rafalPL:~$ sudo iptables -t nat -A PREROUTING -p tcp -s $CLIENT_NET --match multiport --dports 80,443 -j REDIRECT --to-port 8080
rafal@rafalPL:~$ sudo ip rule add fwmark $MARK lookup $TABLE_ID
rafal@rafalPL:~$ sudo ip route add local $CLIENT_NET dev lo table $TABLE_ID

```
4. Compile full_transparency_shim.c
5. Run mitmproxy_shim
```
rafal@rafalPL:~/mitmproxy-master$ sudo chown root:root mitmproxy_shim
rafal@rafalPL:~/mitmproxy-master$ sudo chmod u+s mitmproxy_shim
rafal@rafalPL:~/mitmproxy-master$ ./mitmproxy_shim /usr/local/bin/mitmproxy -T
```
5. Open event log
6. Connect android device to gateway through wifi:
Proxy Server: **NO**
Static IP
IPAdress: 192.168.1.128
Gateway: 192.168.0.103 //My PC's IP
24
DNS1: 8.8.8.8
DNS2: 8.8.4.4
7. Open browser on android device
No internet conncetion
No event logs on mitmproxy

##### Any other comments? What have you tried so far?

Regular mode works well.

Connect through proxy instead of gateway on android device with mitmproxy transparent mode:
```

192.168.0.100:39826: clientconnect
192.168.0.100:39826: HTTP protocol error in client request: Mitmproxy received
an absolute-form request even though it is not running in regular mode. This
usually indicates a misconfiguration, please see
http://docs.mitmproxy.org/en/stable/modes.html for details.
192.168.0.100:39826: clientdisconnect
```

Changed CLIENT_NET to CLIENT_NET=192.168.0.103/**24** results in: 
```
rafal@rafalPL:~$ sudo ip route add local $CLIENT_NET dev lo table $TABLE_ID
RTNETLINK answers: Invalid argument

```

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.2
Platform: Linux-4.8.0-52-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

Android Device: 
Nexus 5 android 7.1.1
LineageOS:
14.1-20170219-UNOFFICIAL-hammerheadcaf
3.4.0-lineageos-g27406e90457510ga6c86d1
experience7@lineageos #1

**Comment by Ritiek** [comment]
@rafalbednarczuk why did you close this?

**Comment by rafalbednarczuk** [comment]
@Ritiek 
I moved it here: 
https://discourse.mitmproxy.org/t/mitmproxy-dosent-see-android-connections-on-transparent-mode/486
since it was my misconfiguration and not an issue
