### ISSUE TITLE
Unable to get mitmproxy working on Sierra

### ISSUE THREAD

**Issue by prastut** [mitmproxy/mitmproxy#2341]
##### Problem:

I have been trying to get mitmproxy to work on my macOS sierra and unable to do so. 

##### What have you tried so far?

* Installed using Hombrew: `brew install mitmproxy`.
* By running `mitmproxy` on the terminal it starts the application. 
* As the docs suggest, I now have to install certificates:
  * Went to `mitm.it`. It shows: `If you can see this, traffic is not passing through mitmproxy.`
  * Googled if somebody else has this issue and followed the manual setup. 
* Removed `~./mitmproxy` folder for a clean run. Restarted `mitmproxy`. The new cert's are created. 
* Copied the entire folder `~./mitmproxy` to the Keychain Access. For files with password entered nothing and continued. In the end Keychain Access gives me the results: 
  ```
  An error has occurred. Unable to import an item. 
  The contents of this item cannot be retrieved.
  ```
* Still I see an entry for `mitmproxy` certs in Keychain access with the following error with it: 

  ```
   This root certificate is not trusted
  ```
* Double clicking on the certificate -> Trust -> When using the certificate. Changed from `Use System defaults` to `Always trust`. The above error of not getting trusted get's removed. 
* Restarted `mitmproxy`. No logs if I go to some website. `mitm.it` shows the same error. 
* Restarted Mac for reloading certs, that also didn't solve the problem. 

##### System information
Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.1
Platform: Darwin-16.5.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.4 ('', '', '') x86_64

#### Thoughts
Read the documentation again more closely in case that I might have missed something. In the [Quick Setup](http://docs.mitmproxy.org/en/latest/certinstall.html#quick-setup) it's mentioned 

```
start mitmproxy and configure your target device with the correct proxy settings.
````

How does one configure my device with correct proxy settings?

**Comment by prastut** [comment]
Followup:

I found this article: 
https://medium.com/@maxgreenwald/mitmproxy-your-d-i-y-private-eye-864c08f84736

And according to the article's suggestions configured Chrome's proxy to port 8080. Now I am able to see the traffic in `mitmproxy` logs. Though if I still go to `mitm.it` I get the same error of traffic not passing through mitmproxy.

**Comment by Kriechi** [comment]
You have to change you browser's proxy settings.
Enable the HTTP proxy, and set it to `localhost` with port `8080`.

Also, I think you have to make sure that there is no "Bypass proxy for these hosts" setting for `localhost` or `127.0.0.1`.

**Comment by mhils** [comment]
Thanks for the detailed report. While it's easy to classify this as a layer 8 error, I think we should ultimately have better docs for this. Or - as Charles and Fiddler do it (I think) - capture the local machine by default.

refs https://github.com/mitmproxy/mitmproxy.org/issues/20

**Comment by mhils** [comment]
I'm closing this anyway, as there's nothing immediately actionable for us in here. We'll handle this in the issue linked above though, thanks again for the report!

**Comment by Graystripe17** [comment]
Another answer: I forgot to turn off my adblock VPN :/
