### ISSUE TITLE
Sniff all my own computer traffic

### ISSUE THREAD

**Issue by john-bonachon** [mitmproxy/mitmproxy#2343]
What should I do to sniff my **own** computer traffic?
i.e. it's easy to setup Chrome proxy to use mitmproxy localhost:port, but what if I need to sniff all traffic happening on my computer? 
Should I set my wifi gateway to my own address and put mitmproxy in transparent mode?

**Comment by javabrett** [comment]
Have you read about [transparent 
Proxying]( http://docs.mitmproxy.org/en/stable/transparent.html)?

Also https://discourse.mitmproxy.org is a good place for Q&A.

**Comment by mhils** [comment]
@javabrett linked to the right places - thanks for that!

refs #630

**Comment by john-bonachon** [comment]
It's not clear... I'm still confused about setting mitmproxy as gateway on the same machine.
I used to add these rules to iptables,

```
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080
```

but setting **other**'s device gateway to the ip machine mitmproxy is running.

Is there any other place I can read about this particular scenario?

**Comment by dorian821** [comment]
@john-bonachon, if still relevant, [this](https://stackoverflow.com/questions/44032210/route-outcoming-traffic-to-mitmdump) question might be able to help you.
