### ISSUE TITLE
Config file Error no such option "view_filter" 

### ISSUE THREAD

**Issue by shaynewang** [mitmproxy/mitmproxy#2344]
##### Steps to reproduce the problem:

1. Add a ```config.yaml``` file include ```view_filter: google```
2. run mitmproxy
3. got error ```mitmproxy: Error reading /Users/Shayne/.mitmproxy/config.yaml: 'No such option: view_filter'```

##### Any other comments? What have you tried so far?
The option is in the source I don't know why it's not in the latest release

##### System information

     .mitmproxy mitmproxy --version
    Mitmproxy version: 2.0.2 (release version)
    Python version: 3.6.1
    Platform: Darwin-16.5.0-x86_64-i386-64bit
    SSL version: OpenSSL 1.1.0e  16 Feb 2017
    Mac version: 10.12.4 ('', '', '') x86_64

**Comment by mhils** [comment]
`view_filter` exists on master, but not yet on 2.x. This will solve itself with the next release, apologies.
