### ISSUE TITLE
Private key is present in mitmproxy-ca-cert.p12

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#2349]
##### Steps to reproduce the problem:

Private key is inserted in .p12 file, although filename says "mitmproxy-ca-**cert**.p12"
Output can be verified with:
openssl pkcs12 -in mitmproxy-ca-cert.p12 -nocerts -nodes

I don't have a Windows machine to test if a .p12 file would work without the private key inside.
We can generate a .p12 file without key with:
openssl pkcs12 -export -nokeys -in mitmproxy-ca-cert.pem -out mitmproxy-ca-cert.p12

-> If private key is needed, file could be renamed "mitmproxy-ca.p12" for better understanding
-> If private key is not needed, .p12 generation should be modified

##### System information

Mitmproxy version: 2.0.1 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Darwin-16.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Mac version: 10.12.5 ('', '', '') x86_64

**Comment by mhils** [comment]
Thanks for the useful report. I just tested this and found that the private key is not needed. Fixing this in [certs.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/certs.py) should be quite easy, so I'll leave this open for new contributors! :)
