### ISSUE TITLE
can't work on iPhone 6S (through Macbook)

### ISSUE THREAD

**Issue by sgbookexchange** [mitmproxy/mitmproxy#2352]
##### Steps to reproduce the problem:

install mitmproxy through brew and then configure iPhone as per guide on [http://jasdev.me/intercepting-ios-traffic](http://jasdev.me/intercepting-ios-traffic). Try to install CA on iPhone 6S but can't connect to mitm.it (connection time out error) properly. Then install CA on Macbook (setting the proxy to 127.0.0.1:8080) and it works. Need some suggestion. Thanks.

##### System information
iOS version 10.3.1
Chrome on iOS 58.0.3029.113

Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.1
Platform: Darwin-16.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.5 ('', '', '') x86_64

**Comment by wimbledon** [comment]
Having the same issue here with same configuration for iPhone 7.

System information

iOS version 10.3.1
Chrome on iOS 58.0.3029.113

Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.1
Platform: Darwin-16.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e 16 Feb 2017
Mac version: 10.12.5 ('', '', '') x86_64

**Comment by mhils** [comment]
Do plain HTTP websites work for you? Do you see anything in mitmproxy's event log?

**Comment by wimbledon** [comment]
mitm.it link does work for me. The plain http website works too. Also, I do see mitmproxy's event logs in these cases.

**Comment by mhils** [comment]
"can't connect to mitm.it" is literally what the initial issue states, so what is your issue then?

**Comment by wimbledon** [comment]
Sorry for the confusion. I've created a new issue: #2355

**Comment by sgbookexchange** [comment]
@mhils nope, can't connect any website including http. I doubt something wrong in configuration step but can't find after double check.

**Comment by mhils** [comment]
Thanks for the feedback. Please check out http://docs.mitmproxy.org/en/stable/modes.html and then ask on Discourse if you still have issues. :)
