### ISSUE TITLE
Cannot Verify Server Identity

### ISSUE THREAD

**Issue by wimbledon** [mitmproxy/mitmproxy#2355]
##### Steps to reproduce the problem:

1. Installed the mitm certificate profile from mitm.it successfully
2. Seen mitmproxy event logs for plain http websites.
3. Works perfectly fine with my old iPhone 6, but not iPhone 7 (iOS 10.3.1) device.

##### Any other comments? What have you tried so far?
Facebook:
![img_0124](https://cloud.githubusercontent.com/assets/3291853/26475281/b77dd4b0-416b-11e7-9966-19d2a22b5fa0.PNG)

Google Map:
![img_0125](https://cloud.githubusercontent.com/assets/3291853/26475283/b77f4da4-416b-11e7-8892-3d017d21b580.PNG)
![img_0126](https://cloud.githubusercontent.com/assets/3291853/26475285/b7803944-416b-11e7-8035-1402a70dcf76.PNG)
![img_0127](https://cloud.githubusercontent.com/assets/3291853/26475284/b77fc89c-416b-11e7-9f3d-d33f385827de.PNG)
![img_0128](https://cloud.githubusercontent.com/assets/3291853/26475286/b78289d8-416b-11e7-90d7-bc23f4911d36.PNG)
![img_0129](https://cloud.githubusercontent.com/assets/3291853/26475282/b77df148-416b-11e7-8030-fb8e2d49494c.PNG)

##### System information
Device: iPhone 7
iOS version 10.3.1
Chrome on iOS 58.0.3029.113

Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.1
Platform: Darwin-16.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e 16 Feb 2017
Mac version: 10.12.5 ('', '', '') x86_64

**Comment by mhils** [comment]
DId you enable mitmproxy in `Settings > General > About > Certificate Trust Settings`?

**Comment by wimbledon** [comment]
No! Thank you for letting me know. Should this be in FAQ or a part of the setup setps?

**Comment by mhils** [comment]
It's in the docs (and on mitm.it) on master, but we default to the stable release docs. We "just" need to push an update.

**Comment by frozenfung** [comment]
Just enable mitmproxy in `Settings > General > About > Certificate Trust Settings`.
Can hear from https sites in terminal now.

However, I want to sniff facebook app but it just show me that `can load this page` in my facebook app.

How can I do?

thanks
