### ISSUE TITLE
How can I change the certificate name?

### ISSUE THREAD

**Issue by Yaldo425** [mitmproxy/mitmproxy#2362]
When downloading the certificate for decrying HTTPS decrypt on a device, the name of the certificate shows up as "mitmproxy" Is there any way to change its name?

**Comment by mhils** [comment]
There is no builtin way. If you want to do it, you have to read and modify the source code.

**Comment by Yaldo425** [comment]
Thank you for the reply. That will not be a problem, but where is the file with the certificate's information so that I can change it? I attempted to go through all of the files related to certificates but it's too much
