### ISSUE TITLE
https proxy Private certificate response 502 error

### ISSUE THREAD

**Issue by topperun** [mitmproxy/mitmproxy#2368]
when i proxy a web like https://10.1.8.4:443 ,the server response "**TlsProtocolException("Cannot establish TLS with 10.1.8.4:443 (sni: None): TlsException('Cannot validate certificate hostname without SNI',)",)**"

I don't konw how to resolve this problem, It's my fault or the process bug?

**Comment by mhils** [comment]
Your client is not sending a Server Name Indication, which is why mitmproxy cannot validate the upstream certificate. You either need to use a client that does that or disable certificate verification in mitmproxy (`--insecure`).
