### ISSUE TITLE
is there any command to clear history

### ISSUE THREAD

**Issue by hihell** [mitmproxy/mitmproxy#237]
In console I need a command to clean package history, is there any command do this job? if not would you kindly add this feature?
Many Thanks

**Comment by ErDmKo** [comment]
In new versions you must use "z" to clear flow list

**Comment by zweifisch** [comment]
Is it possible to clear flow list in mitmweb, or limit the number of entries? I'm running mitmweb in docker container for debuging purpose, and have to restart the container from time to time to clear the flows, otherwise it crashes the browser.

**Comment by mhils** [comment]
mitmproxy -> New.

**Comment by ironsalsa** [comment]
I thought I'd post https://discourse.mitmproxy.org/t/mitmweb-programmatic-clear-of-session/1085/3 for anyone else landing here from search - you can trigger this programatically with an API call to the Web UI:

`export WEB_UI_URL="http://192.168.13.234:8081/" 
export CSRF_COOKIE=$(http --print h ${WEB_UI_URL} | perl -lane'print $1 if /Cookie: (.*);/')
http -v POST "h${WEB_UI_URL}clear?$CSRF_COOKIE" "Cookie:$CSRF_COOKIE"`

**Comment by draksler** [comment]
If I understand correctly, you could trigger that programmatically as well by calling that view directly.

```
from mitmproxy import ctx

view = ctx.master.addons.get("view")
if view.store_count() >= MAX_STORE_COUNT:
    view.clear()
```

**Comment by zakhar-novikov** [comment]
Works for me with python requests:
```
import requests

r1 = requests.get("http://0.0.0.0:8081/")
jar = r1.cookies
csrf_token = jar.get('_xsrf')
r2 = requests.post("http://0.0.0.0:8081/clear?_xsrf={0}".format(csrf_token), cookies=jar)

```

**Comment by kid1412621** [comment]
need the default keymap docs

**Comment by Dan1ve** [comment]
> In new versions you must use "z" to clear flow list

FWIW: I had a problem that the web interface would crash with a completely white page (some JavaScript error, probably due to some special request causing troubles). As the UI was visible for a split second before the page turned white, I tried to hit `Z` really quickly once the page loaded, and that worked 🎉
