### ISSUE TITLE
How to MITM specific domain?

### ISSUE THREAD

**Issue by Yaldo425** [mitmproxy/mitmproxy#2370]
How can I MITM just one specific domain?  I don't mean filtering out results just to show a single domain, I mean leaving all domain traffic untouched except for one domain.

**Comment by Kriechi** [comment]
@Yaldo425 all traffic from your browser goes through a proxy. There is only a proxy-blacklist for domains & IPs that should never go through the proxy. There is no whitelist.
The closest you can get is by using mitmproxy filtering.
