### ISSUE TITLE
Improve All The Docs!

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#2374]
This issue combines all existing and stale documentation-related issues:

  - [x] Transparent Mode on Windows
    - #323, #336
    - https://discourse.mitmproxy.org/t/intercept-roku-traffic-on-windows/406
  - [x] Setting up local transparent proxy
    - #630
  - [x] Improve Server Replay Docs
    - #635
  - [x] HTTP body streaming and Content-Length header
    - #856
  - [x] Link to the right branch in the option documentation
    - #2243
  - [x] Inline certificate installation docs
    - #2089
  - [x] Using external libraries with mitmdump
    - #2238

**Comment by cortesi** [comment]
Do we want to collect infrastructural doc-related issues here? We really need to move away from Sphinx/ReadTheDocs to a simple static generator. The current system is enormously cumbersome to work with, and we can do much better on the layout/design/presentation side if we had full control.

**Comment by cortesi** [comment]
I think we need an FAQ. There's a ton of common questions that could be presented pretty well in this format.

**Comment by mhils** [comment]
I agree. Let's collect questions and answers at mitmproxy/mitmproxy.org#21. :)

**Comment by kira0204** [comment]
Hi, What are our plans with this?

**Comment by MrTsRex** [comment]
@armudgal I can help with this. How do you want to go about this?

**Comment by armudgal** [comment]
Hi @MrTsRex, I couldn't take a look on this. I would wait for the reply from the maintainers cause a lot has been done in the past year.

**Comment by Kriechi** [comment]
@MrTsRex just pick a topic and start contributing by sending a PR 😄 👍 
If you are a mitmproxy-beginner, I would recommend looking at for easy-to-fix things first to get to know our codebase.

**Comment by MrTsRex** [comment]
@armudgal @Kriechi Thanks for the prompt replies guys. 👍

**Comment by rugk** [comment]
All issues you referenced in the OP are closed now? (Fixed?)

**Comment by Kriechi** [comment]
Indeed they are!
