### ISSUE TITLE
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_EVP_PKEY_DHX'

### ISSUE THREAD

**Issue by timdp** [mitmproxy/mitmproxy#2380]
##### Steps to reproduce the problem:

1. `pip3 install --upgrade mitmproxy` 
2. `mitmdump`
3. Crash with __AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_EVP_PKEY_DHX'__

##### System information

Python 3.5.2 on Ubuntu 16.04

Output of `pip3 install`:

> Successfully installed PyYAML-3.12 argh-0.26.2 asn1crypto-0.22.0 blinker-1.4 brotlipy-0.6.0 certifi-2017.4.17 cffi-1.10.0 chardet-3.0.3 click-6.7 construct-2.8.12 cryptography-1.7.2 cssutils-1.0.1 editorconfig-0.12.1 h2-2.6.2 hpack-2.3.0 html2text-2016.9.19 hyperframe-4.0.2 idna-2.2 jsbeautifier-1.6.4 kaitaistruct-0.6 mitmproxy-1.0.2 packaging-16.8 passlib-1.7.1 pathtools-0.1.2 pyOpenSSL-16.2.0 pyasn1-0.1.9 pycparser-2.17 pyparsing-2.2.0 pyperclip-1.5.27 requests-2.13.0 ruamel.yaml-0.13.14 setuptools-34.1.0 six-1.10.0 sortedcontainers-1.5.7 tornado-4.4.2 urllib3-1.21.1 urwid-1.3.1 watchdog-0.8.3

It worked before, so I guess some dependency is outdated? Any suggestions on where to look? Thanks!

**Comment by Kriechi** [comment]
cryptography and openssl would be good suggestion based on your error message.
ref #2372

**Comment by timdp** [comment]
Not sure how I missed that. GitHub search failed miserably. Thanks!
