### ISSUE TITLE
Re-add --raw-tcp/--rawtcp functionality

### ISSUE THREAD

**Issue by Caligatio** [mitmproxy/mitmproxy#2382]
It appears that support for --raw-tcp (apparently now possibly renamed to  --rawtcp) was removed in commit fbaade429845546d751110caa0f886f7b1a62717 citing a move to "explicit control" instead. As far as I can tell it was just removed without a replacement. Was this intentional and, if so, is there any plan to re-add something like it?

Understandably it's difficult to definitely say whether something is raw TCP vs. HTTP but you could check against standard HTTP verbs and fallback to TCP if they're not found.

**Comment by Kriechi** [comment]
As far as I understand this commit, only a "automatic detection heuristic" for raw-tcp mode was removed. 
RawTCPLayer should still be usable via [this](https://github.com/mitmproxy/mitmproxy/blob/fbaade429845546d751110caa0f886f7b1a62717/mitmproxy/proxy/root_context.py#L60) and [this](https://github.com/mitmproxy/mitmproxy/blob/fbaade429845546d751110caa0f886f7b1a62717/mitmproxy/proxy/root_context.py#L83).

**Comment by Caligatio** [comment]
I fully agree that the functionality of --raw-tcp can be *partially* recreated using --tcp and --ignore but both of those assume that you you know the remote host ahead of time, which is a big assumption. Regardless of what parts can be partially recreated, the program's --help shows --raw-tcp as a valid flag, albeit experimental.

I'm happy to submit a PR that either removes the flag or re-adds a slightly improved heuristic; I think people would prefer having the functionality vs. not.

**Comment by Kriechi** [comment]
Let's see what @cortesi has to say, since he originally removed this functionality. I'm fine with both.
/cc @mhils

**Comment by mhils** [comment]
I think it's generally useful (at least it was to me), but at the same time needs to stay off-by-default when reintroduced.

**Comment by Caligatio** [comment]
Due to the determination of RawTCP fallback vs HTTP being iffy at best, I'm with you that it should definitely be off by default.  Is it worth doing a PR to try to re-add it?

**Comment by cortesi** [comment]
Hi @caligato - thanks for triggering a discussion here. Let's see if we can work out how to proceed.

I'd prefer to keep this type of frankly dangerous heuristic out of the codebase if we can, even behind a switch. As the commit says, lets see if we can accomplish the same things in a more explicit fashion. @Caligatio, would you mind telling us about your use-case, please? Could switching based on destination port/host work for you, for instance?

If we find that a hot heuristic is the only approach that works, I'd like to do it properly. That means:

- A better name than "rawtcp"
- Sound documentation for what this does and how it works
- A more sophisticated heuristic than just checking if the first 3 bytes are ASCII
- Finally, this belongs in an addon. We should extend the event mechanism to make protocol switching for this sort of use-case possible (and in fact much of the functionality from root_context.py should also move over).

**Comment by Caligatio** [comment]
I basically want to blindly send all TCP connections from a particular host (a VM) through mitmproxy to be able to dump the (pre-)master secrets on all TLS connections for later analysis.  I don't know anything about the traffic leaving the VM beforehand so unfortunately port/host filtering/switching doesn't help me much.

My proposed "slightly improved" heuristic would be to replace the previous ASCII check with a peek at the first 7 bytes and do a comparison whether those bytes are a HTTP verb.  Why 7 bytes? It's the length of the longest standard HTTP verb and, since we're going to fallback to HTTP anyways, every HTTP request should have at *least* 14 bytes (e.g. "GET / HTTP/1.1").  If it matches against a HTTP verb, fallback to HTTP processing like is done now; if it's not a HTTP verb, process it as a RawTCPLayer.

I'm definitely not wedded to the name "rawtcp" but it does kind of get the point across.  Maybe something like "--generic-tcp-proxy" or "--fallback-tcp-proxy" with some appropriate documentation on what it does and its shortcomings?

**Comment by cortesi** [comment]
So, in your scenario you don't actually care about having plain HTTP interpreted as HTTP - you'd be happy if we just forwarded all non-TLS connections through as TCP, is that correct? This would let you pick out the details you need from TLS connections, and everything else just flows through the proxy as a stream. 

If that's the case, we don't need the gnarly heuristic at all in your case, we just need to be able to switch the default protocol interpretation from HTTP to RawTCP, which is a much simpler and more consistent piece of functionality.

**Comment by Caligatio** [comment]
It would helpful to keep future possibilities open with regards to treating HTTP special and keeping flow scripting.  If absolutely necessary I could chain mitmproxies together, one for TLS dumping and one for HTTP modification, but that's a bit ugly.

**Comment by cortesi** [comment]
Right. Let's do this:

- Re-add rawtcp that unambiguously does what it says on the tin, without heuristics (i.e. the default protocol is raw TCP rather than HTTP). This is a two-line patch [here](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/root_context.py#L108), and I'll happily merge it immediately to get you under way.
- I'll make sure that we're still flexible by letting an addon hook perform protocol switching. That way addons can arbitrarily switch the protocol on a per-connection basis in whatever way they like so we can safely experiment with heuristics. I'd be happy to have an "autodetect_protocol" addon in core on this basis too.

**Comment by Caligatio** [comment]
Ok, so the patch would kick out to RawTCP and then it would be up to an add-on to do HTTP1 identification? Would one do some next_layer hooks like the tls_passthrough.py example except trigger on next_layer being RawTCP?

**Comment by cortesi** [comment]
Yes, that's right. I'd like to sit down and look at that particular part of the addon API to make sure it's consistent and caters for all of these use cases. In fact, I'd like to be able to move the protocol switching mechanism entirely into a built-in addon.

**Comment by Caligatio** [comment]
Caveating that I'm not an add-on expert, I think that sounds reasonable. I would make a passing comment though that RawTCP seems like a semi-confusing name as I would think it's the top layer, not necessarily something that could be under TLS and a sibling of HTTP. If you'd be willing to rename it, something like RawPayload might make more sense.

Hopefully last question =) Since I'll be using an add-on to do HTTP1 identification,  can you chain multiple add-ons together using the  add-ons=[] syntax? Looking at the examples, it appears only one is ever used (note I'm on my phone right now so may have missed an example where that is not the case).

Regardless, thank you for the quick replies and help!

**Comment by cortesi** [comment]
We'll workshop the name a bit. There are some variations we can play with - maybe "passthrough"? I actually think rawtcp is reasonable if the functionality is unambiguously to set the default protocol 
to raw tcp. 

Yes, you can chain together addons. A big drive for me in the next few days is to firm up the addons documentation, and I'll make sure I add something explaining how this works.

**Comment by Caligatio** [comment]
Sorry for being unclear, I meant RawTCP as a protocol class name, not as a flag name.  I'm guessing changing the name of RawTCP may break a lot of downstream stuff and probably it's worth doing.

**Comment by Kriechi** [comment]
Just a quick note regarding fancy heuristics and HTTP/2:
The first bytes a client sends are `PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n`.
Not your typical HTTP verb first line, so please be careful.

**Comment by Caligatio** [comment]
@Kriechi To be clear, the current logic is something like "try a bunch of tests, default to HTTP1" whereas what we're proposing is "try a bunch of tests, if flag set, go with RawTCP, if flag not set, use HTTP1."  This particular patch/idea doesn't hurt the current situation at all.

I'm trying to read up on TLS/ALPN and HTTP2.  It appears HTTP2 *should* use TLS and most browsers require TLS to use HTTP2.  Additionally, it appears most browsers implement ALPN.  I realize there are a lot of mosts/shoulds in that sentence but what it means is that [the ALPN check](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/root_context.py#L99-L105) should pick up HTTP2 most of the time.

**Comment by Kriechi** [comment]
You are right - at the moment mitmproxy only supports HTTP/2 with TLS+ALPN.
So we should be good!

**Comment by mhils** [comment]
> Re-add rawtcp that unambiguously does what it says on the tin, without heuristics (i.e. the default protocol is raw TCP rather than HTTP).

This can already be achieved by `--tcp .*` or `--ignore .*`. I don't think it's useful to have a second flag for this.

> Yes, that's right. I'd like to sit down and look at that particular part of the addon API to make sure it's consistent and caters for all of these use cases. In fact, I'd like to be able to move the protocol switching mechanism entirely into a built-in addon.

Yes - protocol switching is something that we definitely need to solve properly, especially in the light of sans-io. The problem is a bit more generic than what's mentioned here (see e.g. https://github.com/mitmproxy/mitmproxy/issues/1774), so I propose we move that to a new issue. I'm all in for having addons being able to decide, we also already do that in [examples/complex/tls_passthrough](https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/tls_passthrough.py) for example.

fbaade4 only removed the actual logic, but not the option or the command line argument. I opened https://github.com/mitmproxy/mitmproxy/pull/2499 to temporarily re-add rawtcp mode, until a more refined solution is implemented (see 9ca6785d40ebe0293f36683250d72998f438bba9 for more details on this).
