### ISSUE TITLE
Get original host, scheme or url

### ISSUE THREAD

**Issue by 2tunnels** [mitmproxy/mitmproxy#2383]
I'm using `mitmdump` as reverse proxy with script. How can I get original (or incoming) request host.

For example: http://mysite.com/something => https://example.com/something

Now `flow.request.host` == `example.com`, `flow.request.url` == `https://example.com/something`

I need to get `mysite.com` and `http://mysite.com/something` as well.

**Comment by mhils** [comment]
You can use the `requestheaders` hook to get the original information.
