### ISSUE TITLE
about libmproxy

### ISSUE THREAD

**Issue by cuijianxiong** [mitmproxy/mitmproxy#2391]
##### Steps to reproduce the problem:

I am going to do a passive scan project recently.So found this great third-party library.But I have a problem with calling pymproxy on the python3 extension api libmproxy. Unfortunately, I did not find it, but my English was bad. Would like to ask in python3 there is no similar api. Many thanks

**Comment by Ritiek** [comment]
`libmproxy` was renamed to `mitmproxy` a long time ago.

```
import mitmproxy
```

**Comment by cuijianxiong** [comment]
@Ritiek  thank you very much .Can we be friends?

**Comment by Ritiek** [comment]
we all are already friends :D

**Comment by cuijianxiong** [comment]
Thank you also my first foreign friend O (∩ _ ∩) O

**Comment by mhils** [comment]
Thank you two! 😃
