### ISSUE TITLE
Parallel usage of mode upstream and transparent

### ISSUE THREAD

**Issue by mwiora** [mitmproxy/mitmproxy#2400]
Hi all,

I'm using the latest code version

Mitmproxy version: 3.0.0 (release version)
Python version: 3.5.2
Platform: Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g 1 Mar 2016
Linux distro: Ubuntu 16.04 xenial

and I have the following scenario:

(www) <-- (proxy requiring auth) <-- (mitmproxy host) <-- (developer machine)

To achieve that the developer machine is not proxy-aware I would like to operate the mitmproxy host in transparent and upstream mode simultaneously.

With the current dev-version I'm able to operate the mitmproxy in upstream mode with the following command:
mitmproxy -m upstream:http://x.x.x.x:8080

but as soon as I add "-m transparent" the upstream proxy setting is lost.
Is there a way to combine both variants?

Cheers and thanks in advance for any reply,
Matthias

**Comment by mhils** [comment]
The combination of upstream and transparent mode is not possible at the moment. I don't think this is something we are planning to implement in the near future either, sorry.
