### ISSUE TITLE
TlsException (Unexpected EOF) when connecting to SSL

### ISSUE THREAD

**Issue by SmashGuy2** [mitmproxy/mitmproxy#2403]
Hi, I've just install mitmproxy on Bananian. Using Python 3.5 and installed v2.0.2 release version via pip3. Connecting to non-SSL sites works just fine, but when I attempt to connect to SSL sites (google.com in this case), Chrome complains. mitmdump shows various TlsExceptions.

I am posting the output below. The first errors were triggered as I was typing "google.com" into the address bar. When I pressed enter, I received a 301 error followed by the two final errors.

Any help appreciated. Happy to provide whatever additional information I can.

# mitmdump -p 8181
HTTP/2 is disabled because ALPN support missing!
OpenSSL 1.0.2+ required to support HTTP/2 connections.
Use --no-http2 to silence this warning.
Proxy server listening at http://0.0.0.0:8181
192.168.101.154:52637: clientconnect
192.168.101.154:52638: clientconnect
192.168.101.154:52635: clientconnect
192.168.101.154:52636: clientconnect
192.168.101.154:52639: clientconnect
192.168.101.154:52637: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52637: clientdisconnect
192.168.101.154:52635: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52635: clientdisconnect
192.168.101.154:52638: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52638: clientdisconnect
192.168.101.154:52636: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52636: clientdisconnect
192.168.101.154:52639: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52639: clientdisconnect
192.168.101.154:52640: clientconnect
192.168.101.154:52641: clientconnect
192.168.101.154:52640: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52640: clientdisconnect
192.168.101.154:52641: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52641: clientdisconnect
192.168.101.154:52642: clientconnect
192.168.101.154:52643: clientconnect
192.168.101.154:52642: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52642: clientdisconnect
192.168.101.154:52644: clientconnect
192.168.101.154:52643: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52643: clientdisconnect
192.168.101.154:52645: clientconnect
192.168.101.154:52646: clientconnect
192.168.101.154:52644: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52644: clientdisconnect
192.168.101.154:52646: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52646: clientdisconnect
192.168.101.154:52645: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52645: clientdisconnect
192.168.101.154:52647: clientconnect
192.168.101.154:52647: GET http://google.com/
                    << 301 Moved Permanently 219b
192.168.101.154:52648: clientconnect
192.168.101.154:52648: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:52648: clientdisconnect
192.168.101.154:52649: clientconnect
192.168.101.154:52649: CONNECT clients4.google.com:443
 << Cannot establish TLS with client (sni: clients4.google.com): TlsException("(-1, 'Unex
pected EOF')",)
192.168.101.154:52649: clientdisconnect

##### System information

#mitmproxy --version
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.2
Platform: Linux-3.4.111-bananian-armv7l-with-debian-8.8
SSL version: OpenSSL 1.0.1t  3 May 2016
Linux distro: debian 8.8

**Comment by SmashGuy2** [comment]
Oh, I should mention that I installed the Windows CA cert on my client machine. Mitmproxy is running on a separate Linux (Bananian) box on my network.

**Comment by mhils** [comment]
Did you try using a non-browser client such as cURL?

**Comment by SmashGuy2** [comment]
I get the same thing. Here's what I see what I attempt to download from the command line (windows):

**Invoke-Webrequest https://www.google.com**
Invoke-Webrequest : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS
secure channel.
At line:1 char:1
+ Invoke-Webrequest https://www.google.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**And mitmdump returns:**

192.168.101.154:61833: clientconnect
192.168.101.154:61833: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpecte
d EOF')",)
192.168.101.154:61833: clientdisconnect

**Comment by SmashGuy2** [comment]
I just noticed a couple more things, not sure if they are relevant or not. 

When I run mitmproxy, no flows appear when I make the request, though the windows client returns the same error as above (Could not establish trust relationship). I confirmed that mitproxy is receiving the request however, because when I stop it I receive a "connection cannot be established" message.

Secondly, if I request the unencrypted url (http://www.google.com), I get two responses back:

GET http://www.googlecom/
    200 text/html 44.31k 561ms
GET https://ssl.gstatic.com/gb/images/b_8d5afc09.png
    200 image/png 9.53k 747ms

Seems odd that that the 2nd file came through correctly. I followed this up with another request to https://www.google.com and that broke, same as before.

**Comment by mhils** [comment]
The error message in https://github.com/mitmproxy/mitmproxy/issues/2403#issuecomment-309760416 indicates that your client does not trust the certificate presented by mitmproxy. Besides, you're not really using curl (https://github.com/PowerShell/PowerShell/pull/1901).

**Comment by SmashGuy2** [comment]
That's correct. The question is why? The certificate is installed in the client machine...?

**Comment by mhils** [comment]
Can you double-check that you installed the certificate as a root certificate authority?
(`certmgr` -> trusted root certificate authorities)

**Comment by SmashGuy2** [comment]
Ok, that was the problem! The certificate was installing itself in the Personal certificates directory.

Is there a link to a page with install instructions for each OS? The magic page only has Android instructions.

**Comment by SmashGuy2** [comment]
Well, looks like that mostly fixes it anyway. Outlook.microsoft.com is acting very strangely now. It works, but very slowly. And mitmdump is filling up with the following.

(BTW, thanks for your help so far!)

192.168.101.154:50538: clientconnect
192.168.101.154:50536: clientdisconnect
192.168.101.154:50535: CONNECT outlook.office.com:443
 << Cannot establish TLS with client (sni: outlook.office.com): TlsException("(-1, 'Unexp
ected EOF')",)
192.168.101.154:50535: clientdisconnect

**Comment by mhils** [comment]
> Is there a link to a page with install instructions for each OS?

No, we do need better docs for that - contributions are welcome!

Closing this as the original issue seems to be fixed.
