### ISSUE TITLE
Limitations when using a GUI text editor with "view body in external editor" (v) option

### ISSUE THREAD

**Issue by idiotsavant** [mitmproxy/mitmproxy#2404]
##### Steps to reproduce the problem:

1. On MacOS, "edit" invokes TextWrangler from the terminal and "atom" invokes Atom. Both options work fine for opening files directly from the terminal.

2. After setting $EDITOR and $PAGER in .bash_profile I can trigger both external editors from mitmproxy using 'v'. However, neither option works well.

(A) using TextWrangler the contents of the body is correctly opened in TextWrangler. However, the file is read-only, making it impossible to apply JSON pretty-printing using a Text Filter without first doing a "save as". 

(B) using Atom the contents of the body do not arrive in Atom. An empty file opens in Atom instead, with a similar name and in the same directory as the one opened by TextWrangler. But the content is missing.

##### Any other comments? What have you tried so far?

The reason I'm doing this is because I want to examine JSON from the body of particular requests in an external editor, and being able to pretty-print them easily (e.g. using the Beautify package for Atom) is key to being able to scan through the JSON quickly.

##### System information

Mac OS Sierra 10.12.5
mitmproxy installed via Homebrew

Mitmproxy version: 2.0.1 (release version)
Python version: 3.6.1
Platform: Darwin-16.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.5 ('', '', '') x86_64

**Comment by mhils** [comment]
I think the problem with these two editors is that they do not block when opening a file? Does vi/nano work for you?

**Comment by idiotsavant** [comment]
Thanks for your quick response. Yes, nano works fine.

It sounds like this is an enhancement request, and that things are working as designed. It would be great to be able to open the body in a text editor with all the syntax highlighting bells and whistles though!

**Comment by mhils** [comment]
You can export a body and then open it if that helps. The problem with opening it for editing is that we don't get a "done" signal from the editor.

**Comment by idiotsavant** [comment]
Exporting the body works, but it's not as straightforward as pressing 'v' would be. I'm not sure there's a solution to this, but thanks for explaining what's happening. Feel free to close unless you want to add this as a future enhancement. Many thanks for your help.

**Comment by mhils** [comment]
We don't want to leave the file bodies on disk after editing has been completed (from our point of view), so this is tricky... I'd generally be happy to merge any PR that improves the current behaviour, but I'm not sure what's the best way to do so. If you have a cool heuristic to detect that the editor is not blocking, we can combine that with a "press any key when you have finished editing" prompt in mitmproxy.

**Comment by idiotsavant** [comment]
I'm afraid I don't know of any way to detect that. Note that in my case I don't need to edit the body beyond pretty-printing it so I can look through it - I'm trying to use the text editor as an inspector rather than wanting to save changes afterwards.

**Comment by mhils** [comment]
Thanks for clarifying. I don't think this particular use case warrants an additional keybinding in mitmproxy, but you may be able to implement this yourself with the next release as a command (we don't have any docs for that yet, sorry). I'll close this here for now, if you are interested in making a command out of this, the next release should have docs 😃
