### ISSUE TITLE
Pasting view filter with ~hq does not work

### ISSUE THREAD

**Issue by idiotsavant** [mitmproxy/mitmproxy#2405]
##### Steps to reproduce the problem:

1. In mitmproxy console, with a list of flows visible, press 'f' and *type*:
`~hq X-MyMessageTypes`
Flows are filtered as expected, to show only those where this request header is present.

2. press 'f' again clear the filter so all flows are visible again

3. press 'f' again and *paste* the following:
`~hq X-MyMessageTypes`
No flows are displayed.

Typing out the exact same filter works, whereas pasting it in does not. This isn't the case for other view filters such as `~d mydomain`, which works either way.

##### System information

Mitmproxy version: 2.0.1 (release version)
Python version: 3.6.1
Platform: Darwin-16.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.5 ('', '', '') x86_64

**Comment by mhils** [comment]
Are you sure that you did not accidentally paste any additional weird white-space characters?

**Comment by idiotsavant** [comment]
I'm sure - I carefully pasted from a text editor because I wondered about that. It's also not entirely consistent and the way that 'f' remembers the previous entry seems to have something to do with it.

Here's a short video clip so you can see what I mean: https://drive.google.com/file/d/0B1tPawS7MU4CRjRPTkJmSnoyQ3c/view?usp=sharing

**Comment by Kriechi** [comment]
Thanks for the great screen capture! Thanks for reporting this!
Just in case it makes a difference: when you typed the filter by hand, you didn't use `&` between the clauses.

But obviously, even if you just paste a single filter it didn't work. So there is definitely something bugged here!

**Comment by Kriechi** [comment]
Hmm I'm having problem reproducing this on my system:
Python 3.5.2
macOS 10.12.5
iTerm2 3.0.15

Can you try with a different Terminal app? What are you using at the moment? 
Is `~` a [dead key](https://en.wikipedia.org/wiki/Dead_key) on you machine?
You text editor on the left was set to UTF8, does your terminal accept and use the same?
Do you have fancy escape sequences that might interfere with pasting `~`?

**Comment by idiotsavant** [comment]
Thanks for investigating! I'm also using iTerm2, with the same version as you.

I just tried the steps again using the default MacOS Terminal and I got the same behaviour - no flows displayed after pasting. I then tried the steps again, still in Terminal, using the laptop's built-in keyboard and the standard Apple keymap, rather than the external keyboard I usually use, and again I reproduce the issue.

Then I tried once more in iTerm2 as I did originally, and now it works correctly! And after stopping starting mitmproxy several times I still can't reproduce. Weird. Whatever the issue is, I can't reproduce it consistently. If you can't either then feel free to close this. I'll reopen if I can put together a set of steps that consistently triggers the issue.

Good catch on the use of the '&' characters. I've tried it with and without those, and I seem to be able to get away with not using them - I guess it defaults to 'and' with multiple conditions.
