### ISSUE TITLE
Long URLs prevent "going back" to flow list

### ISSUE THREAD

**Issue by yoavfrancis** [mitmproxy/mitmproxy#241]
Hi, 

I was running mitmproxy and ran into a very long "GET" line (Facebook causes that quite often). When I pressed "Enter" to view the flow, I was unable to "Go back" to the flow list by pressing "q". Instead - I was displayed with the "Quit?" Dialog and had to restart mitmproxy.

Here is an example (I removed some of the data in the GET request)

![bug_long_get_line](https://f.cloud.github.com/assets/328378/2445937/9bb0a0d0-ae7c-11e3-9bf3-81d8af866736.png)

Thanks!
Yoav

**Comment by gato** [comment]
Hi @mhils 
This bug seems to be resolved via 32ba6021b3c07efaa45a9223479151cd7e74ccbd 
Regards.
Marcelo

**Comment by mhils** [comment]
Excellent, thanks for noticing! :)
