### ISSUE TITLE
"Palette" function crashes application

### ISSUE THREAD

**Issue by flarn2006** [mitmproxy/mitmproxy#2414]
##### Steps to reproduce the problem:

1. Run `mitmproxy`
2. Press `O`, then `P` to select "Palette"
3. Observe the crash.

##### Any other comments? What have you tried so far?
Really nothing else to say. Obvious bug, should be easily reproducible.

##### System information
Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-4.4.0-75-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian stretch/sid

**Comment by ujjwal96** [comment]
This is fixed on master

**Comment by mhils** [comment]
Thanks for the report! I'll trust @ujjwal96 here that this is fixed already. :)
