### ISSUE TITLE
Portable version of mitmproxy - how to build a standalone package?

### ISSUE THREAD

**Issue by grmpyninja** [mitmproxy/mitmproxy#2415]
Is it possible and how to approach creating a portable version of mitmproxy? I'd simply like to deploy it like e..g go binaries, without any additional dependencies and so on. Everything in a single package, dumped on a server and ready to go.

- docker is good, but it requires installing docker itself
- I once tried pex to bundle everything, but it did not actually work - maybe I need to check it again if there is no other better alternative

any other way to pack everything or build everything to a standalone package? How in general python packages should be deployed this way? without any dependencies and so on.

**Comment by mhils** [comment]
Hey,

We provide standalone binaries at https://github.com/mitmproxy/mitmproxy/releases/ - that should accomodate your needs. :)

**Comment by grmpyninja** [comment]
Awesome thx! I was not aware of that. I always install it from pip/or dev mode. Additionally I can finally learn how to properly package python apps for Linux/Windows. thx

**Comment by lollita** [comment]
Where save the settings the provide standalone binaries?
If it save also in user .mitmproxy it is not portable.
