### ISSUE TITLE
Does mitmproxy provide something similar to apache httpd's ProxyPassReverseCookiePath

### ISSUE THREAD

**Issue by nakulcg** [mitmproxy/mitmproxy#2420]
First of all thanks for the great piece of software. Makes reverse proxying so easy while testing dev environments.

I am proxying a java application which uses jetty web server. I would like mitmproxy to rewrite my cookie path. So if the path of the java application is /dev and of the reverse proxy to be / I'd want this to be implcitly handled by mitmproxy like apache does. Is this already possible, did I miss an option? If not how could it be implemented?

**Comment by mhils** [comment]
Hi,

this is currently not implemented. If you're interested, I'm sure you can write this as an addon using our scripting API: http://docs.mitmproxy.org/en/stable/scripting/overview.html. If you have specific questions, please don't hesistate to ask in our forums or on Slack. I'm closing this here as there's nothing actionable in this for us. :)
