### ISSUE TITLE
Download Failed [iPhone 6S]

### ISSUE THREAD

**Issue by Drakota** [mitmproxy/mitmproxy#2422]
##### Steps to reproduce the problem:

1. Installed mitmproxy on Linux
2. Open it and assign proxy settings in iPhone
3. Go to mitm.it (works), go to Apple, click Download -> Download Failed.

HTTP domains works, but not HTTPS

Thanks for helping.

**Comment by codeon** [comment]
It worked for me on Safari, but the download failed on Google Chrome.

**Comment by mhils** [comment]
Could you be more specific on "Download failed"?

**Comment by Cphilo** [comment]
android(xiaomi phone) brower download failed too.

**Comment by mhils** [comment]
For anything useful to happen here, we need more data:

- Information on the machine mitmproxy is running on
- The output of `mitmproxy --version`
- Information on the client device that attempts the download
- An actual error description.

**Comment by Drakota** [comment]
Sorry for the delay @codeon solve my problem, I was using Chrome on my phone. Working as expected using Safari. Thanks!
