### ISSUE TITLE
Proxy the local loopback when machine is offline

### ISSUE THREAD

**Issue by danielphillips** [mitmproxy/mitmproxy#2424]
I would love to be able to use mitmproxy whilst I am working on my local web server. The situations when I need this the most is for example when I'm offline (travelling by train home/to work), and I am running my mobile app on the simulator and have it pointed to a stubbing server which is running locally on my machine.

My server would be running on http://localhost:1338 and I am retrieving data from it to my app as expected.

However having mitmproxy running I can't figure out how to capture that traffic (local loopback) things flow through mitmproxy if I'm connected to a network.

---
##### Steps to reproduce the problem:

1. Disconnect from your network (turn off wifi for example)
2. Run a web server locally (say localhost:1338) with anything on it (placeholder file will do)
3. Run mitmproxy
4. Go to the browser/whatever rest client/app and hit the localhost to retrieve the file/endpoint

##### Any other comments? What have you tried so far?
N/A

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.1
Platform: Darwin-16.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Mac version: 10.12.5 ('', '', '') x86_64

**Comment by mhils** [comment]
Thanks for the detailed description. Which proxy mode are you running? Regular, transparent, reverse?

**Comment by danielphillips** [comment]
Regular

**Comment by mhils** [comment]
Hm, this works for me just fine:
```
~
λ devd . &
01:11:27: Route / -> reads files from .
01:11:27: Listening on http://devd.io (127.0.0.1:80)
~
λ mitmdump &
Proxy server listening at http://[::]:8080

~
λ curl -x localhost:8080 -k localhost
127.0.0.1:55880: clientconnect
01:11:46: GET /
        <- 200 OK 5.6 kB
127.0.0.1:55880: GET http://localhost/
              << 200 OK 5.45k
<html>
 [...]
```
