### ISSUE TITLE
Linux issue

### ISSUE THREAD

**Issue by NGTmeaty** [mitmproxy/mitmproxy#2425]
##### Steps to reproduce the problem:

1.mitmproxy in terminal
2.On mobile device, attempt to put proxy in.
3.Device cannot connect to internet

##### Any other comments? What have you tried so far?
I've tried multiple wifis, a lot of things, also other proxy programs, I'm unsure what the problem is, any help would be awesome!

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.1
Platform: Linux-4.11.3-1-ARCH-x86_64-with-arch-17.1-ISO-Rolling
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: Antergos Linux 17.1 ISO-Rolling

**Comment by mhils** [comment]
Do you see "clientconnect" messages in mitmproxy's event log? If not, that's a sure indicator that your device does not reach your proxy server.

**Comment by NGTmeaty** [comment]
Hi, there are no clientconnect messages, I can ping the server from my phone(android).

**Comment by mhils** [comment]
In this case there's no traffic reaching the proxy, so this is not a mitmproxy bug. You need to get your client <-> mitmproxy connection working. http://docs.mitmproxy.org/en/stable/modes.html might be helpful.

**Comment by NGTmeaty** [comment]
I'm attempting to do a regular proxy, however it isn't working, it doesn't seem as if the proxy is being made, anyway I can check?

**Comment by ritiek** [comment]
@NGTMeaty You can check it running a port scan with `nmap` from another pc.

Below should work tell you if the port is open or closed:

```
nmap <local_ip_of_pc_running_mitmproxy> -p <port_being_used_by_mitmproxy>
```

**Comment by NGTmeaty** [comment]
Starting Nmap 7.50 ( https://nmap.org ) at 2017-07-06 01:13 UTC
Nmap scan report for 192.168.7.61
Host is up.

PORT     STATE    SERVICE
8080/tcp filtered http-proxy

Nmap done: 1 IP address (1 host up) scanned in 2.07 seconds



Still won't connect

**Comment by ritiek** [comment]
@NGTMeaty Weird, it should give out either `closed` or `open`. `filtered` means something is wrong.

It is possible that your firewall/AV is blocking requests from devices attempting to connect to the port. Try turning them off for a while if they are on. 

Also, have you tried running mitmproxy on some other port? What does `nmap` scan say before and after mitmproxy is started on the new port?

**Comment by NGTmeaty** [comment]
No AV or Firewall, different port doesn't fix anything
