### ISSUE TITLE
Safari cannot open any pages when running mitmproxy

### ISSUE THREAD

**Issue by fbessez** [mitmproxy/mitmproxy#2432]
##### Steps to reproduce the problem:

1. run mitmproxy from terminal
2. go to mitm.it to get certified --> Here it shows up as two GET requests to mitm.it as expected
3. THEN, I can't visit any other websites, as I just get a 'Safari cannot open the page because it could not establish a secure connection to the server'

How do I work around this??
Thank you very much!

##### System information

Mitmproxy version: 2.0.2 (1.1.9dev0045-0xbef2c6c9b) 
Python version: 3.6.1
Platform: Darwin-16.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.12.5 ('', '', '') x86_64

**Comment by mhils** [comment]
Safari on iOS or Safari on OSX? Does [this](https://github.com/mitmproxy/mitmproxy/blob/b115c25dcc07186e1012f57d60766625926c1d56/mitmproxy/addons/onboardingapp/templates/index.html#L7-L20) help?

**Comment by fbessez** [comment]
Yes thank you. I had to enable trust!
