### ISSUE TITLE
How to use mitmproxy/mitmdump as a lib, not a command line tool?

### ISSUE THREAD

**Issue by chenzx** [mitmproxy/mitmproxy#2437]
I've found that if i want to build a custom http ALG(app-layer-gateway), which can:

1、act like a reverse proxy,
2、can modify the Host、Referer header field of client request、and Location of server 302 redirect
3、can modify the content of JSON response, to prefix all the http://... url with http://< my-mitmproxy-ip-port >/http://...
4、log all the original client request data and server response data

The doc doesn't say how to do this. It seems mitmproxy/mitmdump is expected to be used as a cmd tool, not a lib.

Can anyone show me how to do this? I need a simple python script as a main driver...

**Comment by Kriechi** [comment]
Please take a look at our scripting documentation: http://docs.mitmproxy.org/en/stable/scripting/overview.html

**Comment by chenzx** [comment]
Yes, according to the docs, the important seems to be: all the function name are event names, & they are loaded by mitmdump.

But the mitmdump is built-in cmd tool, can i write my own `main.py` script to do this?

**Comment by awdng** [comment]
I have a similar question @chenzx 
ever found a way to do this ?
