### ISSUE TITLE
When mitmproxy does content modification, can it obey the server's original encoding settings?

### ISSUE THREAD

**Issue by chenzx** [mitmproxy/mitmproxy#2438]
If the original html/json response content is 

1. Content-Encoding: gzip
2. Transfer-Encoding: chunked

encoded, and if it's modified by mitmproxy using addon scripts, then does the new response data client receives obey the same encoding settings (gzip+chunked)?

I can't configure the mitmproxy to run on Windows 10, so i just post the question here.

**Comment by mhils** [comment]
> then does the new response data client receives obey the same encoding settings (gzip+chunked)?

gzip yes, chunked no.

> I can't configure the mitmproxy to run on Windows 10, so i just post the question here.

Please use discourse.mitmproxy.org for user questions.
