### ISSUE TITLE
Error starting proxy server: OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)

### ISSUE THREAD

**Issue by chenzx** [mitmproxy/mitmproxy#2439]
##### Steps to reproduce the problem:

1. I downloaded the 2.0.2 exe installer, & try to run mitmdump under venv on Windows 10, but failed

`D:\repo\py3-webservice-http-ALG>venv\Scripts\activate
(venv) D:\repo\py3-webservice-http-ALG>mitmdump
Error starting proxy server: OSError(10013, '以一种访问权限不允许的方式做了一个访问套接字的尝试。', None, 10013, None)

(venv) D:\repo\py3-webservice-http-ALG>`

##### Any other comments? What have you tried so far?

I have tried to install mitmproxy via pip, but a utf8 decoding error caused pip install to fail

**Comment by Kriechi** [comment]
A quick translation of above error message:
> An attempt to access a socket is made in a way that access is not allowed.

Make sure you have nothing else running on port 8080.
mitmproxy requires TPC port 8080 to start the proxy. If this port is already take by some other application, you have to make sure this port is free.

**Comment by chenzx** [comment]
I see. Thanks.

2017-07-13 19:45 GMT+08:00 Thomas Kriechbaumer <notifications@github.com>:
