### ISSUE TITLE
mimt.it  

### ISSUE THREAD

**Issue by Perterually** [mitmproxy/mitmproxy#2442]
##### Steps to reproduce the problem:
Web access error  502 bad requests
![image](http://7xvnj6.com2.z0.glb.clouddn.com/Screenshot%20from%202017-07-17%2020-12-50.png)

##### System information

Mitmproxy version: 2.0.2 (1.1.0dev0000-0xbed627a) 
Python version: 3.6.1
Platform: Linux-4.11.0-10-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: debian stretch/sid

**Comment by Kriechi** [comment]
Please use the correct domain: `mitm.it`.

**Comment by Perterually** [comment]
I' m so sorry.
