### ISSUE TITLE
Improve Option UX

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2444]
I did some work on the mitmweb options today and noted the following things:

- I feel that we should make `flow_detail` and `verbosity` choices instead of ints to increase their usability. It's not really clear at the moment what "verbosity=2" even means.
- There are a whole bunch of options in mitmweb now which don't make sense for mitmweb (`view_filter`, `keepserving`, `flow_detail`, ...). Do we want to keep and ignore them, or are there better solutions? Maybe it's just enough to move them into addons that are only loaded by the respective tools?
- Quite a few options still don't support live editing. We really should fix as many as possible before the next release (@ujjwal96, maybe some easy tasks for you if you want?), For the proxy server options, this refs #2185 and the sans-io work.
- mitmweb currently does live-editing, i.e. if you type a character, we immediately try to update the option at the backend (there is throttling, but that's it). That is great for most options, but I wonder how we should treat `cadir`, which, if we would naively implement live edit support, would create a new CA dir for each character that gets typed. Similarly, `rfile`, which currently only reacts to `running` at startup. Maybe mark some options readonly during execution?

**Comment by MatthewShao** [comment]
I went through the options in current option editor of mitmweb, and track the status of them. It's a brief check, correct me if I'm wrong.

| Option  | Usability | Error Details|
| ------------- | ------------- |-----------|
| add_upstream_certs_to_client_chain  | :x:  |The verify-upstream-cert requires certificate verification to be disabled. If upstream certificates are verified then extra upstream certificates are not available for inclusion to the client chain.|
|anticache|:white_check_mark:|
|anticomp|:white_check_mark:|
|body_size_limit|:white_check_mark:|
|cadir|:grey_question:|
|ciphers_client|:grey_question:|
|ciphers_server|:grey_question:|
|client_certs|:grey_question:|file related, maybe need to switch to file selector input|
|client_replay|:grey_question:|file related, maybe need to switch to file selector input|
|console_focus_follow|:x:|no use in mitmweb|
|console_layout|:x:|no use in mitmweb|
|console_layout_headers|:x:|no use in mitmweb|
|console_mouse|:x:|no use in mitmweb|
|console_order|:x:|no use in mitmweb|
|console_order_reversed|:x:|no use in mitmweb|
|console_palette_transparent|:x:|no use in mitmweb|
|default_contentview|:x:|fail to update the value|
|flow_detail|:grey_question:|mitmdump related, maybe switch to choices option|
|http2|:white_check_mark:|
|http2_priority|:white_check_mark:|
|ignore_hosts|:white_check_mark:|
|intercept|:white_check_mark:|
|keep_host_header|:grey_question:|
|keepserving|:grey_question:|
|listen_host|:x:|live editing failed|
|listen_port|:x:|live editing failed|
|mode|:x:|live editing failed|
|onboarding|
|onboarding_host|:white_check_mark:|
|onboarding_port|:white_check_mark:|
|proxyauth|:grey_question:|not fully tested|
|rawtcp|:white_check_mark:|to be tested|
|refresh_server_playback|:grey_question:|to be tested|
|replacements|:white_check_mark:|
|replay_kill_extra|:grey_question:|to be tested|
|rfile|:grey_question:|file related, maybe switch to choices option|
|save_stream_file|:grey_question:|file related, maybe switch to choices option|
|save_stream_filter|:grey_question:|to be tested|
|scripts|:grey_question:|file related, maybe switch to choices option|
|server|:x:|live editing failed|
|server_replay|:grey_question:|file related, maybe switch to choices option|
|server_replay_ignore_content|:grey_question:|to be tested|
|server_replay_ignore_host|:grey_question:|to be tested|
|server_replay_ignore_payload_params|:grey_question:|to be tested|
|server_replay_nopop|:grey_question:|to be tested|
|server_replay_use_headers|:grey_question:|to be tested|
|####|####|####|
|setheaders|:grey_question:|to be tested|
|showhost|:grey_question:|to be tested|
|spoof_source_address|:grey_question:|to be tested|
|ssl_insecure|:grey_question:|to be tested|
|ssl_verify_upstream_trusted_ca|:grey_question:|to be tested|
|ssl_verify_upstream_trusted_cadir|:grey_question:|to be tested|
|ssl_verify_version_client|:grey_question:|to be tested|
|stickyauth|:grey_question:|to be tested|
|stickycookie|:grey_question:|to be tested|
|stream_large_bodies|:grey_question:|to be tested|
|stream_websockets|:grey_question:|to be tested|
|tcp_hosts|:grey_question:|to be tested|
|upstream_auth|:grey_question:|to be tested|
|upstream_bind_address|:grey_question:|to be tested|
|upstream_cert|:grey_question:|to be tested|
|verbosity|:grey_question:|to be tested|
|view_filter|:grey_question:|to be tested|
|web_debug|:grey_question:|to be tested|
|web_iface|:grey_question:|to be tested|
|web_open_browser|:grey_question:|to be tested|
|web_port|:grey_question:|to be tested|:grey_question:|to be tested|
|websocket|

**Comment by mhils** [comment]
OK, let's make this a bit more tangible and break it into actionable tasks. I'll open new issues for each one and link them here.

**Comment by mhils** [comment]
We should also check how we make the change to options transparent to existing users, see #2457.

**Comment by cortesi** [comment]
Is there anything actionable in this ticket that is still an aim for 3.0?
