### ISSUE TITLE
The mitmproxy crashes with mouse handling on!

### ISSUE THREAD

**Issue by amit-gshe** [mitmproxy/mitmproxy#2446]
Hi all, the mitmproxy crashed when started it on my archlinux system and it details as follow:
```
$ mitmproxy 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy/tools/console/master.py", line 281, in run
    self.loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.6/site-packages/urwid/main_loop.py", line 703, in _loop
    ready, w, err = select.select(fds, [], fds, timeout)
OSError: [Errno 9] Bad file descriptor

mitmproxy has crashed!
Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy
Shutting down...
```

##### Any other comments? What have you tried so far?
The mitmweb works well

##### System information

```
$ mitmproxy --version
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.1
Platform: Linux-4.11.9-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: arch
```

Please let me know how to provide more details. Thanks.

**Comment by mhils** [comment]
No idea what could be causing this - is this happening every time you start mitmproxy? Are you using a full interactive terminal?

**Comment by ritiek** [comment]
Not sure either but `pip3 install -U urwid` could help.

**Comment by amit-gshe** [comment]
@mhils Yes, it happens each time when I run mitmproxy. I tried in xfce4-terminal and deepin-terminal but no luck.

**Comment by amit-gshe** [comment]
Hi, It seems that the mouse handling cause this issue. The mitmproxy starts up normally with the `--no-mouse` option.

**Comment by mhils** [comment]
@amit-gshe: Thanks for tracking this down! All we do with `--no-mouse` is pass it down to urwid [here](https://github.com/mitmproxy/mitmproxy/blob/309274689c3d2eb910b368218706cecbfcc11044/mitmproxy/tools/console/master.py#L191). As this doesn't seem to be a bug in mitmproxy itself, could you maybe try to come up with a minimal urwid example and report this upstream?

**Comment by mhils** [comment]
Closing this here as this is an upstream bug - there's nothing actionable for us.
