### ISSUE TITLE
Options: Distinguish between user-set value and default.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2450]
It would be very useful to distinguish between options that have been explicitly set by a user and options with default values. For example, Firefox's about:config prints all user-set options bold:

![image](https://user-images.githubusercontent.com/1019198/28370871-bef202c4-6c9b-11e7-87d9-304a8a34e2f3.png)

This distinction is useful so that we can offer a save button in mitmweb, that saves all user-set options into a config file on disk. 

Steps:

 - [x] See how we can distinguish default from user-set options. Is it just enough to compare `.default` to `.value` or something like this?
 - [x] Indicate state in mitmproxy
 - [x] Indicate state in mitmweb
 - [x] Offer save button?

**Comment by ujjwal96** [comment]
This is already done in mitmproxy. User set options are shown in a different color

**Comment by MatthewShao** [comment]
I'm working on the mitmweb part, basically just compare `.default` and `.value`, maybe adding some judgement about the special cases.
