### ISSUE TITLE
Options: Check that all options work.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2451]
There are currently a bunch of options that don't really work when edited while mitmproxy is running. We should go through the list, briefly (!) check which ones are working, and then work on fixing the broken ones.

- [x] Move @MatthewShao's excellent table in #2444 to a Google Docs/Sheets (or similar) document that allows concurrent edits and post the URL here.
- [ ] Split options into "verified working", "to be tested", "broken/needs improvement". This should be a group effort - we just need to very briefly check if an option does anything at all. This is also a great way to learn about all the options and improve docstrings where it seems useful 😃 
- [ ] Fix the easily fixable options, discuss the not-so-easy ones. For example, `cadir` is a bit tricky for the reasons mentioned in https://github.com/mitmproxy/mitmproxy/issues/2444#issue-243549323. One way here would be to change the directory immediately, but only create CA files on startup.

**Comment by bwiyy** [comment]
Put @MatthewShao's excellent table into a Google Sheet [here](https://docs.google.com/spreadsheets/d/1DG0tCBjL1OJl9KPB_qt5y34htSaEEv9iI8yhfQJfacU/edit?usp=sharing).

**Comment by mhils** [comment]
thanks, @bwiyy! @MatthewShao: I'm not sure how much testing you did already, can you please move the options you are sure about into the working/broken categories and let us know here one that's done? 😃
