### ISSUE TITLE
raceback

### ISSUE THREAD

**Issue by stempelo** [mitmproxy/mitmproxy#2453]
##### Steps to reproduce the problem:

Mitmproxy set with
./mitmproxy -U http://AAAA.XXXX.it:82 -p 82

raceback (most recent call last):
  File "mitmproxy/net/tcp.py", line 190, in write
   GET http://XXXXXXXXXXXXXXX.trendmicro.com/T/128/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       ← 200 text/html 156b 147ms
   HEAD http://XXXXXXX.XXXXXXXXXX.it/OAB/XXXXXXXXXXXXXX477e-b272-0f36bb61aa01/oab.xml
        ← 503 text/html [no content] 158ms
Traceback (most recent call last):

  File "mitmproxy/proxy/modes/http_proxy.py", line 23, in __call__

##### Any other comments? What have you tried so far?
Mitm continues to work, not crash

##### System information

Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-4.8.0-58-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian stretch/sid

**Comment by mhils** [comment]
Please post a full traceback.

**Comment by stempelo** [comment]
I was using tmux, not everything was printed. Next time I will use stderr on log files. Thanks.
