### ISSUE TITLE
SSL cert not working for IE8 on windows XP

### ISSUE THREAD

**Issue by mbande** [mitmproxy/mitmproxy#2461]
I installed the p12 cert to a windows XP virtual machine, but unfortunately https sites are not working
this is very strange, as mitmproxy is installed in Trusted Root CAs, but browser complains about the issuer.
I wonder if it's related to windows XP only, or all versions of windows are affected.
under my linux box, everything is ok.

**Comment by mhils** [comment]
Which browser? Is there anything in the mitmproxy event log?

**Comment by mbande** [comment]
@mhils i've tried IE7/8 and Firefox
and noting is logged in mitmproxy, as the browser do not trust the certificate

**Comment by mhils** [comment]
What's the contents of your mitmproxy event log (press e to open it)?

**Comment by mbande** [comment]
`192.168.1.40:35312: clientconnect`
`192.168.1.40:35312: clientdisconnect`

**Comment by mhils** [comment]
There clearly must be a message indicating some form of error if your browser complains?

**Comment by mbande** [comment]
IFAIK the browser initially gets the SSL cert of server, and if it can not trust the cert issuer, it makes no further request, and just informs the user that it does not know the issuer without any error logging server side.

**Comment by mhils** [comment]
Yes, but we usually show this in the event log, for example like this:
```
λ mitmdump
Proxy server listening at http://[::]:8080
127.0.0.1:53386: clientconnect
127.0.0.1:53386: CONNECT example.com:443
 << Cannot establish TLS with client (sni: example.com): TlsException('',)
127.0.0.1:53386: clientdisconnect
```

We need your mitmproxy version and a more detailed description of what kind of error you are actually seeing.

**Comment by mbande** [comment]
I'm using mitmproxy version 2.0.2, and i installed the p12 cert successfully in windows as Root CA.
the only error that Firefox throws is error code: `SEC_ERROR_UNKNOWN_ISSUER`

**Comment by mhils** [comment]
Well that's something to work with at least. 😉 
Firefox maintains its own store of trusted CAs. You need to add mitmproxy to that. The simplest way to accomplish that is to navigate to mitm.it and click on "Other".

**Comment by mbande** [comment]
Thank you @mhils , you solved the Firefox error.
Unfotunately, the main issue is with IE, as i have to proxy it via mitm
i started struggling with firefox as at least it shows some error, IE just says "Internet Explorer can not display the web page"!

**Comment by mbande** [comment]
I also tried the "Other" cert with no success

**Comment by Kriechi** [comment]
Wild guessing here:
IE8 for XP supports SNI?
Are our DH-params "short enough" to work on such an old system?
4096-bit RSA supported?

**Comment by mhils** [comment]
Again, there definitely should be a message in the event log between `clientconnect` and `clientdisconnect` if you run `mitmdump -vvv`. That would help greatly with finding the actual root cause.

**Comment by mbande** [comment]
just worked for windows vista with the same IE 8

**Comment by ickromwerk** [comment]
I'm trying to use mitmproxy with Internet Explorer 6.0 from Windows XP. HTTP requests work well, HTTPS not.

I'm installed root certificate and enabled TLS1.0 in internet explorer settings. Got this in mitmdump:
`
172.16.16.178:40836: clientconnect
 << Bad HTTP request line: b'\x80L\x01\x03\x01\x003\x00\x00\x00\x10\x00\x00\x04\x00\x00\x05\x00\x00'
::ffff:172.16.16.178:40836: request
  -> HTTP protocol error in client request: Bad HTTP request line: b'\x80L\x01\x03\x01\x003\x00\x00\x00\x10\x00\x00\x04\x00\x00\x05\x00\x00'
172.16.16.178:40836: clientdisconnect
`

mitmproxy version:
`
Mitmproxy: 6.0.2
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.10.12-gentoo-x86_64-Intel-R-_Core-TM-_i5-2300_CPU_@_2.80GHz-with-glibc2.3
`

Sorry for necropost
