### ISSUE TITLE
Postpone establishing connection with server

### ISSUE THREAD

**Issue by mengbiping** [mitmproxy/mitmproxy#2464]
Hi, I use mitmproxy in upstream mode as a flow replayer by loading a couple scripts and resource files. It's never intended to deliver a request to remote server. Everything is ok except that, although each of the canned responses (loaded from a file on the disk) is correctly returned to the client, it actually makes connection to remote server on each of the flow via the upstream proxy server I configured in the cmd line, which is totally unnecessary and time-wasting in my senario. 
Would it be possible to postpone the establishing of connection with server (after the request() hook has been revoked) so that my upstream mitmproxy server can run with a dummy -U flag, which don't have to be a real proxy server at all, as it never should really forward a request/establish a connection to remote server?

**Comment by mhils** [comment]
Thanks for raising this. As you never intend to send a request upstream, have you tried just using mitmproxy in regular mode instead? That should give you the desired behaviour.

In any case, we need to make the strategy for upstream connections user-decidable. I tracked this in #1775.

**Comment by mengbiping** [comment]
Interesting, yes, as you suggested, it works in regular mode, even if machine the mitmproxy resides on does not have internet connection at all.

However, most of my other client apps would require features of upstream forwarding. Would it be possible for me to server both client apps with one single mitmproxy instance (as they require shared features that are implemented as inline scripts already)?

**Comment by mhils** [comment]
I'm not sure if I get your question correctly. You can only run one proxy mode at the same time. If you need to mitmproxy instances, I would suggest to just run them on different ports.

**Comment by mengbiping** [comment]
Hi @mhils, I send a pull request https://github.com/mitmproxy/mitmproxy/pull/2473, which seems to solve my problem. Would you please take a look?

With the patch, my instance of mitmproxy will not send connect request to remote server upon CONNECT request, as long as I implement in inline script:

```
from mitmproxy.http import make_connect_response
def http_connect(flow):
  if flow.request.method == 'CONNECT':
    flow.response = make_connect_response(flow.request.http_version)
```
