### ISSUE TITLE
Export flow as python code

### ISSUE THREAD

**Issue by ritiek** [mitmproxy/mitmproxy#2465]
AFAIK, there used to be this feature for exporting flow as python code using `requests`. I can't seem to find it now. I could only see options to export as `curl` or `raw` after pressing <kbd>e</kbd>. Did something happen to it or am I missing something?

##### System information

> Mitmproxy version: 3.0.0 (release version) 
Python version: 3.5.3
Platform: Linux-4.10.0-28-generic-x86_64-with-Ubuntu-17.04-zesty
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 17.04 zesty

**Comment by mhils** [comment]
See https://github.com/mitmproxy/mitmproxy/commit/bcbe87bb0986819c83c3e2efc683194bbf9c6c50.

**Comment by ritiek** [comment]
Oh, I see. What about using an external library like [uncurl](https://github.com/spulec/uncurl). Although it is not being maintained anymore..

**Comment by mhils** [comment]
I'm sorry, but we're not going to add additional dependencies for this. That's decidedly too much maintenance.

**Comment by ritiek** [comment]
Okay, no problem. Thanks anyway. :smile:

**Comment by ritiek** [comment]
Just in case somebody misses it like me, 6378b9c804d010802c276f74a5e606c732abe793 is an ugly unoptimized implementation.
