### ISSUE TITLE
Transitive import of mitmproxy.version causes warning

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#2470]
Since #1837, we import `.script`, will imports `.flow`, which imports `.version`.
This causes the following warning in pytest:

```
test/mitmproxy/test_version.py::test_version
  /Users/kriechi/.pyenv/versions/3.5.3/lib/python3.5/runpy.py:125: 
RuntimeWarning: 'mitmproxy.version' found in sys.modules after import of package 
'mitmproxy', but prior to execution of 'mitmproxy.version'; this may result in 
unpredictable behaviour
    warn(RuntimeWarning(msg))

-- Docs: http://doc.pytest.org/en/latest/warnings.html
```

[Note](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-double-import-trap)
> This next trap exists in all current versions of Python, including 3.3, and can be summed up in the following general guideline: “Never add a package directory, or any directory inside a package, directly to the Python path”.

> The reason this is problematic is that every module in that directory is now potentially accessible under two different names: as a top level module (since the directory is on sys.path) and as a submodule of the package (if the higher level directory containing the package itself is also on sys.path).

Maybe using the approach described [here](https://stackoverflow.com/questions/27947639/how-to-properly-create-a-pyinstaller-hook-or-maybe-hidden-import) works better?

**Comment by mhils** [comment]
To be honest I do not quite understand what the actual issue is? Is it the import?

**Comment by Kriechi** [comment]
Not sure myself, but I think the fact that `mitmproxy.version` is available (imported) BEFORE actually being imported is not "good".

**Comment by mhils** [comment]
Maybe this is related to https://github.com/mitmproxy/mitmproxy/blob/aa8969b240310f265640c92e14a4b7d6363e464b/setup.py#L15? Someone needs to remove this and see if CI still complains. If not, we should replace it with something like this: https://github.com/ffalcinelli/pydivert/blob/724bfdc0554ed6fe966eedda3b74197519526cd4/setup.py#L26-L28

**Comment by Kriechi** [comment]
Unfortunately the `RuntimeWarning` is still there.

**Comment by mhils** [comment]
Ah, now it's caused by the test_version execution test. Much easier to fix. :)
