### ISSUE TITLE
[Helper] copy paste ruestion.  not bug

### ISSUE THREAD

**Issue by hhhaiai** [mitmproxy/mitmproxy#2472]
env:
  mac os all version
copy need Fn+mouse left. what need I doing if Iwant modify.

**Comment by hhhaiai** [comment]
new est lib not support python2.7.    only modify pip3 ++>pip ,can work ?

**Comment by mhils** [comment]
Sorry, but I do not understand what your question is.

**Comment by hhhaiai** [comment]
I want modify  copy word  from  mitm .    On macOS  the keymap this Fn+mouse left.  I want modify . what can I do?

**Comment by hhhaiai** [comment]
update keymap

**Comment by hhhaiai** [comment]
@mhils
