### ISSUE TITLE
xss_scanner.py issue

### ISSUE THREAD

**Issue by mojtabamarashee** [mitmproxy/mitmproxy#2477]
hi
in the function test_query_injection the body is converted to lower case (line 153) but in the get_SQLi_data function it is compared with upper case words (line 187) that results in no match

**Comment by mhils** [comment]
Thanks for the report! Would you mind sending a pull request that fixes this? 😃

**Comment by mojtabamarashee** [comment]
sure, also there are issuse with "decode" in log_SQLi_data function(line 176-179) that causes to error.
Im working on a new sqli example that also test post data for sqli and save vulnerable hosts to file.

**Comment by surajt97** [comment]
@mhils can I submit a PR to fix this issue?

**Comment by mhils** [comment]
@surajt97: yes, please!
