### ISSUE TITLE
How to run mitmproxy source code on Windows 7 machine?

### ISSUE THREAD

**Issue by abhineetagarwal** [mitmproxy/mitmproxy#2479]
If anyone can help me with the dependency & steps involved for building the mitmproxy source code on Windows 7 platform.

I have pulled the mitmproxy source code from the below location.
https://github.com/mitmproxy/mitmproxy

**Comment by mhils** [comment]
Please take a look at http://docs.mitmproxy.org/en/stable/install.html.
