### ISSUE TITLE
cannot intercept insatgram's traffic

### ISSUE THREAD

**Issue by wejdan** [mitmproxy/mitmproxy#2486]
I cannot intercept instagram ver 10.31.0 traffic on android .
1-i used arpspoof to redirect android traffic to my laptop
2-i installed mitmproxy certificate in android
3-i can see all the traffic comming from all the other apps 
I know  instagram uses ssl pinning.but the wired thing is the app work just fine and it is connected to the Internet.it as if mitmproxy ignore traffic comming from instagram?

**Comment by mhils** [comment]
> if mitmproxy ignore traffic comming from instagram?

No. We definitely do attempt to intercept any connection that reaches mitmproxy, unless you specify `--ignore`. In summary, this is not a mitmproxy issue.
