### ISSUE TITLE
More flexible pathoc 

### ISSUE THREAD

**Issue by mkagenius** [mitmproxy/mitmproxy#2497]
**Current pathoc do not support:**
1. Method does not allow random text, currently restricted to `GET`, `POST`, `HEAD` and a few more. But can't pass anything else like `HELP`. 
2.  Path does not allow random text, it must start with `/` . We can't pass `@somedomain.com` as path.

Considering pathoc to be really powerful lower level API to play with HTTP, we can probably allow random texts for those two (method and path).

------

In my dev environment, I created a new `pathoc_expr()` in place of `expr()` and got it to accept a random method `HELP` (or any other text):

```
(venv) mitmproxy manish $ pathoc -s google.com HELP:/ -q -p
>> HELP:/
<< 405 Method Not Allowed: 1589 bytes
Bytes written:
       	HELP / HTTP/1.1
       	Host: google.com


Bytes read:
       	HTTP/1.1 405 Method Not Allowed
       	Content-Type: text/html; charset=UTF-8
       	Referrer-Policy: no-referrer
       	Content-Length: 1589
       	Date: Thu, 03 Aug 2017 12:51:25 GMT
       	Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"

       	<!DOCTYPE html>
       	<html lang=en>
       	  <meta charset=utf-8>
``` 

**I think there should be a cleaner way than adding pathoc_expr() **

changes below

```
    @classmethod
    def pathoc_expr(cls):
        parts = [i.expr() for i in cls.comps]
        atom = pp.MatchFirst(parts)
        resp = pp.And(
            [
                pp.MatchFirst(
                    [
                        WS.expr() + pp.Optional(
                            base.Sep + Method.expr()
                        ),
                        RawMethod.expr(),
                    ]
                ),
                base.Sep,
                Path.expr(),
                pp.ZeroOrMore(base.Sep + atom)
            ]
        )
        resp = resp.setParseAction(cls)
        return resp
```

```
class RawMethod(base.Value):
    pass
```

```
    @property
    def method(self):
        return self.tok(RawMethod)
```

**Comment by Kriechi** [comment]
Closing, as pathod and pathoc command line tools and their libraries inside mitmproxy are deprecated. See #4273.
