### ISSUE TITLE
Options: Provide good upgrade experience from 2.0.x

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2498]
##### Steps to reproduce the problem:

1. Existing mitmproxy users updates to 3.0 once it is released.
2. User invokes `mitmproxy -R http://example.com`
3. Mitmproxy returns cryptic "Invalid replacement specifier:" error.

##### Any other comments? What have you tried so far?

The changes to the CLI in 3.0 are quite big, so we should try to provide a somewhat reasonable migration experience for existing users. As I see it, it would make sense to have a very dirty function that checks `argv` for common migration errors. We should at least provide useful hints for the following issues:

- [x] `-T`
- [x] `-R` (now repurposed, remove that?)
- [x] `-U` 
- [x] `--http2` / `--no-http2` (#2500)

Again, implementation of this can be dirty, it's just useful to have for a while to ease migration.

**Comment by ujjwal96** [comment]
Options which mean a different thing in 3.0
----
- R (reverse mode) -> R (replacements)
- k (replay-kill-extra) -> k (ssl-insecure)

Options which are removed - 
----
- cadir
- Z, body-size-limit
- stream
- palette
- palette-transparent
- e, eventlog
- follow
- order
- no-mouse
- reverse
- socks
- http2-priority
- np-http2-priority
- no-websocket
- websocket
- spoof-source-address
- upstream-bind-address
- ciphers-client 
- ciphers-server
- client-certs 
- no-upstream-cert
- add-upstream-certs-to-client-chain
- upstream-trusted-cadir
- upstream-trusted-ca
- ssl-version-client
- ssl-version-server
- no-onboarding
- onboarding-host
- onboarding-port
- server-replay-use-header
- norefresh
- no-pop
- replay-ignore-content
- replay-ignore-payload-param
- replay-ignore-param
- replay-ignore-host
- replace-from-file
- nonanonymous
- singleuser
- htpasswd

Options that are invoked differently -
----
- t -> stickycookie
- u -> stickyauth
- wfile -> save-stream-file
- a, afile -> Use -w and prefix path with + to append
- z -> anticomp
- T -> m transparent
- U -> m upstream:SPEC
- b, bind-address -> listen-host
- port -> listen-port
- I, ignore -> ignore-hosts
- tcp -> tcp-hosts
- cert -> certs
- insecure -> ssl-insecure, k
- c -> C (client-replay)
- replace -> replacements
- i -> intercept
- f, filter -> view-filter

**Comment by ujjwal96** [comment]
Posting this here as it may help with new documentation for 3.0

**Comment by mhils** [comment]
Fixed by #2503! 😃
