### ISSUE TITLE
304 [no content] on HTTP GET request (mitmproxy)

### ISSUE THREAD

**Issue by nesttle** [mitmproxy/mitmproxy#2506]
##### Steps to reproduce the problem:

1. Visit any url with image inside or visit direct url image (i.e. http://i.imgur.com/rXodcGj.jpg)
2. mimtproxy shows response code 304 [no content] randomly
3. HTTP or HTTPS, same behavior (so it's not related to SSL Pinning)
4. Image loads for **200** response code, also for **304** response code

##### Any other comments? What have you tried so far?
`mitmproxy -p 1111 -U http://user:pass@x.x.x.x:8080 -s myscripttosaveimages.py`

##### System information

```
Python version: 3.5.1
Platform: Linux-4.9.35-v7+-armv7l-with-debian-8.0
SSL version: OpenSSL 1.0.1t  3 May 2016
Linux distro: debian 8.0 
```

##### mitmproxy debug/log
![image](https://user-images.githubusercontent.com/4428341/29029593-7873219c-7b88-11e7-8eb7-46f8154d9be4.png)

**Comment by mhils** [comment]
See https://httpstatuses.com/304 - your client has that image already cached, so the server is not resending it. You can have mitmproxy strip the caching header in the request by enabling it's anticache option! 😃
