### ISSUE TITLE
openSLL proxy certificate confusing mitmproxy

### ISSUE THREAD

**Issue by jtchilders** [mitmproxy/mitmproxy#2507]
Hello,
Obviously, I cannot give you my certificate to create your own proxy certificate to test this failure, which probably makes things hard, but I'll submit this for your consideration. Perhaps I'm just misusing the tool somehow.

##### Steps to reproduce the problem:

1. Create an SSL proxy certificate
2. Run a curl using the following arguments
> curl --silent --show-error --connect-timeout 100 --max-time 120 --compressed --capath ./certificates --cert myproxy  --cacert myproxy --key myproxy --config data.txt https://yoursecureserver.com:port/path/command
3. receive error:
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

##### Any other comments? What have you tried so far?

Without the mitmproxy, this curl command works just fine with my server. 
I can get standard http calls without the proxy certificate to work.

##### System information
I've tested this on both my macbook and a linux cluster running RHEL6.5 with the same results. Both were using python3.5 and I used 'pip install --user git+git://github.com/mitmproxy/mitmproxy.git' to install the software.

**Comment by mhils** [comment]
Do you want to use a custom certificate or a custom CA? You can use both with mitmproxy:
http://docs.mitmproxy.org/en/stable/certinstall.html#using-a-custom-certificate
http://docs.mitmproxy.org/en/stable/certinstall.html#using-a-custom-certificate-authority

**Comment by jtchilders** [comment]
Thank you for your quick response. 

I tried:
> mitmproxy --set cadir=./certificates and --cert=myproxy
but this gives the same error.

This has something to do with the certificate chain verification, which honestly I'm only vaguely familiar with its operation. 

The point is I have an X509 proxy certificate, which is created from my own X509 key/cert pair, which in turn is created from a custom Certificate Authority. I must pass curl the CA-directory, and my proxy is passed as the key, certificate, and cacert in order to authenticate. From what I understand, curl does its own authentication check for consistency before even trying to connect to the remote server which then does its own authentication. When I run without mitmproxy, this all works, however, when I use mitmproxy curl complains that I am using a self signed certificate.

Thanks for any help or debugging tips.

**Comment by jtchilders** [comment]
And just for clarity, I'm not trying to use mitmproxy to decrypt the data being passed through. I just need it to be a proxy.

**Comment by mhils** [comment]
> The point is I have an X509 proxy certificate, which is created from my own X509 key/cert pair, which in turn is created from a custom Certificate Authority.

General advice: You're usually best off to just use the mitmproxy-generated CA and make curl trust that one if you can. If you do need something custom, you have two options:

1. Passing a custom CA to mitmproxy. Mitmproxy will use this CA to sign automatically generated certificates that it creates to intercept connections.
2. Passing a custom certificate to mitmproxy. Mitmproxy will use the certificate as-is to intercept some connections, i.e. the client will see exactly that certificate and the information contained in it. If your certificate is the end of a chain of custom certificates CAs, you need to include these intermediary certs in your chain in the PEM file as described in http://docs.mitmproxy.org/en/stable/certinstall.html#using-a-custom-certificate.

If your client still complains, you either made an error generating your certificates or configuring your client/proxy. The error message makes it look like the former, but I'm not exactly sure.

> And just for clarity, I'm not trying to use mitmproxy to decrypt the data being passed through.

In this case you can probably also just use http://docs.mitmproxy.org/en/stable/features/passthrough.html.

**Comment by jtchilders** [comment]
Great, the passthrough was exactly what I needed! Thanks. That works.

**Comment by mhils** [comment]
Awesome, thanks!
