### ISSUE TITLE
Mitmdump doesn't recognize python script

### ISSUE THREAD

**Issue by juamc2503** [mitmproxy/mitmproxy#2515]
##### Steps to reproduce the problem:

1.i Have a script to send response to requests https via mitmdump in a digitalocean server.
2.i have created one in google cloud the same version of linux the same commands of imtallation but apparently the python scripts doesn't run on this server dont know why
3.
mitmdump --host -dd -s "./phone.py ALL" -w logfile.txt | grep "Tried to accept - code"

**Comment by Kriechi** [comment]
Which python version are you using?
Which mitmproxy version are you using?
How did you install mitmproxy?
Are you getting any error messages?

**Comment by juamc2503** [comment]
ubuntu@ip-172-31-29-186:~$ mitmproxy --version
Mitmproxy version: 2.0.2 (release version)
Python version: 3.5.2
Platform: Linux-4.4.0-1028-aws-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
ubuntu@ip-172-31-29-186:~$

Running in aws also the same it doesnt show anything. 
If i use mitmdump --host i can see the request but apparently aren't been read by the py script

**Comment by Kriechi** [comment]
Please show us you script.

**Comment by juamc2503** [comment]
I figured out guys. 

S
To install and run everything in the root user

Sudo su
Then install everything
Aparently the user that comes with google cloud and aws has no enough privileges
