### ISSUE TITLE
ImportError: dlopen failed: cannot locate symbol "log2"

### ISSUE THREAD

**Issue by Deathlive** [mitmproxy/mitmproxy#2516]
I install mitmproxy in Termux(emulator of android).
`pip3 install mitmproxy`

```
File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/brotli/brotli.py", line 5, in <module>
   from  ._brotli import ffi, lib
ImportError: dlopen failed: cannot locate symbol "log2" referenced by "_brotli.abi3.so" ...
```

I install  `pip3 install brotli`.

**Comment by Kriechi** [comment]
Please uninstall `brotli` as mitmproxy depends on `brotlipy`, which should be installed automatically by pip when installing mitmproxy.

If you still have problems, please open an issue with brotliby here: https://github.com/python-hyper/brotlipy
