### ISSUE TITLE
How to Show local IP in console view?

### ISSUE THREAD

**Issue by hhhaiai** [mitmproxy/mitmproxy#2523]
![image](https://user-images.githubusercontent.com/5738285/29313662-d048e148-81ed-11e7-9ada-cb463137b5f0.png)
这里的*想改成本地IP
Want to change * here to the local IP, what should I do?

**Comment by hhhaiai** [comment]
你可以用英文回答,我的英文不太好,描述不清楚

**Comment by MatthewShao** [comment]
Use `--listen-host` options, like `mitmproxy --listen-host 127.0.0.1`, empty string or `0.0.0.0` will be change to `*` here.
> In Chinese: 
   用`--listen-host` 即可, 用命令行如`mitmproxy --listen-host 127.0.0.1`即可换掉`*`

**Comment by hhhaiai** [comment]
default io is 0.0.0.0?

**Comment by MatthewShao** [comment]
The default value of `--listen-host` is empty string `''`, so it will be replaced to `*`, if you use `--listen-host 0.0.0.0`, it will display `*` too.
