### ISSUE TITLE
TypeError: response() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by nesttle** [mitmproxy/mitmproxy#2524]
Similar related issue: #167 

##### Steps to reproduce the problem:

1. `-s script.py`

##### System information

```
Installing collected packages: mitmproxy, netlib
Successfully installed mitmproxy-2.0.2 netlib-0.17

root@mitm:~# mitmproxy --version
mitmproxy 0.15
```

Unknown issue here with mitmproxy 2.0.2 and `-s script.py ` argument:

```
Script error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libmproxy/script/script.py", line 93, in run
    return f(self.ctx, *args, **kwargs)
TypeError: request() takes exactly 1 argument (2 given)

Script error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libmproxy/script/script.py", line 93, in run
    return f(self.ctx, *args, **kwargs)
TypeError: response() takes exactly 1 argument (2 given)
```

netlib-0.17

script.py example
```
import io
import re
import requests
import time

def request(flow):
   #ok
def response(flow):
   #ok
```

Working nice on local! But fails on Debian server.
(Sorry if duplicated)

**Comment by nesttle** [comment]
On local server:
`mitmproxy --version `

```
root@local:~# mitmproxy --version
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.1
Platform: Linux-4.9.35-v7+-armv7l-with-debian-8.0
SSL version: OpenSSL 1.0.1t  3 May 2016
Linux distro: debian 8.0 
```

**Comment by nesttle** [comment]
Looks like there is some issue with mitmproxy version from apt. I'm trying now with pre-compiled version of mitmproxy 2.0.2 `--version`:
```
root@mitm:~# ./mitmproxy --version
Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.2
Platform: Linux-4.4.0-87-generic-x86_64-with-debian-stretch-sid
SSL version: OpenSSL 1.1.0e  16 Feb 2017
Linux distro: debian stretch/sid 
```

./mitmproxy -p 8080 -s script.py 
```
Event log
Loading script: script.py
Script error: Traceback (most recent call last):
  File "script.py", line 4, in <module>
    import requests
ImportError: No module named 'requests'
```

**Comment by mhils** [comment]
Hi,

For the majority of our users we recommend the precompiled binaries. If you are writing scripts with external imports (such as `requests` in your case), you however have to install from source: http://docs.mitmproxy.org/en/stable/install.html#advanced-installation

Regarding your original issue: This looks like an outdated version of mitmproxy.

**Comment by nesttle** [comment]
Thanks Max @mhils 
Will try with a fresh version of system (looks like a problem with repos or outdated version of something) since I neved faced this issue before with mitm
