### ISSUE TITLE
MITM Proxy stops working after connecting to VPN

### ISSUE THREAD

**Issue by ldelossa** [mitmproxy/mitmproxy#2528]
##### Steps to reproduce the problem:

1. Connect to vpn (this is palo alot)

##### Any other comments? What have you tried so far?
Sorry that this is not an issue with mitmproxy per say, but I could use a little help. When I connect to my corporate VPN mitm-proxy stops intercepting traffic. I understand that when I connect to my corporate VPN my internal routing table on my workstation changes, and the default gateway may change also. However what I can't understand is that my (osx) system proxy settings are still sending everything to localhost:8080 where mitm proxy is still listening. I see no requests making it's way through it. I tried googling OSX related articles, but no luck. Making this ticket as last ditch effort.

**Comment by mhils** [comment]
Hi @ldelossa,

Just to clarify - you have mitmproxy running on your mac OS machine, and you are trying to proxy traffic through mitmproxy while being connected to a VPN? Does `curl -x 127.0.0.1:8080 example.com` work?

**Comment by ldelossa** [comment]
Hello @mhils 

That is correct. And doing the curl -x directly to localhost 8080 does in fact send that request through mitm proxy. 

```
>> GET http://example.com/
       ← 200 text/html 1.24k 385ms
```

However it seems like the rest of the OS that STILL has the proxy settings in network configuration (osx) enabled no longer sends through the proxy.

**Comment by mhils** [comment]
Which OSX version is that? @Kriechi, can you reproduce this?

**Comment by ldelossa** [comment]
mac OS Seirra 
10.12.6

my specific VPN is "Global Connect" which is Palo Alto. Trying to determine if we do split DNS or we send all DNS requests over the proxy also.

**Comment by ldelossa** [comment]
Good suggestion, let me try this.

**Comment by ldelossa** [comment]
@mhils Didn't fix the issue.

**Comment by ldelossa** [comment]
My traceroute to google.com looks the same with VPN on (first one) and VPN off (second one) so I don't believe non-company DNS lookups are going over the tunnel. 

```
~
❯ traceroute google.com
traceroute to google.com (172.217.9.238), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  1.098 ms  1.080 ms  2.130 ms
 2  192.168.0.1 (192.168.0.1)  7.482 ms  9.811 ms  9.288 ms
 3  * * *
 4  be57.nycvnyjj01h.nyc.rr.com (68.173.202.52)  29.627 ms  29.946 ms  29.604 ms
 5  agg110.nyclnyrg01r.nyc.rr.com (68.173.198.112)  39.555 ms  39.316 ms  31.975 ms
 6  bu-ether19.nwrknjmd67w-bcr00.tbone.rr.com (66.109.6.78)  28.688 ms  32.990 ms  36.411 ms
 7  bu-ether12.nycmny837aw-bcr00.tbone.rr.com (66.109.6.27)  30.155 ms  20.007 ms  29.933 ms
 8  0.ae0.pr0.nyc20.tbone.rr.com (66.109.6.157)  22.929 ms
    0.ae1.pr0.nyc20.tbone.rr.com (66.109.6.163)  27.279 ms
    0.ae4.pr0.nyc20.tbone.rr.com (66.109.1.35)  31.951 ms
 9  ix-ae-10-0.tcore1.n75-new-york.as6453.net (66.110.96.13)  22.214 ms
    ix-ae-6-0.tcore1.n75-new-york.as6453.net (66.110.96.53)  28.762 ms
    ix-ae-10-0.tcore1.n75-new-york.as6453.net (66.110.96.13)  66.635 ms
10  72.14.195.232 (72.14.195.232)  27.817 ms  28.902 ms  32.002 ms
11  108.170.248.97 (108.170.248.97)  28.275 ms  27.775 ms
    108.170.248.33 (108.170.248.33)  95.337 ms
12  216.239.62.21 (216.239.62.21)  27.475 ms  23.473 ms
    216.239.62.147 (216.239.62.147)  29.991 ms
13  lga34s11-in-f14.1e100.net (172.217.9.238)  25.134 ms  48.758 ms  24.375 ms

~ 17s
❯ traceroute google.com
traceroute to google.com (172.217.12.174), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  1.396 ms  0.896 ms  0.798 ms
 2  192.168.0.1 (192.168.0.1)  7.657 ms  3.804 ms  9.679 ms
 3  * * *
 4  be57.nycvnyjj02h.nyc.rr.com (68.173.202.54)  34.765 ms  25.676 ms  30.067 ms
 5  agg110.nyquny9101r.nyc.rr.com (68.173.198.114)  40.001 ms  41.038 ms  28.563 ms
 6  66.109.3.220 (66.109.3.220)  31.349 ms  41.990 ms  27.624 ms
 7  0.ae4.pr0.nyc20.tbone.rr.com (66.109.1.35)  29.149 ms
    0.ae1.pr0.nyc20.tbone.rr.com (66.109.6.163)  19.004 ms
    0.ae2.pr0.nyc20.tbone.rr.com (107.14.19.147)  17.517 ms
 8  ix-ae-6-0.tcore1.n75-new-york.as6453.net (66.110.96.53)  32.143 ms
    ix-ae-10-0.tcore1.n75-new-york.as6453.net (66.110.96.13)  27.380 ms  29.932 ms
 9  72.14.195.232 (72.14.195.232)  20.611 ms  34.102 ms  22.865 ms
10  108.170.248.65 (108.170.248.65)  28.724 ms *  35.696 ms
11  108.170.226.199 (108.170.226.199)  23.493 ms  43.183 ms
    108.170.226.201 (108.170.226.201)  29.320 ms
12  lga25s62-in-f14.1e100.net (172.217.12.174)  18.642 ms  29.708 ms  30.682 ms
```

**Comment by mhils** [comment]
Sorry that this didn't help - I unfortunately have no further ideas. I'm closing this as it's not quite a mitmproxy bug, but we'd still be interested to hear if someone has a solution to this!

**Comment by luca-borrione** [comment]
The very same is happening to me as well:
$ mitmproxy --version
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.2
Platform: Darwin-15.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.11.6 ('', '', '') x86_64

VPN Pulse Secure

**I noticed that Firefox keeps on working, though.**
The other browsers (Safari, Chrome) relying on the system proxy don't.
Also in the event log opening Safari triggers:
HTTP protocol error in client request: Invalid HTTP request form (expected: relative, got: authority)

**Comment by luca-borrione** [comment]
I am facing the very same issue.

$ mitmproxy --version
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.2
Platform: Darwin-15.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.11.6 ('', '', '') x86_64

However I noticed that **Firefox (which has his own proxy settings) keeps on working:**
only the browsers such as Safari and Chrome that rely on the system proxy stop working.

I solved the issue for Chrome by installing the Proxy Switcher Extension and setting a manual proxy pointing to 127.0.0.1:8080
https://chrome.google.com/webstore/detail/proxy-switcher-manager/onnfghpihccifgojkpnnncpagjcdbjod?hl=en

I am not aware of any extension which can do something similar for Safari.
Thus the issue for Safari is still unsolved for me ...

Hope this helps

**Comment by mb-asapp** [comment]
Anyone could make this work outside chrome? I'm using `mitmproxy` in macOS and iOS Simulator and everything goes through the proxy correctly, until I connect to a VPN (using GlobalProtect client). From that moment on, traffic doesn't go through the proxy. I can even stop `mitmproxy` and things keep on working (while VPN turned on) so with this I confirm traffic isn't going through the proxy. I need to send traffic to the proxy even when connected to the VPN.

**Comment by murselsahin** [comment]
@mb-asapp can you fix it ? i have the same problem.

**Comment by csonuryilmaz** [comment]
@murselsahin @mb-asapp Same here 🙋

**Comment by satishVekariya** [comment]
Samer here

**Comment by baizhiren** [comment]
same here

**Comment by Profesor41** [comment]
Same here, I have a Global Protect VPN and I tried to catch the traffic from my phone, but when I start Global Protect on my phone the mitm not working

**Comment by ahmed-ebaid** [comment]
I’m using the GlobalProtect VPN as well and managed to capture traffic in mitmproxy by running the following command on my Mac:
`mitmproxy --mode local`

**Comment by dwiyatci** [comment]
> only the browsers such as Safari and Chrome that rely on the system proxy stop working.

@luca-borrione Thanks a lot for this clue! 🤩 I'm on GlobalProtect VPN and made it still working for Chrome with `mitmweb` and this underrated [Proxy Switcher](https://chromewebstore.google.com/detail/proxy-switcher/iejkjpdckomcjdhmkemlfdapjodcpgih) extension combo (the extension seems to be recently updated as of 2025: v0.1.9 - June 13, 2025).

<img width="3680" height="2212" alt="Image" src="https://github.com/user-attachments/assets/06fe811b-ca00-4011-a936-2f1e5147d2a5" />
