### ISSUE TITLE
Support CONNECT method for upstream proxy

### ISSUE THREAD

**Issue by splashx** [mitmproxy/mitmproxy#2532]
##### Steps to reproduce the problem:

1. Have a proxy in the environment which supports CONNECT method (this is the upstream proxy)
2. Run mitmproxy with `-U <proxy>:<port>`
3. Setup a iptables rule to forward any traffic locally generated to dst tcp/443 to mitmproxy `localhost:8080`

##### Any other comments? What have you tried so far?

This happens because mitmproxy tries to stablish an SSL connection with a proxy which doesn't support it. When sniffing a working ssl request in this environment (`https_proxy=http://10.17.70.70:3128 curl https://www.google.com`) the following is seen in tcpdump:
C->P: `CONNECT www.google.com:443`

I would suggest to add a flag to upstream to use CONNECT tunnel for ssl destinations (`-U proxy:port ---upstream-use-connect-ssl`). It should work like this (`C` = client, `M` = mitmproxy, `P` = upstream proxy, `S` = https server):
C: https://www.google.com
C->M: certificate presented by MITM, auto-generated, trusted
M->P: sends up `CONNECT www.google.com:443` (this is just a tcp connection, all the handshake will happen here)
P->S: blindly forwards the tcp connection request from `M` to `S`
M--viaP-->S: SSL handshake using the CONNECT tunnel (`P` from now on everything is encrypted to P, `P` can't read anything)

##### System information

```
# mitmdump -U 10.17.70.70:3128
mitmdump: Invalid server specification: 10.17.70.70:3128
root@cog:~# mitmdump -U http://10.17.70.70:3128
Proxy server listening at http://0.0.0.0:8080
100.127.169.165:56054: clientconnect
100.127.169.165:56054: Cannot establish TLS with 10.17.70.70:3128 (sni: www.google.com): TlsException("SSL handshake error: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'unknown protocol')],)",)
100.127.169.165:56054: clientdisconnect
100.127.169.165:56056: clientconnect
100.127.169.165:56056: Cannot establish TLS with 10.17.70.70:3128 (sni: www.google.com): TlsException("SSL handshake error: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'unknown protocol')],)",)
100.127.169.165:56056: clientdisconnect
```

**Comment by mhils** [comment]
To clarify, you want mitmproxy to run as a transparent proxy (you use iptables to redirect traffic to mitmproxy), but mitmproxy should redirect all requests to an upstream proxy? 
We do support CONNECTing upstream, but only if mitmproxy is configured to run as a regular proxy (i.e. no iptables). Would just using proxychains work for you?

**Comment by splashx** [comment]
Thanks for the quick reply @mhils.
In my environment there is a proxy and I'm using an app coded in erlang which doesn't support proxy. The erlang app won't proxychain (tried proxychains3 and proxychains4) - it simply doesn't work (36h on that spent). I threw all that away and now I just want to hardwire the box in a way it's totally transparent for all apps using `tcp/80` and `tcp/443` to go via a non-transparent proxy - I started with squid, it works fine for `tpc/80` but it won't work with ssl. So I instantly thought about mitmproxy - spinned it up and 👎  - didnt work because of the description above.

> To clarify, you want mitmproxy to run as a transparent proxy (you use iptables to redirect traffic to mitmproxy), but mitmproxy should redirect all requests to an upstream proxy?

Correct. Unfortunately I can't use non-transparent proxy (the app doesn't support it).

>We do support CONNECTing upstream, but only if mitmproxy is configured to run as a regular proxy (i.e. no iptables). Would just using proxychains work for you?

I would be great if that could be done also while using mitmproxy in upstream mode 🙏

**Comment by splashx** [comment]
I know this is not a squid place, but just to follow up on the previous message, it's possible to have squid do what it's being required without decrypting the traffic - e.g. without using mitmproxy. 
The snipped looks like this:

```
...
...
ssl_bump splice all
https_port 3129 ssl-bump intercept generate-host-certificates=on dynamic_cert_mem_cache_size=4MB cert=/etc/squid/ssl_cert/myca.pem
....
....
```

I'll leave it to @mhils to close the issue or not - based on dev priorities for mitmproxy project. 

Cheers

**Comment by mhils** [comment]
Thanks, @splashx!
I think that proxychains and redsocks cover the use case of transparently wrapping connections sufficiently, so this is not a priority for us. Glad you found a solution using squid!
