### ISSUE TITLE
How to modify the mitmproxy lib to fake ip header packets on windows?

### ISSUE THREAD

**Issue by henrymark92** [mitmproxy/mitmproxy#2538]
I want use mitmproxy to make ip flooding. How to modify the mitmproxy lib to fake ip header packets  on windows?
Thanks

**Comment by mhils** [comment]
Hi @henrymark92,

I think you are a bit confused about some networking fundamentals, you cannot spoof the source IP of TCP connections unless you are on the connection path. Take a look at http://intronetworks.cs.luc.edu/ or other online resources if you want to understand computer networking in general.

More generally: I have previously asked you to please not use our issue tracker for beginner questions, as project maintenance consumes a lot of our/my (free) time. If you intend to open issues in the future, please demonstrate that you have spend a nonnegligible amount of time trying to solve your problem yourself.
