### ISSUE TITLE
Handling arguments for mitmdump scripts

### ISSUE THREAD

**Issue by phros** [mitmproxy/mitmproxy#2541]
Hey, 

what is the current state of **Handling arguments**? The Readme states: FIXME. Is it currently possible to pass arguments to a python script for mitmdump?

Cheers

**Comment by mhils** [comment]
Are you talking about 2.0 or the current master branch? See https://github.com/mitmproxy/mitmproxy/blob/2.0.x/examples/simple/script_arguments.py for 2.0, and https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/custom_option.py for master. Now I'm only curious where you found that FIXME? 😉

**Comment by ujjwal96** [comment]
I'm guessing he's referring to [this](https://github.com/mitmproxy/mitmproxy/blob/aa0e1340417385302a8c6f5034f9151aadbc25b5/docs/scripting/overview.rst#handling-arguments)

**Comment by mhils** [comment]
Ah, yes. I only searched through our README files 😄. Thanks @ujjwal96!

**Comment by phros** [comment]
Yes, I am talking at the current master branch. @ujjwal96 found the correct position ;)
