### ISSUE TITLE
Add delete all buttons in mitmweb interface for flow modification

### ISSUE THREAD

**Issue by nmiculinic** [mitmproxy/mitmproxy#2546]
This is simple enhancement proposal I'd be thankful if implemented. I use mitmproxy in debugging my application, and it would be useful being able to clear all historic flow data in one button. 

Right now I'm even unable to select multiple flow items and batch delete them.

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.2
Platform: Linux-4.12.6-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: arch

**Comment by mhils** [comment]
Thanks for the feedback. You can currently click mitmproxy -> New. Is that what you are looking for? If so, we should probably look at making the interface more clear.

**Comment by nmiculinic** [comment]
Yes, I can, thank you. That's exactly I'm looking for; I just kinda assumed there would be some big red button clear all or something like it.

**Comment by fabienbk** [comment]
Thanks for this issue. I spammed the "d" key for waaay too long :)
