### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED]  with python requests library

### ISSUE THREAD

**Issue by nmiculinic** [mitmproxy/mitmproxy#2547]
##### Steps to reproduce the problem:
```python
import requests
import urllib.request
with urllib.request.urlopen('https://facebook.com/') as response:
    print(len(response.read()))
print(len(requests.get('https://facebook.com').text))
```

Without mitm proxy:
```
206541
206809
```

With mitm proxy:
```
206922
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, **response_kw)
    553             if is_new_proxy_conn:
--> 554                 self._prepare_proxy(conn)
    555 

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in _prepare_proxy(self, conn)
    749 
--> 750         conn.connect()
    751 

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/packages/urllib3/connection.py in connect(self)
    251                                     server_hostname=hostname,
--> 252                                     ssl_version=resolved_ssl_version)
    253 

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/packages/urllib3/util/ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir)
    304     if HAS_SNI:  # Platform-specific: OpenSSL with enabled SNI
--> 305         return context.wrap_socket(sock, server_hostname=server_hostname)
    306 

/usr/lib/python3.6/ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname, session)
    400                          server_hostname=server_hostname,
--> 401                          _context=self, _session=session)
    402 

/usr/lib/python3.6/ssl.py in __init__(self, sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, family, type, proto, fileno, suppress_ragged_eofs, npn_protocols, ciphers, server_hostname, _context, _session)
    807                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 808                     self.do_handshake()
    809 

/usr/lib/python3.6/ssl.py in do_handshake(self, block)
   1060                 self.settimeout(None)
-> 1061             self._sslobj.do_handshake()
   1062         finally:

/usr/lib/python3.6/ssl.py in do_handshake(self)
    682         """Start the SSL/TLS handshake."""
--> 683         self._sslobj.do_handshake()
    684         if self.context.check_hostname:

SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    375                     retries=self.max_retries,
--> 376                     timeout=timeout
    377                 )

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, **response_kw)
    587             release_conn = True
--> 588             raise SSLError(e)
    589 

SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
<ipython-input-58-20b3921db13c> in <module>()
      3 with urllib.request.urlopen('https://facebook.com/') as response:
      4     print(len(response.read()))
----> 5 print(len(requests.get('https://facebook.com').text))

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/api.py in get(url, params, **kwargs)
     65 
     66     kwargs.setdefault('allow_redirects', True)
---> 67     return request('get', url, params=params, **kwargs)
     68 
     69 

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/api.py in request(method, url, **kwargs)
     51     # cases, and look like a memory leak in others.
     52     with sessions.Session() as session:
---> 53         return session.request(method=method, url=url, **kwargs)
     54 
     55 

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    466         }
    467         send_kwargs.update(settings)
--> 468         resp = self.send(prep, **send_kwargs)
    469 
    470         return resp

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/sessions.py in send(self, request, **kwargs)
    574 
    575         # Send the request
--> 576         r = adapter.send(request, **kwargs)
    577 
    578         # Total elapsed time of the request (approximately)

~/Desktop/proj/.venv/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    445         except (_SSLError, _HTTPError) as e:
    446             if isinstance(e, _SSLError):
--> 447                 raise SSLError(e, request=request)
    448             elif isinstance(e, ReadTimeoutError):
    449                 raise ReadTimeout(e, request=request)

SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)
```

##### Any other comments? What have you tried so far?

It's visible from the logs using urllib works alright, but requests fail miserably. 

this is output of pip freeze:
```
aiodns==1.1.1
aiohttp==2.2.3
async-timeout==1.2.1
asyncio==3.4.3
beautifulsoup4==4.6.0
bleach==2.0.0
cchardet==2.1.1
ccxt==1.4.12
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
colorama==0.3.9
coloredlogs==7.1
ConfigArgParse==0.12.0
coverage==4.4.1
Cython==0.26
dash==0.17.7
dash-core-components==0.5.3
dash-html-components==0.6.2
dash-renderer==0.7.3
decorator==4.1.2
entrypoints==0.2.3
Flask==0.12.2
Flask-Compress==1.4.0
Flask-SeaSurf==0.2.2
forex-python==0.3.2
gevent==1.2.2
graypy==0.2.14
greenlet==0.4.12
gunicorn==19.7.1
html5lib==0.999999999
humanfriendly==4.4
idna==2.6
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
itsdangerous==0.24
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-core==4.3.0
logging-tree==1.7
lxml==3.8.0
MarkupSafe==1.0
mistune==0.7.4
multidict==3.1.1
nbconvert==5.2.1
nbformat==4.3.0
nose==1.3.7
nose2==0.6.5
notebook==5.0.0
numpy==1.13.1
overrides==1.8
pandas==0.20.3
pandocfilters==1.4.1
pexpect==4.2.1
pg8000==1.10.6
pickleshare==0.7.4
plotly==2.0.14
prompt-toolkit==1.0.14
prompter==0.3.10
psycopg2==2.7.1
ptyprocess==0.5.2
py==1.4.34
pycares==2.2.0
Pygments==2.2.0
pytest==3.2.1
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
pyzmq==16.0.2
qtconsole==4.3.0
requests==2.9.0
sh==1.12.14
simplegeneric==0.8.1
simplejson==3.11.1
six==1.10.0
slack-logger==0.2.0
slackclient==1.0.6
SQLAlchemy==1.1.13
SQLAlchemy-Utils==0.32.14
terminado==0.6
testpath==0.3.1
toolz==0.8.2
tornado==4.5.1
traitlets==4.3.2
urllib3==1.22
uvloop==0.8.0
voluptuous==0.10.5
wcwidth==0.1.7
webencodings==0.5.1
websocket==0.2.1
websocket-client==0.44.0
websockets==3.3
Werkzeug==0.12.2
widgetsnbextension==2.0.0
yarl==0.11.0
```

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.2
Platform: Linux-4.12.6-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: arch

**Comment by mhils** [comment]
You need to configure requests to trust mitmproxy's CA certificate: http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

**Comment by nmiculinic** [comment]
Hmm I did. I tried using this same proxy with curl and it works as expected.

**Comment by nmiculinic** [comment]
Can I somehow else test if this is properly configured to determine is it python specific problem or my configuration?

**Comment by nmiculinic** [comment]
```
 ~ 1 https_proxy=http://localhost:8080/ curl -vL https://fb.com > /dev/null
* Rebuilt URL to: https://fb.com/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to fb.com:443
> CONNECT fb.com:443 HTTP/1.1
> Host: fb.com:443
> User-Agent: curl/7.55.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* CONNECT phase completed!
* CONNECT phase completed!
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1861 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.facebook.com
*  start date: Aug 27 14:00:17 2017 GMT
*  expire date: Aug 28 14:00:17 2020 GMT
*  subjectAltName: host "fb.com" matched cert's "fb.com"
*  issuer: CN=mitmproxy; O=mitmproxy
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x77891ad1c0)
} [5 bytes data]
> GET / HTTP/2
> Host: fb.com
> User-Agent: curl/7.55.1
> Accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
< HTTP/2 301 
< location: https://www.facebook.com/
< content-type: text/html
< x-fb-debug: ypwJktFznr2IHpCnBLeqVUzNpRbs8y2FDaZ5S1MzVgQEM6IwFbpEmpEKlRS0P1Djt+6W4MBAS4nQLc4jipjWGQ==
< content-length: 0
< date: Tue, 29 Aug 2017 14:01:17 GMT
< 
{ [5 bytes data]
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'https://www.facebook.com/'
* Found bundle for host www.facebook.com: 0x77891b38b0 [can multiplex]
* Hostname localhost was found in DNS cache
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#1)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.facebook.com:443
> CONNECT www.facebook.com:443 HTTP/1.1
> Host: www.facebook.com:443
> User-Agent: curl/7.55.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* CONNECT phase completed!
* CONNECT phase completed!
{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1879 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.facebook.com
*  start date: Aug 27 14:00:18 2017 GMT
*  expire date: Aug 28 14:00:18 2020 GMT
*  subjectAltName: host "www.facebook.com" matched cert's "*.facebook.com"
*  issuer: CN=mitmproxy; O=mitmproxy
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x77891ad1c0)
} [5 bytes data]
> GET / HTTP/2
> Host: www.facebook.com
> User-Agent: curl/7.55.1
> Accept: */*
> 
{ [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
< HTTP/2 200 
< x-content-type-options: nosniff
< x-xss-protection: 0
< public-key-pins-report-only: max-age=500; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="q4PO2G2cbkZhZ82+JgmRUyGMoAeozA+BSXVXQWB8XWQ="; report-uri="http://reports.fb.com/hpkp/"
< pragma: no-cache
< x-frame-options: DENY
< strict-transport-security: max-age=15552000; preload
< expires: Sat, 01 Jan 2000 00:00:00 GMT
< cache-control: private, no-cache, no-store, must-revalidate
< set-cookie: fr=0fiIEm538IB61aFwT..BZpXOu.g3.AAA.0.0.BZpXOu.AWVA2AuF; expires=Mon, 27-Nov-2017 14:01:18 GMT; Max-Age=7776000; path=/; domain=.facebook.com; secure; httponly
< vary: Accept-Encoding
< content-type: text/html; charset=UTF-8
< x-fb-debug: xhvdTlebCA/hqJuiRBrr6iiP/QFmqWrzd5OkjP/vi0WbNV/mbQCGZwktIu/ONbZAByXCzdhWe7vUggwzBNgLBw==
< date: Tue, 29 Aug 2017 14:01:18 GMT
< 
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0{ [5 bytes data]
100  201k    0  201k    0     0   201k      0 --:--:--  0:00:01 --:--:-- 4276k
* Connection #1 to host localhost left intact
```

and I verify it's logged in mitmweb

**Comment by nmiculinic** [comment]
http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

Apparently request have their own CA_BUNDLE, that is on my system it's ```/usr/lib/python3.6/site-packages/certifi/cacert.pem``` for some reason.

**Comment by felixhummel** [comment]
Thanks! I had the same problem.

Just for future reference: If you are on Debian / Ubuntu, and want requests to use your system bundle, simply run:
```
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt python
```

> This list of trusted CAs can also be specified through the REQUESTS_CA_BUNDLE environment variable.

**Comment by deepthi-lnt** [comment]
I am trying to install some packages required for uptane with the below command
pip3 install -r dev-requirements.txt  --trusted-host pypi.org --trusted-host files.pythonhosted.org        

But it is failing at
Obtaining file:///home/root/uptane (from -r dev-requirements.txt (line 8))
Collecting canonicaljson==1.1.4 (from -r dev-requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/59/8d/791b6b9a297a4ff982bb51e5d5248dbd4367215f1eeb5a97da51e70585c7/canonicaljsol
Collecting cffi==1.11.5 (from -r dev-requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.)
     |################################| 440kB 356kB/s 
Collecting cryptography==2.3 (from -r dev-requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/79/a2/61c8625f96c8582d3053f89368c483ba62e56233d055e58e372f94a393f0/cryptography)
     |################################| 450kB 10.1MB/s 
Collecting pynacl==1.2.1 (from -r dev-requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/08/19/cf56e60efd122fa6d2228118a9b345455b13ffe16a14be81d025b03b261f/PyNaCl-1.2.1)
     |################################| 3.3MB 292kB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
        h.request(req.get_method(), req.selector, req.data, headers)
      File "/usr/lib/python3.5/http/client.py", line 1107, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
        self.endheaders(body)
      File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
        self.send(msg)
      File "/usr/lib/python3.5/http/client.py", line 877, in send
        self.connect()
      File "/usr/lib/python3.5/site-packages/setuptools/ssl_support.py", line 191, in connect
        self.sock = ctx.wrap_socket(sock, server_hostname=actual_host)
      File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
        _context=self)
      File "/usr/lib/python3.5/ssl.py", line 760, in __init__
        self.do_handshake()
      File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
        self._sslobj.do_handshake()
      File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:728)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 766, in open_url
        return open_with_auth(url, self.opener)
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 961, in _socket_timeout
        return func(*args, **kwargs)
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 1080, in open_with_auth
        fp = opener(request)
      File "/usr/lib/python3.5/urllib/request.py", line 466, in open
        response = self._open(req, data)
      File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
        '_open', req)
      File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.5/site-packages/setuptools/ssl_support.py", line 161, in https_open
        lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
      File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:728)>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-npkyukqx/pynacl/setup.py", line 251, in <module>
        "Programming Language :: Python :: 3.6",
      File "/usr/lib/python3.5/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.5/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.5/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/usr/lib/python3.5/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
        not self.always_copy, self.local_index
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 655, in fetch_distribution
        dist = find(requirement)
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 635, in find
        loc = self.download(dist.location, tmpdir)
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 579, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 824, in _download_url
        return self._attempt_download(url, filename)
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 830, in _attempt_download
        headers = self._download_to(url, filename)
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 729, in _download_to
        fp = self.open_url(url)
      File "/usr/lib/python3.5/site-packages/setuptools/package_index.py", line 780, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd6)
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-npkyukqx/pynacl/

Please let me know why i am getting this error.

**Comment by madux** [comment]
THE SIMPLE SOLUTION FROM **Maduka Sopulu** IS TO ADD verify=False

eg. response = requests.post(url, data = parameters, verify=False) 

For any requests type, add verify=False
