### ISSUE TITLE
'typing==3.5.2.2' distribution was not found and is required by mitmproxy

### ISSUE THREAD

**Issue by Astrades** [mitmproxy/mitmproxy#2548]
Hey gus. So, I have a fresh kali-rolling installation and mitmproxy is a pre-installed tool. I've used it before and have never run into this issue. Every time I try to run it, I get a python error stating that my distribution is not found (error below).

'typing==3.5.2.2' distribution was not found and is required by mitmproxy

Also, I am unable to look at the mitm version. Thanks for reading! I look forward to fixing this.

**Comment by ritiek** [comment]
Seems like `typing` module is not included by default in Kali. You should be able get it with `pip install typing`.

**Comment by Astrades** [comment]
It says that the package is already satisfied. Also, I can't
uninstall/reinstall it for some reason. It says that it's out of /usr.

**Comment by ritiek** [comment]
That is weird. The only thing I can think of is that your mitmproxy installation and pip point out to different python version. Explicitly specifying for python 3 may help; `pip3 install typing==3.5.2.2`.

**Comment by Astrades** [comment]
Honestly, I forgot what I did. But, I got it working. Thanks for the help
though!

**Comment by ciblus** [comment]
try this
pip install mitmproxy
