### ISSUE TITLE
tlsv1 alert decrypt error

### ISSUE THREAD

**Issue by nmiculinic** [mitmproxy/mitmproxy#2552]
I'm running mitmproxy in docker container and I get the following error:
```
 << Cannot establish TLS with client (sni: fb.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert decrypt error')],)",)
```

##### Steps to reproduce the problem:

1. ```docker run --rm -it -p 8080:8080 mitmproxy/mitmproxy mitmdump -w /tmp/dump```
2. ```https_proxy=http://localhost:8080/ curl https://www.facebook.com```
3. 
```
172.17.0.1:47570: CONNECT www.facebook.com:443
 << Cannot establish TLS with client (sni: www.facebook.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert decrypt error')],)",)
```
happened

##### System information

Docker, latest

```
/home/mitmproxy/.mitmproxy # mitmproxy --version
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.2
Platform: Linux-4.12.6-1-ARCH-x86_64-with
SSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Comment by mhils** [comment]
Does that happen every time, or did that only happen once? Does this only affect the Docker version? Do other HTTPS websites work?

**Comment by nmiculinic** [comment]
This happened every time. 
As far as I can tell only docker version is affected.

> Do other HTTPS websites work?

I don't get this question. I used facebook as kinda, it's always online. I've tried with few other domains, and it fails on them. Facebook mitm works when installing from python.

**Comment by mhils** [comment]
Works fine for me with the latest docker release using `https_proxy=http://localhost:8080/ curl -k https://www.facebook.com`.
