### ISSUE TITLE
Not an issue: question about api

### ISSUE THREAD

**Issue by securisec** [mitmproxy/mitmproxy#2554]
Hey, while using mitmproxy, one can press `E` on a stream to export it to file as python code. See screenshot for reference.
![image](https://user-images.githubusercontent.com/22226823/29898077-e88aabcc-8db1-11e7-951a-e626f74549bf.png)
Is it possible to export all or some streams to a file as python code using the mitmproxy api?

**Comment by mhils** [comment]
Hi,

From https://twitter.com/mitmproxy/status/902977633109016577:

> Not sure what exactly you are looking for, but you can definitely use our scripting interface for that.
  See e.g. https://github.com/mitmproxy/mitmproxy/tree/master/examples/simple

**Comment by securisec** [comment]
thanks @mhils.  

essentially, what i am looking to do, is as my mitmproxy script processes traffic, i would like it to write out the requests and export as `python code` as mitmproxy can do manually.

I looked through the examples, but dont really see that as an option. if it does not exist, i would like to make this ticket a feature request

**Comment by mhils** [comment]
Writing to a file or stdout on each request/response can be done using our `request/response` script hooks. On 2.x, you can then just call https://github.com/mitmproxy/mitmproxy/blob/2.0.x/mitmproxy/export.py#L56.

As an early heads-up, Python export is currently not present on master (see #2465), but you can for instance just copy the respective 2.0 code into your script.
