### ISSUE TITLE
Upstream proxy and PhantomJS

### ISSUE THREAD

**Issue by nesttle** [mitmproxy/mitmproxy#2559]
##### Steps to reproduce the problem:

1. Start mitmproxy with -U parameter (Upstream proxy)
2. Connect to this proxy with PhantomJS
3. Connection stucks/hangs

##### Any other comments? What have you tried so far?

Upstream proxy is working fine with Mozilla Firefox (after installing mitm.pem), and Chrome (sometimes, other times SSL certificate fails).
Upstream proxy isn't working with PhantomJS (with Selenium Python), with or without `--ignore-ssl-errors` (true|false). Don't know if this issue is related to mitmproxy or PhantomJS.

##### System information

```
root@mitm:~# mitmproxy --version
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.3
Platform: Linux-4.10.0-33-generic-i686-with-Ubuntu-17.04-zesty
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 17.04 zesty

```

**Comment by mhils** [comment]
Thanks for the report. We need easier steps to reproduce this.

**Comment by nesttle** [comment]
` service_args=["--proxy=1.1.1.1:8080","--proxy-type=https","--proxy-auth=username:password","--ignore-ssl-errors=true"])`

**Comment by mhils** [comment]
I'm sorry but that doesn't really help.

- Does it work with a regular (non-upstream) proxy?
- Does it affect both HTTP and HTTPS or only one? All domains, only specific domains?
- Do you see anything in mitmproxy's event log (press `e`)?
- Can you provide a WireShark capture?

**Comment by nesttle** [comment]
Hello mhils! 

- Yes, working with regular (non-upstream) proxy
- Affects both HTTP/HTTPS, not 100% sure about this. All domains.
- No logs on mitmproxy
- Will try with WireShark. Anyway this looks like a problem in PhantomJS authentication via HTTP/HTTPS and not mitmproxy

**Comment by nesttle** [comment]
Can I disable HTTP Authentification in -U (upsteam) proxy?
`mitmproxy -U http://user:pass@1.2.3.4:8080`
**user** & **pass** are credentials for external proxy 1.2.3.4:8080
But mitmproxy are also asking for these credentials when I try to connect.

**Comment by mhils** [comment]
Ah, that's the helpful bit I was missing. This suspiciously looks like you are hitting https://github.com/mitmproxy/mitmproxy/issues/2334! You can maybe try a recent snapshot from master (https://snapshots.mitmproxy.org/) to see if that fixes things for you 😃

**Comment by nesttle** [comment]
Thanks mhils! Sorry, but with recent snapshop how should I run mitmproxy with upstream and disable auth?
Same syntax? 

Thanks

**Comment by mhils** [comment]
`mitmproxy --mode upstream:http://... --upstream-auth USER:PASS` should work.

**Comment by nesttle** [comment]
WOW! mitm 3.0 solved this, thanks for your help again! about 1 week facing this issue and you solved it in 1 minute...

Thanks! :)
