### ISSUE TITLE
Custom certificate is ignored in reverse proxy mode

### ISSUE THREAD

**Issue by chorner** [mitmproxy/mitmproxy#2563]
https://github.com/mitmproxy/mitmproxy/blob/master/docs/certinstall.rst#using-a-custom-certificate
Following the documentation, mitmproxy fails to use the provided custom certificate.

##### Steps to reproduce the problem:

1. `openssl genrsa -out cert.key 2048`
`openssl req -new -x509 -key cert.key -out cert.crt`
`... <specify CSR>`
`cat cert.key cert.crt > cert.pem`
2. `mitmproxy -e -v --cert ./cert.pem -p 8000 -R https://www.google.com:443`
3. `echo | openssl s_client -connect 127.0.0.1:8000`
> ...
> Certificate chain
>  0 s:/CN=www.google.com
>    i:/CN=mitmproxy/O=mitmproxy
>  1 s:/CN=mitmproxy/O=mitmproxy
>    i:/CN=mitmproxy/O=mitmproxy

(the self-signed CSR just created should appear here, rather than the default mitmproxy cert)

**Comment by mhils** [comment]
Thanks for the detailed steps. Which mitmproxy version is this?

**Comment by chorner** [comment]
mitmproxy --version

> Mitmproxy version: 2.0.2 (release version)
> Python version: 3.6.2
> Platform: Darwin-16.7.0-x86_64-i386-64bit
> SSL version: OpenSSL 1.1.0f  25 May 2017
> Mac version: 10.12.6 ('', '', '') x86_64

**Comment by mhils** [comment]
This is fixed on master now, thanks!
