### ISSUE TITLE
TCP 

### ISSUE THREAD

**Issue by du-premraj** [mitmproxy/mitmproxy#2565]
Query on TCP

1. Is it possible to capture and dump the messages exchanged between Server (for e.g. postgres or RabbitMQ) and the corresponding client running in the same CentOS host ? 
2. Does it require any iptables PREROUTING ?
3.

**Comment by mhils** [comment]
For non-HTTP protocols over TLS, the best way to set up things is to use mitmproxy as a reverse proxy. If you don't have TLS, Wireshark is the better alternative for what you are asking for I think.
