### ISSUE TITLE
Receiving wrong request from mitmproxy in 'def request(flow):'

### ISSUE THREAD

**Issue by gkumarpatel** [mitmproxy/mitmproxy#2567]
I am using `mitmdump` with python script to intercept https request and manipulate `flow.request.host`, `flow.request.scheme`, `flow.request.port` and `flow.request.path` with in `def request(flow):`. I have been able to achieve the same and get a response for the manipulated request. After first getting response for first request, my application send a second request. In the second request, instead of the host and port set by my application, I get the same previously manipulated host and port, that is `flow.request.host` and `flow.request.port` are from my last manipulated request but `flow.request.scheme` and `flow.request.path` are same as my application sets in second request.
I am getting wrong request in `def request(flow):` for the second request. 

is there any keep-alive or caching thing that is manipulating my second request?

```
from mitmproxy import http
import sys
    
def request(flow):
    	print("\nOriginal Request : " + str(flow.request)+"\n")
    	if flow.request.pretty_host.endswith("original.host.com"):
    		flow.request.host = "mock.host.com"
    		flow.request.scheme = "http"
    		flow.request.port = 8081
    		flow.request.path = re.sub(r"billing",r"moquer-0.0.2/mockbillingBinding",flow.request.path)
    		print("Manipulated Request : " + str(flow.request)+"\n")
    def response(flow):
    	print("Response : " +str(flow.response)+"\n")

```

Edited : After debugging the python script, found that MITMProxy is not able to **disconnect from client** before the second request arrives. I think I might have to some how disconnect from client. is there any api for disconnecting MITMProxy from client and also from the sever? Thoughts please.

##### System information
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.2
Platform: Darwin-16.7.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.12.6 ('', '', '') x86_64

**Comment by gauravatappdirect** [comment]
@mhils can you please guide me here?

**Comment by mhils** [comment]
Please don't @mention me because you didn't get a reply for six hours, that's very disrespectful. Thanks for helping out with #2568 though, so here we go.

This should not happen and there even is a [test](https://github.com/mitmproxy/mitmproxy/blob/master/test/mitmproxy/proxy/test_server.py#L761) for this. We need clear instructions on how this can be reproduced, for example in the form of a Python script, curl or pathod invocations, etc.

**Comment by gauravatappdirect** [comment]
```
from mitmproxy import http
import datetime
import re

def request(flow):
	print("inside request(flow) : " + str(datetime.datetime.now())+ "\n")
	print("original Request : " + str(flow.request)+"\n")
	if flow.request.pretty_host.endswith("original.host.com"):
		flow.request.host = "mock.host.com"
		flow.request.scheme = "http"
		flow.request.port = 8081
		flow.request.path = re.sub(r"billing",r"moquer-0.0.2/mockbillingBinding",flow.request.path)
		print("manipulated Request : " + str(flow.request)+"\n")
def response(flow):
	print("inside response(flow) : " + str(datetime.datetime.now())+ "\n")
	print("Response : " + str(flow.response)+"\n")
	
def clientconnect(root_layer):
	print("inside clientconnect : " + str(datetime.datetime.now())+ "\n")

def clientdisconnect(root_layer):
	print("inside clientdisconnect : " + str(datetime.datetime.now())+ "\n")

def serverconnect(server_conn):
	print("inside serverconnect : " + str(datetime.datetime.now())+ "\n")

def serverdisconnect(server_conn):
	print("")
	print("inside server disconnect : " + str(datetime.datetime.now())+ "\n")
```
Above is the code from python script redirect.py. I am running this script as `mitmdump -p 1080 -s redirect.py` my client is a java application and i have setup java options(`-Dhttp.proxyHost=localhost -Dhttp.proxyPort=1080 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=1080`) to redirect my http traffic to MITMProxy on localhost and port 1080.

1. If I run my java application normally(without any breakpoints), then mitmproxy **is not able to close connections** with the client(my java application)a nor with the server(mock.host.com). See logs
[mitmdump_output_without_breakpoint_in_java_client.txt](https://github.com/mitmproxy/mitmproxy/files/1301857/mitmdump_output_without_breakpoint_in_java_client.txt). And hence in the second request I get host and port from my first request.
2. If I run my java application in debug mode and use breakpoints to pause for a while, then mitmproxy **is able to close connections** with the client(my java appl) and also with the server(mock.host.com). See logs 
[mitmdump_output_with_breakpoint_in_java_client.txt](https://github.com/mitmproxy/mitmproxy/files/1301863/mitmdump_output_with_breakpoint_in_java_client.txt). And hence the second request has the correct host and port send from my java app.

**Comment by gkumarpatel** [comment]
I got the thing, `http1.check_close_connection ` checks if the request or response has a header `connection = close`, if yes it closes the connection, else if keeps the connection alive.

Now, the question arises, even in the same connection, if MITMProxy gets a new request from client, why does `flow.request.host` and `flow.request.port` still holds values from previous request in the same connection but it load new values for `flow.request.scheme` and `flow.request.path`.

**Comment by mhils** [comment]
Thanks for the patience.  I unfortunately cannot reproduce this on master. If I have two HTTPS requests with the same target domain, mitmproxy successfully restores the original destination after the first request for me. If I have two HTTP requests, they are routed to the correct target as well. If you have instructions on how this can be reproduced with curl, please let me know and we can reopen this.
