### ISSUE TITLE
How to direct traffic  after through mitproxy to other proxy server ?

### ISSUE THREAD

**Issue by henrymark92** [mitmproxy/mitmproxy#2568]

**Comment by gkumarpatel** [comment]
have a look at upstream-porxy : http://docs.mitmproxy.org/en/stable/modes.html#upstream-proxy

**Comment by henrymark92** [comment]
Hi all.
I saw in example.
mitmdump -U http://default-upstream-proxy.local:8080/ -s change_upstream_proxy.py

But It's not working for me. Can you help me?
I want create an upstream proxy through ssh connection
here my config.
mitmdump -U http://localhost:1080/ -s change_upstream_proxy.py
or
mitmdump -U http://127.0.0.1:1080/ -s change_upstream_proxy.py 

ssh config:
![capture](https://user-images.githubusercontent.com/4132665/31509152-b5599db0-afaa-11e7-96a6-d5d8f69ceb30.PNG)

Error:

**Comment by henrymark92** [comment]
@mhils  or @gkumarpatel  can you help me?
