### ISSUE TITLE
MIT incompatible with GPL3

### ISSUE THREAD

**Issue by yhack** [mitmproxy/mitmproxy#2572]
I was pleased to see mitmproxy is licensed under MIT. At least one dependency, html2text, is licensed under GPL3. This is a problem as per https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l. Can we resolve this incompatible licensing issue? html2text is barely used. I think it could be removed.

**Comment by mhils** [comment]
This looks like an oversight on our end - thanks for the heads-up. #2573 should fix this.

**Comment by yhack** [comment]
Awesome! Thanks for the quick turnaround :100:
