### ISSUE TITLE
Performance degrade and errors

### ISSUE THREAD

**Issue by Mradr** [mitmproxy/mitmproxy#2576]
##### Steps to reproduce the problem:
1. --set stream_websockets=true
2. Got to google.com
3. Search Speed Test
4. Use the google loaded Speed Test
5. The speed keeps dropping on each repeat until I see the following error:

Error in WebSocket connection to ndt-iupui-mlab1-ord03.measurement-lab.org:53829: WebSocket connection closed unexpectedly by client: TcpDisconnect("(104, 'ECONNRESET')",)
Exception in thread ServerThread (0.0.0.0:8080):
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/master.py", line 32, in run
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/tcp.py", line 951, in serve_forever
    connection, client_address = self.socket.accept()
  File "/usr/lib/python3.5/socket.py", line 195, in accept
OSError: [Errno 24] Too many open files

Did a bit more research : https://github.com/miguelgrinberg/python-socketio/issues/108
Seems like it's a problem with socket.py. Something about it being lazy:) 

##### System information
Mitmproxy version: 2.0.2 (release version)
Python version: 3.5.2
Platform: Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.1.0f  25 May 2017
Linux distro: Ubuntu 16.04 xenial

**Comment by mhils** [comment]
Thanks. This is not a mitmproxy bug per se, you are just opening more connections than your mitmproxy machine is willing to handle. We plan to fix this with #1775, so I'll close this here.
