### ISSUE TITLE
400 Bad request after HTTP CONNECT

### ISSUE THREAD

**Issue by seannexmo** [mitmproxy/mitmproxy#2580]
##### Steps to reproduce the problem:

1. Start mitmproxy in normal mode using official docker container. Loaded one script, insecure mode, docker host networking, port 5050
2. Configure software under test to connect to proxy located at localhost 5050
3. Trigger a request to fetch an XML file from github
4. Connection fails with the following error:

```<html>
            <head>
                <title>400 Bad Request</title>
            </head>
            <body>
            <h1>400 Bad Request</h1>
            <p>HttpSyntaxException(&quot;Bad HTTP request line: b&#x27;\\x80A\\x01\\x03\\x01\\x00\\x18\\x00\\x00\\x00 \\x00\\x00\\x13\\x00\\x00\\x16\\x00\\x00&#x27;&quot;,)</p>
            </body>
        </html>
```
Tracing reveals the following:
```
T 2017/09/27 16:38:35.225917 127.0.0.1:59624 -> 127.0.0.1:5050 [AP]
CONNECT gist.githubusercontent.com:443 HTTP/1.1.
User-Agent: OaklandSoftware/2.7.0.
Host: gist.githubusercontent.com.
.


T 2017/09/27 16:38:35.267952 127.0.0.1:5050 -> 127.0.0.1:59624 [AP]
HTTP/1.1 200 Connection established.
.


T 2017/09/27 16:38:35.271064 127.0.0.1:59624 -> 127.0.0.1:5050 [AP]
.A........ ........
........2..3../Y.....AY(s.WGN..t}G..O.6w$.\..v.

T 2017/09/27 16:38:35.288685 127.0.0.1:5050 -> 127.0.0.1:59624 [AP]
HTTP/1.1 400 Bad Request.
Connection: close.
Server: mitmproxy 2.0.2.
Content-Type: text/html.
Content-Length: 361.
.


T 2017/09/27 16:38:35.288846 127.0.0.1:59624 -> 127.0.0.1:5050 [AP]
......


T 2017/09/27 16:38:35.288855 127.0.0.1:5050 -> 127.0.0.1:59624 [AP]
<html>
            <head>
                <title>400 Bad Request</title>
            </head>
            <body>
            <h1>400 Bad Request</h1>
            <p>HttpSyntaxException(&quot;Bad HTTP request line: b&#x27;\\x80A\\x01\\x03\\x01\\x00\\x18\\x00\\x00\\x00 \\x00\\x00\\x13\\x00\\x00\\x16\\x00\\x00&#x27;&quot;,)</p>
            </body>
        </html>
```

##### Any other comments? What have you tried so far?
We have tried running mitmproxy on docker in transparent mode, using instructions here:
http://docs.mitmproxy.org/en/stable/transparent.html

We ensured iptables and route tables were updated to route port 80/443 traffic to 5050 via network layer. We disabled proxy settings on the software and attempted to repeat the exercise. When the proxy was restarted, the event log was full of the following messages during connection attempts:
`Transparent mode failure: FileNotFoundError(2, 'No such file or directory')`

##### System information

```Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.2
Platform: Linux-2.6.32-696.el6.x86_64-x86_64-with
SSL version: OpenSSL 1.0.2k  26 Jan 2017
```

**Comment by aayla-secura** [comment]
I think this is the same issue I came across last night. mitmproxy does not handle requests with relative (to root) URI even when the Host header is present. Example:

```
$ nc 127.0.0.1 8080
GET http://www.google.com/ HTTP/1.1
Host: 192.168.56.102

HTTP/1.1 301 Moved Permanently
Location: http://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Fri, 29 Sep 2017 23:30:53 GMT
Expires: Sun, 29 Oct 2017 23:30:53 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 219
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>

$ nc 127.0.0.1 8080
GET / HTTP/1.1
Host: www.google.com

HTTP/1.1 400 Bad Request
Server: mitmproxy 2.0.2
Content-Length: 306
Connection: close
Content-Type: text/html

<html>
            <head>
                <title>400 Bad Request</title>
            </head>
            <body>
            <h1>400 Bad Request</h1>
            <p>HttpException(&#x27;Invalid HTTP request form (expected: authority or absolute, got: relative)&#x27;,)</p>
            </body>
        </html>HTTP/1.1 502 Bad Gateway
Server: mitmproxy 2.0.2
Content-Length: 349
Connection: close
Content-Type: text/html

<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>ProtocolException(&#x27;HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)&#x27;,)</p>
            </body>
        </html>
```

As far as I know a request with a URI starting with / is perfectly valid and mitmproxy should use the Host header.

Can you confirm from your packet trace whether the URI in the GET (or POST or whatever) line includes the http://<host> or not?

**Comment by mhils** [comment]
@seannexmo: Your app is not sending an HTTP request after the CONNECT, so mitmproxy can't process it. What did you expect to happen? FWIW, you can explicitly enable [TCP mode](http://docs.mitmproxy.org/en/stable/features/tcpproxy.html), which however is much more restricted.

**Comment by mhils** [comment]
@aayla-secura: Your issue is different. If you look at the HTTP RFCs, you'll see that for a regular/explicit proxy, the URL must be provided in absolute form in the first line (just the Host header is not enough). This is different in reverse or transparent mode, of course.

**Comment by seannexmo** [comment]
Hi @mhils, thanks for the suggestion. We got a little confused with the usage of TCP mode, pressing 'o' seemed to prompt for Ordering configs. We tried setting "--tcp localhost" as a command arg but that didn't help. Maybe we're doing it wrong.

FWIW we're testing a third party system which appears to be written in C and seems to be run and managed (config file wise) via a Java tool :trollface: 

We are hoping to see mitmproxy intercept the TLS connection after the CONNECT so we can manipulate the incoming XML file its supposed to fetch. As shown in our OP the file is hosted on gist.

We tried fidding with the SOCKS option, but received an error message along the lines of SOCKS5 was expected, but SOCKS4 was used instead.

After a little more tweaking we found that the application would only respect our proxy configs when the config file is written in a very specific way. We started seeing more useful information in the event log. A wireshark capture indicated that it was attempting to connect using TLS1.0.

Currently the event log is showing an error as per below:
```
127.0.0.1:59438: Certificate Verification Error for gist.githubusercontent.com:443: hostname 'no-hostname' doesn't match either of 'www.github.com',
'*.github.com', 'github.com', '*.github.io', 'github.io', '*.githubusercontent.com', 'githubusercontent.com'
127.0.0.1:59438: Ignoring server verification error, continuing with connection
```
Further analysis of the pcap showed the following:
1. CONNECT to gist
2. 200 Connection established
3. Client HELLO 
4. Server HELLO, Certificate,  Server Key Exchange, Server Hello done
5 Alert Level Fatal (Internal Error)

Following the TCP stream revealed the following at the tail end:
```
HTTP/1.1 502 Bad Gateway
Server: mitmproxy 2.0.2
Connection: close
Content-Length: 448
Content-Type: text/html
```

Is there anything we should check at the network level?

Many thanks

**Comment by mhils** [comment]
>  We got a little confused with the usage of TCP mode, pressing 'o' seemed to prompt for Ordering configs. We tried setting "--tcp localhost" as a command arg but that didn't help. 

Probably an oversight in the docs. It's `--tcp-hosts` and `O` on master, you can see what works on 2.x using `--help`.

> We are hoping to see mitmproxy intercept the TLS connection after the CONNECT so we can manipulate the incoming XML file its supposed to fetch.

Your software starts sending `\x80A\x01\x03\x01` after successful CONNECT, which I don't think is a valid beginning for a TLS ClientHello. Hence, mitmproxy doesn't detect that it's TLS, falls back to HTTP and complains that it's not a valid HTTP request line.

> We tried fidding with the SOCKS option, but received an error message along the lines of SOCKS5 was expected, but SOCKS4 was used instead.

Limitation in our SOCKS support - patches welcome, but it doesn't really have much to do with your issue here 😉 

> Currently the event log is showing an error as per below (Certificate Verification Error)

Mitmproxy requires the client to send a TLS server name indication so that it can validate the server's certificate. You can ignore this using `--insecure`, in which case mitmproxy won't validate the upstream certificate. Unrelated to your issue.

> Further analysis of the pcap showed the following:

What you are describing here does not match the behavior you reported in your initial post, so it's not really clear to me what your actual issue is.

**Comment by seannexmo** [comment]
Hi,

After some extra debugging with a colleague we discovered that the application was attempting to connect with SSLv2, which as far as we understand is not supported by mitmproxy.

We've decided that this isn't an issue on the part of mitmproxy now, and will close this off. Thanks for your patience and assistance.

Cheers,
Sean
