### ISSUE TITLE
Error in HTTP connection: ClientHandshakeException - "Unexpected EOF"

### ISSUE THREAD

**Issue by nesttle** [mitmproxy/mitmproxy#2582]
##### Steps to reproduce the problem:

1. mitmproxy -p 1337
2. Randomly crashes

![image](https://user-images.githubusercontent.com/4428341/31340383-47b193fe-ad06-11e7-88a7-21a2162f33f8.png)

**Comment by mhils** [comment]
Thanks. That's probably a network connection issue we're just catching incorrectly. Can you provide us with the full traceback in the event log (press `e`)?
