### ISSUE TITLE
mitmproxy 2.0.1 is failing for HTTPS requests

### ISSUE THREAD

**Issue by krishnask7** [mitmproxy/mitmproxy#2584]
##### Problem:
All HTTPS requests are failing. But HTTP request responses are clearly failing

##### Steps to reproduce the problem:
Command used:
-------------------
1. mitmdump -v -p 9001 -s "D:\Python\Python35\Scripts\har_dump.py" --cert "C:\Users\Krishna\.mitmproxy\mitmproxy-ca-cert.pem" -w "mani.dump"
2. Set up manual proxy port on the android mobile device to 9001 

Python Version:: Python 3.5.0
mitmproxy version: 2.0.1

##### Same Request failing to receive response!

192.168.0.37:48364: request
  -> Request(GET connectivitycheck.gstatic.com:80/generate_204)
192.168.0.37:48364: response
  -> Response(204 No Content, no content)
192.168.0.37:48364: GET http://connectivitycheck.gstatic.com/generate_204
                 << 204 No Content 0b
192.168.0.37:48382: clientconnect
192.168.0.37:48382: Set new server address: ('connectivitycheck.gstatic.com', 443)
192.168.0.37:48382: serverconnect
  -> connectivitycheck.gstatic.com:443
192.168.0.37:48382: Establish TLS with server
192.168.0.37:48381: request
  -> Request(POST /auth)
192.168.0.37:48382: ALPN selected by server: http/1.1
192.168.0.37:48382: Establish TLS with client
192.168.0.37:48382: ALPN for client: b'http/1.1'
192.168.0.37:48382: Failed to send error response to client: ClientHandshakeException('Cannot establish TLS with client (sni: connectivitycheck.gstatic.com): TlsException("SSL hand
shake error: SysCallError(-1, \'Unexpected EOF\')",)',)
192.168.0.37:48382: CONNECT connectivitycheck.gstatic.com:443
 << Cannot establish TLS with client (sni: connectivitycheck.gstatic.com): TlsException("SSL handshake error: SysCallError(-1, 'Unexpected EOF')",)
192.168.0.37:48382: serverdisconnect
  -> connectivitycheck.gstatic.com:443
192.168.0.37:48382: clientdisconnect
192.168.0.37:48381: response
  -> Response(400 Bad Request, text/plain; charset=utf-8, 59b)
192.168.0.37:48381: POST https://android.clients.google.com/auth
                 << 400 Bad Request 59b
192.168.0.37:48381: request
  -> Request(POST /auth)
192.168.0.37:48381: response
  -> Response(400 Bad Request, text/plain; charset=utf-8, 59b)
192.168.0.37:48381: POST https://android.clients.google.com/auth
                 << 400 Bad Request 59b

**Comment by mhils** [comment]
Sorry, it's really not clear what your issue is.
