### ISSUE TITLE
Transparent mode fail with looking up failure.

### ISSUE THREAD

**Issue by Ga-ryo** [mitmproxy/mitmproxy#2594]
##### Steps to reproduce the problem:

1. Launch Wifi Access Point(OS X)
2. Setup pfctl configuration so that http packet will be forwarded.
3. Launch mitmproxy ( `sudo mitmproxy -p 8080 -m transparent --showhost` )
4. Access web page after connecting to AP which launched before.
5. See event log.

##### Any other comments? What have you tried so far?

When I tried to use transparent mode with OS X(10.11.6).
RuntimeError("Could not resolve original destination.") raised.

I investigated this bug.
And I found that this is caused by difference between AF_INET's and AF_INET6's peername.
https://github.com/mitmproxy/mitmproxy/blob/de006ea8adc08b9a8a6aa94eda2b30468727c307/mitmproxy/net/tcp.py#L567

If we use AF_INET, getpeername() return string like `"192.168.2.5:45670"`.
But if we use AF_INET6, getpeername() return string like `"::ffff:192.168.2.5:45670"`.

`pfctl -s state` 's result is like below.
`ALL tcp 192.168.2.5:45670 -> xx.xx.xx.xx:33291 -> xx.xx.xx.xx:443       ESTABLISHED:ESTABLISHED`

As you see, `::ffff:` doesn't exist.

So [lookup](https://github.com/mitmproxy/mitmproxy/blob/f17c0fdac636f7269f4885294e2a8d2c52c23590/mitmproxy/platform/pf.py#L4) function raises RuntimeError() because `spec in i` condition won't become true.

##### System information

Mitmproxy version: 3.0.0 (release version)
Python version: 3.6.2
Platform: Darwin-15.6.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2l  25 May 2017
Mac version: 10.11.6 ('', '', '') x86_64

**Comment by mhils** [comment]
Thanks for the awesome report! :smiley: 🍰
