### ISSUE TITLE
Raw tcp connection

### ISSUE THREAD

**Issue by skotti** [mitmproxy/mitmproxy#2595]
Hello,
I am a little bit confused with catching tcp traffic with mitmproxy.
I do like this:
1. mitmdump(mitmproxy) --raw-tcp -p 5656
2. on my VM I do: netcat 192.168.50.10 5656
3. my machines are connected through bridge, so I can ping all VM's from host and in opposite direction as well.
so, I want to simply record this tcp traffic , but every time I type something I get an error ( this does not happen if I type on host instead mitmdump --raw-tcp -p 5656 (or mitmproxy):
192.168.20.1:45020: clientconnect
192.168.20.1:45020: ProtocolException("Error in HTTP connection: HttpSyntaxException('Bad HTTP request line: 1',)",)
192.168.20.1:45020: clientdisconnect
Why I get a message about http? What I should do to parse , intercept and analyze raw tcp packets? And maybe some others , which have no relation to http at all and are unencrypted?

**Comment by mhils** [comment]
Using `mitmdump --raw-tcp -p 5656` you are starting mitmproxy as a regular HTTP proxy. It will expect clients to send a `GET http://example.com/foo HTTP/1.1` HTTP request or a `CONNECT example.com:1234` request to establish a (raw TCP) tunnel to the destination. There's a more detailed description at http://docs.mitmproxy.org/en/stable/modes.html. For your netcat example to work, you probably want to start mitmproxy as a reverse proxy and provide the destination address. In that case I would recommend using `--tcp .*` right away if you are not expecting HTTP traffic.

**Comment by skotti** [comment]
Thank you for comment.
I have tried but still no success : mitmproxy -R 192.168.20.2:5656 --tcp HOST ( and netcat 192.168.20.10 5656 on another machine) - I can't specify such a string (due to that syntax should include http(s) address, not ip). I am launching this on host and waiting for a netcat message from the first vm.
In general I need to send a tcp message from one VM to host , it should be intercepted with mitmproxy, then forward to another VM.

vm1---> host(mitmproxy)--->vm2

**Comment by mhils** [comment]
You still need to listen on the correct port (`-p 5656`) and you just want to use `--tcp .*` (read the docs page more carefully):

`mitmproxy -p 5656 -R 192.168.20.2:5656 --tcp .*`

**Comment by skotti** [comment]
Actually, as I have written earlier this is an invalid server specification, I can't specify server with ip and port. It causes an error. Maybe you know a way, how to tell mitmproxy to accept such a notation?

**Comment by mhils** [comment]
You can just prefix the server with http:// - the next release will have that fixed and accepts plain server:port specs.

**Comment by skotti** [comment]
Ok , thanks, for mitmdump version this work. However, launching mitmproxy I don't see any traffic. Am I able to parse or analyze or intercept tcp traffic? In your docs it is said, that no, but I want to be sure. I need to intercept tcp traffic, parse it, maybe with some dissector and then forward further.

**Comment by skotti** [comment]
I mean raw tcp traffic, http://docs.mitmproxy.org/en/stable/features/tcpproxy.html

**Comment by skotti** [comment]
Are there any ideas on intercepting tcp?

**Comment by mhils** [comment]
Take a look at
http://docs.mitmproxy.org/en/stable/scripting/events.html#tcp-events and
what is printed in the event log. It's _very_ rudimentary, but may work
depending on your use case.

**Comment by skotti** [comment]
As  soon as I still didn't reach the desired result, pleas could you tell, am I able not only to see logs, but to change tcp messages and delay them?

**Comment by skotti** [comment]
Also, I when  I launch mitmdump in reverse mode:
events, related to tcp messages are not printed, only client connect, clientdisconnect:
mitmdump -p 5656 -R http://192.168.20.1:5656 --tcp '.*' 
192.168.20.2:60600: clientconnect
192.168.20.2:60600: -> tcp -> 192.168.20.1:5656
1

this is what I see when I send one
