### ISSUE TITLE
Sample wsgi_flask_app.py is wrong

### ISSUE THREAD

**Issue by yeradis** [mitmproxy/mitmproxy#2598]
##### Steps to reproduce the problem:

1.
mitmdump -s wsgi_flask_app.py
2.
Go to `example.com` and should appear `Hello World!`
3.
Instead, the original site is shown

##### Any other comments? What have you tried so far?

The sample shows this:

```python
def load(l):
    return wsgiapp.WSGIApp(app, "proxapp.local", 80)
```

but should be:

```python
def start():
    return wsgiapp.WSGIApp(app, "example.com", 80)
```

Placing it inside the `start()` event, returns the expected result

also i´m unable to make the 443 sample to work

**Comment by yeradis** [comment]
@mhils you are right, just installed the homebrew version and went to the repo and tried to follow the examples

with this in mind will be easy 
its my fault for not `reading` : "If you are browsing this on GitHub, make sure to select the git tag matching your mitmproxy version" at https://github.com/mitmproxy/mitmproxy/tree/master/examples

but its interesting the "breaking" changes i just "found" trying to run a simple example xD, three different ways for the same thing xD

going to close this now, thanks for your time

**Comment by mhils** [comment]
Thanks for the feedback and sorry for the confusion. The current API is a bit preliminary, we're basically experimenting with different models for a (then) stable API.

**Comment by yucer** [comment]
I guess that the example is outdated again, because it doesn't work for me. Which is the correct way to work with the *wsgiapp* addon for the current version ?
