### ISSUE TITLE
Transparent proxy not catching responses

### ISSUE THREAD

**Issue by james-88** [mitmproxy/mitmproxy#2605]
Hello,

I have a network of 2 devices, the network is configured to work as the following:
                                        Device A                    Device B
| GATEWAY | --------> | MITMPROXY | ------> | SOURCE |

So basically only data coming from the gateway to the source flow through the device where mitmproxy is running, now if I configure this network to work as a normal network then I can intercept data in both directions with no issues, all I have to do is redirect flows on port 80 to port 8080 using IP tables.

The problem is if I change my configuration as shown above, I should still be able to intercept data coming from the gateway to source through mitmproxy right? I tried it but it does not see any flows even though the data is flowing properly, so if I check with tcpdump and wireshark and I can see flows going from gateway to source, but mitmproxy can't see  anything, is this an issue with mitmproxy or am I doing something wrong?

**Comment by mhils** [comment]
> is this an issue with mitmproxy or am I doing something wrong?

Mitmproxy needs to see the full TCP connection, we cannot operate on only seeing traffic flowing in one direction. I don't know of any other tool that would support that, you'd need to look for something that works on individual packets or change your setup. 😃
