### ISSUE TITLE
How to forward mitmproxy to other proxy?

### ISSUE THREAD

**Issue by henrymark92** [mitmproxy/mitmproxy#2607]
Hi all. How to use mitproxy to forward proxy, modify and bypass request?
1. Make forward mitmproxy (ex: 127.0.0.1:8080) to other proxy (ex:213.45.34.5:8999)
2. Make modify request 
3. Make bypass SSL (tls_passthrough.py)
Anyone. who can help me?
Thanks

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but you need to demonstrate that you made an effort at solving the problem yourself first. Can I please ask you to follow up in [our community forums](https://discourse.mitmproxy.org/) for all support and how-to questions?


Thanks!
Max
