### ISSUE TITLE
transparent mode and mitm certificate do not work.

### ISSUE THREAD

**Issue by ddor254** [mitmproxy/mitmproxy#2609]
Hi , i'm facing a problem when running transparent mode and mitm certificate is trusted in the proxied machine - 

when i'm running on regular mode and i do manual proxy on the proxied machine - all good and i can decrypt the https traffic with the mitm certificate. - see no problems and i'm entering https sites with no warnings.

when changing that to -T option (transparent) and creating iptables rules, and removing the manual proxy configuration from the proxied device , but with the same certificates , every time that i'm entering https site i get  " your connection is not private"\ NET:ERR_CERT_AUTHORITY_INVALID , and the mitm proxy is still in the trusted CA. 

is this a feature or a bug?

##### Steps to reproduce the problem:

1.install certificate on mobile device

2.set iptables rules in machine that redirect https traffic to port 8080 
iptables --table nat --insert PREROUTING -p tcp --destination-port 443 -j REDIRECT --to-ports 8080

3. run mitmproxy : mitmproxy --host -T -p 8080

##### Any other comments? What have you tried so far?
I followed this manual : http://docs.mitmproxy.org/en/stable/transparent/linux.html 

##### System information
Sony Xperia , android version 7.1.1 as the proxied device
Ubuntu 16.04  as the proxy server

Mitmproxy version: 2.0.2 (release version) 

when running mitmdump instead of mitmproxy i get the following error : 
10.0.1.5:52341: Client Handshake failed. The client may not trust the proxy's certificate for cdn.taboola.com. 

so there must be something wrong with the certificate - but in regular mode with the *same* certificate it works !

**Comment by mhils** [comment]
Are you looking at the same application? This is most likely an issue with your phone, not mitmproxy.

**Comment by mdavids** [comment]
See my comment in https://github.com/mitmproxy/mitmproxy/issues/2609, it really seems as if -T breaks SSL.

**Comment by mhils** [comment]
@mdavids: `ERR_CERT_AUTHORITY_INVALID` on the client means that the client doesn't trust the mitmproxy certificate authority. That almost always is not a mitmproxy issue. Anyways, let's not sidetrack this and continue your discussion in a separate issue from https://github.com/mitmproxy/mitmproxy/issues/2308#issuecomment-340263793

**Comment by mdavids** [comment]
One last comment here, as a reply to yours. :-)

It's not as you suggested. There is simply no TLS. So for example: https://example.nl/ (ending up at mitmproxy) gives an SSL protocol error and http://example.nl:443/ works (but obviously without SSL).

Here's what I did:

# does not work, no SSL
sudo ./mitmweb --no-onboarding -T --host --no-upstream-cert --port 443 --cert *=myowncert.pem

# works fine
sudo ./mitmweb  -p 443 -R https://example\.nl:443  --tcp ^.*$ --no-upstream-cert --cert *=myowncert.pem

This is on machine A.

Machine B has a modified /etc/hosts, making example.nl point to machine A (luckily I just needed to intercept this one domain, so the second method works for me). I browse on machine B. 

The myowncert.pem is trusted on machine B.

**Comment by M25A** [comment]
@mdavids and @ddor254 did you guys found any solution? I am having SSL Unpinning, APK Trust Killer, JustTRustMe and MITM CA certificate installed in Android 4.4.2 rooted phone. Still, I get "No internet connection" and "Client Handshake failed. The client may not trust the proxy's certificate for (app)" when I try to inspect traffic of any android application. A few times, I get "TLS verification failed for upstream server at depth 0 with error: Invalid Hostname" in log entries. All proxy configurations are correctly in place. Can someone please guide what possibly could be the reason behind this issue?

**Comment by patcon** [comment]
I used this to get things working by unpinning the cert in the app: https://github.com/ryanking13/android-SSL-unpinning

**Comment by BigSully** [comment]
```
iptables --table nat --insert PREROUTING -p tcp --destination-port 443 -j REDIRECT --to-ports 8080
```

I see you only redirected traffic of port 443. If I'm not wrong, only **http**://mitm.it/ displays the certificate installing page,  **https**://mitm.it/  won't, so you might try to redirect traffic of port 80.
