### ISSUE TITLE
Installed mitmproxy OSX but cannot locate .mitproxy directory

### ISSUE THREAD

**Issue by jac300** [mitmproxy/mitmproxy#261]
I was able to successfully install mitproxy (confirmed by doing a 'pip list') but when I try to 
install the mitmproxy certificate authority in the IOS simulator using the command:

./iosCertTrustManager.py -a ~/.mitmproxy/mitmproxy-ca-cert.pem

I get an no such file or directory error for .mitmproxy/mitmproxy-ca-cert.pem.  I tried to just find the directory by doing cd ~/.mitmproxy/mitmproxy-ca-cert.pem, and even cd ~/.mitmproxy but again I get no such file or directory.

It's possible I am making a very simple mistake (I am a bit of a newbie) but I don't understand why I can't find the directory if the installation was successful. Any help would be appreciated. Thanks!

**Comment by chandankashyap2310** [comment]
I am having same issue. I have installed mitmproxy using below mentioned command but still i am getting no mitmdump found. I have ubuntu server 16.04 LTS

Command : sudo pip3 install mitmproxy
