### ISSUE TITLE
pip install mitmproxy==0.16 failed error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by teguh24** [mitmproxy/mitmproxy#2612]
build/temp.linux-x86_64-2.7/_openssl.c:59549:29: warning: passing argument 2 of ‘X509_get0_signature’ from incompatible pointer type [-Wincompatible-pointer-types]
       { X509_get0_signature(x0, x1, x2); }
                                 ^~
    In file included from /usr/include/openssl/cms.h:16:0,
                     from build/temp.linux-x86_64-2.7/_openssl.c:532:
    /usr/include/openssl/x509.h:552:6: note: expected ‘const X509_ALGOR ** {aka const struct X509_algor_st **}’ but argument is of type ‘X509_ALGOR ** {aka struct X509_algor_st **}’
     void X509_get0_signature(const ASN1_BIT_STRING **psig,
          ^~~~~~~~~~~~~~~~~~~
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Can't rollback cryptography, nothing uninstalled.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Sw5H4e/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-F1G7pb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Sw5H4e/cryptography/

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?
