### ISSUE TITLE
Configurable reverse proxying per site

### ISSUE THREAD

**Issue by jamespo** [mitmproxy/mitmproxy#2614]
Similar to

-R http://example.com --setheader :~q:Host:example.com

from the docs I'd like to forward all requests for eg http://a.com to http://b.com (with host header appropriately set for a.com) but all other requests to go to their "proper" destination?

**Comment by mhils** [comment]
Thanks for the feedback. We are tracking something similar in https://github.com/mitmproxy/mitmproxy/issues/1454, so I'd close this here. 😃 
If you feel there are any points missing in #1454, please comment there!
