### ISSUE TITLE
Bug in expected_http_body_size

### ISSUE THREAD

**Issue by pruzam** [mitmproxy/mitmproxy#2618]
##### Steps to reproduce the problem:

1. Any response with more than one content-length header

##### Any other comments? What have you tried so far?

headers is MultiDict so this:
size = int(headers["content-length"])
can be change to:
size = int(headers.get_all("content-length")[0])

**Comment by mhils** [comment]
Thanks. Would you like to file a PR that fixes that? We should use `get_all` and verify that all returned values are equal as per https://tools.ietf.org/html/rfc7230#section-3.3.2. Like that:
```python
# Handle multiple content-length headers as per https://tools.ietf.org/html/rfc7230#section-3.3.2
sizes = headers.get_all("content-length")
different_content_length_headers = any(x != sizes[0] for x in sizes)
if different_content_length_headers:
    raise exceptions.HttpSyntaxException("Conflicting Content Length Headers")
size = int(sizes[0])
```

**Comment by pruzam** [comment]
Yes, i'll do it today.
