### ISSUE TITLE
Cannot connect to reCaptach

### ISSUE THREAD

**Issue by RedDuckss** [mitmproxy/mitmproxy#2624]
![screenshot_20171108-161227](https://user-images.githubusercontent.com/27011796/32574977-be03e780-c4a0-11e7-88ef-cd55d6f89886.png)

# Steps to reproduce the problem:

1. Setup mitmproxy
2. Setup SLL certs on Android device (I used this tutorial https://blog.heckel.xyz/2013/07/01/how-to-use-mitmproxy-to-read-and-modify-https-traffic-of-your-phone/#Install-mitmproxy-CA-certificate-in-the-phone)
3. Download `Nintendo Switch Online` app
4. Try to login

# Any other comments? What have you tried so far?

When trying to log in to services that utilize reCaptcha, mitmproxy seems to block the connection to the reCaptcha server, preventing the login from continuing. I was attempting to sniff the requests sent by the Switch app but was unable to login due to the reCaptcha failure.

# System information

Mitmproxy version: 2.0.2 (release version) Precompiled Binary
Python version: 3.5.3
Platform: Windows-10-10.0.15063
SSL version: OpenSSL 1.0.2j  26 Sep 2016
Windows version: 10 10.0.15063  Multiprocessor Free

Android phone is a Blu Advance 5.5 running Android 6.0

**Comment by mhils** [comment]
The app you are looking at probably uses certificate pinning, which we cannot fix - sorry.
http://docs.mitmproxy.org/en/stable/certinstall.html#certificate-pinning

**Comment by RedDuckss** [comment]
You say you can’t fix it and that the request is rejected because of certificates, however I was able to use Fiddler on the same application with no issues. So how is it that the application accepts connections from Fiddler and not this

**Comment by mhils** [comment]
That piece of information was missing in the initial post, sorry. Can you possibly provide me with a PCAP?

**Comment by RedDuckss** [comment]
Yes my apologies. It was missing from the original post because at the time of making it, I had not tried Fiddler. I will provide a PCAP asap, as I do not have access to a PC at the moment.

**Comment by RestOp** [comment]
Hello,

on Ubuntu Server

![image](https://user-images.githubusercontent.com/46259141/173208784-29864cf4-2365-4f9f-a2bb-cbccaa6178e6.png)
