### ISSUE TITLE
Allow to push/inject own WebSocket messages

### ISSUE THREAD

**Issue by imilo** [mitmproxy/mitmproxy#2627]
I inspect a HTTPS WebSocket traffic with Mitmproxy. Currently I can read/edit WS messages with:
```python
...
class Intercept:
    def websocket_message(self, flow):
        print(flow.messages[-1])
        ...

def start():
    return Intercept()
```
… as attached script to Mitmproxy.

Please add a functionality to push/inject our own messages to the client/server. Not edit existing one, but send a new message.

**Comment by Kriechi** [comment]
Thanks for the feature request!
Our current protocol stack makes this a bit difficult - but we are exploring a new approach which should make this much easier in the future.

**Comment by abdulaziz-jm** [comment]
+1

**Comment by Kriechi** [comment]
@imilo @abdulaziz-jm please check #3119. It is a work-in-progress, but maybe you can play around with it (install from source if required).
