### ISSUE TITLE
har_dump: KeyError: 'log'

### ISSUE THREAD

**Issue by robben1234** [mitmproxy/mitmproxy#2628]
##### Steps to reproduce the problem:

1. save flow `mitmproxy -w dump`
2. try to convert it to har with `mitmproxy -n -r dump -s har_dump.py`
3. watch stacktrace instead of har file:

```
Script error: TypeError: configure() takes 1 positional argument but 2 were given

Script error: Traceback (most recent call last):
  File "har_dump.py", line 148, in response
    HAR["log"]["entries"].append(entry)
KeyError: 'log'
```

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.3
Platform: Darwin-17.2.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.13.1 ('', '', '') x86_64

**Comment by ujjwal96** [comment]
Looks like you're using the script from master branch with 2.0.2
Try using this instead https://github.com/mitmproxy/mitmproxy/blob/2.0.x/examples/complex/har_dump.py
