### ISSUE TITLE
mitmweb shows nothing

### ISSUE THREAD

**Issue by hryamzik** [mitmproxy/mitmproxy#2630]
##### Steps to reproduce the problem:

1. Run on hight sierra
2. `mitmweb -nr some.dump`

![image](https://user-images.githubusercontent.com/1643962/32831963-47694142-c9fa-11e7-8fe3-8674fae0428c.png)

##### Any other comments? What have you tried so far?

Works fine on sierra with the same version of mitmproxy.

##### System information

```
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.3
Platform: Darwin-17.0.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0g  2 Nov 2017
Mac version: 10.13 ('', '', '') x86_64
```

**Comment by mhils** [comment]
Which browser are you using? Is there anything in your browser's developer console?`Does it work in other browsers?

**Comment by hryamzik** [comment]
It's Chrome. Nothing in console. It works in the same browser if I run proxy from docker.
```
docker run --rm -it -v $PWD:/home/mitmproxy/ -p 8081:8081 mitmproxy/mitmproxy mitmweb --no-browser --web-iface 0.0.0.0 -nr /home/mitmproxy/my.dump
```

**Comment by SwiftyWang** [comment]
still happened in 2.0.2 
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by hryamzik** [comment]
@SwiftyWang can you try with `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`?
