### ISSUE TITLE
Stop traffic and send tcp answer

### ISSUE THREAD

**Issue by skotti** [mitmproxy/mitmproxy#2634]
Hello!
I want to filter inside proxy the incoming traffic by some rule and drop packets where the traffic is not 'good' for me. Is it possible to stop everything and send back the message with failure? Or simply stop?

**Comment by skotti** [comment]
I managed to launch fully tcp mode in transparent proxy, is it possibly to do smth like this there? Or only in reverse proxy?

**Comment by mhils** [comment]
Thanks for getting in touch. Please use our forums at discourse.mitmproxy.org for general support questions. Thanks!
