### ISSUE TITLE
Running custom server instead of running mitmdump/mitmproxy

### ISSUE THREAD

**Issue by awdng** [mitmproxy/mitmproxy#2639]
For a study project, i decided to build a GUI for mitmproxy as a learning project.
I originall planned that his tool would run the ProxyServer itself instead of running another tool (mitmproxy) next to it and communicating with it, but seems like it recent versions this functionality has been mostly replaced and it is strongly encouraged to use mitmdump and the scripting api.

Now, let's say in this GUI tool, users could see a list of Request and dynamically mark those to edit headers on the fly, how would i communicate this to the mitmdump script in realtime ? I can use command line arguments or start a lot of subprocesses per Request to be analyzed but that is not really a good solution.

Do i have to use a shared database that the inline script as well as the GUI app would access to get dynamic data? Running the server inside the same process would make this easier.

Any help much appreciated

**Comment by mhils** [comment]
Hi Arne! Sounds like a fun project - feel free to join us on Slack and bug us with questions. :-)

To start off, have you looked at mitmweb, our web interface? It already provides a REST API you can use. The code in https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/web/ should also give you an idea how it is implemented. You should be able to implement what you want in an addon, where you have access to the proxy master and the associated data. :-)

**Comment by mhils** [comment]
Closing this as there is nothing actionable here for the moment, but please feel free to ping us with questions anytime. :-)
