### ISSUE TITLE
Dump with websocket messages

### ISSUE THREAD

**Issue by edi9999** [mitmproxy/mitmproxy#2640]
Hello,

I would like to record full http + websocket traffic including websocket messages. 

I have tried `mitmdump -w dump`

However, it seems that in the recorded file, only the http requests+ responses are recorded, and the websocket initialisation, but not the separate websocket messages (called frames in chrome Dev tool).

Is it possible to record the websocket frames too with the command line directly ?

I am running master (46901d1d55cb5bad86e17e093b85ade8111315aa)

Thanks in advance

**Comment by mhils** [comment]
Sounds like something we need to fix in https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/save.py - thanks for the heads-up!

**Comment by ujjwal96** [comment]
@mhils is this a bug? iirc websocket flows are not part of the UI yet so even writing them to output file won't be of any help.
@edi9999 As a workaround you can see the websocket messages in the log on git-master

**Comment by mhils** [comment]
@ujjwal96: We should definitely persist the flow, as we do it with TCP flows.

**Comment by Kriechi** [comment]
@edi9999 this should work now - could you give it a try with the latest git-master mitmproxy version?

**Comment by EugeneAbramchuk** [comment]
@Kriechi I just checked out from master - recording writes all websocket requests now.
