### ISSUE TITLE
Unable to import certificate in Chrome on Ubuntu 16.04

### ISSUE THREAD

**Issue by ericstoekl** [mitmproxy/mitmproxy#2641]
Trying to set up certificates, according to [this post](https://github.com/mitmproxy/mitmproxy/issues/551#issuecomment-107452502) I should be able to go into the settings in chrome and import a certificate. I am trying to import the certificates that I generated by running `mitmproxy` for the first time. I converted the 1.pem` files to `.crt` format using the method recommended in the [stackoverflow post here](https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate/94861#94861), which is referenced from the [certificate manual installation guide here](http://docs.mitmproxy.org/en/stable/certinstall.html#ubuntu-debian).

I cannot import the private keys into chrome due to an error message that pops up when I try to import that says "Incorrect private key":

[Screenshot trying to import `mitmproxy-ca-cert.crt`](https://i.imgur.com/ySgobX2.png)
[Screenshot trying to import `mitmproxy.ca.crt`](https://i.imgur.com/nQki5Sy.png)
[Screenshot trying to import `mitmproxy-ca-cert.p12`](https://i.imgur.com/S7q9grL.png) (What is the correct password?)

##### Steps to reproduce the problem:
1. Start `mitmproxy` after installing on Ubuntu 16.04
2. Try to import certificates manually into google chrome using the method recommended [here](https://github.com/mitmproxy/mitmproxy/issues/551#issuecomment-107452502)
3. Still get " If you can see this, traffic is not passing through mitmproxy." on mitm.it

##### Any other comments? What have you tried so far?
Also tried installing using `certutil -d sql:$HOME/.pki/nssdb -A -t C -n mitmproxy -i ~/.mitmproxy/mitmproxy-ca-cert.pem`, hasn't worked for me but maybe I need to restart?

##### System information

```
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.5.2
Platform: Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.0.2g  1 Mar 2016
Linux distro: Ubuntu 16.04 xenial
```

**Comment by mhils** [comment]
Hi,

> " If you can see this, traffic is not passing through mitmproxy." 

This indicates that your traffic is not going through mitmproxy, i.e. it never reaches mitmproxy (and we thus cannot intercept it). This issue sounds unrelated to certificate import.

> I cannot import the private keys into chrome due to an error message that pops up when I try to import that says "Incorrect private key":

It looks like you are importing in the wrong category. It probably needs to be added under "authorities". 😃

**Comment by ericstoekl** [comment]
Thanks @mhils. It looks like traffic is not going through mitmproxy.

I have tried with the docker container and I am still having the same issue:

```
$ docker container ls
CONTAINER ID        IMAGE                 COMMAND                  CREATED              STATUS              PORTS                              NAMES
70d1c49426d9        mitmproxy/mitmproxy   "docker-entrypoint.s…"   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp, 8081/tcp   happy_yonath
$ http_proxy=http://localhost:8080/ curl http://example.com/
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

Any way to debug this? `mitmproxy` runs, I get the blue ncurses screen, and it looks like it should. However, I cannot reach `localhost:8080`.

Thanks in advance,
Eric
