### ISSUE TITLE
Traceback when viewing certain gifs 

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#2658]
Open the attached flow dump in mitmproxy console. When viewing the content, observe the traceback that flashes to screen. A number of issues here:

- [ ] Kaitai should be able to parse this gif. It's not technically correct, but I've seen this often, especially with single-pixel tracking gifs. 
- *Even if Kaitai fails*, we shouldn't crash - the user should see an "invalid image" message (or something more informative). (#2698)
- *Even if we crash*, the traceback shouldn't be flashed to screen and disappear. This is an issue with the way we handle super-long error events in console. (#2699)

[bar.log](https://github.com/mitmproxy/mitmproxy/files/1545955/bar.log)

**Comment by mhils** [comment]
@ujjwal96, do you want to take a look? 😃

**Comment by ujjwal96** [comment]
@mhils sure, will have a look at it soon :smiley:

**Comment by cortesi** [comment]
I see quite a few variations of this with other decoders, especially in the (very frequent) case where the content type doesn't match the content.

**Comment by mhils** [comment]
FWIW, the problem with the image in the initial post is that there's an additional null-byte at the end of the file that shouldn't be there.

**Comment by mhils** [comment]
This issue is now just about fragile GIF parsing, the other bullet points have their own issues or PRs now. I think it's not strictly required to be on the 3.0 milestone now, so I'll remove that here. Nonetheless, we should fix this.

**Comment by ujjwal96** [comment]
Ref: https://github.com/kaitai-io/kaitai_struct_formats/pull/73
@mhils The above PR handles the issue caused due to the attached GIF.
