### ISSUE TITLE
mitmproxy stuck on many connect

### ISSUE THREAD

**Issue by gennadicho** [mitmproxy/mitmproxy#2672]
##### Steps to reproduce the problem:

1. install mitmproxy from master branch
2. run script with body modify and replay by beautifulsoup
3. send a 1000-2000 request to proxy
4. mitmdump -p 30000  -k  -w out.file -s bla1.py
5. bla1.py: just insert in body one tag with bs4 and send it to client

##### Any other comments? What have you tried so far?
Hello. mitmproxy not accepted new connection, and not working anymore, after 1000-2000 connect. And count of thread growing crazy:
`810

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
819

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
829

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
^[[A846

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
846

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1010

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1023

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1034

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1042

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1042

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1177

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1204

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1218

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1230

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1238

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
1996

root@localhost:~# ps a -L|grep -i mitmproxy|wc -l
`
But proxy not working, and connect failed after timeout :(

##### System information

(venv) koka@localhost:~$ mitmproxy --version
Mitmproxy: 3.0.0dev0976 (472d122) 
Python:    3.5.3
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-3.16.0-4-amd64-x86_64-with-debian-8.0

**Comment by Mradr** [comment]
https://github.com/mitmproxy/mitmproxy/issues/2713
https://github.com/mitmproxy/mitmproxy/issues/2575

**Comment by selfcac** [comment]
I Have the same problem (beautifulsoup html in the response) ... not fixed in:

> Mitmproxy: 4.0.4
> Python:    3.7.1
> OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
> Platform:  Windows-10-10.0.17134-SP0

I also even close all connection with : `ctx.kill_flow(flow)` at the end of a response (Not a connection leak, maybe threading issue?).
Only after we stopped using `beautifulsoup` everything works again.

**Comment by imom0** [comment]
> I Have the same problem (beautifulsoup html in the response) ... not fixed in:
> 
> > Mitmproxy: 4.0.4
> > Python:    3.7.1
> > OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
> > Platform:  Windows-10-10.0.17134-SP0
> 
> Only after we stopped using `beautifulsoup` everything works again.
> Update: any change to `flow.response.content` will cause hang...

Did you find some way to solve this problem?

**Comment by selfcac** [comment]
At the end it was caused by my code bugs.... after fixing them all worked.False alarm on my part.
