### ISSUE TITLE
Clicking on tab head does not focus tab

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2676]
##### Steps to reproduce the problem:

1. Open mitmproxy
2. Press `-` to open two pane layout.
3. Click on the header of the "Events" tabs.
4. The "Events" tab does not get focus.

##### Any other comments? What have you tried so far?

This is particularly annoying on Windows, where "shift tab" to switch tabs does not register under WSL. The only way to switch tabs under Windows right now is to open a command prompt and enter `console.panes.next`.

##### System information

Mitmproxy: 3.0.0dev0994 (842c9f7)
Python:    3.5.2
OpenSSL:   OpenSSL 1.0.2g  1 Mar 2016
Platform:  Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial

**Comment by kajojify** [comment]
As I understood, we need mitmproxy to change focus, when we click **exactly** on the headers(Flows, Events), not on the other places of a tab? Am I correct?

**Comment by mhils** [comment]
I had the circled area in mind, but I can be convinced for something else :)

![image](https://user-images.githubusercontent.com/1019198/34447184-d3c1dadc-ece1-11e7-8c73-ffada6a016bb.png)

**Comment by kajojify** [comment]
What about this? 
![2017-12-31 18-16-56](https://user-images.githubusercontent.com/20267977/34462938-cfa56448-ee56-11e7-9149-19dde5eaa6ed.png)
Can we switch between "Key Bindings" - "Filter Expressions" tabs. while focusing on "Events"? 
We can still do it.

**Comment by mhils** [comment]
If the events pane is focused, we shouldn't be able to modify stuff in the Help pane. So yes, this looks like a (related) bug.

**Comment by kajojify** [comment]
@mhils So, do we need to open new issue or leave this bug for current issue?

**Comment by mhils** [comment]
@kajojify: This may have been a misunderstanding. If I have the events pane focused as in your example, pressing "tab" (or any other key) does not switch the tab in the left pane. How do you switch between tabs while focusing the right pane?

**Comment by kajojify** [comment]
@mhils by pressing left button of mouse. It is possible because of mitmproxy/tools/console/tabs.py

**Comment by bksahu** [comment]
@kajojify I agree with you but it doesn't works as it is supposed to. Also by pressing left or right key doesn't works as mitmproxy/tools/console/tabs.py
https://github.com/mitmproxy/mitmproxy/blob/eb53cc7ed26f451855755164f061ea9f49014f8d/mitmproxy/tools/console/tabs.py#L36 
On the other hand `Shift + Tab` just works fine for switching between tabs. 

**PS. This is my System information**
Mitmproxy: 3.0.0dev1082 (ddb8f43)
Python: 3.5.2
OpenSSL: OpenSSL 1.1.0g 2 Nov 2017
Platform: Linux-4.10.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
