### ISSUE TITLE
console.eventlog.clear command has disappeared

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#2681]
@mhils zapped this in #2678, but we need it back.

**Comment by mhils** [comment]
Not really zapped, it's `eventstore.clear` now ([src](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/eventstore.py#L24)). We can probably give it a better name though, maybe `eventlog.clear`.

**Comment by cortesi** [comment]
Hmm - eventstore.clear is probably OK. In that case, we need to update the outdated "z" keybinding, which still points to eventlog.clear.
