### ISSUE TITLE
console: ctx.log.alert output is not seen for comands

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#2688]
Issue a command that emits an alert from the console commander. Note that the alert output doesn't appear.

**Comment by mhils** [comment]
For reference, it only does not appear at the bottom at the screen (this is the bug), it does appear in the event log however.

**Comment by kajojify** [comment]
It seems, I've fixed it. Would it be better to change the style of text?
![screenshot from 2018-01-04 13-32-47](https://user-images.githubusercontent.com/20267977/34561929-cba22aa6-f154-11e7-9d9f-c2f0d1e44dbd.png)

**Comment by kajojify** [comment]
@mhils, before creating a PR I want to make sure I'm not losing any hiden details concerning this bug :)

Alert doesn't appear in the Statusbar, but appears in Event log.
All logs from `ctx.log.*` go to `EventStore`: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/eventstore.py#L10

Here we send our data to connected receivers: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/eventstore.py#L22

Here we subscribe to the signals from `EventStore`: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/master.py#L40

Each time we use `ctx.log.*`, all data gets into `sig_add_log`. And what we see. `sig_add_log` doesn't handle alert messages: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/master.py#L91
We can just fix it with putting `alert` into tuple -> `("error", "warn", "alert")`

The only thing we still have to do is to change the style of alert text.

**Comment by mhils** [comment]
I really haven't looked into this, but what you write sounds all correct. :-)

**Comment by kajojify** [comment]
@mhils ok, I'll create a PR and will be hoping it is correct ;)
