### ISSUE TITLE
Flowview Keybindings are broken

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2693]
##### Steps to reproduce the problem:

1. Open flow
2. Press `e`
3. `Invalid value type: ['console.edit.focus', '{choice}'] - expected <class 'mitmproxy.command.Arg'>`

`v` also doesn't work. `o` in the flowlist also does not work.
##### System information

Mitmproxy: 3.0.0dev1042 (ef9ad11)
Python:    3.5.2
OpenSSL:   OpenSSL 1.0.2g  1 Mar 2016
Platform:  Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial

**Comment by cortesi** [comment]
I've got a fix for this one inbound as part of the type refactoring.

**Comment by cortesi** [comment]
Fixed in #2712
