### ISSUE TITLE
print in addons

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#2701]
`print(...)` doesn't seem to work in addons. No error, no output.
`ctx.log.warn(...)` does print as expected.

Tested on git-master.

**Comment by mhils** [comment]
I can't reproduce this on 6ef6286. The following script works as expected on mitmproxy and mitmdump:

```python
print("hello")

def load(l):
	print("there")


def request(f):
	print("request")
``` 
@Kriechi: Can you retest on _latest_ master please?
