### ISSUE TITLE
Memory/Connection leaks under high traffic volumes

### ISSUE THREAD

**Issue by Mradr** [mitmproxy/mitmproxy#2713]
##### Steps to reproduce the problem:
1. After a while with many devices on the proxy - the server slows down and then freezes.
2. I really don't have a way to reproduce the steps, but I had similar issues a while back when I ran a public proxy and had many many bots connect and disconnect that resulted in errors of things not closing out correctly.
3. We have about 50 devices and it seems "speed" wise fine until about an hour or so in then it slows down and then stop functioning altogether with no error.
4. Seems like it doesn't want to take on new connections - last we see are "Disconnect" over the last open connections.

##### Any other comments? What have you tried so far?
I put try/except around my code, but I don't see any errors with my code. This leads me to mitmproxy having the issues and not my personal code. I be more than happy to pull any information I can to help figure this problem out. Like I said, it seems to happen every hour or so. Right now I create a watchdog to help protect against it crashing like it was so by restarting the proxy software and it seems like it runs fine again for about an hour before it does it again.

I understand Mitmproxy wasn't redesign for speed in mind, but seems like the more devices we do add - the shorter the time table before the proxy just freezes up. What steps can I take to future proof this just a bit? Thread count does reach into 400-600s or so when it last crash). It shouldn't be enough to really break Linux, but something I did notice.

##### System information
Mitmproxy version: 2.0.2 (release version)
Python version: 3.5.2
Platform: Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial
SSL version: OpenSSL 1.1.0f 25 May 2017
Linux distro: Ubuntu 16.04 xenial

##### Past ticket
https://github.com/mitmproxy/mitmproxy/issues/2575

**Comment by mhils** [comment]
Hi @Mradr,

Thanks for the detailed issue. From what you are describing it sounds like we are slowly leaking connections or memory under some circumstances. I agree that's something that needs to be fixed, but I'm sorry to say that this is nothing we (as the core devs) will be actively looking into in the near future. There are two reasons for this:

- We're currently focusing on getting our 3.0 release out. This issue does not affect the user experience of 99% of our users nor does it bother us personally at the moment. Investigating memory leaks is not straightforward and takes time.
 - Our ability to debug these kinds of issues will significantly improve with the work happening in the sans-io branch, and the work there may also eliminate a whole bunch of issues on the way. As such, time spent on finding small-ish connection or memory leaks on the current codebase is pretty much sunk costs.

Overall, supporting a large number of clients or a large number of requests/s is not a design goal we currently pursue. We're of course always open to external contributions.

**Comment by Mradr** [comment]
Hi @mhils 
Thanks for returning my message. Do you think something like this is fix in 3.0 release? Do you think we can beta test the build for you to see if it work?

1) I hope I do not come off rude or anything by answering back with this statement. I understand the focus is not on speed or anything, but this is a broken feature/problem that should be fix soon rather than later. I mean as far as the speed goes - mimproxy it pretty fast/good enough for light amount of devices/use. I would not consider 60 devices to be that many. The main problem just comes from the fact after a while it just random slows down for no reason at all and then we get disconnection/stops accepting new connections in.  I wouldn't consider that a performance problem but a real issue with the way Mitmproxy is handling connects in general of the fact. I hope that makes it a bit more clear that I am not referring that Mitmproxy itself is slow - but a symptom of the problem that we are seeing.

2) I be more than happy to download said build it you think we can pull more debug information to track down this issue and report back. I know python pretty well enough to get by as well to fixing some issues if I know where to start with in a project. Not the best - but I can usually get by once I know where to even start looking here.

**Comment by mhils** [comment]
> Do you think something like this is fix in 3.0 release? Do you think we can beta test the build for you to see if it work?

I don't recall anything specific, but you are welcome to test the developer snapshots from https://snapshots.mitmproxy.org/.

> [...], but this is a broken feature/problem that should be fix soon rather than later.

I'm not debating that this is a bug that should be fixed - sure it is. It doesn't affect users too much during what we consider normal use and it doesn't affect us, so it naturally gets pushed back on the stack (see my previous reply for more elaborate reasoning).

We work on mitmproxy for fun and without compensation, so I'm sorry to say that I won't spend X hours on your business problem. :-)

> is there an alternatives to mitmproxy that might be able to handle that many?

Depending on what you need, sslsplit may be a great fit (see https://security.stackexchange.com/questions/112845/what-is-the-difference-between-mitmproxy-and-sslsplit). Of course there are also plenty of commercial TLS termination appliances (BlueCoat/Symantec, ...), although I wouldn't recommend implementing large-scale TLS MITM in any way.

> I be more than happy to download said build it you think we can pull more debug information to track down this issue and report back.

Sure! One thing you mention is a large number of dangling threads, so a useful start would be to use our debug scripts implemented in [mitmproxy/utils/debug.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/utils/debug.py): You should get some useful debug info by sending SIGUSR1/SIGUSR2 to mitmproxy/mitmdump. If you can track down issues from that, we'd be more than happy to accept PRs.

**Comment by Mradr** [comment]
Oh this isn't for a business xD We just have 60 devices we're playing around with. I mean as a resources - we are more than happen to help figure out problems that are going on with with the project here.

We did download and install 3.0 and it does seem to be feel more stable, but we did run into another issue again and I think this might be related to what we are seeing. I am not sure why 2.0.2 didn't report the issue, but 

> Exception in thread ServerThread (('::', 8080, 0, 0)):

Traceback (most recent call last):

  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner

  File "/home//mitmproxy/mitmproxy/master.py", line 30, in run

  File "/home//mitmproxy/mitmproxy/net/tcp.py", line 608, in serve_forever

  File "/usr/lib/python3.5/socket.py", line 195, in accept

OSError: [Errno 24] Too many open files

**Comment by Kriechi** [comment]
Performance is obviously an ever-ongoing issue. Unless we find concrete evidence where we might be able to improve/speedup/save memory, it is pretty difficult to rectify.
I'm closing this for now, until we have a reproducible benchmark / test case to work with.

**Comment by ericdraken** [comment]
Howdy, I can confirm that memory usage grows and grows. I'll investigate. As my test, I use the stock `mitmdump` with no scripts and let YouTube play a playlist: YouTube has multi-megabyte response payloads to show the increase dramatically.

After 3 minutes, we're up to 500 MiB of RSS.

After 20 minutes, we're up to 3 GiB of RSS!

Also, the 4K and 8K videos take 100% of x86 CPUs. lol

I started with HD videos, then switched to 4K videos, then fell to HD again, then switched up to 8K videos where the CPU was in pain, so dropped back to 4K. Pretty sweet memory leak graph, hey?

![image](https://user-images.githubusercontent.com/22000765/149879886-afb6fdc8-0261-4e63-85b1-bdd9ade4a7b5.png)

So, yup, a server can slow down and die in minutes, as demonstrated. Here is a memory usage plot to show this effect even more clearly.

**Comment by mhils** [comment]
@ericdraken: #4786 may be more relevant. If the workaround posted in https://github.com/mitmproxy/mitmproxy/issues/4786#issuecomment-928002790 does not work I'd be happy to hear more details.

**Comment by ericdraken** [comment]
> @ericdraken: #4786 may be more relevant. If the workaround posted in [#4786 (comment)](https://github.com/mitmproxy/mitmproxy/issues/4786#issuecomment-928002790) does not work I'd be happy to hear more details.

Neat! That comment helps a lot as I was profiling memory allocations and had a lot to step through.
