### ISSUE TITLE
Some traffics are lost in mitmproxy

### ISSUE THREAD

**Issue by wimbledon** [mitmproxy/mitmproxy#2719]
##### Steps to reproduce the problem:
I've been using mitmproxy for a while and it's been a great tool! However, today I came across this app where mitmproxy only shows some of the traffics but not all!

I'm using an iOS 10 iPhone connected to same wifi network as my mac. I then proxyed the iPhone's traffic to mitmproxy. Of course, I went to mitm.it and installed the certificate. The command I used is `mitmproxy -p 8090`.

The issue is that some of the network requests are showing up fine, but some are not showing up! Nothing on the event log for the missing requests either. Yet, the app seems to be completely functional with perfect networking.

##### Any other comments? What have you tried so far?
Could it be certificate pinning? If the app has implemented certificate pinning or other security measures, then the app should not have perfect networking once the iPhone is proxied to mitmproxy.

Do mitmproxy automatically ignore certain traffic?

I tried `--tcp '.*'` option to see if anything came up in the event log, but nothing.

##### System information
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.2
Platform: Darwin-16.7.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.12.6 ('', '', '') x86_64

**Comment by mhils** [comment]
Hi,

If you have configured mitmproxy as a regular proxy for your device, some apps may use functionality that bypasse the system proxy settings (see e.g. https://stackoverflow.com/questions/28061353/how-to-bypass-proxy-in-ios-programmatically). The only workaround is to use transparent mode and/or block connections from the device itself on your router. :-)
