### ISSUE TITLE
console: shift+tab is broken in WSL for some Windows terminals

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#2720]
See https://github.com/Microsoft/WSL/issues/1770. This seems to affect some but not all Windows terminals. 

We use shift+tab by default to switch to the next pane in the console app. We can:

- Say that this is not our problem, and wait for upstream to fix it.
- Find a different binding for next pane - which would be a shame, because shit+tab is very natural.

@mhils what say you?

**Comment by mhils** [comment]
This unfortunately affects the default terminal, which I guess the vast majority uses. 

I think the most pragmatic approach would be to bind to something else on Windows only as a temporary workaround, and unify to shift-tab once Microsoft has fixed it. How do you feel about this?

If you dislike this approach, #2676 would provide at least a somewhat convenient way to switch between panes.
