### ISSUE TITLE
ImportError: cannot import name basethread

### ISSUE THREAD

**Issue by damadamn** [mitmproxy/mitmproxy#2722]
Hello, I've got this problem when I try to import basethread module : 

1.Traceback (most recent call last):
  File "/home/.../mitm-proxy-server.py", line 14, in <module>
    from mitmproxy import controller, proxy, flow
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/controller.py", line 12, in <module>
    from netlib import basethread
ImportError: cannot import name basethread

I don't know why this problem occured, but I need to fix it if I want to use mitmproxy like I need

**Comment by damadamn** [comment]
I have find the problem, the file basethread.py from /usr/lib/python2.7/site-packages/netlib doesn't exist, but I don't konw how to generate it

**Comment by ujjwal96** [comment]
The mitmproxy version you're using is not supported anymore. Please try using python >= 3.5 and mitmproxy version 2.x
