### ISSUE TITLE
There is something wrong with dealing AMQP?

### ISSUE THREAD

**Issue by a3135134** [mitmproxy/mitmproxy#2725]
##### Steps to reproduce the problem:

1.I'm trying to see the Azure IoT SDK which supports AMQP on SSL (port 5671) and set up a MITM using command like"mitmdump -T --raw-tcp".
2.There will be a HTTP parse error blocking the mitmdump.
(BTW, I changed source code fixing the blocking problem(see below please). However, I still cannot see plain AMQP on SSL.)

##### Any other comments? What have you tried so far?
I looked into the sourcecode on github, it seems that file "proxy/root_context.py" line 113 "Check for raw tcp mode" is wrong. I think it should be "if self.config.options.rawtcp or not is_ascii:" , because AMQP starts with "A"? I changed that myself and mitmdump won't be blocked. Is it a bug? 

(However, I still cannot see plain AMQP on SSL by wireshark. Does anyone sniff AMQP on SSL successfully? I did the same experiment on MQTTS and it works well.)
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/root_context.py

##### System information

mitmproxy version 2.0.2 (release version)
Python version 3.6.4rc1
Platform: Linux-4.13.0-kali1-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
SSL version: OpenSSL 1.0.2n 7 Dec 2017

**Comment by mhils** [comment]
I don't really understand what your exact issue is, but it sounds like you want to use `--tcp .*` to force mitmproxy into TCP mode instead of relying on heuristics.

**Comment by a3135134** [comment]
Yes，I want to use "--raw-tcp" to analyze non-HTTP (on SSL) protocol, i.e. AMQP. And mitmdump is blocked because it parses the packet as HTTP.  I believe there's something wrong in "proxy/root_context.py line 113". I changed it to 
`if self.config.options.rawtcp or not is_ascii:`
then it worked.
If I were right, update the code please.

Sorry for my poor English.  : )

**Comment by Kriechi** [comment]
Please see https://github.com/mitmproxy/mitmproxy/pull/2748#pullrequestreview-86354936.
