### ISSUE TITLE
how to use mitmproxy on a vpn server to manipulate the traffic

### ISSUE THREAD

**Issue by AntiverX** [mitmproxy/mitmproxy#2729]
I have a vpn server and I want to monitor the traffic on the server using mitmproxy to see weather people connecting to the server is visiting some forbidden sites and modify the reponse to some kind of words like "you are visiting illegal sites."

Thanks.

**Comment by mhils** [comment]
From the issue template: Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!
