### ISSUE TITLE
TestTCPClient.test_spoof_address and TestTCPClient.test_spoof_address errors found while tox testing

### ISSUE THREAD

**Issue by bksahu** [mitmproxy/mitmproxy#2730]
I tested with tox on my machine running Ubuntu 16.04 having both python 3.5 and 3.6 and got two commands failed errors TestTCPClient.test_spoof_address and TestTCPClient.test_spoof_address.

**Steps to reproduce the problem:**
I am using Ubuntu 16.04. I had both py35 and py36 installed.

1.    I clone the repo: git clone https://github.com/mitmproxy/mitmproxy
2.   cd mitmproxy
3.   Run the dev.sh from terminal     
       sudo ./dev.sh
4.   . venv/bin/activate
5.    tox (Also tried tox -e py35/6)

**Expected behavior:**
py35: commands succeeded
py36: commands succeeded

**Error found:**
=================================== FAILURES ===================================
___________________________ TestProxyServer.test_err ___________________________

```
self = <test.mitmproxy.test_proxy.TestProxyServer object at 0x7fb3be65bac8>

    @skip_windows
    def test_err(self):
        # binding to 0.0.0.0:1 works without special permissions on Windows
        conf = ProxyConfig(options.Options(listen_port=1))
        with pytest.raises(Exception, match="Error starting proxy server"):
>           ProxyServer(conf)
```
E           Failed: DID NOT RAISE <class 'Exception'> matching 'Error starting proxy server'

test/mitmproxy/test_proxy.py:65: Failed
_______________________ TestTCPClient.test_spoof_address _______________________

```
self = <test.mitmproxy.net.test_tcp.TestTCPClient object at 0x7fb3bd7cfba8>

    def test_spoof_address(self):
        c = tcp.TCPClient(("127.0.0.1", self.port), spoof_source_address=("127.0.0.1", 0))
        with pytest.raises(exceptions.TcpException, match="Failed to spoof"):
>           c.connect()

```
E           Failed: DID NOT RAISE <class 'mitmproxy.exceptions.TcpException'> matching 'Failed to spoof'

test/mitmproxy/net/test_tcp.py:628: Failed
============== 2 failed, 1328 passed, 1 skipped in 90.52 seconds ===============
ERROR: InvocationError: '/home/bksahu/Documents/Github/mitmproxy/.tox/py35/bin/pytest --timeout 60 --cov-report= --cov=mitmproxy --cov=pathod --full-cov=mitmproxy/ --full-cov=pathod/'

<hr>

**Any other comments? What have you tried so far?**
Tried tox -e py35/6 and got the same error for both. I looked up the documentation of both mitmproxy and tox but I couldn't find anything relevant.

<hr>

**System information**
Mitmproxy: 3.0.0dev1082 (ddb8f43) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.10.0-28-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by mhils** [comment]
Thanks for the report. Can you run mitmproxy on a privileged port without any further measures on your system? In other words, does `mitmproxy -p 80` spawn a fully functioning mitmproxy instance?

The tests we're looking at should fail because regular users shouldn't have sufficient permissions.

**Comment by bksahu** [comment]
Thanks for your comment. I got this on `mitmproxy -p 80`.
`
Error starting proxy server: OSError(98, 'Address already in use')
`
So the errors I reported are bugs or they are supposed to work that way ?

**Comment by mhils** [comment]
Well you need to check with a free port - you seem to have something running on port 80 already. what about `mitmproxy -p 85` for example? Are you running this as root?

**Comment by bksahu** [comment]
Yes that `mitmproxy -p 85` works fine. Yes I am running this as root.

**Comment by mhils** [comment]
Ok, so the culprit is that you are running this as root, that makes binding
to privileged ports succeed (which would normally fail). Similar to
skip_windows, we probably need a "skip_root" decorator to skip those tests
when running as root.

If you run mitmproxy as a regular user, you should be fine. :-)

**Comment by bksahu** [comment]
I tried `tox -e py35` testing with out root and I got this

```
Traceback (most recent call last):
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
PermissionError: [Errno 13] Permission denied: '/home/batakrishna/Documents/Github/mitmproxy/.tox/py35/.tox-config1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/tox/session.py", line 40, in main
    retcode = Session(config).runcommand()
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/tox/session.py", line 392, in runcommand
    return self.subcommand_test()
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/tox/session.py", line 565, in subcommand_test
    self.finishvenv(venv)
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/tox/session.py", line 482, in finishvenv
    venv.finish()
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/tox/venv.py", line 214, in finish
    self._getliveconfig().writeconfig(self.path_config)
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/tox/venv.py", line 32, in writeconfig
    path.write("\n".join(lines))
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/py/_path/local.py", line 501, in write
    f = self.open(mode)
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/py/_path/local.py", line 361, in open
    return py.error.checked_call(open, self.strpath, mode)
  File "/home/batakrishna/Documents/Github/mitmproxy/venv/lib/python3.5/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EACCES: [Permission denied]: open('/home/batakrishna/Documents/Github/mitmproxy/.tox/py35/.tox-config1', 'w')

```
