### ISSUE TITLE
Connection reset during SSL handshake (or so it seems)

### ISSUE THREAD

**Issue by aspyct** [mitmproxy/mitmproxy#2731]
##### Steps to reproduce the problem:
Not sure how to reproduce that issue, but I believe it happened when I switched off the wifi on my android device. Said device was communicating with a server through mitmdump.

The issue occurred once, and mitmdump continued operating normally.

##### Any other comments? What have you tried so far?

Not a blocking issue, so I went on with business as usual, thankful that I didn't even have to restart mitmdump.

##### System information

mitmdump 1.0.2

Crash log attached.
[mitmdump-log.txt](https://github.com/mitmproxy/mitmproxy/files/1593414/mitmdump-log.txt)

**Comment by Kriechi** [comment]
Thanks for the bug report. It seems like you are running an outdated version of mitmproxy. Could you please try again with the latest v2.0.2 and also via the latest git-master? Both should be available via Homebrew.

Also, what macOS version are you running? Please show us `mitmproxy --sysinfo` or `mitmproxy --version` as well.

**Comment by aspyct** [comment]
Oh waow, ok. I'm seriously late on the versions. Sorry about that! I'll update and see if I can somehow reproduce the issue. Cheers!
