### ISSUE TITLE
Possibly a bug? infinite clientconnect when trying to access http://IP:8080/ in trasnparent mode

### ISSUE THREAD

**Issue by AntiverX** [mitmproxy/mitmproxy#2740]
Ubuntu 17.10
I'm using mimdump cloned from git.

I have a vpn server and use the following command to set up a transparent proxy

> sudo iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner antiver --dport 80 -j REDIRECT --to-port 8080

If my client access http://IP:8080/ directly from browser, the mitmdump will show infinite clientconnect until the server breaks down because of the shrotage of memory.

![image](https://user-images.githubusercontent.com/22369960/34465123-70566c92-eeda-11e7-9014-e412a74d3440.png)

**Comment by mhils** [comment]
This unfortunately is relatively hard to mitigate as it just looks like a regular connection - we already have some simple logic in place to detect issues like this [here](https://github.com/mitmproxy/mitmproxy/blob/4cb96dedd0143cf9b6278d3622457e1e485b3090/mitmproxy/proxy/protocol/base.py#L103). If you have a good idea on how we can improve this, I'd be happy to hear your thoughts or even better merge a PR! Other than that, I don't see anything else we can do here unfortunately, so I'll close this issue as there's nothing actionable.
