### ISSUE TITLE
Just another error

### ISSUE THREAD

**Issue by Mradr** [mitmproxy/mitmproxy#2747]
##### Steps to reproduce the problem:
![image](https://user-images.githubusercontent.com/937790/34506274-ee29a1e0-eff0-11e7-90d7-ff55211762f3.png)

##### Any other comments? What have you tried so far?
Just reporting more errors in

##### System information

2.0.2 on windows

**Comment by bksahu** [comment]
Hi there. You need to be more specific than that.
For,
**Steps to reproduce the problems** you need to specify which steps and commands you tried to you reach that error.
**Any other comments? What have you tried so far?** do as said.
**System information** copy paste the output of `mitmdump --version`

**Comment by Kriechi** [comment]
Thanks for the bug report. This should be already fixed with the latest v3.0.0rc1 and on git-master.
