### ISSUE TITLE
Traceback appears in Status Bar, when trying to run Mitmproxy with --proxyauth ldap (ldaps) argument

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2767]
##### Steps to reproduce the problem:

Run Mitmproxy with argument: `mitmproxy --proxyauth ldap` or `mitmproxy --proxyauth ldaps`

I am seeing:
![screenshot from 2018-01-06 15-41-10](https://user-images.githubusercontent.com/20267977/34640265-0d47714c-f2f8-11e7-91c6-9bfe3a0f9eb6.png)

##### Any other comments? What have you tried so far?
This issue is occured, because mitmproxy doesn't control the syntax of ldap authentication argument. 
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/proxyauth.py#L147-L152

##### System information

Mitmproxy: 3.0.0.dev1101 (commit d9d4d15) binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-104-generic-x86_64-with-debian-stretch-sid

**Comment by Kriechi** [comment]
Looks like the [check](https://github.com/mitmproxy/mitmproxy/blob/012b938254e1bf14d47447d5f3661d3299d8f582/mitmproxy/addons/proxyauth.py#L153-L156) needs to be moved right after the `split`.
