### ISSUE TITLE
Traceback appears, when trying to set mitmproxy's address as upstream server for reverse/upstream mode

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2768]
##### Steps to reproduce the problem:

1. Run mitmproxy in **reverse** or **upstream** mode, using its own address as  upstream server address:
`mitmproxy --mode reverse:http://127.0.0.1:8080` or
`mitmproxy --mode upstream:http://127.0.0.1:8080`
2. Make a request using pathoc `pathoc 127.0.0.1:8080 "get:/"` or a browser.

I am seeing:
![screenshot from 2018-01-06 23-29-35](https://user-images.githubusercontent.com/20267977/34644136-7cac6222-f339-11e7-8995-2b30c6ab5c63.png)

##### Any other comments? What have you tried so far?
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/protocol/base.py#L115
should be handled.

##### System information

Mitmproxy: 3.0.0.dev1101 (commit d9d4d15) binary
Python: 3.5.2
OpenSSL: OpenSSL 1.1.0g 2 Nov 2017
Platform: Linux-4.4.0-104-generic-x86_64-with-debian-stretch-sid

**Comment by mhils** [comment]
I believe we can fix this by moving [this line](https://github.com/mitmproxy/mitmproxy/blob/821d76df02f70ccca5623cbc65d02b80e3998704/mitmproxy/proxy/server.py#L117) into the try: block right afterwards. So that should be fairly simple, but we need a test! :-)
