### ISSUE TITLE
mitmproxy does not work with SPDY

### ISSUE THREAD

**Issue by yoavfrancis** [mitmproxy/mitmproxy#277]
Hi there,

I was trying to figure out why a specific application was not working with mitmproxy. After some delving around - it seemed that the Application is using SPDY (over port 443), while mitmproxy wrongly detected the first SPDY packet as a part of an SSL handshake (for which it reports "wrong version" and terminates)

Does mitmproxy support SPDY? perhaps it can be a nice feature to add SPDY recognition (or ignoring it in the meanwhile and passing SPDY packets not through the proxy)

Thanks,
Yoav

**Comment by pope** [comment]
HTTP2 has been finalized.

**Comment by dustymabe** [comment]
> HTTP2 has been finalized.

Should this issue be re-opened?

**Comment by mhils** [comment]
We have very experimental http2 support in the core for a few months now (`--http2`). Our plan is to replace that with a proper implementation based on @Lukasa 's excellent hyper-h2 (which wasn't ready when we started), but I'm currently lacking the resources to tackle this unfortunately.
Clients should just degrade to HTTP1 automatically at the moment. If that isn't the case, please file a separate issue.

Thanks!
Max

**Comment by Lukasa** [comment]
Depending on how my schedule pans out I *may* be able to spend some time on this myself, but it's really unclear at this time exactly how my priorities are going to shape up.

**Comment by mhils** [comment]
refs #883
