### ISSUE TITLE
Traceback appears, when trying to scan myself with nmap. 

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2771]
##### Steps to reproduce the problem:

1. Run mitmproxy.
2. Scan yourself with **nmap**: `nmap -sT localhost`

Traceback:
![image](https://user-images.githubusercontent.com/20267977/34655444-99f520ce-f412-11e7-9e5b-32d39d237b64.png)

##### System information

Mitmproxy: 3.0.0.dev0004 (commit 68c32d8) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-104-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by ankitsaini2609** [comment]
I have solved this issue see images :)
![image](https://user-images.githubusercontent.com/20846432/35237572-10a30e6a-ffd1-11e7-809a-572aa175e395.png)

Now it will not show traceback error.

**Comment by ankitsaini2609** [comment]
I have solved this issue, this issue arises because there is an exception which goes unhandled in case of localhost. This is the [line](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/tcp.py#L294) where this exception arises. So I have added a try-except statement to handle it.

##### Solution :-
```
        if connection:
            try:
                self.connection = connection
                self.ip_address = connection.getpeername()
                self._makefile()
            except:
                self.ip_address = connection
                self._makefile()
        else:
            self.connection = None

```
##### System Information 
Mitmproxy: 3.0.0.dev1165 (commit 6dd336f) 
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.14.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling

**Comment by hemo91** [comment]
@ankitsaini2609 
Is this true `connection.getpeername() == connection`  ?

I don't suppose so

**Comment by ankitsaini2609** [comment]
Yes, their output is same I have checked it, `getpeername()` return the remote address to which the socket is connected. and in the case when exception happen  value of `connection`  is same as `connection.getpeername()`

**Comment by hemo91** [comment]
@ankitsaini2609 
so you mean 1234 == '1234' would be same, cause print(1234) and print('1234') is same ?

Man , please check your basics first .

**Comment by hemo91** [comment]
@ankitsaini2609 
Man, please don't delete your comments, if it's wrong we will correct you here.

**Comment by ankitsaini2609** [comment]
I am working on it, give me some time yes I was wrong, let me modify my code little bit more

**Comment by ankitsaini2609** [comment]
I was wrong before in which I was assigning  `self.ip_address = connection ` there is no need to assign `self.ip_address = connection` when you encounter that exception just pass that line and start execution from the next line, so if there is another exception going to happen that is handled by [line](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/tcp.py#L590)
##### Modified Code 
```
       if connection:
            try:
                self.connection = connection
                self.ip_address = connection.getpeername()
                self._makefile()
            except:
                self._makefile()

        else:
            self.connection = None
```
##### Image Attached 
![image](https://user-images.githubusercontent.com/20846432/35242288-2422a294-ffdf-11e7-8964-5026df4c1ba8.png)

**Comment by hemo91** [comment]
@ankitsaini2609 
That was quick 😉 
Need to test, on my system.
Can you send me the link of your branch where you have pushed your modified code, so that I can pull it and test it 👍 

Also, instead of only giving a reference like this 

It would be better if you give a small context and then the reference link. It lessens the pain of directly switching back and forth tabs. Something like this : 
[Referenced Code](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/net/tcp.py#L590)
```
 def connection_thread(self, connection, client_address):
        with self.handler_counter:
            try:
                self.handle_client_connection(connection, client_address)
            except:
                self.handle_error(connection, client_address)
            finally:
                close_socket(connection)
```

**Comment by ankitsaini2609** [comment]
Actually, I am a noob but yeah I will remember it from next time.

**Comment by hemo91** [comment]
@ankitsaini2609 
No worries man, we all are learning.
You learn a lot by getting involved with the community. Perhaps you have just started contributing in opensource projects.

**Follow community guidelines** , for starters don't delete your comments 😃

**Comment by ankitsaini2609** [comment]
This is the [link](https://github.com/ankitsaini2609/mitmproxy/tree/issue2771) of my branch where I have pushed my modified code. :-)

**Comment by Kriechi** [comment]
`nmap -sT localhost` currently causes mitmproxy to show this traceback:
```
~/mitmproxy/mitmproxy/net/tcp.py", line 296, in __init__
    self.ip_address = connection.getpeername()
OSError: [Errno 22] Invalid argument
```
However, nmap seems to successfully report that tcp/8080 is open (because of mitmproxy).

**Comment by cortesi** [comment]
This is a race. Nmap connects to the socket, and immediately disconnects. We fire up the client connection thread, and attempt to retrieve the peer name from the connection. At this point the connection is closed, and we get OSError.
