### ISSUE TITLE
Traceback appears, when trying to create and then replay a flow with a request to mitm.it.

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2774]
##### Steps to reproduce the problem:

1. Run mitmproxy.
2. Create a new flow by pressing `n`: `: view.create get http://mitm.it`.
3. Try to replay the corresponding flow by pressing `r`.

![image](https://user-images.githubusercontent.com/20267977/34683425-ad2c316c-f4aa-11e7-884e-4978ffa1f4c3.png)

##### System information

Mitmproxy: 3.0.0.dev0004 (commit 68c32d8) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-104-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by Kriechi** [comment]
Probably a duplicate of #2431. Fixing that should also fix this issue here.

**Comment by kajojify** [comment]
@Kriechi ok, let's close it for now. If #2431 doesn't fix it, I'll reopen.
