### ISSUE TITLE
Flow filters don't persist between invocations of `f`

### ISSUE THREAD

**Issue by fuho** [mitmproxy/mitmproxy#2777]
##### Steps to reproduce the problem:
1 - Hit `f` type in filter, make a typo
2 - Hit 'f' again to fix the typo

##### Expected behaviour
On second hit of f, when filter in use already the command line shows the current filter.

##### Current behaviour
On second hit of f, whn filter in use already, the filter is cleared.

##### System information
Mitmproxy 3 RC2

**Comment by mhils** [comment]
Thanks again - this is very useful UX feedback!

**Comment by fuho** [comment]
Also haven't found a way to copy response body to clipboard. Well no easy
way, with a single key, I think it's doable with the new command interface.
I'll make a new report if I remember.
