### ISSUE TITLE
Implement `share` command

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2779]
@MatthewShao implemented a really cool static viewer based on mitmweb last summer: http://honeynet.org/node/1359.

Long story short, one can upload a mitmproxy flow file at share.mitmproxy.org and will get a shareable link in return. 😃 To make this more accessible, I think it would be awesome to have a mitmproxy command that takes a bunch of flows as argument, uploads them directly from within mitmproxy, and returns a URL to share.

**Comment by mhils** [comment]
For some related code, see e.g. the save command: https://github.com/mitmproxy/mitmproxy/blob/67300fab3119f055a6cbb43b7cbc9d33e849d165/mitmproxy/addons/save.py#L53-L67 
It would be nice to use HTTP upload functionality from Python's stdlib opposed to requests to keep our library footprint small.

**Comment by kajojify** [comment]
@mhils Just want to clarify. I press, for example, `u` button, mitmproxy takes all available flows, uploads them at _share.mitmproxy.org_ and then gets _url_, displaying it in Status Bar.  But how will we be able to copy it and use somewhere?

**Comment by cortesi** [comment]
I've been thinking about this as well. It's a very exciting direction. This is certainly a 4.0 or beyond feature - we have quite a bit of work/thinking to do about the server component here.

**Comment by mhils** [comment]
@kajojify: For now, let's just add a command that can be manually invoked (press `:` and then enter the command and a flowspec) and logs the URL.

**Comment by kira0204** [comment]
Hi, I would like to work on it :) Will keep you updates as I progress

**Comment by kira0204** [comment]
I am almost done, one doubt I have is that since the data is being encoded by multipart/form-data , I need to load the file into the memory first, can I use 'poster' to achieve this or go forward with standard libraries?
@mhils

**Comment by kira0204** [comment]
Hi,
So the approach I am using is that I am saving the flows in a temporary file, (the name will be the unique 7 letter id), the doubt I have is that to send a POST request I need to read the contents of the file so should I use `read_flows_from_paths(paths)` or
```
path = os.path.expanduser(path)
with open(path, "rb") as f:
        content  = f.read()
```
and use `content` to send the POST request?
