### ISSUE TITLE
Add support for request content encodings

### ISSUE THREAD

**Issue by wufeifei** [mitmproxy/mitmproxy#2782]
Now, `-z` option will try to convince servers to send us un-compressed data, but client send server un-compressed data not support.

https://github.com/mitmproxy/mitmproxy/pull/7

**Comment by mhils** [comment]
Hi,

I don't quite understand what your issue is. FWIW, we can hardly influence what the client sends us because the client starts sending data after opening the connection right away. :-)

**Comment by wufeifei** [comment]
If you use the -z option, mitmproxy parses the gzip-compressed response. When the response header contains the content-type: gzip, the final unzipped response can be viewed in flow.response.content.

The -z option handles response content only, but the request content may also be gzipped.

When asked whether to support gzip request content (gzip), so that we can see through flow.request.content gzip decompressed content (just to view the content, rather than change the content sent) ?

**Comment by mhils** [comment]
If you use a somewhat recent mitmproxy release, we always handle gzip decompression automatically. The anticomp option only makes sure that the server doesn't send us gzip.
