### ISSUE TITLE
Editing message attributes is cumbersome on 3.0 / console.choose.cmd needs shortcuts.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2785]
##### Steps to reproduce the problem:

Editing a flow's URL currently requires the following keystrokes:
`e` -> `down` -> `down` -> `down` -> `down` -> `down` -> `down` -> `down` -> `down` -> `down` -> `down` -> `down` -> `down` -> `enter`.

This is a clear downgrade from 2.0 and before where each option in that dialog could be selected by pressing a specific key (e.g. `u` to edit the url). It'd be very useful to add these kinds of shortcuts to `console.choose.cmd` again. A bit tricky because we can't pass an explicit list as before, but still something we should do.

##### System information

Mitmproxy: 3.0.0.dev1147 (commit b7db304)
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-43-Microsoft-x86_64-with-Ubuntu-16.04-xenial

**Comment by kajojify** [comment]
@mhils How should it look like? 
I see two and a half variants :)
1) Like in mitmproxy 2.0.x. When we press `e` in flowview, Part overlay appears along with message in status bar: 
![image](https://user-images.githubusercontent.com/20267977/35242172-801cffd6-ffc1-11e7-9dd4-c71536864476.png)
Then when I press the certain button, the corresponding editor opens.

2) Each line in Part overlay has its shortcut written on this line.
When I press the certain button:
a) The corresponding line is focused  - I need to press `Enter` to confirm my decision and enter the editor.
b) I directly get into the corresponding editor.
Do you have any thoughts about it?

**Comment by mhils** [comment]
@kajojify: I think both 1) and 2b) are good alternatives. My initial idea was that we have `console.choose.cmd` auto-select keyboard shortcuts so that it maybe looks like this:
![image](https://user-images.githubusercontent.com/1019198/35243179-3cf94160-ffbc-11e7-9594-cbb678216487.png)
(this could get aesthetically nicer if we reorder the entries)

or like this:
![image](https://user-images.githubusercontent.com/1019198/35243292-a70fc3ee-ffbc-11e7-8ad5-52a4da7ab711.png)

Looking at it now, I think the last option is the nicest one, both in terms of implementation and UX. No definite opinion though. 🙂

**Comment by kajojify** [comment]
Ok, I'll try to work on it :)

**Comment by kajojify** [comment]
I think, it also makes sense to implements shortcuts for _mode_ overlay
![image](https://user-images.githubusercontent.com/20267977/35506376-b8340538-04f1-11e8-9ed2-88ca6368ea94.png)

**Comment by mhils** [comment]
@kajojify: both use `console.choose` so it should be the same code :)

**Comment by kajojify** [comment]
@mhils 
![image](https://user-images.githubusercontent.com/20267977/35675470-cadb2de0-0750-11e8-9308-b8ff9fc5c6b7.png)

What do you think? :)
Or with `key` highlighting.

![image](https://user-images.githubusercontent.com/20267977/35675687-9f3a7b36-0751-11e8-9f5e-22d419242418.png)

**Comment by mhils** [comment]
@kajojify: very awesome, I do like the key highlighting variant! 😃  Have you tried moving the numbers to the front? How does that look?

**Comment by kajojify** [comment]
@mhils 
![image](https://user-images.githubusercontent.com/20267977/35679456-caa1b4b6-075f-11e8-995a-bd669502c93f.png)

![image](https://user-images.githubusercontent.com/20267977/35679472-d5ccb386-075f-11e8-8d01-1bcb67b71daa.png)

**Comment by mhils** [comment]
Fantastic - send a PR! Depending on how difficult it is, it'd be cool to
have the "(6) " chunk as a part of the selection as well, but post your
code first and we'll see. Great work! :-)

**Comment by kajojify** [comment]
@mhils do we have to implement the feature, which lets users change these shortcuts? :)

**Comment by mhils** [comment]
Please no! :)
This should be very generic for console.choose, always 1-9a-z.
