### ISSUE TITLE
Store ClientHello Extensions

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2788]
@0x4d31 was interested in adding JA3 hash support to mitmproxy, so we need to give him a way to access all TLS extensions sent during the initial handshake.

**Comment by abbbe** [comment]
@0x4D31 @mhils any clue if that story from 2018 has resulted in any publicly available mitmproxy addon for JA3 fingerprinting?

**Comment by raxod502** [comment]
At the very least, is it possible to export the raw packets so that they can be processed by another tool? https://github.com/muzuiget/mitmpcap drops all the TLS data.
