### ISSUE TITLE
mitmproxy transparent and upstream modes: mutually exclusive

### ISSUE THREAD

**Issue by raulsiles** [mitmproxy/mitmproxy#2813]
##### Steps to reproduce the problem:

1. I'm trying to run mitmproxy in transparent mode with an upstream proxy.
```
# mitmproxy -T --host -U http://127.0.0.1:8081
mitmproxy: Transparent, SOCKS5, reverse and upstream proxy mode are mutually exclusive. Read the docs on proxy modes to understand why.
```
2. The error message specifies both modes are mutually exclusive, although the documentation does not talk specifically about this scenario, where these two modes are combined:
http://docs.mitmproxy.org/en/stable/modes.html
3. I think there are scenarios where this setup might work, and could be required. Why are they mutually exclusive?

##### Any other comments? What have you tried so far?

Several other previous mitmproxy GitHub issues already reference chaining proxies. The idea is to intercept all the traffic (both HTTP and HTTPS) from a non-aware proxy client in transparent mode, via mitmproxy, and redirect all its traffic to Burp, as an upstream proxy:

client <---> mitmproxy <---> Burp <---> Internet <---> server

This could also be a very common scenario if you need to use mitmproxy in transparent mode, but you are forced to get out to the Internet through a corporate proxy:

client <---> mitmproxy <---> Corporate proxy <---> Internet <---> server

##### System information

Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.4
Platform: Linux-4.14.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling
SSL version: OpenSSL 1.1.0g  2 Nov 2017
Linux distro: Kali kali-rolling kali-rolling

**Comment by mhils** [comment]
Hi,

Thanks for the report. The error message makes more sense for all other mutually exclusive combinations - in theory transparent and upstream mode could be combined. As I see it, proxychains and redsocks cover the use case of transparently wrapping connections sufficiently, so we're currently not planning to implement this as it adds quite a bit of complexity.

**Comment by raulsiles** [comment]
@mhils I'm not sure I clearly described the scenario above, as I don't see the need to involve other tools. 

The client to mitmproxy link (in transparent mode) is implemented in my case using iptables, so all the selected traffic from the client (let's say tcp/80 and tcp/443) transparently ends up in mitmtproxy. So the question is, why mitmproxy cannot forward all its traffic subsequently to an upstream proxy?

I see this option as the equivalent setting available in Burp under "User options - Upstream Proxy Servers", but simplified, as only one single proxy server would be specified and used by mitmproxy. Sying it in a different way, is it possible to configure an upstream proxy in mitmproxy without affecting its mode of operation client-side (transparent in this case)?

**Comment by mhils** [comment]
@raulsiles: What would you expect mitmproxy to do no the server side? Just open a TCP connection and send a `HTTP CONNECT`, or take an incoming HTTP request and transform it into absolute-form? The former would be relatively trivial to implement, the latter is not as straightforward. Assuming we would always do the former, what do we do if the upstream proxy refuses to CONNECT? How do we signal that to the user? All those problems can be solved, but I believe the use case is probably niche enough that just putting proxychains/redsocks in front of mitmproxy is good enough. I can probably be convinced to accept a PR that adds a "transparent upstream" mode, but it's not something we're actively pursuing ourselves.

**Comment by raulsiles** [comment]
I would expect mitmproxy to present a normal behavior on the server side, as you have mentioned, mostly similar to its behavior when it connects directly to a destination server (but in this case via a proxy: opening a TCP connection and sending a HTTP CONNECT).

If the upstream proxy refuses to CONNECT, for example, we can signal that to the user similarly as when a request is discarded in mitmproxy (delete flow, when interception is enabled). In my current testing, mitmproxy does not send a response and directly closes the TCP connection with a FIN/ACK packet (Burp shows a "No response received from remote server" based on that response from mitmproxy).

(FYI) The reasoning for this feature request is that I'm dealing with an app whose special TLS behavior is properly managed by mitmproxy, but not by other proxies (like Burp), so I need to have mitmproxy as the first element (front-end) in order to deal with this special TLS connection (on the client side). Then, I need mitmproxy to redirect that traffic via other proxies...

I'm not sure this is niche enough: How do mitmproxy users use the tool in transparent mode (for example, with iptables) when working on a corporate environment, where you are forced to reach the Internet via a corporate proxy?

**Comment by mhils** [comment]
> I'm not sure this is niche enough: How do mitmproxy users use the tool in transparent mode (for example, with iptables) when working on a corporate environment, where you are forced to reach the Internet via a corporate proxy?

You either use some iptables magic to chain proxies, or you use redsocks/proxychains as the first entrypoint.


I get your overall point though - if always CONNECTing is enough, this is something we should at least consider for #1775. Thanks again for the detailed arguments!

**Comment by raulsiles** [comment]
Thank you for adding it to the potential todo list!

**Comment by aviau** [comment]
Is there any workaround for this in the meantime?

**Comment by thiagoretes** [comment]
> > I'm not sure this is niche enough: How do mitmproxy users use the tool in transparent mode (for example, with iptables) when working on a corporate environment, where you are forced to reach the Internet via a corporate proxy?
> 
> You either use some iptables magic to chain proxies, or you use redsocks/proxychains as the first entrypoint.
> 
> I get your overall point though - if always CONNECTing is enough, this is something we should at least consider for #1775. Thanks again for the detailed arguments!

Just came here in 2021 and lost 12 hours trying to setup the redsocks from https://github.com/darkk/redsocks and no success, if you read this and need to setup redsocks with mitmproxy use redsocks2(https://github.com/semigodking/redsocks) which is recommended by the owner of redsocks according to their README

**Comment by 3052** [comment]
https://github.com/mitmproxy/mitmproxy/issues/211
