### ISSUE TITLE
It is difficult to get information from request/response/detail tab, if url is very-very long

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2818]
##### Steps to reproduce the problem:

1. Run mitmproxy.
2. Make a request with pathoc: `pathoc -c example.com:80 localhost:8080 'get:/SOMETHING VERY LONG'`
3. Enter the corresponding flow.
You won't be able to see request/response/detail of the flow without changing size of your window. 
![image](https://user-images.githubusercontent.com/20267977/35508608-a7e26636-04f9-11e8-96e6-2627d0b8d1f0.png)

But if we decide to make a request with url over for example 10k length, even changing the size of window won't help you to see request/response/detail tab.

##### Any other comments? What have you tried so far?

About maximum length of a URL
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

##### System information

Mitmproxy: 3.0.0.dev64 (commit 6dd336f) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by tran-tien-dat** [comment]
Maybe I can work on this? My initial thoughts would be to have a maximum URL length, and allow user to select it to see the whole content.

**Comment by mhils** [comment]
@tran-tien-dat: Sure, feel free to. :-)

**Comment by fenilgandhi** [comment]
I could not find a way to display the extra-extra long url with user's consent without breaking the accessibility of the UI. But to restore it currently, i have wrapped the url  upto allowed maximum columns.
