### ISSUE TITLE
parentheses in print function and python version

### ISSUE THREAD

**Issue by ddor254** [mitmproxy/mitmproxy#2822]
##### Steps to reproduce the problem:

1. run mitmproxy/mitmdump with script -s "script.py"

##### Any other comments? What have you tried so far?
I'm using mitmproxy version 0.15, how do i know which python version does it use?
I assumed that it uses python 2.7 from th docs. 
the only problem i don't understand is why do we need parentheses  in print function if it is python 2.7???

the print function gets overwritten somewhere??

##### System information

output when i just do print without parentheses : 
print jsonResponse                     ^
SyntaxError: invalid syntax

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. We're unfortunately not providing support for outdated releases.

**Comment by ddor254** [comment]
in 0.18 it is the same - 0.18 is also not supported?

**Comment by mhils** [comment]
We only support the latest stable release (2.0) and newer developer snapshots, sorry. And yes, Python 2 releases are explicitly _not_ supported anymore.

Without looking closer at your problem, I presume we had a `from __future__ import print_function` in our codebase somewhere.

**Comment by ddor254** [comment]
o.k thank you for the quick help
