### ISSUE TITLE
Better UI Testing

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2826]
We're currently doing a bad job at testing the mitmproxy console UI. While there's an argument to be had that test coverage for UI code quickly yields diminishing returns, we should certainly do better than we do right now. It would be very cool if we had a basic framework to drive UI interactions for testing. I'd love to be able to write a test that roughly looks like this:

```python
def test_edit_setcookies():
    ui = TestUI()
    ui.run("console.edit.focus set-cookies")
    ui.press("a foo <tab> bar <tab> <enter>")
    # set a cookie attribute
    assert ui.focus_flow.cookies == ...
```

The syntax is obviously up for debate, but it should get the general idea across. I'm sure @Kriechi would be happy to extend his testing empire to mitmproxy.console as well. :smile:

**Comment by kajojify** [comment]
I will take a look at it :)

**Comment by mhils** [comment]
Fixed: https://github.com/mitmproxy/mitmproxy/blob/main/test/mitmproxy/tools/console/test_integration.py
