### ISSUE TITLE
run mitmdump lead memory leaks...

### ISSUE THREAD

**Issue by laurdawn** [mitmproxy/mitmproxy#2828]
##### Steps to reproduce the problem:
I just want to run mitmdump with the default mode....
For example, just run it. "mitmdump -p 8888"
Sorry,,my English is so bad. 

##### Any other comments? What have you tried so far?
I looked at all the problems, and there were a few of them, but they couldn't be solved.
For example, I try to add param "-Z 0" or "--stream 0" to avoid it,,,But it doesn't seem to work at all,.
Still memory leaks, the memory has been increasing, until out of memory..

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.3
Platform: Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.4.1708-Core
SSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
Linux distro: CentOS Linux 7.4.1708 Core

**Comment by mhils** [comment]
If I understand you correctly your problem are memory leaks in mitmproxy? 
How many clients, how many requests, how much leakage?

**Comment by Mradr** [comment]
Usually it's not memory leaks you see, but connection leaks. They build and build until you hit either memory problem or out of acceptable connections.

**Comment by laurdawn** [comment]
Sorry, I'm a novice. So, I said my situation , only one client, the mitmproxy accept a phone's all requests, however the momory grouth.
Let me tell you what I did. I run a linux command， “screen -dms mitmdump”，then I simply run it, "mitmdump -p 8888". And that's what happens. In this way , the memory has been increasing. Moreover, 
this is a new Linux server, I just want to a proxy server,  And then there's the situation. 
I'm sorry, I may not be able to express myself clearly.But this is all I do and see.

**Comment by laurdawn** [comment]
@Mradr 
I run the mitmdump with the screen , no script, just a mitmdump.Sorry,, I don't understand you means........
