### ISSUE TITLE
How I can log the TLS master secrets with mitmproxy and use it in the wireshark

### ISSUE THREAD

**Issue by Al-Anoud** [mitmproxy/mitmproxy#2830]
Hi,
I asked before a question about how can I save a mitmproxy data in a pcap format  Issue #2806. 
So based on the suggestion to  (1) log the TLS master secrets with mitmproxy and (2) use a normal PCAP tool for packet capture, I tried to do it myself but unfortunately it did not work or maybe I did something wrong 
if some one did this process and it work with him, please help. 

Thank you 
Anoud

**Comment by mhils** [comment]
When you created this issue, you should have read the following message pre-filled into the textarea: Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!
