### ISSUE TITLE
Form data being deleted, if tried to edit JSON form data

### ISSUE THREAD

**Issue by kira0204** [mitmproxy/mitmproxy#2831]
##### Steps to reproduce the problem:

1. Run mitmproxy
2. Capture some flows with method `POST` and form in JSON, [Example Website](http://knowyourteacher.herokuapp.com/)
3. Press `enter`
![image](https://user-images.githubusercontent.com/19341613/35654181-e204a62a-0711-11e8-9b4d-b2565edbd345.png)

4.  Press `e` -> `form`
![image](https://user-images.githubusercontent.com/19341613/35654206-fc54985a-0711-11e8-9646-e83bd73d2420.png)

5. Press `q`
![image](https://user-images.githubusercontent.com/19341613/35654235-2740f342-0712-11e8-93ee-348ce61aff63.png)

##### Any other comments? What have you tried so far?
I think the basic problem lies with JSON Parsing, Even if the form data is empty and you try to change `mode` by pressing `m` and selecting `json` . It says `Couldn't parse: falling back to raw`

##### System information

Mitmproxy: 3.0.0.dev1176 (commit 02d2ef7) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.13.0-32-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by mhils** [comment]
Thanks for the report. JSON is not HTTP/HTML form data, so mitmproxy clears the contents. I agree this is a bit confusing from a UX perspective, but technically the right thing to do. Fixing this unfortunately is quite nontrivial (we don't have an editor component for something as nested as JSON), so I'll close this for now as we probably don't plan on changing the behavior anytime soon. Contributions are welcome of course!
