### ISSUE TITLE
Invalid HTTP request form (expected: authority or absolute, got: relative) 

### ISSUE THREAD

**Issue by ddor254** [mitmproxy/mitmproxy#2832]
##### Steps to reproduce the problem:

1. mitmdump -p 9999
on the same machine:
2.curl http://localhost:9999

##### Any other comments? What have you tried so far?
I get the "127.0.0.1:60422: HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)" error,

when running with the -T option i get the following error:
"127.0.0.1:60420: Transparent mode failure: OSError(92, 'Protocol not available')"

in mitmdump version 0.15 the same configuration and script with the -T option seems to work.

##### System information
Mitmproxy version: 2.0.2 
Platform: Linux-4.10.0-37-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by mhils** [comment]
Not sure how this is supposed to work - see http://docs.mitmproxy.org/en/stable/modes.html. You run mitmproxy in regular proxy mode and then send a request to it. Where is mitmproxy supposed to send this request to? The actual destination is not specified anywhere.

**Comment by ddor254** [comment]
i am running mitm with the -T option as well and i get the above error regarding the Transport Protocol . and the destination is http://localhost:9999 - this is url i put in the request\curl

**Comment by mhils** [comment]
`localhost:9999` is the proxy itself. Please read the linked documentation.

**Comment by ddor254** [comment]
so what if that is the proxy itself? the proxy is some kind of a server doesn't it?

**Comment by mhils** [comment]
In that case you can set it up a reverse proxy pointing to an invalid destination, it's a weird setup though.

**Comment by Haotian-Shi-cyber** [comment]
one question, what if i want to intercept http request from other host? mitmproxy runs on the web server, how am i gonna do that?
to be specific, i have a web server running at port 32770 on 10.0.1.2 and other host can access it on 10.0.1.2:32770. but i want to use mitmproxy to intercept http request from others
