### ISSUE TITLE
Undesirable traceback, when trying to run user's script on the specific flow twice.

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2838]
##### Steps to reproduce the problem:

1. Run mitmproxy.
2. Press `|` (`shift + \`). 
3. Input the path to your script. Press `Enter`.
4. Repeat steps 2-3 one more time.

Traceback, wich souldn't appear:
![image](https://user-images.githubusercontent.com/20267977/35767541-8392cf22-08f6-11e8-91e0-6b161f2d42ef.png)

##### System information

Mitmproxy: 3.0.0.dev79 (commit 957a630)
Python: 3.5.2
OpenSSL: OpenSSL 1.1.0g 2 Nov 2017
Platform: Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by kira0204** [comment]
I will take a look at this as well, will fix it in #2865 itself since these issues are related

**Comment by cortesi** [comment]
Fixed in master
