### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by zero-master** [mitmproxy/mitmproxy#2840]
##### Steps to reproduce the problem:

Open https://ondemand.icicibank.com/

You'll get this error:

```
502 Bad Gateway
TlsProtocolException('Cannot establish TLS with ondemand.icicibank.com:443 (sni: ondemand.icicibank.com): TlsException("SSL handshake error: Error([(\'SSL routines\', \'ssl3_read_bytes\', \'sslv3 alert handshake failure\')],)",)',)
```
##### Any other comments? What have you tried so far?

I really need some direction here.

##### System information

Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.4
Platform: Linux-4.14.15-1-ARCH-x86_64-with-arch
SSL version: OpenSSL 1.1.0g  2 Nov 2017
Linux distro: arch

**Comment by mhils** [comment]
Hi,
I think you are running into https://github.com/pyca/cryptography/issues/4087: Chrome negotiates TLS_RSA_WITH_RC4_128_MD5, which OpenSSL 1.1 is not built with by default. I suspect the server only supports insecure ciphers, and thus mitmproxy cannot establish a connection. This can be reproduced using plain OpenSSL:
```
openssl s_client -debug -connect ondemand.icicibank.com:443 -cipher ECDHE-ECDSA-AES128-SHA256
```

**Comment by Lucadaff** [comment]
I get same error trying to connect to a domain only accessible from a local network. I'm sorry I can't reproduce the steps. I'm up to date with the latest release.

**System information**

Mitmproxy: 4.0.4
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-3.16.0-8-amd64-x86_64-with-debian-8.11
