### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by cbenitez101** [mitmproxy/mitmproxy#2845]
I tried installing MITM proxy as in the documentation in an Ubuntu 16.04 system. I did exactly the same as it says in the documentation. The problem is that I'm not able to install some modules that I require like BeautifulSoup and netlib.
If I install MITM Proxy via apt-get I don't get those errors but it seems to use python2.7 instead of python3, giving me some other errors during the execution.
Any ideas of how to fully install it with the dependencies I need?
Thanks!

**Comment by mhils** [comment]
Hi,

Which documentation are you referring to? The canonical installation instructions are at http://docs.mitmproxy.org/en/stable/install.html#installation-on-linux. FWIW, netlib does not exist anymore and is now part of mitmproxy. Maybe you want to take a look at https://github.com/mitmproxy/mitmproxy/tree/master/examples for up-to-date examples (make sure to select the branch matching your mitmproxy version).
