### ISSUE TITLE
import ctype error when used with --scripts SCRIPT option from mitmdump

### ISSUE THREAD

**Issue by YuriyPryyma** [mitmproxy/mitmproxy#2849]
##### Steps to reproduce the problem:

1. install binary release
2. run mitmdump -s test.py (with import ctypes)

#### Output:

```
  Addon error: Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 149, in __init__
  File "ctypes/__init__.py", line 347, in __init__
OSError: command_path: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mitmproxy/addonmanager.py", line 67, in safecall
  File "mitmproxy/addons/script.py", line 76, in tick
  File "mitmproxy/addonmanager.py", line 177, in register
  File "mitmproxy/command.py", line 134, in collect_commands
  File "ctypes/__init__.py", line 417, in __getattr__
  File "site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 151, in __init__
PyInstallerImportError: Failed to load dynlib/dll 'command_path'. Most probably this dynlib/dll was not found when the application was frozen.
```

##### System information
UBUNTU 16.04

Mitmproxy: 3.0.0.dev1136 (commit 15f525e) binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.13.0-32-generic-x86_64-with-debian-stretch-sid

**Comment by mhils** [comment]
Hi,

If you want to use third-party modules in your mitmproxy scripts, you need to install mitmproxy from source (http://docs.mitmproxy.org/en/stable/install.html#advanced-installation). Our precompiled binaries contain a frozen Python environment which does not ship with `ctypes`:

**Comment by Houd1ny** [comment]
Man I will have the same error even if I run it from sources

**Comment by Houd1ny** [comment]
see https://github.com/mitmproxy/mitmproxy/pull/2850

**Comment by mhils** [comment]
You definitely shouldn't get a `PyInstallerImportError` when running from source, but yes, we should probably catch this better.

**Comment by Houd1ny** [comment]
This is possible that user redefined hasattr method as ctypes libraries does
And it could throw when started with argument "command_path"

**Comment by mhils** [comment]
Yes - we definitely should catch this better and I very much welcome #2850, the root cause of @YuriyPryyma's problem is the use of the binaries though.

**Comment by idiotsavant** [comment]
Homebrew has an `--enable-bar` option to force building from source rather than using a "bottled" binary. Any chance of supporting that in future? It would have been handy in this case to get BeautifulSoup working again in my scripts.

**Comment by crifan** [comment]
**Same error here**

macOS, install by brew

`brew install mitmproxy`

then run

`mitmdump -p 8081 -s Save1.py`

error: `in script Save1.py: No module named 'yaml'`

**Reason**:

brew installed mitmproxy contained a self version python, located in 

`/usr/local/Cellar/mitmproxy/4.0.4_3/libexec/bin/python`

when using `mitmdump -s some_python_script.py`, while `some_python_script.py` contain some thirdparty libs, such as here's `yaml`

it can NOT found it, so report error: `No module named 'yaml'`

**Solution**:

**NOT** using brew install mitmproxy:
`brew uninstall mitmproxy`

but change to your system's Python:

`pyenv global 3.8.0`

's pip:

`pip3 install mitmproxy`

**Note**:
can NOT use (system's) python2(2.7.5) to install mitmproxy, it will fail:

```bash
pip install mitmproxy
...
ERROR: matplotlib 1.3.1 requires nose, which is not installed.
Installing collected packages: configargparse, six, editorconfig, jsbeautifier, argh, pathtools, watchdog, MarkupSafe, Jinja2, Werkzeug, click, itsdangerous, Flask, pyperclip, singledispatch, certifi, backports-abc, tornado, pyasn1, pycparser, cffi, enum34, ipaddress, idna, cryptography, pyOpenSSL, backports.ssl-match-hostname, brotlipy, passlib, blinker, lxml, hyperframe, pyparsing, construct, requests, html2text, urwid, typing, cssutils, Pillow, hpack, h2, mitmproxy
    Running setup.py install for configargparse ... done
  Found existing installation: six 1.4.1
ERROR: Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by expecttheunusual** [comment]
> Hi,
> 
> If you want to use third-party modules in your mitmproxy scripts, you need to install mitmproxy from source (http://docs.mitmproxy.org/en/stable/install.html#advanced-installation). Our precompiled binaries contain a frozen Python environment which does not ship with `ctypes`:

Fix link to http://docs.mitmproxy.org/en/stable/install.html#advanced-installation
