### ISSUE TITLE
Wrong behavior when specifying the configuration file

### ISSUE THREAD

**Issue by LetMeR00t** [mitmproxy/mitmproxy#2854]
##### Steps to reproduce the problem:

Context :
I set up a virtual machine on Windows 7 that can communicate with Internet on ports 80 and 443 only.
Mitmproxy is used as a transparent proxy for these communications in order to decrypt all HTTPS traffic. A redirection is made thanks to my iptables physical host that redirect the traffic on port 8080.
I'm using Internet Explorer v11.0.49 and Mozilla Firefox v58.0.1 on the VM.

I will explain 4 cases concerning this setup and the use of the configuration file :
Configuration for the both first tests : **Cipher client used is AES256-SHA256** 
![capture du 2018-02-08 21-09-50](https://user-images.githubusercontent.com/10530375/35996607-42f3350e-0d17-11e8-9624-ba69fd489a65.png)

## 1st test : browser is Firefox

Communication doesn't work, error on mitmproxy's interface

![capture du 2018-02-08 21-15-02](https://user-images.githubusercontent.com/10530375/35996739-9b8cd026-0d17-11e8-87a6-05639ec40d30.png)

it seems that mitmproxy doesn't answer to the client (that started the communication using TLSv1.0)

![capture du 2018-02-08 21-15-53](https://user-images.githubusercontent.com/10530375/35996740-9bada3be-0d17-11e8-8ed2-84f5a9c1c7f1.png)

The chosen cipher is well proposed by the client in his list.

![capture du 2018-02-08 21-16-19](https://user-images.githubusercontent.com/10530375/35996742-9be3624c-0d17-11e8-8774-06b194910810.png)

## 2nd test : browser is Internet Explorer

Communication worked

![capture du 2018-02-08 21-17-19](https://user-images.githubusercontent.com/10530375/35996928-3bb50f28-0d18-11e8-88cc-5f3cdcaad24b.png)

it seems that mitmproxy answered to the client (that started the communication using TLSv1.2)

![capture du 2018-02-08 21-17-56](https://user-images.githubusercontent.com/10530375/35996932-3fce0858-0d18-11e8-8538-8af0b8f2a891.png)

The chosen cipher is well proposed by the client in his list. (of course)

![capture du 2018-02-08 21-18-07](https://user-images.githubusercontent.com/10530375/35996938-42fa674c-0d18-11e8-8534-16250a9cfceb.png)

Configuration for the both last tests : **Cipher client used is ECDHE-ECDSA-AES128-SHA256** 
![capture du 2018-02-08 21-38-44](https://user-images.githubusercontent.com/10530375/35997012-868450d6-0d18-11e8-8da8-b37524c23234.png)

## 3rd test : browser is Firefox (same behavior that the 1rst test)

Communication doesn't work, error on mitmproxy's interface

![capture du 2018-02-08 21-23-02](https://user-images.githubusercontent.com/10530375/35997071-ac9ee074-0d18-11e8-8ade-806fc0c77a56.png)

it seems that mitmproxy doesn't answer to the client (that started the communication using TLSv1.0)

![capture du 2018-02-08 21-23-35](https://user-images.githubusercontent.com/10530375/35997074-afd8c110-0d18-11e8-8d43-b0943814da6f.png)

The chosen cipher seems to be proposed by the client in his list. I'm not sure regarding the last test however ...

![capture du 2018-02-08 21-23-45](https://user-images.githubusercontent.com/10530375/35997080-b59c8f96-0d18-11e8-8974-2119d03e9206.png)

## 4th test : browser is Internet Explorer

Communication doesn't work, error on mitmproxy's interface

![capture du 2018-02-08 21-24-42](https://user-images.githubusercontent.com/10530375/35997147-e8bceaba-0d18-11e8-8849-b7f97b61f158.png)

it seems that mitmproxy doesn't answer to the client (that started the communication using TLSv1.2)

![capture du 2018-02-08 21-25-28](https://user-images.githubusercontent.com/10530375/35997150-ecf5fd88-0d18-11e8-82c9-0e8092473556.png)

The chosen cipher is well proposed by the client in his list.

![capture du 2018-02-08 21-25-43](https://user-images.githubusercontent.com/10530375/35997156-f293ab00-0d18-11e8-966f-c74609abb23c.png)

##### Any other comments? What have you tried so far?

As you can see, most of the tests were unsuccessful but the context was not the problem because it's worked in test 2 as expected.
I'm more worried about the fact that mitmproxy doesn't answer to the client ? Why did it do that ?
Moreover, the client seems to be legitimate for the connection but he is refused ...
I'm seeing in the code that the cipher suites are not so easily configurable as we can expect ... but the behavior of mitmproxy is very strange !
Could you investigate on this to know if there is a bug ? In all the tests, mitmproxy should be working 
What I understand is that the handshake doesn't work because the server thinks that there is no cipher suite available for the client ... I would like to add that when I don't specify the cipher suite, it's working. But because I want to decrypt HTTPS using cuckoo and mitmproxy, I need to specify the cipher suites (AES GCM seems to be problematic for the decryption, see https://github.com/cuckoosandbox/cuckoo/pull/2104)

##### System information

Mitmproxy: 3.0.0.dev1180 (commit 957a630) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.13.0-32-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by mhils** [comment]
Thanks for the extensive writeup - really appreciated!

### First Case

You're looking at the wrong packet - the interesting one is 247 where mitmproxy does answer with a TLS alert. From the Firefox screenshot, we can see that there is not cipher overlap. If you specify `AES256-SHA256` as your cipher, OpenSSL will only use `TLS_RSA_WITH_AES_256_CBC_SHA256` ([docs](https://wiki.openssl.org/index.php/Manual:Ciphers(1))), which Firefox did not offer: Notice that `SHA` is not `SHA256` in your screenshot.

### Second Case

Works, because IE offers `TLS_RSA_WITH_AES_256_CBC_SHA256`.

### Third Case

`SHA` isn't `SHA256`.

### Fourth Case

`ECDHE_ECDSA` isn't `ECDHE_RSA`.

----------------

So yes - I agree that cipher specification is terrible, but this is caused by OpenSSL to which we just pass your settings. Realistically there's not much we can do here. If you only want non-perfect-forward-secrecy ciphers, I believe you want something like `TLSv1.2:!kEECDH:!kEDH`. This is untested, but should illustrate the principle. Feel free to post a better version if you find one.

**Comment by LetMeR00t** [comment]
Thank you very much for you complete answer.
You're totally right, I didn't notice the difference between the cipher suites sorry.
Just for the cause, I made these tests because I detected something wrong in my PR for Cuckoo (which has nothing to do with mitmproxy, see https://github.com/cuckoosandbox/cuckoo/pull/2104)
It seems that using GCM cipher suites doesn't succeed to decipher the traffic using the httpreplay software.
I made these tests to see if it better works with different cipher suites but I was not using the good cipher suites so sorry :)
You can close this issue of course.
