### ISSUE TITLE
mitmdump 3.0.0rc2 doesn't accept arguments of script

### ISSUE THREAD

**Issue by bobby7718** [mitmproxy/mitmproxy#2862]
##### Steps to reproduce the problem:

1.install v3.0.0 RC2
wget https://github.com/mitmproxy/mitmproxy/releases/download/v3.0.0rc2/mitmproxy-3.0.0.dev1136-0x15f525e-py3-none-any.whl
sudo pip3 install mitmproxy-3.0.0.dev1136-0x15f525e-py3-none-any.whl
```
Mitmproxy: 3.0.0.dev1136 (commit 15f525e) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-87-generic-x86_64-with-Ubuntu-16.04-xenial
```
2.copy the example script(for 2.0) - https://github.com/mitmproxy/mitmproxy/blob/2.0.x/examples/simple/script_arguments.py
```
import argparse


class Replacer:
    def __init__(self, src, dst):
        self.src, self.dst = src, dst

    def response(self, flow):
        flow.response.replace(self.src, self.dst)


def start():
    parser = argparse.ArgumentParser()
    parser.add_argument("src", type=str)
    parser.add_argument("dst", type=str)
    args = parser.parse_args()
    return Replacer(args.src, args.dst)
```
3.run the command explained in the doc(still for 3.0) - https://github.com/mitmproxy/mitmproxy/blob/master/docs/scripting/overview.rst, see section `Running scripts on saved flows`. 

```
mitmdump -dd -s "./script_arguments.py html fakehtml"
```
or use --flow-detail instead -dd, which seems not supported either. 
```
mitmdump --flow-detail 3 -s "./script_arguments.py html fakehtml"
```
outputs of above command
```
$ mitmdump -dd -s "./script_arguments.py html fakehtml"
usage: mitmdump [options] [filter]
mitmdump: error: unrecognized arguments: -dd

#:~$ mitmdump --flow-detail 3 -s "./script_arguments.py html fakehtml"
/usr/local/bin/mitmdump: No such script: ./script_arguments.py html fakehtml
```

##### Any other comments? What have you tried so far?

I checked the release notes for 3.0, don't see anything changed with regard to mitmdump's script arguments since 2.0.2. 

Below is the output of the same command for mitmdump 2.0.2, which seems OK. 

Is there anything changed regarding mitmdump's command line options ?

```
$ mitmdump -dd -s "./script_arguments.py html fakehtml"
Loading script: ./script_arguments.py html fakehtml
Proxy server listening at http://0.0.0.0:8080

$ mitmdump --version
Mitmproxy version: 2.0.2 (release version) 
Python version: 3.6.4
Platform: Darwin-16.1.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2n  7 Dec 2017
Mac version: 10.12.1 ('', '', '') x86_64

```

##### System information
```
#:~$ mitmdump --version
Mitmproxy: 3.0.0.dev1136 (commit 15f525e) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-87-generic-x86_64-with-Ubuntu-16.04-xenial
```

**Comment by mhils** [comment]
Thanks. As mentioned in the RC release notes, documentation still needs a major overhaul. Instead of passing arguments to scripts, you can now have scripts declare options: https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/custom_option.py. One benefit of this is that you can change them during execution from the UI.
