### ISSUE TITLE
Release mitmproxy 3.0

### ISSUE THREAD

**Issue by asfaltboy** [mitmproxy/mitmproxy#2864]
### Major items

- [ ] Update documentation: Scripting API, Options, Commands, ... (@cortesi)

### Minor Items

- [ ] Complete [Changelog](https://docs.google.com/document/d/1cjSb7iNcm-wkBoyovgCWqySRfTJyI6yaepvSzcdTjLs/edit). (@mhils, @cortesi)
- [x] Finish [website](https://github.com/mitmproxy/www). (@mhils)
- [ ] Resolve remaining [issues](https://github.com/mitmproxy/mitmproxy/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.0). (everyone)

**Comment by cortesi** [comment]
I believe all of these are now complete. We're ready for 3.0.
