### ISSUE TITLE
Potential bug with options usage.

### ISSUE THREAD

**Issue by aniketpanjwani** [mitmproxy/mitmproxy#2866]
##### Steps to reproduce the problem:

1. Enter mitmproxy --allow_remote in terminal.
2. Get message:
```
mitmproxy --allow_remote
usage: mitmproxy [options]
mitmproxy: error: unrecognized arguments: --allow_remote
```

##### Any other comments? What have you tried so far?

I expect to get a message telling me to enter one argument (either True or False), since allow_remote is specified as a boolean option in mitmproxy/options.py. I also see this same problem for another option - body_size_limit. Am I making a mistake in how I am using the option?

##### System information

Mitmproxy: 3.0.0.dev1179 (commit 6d8731e) 
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-21-generic-x86_64-with-debian-stretch-sid

**Comment by mhils** [comment]
The correct way is `mitmproxy --set allow_remote` or `mitmproxy --set allow_remote=true`. We may need to work on the UX a bit - what made you believe that `--allow_remote` is the way to go?

**Comment by aniketpanjwani** [comment]
Currently, [the docs](http://docs.mitmproxy.org/en/latest/config.html) just say to look at [options.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/options.py). Some of the options in options.py definitely work without the `--set` in front, e.g. `mitmproxy --mode transparent`, so I thought the other options would be formatted analagously.
