### ISSUE TITLE
encoding/decoding hotkey "z" not actually work

### ISSUE THREAD

**Issue by PaleNeutron** [mitmproxy/mitmproxy#2874]
##### Steps to reproduce the problem:

1.go to flow view
2.tap z to choose encode type or remove
3.content-encoding header changed but the response body not

##### System information
Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.4
Platform: Darwin-17.4.0-x86_64-i386-64bit
SSL version: OpenSSL 1.0.2n  7 Dec 2017
Mac version: 10.13.3 ('', '', '') x86_64

**Comment by mhils** [comment]
Hi,

Thanks for the report. `z` works fine for me on 3.0rc2, please reopen if that's not the case.

**Comment by PaleNeutron** [comment]
[img1](https://imgur.com/DGFP4yW)

[img2](https://imgur.com/gxIXT29)

We could see the header and the body size changed but the response in view not.

Platform:
Mitmproxy: 3.0.0.dev1136 (commit 15f525e) binary
Python:    3.5.3
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Darwin-17.4.0-x86_64-i386-64bit

**Comment by mhils** [comment]
Ah, now I get it - thanks! So we do update the body, but we automatically deflate it for display in the UI only: 
![image](https://user-images.githubusercontent.com/1019198/36380018-0a765e82-1581-11e8-98eb-9b0bc2ff7adb.png)

If you do this during interception or for server replay, the client will get a compressed response. Does that make sense?

**Comment by PaleNeutron** [comment]
Maybe I need to write an add-on that modify the view?

I mean the compress toggle is confusing when the flow is not intercepted.

**Comment by PaleNeutron** [comment]
I am monitoring net traffic of an app, whose response lost the `deflate` flag.  
That makes all the debug tools  not decode the body.

**Comment by mhils** [comment]
I see - in this case you want to write your own addon that either adds a custom contentview or modifies the response content.

**Comment by PaleNeutron** [comment]
Yes, I found https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/custom_contentview.py
may help, but don't know how to load it.

`mitmproxy -s custom_contentview.py` seems not work.

**Comment by mhils** [comment]
Make sure you use the correct version of the script, e.g. if you are using mitmproxy 2.0, you want the version from the 2.0 branch; if you are using 3.0, master is your choice. You should then be able to press `m` to select your custom view.

**Comment by PaleNeutron** [comment]
Thanks! That woks.

BTW, after script loaded, we got [script:1] in the bottom bar, `s` in different color, but `s` isn't a hotkey?
In the script, `prompt = ("swap case text", "Z")` seems defined hotkey `Z`, but this one also not work.

**Comment by mhils** [comment]
> BTW, after script loaded, we got [script:1] in the bottom bar, s in different color, but s isn't a hotkey?

Thanks for spotting that! It used to be. Would you mind fixing this [here](https://github.com/mitmproxy/mitmproxy/blob/e117c9e337b27eb6c8bcbd99d3cc8f761e3f7430/mitmproxy/tools/console/statusbar.py#L232-L235) and sending a PR? 😃 

> In the script, prompt = ("swap case text", "Z") seems defined hotkey Z, but this one also not work.

Great catch as well, thanks. You get partially blind for these things when seeing it every day, please continue to report stuff like this 😛. We used to use that as the hotkey when you press `m`, but we have @kajojify's fantastic 1-9a-z hotkeys there now. I guess this also just needs to be removed, I'll open an issue and link here.

**Comment by PaleNeutron** [comment]
What's the heading_key `s` designed for?
the hotkey is broken or just should be removed.

**Comment by mhils** [comment]
The hotkey just needs to be removed. :)
