### ISSUE TITLE
Investigate contentview hotkeys

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2877]
As noticed by @PaleNeutron in  #2874, every contentview currently [defines a hotkey](https://github.com/mitmproxy/mitmproxy/blob/93425d4b1aaab2d96ff001fee2997be1a51e7c17/examples/simple/custom_contentview.py#L13), which however does not seem to be used anywhere:

> In the script, prompt = ("swap case text", "Z") seems defined hotkey Z, but this one also not work.

We used to have these hotkeys to select a contentview when pressing `m` while viewing a flow, but we use `console.choose` there now, which doesn't have/need that. We need to:

1. Find out if those contentview prompts are still used anywhere.
2. If not, remove them.

**Comment by kajojify** [comment]
It also looks suspiciously :) 
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/common.py#L13-L22

**Comment by kajojify** [comment]
Should it be closed? :)
