### ISSUE TITLE
UI garbage appears, when we try to replay killed flow

### ISSUE THREAD

**Issue by kajojify** [mitmproxy/mitmproxy#2879]
##### Steps to reproduce the problem:

1. Run mitmproxy.
2. Press `i` and set intercept to `google`.
`:  set intercept=google` 
3. Try to enter google.com in your browser.
4. Kill the corresponding flow by pressing `X`.
5. Press `r` to replay this flow.

![image](https://user-images.githubusercontent.com/20267977/36389830-453780dc-15a9-11e8-9c4b-6deccf16d3f4.png)

##### System information

Mitmproxy: 3.0.0.dev113 (commit 93425d4) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-112-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by cortesi** [comment]
Fixed in master
