### ISSUE TITLE
How can I capture all traffic network by mitmproxy ? 

### ISSUE THREAD

**Issue by AbedAlqaderSwedan1** [mitmproxy/mitmproxy#2883]
Not just HTTP OR HTTPS, I need to capture all traffic network, how can I do that by mitmproxy  ? can I edit mitmproxy to do that? 

like tcpdump, Wireshark captures all traffic network.

**Comment by AbedAlqaderSwedan1** [comment]
Not just HTTP OR HTTPS, I need to capture all traffic network, how can I do that by mitmproxy  ? can I edit mitmproxy to do that? 

like tcpdump, Wireshark captures all traffic network.

**Comment by Kriechi** [comment]
mitmproxy is a HTTP/HTTPS proxy. We have support for websocket and tcp sessions, but support is rather limited. If you want to capture other protocols I would recommend Wireshark or tcpdump.

**Comment by AbedAlqaderSwedan1** [comment]
but tcpdump and Wireshark can't decrypt SSL ! how can I  solve this problem!

in fact, Wireshark can decrypt SSL but after capture packet, but I  need in real time 

can you help me with it? 

for example Mitmproxy + tcpdump?  or if I can edit mitmproxy to capture  all packets

**Comment by AbedAlqaderSwedan1** [comment]
@Kriechi @rory
