### ISSUE TITLE
Verbose mode not working in v3.0.0 RC2

### ISSUE THREAD

**Issue by Gigiarum** [mitmproxy/mitmproxy#2885]
##### Steps to reproduce the problem:

1. Start mitmdump with -v or --verbose flag
2. No DEBUG level logs prints on standard output

##### Any other comments? What have you tried so far?

In old stable version (2.0.2) the same steps produce desired output.

##### System information

Mitmproxy: 3.0.0.dev1136 (commit 15f525e)
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-3.16.0-5-amd64-x86_64-with-debian-8.9

**Comment by mhils** [comment]
Good catch, thanks! We apparently need to handle this here:

https://github.com/mitmproxy/mitmproxy/blob/da4c1ee625a3451b58c69454ecd5f4faf3cb67d4/mitmproxy/tools/main.py#L42-L48
