### ISSUE TITLE
pydoc fails on some modules

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#2887]
Some of our modules fail to display in pydoc. I'd like us to be as pydoc-friendly as possible, because this is the easiest way to explore our APIs. 

```
> python -m pydoc mitmproxy.proxy   
problem in mitmproxy.proxy - AttributeError: module 'platform' has no attribute 'python_implementation'
```

**Comment by mhils** [comment]
This is because we have `mitmproxy.platform`, which Python version is that? 
I can't reproduce this with either 3.5 (WSL) or 3.6 (Windows).

**Comment by cortesi** [comment]
Digging deeper:

- I don't think the Python version is relevant, but I'm on 3.6.4
- This fails when within the source tree, but succeeds outside the source tree. It's still pretty surprising.
- The issue seems to be due to the fact that we import the built-in platform module in various places, with `import platform`. When we're within the tree this resolves to the `mitmproxy.platform` module. This is worth fixing - just using "import mitmproxy.platform" in the appropriate spots does the trick.

**Comment by mhils** [comment]
I think it's the other way around. We do `import platform`, which resolves to `mitmproxy.platform`. See the original error message, `platform` should have `python_implementation`.

**Comment by cortesi** [comment]
Yes, I believe that's what I just said. ;)

**Comment by mhils** [comment]
Sorry, I focused on the last sentence:

> just using "import mitmproxy.platform" in the appropriate spots does the trick.

I believe this does not work, because `import platform` (where we want the builtin) would still resolve to the mitmproxy one?

**Comment by cortesi** [comment]
It does work, but perhaps for complicated reasons to do with the way modules are reused. Try it!

Let's dig into this more later. The most complete solution is probably to rename the platform module so it doesn't shadow a built-in. We don't have many instances of this sort of thing.

**Comment by cortesi** [comment]
No, belay that. Doing that just introduces a different set of directories this fails for. Let's just fix it properly, but not today.

**Comment by mhils** [comment]
We may be running into https://bugs.python.org/issue30024 here - anyway, let's fix this later.

**Comment by Kriechi** [comment]
Seems to work with current master.
