### ISSUE TITLE
docs are not working anymore

### ISSUE THREAD

**Issue by ottens** [mitmproxy/mitmproxy#2893]
##### Steps to reproduce the problem:

1. go to http://docs.mitmproxy.org/en/stable/
2. it shows an autogenerated index file, nothing else

**Comment by mhils** [comment]
Thanks - we've just released 3.0 which brings significant documentation changes, looks like we need to somehow convince rtd to stay on 2.x :)

**Comment by mhils** [comment]
FWIW, http://docs.mitmproxy.org/en/v2.0.2/ works.

**Comment by NotAFile** [comment]
As if now, it seems it does not. Convincing rtd to keep a certain version is relatively easy though. It should be on the main project page in the config. There you can change the public-ness as well as the tag/branch it should build against.

**Comment by mhils** [comment]
@NotAFile: Just tried that (you saw the rebuild, should be up again), it seems like I unfortunately cannot convince rtd to keep stable on 2.0.

**Comment by NotAFile** [comment]
can you not just set the tag/branch for stable to 2.0.2 or 2.0.x?

**Comment by mhils** [comment]
@NotAFile, there is no setting for that. Stable is determined automatically from the latest tag. I'm playing around with redirects at the moment, which don't seem to have any effect at all.

**Comment by NotAFile** [comment]
Hm? I checked it before replying here. Maybe that field doesn't do what I expect it to do, though.

![image](https://user-images.githubusercontent.com/5447747/36545224-bbeda364-17e8-11e8-9b95-8c31e14960c5.png)

**Comment by mhils** [comment]
![image](https://user-images.githubusercontent.com/1019198/36545326-f0a2508c-17e8-11e8-8eda-cd36f8b92735.png)

¯\_(ツ)_/¯

**Comment by mhils** [comment]
With readthedocs versions not cooperating and redirects showing no effect, I set up a temporary redirect server. All links should work again in a few minutes. If you still experience issues in an hour, please let me know.
