### ISSUE TITLE
Docs Improvements

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2895]
Thanks to @cortesi, we have fantastic revamped docs. 🎉 🍰 
To not interfere with his final touches, I'm collecting minor things here:

- [x] We definitely need a link back to mitmproxy.org. We'll have users land on the docs and they won't find a way to download the thing. 😄 I think it'd be great to have the mitmproxy.org header in the docs as well.
- [ ] To the surprise of @cortesi, we do support transparent mode on Windows. That should be added.
- [x] Clicking directly on "Docs" should take us to the latest version, not ReadTheDocs.
- [x] "Linux fully transparent mode" seems to be way to prominent on https://www-test.mitmproxy.org/docs/latest/howto-transparent/ and should probably be moved to the bottom.
- [ ] We need to mention --tcp and --raw-tcp somewhere.
- [x] "Other releases" link on main page is broken, needs to point to https://mitmproxy.org/docs/latest/overview-installation/
- [x] Add a max-width to the docs. It is hard to read on 27" screens.
- [x] From https://discourse.mitmproxy.org/t/certificates-quick-setup/890 - Mac OS X link has been archived and is no longer updated by Apple. Maybe this link is a suitable replacement: https://support.apple.com/kb/PH20129?locale=en_US
- [x] From https://github.com/mitmproxy/mitmproxy/issues/2981: Add border mitm.it screenshot to make clear it's an image.
- [x] https://mitmproxy.org/docs/ needs to go.
- [x] Google Analytics for docs
- [x] Google Analytics for main site
- [ ] Addon development docs, mentioning hot reload and testing
- [ ] Key binding configuration docs
- [x] Provide an auto-generated man-page like listing of all options, ideally with availability tags for mitmproxy/mitmweb/mitmdump, via a [script](https://github.com/mitmproxy/mitmproxy/tree/master/docs/scripts)
- [ ] Provide an auto-generated man-page like listing of all commands, ideally with availability tags for mitmproxy/mitmweb/mitmdump, via a [script](https://github.com/mitmproxy/mitmproxy/tree/master/docs/scripts)
- [ ] make top-left banner `src/static/logo-docs.png` either high-res (apple 2x style) or an svg vector graphic. Image source at https://github.com/mitmproxy/mitmproxy.org/tree/master/logo (see modd.conf)

To be discussed:

- [ ] Have we considered adding a second level navigation as on rtd? https://www-test.mitmproxy.org/docs/latest/overview-features/ seems a bit off, and https://www-test.mitmproxy.org/docs/latest/howto-transparent/ would need one.

**Comment by cortesi** [comment]
Adding to this:

- Google Analytics for both docs and the main site
- Addon development docs, mentioning hot reload and testing
- Key binding configuration docs

**Comment by Kriechi** [comment]
* Make h1/h2/h3/etc deep-linkable so we can directly link to sections, e.g., http://docs.mitmproxy.org/en/latest/install.html#advanced-installation
* https://mitmproxy.org/docs/ should contain something useful
* https://mitmproxy.org/docs/latest should be built from git-master and be always up to date (travis S3 upload)
* https://mitmproxy.org/docs/stable should be manually updated to show the current stable branch (again travis with a manually set branch name or only manually compiled and uploaded)

**Comment by Kriechi** [comment]
* Deep-links on RTD also render a fancy "hyperlink" icon on mouse-over. This allows users to share deep-links very easily by right-clicking and copying the link. `<h2>Examples<a class="headerlink" href="#examples" title="Permalink to this headline">¶</a></h2>` with the `¶` getting replaced by an icon on mouse-over.

**Comment by cortesi** [comment]
Regarding the hyperlink icon for header anchors - I've had a look at this, and it seems that the easiest way to do this would be to have a light-weight bit of JavaScript that adds the decoration.

**Comment by Kriechi** [comment]
* TLS Master Secrets with Wireshark: this page seems to got lost in the transition: https://github.com/mitmproxy/mitmproxy/blob/2.0.x/docs/dev/sslkeylogfile.rst

**Comment by Kriechi** [comment]
Currently the sidebar is rendered with `height: 100vh`, which is a bit odd. On a long page, the sidebar is only as tall as your viewport. Once you scroll down a bit, the sidebar is gone (out of view), but on my 13'' screen, the sidebar itself requires scrolling. So you end up with a too small sidebar which requires scrolling, although there is plenty of vertical room...

I would suggest removing the viewport height restriction all together, and just render it normally.

**Comment by Kriechi** [comment]
The top-left banner `src/static/logo-docs.png` could benefit from a higher resolution or svg file format. It would be nice if we also keep the "raw" files for such generated artifacts somewhere in the repo.

**Comment by Kriechi** [comment]
Do we have a (rendered) page of all our options? Like a typical man-page would provide?

**Comment by mhils** [comment]
> Do we have a (rendered) page of all our options? Like a typical man-page would provide?

No. This would need to be in https://github.com/mitmproxy/mitmproxy/tree/master/docs/scripts.

**Comment by lacombar** [comment]
FWIW, `docs/src/content/howto-transparent.md` has been outdated for about a year. Neither `-T` or `--host` option exist anymore.

**Comment by kira0204** [comment]
@lacombar Hi, the issue was identified and was rectified in the master branch. The website will be updated soon. Thanks

**Comment by Kriechi** [comment]
Since we are back to using https://docs.mitmproxy.org/, we should make a redirect on:
  * https://www.mitmproxy.org/docs/
  * https://www.mitmproxy.org/docs/latest

because there are a few blog posts / HN articles / etc. that link to those pages.

**Comment by mhils** [comment]
@Kriechi: done!

**Comment by q2dg** [comment]
I don't know if it's a bit off-topic here, but it's worthy mentioning script API documentation needs to be done.

**Comment by Kriechi** [comment]
Lots of changes have been merged - let's consider this issue closed and keep track of new tasks in a new issue.

**Comment by 1268** [comment]
https://github.com/mitmproxy/mitmproxy/issues/6377

**Comment by DivvSaxena** [comment]
can we work on the remaining tasks @mhils ? I am want to work on this task!

- [ ]  make top-left banner src/static/logo-docs.png either high-res (apple 2x style) or an svg vector graphic. Image source at https://github.com/mitmproxy/mitmproxy.org/tree/master/logo (see modd.conf)
