### ISSUE TITLE
Body editing is broken.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2901]
From @kajojify:

> Enter request-body/response-body editor, then leave it and try to interact with mitmproxy. 
Everything was ok with v3.0.0rc2, but v3.0.1 stops reacting on any button.

I can reproduce this on WSL - this needs to be fixed ASAP and probably warrants a bugfix release. I'm unfortunately super busy this weekend, so it'd be great if someone could take a closer look.

**Comment by cortesi** [comment]
This is an URWID issue, reported here:

https://github.com/urwid/urwid/issues/285

Urwid seems to have had a bit of an internal revolution, and has seen two releases this year (last one before that in 2015!). This is great news. I'll chip in on the Urwid ticket to add our voice.

In the meantime, we should pin to 1.3.1, and cut a bugfix release. I'm on cafe wifi today, which means I can't do a release until this afternoon. Let's see if someone beats me to it.

**Comment by cortesi** [comment]
Actually, I've found a better fix. Please hold.
