### ISSUE TITLE
Update socks mode access commandline + documentation (v3.0.2)

### ISSUE THREAD

**Issue by kaiof** [mitmproxy/mitmproxy#2906]
##### Steps to reproduce the problem:
1. mitmproxy --socks
"--socks is deprecated 
Please use '--set socks=value' instead"
2. Check online documentation at:
https://mitmproxy.org/docs/latest/concepts-modes/#socks-proxy
3. Check mitmproxy --help

##### Any other comments? What have you tried so far?
1. The advice given here doesn't appear to work (no combinations I tried were accepted).
2. The online documentation stops at Socks Proxy (no content)
3. The --help text shows the correct method (--mode socks5)

##### System information
Mitmproxy: 3.0.2
Python:    3.5.5rc1
OpenSSL:   OpenSSL 1.0.1f 6 Jan 2014
Platform:  Linux-2.6.39.4-kat124-ga627d40-armv7l-with-debian-jessie-sid

(Android: KatKiss Marshmallow hosting Linux Deploy: Ubuntu Trusty [armhf] using pyenv)

**Comment by fristonio** [comment]
Thanks @kaiof for reporting the issue

I have fixed the issue with the command line help. Not sure what to put up in the documentation, might need some help here @mhils @cortesi  :)
