### ISSUE TITLE
Using external $EDITOR renders the console UI unusable

### ISSUE THREAD

**Issue by philjackson** [mitmproxy/mitmproxy#2915]
##### Steps to reproduce the problem:

1. Set intercept to google.com, get to the point you can edit the response.
2. From the edit menu, pick 'a' (response body)
3. Edit the body, saving the file and close the editor.
4. Note that the mitmproxy UI will no longer respond to input.

##### Any other comments? What have you tried so far?

Different editors:

    EDITOR=emacsclient
    EDITOR=vi

Different terminals: `xterm`, `gnome-terminal`

##### System information

```
Mitmproxy: 3.0.2 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.13.0-16-generic-x86_64-with-debian-stretch-sid
```

**Comment by philjackson** [comment]
Hey, @cortesi. Thanks for the response. This was the "binary" release from Github. I tried from source and, you're right, works perfectly.

**Comment by cortesi** [comment]
Heh. It turns out that I somehow tagged the release before merging the fix! Thanks for reporting this. I'm cutting 3.0.3 right now, which will actually contain the fix and should work as expected.

**Comment by mhils** [comment]
3.0.3 is out. :)
