### ISSUE TITLE
how to write to file in mitmdump 3.02 ?

### ISSUE THREAD

**Issue by StevenRoosa** [mitmproxy/mitmproxy#2918]
##### Steps to reproduce the problem:

1.  How do I accomplish writing saved flows with mitmdump 3 on Linux, which would have been done in earlier versions with a command like this:  ./mitmdump -nr  infile_name  -dddd  --host >  outfile_name

##### Any other comments? What have you tried so far?
I have looked in the --options, and I see reference to flow detail, but not the rest of the necessary options syntax

##### System information

Mitmproxy: 3.0.2 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.8.0-52-generic-x86_64-with-debian-stretch-sid

**Comment by mhils** [comment]
- `-n`: Stays the same.
- `r infile`: Stays the same.
- `-dddd` -> `--set flow_detail 3`
- `--host` -> `--showhost`

Is that what you were asking? :)

**Comment by StevenRoosa** [comment]
Is this what is supposed to work:
./mitmdump -nr infile --set flow_detail: 3 --showhost > outfile 
or 
./mitmdump -nr infile --set flow_detail 3 --showhost > outfile
I am still getting errors.  I also tried:
./mitmdump -nr infile flow_detail: 3 --showhost > outfile
This option purportedly wrote to file without throwing an error, but it was zero bytes, so it didn't work.
I am trying to use mitmdump to write a saved mitmproxy capture to a flat file.  I Apologize for the multiple requests, and your thoughts here are greatly appreciated.

**Comment by cortesi** [comment]
Hi there. Try this:

> mitmdump -nr /tmp/foo --set flow_detail=3 --showhost > outfile

**Comment by StevenRoosa** [comment]
Shazam!  This worked perfectly.  Thank you!!
