### ISSUE TITLE
Chain mitmproxy and charles/burp proxy (HTTPS)

### ISSUE THREAD

**Issue by Semyazz** [mitmproxy/mitmproxy#292]
How can I chain multiple proxies (HTTPS) according the the following schema

```
Browser -> mitmproxy-1:8080 -> burp/charles:8081 -> mitmproxy-2:8082 -> Internet
```

I know it's possible to chain `mitmproxy-1 -> mitmproxy-2` and I've already tested that, but I can't put something else in between.

Is it even possible? How can I achieve that.

The goal behind this is that mitmproxy is great for scripting, but Charles/Burp are much better for manual editing stuff. I'd like to script some stuff in mitmproxy and later inspect requests manually in some GUI tool like Charles or Burp

**Comment by VihaanVerma89** [comment]
`mitmdump  --mode upstream:http://192.168.0.105:8888 --ssl-insecure` made it work in my case.
