### ISSUE TITLE
mitmproxy certificate directory not found and --set cadir not working on Windows

### ISSUE THREAD

**Issue by CorTal** [mitmproxy/mitmproxy#2930]
##### Steps to reproduce the problem:

1.Install latest version of mitmproxy
2. Try to run mitmdump without any arguments
![error_mitmdump](https://user-images.githubusercontent.com/15815157/36662817-f46c41ec-1adf-11e8-8eb9-f2f27aaa31eb.JPG)

##### Any other comments? What have you tried so far?
In order to use mitmproxy and adapt it to my use, I did all the steps to start the development.
I managed to make it work last Friday but now mitmdump says that it can't find the .mitmproxy repertory.
It might be a problem from my PATH or my environment, but then I tried to put directly the path to the file with the option "--set cadir", I tried to put directly in the command line the path and I got the same error.
![error_set](https://user-images.githubusercontent.com/15815157/36663009-79b7f8fa-1ae0-11e8-91a1-c3af193cf769.JPG) 
Because of this error, I'm unable to see the --options display since it crashes before (Which can make it difficult to correct that issue).
![error_options](https://user-images.githubusercontent.com/15815157/36663157-f46806c6-1ae0-11e8-9014-f6ae1a41c6b4.JPG)

So then, I went into the "mitmproxy/options.py" directly to put the path in the variable "CA_DIR", making it working.
![options_modified](https://user-images.githubusercontent.com/15815157/36663437-db35c142-1ae1-11e8-968b-d2dde02841c5.JPG)
![options_working](https://user-images.githubusercontent.com/15815157/36663439-dccfbb20-1ae1-11e8-85ce-b856e1d9f736.JPG)

I used the working state of mitmdump to use the --options and put the output in a config file. In this config file, I modified directly the "cadir" line with the exact same path I wrote in the command line with --set.
![conf_file](https://user-images.githubusercontent.com/15815157/36663492-06526df8-1ae2-11e8-9d67-74ac169f517a.JPG)
Then, reverted my modifications to "options.py" to return back to the initial state and gave my config file to the command line with --conf and made it work.
![conf_passed](https://user-images.githubusercontent.com/15815157/36663572-4f3a1746-1ae2-11e8-848b-a578404f14fc.JPG)

 So I wondered that maybe the --set option wasn't working properly, but maybe I'm wrong. And I wondered too if any troubles with the Windows PATH handling got into the new updates of mitmproxy

### UPDATE 1

After getting through to understand better what's going on, I realized that on start, the proxy is initiated first with default values from options.py, and then some lines after, the options are modified accordingly to the --set commands.
So, it may not be an issue here, but the thing is that if mitmproxy's default configuration of path to .mitmproxy is incorrect for the current system, it is not possible to put "--set cadir='...'" because it will crash before. 

##### System information

![mitm_version](https://user-images.githubusercontent.com/15815157/36663710-bdee7fba-1ae2-11e8-82dd-f28b27a9335d.JPG)

##### Misc

I use that issue to thank you for that amazing tool I will be using in my apprenticeship, you're doing an amazing work and I'm really grateful for giving us that tool.

**Comment by mhils** [comment]
Thanks for the report. What's the output of the following command on your system?
```
python -c "import os; print(os.path.expanduser('~'))"
```
(you may need to use python3 instead of python)

**Comment by CorTal** [comment]
![expand_user](https://user-images.githubusercontent.com/15815157/36714833-fe433220-1b93-11e8-8f45-7bbca728379b.JPG)

**Comment by mhils** [comment]
Thanks again. This is still a bit confusing to me - Does `C:\Users\<your username>` not exist on your system? 
If it does exist, can you apply the changes in https://github.com/mitmproxy/mitmproxy/pull/2950 and report the error message you get then?
