### ISSUE TITLE
listen_port and listen_host options have no effect

### ISSUE THREAD

**Issue by bugreport998** [mitmproxy/mitmproxy#2932]
##### Steps to reproduce the problem:

options have no effect when set on the command line

1. mitmproxy --set listen_port=1234
2. lsof -iTCP -sTCP:LISTEN -P | grep python
3. mitmproxy is still listening on port 8080

options have no effect when set in the ui

1. mitmproxy 
2. set listen_port option at runtime (pressing O)
3. ui shows *.1234, lsof still shows port 8080

the same appears to be true for listen_host (bound to *. when set to listen on loopback only)

##### System information

Mitmproxy: 3.0.3
Python:    3.6.4
OpenSSL:   OpenSSL 1.0.2n  7 Dec 2017
Platform:  Darwin-17.3.0-x86_64-i386-64bit

**Comment by fristonio** [comment]
@bugreport998 the command to set the listen port is `mitmproxy --listen-port [PORT]` and it is working perfectly fine, you can check `mitmproxy --help` for that. I will take a look at setting listen port using UI. :)

**Comment by bugreport998** [comment]
Thankyou for the quick response to this issue. Using --listen-port does work as expected :)

I think It's a little unintuitive that --set for those options doesn't work where there is a seperate --listen-port switch

That is a little strange because the UI updates to reflect the setting for listen_port and listen_host (when set with --set). 

![mitmproxy_port](https://user-images.githubusercontent.com/36875264/36742589-eab54b2c-1b9c-11e8-9478-f81f583b0fde.png)
![image](https://user-images.githubusercontent.com/36875264/36742613-fdd15c32-1b9c-11e8-8293-49044971c28c.png)

launching mitmproxy with --set listen_port=1234 --set listen_host=127.5.5.5 also reflects that option in the options UI

![image](https://user-images.githubusercontent.com/36875264/36742662-21bcf5e8-1b9d-11e8-8ef0-ead0673aa82a.png)

**Comment by mhils** [comment]
If `--listen-port 1234` and `--set listen_port=1234` behave differently, that's definitely a bug.

**Comment by fristonio** [comment]
@mhils was `--set listen_port=1234` supposed to work. Also, how does the port changing work here when we set it using console UI option, does it closes the connection and then reopens at the specified port?

**Comment by mhils** [comment]
listen_host and listen_port cannot be changed during execution at the moment (that's a separate bug I guess) - maybe that's the same issue here, although we _should_ update settings before spawning a server.

**Comment by cortesi** [comment]
Yes, we have two issues here - the fact that the proxy component doesn't rebind on change, and the fact that command-line options are apparently not applied before the proxy initially binds. I'm in the process of refactoring this part of our codebase, and both of these issues should be fixed by the time I'm done.

**Comment by bugreport998** [comment]
I did try changing listen_port and listen_host and then toggling the 'server' option - that is what seemed intuitive to me as a user. It might make more sense to make the user (but tell them!) that they need to bounce the proxy themselves rather than tearing down an active proxy that might otherwise be in use.

**Comment by mhils** [comment]
The proxy now rebinds on master! :)
