### ISSUE TITLE
MITMProxy Windows certificate issue... Browser revoking certificate 

### ISSUE THREAD

**Issue by talhasgh** [mitmproxy/mitmproxy#2933]
##### The issue is :

1. I've download the MITMProxy zip(windows exe) file from official site and install it on my pc and install.
2. Afterward i tried to capture it works for HTTP but when i open any HTTPS site it show revoking certificate error.
3. I dig deep into this error still facing same issue i install the certificate but never worked, or may be my methodology to use MITMProxy is not right.

**Comment by elig0n** [comment]
What device are you monitoring? Have you followed the instructions at mitm.it ?

**Comment by talhasgh** [comment]
Yes somehow i was doing wrong but now it worked fine
