### ISSUE TITLE
Mitmweb changes default value of options

### ISSUE THREAD

**Issue by armudgal** [mitmproxy/mitmproxy#2935]
##### Steps to reproduce the problem:

1. run `mitmweb`
2. enable `spoof_source_address` from options
3. close `mitmweb` and open `mitmproxy`
4. Go to options by pressing `O` , `spoof_source_address` will be enabled by default

##### Any other comments? What have you tried so far?

Even if you try to change the setting using `options` from `mitmproxy` UI, the default is changed until and unless you open `mitmweb` and untick it back.
Idk if it's a solid issue or not but this can trouble the user a lot. 

##### System information

```
Mitmproxy: 4.0.0.dev1295 (commit 10b6f62) 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial
```

**Comment by mhils** [comment]
This is because mitmweb writes `config.yaml`. We probably should do something more elaborate here, e.g. considering a separate `mitmweb.yaml` file. @cortesi probably already has a stronger opinion on this. :)

**Comment by cortesi** [comment]
Oh, wow. Yes, @cortesi has a strong opinion here - mitmweb should definitely not save options without the user clicking a "Save" button, and should certainly only save options that have been changed from defaults rather than blorting out all options into the file, and should certainly not over-write options the user has set explicitly.

**Comment by MatthewShao** [comment]
Thanks for the opinion on this feature, I'll improve this in next few days.

**Comment by cortesi** [comment]
I've temporarily disabled options saving by mitmweb on master - it kept tripping me up while I was troubleshooting an unrelated issue.
