### ISSUE TITLE
Wire shark Captured TLS/SSL packet decryption using  TLS master secrets with mitmproxy.(Windows 10)

### ISSUE THREAD

**Issue by talhasgh** [mitmproxy/mitmproxy#2938]
##### Actully in this question i'm only asking how can i decrypt the SSL packet using TLS master secrets with mitmproxy in windows 10.

1. I uses the mitmproxy to capture traffic but it doesn't support .pcap format. Somewhere searching i see someone mention the this method 

> **use log the TLS master secrets with mitmproxy**

2. When i dig deep into the method  **log the TLS master secrets with mitmproxy** i get nothing that can help me understand how to use this.
3. I'm asking in this form is there anyone who can help, if you tried can explain the procedure.

**Comment by Kriechi** [comment]
Sorry, it seems like the docs page about this topic got lost in the recent major overhaul of our documentation. Here is a link to the old version, which is still valid: https://mitmproxy.readthedocs.io/en/v2.0.2/dev/sslkeylogfile.html

**Comment by talhasgh** [comment]
I've added it using pre master log file with wireshark but i don't understand how to save decrypted packets
in pcap format?
