### ISSUE TITLE
Improve preformance

### ISSUE THREAD

**Issue by cbenitez101** [mitmproxy/mitmproxy#2939]
Hi guys, I'm using the last version of MITM Proxy to inject advertisements to my hotspots users. The problem is that the performance is so poor. It takes like 2 mins. to load a webpage.

I have the next code:

from bs4 import BeautifulSoup   # nice representation of the DOM
from mitmproxy import flow 
from mitmproxy import ctx, http
from mitmproxy.script import concurrent

"""
def start(context, argv):
    if len(argv) < 2:
        raise ValueError("Script name must be provided as the first parameter")
    context.script = argv[1]
"""

class Injector:
    
    
 

    def response(self, flow: http.HTTPFlow):
            html = BeautifulSoup(flow.response.content, "html.parser")
            if html.body and ("text/html" in flow.response.headers["content-type"]):     # inject only for HTML resources
           
                if "Content-Security-Policy" in flow.response.headers:
                    del flow.response.headers["Content-Security-Policy"]
             

 
                div = BeautifulSoup('<div id="advertisements" style="background-color: #aaa; position:fixed; bottom:0; width:100%; height:15%; z-index:99999999999;"><img src="somedir/publi-mock2.png" style="min-width:100%; height:100%"></div>', "html.parser")
                html.body.insert(len(html.body.contents), div)

                cdn = html.new_tag("script", type="text/javascript", src="http://code.jquery.com/jquery-3.3.1.min.js")
                html.body.insert(0, cdn)

                cdn = html.new_tag("script", type="text/javascript", src="http://www.somedir/inject.js")
                html.body.insert(1, cdn)
                flow.response.content = str(html).encode("utf8")
                print("script injected")
             
                

addons = [Injector()]

As you can see, I try to load an image, jquery and another js file. Any idea of how can I improve the performance?.
Thank's in advance!

**Comment by mhils** [comment]
This is terrible, please don't do it. I know you may have customers asking for this, but it's your obligation to politely explain them that ad injection is a bad idea. In any case, please don't use mitmproxy for this.
