### ISSUE TITLE
How to import bs4 in mitmproxy 3.0 scripting

### ISSUE THREAD

**Issue by kjkpoi** [mitmproxy/mitmproxy#2940]
##### Steps to reproduce the problem:

I used to use bs4 module in mitmproxy scripting, but after 3.0 version, import bs4 makes error (ImportError: No module named 'bs4').
It seems to make error when import other modules.

How can i solve it?

**Comment by fenilgandhi** [comment]
Could you check if you have `bs4` module in `python3` ? If not you can install it as `python3 -m pip install beautifulsoup4`. If you have it installed, you need to provide more info by running `mitmproxy --version`

**Comment by kjkpoi** [comment]
@fenilgandhi of course i checked bs4 in python3, my codes with bs4 works on mitmproxy v2.02 but not work with above v3.0.

**Comment by fenilgandhi** [comment]
Then providing some more info regarding would be very helpful in finding a solution. Could you provide some kind of stack-trace, or  addon script which you were running.

**Comment by kjkpoi** [comment]
@fenilgandhi 
![image](https://user-images.githubusercontent.com/962819/36945989-3ff0d498-1ff9-11e8-887e-645529465aa7.png)
i attach my error
v3_instrument_javascript.py is simple
just import bs4

**Comment by kajojify** [comment]
@kjkpoi Hi! See this -> https://github.com/mitmproxy/mitmproxy/issues/2849#issuecomment-363762607

**Comment by fenilgandhi** [comment]
Thanks @kajojify .

**Comment by kjkpoi** [comment]
@kajojify Thanks!! The question solved. :)

**Comment by expecttheunusual** [comment]
I find having to install venv and all the other things that come around it just to track down a simple https url a little too complicated
