### ISSUE TITLE
https only runs locally on the host.

### ISSUE THREAD

**Issue by she40841** [mitmproxy/mitmproxy#2942]
##### Steps to reproduce the problem:

1. Follow all the mitm installations - try connecting to a https website when it's done. (it wont run)
2. Add the certificate from mitm.it and try connecting to a https website again, it will connect.
3. Port forward so you can you connect to the proxy on other IPs.
4. When trying to connect to a https website on another IP you will recieve "Your connection is not secure" even when the certificate is installed. You will be able to connect to http links though.

##### Any other comments? What have you tried so far?
I've tried to get this to work for the past 2 days and no success. Is mitm not supposed to run on public net since i can only connect to http links.

**Comment by mhils** [comment]
> When trying to connect to a https website on another IP

I am not exactly sure what you mean by that. You definitely need to have the mitmproxy CA installed on the machine where you are browsing on.

**Comment by she40841** [comment]
@mhils That clears up a lot of things! Thank you. I'm very new to MITM and it's all very confusing. Is there any possible alternative to this? Maybe purchase a ssl license that is reconized by a lot of browsers?

**Comment by mhils** [comment]
You can obtain a publicly-trusted certificate for a domain you control - Let's Encrypt offers them for free for example. You cannot obtain a certificate for a domain you don't control (e.g. google.com).

**Comment by she40841** [comment]
Thank you very much, have a great day.
