### ISSUE TITLE
Cannot filter by UTF-8 string

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#2951]
##### Steps to reproduce the problem:

1. run `mitmproxy`
2. type (in UTF-8) `: set view_filter=~bs Троцкий`
3. “Invalid interception filter: ~bs Троцкий”
4. type `: set view_filter=~bs trotskij`
5. the filter is set and correctly limits the view to flows where response body contains “trotskij”

##### Any other comments? What have you tried so far?

mitmproxy should make it possible to filter by arbitrary UTF-8 strings.

I have `LANG=en_US.UTF-8`; setting `LC_ALL=en_US.UTF-8` doesn’t help.

These don’t work, either:

- `: set view_filter=~bs "Троцкий"` (the quotes are automatically removed after typing the second one)
- `: set "view_filter=~bs Троцкий"`
- `: set view_filter=~bs /Троцкий/`

##### System information

Mitmproxy: 3.0.3 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid

**Comment by fenilgandhi** [comment]
I think this issue occurs because python might not be able to accept the string. 
![deepinscreenshot_select-area_20180304180343](https://user-images.githubusercontent.com/9128903/36945685-c25ddeb6-1fd7-11e8-8083-3bb430258ada.png)

**Comment by mhils** [comment]
Thanks for reporting this! refs #2801
