### ISSUE TITLE
No shortcut for replacements editor

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#2953]
##### Steps to reproduce the problem:

1. run `mitmproxy`
2. type `O` to open the options editor
3. move the cursor down to `replacements` and press Enter
4. type `a` then `/~s/foo/bar` to add a replacement, and press Esc to commit
5. type `q` and again `q` to return to the flows list
6. the status bar now says “[Replacing]” with the ‘R’ highlighted, as if it were a shortcut
7. however, typing `R` doesn’t do anything

##### Any other comments? What have you tried so far?

It seems like `R` was intended to be a shortcut for the replacements editor (which would be very convenient), but left out. It’s not listed in the online help, either.

If it wasn’t intended to be a shortcut, it shouldn’t be highlighted in the status bar.

##### System information

Mitmproxy: 3.0.3 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid

**Comment by proishan11** [comment]
Hi! If someone isn't working on this already, I would like to work on this.

So from the above discussion, I am not sure that whether or not would we be needing R as a shortcut . Also, if we need to make it a shortcut, do I need to add a relevant entry here: https://github.com/mitmproxy/mitmproxy/blob/957a630bb5d2fcd6a8ad7092863d19e38307f090/mitmproxy/tools/console/overlay.py#L67

Thanks!

**Comment by kira0204** [comment]
Hello, I am not working on this, you would like to ask others as well.
@kajojify @fenilgandhi

**Comment by fenilgandhi** [comment]
I had a look into it but hit the same dead end. There is a decision to be made here and needs someone more  familiar with the code as the wrong one would add inconsistency to the code. 

@proishan11  Also if you want to you can start looking into it or wait for @kajojify  to reply.
But if the decision comes in favor of removing the highlight , it can be done here. 
https://github.com/mitmproxy/mitmproxy/blob/957a630bb5d2fcd6a8ad7092863d19e38307f090/mitmproxy/tools/console/statusbar.py#L162

**Comment by kajojify** [comment]
I am not working on it. Feel free to take it :) 
Good luck!

**Comment by proishan11** [comment]
Thanks to your help @fenilgandhi, I am having no problem in removing the highlight.
Also, I want to ask that is there any documentation to get familiar with the code?

**Comment by fenilgandhi** [comment]
hey @proishan11, did you submit a PR on this one ?

**Comment by proishan11** [comment]
@fenilgandhi  I am not working on this. Feel free to take it :)

**Comment by fenilgandhi** [comment]
@vfaronov  Fixed in #2999. Can you close the issue.
