### ISSUE TITLE
Mysql Api

### ISSUE THREAD

**Issue by c0rpse** [mitmproxy/mitmproxy#2958]
How  should I save flows into mysql?
I want to save each flow in flow.response function.

**Comment by kira0204** [comment]
Hi,
You can save different parts of the flows as different columns by using a third-party module [mysql.connector](https://dev.mysql.com/doc/connector-python/en/), third-party modules don't work with our precompiled binaries, more info [here](https://github.com/mitmproxy/mitmproxy/issues/2849#issuecomment-363762607)

Also, you can save all flows in a file instead using pressing `w` on mitmproxy console window and then providing the path, clicking on `mitmproxy(top-left)` -> `Save` if you are using mitmweb, or directly stream the flows to a file as soon as they arrive by `mitmproxy -w PATH` or `mitmdump -w PATH`

**Comment by mhils** [comment]
Thanks @kira0204 and @Gigiarum!

**Comment by c0rpse** [comment]
> Discourse post



> In this [Discourse post](https://discourse.mitmproxy.org/t/har-mongo-dump-script/901) there is my script to save requests and responses to MongoDB.

Thanks a lot!
