### ISSUE TITLE
User's script error handler function

### ISSUE THREAD

**Issue by kira0204** [mitmproxy/mitmproxy#2962]
As discussed with @cortesi on slack, right now whenever a user's script throws an error due to various reasons, it is being handled at different places differently.
Therefore we can have a consistent error handler function which can be invoked whenever there is an error
This will also handle #2837 #2838 #2839 
### Function

Signature
`script_error(path, message, lineno, exception)`

What function will do
>"Error in script XXX:NNN MMM” where XXX is the path as specified by the user (the .path attribute of Script), NNN is a line number if we have one, and MMM is a short message

The idea here is to display the above mentioned message in the console app and display the traceback related to the error in the event log.

**Comment by kira0204** [comment]
Hi,
I was working on this and now I think of it, I have many doubts.
I was thinking that instead of keeping the signature as `script_error(path, message, lineno, exception)` let's keep the signature as `script_error_handler(path, exc, tb = False)`
The optional traceback will help us to handle whether to provide the user with the same or not

The function would roughly look like this 
```
def script_error_handler(path, exc, tb=False):
    """
        Handles all the user's script errors with
        an optional traceback
    """
    exception = type(exc).__name__
    lineno = ""
    if hasattr(exc, "lineno"):
        lineno = str(exc.lineno)
    msg = "Error in Script {}:{} {}".format(path, lineno, exception)
    if tb:
        etype, value, tback = sys.exc_info()
        tback = addonmanager.cut_traceback(tback, "invoke_addon")
        msg = msg.join(["\n"]+traceback.format_exception(etype, value, tback))
    ctx.log.error(msg)
```

which can be called like this
```
try:
    something
except Exception as exc:
    script_error_handler(path, exc)
```
@cortesi  what do you think? :confused:

**Comment by cortesi** [comment]
I think the line number extraction here works - I think a `lineno` attribute is the common API. My rationale for the short message argument is as follows. In the console app, only the first line (or a portion of the first line) of an error is now displayed, and the user has to switch to the event log for everything else. This makes the first line very valuable, and we need to pack as much information as possible in there. It would be nice for this line to say "Syntax error..." and "Exception raised...", and so forth - and in some cases we might be able to give even better information. 

That said, the first step here is to centralise, and then we can tweak the presentation later. Play around until you have a solution that feels right - we can then merge and tweak it.

**Comment by kira0204** [comment]
Hi, so I had this thought process that since the first line is very critical, we might like to provide the user with the name of the type of error that has been raised and providing any other information in place of this would be a big tradeoff(and fitting more than two words at the end of that line would not be very useful if the user has not maximized the window). 
Maybe in the eventlog we can do like, the important first line with path,line no, name of exception type, second line a useful message and then our optional traceback
