### ISSUE TITLE
Transparent mode failure: AttributeError("'Resolver' object has no attribute 'wfile'",)

### ISSUE THREAD

**Issue by GHXST01** [mitmproxy/mitmproxy#2964]
When trying to start mitmproxy in transparent mode and a custom CA directory as followed:
` .\mitmweb.exe --set cadir=C:\Users\Admin\Documents\_custom_cert`

I get the following output:
```
192.168.178.40:46345: Transparent mode failure: AttributeError("'Resolver' object has no attribute 'wfile'",)
192.168.178.40:46345: clientdisconnect
```

I am forwarding port 80 and 443 from my custom router to mitmproxy listening on port 8080.

Any idea what is causing this?

**Comment by GHXST01** [comment]
To clarify; I was having this issue on windows. I decided to move to Linux and it behaves as expected!

**Comment by pravic** [comment]
That's not the solution! How to workaround this on Windows?

**Comment by GHXST01** [comment]
You install Linux on on a VM or you try the built in Linux kernel.

**Comment by pravic** [comment]
Not an option.

**Comment by GHXST01** [comment]
No solution that I know.
