### ISSUE TITLE
How can I speed up mimproxy

### ISSUE THREAD

**Issue by kjkpoi** [mitmproxy/mitmproxy#2970]
In my system, mitmproxy is a bottleneck.
Usually, I visit websites through mitmproxy.
I found cpu usage is really high (over 120% of linux 'top' command), it makes website connection slower.
How can I speed up mitmproxy.
In addition, I use mitmdump and scripting.

Thanks.

**Comment by GHXST01** [comment]
Are you using mitmproxy for what it is intended for ?

**Comment by kjkpoi** [comment]
@GHXST01 Intend for crawling, in the crawling we need script injection

**Comment by mhils** [comment]
You may want to check if your scripts are causing that. If not, #2713 pretty much tracks that we need to work on performance issues, so I'm closing this here.
