### ISSUE TITLE
Icons on About Certificates page aren't clickable

### ISSUE THREAD

**Issue by kenorb** [mitmproxy/mitmproxy#2981]
##### Steps to reproduce the problem:

1. Go to: https://docs.mitmproxy.org/stable/concepts-certificates/
2. Click on one of the icons in _Quick Setup_ section.

##### Any other comments? What have you tried so far?

Nothing happens.  No errors in DevTools

##### System information

Tested on Chrome 66.0.3350.0 and Firefox Quantum 60.0b1 on macOS High Sierra.

**Comment by Kriechi** [comment]
You are not supposed to click those icons.
Please read the instructions, you have to setup mitmproxy, and visit the `mitm.it` page to install the certificate.

**Comment by mhils** [comment]
@Kriechi is correct - this is helpful UX feedback though, we can make it a bit clearer that this is a screenshot. Thanks!

**Comment by kenorb** [comment]
I've been few times on http://mitm.it/, but I'm seeing:

> If you can see this, traffic is not passing through mitmproxy.

Sorry, probably I skip too many paragraphs to make it quick. Will read it again. Thanks.

**Comment by kenorb** [comment]
Ok, I've found the simple instructions:

1. Run: `mitmdump --mode reverse:http://mitm.it/ -p 8080`.
2. Open: http://localhost:8080/
3. Follow the instructions on the page.
