### ISSUE TITLE
Bad HTTP request line: b'\x00`\x16...

### ISSUE THREAD

**Issue by kenorb** [mitmproxy/mitmproxy#2982]
##### Steps to reproduce the problem:

I've run `mitmdump` and I'm connected via app to `localhost:443` and I've got this error:
```
$ sudo mitmdump --mode reverse:https://173.234.x.x:443/ -p 443
Proxy server listening at http://*:443
127.0.0.1:50566: clientconnect
 << Bad HTTP request line: b'\x00`\x16\x95t\x8e\x93\xcdw\xae\x0f\xa6]\xea\xc7\x83\x88\x7f\x9d\xc3\x8e\\h\xc8\xf4-bj\xd6'
127.0.0.1:50566: HTTP protocol error in client request: Bad HTTP request line: b'\x00`\x16\x95t\x8e\x93\xcdw\xae\x0f\xa6]\xea\xc7\x83\x88\x7f\x9d\xc3\x8e\\h\xc8\xf4-bj\xd6'
127.0.0.1:50566: clientdisconnect
127.0.0.1:50592: clientconnect
```

I'm using MetaTrader 4 platform to connect to the server and I'd like to see the traffic between the server. I believe it may use some custom binary protocol? Is there any way that I can dump the binary format instead?

##### System information

```
$ mitmdump --version
Mitmproxy: 3.0.3 
Python:    3.6.4
OpenSSL:   OpenSSL 1.0.2n  7 Dec 2017
Platform:  Darwin-17.3.0-x86_64-i386-64bit
```

**Comment by mhils** [comment]
Hi,

This looks like your app is not using HTTP. You can make mitmproxy fall back to it's raw tcp mode using `--rawtcp`, which will at least dump the binary contents into the log. We hopefully have that in the UI at some point (#1020), but whatsoever this looks like a binary protocol you need to decode at some point. You can maybe use mitmproxy to log TLS master secrets and then dissect it in Wireshark.

**Comment by miaomi** [comment]
Hi,

@mhils Is it possible turn on rawtcp mode for hosts with

>  HTTP protocol error in client request: Bad HTTP request line

 issue in runtime?
