### ISSUE TITLE
Possibility to change color-scheme

### ISSUE THREAD

**Issue by 0x098912378** [mitmproxy/mitmproxy#2983]
mitmproxy doesn't use the default terminal layout (overwriting background-color etc.). It is possible to add custom color, or reset the background to the default terminal-background?

**Comment by Kriechi** [comment]
Yes, mitmproxy support multiple color palettes:

> Color palette. Valid values are 'dark', 'light', 'lowdark', 'lowlight', 'solarized_dark', 'solarized_light'.

`mitmproxy --set console_palette=lowdark`

Or you can set this option in your config file as well.
