### ISSUE TITLE
How to get the first real one url? 

### ISSUE THREAD

**Issue by xiaoTangSSS** [mitmproxy/mitmproxy#2987]
##### Steps to reproduce the problem:

1.
2.
3.

**Comment by kira0204** [comment]
HI @xiaoTangSSS , I couldn't understand the issue you are facing, can you please be more specific and fill the issue template, thanks.

**Comment by xiaoTangSSS** [comment]
HI @kira0204 
when i visit "https://github.com/mitmproxy/mitmproxy/issues"
There will be many requests. ( GET html png js css..)
GET https://github.com/mitmproxy/mitmproxy/issues    ( i only need to get the first request data everytime)
GET https://assets-cdn.github.com/assets/frameworks-a4bf54bef6fb.css
GET https://assets-cdn.github.com/assets/github-ac2ce2821692.css
GET https://assets-cdn.github.com/favicon.ico

when i visit "https://github.com/mitmproxy/mitmproxy/issues"
There will be many requests. ( GET html png js css..)
GET https://github.com/mitmproxy/mitmproxy/issues    ( i only need to get the first request data everytime)
GET https://assets-cdn.github.com/assets/frameworks-a4bf54bef6fb.css
GET https://assets-cdn.github.com/assets/github-ac2ce2821692.css
GET https://assets-cdn.github.com/favicon.ico.

**Comment by fenilgandhi** [comment]
@xiaoTangSSS  There is no exact way to distinguish if a request is actually called by the user or the browser rendering but you can set a `view filter`  to remove the other requests for css js png etc from the flow display list. 
one such filter could be `(~m GET) & (~t text/html) & (~bs [.]+ )`. This one only allows GET requests with some HTML content in the response. You can modify it according to your needs to get better results.

**Comment by xiaoTangSSS** [comment]
@fenilgandhi  thanks!  I've got the HTML data before, the data is filtered by the inline scripts, I want to write the first request and response  data to the database, I haven't found some good ideas yet. 
anyway,thanks for your help!!!

**Comment by kira0204** [comment]
@xiaoTangSSS If your query is answered, can we close this issue?
