### ISSUE TITLE
Keybinding ‘M’ erroneously highlighted

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#2990]
##### Steps to reproduce the problem:

1. run `mitmproxy`
2. type `O` to open the options editor
3. move the cursor down to `default_contentview` and press Enter
4. type `4` to select `json`
5. type `q` to return to the flows list
6. the status bar now says “[M:json]” with the ‘M’ highlighted, as if it were a shortcut
7. however, typing `M` invokes “Toggle viewing marked flows” instead

##### Any other comments? What have you tried so far?

This is similar to #2953.

##### System information

Mitmproxy: 3.0.3 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid

**Comment by mhils** [comment]
Thanks for reporting these with fantastic instructions, this is really helpful! For now let's just remove the binding, we can think about adding it back later. 

If someone wants to tackle the "adding back" part in a second PR, it's a bit more difficult now that shortcuts are user-configurable. We'd need to have a function that returns the current keybinding for a given command, and catch the case, where no keybinding is configured (in which case we probably need to display something else, e.g. `[mode:json]`).

**Comment by fenilgandhi** [comment]
Ok, i am on it. For the time being, i am removing it but if some one is free, the adding back part is still available.
