### ISSUE TITLE
commands taking a filename should expand home dir (tilde)

### ISSUE THREAD

**Issue by majewsky** [mitmproxy/mitmproxy#3002]
##### Steps to reproduce the problem:

1. Open a flow on the response tab.
2. Press "b".
3. When prompted for a filename, enter `~/example`.

This says "No such file or directory". Entering "/home/username/example" works.

##### System information

Mitmproxy: 3.0.3
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.15.10-1-ARCH-x86_64-with-arch

**Comment by kajojify** [comment]
Thanks for the issue.
### Tilda support for commands at this moment.

| Button | Command | Status |
| --- | --- | --- |
| `W` | console.command.set save_stream_file | :heavy_check_mark: |
| `b` | cut.save | :x: |
| `e` | export.file | :x: |
| `L` | view.load | :heavy_check_mark: |
| `L` | options.load | :heavy_check_mark: |
| `S` | options.save | :heavy_check_mark: |
| `r` | console.grideditor.load | :heavy_check_mark: |
| `R` | console.grideditor.load_escaped | :heavy_check_mark: |
| `w` | console.grideditor.save | :x: |
| `shift+\` | script.run | :heavy_check_mark: |

I'll fix this.

**Comment by mhils** [comment]
IIRC at some point it was discussed to have a dedicated `Path` argument type that automatically handles that. Are we tracking that anywhere already?

**Comment by kajojify** [comment]
@mhils I only see, that some commands have `path = os.path.expanduser(path)`

**Comment by mhils** [comment]
It looks like @cortesi started hacking on this: https://github.com/mitmproxy/mitmproxy/blob/443409e32bcc28a7f0475d7af42efff03473b72f/examples/addons/commands-paths.py#L17 - not sure if that auto-expands already?

**Comment by vfaronov** [comment]
> not sure if that auto-expands already?
It doesn’t; would be nice if it did.
