### ISSUE TITLE
open har file error with charles

### ISSUE THREAD

**Issue by coderzhw** [mitmproxy/mitmproxy#3005]
##### Steps to reproduce the problem:

1.
I use mitmdump and har_dump.py to convert the file to har,but when Iopen it with charles,it,s error,
MalformedJson:Use JsonReader.setLenient(true) to accept malformed JSON 

2.
Mitmproxy: 3.0.3 
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-2.6.32-431.el6.x86_64-x86_64-with-centos-6.5-Final

3.
the har_dump.py is 

https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/har_dump.py

**Comment by coderzhw** [comment]
the dump file is as follow link
https://send.firefox.com/download/3f8be846da/#UzMW099RgcYaG-J2uDbUkg

**Comment by kira0204** [comment]
Hi,
I created a HAR file using `har_dump.py` and loaded it successfully by `Charles Proxy`. 
Also the dump file link is expired, if you provide a new link I will test with that as well and revert.

**Comment by coderzhw** [comment]
the dump file can be download as follow:
http://pan.zhangwei.wiki/dump

**Comment by coderzhw** [comment]
[dump.zip](https://github.com/mitmproxy/mitmproxy/files/1846066/dump.zip)

**Comment by coderzhw** [comment]
@kira0204 the file has upload in 4th floor! please help me!

**Comment by kira0204** [comment]
Hi @coderzhw, sorry for the slow response. I converted your flows to a har file using `har_dump.py`, loaded it successfully with Charles. The HAR file can be found here https://files.fm/u/6592asxe. If your HAR file differ from this, please share the file with us so that we might understand what is the problem.

**Comment by coderzhw** [comment]
@kira0204  your har file can be open with charles ,can you tell me whice version of your mitproxy and what command you use tou convert? 
mitmdump -ns har_dump.py -r srcfile -w dstfile.har
is this command right?

**Comment by coderzhw** [comment]
I have solved it ,thank you !
