### ISSUE TITLE
mitmweb as a central transparent mode proxy

### ISSUE THREAD

**Issue by hariszukanovic** [mitmproxy/mitmproxy#3007]
##### Steps to reproduce the problem:

1. Run some traffic through it for a day or so... it seems to happen much quicker when passing bigger files through it (like video streaming)
2. mitmweb uses up all available system memory and system starts swapping, I am even unable to ssh into it

##### Any other comments? What have you tried so far?
Is it possible to configure the mitmweb to avoid running out of memory so it can be run constantly as a central transparent mode proxy. 
I would like to use it for debugging purposes and it would be shared by different people.

Since mitmweb seems to keep flows in the memory, is there an option to limit this memory and throw away oldest requests as the new ones come in?

##### System information

Mitmproxy: 3.0.3 
Python:    3.5.5
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core

**Comment by mhils** [comment]
Hi,

For this particular use case you can probably write your own scripts to remove old flows. We're planning to introduce proper disk-backed sessions, but that's a bit down the track.
