### ISSUE TITLE
No way to set a sequence option on the command line

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#3015]
##### Steps to reproduce the problem:

1. Create a file `/tmp/example.py` with the following text:
```python
import typing
from mitmproxy import ctx

class Example:

    def load(self, loader):
        loader.add_option(name='myoption', typespec=typing.Sequence[str],
                          default=[], help='')

    def response(self, flow):
        ctx.log.info(repr(ctx.options.myoption))

addons = [Example()]
```
2. Run `mitmdump -s /tmp/example.py --set myoption=foo --set myoption=bar`
3. Run a request through it: `curl -sx http://localhost:8080 http://httpbin.org/get`
4. Observe that `['bar']` is printed, meaning that `myoption` is set to a sequence of one element — the last one passed on the command line, with the first one ignored.

##### Any other comments? What have you tried so far?

Looking at [the code](https://github.com/mitmproxy/mitmproxy/blob/79fc4e8ad6cab5181ba39d7f0b0d40f7c11a8389/mitmproxy/optmanager.py#L312-L316), I’m not immediately sure why the multiple `--set` don’t work as I expected them to.

##### System information

Mitmproxy: 4.0.0 (79fc4e8)
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by mhils** [comment]
Thanks for the concise example, this looks like a bug!

**Comment by madt1m** [comment]
I will take a look at this :)

**Comment by cortesi** [comment]
To solve this properly, we will have to define a format for sequences of strings, and teach the `parse_setval` function to know about it. @madt1m mad a valiant attempt to avoid doing this, but I don't think it works. ;)

**Comment by madt1m** [comment]
@cortesi could something in line with the good ol' $PATH-like format do the trick? Changing the --set myopt="opt1;opt2;..."

**Comment by mhils** [comment]
That's tricky because it's plausible to have any of those delimiters in e.g. a regex pattern. I'm afraid we have to go the strenuous route and add an additional "temp dict" argument to `parse_setval`.

**Comment by cortesi** [comment]
I don't want there to be any ambiguity about set on the command-line or in the command prompt: if you set an option, you over-write what was there before in toto. So no book-keeping between --set options, please.

I suggest we do two things:

- Teach `--set` to know about delimited strings. I think `;` or `,` are both fine, and add backslash escaping. This gets complicated in the presence of a shell, but users are familiar with this from all sorts of contexts, and it's bearable.
- I'd be happy to have an `--append` command-line option and matching command that appends a value to a sequence option. This can be used where we don't mind if update is called after every append. We also might need a better name than "append" which is a bit over-loaded.

**Comment by madt1m** [comment]
I'll manage to allocate some time in this weekend for this. I'll try to come up with a feasible solution :)

**Comment by jvilk** [comment]
Just to chime in: This bug / limitation has bit me, as well. I'm going to have to use a string option instead with a custom delimiter and hand-parse it myself to upgrade from MITMProxy 2 (where I just used argparse) to 4.

**Comment by bobvanderlinden** [comment]
I'm having the same issue, but with `server_replay_use_headers`. There doesn't seem to be a command-line argument to add such headers and using `--set server_replay_use_headers headera,headerb` or `--set server_replay_use_headers=headera --set server_replay_use_headers=headerb` doesn't work correctly.

**Comment by Yopi** [comment]
Is there any way to circumvent this limitation? I tried adding an inline script to do something, but it doesn't seem to work.

I.e.
```
from mitmproxy import ctx

ctx.options.server_replay_ignore_params = [
    "one",
    "two"
]
```

It looks correct in `mitmproxy`, but it does not seem to actually do anything.
<img width="371" alt="image" src="https://user-images.githubusercontent.com/641248/93106496-a0c28100-f6b0-11ea-8806-1fe60f91cd30.png">

**Comment by twhitbeck** [comment]
I'm trying to set multiple `--modify-body` options from the command line.
My first assumption was that I would simply supply `--modify-body` multiple times to perform multiple replacements, but that doesn't work. It seems to just take the last option and ignore the others. Is this issue about this problem?

My next thought was that I somehow needed to supply a sequence of patterns to `--modify-body`, but I couldn't for the life of me figure out how I might do that.
