### ISSUE TITLE
Error in loading msxml3.dll in vc2015 

### ISSUE THREAD

**Issue by shmaylibi** [mitmproxy/mitmproxy#3016]
##### Steps to reproduce the problem:

I want to create an instance by this docPtr.CreateInstance(__uuidof(DOMDocument30)); but result is 
Information not available, symbols not loaded for msxml3.dll
#import "C:\\Windows\\SysWOW64\\msxml3.dll" 
using namespace MSXML2;

After doing this dll is not load.
OS : window 10
Visual studio: 2015

**Comment by mhils** [comment]
Hi,

This problem does not seem to be related to mitmproxy at all.
