### ISSUE TITLE
mitmproxy 3.0.3 doesn't work on “Full” transparent mode

### ISSUE THREAD

**Issue by lovethink2** [mitmproxy/mitmproxy#3019]
##### Steps to reproduce the problem:

1. According to instruction at https://docs.mitmproxy.org/stable/howto-transparent/#full-transparent-mode-on-linux
2. Use the command:  ./mitmproxy_shim $(which mitmproxy) --mode transparent --set spoof_source_address=true
3. Got an error: "Server connection to ('xxx.xxx.xxx.xxx', 8086) failed: Error connecting to "xxx.xxx.xxx.xxx": [Errno 99] Cannot assign requested address"

##### System information

Mitmproxy: 3.0.3 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-3.10.0-514.el7.x86_64-x86_64-with-centos-7.4.1708-Core

**Comment by ujjwal96** [comment]
Sorry, fat-fingered the assign button while browsing on cell phone :sweat_smile:

**Comment by mhils** [comment]
This may be a CentOS/RHEL problem, or a problem in combination with the shim. We just call `sock.setsockopt(socket.SOL_IP, socket.IP_TRANSPARENT, 1)`, and apparently that triggers the error you see later on. I'm sorry, but we can't help much with that specific problem.

**Comment by lovethink2** [comment]
Hi mhils, the issue has been resolved. the root cause is that we do not set /proc/sys/net/ipv4/ip_nonlocal_bind to 1.  Anyone who has the same issue can refer to https://codemonkeytips.blogspot.com/2011/07/howto-bind-to-non-local-address.html and https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/load_balancer_administration/s1-initial-setup-forwarding-vsa.

**Comment by mhils** [comment]
Thanks! I'd be very happy to merge a PR that puts this reference in the
docs! :-)
