### ISSUE TITLE
Add threading.Event() to indicate when mitmproxy is ready to receive traffic

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#302]
https://groups.google.com/forum/#!topic/mitmproxy/4YynkCSFUoM
> I am writing an app using libmproxy. The example in the libmproxy document shows functions for run, handle_request, and handle_response. I'm wondering if a similar function is available that would get called when the proxy is running and ready to receive traffic. I would like to have a function called at that time so it could start a browser that would drive the traffic through the proxy. Anyone know if libmproxy has something like this? Thanks.
> I have tried starting the browser process in the run callback, just before calling controller.Master.run(self). It works in my limited testing so far. However, I'm not sure if this will always work or if I am just getting lucky with the timing (i.e., the browser process takes a while to get going, and that gives the call to controller.Master.run(self) time to get the proxy ready to handle traffic).

Rather than relying on race conditions here, we should have a threading.Event() (like should_exit) that signals that mitmproxy has started.

**Comment by albertzaharovits** [comment]
IMHO starting the proxied app after the controller.Master instantion is no race.
controller.Master.init receives a netlib.tcp.TCPServer instance listening on the TCP socket. controller.Master.run will start the Slave thread which will accept any pending connection requests on the socket.
Am I missing something here?

PS I assume one is using libmproxy as in examples/flowbasic

**Comment by cortesi** [comment]
We now have the ``start()`` event, which serves this purpose. It's called on instantiation of the master on all addons. This is after the server has been bound to the socket, so I don't believe there's a race there.
