### ISSUE TITLE
Custom keybindings with modifier keys don’t work

### ISSUE THREAD

**Issue by vfaronov** [mitmproxy/mitmproxy#3023]
##### Steps to reproduce the problem:

1. Run `mitmproxy`
2. Type `:console.key.bind global "ctrl q" console.exit` to add a keybinding
3. Type `?` to open the keybindings list
4. Scroll down to check that Ctrl+Q has been registered as a keybinding along with the built-in Ctrl+B and Ctrl+F
4. Press Ctrl+Q

This should trigger the `console.exit` command and thus exit mitmproxy. Instead, nothing happens.

##### Any other comments? What have you tried so far?

Same if I replace `ctrl q` with `shift pgup`, so not limited to Ctrl.

##### System information

Mitmproxy: 3.0.3 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid

Running in xfce4-terminal 0.6.3

**Comment by madt1m** [comment]
I have reproduced this. I believe the bug stays not in the keybinding mechanism. While debugging, I have noticed that `ctrl q` in particular does not trigger any event.

As an example, please try the same steps, with `ctrl r` binding, and let me know what happens.

**Comment by vfaronov** [comment]
You’re right, `ctrl r` works.

**Comment by madt1m** [comment]
:) considering the situation, I'm not actually sure of how to solve this. The keys aren't caught at Urwid level. A solution could probably be documenting this. Or, furthermore, identify the 'faulty' key combinations and notice the user after having tried registering a keybinding with one of these.

**Comment by vfaronov** [comment]
> documenting this. Or, furthermore, identify the 'faulty' key combinations and notice the user

Sounds good enough to me. Feedback would be helpful in any case, because right now you can e.g. bind `F4` and wonder why it does nothing (because you have to bind `f4` instead).

**Comment by Kriechi** [comment]
Keep in mind that some key combination might already be captured by your terminal, your shell, or whatever else you are running. Unfortunately there is no "one-size-fits-all" solution.

**Comment by vfaronov** [comment]
> some key combination might already be captured by your terminal, your shell, or whatever else you are running

Weird how I forgot about this. Probably because mitmproxy is so pleasant to use you forget it’s running *somewhere*

I checked against nano, which is heavy on Ctrl+keys, and keybindings employed there seem to work in mitmproxy, as well as stuff like `shift f6`, which means I was just unlucky to hit the few problematic cases and generalized from those.
