### ISSUE TITLE
High CPU usage while idling

### ISSUE THREAD

**Issue by gusennan** [mitmproxy/mitmproxy#3039]
##### Steps to reproduce the problem:

1. Install mitmproxy on a Ubuntu Virtual Machine running in virtualbox
2. Start TMUX and open a new window for mitmproxy
3. Run mitmproxy with default settings
4. Run top to monitor CPU usage, notice CPU usage for mitmproxy is around 20%.  See captures from top here: 
[after-starting-mitmproxy.txt](https://github.com/mitmproxy/mitmproxy/files/1875893/after-starting-mitmproxy.txt)
[before-starting-mitmproxy.txt](https://github.com/mitmproxy/mitmproxy/files/1875894/before-starting-mitmproxy.txt)
(note that the CPU usage of the top program is high in these captures since it ran in batch mode to capture savable output.  Typically top drops to < 1% of CPU when run in interactive mode, but mitmproxy hovers around 20%)

##### Any other comments? What have you tried so far?
I took a look at https://github.com/mitmproxy/mitmproxy/issues/1112 and expected that the CPU usage would be under 1%.

##### System information
code> mitmproxy --version
Mitmproxy: 3.0.3 binary
Python:    3.5.2
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-119-generic-x86_64-with-debian-stretch-sid

**Comment by cortesi** [comment]
Hey there. I've just committed a change to our core event loop that has relevance to our idle performance. Could you please check if you still see this behaviour with the current git master?

**Comment by gusennan** [comment]
With HEAD on master, I see it hang around 13-14% CPU:

```(mitmproxy-WQBGXUWx) mitmproxy> mitmproxy --version
Mitmproxy: 4.0.0.dev188 (commit 8e54a36) 
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.4.0-119-generic-x86_64-with-Ubuntu-16.04-xenial```

[head.txt](https://github.com/mitmproxy/mitmproxy/files/1879896/head.txt)

**Comment by cortesi** [comment]
@gusennan Could you please check how the current master fares? I've just refactored our core to use asyncio, and the final part of that is to remove a `tick` event that fired multiple times per second under our old main loop strategy. I think that's probably as far as I can take optimising idle performance at this point.

**Comment by cortesi** [comment]
I think we have this as low as we can (easily) go. Please re-open if you still see significant load and want os to try harder.
