### ISSUE TITLE
GRPC proxy issue

### ISSUE THREAD

**Issue by lars1298** [mitmproxy/mitmproxy#3052]
##### Steps to reproduce the problem:
1.  Attempt to proxy an SSL session over HTTP2 
2.  See that connection is dropped

##### Any other comments? What have you tried so far?
The server is only requiring self-signed certificates installed on the client, so it really not a certificate issue.  Is it possible the stream of data is too fast for a proxy interruption?

##### System information
Kali Linux, Rolling

root@kali:~/Downloads# ./mitmproxy --version
Mitmproxy: 3.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.14.0-kali3-amd64-x86_64-with-debian-kali-rollin

**Comment by Kriechi** [comment]
Do you see an error message in your event log?
Did you try to set the `flow_detail` to 3 and check the output?
Please fill in the system information we asked for the in the issue template.

**Comment by lars1298** [comment]
Sorry about that, updated.

> Here is what I see with debug messages turned on:
:ffff:192.168.150.5:54404: Establish TLS with client
::ffff:192.168.150.5:54404: ALPN for client: b'grpc-exp'
192.168.150.5:54404: Cannot connect to server, no server address given.
192.168.150.5:54404: ProtocolException('Cannot connect to server, no server address given.',)
192.168.150.5:54404: clientdisconnect
192.168.150.5:45070: clientconnect
192.168.150.5:45070: HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)
192.168.150.5:45070: ProtocolException('HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)',)
192.168.150.5:45070: clientdisconnect

**Comment by Kriechi** [comment]
You are trying to proxy an unknown protocol with `ALPN for client: b'grpc-exp'`.
mitmproxy does not support GRPC - only HTTP/1.1 and HTTP/2 via ALPN.

**Comment by 0gawa** [comment]
@Kriechi @lars1298 
I faced the same issue.
The problem is that some gRPC libraries try to start talking HTTP/2.0 by sending ClientHello with ALPN: grpc-exp, not h2. grpc-exp indicates that only gRPC messages will be sent over the HTTP/2.0 connection, so if you like to avoid errors, a workaround would be to replace alpn=grpc-exp in ServerHello with alpn=h2. (It works for me.)

**Comment by takehaya** [comment]
@nkoneko hi. I am having trouble with a similar problem. can you tell me how I rewrote it to alpn = h2?

**Comment by ahmedmani** [comment]
@takehaya did you find a solution to this?

**Comment by takehaya** [comment]
@ahmedmani The recommended way is to stop using mitmproxy
I recommended tools is charles and  grpcdump. What I mean is combinate using. 
It is to derigate the processing of only grpc

**Comment by ahmedmani** [comment]
found a solution i used secure channel and put the server address as the host but used mitmproxy cert to start the connection and the request showed up on mitm

```
import os
proxy = 'http://localhost:8080'

os.environ['http_proxy'] = proxy`
os.environ['HTTP_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTPS_PROXY'] = proxy

mitmproxy cert
with open('/Downloads/mitmproxy-ca-cert.cer', 'rb') as f:
     credentials = grpc.ssl_channel_credentials(f.read())
channel = grpc.secure_channel('aws.api.snapchat.com', credentials)
stub = service_pb2_grpc.serviceServiceStub(channel)
k = stub.call(a)
```

**Comment by MalitsPlus** [comment]
> Here's an implementation of [at]nkoneko's solution:

@tnytown Man you saved my day! Million thanks!
