### ISSUE TITLE
Use Python 3.6 variable type annotations 

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#3053]
A super easy task for someone who wants to get started working on mitmproxy: There are quite a few occasions in the codebase where we still use old-style variable type annotations, e.g. here:
https://github.com/mitmproxy/mitmproxy/blob/660aa87a2471587f3d8a7597a7397be9006db83f/mitmproxy/websocket.py#L66

In Python 3.6 this can be expressed much more nicely without the use of a comment:
```python
self.messages: List[WebSocketMessage] = []
```
(see https://docs.python.org/3.6/whatsnew/3.6.html#whatsnew36-pep526)

A great beginner task to get familar with the whole development process would be to go through the codebase and replace all occurences of `# type:` with the proper new annotation form. That should be pretty straightforward to do, so this issue is strictly meant for first time contributors only. 😃 🚀

**Comment by kira0204** [comment]
Let's close this? Solved via #3059.
