### ISSUE TITLE
save dump file per hour

### ISSUE THREAD

**Issue by coderzhw** [mitmproxy/mitmproxy#3058]
##### Steps to reproduce the problem:
I want to save the output file per hour,How can I do?
mitmproxy -w output 
this command just save one file,I want to save this file by hour,Can you help me?
##### Any other comments? What have you tried so far?
https://groups.google.com/forum/#!topic/mitmproxy/4C-4FiS4W94
this man has the same question,please help me ~

**Comment by mhils** [comment]
Hi,

Please use our forums at discourse.mitmproxy.org for how-to questions. If you some kind of custom log rotation, your best bet is probably to adapt https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/save.py to your needs.
