### ISSUE TITLE
har_dump.py does not convert the req-res in order they were exchanged. 

### ISSUE THREAD

**Issue by avee137** [mitmproxy/mitmproxy#3060]
##### Steps to reproduce the problem:

1.visit 10 sites one after other. capture the dump using mitmdump.
2.convert the dump to har format using har_dump.py
3.the order in which the GET request to sites appear in har is not same as the order they were visited,
   or the order which appears in mitmproxy console when we load the captured dump file

##### System information

Mitmproxy: 3.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.10.0-42-generic-x86_64-with-debian-stretch-sid

**Comment by Gigiarum** [comment]
From [HAR specs](http://www.softwareishard.com/blog/har-12-spec/)
> _entries_
This object represents an array with all exported HTTP requests. Sorting entries by startedDateTime (starting from the oldest) is preferred way how to export data since it can make importing faster. However the reader application should always make sure the array is sorted (if required for the import).

You can check **startedDateTime** field values order.

**Comment by avee137** [comment]
it dumps the request - response like this-

172.24.21.85:42640: GET https://www.google.com/searchdomaincheck?format=domain&type=chrome HTTP/2.0
                 << 200  18b
172.24.21.85:42642: GET http://toogle.com/
                 << 302 Found 170b
172.24.21.85:42644: GET http://buyingedge.com/tst/redirs-nnw.php?blf=toog
                 << 302 Moved Temporarily 0b
172.24.21.85:42656: GET http://nordsrom.com/
                 << 200 OK 290b
.
.
therer is no startedDateTime value.

**Comment by avee137** [comment]
I think I am not using the 'har_dump.py' correctly with the '-s' option. I have a traffic capture using 'mitmdump'. Now I want to extract a '.har' file using this dump. How do i use 'har_dump.py' using '-s' so that i get a '.har' file as an outcome. I used these commands- 
1.
 avkumar@lpro [ har ]$ mitmdump -r emulator-5554_20180415115510.dump -s 'har_dump.py tmp.har'
mitmdump: No such script: "har_dump.py tmp.har"
2.
avkumar@lpro [ har ]$ mitmdump -r emulator-5554_20180415115510.dump -s 'har_dump.py'
dumps the logs only.

Please help, I am blocked on this for long.

**Comment by mhils** [comment]
On mitmproxy 3.0+, the hardump addon registers its own option. You can use for example the following:
```
mitmdump -n -r dump.mitm -s har_dump.py --set hardump=tmp.har
```

Besides, @Gigiarum is right. Strictly speaking this is not a bug, but I'd be happy to merge a PR that sorts the entries.

**Comment by avee137** [comment]
mitmdump -n -r dump.mitm -s har_dump.py --set hardump=tmp.har works
