### ISSUE TITLE
[mitmweb] asyncio has no attribute call_soon

### ISSUE THREAD

**Issue by CorTal** [mitmproxy/mitmproxy#3066]
##### Steps to reproduce the problem:

1.Launch mitmweb
2.Save some flow
3.Load those flows

![asyncio_attribute_error](https://user-images.githubusercontent.com/15815157/38856635-48c7130c-4227-11e8-9019-0caf8f22038c.JPG)

##### Any other comments? What have you tried so far?

https://github.com/mitmproxy/mitmproxy/blob/0fa1280daa94729defa8411d86266bd2b52ad0b6/mitmproxy/tools/web/app.py#L238-L239

I replaced this line with `asyncio.ensure_future(self.master.load_flows(i))` to make the loading works.

##### System information

![mitmdump_version](https://user-images.githubusercontent.com/15815157/38857072-93f56a8a-4228-11e8-8fbb-fed4e11c2745.JPG)

**Comment by cortesi** [comment]
Want to submit a PR for this? Your solution is correct.
