### ISSUE TITLE
[mitmweb] CTRL-C not working

### ISSUE THREAD

**Issue by CorTal** [mitmproxy/mitmproxy#3067]
##### Steps to reproduce the problem:

1.Start mitmweb
2.Try to shutdown with CTRL-C
3.Nothing happens

##### Any other comments? What have you tried so far?

With the signal handler not being implemented on Windows, CTRL-C on mitmweb is not doing anything. On top of that the message "Proxy server listening on ..." doesn't appear anymore.

I found this workaround that I tested myself : 
https://stackoverflow.com/questions/27480967/why-does-the-asyncios-event-loop-suppress-the-keyboardinterrupt-on-windows

It's working, it's just that it's not a clean exit of the program

##### System information

![mitmdump_version](https://user-images.githubusercontent.com/15815157/38858134-336ea1ce-422b-11e8-917a-a329e97591ab.JPG)

**Comment by cortesi** [comment]
A fix for this one is on the way. If you're on Windows, I'd appreciate it if you could test the exit behaviour for me once the PR is  merged.

**Comment by fenilgandhi** [comment]
It's a error specific to Windows. This functionality is not implemented in asyncio itself. I think it is resolved with #3063. You can verify and close the issue.
