### ISSUE TITLE
A New Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [mitmproxy/mitmproxy#3068]
Hello, I'd like to colaborate to this project by delivering a new logo proposal that is more alike with the mame of the proxy, I'm available if this is of your interest.

**Comment by cortesi** [comment]
Hi there. Thanks for the offer, but we like the current logo. I must say, offering logo design to Open Source projects is a great idea, and I think there are many projects that would love a contribution like this.

**Comment by kira0204** [comment]
Hi @LuigiBaute, there are other THP's project such as https://github.com/buffer/thug that would love to have a logo.
