### ISSUE TITLE
Tunneling RTSP over HTTP

### ISSUE THREAD

**Issue by MarvinSmarDTV** [mitmproxy/mitmproxy#3079]
Hi,
I use your proxy in transparent mode for intercepting traffic between an IP camera and a client. I want to modify on the fly the ONVIF command sent to the camera.
During my tests the client requests a RTSP stream over HTTP by sending a HTTP GET request to the server and the server respond with 200 OK without "Content-Length" header because it will send more data next. See https://opensource.apple.com/source/QuickTimeStreamingServer/QuickTimeStreamingServer-412.42/Documentation/RTSP_Over_HTTP.pdf for more details.

The problem is that mitmproxy doesn't forward the response to the client.
The response looks like this:
```
HTTP/1.1 200 OK 
Connection: close 
Content-Type: application/x-rtsp-tunnelled 
```

How can I handle this please ?

##### System information

Mitmproxy: 3.0.4
Python: 3.6.4
OpenSSL: OpenSSL 1.1.0h 27 Mar 2018
Platform: Linux-4.14.0-kali3-amd64-x86_64-with-Kali-kali-rolling-kali-rolling

**Comment by mhils** [comment]
Hi,

This is no proper HTTP, so mitmproxy won't handle it out of the box. You can either switch to TCP mode (https://docs.mitmproxy.org/stable/concepts-protocols/#raw-tcp-tcp-proxy-fallback), or you can manually patch the proxy logic (you can start at https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/protocol/http.py). The former option is definitely easier. :-)

**Comment by MarvinSmarDTV** [comment]
Thanks for your reply, it is possible to make an addon for detecting the GET request with "Accept: application/x-rtsp-tunnelled" header and then ignore this flow (request and future response) ?

**Comment by MarvinSmarDTV** [comment]
Hi,

I come back to you to give a solution and help people who have the same problem.
To solve my issue, firstly I switch mitmproxy in raw tcp mode with:
```sh
mitmproxy --mode transparent --rawtcp --tcp-host '.*' -s RTSPoverHTTP.py
```

and in RTSPoverHTTP.py I modify ONVIF commands at TCP level, so I have to update manually the Content-Length header. Here is an example:
```python
from mitmproxy import ctx


class RTSPoverHTTP:
    def __init__(self):
        pass

    def update_content_length(self, flow, diff):
        """
        Update the Content-Length HTTP header of last message in flow given the
        difference in length between original and modified content
        :param flow: TCP flow
        :param diff: Length difference
        :return: None
        """
        old_content = flow.messages[-1].content
        index_content_length_header = old_content.find(b'Content-Length:')
        content_length = int(old_content[index_content_length_header + 16:index_content_length_header + 16 + 4])

        flow.messages[-1].content = old_content.replace(bytes('Content-Length: {}'.format(content_length), 'ascii'),
                                                        bytes('Content-Length: {}'.format(content_length + diff), 'ascii'))

    def tcp_message(self, flow):
        message = flow.messages[-1]
        old_content = message.content
        if message.content.find(b'Rebooting in 90') != -1:
            message.content = old_content.replace(b'Rebooting in 90', b'Rebooting in 120')

            self.update_content_length(flow, 1)
            ctx.log.info('TCP message replace')


addons = [ RTSPoverHTTP() ]

```

The next step is to use regexp to find and edit the Content-Length header and use mitmproxy classes and functions to parse and modify the HTTP content.

How can I reuse mitmproxy to parse HTTP ?
