### ISSUE TITLE
Improper typing signature in addon causes mitmproxy to fail silently

### ISSUE THREAD

**Issue by gcmurphy** [mitmproxy/mitmproxy#3088]
##### Steps to reproduce the problem:

1. Create the following 'command addon'
```python
# example.py
from mitmproxy import command, ctx

class Addon:
    @command.command('example.command')
    def example(self):
        ctx.log.info("doesn't work")

addons = (
    Addon(),
)
```

2. Attempt to start mitmproxy:

```
# mitmproxy doesn't start and exits without printing an error
$ mitmproxy --verbose -s example.py
$ echo $?
```

##### Any other comments? What have you tried so far?

Whilst this is an error in the addon definition, it was actually quite annoying + difficult to track down. 
(The fix was to add `-> None` in the signature).

##### System information

```
mitmproxy --version
Mitmproxy: 3.0.4 
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Darwin-17.5.0-x86_64-i386-64bit
```

**Comment by cortesi** [comment]
On master this at least doesn't cause mitmproxy to exit without error. However:

- Invoking the command causes mitmproxy to crash.
- In what looks like a separate bug, I don't see the "example.command" command listed in the command palette.

@gcmurphy Thanks for reporting this. We'll get this fixed soon.
