### ISSUE TITLE
SSLv2 Handshake Packets Not Handled

### ISSUE THREAD

**Issue by Yushatak** [mitmproxy/mitmproxy#3092]
The client is Windows for Workgroups 3.11 using an NDIS3 driver for a Kingston KNE20T card and running Opera 3.62 as the browser.

[PCAPs.zip](https://github.com/mitmproxy/mitmproxy/files/1967077/PCAPs.zip)

Two PCAP files here:
mitmproxyOpera3.62https.pcap - With all ciphers enabled.
mitmproxyOpera3.62httpsWithout168Bit.pcap - With the 168-bit 3DES disabled in the client.

It appears that 168-bit 3DES makes the bad request error happen pretty much every time, whereas it's hit-or-miss otherwise. On the occasions where there's no bad request, it hangs without ever responding to the client.

Both sessions were with ssl_client_version=all and ssl_server_version=all just to maximize compatibility, but the same errors occur without these options.

Similar behavior occurs with MSIE5 16-bit.

Mitmproxy: 3.0.4 binary
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-8.1-6.3.9600

**Comment by Yushatak** [comment]
Just tried with MSIE5 (16-bit) and it hung in the same fashion, pretty much identical PCAP.

**Comment by Yushatak** [comment]
Using --rawtcp changes things, there's no bad request error but it doesn't work properly, and on TLSv1 throws a handshaking error. I presume this is due to the nature of how --rawtcp works.

**Comment by Yushatak** [comment]
Tested with Lynx 2.8.5rel1 (OpenSSL 0.9.7d), same bad request issue, and that's not even terribly primitive as far as the browser technology.

```
192.168.137.129:1045: clientconnect
192.168.137.129:1045: Set new server address: www.myabandonware.com:443
 << Bad HTTP request line: b'\x80|\x01\x03\x01\x00c\x00\x00\x00\x10\x00\x009\x00
\x008\x00\x005\x00\x00\x16\x00\x00\x13\x00\x00'
192.168.137.129:1045: CONNECT www.myabandonware.com:443
    Host: www.google.com
    Accept: text/html, text/plain, text/sgml, audio/basic, audio/x-midi, image/x
-icon, image/pict, image/png, image/pcx, image/jpeg, image/bmp, image/targa, ima
ge/tiff, image/x-tiff, image/gif, */*;q=0.01
    Accept-Encoding: gzip, compress
    Accept-Language: en
    User-Agent: Lynx/2.8.5rel.1 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/0.9.7d-dev
    Cookie2: $Version="1"
    Cookie: 1P_JAR=2018-05-02-16; NID=129=CPrYJ8vHuGiBXqoJMAOw3pkU8x5HhuslQ-7PW3
dy5MiFHG3OOV1iDD12aspMpLxpawgOMHroQwTXHm8ZxC32f-ZWOU9aQdmgBDwGu0OVDBt-fzQ7x3zGRn
gyn2arImJm
 << HTTP protocol error in client request: Bad HTTP request line: b'\x80|\x01\x0
3\x01\x00c\x00\x00\x00\x10\x00\x009\x00\x008\x00\x005\x00\x00\x16\x00\x00\x13\x0
0\x00'
192.168.137.129:1045: clientdisconnect
```

**Comment by Yushatak** [comment]
The root cause of this seems to be that SSLv3/TLS (which is essentially SSLv3.1) handshake packets are accepted and SSLv2 ones are not handled in any way.

**Comment by mhils** [comment]
FWIW, I think there are three steps that would be needed to make this work:

1. Compiling cryptography with an OpenSSL version that still allows SSLv2 (pretty sure that's not included anymore by default)
2. Patching our `is_tls_record_magic` function to recognize SSLv2.
3. Explicitly enabling SSLv2 in mitmproxy using mitmproxy's command line arguments.

There should be no need to manually generate SSLv2 packets.
