### ISSUE TITLE
duplicate and replay example error

### ISSUE THREAD

**Issue by turkogluc** [mitmproxy/mitmproxy#3096]
Hello I am trying to understand duplicate and replay process so I tried to run dup_and_replay.py but there is something that I keep getting this error

Addon error: Traceback (most recent call last):
  File "dup.py", line 6, in request
    ctx.master.view.add(f)
AttributeError: 'DumpMaster' object has no attribute 'view'

Could you please help me

**Comment by cortesi** [comment]
Hi there! Thanks for reporting this - I have updated the example in PR #3097, which will be merged shortly. 

There were a number of issues here:

- The "view" addon is only present for interactive tools. I've changed the example to gracefully handle cases where view is absent.
- We want to discourage direct invocation of methods on addons. I've exposed the "view.add" command that lets you add flows to the view.
- Client replay is now also a command. 
- There was an infinite loop issue that I've fixed.

**Comment by turkogluc** [comment]
Hello, Thanks a lot for that quick reaction!

Could you please explain me what is view. I am connecting the proxy from chrome browser. My aim is changing the query parameters in a loop. in case of successful duplicate, is it possible to see in the browser all of these results ? In other words if loop changed the url 10 times, Can I see 10 different response at the browser or should I also add a mechanism to forward these responses to browser ?

And when I tried your example it gives me this error:

Addon error: Traceback (most recent call last):
  File "dup.py", line 14, in request
    ctx.master.commands.call("replay.client", [flow])
TypeError: call() takes 2 positional arguments but 3 were given

I could not understand there are 2 parameters but error says 3 were given.
