### ISSUE TITLE
Release Notes for v4.0

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#3101]
This is a work-in-progress write-up for the upcoming mitmproxy v4.0 release notes:

**Features:**
  * mitmproxy now requires Python 3.6!
  * Moved the core to asyncio - which gives us a significant performance boost!
  * Reduce memory consumption by using `SO_KEEPALIVE` (#3076)
  * Export request as httpie command (#3031)

**Breaking Changes:**
  * `allow_remote` got replaced by `block_global` and `block_private` (#3100)
  * no more custom events (#3093)

**Bugfixes:**
  * Correctly block connections from remote clients with IPv4-mapped IPv6 client addresses (#3099)
  * Expand `~` in paths during the `cut` command (#3078)
  * Remove socket listen backlog constraint
  * Improve handling of user script exceptions (#3050)
  * Ignore signal errors on windows
  * And lots of typos, docs improvements, revamped examples, and general fixes!

**Comment by cortesi** [comment]
I've transferred this to the CHANGELOG file. We're feature complete for 4.0, so there won't be many further changes. Lets track that in the repo.
