### ISSUE TITLE
How to get the real client ip

### ISSUE THREAD

**Issue by Totti0135** [mitmproxy/mitmproxy#3111]
##### Steps to reproduce the problem:
I use the redsocks as a transparent proxy and set the mitmproxy as a upstream-proxy.
In script, I use `cli_ip = flow.client_conn.address`,but the `cli_ip` is the redsocks's ip not the client ip.
I want to know how can I get the real client ip?

##### System information

Mitmproxy version: 2.0.2 (release version)
Ubuntu 3.19.0-25.26~14.04.1-generic 3.19.8-ckt2

**Comment by Kriechi** [comment]
I think you are looking for the `Forwarded` or one of the other headers that redsocks adds:
https://github.com/darkk/redsocks/blob/master/http-connect.c#L267-L282

mitmproxy only sees your redsocks IP - there is no other way to identify the actual client, unless redsocks adds one of these headers to preserve this information.
