### ISSUE TITLE
Proxy constantly erroring on "HttpSyntaxExecption"

### ISSUE THREAD

**Issue by BlackHoleFox** [mitmproxy/mitmproxy#3112]
I'm currently trying to figure out how my Honeywell IoT thermostat talks home and I setup a MITMProxy instance to run all its traffic through, though all that ever appears are console errors saying
```HTTP Protocol error in client request: Bad HTTP request line:  b&#x27;CBKPPR\\x05PB\\x00&amp;\\x00\\x00\\x00\\x00\\xd0-3\\xc1`a^\\xcdOF\\x93\\xe9\\x93\\xbf/\\xadTE\\xd4M\\xca&lt;\\xeb\\x97\\xe4\\xd7B^i}\\x05\\xbf\\xdf\\x85\\xd```

It works fine off the proxy, and I have tried the proxy in both transparent and regular mode. I have the Thermostat's default gateway set to the IP of the MITMInstance. Wireshark analysis shows that Honeywell's server is returning a "Bad Request" and also a "Bad Gateway" to the IP of my Thermostat.

If anyone can shine some light on this topic, it would be greatly appreciated. (Don't you just love IoT?)

##### System information
Mitmproxy: 3.0.4 binary
Python: 3.6.3
OpenSSL: OpenSSL 1.1.0h   27 Mar 2018
Platform: Linux-4.13.0-41-generic-x86_64-with-debian-stretch-sid

**Comment by Kriechi** [comment]
Can you maybe provide a pcap dump (Wireshark) so we can look at the traffic?
I suspect that your IoT device does not use HTTP but maybe some other protocol.
mitmproxy currently only supports HTTP, HTTPs, and Websockets. 
You could try and use our raw-tcp mode!

**Comment by BlackHoleFox** [comment]
@Kriechi Thanks for the fast response!

I tried the raw-tcp mode, to no avail sadly. My testing to this previously shows that it uses TCP of some kind for a keep-alive to their servers. I do know that the commands to change its temp etc are sent over TLS, but I cant capture these as the keep-alive is failing, causing the app to not function.

Here is the file, as requested. (GitHub forced me to ZIP it)
[packetdump.zip](https://github.com/mitmproxy/mitmproxy/files/1991102/packetdump.zip)

**Comment by Kriechi** [comment]
Sorry, but I think they are not using HTTP of any kind which mitmproxy supports.
If you find out more about the protocol we can take another look.

mitmproxy's TCP mode should at least give you a working connection, but you cannot intercept / modify anything.

**Comment by BlackHoleFox** [comment]
@Kriechi Thanks for the insight. I will have to look into it more. Though I do know, raw-tcp isn't allowing it a working connection for what it needs, the Thermostat itself is saying "no internet connection"

**Comment by ColtB45** [comment]
I'm working on reversing the TCP protocol the Honeywell thermostats use. Have you made any further advances here?

I wrote some python code that is really just replaying a previous message against the thermostat and seems to fool it into thinking it's talking to Honeywell but it's not useful by itself.

It seems there is a device specific identifier at h11 - h13 (maybe h10 - h13) in both requests and responses. All data from h14 onward is encoded or encrypted in some unknown way.

I've also replayed streams against the Honeywell servers. All data seems to be protected against modification. Changing a single by forces the server to rst the connection but it can be replayed endlessly.

**Comment by BlackHoleFox** [comment]
@ColtB45 I tried for another week before I gave up. Ended up moving to a new house anyway that didn't have a Honeywell one. In my last bits of testing, I could not figure out anything else out about the protocol they use, sorry.

**Comment by purduephotog** [comment]
I've run into this recently. I can provide a TCPDump of the initial connection and the bad requests; this started about 2 years ago (about the time this got posted) and I constantly am disconnecting.

**Comment by mhils** [comment]
@purduephotog: for protocol-related issues, please upgrade to the latest master version and open a new issue with a minimal example. :)

**Comment by ChuckMash** [comment]
> I'm working on reversing the TCP protocol the Honeywell thermostats use. Have you made any further advances here?
> 
@ColtB45 I'm attempting to do the same, did you ever get anywhere with this?

**Comment by trwbox** [comment]
> > I'm working on reversing the TCP protocol the Honeywell thermostats use. Have you made any further advances here?
> 
> [@ColtB45](https://github.com/ColtB45) I'm attempting to do the same, did you ever get anywhere with this?

@ChuckMash I am also taking a bit of a look at this, so if you learned anything I would love to hear! What I've got so far.
byte 0x00-0x06 seem like a header across all packets
byte 0x07 might also be part of the header, but is always `P` for me.
byte 0x08 seems like a packet type field of some kind. I've seen `B`, `N`, `F`, `P`, `I`, `K`, and `E`. `B` feels like some heartbeat message, I've never seen `P` come from the server only sent from the thermostat. `F` feels like a force push of data of some kind, `N` seems a little more common after a few TCP retransmissions show up so maybe lost data or something.
byte 0x09 has always been 0x00
byte 0x0a (and I think 0x0b) are a uint16 that is the length of packet starting at the MAC address
byte 0x0c-0x0d are repeated across series of packet, but not super clear why? Maybe some sort of packet id or channel. Notably `0x0000` on `B` type messages.
byte 0x0e-0x13 are the wifi mac address of the thermostat
Then the rest of the packet is the length from 0x0a minus 6 for the mac address, but haven't made any progress on it. I haven't done the math on the entropy yet, but it feels like it could be encrypted.

One other note. The CRC for registration based on MAC address, all uppercase (labled MAC ID) is CRC-16/UMTS.

**Comment by ChuckMash** [comment]
@trwbox I came to the same conclusion, everything after the device MAC seems to be encrypted, or at least heavily obfuscated.

I spent far too much time on this and ended up calling it quits when my next right indicated step was to attempt to dump firmware and see if I could dump the encryption keys.
