### ISSUE TITLE
Error while read in output_file contains https

### ISSUE THREAD

**Issue by fourirakbar** [mitmproxy/mitmproxy#3118]
##### Steps to reproduce the problem:

I start with `mitmdump --anticache --anticomp -v -w bisa5.stream`. I try to open HTTP web like `http://if.its.ac.id/`. Then type `mitmdump -nr bisa5.stream --set flow_detail=2 --showhost > outfile3b` it works fine

Then I try to open HTTPS web like `https://github.com/`, there will be an error when I start `mitmdump -nr bisa5.stream --set flow_detail=2 --showhost > outfile3c`

> Addon error: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 239, in response
    self.echo_flow(f)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 222, in echo_flow
    self._echo_message(f.response)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 108, in _echo_message
    self.echo(content)
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 69, in echo
    click.secho(text, file=self.outfp, **style)
  File "/usr/local/lib/python3.5/dist-packages/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python3.5/dist-packages/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 1510: ordinal not in range(128)

> Addon error: Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 239, in response
>     self.echo_flow(f)
>   File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 222, in echo_flow
>     self._echo_message(f.response)
>   File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 108, in _echo_message
>     self.echo(content)
>   File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 69, in echo
>     click.secho(text, file=self.outfp, **style)
>   File "/usr/local/lib/python3.5/dist-packages/click/termui.py", line 420, in secho
>     return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
>   File "/usr/local/lib/python3.5/dist-packages/click/utils.py", line 259, in echo
>     file.write(message)
> UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 163: ordinal not in range(128)
> 
> Addon error: Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 239, in response
>     self.echo_flow(f)
>   File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 215, in echo_flow
>     self._echo_message(f.request)
>   File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 108, in _echo_message
>     self.echo(content)
>   File "/usr/local/lib/python3.5/dist-packages/mitmproxy/addons/dumper.py", line 69, in echo
>     click.secho(text, file=self.outfp, **style)
>   File "/usr/local/lib/python3.5/dist-packages/click/termui.py", line 420, in secho
>     return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
>   File "/usr/local/lib/python3.5/dist-packages/click/utils.py", line 259, in echo
>     file.write(message)
> UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 102: ordinal not in range(128)
> 
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'
> 404 GET /robots.txt (::ffff:192.168.0.15) 0.27ms
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'
> Error in wsgi app. b'Traceback (most recent call last):\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 155, in serve\n    write(i)\n  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/net/wsgi.py", line 124, in write\n    soc.write("HTTP/1.1 {status}\\r\\n".format(status=state["status"]).encode())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n'

##### Any other comments? What have you tried so far?

I follow cortesi answer from https://github.com/mitmproxy/mitmproxy/issues/2918. 

##### System information

Mitmproxy: 3.0.4 
Python:    3.5.2
OpenSSL:   OpenSSL 1.0.2g  1 Mar 2016
Platform:  Linux-4.10.0-38-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by mhils** [comment]
Hi,

Can you share bisa5.stream? How can we reproduce this easily?

**Comment by fourirakbar** [comment]
Hi Mhils!
Thanks for your response. But a day after I post this issue, I know that there are few in error inside bisa5.stream. Now the promblem is clear. Sorry for slow response
