### ISSUE TITLE
mitmproxy 0.18.2 has requirement help me ?

### ISSUE THREAD

**Issue by abkreno2530** [mitmproxy/mitmproxy#3120]
i have this error please help me if you can
![screenshot from 2018-05-12 18-01-13](https://user-images.githubusercontent.com/39168546/39959183-84c6960c-560e-11e8-8310-1788120f396b.png)

**Comment by Kriechi** [comment]
Please use the latest mitmproxy v3.0.4.
v0.18.2 is pretty old and we do not support it anymore - sorry!

**Comment by abkreno2530** [comment]
@Kriechi oky i will try it and i very think you for answer
