### ISSUE TITLE
py3.7 incompatibility: urllib.parse.quote and ~

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#3122]
Testing mitmproxy-master revealed a small issues with the way `urllib.parse.quote` escapes the full byte range:

```python
import urllib.parse
print(urllib.parse.quote(bytes(range(125,128)).decode("utf8", "surrogateescape")))
```
Output:
```
Python 3.6: %7D%7E%7F
Python 3.7-dev: %7D~%7F
```

This currently causes one of our tests to fail: `test/mitmproxy/net/http/test_url.py:123`.

Looking through the Python bugtracker, I found:
https://bugs.python.org/issue16285
https://github.com/python/cpython/commit/21024f06622c4c55b666adb130797a4ee205d005
https://bugs.python.org/issue12910

Can we safely update our code to ignore this, or do we generate a new pitfall by (not) handling this?
We could use the `safe` keyword-arg to include `~`, which then results in the same behaviour on py36 an dpy37.

**Comment by cortesi** [comment]
I think we can ignore quoting of `~` in our test suite. My reading is that both of these behaviours are acceptable, but that the behaviour in 3.7 is more correct. I can't think of a reason why we need to enforce one or the other.
