### ISSUE TITLE
CLI tools and distribution

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#3123]
It's time to reassess how our CLI tools are named and distributed.

- At the moment, we compile separate binaries for all our CLI tools (mitmproxy, mitmweb, mitmdump, pathod and pathoc). For each command, we bundle a complete self-contained interpreter and all its dependencies. This significantly bloats our distribution.
- We need more commands. I'm speccing out a separate command for managing and installing mitmproxy addons. I also think we have a "missing command" for processing flows and exiting, without starting a proxy. Conflating this use case with mitmdump has caused significant complexity and confusion.

All of this together has tipped us over to a point where a single-binary distribution makes sense. See previous discussion in #1526.

# Proposal

I propose that we roll up all of our tools in a single command called **mx**, which is invoked as follows:

- `mx --flags` - equivalent to current `mitmproxy --flags`. This command takes no arguments, so can be the top-level.
- `mx dump args` - equivalent to `mitmdump args`. I think there's an argument for renaming this - the analogy with tcpdump grows tenuous, and "dump" is not really the most apt description of what the tool does.
- `mx web args` - equivalent to `mitmweb args`
- `mx pathod args` - equivalent to `pathod args`
- `mx pathoc args` - equivalent to `pathoc args`

In the next iteration, I would also like to add commands like:

- `mx addon args` - Addon installation and management (`mx addon install`, `mx addon list`, etc.)
- `mx proc args` - Command to process a set of flows and exit, used for conversion, client replay, etc. I'm not attached to the **proc** name here, so lets not argue about that one yet.

**Comment by Kriechi** [comment]
Overall: YES!

But I’m not a big fan of `mx`. I’d like to keep our brand alive: `mitmproxy` is **the** name of our tool. 
Shell auto-completion is good enough to warrant typing the full name of our project.
If you want to introduce a new `mx` command, users will have a hard time after the next release finding and invoking our tools... 

I'd like to stick to `mitmproxy` instead of `mx`:
```
mitmproxy --flags
mitmproxy args
mitmproxy dump args
mitmproxy web args
mitmproxy addon args
mitmproxy proc args
```

I'm open for changes to pathod/pathoc. We can roll them into mitmproxy itself, or keep them as separate tools.

**Comment by cortesi** [comment]
What about something like this as a shorter command that still relates more strongly to the brand?

```
mitm --flags
mitm dump args
mitm web args
mitm addon args
mitm proc args
```

**Comment by Kriechi** [comment]
On my "daily driver" laptop this would not benefit me at all:

`mit<tab>` expands to `mitm`, which is not a full command yet.
`mitm<tab>` then lists me exactly the three mitmproxy tools.

So, assuming we only have one tool called `mitmproxy`, on my system `mit<tab>` would fully auto-complete to `mitmproxy`.

How about your system @cortesi @mhils?

**Comment by cortesi** [comment]
Yes, I guess in the face of ubiquitous tab completion the length of the command might not be critical. I'm not fixated on shortening the command, and would be happy to go with **mitmproxy** if that's the consensus. 

I think it's worth considering the options, though, because if we *do* want to shorten the command this refactoring is probably the last chance to do it. Going from `mitmdump` to `mitm dump` is marginally nicer than going from `mitmdump` to `mitmproxy dump`.

**Comment by Kriechi** [comment]
I think the consensus so far is for keeping `mitmproxy`, @mhils and myself. 
If anyone else wants to raise their voice - now is the time! /cc @mitmproxy/devs

If you really want to shorten the command, I would recommend using a shell alias. 
Feel free to add it to the docs if you feel that strongly about it. 😄

**Comment by dufferzafar** [comment]
I would prefer `mitm`.

A bit related to this, we could create an autocomplete file (for bash, zsh, fish etc.) that would help with commands or their args etc.

**Comment by madt1m** [comment]
We could follow the netcat approach here!
Like, `mitmproxy` or 'mx' (or similar) should both be valid.

> A bit related to this, we could create an autocomplete file (for bash, zsh, fish etc.) that would help with commands & their args etc.

Good shot!

**Comment by mhils** [comment]
For our portable distributions, a name change should be ok - users see the executable name during download. On Windows, we can just alias `mitmproxy` to whatever we decide on. For `pip install`, we can also do what we want in `setup.py`. What's the situation like for brew? Where does brew get the executable names from, and how can we add aliases here?

**Comment by Kriechi** [comment]
@mhils: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mitmproxy.rb
and specifically https://github.com/Homebrew/homebrew-core/blob/14302ab4c188338d6248d86947fa411f1023d427/Formula/mitmproxy.rb#L159

Just to make it clear: I'm against a rename. I want to keep `mitmproxy`.
