### ISSUE TITLE
400 BAD request, HttpException (on mitm.it)

### ISSUE THREAD

**Issue by TonyStark** [mitmproxy/mitmproxy#3127]
##### Steps to reproduce the problem:
```sudo sysctl -w net.ipv4.ip_forward=1```
```sudo iptables -t nat -A PREROUTING -i enp3s0 -p tcp --dport 443 -j REDIRECT --to-port 8080```
```sudo iptables -t nat -A PREROUTING -i enp3s0 -p tcp --dport 80 -j REDIRECT --to-port 8080```
```sudo ./mitmproxy --mode transparent --showhost```
Getting Error while opening mitm.it from my Android
Error is--
> 
> 400 Bad Request
> HttpException('\n Mitmproxy received an absolute-form request even though.......

My ifconfig is
```
enp0s29f7u8 Link encap:Ethernet  HWaddr XXX  
          inet addr:192.168.42.28  Bcast:192.168.42.255  Mask:255.255.255.0
          inet6 addr: 2405:ccc:7306:4d8c/64 Scope:Global
          inet6 addr: XXXea/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8112 errors:1 dropped:0 overruns:0 frame:0
          TX packets:7987 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6120219 (6.1 MB)  TX bytes:1588233 (1.5 MB)

enp3s0    Link encap:Ethernet  HWaddr XXX  
          inet addr:10.42.1.1  Bcast:10.42.1.255  Mask:255.255.255.0
          inet6 addr: feXXXX5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:60978 errors:0 dropped:0 overruns:0 frame:0
          TX packets:40965 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:66103467 (66.1 MB)  TX bytes:6917725 (6.9 MB)
```
In my android wifi, i added proxy as 10.42.1.1 port 8080
And i cant find eventlog :(
How to make it work?

##### Any other comments? What have you tried so far?
Also i tried with mitmweb and it worked, but after click on request i got blank page.
And it seems mitmweb cant capture SSL(HSTS), is that true???
Does mitmproxy successfully capture HSTS request?

##### System information
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

```
Mitmproxy: 3.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.13.0-41-generic-x86_64-with-debian-stretch-sid
```

**Comment by mhils** [comment]
Hi,

From https://docs.mitmproxy.org/stable/concepts-modes/#transparent-proxy:

> Make sure you have not explicitly configured an HTTP proxy on the client. This is not needed in transparent mode.

**Comment by TonyStark** [comment]
@mhils 
still Getting error
I add proxy in my android wifi setting with port 8080
and opened mitm.it and got 400 request
In docs page not everything describe.
right now i execute command ```sudo ./mitmproxy```
can you tell me is that command i typed is right or not.
or do you have any setup tutorial page or docs.
Thank you

**Comment by TonyStark** [comment]
?

**Comment by TonyStark** [comment]
@mhils 
This is still not solved
Now i m on Manjaro OS 64bit
Still when i run ```sudo ./mitmproxy --mode transparent --showhost``` getting 400 BAD request
but if i run only ```sudo ./mitmproxy``` i can successfully load mitm.it page

**Comment by Alirezamn93** [comment]
I'm having this issue. did you find the solution?

**Comment by TonyStark** [comment]
nope :(

**Comment by typoon** [comment]
@TonyStark you should not set a proxy on your Android device. The Android device should have its gateway configured to `10.42.1.1` and that is it. Data will then flow like this:

Android device opens https://www.mitmproxy.it/
Request is sent to the gateway
Gateway redirects request to port 8080
Request goes out to target destination (mitmproxy.it in this case)

**Comment by TonyStark** [comment]
@typoon 
even on linux/windows i got same error
i will try your suggestion on android
should i really set proxy to firefox? i watch on youtube that i dont need to set proxy in firefox if you are using mitm transparent mode.
