### ISSUE TITLE
mitmweb can't be closed by Ctrl+C on Windows anymore

### ISSUE THREAD

**Issue by pravic** [mitmproxy/mitmproxy#3133]
##### Steps to reproduce the problem:

I even compared this behavior with 3.0.4.

**4.0.1:**

1. Run `mitmweb`
2. Press Ctrl+C in console
3. Nothing happens. 
4. if you close web browser, you will get a warning:
5. >`lib\asyncio\base_events.py:492`: RuntimeWarning: coroutine 'Master._shutdown' was never awaited
  self._ready.clear()
6. So, you have to kill `python.exe` manually. 

**3.0.4:**

1. Run `mitmweb`
2. Press Ctrl+C in console
3. `mitmweb` will be closed regardless of a browser.

##### Any other comments? What have you tried so far?

4.0.1 works fine on **Linux**. It may be connected with `asyncio`.

And just a guess: https://gist.github.com/lambdalisue/05d5654bd1ec04992ad316d50924137c (Ctrl+C hotfix patch of asyncio on Windows)

##### System information

> Mitmproxy: 4.0.1
Python:    3.6.2 (3.6.5 - the same issue)
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-7-6.1.7601-SP1

**Comment by mhils** [comment]
Thanks - most likely that's it. Do you want to send a quick PR?

**Comment by Jazzelhawk** [comment]
This also happens with `mitmdump` and the problem was introduced in this commit: https://github.com/mitmproxy/mitmproxy/commit/44016a0de519469792769f7b78c37e7de9bfde24
```
44016a0de519469792769f7b78c37e7de9bfde24 is the first bad commit
commit 44016a0de519469792769f7b78c37e7de9bfde24
Author: Aldo Cortesi <aldo@corte.si>
Date:   Sat Apr 7 11:46:34 2018 +1200

    asyncio: shift script reloading out of the tick event

    The tick event is a nasty compromise, left over from when we didn't have an
    event loop. This is the first patch in a series that explores moving our
    built-in addons to managing coroutines on the eventloop directly for periodic
    tasks.
```

I tried having a go at fixing this but unfortunately I don't know enough about asyncio.

**Comment by pravic** [comment]
Thanks!

**Comment by pravic** [comment]
Works in 4.0.3. Thanks!
