### ISSUE TITLE
SOCKS5 mode failure. Invalid SOCKS version.

### ISSUE THREAD

**Issue by pratham2003** [mitmproxy/mitmproxy#3143]
##### Steps to reproduce the problem:

1. Run mitmweb.exe --version --mode socks5 --listen-port 7878 --listen-host 127.0.0.1
2. Setup firefox to use socks5
3. Try to browse, mitmweb throws error SOCKS5 mode failure: SocksError('Invalid SOCKS version. Expected 0x05, got 0x47',) ... I tried to proxy other app it showed SocksError('Invalid SOCKS version. Expected 0x05, got 0x43',)

##### System information
Mitmproxy: 3.0.4 binary
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.16299

also

Mitmproxy: 4.0.1 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.16299

**Comment by mhils** [comment]
0x47 is a "G", indicating that you probably configured Firefox to use a HTTP proxy, not a SOCKS proxy: Firefox starts with "GET ...". Same for 0x43, which is "C" for (HTTP) CONNECT.

**Comment by IamGiel** [comment]
so what to do here @mhils ???

**Comment by IamGiel** [comment]
anyupdate here?

**Comment by rahmed13** [comment]
@IamGiel were you able to find the solution?

**Comment by 14u9h** [comment]
wow. Problem solved  
Setup firefox to use socks5. Do not set HTTP、SSL、FTP or All.
