### ISSUE TITLE
I close all the connections,  but the Memory is not decreasing

### ISSUE THREAD

**Issue by luckychelsea** [mitmproxy/mitmproxy#3146]
##### Steps to reproduce the problem:
and the memory will increase in a few minutes
                                                                       cpu 0.3  mem 35.3
29863 root      25   5 1071m  348m  4992 S   0.3  35.3   3:22.70 mitmdump 

There is no any connection now.

##### System information
Mitmproxy: 4.0.1 
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-2.6.32-431.el6.x86_64-x86_64-with-centos-6.5-Final

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but you need to demonstrate that you made an effort at solving the problem yourself first. Can I please ask you to follow up in [our community forums](https://discourse.mitmproxy.org/) for all support and how-to questions?


Thanks!
Max
