### ISSUE TITLE
v4.0.1 Client connection killed by block_signal

### ISSUE THREAD

**Issue by luckychelsea** [mitmproxy/mitmproxy#3148]
##### Steps to reproduce the problem:

mitmdump -p 16002 -m reverse:https://172.168.0.190:333 --ssl-insecure --anticache
Proxy server listening at http://*:16002
172.168.0.121:24086: clientconnect
Client connection from 172.168.0.121 killed by block_global
172.168.0.121:24086: Connection killed
172.168.0.121:24086: clientdisconnect
172.168.0.121:24087: clientconnect
Client connection from 172.168.0.121 killed by block_global
172.168.0.121:24087: Connection killed
172.168.0.121:24087: clientdisconnect
172.168.0.121:24088: clientconnect

**but the v3.0.4 is ok**

##### System information

Mitmproxy: 4.0.1
Python: 3.6.5
OpenSSL: OpenSSL 1.1.0g 2 Nov 2017
Platform: Linux-2.6.32-431.el6.x86_64-x86_64-with-centos-6.5-Final

**Comment by CreditTone** [comment]
me too

**Comment by ppp1234** [comment]
me too

**Comment by PoppyGost** [comment]
Did you solve it? how ?

**Comment by kennylbj** [comment]
+ 1

**Comment by lowleveldesign** [comment]
Add `--set block_global=false` as an argument. With --set you may override any of the options listed with `mitmdump --options`. `block_global` is one of them.
