### ISSUE TITLE
Mitmproxy error on startup

### ISSUE THREAD

**Issue by jenskueper** [mitmproxy/mitmproxy#3153]
##### Steps to reproduce the problem:

1. Install the latest mitmproxy version via pip 10 under Debian 9

Hey, I justed updated mitmproxy and if I want to run it, I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 7, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/usr/local/lib/python3.5/dist-packages/mitmproxy/tools/main.py", line 101
    server: typing.Any = None
          ^
SyntaxError: invalid syntax

Does anybody have an idea what causes this?

**Comment by kajojify** [comment]
@jenskueper Hello! Mitmproxy requires Python 3.6+ now. It seems you are using 3.5

**Comment by Joshfindit** [comment]
Might be related?

```
# mitmproxy -T --host
/usr/local/bin/mitmproxy[1]: syntax error: `(' unexpected
```

`OpenBSD hostname 6.7 GENERIC.MP#152 amd64`
`Python 3.8.2`

This is after installing python and extracting https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-linux.tar.gz to `/usr/local/bin`

**Comment by mhils** [comment]
Python 3.8 is explicitly supported in 5.1, so this is unlikely to be related.
