### ISSUE TITLE
block_global option not working

### ISSUE THREAD

**Issue by sameer17cs** [mitmproxy/mitmproxy#3158]
##### Steps to reproduce the problem:

1. --------@mitm:~$ ./mitmdump --block_global false

2.
3.

##### Any other comments? What have you tried so far?
Response:
usage: mitmdump [options] [filter]
mitmdump: error: unrecognized arguments: --block_global

**Comment by Kriechi** [comment]
The correct syntax is:
`$ mitmdump --set block_global=false`
