### ISSUE TITLE
RuntimeError: can't start new thread after few hours

### ISSUE THREAD

**Issue by aznxfrost** [mitmproxy/mitmproxy#3161]
##### Steps to reproduce the problem:

1. Run mitmweb and set it up as a HTTP Proxy
2. Have my other server tunnel through the proxy using PHP CURL
3. After processing thousands of requests, mitmproxy will run out of threads with the following error:

Error in processing of request from ('::ffff:xxx.xxx.xxx.xxx', 42182, 0, 0)
Traceback (most recent call last):
  File "mitmproxy\net\tcp.py", line 621, in serve_forever
  File "threading.py", line 846, in start
RuntimeError: can't start new thread

5. Only way to keep mitmproxy working is keep restarting it every few hours so it closes the thread/leaks  properly.

Note. I have checked other two related issues but they were closed with no real solutions.

##### System information

mitmproxy v4.0 Windows Server 2016

**Comment by lzjun567** [comment]
how to solve it

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
