### ISSUE TITLE
Server replay does not cache POST requests

### ISSUE THREAD

**Issue by gajus** [mitmproxy/mitmproxy#3167]
Using mitmproxy v2 and server replay I was able to server replay all requests, including POST.

It appears that as of version v4 POST requests are not being replayed.

It is unclear having read the entire documentation what is the reason POST requests are not being cached.

**Comment by gajus** [comment]
For the record, I am replaying all the flows using `replay.server @all`.

**Comment by mhils** [comment]
I don't see different behavior between GET and POST, but nothing happens if I `mitmproxy -r [replay.mitm](https://uploads.hi.ls/2018-05/replay.mitm)` -> `replay.server @all`. Clearly a bug, thanks for reporting!

**Comment by Kelvinyang97** [comment]
Hi I’m a newbie in this project but I’m really keen to cobtribute! May I please work on this? Cheers

**Comment by baretomas** [comment]
I am not catching post requests in mitmweb using regular proxy. At least they are not showing in the mitmweb interface.

Is this the same bug?

**Comment by Prinzhorn** [comment]
I think this was fixed in #3705, it was mentioned in #3482
