### ISSUE TITLE
change_upstream_proxy_server 

### ISSUE THREAD

**Issue by baolitoumu** [mitmproxy/mitmproxy#3168]
i have two http proxy serivce :  http://104.199.205.163:8888   and   http://104.155.220.54:8888
when i am run `driver.get('http://httpbin.org/ip')`

and mitmproxy： `mitmproxy -s proxy.py --mode upstream:http://104.199.205.163:8888 --no-http2 --ssl-insecure --set upstream_cert=false`
show ip ：104.155.220.54

`mitmproxy -s proxy.py --mode upstream:http://default-upstream-proxy.local:8080/ --no-http2 --ssl-insecure --set upstream_cert=false`
show the ip ：104.196.15.117

proxy.py
```
def request(flow):
    proxy='104.155.220.54'
    port=8888
    flow.live.change_upstream_proxy_server((proxy,port))
```

why i must set `-mode upstream:http://104.199.205.163:8888` show this ip `104.155.220.54`?
can I  do it through a python script?
Where is the meaning of the option` --mode upstream:http://104.199.205.163:8888 `
I don't want to link extra servers（104.155.220.54）

**Comment by mhils** [comment]
I'm sorry, but I don't understand you question. Can you please rephrase it more clearly?

**Comment by baolitoumu** [comment]
I want to forward the https request to proxy to this server '104.155.220.54', but i must be set `mitmproxy -s proxy.py --mode upstream:http://104.199.205.163:8888 --no-http2 --ssl -insecure --set upstream_cert=false`if I use: `mitmproxy -s proxy.py --mode upstream:http://default-upstream-proxy.local:8080/ --no-http2 --ssl-insecure - -set upstream_cert=false` , can't take effect

**Comment by lonngxiang** [comment]
same assue,confusion

**Comment by langlanglanglanglang** [comment]
> 同样的困惑，困惑

你好，请问你解决这个问题了吗，我遇到同样的问题，甚至我用 -s proxy的方式也不行

**Comment by fail2010** [comment]
new version 8.0 has see same problem, 
![image](https://user-images.githubusercontent.com/6283842/167137334-1e18de7b-4615-486d-932a-8bd6fab14949.png)
mitmdump --mode upstream:http://127.0.0.1:8123 -s mitm_proxy.py -p 8890
show: 
Addon error: Traceback (most recent call last):
  File "mitm_proxy.py", line 27, in request
    flow.live.change_upstream_proxy_server(proxy)
AttributeError: 'bool' object has no attribute 'change_upstream_proxy_server'

and, old version 7 din't show it

**Comment by mhils** [comment]
`change_upstream_proxy_server` does not exist anymore. See https://github.com/mitmproxy/mitmproxy/blob/main/examples/contrib/change_upstream_proxy.py for an alternative.
