### ISSUE TITLE
invalid syntax "server: typing.Any = None"

### ISSUE THREAD

**Issue by cwaazywabbit** [mitmproxy/mitmproxy#3171]
Hi,

no matter how I install mitmproxy (git, pip3, pre-package) I get the following syntax error:
```
    server: typing.Any = None
          ^
SyntaxError: invalid syntax
```

How can I solve this? using Centos 6.9.

Regards

**Comment by madt1m** [comment]
Hey. Can you post your python and mitmproxy versions? Current release requires python 3.6+ :)

**Comment by kajojify** [comment]
The same as https://github.com/mitmproxy/mitmproxy/issues/3153.
