### ISSUE TITLE
multipart/form-data current values are deleted right before editing

### ISSUE THREAD

**Issue by madt1m** [mitmproxy/mitmproxy#3175]
##### Steps to reproduce the problem:

1. Edit with 'e' a POST flow with multipart/form-data type.
![image](https://user-images.githubusercontent.com/20267977/40647853-96e32650-6335-11e8-9cbd-9611a73eb531.png)

2. An empty editor will appear:
![image](https://user-images.githubusercontent.com/25264901/40630461-28b07b86-62d3-11e8-8c17-6ed102bba816.png)

3. Add a row, and go back to check that previous fields have sadly been overwritten:
![image](https://user-images.githubusercontent.com/25264901/40630471-385693f4-62d3-11e8-8180-ce96cbe3d482.png)

![image](https://user-images.githubusercontent.com/20267977/40647865-9dbf1984-6335-11e8-9c4d-f4f46d6d2fd4.png)

##### Any other comments? What have you tried so far?

It seems to me that the editor expects a URL-encoded form type, and thus the unexpected format passes unnoticed, while the new form is saved with the URL-encoded format. I'll wait for some insights from anyone which knows something about it. Otherwise, I'll take a look at it in the next days.

##### System information

Mitmproxy: 4.0.0 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.15.0-kali3-amd64-x86_64-with-debian-kali-rolling

**Comment by kajojify** [comment]
Confirmed for the latest master.

**Comment by kajojify** [comment]
https://github.com/mitmproxy/mitmproxy/blob/7d3d4ca9ea4b7f15c1d34340a5fd7eafee9d1c08/mitmproxy/tools/console/grideditor/editors.py#L64
&#8595;
https://github.com/mitmproxy/mitmproxy/blob/7d3d4ca9ea4b7f15c1d34340a5fd7eafee9d1c08/mitmproxy/net/http/request.py#L429-L430
&#8595;
`is_valid_content_type` is False for multipart/form-data, since the condition checks only application/x-www-form-urlencoded.

**Comment by madt1m** [comment]
Still, here's the logic to parse and decode `multipart/form-data` in the code:
https://github.com/mitmproxy/mitmproxy/blob/a2740ee4aec5bd6258a0d9c17d58b7ef7d2ed3ee/mitmproxy/net/http/request.py#L462

https://github.com/mitmproxy/mitmproxy/blob/a2740ee4aec5bd6258a0d9c17d58b7ef7d2ed3ee/mitmproxy/net/http/request.py#L465
