### ISSUE TITLE
Can find the simple shortcut for copy / export curl, python, body header

### ISSUE THREAD

**Issue by felipeflorencio** [mitmproxy/mitmproxy#3176]
I always used mitmproxy to validate the request's from mobile request, and the easy step that I always did is some keyboard shortcut inside the flow details to export the curl, as python, header, body.

After search to much I did not found anything else to this simples task that was there before, does anyone know how to show this options again?

Before was just that easy: Shift + C

**Comment by kajojify** [comment]
If you need more help, please reopen this issue :)
