### ISSUE TITLE
connection not private error on android chrome

### ISSUE THREAD

**Issue by TonyStark** [mitmproxy/mitmproxy#3179]
##### Steps to reproduce the problem:

I have installed certificate using this method on android (https://github.com/mitmproxy/mitmproxy/issues/2054#issuecomment-327735569)
So before week mitmproxy works fine, google had opened successfully in android chrome browser
but today i tried to open google it said your connection is not private
i also clear user credential, and update mitmproxy v4, reinstalled certificate
but still getting error that your connection is not private.

##### Any other comments? What have you tried so far?
Removed Certificate, reinstalled using adb method
tried ```--ssl-insecure``` not work

##### System information

Mitmproxy: 4.0.1 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.13.0-43-generic-x86_64-with-debian-stretch-sid

##### ./mitmdump
```
10.42.0.204:53930: CONNECT www.google.co.in:443
 << Cannot establish TLS with client (sni: www.google.co.in): TlsException("(-1, 'Unexpected EOF')",)
10.42.0.204:53930: clientdisconnect
10.42.0.204:53931: clientconnect
10.42.0.204:53932: clientconnect
10.42.0.204:53931: CONNECT www.google.co.in:443
 << Cannot establish TLS with client (sni: www.google.co.in): TlsException("(-1, 'Unexpected EOF')",)
10.42.0.204:53931: clientdisconnect
10.42.0.204:53933: clientconnect
10.42.0.204:53932: CONNECT www.google.co.in:443
 << Cannot establish TLS with client (sni: www.google.co.in): TlsException("(-1, 'Unexpected EOF')",)
10.42.0.204:53932: clientdisconnect
10.42.0.204:53933: CONNECT www.google.co.in:443
 << Cannot establish TLS with client (sni: www.google.co.in): TlsException("(-1, 'Unexpected EOF')",)
10.42.0.204:53933: clientdisconnect
10.42.0.204:53934: clientconnect
10.42.0.204:53934: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(104, 'ECONNRESET')",)
10.42.0.204:53934: clientdisconnect
10.42.0.204:53935: clientconnect
10.42.0.204:53935: CONNECT clients4.google.com:443
 << Cannot establish TLS with client (sni: clients4.google.com): TlsException("(104, 'ECONNRESET')",)
10.42.0.204:53935: clientdisconnect
10.42.0.204:53936: clientconnect
10.42.0.204:53937: clientconnect
10.42.0.204:53936: POST http://event.apiv9.com/event.php
                << 200 OK 33b
10.42.0.204:53937: CONNECT www.google.com:443
 << Cannot establish TLS with client (sni: www.google.com): TlsException("(-1, 'Unexpected EOF')",)
10.42.0.204:53937: clientdisconnect
10.42.0.204:53936: POST http://event.apiv9.com/event.php
                << 200 OK 33b


```

**Comment by mhils** [comment]
Hi,

Your error messages indicate that the client is not trusting mitmproxy's CA. I don't think this is a bug in mitmproxy?

**Comment by TonyStark** [comment]
Hi
Okay let me check again today
I will reply soon

**Comment by TonyStark** [comment]
okay today i reinstalled certificate in /etc/security/cacert directory
also disable and re-enabled from settings>securitys>trusted certificate
then run mitmproxy --showhost
now same private connection error is appear in chrome browser
also blank terminal window too
and strange thing is i can send email from gmail app successfully. But mitmproxy did not display any request made from gmail app too
Any idea bro, whats problem?
PS. simple http site display request in mitmproxy window, but https connection remain blank

**Comment by bastova** [comment]
This is likely caused by this error NET::ERR_CERT_WEAK_SIGNATURE_ALGORITHM
I am seeing this error in Desktop Chrome browser, google recently updated Chrome to now allow SHA-1 certificates. They need to be updated. I presume they update the Chrome on Android as well.

**Comment by mhils** [comment]
Recent mitmproxy releases generate proper certificates, so the fix here is to 1) update mitmproxy, 2) delete ~/.mitmproxy, 3) start mitmproxy, and 4) install the new certificate.
