### ISSUE TITLE
SyntaxError on any mitmproxy/mitmweb command

### ISSUE THREAD

**Issue by hkevicBB** [mitmproxy/mitmproxy#3187]
##### Steps to reproduce the problem:

1. Clean installation of both Python and Mitmproxy (and all other dependencies, followed tutorial from https://www.adamengle.com/2016/12/08/raspberry-pi-3-mitmproxy/)
2. Execute any of the mitmproxy or mitmweb commands, i.e.:
mitmproxy --version
or
mitmweb -h

3. Results in the SyntaxError below.

##### Any other comments? What have you tried so far?
Tried to reinstall components, downloading the latest Mitmproxy from the web and manual installation;
rebooted the system (Raspberry Pi)

##### System information
Traceback (most recent call last):
  File "/usr/local/bin/mitmweb", line 7, in <module>
    from mitmproxy.tools.main import mitmweb
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/tools/main.py", line 101
    server: typing.Any = None
          ^
SyntaxError: invalid syntax

pi@RaspberryPi:~ $ mitmproxy --version
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 7, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/usr/local/lib/python3.5/site-packages/mitmproxy/tools/main.py", line 101
    server: typing.Any = None
          ^
SyntaxError: invalid syntax

**Comment by Kriechi** [comment]
This has been reported multiple times already - mitmproxy requires Python 3.6 or higher.

I assume Raspbian currently ships with Python 3.5 - so you need to install a matching Python interpreter manually.
