### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by rajkotraja** [mitmproxy/mitmproxy#3195]
Proxy giving this error
502 Bad Gateway
ProtocolException('Server connection to (\'www.oraculous.in\', 80) failed: Error connecting to "www.oraculous.in": [Errno -3] Temporary failure in name resolution',)

**Comment by rajkotraja** [comment]
mitmproxy version is 4.0
operating mode or command was mitmdump -p 8080

i installed python 3.6 and then mitmproxy on ubuntu 18.04

**Comment by mhils** [comment]
The error message states that mitmproxy cannot resolve the IP address of www.oraculous.in. That's not a mitmproxy issue, that's a problem with your internet connectivity (or with www.oraculous.in being unavailable in general).

**Comment by mhils** [comment]
See also: #3203
