### ISSUE TITLE
request event is fired 4 times when it is supposed to be fired only once

### ISSUE THREAD

**Issue by P0oOOOo0YA** [mitmproxy/mitmproxy#3197]
I'm trying to learn mitmproxy but there are not many examples on the internet and also on the documentation. Please provide more and more real word examples of using mitmproxy for app development and modifying flows on the fly. It is much appreciated.

I'm using mitmproxy to mitm between Android sdkmanager and  google android repository (dl.google.com). The goal is to add the requested package url to aria2 download manager via a wrapper around aria rpc if the package is not on the hard drive  and if it is, feed sdkmanager with the package on the local machine. I have achieved my goal thanks to aria2 and mitmproxy but i noticed something weird on my download session. ***Every  package url is repeated exactly four times***. 

pseudo code follows

	def request(a_flow):
	    path = a_flow.request.path
	    if a_flow.request.host == "dl.google.com" and not path.endswith(".xml"):
		if package_on_the_machine:
			// redirect the request to local server
		else:
			// add the package url to aria2
			a_flow.kill()

	def responseheaders(a_flow):
	    if a_flow.request.host == "127.0.0.1":
        	a_flow.response.stream = True

**Comment by mhils** [comment]
Hi,

I'm sorry, but it's not exactly clear to me what your issue is.
