### ISSUE TITLE
TlsException("(-1, 'Unexpected EOF')",)

### ISSUE THREAD

**Issue by aznxfrost** [mitmproxy/mitmproxy#3201]
##### Steps to reproduce the problem:

Running mitmdump with just port parameter, while some websites works flawlessly some websites simply doesn't work at all.

```
127.0.0.1:59082: clientdisconnect
127.0.0.1:59086: clientconnect
127.0.0.1:59086: CONNECT 35.173.95.148:443
 << Cannot establish TLS with client (sni: polka.typekit.com): TlsException("(-1, 'Unexpected EOF')",)
127.0.0.1:59086: clientdisconnect
127.0.0.1:59089: clientconnect
127.0.0.1:59089: CONNECT 34.235.245.109:443
 << Cannot establish TLS with client (sni: tch83795.tch.quora.com): TlsException("(-1, 'Unexpected EOF')",)
127.0.0.1:59089: clientdisconnect
127.0.0.1:59097: clientconnect
127.0.0.1:59097: CONNECT 52.72.185.152:443
 << Cannot establish TLS with client (sni: scss.adobesc.com): TlsException("(-1, 'Unexpected EOF')",)
```

##### System information

Mitmproxy: 4.0.1 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.14393

**Comment by anish312** [comment]
Can anybody point out which files to modify/work on to fix this issue?

**Comment by mhils** [comment]
Hi,

The error you are seeing here indicates that the client abruptly disconnected during the TLS handshake, most likely because it does not trust mitmproxy's certificate. There's not much we can do about this, see https://docs.mitmproxy.org/stable/concepts-certificates/#certificate-pinning.
