### ISSUE TITLE
Unable to replay a https connection when offline - 502 Bad Gateway (Errno 3: Temporary failure in name resolution)

### ISSUE THREAD

**Issue by GuillaumeGETTE** [mitmproxy/mitmproxy#3203]
##### Steps to reproduce the problem:

1. run "mitmdump -w test.replay"
2. visit https://example.com via the proxy
3. stop mitmdump & cutoff web connection
4. run mitmdump in replay mode : "mitmdump -S test.replay"
5. try to access the same webpage

I obtain the following error: 502 Bad Gateway (Errno 3: Temporary failure in name resolution)

##### Any other comments? What have you tried so far?
I tried to disable the server_replay_refresh option, didn't solve it.
While replaying, wireshark shows that mitmdump still tries to connect to the remote server (which in my case fails since I'm offline).  

##### System information

Mitmproxy: 4.0.1
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.16.13-2-ARCH-x86_64-with-arch

**Comment by mhils** [comment]
Does `mitmdump --set upstream_cert=false` do the trick for you?

**Comment by GuillaumeGETTE** [comment]
Thank you !  It works.
