### ISSUE TITLE
4.0.3 socks5 mode sucks [2]

### ISSUE THREAD

**Issue by Sfinx** [mitmproxy/mitmproxy#3209]
##### Steps to reproduce the problem:

1. setup two socks5 proxies (srelay & mitmproxy) at some amazon server (I've used free tier)
2. install stock ubuntu tsocks app at your test box
3.  use simple /etc/tsocks.conf:

```
server = amazon_server_ip
# Server type defaults to 4 so we need to specify it as 5 for this one
server_type = 5
# The port defaults to 1080 but I've stated it here for clarity
server_port = 8080
```

4. launch slrealy proxy at amazon server and check some connection from some external to amazon host test box : **tsocks telnet some_host 22**

```
Trying xxxxx...
Connected to xxxxxx.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
```
All is working as expected.

5. Stop srelay, launch mitmproxy as **mitmproxy -m socks5** :

```
tsocks telnet xxxxx 22
Trying xxxxx...
telnet: Unable to connect to remote host: Transport endpoint is not connected
```

Stock Ubuntu 16.04.4 LTS at amazon & Ubuntu 18.04 as second box & 4.0.3 mitmproxy

**Comment by Sfinx** [comment]
Made a typo about telnet over mitmproxy output:

```
tsocks telnet xxxxx 22
Trying xxxxx...
telnet: Unable to connect to remote host: Transport endpoint is not connected
```

**Comment by mhils** [comment]
this looks like a configuration issue on your end, "Transport endpoint is not connected" means no TCP connection could be established with the server.
