### ISSUE TITLE
mitmproxy binary self-corruption (Ubuntu 18.04)

### ISSUE THREAD

**Issue by Sfinx** [mitmproxy/mitmproxy#3212]
##### Steps to reproduce the problem:

1. get the 4.x mitmproxy release from github, untar it to /usr/local/bin
2. work with some traffic
3. exit and try to start binary again, you will get:

```
[13310] Cannot open self /usr/local/bin/mitmproxy or archive /usr/local/bin/mitmproxy.pkg

```

Noticed that file size of corrupted binary have been increased:

```
~# l /usr/local/bin/old/mitmproxy 
-rwxr-xr-x 1 2000 2000 22450352 Jun 16 07:51 /usr/local/bin/corrupted_mitmproxy*
~# l /usr/local/bin/mitmproxy 
-r-xr-xr-x 1 2000 2000 22444880 Jun 16 07:51 /usr/local/bin/mitmproxy*

```

**Comment by Kriechi** [comment]
Sorry, but I'm unable to reproduce this on a fresh Ubuntu 18.04.
Please verify that your downloaded archive matches the one we provide:
```
root@b1b80d3e0e80:/# sha256sum /usr/local/bin/*
58656835f8546b3361099770b8cd5cd7d943095b8d0922ca1d3f1b142507ede6  /usr/local/bin/mitmdump
9907fbfc362917c187fbc133d567325b300debfe9737371b5caf11307a274f11  /usr/local/bin/mitmproxy
fa4cb46562143275e99dddeecc765b838b0ea61a2fc63a3e359cecf1e1a19421  /usr/local/bin/mitmproxy-4.0.3-linux.tar.gz
714e76a2074f16674499a929c2818643f156fd62be48e8a7d78275c2691b9463  /usr/local/bin/mitmweb
root@b1b80d3e0e80:/# ls -la /usr/local/bin
total 130848
drwxr-xr-x 1 root root     4096 Jun 17 06:37 .
drwxr-xr-x 1 root root     4096 May 26 00:44 ..
-rwxr-xr-x 1 2000 2000 22091192 Jun 16 04:51 mitmdump
-rwxr-xr-x 1 2000 2000 22444880 Jun 16 04:51 mitmproxy
-rw-r--r-- 1 root root 66644723 Jun 16 04:53 mitmproxy-4.0.3-linux.tar.gz
-rwxr-xr-x 1 2000 2000 22787936 Jun 16 04:52 mitmweb
root@b1b80d3e0e80:/# uname -a
Linux b1b80d3e0e80 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Sfinx** [comment]
It is definitely not related to download issue as :

a) github tar.gz unpacks ok without gzip csum errors
b) the first app run is successful
c) the size of the binary changes **after** the first successful binary start
d) the corrupted binary do not start anymore

If the issue was related to the corrupted download then the first 3 points were false. Anyway chmod -w /usr/local/bin/mitmproxy helps me so far

**Comment by Kriechi** [comment]
The error itself comes from pyinstaller - and the only reference I could find about it was 
https://github.com/pyinstaller/pyinstaller/blob/07ab024c395619e7a220628f99173ca64e044d88/bootloader/src/pyi_main.c#L95 and https://github.com/pyinstaller/pyinstaller/issues/3142

**Comment by Sfinx** [comment]
Found the issue, it is not related to the mitmproxy ;) This bug triggered after usual Ubuntu prelink cron job  run (/usr/sbin/prelink -a -mR -T -q)

**Comment by Sfinx** [comment]
https://github.com/pyinstaller/pyinstaller/issues/1812

**Comment by Kriechi** [comment]
Good find! The issues seems to be fixed already - then why are you still seeing this on your system?
Do we need to upgrade our pyinstaller integration?
Maybe this one is still relevant to us: https://github.com/pyinstaller/pyinstaller/issues/3441

**Comment by Sfinx** [comment]
Exactly - this issue appeared again at newer pyinstaller ;) Seems like guys do not bother with regression tests at all. All I can do here is to supply enough debug/reproduce info as I'm dumb in python. It is 100% reproducible at my system so I've to add exception for mitm* binaries to prelink config.
