### ISSUE TITLE
SOAP problem?

### ISSUE THREAD

**Issue by paul-bell** [mitmproxy/mitmproxy#3214]
##### Steps to reproduce the problem:

1. mitmdump --mode reverse:https://172.19.7.40:443 -p 8082 -v -w ./vsphere.log --ssl-insecure -s ./pbtest.py > shell.log
2. start the client application (talks to 172.19.7.40) and attempt to register 172.19.7.40. This is done by pointing the client to the IP:PORT where mitmdump (or mitmproxy) is running.

##### Any other comments? What have you tried so far?

The server at 172.19.7.40:443 is a VMware vSphere server. The client registration of this server involves client use of the vSphere SDK APIs. My understanding is that these APIs talk "SOAP".

The shell.log file contains this:

```
Proxy server listening at http://*:8082
172.20.2.157:51319: clientconnect
::ffff:172.20.2.157:51319: serverconnect
  -> ('172.19.7.40', 443)
::ffff:172.20.2.157:51319: Establish TLS with server
::ffff:172.20.2.157:51319: Certificate verification error for 172.19.7.40: unable to get local issuer certificate (errno: 20, depth: 0)
::ffff:172.20.2.157:51319: Ignoring server verification error, continuing with connection
::ffff:172.20.2.157:51319: ALPN selected by server: -
::ffff:172.20.2.157:51319: Establish TLS with client
 << Invalid header line: b'SOAPAction\r\n'
::ffff:172.20.2.157:51319: serverdisconnect
  -> ('172.19.7.40', 443)
172.20.2.157:51319: HTTP protocol error in client request: Invalid header line: b'SOAPAction\r\n'
172.20.2.157:51319: ProtocolException("HTTP protocol error in client request: Invalid header line: b'SOAPAction\\r\\n'",)
172.20.2.157:51319: clientdisconnect
```

##### System information

Mitmproxy: 4.0.3
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-2.6.32-642.11.1.el6.x86_64-x86_64-with-centos-6.9-Final

Grateful for any light you can shed on this.

-Paul

**Comment by paul-bell** [comment]
Suppose that the vSphere SOAP protocol does not return a valid HTTP response or, at least that it doesn't return HTTP headers where they are expected to be.

Is it possible to provide a script to mitmproxy or  mitmdump that tolerates this, e.g., don't process the response headers - and don't choke on them. Instead, simply return the data to the requesting client?

If so, can you provide an example of how to do this?

Thanks.

**Comment by mhils** [comment]
Hi,

This indeed looks like you are not dealing with HTTP traffic. You can use mitmproxy's raw tcp mode to exempt traffic from parsing (https://docs.mitmproxy.org/stable/concepts-protocols/#raw-tcp-tcp-proxy-fallback), although that limits you in what you can do.

**Comment by moonlitSpider** [comment]
Hi,

Thank you for getting back to me about this.

In fact, I did get this working by means of raw TCP. In the process I learned that, in fact, the initial client request in this conversation contains what purports to be an HTTP header that consists of 'SOAPAction' just as I wrote it - no colon after the term, and no value.

I may also have stumbled over the mitmproxy code that splits on the colon and complains about lack of a value.

While I suppose that this header's structure represents a protocol violation, it might not be a bad idea if you could tolerate it. Just a thought.

I will likely have some more questions for you about how to proxy an NFS server, but I'll open them in a different issue.

Thanks again!

**Comment by mhils** [comment]
> While I suppose that this header's structure represents a protocol violation, it might not be a bad idea if you could tolerate it. Just a thought.

Yes, slippery slope unfortunately. If we accept lines without colons, many not HTTP-ish protocols may suddenly be parsed by our HTTP parser, which probably creates a bunch of cunfusing errors somewhere else. At this point I'm rather inclined to say no to this as long as it stays a rather obscure phenomenon.

Thanks for the quick feedback!
