### ISSUE TITLE
Parsing log output

### ISSUE THREAD

**Issue by moonlitSpider** [mitmproxy/mitmproxy#3215]
##### Steps to reproduce the problem:

1. mitmdump --mode reverse:https://172.19.7.40:443 -p 8082 -v -w ./w1.log --rawtcp --tcp-host 172.19.7.40 --ssl-insecure -s ./tcp_message.py > stdout1.log

##### Any other comments? What have you tried so far?
I would like to write a program to parse the output in stdout1.log (the redirected file named above). But I noticed this anomaly (seen here and elsewhere in the log): the initial 'P' as in 'POST' is interrupted by 1 line of output from mitmdump and 1 line from your example script tcp_message.py. The following line continues the 'OST' from 'POST'.

To simplify parsing this output, is there a way to prevent this behavior, e.g., flushing log after each write?

Thank you.

```
P
172.20.2.157:60377 -> tcp -> 172.19.7.40:443
[tcp_message] from client to server:
OST /sdk HTTP/1.1\r\nSOAPAction: urn:vim25/5.5\r\nContent-Type: text/xml; charset=utf-8\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nUser-Agent: Java/1.7.0_80\r\nHost: 71.100.14.12:8082\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\nConnection: keep-alive\r\nContent-Length: 439\r\n\r\n
172.20.2.157:60377 -> tcp -> 172.19.7.40:443
```

##### System information

Mitmproxy: 4.0.3
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-2.6.32-642.11.1.el6.x86_64-x86_64-with-centos-6.9-Final

**Comment by kitardevil** [comment]
172.20.2.157:60377 -> tcp -> 172.19.7.40:443
[tcp_message] from client to server:
OST /sdk HTTP/1.1\r\nSOAPAction: urn:vim25/5.5\r\nContent-Type: text/xml; charset=utf-8\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nUser-Agent: Java/1.7.0_80\r\nHost: 71.100.14.12:8082\r\nAccept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2\r\nConnection: keep-alive\r\nContent-Length: 439\r\n\r\n
172.20.2.157:60377 -> tcp -> 172.19.7.40:443

**Comment by mhils** [comment]
Hi,

I'd definitely recommend against parsing mitmproxy's stdout output. You can write your own addon that just dumps things into a file in the format you prefer. Here's the addon that generates the stdout output: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/dumper.py
