### ISSUE TITLE
NET::ERR_CERT_WEAK_SIGNATURE_ALGORITHM

### ISSUE THREAD

**Issue by bastova** [mitmproxy/mitmproxy#3219]
Getting "Your connection is not private" error in Chrome browser.
Based on the error description, looks like the mitmproxy certificate is using SHA-1 hashing, which is deemed insecure and is no longer supported by any Chrome browser version. The certs need to be updated to use SHA-256.

**Comment by mhils** [comment]
Did you upgrade to the lastest version and did you delete your ~/.mitmproxy folder before starting? You may have an old cert from an old install.
