### ISSUE TITLE
Console string escaping round trips

### ISSUE THREAD

**Issue by cortesi** [mitmproxy/mitmproxy#3220]
We have a bit more work to do with console string escaping round trips. On the command line, enter the following:

   : console.command "\"foo\""

First, note that the highlighting is inconsistent. Second, note that what appears on the command-line afterwards is:

    : \ foo\""

There are a few more round-trip issues of this sort.

**Comment by mhils** [comment]
This has been fixed by @typoon a while ago, closing this! 😃
