### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by Octolus** [mitmproxy/mitmproxy#3222]
I have removed the certificate pinning from the application, and redirected all the traffic via MITMPROXY UI.

I can read the HTTPS Traffic, but the "Secure Web Socket" traffic isn't anywhere? I can use a debugger like Charles, which would show raw connection.

Does the web ui support "SECURE WEB SOCKETS"? It connets fine to it, just can't read it using the tool..

```
::ffff:127.0.0.1:61258: Certificate verification error for None: self signed certificate (errno: 18, depth: 0)
::ffff:127.0.0.1:61258: Ignoring server verification error, continuing with connection
```

**Comment by Kriechi** [comment]
Unfortunately our UIs don't support WebSockets quite yet - but all our tools will process them!
Take a look at https://docs.mitmproxy.org/stable/concepts-protocols/#websocket and all the `websocket_*` events https://docs.mitmproxy.org/stable/addons-events/#supported-events, so you can write a little script to log, intercept, or modify WebSocket messages.
