### ISSUE TITLE
requestheaders addon event problem

### ISSUE THREAD

**Issue by Gigiarum** [mitmproxy/mitmproxy#3224]
I wrote an addon which implements both `requestheaders` and `request` addon events. Sometimes I receive `None` value from `flow.request.host` property in `requestheaders`. Same property in `request` event returns correct value. This problem does not appear for `flow.request.path` property.

##### System information

Mitmproxy: 4.0.1
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-3.16.0-6-amd64-x86_64-with-debian-8.9

**Comment by Kriechi** [comment]
Do you have an example URL, or a dump file that you can upload?
Do you see any error messages in the eventlog?

**Comment by Gigiarum** [comment]
Here my output log.

> 192.168.3.193:59083: clientconnect
> ::ffff:192.168.3.193:59083: Set new server address: my-remote-site:443
> ::ffff:192.168.3.193:59083: serverconnect
>   -> ('my-remote-site', 443)
> my_addon_1 http_connect flow.request.host=[my-remote-site], flow.request.pretty_host=[None].
> ::ffff:192.168.3.193:59083: Establish TLS with server
> ::ffff:192.168.3.193:59083: ALPN selected by server: -
> ::ffff:192.168.3.193:59083: Establish TLS with client
> ::ffff:192.168.3.193:59083: ALPN for client: b'http/1.1'
> my_addon_2 requestheaders flow.request.host=[None], f.request.path=[/]
> ::ffff:192.168.3.193:59083: request
>   -> Request(GET /)
> my_addon_2 request flow.request.host=[my-remote-site], f.request.path=[/]

I have two addons, my_addon_1 and my_addon2, first implementing `http_connect` event and second one implementing `requestheaders` e `request`. You will see logs with addon name, event name and properties.

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
