### ISSUE TITLE
Python3.6 and installation

### ISSUE THREAD

**Issue by sommis** [mitmproxy/mitmproxy#3226]
Can you explain please how to run a new version of mitmproxy on Debian 9? When I run
"mitmproxy" I always get the error, that python 3.6 or higher must be installed, despite the fact that I've installed it. 

##### Any other comments? What have you tried so far?
1. Aliases for "python" and "python3" pointing to python3.6
2. update-alternatives switching to python3.6

3."python --version" says "Python 3.6.4"

4. Installing python 3.6 from sources and from testing repository
5. Installing mitmproxy from git
6. Installing mitmproxy via pip

##### System information
Debian-9-x86_64
Mitmproxy 4.0.3

**Comment by sommis** [comment]
If this can help someone - the kind of solution is to download the source code of mitmproxy and run "python3.6 setup.py install" - so in this way mitmproxy will be linked to python3.6. But I don't think it's the right solution, and surely this is not the easiest way of installation. So still waiting for another variant.

**Comment by Kriechi** [comment]
How did you install mitmproxy? With `apt-get`? with `pip3`?
Apt-get won't work at all.
If you use pip3, make sure to use the one from python3.6 - and not the system one! You can check with `pip3 --version`

**Comment by sommis** [comment]
I installed mitmproxy with pip3. As I've checked recently `pip3 --version` is saying that it was installed into python3.5 folder. So how should have I installed pip3 to have it being installed into python3.6 folder? I was just followig instructions from here https://docs.mitmproxy.org/stable/overview-installation/.
- sudo apt install python3-pip
- sudo pip3 install -U pip
- sudo pip3 install mitmproxy

**Comment by Kriechi** [comment]
Well yes - Debian 9 simple does not provide a Python version that is compatible with mitmproxy - thats why we put in the warning/error message.

You need to install Python3.6 including pip3 for that python version, then you can use `pip3 install mitmproxy`. I suggest you take a look at https://github.com/pyenv/pyenv

**Comment by sommis** [comment]
Can you explain please how to install Python3.6 including pip3? I installed python3.6 from here https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz and if I am not mistaken it doesn't include pip. When I run command from your instructions (`sudo apt install python3-pip` ) pip is linked to the python3.5 (because there is no python3.6 in stable version of Debian). So the question now is how to install pip to have it working with python3.6 by default? I think you should update your instruction after you have moved to new python version which is not even supported in stable versions of Debian.

**Comment by Kriechi** [comment]
Our docs clearly state that we don't support older Debian versions. There is no point in explaining something we don't support.

Did you look at the pip documentation on how to install it? https://pip.pypa.io/en/stable/installing/

**Comment by sommis** [comment]
Excuse me, Debian 9 is the latest stable version for now. The new Debian 10 which supports python3.6  is only in testing version. So you claim that you don't support Debian at all?

**Comment by Kriechi** [comment]
Not at the moment, yes. This is stated in our docs: `sudo apt install python3-pip # Debian 10 or higher, Ubuntu 17.10 or higher`

**Comment by mhils** [comment]
> So you claim that you don't support Debian at all?

You can of course use the precompiled binaries or Docker - we just don't support this specific installation method on Debian 9. There's probably a way to install mitmproxy from source nonetheless, but we don't have the resources to look into it - sorry.

**Comment by sommis** [comment]
> Did you look at the pip documentation on how to install it? https://pip.pypa.io/en/stable/installing/
Yes, now I've found how to install it manualy, but I thought there must be an easier way like it was when mitmproxy worked with python3.5. Now I see that there isn't. Anyway, I think that you have to mention in your instructions how to install pip3.6 or python3.6  on older versions of Debian and other Linux versions. I can't even call the Debian 9 "older" because it's the latest stable version. I think the same situation with Ubuntu. If you do it, I think the list of your users will be wider. For example, I had no problems of installing mitmproxy 3.0.4 and eairlier, and updating it. It was done just by few commands. But when you upgraded to python3.6 I stucked with it.

Anyway, thank you for help guys. You are doing right job.

**Comment by Kriechi** [comment]
We did not take the decision lightly to move to Python 3.6.
Here is a comprehensive list of Linux variants that provide py3.6 directly:
https://github.com/mitmproxy/mitmproxy/issues/2266

As mentioned in our docs, `pyenv` is an easy way to install new Python versions.
Here are a few commands that should be straightforward (untested):

```
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
# now do what pyenv-installer told you to do
pyenv install 3.6.5
pyenv shell 3.6.5
pip3 install mitmproxy
```

Not that complicated after all, is it?
