### ISSUE TITLE
modifying http responses through mitmproxy

### ISSUE THREAD

**Issue by hgundogdu53** [mitmproxy/mitmproxy#3227]
when I typed "I" and add "~s" as a filter, web page is intercepted and I modified the page after  typed "a"
and updated web page released. I want to do that without intercepting the page, Is there a way to do that automatically, not every time intercept the page.

**Comment by kajojify** [comment]
@hgundogdu53 Hello! 
Please, see _this_ -> https://docs.mitmproxy.org/stable/overview-features/#replacements in the docs.
**Usage.** Run mitmproxy with `--replacements PATTERN` or `-R PATTERN` argument.

**Comment by kajojify** [comment]
@hgundogdu53 Please, reopen, if you still have any questions :)
All the best!

**Comment by hgundogdu53** [comment]
Thank you for helping , it works correctly . Appreciate that again
