### ISSUE TITLE
Does uploadContent work?

### ISSUE THREAD

**Issue by pravic** [mitmproxy/mitmproxy#3228]
Mitmweb 4.0.3

##### Steps to reproduce the problem:

1. Intercept any HTTP POST packet
2. Download it
3. Try to edit it and upload it back

Nothing happens. 

##### Any other comments? What have you tried so far?

Even if I attach a debugger and set breakpoints to the `FlowContent.post` and `FlowContent.get`, only the second method works when I try to download the packet.

So, it looks like a problem in frontend JS code. And I believe it is because of the following error message when I upload something:

> POST http://127.0.0.1:8081/flows/279d81d1-deee-4795-b99e-1c97e584f718/request/content?_xsrf=2|4a3759c3|09fcb860706632cb87ac58641d3472eb|1526013962 404 (Not Found)

##### System information

> Mitmproxy: 4.0.3
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-7-6.1.7601-SP1

**Comment by pravic** [comment]
@mhils Do you know anybody, by chance, who is familiar with the frontend part of the mitmweb?

**Comment by kajojify** [comment]
@pravic Hello! Thanks for the report! I think @MatthewShao and @mhils are familiar with the frontend part of the mitmweb.

**Comment by mhils** [comment]
This should normally trigger this: 

https://github.com/mitmproxy/mitmproxy/blob/3dec4176cfd86a8adf879e76dcf9f9a599bf2996/mitmproxy/tools/web/app.py#L484

https://github.com/mitmproxy/mitmproxy/blob/3dec4176cfd86a8adf879e76dcf9f9a599bf2996/mitmproxy/tools/web/app.py#L353

Not sure why this isn't happening.

**Comment by mhils** [comment]
Ah, looks like I screwed this up here where we renamed the endpoint without changing the call: https://github.com/mitmproxy/mitmproxy/commit/bf243244ce3b0c88170484444ce340129b984dee#diff-6b3611260d81a34d1b11040f6e22362cL479

PRs welcome! 😃

**Comment by pravic** [comment]
As I've said, it looks like a problem on JS side. Because it triggers right after I click "Upload".

If that script wasn't minimized, I'd try to debug it.

**Comment by mhils** [comment]
The unminified code is here: https://github.com/mitmproxy/mitmproxy/blob/master/web/src/js/ducks/flows.js#L208. The problem is that the API endpoint has been renamed in the meantime.

**Comment by pravic** [comment]
Oops, I was answering to the previous comment.

Well, I see. And no, it looks too cryptic for me to make a PR. Can you fix this?
