### ISSUE TITLE
Response json mode with chinese character display as ??

### ISSUE THREAD

**Issue by zxw1962** [mitmproxy/mitmproxy#3231]
##### Steps to reproduce the problem:

1. any API response with chinese character;
2. check response tab with json mode;
3. like "realname": "\*哈哈", but display as "realname":"\*??" ;

##### System information
mac os v10.13.2

Mitmproxy: 4.0.3 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Darwin-17.3.0-x86_64-i386-64bit

**Comment by kajojify** [comment]
@zxw1962 Hello! Thanks for the report.
I can't reproduce(simulate) your issue. Sequence of actions:
1. Json file with:
```
{"realname": "*哈哈"}
```
2. Run pathod `pathod -a '/=200:b<"chinese.json"' -d ~/`, where `~/` is the folder with `chinese.json`.
3. Run mitmproxy -> create a request `view.create get http://127.0.0.1:9999` -> press `r`.
4. My response tab:
![image](https://user-images.githubusercontent.com/20267977/42125082-69d67f5c-7c78-11e8-9a62-795c9aea174e.png)

In json mode:
![image](https://user-images.githubusercontent.com/20267977/42125085-7d59af68-7c78-11e8-926f-e7a25ec6d442.png)

I also checked different sets of headers with chinese characters. It seems everything works ok for me.

**Comment by zxw1962** [comment]
@kajojify what's your version of mitmproxy, the latest v4.0.3?

**Comment by kajojify** [comment]
@zxw1962 I tried it with the latest master branch and with 4.0.3 binaries as well.

**Comment by mhils** [comment]
Thanks for triaging this, @kajojify! :)
