### ISSUE TITLE
Transparent mode failure: FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by pannzh** [mitmproxy/mitmproxy#3236]
##### Steps to reproduce the problem:

1.  start ap and redirect tcp 80/443 stream to 8080
2.  pull and start mitmproxy for raspberrypi model 3
```
docker run -it --rm -p 8080:8080 mitmproxy/mitmproxy:4.0.3-ARMv7 mitmdump -m transparent -p 8080 -v 
```
and it shows:
```
...
clientconnect
Transparent mode failure: FileNotFoundError(2, 'No such file or directory')
ProtocolException("Transparent mode failure: FileNotFoundError(2, 'No such file or directory')",)
clientdisconnect
...
```

##### System information

```
$ uname -a
Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv71 GNU/Linux
$ docker run --rm mitmproxy/mitmproxy:4.0.3-ARMv7 mitmproxy --version
Mitmproxy: 4.0.3
Python:       3.6.3
OpenSSL:   OpenSSL 1.0.2o 27 Mar 2018
Platform:     Linux-4.14.34-v7+-armv71-with
```

**Comment by Kriechi** [comment]
Thanks for the bug report - I don't think RPi and transparent mode is currently supported (at least nobody tried so far..)

What does `python3 -c "import sys ; print(sys.platform)"` return on your RPi?
Maybe you can even run that inside the docker image?

**Comment by pannzh** [comment]
Both in the RPi and the docker image returns `linux`. 
In case you want to known, there're two network interfaces in my RPi, wlan0 and wlan1, which wlan1 connected to the internet and wlan0 worked as an AP. Will this cause such exception?

**Comment by Kriechi** [comment]
I tested with a normal installation on my RPi3 with Raspian Stretch, and transparent mode works.
But inside the docker image, I'm getting this error traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 13, in __call__
    self.server_conn.address = platform.original_addr(self.client_conn.connection)
  File "/usr/lib/python3.6/site-packages/mitmproxy/platform/linux.py", line 27, in original_addr
    dst = csock.getsockopt(socket.SOL_IP, SO_ORIGINAL_DST, 16)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by Kriechi** [comment]
Looks like Docker containers are not allowed to use SO_ORIGINAL_DST.
I'm closing this as we cannot do anything about that at this point.

Transparent mode does work on native Raspbian images though.

**Comment by mhils** [comment]
I think `--network host` may actually work. :)

**Comment by pannzh** [comment]
@mhils Aye! it does work by using host network inside docker container, and it works well with RPi Raspbian image too! Nice job guys, thanks very much!

**Comment by LaumiH** [comment]
I am running into the same error and cannot find anything about it besides this issue.
I don't even know how to debug this with my current setup, can anyone help?

I have mitmproxy as a pod inside a kubernetes cluster, another pod can send http through it, but I get the FileNotFound error after clientconnect, and this is all I see. The pod sending the http gets a 502 back.

**Comment by mhils** [comment]
@LaumiH: I guess your Kubernetes pod doesn't provide with access to the socket, and mitmproxy thus fails when calling `getsockopt(SOL_IP, SO_ORIGINAL_DST, 16)`. Ideally you just don't use mitmproxy in transparent mode, alternatively you need to figure out how to fix this with Kubernetes. It's not a mitmproxy bug.

**Comment by LaumiH** [comment]
The error persists when I use a local Docker container though, so it is nothing k8s specific. I will continue searching, thanks for the hint @mhils !
If I find the solution I will document it here for others to find if this is ok. At least someone seems to have managed to get it working (though on an old k8s and docker version): https://github.com/danisla/kubernetes-tproxy

**Comment by krisai** [comment]
asdasd
