### ISSUE TITLE
Addon scripts don't have access to full Python 3 standard library

### ISSUE THREAD

**Issue by 0x326** [mitmproxy/mitmproxy#3238]
##### Steps to reproduce the problem:

1. Install mitmproxy for Windows. (I used [Scoop](https://scoop.sh/); `scoop install mitmproxy`)
2. `echo "from pathlib import Path" > test_addon.py`
3. `mitmdump -s test_addon.py`

Output is:
```
Loading script test_addon.py
in script test_addon.py: No module named 'pathlib'
Proxy server listening at http://*:8080
```

Expected output: No error since `pathlib` was introduced in Python 3.4

##### Any other comments? What have you tried so far?

I tested other standard library modules, such as `os` and `sys` and they work as expected.

##### System information

```
$ mitmdump --version
Mitmproxy: 4.0.3 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.16299
```

**Comment by mhils** [comment]
You are running in the problem described here: https://discourse.mitmproxy.org/t/why-is-etree-module-from-xml-missing/1120/2
