### ISSUE TITLE
http2 buggy

### ISSUE THREAD

**Issue by inetghost** [mitmproxy/mitmproxy#3241]
The http2 code seems to be buggy. Watching videos through mitmproxy on watchbox.de does not work. This can easily be reproduced, just try to watch one video on watchbox.de while proxying.

When disabling http2 support with —set http2=false the playback works, which indicates an issue in the http2 code.

Mitmproxy: 5.0.0.dev (+81, commit 3f6147e)
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h. 27 Mar 2018
Platform: Linux-4.16.14-300.fc28.x86_64-with-fedora-28-Twenty_Eight

**Comment by Kriechi** [comment]
Can you elaborate a bit more? Do you see an error message? Does the page not load?

I tested with Firefox latest, mitmproxy latest, and a random movie on watchbox.de.
It plays just fine, and I see a lot of successful requests, such as `https://vodwbusodash-a.akamaihd.net/proxy/manifest-wb-clear/at-ch-de/340606-2-26482.ism/dash/340606-2-26482-audio=128000-11113472.dash`

**Comment by sommis** [comment]
Wow, where did you find Mitmproxy 5.0.0.dev?

**Comment by kajojify** [comment]
@sommis it is just some version of the master branch after releasing mitmproxy 4.0.0 :)
