### ISSUE TITLE
The windows mitmdump connection is slow when you download the file

### ISSUE THREAD

**Issue by logan-x** [mitmproxy/mitmproxy#3242]
##### Steps to reproduce the problem:

1.Start mitmdump on Windows
2.Listen for localhost: 8888
3.Click the download button on the web page

##### Any other comments? What have you tried so far?
At run time, memory is always high and there is no reduction in closing the browser.

##### System information

Mitmproxy: 4.0.3 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-2008ServerR2-6.1.7601-SP1

**Comment by mhils** [comment]
It looks like you want to stream large response bodies? 
https://docs.mitmproxy.org/stable/overview-features/#streaming

**Comment by logan-x** [comment]
Thank you for your answer. I'll try it.
