### ISSUE TITLE
Icloud.com error

### ISSUE THREAD

**Issue by michka4** [mitmproxy/mitmproxy#3244]
##### Steps to reproduce the problem:

1. Start mitmproxy and listen on port 8080.
2. Setup proxy in macOS.
3. Navigate to yahoo.com and to icloud.com
Icloud.com is saying 'meet connection problems'
And same for Yahoo.com is loading without sucess.

Mitmproxy: 4.0.3
Python:    3.7.0
OpenSSL:   OpenSSL 1.0.2o  27 Mar 2018
Platform:  Darwin-17.6.0-x86_64-i386-64bit

**Comment by Kriechi** [comment]
Which browser are you using?
Is it possible that your browser has pinned the certificate? In that case we cannot do anything unfortunately.

icloud.com works for me with the latest Firefox on macOS.
