### ISSUE TITLE
Mitm Installation & Root Certificate for Cuckoo

### ISSUE THREAD

**Issue by saxenakanishk** [mitmproxy/mitmproxy#3246]
1. I tried to install mitmproxy by following the official site. But I am not sure whether it got installed or not. How can I verify that?
2. Please tell me what is mitm root certificate and how should I add it properly? I'll be using mitm for my malware analysis with cuckoo sandbox.
3. Is the certificate need to be added on the host or guest machine of cuckoo sandbox?

##### System information

On running "mitmproxy --version", I get a error saying -
"Error: mitmproxy requires a UTF console environment.
Set your LANG environment variable to something like en_US.UTF-8"

Cuckoo Version -
Cuckoo Sandbox 2.0.6

Operating System -
Host - Ubuntu 18.04 LTS (Bionic Beaver)
Guest (VM) - Windows 7 Ultimate SP1 - x64 bit.

I need this mitm running properly on my system with the certificate asap. Please help me. Thanks in advance.

**Comment by theNailz** [comment]
Run using `LANG=en_US.UTF-8 mitmproxy --version` or 
```
export LANG=en_US.UTF-8
mitmproxy --version
```
