### ISSUE TITLE
Errors running tests

### ISSUE THREAD

**Issue by FFY00** [mitmproxy/mitmproxy#3250]
##### Steps to reproduce the problem:

1. `python setup.py pytest `
Output:
```
==================================== ERRORS ====================================
________________________ ERROR at setup of test_mitmweb ________________________
file /build/mitmproxy-git/src/mitmproxy/test/mitmproxy/tools/test_main.py, line 9
  def test_mitmweb(event_loop, tdata):
E       fixture 'event_loop' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tdata, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/build/mitmproxy-git/src/mitmproxy/test/mitmproxy/tools/test_main.py:9
_______________________ ERROR at setup of test_mitmdump ________________________
file /build/mitmproxy-git/src/mitmproxy/test/mitmproxy/tools/test_main.py, line 18
  def test_mitmdump(event_loop, tdata):
E       fixture 'event_loop' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_xml_attribute, record_xml_property, recwarn, tdata, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/build/mitmproxy-git/src/mitmproxy/test/mitmproxy/tools/test_main.py:18
```

1. `python setup.py pytest`
Output:
```
Exception in thread WebsocketFrameReader:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/build/mitmproxy-git/src/mitmproxy/pathod/pathoc.py", line 128, in run
    r, _, _ = select.select([self.rfile], [], [], 0.05)
ValueError: file descriptor cannot be a negative integer (-1)
```

##### Any other comments? What have you tried so far?

1. I ran `pytest --fixtures`
Output:
```
---------------------------------------------------------------------------------------- fixtures defined from test.conftest ----------------------------------------------------------------------------------------
tdata
    build/mitmproxy-git/src/mitmproxy/test/conftest.py:41: no docstring available

------------------------------------------------------------------------------ fixtures defined from test.mitmproxy.addons.test_export ------------------------------------------------------------------------------
get_request
    build/mitmproxy-git/src/mitmproxy/test/mitmproxy/addons/test_export.py:15: no docstring available
post_request
    build/mitmproxy-git/src/mitmproxy/test/mitmproxy/addons/test_export.py:26: no docstring available
patch_request
    build/mitmproxy-git/src/mitmproxy/test/mitmproxy/addons/test_export.py:37: no docstring available
tcp_flow
    build/mitmproxy-git/src/mitmproxy/test/mitmproxy/addons/test_export.py:44: no docstring available

------------------------------------------------------------------------------ fixtures defined from test.mitmproxy.tools.web.test_app ------------------------------------------------------------------------------
no_tornado_logging
    build/mitmproxy-git/src/mitmproxy/test/mitmproxy/tools/web/test_app.py:19: no docstring available

----------------------------------------------------------------------------- fixtures defined from test.mitmproxy.addons.test_readfile -----------------------------------------------------------------------------
data
    build/mitmproxy-git/src/mitmproxy/test/mitmproxy/addons/test_readfile.py:15: no docstring available
corrupt_data
    build/mitmproxy-git/src/mitmproxy/test/mitmproxy/addons/test_readfile.py:33: no docstring available

------------------------------------------------------------------------------- fixtures defined from test.examples.test_xss_scanner --------------------------------------------------------------------------------
logger
    build/mitmproxy-git/src/mitmproxy/test/examples/test_xss_scanner.py:308: no docstring available
```

##### System information

Latest from git (tag.revision.commit): `4.0.0.r93.7f464b892`
(`git describe --long --tags | sed 's/^v//;s/\([^-]*-\)g/r\1/;s/-/./g;s/\.rc./rc/g'`)

I don't know why `4.0.0` shows up as the tag.

##### Note

I am maintaining [`mitmproxy-git`](https://aur.archlinux.org/packages/mitmproxy-git) in Arch Linux's AUR repo. The packaging process runs tests by default. Committing to the repo without checking if the changes break the tests will break the package, please be careful when doing this. Thanks.

**Comment by mhils** [comment]
Tests are running fine for us, see https://travis-ci.org/mitmproxy/mitmproxy. Does `tox` work for you?

**Comment by Kriechi** [comment]
@FFY00 I'm not sure why or how you are using `git describe` to get the version number, but `mitmproxy --version` currently reports `Mitmproxy: 5.0.0.dev (+93, commit 7f464b8)` as of today.
Please see `mitmproxy/version.py::get_dev_version()` on how we are reporting the version number.

**Comment by FFY00** [comment]
@Kriechi, running `mitmproxy --version` only makes sense if I am having a problem after installing mitmproxy. Please read my post, the version showed has nothing to do with the internal mitmproxy version. I am definitely using the last commit. Please run `git describe --long --tags` in your local repo, you should reproduce it. I am not sure why git is using `4.0.0` as the tag.

@mhils `tox` doesn't work for me. It goes download dependencies on its own and I can't have that happening. Also, `tox` expects a binary named `python3.7`, we don't have that in Arch. We only have `python3` and I can't create a symlink from a build environment.
The solution for this seems easy, just add a docstring where it's missing. I didn't open a Pull Request with this done because I am not involved in the development and I can't be sure what's the purpose of each function. If you don't want to write documentation for those functions, just create an empty docstring. It would also be beneficial to add `python setup.py pytest` to travis as it should be compatible with tox (except that it checks the documentation?). I am maintaining a `-git` package (installs latest version from git master) but if you want to the base package (`mitmproxy`) to be updated in the official repository, this needs to be fixed.

**Comment by Kriechi** [comment]
@FFY00 yes, `git describe --long --tags` returns v4 - which is odd.
But thats not what I was trying to explain: we have a dedicated file to generate meaningful version identifiers. 

You can simply run `python mitmproxy/version.py` and it will print the current version (without the number of ahead commits). 

If you want the full version identifier, then you should use the `get_dev_version` function in this file: `python -c "from mitmproxy import version ; print(version.get_dev_version())"`

**Comment by FFY00** [comment]
Oh, thank you. I changed to `pkgver` command to `python -c "from mitmproxy import version ; print(version.get_dev_version())" | sed -e 's| .*commit |.|g' -e 's|)||g'` and it's working as it was suposed to (returning `5.0.0.dev.7f464b8`).

**Comment by Kriechi** [comment]
Regarding the `ValueError: file descriptor cannot be a negative integer (-1)`:
I remember seeing that in the past on TravisCI from time to time, but I think we solved this a while ago... It's a flaky test / race condition. Does it happen every time you run it?

**Comment by FFY00** [comment]
No, just sometimes. When it doesn't happen, I get the first error. This is weird because I seem to be able to properly install `mitmproxy-git` in my machine. It just fails when building in a clean chroot. The most obvious source of an issue like this would be a missing dependency but due to the nature of the error that seems weird (maybe it's not, I have never used pytest in any of my projects). Can you have a look at the dependencies and make sure everything is fine? https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mitmproxy-git

**Comment by Kriechi** [comment]
I'm not really sure about your dependencies, especially about the specific versions you are providing in AUR for all the other packages... This is unfortunately a constant pain for us and for the package maintainers in Debian/Ubuntu/Kali/etc. We can only test with the dependencies we define in our `setup.py` - if distro people opt to not use it, well, then I guess it makes things more difficult.

On a first glance, I don't see `certifi` and `pytest-asyncio` in your list. I suppose the latter might be important for running the tests.
We do not list `python-h11` explicitly, but I is a dependency of one of our dependency. What is your guideline in AUR for including those in the `depends` list?

**Comment by Kriechi** [comment]
Regarding your check command: `python setup.py pytest`:

I don't think pytest-runner (https://pypi.org/project/pytest-runner/) works correctly in this case...
Why are you using it? Why not call pytest directly?

**Comment by FFY00** [comment]
Hey, sorry for the late response, I had to leave the house for a bit.

Isn't `asyncio` part of the standard library?
`certify` isn't a dependency because we replace `certify.where()` with ca certs path. See `prepare()` (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mitmproxy-git#n34).

`python-h11` should be removed. I based my `PKGBUILD` on [`mitmproxy`](https://www.archlinux.org/packages/community/any/mitmproxy/)'s where `python-h11` is declared as a dependency, that should be fixed.

I get the same issue using either `python setup.py pytest` or `pytest`. As I said before my `PKGBUILD` was based on `mitmproxy`'s, I am not sure about that. I asked for some clarification in IRC, I am waiting for a response.

**Comment by Kriechi** [comment]
asyncio is part of the stdlib, but the `pytest-asyncio` package makes the tests work (better):
https://github.com/pytest-dev/pytest-asyncio

pytest downloads stuff? I didn't expect that...
tox obviously downloads stuff - thats ok.

**Comment by FFY00** [comment]
Installing `python-pytest-asyncio` seems to solve the issue, thanks!
