### ISSUE TITLE
HTTPS traffic doesn't intercept and just tunnled 

### ISSUE THREAD

**Issue by dirkwirth** [mitmproxy/mitmproxy#3261]
Hey All,
I tried to connect my iPhone to mitmproxy and i didn't see any HTTPS traffic.
I configure the mitmproxy to be proxy server of my iPhone.

When i used transparent mode, i got the error: "Unexpected CONNECT request." 
and when i tried to open the mitmproxy in regular mode then i didn't see traffic HTTPS traffic. 

This is what i see:
10.129.0.50:53623: clientdisconnect
10.129.0.50:53624: clientconnect
10.129.0.50:53624: clientdisconnect
10.129.0.50:53626: clientconnect
10.129.0.50:53626: clientdisconnect
10.129.0.50:53629: clientconnect
10.129.0.50:53629: clientdisconnect
10.129.0.50:53630: clientconnect
10.129.0.50:53630: clientdisconnect

Thanks! :)

**Comment by dirkwirth** [comment]
Second issue: I confiure WIFI Hotspot from my computer and i connected my iphone for him.
And i ran the mitmproxy in transparent mode and i got the error: "Client Handshake failed. The client may not trust the proxy's certificate for".

Importent: I confiugred in my iPhone SSL Kill Switch 2.

In addition, if i connect the Burp Suite then its works.

I dont know what am i miss ?

**Comment by mhils** [comment]
>  'ssl_bytes_to_cipher_list', 'inappropriate fallback')

This indicates you have a TLS version mismatch somwhere. If you use the latest version of mitmproxy you should be fine.

**Comment by hopwesley** [comment]
I have the same issue
my network is:

app on android-->wifi proxy(my mac pc ip address) --> my mac pc running mitmproxy--> app server

 mitmproxy --version
Mitmproxy: 11.0.0.dev (+11, commit 9f8b2e2)
Python:    3.11.6
OpenSSL:   OpenSSL 3.1.3 19 Sep 2023
Platform:  macOS-14.0-x86_64-i386-64bit

**Comment by hopwesley** [comment]
> I have the same issue my network is:
> 
> app on android-->wifi proxy(my mac pc ip address) --> my mac pc running mitmproxy--> app server
> 
> mitmproxy --version Mitmproxy: 11.0.0.dev (+11, commit [9f8b2e2](https://github.com/mitmproxy/mitmproxy/commit/9f8b2e2a6654d6b64f6a78d1d6a9a0eb3c5b556e)) Python: 3.11.6 OpenSSL: OpenSSL 3.1.3 19 Sep 2023 Platform: macOS-14.0-x86_64-i386-64bit

the browser work fine on my andriod device and I have installed the ca file by visit mitm.it
