### ISSUE TITLE
Weird SSL_PROTOCOL_ERROR on iOS / macOS devices but not Android in transparent mode.

### ISSUE THREAD

**Issue by SgrAlpha** [mitmproxy/mitmproxy#3264]
I git a weird SSL_PROTOCOL_ERROR on iOS / macOS devices when playing with transparent mode.

The deployment topology is my clients will connect to my VPS server using shadowsocks proxy, mitmproxy is enabled on the VPS and running in transparent mode to capture the communications to one specific site.

All Android devices work perfectly without error, but on all iOS / macOS devices, will hit SSL_PROTOCOL_ERROR when trying to browse HTTPS site.

Usually that's due to wrong CA, but I confirm the root CA has been installed to all iOS devices, and enabled in General -> About -> Certificate Trust Settings.

##### Steps to reproduce the problem:
1. Build a new Ubuntu 18.04 VPS
2. Setup [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev) server listen to port 8989 for example.
3. Enable UFW and allow 8989 and 5800
4. Update `/etc/ufw/before.rules`, append following after the last commit:
`*nat`
`:PREROUTING ACCEPT [0:0]`
`:POSTROUTING ACCEPT [0:0]`
`:OUTPUT ACCEPT [0:0]`
`-A OUTPUT -p tcp -m owner --uid-owner nobody --dport 80 -j REDIRECT --to-port 8080`
`-A OUTPUT -p tcp -m owner --uid-owner nobody --dport 443 -j REDIRECT --to-port 8080`
`COMMIT`
5. Install mitmproxy and start with: `mitmdump --mode transparent --ignore-hosts <rules> --script /capture.py`
6. Let clients connect to the VPS via shadowsocks client.
7. Open Safari / Chrome and visite https://www.google.com

##### Any other comments? What have you tried so far?
Android devices work perfectly. If I remove the changes in `/etc/ufw/before.rules`, switch to regular mode and let clients connect as a HTTP proxy, both Android and iOS work.

##### System information
Mitmproxy: 4.0.3
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by SgrAlpha** [comment]
I have another VPS (Ubuntu 16.03 with openssl 1.0.2g installed) with same configuration works.

One the server with issue, `mitmproxy --version` shows openssl 1.1.0h but `openssl version` shows 1.1.0g

**Comment by mhils** [comment]
What do you see in mitmproxy's event log? This looks like a misconfiguration somewhere on your setup, not sure where/what exactly.

**Comment by SgrAlpha** [comment]
Nothing in the console log if that's the `even`t log you mean, looks like the connection never went through because SSL_PROTOCOL_ERROR. If not, where can I find this event log?

**Comment by SgrAlpha** [comment]
Speaking of config, here're what I've changed:

`block_global: false`
`confdir: /mitm/conf`
`ignore_hosts: ['google.com','googleapis.com','google-analytics.com','izatcloud.net']`
`showhost: true`
`spoof_source_address: true`
`ssl_version_client: TLSv1_2`
`ssl_version_server: TLSv1_2`

I've tried unset `ssl_version_client` and `ssl_version_server`, set them to all, still not working.

**Comment by SgrAlpha** [comment]
Works in charm if I upgrade OpenSSL to 1.1.0h on Ubuntu 18.04. So two problems still:

1. Why I have OpenSSL 1.1.0g actually installed but `mitmproxy --version` shows 1.1.0h?
2. Why it requires OpenSSL 1.1.0h but not 1.1.0g to work on Ubuntu 18.04?

**Comment by mhils** [comment]
> Why I have OpenSSL 1.1.0g actually installed but mitmproxy --version shows 1.1.0h?

Depending on how you install mitmproxy, we bundle OpenSSL.
