### ISSUE TITLE
Norton Reported Trojan in mitmweb.exe

### ISSUE THREAD

**Issue by richp10** [mitmproxy/mitmproxy#3269]
Please note it is possible another program is the problem and infected mitmweb.exe.  I thought however that the risk was sufficiently serious that it was worth reporting and having several people double check.  

##### Steps to reproduce the problem:
Installed mitmweb using the windows installer

Two weeks later, after a full scan, Norton reported Trojan.Gen.6 infection of mitmweb.exe and removed the exe. 

##### Any other comments? What have you tried so far?
I have just uninstalled 

##### System information
Uninstalled, though installation / version was about 10/06/2018 (I then went away and noticed infection on return, after full scan by Norton).

**Comment by richp10** [comment]
Actually there was another norton log entry pointing to this: https://www.symantec.com/security_response/sape/

I do wonder whether Norton is detecting some of the 'normal' functionality of mitm and interpriting this as trojan. 

If the team is convinced this is a false report, there is a way of reporting this to norton: https://submit.symantec.com/false_positive/

**Comment by mhils** [comment]
> Your submission has been sent Mon Jul 30 12:18:46 UTC 2018.

**Comment by mhils** [comment]
Mail from Symantec below, thanks again!

------

Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

    File name: mitmdump.exe
    MD5: 717BDDD4366456B9228F372C33F85D90
    SHA256: 1C579C78B5990FA723276D214D6749EFA15B3CF3928F0CDEAD734ED24C1C5674
    Note: Whitelisting is available by downloading a RAPID RELEASE indicated in the Further Information section below or via the next Live Update
    File name: mitmweb.exe
    MD5: 492540610E7E795006F1FA33B1F4F10D
    SHA256: 8FF93F438E244E310CD8EF4C6C6088A8AE18A264C344034187C6219C0AE7A474
    Note: Whitelisting is available by downloading a RAPID RELEASE indicated in the Further Information section below or via the next Live Update
