### ISSUE TITLE
Reduce certificate validity for Chrome >= 68

### ISSUE THREAD

**Issue by muffl0n** [mitmproxy/mitmproxy#3273]
##### Steps to reproduce the problem:

1. Install Chrome 68
2. Start mitmproxy, add mitmproxy-ca to your cert-store
3. Open any site via https
4. Chrome shows NET::ERR_CERT_VALIDITY_TOO_LONG error

##### Any other comments? What have you tried so far?
In #815 the validity of the certificates was reduced to three years which was enough for Chrome's "not valid longer than 39 month". It seems like Chrome 68 changed this to a shorter value though I haven't found any evidence in the code yet.
After tinkering around I found that the value "71107200" (around 27 month) for DEFAULT_EXP is the greatest value that is accepted by Chrome.

I know that I'm not using the most recent version of mitmproxy but the value for DEFAULT_EXP is the same in the current version so I assume the problem is still the same.

Suggesting to just reduce the validity to something really short, like Let's Encrypt's three month. Should not be a problem and saves us from further reduction in Chrome.

##### System information
-> % mitmproxy --version
Mitmproxy: 3.0.3 
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.17.8-1-ARCH-x86_64-with-arch

**Comment by Kriechi** [comment]
Reducing it to three months means that every mitmproxy user needs to re-install their CA cert very three months.... not very user friendly.

I'm open to reducing it a level that makes it valid in Chrome again, e.g., 24 months or similar.
@mhils @cortesi?

**Comment by muffl0n** [comment]
You are absolutely right, my suggestion was not complete: The CA cert can (and should!) have a longer validity. It's the cert for the site that is generated on the fly that should have a shorter validity.

The odd thing is: After digging through Chrome's code I did not find any change in the check for the validity: https://chromium.googlesource.com/chromium/src/+/68.0.3440.85/net/cert/cert_verify_proc.cc#894

But still I'm experiencing this problem. Can someone confirm this behaviour?

**Comment by muffl0n** [comment]
Nevermind...it's this part: https://chromium.googlesource.com/chromium/src/+/68.0.3440.85/net/cert/cert_verify_proc.cc#898
```
  // For certificates issued after 1 March 2018: 825 days.
  if (start >= time_2018_03_01 &&
      validity_duration > base::TimeDelta::FromDays(825)) {
    return true;
  }
```

**Comment by Kriechi** [comment]
Ok sounds good. Feel free to send a PR that changes the DEFAULT_EXP for issued certs!

**Comment by subworx** [comment]
https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/certificate_lifetimes.md

Maximum certificate lifetime has been reduced to 398 days, possibly crashing Android WebView (happened for me) and leading to errors in Chrome (NET::ERR_CERT_VALIDITY_TOO_LONG).

**Comment by mhils** [comment]
It's currently at 365 days in mitmproxy 7. :)
