### ISSUE TITLE
pyOpenSSL

### ISSUE THREAD

**Issue by Mradr** [mitmproxy/mitmproxy#3279]
##### Steps to reproduce the problem:

1. Install mitmproxy, gevent, gevent_openssl
2. Monkey patch for gevent_openssl and then gevent
3. Go to a HTTPS website
4. << Cannot establish TLS with www.google.com:443 (sni: www.google.com): TlsException("SSL handshake error: Error([('SSL routines', 'SSL_do_handshake', 'connection type not set')])")

##### Any other comments? What have you tried so far?

HTTP works just fine, but HTTPS sites seem to be broken when doing this method. 

##### System information

4+

**Comment by Kriechi** [comment]
As already mentioned in https://github.com/gevent/gevent/issues/1265, mitmproxy does lots of I/O and threading with C libraries, using greenlets is not going to work. 

We have made a recent change to switch our core-loop to asyncio, and we are also making progress on a sans-io implementation.
