### ISSUE TITLE
[Feature Request] Manage Multiple Servers/Proxies from One UI

### ISSUE THREAD

**Issue by zero77** [mitmproxy/mitmproxy#3284]
Can you please add support for managing more than one proxy from one web-ui, by configuring each proxy to connect back to one specified proxy/server for management.
Thanks

**Comment by Kriechi** [comment]
Would you mind describing your use case for multiple mitmproxy instances with a single web-ui?

**Comment by mhils** [comment]
This would require major changes and is definitely not on the roadmap. Sorry!
