### ISSUE TITLE
Docs on ReadTheDocs outdated

### ISSUE THREAD

**Issue by ulope** [mitmproxy/mitmproxy#3285]
##### Steps to reproduce the problem:

1. Google for `mitmproxy docs`
2. Mitmproxy on ReadTheDocs shows up relatively high in the results list
3. Notice that the newest version on there is 2.x

Solution: Either update or delete them on RTD.

**Comment by Kriechi** [comment]
The first results page of my Google search yields:
#1 through #8 with the correct & new https://docs.mitmproxy.org/stable/ site. 
#9 #10 are indeed RTD links.
#11 is the docs folder in our Github repo.

@mhils: I know we already tweaked RTD to some extent - anything else we can do?

**Comment by mhils** [comment]
Yes, this sucks. We can probably update rtd somehow, but no idea what's the best approach for this. I'd be fine with turning off rtd entirely, although we link to the pathod docs there from the main page. I mean we can remove that reference too, depending on how y'all feel about it.

**Comment by einverne** [comment]
I have noticed that some parts of the docs like [api](https://mitmproxy.readthedocs.io/en/v2.0.2/scripting/api.html) which is really useful for starters, but still missing in the stable https://docs.mitmproxy.org/stable/ versions.
