### ISSUE TITLE
Windows build/download link not working

### ISSUE THREAD

**Issue by gregorylyons** [mitmproxy/mitmproxy#3291]
##### Steps to reproduce the problem:

1. Click on download link on homepage
e.g. https://snapshots.mitmproxy.org/4.0.4/mitmproxy-4.0.4-windows-installer.exe

##### Any other comments? What have you tried so far?
File appears to be missing; 4.0.3 exists.

**Comment by elijahbal** [comment]
I don't know how this link is generated, but the windows build is clearly missing :+1: 

Check that link:

https://snapshots.mitmproxy.org/4.0.4/

So yes, indeed, windows build 4.0.4 is missing.
