### ISSUE TITLE
[Feature Request] Add an option to allow hosts

### ISSUE THREAD

**Issue by KevCui** [mitmproxy/mitmproxy#3295]
There is an option `ignore_hosts` to ignore hosts. Do you think it makes sense to add an option, like whitelist hosts, to allow only some hosts go to proxy? Let's call it `allow_hosts`?

Asking for a friend 😃

**Comment by madt1m** [comment]
Do you think this is something which couldn't be obtained using `!` operator in `ignore_hosts` filter expression?
https://docs.mitmproxy.org/stable/concepts-filters/

**Comment by KevCui** [comment]
Thanks @madt1m for the guide. With `!` operator, the "allow hosts" works well in ignore_hosts. However, it's preferable to have an option allow_hosts, which makes configuration more straightforward. Anyhow, it's my friend and my personal opinion, please close the ticket if you think it's not worth the effort.

**Comment by mhils** [comment]
I'm indifferent on this. What do others think?

**Comment by kajojify** [comment]
Just look at `--help` output. 
There are many examples of options, which have their twins with the opposite effect. So, if there is a usecase, which shows, that we need `allow_hosts`, why not to implement it? :)

**Comment by rjt-gupta** [comment]
I would like to work on this.
