### ISSUE TITLE
Using mitmproxy inside python script

### ISSUE THREAD

**Issue by j3ssie** [mitmproxy/mitmproxy#3298]
I'm new in mitmproxy so I have a question why I can't figure out how to put mitmproxy inside my python script(my purpose is just to make some modify with the request and analyze response)

I'm found this but this doesn't work anymore
https://gist.github.com/dannvix/5285924#example-of-proxypy
and
https://2qwesgdhjuiytyrjhtgdbf.readthedocs.io/en/latest/scripting/mitmproxy.html#examples-stickycookies

So I wonder why are you guys refer using 

```
mitmproxy -s sample.py
```

instead of do some configuration inside python script like 

```
config = proxy.ProxyConfig(port=8080)
server = ProxyServer(config)
```
then just run sample.py script.

##### System information
OS: Mac OS
Lastest version of mitmproxy via pip3 install mitmproxy

**Comment by yan-ace62** [comment]
You can write your scripts as shown in the following example.

`from mitmproxy import ctx
class Counter:
    def request(self, flow):
        “”“You only need to process the input parameter flow"""
       pass
    def response(self, flow):
          """ like above"""
addons = [
    Counter()
]`
flow has attribute flow.requset and flow.response, if you want just to make some modify with the request and analyze response inside python3 script,  You should manipulate the input flow object.

**Comment by mhils** [comment]
We discourage subclassing any of the master classes - it's better to write addons, which can then be reused more easily.
