### ISSUE TITLE
All release packages missing

### ISSUE THREAD

**Issue by Solarer** [mitmproxy/mitmproxy#3299]
##### Steps to reproduce the problem:

1. Visit https://mitmproxy.org/downloads/ or https://snapshots.mitmproxy.org/4.0.4/ or any related page
All files appear to be missing

**Comment by Solarer** [comment]
IE 11.125.16299.0
![mitmproxy](https://user-images.githubusercontent.com/2805109/44391774-43cf5d80-a520-11e8-8b27-b29b8e8425d4.PNG)

Using Edge, I can see all files and download them.
![mitmproxy_edge](https://user-images.githubusercontent.com/2805109/44391970-a0327d00-a520-11e8-912a-6fbd70b9d29a.PNG)

Have not tested other Browsers yet but this might be limited to my Internet Explorer.

**Comment by mhils** [comment]
Thanks. Is there anything in the browser event log?

Jan Adam <notifications@github.com> schrieb am Di., 21. Aug. 2018, 01:01:

**Comment by elijahbal** [comment]
Can't say I have experienced this.

https://snapshots.mitmproxy.org/4.0.4/ works perfectly fine ATM with chromium.

Only the windows build is missing (see #3291).

**Comment by Solarer** [comment]
Here is the Browsers console Output. Sorry, it is in german.

```Trennzeichen für Navigationsereignisse
HTML1300: Navigation wurde ausgeführt.
downloads
DOM7011: Der Code auf dieser Seite hat die Zwischenspeicherung für das Vor- und Zurücknavigieren deaktiviert. Weitere Informationen dazu finden Sie unter: http://go.microsoft.com/fwlink/?LinkID=291337
downloads
HTML1508: Endmarkierung ohne Entsprechung.
downloads (243,1)
Possible Unhandled Promise Rejection: TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "forEach" nicht
   "Possible Unhandled Promise Rejection:"
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "TypeError"
      },
      description: "Das Objekt unterstützt die Eigenschaft oder Methode "forEach" nicht",
      message: "Das Objekt unterstützt die Eigenschaft oder Methode "forEach" nicht",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Das Objekt unterstützt die Eigenschaft oder Methode "forEach" nicht
   at Anonymous function (https://mitmproxy.org/snapshots.js:27:13)
   at Anonymous function (https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js:1:766)"
   }
```

**Comment by mhils** [comment]
Thanks. We don't really want to support IE11 anymore, but I fixed the site so that you can at least download mitmproxy now.

(The fact that the Windows 4.0.4 binaries are still missing is unrelated and tracked in #3291)
