### ISSUE TITLE
Byte size limit for mitmproxy

### ISSUE THREAD

**Issue by hgbing** [mitmproxy/mitmproxy#3302]
I got an error with "fork:cannot allocate memory" , mitmproxy was working on regular mode for 24 hours. is there the method as i supposed:
1. set  Byte size limit when mitmproxy startups
2. clean memory period by commands or scripts

**Comment by madt1m** [comment]
It should be trivial to develop the addon you're talking about. Check the docs to learn more about addon development. You can both limit the size of the view for each request received, or set up (using `asyncio`) a task which periodically writes to disk and clears memory. 

The command you're looking for is `view.clear`

Actually, we're trying to solve this issue by moving mitmproxy storage layer to disk. It will hopefully be released soon, but let us know if you write this addon and want to add it to repo folder :)

**Comment by mhils** [comment]
Also refs #3191.
