### ISSUE TITLE
(ipv6) 400 Bad Request in reverse mode

### ISSUE THREAD

**Issue by luckychelsea** [mitmproxy/mitmproxy#3303]
##### Steps to reproduce the problem:
**Mitmproxy: 4.0.4
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-2.6.32-358.el6.x86_64-x86_64-with-centos-6.4-Final**

**mitmdump -m reverse:https://[2400:a480:aaaa:888::102]:444 -p 16008 --ssl-insecure**

**This address is accessible  https://[2400:a480:aaaa:888::102]:444

however...**

172.168.0.121:16457: GET https://[2400:a480:aaaa:888::102]:444/
2400:a480:aaaa:888::102
                  **<< 400 Bad Request 347b**
172.168.0.121:16457: clientdisconnect

**After the domain name is configured in the /etc/hosts file, it works normally**
**172.168.0.121:16609: GET https://[dbhost]:444/
                     << 200 OK 44b**

Can't access it using real IP?

**Comment by mhils** [comment]
Can you please increase log verbosity and post an updated log here?

**Comment by kajojify** [comment]
If you still have any problems with this, please, feel free to reopen (and provide more information about your case, please).
