### ISSUE TITLE
Measure request and response times from inline script?

### ISSUE THREAD

**Issue by j3ssie** [mitmproxy/mitmproxy#3304]
How do I measure request and response from inline script?

I used formal below to measure time from start to send request from get response from server,
but after convert that into human readdle I realize that not acctually time of issue request(I used Burp Proxy to compare).

```
flow.request.timestamp_start - flow.response.timestamp_end
```

##### System information

Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Darwin-17.7.0-x86_64-i386-64bit

**Comment by mhils** [comment]
flow.request.timestamp_start = mitmproxy starts to receive traffic.
flow.request.timestamp_end = mitmproxy has received the full request, will usually start sending immediately now.
flow.response.timestamp_end = We have completely read the response.

Does that clarify things?

**Comment by j3ssie** [comment]
Very clear thank you so much.
