### ISSUE TITLE
How to get the  detail timing by python script?

### ISSUE THREAD

**Issue by tttaotie** [mitmproxy/mitmproxy#3308]
##### Steps to reproduce the problem:

I didn't find the api to get  the  detail timing  .  for example : client conn established、 server conn initiated、server conn tcp handshake and so on

**Comment by madt1m** [comment]
If you wish to inspect the timestamps, you can find the relative attributes in client and server connections here:

https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/connections.py

So, given a flow `f` intercepted e.g. by a script, you can access those fields in `f.client_conn` and `f.server_conn` objects. Does this help?

**Comment by tttaotie** [comment]
@madt1m thank you  very much~
