### ISSUE TITLE
Fresh new mitmproxy-ca-cert on every install

### ISSUE THREAD

**Issue by john-bonachon** [mitmproxy/mitmproxy#3309]
mitmproxy's CA certificate (taken from ~/.mitmproxy or mitm.it) installed on a machine means that any mitmproxy user could take advantage of it.

shouldn't it be generated at mitmproxy installation/first-use? as explained on https://docs.mitmproxy.org/stable/concepts-certificates/#using-a-custom-certificate-authority

**Comment by mhils** [comment]
Hi! Not sure if I understand your request, the behavior you are describing is precisely what happens? :-)

**Comment by john-bonachon** [comment]
actually yes, but I mean if that could be a vulnerability.

say you're testing mitmproxy on pc A, any partner could setup a man in the middle scenario and use mitmproxy to read pc A's packets (because it already trusts in mitmproxy CA)

that should be pc A's user responsability, but could we prevent that from happening by generating a new mitmproxy CA on any fresh mitmproxy install?

**Comment by mhils** [comment]
> but could we prevent that from happening by generating a new mitmproxy CA on any fresh mitmproxy install?

We do generate a new CA when ~/.mitmproxy is not present, see https://docs.mitmproxy.org/stable/concepts-certificates/#the-mitmproxy-certificate-authority.

**Comment by john-bonachon** [comment]
Got it. Is mitm.it CA generated on the fly too?

**Comment by mhils** [comment]
mitm.it just serves the certificate from ~/.mitmproxy. That's also noted at the bottom of the page.
