### ISSUE TITLE
Full Transparent mode C script error

### ISSUE THREAD

**Issue by IcoBoyanov** [mitmproxy/mitmproxy#3310]
I have problems enabling full transparent mode on ubuntu 16.04 machine.
https://docs.mitmproxy.org/stable/howto-transparent/#full-transparent-mode-on-linux
##### Steps to reproduce the problem:
1.  Cloning mitmproxy repo
2.  Configuring linux as shown in mitmproxy docs
3. running:  gcc examples/complex/full_transparency_shim.c -o mitmproxy_shim -lcap

raises the following error 
"examples/complex/full_transparency_shim.c:6:28: fatal error: sys/capability.h: No such file or directory
compilation terminated."

##### Any other comments? What have you tried so far?
Where can i find this lib ? Are there any alternatives to run full transparent mode

##### System information

Mitmproxy: 4.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.4.0-127-generic-x86_64-with-debian-stretch-sid

**Comment by madt1m** [comment]
A quick Google search led me to:

`sudo apt-get install libcap-dev`

This should fix.
