### ISSUE TITLE
mitmdump crashes

### ISSUE THREAD

**Issue by miaonagemide** [mitmproxy/mitmproxy#3311]
##### Steps to reproduce the problem:

1.run mitmdump with my python script, script is to intercept an android app video packets
2.it automatically downloading, sometimes, maybe in 10 mins, maybe in 20mins, there is no http flow
3.then when I Ctrl+C, there is no response, I have to continue press Ctrl+C to end the program. Then I got many "mitmproxy has crashed!" message in the command line

##### Any other comments? What have you tried so far?

here is the message after last avaliable http:

192.168.168.180:47697: Error in HTTP connection: HttpException('Unexpected EOF')
192.168.168.180:47697: clientdisconnect
192.168.168.180:48371: clientconnect
192.168.168.180:56111: clientconnect
::ffff:192.168.168.180:38581: Ping Received from client
  -> ping
::ffff:192.168.168.180:38581: Pong Received from server
  ->
192.168.168.180:36381: Error in HTTP connection: HttpException('Unexpected EOF')
192.168.168.180:36381: clientdisconnect
192.168.168.180:55677: Error in HTTP connection: HttpException('Unexpected EOF')
192.168.168.180:55677: clientdisconnect
192.168.168.180:45515: Error in HTTP connection: HttpException('Unexpected EOF')
192.168.168.180:45515: clientdisconnect
192.168.168.180:38559: clientconnect
192.168.168.180:56262: Error in HTTP connection: HttpException('Unexpected EOF')
192.168.168.180:56262: clientdisconnect
192.168.168.180:48222: Error in HTTP connection: HttpException('Unexpected EOF')
192.168.168.180:48222: clientdisconnect
192.168.168.180:36641: Error in HTTP connection: HttpException('Unexpected EOF')

Here is the repeating message that was stucked then appeared after I force quit the program (Ctrl+C)

Traceback (most recent call last):
  File "e:\python37\lib\site-packages\mitmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "e:\python37\lib\site-packages\mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
    layer()
TypeError: 'NoneType' object is not callable
mitmproxy has crashed!
192.168.168.180:49942: Error in HTTP connection: HttpException('Unexpected EOF')Traceback (most recent call last):
  File "e:\python37\lib\site-packages\mitmproxy\proxy\server.py", line 121, in handle
    root_layer()
  File "e:\python37\lib\site-packages\mitmproxy\proxy\modes\http_proxy.py", line 9, in __call__
    layer()
TypeError: 'NoneType' object is not callable

##### System information

Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-10-10.0.16299-SP0

**Comment by NikolayStarodubtsev** [comment]
I have the issue which looks closely to this one. 
I try to use mitmproxy with upstream mode, and a python script for ssl passthrough. Sometimes it works just fine, but it  can halt and and stop to react even to Ctrl+C and kill command. To stop mitmproxy I need to use kill -9

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
