### ISSUE TITLE
mitmweb status code colors

### ISSUE THREAD

**Issue by reden87** [mitmproxy/mitmproxy#3312]
It would be great to have colored status codes in mitmweb too.

mitmproxy example:

![screen shot 2018-09-04 at 11 26 50](https://user-images.githubusercontent.com/869119/45022861-8d966880-b035-11e8-93d1-cb648cdb84c9.png)

mitmweb example:

![screen shot 2018-09-04 at 11 27 07](https://user-images.githubusercontent.com/869119/45022879-94bd7680-b035-11e8-8eef-e16300ee1b2f.png)

**Comment by kajojify** [comment]
Closed thanks to https://github.com/mitmproxy/mitmproxy/pull/3351
:tada:
