### ISSUE TITLE
[Feature Request] Save filtered flows only in mitmweb

### ISSUE THREAD

**Issue by coreywei** [mitmproxy/mitmproxy#3313]
In mitmweb it is able to filter out flows with some search criteria, but it still saves all the flows when clicking on "save" button.  So I have to delete unwanted flows one by one and then save.

It would be great if we can multi-select flows to delete/save.

**Comment by lups2000** [comment]
@mhils it looks like "Save filtered" as already been implemented! Do we still want to have multi-selection of flows?

**Comment by mhils** [comment]
multi-selection would still be nice to have eventually, but I agree that this here is sufficiently addressed by means of "Save filtered" :)
