### ISSUE TITLE
Request host in requestheaders event

### ISSUE THREAD

**Issue by Gigiarum** [mitmproxy/mitmproxy#3315]
Are properties "host" and "pretty_host" always set in flow.request in requestheaders event?
If I try request event I don't have this problem.

##### System information
Mitmproxy: 4.0.1
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-3.16.0-6-amd64-x86_64-with-debian-8.9

**Comment by mhils** [comment]
That may depend on a few things, the relevant code is https://github.com/mitmproxy/mitmproxy/blob/b7aa325bfe9e392f5f5089a0b6be648e7ccaf6d7/mitmproxy/proxy/protocol/http.py#L269-L320.

**Comment by kajojify** [comment]
Is the question still relevant?

**Comment by Gigiarum** [comment]
I read the code but I cannot find why sometimes I found properties set and sometimes no.
