### ISSUE TITLE
Using https proxy as upstream proxy occur Server disconnected

### ISSUE THREAD

**Issue by jkryanchou** [mitmproxy/mitmproxy#3317]
##### Steps to reproduce the problem:

1. Using https proxy as upstream proxy as following commands: `mitmdump --mode upstream:https://foo.com -p 8081 -s ./proxy/flow_dumper.py`

The mode represents as below:

```
Client <--- http ---> MITMproxy<----HTTPS(Proxy)---> Internet
```

2. It shows `Server disconnected` as below

```
127.0.0.1:51409: HTTP protocol error in client request: Server disconnected
127.0.0.1:51409: clientdisconnect
 << Server disconnected
127.0.0.1:51408: HTTP protocol error in client request: Server disconnected
127.0.0.1:51408: clientdisconnect
127.0.0.1:51412: clientconnect
 << Server disconnected
127.0.0.1:51412: HTTP protocol error in client request: Server disconnected
127.0.0.1:51412: clientdisconnect
127.0.0.1:51419: clientconnect
 << Server disconnected
127.0.0.1:51419: HTTP protocol error in client request: Server disconnected
127.0.0.1:51419: clientdisconnect
127.0.0.1:51429: clientconnect
 << Server disconnected
... ...
```

##### Any other comments? What have you tried so far?

I have no idea what options set to mitmproxy. Try several options while it doesn't work.

##### System information

Mitmproxy: 4.0.4
Python:    3.6.1
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Darwin-17.5.0-x86_64-i386-64bit

**Comment by mhils** [comment]
You probably just want to use "http://". mitmproxy will of course still send HTTPS requests over that proxy.

As per #1775, we currently don't support TLS-over-TLS, which would be required for what the Chromium guys call a ["Secure Web Proxy"](https://www.chromium.org/developers/design-documents/secure-web-proxy). Most regular HTTP proxies don't work that way and should work just fine.

**Comment by jkryanchou** [comment]
@mhils Oh sorry I had make a mistake on mode i draw above.  I update the graph

```
Client <--- http ---> MITMproxy<----HTTPS(Proxy)---> Internet
```

While I wan to visit the https site like `https://www.google.com` through http://127.0.0.1:8081 (mitmproxy). It represent as the forward node to second https proxy.

**Comment by mhils** [comment]
Sorry, I don't understand your point or what you are trying to achieve.

**Comment by jkryanchou** [comment]
@mhils I want to use the mitmproxy in upstream proxy mode to forward the traffic to https proxy.

**Comment by mhils** [comment]
There's no such thing like an "HTTPS proxy". You are probably referring to an HTTP proxy that support TLS after CONNECT (in which case you just use http:// in the upstream specification), or you are referring to a "Secure Web Proxy" - a relative new (and still rare) type of proxy that requires TLS over TLS, which we unfortunately currently don't support.

**Comment by jkryanchou** [comment]
@mhils Yeah, I mean that it was probably the proxy which could support TLS after Connect. Could mitmproxy support this proxy in upstream mode?

**Comment by mhils** [comment]
@aegeavaz: We have major changes for this on the main branch, you may want to try out a dev snapshot.

**Comment by aegeavaz** [comment]
Hi @mhils

I did it but the upstream auth is not yet implemented. I've already vote for it on the feature priority thread.

Thank you very much for you quick response and your amazing project.

**Comment by 0xSparrow** [comment]
Any updates about this ? I'm searching for this problem too, "https://" in  --mode upstream give me  Upstream proxy myproxy:9702 refused HTTP CONNECT.

Any solution for this ?
Thanks
