### ISSUE TITLE
Inquiry for replay example

### ISSUE THREAD

**Issue by Festum** [mitmproxy/mitmproxy#3318]
Hello,

It actually not an issue. 
I'm new to mitmproxy wondering if there is an example for capture client data and replay it. 
We want to capture real server response while crawlers hitting websites then put these captured responses setup a mock server on the staging environment for e2e test and prevent external traffic cost.

**Comment by mhils** [comment]
See https://docs.mitmproxy.org/stable/overview-features/#server-side-replay. Also, please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!
