### ISSUE TITLE
How to debug an electron based app that does not respond to proxy?

### ISSUE THREAD

**Issue by indickanajack** [mitmproxy/mitmproxy#3323]
I have installed an app that is based on electron. The GUI is in javascript, html, css and it does not support setting proxy for it.  

How can I intercept and record traffic for this particular application using mitm proxy? Are there any other tools that does what I want?  

I have another application installed ( https://soroush-app.ir/ ) which I guess is based on electron. It does support proxy (HTTP and SOCKS5) but when I use HTTP it dumps nothing on the web interface. Socks5 says that authentication is not supported and I dont know why does it says this.

I am using windows server 2008 R2 for testing all of this (the core is Windows 7) installing both mitmproxy and soroush on the same machine.

Thanks.

**Comment by mhils** [comment]
Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!
