### ISSUE TITLE
How to get real ip address

### ISSUE THREAD

**Issue by Zoe1808** [mitmproxy/mitmproxy#3326]
Device connects to a WiFi which provided by a Router, mitmproxy only recognizes the Router's ip, not the device real ip. 
The Question is how to get the real device ip?

Device ip: 192.16.2.49
Router ip: 10.101.52.79

![image](https://user-images.githubusercontent.com/10767521/45349425-d32dd500-b5e3-11e8-8e5e-2c8c65daeb9d.png)

**Comment by mhils** [comment]
I'm not sure if I understand the question, but there surely is a problem with how we display the client IP address in mitmweb. Which mitmproxy version is this?

**Comment by Zoe1808** [comment]
@mhils It's the latest version, 5.0.0. It's not only the problem in mitmweb,  but also in mitmproxy, the flow.client_conn.address.address stores the router ip.
