### ISSUE TITLE
ChromeDriver+Mitmproxy ,"Client Handshake failed"

### ISSUE THREAD

**Issue by rainsun007** [mitmproxy/mitmproxy#3333]
google-chrome 69
ChromeDriver 2.42.591071
    chromeOptions = webdriver.ChromeOptions()
    chromeOptions.add_argument('--no-sandbox')
    chromeOptions.add_argument('--headless')
    chromeOptions.add_argument('--disable-gpu')
    chromeOptions.add_argument('--disable-dev-shm-usage')
    chromeOptions.add_argument('--ignore-certificate-errors')
    chromeOptions.add_argument('--window-size=1920x1080')
    chromeOptions.add_argument("--proxy-server=127.0.0.1:60800")

Mitmproxy: 4.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core

[service]
mitmdump --mode upstream:http://10.0.0.228:28084 -s mitm_pro.py -p 60800 --ssl-insecure --set upstream_cert=false

[problem]
"Client Handshake failed. The client may not trust the proxy's certificate for www.baidu.com."

@mhils   How can I solve this problem.   thx

**Comment by mhils** [comment]
AS the error message states, the client probably does not trust the mitmproxy certificate. Not sure why ChromeDriver doesn't accept it, but this doesn't look like a mitmproxy bug.

**Comment by rainsun007** [comment]
chrome vfersion questions?
