### ISSUE TITLE
mitmproxy charles https

### ISSUE THREAD

**Issue by rulaimiao** [mitmproxy/mitmproxy#3337]
I get mitmproxy-ca.pem , can get https requests , 
but not get some https requests
I use charles can get all https requests ,
why

**Comment by kajojify** [comment]
@rulaimiao Hello! 
So, you installed mitmproxy certificate, mitmproxy itself and noticed that Charles showed you all https requests, but in the meantime mitmproxy skipped some of them. Did I understand your question? 

If yes, could you please give us more information about your case? What kind of request do you make? What is the version of your mitmproxy (`mitmproxy --version`)?

**Comment by rulaimiao** [comment]
> @rulaimiao Hello!
> So, you installed mitmproxy certificate, mitmproxy itself and noticed that Charles showed you all https requests, but in the meantime mitmproxy skipped some of them. Did I understand your question?
> 
> If yes, could you please give us more information about your case? What kind of request do you make? What is the version of your mitmproxy (`mitmproxy --version`)?

@kajojify  Sorry, I didn't see it before, your understanding is no problem. Now I suspect that the mitmproxy certificate may not be fully trusted on the android phone, so some https requests are not caught, the mitmproxy version is the latest, I tried the previous Version still can't be caught
