### ISSUE TITLE
call request addon in mitm with selenium

### ISSUE THREAD

**Issue by ravi45722** [mitmproxy/mitmproxy#3338]
##### Steps to reproduce the problem:

1. Copy the counter example in the addons sections
2. Add an option in selenium "--proxy-server=localhost:8080"
3. Then hit an url using driver.get("https://bitbucket.org/") 

Its showing a log at the end saying **We've seen 25 flows** including css, png, js and everything. 
I need to call the **request** or any function only once (when I call the proxy for an url). 
I don't want this on internal request (png, js, css, html, external domains)

##### Any other comments? What have you tried so far?
I tried all the add-on functions available in the docs. Nothing worked for my use case

I am expecting the output from my addon as 1 flow when I hit one url. Anyway for this??

**Comment by Prinzhorn** [comment]
If this is still relevant, feel free to post this in discussions https://github.com/mitmproxy/mitmproxy/discussions or on StackOverflow
