### ISSUE TITLE
Errors on standard output instead of standard error

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#3339]
I receive errors from dumper on standard output, they would be better to appear on StandardError

Ex:
"Error in WebSocket connection to 192.x.x.x:443: WebSocket connection closed unexpectedly by server: TcpDisconnect(None,)"

Think it comes from here:
https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/mitmproxy/addons/dumper.py#L245

There's the same output for tcp_error apparently:
https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/mitmproxy/addons/dumper.py#L270

##### System information

Mitmproxy: 4.0.3 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Darwin-17.7.0-x86_64-i386-64bit

**Comment by Kriechi** [comment]
We are happy to accept a PR for this! 👍

**Comment by tomlabaude** [comment]
Aie, I'd love to, really... But I'm totally beginner with Python & mitmproxy dev environment and also, so many bugs to fix in my own app!

**Comment by Prinzhorn** [comment]
Looks like this affects `--quiet` as well. I'm spawning `mitmdump --quiet` from another process and communicate via stdin/stdout with the process. Even though `--quiet` is specified, I get

> Error in WebSocket connection to .....:443: WebSocket connection closed unexpectedly by client: TcpDisconnect(None)

on stdout

**Comment by Prinzhorn** [comment]
I upgraded from 4.0.4 to 5.0.1, nice work 🎉

I think this issue can be closed https://github.com/mitmproxy/mitmproxy/blob/184384af57e81bce09469e2fefe6dbb134eda6ce/CHANGELOG#L45
