### ISSUE TITLE
Feature request - copy response body to clipboard

### ISSUE THREAD

**Issue by rwozniak** [mitmproxy/mitmproxy#334]
As in the title - it would be nice to be able to copy response body to clipboard with some shortcut.

**Comment by mhils** [comment]
Thanks to @gato, the next mitmproxy version will ship with this feature. :-)

**Comment by danielphillips** [comment]
How do you use this feature?

**Comment by dufferzafar** [comment]
@danielphillips Depends on which mitmproxy version you're using.

In the code from latest master, you just press `C` on a flow and choose what you want to copy - body, headers etc.

**Comment by shubham-mandal** [comment]
How do we copy the flow in the latest version of mitmproxy 3.0.3?

**Comment by shubham-mandal** [comment]
How do we copy the flow in the latest version of mitmproxy 3.0.3?

**Comment by kajojify** [comment]
@shubham-mandal Hi! 
`ctrl + L` (L in lowercase)
You will see `: cut.clip [flow] [cut]` in the statusbar, where `[flow]` is some view flow selector from https://docs.mitmproxy.org/stable/concepts-filters/ and [cut] is a part of a flow.

**Comment by shubham-mandal** [comment]
@kajojify  Many thanks, I had tried the command but couldn't figure out the arguments. After a mild research, I finally understood them. Thanks again.

**Comment by laxiK** [comment]
How to copy the request url and request headers in the latest version of mitmproxy 3.0.3 as I've tried these steps: ctrl + L (L in lowercase)
then : cut.clip @focus request.url
But it's not working.

**Comment by alejoes** [comment]
@shubham-mandal would you mind sharing the arguments? I guess you mean [flow][cut], I have not been able to figure it out. Thanks

**Comment by alejoes** [comment]
Hi, I just recently discovered mitmproxy, I'm not much of a gig and I'm having trouble figuring out what to do after clicking ctrl + L (L in lowercase),  when cut.clip [flow] [cut] shows in the statusbar
I would appreciate any help.
Thank you
