### ISSUE TITLE
mitmproxy does not receive chunked mpeg/audio stream

### ISSUE THREAD

**Issue by yherve** [mitmproxy/mitmproxy#3341]
Hi

I started to play yesterday with mitmproxy, which looks really awesome. Unfortunately I have a problem while streaming audio over http (https does not work either).  

##### Steps to reproduce the problem:

    mitmproxy -v  --set stream_large_bodies=1k

    http_proxy=http://localhost:8080 curl -i http://chai5she.cdn.dvmr.fr/fip-midfi.mp3?ID=radiofrance

no response received by curl. The following output is reported by mitmproxy.

    >> GET http://chai5she.cdn.dvmr.fr/fip-midfi.mp3?ID=radiofrance
       ← 200 audio/mpeg [content missing] 0ms

tested with dev version (commitid a8b809dc) and also with version installed by pip3

##### System information
ubuntu 18.04 x64

**Comment by mhils** [comment]
Thanks, this indeed looks like a bug. refs #1775.

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
