### ISSUE TITLE
when I use mitmproxy all http websites don't work!!!

### ISSUE THREAD

**Issue by mohamed159753** [mitmproxy/mitmproxy#3345]
##### Steps to reproduce the problem:

1.I set proxy to : 127.0.0.1:8080
2.I load any http page
3.it tell me "problem loading page"

##### Any other comments? What have you tried so far?

https websites work fine

##### System information

2.02

PLease HELP!!

**Comment by armudgal** [comment]
Hi @mohamed159753, can you please upgrade `mitmproxy` and see if the problem still persists. Thanks
