### ISSUE TITLE
Not able to dump WebSocket messages

### ISSUE THREAD

**Issue by raamojirao** [mitmproxy/mitmproxy#3346]
##### Steps to reproduce the problem:

mitmdump -w outfile does not dump any traffic to the output file

I have attached the screenshot. How do I dump the websocket message displayed in the screenshot.

![screen shot 2018-10-09 at 11 57 23 am](https://user-images.githubusercontent.com/21014170/46682161-cbe5f100-cbba-11e8-9ba9-5ff83e639642.png)

**Comment by Kriechi** [comment]
Please provide the system information we asked for in the issue template.

You are not using `-w outfile` in your screenshot.
I tested this with the latest git-master version, and the outfile contains the websocket messages - but keep in mind that the outfile is a mitmproxy-specific serialization format!

You can access each message via this event https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/dumper.py#L253-L256 by using a script or addon (use `mitmdump -s my_script.py` and see our docs)

**Comment by Kriechi** [comment]
You can also find a simple websocket example: https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/websocket_messages.py
