### ISSUE TITLE
Invalid HTTP request form (expected: authority or absolute, got: relative) from Burp

### ISSUE THREAD

**Issue by j3ssie** [mitmproxy/mitmproxy#3349]
##### Steps to reproduce the problem:

1. I used mitmproxy as forwarding proxy from Burp but I keep getting these error.
![Without mitmproxy](https://user-images.githubusercontent.com/23289085/46723629-797fff80-cca2-11e8-9d21-a76d0cb15e9e.png)
![With mitmproxy](https://user-images.githubusercontent.com/23289085/46723683-93b9dd80-cca2-11e8-9e4b-0702d6a5292a.png)

2. And this is error I get from console
```
mitmdump -p 8779 -s proxy.py

Proxy server listening at http://*:8779
127.0.0.1:56560: clientconnect
 << Invalid HTTP request form (expected: authority or absolute, got: relative)
127.0.0.1:56560: HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)
```
3. I only get this error when use mitmproxy as upstream proxy on burp in **Repeater tab from Burp** 

##### System information
Mitmproxy: 3.0.2
Python:    3.7.0
OpenSSL:   OpenSSL 1.0.2p  14 Aug 2018
Platform:  Darwin-18.0.0-x86_64-i386-64bit

**Comment by mhils** [comment]
I'm not sure how Burp's forwarding proxy is supposed to work, but this looks like a configuration issue. Please take a look at https://docs.mitmproxy.org/stable/concepts-modes/.

**Comment by jkryanchou** [comment]
@mhils I have met this issue too. Is there any solution on it. Mitm should be regular proxy mode in this case.

**Comment by jkryanchou** [comment]
@mhils FIxed it. MITM could not pass the relative Path requests.

**Comment by patrickjahns** [comment]
@jkryanchou 
Could you share your solution or how it worked out for you ?

**Comment by jkryanchou** [comment]
@patrickjahns it turns out that you should use absolute paths rather than relative paths. like
Do it 
```
GET https://xxx.google.com/foo/bar
hostname: xxx.google.com
... ...
```

instead of 

```
GET /foo/bar
hostname: xxx.google.com
... ...
```

**Comment by This-is-Y** [comment]
System information
Mitmproxy: 5.0.0
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Windows-10-10.0.19041-SP0

I have met this issue too.but your solution is work@ @jkryanchou 
thanks

![图片](https://user-images.githubusercontent.com/51741690/236597940-2d504b50-a785-448b-b994-ddb57af14585.png)
![图片](https://user-images.githubusercontent.com/51741690/236597958-cf4f7f31-5d1b-4503-9254-fa945e88e1ce.png)

**Comment by Divano-Li** [comment]
@jkryanchou 
i face the same error 
Mitmproxy: 4.0.4
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-5.4.0-139-generic-x86_64-with-glibc2.29
how to change 
`GET /foo/bar
hostname: xxx.google.com
... ...`
to 
`GET https://xxx.google.com/foo/bar
hostname: xxx.google.com
... ...`

**Comment by Divano-Li** [comment]
how to let client use `GET https://xxx.google.com/foo/bar
hostname: xxx.google.com
... ...`
