### ISSUE TITLE
Two error responses on bad HTTP request

### ISSUE THREAD

**Issue by slepogin** [mitmproxy/mitmproxy#3354]
##### Steps to reproduce the problem:

1. Start mitmdump or mitmproxy
2. $ echo "GET bad request HTTP/1.1" | nc 0.0.0.0 8080

This would produce two errors in the response:

```
HTTP/1.1 400 Bad Request
Server: mitmproxy 5.0.0.dev
Connection: close
Content-Length: 290
Content-Type: text/html

<html>
            <head>
                <title>400 Bad Request</title>
            </head>
            <body>
            <h1>400 Bad Request</h1>
            <p>HttpSyntaxException(&quot;Bad HTTP request line: b&#x27;GET test me HTTP&#x27;&quot;,)</p>
            </body>
        </html>HTTP/1.1 502 Bad Gateway
Server: mitmproxy 5.0.0.dev
Connection: close
Content-Length: 327
Content-Type: text/html

<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>ProtocolException(&quot;HTTP protocol error in client request: Bad HTTP request line: b&#x27;GET test me HTTP&#x27;&quot;,)</p>
            </body>
        </html>
```
Expected behaivor - only one error.

##### Any other comments? What have you tried so far?

Happens due to propagating of ProtocolException from **protocol/http.py:292** to **server.py:143**

**Comment by mhils** [comment]
Oops. Well I guess two is better than none. Thanks for the report and the easy repro! 
refs #1775

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
