### ISSUE TITLE
Recommend installation in a virtualenv

### ISSUE THREAD

**Issue by cdunklau** [mitmproxy/mitmproxy#3357]
I noticed that the advanced installation guide recommends using `sudo` for installation with `pip`. This can cause problems because `pip` and the system package manager disagree on who owns what, and in some cases can actually break the OS.

Instead, I suggest advising to install in a virtualenv, or at least in the user site. I don't have the time now to make a full PR, but here's a suggested workflow, after getting Python 3.6 installed:

Make sure you have the stdlib `venv` package. Some distributions don't include this (e.g. Debians), so you need to:

    sudo apt-get install python3-venv

Then create a new virtualenv, and upgrade pip:

    python3 -m venv mitmproxy-env
    mitmproxy-env/bin/pip install --upgrade pip setuptools

And install mitmproxy:

    mitmproxy-env/bin/pip install mitmproxy

The executables can be invoked directly with the path:

    mitmproxy-env/bin/mitmproxy [options]

**Comment by mhils** [comment]
Thanks for raising this. I think there's the implicit assumption from our end that whoever goes to the advanced installation steps runs stuff in venvs anyway, but I guess that's a bad assumption we shouldn't make. 🙄 How would you feel if we just shorten the whole section to the following points:

1. You need Python 3.6 and pip. You can use pyenv to get a recent Python version. (no further specific instructions)
2. Make sure to install stuff into a venv. (we can link to https://docs.python-guide.org/dev/virtualenvs/ here)
3. You can `pip install mitmproxy`, which doesn't require any additional dependencies.

I feel like that'd be easier to maintain than pip + venv install instructions.

**Comment by cdunklau** [comment]
Seems reasonable!

**Comment by ylmrx** [comment]
#3715 please check this.
