### ISSUE TITLE
PermissionDenied on MacOS trying to use transparent proxying

### ISSUE THREAD

**Issue by jabley** [mitmproxy/mitmproxy#3358]
##### Steps to reproduce the problem:

1. Follow the steps for transparent proxying in the documentation – https://docs.mitmproxy.org/stable/howto-transparent/
2. Last step fails

```sh
> sudo -u nobody mitmproxy --mode transparent --showhost
sudo: unable to execute /opt/boxen/homebrew/bin/mitmproxy: Permission denied
```

mitmproxy has been installed with the following she-bang:

`#!/opt/boxen/homebrew/Cellar/mitmproxy/4.0.4/libexec/bin/python3.7`

Python3.7 looks like:

```sh
> ll /opt/boxen/homebrew/Cellar/mitmproxy/4.0.4/libexec/bin/python3.7
-rwxr-xr-x  1 jabley  staff  12552 31 Jul 13:01 /opt/boxen/homebrew/Cellar/mitmproxy/4.0.4/libexec/bin/python3.7
```

##### Any other comments? What have you tried so far?

I can execute other commands using `sudo -u nobody`

```sh
> sudo -u nobody ls
cdn-acceptance-tests	gds-boxen		govuk_frontend_toolkit	metadata-api		router
```

##### System information

```sh
> mitmproxy --version
Mitmproxy: 4.0.4 (+504, commit fdd8e9b)
Python:    3.7.0
OpenSSL:   OpenSSL 1.0.2p  14 Aug 2018
Platform:  Darwin-17.7.0-x86_64-i386-64bit
```

**Comment by mhils** [comment]
Thanks for the report. I'm not on OSX, so I can only guess: What's your output for
```
ll /opt/boxen/homebrew/bin/mitmproxy
```
?

**Comment by kajojify** [comment]
Out of date. Closing. Please, reopen if you still have the issue.
