### ISSUE TITLE
Part of the interface return “content missing”

### ISSUE THREAD

**Issue by susu123456789** [mitmproxy/mitmproxy#3361]
##### Steps to reproduce the problem:

1.Start the mitmproxy
2.Visit the web page and find that part of the interface cannot return data，request headers display "provisional headers are shown"，Chrome's console display "net::ERR_CONNECTION_CLOS"

##### Any other comments? What have you tried so far?

<img width="1414" alt="net_closed" src="https://user-images.githubusercontent.com/29501175/47480777-0e1e5c00-d864-11e8-90cf-01b9fde4dd07.png">

##### System information

Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.0.2p  14 Aug 2018
Platform:  Darwin-17.7.0-x86_64-i386-64bit

**Comment by mhils** [comment]
Can you reproduce this with HTTP/1 or is this a HTTP/2-only phenomenon?

**Comment by susu123456789** [comment]
I think it was  a HTTP/2-only phenomenon, because I didn't find the phenomenon on HTTP /1

**Comment by mhils** [comment]
I can't reproduce this anymore with 7.0 😃
