### ISSUE TITLE
How can I functionally replace the PIP version with the Linux binary?

### ISSUE THREAD

**Issue by 2fst4u** [mitmproxy/mitmproxy#3363]
I can't get mitmproxy to run using the PIP version, I receive errors that I've seen other users complain about, however the binary works fine.

Is there any way I can replace the PIP version with the binary files so that the command "mitmproxy" runs the working version instead of the broken one?

**Comment by mhils** [comment]
This really is a Linux question, not a mitmproxy one. You could just uninstall the pip version, and then place the binary in /usr/local/bin.
