### ISSUE TITLE
Is it possible to add custom log level?

### ISSUE THREAD

**Issue by mitjans** [mitmproxy/mitmproxy#3368]
Hi!

I'm trying to log certain information based on the contents of a websocket message. The default log level is "Info", which means that every time a websocket message is received either by the client or the server, the following message is presented in the EventLog panel:

`info: 192.168.1.54:59672 <- WebSocket 1 message <- "server address"`

A lot of websocket messages are sent between client and server, so the EventLog gets filled with this info level logs. To avoid it, I can lower the log level to "warn" or "error" and use `ctx.log.warn` or `ctx.log.error` in my script to print the logs I'm interested in. This workaround is, although functional, a bit cumbersome and impractical (my script logs will be in red and merged with real errors and warnings).

Is there a way to suppress default "info" logging done by mitm? If not, is there a way to create a custom log level, and then filter the EventLog with the newly created level so that EventLog only displays my logs?

Thanks in advance!

**Comment by mhils** [comment]
Hi,

The log entries you are seeing in mitmproxy are generated here: https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/mitmproxy/tools/console/consoleaddons.py#L41
Logging in mitmdump is also implemented in a separate addon: 
https://github.com/mitmproxy/mitmproxy/blob/c2e2fd1751bfead2e9373358ad81a62728199309/mitmproxy/addons/dumper.py#L29

Right now there is no way to introduce custom log levels or disable builtin addons. You can of course manually monkeypatch them if you so desire, but there are no guarantees that this won't break in a future release. Ultimately we want to display WebSocket flows in the UI, making `UnsupportedLog` go away.
