### ISSUE TITLE
[Windows 7 Critical Issue ] In transparent mode, it cannot capture https url with dedicate port(eg: https://www.h.xiaohanapp.com:4445) while in proxy mode it can

### ISSUE THREAD

**Issue by GeekTT** [mitmproxy/mitmproxy#3369]
##### Steps to reproduce the problem:

1. mitmdump.exe --showhost --mode transparent
2. open one regular url web: https://www.google.com,  it can capture successfully
3. open one https url with dedicate port: https://www.h.xiaohanapp.com:4445, it cannot capture
3. Alternate with no transparent mode, it can capture https://www.h.xiaohanapp.com:4445

##### Any other comments? What have you tried so far?
In transparent mode, it cannot capture all http/https url with dedicate port.
While it did well in proxy mode.

##### System information

C:\Users\qiao>mitmdump --version
Mitmproxy: 4.0.3 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-7-6.1.7601-SP1

**Comment by mhils** [comment]
Hi,

mitmproxy's transparent mode on Windows currently on captures ports 443 and 8080. You can change that by manually starting the redirection before running mitmproxy: 
```
python3 -m mitmproxy.platform.windows redirect --help
```

**Comment by GeekTT** [comment]
Hi, @mhils , thanks for your feedback
I will check this with following command, and if it did take work, I will close it ,thanks.
-------------Check whether "https://www.h.xiaohanapp.com:4445" will be captured -------------------
python3 -m mitmproxy.platform.windows redirect -p 4445
mitmdump --showhost --mode transparent

**Comment by kajojify** [comment]
Out of date. Closing this. 
@GeekTT if you still have questions/issues concerning this topic, please feel free to reopen.
