### ISSUE TITLE
mitmproxy auth + HTTPS site access doest not work with Apple iOS 12.1

### ISSUE THREAD

**Issue by yurig93** [mitmproxy/mitmproxy#3373]
##### Steps to reproduce the problem:

1. Start a proxy with basic auth set (http proxy).
2. Configure iPhone to use your proxy (with auth).
3. Install custom mitm certificate.
4. Access an http site (should work) using safari.
5. Access an https site - you will get a blank page.
6. Now un proxy without auth
7. Access https site (will work).

##### Any other comments? What have you tried so far?
It seems that enabling auth on the proxy somehow breaks https site access with iOS.

##### System information
```
~/code $ mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.6.6
OpenSSL:   OpenSSL 1.0.2p  14 Aug 2018
Platform:  Linux-4.4.111+-x86_64-with
```

**Comment by bamtan** [comment]
I can't even get my client (iPhone 12.1.1) to connect to the mitmproxy. I've tried changing to default port (8080), as well as a different machine (different IP) and still no connection.

**Comment by luzhongyang** [comment]
The same question,https with auth can not work with ios in all mitmproxy versions.

**Comment by outsourcestudio** [comment]
Same here. OS X too
