### ISSUE TITLE
Har file is not being written to disk when using har dump addon with Mitmdump 4.0.4

### ISSUE THREAD

**Issue by YafimK** [mitmproxy/mitmproxy#3377]
artifacts:
1. mitmdump 4.0.2 - downloaded release binaries from the site marked as 4.0.4 (which is a bit odd)
2. har_dump example addon from github repository from '4.x' branch.

##### Steps to reproduce the problem:
1. Try to run 'mitmdump' from cmd, with the mitmdump example addon.
2. No har file is created on exit 

**also reproduced on MacOS.

##### Any other comments? What have you tried so far?
Works perfectly with mitmdump 3.0.4

##### System information
Mitmproxy: 4.0.2 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.17134

**Comment by kajojify** [comment]
@YafimK Hello! Thank you for the report. Sorry for the late response.
Could you please provide the precise link you used to download mitmproxy 4.0.4?

**Comment by jksecurity** [comment]
I can confirm this issue still exists with the latest version of mitmdump (4.0.4) which I pulled from pip. No errors are triggered, but no HAR file is created either.

$ mitmdump --version
Mitmproxy: 4.0.4
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-10-10.0.17134-SP0

The HAR file should only be created on exit, perhaps this event is not being triggered correctly.

**Comment by jksecurity** [comment]
I can confirm that using the har_dump.py from https://github.com/mitmproxy/mitmproxy/pull/3416 and enabling 1 HAR file per flow works fine.

**Comment by worldmind** [comment]
+ official mitmproxy docker image must contain har_dump.py

**Comment by abitrolly** [comment]
Tests for `har_dump.py` are also failing. I fixed simple path problem in #4424 and there are stil errors.

Understanding how to run test in `examples/` is not trivial. Basically `pytest` needs `conftest.py` file with fixtures to be somewhere on the path. I could not find a way to specify location of this file for tests in `examples/`, so I symlinked it.
```
ln -sr test/conftest.py examples
pytest examples/contrib/test_har_dump.py
```

After that, the primary error is still this.
```python
_____________________________ TestHARDump.test_simple _____________________________

self = <test_har_dump.TestHARDump object at 0x7fb35cdb2790>
tmpdir = local('/tmp/pytest-of-anatoli/pytest-10/test_simple0')
tdata = <mitmproxy.utils.data.Data object at 0x7fb35cdbcc70>

    def test_simple(self, tmpdir, tdata):
        with taddons.context() as tctx:
            a = tctx.script(tdata.path("../examples/contrib/har_dump.py"))
            path = str(tmpdir.join("somefile"))
>           tctx.configure(a, hardump=path)

examples/contrib/test_har_dump.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
mitmproxy/test/taddons.py:107: in configure
    self.options.update(**kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = mitmproxy.options.Options({
    'add_upstream_certs_to_client_chain': False [<class 'bool'>],
    'allow_hosts': [] [t...osts': [] [typing.Sequence[str]],
    'upstream_cert': True [<class 'bool'>],
    'websocket': True [<class 'bool'>]
})
kwargs = {'hardump': '/tmp/pytest-of-anatoli/pytest-10/test_simple0/somefile'}
u = {'hardump': '/tmp/pytest-of-anatoli/pytest-10/test_simple0/somefile'}

    def update(self, **kwargs):
        u = self.update_known(**kwargs)
        if u:
>           raise KeyError("Unknown options: %s" % ", ".join(u.keys()))
E           KeyError: 'Unknown options: hardump'
```

**Comment by mhils** [comment]
@abitrolly: The HAR addon really has been a bit neglected. If you care enough to polish it so that we can move it into mitmproxy's core, please hit me up on Slack and I'm happy to help with stuff. :)

**Comment by abitrolly** [comment]
@mhils discord > slack. At least I already registered there. And for Slask I am just tired of registering every time. )

Maybe we can just continue here?

Actually I won't bother with HAR files at all if there was some kind of `mitmdiff` utility with nice colored content. The console command already gives a very nice representation of flows. I am concerned that raw `diff -u3` over HAR files won't be as informative.

For the test itself. It looks like the `load` function is not invoked to set options in fixture call. Is this how this fixture is supposed to work?

https://github.com/mitmproxy/mitmproxy/blob/578514d4f2193468f25ab2c3a5de6e8f445a1c40/examples/contrib/test_har_dump.py#L22-L26

**Comment by mhils** [comment]
Well our developer chat just happens to be on [slack.mitmproxy.org](http://slack.mitmproxy.org/)... 😄 But happy to continue here as well. :)

> For the test itself. It looks like the load function is not invoked to set options in fixture call. Is this how this fixture is supposed to work?

The test and the addon just seem to be in a pretty bad state in general. I would try and go the following route:

1. Make the HAR addon a proper addon class, similar to https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/anticache.py for example (or any of the other addons in mitmproxy.addons).
2. You can then have a proper test set up by passing the addon instance to the `context()` call, like this: https://github.com/mitmproxy/mitmproxy/blob/578514d4f2193468f25ab2c3a5de6e8f445a1c40/test/mitmproxy/addons/test_anticache.py#L9-L10
3. Move the HAR addon out of contrib into mitmproxy/addons/har_export.py.
4. Instead of writing the HAR file to disk in `done()`, write a har_export command similar to this: https://github.com/mitmproxy/mitmproxy/blob/578514d4f2193468f25ab2c3a5de6e8f445a1c40/mitmproxy/addons/export.py#L129-L145
5. You can use `typing.Sequence[flow.Flow]` for multiple flows.

Does that make sense? :)

**Comment by abitrolly** [comment]
It does make sense, and also raises the question how can people write tests for their scripts? Is transforming everything to classes the only way to make the script testable?

> Instead of writing the HAR file to disk in done(), write a har.export command similar to this: 

When this `save` def will be called? I can't find any `save` event at https://docs.mitmproxy.org/stable/addons-events/

**Comment by mhils** [comment]
> When this save def will be called? I can't find any save event at https://docs.mitmproxy.org/stable/addons-events/

Manually by the user, see https://docs.mitmproxy.org/master/concepts-commands/. The benefit is that you can interactively select which flows you want to export, for example you can filter the display flows and then do `safe.file @shown foo.mitm`.

The rest of the `save` addon cover the handling of the `-w` command line switch in `save_stream_file`. It would be really nice if we could eventually unify this, but let's not try to do two things at once. :)

The common part would be to have something like `io.FlowWriter` for HAR files (with an additional finish() method).

> It does make sense, and also raises the question how can people write tests for their scripts? Is transforming everything to classes the only way to make the script testable?

Honestly I've not spend much time thinking about this, but I guess something like the following should just work? 
```python
har = tctx.script(tdata.path("../examples/complex/har_dump.py"))
with taddons.context(har) as tctx:
    ...
```

**Comment by abitrolly** [comment]
@mhils I found this exception in trace log.
```python
ImportError("cannot import name 'connections' from 'mitmproxy')
```
There is indeed no such module. I am of course interested why it is missing and how to replace it, but more important is why the exception is not reraised? There is another exception during trace handling. Any hints if `mitmproxy.ctx` should come with `log` attached?
```pyhton
script_error_handler: (<class 'AttributeError'>, AttributeError("module 'mitmproxy.ctx' has no attribute 'log'"), <traceback object at 0x7fc0fe5861c0>)
```

The hunter trace.
```python
examples/contrib/test_har_dump.py [...]y/examples/contrib/test_har_dump.py:27    line      a = script.load_script(fullpath)
[...]itmproxy/mitmproxy/addons/script.py:19    call      => load_script(path='/home/anatoli/h/hackerspace.by/lib/_mitmproxy/examples/contrib/har_dump.py')
[...]itmproxy/mitmproxy/addons/script.py:20    line         fullname = "__mitmproxy_script__.{}".format(
[...]itmproxy/mitmproxy/addons/script.py:21    line         os.path.splitext(os.path.basename(path))[0]
[...]itmproxy/mitmproxy/addons/script.py:20    line         fullname = "__mitmproxy_script__.{}".format(
[...]itmproxy/mitmproxy/addons/script.py:25    line         sys.modules.pop(fullname, None)
[...]itmproxy/mitmproxy/addons/script.py:26    line         oldpath = sys.path
[...]itmproxy/mitmproxy/addons/script.py:27    line         sys.path.insert(0, os.path.dirname(path))
[...]itmproxy/mitmproxy/addons/script.py:28    line         m = None
[...]itmproxy/mitmproxy/addons/script.py:29    line         try:
[...]itmproxy/mitmproxy/addons/script.py:30    line         loader = importlib.machinery.SourceFileLoader(fullname, path)
[...]itmproxy/mitmproxy/addons/script.py:31    line         spec = importlib.util.spec_from_loader(fullname, loader=loader)
[...]itmproxy/mitmproxy/addons/script.py:32    line         m = importlib.util.module_from_spec(spec)
[...]itmproxy/mitmproxy/addons/script.py:33    line         loader.exec_module(m)
[...]mproxy/examples/contrib/har_dump.py:1     call         => <module>()
[...]mproxy/examples/contrib/har_dump.py:1     line            """
[...]mproxy/examples/contrib/har_dump.py:12    line            import json
[...]mproxy/examples/contrib/har_dump.py:13    line            import base64
[...]mproxy/examples/contrib/har_dump.py:14    line            import zlib
[...]mproxy/examples/contrib/har_dump.py:15    line            import os
[...]mproxy/examples/contrib/har_dump.py:16    line            import typing  # noqa
[...]mproxy/examples/contrib/har_dump.py:18    line            from datetime import datetime
[...]mproxy/examples/contrib/har_dump.py:19    line            from datetime import timezone
[...]mproxy/examples/contrib/har_dump.py:21    line            import mitmproxy
[...]mproxy/examples/contrib/har_dump.py:23    line            from mitmproxy import connections  # noqa
[...]mproxy/examples/contrib/har_dump.py:23    exception     ! <module>: (<class 'ImportError'>, ImportError("cannot import name 'connections' from 'mitmproxy' (/home/anatoli/h/hackerspace.by/lib/_mitmproxy/mitmproxy/__init__.py)"), <traceback object at 0x7fc0fe57df80>)
[...]mproxy/examples/contrib/har_dump.py:23    return       <= <module>: None
[...]itmproxy/mitmproxy/addons/script.py:33    exception  ! load_script: (<class 'ImportError'>, ImportError("cannot import name 'connections' from 'mitmproxy' (/home/anatoli/h/hackerspace.by/lib/_mitmproxy/mitmproxy/__init__.py)"), <traceback object at 0x7fc0fe586100>)
[...]itmproxy/mitmproxy/addons/script.py:36    line         except Exception as e:
[...]itmproxy/mitmproxy/addons/script.py:37    line         script_error_handler(path, e, msg=str(e))
[...]itmproxy/mitmproxy/addons/script.py:43    call         => script_error_handler(path='/home/anatoli/h/hackerspace.by/lib/_mitmproxy/examples/contrib/har_dump.py', exc=ImportError("cannot import name 'connections' from 'mitmproxy' (/home/anatoli/h/hackerspace.by/lib/_mitmproxy/mitmproxy/__init__.py)"), msg="cannot import name 'connections' from 'mitmproxy' (/home/anatoli/h/hackerspace.by/lib/_mitmproxy/mitmproxy/__init__.py)", tb=False)
[...]itmproxy/mitmproxy/addons/script.py:48    line            exception = type(exc).__name__
[...]itmproxy/mitmproxy/addons/script.py:49    line            if msg:
[...]itmproxy/mitmproxy/addons/script.py:50    line            exception = msg
[...]itmproxy/mitmproxy/addons/script.py:51    line            lineno = ""
[...]itmproxy/mitmproxy/addons/script.py:52    line            if hasattr(exc, "lineno"):
[...]itmproxy/mitmproxy/addons/script.py:54    line            log_msg = f"in script {path}:{lineno} {exception}"
[...]itmproxy/mitmproxy/addons/script.py:55    line            if tb:
[...]itmproxy/mitmproxy/addons/script.py:59    line            ctx.log.error(log_msg)
[...]itmproxy/mitmproxy/addons/script.py:59    exception     ! script_error_handler: (<class 'AttributeError'>, AttributeError("module 'mitmproxy.ctx' has no attribute 'log'"), <traceback object at 0x7fc0fe5861c0>)
[...]itmproxy/mitmproxy/addons/script.py:59    return       <= script_error_handler: None
[...]itmproxy/mitmproxy/addons/script.py:37    exception  ! load_script: (<class 'AttributeError'>, AttributeError("module 'mitmproxy.ctx' has no attribute 'log'"), <traceback object at 0x7fc0fe586440>)
[...]itmproxy/mitmproxy/addons/script.py:37    line         script_error_handler(path, e, msg=str(e))
[...]itmproxy/mitmproxy/addons/script.py:39    line         sys.path[:] = oldpath
[...]itmproxy/mitmproxy/addons/script.py:40    line         return m
[...]itmproxy/mitmproxy/addons/script.py:40    return    <= load_script: <module '__mitmproxy_script__.har_dump' from '/home/anatoli/h/hackerspace.by/lib/_mitmproxy/examples/contrib/har_dump.py'>
[...]y/examples/contrib/test_har_dump.py:28    line      print(a)
```

**Comment by mhils** [comment]
> but more important is why the exception is not reraised?

Addons are not supposed to crash mitmproxy in its entirety, so they should only land in the log. Or am I misunderstanding your question?

`mitmproxy.ctx.log` is expected to exist in a properly initialized mitmproxy instance. This is happening in tests?

**Comment by abitrolly** [comment]
@mhils `mitmproxy.ctx.log` doesn't exist at the time the script is loaded.
```python
        from mitmproxy import ctx
        ns = script.load_script(
            tdata.path(
                "mitmproxy/data/addonscripts/addon.py"
            )
        )
>       ctx.log('yyyyyy')
E       AttributeError: module 'mitmproxy.ctx' has no attribute 'log'
```

**Comment by mhils** [comment]
@abitrolly: You need to have a test context, here you can find an example:

https://github.com/mitmproxy/mitmproxy/blob/4909198da7711d623e47b17e60351c7e27c20a4d/test/mitmproxy/addons/test_script.py#L20-L40

**Comment by abitrolly** [comment]
I've added the context and now there is no internal exception about missing `log` attribute. There is also no message about failed `import` exception. This makes troubleshooting these tests uncomfortably hard.

**Comment by abitrolly** [comment]
The missing `mitmproxy.connections` interface was removed in d159897d98d47034827714bd0298268d1b9af6f0. It would be nice to see a direct mention about that in `CHANGELOG` with a reference to porting guide.

**Comment by mhils** [comment]
@abitrolly: Sorry that you have such a painful experience :anguished:

Our current master branch has massive changes compared to the last release (https://mitmproxy.org/posts/new-proxy-core/), which unfortunately comes with a lot of breakage. We haven't assembled a full blog post / changelog yet. I've just been working on new API docs this week in https://github.com/mitmproxy/mitmproxy/pull/4422, which I hope make addon development easier. I have linked the current state in the first post there, is that helpful?

**Comment by abitrolly** [comment]
@mhils the post must be nice reading for someone already familiar `mitmproxy`, but not for me. I prefer to learn be examples, although I must admit diagram looks interesting. Making it animated (to know where to look first) will be even more useful in understanding `mitmproxy` internals.

In #4439 tests are now green and I am going to test the script manually now to ensure this issue is fixed.

**Comment by abitrolly** [comment]
I can confirm now that #4439 fixes this issue.

```bash
$ mitmdump -s ./examples/contrib/har_dump.py --set hardump=export.har
Loading script ./examples/contrib/har_dump.py
Proxy server listening at http://*:8080
^C%
$ less export.har 
$ cat export.har 
{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "mitmproxy har_dump",
      "version": "0.1",
      "comment": "mitmproxy version mitmproxy 7.0.0.dev"
    },
    "entries": []
  }
}%                                                  
```
