### ISSUE TITLE
handle connection timeout error

### ISSUE THREAD

**Issue by mengluo0107** [mitmproxy/mitmproxy#3381]
##### Steps to reproduce the problem:
To save traffics into a har file, I used har_dump.py code. But the traffics are only saved if their responses are received. If I need to save traffics(requests) with connection timeout error, I think I should defined an event handler for error which should be called when a flow error occurred. However, this event is never called, even though there is a connection timeout error.

What I defined is as follows,

def error(flow):
    timestamp = datetime.fromtimestamp(flow.error.msg, tzlocal.get_localzone()).isoformat()
    states = flow.error.get_state()
    mitmproxy.ctx.log(states)
    entry = {
        "timestamp" : timestamp,
        "states": states
    }
    HAR["log"]["entries"].append(entry)

##### System information

3.0.4

**Comment by mhils** [comment]
This should be fixed on master now, please reopen a new issue if that's not the case!
