### ISSUE TITLE
Create a Chocolatey Package Installer

### ISSUE THREAD

**Issue by amirhalatzi** [mitmproxy/mitmproxy#3383]
##### Steps to reproduce the problem:

1. curl https://snapshots.mitmproxy.org/4.0.4/mitmproxy-4.0.4-windows-installer.exe --output mitmproxy-4.0.4-windows-installer.exe 
2. mitmproxy-4.0.4-windows-installer.exe --unattendedmodeui none --mode unattended
3. certutil  -f -service -addstore "Root"  "%userprofile%\.mitmproxy\mitmproxy-ca-cert.cer"

##### Any other comments? What have you tried so far?

Scripting the installation of mitmproxy on Windows

##### System information

Mitmproxy: 4.0.4 binary
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-10-10.0.17134

We'd like to automate mitmproxy install on Windows, the same way it is with brew and other package managers. As Chocolatey is the semi-official package manager for Windows, having a ready-made package would be great

**Comment by mhils** [comment]
Thanks for the suggestion. We currently don't have the resources to maintain individual Linux distribution or Chocolatey packages, so the installer needs to be sufficient for now. I know this might be a bit disappointing, but we do need to make some tradeoffs to spend our time effectively. Sorry!
