### ISSUE TITLE
Seamless mitmproxy?

### ISSUE THREAD

**Issue by javixeneize** [mitmproxy/mitmproxy#3384]
Hi

Is there any way to start mitmproxy in non-interactive mode? It is, it just records the traffic, writes the log in a file, but the app is not displayed in the screen?

Im mainly interested in this option for the docker image, as i need to start it always in interactive mode (-it parameter)

Thanks

**Comment by javixeneize** [comment]
Yes, something like that. Does it worth to rebuild the docker image to
expose it?

**Comment by kajojify** [comment]
@javixeneize yes, you can rebuild the docker image to use mitmdump instead of mitmweb. Please, see this instruction -> https://hub.docker.com/r/mitmproxy/mitmproxy/
If you still have any questions, please feel free to reopen :)
Good luck!
