### ISSUE TITLE
how to decrypt the tcp ssl traffic in transparent mode?

### ISSUE THREAD

**Issue by daumbrella** [mitmproxy/mitmproxy#3386]
##### Steps to reproduce the problem:

1.  when i do : 
"mitmproxy --mode transparent --showhost"
 mitmproxy can decrypt all https trafiic which means the transparent is good.
2. Then I want to decrypt tcp ssl traffic with this:
"mitmproxy --mode transparent --showhost --tcp :443"
the eventlog shows "Client handshake failed."
and when i want to access some https websites , it  suggests that I have a problem with the certificate.

##### Any other comments? What have you tried so far?

I have tried 
"mitmproxy --mode transparent --showhost --tcp ".*" "
"mitmproxy --mode transparent --showhost --tcp  "ip:443""
they won't help.

##### System information

mitmproxy version 4.0.4

**Comment by mhils** [comment]
This should be fixed on master. If that's not the case, please open a new issue!
