### ISSUE TITLE
Non root Docker image 

### ISSUE THREAD

**Issue by javixeneize** [mitmproxy/mitmproxy#3387]
Hi

I have noticed that the docker image of mitmproxy runs as root

However, in the dockerfile less privileged user, mitmproxy, is created

I am trying to modify the dockerfile to start the container as mitmproxy, it is, adding a new step before 
VOLUME /home/mitmproxy/.mitmproxy to switch to that user

USER mitmproxy

But, when running it, this user has no write permission in .mitmproxy folder to store the certificate there

    with open(os.path.join(path, basename + "-ca.pem"), "wb") as f:
PermissionError: [Errno 13] Permission denied: '/home/mitmproxy/.mitmproxy/mitmproxy-ca.pem'

I have tried to own that folder for mitmproxy user (RUN chown mitmproxy /home/mitmproxy/mitmproxy) and even change the permissions to 777, but i still face that problem

Any idea what could i do to make this work?

Thanks

**Comment by mhils** [comment]
> I have noticed that the docker image of mitmproxy runs as root

That shouldn't be the case: https://github.com/mitmproxy/mitmproxy/blob/master/release/docker/docker-entrypoint.sh#L10

Are we doing anything wrong here?

**Comment by javixeneize** [comment]
Hi

The problem is that you execute that docker-entrypoint.sh as root. You can try to add a whoami step in the dockerfile before running that step

I have managed to build a new dockerfile that seems to work fine, although i am not calling that .sh script as entrypoint. 

I am happy to share it if you want to see it

Thanks

**Comment by mhils** [comment]
Yes, but my understanding is that we drop that with `su-exec` when actually running mitmproxy. If you run `whoami` before that you of course get root back.

That being said - please do share your Dockerfile. I'm by no means an expert on this, happy to improve it where possible.

**Comment by javixeneize** [comment]
Hi

Mitmproxy command is not running as root, but you are executing the docker container as root. In fact, i have tried to run this in a PaaS platform and i have an error saying that i can't execute containers with root permissions

Creating a non root user in the dockerfile and creating the .mitmproxy folder with that user will grant him write access there as he is the owner of that folder

**Comment by mhils** [comment]
> Creating a non root user in the dockerfile and creating the .mitmproxy folder with that user will grant him write access there as he is the owner of that folder

`~/.mitmproxy` is not writable in the first place if you invoke docker with `-v ~/.mitmproxy:/home/mitmproxy/.mitmproxy` .

**Comment by javixeneize** [comment]
If you create that folder in the dockerfile it works, as i said with the lines i added to the dockerfile everything works fine, but thats ok
