### ISSUE TITLE
json.dumps(flow.get_state()) - not json serializable

### ISSUE THREAD

**Issue by phackt** [mitmproxy/mitmproxy#3388]
Hello,

While i was playing with a custom script, i tried to dumps the flow.get_state() in order to send it to a rest API. Unfortunately some bytes values are present and i got the following:

```
variable = json.dumps(flow.get_state())
...
TypeError: Object of type 'bytes' is not JSON serializable
```

Am i missing something ? Do i need to use pickle instead ?

Thanks in advance,

**Comment by mhils** [comment]
`.get_state()` works as intended, there are no claims that its output is json-serializable. We have a dedicated function for this in mitmweb:
https://github.com/mitmproxy/mitmproxy/blob/6f893a83c090f049e7cebe3335e7a2a32695946b/mitmproxy/tools/web/app.py#L24
