### ISSUE TITLE
Where is the code design flow

### ISSUE THREAD

**Issue by mansonami** [mitmproxy/mitmproxy#3390]
##### Steps to reproduce the problem:

1. Checkout the code

##### Any other comments? What have you tried so far?
I don't know where to study the code, also check the Doc about how mitmproxy works, but where is the code design flow? Seem that many codes are duplication.

##### System information

latest

**Comment by kajojify** [comment]
@mansonami Hello! Sorry, but I didn't quite understand what you wanted to say(ask). 
- you can study the source code from https://github.com/mitmproxy/mitmproxy/tree/master/mitmproxy
- docs don't describe the code design, docs describe **how to use** the tool. 
Feel free to reopen if you still have questions :)
