### ISSUE TITLE
Injecting multiple websocket messages freezes mitmproxy

### ISSUE THREAD

**Issue by andresriancho** [mitmproxy/mitmproxy#3396]
https://github.com/mitmproxy/mitmproxy/pull/3119 added the feature to inject new messages into existing websocket connections.

The injected messages get stored in two queues, defined [here](https://github.com/mitmproxy/mitmproxy/pull/3119/files#diff-0de40cbc6458548283e26e099bf4edccR84). The queues have `maxsize=1`.

During an application security assessment I was using `mitmproxy` and noticed that when I wanted to inject more than one message the whole `mitmproxy` (actually mitmdump but I guess it is the same) froze while trying to `put()` the second message to the queue.

After a little bit of debugging I changed the size of those queues (to 100), and my code started to work.

##### Steps to reproduce the problem:
Create a script like:

```python
def websocket_message(flow: websocket.WebSocketFlow) -> None:
    flow.inject_message(flow.server_conn, '123')
    flow.inject_message(flow.server_conn, '123')
```

Run it and the code will freeze in the second call to `inject_message`

##### Any other comments? What have you tried so far?
Not sure if I'm doing something wrong: maybe I should do this in an async way? Maybe I should wait until the queue is empty?

Anyways, wanted to report this because it might be a bug that others might hit too.

##### System information
Latest mitmproxy from github.

**Comment by CapitanShinChan** [comment]
Quick question, can you update the messages in in mitm proxy before sending them to the destination?

**Comment by andresriancho** [comment]
AFAIK, no.

**Comment by Kriechi** [comment]
@CapitanShinChan @andresriancho: updating a message before it is sent to the destination should be simple: see this example https://github.com/mitmproxy/mitmproxy/blob/db658b12edf9a44e40ca79209a652e839ffa78dd/examples/simple/websocket_messages.py

@andresriancho for the actual issue you reported here:
Thanks for opening this issue - unfortunately I don't remember why I chose `max_size=1`. 
I think the main idea of limiting the queue size is, to allow the connection to do protocol-level tasks, such as ping+pong frames, without overwhelming it with 1000's of injected messages.

I would be happy to merge a PR that increases the queue size to a reasonable amount, including some form of comment/documentation on the drawbacks and your original findings (i.e., freezing issues with too small queues).

**Comment by CapitanShinChan** [comment]
@Kriechi I tried what you suggest, but the content of the message doesn't get updated.

[Issue with the information](https://github.com/mitmproxy/mitmproxy/issues/3391)

**Comment by dkasak** [comment]
I also ran into this just now. Other than mentioning this problem in the documentation, perhaps it would be reasonable to expose this as a mitmproxy configuration option? I might get around to submitting a PR.

**Comment by Prinzhorn** [comment]
@dkasak looks like you're doing some intensive WebSocket stuff lately! I had this issue subscribed for a while. I was wondering if there is a better way to do this @Kriechi ? Can't we remove the artificial limit completely? If the main reason was to allow for ping/pong, then couldn't we add pongs to the front of the queue when we receive a ping to prioritize it? Isn't the exact point of a queue to prevent overwhelming the other end? I think a user script should be able to queue as many messages as it wants and it's the implementations jobs to make sure the queue is processed in a manner that doesn't conflict with the low level protocol. But I'm not familiar with the low level details of WebSockets.

**Comment by Kriechi** [comment]
Currently there are no strong guarantees. I don't recall a strong reason for the limit of 1 element for each queue. The only reason was to prevent a self-inflicted denial-of-service when dumping 100s of messages into the queue, and then the main loop would fail responding to pings. I'd be happy to merge a PR removing the limit - and see what happens.

Compared to HTTP/2, the problem with WebSocket is that it has no multiplexing on the wire. This means a message consisting of multiple frames blocks the wire until all frames are sent (and received), before the next message can be sent. Ping/pong and other control frames can be injected into the middle if messages (consisting of multiple frames).

**Comment by Prinzhorn** [comment]
This should be fixed in master with a completely rewritten core and WebSocket injection and everything

https://github.com/mitmproxy/mitmproxy/blob/master/examples/addons/websocket-inject-message.py

Please check it out, latest builds are always here https://mitmproxy.org/downloads/#branches/master/
