### ISSUE TITLE
mitmweb does not display icons in Firefox

### ISSUE THREAD

**Issue by baptx** [mitmproxy/mitmproxy#3397]
##### Steps to reproduce the problem:

Icons are not displayed in mitmweb when using Firefox. It works with Chromium but both browser have 404 Not Found errors for fontawesome-webfont.woff and fontawesome-webfont.ttf files.
Ideally, mitmweb should not depend on third-party libraries like Font Awesome and simply use a PNG sprite or inline SVG instead of the icon fonts (https://css-tricks.com/icon-fonts-vs-svg/).

Related issue: https://github.com/mitmproxy/mitmproxy/issues/3034

You can find a screenshot of the icons bug below:
![mitmweb_missing_icons_firefox](https://user-images.githubusercontent.com/3785220/49244642-90c0ab00-f410-11e8-8c99-7cdcb5bbd6e1.png)

##### System information

Mitmproxy: 4.0.4
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.1  11 Sep 2018
Platform:  Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.10-cosmic

**Comment by rolurq** [comment]
Any plans on solving this?

**Comment by crertel** [comment]
This is still an issue.

**Comment by A9466315** [comment]
Get a better browser, and quit using those gay icon packs then we'll talk.

**Comment by crertel** [comment]
@A9466315 there are no "icon packs" being used--the file appears to fail to load, and for whatever reason the links themselves don't render. A simple text fallback underneath (since the anchor elements are clearly visible in the DOM) would help immensely.

Always, please consider how your words might impact other people who are otherwise having a nice day.

**Comment by baptx** [comment]
@A9466315 the font requests fails on both Firefox and Chrome / Chromium. It looks like Chrome / Chromium uses a fallback with local fonts but I would not call it a "better" problem just because it uses a workaround. Firefox still has advantages over Chrome, like being completely open source and Google promotes Chrome, not Chromium, which also does not have an official stable version.

**Comment by mhils** [comment]
mitmweb renders fine for me on the main branch and FontAwesome is loaded properly. If this still is an issue, please reopen. 😃
