### ISSUE TITLE
Allowing Connection: Upgrade to transparently continue

### ISSUE THREAD

**Issue by robertjpayne** [mitmproxy/mitmproxy#340]
Been trying out mitmproxy and must say it's quite awesome. One thing that I'm unsure if it's something I've misconfigured or not is that WebSockets get dropped after the 100 Continue response from the server.

I don't expect mitmproxy to log off the web sockets but it would be nice if it transparently let them continue to run?

Is this possible / planned / able to be scripted?

**Comment by ryoqun** [comment]
@mhils Thanks for supporting WebSocket!

I tested the script. And it works greatly!

However,  I found a corner case bug: When the server sends some data immediately after the connection upgrade, that messages is lost somewhere.. (I couldn't create a patch essily)...

**Comment by ryoqun** [comment]
oops. I was wrong. In my environment, it finally worked with different fix. I'll create a pull request shortly after.

**Comment by ryoqun** [comment]
@mhils As I promised yesterday, here it is: https://github.com/mitmproxy/mitmproxy/pull/544

**Comment by zglozman** [comment]
Did anybody do it ? If not I would love to do it./
