### ISSUE TITLE
error: HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)

### ISSUE THREAD

**Issue by Amaleid** [mitmproxy/mitmproxy#3400]
When i try to use [coffeeminer,](https://github.com/arnaucube/coffeeMiner) the code works perfectly, but only 1 issue is caused, I can't make the devices in my network to connect to the httpserver and i cant execute the script on them error code below.

root@kali:~/Desktop/coffeeMiner-master# python3 coffeeMiner.py 10.20.2.15
gateway: 10.20.2.15
victims:
['10.20.2.20', '']
Loading script injector.py
Proxy server listening at http://*:8080
10.20.2.20:48010: clientconnect
10.20.2.20:48012: clientconnect
**10.20.2.20:48010: HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)**
10.20.2.20:48010: clientdisconnect
10.20.2.20:48012: clientdisconnect

**Comment by Sunil-prajapati** [comment]
Hello 
I am also facing the same issue 

I am trying to send a request with curl and all the data which I am sending is correct

my curl response is 7**.Invalid http request form**
======================
 $delete_data = array(
    	'clientid' =>  $userID,
		'update_time' =>  $update_time,
		'client_name' =>  $details['clientName'],
		'address' =>  '',
		'phone' =>  '',
		'email' =>  '',
		'periodid' => '0',
		'username' =>  $details['username'],
		'password' =>  $details['password'],
		'user_agent' => '',
		'stalker_mac' => '',
		'flag_delete' => 'on',
    );

    $a = http_build_query($delete_data);
     
	 $c['bouquetid'] = $packages;
	 
	    foreach ($c['bouquetid'] as $value) 
	    {
	        $a .= '&';
	        $a .=  'bouquetid'.'='.$value;
	        
	    }
	    $deleteClient = $a;
        curl_setopt($ch, CURLOPT_URL, $adminurl."client_edit?id=".$userID);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $deleteClient);
        curl_setopt($ch, CURLOPT_COOKIEJAR, $cookie_path);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);	
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        $delete = curl_exec($ch);
        echo $delete;die();
