### ISSUE TITLE
Cant run multiple prxies on same port

### ISSUE THREAD

**Issue by MarcoD1337** [mitmproxy/mitmproxy#3409]
I tried to run multiple proixes on same port but it gave me an error which said "Error starting proxy server: OSError(48, 'Address already in use')", It would help if anybody knows how to run multiple proxies on same port.

**Comment by kajojify** [comment]
@MarcoD1337 Hello! You can't run 2 mitmproxys on the same port. Please, use `--listen-port ` to run second instance of mitmproxy on the other port.
