### ISSUE TITLE
mitmproxy crash on connection

### ISSUE THREAD

**Issue by pholat** [mitmproxy/mitmproxy#3414]
##### Issue

I've wanted to dump session keys for connection on port 1883 (mqtt)  using transparent proxy to use them in Wire-shark to decrypt connection.  Mitmproxy crashed.

##### Steps to reproduce the problem:

1. add iptable rule: `sudo iptables -t nat -A PREROUTING -i "$device" -p tcp --dport 8883 -j REDIRECT --to-port 1883`
__on default ubuntu 16.04 package mitmproxy v0.15__
2. run: mitmproxy `SSLKEYLOGFILE="$PWD/.mitmproxy/sslkeylogfile.txt" mitmproxy -T --host -p 1883 -e --cert ./cacertfile.pem`
__on latest v4.0.4__
2. run: SSLKEYLOGFILE="$PWD/sslkeylogfile.txt" ./mitmproxy --mode transparent -p 1883 --certs ~/workspace/docker/rabbitmq-config/cacertfile.pem --ssl-insecure
3. create (can be mqtt) host waiting for connection, using cacertfile.pem i.e. with eclipse-mosquitto or with RabbitMQ with MQTT enabled in my case.
4. make connection attempt to host
5. crash happens with logs below

##### System information

version: mitmproxy 0.15

Log:

v0.15: 

`Exception in thread SlaveThread (0.0.0.0:1883):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/dist-packages/libmproxy/controller.py", line 83, in run
  File "/usr/lib/python2.7/dist-packages/netlib/tcp.py", line 818, in serve_forever
  File "/usr/lib/python2.7/socket.py", line 206, in accept
error: [Errno 24] Too many open files

Event log
10.10.0.146:50490: clientconnect
10.10.0.146:50492: clientconnect
10.10.0.146:50494: clientconnect
10.10.0.146:50496: clientconnect
10.10.0.146:50498: clientconnect
10.10.0.146:50500: clientconnect
10.10.0.146:50502: clientconnect
10.10.0.146:50504: clientconnect
10.10.0.146:50506: clientconnect
10.10.0.146:50508: clientconnect
10.10.0.146:50510: clientconnect
10.10.0.146:50512: clientconnect
10.10.0.146:50514: clientconnect
10.10.0.146:50516: clientconnect`

v4.0.4

Exception in thread ServerThread (('::', 1883, 0, 0)):
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "mitmproxy/master.py", line 37, in run
  File "mitmproxy/net/tcp.py", line 607, in serve_forever
  File "socket.py", line 205, in accept
OSError: [Errno 24] Too many open files

**Comment by mhils** [comment]
Pretty sure you have a redirect loop here where you redirect traffic outgoing from mitmproxy back to mitmproxy again.

**Comment by kajojify** [comment]
@pholat hi! :) 
Can you please check what mhils wrote above? If it is already irrelevant, I will close the issue.

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
