### ISSUE TITLE
Silent Mode

### ISSUE THREAD

**Issue by jcampbell05** [mitmproxy/mitmproxy#3417]
I wish to use this proxy as a production proxy since it has functionality other proxies lack.
Is there a way of running it without any of the debug UI and just as a CLI.

**Comment by jcampbell05** [comment]
@kajojify yes I want to use this proxy as a production proxy, is this possible ?

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but you need to demonstrate that you made an effort at solving the problem yourself first. Can I please ask you to follow up in [our community forums](https://discourse.mitmproxy.org/) for all support and how-to questions?


Thanks!
Max
