### ISSUE TITLE
set-cookie header not returned correctly

### ISSUE THREAD

**Issue by javixeneize** [mitmproxy/mitmproxy#3429]
Hi

I am trying to extract the headers from the traffic captured in mitmproxy. I have noticed that, when in the response there are two set-cookie directives as in https://github.com, it does display only the first one

  data = io.FlowReader(file)
print (item.request.headers.fields)

Set-cookie should be returned as a list

I faced the same problem in another application, and i solved it getting that set-cookie value with response.raw.headers.getlist('Set-Cookie')

**Comment by javixeneize** [comment]
Hi. Yes, set cookie header only contains the first set cookie header when
it should have a list with two cookies

**Comment by javixeneize** [comment]
Hi. Do you need any further information on this?

Thanks

**Comment by mhils** [comment]
We need concrete steps how this can be reproduced and what the actual issue is. I'm still completely in the dark, sorry.

**Comment by javixeneize** [comment]
Ok. Let’s start again


- start mitmdump and write the output to a text file
- Choose a site that sets two cookies, eg - github.com and send it through
the proxy

- check which information has been captured for set cookie header. Only one
of the set cookies directives have been captured
data = io.FlowReader(file)
print (item.request.headers.fields)

**Comment by mhils** [comment]
I'm doing the following:
```
λ mitmproxy --version
Mitmproxy: 4.0.4 (+3, commit 671c86b)
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-16.04-xenial
λ mitmdump -w issue3429
(then in a second tab)
λ curl -x localhost:8080 -k https://github.com/
```
Which gives me the following:
```
λ mitmdump -nr issue3429 --flow-detail 2
127.0.0.1:55827: GET https://github.com/
    Host: github.com
    User-Agent: curl/7.61.0
    Accept: */*
 << 200 OK 78.08k
    Server: GitHub.com
    Date: Sat, 29 Dec 2018 14:54:56 GMT
    Content-Type: text/html; charset=utf-8
    Transfer-Encoding: chunked
    Status: 200 OK
    Cache-Control: no-cache
    Vary: X-PJAX
    Set-Cookie: has_recent_activity=1; path=/; expires=Sat, 29 Dec 2018 15:54:56 -0000
    Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Wed, 29 Dec 2038 14:54:56 -0000; secur
e; HttpOnly
    Set-Cookie: _gh_sess=c[...]a; path=/; secure; HttpO
nly
    X-Request-Id: 2536f52c-e947-43a0-ab59-ae441a163de8
    Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
    X-Frame-Options: deny
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
    Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
    Content-Security-Policy: [...]
    X-GitHub-Request-Id: 6FBF:40E7:8BD09D9:FBC58EC:5C278ABD
```

This seems correct to me, with all headers captured?

**Comment by javixeneize** [comment]
Hi

I am not retrieving the headers in that way. I’m using io.FlowReader to
retrieve the data from the log file

    freader = io.FlowReader(logfile)

And then I get the headers from there, in a similar way as you do in the
following example

https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/io_read_dumpfile.py

But printing f.request.headers.fields
