### ISSUE TITLE
The session key is not created during client handshake

### ISSUE THREAD

**Issue by skotti** [mitmproxy/mitmproxy#3432]
Hello!

I set up SSLKELOGFILE variable, but when I set it in wireshark only server<->mitmproxy part is decrypted. 
I attach two photos from wireshark with the traffic sent. As I have mitmproxy installed on the client, there are two recordings - on the lo interface and ens33.

As I see all steps of tls handshake are correct, so I think session key should be formed before these alert message are sent in both client<->mitmproxy and mitmproxy<->server. What could be the reason for that?
![screenshot from 2018-12-21 15-24-31](https://user-images.githubusercontent.com/8792989/50342548-905d9080-0534-11e9-90c2-5f15895b12ff.png)
![screenshot from 2018-12-21 15-24-06](https://user-images.githubusercontent.com/8792989/50342550-905d9080-0534-11e9-9b18-ae39ac11f5aa.png)

**Comment by mhils** [comment]
This should be fixed on master! :)
