### ISSUE TITLE
Redirecting a particular website on localhost

### ISSUE THREAD

**Issue by khanof89** [mitmproxy/mitmproxy#3433]
##### Steps to reproduce the problem:

1. I am not sure
2.
3.

##### Any other comments? What have you tried so far?

The other day I have installed mitm on my local system and ran it, I was going through examples and used the redirect examples to redirect a particular website to mitmproxy.org, now that i am not even running mitm it still redirect that particular website to mitmproxy.org

##### System information

I have cloned the git repo and ran it in a virtual environment, now when I run this command it says "Command 'mitmproxy' not found, but can be installed with:"

**Comment by mhils** [comment]
Thanks @mansonami!
