### ISSUE TITLE
WARNING:tornado.access on macOS Mojave

### ISSUE THREAD

**Issue by Tomygames** [mitmproxy/mitmproxy#3436]
##### Steps to reproduce the problem:

1. use mitmweb/mitmproxy
2. Try to use it, and see it doesn't work
3. See this in log for every website you visit:
`
WARNING:tornado.access:405 CONNECT github.com:443 (127.0.0.1) 0.38ms
WARNING:tornado.access:405 CONNECT api.github.com:443 (127.0.0.1) 0.29ms
WARNING:tornado.access:405 CONNECT github.com:443 (127.0.0.1) 0.37ms
`

##### Any other comments? What have you tried so far?

Tried to use the master branch, doesn't work

##### System information
Mitmproxy: 4.0.4
Python:    3.7.2
OpenSSL:   OpenSSL 1.0.2q  20 Nov 2018
Platform:  Darwin-18.2.0-x86_64-i386-64bit

Also tested with

Mitmproxy: 5.0.0.dev
Python:    3.7.2
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-18.2.0-x86_64-i386-64bit

macOS version: 10.14.2

**Comment by mhils** [comment]
Hi,

You are using the wrong proxy port. The proxy listens on port 8080, the web interface on 8081.

**Comment by hayden-t** [comment]
der, thanks :)
