### ISSUE TITLE
Unable to run windows.py redirector on Win10 + WSL Linux

### ISSUE THREAD

**Issue by grzaks** [mitmproxy/mitmproxy#3438]
**My setup:**
- Windows 10
- Kali linux installed from Microsoft Store on top of Windows Subsystem for Linux
- In Kali:
Mitmproxy: 4.0.4
Python:    3.6.8rc1
OpenSSL:   OpenSSL 1.1.1  11 Sep 2018
Platform:  Linux-4.4.0-17134-Microsoft-x86_64-with-Kali-kali-rolling-kali-rolling

**The issue**
Mitmproxy itself runs just fine on the Kali shell - it just doesn't get any traffic. I'm sure traffic from mobile device is redirected via this laptop because I can see it in wireshark. It's just the redirector which is not running.

There are IMHO two issues:
1/ on WSL python the `sys.platform` says "linux" so [`mitmproxy/platform/__init__.py`](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/platform/__init__.py) code does not even try to run `windows.py` - so no chance to get the traffic redirected:

```$ python3
Python 3.6.8rc1 (default, Dec 12 2018, 06:12:40)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'linux'
```

2/ if I try to run the `windows.py` script manually I'm getting issues on both WSL Kali shell and native Windows cmd.exe shell with windows version of Python installed. Details below:

**WSL Linux:**

```$ python3 /usr/local/lib/python3.6/dist-packages/mitmproxy/platform/windows.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mitmproxy/platform/windows.py", line 3, in <module>
    import ctypes.wintypes
  File "/usr/lib/python3.6/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported
```

If I understand things correctly WSL is unlike cygwin really a linux, so it'll be unable to run "windows" code. I get the same error when I open python3 shell and try to `import ctypes.wintypes`. Is it correct, that the windows.py script was never ment to be run from WSL shell?

**Native Windows cmd.exe shell**

I did install Python for windows and try to run the same `windows.py` script on it. First it required the `click` and then `pydivert` packages so I installed them via `pip.exe`. 

When I run `python.exe windows.py` without any arguments it works fine, displaying help message:

```
windows.py:174: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class TcpConnectionTable(collections.Mapping):
Usage: windows.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  connections  List all TCP connections and the associated PIDs.
  redirect     Redirect flows to mitmproxy.
```

The `connections` command also works fine:

```
windows.py:174: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class TcpConnectionTable(collections.Mapping):
10.0.0.68:55739 -> 7908
10.0.0.68:55740 -> 7908
10.0.0.68:55741 -> 7908
10.0.0.68:55751 -> 4400
10.0.0.68:55752 -> 9892
10.0.0.68:55912 -> 9892
10.0.0.68:55922 -> 7908
10.0.0.68:55938 -> 9892
10.0.0.68:55939 -> 9892
10.0.0.68:55940 -> 9892
10.0.0.68:55941 -> 9892
10.0.0.68:55942 -> 9892
```

But the `redirect` command fails with this traceback:

```
windows.py:174: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class TcpConnectionTable(collections.Mapping):
 * Redirection active.
Traceback (most recent call last):
  File ".\windows.py", line 591, in <module>
    cli()
  File "C:\Users\ibm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ibm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\ibm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ibm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ibm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File ".\windows.py", line 571, in redirect
    print(f"   Filter: {proxy.request_filter}")
AttributeError: 'TransparentProxy' object has no attribute 'request_filter'
```

Any idea how to fix that?

**Comment by grzaks** [comment]
I managed to get the `redirect` command running without crash but it doesn't actually redirect any packets. 
The `request_filter attribute` error above was easy to fix by just commenting out the print line in the `windows.py` code. The attribute is not mentioned anywhere else in the code. (I'm working on windows.py file from the master branch)

I did enable some debug printing in the code to see what is going on and it looks like injecting the packet back with the dst host/port changed doesn't work. I can't see those packets in the wireshark nor it's getting any response from the mitmproxy/mitmdump app:

```
C:\users\ibm\AppData\Local\Programs\Python\Python37-32\python.exe wind
ows.py redirect --no-local
windows.py:174: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class TcpConnectionTable(collections.Mapping):
IPv4: 10.0.0.68, IPv6: None
 * Redirection active.
 * Redirect client -> server to proxy
10.0.0.222:54958 -> 17.252.92.16:443
10.0.0.222:54958 -> 10.0.0.68:8080

 * Redirect client -> server to proxy
10.0.0.222:54958 -> 17.252.92.16:443
10.0.0.222:54958 -> 10.0.0.68:8080

 * Redirect client -> server to proxy
10.0.0.222:54958 -> 17.252.92.16:443
10.0.0.222:54958 -> 10.0.0.68:8080

 * Redirect client -> server to proxy
10.0.0.222:54958 -> 17.252.92.16:443
10.0.0.222:54958 -> 10.0.0.68:8080

 * Redirect client -> server to proxy
10.0.0.222:54958 -> 17.252.92.16:443
10.0.0.222:54958 -> 10.0.0.68:8080

 * Redirect client -> server to proxy
10.0.0.222:54958 -> 17.252.92.16:443
10.0.0.222:54958 -> 10.0.0.68:8080

 * Shutting down...
 * Shut down.
```

10.0.0.222 is my mobile device
10.0.0.68 is my laptop with mitmproxy or mitmdump running on port 8080

**Comment by mhils** [comment]
This is fixed on main now, I can directly use transparent mode on Windows 10 from an elevated command prompt. 😃
