### ISSUE TITLE
Cannot install certificate on android

### ISSUE THREAD

**Issue by Knifespirit** [mitmproxy/mitmproxy#3440]
##### Steps to reproduce the problem:

1. Start mitmdump
2. Configure the proxy inside the wifi settings
3. Go to mitm.it
4. Download the android version
5. Try installing the cert from ssd
6. You cannot select any .pem files as a cert file

##### Any other comments? What have you tried so far?
I tried using the .p12 version (since I read that android accepts .p12 by default), that you can get from downloading the windows version. Atleast I was able to select the .p12 file, which I could not with the .pem file.

But the problem is. Android only accepts .p12 files with a non empty password.

##### Android
I got android 8.0 

##### Solution
Make a .p12 version avaiable for download with a simple password instead of no password.

**Comment by mhils** [comment]
Installing certs works fine for me on recent Android versions. This much rather seems to be an issue with your Android distribution.
