### ISSUE TITLE
mitmdump memory grows

### ISSUE THREAD

**Issue by ubergeek42** [mitmproxy/mitmproxy#3450]
##### Steps to reproduce the problem:

1. Launch `mitmdump`, the options don't really seem to matter much(I've tried transparent, and regular proxy, with and without scripts)
2. Run htop or similar and filter for the `mitmdump` process, observe Res/Virt memory usage.
3. Load `fast.com`, or literally any website
4. Check memory usage again, observe that it's gone up(and will continue to increase as more requests are made).
5. Wait a while, and observe that the memory usage never goes back down.

Given ~10 minutes I'm able to grow the process from ~50MiB(when it initially starts before receiving any requests) to around ~550MiB(By just going to e.g. news.ycombinator.com and clicking through to every article link on the page). It seems to grow more when loading unique pages, refreshing the same page over and over again grows the resource usage, but not as quickly as loading different sites.

##### Any other comments? What have you tried so far?
I've tried setting websocket streaming to true, `stream_large_bodies` to 1, and different requests: I can trigger this behavior by just running curl to a local http-only(non-ssl) site in a loop. I also tried disabling http2.

I've seen a number of tickets about this, but nothing recent-ish. I saw there were great strides made in the past to fix these memory issues with mitmdump, so I'm curious if this bug report is useful to you.
https://github.com/mitmproxy/mitmproxy/issues/2828 - related recent issue
https://discourse.mitmproxy.org/t/mitmdump-large-memory-consumption/197

I am happy to run any additional tests/test out any patches/config options/etc. I'd also appreciate any pointers in the right direction to help narrow down the cause of the memory usage myself.

##### System information
I'm running inside a generic ubuntu:18.04 docker image, using system python and just doing `pip3 install mitmproxy`. I believe I've also tried the latest from git with the same issue.

```
# mitmdump --version
Mitmproxy: 4.0.4
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
```

**Comment by bleuf1sh** [comment]
see the related issue
#3191 
https://github.com/mitmproxy/mitmproxy/issues/3191#issuecomment-469557156

**Comment by irsl** [comment]
Come on, this turns this awesome software kind of useless.

**Comment by Prinzhorn** [comment]
A lot of improvement has been made since this was opened, most notably but not only because of the efforts in https://github.com/mitmproxy/mitmproxy/issues/4456
