### ISSUE TITLE
decide on response event base on requestheaders event value

### ISSUE THREAD

**Issue by s0heil** [mitmproxy/mitmproxy#3452]
##### Steps to reproduce the problem:
i want to add something at response of some request that received with my mitmproxy. based on request header on it. at first i define instance value in my addon, (use a flag). then check request header in requestheaders event, if the condition is true, set true on my flag. at response event if my flag is true then add some thing to the response. but the point is there is no instance value in addon and the initialized just once that mitmproxy start working.  
i checked many way, for example saving requestheaders value in hash table but i can not even find a way to map which response is for which request.
I would appreciate  FOR ANY HELPS

 Thanks! :) -->

**Comment by mhils** [comment]
Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!
