### ISSUE TITLE
 Mobile internet

### ISSUE THREAD

**Issue by WhisperLoli** [mitmproxy/mitmproxy#3455]
I installed mitmproxy, the phone is also connected to the proxy, but can not access the Internet

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but you need to demonstrate that you made an effort at solving the problem yourself first. Can I please ask you to follow up in [our community forums](https://discourse.mitmproxy.org/) for all support and how-to questions?


Thanks!
Max
