### ISSUE TITLE
unable install mitmproxy on mac

### ISSUE THREAD

**Issue by zimengfang** [mitmproxy/mitmproxy#3458]
pip install mitmproxy
Collecting mitmproxy
  Using cached https://files.pythonhosted.org/packages/e5/6c/fe3f4b4cbef7f703b1199d5443963c4c56c2182223375bdaf0930e1ad052/mitmproxy-4.0.4-py3-none-any.whl
Requirement already satisfied: certifi>=2015.11.20.1 in ./venv/lib/python3.7/site-packages (from mitmproxy) (2018.11.29)
Requirement already satisfied: tornado<5.2,>=4.3 in ./venv/lib/python3.7/site-packages (from mitmproxy) (5.1.1)
Requirement already satisfied: h2<4,>=3.0.1 in ./venv/lib/python3.7/site-packages (from mitmproxy) (3.1.0)
Requirement already satisfied: cryptography<2.4,>=2.1.4 in ./venv/lib/python3.7/site-packages (from mitmproxy) (2.3.1)
Requirement already satisfied: pyperclip<1.7,>=1.6.0 in ./venv/lib/python3.7/site-packages (from mitmproxy) (1.6.5)
Requirement already satisfied: passlib<1.8,>=1.6.5 in ./venv/lib/python3.7/site-packages (from mitmproxy) (1.7.1)
Requirement already satisfied: kaitaistruct<0.9,>=0.7 in ./venv/lib/python3.7/site-packages (from mitmproxy) (0.8)
Requirement already satisfied: click<7,>=6.2 in ./venv/lib/python3.7/site-packages (from mitmproxy) (6.7)
Requirement already satisfied: pyasn1<0.5,>=0.3.1 in ./venv/lib/python3.7/site-packages (from mitmproxy) (0.4.5)
Collecting brotlipy<0.8,>=0.7.0 (from mitmproxy)
  Using cached https://files.pythonhosted.org/packages/d9/91/bc79b88590e4f662bd40a55a2b6beb0f15da4726732efec5aa5a3763d856/brotlipy-0.7.0.tar.gz
Requirement already satisfied: ldap3<2.6,>=2.5 in ./venv/lib/python3.7/site-packages (from mitmproxy) (2.5.2)
Requirement already satisfied: pyparsing<2.3,>=2.1.3 in ./venv/lib/python3.7/site-packages (from mitmproxy) (2.2.2)
Requirement already satisfied: urwid<2.1,>=2.0.1 in ./venv/lib/python3.7/site-packages (from mitmproxy) (2.0.1)
Requirement already satisfied: pyOpenSSL<18.1,>=17.5 in ./venv/lib/python3.7/site-packages (from mitmproxy) (18.0.0)
Requirement already satisfied: blinker<1.5,>=1.4 in ./venv/lib/python3.7/site-packages (from mitmproxy) (1.4)
Requirement already satisfied: ruamel.yaml<0.16,>=0.13.2 in ./venv/lib/python3.7/site-packages (from mitmproxy) (0.15.87)
Requirement already satisfied: sortedcontainers<2.1,>=1.5.4 in ./venv/lib/python3.7/site-packages (from mitmproxy) (2.0.5)
Requirement already satisfied: wsproto<0.12.0,>=0.11.0 in ./venv/lib/python3.7/site-packages (from mitmproxy) (0.11.0)
Requirement already satisfied: hyperframe<6,>=5.1.0 in ./venv/lib/python3.7/site-packages (from mitmproxy) (5.2.0)
Requirement already satisfied: hpack<4,>=2.3 in ./venv/lib/python3.7/site-packages (from h2<4,>=3.0.1->mitmproxy) (3.0.0)
Requirement already satisfied: idna>=2.1 in ./venv/lib/python3.7/site-packages (from cryptography<2.4,>=2.1.4->mitmproxy) (2.8)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in ./venv/lib/python3.7/site-packages (from cryptography<2.4,>=2.1.4->mitmproxy) (1.11.5)
Requirement already satisfied: asn1crypto>=0.21.0 in ./venv/lib/python3.7/site-packages (from cryptography<2.4,>=2.1.4->mitmproxy) (0.24.0)
Requirement already satisfied: six>=1.4.1 in ./venv/lib/python3.7/site-packages (from cryptography<2.4,>=2.1.4->mitmproxy) (1.12.0)
Requirement already satisfied: h11~=0.7.0 in ./venv/lib/python3.7/site-packages (from wsproto<0.12.0,>=0.11.0->mitmproxy) (0.7.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography<2.4,>=2.1.4->mitmproxy) (2.19)
Installing collected packages: brotlipy, mitmproxy
  Running setup.py install for brotlipy ... error
    Complete output from command /Users/zimengfang/python/scrapy项目/venv/bin/phon -u -c "import setuptools, tokenize;__file__='/private/var/folders/t4/flv3wjsj56qdjty1156d45fh0000gn/T/pip-install-insevcl0/brotlipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/t4/flv3wjsj56qdjty1156d45fh0000gn/T/pip-record-81pz3s4f/install-record.txt --single-version-externally-managed --compile --install-headers /Users/zimengfang/python/scrapy项目/venv/include/site/python3.7/brotlipy:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.7
    creating build/lib.macosx-10.6-intel-3.7/brotli
    copying src/brotli/build.py -> build/lib.macosx-10.6-intel-3.7/brotli
    copying src/brotli/__init__.py -> build/lib.macosx-10.6-intel-3.7/brotli
    copying src/brotli/brotli.py -> build/lib.macosx-10.6-intel-3.7/brotli
    running build_clib
    building 'libbrotli' library
    creating build/temp.macosx-10.6-intel-3.7
    creating build/temp.macosx-10.6-intel-3.7/libbrotli
    creating build/temp.macosx-10.6-intel-3.7/libbrotli/common
    creating build/temp.macosx-10.6-intel-3.7/libbrotli/dec
    creating build/temp.macosx-10.6-intel-3.7/libbrotli/enc
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/common/dictionary.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/common/dictionary.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/dec/huffman.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/dec/huffman.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/dec/bit_reader.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/dec/bit_reader.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/dec/decode.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/dec/decode.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/dec/state.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/dec/state.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/backward_references.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/backward_references.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/backward_references_hq.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/backward_references_hq.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/bit_cost.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/bit_cost.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/block_splitter.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/block_splitter.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/histogram.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/histogram.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/memory.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/memory.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/literal_cost.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/literal_cost.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/brotli_bit_stream.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/brotli_bit_stream.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/compress_fragment_two_pass.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/compress_fragment_two_pass.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/compress_fragment.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/compress_fragment.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/cluster.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/cluster.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/utf8_util.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/utf8_util.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/encode.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/encode.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/metablock.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/metablock.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/static_dict.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/static_dict.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/dictionary_hash.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/dictionary_hash.o
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli/include -Ilibbrotli/ -Isrc/brotli -c libbrotli/enc/entropy_encode.c -o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/entropy_encode.o
    ar rcs build/temp.macosx-10.6-intel-3.7/liblibbrotli.a build/temp.macosx-10.6-intel-3.7/libbrotli/common/dictionary.o build/temp.macosx-10.6-intel-3.7/libbrotli/dec/huffman.o build/temp.macosx-10.6-intel-3.7/libbrotli/dec/bit_reader.o build/temp.macosx-10.6-intel-3.7/libbrotli/dec/decode.o build/temp.macosx-10.6-intel-3.7/libbrotli/dec/state.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/backward_references.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/backward_references_hq.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/bit_cost.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/block_splitter.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/histogram.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/memory.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/literal_cost.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/brotli_bit_stream.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/compress_fragment_two_pass.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/compress_fragment.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/cluster.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/utf8_util.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/encode.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/metablock.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/static_dict.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/dictionary_hash.o build/temp.macosx-10.6-intel-3.7/libbrotli/enc/entropy_encode.o
    warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: build/temp.macosx-10.6-intel-3.7/liblibbrotli.a will be fat and ar(1) will not be able to operate on it
    ranlib build/temp.macosx-10.6-intel-3.7/liblibbrotli.a
    running build_ext
    generating cffi module 'build/temp.macosx-10.6-intel-3.7/_brotli.c'
    building '_brotli' extension
    creating build/temp.macosx-10.6-intel-3.7/build
    creating build/temp.macosx-10.6-intel-3.7/build/temp.macosx-10.6-intel-3.7
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -Ilibbrotli -Ilibbrotli/include -I/Users/zimengfang/python/scrapy项目/venv/include -I/Library/Frameworks/Python.frawork/Versions/3.7/include/python3.7m -c build/temp.macosx-10.6-intel-3.7/_brotli.c -o build/temp.macosx-10.6-intel-3.7/build/temp.macosx-10.6-intel-3.7/_brotli.o
    gcc -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.7/build/temp.macosx-10.6-intel-3.7/_brotli.o -Lbuild/temp.macosx-10.6-intel-3.7 -llibbrotli -lstdc++ -llibbrotli -o build/lib.macosx-10.6-intel-3.7/brotli/_brotli.abi3.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

**Comment by freedom-wy** [comment]
i have same problem on mac os

**Comment by issess** [comment]
Try again in python 3.6.  I succeeded.

**Comment by youran1024** [comment]
i have the same too, any idea?

**Comment by unsunzhensheng** [comment]
You can install mitmproxy with Homebrew.
Homebrew official website ：https://brew.sh/
After installing the Homebrew，in terminal operation

brew install mitmproxy

**Comment by shieleven** [comment]
> 再试一次python 3.6。
> 
> 要么
> 
> 改变stdlib
> 
> export MACOSX_DEPLOYMENT_TARGET = 10.10 
> CFLAGS =' - stdlib = libc ++' 
> pip install mitmproxy
Thank you very much for your reply. I solved the problem.
