### ISSUE TITLE
Trying to run mitmweb on a Hyper-V VM win windows 10 Home

### ISSUE THREAD

**Issue by baretomas** [mitmproxy/mitmproxy#3461]
##### Steps to reproduce the problem:

1. Install Mitmproxy
2. Install certificate through web page and put certificate into trusted root certificate authorities
3. Run: mitmweb --mode transparent --listen-port 1081 --web-port 8081 --showhost

##### Any other comments? What have you tried so far?
The web page will load but no traffic is captured. If I open a browser (Edge I tested), no web pages are loaded. Lookes like it lost internet Connectivity. 
What am I missing?mit

##### System information

Mitmproxy: 4.0.4
Python: 3.6.6
OpenSSL: OpenSSL 1.1.0i 14 Aug 2018
Platform: Windows-10-10-0.17763

**Comment by 1UC1F3R616** [comment]
@baretomas you found the error?

**Comment by baretomas** [comment]
I solved it yeh. Was on my end, but can't remember what it was now.

**Comment by 1UC1F3R616** [comment]
I solved this
- Check that you install the required certificate, click [here](mitm.it) after starting the mitmweb and directing traffic through the mitm proxy port
- Now simply keep clicking and in password leave it blank (yeah blank) and make it a trusted one, refer [here](https://stackoverflow.com/questions/43596121/mitmproxy-certificate-prompting-for-the-password)
- You are all done, happy hacking :)
