### ISSUE TITLE
Can I control the intercept behavior via network?

### ISSUE THREAD

**Issue by lexjhuang** [mitmproxy/mitmproxy#3463]
##### Steps to reproduce the problem:

There is a need that we control the intercept behavior via network, that is something like below work flow.
  setup the proxy -> visit an url via the proxy -> a command is injected to the proxy(so that the proxy will intercept or modify the traffic according to my command)
Hope you understand what I mean.
I think the proxy now have the power like mitmproxy -s myscript.py
But my question is can I do write myscript.py to fulfill above need?

##### Any other comments? What have you tried so far?

I have already fork a branch of mitmproxy and achieve this by modifying the mitmproxy itself.
If the answer is no, then I think I can do a pull request.
##### System information

mitmproxy 4.0

**Comment by c0rpse** [comment]
Looks like BurpSuite?

**Comment by codewithvicky** [comment]
No, You can do the or create a pull request.

**Comment by Prinzhorn** [comment]
You can use `ctx.options` in a `request` hook to do exactly that and change options by calling a URL such as `http://mitmproxy-controller/toggle-something` through the proxy

```py
from mitmproxy import ctx
from mitmproxy import http


def request(flow):
    if (
        flow.request.pretty_host == "mitmproxy-controller"
        and flow.request.path == "/disable-http2"
    ):
        ctx.options.update(http2=False)
        flow.response = http.Response.make(200, "", dict())

```
