### ISSUE TITLE
Block global is blocking local IP

### ISSUE THREAD

**Issue by aznxfrost** [mitmproxy/mitmproxy#3466]
##### Steps to reproduce the problem:

1. 
Set up transparent proxy using MITMPROXY with block_global=true

2. 
Use iptables port redirection to redirect local traffic to MITMPROXY, for example: `iptables -t nat -A OUTPUT -p tcp --dport 443 -m owner ! --uid-owner 0 -j DNAT --to 127.0.0.1:7888`

3. 
When traffic are being redirected through MITMPROXY, mitmproxy detects connecting IP as "::ffff:192.168.1.2" and mistakenly categorize it as a global IP hence blocking the connection (it is in fact an IPv4 padded IPv6 LAN IP)

ip -A reveals two network interfaces:
lo: 127.0.0.1
eth0: 192.168.1.2

I have never seem this problem before, this only happens to one particular VPS provider running CentOS 7.6.
Disabling IPV6 on the machine does not help, listening on 127.0.0.1 doesnt help either.

##### System information

Mitmproxy: 4.0.4
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core

**Comment by mhils** [comment]
We do indeed do classify `::ffff:192.168.1.2` as private, the relevant code is at https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/addons/block.py. :)
