### ISSUE TITLE
Unformatted documentation page

### ISSUE THREAD

**Issue by cwardata** [mitmproxy/mitmproxy#3467]
##### Steps to reproduce the problem:

1. google "simple mitmproxy example"
2. first result is: https://mitmproxy.readthedocs.io/en/latest/src/examples/simple/
3. See unreadable page

##### Any other comments? What have you tried so far?

Obviously the correct examples are in the examples/ folder in this repo

**Comment by cwardata** [comment]
Also links to https://mitmproxy.readthedocs.io/en/latest/index.html without much data and "Edit" button links to unexistent github page

**Comment by kajojify** [comment]
Hello! Thank you for the report. Unfortunately google shows the old documentation for this query.
We have new one https://docs.mitmproxy.org/stable/, so please use it :)

**Comment by cwardata** [comment]
@kajojify Couldn't it redirect to the new documentation home at least, ideally to the correct new pages would be extra nice
