### ISSUE TITLE
Export to JSON

### ISSUE THREAD

**Issue by cwardata** [mitmproxy/mitmproxy#3468]
##### Steps to reproduce the problem:

1. Log flows
2. Want to read flows from other language from python
3. Can't export one or multiple flow to JSON

##### Any other comments? What have you tried so far?

Ideally I could export all the flows matching a filter to JSON

##### System information

```
Mitmproxy: 4.0.4
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Darwin-17.7.0-x86_64-i386-64bit
```

**Comment by cwardata** [comment]
Found a way to do it by hooking up a script to `mitmdump`.

```
from mitmproxy import http
import json

def response(flow: http.HTTPFlow) -> None:
    if (flow.request.method == "x"):
        if (flow.request.host == "x"):
            if (flow.request.path == "x"):
                with open('out.json', 'w') as out:
                    json.dump(flow.response.text, out)
```

Also `mitmdump -s script.py "~u mypath"` should probably filter the requests the script receives

**Comment by kajojify** [comment]
@cwardata Hello there! Please, use this script to export flows into json - https://github.com/mitmproxy/mitmproxy/pull/2861
We can't get it merged because of the other blocking issue, but it should work well. 
Please, reopen if you need anything :) 
Good luck!

**Comment by cwardata** [comment]
@kajojify Thanks a lot. I was kind of confused at first about how to use mitmproxy / mitmdump but now it's all good and I think it's one of best software ever made! Thanks a lot to all the team!
