### ISSUE TITLE
I run mitmweb but get "OSError 98 Address already in use" error

### ISSUE THREAD

**Issue by hub2git** [mitmproxy/mitmproxy#3471]
##### Steps to reproduce the problem:

1. Download https://snapshots.mitmproxy.org/4.0.4/mitmproxy-4.0.4-linux.tar.gz
2. Extract archive
3. Run chmod +x mitmproxy
4. Run chmod +x mitmweb
5. Run chmod +m mitmdump
6. Run ./mitmweb

 

##### System information

Cinnaman Linux Mint 19.1 Tessa 

 ~ $ python3 --version
Python 3.6.7

 python --version
Python 2.7.15rc1

> mitmproxy --version
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (urwid 2.0.1 (/usr/lib/python3/dist-packages), Requirement.parse('urwid<1.4,>=1.3.1'), {'mitmproxy'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/mitmproxy", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
>     @_call_aside
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'urwid<1.4,>=1.3.1' distribution was not found and is required by mitmproxy
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
>     os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mitmproxy.1000.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (urwid 2.0.1 (/usr/lib/python3/dist-packages), Requirement.parse('urwid<1.4,>=1.3.1'), {'mitmproxy'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/mitmproxy", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
>     @_call_aside
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'urwid<1.4,>=1.3.1' distribution was not found and is required by mitmproxy
>

**Comment by full-stack-ex** [comment]
Getting the same when running this on Ubuntu 18.04.3 LTS:
mitmdump -R http://localhost:8080 -p 8888

Python 2.7.15+ is the default.

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
