### ISSUE TITLE
On windows server 2008 r2, using ip to access the website failed when the dns server is unavailable

### ISSUE THREAD

**Issue by luojian520** [mitmproxy/mitmproxy#3473]
##### Steps to reproduce the problem:

1.set a dns server which is not unavailable
![image](https://user-images.githubusercontent.com/26667694/52626649-9ba6ba00-2eee-11e9-9368-307dd94bf0f6.png)

2.open proxy
![image](https://user-images.githubusercontent.com/26667694/52627249-ebd24c00-2eef-11e9-83d2-d6b374403647.png)

3.chrome cannot access website by ip
![image](https://user-images.githubusercontent.com/26667694/52627282-fd1b5880-2eef-11e9-8a49-b8b49e6975ae.png)

4.it is ok on windows 10

##### Any other comments? What have you tried so far?
![image](https://user-images.githubusercontent.com/26667694/52627525-90548e00-2ef0-11e9-851c-66adb7d8e6b3.png)
I commented out these two lines in mitmproxy\net\tcp.py, It seems to be good.
But I don't know the role of these two lines.

##### System information

mitmproxy version is 2.0.22

**Comment by Kriechi** [comment]
outdated mitmproxy version. please upgrade.
