### ISSUE TITLE
Redirects in the documentation

### ISSUE THREAD

**Issue by localhostdotdev** [mitmproxy/mitmproxy#3474]
##### Steps to reproduce the problem:

1. Read through Github issues
2. Find a link like: http://docs.mitmproxy.org/en/stable/features/passthrough.html#how-it-works
3. Link redirects to documentation home page

##### Any other comments? What have you tried so far?

The links are still nice enough that I usually can find the corresponding page. In this case the closest I could get was https://docs.mitmproxy.org/stable/overview-features/ and could not get to the correct page

(I'm getting `nodename nor servname provided, or not known` and not sure how to fix, looking everywhere, solution for future googlers was to restart my computer)

**Comment by Kriechi** [comment]
Most information moved into https://docs.mitmproxy.org/stable/concepts-modes/
