### ISSUE TITLE
mitmdump fails with 404 error

### ISSUE THREAD

**Issue by yhojann-cl** [mitmproxy/mitmproxy#3475]
##### Steps to reproduce the problem:

1. Execute:

> $ mitmdump --listen-port 8888 --listen-host 127.0.0.1 --mode reverse:http://127.0.0.1:8080/ --scripts test.py

2. In the python script:

```
from mitmproxy.script import concurrent

@concurrent
def error(flow):
    pass

@concurrent  # Remove this and see what happens
def request(flow):
    flow.request.headers['Host'] = 'abc.com'
    pass

@concurrent
def responseheaders(flow):
    pass

@concurrent
def response(flow):
    pass
    
@concurrent
def clientconnect(root_layer):
    pass
```

The result:

```
127.0.0.1:56182: GET http://127.0.0.1:8080/abc/def.html?var=value&var2%5Bdimension%5D=value
              << 404 Not Found 210b
Addon error: Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/mitmproxy/script/concurrent.py", line 32, in _concurrent
    obj.reply.take()
  File "/home/***/.local/lib/python3.6/site-packages/mitmproxy/controller.py", line 92, in take
    "Reply is {}, but expected it to be start.".format(self.state)
mitmproxy.exceptions.ControlException: Reply is committed, but expected it to be start.
```

##### System information

```
$ mitmdump --version
Mitmproxy: 4.0.4
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.15.0-45-generic-x86_64-with-Ubuntu-18.04-bionic
```

Installed from pip3.

**Comment by MrHr6874** [comment]
@WHK102 
![Screenshot from 2019-03-17 08-52-51](https://user-images.githubusercontent.com/42005470/54491128-43b6f680-4892-11e9-8e83-f79215e0f162.png)

**Comment by WHK102** [comment]
Sorry, you need the mitmproxy header `from mitmproxy.script import concurrent`, but the problem are the unable send the real "host" header to server beacuse mitmproxy override the header send a false hostname and the virtualhost of apache httpd server can not found the hostname.

I solve my problem forcing the host header using `flow.request.host_header` and `flow.request.host`.

The arbitrary changing of the host header by mitmproxy is a very very bad. When using the mitmproxy for intercept real websites the people modify the `/etc/host` file for redirect all traffic of the affected website to local, by example, using the Burpsuite, but the host header for the http request can not change, one server can having one o more virual host or hostnames, by example www.example.com and example.com and this two hostname store two different rules in the webserver. For solve this using mitmproxy need run an instances of mitmproxy for test with www and stop and run again for without www?. It can made using the application script, but the mitmproxy should not override the host header in http requests.

Find it in Google: `(mitmproxy | mitmdump) header host problem`, many people have a problems with the arbitrary modification of header host using mitmproxy or mitmdump.
