### ISSUE TITLE
If you can see this, traffic is not passing through mitmproxy

### ISSUE THREAD

**Issue by jepunband** [mitmproxy/mitmproxy#3476]
mitmproxy - 0.18.2

Hi after starting mitmproxy, when go to mitm.it i get this "**If you can see this, traffic is not passing through mitmproxy**".

i have done all this:
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080

how to solve this?

**Comment by mhils** [comment]
Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!
