### ISSUE TITLE
error:HTTP protocol error in client request

### ISSUE THREAD

**Issue by yslion** [mitmproxy/mitmproxy#3481]
<< Bad HTTP request line: b'\x80U\x01\x03\x01\x00<\x00\x00\x00\x10\x00\x005\x00\x00/\x00\x00\x04\x00\x00\x05\x00\x00'
10.10.8.250:1692: CONNECT 10.134.132.176:8888
 << HTTP protocol error in client request: Bad HTTP request line: b'\x80U\x01\x03\x01\x00<\x00\x00\x00\x10\x00\x005\x00\x00/\x00\x00\x04\x00\x00\x05\x00\x00'

**Steps to reproduce the problem:**
1 run ‘mitmdump.exe --set ssl_version_client=TLSv1 --set ssl_version_server=TLSv1  --s
sl-insecure‘  in cmd 
2  find another PC ,  install root certificate   ,  Configure **IE6/IE8 in XP**   to use it as a proxy  (chrome in XP is ok )
3 Visit a website started with 'https'  

**Any other comments? What have you tried so far?**
mitmproxy works well in win10 ie11 chrome firefox  , but only   IE6/IE8 with https in XP   . 

Many customers of us are using these old Win system :(

Could you give me some solutions ? many thanks ..

**Comment by Henner** [comment]
I have the same problem. Any hints on this?

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
