### ISSUE TITLE
Feature request - Add  an option to run in background as service

### ISSUE THREAD

**Issue by WHK102** [mitmproxy/mitmproxy#3483]
Add  an option to run in background as service like as postgresql binaries using pg_ctl. From ssh access run the pg_ctl with run arguments and the pg service run in background without current shell session.

Example: `mitmdump [options...] --service start`

And save the pid file in current directory for multiple instances or declare manualy, example: `mitmdump [options...] --service start --pid-file ./instance-website.com.pid`

**Comment by mhils** [comment]
Thanks for the suggestion. This seems like something you can solve with a simple bash script (or mitmproxy addon if so desired), so I don't see why we should maintain multiple command line flags for this?

**Comment by kajojify** [comment]
If there are any questions, please reopen.

**Comment by jineshqa** [comment]
@mhils Perhaps a comprehensive example will help.

**Comment by jineshqa** [comment]
@WHK102 Were you able to find a workaround? If not here is what I do,

`screen -dm -S "mitmqa" ./startmitm.sh`

mitmqa is alias for my screen and ./startmitm.sh contains command to run mitmproxy with certain options.

**Comment by WHK102** [comment]
screen does not replace a dedicated service, for example, it does not handle state logs, nor is it able to re-establish the process when it is stopped, nor is it capable of allocating resource use efficiently. A dedicated service is designed to run an application efficiently and stably, screen only serves to keep running something in the background. If a dedicated service were created even if it were basic, official features could be added along the way. mitmdump is not only used for hacking, also to create business layers in WEB applications, for which a background option that is native and that works in both linux and windows and mac is necessary, so it can not depend so much on screen or systemd, just like postgres does with `pg_ctl start [...]`.

**Comment by jaimeiniesta** [comment]
Hi, I'm looking for a way to self-host a proxy service on Render.com and it looks like mitmdump could do the job.

Deploying on Render can be done with a Dockerfile, and the deploy must run in non-interactive mode so running it via systemd looks like the best option.

Have you got an example of how to do this?
