### ISSUE TITLE
not capturing anything

### ISSUE THREAD

**Issue by asvi2409** [mitmproxy/mitmproxy#3484]
greetings 

Events
info: 127.0.0.1:59374: clientconnect
info: 127.0.0.1:59376: clientconnect
warn: 127.0.0.1:59376: HTTP protocol error in client request: Bad HTTP request line:
b'\x05\x01\x00'
warn: 127.0.0.1:59374: HTTP protocol error in client request: Bad HTTP request line:
b'\x05\x01\x00'
info: 127.0.0.1:59374: clientdisconnect
info: 127.0.0.1:59376: clientdisconnect
info: 127.0.0.1:59380: clientconnect
info: 127.0.0.1:59382: clientconnect

I also tried to run with --rawtcp and transparent mode but getting the same result

Mitmproxy: 4.0.4
Python:    3.7.2
OpenSSL:   OpenSSL 1.1.1a  20 Nov 2018
Platform:  Linux-4.14.101-1-MANJARO-x86_64-with-arch-Manjaro-Linux

**Comment by WHK102** [comment]
More details? what is the raw request?

**Comment by kajojify** [comment]
Hi! Thanks for the report! :)
Sorry, but closing this because of inactiveness.

**Comment by Skeeve** [comment]
Same(?) issue here

```
 << Bad HTTP request line: b'\x05\x01\x00'
 << Bad HTTP request line: b'\x05\x01\x00'
::ffff:127.0.0.1:51374: request
  -> HTTP protocol error in client request: Bad HTTP request line: b'\x05\x01\x00'
```

Trying to listen to music on http://myzcloud.me/album/1045126/yves-deruyter-2001-2001
