### ISSUE TITLE
Error when decode utf8 but the content is not utf8

### ISSUE THREAD

**Issue by WHK102** [mitmproxy/mitmproxy#3485]
Using mitmdump 4.0.4 when make a reverse proxy to google.cl says in request and try access to `flow.response.text` using a python3 script on `on_response` event:

```
Exception in thread ScriptThread:
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/mitmproxy/net/http/encoding.py", line 52, in decode
    decoded = custom_decode[encoding](encoded)
KeyError: 'UTF-8'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/mitmproxy/net/http/encoding.py", line 54, in decode
    decoded = codecs.decode(encoded, encoding, errors)
  File "/usr/lib/python3.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 280: invalid start byte

During handling of the above exception, another exception occurred: ...
```

How to ignore and drop the conflicted bytes?, in python3 using `''.decode(errors='ignore')` but in the `mitmproxy/net/http/encoding.py` use a custom decoder: `custom_decode[encoding](encoded)`.

Please, add the ignore error when exception is found.

**Comment by WHK102** [comment]
Works fine replacing:

`decoded = codecs.decode(encoded, encoding, errors)`

By:

`decoded = codecs.decode(encoded, encoding, errors='ignore')`

In mitmproxy/net/http/encoding.py:54

**Comment by rjt-gupta** [comment]
@WHK102 Hi! Thanks for the report :)
 Would you mind submitting a PR?

**Comment by WHK102** [comment]
What is a PR?

**Comment by kajojify** [comment]
@WHK102 pull request :)
