### ISSUE TITLE
Unable get the real hostname from request in a python script

### ISSUE THREAD

**Issue by WHK102** [mitmproxy/mitmproxy#3488]
It is very simple: Need get the current host request from host header using a python script and mitmdump as reverse proxy.

The `flow.request.data.host` can set the custom header, but need get the real host request from web browser using the same server ip address.

In the Apache settings i can make a virtual host with separated settings by hostname and port, but the mitmproxy can not get the real hostname.

I try get this using:

```
flow.request.get_state()
flow.request.data
flow.request.headers.get('host')
flow.request.host
```
But, the data is a empty byte, the state show the ip address but no the hostname.

How to get the raw request binary data to get the real hostname using a regular expression?

The modify of the header host is a big bad idea.

**Comment by mhils** [comment]
See https://docs.mitmproxy.org/stable/api/mitmproxy/http.html#Request.pretty_host.

**Comment by WHK102** [comment]
`pretty_host` gets the setted hostname by mitmproxy but is not the real host header value in original request.
