### ISSUE TITLE
What is mitmproxy doing under the hood to be able to fix my issue?

### ISSUE THREAD

**Issue by ghost** [mitmproxy/mitmproxy#3493]
I am working on a web automation application, and it seems that the request endpoint is protected by Akamai. Whenever I tunnel the proxy through mitm, it runs perfect. However as soon as mitm is off, I get a Forbidden (403) error. I'm using C#.

##### Steps to reproduce the problem:

1. Find an Akamai protected endpoint.
2. Submit a request to it with legit cookies and no proxy (won't work)
3. Submit a request to it with the same cookies/headers but through mitmproxy (and it'll work)

##### Any other comments? What have you tried so far?

This is not a mitm issue per se, but I wanted to find out what does mitm do under the hood in order to fix my issue, so I could replicate it and make it work without mitm as well.

I'm sending the same exact request (same cookies, headers, data). I even tried using mitm's CA certificate with my request.

##### System information

Mitmproxy: 4.0.4 binary
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-10-10.0.17134

Thank you so much.

**Comment by jineshqa** [comment]
@b0zhidar Change your wifi settings to not proxy if mitmproxy is not running.

**Comment by b0zhidar** [comment]
> @b0zhidar Change your wifi settings to not proxy if mitmproxy is not running.

I'm not setting my system proxy settings at all, only tunneling my requests through mitm. I can access the internet just fine and send requests to other servers with no problem.

**Comment by jineshqa** [comment]
Hi @b0zhidar, how are you doing that without changing proxy settings on your OS?

**Comment by b0zhidar** [comment]
@jineshqa By setting the proxy property of my requests (https://docs.microsoft.com/en-us/dotnet/api/system.net.webproxy?view=netframework-4.7.2)

**Comment by arthurmoreno** [comment]
I am having the same issue here! Why this issue was closed without an answer?

**Comment by tokiakasu** [comment]
Same issue with golang. Is there any updates?
