### ISSUE TITLE
How to modify the server name indication(sni) ?

### ISSUE THREAD

**Issue by wangkuncaixu** [mitmproxy/mitmproxy#3494]
##### Steps to reproduce the problem:

I am now using the mitmproxy to bypass the firewall. I want to remove the sni in the clienthello message of the TLS handshake. Can I use the mitmproxy to modify or remove the sni?

**Comment by j4s0nmo0n** [comment]
Have you heard about ESNI, with TLS1.3? there's a IETF Draft about it: https://github.com/tlswg/draft-ietf-tls-esni

**Comment by ghuser** [comment]
No matter what the use is I would this would be a nice feature for checking how servers behave on unexpected SNI values.

**Comment by BkPHcgQL3V** [comment]
Not sure if this does what you want, but it might help. In a script you can do this:
```python
def next_layer(next_layer):
    if isinstance(next_layer, TlsLayer):
        if next_layer.server_conn.address[0] == _redirect_source:
            next_layer._custom_server_sni = _redirect_target
```

**Comment by mhils** [comment]
You can now set `flow.server_conn.sni` in the server_connect hook on master!
