### ISSUE TITLE
In upstream mode not sending auth when I run resend

### ISSUE THREAD

**Issue by nemanjan00** [mitmproxy/mitmproxy#3499]
##### Steps to reproduce the problem:

1. Run mitmproxy in upstream mode with auth
2. Send request from browser configured to use mirmproxy
3. Resend that request

##### System information

Mitmproxy: 4.0.4
Python:    3.7.2
OpenSSL:   OpenSSL 1.1.1b  26 Feb 2019
Platform:  Linux-5.0.2-zen1-1-zen-x86_64-with-arch

**Comment by mhils** [comment]
I can't reproduce this. If this issue still exists, please open a new issue with clearer steps :)
