### ISSUE TITLE
how to get entire raw request and response

### ISSUE THREAD

**Issue by Lucifer1993** [mitmproxy/mitmproxy#3500]
Hello, how to use mitmproxy get entire requests and response like with python3:

POST /sample.jsp HTTP/1.1
Accept:image/gif.image/jpeg,*/*
Accept-Language:zh-cn
Connection:Keep-Alive
Host:localhost
User-Agent:Mozila/4.0(compatible;MSIE5.01;Window NT5.0)
Accept-Encoding:gzip,deflate
 
username=jinqiao&password=1234

**Comment by mhils** [comment]
Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!
