### ISSUE TITLE
Transparent Proxy not catching any requests

### ISSUE THREAD

**Issue by vunhatminh241191** [mitmproxy/mitmproxy#3503]
I have 2 machines (A and B), which can talk directly with each other because they are in the same VLAN. I put my proxy in B, where I have a simple docker container running (ports 8070 and 8448). I put my transparent proxy in front of these port numbers because I want to catch the network traffic through this port. I also config my iptable to listen to any incoming package comes to these ports and forwarding to my proxy. However, when I do the request from A to B, it goes direct to my docker container's port instead of forwarding it to my proxy. Does anyone have ideas about what is going on?

##### Steps to reproduce the problem:

1. Follow these step https://docs.mitmproxy.org/stable/howto-transparent/
2. mitmproy --m transparent -p $PORTNUMBER

##### Any other comments? What have you tried so far?
I tried to use "traceroute" but I can't get anything.

##### System information
Mitmproxy: 4.0.4
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by mhils** [comment]
Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!
