### ISSUE TITLE
Hide the fact that mitmproxy is being used

### ISSUE THREAD

**Issue by localhostdotdev** [mitmproxy/mitmproxy#3505]
##### Steps to reproduce the problem:

1. Go to "https://google.com"
2. See "captcha" / "We are sorry" page

##### Any other comments? What have you tried so far?

reCaptcha doesn't work when using mitmproxy too so no way to escape that with the default config. (I'm already disabling HTTP/2)

##### System information

```
Mitmproxy: 4.0.4
Python:    3.7.2
OpenSSL:   OpenSSL 1.0.2q  20 Nov 2018
Platform:  Darwin-17.7.0-x86_64-i386-64bit
```

I'm guessing this is based on TLS cyphers signatures like caddy does.

**Comment by mhils** [comment]
I can access google.com through mitmproxy just fine. I suppose that problem is due to your network activity.

**Comment by RestOp** [comment]
Hello,

is is really so

![image](https://user-images.githubusercontent.com/46259141/173208734-fc7ccc42-f023-4454-9de3-7c05db185179.png)

withour mitmproxy everything works fine
