### ISSUE TITLE
"If you can see this, traffic is not passing through mitmproxy."

### ISSUE THREAD

**Issue by knlr** [mitmproxy/mitmproxy#3513]
I'm reaching the actual site and I can see the request to mitm.it in the flows window. It does not appear to be intercepted. Other requests also appear in the flows window, so my traffic is clearly passing through mitmproxy.

##### Steps to reproduce the problem:

1. visit http://mitm.it from the proxy'd browser

##### Any other comments? What have you tried so far?

`rm -rf ~/.mitmproxy` didn't help

##### System information

Mitmproxy: 4.0.4
Python:    3.7.3
OpenSSL:   OpenSSL 1.0.2r  26 Feb 2019
Platform:  Darwin-18.5.0-x86_64-i386-64bit

**Comment by yan12125** [comment]
Let me guess. Are you using mitmproxy from MacPorts?

**Comment by knlr** [comment]
yes, I am.

**Comment by yan12125** [comment]
Got it - sorry for the inconvenience. I disabled the plugin that handles mitm.im in https://github.com/macports/macports-ports/commit/5cffb2c8a0334c4c98ac5461948185dbb8f672ad. The reason behind that commit is that Tornado is upgraded to 6.x in MacPorts, but the onboarding plugin is not compatible with Tornado 6.x yet. For now you'll need to install certificates on clients manually.

**Comment by knlr** [comment]
ok thanks. I'll install it through homebrew then

**Comment by mhils** [comment]
@yan12125: Is there any way you can ship mitmproxy without disabling builtin features? This ultimately  ends in support requests and confused users, which takes our time.

**Comment by yan12125** [comment]
Sorry for adding troubles. I asked the maintainer of tornado in MacPorts if it's fine to revert to 5.x: https://trac.macports.org/ticket/58343#ticket.

**Comment by yan12125** [comment]
I proposed to revert tornado in MacPorts to 5.x to allow the onboarding plugin to work again [1], but the maintainer of tornado is "not sure that's a good decision to revert tornado to old version". Is it possible to fix the onboarding plugin for tornado 6.x compatibility?

[1] https://github.com/macports/macports-ports/pull/4086
[2] https://github.com/macports/macports-ports/pull/4086#issuecomment-484425144

**Comment by yan12125** [comment]
Finally, the patch using Tornado 5.x is merged. Tornado 5.x is not enabled by default for MacPorts users. Instead, there's a note telling users that they can enable the onboarding app with the `+onboardingapp` flag during installation.

**Comment by vimaldhana** [comment]
Hi All,

I'm a beginner to this work, trying to set up mitmproxy , installed Mitmproxy in raspberry pi when I try to run mitm.it 
errors: traffic is not passing through mitmproxy
Can anyone help to resolve this issue please

**Comment by htdcander** [comment]
me too

```bash
[root@cander ~]# mitmdump --version
Mitmproxy: 4.0.4
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-5.3.7-301.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
```
