### ISSUE TITLE
how to  fake response and reply immediately in request function instead of kill flow?

### ISSUE THREAD

**Issue by OldTiger** [mitmproxy/mitmproxy#3514]
Description: I have tried [Return custom response with mitmproxy](https://stackoverflow.com/questions/34677062/return-custom-response-with-mitmproxy) 
But met error because flow.reply is not callable

**Comment by mhils** [comment]
The examples in the Stackoverflow post are outdated. Please refer to our scripting documentation and examples on docs.mitmproxy.org.
