### ISSUE TITLE
error: can't start new thread

### ISSUE THREAD

**Issue by yxksabri** [mitmproxy/mitmproxy#3520]
Error in processing of request from 127.0.0.1:21893
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\netlib\tcp.py", line 951, in serve_forever
    t.start()
  File "c:\python27\lib\threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

**Comment by kajojify** [comment]
Hello! :) 
Thanks for the report. 
1. It seems you use the old version of Python, which we don't support (Python 2.7).
2. What exactly are you trying to do? What goes wrong?

Please, reopen and provide more details if needed.
