### ISSUE TITLE
library not found for -lstdc++

### ISSUE THREAD

**Issue by youran1024** [mitmproxy/mitmproxy#3521]
##### Steps to reproduce the problem:
pip3 install mitmproxy

##### System information

 clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mhils** [comment]
https://docs.mitmproxy.org/stable/overview-installation/
