### ISSUE TITLE
Script API doc for release version

### ISSUE THREAD

**Issue by mikesxf** [mitmproxy/mitmproxy#3523]
##### Any other comments? What have you tried so far?
I’m using mitmproxy to capture traffic with my own script (officially called addon). But I can’t find the detailed API doc on web docs (https://docs.mitmproxy.org/archive/v3/addons-overview/) like before (v2 or older version). It is said that I can use command pydoc mitmproxy.http to get the doc. But it can’t work as I’m using the release version I think.
Is there any way to get the detailed script API doc when using release version? Thanks!

##### System information

mitmproxy-3.0.4-linux  release version

**Comment by mhils** [comment]
You can find documentation for older versions at https://mitmproxy.readthedocs.io/. That being said, we don't support any old releases.

Regarding your comment concerning "release version": The latest release is 4.0.4, docs for that are on the website.

**Comment by mikesxf** [comment]
Sorry I still not find the detailed API of script for v3 or v4 like the picture (picture is for v2)
![image](https://user-images.githubusercontent.com/20496884/56131450-03928300-5fba-11e9-986e-11ce9646dcb2.png)
I notice that v4 requires python3.6 and I think it has a little trouble to change my environment, so I choose the v3.

**Comment by mikesxf** [comment]
about the detailed API doc, e.g. , if I want to get server ip of http request in script, I'm not sure which is right, `req.ip` or `rep.server_ip`? I'm sorry I  have not found the info on the website so far.
