### ISSUE TITLE
datetime.fromtimestamp

### ISSUE THREAD

**Issue by Shnitzelil** [mitmproxy/mitmproxy#3524]
##### Steps to reproduce the problem:

1. Create addon that import datetime
2. date should be value lower than 86400
3. datetime.fromtimestamp(date)

##### Any other comments? What have you tried so far?
Just change the value to 86400

The [issue comes from python sdk](https://bugs.python.org/issue29097), to solve this mitmproxy must upgrade to python 3.7 or later

##### System information

4.0.4

**Comment by mhils** [comment]
Please use the mitmproxy forums (https://discourse.mitmproxy.org/) for support/how-to questions. Thanks!

**Comment by Shnitzelil** [comment]
@mhils 
It seems to me that there is a problem.
Anyway, I creating [new topic in the forum](https://discourse.mitmproxy.org/t/upgrading-python-sdk/1508)
Regards,
