### ISSUE TITLE
Mitmproxy can't import other Module

### ISSUE THREAD

**Issue by Alennnnnn** [mitmproxy/mitmproxy#3527]
##### Steps to reproduce the problem:

1.i install mitmproxy and mitmproxy.exe
2. mitmdump -s“a.py”
3.mitmproxy remind me [ in script E:\Workspace\Python\CaidaoMitmProxy\CaidaoMP.py: No module named 'pyDes']
![](https://i.imgur.com/AyJe91Q.png)

##### Any other comments? What have you tried so far?
Nothing

##### System information
Mitmproxy Version:4.0.4
Operating System: Windows 10

**Comment by Alennnnnn** [comment]
I am very sure I installed the pyDes Module in my python

**Comment by selfcac** [comment]
I read in some other issue that the compiled version for Windows have a closed environment python.

I solved by installing from python 3 pip:
`pip(3) install mitmproxy`

And then run the command:
`"C:\Users\{USER}\AppData\Local\Programs\Python\Python37-32\Scripts\mitmdump.exe"`

**Comment by Alennnnnn** [comment]
> I read in some other issue that the compiled version for Windows have a closed environment python.
> 
> I solved by installing from python 3 pip:
> `pip(3) install mitmproxy`
> 
> And then run the command:
> `"C:\Users\{USER}\AppData\Local\Programs\Python\Python37-32\Scripts\mitmdump.exe"`

Is work! Thank you very much
