### ISSUE TITLE
Ignore all domains, except 2

### ISSUE THREAD

**Issue by Fredus69** [mitmproxy/mitmproxy#3528]
Hello,
I am using mitmdump version 4.0.4 for linux.

I want to ignore every domain from mitmproxy'mechanisms interception HTTPS except 2 in particular (site1.site.com & example.com) in transparent mode.

I followed doc here : https://docs.mitmproxy.org/stable/howto-ignoredomains/

So i put this command  :
`mitmdump -v --ignore-hosts '^(?!site1\.site\.com)(?!example\.com)' --mode transparent -p 1337`

In logs of connexion, Every domains are intercepted by mitmdump, and not only the 2 excepts i put in my command (site1.site.com & example.com)  :(

I probably made a mistake, but after a lots of tries, i cannot figure out where is it.

Thanks for your help,

Regards

Fred

**Comment by mhils** [comment]
You should be able to use `allow_hosts` for this now! :)
