### ISSUE TITLE
mitmdump not running in docker container

### ISSUE THREAD

**Issue by adr-arroyo** [mitmproxy/mitmproxy#3529]
##### Steps to reproduce the problem:

1. Created the following dockerfile:

```
FROM mitmproxy/mitmproxy:latest

RUN mkdir data_tampering
WORKDIR /home/$USER/data_tampering
COPY ./modify_content.py .


EXPOSE 80:80
EXPOSE 8080:8080

ENTRYPOINT ["mitmdump --mode transparent -s ./modify_content.py"]
```

2. Build image by: `docker build . -t mitmdump_tampering`
3. RUN image with: `docker run -it mitmdump_tampering:latest` resulting in:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"mitmdump --mode transparent -s ./modify_content.py\": stat mitmdump --mode transparent -s ./modify_content.py: no such file or directory": unknown.

##### Any other comments? What have you tried so far?
I have iteratively run the container (with `docker run -it mitmdump_tampering /bin/bash`) without the ENTRYPOINT and mitmdump runs successfully with the python script INSIDE the container. However, if I directly run the container from the host, i get the error above. I cannot see the reason for this

##### System information

Mitmproxy: 4.0.4
Python:    3.6.7
OpenSSL:   OpenSSL 1.1.0g  2 Nov 2017
Platform:  Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by adr-arroyo** [comment]
Resolved with modification of ENTRYPOINT format to:

`ENTRYPOINT ["/usr/bin/mitmdump", "--mode", "transparent", "-s", "./modify_content.py"]`

**Comment by michalrubaj** [comment]
Hey Adrian,

I've got a question.  I am facing similar issue but when I run image I have an error 

> /usr/bin/mitmproxy: No such script

Which directory you put your python script in?

**Comment by adr-arroyo** [comment]
Hello @michaeljau 

If you look at the line:

```
COPY ./modify_content.py .
```

The script is copied in the current directory, which is given by the line: 

```
WORKDIR /home/$USER/data_tampering
```

Cheers

**Comment by LaumiH** [comment]
I just found this issue and it made me very happy, as I have been trying to get transparent mode with mitmdump in docker working for days.
However if I run the container on my local machine it gives me `Failed to connect to localhost port 8080: connection refused` and I cannot see why.
How did you the proceed to get the proxy working?

**Comment by adr-arroyo** [comment]
Hello @LaumiH 
How is your docker run command? It might be possible that you need to open the ports, or use the host's network with `--network host`

**Comment by LaumiH** [comment]
Hey, thanks for answering!
I tried with `--network host` and got a `Transparent mode failure: FileNotFoundError(2, 'No such file or directory')` error. I don't know how to debug this.
I run it with the command you also ran.

What exactly do you mean by opening ports? 8080 on my host? I cannot even see the docker process with `ss -tnlp`.

When I run docker from command line, `sudo docker run --rm -it -v ~/.mitmproxy:/home/mitmproxy/.mitmproxy -p 8080:8080 mitmproxy/mitmproxy:latest -- mitmdump`, I can see the traffic, but when I try to execute it with `--set mode=transparent` I get the above FileNotFound.

**Comment by adr-arroyo** [comment]
Hi,

I am afraid I cannot help you with the `FileNotFoundError`, I have not come across it.

Are you providing an script with `"-s"` option?

Maybe you can check this [tutorial](https://docs.mitmproxy.org/stable/howto-transparent/).

Regards.
