### ISSUE TITLE
Server replay errors

### ISSUE THREAD

**Issue by yonixw** [mitmproxy/mitmproxy#3534]
##### Steps to reproduce the problem:

1. Use '-w' option to save to file
2. Use '-S' option to read file as server replay
3. I  am using addons, might be related?

##### Any other comments? What have you tried so far?

```
Addon error: Traceback (most recent call last):
  File "c:\users\yoni\appdata\local\programs\python\python37-32\lib\site-packages\mitmproxy\addons\serverplayback.py", line 183, in request
    response.refresh()
  File "c:\users\yoni\appdata\local\programs\python\python37-32\lib\site-packages\mitmproxy\net\http\response.py", line 178, in refresh
    delta = now - self.timestamp_start
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

The line in question:
[https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/mitmproxy/net/http/response.py#L178](https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/mitmproxy/net/http/response.py#L178)

If i add "return" at the start of Response\refresh() replay is being playing back OK. (Obviously not refreshed)

##### System information

Mitmproxy: 4.0.4
Python:    3.7.1
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-10-10.0.17134-SP0

**Comment by mhils** [comment]
I can't reproduce this, `timestamp_start` really should always be set. If it isn't, please file a new issue with clear steps. :)
