### ISSUE TITLE
Can't hide logs from the python script

### ISSUE THREAD

**Issue by AyoubMarouan** [mitmproxy/mitmproxy#3535]
```
import logging

logging.basicConfig(level=logging.CRITICAL)
#logging.basicConfig(level=logging.INFO)

debugVar = ""

class AddHeader:
    def log(self , *mdg ):
        return ""
    
    def request(self, flow):
            debugVar = flow.request.url
            ctx.log( "\n\n\n {} \n\n\n\n".format( debugVar )  )

def start():
    myaddon = AddHeader()
    opts = options.Options(listen_host='192.168.1.16', listen_port=8080)
    pconf = proxy.config.ProxyConfig(opts)
    m = DumpMaster(opts)
    m.server = proxy.server.ProxyServer(pconf)
    m.addons.add(myaddon)

    try:
        m.run()
    except KeyboardInterrupt:
        m.shutdown()

start()
```

I can't hide all the logs, i just want to show the debug from the addons i have added, i didn't find any solution in the documentation or anythings else

**Comment by franga2000** [comment]
Any news on this? I'm having the same problem

**Comment by younesslam** [comment]
use -q, --quiet command line option

for example : 

mitmdump -s ./script.py -q

**Comment by B1ank-H** [comment]
> ```
> import logging
> 
> logging.basicConfig(level=logging.CRITICAL)
> #logging.basicConfig(level=logging.INFO)
> 
> debugVar = ""
> 
> class AddHeader:
>     def log(self , *mdg ):
>         return ""
>     
>     def request(self, flow):
>             debugVar = flow.request.url
>             ctx.log( "\n\n\n {} \n\n\n\n".format( debugVar )  )
> 
> def start():
>     myaddon = AddHeader()
>     opts = options.Options(listen_host='192.168.1.16', listen_port=8080)
>     pconf = proxy.config.ProxyConfig(opts)
>     m = DumpMaster(opts)
>     m.server = proxy.server.ProxyServer(pconf)
>     m.addons.add(myaddon)
> 
>     try:
>         m.run()
>     except KeyboardInterrupt:
>         m.shutdown()
> 
> start()
> ```
> 
> I can't hide all the logs, i just want to show the debug from the addons i have added, i didn't find any solution in the documentation or anythings else

Add the following function maybe help you
```
from mitmproxy import ctx 
...

def load():
    ctx.options.flow_detail = 0
def response():
    ...
def request():
    ...
```
