### ISSUE TITLE
Force ALPN selection to h2 with upstream_cert=false

### ISSUE THREAD

**Issue by tarekziade** [mitmproxy/mitmproxy#3536]
##### Steps to reproduce the problem:

1. Replay an http/2 recorded playback file
2. use the upstream_cert=false option to avoid calling the upstream server
3. downgraded to http/1

From my current investigation in the code it could be as simple as added a script callback
in __alpn_select_callback in the mitmproxy/proxy/protocol/tls.py module but I am not 100% 
sure that's the right fix.

Investigating on this, any hint appreciated

**Comment by tarekziade** [comment]
I ended up wrapping OpenSSL.SSL.Connection so it does not use its underlying socket and give all the answers we want via get_peer_certificate() and get_alpn_proto_negotiated() but it's very hackish. Not sure if that's the right approach

**Comment by mhils** [comment]
From https://discourse.mitmproxy.org/t/possible-to-playback-http-2-with-upstream-cert-sniffing-disabled-upstream-cert-false/1394:

> This is a tricky problem we currently don’t have a good answer for. We currently don’t do HTTP/2 <-> HTTP/1 translation, so when we negotiate HTTP/2 with the client we kind of need to make sure that the server supports it as well (as we can’t determine if a replay will happen at this point).
One viable approach might be to provide some form of ALPN callback to the scripting interface, but we haven’t implemented anything of that sort yet.
> 
> If you really really do need HTTP/2, one viable workaround might be to put mitmproxy into upstream/reverse proxy mode and point to some dummy server running on the same machine that advertises h2. This will trick mitmproxy into thinking that upstream does support it.

The most relevant bits are here: https://github.com/mitmproxy/mitmproxy/blob/6f893a83c090f049e7cebe3335e7a2a32695946b/mitmproxy/proxy/protocol/tls.py#L335-L350

The simple approach would be to just monkeypatch `alpn_for_client_connection` from an addon, the more long-term approach would be to add a custom event (https://docs.mitmproxy.org/stable/addons-events/) which allows users to manually override the ALPN specification.

**Comment by tarekziade** [comment]
Monkey patching those 2 function is not working because the proxy will still try to initiate a connection to the upstream server in the http2 layer via the tls class in http.handle_regular_connect()


```
Traceback (most recent call last):
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/modes/http_proxy.py", line 9, in __call__
    layer()
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 188, in __call__
    if not self._process_flow(flow):
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 260, in _process_flow
    return self.handle_regular_connect(f)
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 206, in handle_regular_connect
    layer()
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 286, in __call__
    layer()
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 327, in __call__
    self._initiate_server_conn()
  File "/private/tmp/ok/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http2.py", line 112, in _initiate_server_conn
    self.connections[self.server_conn].initiate_connection()
KeyError: <ServerConnection: www.bing.com:443>
```

(in record or playback mode)

**Comment by mhils** [comment]
Ah, yes. That's not easily patched out. 

> I am also trying to do the local http/2 server but I fail to understand your proposed solution. (upstream/reverse)
> I am not exactly sure what you mean, by that. Would you mind giving me an example of an mitmproxy running in that mode?

1. You run an HTTP/2 server on localhost:1234 (e.g. https://github.com/GoogleChromeLabs/simplehttp2server or caddy)
2. You point mitmproxy to it: `mitmproxy --mode reverse:https:/localhost:1234` (see https://docs.mitmproxy.org/stable/concepts-modes/#reverse-proxy)
3. mitmproxy should now negotiate TLS with your local server, and replay can be applied.

**Comment by tarekziade** [comment]
Let's say I have a record dump with http/2 pages from example.com

When I set up mitmproxy as a reverse proxy on playback mode, with a dummy local h2 server,
mitmproxy with forward the requests correcly to the local h2 server and I can negotiate h2 no problem.
But mitmproxy will never play back my recorded queries, probably because there's a host mismatch.

If I use example.com as the host, mitmproxy will reject any CONNECT request (this is explicitely done in the code in reverse proxy mode) -- so I am not sure how I can use mitmproxy in reverse mode with a playback file.

Do I need to change the host name in flight in an addon ?

**Comment by tarekziade** [comment]
After more patching in mitmproxy (I used 2.0.2 but I think 4.0.4 is close in that area) I got it working.

I needed to:

- patch tls.TlsLayer.alpn_for_client_connection (we knew that)
- activate no_upstream_cert
- patch proxy.protocol.Http2Layer._initiate_server_conn in order to ignore the server connection in case it's not connected and not in self.connections
- patch all self._handle_XXX function that are doing something with the server

That's a lot of patching obviously, and I think we can make the http2 protocol layer a little smarter about what to do when the client picks h2 and we don't want to get the upstream cert

I will push here the whole patch for the record, I guess that's a good basis to make the http2 layer smarter about this

**Comment by tarekziade** [comment]
This is what I have @mhils   

```python
from mitmproxy.proxy.protocol import tls
from mitmproxy.proxy.protocol.http2 import Http2Layer


@property
def _alpn(self):
    if "bing.com" in self.server_sni:
        print("Forcing HTTP/2 on %s" % self.server_sni)
        return b"h2"
    return b""


tls.TlsLayer.alpn_for_client_connection = _alpn


def _server_conn(self):
    if not self.server_conn.connected() and self.server_conn not in self.connections:
        print("Ignored CONNECT call on upstream server")
        return
    if self.server_conn.connected():
        config = h2.config.H2Configuration(
            client_side=True,
            header_encoding=False,
            validate_outbound_headers=False,
            validate_inbound_headers=False,
        )
        self.connections[self.server_conn] = SafeH2Connection(
            self.server_conn, config=config
        )
    self.connections[self.server_conn].initiate_connection()
    self.server_conn.send(self.connections[self.server_conn].data_to_send())


Http2Layer._initiate_server_conn = _server_conn


def _remote_settings_changed(self, event, other_conn):
    if other_conn not in self.connections:
        print("Ignored remote settings upstream")
        return True
    new_settings = dict(
        [(key, cs.new_value) for (key, cs) in event.changed_settings.items()]
    )
    self.connections[other_conn].safe_update_settings(new_settings)
    return True


Http2Layer._handle_remote_settings_changed = _remote_settings_changed
```

**Comment by mhils** [comment]
This should be fixed on master. If that's not the case, please open a new issue!
