### ISSUE TITLE
pip3 install mitmproxy error

### ISSUE THREAD

**Issue by suanping** [mitmproxy/mitmproxy#3537]
##### Steps to reproduce the problem:

1. python3.7 version
2. pip3 install mitmproxy
3. any suggestion ?

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>pip3 install mitmproxy
Collecting mitmproxy
  Using cached https://files.pythonhosted.org/packages/e5/6c/fe3f4b4cbef7f703b11
99d5443963c4c56c2182223375bdaf0930e1ad052/mitmproxy-4.0.4-py3-none-any.whl
Requirement already satisfied: kaitaistruct<0.9,>=0.7 in d:\python37\lib\site-pa
ckages (from mitmproxy) (0.8)
Requirement already satisfied: hyperframe<6,>=5.1.0 in d:\python37\lib\site-pack
ages (from mitmproxy) (5.2.0)
Requirement already satisfied: blinker<1.5,>=1.4 in d:\python37\lib\site-package
s (from mitmproxy) (1.4)
Requirement already satisfied: pyOpenSSL<18.1,>=17.5 in d:\python37\lib\site-pac
kages (from mitmproxy) (18.0.0)
Requirement already satisfied: wsproto<0.12.0,>=0.11.0 in d:\python37\lib\site-p
ackages (from mitmproxy) (0.11.0)
Requirement already satisfied: urwid<2.1,>=2.0.1 in d:\python37\lib\site-package
s (from mitmproxy) (2.0.1)
Requirement already satisfied: h2<4,>=3.0.1 in d:\python37\lib\site-packages (fr
om mitmproxy) (3.1.0)
Requirement already satisfied: certifi>=2015.11.20.1 in d:\python37\lib\site-pac
kages (from mitmproxy) (2019.3.9)
Requirement already satisfied: pyperclip<1.7,>=1.6.0 in d:\python37\lib\site-pac
kages (from mitmproxy) (1.6.5)
Requirement already satisfied: pyparsing<2.3,>=2.1.3 in d:\python37\lib\site-pac
kages (from mitmproxy) (2.2.2)
Requirement already satisfied: cryptography<2.4,>=2.1.4 in d:\python37\lib\site-
packages (from mitmproxy) (2.3.1)
Requirement already satisfied: click<7,>=6.2 in d:\python37\lib\site-packages (f
rom mitmproxy) (6.7)
Requirement already satisfied: passlib<1.8,>=1.6.5 in d:\python37\lib\site-packa
ges (from mitmproxy) (1.7.1)
Requirement already satisfied: pyasn1<0.5,>=0.3.1 in d:\python37\lib\site-packag
es (from mitmproxy) (0.4.5)
Requirement already satisfied: ruamel.yaml<0.16,>=0.13.2 in d:\python37\lib\site
-packages (from mitmproxy) (0.15.94)
Requirement already satisfied: pydivert<2.2,>=2.0.3; sys_platform == "win32" in
d:\python37\lib\site-packages (from mitmproxy) (2.1.0)
Requirement already satisfied: sortedcontainers<2.1,>=1.5.4 in d:\python37\lib\s
ite-packages (from mitmproxy) (2.0.5)
Requirement already satisfied: tornado<5.2,>=4.3 in d:\python37\lib\site-package
s (from mitmproxy) (5.1.1)
Requirement already satisfied: ldap3<2.6,>=2.5 in d:\python37\lib\site-packages
(from mitmproxy) (2.5.2)
Collecting brotlipy<0.8,>=0.7.0 (from mitmproxy)
  Using cached https://files.pythonhosted.org/packages/d9/91/bc79b88590e4f662bd4
0a55a2b6beb0f15da4726732efec5aa5a3763d856/brotlipy-0.7.0.tar.gz
Requirement already satisfied: six>=1.5.2 in d:\python37\lib\site-packages (from
 pyOpenSSL<18.1,>=17.5->mitmproxy) (1.12.0)
Requirement already satisfied: h11~=0.7.0 in d:\python37\lib\site-packages (from
 wsproto<0.12.0,>=0.11.0->mitmproxy) (0.7.0)
Requirement already satisfied: hpack<4,>=2.3 in d:\python37\lib\site-packages (f
rom h2<4,>=3.0.1->mitmproxy) (3.0.0)
Requirement already satisfied: asn1crypto>=0.21.0 in d:\python37\lib\site-packag
es (from cryptography<2.4,>=2.1.4->mitmproxy) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in d:\python37\lib\site-packag
es (from cryptography<2.4,>=2.1.4->mitmproxy) (1.12.3)
Requirement already satisfied: idna>=2.1 in d:\python37\lib\site-packages (from
cryptography<2.4,>=2.1.4->mitmproxy) (2.8)
Requirement already satisfied: pycparser in d:\python37\lib\site-packages (from
cffi!=1.11.3,>=1.7->cryptography<2.4,>=2.1.4->mitmproxy) (2.19)
Installing collected packages: brotlipy, mitmproxy
  Running setup.py install for brotlipy ... error
    ERROR: Complete output from command 'd:\python37\python.exe' -u -c 'import s
etuptools, tokenize;__file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip
-install-jafsrcn7\\brotlipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', o
pen)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exe
c(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\
AppData\Local\Temp\pip-record-jrk8bsc0\install-record.txt' --single-version-exte
rnally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\brotli
    copying src\brotli\brotli.py -> build\lib.win-amd64-3.7\brotli
    copying src\brotli\build.py -> build\lib.win-amd64-3.7\brotli
    copying src\brotli\__init__.py -> build\lib.win-amd64-3.7\brotli
    running build_clib
    building 'libbrotli' library
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\libbrotli
    creating build\temp.win-amd64-3.7\libbrotli\common
    creating build\temp.win-amd64-3.7\libbrotli\dec
    creating build\temp.win-amd64-3.7\libbrotli\enc
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC
\14.20.27508\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilibbro
tli/include -Ilibbrotli/ -Isrc/brotli "-IC:\Program Files (x86)\Microsoft Visual
 Studio\2019\BuildTools\VC\Tools\MSVC\14.20.27508\include" "-IC:\Program Files (
x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tclibbrotli/common/dictionary.c /F
obuild\temp.win-amd64-3.7\libbrotli/common/dictionary.obj
    dictionary.c
    libbrotli/include\brotli/types.h(15): fatal error C1083: 无法打开包括文件:
“stddef.h”: No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Buil
dTools\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x64\\cl.exe' failed with exi
t status 2
    ----------------------------------------
ERROR: Command "'d:\python37\python.exe' -u -c 'import setuptools, tokenize;__fi
le__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-jafsrcn7\\brotl
ipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.re
ad().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__
, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-r
ecord-jrk8bsc0\install-record.txt' --single-version-externally-managed --compile
" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-j
afsrcn7\brotlipy\

**Comment by gulyayko** [comment]
Faced the same problem, tried most of tips from net, nothing helped. Finally the installation of Microsoft Visual C++ Compiler for Python 2.7 helped. https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

**Comment by nikhil1699** [comment]
If you are using their installation guide, try this instead of pip3 install 
I will copy some content from their Readme

To get started hacking on mitmproxy, please follow the advanced installation steps to install mitmproxy from source, but stop right before running pip3 install mitmproxy. Instead, do the following:

git clone https://github.com/mitmproxy/mitmproxy.git
cd mitmproxy
./dev.sh  # "powershell .\dev.ps1" on Windows

This will create a **venv** and will install side dependencies too.

**Comment by blagawuga** [comment]
Hello, I faced the exact same issue and it's brotlipu that's failing to install. Before doing installing mitmproxy using pip, install brotlipy via pip and then install mitmproxy. It'll do a clean install.

**Comment by mhils** [comment]
https://docs.mitmproxy.org/stable/overview-installation/
