### ISSUE TITLE
TypeError: Object of type MultiDictView is not JSON serializable

### ISSUE THREAD

**Issue by binger1990** [mitmproxy/mitmproxy#3538]
##### Steps to reproduce the problem:
def request(self, flow: mitmproxy.http.HTTPFlow):
		ctx.log.info(flow.request.query)

#####addons.py
addons = [
    AdReport.AdReport()
]

#####Error:
![image](https://user-images.githubusercontent.com/6611445/57667416-f955ba00-7635-11e9-921f-3403c7e4b30f.png)
![image](https://user-images.githubusercontent.com/6611445/57667428-01155e80-7636-11e9-803e-2600b1087b36.png)

##### System information
python3.7.3

**Comment by mhils** [comment]
This looks like an issue in your addon, not a mitmproxy issue.
