### ISSUE TITLE
Deploy to kubrentes

### ISSUE THREAD

**Issue by botzill** [mitmproxy/mitmproxy#3543]
I'm trying to deploy mitmproxy to kubernetes using nginx-ingress. Did anyone try that, how it works? I somehow don't manage to get it to work.

**Comment by russell** [comment]
I have tested this and i think that it's not working due to the dns rebind protection https://github.com/mitmproxy/mitmproxy/pull/3243 though you could work around that if you have an IP address per mitmweb instance

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions. You can post the link to your question here so that people can follow up.

Thanks!
