### ISSUE TITLE
How to script mitm between to machines

### ISSUE THREAD

**Issue by qymspace1** [mitmproxy/mitmproxy#3546]
##### Steps to reproduce the problem:
I have no Problem. Just a question/ask for advice
Could you brilliant people please point on the right direction of how to achieve this:

Run a mitm proxy on my computer(Client) -> Intercept all requests -> Send all requests as text(Via email/chat) ->  Receive the message on my server(Server) which runs a second mitm proxy -> Text the message and pass it as a request to mitm proxy on Server to complete the request->Send response back as text(Email/Chat) back to Client

How can I script mitm proxy to achieve this?

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
