### ISSUE TITLE
support Wireshark extcap interface instead of current GUI

### ISSUE THREAD

**Issue by KOLANICH** [mitmproxy/mitmproxy#3548]
Wireshark has a feature called extcap. There is an `extcap` dir in Wireshark dir. In this dir binaries reside. These binaries have the same command line interface. Wireshark introspects their capabilities and configures and calls them via CLI. They output a pcap stream into the pipe they get as a CLI arg.

It may make sense to have a mode of mitmproxy, which doesn't start a web interface, but works like an extcap, but Wireshark is used as a visualizing and analysing app.

Here is an example of extcap: https://github.com/wireshark/wireshark/blob/master/doc/extcap_example.py

**Comment by muzuiget** [comment]
It look like you need mitmproxy export a PCAP file, so it can view with Wireshark?

**Comment by KOLANICH** [comment]
>It look like you need mitmproxy export a PCAP file, so it can view with Wireshark?

1. I don't really strongly need it, it is just nice feature to have.
2. extcap is not just exporting into a pcap file, but it is an interface allowing to configure live capture in Wireshark GUI and then pass pcap frames to Wireshark as theybare captured.

**Comment by mhils** [comment]
We don't and won't support PCAP export in the forseeable future as we are simply a few layers too high on the protocol stack for this. Sorry!
