### ISSUE TITLE
Main screen split view

### ISSUE THREAD

**Issue by acaetano** [mitmproxy/mitmproxy#3550]
This is not really a problem, but an enhancement.

mitmproxy's main screen lists the requests along with the response's status code. When you're pentesting, you need to take a look at each response, but you need to enter each one and switch to the response tab.

Now think about sifting through that when you have more than a thousand requests to check?

Would it be possible for the team to create a split view of the main screen where we can see the response of the highlighted request? I've created a (very ugly) mockup of my idea below.

[Sorry, couldn't upload it here](https://pasteboard.co/IgNjsQW.png), github might have some aesthetic bots to block it...

**Comment by mhils** [comment]
Hi! We already support this. You can cycle through layouts using `-` and then pressing `P` in the second view. 😃
