### ISSUE TITLE
mitmdump not seeing traffic

### ISSUE THREAD

**Issue by jdmevo123** [mitmproxy/mitmproxy#3555]
Im not seeing the traffic coming through with mitmdump. currently running latest version.

In the logs all i see is:

<ip>:65013: clientconnect
<ip>:65013: clientdisconnect
<ip>:65052: clientconnect
<ip>:65052: clientdisconnect
<ip>:65088: clientconnect
<ip>:65088: clientdisconnect
<ip>:65118: clientconnect
<ip>:65119: clientconnect
<ip>:65119: clientdisconnect
<ip>:65118: clientdisconnect
::ffff:<ip>:52695: Ping Received from server
  ->
::ffff:<ip>:52695: Pong Received from client
  ->
<ip>:65147: clientconnect
<ip>:65147: clientdisconnect
<ip>:65181: clientconnect
<ip>:65181: clientdisconnect
::ffff:<ip>:52695: Ping Received from server
  ->

**Comment by mhils** [comment]
This looks like an issue with your network configuration, not a mitmproxy bug.
