### ISSUE TITLE
HTTP protocol error in client request

### ISSUE THREAD

**Issue by amitbha** [mitmproxy/mitmproxy#3556]
##### Steps to reproduce the problem:
1. mitmdump running in linux.
2. cp ~/mitmproxy/mitmproxy-ca-cert.p12 to windows xp, and import into root cert.
3. run the app (weixin-windows, [download link](https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe)) in windows xp, set its proxy to mitmdump.
4. mitmdump print lots of errors like:
> 192.168.10.102:2245: CONNECT 14.215.158.119:80
> << HTTP protocol error in client request: Bad HTTP request line: b"\x16\xf1\x03\x00\xa1\x00\ ........
> 192.168.10.102:2245: clientdisconnect
5. the expected traffic to "mp.weixin.qq.com" never seen.

##### Any other comments? What have you tried so far?
Also tried Fiddler4 in windows, with "Decrypt HTTPS Traffic" enabled, worked as expect, no errors.

##### System information

```shell
# mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1b  26 Feb 2019
Platform:  Linux-4.18.20-1-MANJARO-x86_64-with-arch-Manjaro-Linu
```

**Comment by mhils** [comment]
This looks like SSLv2 to me, which we currently don't support.
