### ISSUE TITLE
Addon OptionsError is neither logged, nor does it stop mitmproxy

### ISSUE THREAD

**Issue by cventers** [mitmproxy/mitmproxy#3558]
##### Steps to reproduce the problem:

1. Following the master branch documentation here:

https://docs.mitmproxy.org/master/addons-options/

```
(venv) chase@turbotaz .../Stage/mitmproxy $ which mitmdump
/home/chase/Stage/mitmproxy/venv/bin/mitmdump
(venv) chase@turbotaz .../Stage/mitmproxy $ mitmdump -s ./examples/addons/options-configure.py --set addheader=1000
Loading script ./examples/addons/options-configure.py
Proxy server listening at http://*:8080
```

##### System information

Mitmproxy: 5.0.0.dev (+237, commit 8353f4a)
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-4.13.0-sabayon-x86_64-Intel-R-_Core-TM-_i5-6500_CPU_@_3.20GHz-with-gentoo-2.6

**Comment by mhils** [comment]
This should be fixed in mitmproxy 8! 😃
