### ISSUE TITLE
mitmproxy does not intercept all the traffic coming from my android device

### ISSUE THREAD

**Issue by yosradirgham** [mitmproxy/mitmproxy#3561]
##### Steps to reproduce the problem:

1. Install mitmproxy's CA on a rooted Android
2. open wireshark on the same device on which mitmproxy is running using `$ mitmproxy --ssl-insecure`
3. open an application to inspect its HTTPS traffic

##### Any other comments? 
I want to intercept the traffic coming from a specific app, when i first open this app, I can see that mitmproxy does intercept some dafa from it, however it doesn't not intercept all the traffic. Mitmproxy only intercepts https requests that the application sends automatically to update its content, but the https requests I send aren't intercepted by mitmproxy.

##### What have you tried so far?
1. I've rooted my android device
2. I've added the mitmproxy certificate to the root store on my android following these [steps](https://github.com/mitmproxy/mitmproxy/issues/2054#issuecomment-327735569)
3. I've tried to run mitmproxy in transparent mode following the steps from the documentation, and when I do, mitmproxy doesn't intercept anything at all.
4. I've used [ProxyDroid](
https://play.google.com/store/apps/details?id=org.proxydroid&hl=en) to force all the traffic to be redirected to mitmproxy. When I do this, Wireshark does intercept the requests that are sent to the server, but the server never responds, what I get instead is a 502 Bad Gateway message from the proxy. Since this enables me at least to intercept the request that the application sends to the proxy, I tried sending it on postman, and what I get is  `There was an error connecting to https://192.168.10.211/message.`

##### System information

This is my topology:
Android --> mitmproxy --> server

Android's version is : 6.0.1, it's IP address is `192.168.10.199`
Mitmproxy is running on Linux, it's IP address is `192.168.10.264`
Server's IP address is `192.168.10.211`

**Comment by mhils** [comment]
If your Android application explicitly does not consider your configured proxy, you have to run mitmproxy in transparent mode (or use a workaround such as ProxyDroid). The second issue you are having (502 Bad Gateway) needs more details. The body of that response should have more details. If the app embeds a client certificate, you have to set that in mitmproxy as well.
