### ISSUE TITLE
Get only hostname without intercepting the request 

### ISSUE THREAD

**Issue by Badranh** [mitmproxy/mitmproxy#3562]
Hello, I wanna to intercept the host name and based on the host name I wanna drop or continue the request ( I don't care about the content at all).

I have tried the example below:

```
from mitmproxy import http

def request(flow: http.HTTPFlow) -> None:
    print("sending request to"+ flow.request.pretty_host)

```

but I'm receiving an error: Cannot establish TLS with client so is there any way to achieve this without installing custom certs ?

**Comment by mhils** [comment]
For this you either want to look at the TLS Server Name Indication or the HTTP Host header for cleartext communication. Long story short, this is nothing mitmproxy really supports at the moment.
