### ISSUE TITLE
How to convert from HTTPS proxy to HTTP proxy

### ISSUE THREAD

**Issue by pauldraper** [mitmproxy/mitmproxy#3563]
How can I use MITM proxy as an HTTPS proxy in front of an HTTP proxy?

So `https_proxy=http://mitmproxy curl https://example.com` would CONNECT to mitmproxy, and mitmproxy would send a GET Host: example.com to a configured upstream server, which would send GET Host: example.com to example.com.

My current solution:

1. Regular mode

2. Disable HTTP2

3. Addon

```
def http_connect(flow):
    flow.request.host = <upstream_proxy_host>
    flow.request.port = <upsteam_proxy_port>
```

4. Disable mitmproxy SSL checks

5. Add SSL proxy upsteam.

Is there a better way?

**Comment by mhils** [comment]
This sounds like you want to use the upstream proxy mode and then just set the scheme to "http" instead of "https".

**Comment by hacker1024** [comment]
@mhils Upstream proxy mode does not do what the first post describes. CONNECT requests are sent to the upstream proxy, rather than mitproxy handling the TLS itself and only sending regular HTTP requests to the upstream proxy.
