### ISSUE TITLE
[QUESTION] HTTPS within script

### ISSUE THREAD

**Issue by loretoparisi** [mitmproxy/mitmproxy#3565]
Is it possibile to make an `HTTPS` call to a different endpoint within the mitmproxy script?
Assumed I have like

```python
def response(flow):
    if flow.request.pretty_host.endswith(my_host):
        res = flow.response
       if res.content:
          # http call?
```

it seems that the `mitmproxy` hangs when trying the `HTTPS` call within the script. I do no have to forward traffic etc., just calling a different endpoint, while keeping the flow as-it-is.

**Comment by mhils** [comment]
You can use requests or whatever you want, but keep in mind that this is blocking and will by default freeze your proxy in the meantime.
