### ISSUE TITLE
websockets: replace simple Masker with speed-optimized version

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#3567]
see the recent discussion in https://github.com/python-hyper/wsproto/issues/127

Summary: Our ["simple" Masker](https://github.com/mitmproxy/mitmproxy/blob/8353f4a55afeec9d30727d91d642e8b8af4040f8/mitmproxy/net/websockets/masker.py) is not really performant. With a little code magic we can gain speedup of up to 60x!

**Comment by MathieuBordere** [comment]
Hi, I'll pick this one up as my first contribution to mitmproxy

**Comment by typoon** [comment]
I assume this can be closed?
