### ISSUE TITLE
Roadmap for mitmweb

### ISSUE THREAD

**Issue by oxr463** [mitmproxy/mitmproxy#3568]
First off, `mitmproxy` is such a wonderful tool; as a programmer turned pen-tester, I find it to be a lot more intuitive than using GUI-driven tools like Burp, and Zap.

The documentation states that `mitmweb` is still in beta, but I am unable to find any roadmap for it, or for `mitmproxy` in general. I'd like to contribute, and I see there are many issues to work on, but there doesn't appear to be any priorities set for any of them.

For now, I guess I'll take a look at the [area/web tag](https://github.com/mitmproxy/mitmproxy/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fweb).

Thanks,

**Comment by mhils** [comment]
Hi @oxr463,

The best way forward would be to join us on the developer Slack and chat there. We have a bunch of things planned for upcoming releases, but things are working a bit slower at the moment till July at least as we are all busy with other things. :)

Best,
Max
