### ISSUE TITLE
curl -x option get 502 bad gateway

### ISSUE THREAD

**Issue by ramumanavalan** [mitmproxy/mitmproxy#3569]
When I apply for proxy on my whole device is working fine. But when I tried to make curl proxy connection I got 502 Bad Gateway

`curl -x 127.0.0.1:8080 http://ipinfo.io/ip`

**Log**:
`127.0.0.1:42420: clientconnect
::ffff:127.0.0.1:42420: request
  -> Request(GET scratchpads.eu:80/)
::ffff:127.0.0.1:42420: Set new server address: scratchpads.eu:80
::ffff:127.0.0.1:42420: serverconnect
  -> ('scratchpads.eu', 80)
::ffff:127.0.0.1:42420: server communication error: HttpReadDisconnect('Server disconnected')
::ffff:127.0.0.1:42420: serverdisconnect
  -> ('scratchpads.eu', 80)
::ffff:127.0.0.1:42420: serverconnect
  -> ('scratchpads.eu', 80)
::ffff:127.0.0.1:42420: serverdisconnect
  -> ('scratchpads.eu', 80)
127.0.0.1:42420: clientdisconnect`

**Response**:
`<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>HttpReadDisconnect(&#x27;Server disconnected&#x27;)</p>
            </body>
        </html>`

**Comment by mhils** [comment]
Not a bug. The remote server just disconnected.
