### ISSUE TITLE
mitmdump doesn't raise done() event

### ISSUE THREAD

**Issue by kubistika** [mitmproxy/mitmproxy#3572]
done() function isn't invoked when CTRL+C is pressed.
This event is super important. I need it in order to close a file I'm writing output to, and because the event isn't being raised, the file never closes and buffered data is not written to the filesystem.

##### Steps to reproduce the problem:

```python
import random
import sys
import os
import json
from datetime import datetime


class RequestsLogger:

    def __init__(self):
        self.requests = []
    
    def request(self, flow): 
        req = flow.request
        client_conn = flow.client_conn 
 
        info = {
            "scheme": req.scheme,
            "url":  req.url,
            "method": req.method,
            "time": str(datetime.now()),
            "host": req.host,
            "dst_port": req.port,
            "headers": dict(req.headers),
            "client_info": {
                "src_addr": client_conn.address[0],
                "src_port": client_conn.address[1],
                "username": os.getlogin()
            }
        }

        self.requests.append(info)
        
    def done(self):
        print('this should be printed at shutdown')
        print('got {} requests', len(self.requests))
        
addons = [
    RequestsLogger()
]

```
Run with `mitmdump -s some_file_name.py -q`

##### System information
Mitmproxy: 4.0.4 binary
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.17763

**Comment by mhils** [comment]
Thanks for the report! Also refs #3584

**Comment by Shnitzelil** [comment]
Question: is it ok to call to `mitmproxy.ctx.master.addons.trigger("done")` ?

**Comment by bigfoxtail** [comment]
I had the same problem.

**Comment by mhils** [comment]
I cannot reproduce this anymore on main, this seems to be fixed. Thanks again for the report and sorry that it took so long. :)
