### ISSUE TITLE
Dyld

### ISSUE THREAD

**Issue by Imparium** [mitmproxy/mitmproxy#3574]
##### Steps to reproduce the problem:

1. Have a macOS High Sierra 10.13.6
2. Have brew
3. Install mitmproxy using brew and run it.

##### Any other comments? What have you tried so far?
Updating everything from brew

##### System information

dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/mitmproxy/4.0.4/libexec/bin/python3.7
  Reason: image not found
[1]    14539 abort      mitmproxy

**Comment by Kagamiiiii** [comment]
What's your python version?
check by running `python3 --version`

On the original installation, my python version is `3.7.4`, but I later changed it to `3.6.5` for  compatibility of other packages and this problem appears as the global python3 version is `3.6.5`;

If your python installation was done via Homebrew, you could switch python3 version to >= `3.7`;
in my case I do `brew switch python 3.7.4`.

If you don't have python 3.7, you could install it via Homebrew and then switch to that version.
