### ISSUE TITLE
Request edit option with new body

### ISSUE THREAD

**Issue by tushardhole** [mitmproxy/mitmproxy#3575]
Hello Everyone,

Currently we can edit request body, and while doing so it opens up vi(editor) with original body.
There are many times, when I need to delete all contents in body, paste new contents in body.

What about having a new option like, 'new-request-body' where it opens up blank vi(editor) and i just paste the new body that i want.

I had first posted it on the forum also,
https://discourse.mitmproxy.org/t/request-edit-option-with-new-body/1572

If sounds foolish, please close the issue, if sounds good then we can discuses more.

**Comment by mhils** [comment]
Thanks for the suggestion. I think adding a new options adds more complexity than what we gain from implementing this. If you use vi (and have not reconfigured your EDITOR variable), there are plenty of ways to delete all lines: https://unix.stackexchange.com/questions/161821/how-can-i-delete-all-lines-in-a-file-using-vi
