### ISSUE TITLE
No module named 'mitmproxy.models'

### ISSUE THREAD

**Issue by arunkumarmn9** [mitmproxy/mitmproxy#3582]
i was trying to modify the response body so i followed the example  **modify_response_body.py** 
but i'm getting the above error while running 
./mitmproxy -s modify_response_body.py

code: modify_response_body.py
```
# Usage: mitmdump -s "modify_response_body.py mitmproxy bananas"
# (this script works best with --anticache)
from mitmproxy.models import decoded


def start(context, argv):
    if len(argv) != 3:
        raise ValueError('Usage: -s "modify_response_body.py old new"')
    # You may want to use Python's argparse for more sophisticated argument
    # parsing.
    context.old, context.new = argv[1], argv[2]


def response(context, flow):
    with decoded(flow.response):  # automatically decode gzipped responses.
        flow.response.content = flow.response.content.replace(
            context.old,
            context.new)
```

my version:
 Mitmproxy: 4.0.4
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by mhils** [comment]
Hi!

It looks like your example is for an old version, but you are using the latest stable release from mitmproxy.

**Comment by brandonros** [comment]
What's the proper new updated import for `from mitmproxy.models import decoded` supposed to be?

**Comment by mhils** [comment]
@brandonros: You can decide between `.raw_content`, `.content`, and `.text`, see https://mitmproxy-pdoc.netlify.app/api/mitmproxy/http.html#Message.raw_content

Future readers: The link above is a preview of our 7.0 docs and likely will not work anymore (#4422). Don't use it, use https://docs.mitmproxy.org/master/api/mitmproxy/http.html#Message.raw_content instead. :)
