### ISSUE TITLE
WBXML is out of date

### ISSUE THREAD

**Issue by user185953** [mitmproxy/mitmproxy#3596]
wbxml is out of date.
Support for EAS 16.1 is available upstream for more than a year
and fix for #2638 is currently waiting for merge.

**Comment by user185953** [comment]
All fixes are merged upstream, ready for pulling

**Comment by mhils** [comment]
We have no vested interest in WBXML support. If you or anyone else wants to see the version in mitmproxy updated, please send a PR! 😃

**Comment by mhils** [comment]
I'm closing this here as I have no particular interest in WBXML, but I'd still be happy to merge a PR. :)
