### ISSUE TITLE
Cannot parse ActiveSync 16.0 messages involving concepts

### ISSUE THREAD

**Issue by user185953** [mitmproxy/mitmproxy#3601]
##### Steps to reproduce the problem:

1. Observe Exchange ActiveSync 16.0 network traffic
2. Transfer a concept between phone and exchange
3. Try to see content

##### System information

Mitmproxy: 4.0.4
Python:       3.6.8
OpenSSL:    OpenSSL 1.1.0i

This is caused by PyWBXMLDecoder crashing on unknown tokens and #3596

**Comment by mhils** [comment]
Thanks for the report! I'm closing this in favor of #3596.
