### ISSUE TITLE
mitmdump hang after launching several minutes

### ISSUE THREAD

**Issue by imom0** [mitmproxy/mitmproxy#3602]
##### Steps to reproduce the problem:

1.Launch mitmdump with args: mitmdump -p 8082 --ignore=www.dpfile.com:443 --ignore=dianping.com:443 --ignore=report.meituan.com:443 --ignore=meituan.net:443 --ignore=push-hotel.meituan.com:443 --no-http2 --ssl-insecure -s myscript.py
2.The script do these things: read from local file, get upstream proxy config, use it for several mins, use another, in response, change some content like:
```
def response(flow):
    if '.js' in flow.request.url and 'order' in flow.request.url:
        flow.response.text = flow.response.text.replace('&&"ABORT"===', '&&"RESCHEDULED"===')
    if 'ebk/consume/order.html' in flow.request.url:
        flow.response.text = flow.response.text.replace("""{{item.checkInDate | date: 'MM-dd'}}""", """{{item.checkInDate | date: 'yyyy-MM-dd'}}""")
        flow.response.text = flow.response.text.replace("""{{item.checkOutDate | date: 'MM-dd'}}""", """{{item.checkOutDate | date: 'yyyy-MM-dd'}}""")
        flow.response.text = flow.response.text.replace("""{{item.price/100""", """{{ (item.totalFee || item.price)/100""")
        flow.response.text = flow.response.text.replace("""{{item.rpInfo}}""", """{{item.goodsId}}""")
        flow.response.text = flow.response.text.replace("""(item.cancelRules""", """(false""")
```
3.10 mins or longer, mitmdump service hang with no response.

##### Any other comments? What have you tried so far?

do not use upstream proxies only change the content, the problem also exists.

##### System information

Mitmproxy: 4.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.4.0-142-generic-x86_64-with-debian-stretch-sid

**Comment by dedededede** [comment]
I had the same question, how did you solve it?

**Comment by imom0** [comment]
@dedededede change open file limit value to bigger

**Comment by mhils** [comment]
I can't seem to reproduce this. Any pointers?
