### ISSUE TITLE
AP Isolation is set in wifi, how to set up mitmproxy

### ISSUE THREAD

**Issue by mansonami** [mitmproxy/mitmproxy#3604]
##### Steps to reproduce the problem:

1. start: mitmdump 
Proxy server listening at http://*:8080
2. modify phone wifi proxy same to MAC

##### Any other comments? What have you tried so far?

Since AP Isolation, mitmdump can catch the phone traffic， how to set in mitmproxy to avoid AP Isolation?

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
