### ISSUE TITLE
Upon running mitmproxy Windows Installer avast antivirus is giving Win32:Malware-Gen Warning

### ISSUE THREAD

**Issue by player67** [mitmproxy/mitmproxy#3606]
Hi!

Upon running mitmproxy windows installer to download mitimproxy Avast antivirus is giving **Win32:Malware-gen**  warning and blocking it. Is mitmproxy windows installer malware affected?

Thanks

**Comment by cruscio** [comment]
Cisco AMP quarantined `mitmweb.exe` on my machine just now

**Comment by mhils** [comment]
You both are encountering false-positives here. If you have downloaded mitmproxy from https://mitmproxy.org (or any of the sources linked there), you should be fine:

- We do not ship any form for malware/adware/tracking/monetization/... with mitmproxy.
- We only collect statistics for our website. We do not collect any form of statistics from your mitmproxy installations and we deliberately do not include any phone-home/telemetry/crash reporting/... functionality in mitmproxy. 

Why is mitmproxy being flagged by your antivirus software? That requires a more technical explanation:

- First, some (OSX) malware unfortunately includes mitmproxy's executables to redirect users' traffic. We – the mitmproxy developers – are in no way affiliated with this and condemn the criminals’ activities. Unfortunately, we cannot stop them including our code in their software.
- Second, we compile our Python source code to executables using [PyInstaller](https://www.pyinstaller.org/). Again, some malware families are also using Pyinstaller for their Python code. As antivirus companies are pushing out heuristics to detect malware, we are occasionally misclassified as a side-effect.

The binaries we provide to users are (to the best of our knowledge) completely safe to use.

**Comment by cruscio** [comment]
I expect it _was_ a false positive. Just thought you should know multiple not-insignificant AV vendors are flagging it as malware. 

Thanks for the response/info @mhils
