### ISSUE TITLE
Certificate verification, unkown CA

### ISSUE THREAD

**Issue by kubistika** [mitmproxy/mitmproxy#3607]
As mitmproxy using OpenSSL to verify certificates, mitmproxy won't allow HTTPS communication with an HTTPS server who's certificate is signed by a CA that is not known by OpenSSL. In order to solve my problem, I tried to run mitmdump with `--set ssl_verify_upstream_trusted_ca=PEM_CA`, then mitmproxy was able to connect via HTTPS to that site, but was using only the custom CA, instead of using it + all of OpenSSL known CAs, so all other HTTPS connections to the internet failed. (unable to get local issuer certificate error...).

How should this one be handled? Isn't there an option for telling mitmproxy to trust a custom CA in addition to all of OpenSSL known CAs?

**Comment by jsenecal** [comment]
Wouldn't this work ?
https://docs.mitmproxy.org/stable/concepts-certificates/#using-a-client-side-certificate

**Comment by mhils** [comment]
The logic in mitmproxy is as follows (this is for 5.0, but also applies for previous versions):

1. In the default configuration, we use https://pypi.org/project/certifi/ for `ssl_verify_upstream_trusted_ca`.
2. If `ssl_verify_upstream_trusted_ca` is set manually, only that is used.

If you want both, take the list from certifi and append it to your PEM file. 😃
