### ISSUE TITLE
Proxy Chaining issue

### ISSUE THREAD

**Issue by rajarajan1888** [mitmproxy/mitmproxy#3613]
##### Steps to reproduce the problem:

Hi,

  I've been facing this new issue with MiTM Proxy that I haven't faced before, at least until Dec 2018. 

 I was doing proxy chaining between MiTMproxy and Charles proxy with the following setup:

1. Android phone <---> Charles Proxy <---> Internet <---> MiTM Proxy <---> IP Server

   - Note that the Android phone <---> IP Server connection is a TLS- encrypted connection over HTTPS for applications such as Netflix, Facebook, etc.

2. The Charles Proxy's and MiTM proxies SSL certificates were installed in the Android phone. The phone runs Android 6, so can trust user- installed SSL certificates. I also have MiTMproxy certificate installed in the Windows 10 machine that runs Charles proxy. The Charles proxy is in the same local network (and hence,  a private IP) as the Android client.  The MiTMproxy runs on an Amazon EC2 instance with public IP.

3. The purpose of having a MiTMproxy in public IP is to collect some TCP stats (like RTT, etc) on the IP side, upon routing the traffic data through the proxy. 

4. The above setup successfully enabled me route the HTTPS/TLS-encrypted traffic over both the proxies and intercept the traffic on both the proxies using tcpdump, etc. This was till Dec 2018.

5. However, when I recreated the same setup now,  the MiTMProxy does not seem to be working fine with HTTPS. It works fine with HTTP though. I only see a "ClientConnect" from Event logs of MiTMProxy when I use HTTPS. Even as the client is successfully connected to the MiTMproxy, I immediately see a "Client Disconnect". The Android client is getting a connection timeout and there is no HTTPS data transfer to the client. This was never the case until Dec 2018.

6. When I use Windows chrome browser as client, I see "waiting for proxy tunnel" message. And when I use MiTMproxy, I only see something like "GET http://www.google.com" . Note the URL doesn't say "https". Then, there is a 301 or 302 as response.

**Comment by mhils** [comment]
This sounds like a networking issue, not a mitmproxy issue.
