### ISSUE TITLE
certutil.exe -importpfx Root mitmproxy-ca-cert.p12 does not work

### ISSUE THREAD

**Issue by vincenthawke** [mitmproxy/mitmproxy#3622]
OS: Windows 10
Mitmproxy ver: 4.0.4

I am unable to use cmd or PS to install the certificate. 
Running the provided command returns this:

```
C:\projects>certutil -importpfx Root mitmproxy-ca-cert.p12
Enter PFX password:
CertUtil: -importPFX command FAILED: 0x80092007 (-2146885625 CRYPT_E_SELF_SIGNED)
CertUtil: The specified certificate is self signed.
```

**Comment by mhils** [comment]
`-importpfx` requires the full certificate including private key. If you have a command to import the cert only we'd be happy to take that, please submit a PR! 😃

**Comment by MorrisonCole** [comment]
@mhils sorry to raise this issue from the dead, but as a new user, I followed your [documentation here](https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually) which told me to run that exact command and received the same error.

I don't think having this in the documentation is particularly useful - I've found quite a few users referencing the same problem: [1](https://discourse.mitmproxy.org/t/cannot-install-mitmproxy-certificate-on-windows-10/784/3), #3605 from my still open tabs 😄

**Comment by cshesse** [comment]
I am also having this issue now and found multiple unanswered posts with the same issue:

https://discourse.mitmproxy.org/t/cannot-install-mitmproxy-certificate-on-windows-10/784/3
https://discourse.mitmproxy.org/t/certutil-fails-with-self-signed-certificate-error/946

**Comment by cshesse** [comment]
Instead of the listed command I ran `certutil -addstore root mitmproxy-ca-cert.cer` from https://social.technet.microsoft.com/Forums/ie/en-US/327f3293-d3ea-409d-b8d9-2243ce7f6a72/upgrade-ca-to-sha256?forum=winserversecurity and it seems to have worked

**Comment by mhils** [comment]
Thanks @cshesse! Could you file a PR that updates our docs? 😃

**Comment by kriti218** [comment]
hi, i have been banging my head around the self-signed error i am getting.
My scenario is:
1. I have a .pfx file with string password
2. I run certutil -f --p "password" -importpfx "filepath" under admin access
3. I get error "The specified certificate is self-signed"

Note: I am able to import into local machine personal store using certificate management UI.
Please suggest as i am really stuck with this issue.

**Comment by andrejzoz** [comment]
Hi, I'm begging here for some clarification - is this a bug or feature?

**Comment by ra185270** [comment]
The order of the parameters should be modified to look like below.

certutil -p "_password_" -importpfx Root _mca-com.p12_

**Comment by mstrmke** [comment]
@ra185270, this did not work for me. I still have the same error. Any other ideas?

**Comment by g3nsvrv** [comment]
not really good instructions, tho
<img width="505" height="395" alt="Image" src="https://github.com/user-attachments/assets/f4c0ee70-9d2c-4c7e-ab3c-936c49211d70" />
