### ISSUE TITLE
the client may not trust the proxy's certificate 

### ISSUE THREAD

**Issue by shay444** [mitmproxy/mitmproxy#3623]
##### Steps to reproduce the problem:
hi, i got a problem with the trust certificate i'm using virtualbox 1 with kali and mitmproxy and win10.
![image](https://user-images.githubusercontent.com/51204841/63836892-1e6efe00-c983-11e9-9504-2655dbd58885.png)
i can use firefox in the win10 only when i use "ufw disable" on kali when i tried to use ip tabels with:
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080
ip6tables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
ip6tables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080
u can see that i add the mitmproxy certificate to: 
![image](https://user-images.githubusercontent.com/51204841/63837380-0ea3e980-c984-11e9-815f-98ad2629ca15.png)
![image](https://user-images.githubusercontent.com/51204841/63837425-21b6b980-c984-11e9-93d8-e12eac219107.png)

ty for the help :)

##### System information
KALI
WIN10

4.0.4

**Comment by mhils** [comment]
Firefox has a separate certificate store. You need to add the mitmproxy CA there.
