### ISSUE TITLE
Can we catch timeout exception  when using upstream mode?

### ISSUE THREAD

**Issue by xiongjiabin** [mitmproxy/mitmproxy#3628]
Could we catch below exception in addon code or somewhere when the upstream server is down?

> << Server connection to ('125.117.144.120', 57114) failed: Error connecting to "125.117.144.120": [Errno 61] Connection refused

##### System information

Mitmproxy: 4.0.4
Python:    3.7.2
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Darwin-18.7.0-x86_64-i386-64bit

**Comment by dedededede** [comment]
Hi, i had the same problem. How did you solve it?

**Comment by monkeysuffrage** [comment]
Same problem, mitmproxy just hangs forever.

**Comment by mhils** [comment]
refs #1775

**Comment by mhils** [comment]
This should be fixed on master. If that's not the case, please open a new issue!
