### ISSUE TITLE
Proxy breaks multi-part responses

### ISSUE THREAD

**Issue by rdegraaf** [mitmproxy/mitmproxy#3629]
I am trying to use mitmproxy to test a service that implements push messages over HTTP/2 in an unusual way: clients issue a GET request to a particular route, which immediately responds with an HTTP 200 with the header "content-type: multipart/related; boundary=------abcde123; type=application/json".  It does *not* send a content-length header.  The server then keeps the session open and sends further response frames as push messages become available.

When I try to proxy this application with mitmproxy, it appears that mitmproxy is closing the session immediately after the initial response; the client never receives the additional responses.

##### Steps to reproduce the problem:

**Note: this is not the test setup that I'm using; I can't share the actual client and server with you and I haven't written a full reproduction case.  However, the setup described below *should* be equivalent to what I'm testing.

1.  Set up an HTTP/2 server (I haven't tried this with HTTP/1.1) that responds to a GET request with a 200 response containing the header "content-type: multipart/related; boundary=------abcde123; type=application/json", then leaves the stream open; it later sends more response data such as "------abcde123\r\nhello world\r\n------abcde123\r\n

2.  Set up a client for the above server.  This can be implemented with Python code similar to the following:

        import hyper
        conn = hyper.HTTP20Connection("SERVER_NAME")
        conn.connect()
        sid = conn.request('GET', "/PATH", {'accept':'*/*'})
        resp = conn.get_response(stream_id=sid)
        print(resp.status)
        print(resp.headers)
        for data in resp.read_chunked():
            print(data)

3.  Connect the client to the server.  Observe that the "hello world" response is received.

4.  Insert mitmproxy between the client and server (this should be possible using the `proxy_host` and `proxy_port` parameters to hyper.HTTP20Connection; see <https://hyper.readthedocs.io/en/latest/api.html#http-2>)

5.  Connect the client to the server through the proxy.  Observe that the stream closes immediately and "hello world" is never received.

##### System information

    $ bin/mitmweb --version
    Mitmproxy: 4.0.4
    Python:    3.6.8
    OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
    Platform:  Linux-4.15.0-58-generic-x86_64-wth-Ubuntu-18.04-bionic

**Comment by Kriechi** [comment]
We just merged a brand new protocol implementation - if you can repeat the problem with the latest version from git-master, please re-open this issue.
