### ISSUE TITLE
gulp build broken

### ISSUE THREAD

**Issue by fliot** [mitmproxy/mitmproxy#3632]
##### Steps to reproduce the problem:

1. cd ./web && yarn && gulp
2. pip3 uninstall mitmproxy && pip3 -v install . --upgrade   # hard way
3. mitmweb
4. each displayed request breaks the react view:
![image](https://user-images.githubusercontent.com/3476379/64531438-d13e4500-d30f-11e9-8fe0-9d36ee4b3c7b.png)

##### Any other comments? What have you tried so far?
I tried several version of Yarn and Gulp, just in case, but I get the same behavior...

##### System information
yarn -v
1.17.3

node -v
v10.16.3

gulp -v 
CLI version: 2.2.0
Local version: Unknown

mitmweb --version
Mitmproxy: 5.0.0.dev    (I got the same behavior with 4.0.4)
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.0.0-27-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by fliot** [comment]
Same thing with

gulp -v
[18:05:18] CLI version 3.9.1
[18:05:18] Local version 3.9.1

**Comment by mhils** [comment]
Thanks @fliot! Sorry for the late reply, this has been fixed in #3745.
