### ISSUE TITLE
MITMProxy is detected

### ISSUE THREAD

**Issue by gianlucacolucci** [mitmproxy/mitmproxy#3635]
I am trying to debug a mobile app, which seems to have some kind of protection against MITM attacks. 

The presence of MITMProxy is detected. 

Is there any way around this?

**Comment by fliot** [comment]
I don't know the case you face, but their are many way software developers can harden their access to prevent MITM attacks.

The followed list implementation have no work around, impossible to lure them,
Dev can implement in their app :
1) checking/verifing directly the remote certificate in their apps, not on OS/System API.
2) checking/verifing directly the CA certificate in their apps, not on OS/System API.
3) implementing client certificate communication

**Comment by ylmrx** [comment]
This is called unpinning, there are several methods to achieve this. 
such as : https://securitygrind.com/bypassing-android-ssl-pinning-with-frida/

It's beyond mitmproxy scope, and might have legal implication depending on where you are.

**Comment by mhils** [comment]
Thanks @ylmrx! We'd definitely be happy to have some more documentation on unpinning methods, but it's not exactly in our scope.
