### ISSUE TITLE
Support of .yml extension in config file.

### ISSUE THREAD

**Issue by HasBert** [mitmproxy/mitmproxy#3639]
Hey,
**this is not a bug issue it's more a feature request.** 
Yesterday I made a STUPID mistake and named the `config.yaml` file `config.yml`. It cost me some time to find out. (Yeah I know that the docs say use `config.yaml` xD)
According to [this post](https://stackoverflow.com/questions/22268952/what-is-the-difference-between-yaml-and-yml-extension), the extensions `.yaml` and `.yml` are the same. The extension `.yml` [has grown](https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml) in Google search results, over the past years. 

However, I thought, that accepting both file extensions would make mitmproxy more robust. I started to implement this "feature" for a pull request, and then thought that I should ask you first, **if you even want to have it?** Maybe you want to force people to use the [correct](https://yaml.org/faq.html) extension.

**Comment by Kriechi** [comment]
Sounds reasonable to me - pull requests are welcome!

**Comment by YuriyTigiev** [comment]
Where can I find a config file for linux and windows version of mitmproxy?
Can you share the sample of the file?
How to use --options for change some configuration?

**Comment by WAZAAAAA0** [comment]
> Where can I find a config file for linux and windows version of mitmproxy?
> Can you share the sample of the file?
> How to use --options for change some configuration?

@YuriyTigiev on Windows, you need to create the `config.yaml` file in this path:
`%HOMEPATH%\.mitmproxy\config.yaml`

sample content inside `config.yaml`:
```yaml
ssl_insecure: true
validate_inbound_headers: false
tls_version_client_min: TLS1
tls_version_server_min: TLS1
anticomp: true
```

and from now if you run `mitmweb`, the webpage should show at the bottom left corner the options `ssl_insecure anticomp` as confirmation


![mitmweb config settings](https://i.imgur.com/9KOSJFi.png)
