### ISSUE TITLE
How to create certificate?

### ISSUE THREAD

**Issue by piko789** [mitmproxy/mitmproxy#3641]
##### Steps to reproduce the problem:

1. openssl genrsa -out cert.key 2048
openssl req -new -x509 -key cert.key -out cert.crt
2. cat cert.key cert.crt > cert.pem
3. then i run mitmproxy in transparrent mode and i add --cert *=cert.pem
4. sudo nano cert.pem
5. create txt file in ansi on my pc and copy paste the cert.pem. then save file
6. send cert.pem to my android phone and instlal certificate.

##### Any other comments? What have you tried so far?

certificates installs successfully on the phone. then i get handshake error on the mitmproxy and cant visit any https website on the phone. Phone connects to linux server using pptpd. non https sites works. https i get error.. If i run in regular mode and add manually proxy then i can visit mitm.mi and download cert,install it and it works fantastic.however when i run mitmproxy in transparrent mode i cannot visit mitm.it on the phone as it says that traffic does not go through mitmproxy but it DOES go because non https websites i can visit them..
Is it wrong the way i try to create my own certificate in order to avoid downloading a new one all the time(plus mitm.it isnt working when on transparrent)??

thank you

##### System information

4.0.4

**Comment by Kriechi** [comment]
Please do not generate a certificate manually - it will not work.
You can install the auto-generated certificate authority by mitmproxy with these instructions: https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually

**Comment by ChillVibesMushroom** [comment]
mitmproxy - -mode transparent --certs *=cert.pem

alongside arp spoofing will this work I need to be ssl stripping in order to control all https traffic
