### ISSUE TITLE
The windows mitmdump can‘t download file，Always in the link

### ISSUE THREAD

**Issue by logan-x** [mitmproxy/mitmproxy#3644]
Steps to reproduce the problem:
1.Start mitmdump on Windows
2.Listen for localhost: 8888，domain: qq.com
3.Open https://work.weixin.qq.com/
3.Click the download button on the web page

Any other comments? What have you tried so far?
It's always on the link. It can't be downloaded. https://pc.weixin.qq.com/ is the same。
set "flow.response.stream" = True Also is invalid

System information
Mitmproxy: 4.0.3 binary
Python: 3.6.5
OpenSSL: OpenSSL 1.1.0h 27 Mar 2018
Platform: Windows-2008ServerR2-6.1.7601-SP1

**Comment by logan-x** [comment]
![1](https://user-images.githubusercontent.com/25201266/65216355-2a159680-dae3-11e9-931c-96fb91c0c0fb.png)
![2](https://user-images.githubusercontent.com/25201266/65216359-2c77f080-dae3-11e9-9595-e4c74cef39ae.png)

**Comment by sk3lk0** [comment]
use inspect element ctrl+shift+i

**Comment by mhils** [comment]
I can't really reproduce this, sorry. Closing for now.
