### ISSUE TITLE
[Feature] Support for TLS1.3

### ISSUE THREAD

**Issue by njnuzhao** [mitmproxy/mitmproxy#3645]
Hello, the tested app  only use tls1.3, does the latest version of mitmproxy supports tls1.3-https traffic analysis? Thank you.

**Comment by Kriechi** [comment]
mitmproxy is not yet tested with TLS1.3.
Most of our dependencies, openssl, and their Python libs, should support it though - but we need to check our custom TLS parser logic.

**Comment by Kriechi** [comment]
Released as part of mitmproxy v5.1.0.
