### ISSUE TITLE
Mitmproxy doesn't work in iOS apps

### ISSUE THREAD

**Issue by n3oney** [mitmproxy/mitmproxy#3647]
##### Steps to reproduce the problem:

1. Connect an iPhone to mitmproxy
2. Open an app like Messenger
3. Messenger can't connect to the internet.

##### Any other comments? What have you tried so far?

I have tried using mitmproxy on Ubuntu and MacOS both, nothing has changed. The apps still can not access the internet. I can open websites normally (I've trusted the certificate) but not use apps like Messenger, Discord.

I'm on an iPhone 6s iOS 12.4, jailbroken. So, if there is a way to make this work that requires jailbreak, I would be happy to try it.

##### System information

Mitmproxy: 4.0.4 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Darwin-19.0.0-x86_64-i386-64bit

**Comment by alexm92** [comment]
I just starting to have a similar issue after I upgraded from iOS 12 to 13.
On iOS 12 everything worked perfectly, but after the upgrade something has changed and the root certificate is no longer valid.

@mhils any ideas?

**Comment by mhils** [comment]
For iOS 13, see #3649.
