### ISSUE TITLE
iOS 13 and HTTPS Inspection - Root Certificate Issue

### ISSUE THREAD

**Issue by Ogekuri** [mitmproxy/mitmproxy#3649]
##### Steps to reproduce the problem:

1. Upgrade iPhone to iOS 13
2. Try in inspect HTTPS traffic of Safari
3. Unable to connect to remote site with Safari

##### Any other comments? What have you tried so far?

It appears that iOS 13 introduced new requirements for HTTPS certificates to be treated as valid: 
[https://support.apple.com/en-gb/HT210176](https://support.apple.com/en-gb/HT210176)
##### System information

mitmproxy-4.0.4-windows>mitmweb.exe --version
Mitmproxy: 4.0.2 binary
Python:    3.6.5
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.17763

**Comment by Shadoovv128** [comment]
Azu, SS7, CSS, RSS
