### ISSUE TITLE
Clear All option for mitmweb

### ISSUE THREAD

**Issue by mswilson4040** [mitmproxy/mitmproxy#3665]
##### Steps to reproduce the problem:

1. run `mitmweb`
2. Wait for the a bunch of requests to be picked up
3. Let the OCD kick in and want to clear the entries
4. Too bad, delete everything one-by-one

##### Any other comments? What have you tried so far?

This is just a feature request to add a feature to 'Clear All' for `mitmweb`. There's a delete option, but it's only a single delete. It would be nice if there was a Clear All button or maybe just a 'Select All' > Delete flow.

##### System information

Mitmproxy: 4.0.4
Python:    3.7.4
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Darwin-19.0.0-x86_64-i386-64bit

**Comment by mhils** [comment]
How do you feel about File -> New (which already exists)?

**Comment by mswilson4040** [comment]
Yea, I saw that. I was a little unsure if that actually reset everything (filters/config/etc...)

**Comment by mhils** [comment]
I guess you have a point. Let's change the icon and rename it. PRs welcome! 😃

**Comment by Eluch** [comment]
I think what you are searching for is a function what exists but quite hidden: If you press "Z" when the tab is active then all the requests are deleted.

**Comment by weberjn** [comment]
What about enhancing the [d]elete flow tooltip with [z] delete all ?
