### ISSUE TITLE
Addon script loaded successfully but not working

### ISSUE THREAD

**Issue by supermariogo** [mitmproxy/mitmproxy#3668]
Hi,

I run into a very weird issue on Ubuntu MATE installed on Pi3. mitmproxy can load addon script successfully, but only `init` can be executed and no other response after that when http requests come.

For the same script, I can see log output on my mac.

##### Steps to reproduce the problem:

1. Ubuntu MATE on Pi3 and install mitimproxy by pip3 install 
2. Create the sample add-on script:
```
from mitmproxy import ctx


class Counter:
    def __init__(self):
        self.num = 0
         ctx.log.info("init")

    def request(self, flow):
        self.num = self.num + 1
        ctx.log.info("We've seen %d flows" % self.num)


addons = [
    Counter()
]
```
3. mitmdump -s aboveScript.sh

##### Any other comments? What have you tried so far?

Searched web, but no one mentioned this.

##### System information
Ubuntu MATE installed on Pi3

mitmproxy --version
Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.8
Platform: Linux-4.15.0-1032-raspi2-armv7l-with-Ubuntu-18.04-bionic
SSL version: OpenSSL 1.1.1  11 Sep 2018
Linux distro: Ubuntu 18.04 bionic

**Comment by ylmrx** [comment]
How exactly do you try it (what request, and how?) ?
 Bear in mind that a request will be counted only after the handshake was successful (in case of an HTTPS  request).

If you want to count every "`clientconnect`", this is what you're aiming for : 

```python
def clientconnect(self, layer):
    self.num = self.num + 1
    ctx.log.info("We've seen %d flows" % self.num)
```

if you want to count every exchange: 
```python
def update(self, flows):
    self.num = self.num + len(flows)
    ctx.log.info("We've seen %d flows" % self.num)
```
It doesn't seem like a raspberry-specific issue.

**Comment by mhils** [comment]
Thanks @ylmrx!
