### ISSUE TITLE
'MultiDictView' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by chuky3000x** [mitmproxy/mitmproxy#3673]
I use mitmproxy to capture cookies from my network traffic. I start mitmproxy from python with an addon.

For example my addon looks like this:
```
class AddonProxy():
    def __init__(self, cookieclass):
        self.cookieclass = cookieclass

    def response(self, flow):

        cookies = flow.response.cookies

        if cookies:
            self.cookieclass.test_cookies_response.append(cookies)

    def request(self, flow):

        cookies = flow.request.cookies

        if cookies:
            self.cookieclass.test_cookies_request.append(cookies)
```

For every request or response i store the cookies in a list. After i visit all websites with selenium, i would like to work with the cookie information. The [mitmproxy doc](https://2qwesgdhjuiytyrjhtgdbf.readthedocs.io/en/latest/dev/models.html#netlib.multidict.MultiDictView) tells me that the MultiDictView class have a function that gives me the MultiDictView as a python dict. But it not work.

My code looks like:
```
for ob in self.test_cookies_response:
    pprint.pprint(ob.to_dict())
```

I get an error:
`AttributeError: 'MultiDictView' object has no attribute 'to_dict'`

Why?

I use Python 3.7.3 and Mitmproxy: 4.0.4 under Debian 10.1

**Comment by woshichuanqilz** [comment]
How do you solve this I get this error to I tried to convert flow.request.urlencoded_form to dict

**Comment by enriquejr99** [comment]
Try using dict(x) instead of x.to_dict()
