### ISSUE TITLE
Multiple mitmproxy/mitmdump instances can run on the same port

### ISSUE THREAD

**Issue by jpstotz** [mitmproxy/mitmproxy#3674]
Currently mitmproxy opens the proxy port always using the option `allow_reuse_address = True` without any exception.
https://github.com/mitmproxy/mitmproxy/blob/e74e97bcd96346a1ae8c372a94149100a755739a/mitmproxy/proxy/server.py#L35-L36

In my understanding this option should only be set in cases where load distribution by using multiple processes is used. Or is there any other mitmproxy related use case I don't see that requires multiple mitmproxy instances listening on the same proxy port for incoming requests?

On the other hand the current situation with `allow_reuse_address = True` can lead nondeterministic  behavior in situations where multiple mproxy/mitmdump instances are using the same proxy port (or even other third party programs). 

Therefore I suggestion is to change this and set `allow_reuse_address = False` or at least provide an command-line option to set the default reuse behavior for the proxy port.

**Comment by mhils** [comment]
Aside from the fact that this attribute seems to be ignored in tcp.TCPServer (PRs to remove it are welcome), we set SO_REUSEADDR to allow seamless mitmproxy restarts. Relevant excerpt from
https://stackoverflow.com/a/14388707/934719:

> If SO_REUSEADDR is not set, a socket in state TIME_WAIT is considered to still be bound to the source address and port and any attempt to bind a new socket to the same address and port will fail until the socket has really been closed, which may take as long as the configured Linger Time. So don't expect that you can rebind the source address of a socket immediately after closing it. In most cases this will fail. However, if SO_REUSEADDR is set for the socket you are trying to bind, another socket bound to the same address and port in state TIME_WAIT is simply ignored, after all its already "half dead", and your socket can bind to exactly the same address without any problem.

Long story short, the topic is rather complex (read the full SO answer), but it makes sense for us to enable SO_REUSEADDR by default so that people can Ctrl+C and then start mitmproxy again right away. 

My intuition would be that the complexity of a command line flag outweighs its benefits, but I'm willing to be convinced with real-world evidence.

**Comment by jpstotz** [comment]
OK, I agree with you that `allow_reuse_address = True` makes sense on Linux systems. I already have experienced the effect but wasn't aware of the background causing it.

May be my use case is a bit specific, because I want to use mitmproxy in an environment where mitmdump instances are created and stopped by an external script. Before starting a new mitmdump process I want to make 100% sure that the previous mitmdump process has been terminated and the proxy port is exclusively available to my new instance. I can't do this on process level I tried to check the availability of the port which of course does not work if the socket allows reusing.

I will check how much work a PR with a new option will make. At least the development environment set-up on Linux works as described (the Windows powershell script fails on some `hg` call).
I also haven't figured out how to start mitmdump on the source code version of mitmproxy - am I right that `mitmdump` is started by directly calling a non-main method in `mitmproxy.tools.main`? I have never seen such a set-up and have problems starting that method manually from command-line or within PyCharm.

**Comment by mhils** [comment]
> I will check how much work a PR with a new option will make.

Not much, but there's a long-term cost associated with maintaining it, which I think we don't want to bear unless there's a good general reason to do so. You can of course maintain your own fork with that change.

> the Windows powershell script fails on some hg call

Please do feel free to submit an issue for this, it should work just fine.

> I also haven't figured out how to start mitmdump on the source code version of mitmproxy 

```
$ pip3 install -e .
$ # make sure that your Python scripts path is in $PATH
$ mitmdump
```

**Comment by jpstotz** [comment]
@mhils Finally I was able to set-up my dev environment on Linux and Windows successfully. I found out that on Linux the `mitmdump` file in the venv is just a Python script without .py file ext. Therefore this can be used for debugging. On Windows you can use the file `mitmdump-script.py` from the `venv\Scripts` directory for running mitmdump e.g. from within PyCharm with or without debugger attached.

Then I made the changes and started testing it. After having added the new option in a way that it really worked I had to realize that it was useless: even ignoring the option and making a static change to `allow_reuse_address = False` in the `ProxyServer` class had no effect in my tests. I am not sure why this does not have any effect.

In the end I found out that I can my code work reliable that tests if the TCP port is free or used by a program. This code now works independently if the port allows reusing or not.
Therefore from my side there is no need for this option anymore. 
Anyway thanks for your help so far.
