### ISSUE TITLE
Download page doesn't work on chrome

### ISSUE THREAD

**Issue by UmbreonFR4** [mitmproxy/mitmproxy#3677]
##### Steps to reproduce the problem:

1. goto https://mitmproxy.org/downloads/ on chrome and wait for it to load (it will never load)

##### Any other comments? What have you tried so far?
Ive went onto firefox and it has worked instantly

**Comment by mhils** [comment]
Works fine for me. Which version are you on? Anything in the developer console? Any nerfarious Chrome extensions?

**Comment by UmbreonFR4** [comment]
Two errors in console:
`Uncaught SyntaxError: Identifier 'WEB_ROOT' has already been declared
    at snapshots.js:1
(index):192 Uncaught ReferenceError: fetchS3 is not defined
    at update ((index):192)
    at (index):195`

**Comment by mhils** [comment]
Which version of Chrome are you on?
Could you share your contents of https://mitmproxy.org/snapshots.js and the source you are seeing for https://mitmproxy.org/downloads/?
