### ISSUE TITLE
Is there any configuration description for the transparent mode on windows?

### ISSUE THREAD

**Issue by xiaojinxiansheng** [mitmproxy/mitmproxy#3681]
Unable to capture the phone's package using mitmdump.exe or python version of mitmdump
Local pc also cannot access the Internet.(http is ok, but https not)
But it works on other machines in the same LAN

**Comment by xiaojinxiansheng** [comment]
host address

**Comment by xiaojinxiansheng** [comment]
host address:
  192.168.223.225
  255.255.254.0
  192.168.222.254

iphone address:
  192.168.221.137
  255.255.254.0
  192.168.223.225

**Comment by mhils** [comment]
Any form of advanced networking on Windows is slightly tricky. See https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/platform/windows.py#L370 for _some_ documentation.
