### ISSUE TITLE
How to filter the display request via device ip

### ISSUE THREAD

**Issue by ThinkerT** [mitmproxy/mitmproxy#3683]
How to filter requests through the device's ip when using mitmweb？

![image](https://user-images.githubusercontent.com/15814211/68011270-d8efe980-fcc1-11e9-973c-f908cf8fb9ac.png)

```
Mitmproxy: 5.0.0.dev (+328, commit 65edbda)
Python:    3.7.2
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-17.5.0-x86_64-i386-64bit
```

**Comment by mhils** [comment]
See https://docs.mitmproxy.org/stable/concepts-filters/: Use `~src`.
