### ISSUE TITLE
(Almost) can't access the internet with the android proxy

### ISSUE THREAD

**Issue by Raklure** [mitmproxy/mitmproxy#3684]
##### Steps to reproduce the problem:

1. Install mitmproxy with pip on Ubuntu
2. Configure the proxy on the Android device
3. Try to access to the internet

##### Any other comments? What have you tried so far?

I've tested it only on my OnePlus6.
The thing is that my devices says "connected to the wifi but no internet connection".
- My computer has mitmproxy launched and is connected to the same wifi
- The CA is well installed on my phone and computer
- My android device has a proxy setup with the local IP adress of my computer and 8080 port
- mitmproxy reads what my phone is trying to do, so it writes HTTP and HTTPS requests
- I can't access most of things, such as Google Play or just connecting to a game
- I can navigate on google without any problem, only few sites won't let me in

I don't really know why it does that, I looked if someone else met the same problem, I only came up with few SSL tips that didn't work well for me.
If you have any help to bring me, feel free !

##### System information

My mitmproxy version is 0.18.2 and I'm using python 2.7

**Comment by Kriechi** [comment]
Please use the latest version of mitmproxy: https://docs.mitmproxy.org/stable/overview-installation/
Your version 0.18.2 is not supported any more.
