### ISSUE TITLE
After upgrading mitmproxy it stopped working

### ISSUE THREAD

**Issue by dutzi** [mitmproxy/mitmproxy#3685]
I upgraded to the latest version (4.0.4_3, `brew upgrade mitmproxy`) 

Now, when running `mitmproxy` or `mitmdump` I get the following error:

```
Abort trap: 6
```

And a few seconds later a message box opens saying Python has crashed.

**Comment by vin01** [comment]
Are you on MacOS Catalina and using brew for installing Python?

If so, then you might be running into this: https://holgr.com/python-3-in-macos-catalina-fixing-the-abort-trap/

**Comment by dutzi** [comment]
I hit upgrade again and it worked.

Thank you @vin01.
