### ISSUE TITLE
Persistent cache based on http headers

### ISSUE THREAD

**Issue by thenewguy** [mitmproxy/mitmproxy#3687]
It would be nice to be able to configure persistent cache based on response http headers.  Perhaps specifying a path on disk.  Apt packages are of particular interest =)

**Comment by mhils** [comment]
FWIW, I think mitmproxy is the wrong tool for this, but you should be able to implement this as an addon yourself. It's likely nothing we want to have included in the core anytime soon, so I'm closing this for now.
