### ISSUE TITLE
Save all traffic *except* image content

### ISSUE THREAD

**Issue by elastic-paul** [mitmproxy/mitmproxy#3690]
Not so much a feature request as a question.

I use Mitmprox and save all traffic to file. However if I visit a page with a lot of JPGs (for instance a lot of thumbnails) I don't want to save the actual binary encoded JPG. I want everything except for the body of the image. I never want the images - saves a huge amount of space.

Can I do this with a filter? Or even a python script?
Thanks

**Comment by typoon** [comment]
Sorry for the delay. I just tested it with this filter here:

```
!(~hs image/jpg)
```

That one will filter out any files that have `image/jpg` in any of the headers in the response. For jpg images, the `Content-Type` header is usually `image/jpg`. 

If you want to remove other types (say png images), you can use the following:

```
!((~hs image/jpg) | (~hs image/png))
```

Now in the filtered screen, just use the command:

```
: save.file @shown /path/to/your/file
```

Let me know if that works for you.

**Comment by elastic-paul** [comment]
Thanks for taking the time on this!
Rather than the NOT image/jpg approach could I use wildcard in there instead?
`!(~hs image/*)`
This would save me having to add all types? 
I am not need my proxy lab to test I'm afraid.

**Comment by Prinzhorn** [comment]
Filter expression use regular expression, just ` !(~hs image/)` is enough since it matches _anywhere_.
But you'd rather use `~ts` as it matches the content-type directly instead of all the headers.

I guess this can be closed.
