### ISSUE TITLE
Transparent mode failure: FileNotFoundError(2, "No such file or directory: 'sudo'")

### ISSUE THREAD

**Issue by maysammortazi** [mitmproxy/mitmproxy#3696]
mitmweb --mode transparent

clientconnect
Transparent mode failure: FileNotFoundError(2, "No such file or directory: 'sudo'")
clientdisconnect

System information

mitmproxy version 4.0.4
OS: FreeBSD 11.1
Python 3.6.9

**Comment by ylmrx** [comment]
It might sound a bit silly : do you have `sudo` installed ?

**Comment by maysammortazi** [comment]
> It might sound a bit silly : do you have `sudo` installed ?

yes, you are right.
I solved it by installing `sudo`.

**Comment by liudonghua123** [comment]
I run on windows, it gave me the following error.
![image](https://user-images.githubusercontent.com/2276718/71944991-7c003a80-3200-11ea-95e8-aba505938f1e.png)
