### ISSUE TITLE
/usr/local/bin/mitmproxy: No such script

### ISSUE THREAD

**Issue by nadermx** [mitmproxy/mitmproxy#3706]
I'm trying to have mitmproxy do the tls_passthrough but I get the `/usr/local/bin/mitmproxy: No such script`

I'm running the command `sudo mitmproxy --set stream_large_bodies=1 --set block_global=false --showhost -s tls_passthrough.py`

#### System Information
sudo mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.1  11 Sep 2018
Platform:  Linux-4.15.0-58-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!

**Comment by nadermx** [comment]
done, https://stackoverflow.com/questions/58884452/usr-local-bin-mitmproxy-no-such-script

Thank you
