### ISSUE TITLE
Docker: Move away from Alpine

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#3712]
On my quest to shorten CI times, building Docker images has become a major bottleneck. A major issue here is that we use Alpine Linux, which means we can't use precompiled manylinux wheels (Alpine uses musl...).

@mitmproxy/devs: any opinions on moving to a minimal Ubuntu image? I feel that should be just fine.

**Comment by Kriechi** [comment]
👍

**Comment by ylmrx** [comment]
:+1:

**Comment by mhils** [comment]
I'm closing this for now as the switch to GitHub actions means we don't need this for PRs. The pressure for master branch builds is less severe, to say the least.

**Comment by mhils** [comment]
`cryptography` now includes Rust code, which makes an Ubuntu-based image that can consume prebuilt wheels much more appealing.

**Comment by alt-glitch** [comment]
Hi, I'd like to work on this issue. If I understand correctly, we are trying to move from an Alpine Linux Docker Image for mitmproxy to a small Ubuntu/Debian one right? And the reasoning for this is to shorten the Docker build times if I'm not wrong? How should I go about building the image and what steps am I supposed to follow?

**Comment by mhils** [comment]
Yes! It's probably the easiest to base it off [python:3.9-buster](https://hub.docker.com/_/python). You basically need to install mitmproxy with pip and make sure that it starts properly. :)

**Comment by hazcod** [comment]
@mhils honest question, why not python:3.9-slim-buster ?

**Comment by mhils** [comment]
@hazcod: From https://hub.docker.com/_/python

> Unless you are working in an environment where only the python image will be deployed and you have space constraints, we highly recommend using the default image of this repository.

**Comment by mhils** [comment]
@hazcod: I retract my previous statement. Looking at the Python Dockerfile, the slim variants are based upon debian:-slim, which is perfectly fine I think. The image is _much_ smaller, let's just use it.
