### ISSUE TITLE
Infra: Remove npm/yarn from docs.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#3716]
We currently recommend to use yarn to compile the docs SCSS:

https://github.com/mitmproxy/mitmproxy#documentation
https://github.com/mitmproxy/mitmproxy/tree/master/docs

Hugo now has an "extended version", which automatically compiles SCSS to CSS. This means we can get rid of all the yarn/npm/.. stuff and just use that. I updated our website repo already (https://github.com/mitmproxy/www/pull/21), it would be fantastic if someone could step up and do the same here! 😃

**Comment by akshaycbor** [comment]
I'll take this up

**Comment by meetmangukiya** [comment]
@akshaycbor are you still working on this?
