### ISSUE TITLE
🚀 Ship mitmproxy 5.0

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#3719]
A new release is long overdue, so let's cut one!

- [x] Write the CHANGELOG. One basically needs to go through the commit list and write out all new features from a user perspective. Do we have any volunteers for that? https://docs.google.com/document/d/1fqEXRSD_YNWNLLNK5ir689wH6bBgPEsxujx0EFvt2cY/
- [x] Figure out what's the current state of the session addon? Can we ship this or defer? @cortesi? @madt1m?
- [x] Ideally get through the issues linked in https://github.com/mitmproxy/mitmproxy/milestone/20. No problem if we don't, we definitely do want to increase release frequency.
- [x] Compile mitmweb from source and push the updated minified JS.
- [ ] Finally, cut the release. @mhils will take care of this to check if the new CI handles it well.

**Comment by Jessonsotoventura** [comment]
Time to close this :muscle: !
