### ISSUE TITLE
python3 -m venv venv returns error

### ISSUE THREAD

**Issue by slinkinone** [mitmproxy/mitmproxy#3726]
#### Problem Description
I get the error message after this command:
`python3 -m venv venv`
If be honest, I don't know exactly the reason for that, but maybe the first answer to [this](https://software.intel.com/en-us/forums/intel-distribution-for-python/topic/782894) can be the reason?
 

#### Steps to reproduce the behavior:
```
./dev.sh
+ echo 'Creating dev environment in ./venv...'
Creating dev environment in ./venv...
+ python3 -m venv venv
Error: Command '['/home/user/Documents/github/mitmproxy/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

```

#### System Information
```
Python 3.7.4
x86_64 GNU/Linux 5.3.12-1-MANJARO 
```

**Comment by mhils** [comment]
What's the output of the following commands on your system?
```
python3 --version
python3 -m pip --help
python3 -m venv --help
```

**Comment by slinkinone** [comment]
```
[user@thinkPad ~]$ python3 --version
Python 3.7.4
[user@thinkPad ~]$ python3 -m pip --help

Usage:   
  /usr/bin/python3 -m pip <command> [options]
...

[user@thinkPad ~]$ python3 -m venv --help
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
            [--upgrade] [--without-pip] [--prompt PROMPT]
            ENV_DIR [ENV_DIR ...]

Creates virtual Python environments in one or more target directories.
...
```

**Comment by mhils** [comment]
What happens if you run `python3 -m venv venv` manually?

**Comment by slinkinone** [comment]
[user@thinkPad ~]$ python3 -m venv venv
Error: Command '['/home/user/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

**Comment by mhils** [comment]
Thanks. This looks like a problem with your Python installation and not mitmproxy. I'm sorry, but I'm afraid we can't be of much help here!
