### ISSUE TITLE
mitmproxy 5.0.0 crashes on macOS 10.12 (ok on 10.13)

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#3728]
1. Downloaded https://snapshots.mitmproxy.org/branches/master/mitmproxy-master-osx.tar.gz
2. Crashes on macOS 10.12.6 with error

```
./mitmdump --version
[787] Error loading Python lib '/var/folders/sj/f0p38wnd2dz1483n0zlns51w0000gn/T/_MEIJdk2Qd/Python': dlopen: dlopen(/var/folders/sj/f0p38wnd2dz1483n0zlns51w0000gn/T/_MEIJdk2Qd/Python, 10): Symbol not found: _futimens
  Referenced from: /var/folders/sj/f0p38wnd2dz1483n0zlns51w0000gn/T/_MEIJdk2Qd/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/sj/f0p38wnd2dz1483n0zlns51w0000gn/T/_MEIJdk2Qd/Python
```

-> It runs without problem on 10.13.6

**Comment by mhils** [comment]
Yeah, this is a bit annoying. GitHub Actions currently only provides runners for macos-latest. PyInstaller [wants us to compile on the oldest supported macOS version](https://pythonhosted.org/PyInstaller/usage.html#building-mac-os-x-app-bundles). Two options:

1. We declare that our binaries only support the latest macOS release.
2. We fix compatibility with older versions.

For Option 2, I see the following possibilities:

- Use self-hosted Github CI runners with an old OSX version. This is suuuuper painful, see e.g. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories
- Bring back Travis CI to build binaries. Re-introducing another CI provider is kind of annoying, but should work. We definitely want to exclude that from Pull Requests to keep build times short.

I have no idea how bad Option 1 would be. @mitmproxy/devs, any opinions?

**Comment by Kriechi** [comment]
Option 1 doesn't sound too bad...

**Comment by mhils** [comment]
Ok. Let's try 1 and reopen here if we receive complaints.

**Comment by tomlabaude** [comment]
> 1. We declare that our binaries only support the latest macOS release.

Where/how can we know which macOS versions are supported for a specific mitmproxy release ?

Current last version is 10.15, soon it'll be 11.0, does mitmproxy team simply specify "macos-latest", or you'll guarantee/test let say 10.14/10.15/11.0 and will explicitly mention it somewhere ?

(Also this link fails : https://pythonhosted.org/PyInstaller/usage.html#building-mac-os-x-app-bundles)

**Comment by mhils** [comment]
GitHub now exposes a "10.15" environment, which wasn't the case when we set this up. I've pinned our CI workers to that environment now. We're not going to make any commitments, but this is likely to remain that way until GitHub deprecates it.
