### ISSUE TITLE
Codesigning mitmdump for notarization (with flag 'runtime') makes it crash

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#3729]
Embedding mitmdump binary in a macOS app requires it to be signed with command:

```
codesign -s "Developer ID Application" mitmdump_ok

codesign --display -v mitmdump_ok
Executable=mitmproxy/release/build/binaries/osx/mitmdump_ok
Identifier=mitmdump_ok
Format=Mach-O thin (x86_64)
CodeDirectory v=20200 size=117387 flags=0x0(none) hashes=3664+2 location=embedded
Signature size=9051
Timestamp=25 Nov 2019 at 22:52:07
Info.plist=not bound
TeamIdentifier=AATLWWB4MZ
Sealed Resources=none
Internal requirements count=1 size=172

./mitmdump_ok --version
Mitmproxy: 5.0.0.dev binary
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-18.7.0-x86_64-i386-64bit
```

Apple Notarization of an app now requires to enable Hardened Runtime entitlement and a flag 'runtime' during codesigning:
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues

```
codesign -o runtime -s "Developer ID Application" mitmdump_err

codesign --display -v mitmdump_err
Executable=mitmproxy/release/build/binaries/osx/mitmdump_err
Identifier=mitmdump_err
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=117432 flags=0x10000(runtime) hashes=3664+2 location=embedded
Signature size=9051
Timestamp=25 Nov 2019 at 22:58:33
Info.plist=not bound
TeamIdentifier=AATLWWB4MZ
Runtime Version=10.11.0
Sealed Resources=none
Internal requirements count=1 size=172

./mitmdump_err
[33886] Error loading Python lib '/var/folders/xd/spqtylb911ncthxhqzlxy7d80000gn/T/_MEI4lZWPI/Python': dlopen: dlopen(/var/folders/xd/spqtylb911ncthxhqzlxy7d80000gn/T/_MEI4lZWPI/Python, 10): no suitable image found.  Did find:
	/var/folders/xd/spqtylb911ncthxhqzlxy7d80000gn/T/_MEI4lZWPI/Python: code signature in (/var/folders/xd/spqtylb911ncthxhqzlxy7d80000gn/T/_MEI4lZWPI/Python) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
```

I tried unsuccessfully this fork of pyinstaller which signs all embedded binaries
https://github.com/cculianu/pyinstaller/releases/tag/3.4AppleEventsCodeSign

-> It failed, according to dev _"You can't use the -o runtime option with Pyinstaller because it does evil crap like create a binary from its internal archive and fork() then execute() it.  -o runtime disallows this."_

**Comment by mhils** [comment]
Thanks for filing this. I guess it boils down to 

1. wait for PyInstaller changes to appear, 
2. fix PyInstaller ourselves, or 
3. switch to another packaging tool.

I don't think we have anyone who has the time and motivation to push 2 or 3 forward, and frankly speaking it's not directly a mitmproxy issue. Our default recommendation for OSX is `brew install`, so that's not really affected either.

Lastly, there is some malware that unfortunately embeds our mitmdump binaries as-is and uses a custom addon for their malicious actions (https://discourse.mitmproxy.org/t/majorsignalsearch-malware-using-mitmproxy/1690). If we'd code-sign mitmproxy, they could effectively ship code-signed malware. As long as not signing doesn't really affect us too much, I don't want to enable that.

I'll close this here as I don't see any action that should be taken, but if you or anyone else has an opinion on the topic: Please feel free to chime in nonetheless.

**Comment by Shnitzelil** [comment]
Hi, 
Currently, running mitmproxy on Mac raise message.
It seems that PyInstaller ready for codesiging and more.
Please refer to [PyInstaller Issue 4629](https://github.com/pyinstaller/pyinstaller/issues/4629) it might solve some difficulties.

Maybe it's time to reopen this case?

**Comment by mhils** [comment]
No, see https://github.com/mitmproxy/mitmproxy/issues/3926#issuecomment-612488441. I am open to hearing convincing new use cases though.

**Comment by tomlabaude** [comment]
[PyInstaller comments #4629](https://github.com/pyinstaller/pyinstaller/issues/4629) explain how to :
- codesign your macOS binaries with runtime flag (mandatory for macOS 10.15)
- codesign your 3rd binary built with pyInstaller _without_ runtime flag with an entitlement saying to macOS "It's ok for me to have this 3rd binary without the runtime flag"

I didn't have this solution when I created this issue.
On my side, everything is ok at the moment until Apple will change politic on this and in that case, it won't be an issue with mitmproxy but how _not_ to embed mitmproxy in a macOS app.

FYI, they speak about several entitlements, I succeed to use just one : `com.apple.security.cs.disable-library-validation`

**Comment by Shnitzelil** [comment]
> [PyInstaller comments #4629](https://github.com/pyinstaller/pyinstaller/issues/4629) explain how to :
> 
> * codesign your macOS binaries with runtime flag (mandatory for macOS 10.15)
> * codesign your 3rd binary built with pyInstaller _without_ runtime flag with an entitlement saying to macOS "It's ok for me to have this 3rd binary without the runtime flag"
> 
> I didn't have this solution when I created this issue.
> On my side, everything is ok at the moment until Apple will change politic on this and in that case, it won't be an issue with mitmproxy but how _not_ to embed mitmproxy in a macOS app.
> 
> FYI, they speak about several entitlements, I succeed to use just one : `com.apple.security.cs.disable-library-validation`

The additional entitlement help me too. thank you!
