### ISSUE TITLE
mitmdump --ignore-hosts option can't ignore domain ocsp.digicert.com

### ISSUE THREAD

**Issue by hkglue** [mitmproxy/mitmproxy#3730]
#### Problem Description
I use command：mitmdump -s addos.py --ignore-hosts '(digicert\.com)|(mozilla\.)', then excute command :curl --proxy 127.0.0.1:8080 http://ocsp.digicert.com/ssssssss . 
it can ignore mozilla but can't ignore ocsp.digicert.com
#### Steps to reproduce the behavior:

> $mitmdump -s addos.py --ignore-hosts '(digicert\.com)|(mozilla\.)'
Loading script addos.py
Proxy server listening at http://*:8080
127.0.0.1:63264: clientconnect
127.0.0.1:63267: clientconnect
127.0.0.1:63269: clientconnect
127.0.0.1:63274: clientconnect}
127.0.0.1:63274: GET http://ocsp.digicert.com/ssssssss
              << 200 OK 5b

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 4.0.4
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Darwin-17.7.0-x86_64-i386-64bit

**Comment by mhils** [comment]
See the [documentation of ignore_hosts](https://docs.mitmproxy.org/stable/concepts-options/): 

> In regular mode, only SSL traffic is ignored [...]
