### ISSUE TITLE
Missing command-line tools after pip3 install

### ISSUE THREAD

**Issue by njlr** [mitmproxy/mitmproxy#3731]
#### Problem Description

After I install mitmproxy using pip, I expected the command-line tools to be available. However, the installation succeeds but I cannot find them. 

I _can_ successfully install the binary packages, but these do not work with the Python plugins I plan to use. 

#### Steps to reproduce the behavior:
1. 
```
$ pip3 install mitmproxy
```
2. 
```
$ mitmproxy --version
zsh: command not found: mitmproxy
```
3. 
```
$ locate mitmproxy
-
```

#### System Information

```bash
$ mitmproxy --version
zsh: command not found: mitmproxy

$ python3 --version
Python 3.6.8

$ pip3 --version
pip 19.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)

$  lsb_release -a 
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

**Comment by njlr** [comment]
Found it: 

```bash
$ ~/.local/bin/mitmproxy --version 
Mitmproxy: 4.0.4
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-5.0.0-29-generic-x86_64-with-Ubuntu-18.10-cosmic
```

Perhaps the docs should mention that it will be placed here?

**Comment by mhils** [comment]
We actually revised our docs a couple of days ago and recommend pipx now: https://docs.mitmproxy.org/master/overview-installation/

Does that mitigate this issue?

**Comment by njlr** [comment]
I managed to get things working with `pip3`, so let's close this.
