### ISSUE TITLE
CA certificate issuer name should be identifiable

### ISSUE THREAD

**Issue by selurvedu** [mitmproxy/mitmproxy#3737]
When you install mitmproxy for the first time, you need to trust the root CA certificate that is generated on the first run. The issuer name is "mitmproxy".

I see the following problem: a third party (an attacker) could trick a non-suspecting regular user of mitmproxy to trust *their* certificate. If the person being attacked is not very attentive, they could think that they are trusting their own certificate, not the attacker's.

#### Describe the solution you'd like
I think that the issuer field could contain some information that would help the user to understand if they are going to trust the correct certificate. That could be the user name and/or machine name, or other human-readable text, or an auto-generated ID that would be displayed in the console when starting mitmproxy.

#### Additional context
Of course, when we look at this problem from the attacker's point of view, there is a little disadvantage. This change would potentially lead to leaking the attacker's personal information when performing a MITM attack at someone else, but I don't think this would be a problem in practice. In any case (with or without this change), performing an attack without replacing the auto-generated certificate can be successful only when targeting a user that would blindly click "accept the risk and continue anyway" without checking the issuer field.

**Comment by mhils** [comment]
All fields in an untrusted certificate are just as untrusted as they could be arbitrarily spoofed by an attacker. You would only provide a false sense of security. If you want to check if you have the correct certificate, you need to verify its hash.

If you want to have a different CA certificate, you'd need to generate that yourself.

**Comment by selurvedu** [comment]
> If you want to have a different CA certificate, you'd need to generate that yourself.

Sure.

> If you want to check if you have the correct certificate, you need to verify its hash.

This is also true. But what if mitmproxy told me to verify that the issuer field contains a (pseudo)random string that is shown in the terminal?

**Comment by mhils** [comment]
>  But what if mitmproxy told me to verify that the issuer field contains a (pseudo)random string that is shown in the terminal?

You can also just verify that the certificate fingerprint matches, which is more reliable than introducing pseudorandom strings. :)

**Comment by selurvedu** [comment]
Ok, closing then.
