### ISSUE TITLE
Netflix MSL

### ISSUE THREAD

**Issue by nzsjb** [mitmproxy/mitmproxy#3740]
I've read on another forum that mitmproxy can decode Netflix MSL messages. If this is true

1. Does mitmdump decode them as well?
2. What do I need to do to enable this to happen. Does mitmdump need to see the key handshake sequence between the client and the server?

**Comment by mhils** [comment]
There is no Netflix MSL support in mitmproxy's core. A cursory Google search turns up https://github.com/nohajc/netflix-mitm-proxy/.

**Comment by nzsjb** [comment]
Apologies - I should have looked.
