### ISSUE TITLE
App do not trust my proxy’s certificate

### ISSUE THREAD

**Issue by zhuzcpzcp** [mitmproxy/mitmproxy#3741]
I have download certificate in browser and trust the proxy’s certificate in my android phone.But many apps still cannot connect the internet while others can,and the log of mitmproxy show “the client do not trust the proxy’s certificate for...”.  It seems that many apps check the certificate and find the certificate is sended by a middleman.So my question is how to let these apps to trust the proxy’s certificate.

**Comment by zhuzcpzcp** [comment]
I almost have got the answer in docs. It said I should patch the apps,but it is too difficult to for me.Is there any way else？

**Comment by typoon** [comment]
Depends on the app and Android version. You could try something like Frida (https://frida.re/) or Xposed (https://www.xda-developers.com/xposed-framework-hub/) to patch it during execution. For some apps, you might find patchers online to remove the certificate pining. Check out those things and see if they help.

**Comment by TonyStark** [comment]
Quicker way >> https://github.com/shroudedcode/apk-mitm
