### ISSUE TITLE
Some random keys   are not writen to keylog

### ISSUE THREAD

**Issue by zhuzcpzcp** [mitmproxy/mitmproxy#3744]
I  start mitmproxy with cmd " SSLKEYLOGFILE="/root/mitmproxy/sslkeylogfile.txt" mitmproxy  --mode upstream:http://192.1“ "  .  I  find  some random keys are not writen in sslkeylogfile.txt  ,  and I check it with  my wireshark.   How did it happen?

**Comment by mhils** [comment]
I don't know as I don't know how to reproduce this. Any pointers?
