### ISSUE TITLE
How can I redirect request  after response flow 

### ISSUE THREAD

**Issue by hucailai** [mitmproxy/mitmproxy#3746]
`
class Modify:
        def response(self, flow):
                   # parse the flow and redirct to another web 
                    if ....:
                         redirect....
addons = [
        Modify()
]
`

How can I redirect to another web after parse the response flow

I got the sample of  "redirect_requests.py" , but it's redirct before response.

I need redirect after response, how can I do.

@mhils

**Comment by typoon** [comment]
Maybe add the `Location` header to the response? That way the browser will redirect you to the URL specified there.

flow.response.headers['Location'] = 'http://www.example.com'

**Comment by hucailai** [comment]
> Maybe add the `Location` header to the response? That way the browser will redirect you to the URL specified there.
> 
> flow.response.headers['Location'] = 'http://www.example.com'

@typoon , thanks

Set Location header，  it doesn't work。

**Comment by typoon** [comment]
Mind sharing your code and how are you validating that it doesn't work?

**Comment by KORraNpl** [comment]
@typoon Is the header though? I would expect that `flow.response.status_code` should be changed as well, i.e. to 301/302 to make sure that client will even bother with `Location` header.

@hucailai On the other note, I think it was requested by authors to ask questions at https://stackoverflow.com/questions/tagged/mitmproxy

**Comment by mhils** [comment]
You probably want use Response.make(302, ...).

Also, please use StackOverflow. I wish we could, but just can't handle the volume of user questions here.
