### ISSUE TITLE
Regex not working in Replacement patterns

### ISSUE THREAD

**Issue by 2NuFyeat4PZt** [mitmproxy/mitmproxy#3749]
#### Problem Description
-R :~q:GET /.*$:GET /example.html
Does not match GET requests despite "GET /.*$" being a valid regex.

-R :~q:/.*$:/example.html triggers replacement of text after all "/" in headers; expanding the regex should not cause it to fail.

#### Steps to reproduce the behavior:
1. run mitmdump in reverse mode with -R :~q:GET /.*$:GET /example.html
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 4.0.4
Python:    3.6.9
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by mhils** [comment]
We currently run replacements on the request path only: 
https://github.com/mitmproxy/mitmproxy/blob/62b89e9447a4fc93b072b74b52e992ff5c17b2c3/mitmproxy/net/http/request.py#L131-L150

I'd be happy to merge a PR that changes this to include the full first line. Here is our logic to assemble and read the first line: https://github.com/mitmproxy/mitmproxy/blob/62b89e9447a4fc93b072b74b52e992ff5c17b2c3/mitmproxy/net/http/http1/assemble.py#L44-L73
https://github.com/mitmproxy/mitmproxy/blob/62b89e9447a4fc93b072b74b52e992ff5c17b2c3/mitmproxy/net/http/http1/read.py#L241-L266

**Comment by 2NuFyeat4PZt** [comment]
Apologies for the the delay in getting back to you; I've been off for the holidays.

To be honest, it's beyond me to critique what you have proposed; I'm a network engineer with limited programming/development (and zero github) experience. 

If this is merged, how would I access the revised code?

**Comment by 2NuFyeat4PZt** [comment]
Do you need me to do something?

**Comment by mhils** [comment]
You currently cannot use our replacements feature to change parts of the request line. As a workaround, I would suggest to write a mitmproxy addon that conditionally replaces `flow.request.path`.

If you want to upgrade the replacement feature to also support replacements on the first line, you (or anyone else) are welcome to send a pull request.

**Comment by MarkKoester** [comment]
In this particular case you can use the ~m operator in your replacement pattern to only match requests using the GET method

**Comment by 2NuFyeat4PZt** [comment]
Thanks again for your help Mark. 

For the benefit of any other poor soul trying to do this, the following filter expression requires quotes to work:  ":~q ~m GET:.*:/replacement.html".

Documentation update PR raised.
