### ISSUE TITLE
The issue with a connection to the remote server by https (sslv3, tls)

### ISSUE THREAD

**Issue by YuriyTigiev** [mitmproxy/mitmproxy#3751]
#### Problem Description
The issue with connection to a remote server which uses sslv3/tls1  by https protocol 

[root@localhost bin]# ./mitmdump -R https://localhost -p 8088
-R is used for specifying replacements.
To use mitmproxy in reverse mode please use --mode reverse:SPEC instead
Proxy server listening at http://*:8088
127.0.0.1:52072: clientconnect
127.0.0.1:52072: GET https://172.30.129.98:8446/script

 << Cannot establish TLS with 172.30.129.98:8446 (sni: 172.30.129.98): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",)
127.0.0.1:52072: clientdisconnect

#### Steps to reproduce the behavior:
No way to reproduce, because the remote server is on the intranet. 

#### System Information
Mitmproxy: 6.0.0.dev (+494, commit 67955fa)
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core

**Comment by mhils** [comment]
The error messages states that we failed establishing TLS with the upstream server. Some reasons why this could be:

1. The upstream server and mitmproxy can't agree on ciphers, TLS version, etc. You should upgrade the upstream server, or lower the requirements in mitmproxy (see the ssl_* options).
2. The upstream server expects a client certificate.

In any case, this is not a mitmproxy bug.

**Comment by YuriyTigiev** [comment]
Does the software support  tlsv1/sslv3 client? Should I install special software for that?  
The remote server to which we connecting is legacy which support only those protocols.

**Comment by mhils** [comment]
mitmproxy itself does support SSLv3/TLSv1, but it really depends on which OpenSSL version is used by [pyca/cryptography](https://github.com/pyca/cryptography). AFAIK the releases provided by cryptography support TLS 1.0+ only.

I would be interested to know if setting `ciphers_server` to `ALL` has any positive effect for you.

For reference, the following code lists all available ciphers available to mitmproxy.
```python
from OpenSSL import SSL
ctx = SSL.Context(SSL.SSLv23_METHOD)
ctx.set_cipher_list(b"ALL")
conn = SSL.Connection(ctx)
print(conn.get_cipher_list())
```

**Comment by YuriyTigiev** [comment]
I will briefly describe what is a goal

1) client service should connect to the proxy server by https TLS 1.2 
2) the proxy server should forward the request from the client to the destination server by https TLS 1.0 get a response and return it to the client service 
3) (optional) if is it possible the proxy should send a request from the client IP but I think it is impossible.

With which options I should run the "mitmdump" to reach a goal.

**Comment by YuriyTigiev** [comment]
Hello 

I have run your script with parameters 

`[root@localhost ~]# mitmdump -p 8090 --set ssl_insecure=true --set ssl_version_client=all --set ssl_version_server=all -s proxy_test.py`

and got a result

```
['ECDHE-ECDSA-AES256-GCM-SHA384', 'ECDHE-RSA-AES256-GCM-SHA384', 'DHE-DSS-AES256-GCM-SHA384', 'DHE-RSA-AES256-GCM-SHA384', 'ECDHE-ECDSA-CHACHA20-POLY1305', 'ECDHE-RSA-CHACHA20-POLY1305', 'DHE-RSA-CHACHA20-POLY1305', 'ECDHE-ECDSA-AES256-CCM8', 'ECDHE-ECDSA-AES256-CCM', 'DHE-RSA-AES256-CCM8', 'DHE-RSA-AES256-CCM', 'ADH-AES256-GCM-SHA384', 'ECDHE-ECDSA-AES128-GCM-SHA256', 'ECDHE-RSA-AES128-GCM-SHA256', 'DHE-DSS-AES128-GCM-SHA256', 'DHE-RSA-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES128-CCM8', 'ECDHE-ECDSA-AES128-CCM', 'DHE-RSA-AES128-CCM8', 'DHE-RSA-AES128-CCM', 'ADH-AES128-GCM-SHA256', 'ECDHE-ECDSA-AES256-SHA384', 'ECDHE-RSA-AES256-SHA384', 'DHE-RSA-AES256-SHA256', 'DHE-DSS-AES256-SHA256', 'ECDHE-ECDSA-CAMELLIA256-SHA384', 'ECDHE-RSA-CAMELLIA256-SHA384', 'DHE-RSA-CAMELLIA256-SHA256', 'DHE-DSS-CAMELLIA256-SHA256', 'ADH-AES256-SHA256', 'ADH-CAMELLIA256-SHA256', 'ECDHE-ECDSA-AES128-SHA256', 'ECDHE-RSA-AES128-SHA256', 'DHE-RSA-AES128-SHA256', 'DHE-DSS-AES128-SHA256', 'ECDHE-ECDSA-CAMELLIA128-SHA256', 'ECDHE-RSA-CAMELLIA128-SHA256', 'DHE-RSA-CAMELLIA128-SHA256', 'DHE-DSS-CAMELLIA128-SHA256', 'ADH-AES128-SHA256', 'ADH-CAMELLIA128-SHA256', 'ECDHE-ECDSA-AES256-SHA', 'ECDHE-RSA-AES256-SHA', 'DHE-RSA-AES256-SHA', 'DHE-DSS-AES256-SHA', 'DHE-RSA-CAMELLIA256-SHA', 'DHE-DSS-CAMELLIA256-SHA', 'AECDH-AES256-SHA', 'ADH-AES256-SHA', 'ADH-CAMELLIA256-SHA', 'ECDHE-ECDSA-AES128-SHA', 'ECDHE-RSA-AES128-SHA', 'DHE-RSA-AES128-SHA', 'DHE-DSS-AES128-SHA', 'DHE-RSA-SEED-SHA', 'DHE-DSS-SEED-SHA', 'DHE-RSA-CAMELLIA128-SHA', 'DHE-DSS-CAMELLIA128-SHA', 'AECDH-AES128-SHA', 'ADH-AES128-SHA', 'ADH-SEED-SHA', 'ADH-CAMELLIA128-SHA', 'RSA-PSK-AES256-GCM-SHA384', 'DHE-PSK-AES256-GCM-SHA384', 'RSA-PSK-CHACHA20-POLY1305', 'DHE-PSK-CHACHA20-POLY1305', 'ECDHE-PSK-CHACHA20-POLY1305', 'DHE-PSK-AES256-CCM8', 'DHE-PSK-AES256-CCM', 'AES256-GCM-SHA384', 'AES256-CCM8', 'AES256-CCM', 'PSK-AES256-GCM-SHA384', 'PSK-CHACHA20-POLY1305', 'PSK-AES256-CCM8', 'PSK-AES256-CCM', 'RSA-PSK-AES128-GCM-SHA256', 'DHE-PSK-AES128-GCM-SHA256', 'DHE-PSK-AES128-CCM8', 'DHE-PSK-AES128-CCM', 'AES128-GCM-SHA256', 'AES128-CCM8', 'AES128-CCM', 'PSK-AES128-GCM-SHA256', 'PSK-AES128-CCM8', 'PSK-AES128-CCM', 'AES256-SHA256', 'CAMELLIA256-SHA256', 'AES128-SHA256', 'CAMELLIA128-SHA256', 'ECDHE-PSK-AES256-CBC-SHA384', 'ECDHE-PSK-AES256-CBC-SHA', 'SRP-DSS-AES-256-CBC-SHA', 'SRP-RSA-AES-256-CBC-SHA', 'SRP-AES-256-CBC-SHA', 'RSA-PSK-AES256-CBC-SHA384', 'DHE-PSK-AES256-CBC-SHA384', 'RSA-PSK-AES256-CBC-SHA', 'DHE-PSK-AES256-CBC-SHA', 'ECDHE-PSK-CAMELLIA256-SHA384', 'RSA-PSK-CAMELLIA256-SHA384', 'DHE-PSK-CAMELLIA256-SHA384', 'AES256-SHA', 'CAMELLIA256-SHA', 'PSK-AES256-CBC-SHA384', 'PSK-AES256-CBC-SHA', 'PSK-CAMELLIA256-SHA384', 'ECDHE-PSK-AES128-CBC-SHA256', 'ECDHE-PSK-AES128-CBC-SHA', 'SRP-DSS-AES-128-CBC-SHA', 'SRP-RSA-AES-128-CBC-SHA', 'SRP-AES-128-CBC-SHA', 'RSA-PSK-AES128-CBC-SHA256', 'DHE-PSK-AES128-CBC-SHA256', 'RSA-PSK-AES128-CBC-SHA', 'DHE-PSK-AES128-CBC-SHA', 'ECDHE-PSK-CAMELLIA128-SHA256', 'RSA-PSK-CAMELLIA128-SHA256', 'DHE-PSK-CAMELLIA128-SHA256', 'AES128-SHA', 'SEED-SHA', 'CAMELLIA128-SHA', 'IDEA-CBC-SHA', 'PSK-AES128-CBC-SHA256', 'PSK-AES128-CBC-SHA', 'PSK-CAMELLIA128-SHA256']
Loading script proxy_test.py
Proxy server listening at http://*:8090
127.0.0.1:56340: clientconnect
127.0.0.1:56340: GET https://172.30.129.98:8446/script
 << Cannot establish TLS with 172.30.129.98:8446 (sni: 172.30.129.98): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",)
127.0.0.1:56340: clientdisconnect

```
