### ISSUE TITLE
can't establish TLS with client <....>:TlsException("(-1,unexpected EOF)")

### ISSUE THREAD

**Issue by sytpb** [mitmproxy/mitmproxy#3753]
#### Problem Description
can't establish TLS with client <....>:TlsException("(-1,unexpected EOF)")

#### Steps to reproduce the behavior:
1. mitmproxy installed in win7  
2. two cell phones connect with mitproxy , 
3.  one is HuaWei   , another is XiaoMi ,    Huawei runs ok ,   XiaoMi show me error as above . i don't know why ?  

#### System Information
Paste the output of "mitmproxy --version" here.
4.0.4

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!

**Comment by TonyStark** [comment]
Can you provide more detail of your android system information of your both phone.
Because i m having same issue, like yours
https://stackoverflow.com/questions/59509156/cannot-establish-tls-with-client
