### ISSUE TITLE
Cannot parse Client Hello when too large

### ISSUE THREAD

**Issue by EndUser509** [mitmproxy/mitmproxy#3755]
#### Problem Description
Starting recently the iOS Youtube client sometimes sends ClientHello requests what contain a large 'key_share' extension. The request becomes too large for one frame. However the peeking into the socket in the get_client_hello() function can only see as far as the first frame and therefore the parsing fails.

The attached [example.zip](https://github.com/mitmproxy/mitmproxy/files/3991840/example.zip) contains a pcap of such a ClientHello and the resulting error message.

My feeling is that instead of throwing an error when peek returns less data than expected, the get_client_hello() function should wait for more data to be available on the socket.

#### Steps to reproduce the behavior:
1. Use Youtube on an iOS 13 device and wait.  

#### System Information
Mitmproxy: 5.0.0.dev <- pulled from github in 2018
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.18.0-80.11.2.el8_0.x86_64-x86_64-with-centos-8.0.1905-Core

**Comment by mhils** [comment]
Thanks! This definitely is bad parsing code on our end. I believe I have this fixed on the sans-io branch at https://github.com/mitmproxy/mitmproxy/blob/07a6574d498f71d07f738ea534aca8a91aa1a6b4/test/mitmproxy/proxy2/layers/test_tls.py#L56, but that may take a bit until it its production.

**Comment by EndUser509** [comment]
Thanks for the reply. Good to hear that this is fixed in a future version. I will patch my own copy of the code to wait and try again if there is not enough data.

**Comment by mhils** [comment]
This should be fixed on master. If that's not the case, please open a new issue!
