### ISSUE TITLE
about multi-network support

### ISSUE THREAD

**Issue by xLabel** [mitmproxy/mitmproxy#3756]
does it support specifying outbound ip ?
E.g:
intranet ip ->  extranet ip
10.0.0.2     ->  A
10.0.0.3     ->  B

userA-> 10.0.0.2-> A-> target internet
userB-> 10.0.0.3-> B-> target internet

**Comment by mhils** [comment]
There's nothing within mitmproxy, but you should be able to configure that with `ip route` etc. We just open regular sockets. :)
