### ISSUE TITLE
How to grab tcp at the same time and forward http to other tools

### ISSUE THREAD

**Issue by ldbfpiaoran** [mitmproxy/mitmproxy#3759]
How to grab tcp at the same time and forward http to other tools
I need client-> mitmproxy-> burp-> server
But i don't want to lose tcp traffic so what should i do
tcp_message (flow: tcp.TCPMessage) does not correctly forward http

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
