### ISSUE TITLE
Cannot establish TLS with client in android

### ISSUE THREAD

**Issue by TonyStark** [mitmproxy/mitmproxy#3761]
Everything works just except one website..

Site has self sign certificate, so when i try to open in firefox i get warning about potential risk.

`xyxyxyx.com uses an invalid security certificate. The certificate is not trusted because it is self-signed. Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT`

So i accept and continue, then site open.
This is Firefox side, now lets get back on android app which uses same site to send/receive data.

Since i'm on android 10 i have modified app res/xml network_config to capture ssl request from app to server. Also installed mitm cert as system and user too.

Now i setup everything and start capturing request by mitmproxy command. And then....

`Certificate verification error for www.kjljjlk.com.mx:
                          ("hostname 'www.hjkhjk.com.mx' doesn't match either
                          of 'a248.e.jhkhkdsfsf.net', '*.dsfsfds-sdfsdfdsf.net',
                          '*.sdffdsfsdf.net', '*.dsfsdfdsf-sdfsfsf.net',
                          '*.dfsfsdsdf.net'",)`

Using mitmdump command.....
`<< Cannot establish TLS with client (sni: xyxyxyxy.com): TlsException("SSL handshake error: Error([('SSL routines', 'tls_process_client_hello', 'parse tlsext')])")`

I also try with burpsuite, but i get unknown ca error
So i dont know why dont work this

`Mitmproxy: 5.0.0 binary Python:    3.7.5 OpenSSL:   OpenSSL 1.1.0j  20
Nov 2018 Platform: 
Linux-5.3.0-7625-generic-x86_64-with-debian-buster-sid`

I also posted at. 
https://stackoverflow.com/questions/59509156/cannot-establish-tls-with-client
Thanks for nice tool :)

**Comment by TonyStark** [comment]
![Screenshot_2019-12-29_14-32-00](https://user-images.githubusercontent.com/5529450/71554672-72c8de00-2a48-11ea-9a59-1240fc312ee6.png)

**Comment by mhils** [comment]
This belongs to StackOverflow, I answered there.
