### ISSUE TITLE
Custom web view for mitmproxy

### ISSUE THREAD

**Issue by abinhho** [mitmproxy/mitmproxy#3763]
Hello,
I search around but could not find the answer so I'd like to ask here.
I installed mitmproxy already, now I would like to develop a webapp (EX: VueJS + Python Flask) that users can view their request and response via mitmproxy server. I don't know how to read stored data via `python flask`.

Please help!
Sorry I am new here.

**Comment by mhils** [comment]
It looks like you want to build something like mitmweb? You can take a look at mitmweb's source code (https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/web/master.py)

**Comment by abinhho** [comment]
@mhils Thanks for your answered.
I read `tools/web/master.py` already. But still not figure out what should I do.
This is a context I'm trying to do:
- Install mitmproxy into a server
- Run mitmproxy as background.
- Run 1 API service uses such as `Flask` that can return user request today, yesterday or specify datetime.

So, could you please tell me which steps I should be do for this context.
Please help !

**Comment by mhils** [comment]
A simple way to go would be to just run a regular HTTP server from an Addon.
