### ISSUE TITLE
brew install mitmproxy - uncertain dependency between version 2 and 3 of python

### ISSUE THREAD

**Issue by punnerud** [mitmproxy/mitmproxy#3764]
#### Problem Description
When running 'brew install mitmproxy' it have dependency to just python without specifying Python2 or Python3, resulting that Python2 is removed on Mac OS Catalina.

#### Steps to reproduce the behavior:
1. brew install mitmproxy
2. Try to run 'python2' afterward

## Solution ##
Change dependency from 'python' to 'python3' as described where:
https://docs.brew.sh/Homebrew-and-Python

Where to change:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/mitmproxy.rb
https://formulae.brew.sh/api/formula/mitmproxy.json

**Comment by punnerud** [comment]
Temporarily workaround for users having problem after running 'brew install mitmproxy':
`brew reinstall python@2`

**Comment by Kriechi** [comment]
Please report this to homebrew directly.
We, the mitmproxy maintainers & community, have no direct control or responsibilities for the downstream packaging and distributors.
