### ISSUE TITLE
self generated ssl cert can't generate the interception certificate

### ISSUE THREAD

**Issue by c4pr1c3** [mitmproxy/mitmproxy#377]
I followed the guide on http://mitmproxy.org/doc/ssl.html , but the self generated PEM can't be used to generate the interception certificate on the fly. In browser, only the self generated cert is present. 

I used the following command line to produce the above result:

mitmproxy --cert ca.pem

However, I replaced the ~/.mitmproxy/mitmproxy-ca.pem with my self-generated cert ca.pem and run using the following command:

mitmproxy

It works! Interception certificate is generated on-the-fly.

runtime configuration as follows:

$ pip freeze
BeautifulSoup==3.2.1
cffi==0.8.6
cryptography==0.6
mercurial==3.0.2
mitmproxy==0.10.1
pyOpenSSL==0.14
pycparser==2.10
pypimirror==1.0.16.4
six==1.8.0
vboxapi==1.0
wsgiref==0.1.2
zc.lockfile==1.1.0

$ python --version
Python 2.7.8

$ mitmproxy --version
mitmproxy 0.10.1

OS: mac os x 10.9
Homebrew installed mitmproxy

**Comment by jkryanchou** [comment]
@mhils It confused me a lot. I have tried so many times to specify `--confdir=/path/mycadir/` to my own CA directory which contains `ca.pem`, `ca.key`, `ca.crt` by using `openssl` to self signed. while it still re-generated `mitmproxy-ca.pem` when I run `mitmproxy --confdir=/path/mydir/` again and again.
