### ISSUE TITLE
Multi devices support?

### ISSUE THREAD

**Issue by abinhho** [mitmproxy/mitmproxy#3773]
**Is your feature request related to a problem? Please describe.**
Hello again,
For example I have 10 Iphone, I1, I2.. I10 and setting mimtproxy to each of Iphone.
Then in web view, how could I know which request is of which Iphone?.
I researched each of request, header have attach an uniqueID of each device but seem not have.

Please advice me!

**Comment by mhils** [comment]
You can differntiate them by the client IP. In the future, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions.

Thanks!

**Comment by abinhho** [comment]
Thank you!
