### ISSUE TITLE
Replace "Toggle Proxy" addon recommendation in client replay tutorial

### ISSUE THREAD

**Issue by aesyondu** [mitmproxy/mitmproxy#3775]
#### Problem Description
In https://github.com/mitmproxy/mitmproxy/blame/master/docs/src/content/tute-clientreplay.md#L35, Toggle Proxy is linked, but it no longer exists.

#### Steps to reproduce the behavior:
1. GOTO https://docs.mitmproxy.org/stable/tute-clientreplay/
2. GOTO https://addons.mozilla.org/en-us/firefox/addon/toggle-proxy-51740/
3. SEE Oops! We can’t find that page

#### System Information
DOCS

**Comment by mhils** [comment]
Thanks for the report. I'd be happy for a PR that replaces it with something else, e.g. FoxyProxy.

**Comment by globefire** [comment]
@mhils is this issue taken? If not can you please assign this issue to me?

**Comment by diegotony** [comment]
@mhils  the issue was resolved?

**Comment by ghunaaugest** [comment]
Thanks community
