### ISSUE TITLE
Transparent proxy based DNS support?

### ISSUE THREAD

**Issue by liudonghua123** [mitmproxy/mitmproxy#3777]
**Is your feature request related to a problem? Please describe.**
I want to build a transparent proxy server which proxy all the http/https request. the clients has a customized dns server which resolve some domains to the transparent proxy server. For example, `google.com` will resolve to `10.0.0.1` which is the transparent proxy server, and When the user navigation `google.com`, all the traffics of `google.com` will send to `10.0.0.1`.

#### Describe the solution you'd like
Add some options which support this feature and let the proxy server listen 80/443. And ready for accepting request from network.

**Comment by mhils** [comment]
Did you see https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/dns_spoofing.py? :)

**Comment by liudonghua123** [comment]
@mhils Thanks for your tips. It seems similar to my requirements. I will try it. 😃
