### ISSUE TITLE
ProtocolException("Error in HTTP connection: Http2ZombieException('Connection already dead')")

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#3780]
#### Problem Description

The thumbnails on YouTube don't load after navigating around the page. I'm not sure what exactly is happening, it seems to be related to HTTP 2? See the attached video. Sorry for the video being such a hot mess. During recording it didn't happen after the first navigation (of course, why would it) and it took a moment to be reproducible. When I opened the image in a new tab it still didn't load. The second time I [alt+enter]ed it into a new tab.

In dev tools the requests appear as `(pending)`. So mitmproxy never tells Chrome that the request failed?

![Selection_561](https://user-images.githubusercontent.com/679144/72176316-69dbf300-33de-11ea-80e2-09fe60047eb7.png)

#### Steps to reproduce the behavior:
1. Start `mitmdump`
2. Open Chromium
3. Browse to www.youtube.com
4. Click on a video
5. Go back to the front page by clicking on the logo
6. Most thumbnails will not load (you might need to repeat 4+5). I assume it is related to the error in the title. No amount of waiting makes them load.

Now the question is: is YouTube or Chromium doing something funny or is it mitmproxy that has the issue?

#### System Information

```
Mitmproxy: 5.0.1
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.3.0-26-generic-x86_64-with-Ubuntu-19.10-eoan
```

#### Attachments
video: http://www.prinzhorn.me/mitmproxy/screencast.mp4
video of me hovering the thumbnails: http://www.prinzhorn.me/mitmproxy/screencast-hover.mp4
dump: http://www.prinzhorn.me/mitmproxy/youtube

**Comment by mhils** [comment]
Thanks for the extensive write-up! The obvious workaround is to disable HTTP2 in mitmproxy, but we want to get that fixed anyways of course.

/cc @Kriechi 

(somewhat refs #1775)

**Comment by Kriechi** [comment]
I can reproduce the issue with Firefox on macOS as well.
This problem seems related to RESET_STREAM, when the browser sends a request, but a few milliseconds sends a RESET for that same stream. The server already responded with the full body. Then something stalls/breaks/blocks - I haven't found that last bit yet...

**Comment by Kriechi** [comment]
Found the underlying problem - it is in one of our dependencies that take care of the low-level heavy-lifting for HTTP/2.
https://github.com/python-hyper/hyper-h2/issues/1210

**Comment by Prinzhorn** [comment]
Nice, thank you @Kriechi
