### ISSUE TITLE
 Version 5.0.1 cannot display https requests, 4.04 can display https requests

### ISSUE THREAD

**Issue by crusj** [mitmproxy/mitmproxy#3781]
#### Problem Description

Version 5.0.1 cannot display https requests, 4.04 can display https requests
v5.01 I tried for a long time，v5.0.1 need additional configuration?

#### System Information
v5.0.1 linux

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
