### ISSUE TITLE
Connecting to proxy directly using browser throws "Invalid certifcate" error. Causes MITMproxy to be blocked by some programs.

### ISSUE THREAD

**Issue by Hacksawfred3232** [mitmproxy/mitmproxy#3783]
#### Problem Description
When attempting to connect to the proxy port via using something like Edge, Edge reports that
the certificate is invalid. The most striking quirk about this is the absence of a subject line. I'm suspecting that this gets set upon receiving a server address from the client. It looks like some programs have a way of testing the proxy due to this quirk. When either set in the proxy settings for the target, or using a program to force the target to use a proxy, the target program reports a "self-signed certificate" in the chain, although it is reading the certificate store to check root certificates, which the MITMProxy's certificate is installed in there. A forced installation of the root certificate into "AuthRoot" - as indicated in RegEdit - was also performed. In addition, the absence of an additional certificate to verify the presence of HSTS verification might be related. 

#### Steps to reproduce the behaviour:
1. Start any target program that uses libcurl 7.55.1-DEV or something akin to this version. 
2. Start up MITMProxy. Settings used: "--anticache, -k". I am using the windows version installed via pip.
3. Attempt to connect to the proxy on the proxy port (In this case for me, its 8080). You should get an error about an invalid certificate, where the certificate has a blank subject line.
4. Attempt to connect to a secure remote host with the target program.
Outcome - You should get an error through either debug or a visible prompt that the target
can't connect to the remote host due to a "self-signed certificate".

#### System Information
mitmproxy: 4.0.4
Python:    3.7.4
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-10-10.0.18362-SP0

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by Hacksawfred3232** [comment]
Nevermind. After trying Burpsuite as the proxy program, its exhibitng the same problem. "Self signed certificate". Burpsuite does not return anything upon connection, probs due to using HTTP not HTTPS for the proxy port. How fucking buggy is this "libcurl" lib anyway? The target program opens the reg key for CA cert store, but doesn't take notice of the fact that Mitmproxy or "PortSwigger" is installed in the CA cert store? And it does not have HSTS as well. What is it even doing? 
Some advice please? I am honestly confused out of my mind on this.  🤦‍♂ 
Also, mitmproxy is already updated?
```
Requirement already satisfied: mitmproxy in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (4.0.4)
Requirement already satisfied: sortedcontainers<2.1,>=1.5.4 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (2.0.5)
Requirement already satisfied: cryptography<2.4,>=2.1.4 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (2.3.1)
Requirement already satisfied: ldap3<2.6,>=2.5 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (2.5.2)
Requirement already satisfied: h2<4,>=3.0.1 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (3.1.1)
Requirement already satisfied: pyasn1<0.5,>=0.3.1 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (0.4.7)
Requirement already satisfied: ruamel.yaml<0.16,>=0.13.2 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (0.15.100)
Requirement already satisfied: blinker<1.5,>=1.4 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (1.4)
Requirement already satisfied: tornado<5.2,>=4.3 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (5.1.1)
Requirement already satisfied: hyperframe<6,>=5.1.0 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (5.2.0)
Requirement already satisfied: brotlipy<0.8,>=0.7.0 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (0.7.0)
Requirement already satisfied: kaitaistruct<0.9,>=0.7 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (0.8)
Requirement already satisfied: passlib<1.8,>=1.6.5 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (1.7.1)
Requirement already satisfied: pyparsing<2.3,>=2.1.3 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (2.2.2)
Requirement already satisfied: certifi>=2015.11.20.1 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (2019.9.11)
Requirement already satisfied: pyOpenSSL<18.1,>=17.5 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (18.0.0)
Requirement already satisfied: click<7,>=6.2 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (6.7)
Requirement already satisfied: urwid<2.1,>=2.0.1 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (2.0.1)
Requirement already satisfied: pydivert<2.2,>=2.0.3; sys_platform == "win32" in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (2.1.0)
Requirement already satisfied: wsproto<0.12.0,>=0.11.0 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (0.11.0)
Requirement already satisfied: pyperclip<1.7,>=1.6.0 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from mitmproxy) (1.6.5)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from cryptography<2.4,>=2.1.4->mitmproxy) (1.12.3)
Requirement already satisfied: idna>=2.1 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from cryptography<2.4,>=2.1.4->mitmproxy) (2.8)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from cryptography<2.4,>=2.1.4->mitmproxy) (0.24.0)
Requirement already satisfied: six>=1.4.1 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from cryptography<2.4,>=2.1.4->mitmproxy) (1.12.0)
Requirement already satisfied: hpack<4,>=2.3 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from h2<4,>=3.0.1->mitmproxy) (3.0.0)
Requirement already satisfied: h11~=0.7.0 in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from wsproto<0.12.0,>=0.11.0->mitmproxy) (0.7.0)
Requirement already satisfied: pycparser in c:\users\hacks\appdata\local\programs\python\python37\lib\site-packages (from cffi!=1.11.3,>=1.7->cryptography<2.4,>=2.1.4->mitmproxy) (2.19)
```

**Comment by mhils** [comment]
This looks like a Layer 8 error to me, maybe https://docs.mitmproxy.org/stable/concepts-modes/ may be helpful for you.

**Comment by Hacksawfred3232** [comment]
And that's going to help because? I'm forcing the trafic to reroute through the proxy via Proxifier. There isn't a configuration error as far as I can tell. The CA cert is installed inside the store, and the target program is looking inside the store to verify the certificate, but refusing to accept it.
