### ISSUE TITLE
need a python interface to get real IP but not mitm's IP

### ISSUE THREAD

**Issue by weiyuchen** [mitmproxy/mitmproxy#3784]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when I want to get the attacker's real ip, I'm using python scripts in a addons method, but I try all 5 events style, I can only get mitm's ip by using:
 `flow.client_conn.address`

#### Describe the solution you'd like
I'd like to know if there has had such a interface, or if there is a plan to get the real ip.

**Comment by mhils** [comment]
`flow.client_conn.address` should have the client's IP. I'm almost sure this is an issue because of how you redirect traffic to mitmproxy.
