### ISSUE TITLE
Any workaround incase the ISP blocks the CONNECT tunnel?

### ISSUE THREAD

**Issue by mariolatiffathy** [mitmproxy/mitmproxy#3788]
**Is your feature request related to a problem? Please describe.**

Actually, the problem is that I can't load any HTTPS site because my ISP blocks the CONNECT tunnel, and it is a problem for any proxy server that I use (not only mitmproxy). The connection gets reset by peer on requesting any HTTPS site.

I was wondering if there's a workaround for this, or the `CONNECT` tunnel is always necessary to be used?

**Comment by mhils** [comment]
Shame on your ISP I guess. You could try running mitmproxy in SOCKS mode or using an additional SSL termination to run a ["Secure Web Proxy"](https://www.chromium.org/developers/design-documents/secure-web-proxy).

I'm closing this here as it's not really a mitmproxy bug. Please use StackOverflow for general support. :)
