### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by alexolivier** [mitmproxy/mitmproxy#379]
I'm struggling to get this installed. It is erroring out when installing the netlib package. Any ideas?

```
pip install --src . -r requirements.txt

Command /usr/bin/python -c "import setuptools, tokenize; 
__file__='/Users/alexolivier/repos/mitmproxy/netlib/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps failed with error code 1 in /Users/alexolivier/repos/mitmproxy/netlib
```

Python 2.7.5

Darwin Alex-Oliviers-MacBook-Pro.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64

**Comment by edvernon** [comment]
mhils, hi Max,

I am also having an issue trying to install beets. on centos 7.
Although what I am experiencing is compile error with gcc.
Please help.
Thank you, 
Ed

Error output is below and versions, let me know if you need more pleasel
$ pip --version
pip 7.1.2 from /usr/lib/python2.7/site-packages (python 2.7)

$ sudo pip install beets
Collecting beets
Requirement already satisfied (use --upgrade to upgrade): munkres in /usr/lib/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): unidecode in /usr/lib64/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): jellyfish in /usr/lib/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): musicbrainzngs>=0.4 in /usr/lib/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.27 in /usr/lib/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /usr/lib/python2.7/site-packages (from beets)
Collecting pyyaml (from beets)
  Using cached PyYAML-3.11.tar.gz
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml
  Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-99nnKA/pyyaml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpG5Znlbpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/cyaml.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/serializer.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/scanner.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/loader.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/emitter.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/events.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/composer.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/resolver.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/nodes.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/__init__.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/parser.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/reader.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/dumper.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/tokens.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/error.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/constructor.py -> build/lib.linux-x86_64-2.7/yaml
  copying lib/yaml/representer.py -> build/lib.linux-x86_64-2.7/yaml
  running build_ext
  creating build/temp.linux-x86_64-2.7
  checking if libyaml is compilable
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
  checking if libyaml is linkable
  gcc -pthread build/temp.linux-x86_64-2.7/check_libyaml.o -L/usr/lib64 -lyaml -o build/temp.linux-x86_64-2.7/check_libyaml
  building '_yaml' extension
  creating build/temp.linux-x86_64-2.7/ext
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o
  ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
   #include "pyconfig.h"
                        ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyyaml
Failed to build pyyaml
Installing collected packages: pyyaml, beets
  Running setup.py install for pyyaml
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-99nnKA/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1m3taG-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building '_yaml' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o
    ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory
     #include "pyconfig.h"
                          ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-99nnKA/pyyaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1m3taG-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-99nnKA/pyyaml

**Comment by edvernon** [comment]
Hey guys,

I figured out the issue, it seems I was missing python-devel, after installing I ran "pip install beets" and all seems to be well now.  Thank you 

$ sudo yum install python-devel.x86_64

$ sudo pip install beets
Collecting beets
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already satisfied (use --upgrade to upgrade): munkres in /usr/lib/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): unidecode in /usr/lib64/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): jellyfish in /usr/lib/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): musicbrainzngs>=0.4 in /usr/lib/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.27 in /usr/lib/python2.7/site-packages (from beets)
Requirement already satisfied (use --upgrade to upgrade): enum34>=1.0.4 in /usr/lib/python2.7/site-packages (from beets)
Collecting pyyaml (from beets)
  Using cached PyYAML-3.11.tar.gz
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml
  Stored in directory: /root/.cache/pip/wheels/fa/db/f6/dee55793d344f1706dc4a5a693298f0115241d1085cc212364
Successfully built pyyaml
Installing collected packages: pyyaml, beets
Successfully installed beets-1.3.15 pyyaml-3.1
-END-

**Comment by kylethielk** [comment]
Hi Guys,

I had a very similar problem and during my hunt stumbled on this Issue which led me to find a solution. 

It was indeed in my case caused by an outdated pip, but upgrading PIP didn't itself fix the issue however it did result in a more descriptive error message which did allow me to eventually solve the problem. 

Writing here in case someone finds this issue from Google. Try upgrading PIP and re-running command:

`sudo pip install --upgrade pip`

**Comment by hafizurcse** [comment]
Upgrading pip didn't help.
Please see the installation logs:

```Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.0.3
Removing intermediate container bbfa83284a1e
 ---> 59aa3ee46549
Step 12/13 : RUN pip install -r requirements.txt
 ---> Running in 59246eec192c
..........................................


running build_ext
    building 'regex._regex' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/regex_2
    gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -fPIC -I/usr/include/python2.7 -c regex_2/_regex.c -o build/temp.linux-x86_64-2.7/regex_2/_regex.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    --- --- ----     --- --- ----     --- --- ---- 
    --- --- ----     --- --- ----     --- --- ---- 
    --- --- ----     --- --- ----     --- --- ---- 
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gZsBJj/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hJuDe3/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-gZsBJj/regex/
ERROR: Service 'api' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```
