### ISSUE TITLE
Confused about setheader: how to check if it works?

### ISSUE THREAD

**Issue by register110** [mitmproxy/mitmproxy#3795]
**Problem**
I started mitmproxy with the following command:
mitmproxy --setheader /~q/User-Agent/"TEST"
This is fine, all User-Agents have been modified to "TEST" in mitmproxy, but
When I turned to inspecting requests in firefox dev tools, all the request User-Agent headers were not changed
So, does it work?

**Enviroment**
Mitmproxy: 5.0.1
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.3.7-1.el7.elrepo.x86_64-x86_64-with-centos-7.7.1908-Core
Firefox: 68.2.0esr

Thanks!

**Comment by Prinzhorn** [comment]
Your setup is probably like this

```
Firefox -> mitmproxy -> some website
```

Now the User-Agent goes

```
Firefox ---"Mozilla/5.0...."---> mitmproxy ----"TEST"---> some website
```

So of course it is still unchanged in dev tools, Firefox does simply not know what mitmproxy does to the header. Check the access logs of a website you run or visit a website such as http://my-user-agent.com/ and you should see

![Selection_563](https://user-images.githubusercontent.com/679144/73020821-b126a280-3e26-11ea-9c21-8bd48f339bd2.png)

**Comment by register110** [comment]
Thank you very much, it looks like only the response server can fully know the request headers
