### ISSUE TITLE
can't see request/response body with test on java

### ISSUE THREAD

**Issue by morkibka** [mitmproxy/mitmproxy#3800]
create test with java + appium + android + mitmproxy and instead of request/response body in IDEA logs see only code like "[105, 101, 115, 34, 58, 34, 48, 34, 125]"
my code:
`public void basicTest () throws InterruptedException {

        org.apache.log4j.BasicConfigurator.configure(new NullAppender());

        List<InterceptedMessage> messages = new ArrayList<InterceptedMessage>();

        MitmproxyJava proxy = new MitmproxyJava("/usr/local/bin/mitmdump", (InterceptedMessage m) -> {
            System.out.println( m.requestURL.toString() + Arrays.toString(m.requestBody)+ m.responseHeaders.toString() + m.responseBody.toString());
            messages.add(m);
            return m;

        });
        try {
            proxy.start();

            //first step to get traffic
            wait.until(ExpectedConditions.visibilityOfElementLocated
                    (By.id("com.appcraft.unicorn:id/btnAccept"))).click();
            Thread.sleep(3000);
            System.out.println(messages);

            proxy.stop();

        } catch (IOException | TimeoutException | URISyntaxException | InterruptedException e) {
            System.out.println(e);
        }`
what i get: https://gist.github.com/morkibka/4b802c86f37705b7fefe07a3740d5612
if i use .toString() then i get Ljava.lang.String 
if i use Arrays.toString then i get "[105, 101, 115, 34, 58, 34, 48, 34, 125]"
can someone help me pls?

**Comment by Prinzhorn** [comment]
I think the correct place to ask is here: https://github.com/appium/mitmproxy-java

Anyway, `requestBody` is of type `byte[]`. Googling "java byte array to string" brings up sth. [like this]
(https://stackoverflow.com/questions/6684665/java-byte-array-to-string-to-byte-array) or [this](https://stackoverflow.com/questions/88838/how-to-convert-strings-to-and-from-utf8-byte-arrays-in-java)

Does that work for you? I don't do Java

```java
new String(m.requestBody, StandardCharsets.UTF_8)
```

**Comment by morkibka** [comment]
thx!
