### ISSUE TITLE
Question whitelisted hosts

### ISSUE THREAD

**Issue by Nisutec** [mitmproxy/mitmproxy#3806]
Hallo,
Is it with mitmproxy possible to block all http/s requests except the requests of whitelisted hosts.

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
