### ISSUE TITLE
Is it possible to setup reserve address?

### ISSUE THREAD

**Issue by evadogstar** [mitmproxy/mitmproxy#3813]
Hello, is it possible to setup reserve address to connect to if first one is unreachable? Something like `--mode reverse2:http://backupserevr:3333` 
Thanks!

**Comment by mhils** [comment]
Thanks for the suggestion. To cut a long story short, this is nothing we intend to implement anytime soon. mitmproxy is not really meant to be used as a load balancer and implementing this would be non-trivial.
