### ISSUE TITLE
Using cookies in reverse proxy mode

### ISSUE THREAD

**Issue by molekulo1957** [mitmproxy/mitmproxy#3818]
Hello. Is it possible to use cookies from an original web-site in reverse proxy mode?
For example, when user logs in on a reverse proxy server it should show content as he is logged in on a real (original) server. How can I do that?
Thanks

**Comment by mhils** [comment]
Hi,

I'm not sure if I understand what you want. Maybe you want to look at the stickycookie/stickyauth addons, which offer related functionality.
