### ISSUE TITLE
Picture preview for webp

### ISSUE THREAD

**Issue by Sykursen** [mitmproxy/mitmproxy#3822]
#### Describe the solution you'd like
When mitmproxy catch some webp image, you can't preview the picture.
But firefox and chromium supports webp.

**Comment by Prinzhorn** [comment]
I assume you're talking about mitmweb? This was added in https://github.com/mitmproxy/mitmproxy/pull/3747 and according to the changelog it shipped with 5.0.1. But I can't see webp either.

Looking at http://127.0.0.1:8081/static/app.js it still ships the old code, without webp.

**Comment by mhils** [comment]
Whoops. @Prinzhorn is right, I screwed up the bundling. 🙊

**Comment by Prinzhorn** [comment]
@mhils sounds like a great opportunity to improve the build/release scripts to make less room for human error :+1:

**Comment by mhils** [comment]
Yeah - this is an annoyingly tricky problem. We a) want people to have an easy development experience which doesn't require a whole JS stack and b) can't update the compiled assets everytime as that results in an unsustainable repository growth.

I'm not really sure what's the best solution here. I've added a small note to the release checklist, maybe that's enough. :)

**Comment by mhils** [comment]
I've pushed an update to the compiled assets on master. If you can't wait for the next release, you can should find a snapshot at https://mitmproxy.org/downloads/#branches/master/ in a couple of minutes. :-)
