### ISSUE TITLE
websocket stream - error 403

### ISSUE THREAD

**Issue by Egyras** [mitmproxy/mitmproxy#3824]
#### Problem Description
websocket stream isnt passed corectly

#### Steps to reproduce the behavior:
I'am checking IOT device websocket data stream to Cloud and get 403 error doing this mitmproxy. Steps to reproduce the behavior: IOT application has 3 pem files: cacert.pem, newcert.pem, newkey.pem
launch mitmproxy --mode transparent --showhost --ssl-insecure --cert *=/tmp/ssl/cert.pem
(cert.pem has both newcert.pem and newkey.pem inside)

error:
Server Error
403 - Forbidden: Access is denied.
You do not have permission to view this directory or page using the credentials that you supplied.

Seems it wants to accees like simple webpage instead passing IOT application websocket traffic.....

#### System Information
System Information Mitmproxy: 5.0.1 Python: 3.6.8 OpenSSL: OpenSSL 1.1.1 11 Sep 2018 Platform: Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.10-cosmic

**Comment by mhils** [comment]
Can you provide a minimal, reproducible example of the issues you are encountering? "It doesn't work" isn't specific enough to fix it.
