### ISSUE TITLE
mitmproxy for this url does not work

### ISSUE THREAD

**Issue by Luis-Hebendanz** [mitmproxy/mitmproxy#3825]
#### Problem Description
The url described in the "steps to reproduce" section does not work under
mitmproxy. Normally a file would be downloaded but the connection fails under mitmproxy.
Tested with chrome and firefox, both do not work. The mitm certificate is installed properly.

#### Steps to reproduce the behavior:
1. ```mitmproxy --mode regular --anticomp --anticache```
2.  Browse to https://developer.amd.com/amd-aocc/ and click on the link
aocc-compiler-2.1.0.tar.
3.  Click on "I accept"
4. Download does not work through mitmproxy

#### System Information
Mitmproxy: 4.0.4
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.4.19-hardened-x86_64-with-glibc2.2.5

**Comment by Prinzhorn** [comment]
Did you try `stream_large_bodies` or waiting long enough?

I'm testing with 5.0.1 and with `--verbose` logging I can see that the file is downloaded perfectly fine. However, mitmproxy will cache the whole 100MB before sending it to your browser.

```
mitmdump --set stream_large_bodies=1m
```

Now I will get the file in Chrome immediately, bypassing the mitmdump memory.

**Comment by Luis-Hebendanz** [comment]
Oh yeah it works now! Sorry for the trouble
