### ISSUE TITLE
Transparent mode failure: Runtime Error (could not resolve original destination)

### ISSUE THREAD

**Issue by Jsonlu** [mitmproxy/mitmproxy#3828]
#### Problem Description
as title description, i want to use Custom Routing of Transparent Proxying, but can't regular work
![](https://docs.mitmproxy.org/stable/schematics/proxy-modes-transparent-3.png)

#### Steps to reproduce the behavior:
the NAT Gateway and MitmProxy are 2 devices，NAT Gateway is a desk route(IP is 192.168.2.1)，MitmProxy is a pc（macbook pro,IP is 192.168.2.2,Default Gateway is 192.168.2.1），the test phone is android OS(IP is 192.168.2.3,Default Gateway is 192.168.2.1), all devices are working normally.
1. as pc, run mitmproxy as command :
`mitmweb --mode transparent --showhost -p 9999`
2. as route, run iptables rules 
`iptables -t nat -A PREROUTING  -s 192.168.2.3 -p tcp --dport 80 -j DNAT --to-destination 192.168.2.2:9999; `
`iptables -t nat -A PREROUTING  -s 192.168.2.3 -p tcp --dport 443 -j DNAT --to-destination 192.168.2.2:9999;`
3. as phone, open browser address as `http://www.ip138.com:8080/search.asp?action=mobile`

#### System Information
Mitmproxy: 5.0.1
Python:    3.8.1
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  macOS-10.13.4-x86_64-i386-64bit

**Comment by Jsonlu** [comment]
and i see the [pf.py](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/platform/pf.py), looks like code line 24 doesn't work

**Comment by techgulesGu0** [comment]
have the same problem

**Comment by mhils** [comment]
Please take a look at https://docs.mitmproxy.org/stable/howto-transparent/. This seems to be a routing question, not a mitmproxy bug.
