### ISSUE TITLE
Support alternative syntax for --set arguments

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#3830]
**Is your feature request related to a problem? Please describe.**

I'm trying to spawn mitmproxy from Node.js in a safe way. If I supply Node.js with the arguments as an array it will ensure that no command or argument injection is possible. However, this is impossible for arguments like `--set confdir="user-provided-unsafe-please-wear-a-helmet"` because the second part is technically a single argument. I'd need to resort to string interpolation of user provided input 😳

#### Describe the solution you'd like

Support an alternative syntax with a space, e.g. `--set confdir "foo"`

#### Describe alternatives you've considered

It might be possible to manually escape the string and interpolate it, but this is borderline asking for issues (especially across OSs). The answers to this question are painful https://stackoverflow.com/questions/1779858/how-do-i-escape-a-string-for-a-shell-command-in-node

#### Additional context

Maybe the arg parser mitmproxy uses is already able to handle that out of the box?

**Comment by mhils** [comment]
This sounds like a reasonable use case, but I'm not sure if I understand the security issues here. Calling with `["--set", "confdir=unsafe-input"]`should be fine, no? We just split on the first `=`.

**Comment by Prinzhorn** [comment]
> not sure if I understand the security issues here.

Not necessarily security issues (which probably only exist if I enable `shell: true` on the Node.js side) but issues in general and doing things "the correct way". User input might contain spaces and quotes and whatnot.

> Calling with `["--set", "confdir=unsafe-input"]`should be fine, no? We just split on the first `=`.

Interesting, I hadn't looked at the argument that way. For some reason I was thinking the value needs to be quoted and that the arg parser needed it. But `mitmproxy --set "confdir=/tmp/with spaces"` works just fine. 

Thank you very much.

**Comment by Prinzhorn** [comment]
For future reference these work as expected

```sh
mitmproxy --set "confdir=/tmp/with=equal"
mitmproxy --set "confdir=/tmp/with=\"' bs"
```

thanks to "maxsplit=1" https://github.com/mitmproxy/mitmproxy/blob/7f7838eba9bd4f7ceeb97744c544b68a42d7b5ea/mitmproxy/optmanager.py#L300

Paranoid-me wonders if there's a test-case for weird arguments 🤔😅
