### ISSUE TITLE
Headers replace bug when count is set

### ISSUE THREAD

**Issue by eremeevdev** [mitmproxy/mitmproxy#3833]
#### Problem Description
Headers matching for replace are fully removed, if count=1

#### Steps to reproduce the behavior:
1. create header instance: `headers = Headers(host='foo.com', referrer='foo.com')`
2. replace `foo` with `bar` and `count=1`: `headers.replace('foo', 'bar', count=1)`
3. result is empty headers: `Headers[]`

```
>>> headers = Headers(host='foo.com', referrer='foo.com')
>>> headers.replace('foo', 'bar', count=1)
1
>>> headers
Headers[]
```

#### System Information
Mitmproxy: 5.0.1
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Darwin-19.3.0-x86_64-i386-64bit

**Comment by mhils** [comment]
Thanks for providing super easy steps to reproduce this! :smiley:

**Comment by naivekun** [comment]
I'll try to fix it.
