### ISSUE TITLE
Completely faking connection to server in script

### ISSUE THREAD

**Issue by BkPHcgQL3V** [mitmproxy/mitmproxy#3843]
**Is your feature request related to a problem? Please describe.**
I haven't found a good way to completely intercept connections (and all requests) to a server from a script.

#### Describe the solution you'd like
Perhaps there should be a `FakeLayer` or some other mechanism which would simulate the procedure of connecting to an upstream server, without actually doing so.

#### Describe alternatives you've considered
Here is the best solution I found so far:

```python
from mitmproxy import http
from mitmproxy.proxy.protocol import TlsLayer

# The server to which we wish to intercept connections.
# When the hostname doesn't exist, this becomes a hard requirement.
_redirect_source = 'nonexisting.example.net'

# The server we will be redirecting the connection to.
# Can be any server which listens on the same ports as _redirect_source.
_redirect_target = 'www.google.com'


# Change the server address at connection time.
def serverconnect(cc):
    if cc.address[0] == _redirect_source:
        cc._my_real_address = cc.address  # Save original address
        cc.address = (_redirect_target, cc.address[1])
        return True


# For TLS, we must also patch the SNI hostname.
# Otherwise, certificate validation will fail.
def next_layer(next_layer):
    if isinstance(next_layer, TlsLayer):
        if next_layer.server_conn.address[0] == _redirect_source:
            next_layer._custom_server_sni = _redirect_target


def request(flow: http.HTTPFlow) -> None:
    # Now, undo the hostname patch in serverconnect,
    # so that mitmproxy's UI shows the right URL.
    try:
        flow.server_conn.address = flow.server_conn._my_real_address
        flow.request.host = flow.server_conn.address[0]
        flow.request.port = flow.server_conn.address[1]
    except AttributeError:
        pass
    # Now send our fake response
    flow.response = ...
```

#### Additional context
The above workaround is not perfect as it still does require a target server to redirect the connection to. (Using a local server poses difficulties as it would have to have a valid SSL certificate for the target redirect domain name.)

**Comment by mhils** [comment]
What exactly are you trying to achieve? If you want to fake the HTTP response from a server, take a look at https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/send_reply_from_proxy.py.

**Comment by BkPHcgQL3V** [comment]
@mhils I'm not sure why you would post that when the script I posted already incorporates that approach.

It is insufficient, because the script request hook is fired only after a connection to the target server is established.

As already mentioned, the goal is to completely fake the connection to the target server, so that mitmproxy never attempts to establish a connection to it. As already mentioned, this is a hard requirement when the target host does not exist (e.g. when MITM-ing an application which tries to connect to a domain which has hence expired).

**Comment by mhils** [comment]
I see what you are attempting to do (completely fake the connection to the target server), but I'm not sure if I understand your high-level requirement.

For example, if you set the `upstream_cert` option to false, mitmproxy should happily intercept TLS for you without contacting the upstream server in that step. If you then use the script I linked above, you could send a reply from the proxy without mitmproxy contacting the upstream server. This way you could spoof replies from a target host that does not exist. Does this approach not work for you?

**Comment by BkPHcgQL3V** [comment]
Ahh, so it only establishes the connection before reading the request to read the certificate. I see. Thank you for letting me know about that option. However, I still don't see a way to enable it on a per-connection basis from a script. Is there a way?

**Comment by petromoldovan** [comment]
I hope it helps somebody to save the time that i wasted. 

I tried to intercept requests to particular fake domains and return json responses. At first i used the latest at time mitmproxy version `7.0.2`(default at the time for homebrew). No matter what I did, mitmproxy tried to connect to the fake domains. As these domains did not exist it gave me always "error establishing server connection" and i could not intercept these request, hence i could not return the custom json response.

I downloaded `6.0.2` binary(https://mitmproxy.org/downloads/#) and it finally worked. I am not sure if it is a bug or a feature in the 7.X.X versions but i could not find a way to disable this mandatory connection to fake upstream servers.

**Comment by yufengzjj** [comment]
> I hope it helps somebody to save the time that i wasted.
> 
> I tried to intercept requests to particular fake domains and return json responses. At first i used the latest at time `mitmproxy` version `7.0.2`(default at the time for `homebrew`). No matter what I did, mitmproxy tried to connect to the fake domains. As these domains did not exist it gave me always `error establishing server connection` and i could not intercept these request, hence i could not return the custom json response.
> 
> I downloaded `6.0.2` binary(https://mitmproxy.org/downloads/#) and it finally worked. I am not sure if it is a bug or a feature in the `7.X.X` versions but i could not find a way to disable this mandatory connection to fake upstream servers.
> 
> Anyway, thanks to maintainers for the awesome project!

set option connection_strategy to lazy(default is eager) will works if you want to mock a server which is not exists in real world and make a custom response before mitmproxy connect to this non-exist server.

I think this issue should be closed. 
is this what you wanted? @BkPHcgQL3V @petromoldovan

**Comment by petromoldovan** [comment]
@yufengzjj thanks! i will try that!
