### ISSUE TITLE
Config dns map (like map domain to ip) with transparent mode

### ISSUE THREAD

**Issue by Jsonlu** [mitmproxy/mitmproxy#3844]
**Is your feature request related to a problem? Please describe.**
as title

#### Describe the solution you'd like
I want to get a config for dns map, but if the domain is not existed, the script's lifecycle is like not running.i know if add some lifecycles in script is not easy, but i need it.

#### Describe alternatives you've considered
add a config for dns resolves, or some like useful case

**Comment by mhils** [comment]
Hi @Jsonlu,

I think what you are suggesting is useful, but a bit premature. We don't support UDP at all at the moment, so that'd need to be sorted out first. I'll close this here until we have some support for UDP, then we can talk about modifying DNS. :-)

Cheers,
Max
