### ISSUE TITLE
Is possible to change proxy behaviour on fly without restart ?

### ISSUE THREAD

**Issue by Grooos17** [mitmproxy/mitmproxy#3847]
Hi!

Can I change addons/proxy behaviour in process running without restart it? 
For example I would be replace some text in response in one case and in another case I would be replace same text to another one.

Thanks ^)

**Comment by mhils** [comment]
You can update mitmproxy options during runtime and those changes should be processed by all addons. For further support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!

**Comment by caglance** [comment]
How to update mitmproxy options in the way of python?

**Comment by caglance** [comment]
I searched everywhere and got nothing, please help me !
