### ISSUE TITLE
traffic is not passing through mitmproxy

### ISSUE THREAD

**Issue by heronils** [mitmproxy/mitmproxy#3848]
#### Problem Description
I am on Windows 7. I have run the latest installer (5.0.1). Then i have set up in my system settings (that what google chrome opens when i click on "open proxy settings of computer") that it shall listen on port 8080. When i then start the ui, it says:

Web server listening at http://127.0.0.1:8081/
Proxy server listening at http://*:8080"

but mitm.it says "If you can see this, traffic is not passing through mitmproxy." Hmm, what could be the error here? Could anyone give me a hint?

Notice, i tried to register in the discourse forum but it wont allow me to do that. Which is why i am asking here :-)

#### Steps to reproduce the behavior:
See above

#### System Information
"Error: mitmproxy's console interface is not supported on Windows. You can run mitmdump or mitmweb instead."

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!

**Comment by lycanthropes** [comment]
I also met this problem, my os is windows 10 professional , and my chrome edition is 90.0.4430. After installed mitmproxy, I can open the web listening page, but when I want to visit mitm.it and install the CA , now matter whether I configured the proxy port in chrome, it always shows "traffic is not passing through mitmproxy." How can I solve it? Please give me a hand...
