### ISSUE TITLE
mitmproxy does not show raw tcp packets.

### ISSUE THREAD

**Issue by rubeste** [mitmproxy/mitmproxy#3852]
#### Problem Description
I am trying to see what is going on in an MQTT connection, but I do not see any TCP packets. I do not know if I am doing it wrong or if something else is happening.
When I do mitmdump I see this:
![image](https://user-images.githubusercontent.com/28504874/76219153-ac228480-6215-11ea-9d94-ecf6847a0f6e.png)

#### Steps to reproduce the behavior:
1. Setup for transparent proxy
2. use this command: sudo mitmproxy --mode transparent --ssl-insecure --certs {HOST}=/home/kali/mitmproxy/final/server.pem --set confdir=/home/kali/mitmproxyxy/final --ignore-hosts 192.168.152.131 --ignore-hosts 192.168.152.30 --set rawtcp=true --tcp-hosts 192.168.152.130

#### System Information
Mitmproxy: 5.0.1 binary
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.4.0-kali3-amd64-x86_64-with-debian-kali-rolling

#### Setup
192.168.152.130: Mosquitto MQTT broker
192.168.152.128 on eth0 & 172.22.0.1 br-fa44f6c04b4c: MitM
172.22.0.2: docker image with MQTT client

echo $SSLKEYLOGFILE
/home/kali/.mitmproxy/sslkeylogfile.txt

I am using the Certificate from the MQTT broker plus a custom CA

**Comment by mhils** [comment]
You want to crank up your `flow_detail` option: https://github.com/mitmproxy/mitmproxy/blob/e01f044c33aba51d9e5b6053e759b47594ad0855/mitmproxy/addons/dumper.py#L285-L295

**Comment by mhils** [comment]
For reference, proper support for viewing TCP is tracked in #3680.

**Comment by rubeste** [comment]
Thank you for your help. The link you sent me works.
