### ISSUE TITLE
Comparison of recordings

### ISSUE THREAD

**Issue by bobvanderlinden** [mitmproxy/mitmproxy#3853]
This is a feature request or question how others are doing this.

Currently I am working on a migration of an existing application to a new implementation. The applications APIs should act exactly the same as the old system. We would like to make 2 recordings: one for the old system and one for the new system. Afterwards we want to compare the two recordings on server-responses.

#### Describe the solution you'd like

To do this we can use `mitmdump` to record client-requests and the server-responses on our old system. We can use the same recording to replay the client-requests toward our new system and again record the server-responses.

#### Describe alternatives you've considered

However I have not found any tools to compare the 2 recordings based on server-responses. I might have missed some documentation on how to do this, there might be third-party tools to do this or lastly I could build a tool for the purpose.

For building such a tool, I need to know the format that mitmdump uses for recordings. Looking at that file it seems it is not that straightforward. This issue was already described here #3075.

**Comment by mhils** [comment]
Two thoughts come to mind:

1. If you want to build this into a separate tool, can your tool depend on mitmproxy itself? In that case you could use something like [examples/simple/io_read_dumpfile.py](https://github.com/mitmproxy/mitmproxy/blob/master/examples/simple/io_read_dumpfile.py) to get flow objects.

2. Alternatively, you can probably implement your own command (https://docs.mitmproxy.org/stable/addons-commands/) which compares two flows (or a flow with its non-replayed version saved as backup).

**Comment by bobvanderlinden** [comment]
Ah that makes a lot of sense. I have been thinking about this some more and it might already work if it would export requests and responses as JSON. Something like jsondiff can then be used to do the comparison.

If that isn't satisfactory I can look into doing the comparison directly in a command.

I'll keep this issue open until some solution is finished. Will keep you posted.

**Comment by bobvanderlinden** [comment]
I made `mitmjson`. A command-line tool like you suggested, but it converts flows to json. JSON can then be used to more easily compare and manipulate (removing headers, timestamps, etc). It's available here:

https://github.com/bobvanderlinden/mitmjson

I published it to pypi, so it can be installed using:

```
pip install mitmjson
```

I'm not a 'native' Python programmer, so any suggestions are welcome.

**Comment by mhils** [comment]
Awesome, thanks for sharing!
FWIW, we also have a flow_to_json function in mitmweb: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/web/app.py#L26. Maybe that makes your life a bit easier. :)

**Comment by bobvanderlinden** [comment]
I wasn't aware mitmproxy also had an example for exporting to HAR files. Those are standardized JSON, so easier to compare. The example can be found here: https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/har_dump.py

I'll close this issue, as I think this should be enough for most use-cases. Otherwise, there are probably HAR tools that can do comparisons.

**Comment by abitrolly** [comment]
The new location is here https://github.com/mitmproxy/mitmproxy/blob/master/examples/contrib/har_dump.py

I still wish it could be possible to view the diff between two flows directly in console UI.
