### ISSUE TITLE
Mitm 4.0.4 for windows contains mitmdump version 4.0.2

### ISSUE THREAD

**Issue by bebef1987** [mitmproxy/mitmproxy#3856]
#### Problem Description
When downloading `mitmproxy-4.0.4-windows.zip` from https://mitmproxy.org/downloads/#4.0.4/ 

the `mitmdump.exe` file containd in that zip reports mitmversion `4.0.2`

**Comment by mhils** [comment]
Hm - not sure what has gone wrong here, normally that's just pushed by CI. I'm afraid fixing this has very little return on investment. What's holding you off upgrading to 5.x?

**Comment by bebef1987** [comment]
we are in the process of upgrading and found this issue thought you should know about it
