### ISSUE TITLE
Is it possible to capture traffic from a python script?

### ISSUE THREAD

**Issue by Lucia-Marcos** [mitmproxy/mitmproxy#3858]
I use mitmproxy a lot, thank you very much for create a fantastic development.

I tried to use mitmproxy in my script in python, but I am not able to get the script to return the traffic to the same script (with from mitmproxy.tools.dump import DumpMaster...)

I have seen that someone has done it by creating a save in sql with addons, but it seems crazy to do so.

Is there a way to dump traffic to the same script with new requests?

**Comment by Prinzhorn** [comment]
If I understand correctly this is a duplicate of #3406

**Comment by mhils** [comment]
Yes, thanks!
