### ISSUE TITLE
Use XDG_CONFIG_HOME for the configuration

### ISSUE THREAD

**Issue by hauleth** [mitmproxy/mitmproxy#3863]
Currently mitmproxy stores the configuration in the `~/.mitmproxy` which is hard to manage and increases clutter in the home directory.

#### Describe the solution you'd like

Use [FreeDesktop XDG directory recommendations](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) which mean that the used directory is `$XDG_CONFIG_HOME/mitmproxy` where `XDG_CONFIG_HOME` defaults to the `$HOME/.config`. That makes everything much easier to manage. Of course for backwards compatibility it should fall back to current behaviour if the above directory is not found.

**Comment by Kriechi** [comment]
I would be happy to accept a PR for this!

**Comment by Kriechi** [comment]
Not in scope for us - but happy to review a PR.
