### ISSUE TITLE
Upgrade request (GET ws://)

### ISSUE THREAD

**Issue by zi0Black** [mitmproxy/mitmproxy#3867]
I'm having several problems building a reverse proxy  for an application that makes the following protocol upgrade request:

```
GET ws://127.0.0.1:6565/?reconnectionToken=[redacted] HTTP/1.1
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Key: 4l2gyUWXMc6gwhW26k3OAw==
```
mitm-proxy error:
```
HTTP protocol error in client request: Invalid request scheme: ws
```

It is probably not fully RFC compliant or most libraries do not include `ws` and `wss` as protocols.

If you can add support for these protocols it could be very useful. (I also accept workaround of all kinds).

**Comment by zi0Black** [comment]
After reading the RFC of HTTP protocol, I found my answer. So I'm closing this issue as unnecessary.

**Comment by Prinzhorn** [comment]
First of all can you name the application so we can publicly shame it? :smile: 

Anyway, I don't think this is valid at all so I'm not sure this will (or can) be added to mitmproxy.

Here's your workaround: start a second mitmproxy in reverse mode in from of your regular one and correct these nasty packets.

```sh
mitmdump --rawtcp --mode reverse:http://localhost:8081 --tcp-hosts '.*' --scripts addon.py
```

```python
import mitmproxy.tcp;

def tcp_message(flow: mitmproxy.tcp.TCPFlow):
  flow.messages[-1].content = flow.messages[-1].content.replace(b'GET ws://', b'GET http://', 1)
```

**Comment by zi0Black** [comment]
I can't name the application but I have to say that it has caused me quite a few headaches. Thanks for the workaround, I hadn't thought about it.
(for me we can close the issue too).

**Comment by Prinzhorn** [comment]
Feel free to close it then, I'm not a maintainer.

**Comment by xverges** [comment]
Thanks! I think that the 2026 version of the command would be

```
mitmdump --mode reverse:tcp://localhost:8081 --tcp-hosts '.*' --script addon.py
```
