### ISSUE TITLE
Error during mitmproxy deployment on Kubernetes

### ISSUE THREAD

**Issue by michalrubaj** [mitmproxy/mitmproxy#3868]
#### Problem Description

Hey guys,

I'm trying to deploy a mitmproxy instance on Kubernetes cluster as a pod. No matter which image I use from dockerhub, in the end, I'm always stuck with the same error after the instantiation of a pod.  I don't know the exact cause of this issue since I am able to create and run a container out of image locally. The pod is created with flags:

`stdin: true,
 tty: true`

**Error trace:**

![image](https://user-images.githubusercontent.com/39368662/77435530-b3838980-6de2-11ea-912e-dd46c5952ed1.png)

Can someone help me with this issue? I believe my deployment yaml is correct, but I can provide it here as well if necessary

**Comment by Prinzhorn** [comment]
Use `mitmdump` instead of `mitmproxy` since you're working headless I guess (the error looks like it is related to rendering on a terminal)

**Comment by mhils** [comment]
Yes, this is probably because the terminal width is reported to mitmproxy as being 0, which won't work.
