### ISSUE TITLE
@concurrent example confusing

### ISSUE THREAD

**Issue by nozhT** [mitmproxy/mitmproxy#3877]
The example [here](https://github.com/mitmproxy/mitmproxy/blob/af1a4ffdcd4c98afefd4228bbc2bc276cfd8436f/examples/complex/nonblocking.py#L9) says to not use `ctx` from a different thread however the example does so in the exact next line.

**Comment by mhils** [comment]
Thanks for spotting this. That's definitely the artifact of a botched refactor here: https://github.com/mitmproxy/mitmproxy/commit/af1a4ffdcd4c98afefd4228bbc2bc276cfd8436f.
