### ISSUE TITLE
How does mitmproxy handle tcp traffic in transparent mode

### ISSUE THREAD

**Issue by SmartestKen** [mitmproxy/mitmproxy#3878]
Based on the source code, mitmproxy begins with a listening socket and create a new thread when a new connection arrives. Now we have a stream of tcp packets.

But since packet boundary does not have meaning, multiple http/websocket/TLS header may appear in one packet or one header can span multiple packets, how does mitmproxy extract requests from raw tcp stream? 

If it takes long to explain, could you please point me to the implementation file? (I got lost at root_context.py....). Thank you.

**Comment by techathena** [comment]
Hey ,this might help you get started!I think this is the file you were looking for.
All the explanation is in comments.
https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/protocol/__init__.py
Lemme know if this helps :)

**Comment by SmartestKen** [comment]
Yes. I am aware of that architecture. 
But for example, take a look at __call()__ in protocol/tls.py, which ends up calling get_client_hello() in net/tls.py. In get_client_hello(), we simply peek into the rfile. 

But what if there are multiple requests? For example:

client connect - https - https - https - https - client close

Requests in the middle may begin in the middle of some tcp packet, right after the end of the previous request? How does mitmproxy keep track of that? (Again, please point me the implementation if it takes long to explain)

**Comment by mhils** [comment]
Good question! TCP stream reassembly is done by the operating system, we work one layer on top of this with sockets. If we call peek() or read(), we get the byte stream in the correct order.

Does that explain it?

**Comment by SmartestKen** [comment]
Ok. But how do we know that we are at the beginning of a higher layer (http/websocket/tls) request when we call peek() or read()?

For example, 
client connect - request A - request B - ....

Don't we need to track when request A ends to know when request B starts?

**Comment by SmartestKen** [comment]
Something like
First read()      "request A header .... request A body......request B header (partial)"
Second read()  "request B header (partial)....request B body"

or 

First read()      "request A header .... request A body (partial)"
Second read()  "request A body (partial).... request B header..."

by header I mean header/frame/record etc. (i.e. requests not restricted to plain http 1.1)

**Comment by mhils** [comment]
> Don't we need to track when request A ends to know when request B starts?

We do. If you look at our layer implementations, those checks mostly happen at the beginning of a new connection, or at the beginning of a new connection state (e.g., after HTTP CONNECT). We can be sure at those places that we're at the beginning of the next message, if you want so.
