### ISSUE TITLE
How does mitmproxy drop request?

### ISSUE THREAD

**Issue by majidmc2** [mitmproxy/mitmproxy#3879]
Hi
I want to create an interception proxy like Burp Suite (between Firefox and server) to checks some conditions in the body or header of request and if the result is true, then it drops the request.
How does mitmproxy help me?

Thanks.

**Comment by Prinzhorn** [comment]
Flows have a `kill` method

```python
if flow.response.raw_content == 'just an examle':
    flow.kill()
```

**Comment by majidmc2** [comment]
> Flows have a `kill` method
> 
> ```python
> def response(flow: mitmproxy.http.HTTPFlow):
>     if flow.response.raw_content == 'just an examle':
>         flow.kill()
> ```
> 
> Edit: @mhils can we rename this to `dropable` / `drop` in the next major version to be less violent? And actually `drop` fits better, doesn't it? But I don't have hard feelings regarding it.

Thanks for your answer. When I run this command:

`$ mitmdump -q -s mitm-test.py`

It uses Python2.6 instead of Python3.6!!!

Error:
```
mitmdump: Traceback (most recent call last):
  File "/home/majidmc2/.local/lib/python2.7/site-packages/libmproxy/script.py", line 99, in load
    execfile(self.argv[0], ns, ns)
  File "mitm-test.py", line 29
    def request(flow: http.HTTPFlow) -> None:
                    ^
SyntaxError: invalid syntax
```

**Comment by mhils** [comment]
> Edit: @mhils can we rename this to `dropable` / `drop` in the next major version to be less violent? And actually `drop` fits better, doesn't it? But I don't have hard feelings regarding it.

I'm open to renaming it in general, but maybe let's wait for this until the sans-io branch hits. I _think_ the general API will stay, but if it doesn't, we don't want to break the API again then. Does that work for you?

**Comment by Prinzhorn** [comment]
> It uses Python2.6 instead of Python3.6!!!

How did you install mitmproxy? What `mitmdump --version` are you using?

**Comment by majidmc2** [comment]
> > It uses Python2.6 instead of Python3.6!!!
> 
> How did you install mitmproxy? What `mitmdump --version` are you using?
> 
> > I'm open to renaming it in general, but maybe let's wait for this until the sans-io branch hits. I _think_ the general API will stay, but if it doesn't, we don't want to break the API again then. Does that work for you?
> 
> Sure that works for me, I'm not that involved in mitmproxy anyway. When the time has come I can create a PR, sounds like an easy enough thing to get more familiar with Python and the code base.

I am using mitmdump 0.13

**Comment by Prinzhorn** [comment]
> I am using mitmdump 0.13

That was released in Aug 16, 2015. Now is the perfect time to upgrade!

**Comment by mhils** [comment]
Thanks @Prinzhorn, closing this here! 😄
