### ISSUE TITLE
ServerConnection.ip_address is not populated inside `serverconnect` event

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#3880]
#### Problem Description

Inside the `serverconnect` event the `ip_address` property is not populated, it is `None`. The `address` property is correctly populated. Since the connection is open I would expect the IP address to be known and the property to be available.

#### Steps to reproduce the behavior:

`mitmdump --scripts conn.py`

```python
def serverconnect(conn):
  print('-------connect--------------')
  print(conn.id)
  print(conn.address)
  print(conn.ip_address)
  print('-------/connect--------------')

def serverdisconnect(conn):
  print('----------disconnect-----------')
  print(conn.id)
  print(conn.address)
  print(conn.ip_address)
  print('----------/disconnect-----------')
```

Output

```
-------connect--------------
ab301a58-2366-4025-bab9-77c2bdfe74e6
('prinzhorn.it', 80)
None
-------/connect--------------

----------disconnect-----------
ab301a58-2366-4025-bab9-77c2bdfe74e6
('prinzhorn.it', 80)
('87.98.150.101', 80)
----------/disconnect-----------
```

#### System Information

```
Mitmproxy: 5.0.1
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.3.0-45-generic-x86_64-with-Ubuntu-19.10-eoan
```

**Comment by Prinzhorn** [comment]
I assume this is the place https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/protocol/base.py#L164-L166

If this is expected behavior then the docs need to be updated. It says

> Mitmproxy **has** connected to a server.

**Comment by Prinzhorn** [comment]
`conn.connected()` is `False` in both cases. Either it needs to be `True` inside `serverconnect` or `True` inside `serverdisconnect`. It is not symmetrical right now.

https://github.com/mitmproxy/mitmproxy/blob/3046a628fd0b719ff587eac5f5fd6965cd5eac89/mitmproxy/proxy/protocol/base.py#L148-L149

**Comment by mhils** [comment]
Thanks for spotting this and the great report! ❤️

I agree that for symmetry reasons `serverconnect` should behave as it is documented. 

If we find there is a strong use case for "before_serverconnect" event (we could probably find a better name), we can always add it on top.

**Comment by Prinzhorn** [comment]
> If we find there is a strong use case for "before_serverconnect" event (we could probably find a better name), we can always add it on top.

Agree. A use-case would be to have a chance to prevent certain connections to be made at all. But I don't have that use-case and like you said we can add another event if needed.
