### ISSUE TITLE
New event after `clientconnect` as soon as TLS is established

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#3884]
**Is your feature request related to a problem? Please describe.**
`layer.client_conn.timestamp_tls_setup` is `None` in `clientconnect`. I'm storing all mitmproxy data in SQLite and there is no event I can hook into to easily get `timestamp_tls_setup`. I could wait for `clientdisconnect` but I want to have the data as soon as it is available. Same for `cert` inside `serverconnect`.

#### Describe the solution you'd like
An event, maybe we can call it `clientconvert` analogous to `convert_to_tls` method. The event is triggered once a client connection is converted. So obviously not all client connections will be converted to TLS, it will never fire for them.

I'd also need a symmetrical event like `serverconvert` so that I can process `conn.cert` only once and not for every single `request`. Right now inside `serverconnect` the `cert` is `None`. My current workaround is to process the `cert` for every `request` but have a UNIQUE constraint on the cert sha256 and effectively only storing it once.

#### Describe alternatives you've considered
For HTTP data I can use the first `request` event for any given `client_conn` and process it as needed. But that requires additional logic or it will process stuff multiple times if a connection is shared.

#### Additional context
There's also `next_layer`. Could I use that? I'm not familiar enough with what a layer is and how that works. Even if I could use it I guess two new events would be user friendly and explicit.

**Comment by mhils** [comment]
This is a good feature request. In fact, on the sans-io branch I already expose `tls_clienthello` (we just received a ClientHello) and `tls_start` events (we are about to establish TLS with someone). We could conceivably also add `tls_success` and `tls_error` events there.

Workaround for now: I believe what you should be able to do right now is to just update the TLS certificate on `clientdisconnect` and `serverdisconnect`. You should get all connections in their final state that way.


Finally, `next_layer`: [`mitmproxy/proxy/protocol/__init__.py`](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/protocol/__init__.py#L1-L29) has a bit of an explanation. It's a very low-level hook to influence which protocol should be next on the stack. It could be abused for your use case (check for calls to next_layer where the current top layer is TLS), but that's nothing I would actively encourage. Using `*disconnect` seems much cleaner to me.

**Comment by Prinzhorn** [comment]
> This is a good feature request. In fact, on the sans-io branch I already expose `tls_clienthello` (we just received a ClientHello) and `tls_start` events (we are about to establish TLS with someone). We could conceivably also add `tls_success` and `tls_error` events there.

Neat :+1: 

> Workaround for now: I believe what you should be able to do right now is to just update the TLS certificate on `clientdisconnect` and `serverdisconnect`. You should get all connections in their final state that way.

Thank you very much. That's what I will go with for now. The reason I need the info as quick as possible is because if a user of my to-be-released (probably way after sans-io) application clicks on an HTTP request to see details the cert info would be missing if the current connection is still open and used for other requests. But I like that workaround better than handling the cert inside the `request` event and having to process it multiple times (or have code to prevent that). It will make it easier to migrate to the new events later.

**Comment by mhils** [comment]
> (probably way after sans-io)

You are either very pessimistic regarding your work or very optimistic regarding our progress. 😄 

Anyways, we'd of course be very interested to hear what you are building and if there's anything we can help with. On that note, feel free to join us on Slack!

**Comment by Prinzhorn** [comment]
> You are either very pessimistic regarding your work or very optimistic regarding our progress. smile

Yes.

> Anyways, we'd of course be very interested to hear what you are building and if there's anything we can help with. On that note, feel free to join us on Slack!

Maybe it is because of the Jedi tricks I've been using, but you have in fact already helped me in the past few months without realizing :wink: 

I will share more details some time in the future and check out Slack as well!

**Comment by Prinzhorn** [comment]
Correct me if I'm wrong, this is now `tls_established_client` and `tls_established_server`? They give me tls info for every connection as soon as possible?

```
def client_connected(client):
    print('client_connected')
    print(client.timestamp_tls_setup)


def tls_established_client(data):
    print('tls_established_client')
    print(data.conn.timestamp_tls_setup)


def server_connected(data):
    print('server_connected')
    print(data.server.timestamp_tls_setup)


def tls_established_server(data):
    print('tls_established_server')
    print(data.conn.timestamp_tls_setup)

```
