### ISSUE TITLE
Clarify developer documentation for mitmweb

### ISSUE THREAD

**Issue by oxr463** [mitmproxy/mitmproxy#3888]
#### Problem Description
The quick start instructions for mitmweb assume the virtual environment has been set up already;
This needs to be made clear to any potential contributors.

#### Steps to reproduce the behavior:
1. Run `yarn` to install dependencies
2. Run `yarn run gulp` to start live-compilation.
3. Cannot run `mitmweb` as it has not been installed

#### System Information
Running on master branch (currently 0b76afd).

```sh
mitmweb
Command 'mitmweb' not found, but can be installed with:

sudo apt install mitmproxy
```

**Comment by mhils** [comment]
Thanks! That's a good illustration of core contributor blindness. 😃 

@oxr463: Would you mind sending a PR that fixes the instructions? Thanks! 🍰
