### ISSUE TITLE
Mitweb inconsistent option: web-iface

### ISSUE THREAD

**Issue by oxr463** [mitmproxy/mitmproxy#3891]
#### Problem Description
For `mitmweb`, the option is `--web-iface`; but for `mitmproxy`, the option is `--listen-host`.

These two settings are practically the same, since the interface value is actually an IP address.
Coming from Linux, I initially tried setting it to `eth0`, but that failed.

Searching for the option in the repository led me to the following command:

```sh
docker run --rm -it -p 8080:8080 -p 127.0.0.1:8081:8081 mitmproxy/mitmproxy mitmweb --web-iface 0.0.0.0
```

Source: https://github.com/mitmproxy/mitmproxy/blob/master/release/docker/README.md#usage

Instead, I think we should change it to `--web-host` to match the proxy.

**Comment by mhils** [comment]
Yes, that sounds reasonable. I'd be happy to merge a PR that unifies things! 😃

**Comment by sohnemann** [comment]
Please add this change to the documentation on dockerhub.
I was wondering why it wouldn't accept --web-iface 0.0.0.0 as suggested there.
Thanks!

**Comment by oxr463** [comment]
> 
> 
> Please add this change to the documentation on dockerhub.
> I was wondering why it wouldn't accept --web-iface 0.0.0.0 as suggested there.
> Thanks!

The source file was updated, (See: release/docker/README.md); perhaps someone will need to update it manually on Docker Hub.

**Comment by zeroum** [comment]
Guys, please give a deprecation warning a few versions before you implement a breaking change in an interface. Keep the old one working during that time.

--web-iface was stable for 3 years.

**Comment by oxr463** [comment]
@zeroum apologies, I only made the code change itself; I am not a maintainer.

However, it was put in the Change Log, (See: https://github.com/mitmproxy/mitmproxy/blob/master/CHANGELOG#L11); and also see below:

> Mitmweb is currently in beta. We consider it stable for all features
currently exposed in the UI, but it still misses a lot of mitmproxy's
features.

Source: https://github.com/mitmproxy/mitmproxy/blob/master/docs/src/content/tools-mitmweb.md
