### ISSUE TITLE
Issue proxying traffic through burp suite

### ISSUE THREAD

**Issue by rek7** [mitmproxy/mitmproxy#3894]
Using the command: sudo -u mitmproxyuser bash -c 'mitmdump --mode transparent --showhost --set block_global=false --mode reverse:http://localhost:8085 --set insecure_ssl=true --set upstream_cert=false' I'm trying to proxy my traffic to burp suite listening on 8085, unfortaently I get the error:
Client Handshake failed. The client may not trust the proxy's certificate for portswigger.net.
Both the MITM and burp CA are in the correct locations.

**Comment by Prinzhorn** [comment]
You didn't specify what version you are using, but I'm not sure the option was ever called `insecure_ssl`. Try `ssl_insecure`.
