### ISSUE TITLE
ServerConnection.source_address has a default value of ('', 0)

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#3896]
#### Problem Description
`source_address` should be `None` until it is known. Currently it is `('', 0)` which is an odd value.

**Note**:  #3881 "fixes" the issue, inside `serverconnect` the value is now also properly populated. However, the default value still does not align with others and I'm not sure where else it might pop up. It should be `None` for consistency. Currently you cannot check if the value is set, because it is always set to a tuple.

#### Steps to reproduce the behavior:
`mitmdump --quiet --scripts conn.py`

```python
def serverconnect(conn):
  print('-------connect--------------')
  print(conn.id)
  print(conn.address)
  print(conn.ip_address)
  print(conn.source_address)
  print(conn.connected())
  print('-------/connect--------------')

def serverdisconnect(conn):
  print('----------disconnect-----------')
  print(conn.id)
  print(conn.address)
  print(conn.ip_address)
  print(conn.source_address)
  print(conn.connected())
  print('----------/disconnect-----------')
```

```
-------connect--------------
026f902f-001b-4e0e-a17d-8ee16a027dca
('www.google.com', 80)
None
('', 0)
False
-------/connect--------------
----------disconnect-----------
026f902f-001b-4e0e-a17d-8ee16a027dca
('www.google.com', 80)
('2a00:1450:4001:81f::2004', 80, 0, 0)
('2a02:810b:1040:8398:61a2:13f8:be5f:9eff', 41361, 0, 0)
False
----------/disconnect-----------
```

**Output with master branch**

```
-------connect--------------
6e73001d-cbc2-45db-9e68-e2809efe51f6
('www.google.com', 80)
('2a00:1450:4001:81f::2004', 80, 0, 0)
('2a02:810b:1040:8398:61a2:13f8:be5f:9eff', 47873, 0, 0)
True
-------/connect--------------
----------disconnect-----------
6e73001d-cbc2-45db-9e68-e2809efe51f6
('www.google.com', 80)
('2a00:1450:4001:81f::2004', 80, 0, 0)
('2a02:810b:1040:8398:61a2:13f8:be5f:9eff', 47873, 0, 0)
False
----------/disconnect-----------
```

#### System Information

```
Mitmproxy: 5.0.1
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-5.3.0-45-generic-x86_64-with-Ubuntu-19.10-eoan
```

**Comment by Prinzhorn** [comment]
I just noticed the additional `0, 0`. What's up with them? I thought it'd be tuples of length 2 with ip+port. Is that some ipv6 stuff I don't know about?

**Comment by Prinzhorn** [comment]
On a related note: can we rename `address` vs `ip_address`? They're misleading. `ip_address` does not contain the ip address, but a tuple. Maybe rename to `resolved_address` instead? Because it's basically `address` but it is guaranteed that the host has been resolved if it wasn't an IP already?

**Comment by mhils** [comment]
> source_address should be None until it is known. Currently it is ('', 0) which is an odd value.

Yes, I fixed this on the mystical sans-io branch already. 🙊 https://github.com/mitmproxy/mitmproxy/blob/744f7e5720eb3cb01958f6342b64d1eea9bf42b0/mitmproxy/proxy2/context.py#L20-L21

> On a related note: can we rename `address` vs `ip_address`? 

This sounds sensible. How about we go with `peername` and `sockname` for all connections, and additionally `address` for server connections? This would align with the Berkeley socket API.


> [flowinfo and scopeid in the IPv6 four-tuple] Are these two relevant for mitmproxy at all? Maybe we should slice them away for consistency?

Tricky question. I _think_ we shouldn't discard them unless it causes us major pain. For example, if someone were to use link-local IPv6 addresses with mitmproxy, sin6_scope_id is very relevant. I'm not saying that anyone ever does this for practical purposes, but we may want to have support for it to just allow security researchers to fiddle with it.

**Comment by Prinzhorn** [comment]
> Yes, I fixed this on the mystical sans-io branch already. speak_no_evil

sans-io seems to be a cool dude



> This sounds sensible. How about we go with `peername` and `sockname` for all connections, and additionally `address` for server connections? This would align with the Berkeley socket API.

Never heard either term. But I'm all for consistency. I assume the new code will have comments such as

https://github.com/mitmproxy/mitmproxy/blob/3cd37652709292cffa1bc733134cef5483489341/mitmproxy/connections.py#L16-L32

because they've helped me a lot.

> Tricky question. I _think_ we shouldn't discard them unless it causes us major pain. For example, if someone were to use link-local IPv6 addresses with mitmproxy, sin6_scope_id is very relevant. I'm not saying that anyone ever does this for practical purposes, but we may want to have support for it to just allow security researchers to fiddle with it.

Ok, it doesn't hurt to keep them. I just don't know what they're for (yet) and might find them useful myself.
