### ISSUE TITLE
(request/feature) Transparent TLSv1.2 websocket analysis not working

### ISSUE THREAD

**Issue by tsujp** [mitmproxy/mitmproxy#3901]
**Is your feature request related to a problem? Please describe.**

Yes it is. I am trying to DE TLSv1.2 packets of a game so that I can make those API calls outside of the game itself, for statistical analysis. I've used Wireshark and mitmproxy to determine that the game is requesting a websocket upgrade, receives an HTTP 101 upgrade from the server after which all traffic is over said websocket. Mitmproxy doesn't display this, and I cannot get certificates working with mitmdump despite even with this issue: https://github.com/mitmproxy/mitmproxy/issues/899#issuecomment-608996389

The result is always `Client Handshake failed. The client may not trust the proxy's certificate`. Note, the certificates are fine when using `mitmproxy` for the initial websocket upgrade so I don't understand.

#### Describe the solution you'd like

Viewing websocket data transparently within `mitmproxy` or instructions on how to dump decrypted websocket data with `mitmdump`, as I cannot get certificates to work.

#### Describe alternatives you've considered

I've tried every single library I can find for MiTM proxy self-attacks and none work, almost all are designed for browsers which this application is not and uses no part of. I've also tried `MITMPROXY_SSLKEYLOGFILE` but of course this doesn't do anything since it refuses the certificate to start the handshake, as well as `SSLKEYLOGFILE` and `LD_PRELOAD` which as far as I know are also browser specific.

#### Additional context

My `mitmdump` command is as follows (foobar.py is from the issue aforementioned)

```
mitmdump -s ./foobar.py -p 8081 --cert *=~/.mitmproxy/mitmproxy-ca-cert.pem --set block_global=false --set keep_host_header=true
```

**Comment by Kriechi** [comment]
You do not need to specify the mitmproxy certs from the default directory.
You do not need to generate your own CA and certs - mitmproxy takes care of it on the first start.

Does the game still work with mitmproxy/mitmdump active, or do all requests fail?
Which mitmproxy version?
Which OS?
How do you configure your game to use mitmproxy?
Did you try mitmproxy/mitmdump with `-vvv`?

**Comment by alanlonglong** [comment]
mac 10.15.3  always retry about TLSv1.2


---------start--------- type websocket
---------start--------- id 17f1739e-8ad1-4d4a-9880-647324729685
---------start--------- client_conn <ClientConnection: [TLSv1.2] 127.0.0.1:57146>
---------start--------- server_conn <ServerConnection: [TLSv1.2: widget-mediator.zopim.com] widget-mediator.zopim.com:443>
---------start--------- live None
---------start--------- error None
---------start--------- intercepted False
---------start--------- _backup None
---------start--------- reply <mitmproxy.controller.Reply object at 0x107c0a490>
---------start--------- marked False
---------start--------- metadata {'websocket_handshake': 'c45427a7-1ce0-4142-b7f7-38c02fb90a80'}
---------start--------- messages []
---------start--------- close_sender client
---------start--------- close_code CloseReason.NORMAL_CLOSURE
---------start--------- close_message (message missing)
---------start--------- close_reason unknown status code
---------start--------- stream False
---------start--------- handshake_flow <HTTPFlow
  request = Request(GET widget-mediator.zopim.com:443/s/W/ws/slUtsF+ZqfWv1X9Q/c/1586073818445)
  response = Response(101 Switching Protocols, no content)
  client_conn = <ClientConnection: [TLSv1.2] 127.0.0.1:57146>
  server_conn = <ServerConnection: [TLSv1.2: widget-mediator.zopim.com] widget-mediator.zopim.com:443>>
---------start--------- ended False
---------start--------- _inject_messages_client <queue.Queue object at 0x107d87e90>
---------start--------- _inject_messages_server <queue.Queue object at 0x107c0a150>
---------start--------- client_key GggoucT+0FEQNox1jdY8Bw==
---------start--------- client_protocol None
---------start--------- client_extensions permessage-deflate; client_max_window_bits
---------start--------- server_accept S/3xyfqpW9/xi26h6o1AGVAv9A8=
---------start--------- server_protocol None
---------start--------- server_extensions None

**Comment by tsujp** [comment]
@Kriechi  ah whoops, maybe I had borked something earlier but I took the certificate defintion off and am getting this error now, as with `-vvv`.

```
192.168.1.139:48892: clientconnect
::ffff:192.168.1.139:48892: Establish TLS with client
 << Invalid HTTP request form (expected: authority or absolute, got: relative)
::ffff:192.168.1.139:48892: request
  -> HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)
192.168.1.139:48892: clientdisconnect
```

> Does the game still work with mitmproxy/mitmdump active, or do all requests fail?

All online requests fail with the error described at the top of this comment.

> Which mitmproxy version?
> Which OS?

Mitmproxy: 5.0.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1e  17 Mar 2020
Platform:  Linux-5.5.10-arch1-1-x86_64-with-glibc2.2.5


> How do you configure your game to use mitmproxy?

```bash
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -w net.ipv4.conf.all.send_redirects=0
sudo iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner mitmproxyuser --dport 80 -j REDIRECT --to-port 8080
sudo iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner mitmproxyuser --dport 443 -j REDIRECT --to-port 8080
sudo iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner mitmproxyuser --dport 60442 -j REDIRECT --to-port 8081
```

The last line redirects the games specific 60442 to 8081 instead of 8080 so that I can use mitmdump for that. Then:

```bash
sudo -u mitmproxyuser bash -c 'mitmproxy --mode transparent --showhost --set block_global=false --set keep_host_header=true'

mitmdump -s ./foobar.py -p 8081
```

> Did you try mitmproxy/mitmdump with -vvv?

I have done now and have posted the error at the top of this comment.

**Comment by tsujp** [comment]
If I add `--mode transparent` (I forgot) I instead get:

```
192.168.1.139:49052: clientconnect
::ffff:192.168.1.139:49052: Establish TLS with client
::ffff:192.168.1.139:49052: request
  -> Request(GET /)
::ffff:192.168.1.139:49052: serverconnect
  -> ('37.187.27.57', 60442)
::ffff:192.168.1.139:49052: Establish TLS with server
192.168.1.139:40521: clientconnect
::ffff:192.168.1.139:40521: Establish TLS with client
192.168.1.139:40521: Client Handshake failed. The client may not trust the proxy's certificate for master.shirogames.com.
192.168.1.139:40521: ClientHandshakeException('Cannot establish TLS with client (sni: master.shirogames.com): TlsException("SSL handshake error: Error([(\'SSL routines\', \'ssl3_read_bytes\', \'tlsv1 alert decrypt error\')])")')
192.168.1.139:40521: clientdisconnect
192.168.1.139:49052: GET https://37.187.27.57:60442/
    Host: master.shirogames.com
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Key: SjNN5gbKf+FHXSzpc/3GUQ==
    Sec-WebSocket-Version: 13
    X-Ident: northgard
    X-Pass: 5b69ae0b2864a49d753b27fe974c36a485d605ca
 << Certificate verification error for master.shirogames.com: certificate signature failure (errno: 7, depth: 0)
::ffff:192.168.1.139:49052: serverdisconnect
  -> ('37.187.27.57', 60442)
192.168.1.139:49052: clientdisconnect
```

**Comment by Kriechi** [comment]
@mhils could this be a case of client cert pinning?

**Comment by mhils** [comment]
We have two separate issues here:

**First,** there is a connection from :49052 which is intercepted just fine. However, the upstream server's certificate is not trusted, which is why mitmproxy does not continue: 
```
192.168.1.139:49052: GET https://37.187.27.57:60442/
    Host: master.shirogames.com
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Key: SjNN5gbKf+FHXSzpc/3GUQ==
    Sec-WebSocket-Version: 13
    X-Ident: northgard
    X-Pass: 5b69ae0b2864a49d753b27fe974c36a485d605ca
 << Certificate verification error for master.shirogames.com: certificate signature failure (errno: 7, depth: 0)
```
The fix here is to set mitmproxy's ssl_insecure option to true.


**Second,** there is a connection from :40521 which we can't intercept:
```
192.168.1.139:40521: Client Handshake failed. The client may not trust the proxy's certificate for master.shirogames.com.
192.168.1.139:40521: ClientHandshakeException('Cannot establish TLS with client (sni: master.shirogames.com): TlsException("SSL handshake error: Error([(\'SSL routines\', \'ssl3_read_bytes\', \'tlsv1 alert decrypt error\')])")')
```
This likely is certificate pinning.

**Comment by danghuong18** [comment]
> We have two separate issues here:
> 
> **First,** there is a connection from :49052 which is intercepted just fine. However, the upstream server's certificate is not trusted, which is why mitmproxy does not continue:
> 
> ```
> 192.168.1.139:49052: GET https://37.187.27.57:60442/
>     Host: master.shirogames.com
>     Upgrade: websocket
>     Connection: Upgrade
>     Sec-WebSocket-Key: SjNN5gbKf+FHXSzpc/3GUQ==
>     Sec-WebSocket-Version: 13
>     X-Ident: northgard
>     X-Pass: 5b69ae0b2864a49d753b27fe974c36a485d605ca
>  << Certificate verification error for master.shirogames.com: certificate signature failure (errno: 7, depth: 0)
> ```
> 
> The fix here is to set mitmproxy's ssl_insecure option to true.
> 
> **Second,** there is a connection from :40521 which we can't intercept:
> 
> ```
> 192.168.1.139:40521: Client Handshake failed. The client may not trust the proxy's certificate for master.shirogames.com.
> 192.168.1.139:40521: ClientHandshakeException('Cannot establish TLS with client (sni: master.shirogames.com): TlsException("SSL handshake error: Error([(\'SSL routines\', \'ssl3_read_bytes\', \'tlsv1 alert decrypt error\')])")')
> ```
> 
> This likely is certificate pinning.

I cant capture websockets, could you help me?
I tried everything but it still didn't work.

**My version mitmproxy:**
Mitmproxy: 5.1.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Windows-10-10.0.18362-SP0

Thanks.
