### ISSUE TITLE
serverconnect - cert is alway None

### ISSUE THREAD

**Issue by mstrelex** [mitmproxy/mitmproxy#3907]
#### Problem Description
I've configured an mitmProxy in upstream mode, and trying to intercept the certificate it (Fiddler) presents to mitmProxy using an add-on. 

`cert` field from`mitmproxy.connections.ServerConnection` object is always _None_ 

Maybe I'm doing something wrong...

#### Steps to reproduce the behavior:
```pyhton
import mitmproxy
from mitmproxy import ctx


class MyAddon:

    def serverconnect(self, conn: mitmproxy.connections.ServerConnection):
        ctx.log.info("serverconnect: %s" % vars(conn))

addons = [
    MyAddon()
]
```

#### System Information
5.0.1

**Comment by Prinzhorn** [comment]
I think this was just recently fixed in #3881, the event is called too soon. Could you try with the master branch?

**Comment by Prinzhorn** [comment]
Pardon me, it's actually #3884 

In the mean time you can use `serverdisconnect` and the `cert` will be there

**Comment by mstrelex** [comment]
Thanks @Prinzhorn 

It is indeed returned in `serverdisconnect` and I will check master branch for `serverconnect `

I'm trying to create a custom "trust manager" by inspecting `cert.x509._subject_invalidator` and if it's created by a specific issuer, pass-trough the request, otherwise block it.

Any chance you can please point me to some sort of an example (if any exists) of how to do it?

**Comment by Prinzhorn** [comment]
> I'm trying to create a custom "trust manager" by inspecting `cert.x509._subject_invalidator` and if it's created by a specific issuer, pass-trough the request, otherwise block it.

In this case you can work around by using the `request` event and  `flow.kill()` if your check fails.

Pseudocode:

```
request(flow):
    if(flow.server_conn.cert......):
        flow.kill()
```

**Comment by mstrelex** [comment]
@Prinzhorn Thanks, but my goal is a bit different, I don't want to configure `ssl_verify_upstream_trusted_ca` in advance, and instead make the decision to accept the cert of the upstream proxy or not, in "runtime"... can this be achieved somehow?

**Comment by mhils** [comment]
I think @Prinzhorn's previous comment achieves just that. We will eventually expose the relevant OpenSSL bits in an addon, but for now @Prinzhorn's approach is probably the best way to go next to monkeypatching the core.
