### ISSUE TITLE
have issue about change one https to http in API response

### ISSUE THREAD

**Issue by majedalanni** [mitmproxy/mitmproxy#3909]
sorry for my question, but I'm not that expert and I would if you help me

I have API response body has url link start with HTTPS, can I use MITMProxy to change the URL HTTPS to HHTP?

**Comment by Prinzhorn** [comment]
There are multiple example scripts you can use as building block. A rudimentary version could probably be a one-liner that replaces all "https://" with "http://" in `flow.response.content`

https://github.com/mitmproxy/mitmproxy/blob/fbe296aaba774b01348a55a6c9e10097bfd61b60/examples/simple/internet_in_mirror.py

https://github.com/mitmproxy/mitmproxy/blob/fbe296aaba774b01348a55a6c9e10097bfd61b60/examples/simple/link_expander.py
