### ISSUE TITLE
Not able to bind one key for two different cmd under two different contexts

### ISSUE THREAD

**Issue by KevCui** [mitmproxy/mitmproxy#3911]
#### Problem Description

I'd like to bind `l` key as `console.nav.select` on `flowlist` and `console.nav.right` on `flowview`.

The `keys.yaml` looks like:

```
- 
  key: l
  ctx: ['flowlist']
  cmd: console.nav.select
- 
  key: l
  ctx: ['flowview']
  cmd: console.nav.right
```

However, mitmproxy seems to only get the latest keybinding in yaml file. In this case, `l` key won't perform `select` nav action on `flowlist`, only perform `right` nav action on `flowview`.

#### System Information

Mitmproxy: 5.0.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.5.9-arch1-2-x86_64-with-glibc2.2.5

**Comment by mhils** [comment]
Fixed by #3912, thanks again!
