### ISSUE TITLE
Client with no ability to install cert

### ISSUE THREAD

**Issue by majedalanni** [mitmproxy/mitmproxy#3917]
Hi,
if I have a machine with browser that locked very well and I cannot install cert on it, it uses only the public ones, also the browser wont open any self-sign website, is there a way I can install a cert in mitmproxy server from Comodo or any other cert provider to let the browser trust it ?

Thanks in advance

**Comment by mhils** [comment]
We have that described in the docs: https://docs.mitmproxy.org/stable/concepts-certificates/#using-a-custom-server-certificate. For further support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!
