### ISSUE TITLE
How to exit a request view ?

### ISSUE THREAD

**Issue by lefuturiste** [mitmproxy/mitmproxy#3919]
#### Problem Description

I'm on the `mitmproxy` flow cli interface and when I want to view a request I can't go back to see all the requests made.

#### Steps to reproduce the behavior:
1. Start for example : `mitmproxy --mode reverse:http://localhost:8000  --listen-port 8001 --listen-host 0.0.0.0`
2. Do a request
3. Open a detailed view of the request
4. How to get out of this view ? 

#### System Information

```
Mitmproxy: 5.0.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1e  17 Mar 2020
Platform:  Linux-5.5.13-arch1-1-x86_64-with-glibc2.2.5
```

I known this is a dumb issue but can't you make the control more clear? I can't find any info on the `?` pane

**Comment by sarthak212** [comment]
@lefuturiste you can go back with "q" to see all request and I think it's available at Global key bindings as `q Exit the current view`

**Comment by sarthak212** [comment]
![info](https://user-images.githubusercontent.com/33999269/78989881-7ba27300-7b52-11ea-8bba-3e89ad805ffe.png)
@mhils what do you think if we add info about q below request as 
`press tab to view response and q to view all requests`

**Comment by mhils** [comment]
I do agree that we have an usability problem here. The keybinding list is sorted by scope and alphabetically, which places `q` somewhere at the end. "press tab to view response" is already an ugly workaround, and I feel that adding more there isn't really helping. I would prefer to see improvements to the keybinding list, for example a list of manually-picked "common actions" at the top.

**Comment by sarthak212** [comment]
Yeah, you are right `q` is another common action that everybody uses in mitmproxy and improving keybinding list is a good option.
