### ISSUE TITLE
Colorize JSON Contentview

### ISSUE THREAD

**Issue by lefuturiste** [mitmproxy/mitmproxy#3920]
I use mitmweb or mitmproxy to debug webhooks call to my api, often these webhooks are full of useful JSON data. So I think a JSON syntax coloration is a key feature for a proxy like that. May be I don't have it enabled or whatever and this feature is already implemented but not enabled by default ?

**Comment by mhils** [comment]
That sounds like a useful feature suggestion! We do have support for syntax highlighting for contentviews (see the hex view for example), if someone would extend the JSON view to do that, that'd be great! 😃
