### ISSUE TITLE
Document mitmweb architecture

### ISSUE THREAD

**Issue by oxr463** [mitmproxy/mitmproxy#3925]
There are two components:

- Server: [`mitmproxy/tools/web/`](https://github.com/mitmproxy/mitmproxy/tree/master/mitmproxy/tools/web)

- Client: [`web/`](https://github.com/mitmproxy/mitmproxy/tree/master/web)

**Comment by oxr463** [comment]
How can I debug the server component? I would like to see logs for all events, such as toggling a setting in the UI.

**Comment by mhils** [comment]
What kind of documentation would you be looking for? If you want to debug mitmweb's server side, my personal recommendation would be to debug it in PyCharm and set breakpoints in the handlers in https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/web/app.py.
