### ISSUE TITLE
Automated Installer package for OSX security certificate

### ISSUE THREAD

**Issue by kand617** [mitmproxy/mitmproxy#3926]
Feature Request:

To ease the OSX installation of the certificate, one could create a installer?
Similar to the one below? 

https://support.securly.com/hc/en-us/articles/206058318-How-to-install-the-Securly-SSL-certificate-on-Mac-OSX-

I think this is quite nice, it downloads the certificate and then trusts it automatically.

**Comment by mhils** [comment]
The mitmproxy CA certificate is unique per installation, so we will definitely not do what the company you linked to is doing.

Other than that, I'm slightly :-1: on signing mitmproxy binaries. We've seen evidence of people shipping mitmproxy as-is with a small malicious Python add-on as malware. Our target audience will likely just `brew install` anyways, so essentially we're just making malware easier to deploy...

**Comment by Kriechi** [comment]
yep.
