### ISSUE TITLE
cannot import  name 'code' from 'bson.code'

### ISSUE THREAD

**Issue by javajiang** [mitmproxy/mitmproxy#3931]
#### Problem Description
when i use mitmpdump -s to insert  mongodb,first it should import pymongo,but it says cannot import  name 'code' from 'bson.code',the other module import success ,i don't know why.python version is 3.7

#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.

![微信图片_20200413150509](https://user-images.githubusercontent.com/20487883/79100151-4f783380-7d98-11ea-9f76-f786de9f052c.jpg)

**Comment by mhils** [comment]
Your addon uses additional dependencies, which aren't included in the precompiled binaries we ship:

> If your mitmproxy addons require the installation of additional Python packages, you can install mitmproxy from PyPI. [[src]](https://docs.mitmproxy.org/stable/overview-installation/#installation-from-the-python-package-index-pypi)
