### ISSUE TITLE
mitmproxy/mitmproxy:latest Docker image: env: can't execute 'bash': No such file or directory

### ISSUE THREAD

**Issue by MagnificentUrukHai** [mitmproxy/mitmproxy#3933]
#### Problem Description
I was using mitmproxy/mitmproxy:latest Docker image as a base for my custom image. In my image entrypoint script uses tiny shell script to set up certificates from the environment variable. Today I noticed that my container doesn't start and crashes with the following error:
```
env: can't execute 'bash': No such file or directory
```
My shell script:
```
#! /usr/bin/env sh

PEM=$SERVER_PEM

if [ -z "$PEM" ]; then
    echo "Server PEM is not set"
    exit 1
fi

echo "$PEM" > ./server.pem

echo "Server PEM is set"
```
With mitmproxy/mitmproxy:5.0.1 image everything is fine. 

#### Steps to reproduce the behavior:
`docker run -it --rm mitmproxy/mitmproxy:latest sh`

#### System Information
mitmproxy/mitmproxy:latest Docker image
Docker Desktop 2.2.0.5 on macOS Catalina 10.15.3

**Comment by Kriechi** [comment]
We updated to the most recent alpine base image (from 3.8 which is EOL, to 3.11).
You probably just need to install sh or bash inside the container.

**Comment by Kriechi** [comment]
Mhm on second thought - we do depend on bash for our entrypoint script...

**Comment by Kriechi** [comment]
@MagnificentUrukHai please try with the most recent `dev` tag of the Docker image - it should fix the problem. I plan to release a proper bugfix release later today.

**Comment by MagnificentUrukHai** [comment]
Thanks, I will try a little later today!

**Comment by MagnificentUrukHai** [comment]
Confirming, both `latest` and `dev` tags work as expected.
