### ISSUE TITLE
Client constantly connecting and disconnecting

### ISSUE THREAD

**Issue by helloitsm3** [mitmproxy/mitmproxy#3939]
#### Problem Description
Client is constantly connecting/disconnecting. I'm unable to load mitm.me to download the certificate on my IOS device.

#### Steps to reproduce the behavior:
1. Download MITM proxy
2. Set up device proxy
3. Try to access the certification download page

#### System Information
Paste the output of "mitmproxy --version" here.
mitmproxy latest version as of 15 April 2020. 
Windows 10
IOS 13.3.1

**Comment by naivekun** [comment]
Maybe you should access `http://mitm.it` to download certificate?

**Comment by helloitsm3** [comment]
> 
> 
> Maybe you should access `http://mitm.it` to download certificate?

I found out the problem. Apparently for IOS, you need to enable root access for the certificate in order for it to work

**Comment by empty-id** [comment]
What do you mean? How to enable root access on IOS ??? @helloitsm3
