### ISSUE TITLE
Certificate verification error for host. Hostname mismatch (errno: 62, depth: 0)

### ISSUE THREAD

**Issue by Satamana** [mitmproxy/mitmproxy#3942]
#### Problem Description
Certificate verification error. We use a docker with Katalon base image that running Chrome with python and get mitmproxy dump (mitmproxy use upstream proxy). Firstly we generate mitm certificate, copy to ca-certificates folder and update certificates. After we create certificates DB for browsers and certificates for browsers to trust. That way worked on mitmproxy 5.0.1 fine. On 5.1.1 we get:

```
clientconnect
Certificate verification error for accounts.google.com: Hostname mismatch (errno: 62, depth: 0)
Invalid certificate, closing connection. Pass --ssl-insecure to disable validation.
clientdisconnect
```

#### System Information
Docker container with [katalonstudio/katalon:7.2.4](https://hub.docker.com/layers/katalonstudio/katalon/7.2.4/images/sha256-8d9208c09594bcc1338c95c673b1c8af7fd3996ec3fdb74a48d5120deab4a6cd) image
chrome 81.0.4044.92
python 3.6
mitmproxy 5.1.1

**Comment by mhils** [comment]
This error indicates that mitmproxy doesn't trust the upstream certificate. Does mitmproxy receive the correct certificate from upstream? We'd need a minimal reproducible example if you suspect this is a mitmproxy bug.
