### ISSUE TITLE
Use markdown code blocks for documentation

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#3946]
**Is your feature request related to a problem? Please describe.**
The `{{< highlight none >}} :~q:foo:bar {{< / highlight >}}` blocks don't work on GitHub. It's confusing and makes the code examples almost useless on GitHub itself. And also in your code editor if you have Markdown syntax highlighting with embedded highlighting for nested code.

#### Describe the solution you'd like
It'd be neat if we could switch to using the standard triple backticks. I didn't search for it, I guess this has to do with how the website is generated from the markdown files. Can this be updated?

**Comment by mhils** [comment]
We use Hugo for the website. It looks like this can be done by setting `pygmentsCodefences = true` in config.toml. I haven't looked more into it, but I'd be happy to merge a PR! Instructions for getting the docs up and running locally are at https://github.com/mitmproxy/mitmproxy/blob/master/docs/README.md.

**Comment by Prinzhorn** [comment]
Nice. I won't jump onto that right now, so if anyone is interested feel free to look into it.

**Comment by deepanshululla** [comment]
I would like to take this on.

**Comment by deepanshululla** [comment]
is this all we need to do
```
baseURL = ""
languageCode = "en-us"
title = "mitmproxy.org docs"
theme = "mitmproxydocs"
publishDir = "../public"
RelativeURLs = true
googleAnalytics = "UA-4150636-13"
pygmentsCodefences = true
[indexes]
  tag = "tags"
```

**Comment by deepanshululla** [comment]
Hi, I created a PR for this issue. I would appreciate a review here for the same. @mhils @Prinzhorn  Thanks a lot for your time.
