### ISSUE TITLE
Looping Networks

### ISSUE THREAD

**Issue by gben733** [mitmproxy/mitmproxy#3953]
I am not being assigned an IP address. My device can see the network, but keeps looping between connecting states. 

#### Steps to reproduce the behavior:
1. Connect to the mitmproxy network on the device. 
2. Run the mitm_start on the virtual desktop  
3. 

#### System Information
Paste the output of "mitmproxy --version" here.

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
