### ISSUE TITLE
Feature: expose API from Headers class to replace all headers / allow strings in constructor

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#3954]
#### Is your feature request related to a problem? Please describe.
I'm spawning `mitmdump` from another process. They communicate via gRPC. The parent process implements things like replacements etc. because it will be hooked to a UI.

TLDR: Inside the `request` event I receive a list of updated header tuples from the parent process and need to replace the full `flow.request.headers`. There is no super straight forward way because I also need to turn the strings I get from gRPC into bytes.

#### Describe the solution you'd like
Looking at the current implementation it is somewhat schizophrenic. First all the name/value pairs are type checked, and then the loop does `_always_bytes` anyway. Either one of them needs to leave. If the type check is removed I can just pass strings to it.

https://github.com/mitmproxy/mitmproxy/blob/2774928319b706d8b6f85919f8811776342986c9/mitmproxy/net/http/headers.py#L80-L88

I mean APIs like `insert` already accept strings, so maybe it would be most consistent to just allow them in the constructor as well? I don't see a reason not to.

Edit: whoops, I guess there's a different between fields vs headers argument. My Python skills reach its limit right about here.

#### Describe alternatives you've considered

This is what I'm currently doing, essentially duplicating/copying code from mitmproxy.

```python
# https://github.com/mitmproxy/mitmproxy/blob/2774928319b706d8b6f85919f8811776342986c9/mitmproxy/net/http/headers.py#L15-L16
def _always_bytes(x):
  return strutils.always_bytes(x, "utf-8", "surrogateescape")

if reply.replace_headers:
  flow.request.headers = mitmproxy.net.http.Headers(
    [
      (_always_bytes(header.name), _always_bytes(header.value))
      for header in reply.headers
    ]
  )
```

`reply` is the gRPC reply, essentially

```proto
message HTTPHeader {
  string name = 1;
  string value = 2;
}

message RequestReply {
  bool replace_headers = 1;
  repeated HTTPHeader headers = 2;
}
```

**Comment by mhils** [comment]
Hm... I think the current API is actually fine. If you know that you have strings, you can just call `.encode() on them:

```python3
mitmproxy.net.http.Headers([
      (x.name.encode(), x.value.encode())
      for x in reply.headers
])
```

Also, I'm getting more curious on what you are building. :-)

**Comment by Prinzhorn** [comment]
> If you know that you have strings, you can just call `.encode() on them:

Oh, so the `always_bytes` util is mostly needed to transparently handle strings and bytes? I was copying it just to make sure there are no subtle differences that I wasn't aware of. I guess I should use `surrogateescape` as well?

> Also, I'm getting more curious on what you are building. :-)

I bet :see_no_evil:

**Comment by mhils** [comment]
> Oh, so the `always_bytes` util is mostly needed to transparently handle strings and bytes? I was copying it just to make sure there are no subtle differences that I wasn't aware of. I guess I should use `surrogateescape` as well?

Yes. The only subtle difference is surrogateescape. If you know that you have valid UTF-8, you don't need that.

**Comment by Prinzhorn** [comment]
Another mystery solved, thanks!
