### ISSUE TITLE
Question: How is the decompression handled?

### ISSUE THREAD

**Issue by Nado15** [mitmproxy/mitmproxy#3957]
Hello everyone, 

I have a question regarding how decompression is handled with mitmproxy. I am trying to read some https requests, and I just see a mess. 

The HTTP Response includes: 

Content-Type: application/octet-stream
Accept-Encoding: gzip

In order to read the http body do I have to decompress the http body by myself or is it already decompressed but just maybe encrypted or compressed from the application?

**Comment by Prinzhorn** [comment]
> I am trying to read some https requests, and I just see a mess.

Please elaborate how you are currently reading them. In the mitmproxy UI? Using an addon?

gzip should be handled transparently, e.g. in the mitmproxy UI it says "[decoded gzip]".

What type of response are you expecting? `application/octet-stream` suggests that it might be a binary format and judging from your question you don't know which format?

**Comment by Prinzhorn** [comment]
> The HTTP Response includes:
> 
> Content-Type: application/octet-stream
> Accept-Encoding: gzip

I hadn't read that part carefully. Are you sure this is a _response_? `Accept-Encoding` is for requests.
