### ISSUE TITLE
iOS certificate expired as of 25 April 2020

### ISSUE THREAD

**Issue by dmorgun** [mitmproxy/mitmproxy#3959]
It looks like mitmproxy certificate generated by mitm.it for iOS has expired as of 25 April, 2020

STR:
1. Setup manual HTTP proxy in WiFi - Configure Proxy - Manual - Specify server/port
2. Run `mitmproxy` in console on MacOS
3. Open Safari on iOS and open mitm.it website - tap Apple
4. Go to General - Device Management - mitmproxy - Install the certificate - Tap More Details
5. Review expiration date

AR: Expired: 25 April 2020

System Information
Mitmproxy: 5.1.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  macOS-10.15.3-x86_64-i386-64bit

iOS: 13.3.1

**Comment by mhils** [comment]
Thanks for using mitmproxy for at least a year I guess. 😄 

For security reasons, the mitmproxy CA is generated uniquely on the first start and is not shared between mitmproxy installations on different devices. If you delete your local CA, a new one is generated on the next startup.

We should also display a warning that the CA has expired and needs to be regenerated. Is that not the case for you?

**Comment by dmorgun** [comment]
Hi @mhils I have tried deleting my local certificate from both iOS and MacOS keychain, but when I open `mitmproxy-ca-cert.cer` file from `~/.mitmproxy` it still shows that the certificate has expired on Apr 25, 2020.
I have updated my mitmproxy on MacOS via `brew upgrade mitmproxy` command today.

**Comment by mhils** [comment]
You have to delete the `mitmproxy-ca-*` files in `~/.mitmproxy`, and then restart mitmproxy.

**Comment by dmorgun** [comment]
@mhils It worked! Thank you so much :)
