### ISSUE TITLE
pip install fails 0.10.1 because of cryptography - OS X 10.9.5 (Mavericks)

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [mitmproxy/mitmproxy#396]
Installing mitmproxy with pip in a python 2.7.8 virtualenv fails because the cryptography package fails to install.

The workaround is found here: http://chriskief.com/2014/03/25/installing-cryptography-via-pip-with-macports-or-homebrew/

I have openssl installed with mac ports. By first installing cryptography using the command "`env ARCHFLAGS="-arch x86_64" LDFLAGS="-L/opt/local/lib" CFLAGS="-I/opt/local/include" pip install cryptography`" I was able to subsequently and successfully install mitmproxy.

**Comment by cortesi** [comment]
@JeNeSuisPasDave Dave, could you confirm that this is now fixed? I don't see this on Yosemite at the moment, but I do remember encountering this in the past.
