### ISSUE TITLE
Using mitmweb UI with Apache reverse proxy

### ISSUE THREAD

**Issue by tinwinaung** [mitmproxy/mitmproxy#3960]
#### WebSocket issue
I tried doing it but websocket give me issue

**Comment by Prinzhorn** [comment]
Please share more details of what you have tried and what exactly is not working as expected

**Comment by tinwinaung** [comment]
I am trying to reverse proxy it in Apache 

Client (browser) <-> Apache2 (reverse proxy) <-> MITMWEB (server)

#ProxyPass /mitm http://127.0.0.1:9090
#ProxyPassReverse /mitm http://127.0.0.1:9090


But mitm always redirect resources to the root and do not stay in proxy subfolder such as /static (expecting to be /mitm/static from client through Apache)

Even thought I try to add ProxyPass for static, websoket connection have problem.

**Comment by mhils** [comment]
Got you. I would recommend you use a dedicated subdomain.

I would accept a PR that fixes your issue, but I generally don't see a convincing use case to spend time on this.
