### ISSUE TITLE
How to make chrome trust mitmproxy.crt CA certificate

### ISSUE THREAD

**Issue by xuwintery** [mitmproxy/mitmproxy#3964]
####The environment
Docker IMAGE : selenium/node-chrome-debug
Chrome Version:81.0.4044.92 (Official Build) (64-bit)

#### Problem Description
I installed mitmproxy-ca-cert.pem CA certificate in the docker container of chrome, opened chrome, and prompted "not secure"
The method I have tried：
1.
$ sudo mkdir /usr/share/ca-certificates/extra
$ sudo cp mitmproxy.crt /usr/share/ca-certificates/extra/mitmproxy.crt
$ sudo dpkg-reconfigure ca-certificates
 2.
certutil -d sql:$HOME/.pki/nssdb -A -t C -n mitmproxy -i ~/.mitmproxy/mitmproxy-ca-cert.pem

3.
open Developer Tools > Security, and select View certificate
Click the Details tab > Export. Choose PKCS #7, single certificate as the file format（I do n’t know what “Export. Choose PKCS # 7, single certificate as the file format” means in this method，How do I get a file in "PKCS # 7" format）

#### System Information
Mitmproxy: 5.0.1
Python:    3.7.7
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
