### ISSUE TITLE
Issues with 5.1.1 on MacOS

### ISSUE THREAD

**Issue by marwinxxii** [mitmproxy/mitmproxy#3967]
#### Unknown locale exception

1. Install version 5.1.1
2. Run `mitmproxy` or `mitmdump`
3. Following exception is raised: `ValueError: unknown locale: UTF-8`

Happens because of [urwid 2.1.0](https://github.com/urwid/urwid/issues/377) and can be workarounded by

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
prior running `mitmproxy`

#### UI palette issues
After making `mitmproxy` run, I've noticed the following issues with UI:
- Everything is transparent
- No selection is highlighted in the options screen, in the flows screen, so it's impossible to understand what is currently selected

This is happening with default palette `solarized_dark`, with `solarized_light`, but `lowdark` looks fine (see screenshots below).

----
After rolling back to `5.0.1` everything is back to normal.
I wasn't sure if these are two separate issues or have one cause (`urwid` is my guess), let me know, if I should split the issue.

#### Screenshots
In the plain black/white terminal:
![image](https://user-images.githubusercontent.com/679204/80789917-b6b22800-8b8d-11ea-9cfc-7543c101f0ee.png)

In the black/green terminal (selection highlight is missing on `key_size`):
![image](https://user-images.githubusercontent.com/679204/80790435-1fe66b00-8b8f-11ea-9866-e363790ec8e7.png)

`lowdark` theme that fixes things:
![image](https://user-images.githubusercontent.com/679204/80790381-f9283480-8b8e-11ea-87ed-6cc3334960aa.png)

**Comment by mhils** [comment]
Thanks for the detailed report! Could you check if the transparency issues can be fixed by setting `console_palette_transparent` to false on 5.1?

**Comment by marwinxxii** [comment]
> Could you check if the transparency issues can be fixed by setting `console_palette_transparent` to false on 5.1?

`false` is the default value, but setting it to `true` makes colors slightly better (more contrast), but there is still no selection highlight.

![image](https://user-images.githubusercontent.com/679204/81005266-f444d880-8e4d-11ea-986f-396a00fcbde2.png)

**Comment by mhils** [comment]
Thanks. Looks like we really should downgrade urwid (see also #3936). We can probably monkeypatch https://github.com/urwid/urwid/pull/304/files, which is why @Kriechi bumped urwid in https://github.com/mitmproxy/mitmproxy/issues/3765.

**Comment by t0rr3sp3dr0** [comment]
Any updates on this?

**Comment by mhils** [comment]
We've downgraded urwid to 2.0.1 for now, which should fix this issue. We'll hopefully be back with full color support soon!
