### ISSUE TITLE
How to remove someone in response headers by mitmproxy

### ISSUE THREAD

**Issue by otherbanana** [mitmproxy/mitmproxy#3968]
For example I want to remove "Server" in response header 

![微信图片_20200502000514](https://user-images.githubusercontent.com/34509569/80820700-fae30e00-8c09-11ea-9c1c-948d2fb6292d.png)

Is there a way can acheive this?

**Comment by mhils** [comment]
refs #3948

**Comment by mhils** [comment]
To answer your question: At the moment, you either do it manually/interactively, or you write a small addon that does just this.

**Comment by otherbanana** [comment]
Ok!Thank you so much.
I write a small addon such as:
if flow.request.url.startswith("https://example.com")\
   and ('example-header') in flow.response.headers:
del flow.response.headers['example-header']
