### ISSUE TITLE
GraphQL Request Body Is Formatted Incorrectly

### ISSUE THREAD

**Issue by uttiya10** [mitmproxy/mitmproxy#3971]
#### Problem Description
The request body shows new line characters and indents (see attached screenshot below)

#### Steps to reproduce the behavior:
1. Send a http request to a api endpoint that uses GraphQl (such as github api v4)
2. Look at the http request body that MitmProxy is showing.

#### System Information
Mitmproxy: 5.1.1 binary
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Windows-10-10.0.18362-SP0

#### Attached Pictures:
![image](https://user-images.githubusercontent.com/56562649/80848115-19341400-8be0-11ea-9afb-f15a1344bc2a.png)

**Comment by mhils** [comment]
That's not a mitmproxy bug. The "query" attribute in your screenshot is a string which contains escaped newlines. It's a string which first contains a `\` and then a `n`.
