### ISSUE TITLE
Encoding / charset guessing inconsistencies

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#3974]
#### Problem Description

This is unrelated to #3969, I'm just coincidentally looking into the whole encoding thing anyway (oh happy day).

I'm currently exposing `http.Message.guess_encoding` to be able to store it alongside the `content` in my addon. I figured this would be better than storing just  `content` (without knowing the encoding) or `text` (possibly wrongly encoded and I'd lose the original raw data) or both (wasting space). So I'm sending the `content` bytes alongside the `encoding` string via gRPC. I'm not touching `request/response.text` at all. I'd manipulate the stuff on the Node.js end and then send the `content` bytes back, preserving the encoding (I want to avoid the update magic here https://github.com/mitmproxy/mitmproxy/blob/dac0bfe786a8d1dfdd97f29d6bb262ed258153fa/mitmproxy/net/http/message.py#L218-L223)

If you look at the screenshot you'll notice what inconsistencies I'm talking about.

![Selection_621](https://user-images.githubusercontent.com/679144/80981617-80dd9f80-8e2a-11ea-93b2-c06c80b5a9bf.png)

1. I'm seeing multiple `"utf-8"` which comes from `text/html; charset="utf-8"`. Blame Facebook for the quotes (I'm not even sure what the spec says about it). But I think we need to handle them here https://github.com/mitmproxy/mitmproxy/blob/7fdcbb09e6034ab1f76724965cfdf45f3d775129/mitmproxy/net/http/headers.py#L191-L215. That's probably easier than convincing the Facebook team to update :smile: 
2. All "non-text" (I know it's impossible to know if something might not be text in the end using some weird encoding) falls back to `latin-1`. I'll have to think about this a bit more, I'm currently using https://github.com/gjtorikian/isBinaryFile on the Node.js end, which kind of works but fails for exotic encoding. At least I'd like to be able to distinguish between a `latin-1` that was found and `latin-1` the fallback.
3. I'm seeing `UTF-8` vs `utf-8` vs `utf8`. Maybe we should normalize them, but I assume every library will treat them equally (maybe we should lower-case them?)

Honestly I'm lacking energy right now to think about this in detail. I'll promise I come back.

**Comment by mhils** [comment]
Quotes are okay, see https://tools.ietf.org/html/rfc7231#section-3.1.1.1. I'm happy to accept a PR that improves the parser, but this doesn't really affect us. I'm closing this here as it isn't really a mitmproxy problem - it's `._guess_encoding` and not `.guess_encoding` for a reason. 😉 

In Python, normalization is done by the standard library (https://docs.python.org/3/library/codecs.html#standard-encodings). If you need to normalize, you can call `codecs.lookup(x).name`.

**Comment by Prinzhorn** [comment]
Thanks once again for your patience and help!

> Quotes are okay, see https://tools.ietf.org/html/rfc7231#section-3.1.1.1.

Nice. I was definitely expecting `codecs.decode(x, '"utf-8"')` to throw, but it just doesn't care. It's _very_ liberal and trims away everything it doesn't like. TIL.

```
>>> codecs.lookup('"~`+-*/_# \t\nutf8')
<codecs.CodecInfo object for encoding utf-8 at 0x7f69f7aa2e80>
```

So I guess this will do exactly what I need then :tada:
