### ISSUE TITLE
[DOC]  https://docs.mitmproxy.org/stable/concepts-filters page doesn't show "View Flow Selectors" section correctly

### ISSUE THREAD

**Issue by q2dg** [mitmproxy/mitmproxy#3975]
Markdown is right here (https://github.com/mitmproxy/mitmproxy/blob/c16b4887875bcdecdf18355f28347a48ba4297fd/docs/src/content/concepts-filters.md) but when rendered to HTML, this section is completely gone. 
Thanks!

**Comment by thunghan** [comment]
Seems like `unsafe` mode needs to be [enabled](https://gohugo.io/news/0.60.0-relnotes/) to render inline HTML in Markdown files.

Alternatively, we can create a simple shortcode to insert raw HTML, as shown in this [example](https://anaulin.org/blog/hugo-raw-html-shortcode/).

I can make a PR for either, do we have a preference?

**Comment by mhils** [comment]
Thanks for tracking this down @thunghan! I think setting unsafe=true is perfectly acceptable for our docs, we are in complete control of the source files. If you could send a PR that'd be highly appreciated!
