### ISSUE TITLE
How to run python scripts with mitmdump in windows 10

### ISSUE THREAD

**Issue by SumanDas94** [mitmproxy/mitmproxy#3978]
Not aware whether this has been looked into or not but trying to run mitmdump when installed via pip3 gives a bunch of errors when doing it in Windows 10. Is this scripting feature not configured for windows yet ?

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
