### ISSUE TITLE
Proxy with NTLM Authentication

### ISSUE THREAD

**Issue by Shnitzelil** [mitmproxy/mitmproxy#3979]
#### Is your feature request related to a problem? Please describe.
Would like to add support for proxy with NTLM authentication

#### Describe the solution you'd like
I made some initial work to support this and would like to share it with mitmproxy project.
I decided to use a 3rd party ntlm-auth version 1.4.0 for the handshake.

We need to add two more flags:

1. authentication type (basic or ntlm)
2. domain

Please advise what shall be my next steps.

**Comment by mhils** [comment]
Awesome! Please integrate your work into https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/proxyauth.py and then submit a PR here on GitHub!

**Comment by dopstar** [comment]
was this added or should i try to add it?

**Comment by Shnitzelil** [comment]
> was this added or should i try to add it?

sadly no...
