### ISSUE TITLE
Document installation of dependencies.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#398]
We have a variety of bug reports wrt. the installation procedure. While installing mitmproxy itself usually doesn't cause any issues, our dependencies often do ( #396, #379, ...).

We should document installation instructions for Linux, OSX and Windows, both for binary distributions as well as for installing from source.

refs: 
- https://gist.github.com/mhils/9315651
- #394
- https://groups.google.com/d/msg/mitmproxy/SoNVziqow3g/3dELw1BNjQsJ

**Comment by elitest** [comment]
Having worked in Ubuntu and Windows today re:#555, I'll give some feedback on this.  Are these reports a problem with pip, or are they problems with the libraries we rely on(i.e. something they need to fix), or are they a conflict in dependencies due to people installing conflicting stuff or not updating stuff with pip?

I find pip very fragile on Ubuntu, and the only reliable way I have found to update it is to use apt, rather then self-updating using pip.  I also find not working of virtual environments troublesome on Ubuntu due to the wide range of python stuff already installed, due to the risk of pip clobbering something.

I was pleasantly surprised by how well it seemed to work on Windows.  Now that pip is shipping with Python, perhaps just updating python will be the best way to update pip?

Most of the issues you reference are issues on OS X, I'm guessing due to the weird kludge of different version you can get yourself into on that platform.  Perhaps the binary installer for end users is better than using pip on this platform.

**Comment by mhils** [comment]
> Having worked in Ubuntu and Windows today re:#555, I'll give some feedback on this. Are these reports a problem with pip, or are they problems with the libraries we rely on(i.e. something they need to fix), or are they a conflict in dependencies due to people installing conflicting stuff or not updating stuff with pip?

The most common issues are old versions of pyOpenSSL lying around (see [here](https://github.com/mitmproxy/mitmproxy/blob/923503260ed48510da63e4dd1d6b36b4b859b110/libmproxy/main.py#L30-L48)) and missing dependencies (pip fails with a very obscure message if compilation of a binary module fails).

Given the fabolous state of Python packaging, we should always prefer binaries over manual installation. Maybe we could simplify the whole thing it as follows:

## Windows

`pip install mitmproxy` as the primary means (until we have Windows binaries). As you already described, this works pretty flawless.

### Installing from Source

Instructions for installing mitmproxy from source can be found in the README: https://github.com/mitmproxy/mitmproxy#hacking

## OSX

Using the binary should be the preferred way to install mitmproxy.
[Customization text as in the current docs...]

### Installing from Source

Homebrew/XCode Warning
See https://github.com/mitmproxy/mitmproxy#hacking

## Linux

1. List required packages (`build-essential python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev git python-pip` if I'm not mistaken)
2. `pip install mitmproxy`

### Installing from source

Install required pacakges, then https://github.com/mitmproxy/mitmproxy#hacking

-----

For Linux, we should work on a better solution in the long term (either binares or fix `apt-get install mitmproxy`, but I think that's the best we have at the moment.

Thanks for the great work you're doing!

**Comment by elitest** [comment]
So your suggestion is to reorg the docs to de-emphasize "Installing from Source"?  What about just moving the Installing from source section down to the bottom, and basically say a Homebrew/old dependencies/Here be dragons warning and then linking to the dev docs.

I struggled with whether or not to change the ordering, do we want to put Windows first?  I feel like the platforms that work "best" should go before Windows.

>For Linux, we should work on a better solution in the long term (either binares or fix apt-get install mitmproxy, but I think that's the best we have at the moment.

I have tried debian packaging and it is the type of thing that makes me realize why pip was created, and also why it is so much easier to run into problems with pip :).  But I totally agree about a Windows installer!

**Comment by mhils** [comment]
> So your suggestion is to reorg the docs to de-emphasize "Installing from Source"?

I just want to avoid that less experienced users which land on the installation instructions rather than the front page (where we have a big binary download link for the OSX binary) realize that there are easy-to-run binaries.

>  What about just moving the Installing from source section down to the bottom, and basically say a Homebrew/old dependencies/Here be dragons warning and then linking to the dev docs.

I'd be very much inclined to keep separate "build from source" sections even if that implies some duplication. This should be the primary topic of the page, the "use the binary" thing should just be a quick reminder for those who weren't aware of them.

> I struggled with whether or not to change the ordering, do we want to put Windows first?

Sorry, I didn't think about the Win/OSX/Linux order when writing this down :relaxed: . I adjusted the post above.

Thanks!
Max

**Comment by elitest** [comment]
I have made the discussed modifications, however, I have not linked to the binary installer for OS X.  If I did it would require someone to update the user install docs each release.  This could be changed if the binary installer was http://mitmproxy.org/download/osx-mitmproxy-latest.tar.gz or some such.

**Comment by mhils** [comment]
Excellent. I'll just merge that right away. :smile:
