### ISSUE TITLE
ValueError: too many values to unpack (expected 2) when passing more than two headers

### ISSUE THREAD

**Issue by mariolatiffathy** [mitmproxy/mitmproxy#3983]
#### Problem Description
Hello,

I am trying to forward the requests received by mitmproxy to an external API using `request` then return the new response body, status code, and headers to the client.

An example of what I am doing is:
```py
def request(flow: http.HTTPFlow):
    request = request.get("http://example.com")

    flow.response = http.HTTPResponse.make(request.status_code, request.text.encode(), request.headers)
```

However, the 3rd parameter of  `http.HTTPResponse.make` throws an error if there's more than two headers:
```
Addon error: Traceback (most recent call last):
  File "addon.py", line 38, in request
    flow.response = http.HTTPResponse.make(
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/net/http/response.py", line 92, in make
    resp.headers = nheaders.Headers(headers)
  File "/usr/local/lib/python3.8/site-packages/mitmproxy/net/http/headers.py", line 80, in __init__
    for key, value in self.fields:
ValueError: too many values to unpack (expected 2)
```

#### System Information
Mitmproxy: 5.1.1
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-glibc2.17

**Comment by dev-zarir** [comment]
I'm having the same problem. I also used the same as your code
