### ISSUE TITLE
Increase WebSocket message timestamp precision

### ISSUE THREAD

**Issue by JustAnotherArchivist** [mitmproxy/mitmproxy#3986]
#### Is your feature request related to a problem? Please describe.
Timestamps for WebSocket messages are rounded to whole seconds. For at least some protocols or analyses, a higher precision may be useful or even necessary for productive use; one example is measuring the performance impact of mitmproxy.

#### Describe the solution you'd like
Avoid converting the timestamp to an integer and use a float instead:

https://github.com/mitmproxy/mitmproxy/blob/7fdcbb09e6034ab1f76724965cfdf45f3d775129/mitmproxy/websocket.py#L28

Basic support for higher-precision timestamps seems to be as simple as changing the type of `WebSocketMessage.timestamp` from `int` to `float` and dropping the `int()` call around `time.time()`. I'm not sure if more is needed e.g. to ensure backward compatibility, but I was able to read a previous dump just fine with that modification (which makes sense since integers in the relevant range are strictly a subset of double-precision floats).

#### Describe alternatives you've considered
If keeping the `timestamp` an `int` is unavoidable, the Linux approach of storing the microseconds in a second integer (between 0 and 999999, inclusive) could be used. I don't think this is a good idea though.

#### Additional context
None

**Comment by mhils** [comment]
Thanks! You are absolutely right, this should just be a float. Happy to accept a PR that fixes this. :)
