### ISSUE TITLE
~websocket filter when reading from a file does not work

### ISSUE THREAD

**Issue by JustAnotherArchivist** [mitmproxy/mitmproxy#3990]
#### Problem Description
It appears that the `~websocket` filter, which is supposed to match all WebSocket flows per <https://docs.mitmproxy.org/stable/concepts-filters/>, does not match anything when reading from an existing dump.

#### Steps to reproduce the behavior:
1. Capture WebSocket traffic: `mitmdump -w infile ~websocket`
2. Apply a filter of `~websocket`: `mitmdump -nr infile -w outfile ~websocket`

The result is a non-empty `infile`, which contains the expected WebSocket messages, and an **empty** `outfile` even though they should contain the same data.

In addition, I also noticed that `mitmdump -nr infile` produces no output whatsoever, even with `-v` to increase the verbosity. I'm aware that the UI does not properly support WebSocket (#1020), but I'd expect it to at least report that messages exist as it does during dumping (i.e. `127.0.0.1:57466 -> WebSocket 1 message -> URL` etc.). This does not happen when the initial capturing is done without a filter, i.e. those "message" log lines appear in that case. This might point at a more fundamental issue with reading back the WebSocket data than just the filtering.

#### System Information
```
$ mitmproxy --version
Mitmproxy: 5.1.1 (+2, commit a8ca63f)
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.6.0-1-amd64-x86_64-with-glibc2.29
```

(Regarding the version number, see #3987; this is a clean 5.1.1 installation.)

**Comment by Kriechi** [comment]
The HTTP-WebSocket handshake flow is missing from the dump file, which seems to cause a few missing internal links...
I'll send a PR to fix this by also matching all HTTP-WebSocket handshake flows with the `~websocket` filter.
