### ISSUE TITLE
SSLKEYLOGFILE is not containing TLSv1.3 secrets

### ISSUE THREAD

**Issue by br-olf** [mitmproxy/mitmproxy#3994]
#### When using mitmproxy with the SSLKEYLOGFILE environment variable TLSv1.3 keys are not exported or correctly labeled. 

I want to analyze and decrypt TLSv1.3 traffic of an application with mitmproxy and Wireshark.
I configured a gateway running mitmproxy in transparent mode and inside mitmproxy the traffic gets decrypted but Wireshark can not decrypt the captured data using the keylogfile provided by mitmproxy. 
After some research I found [this presentation](https://lekensteyn.nl/files/wireshark-tls-debugging-sharkfest19us.pdf) regarding the decryption of TLSv1.3 traffic with Wireshark. On Slide 9 there is a keylogfile example for decrypting TLSv1.3. 
In the  keylogfile provided by mitmproxy I can't find any lines starting with CLIENT_HANDSHAKE_TRAFFIC_SECRET, CLIENT_TRAFFIC_SECRET_0 nor EXPORTER_SECRET but only ones starting with CLIENT_RANDOM.

#### Steps to reproduce the behavior:
1. Export the SSLKEYLOGFILE environment variable
2. Setup mitmproxy in transparent monde
3. Open a website using TLSv1.3
4. Check the keylogfile

#### System Information
Mitmproxy: 5.1.1 binary
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-5.5.0-kali2-amd64-x86_64-with-debian-kali-rolling

**Comment by mhils** [comment]
Thanks! We're currently waiting for upstream to expose the new OpenSSL hooks. For now the workaround is to disable 1.3 for key logging, eventually we'll support it properly. :)

refs https://github.com/pyca/cryptography/pull/5187
refs https://github.com/pyca/pyopenssl/pull/910

**Comment by iamtomkeen** [comment]
I'm sorry for disturbing, could you please advise when you plan to fix it?

**Comment by rugk** [comment]
https://github.com/pyca/pyopenssl/pull/910 has been merged just now, so that should not take that long…™

**Comment by iamtomkeen** [comment]
Looking forward to it 🤞

**Comment by iamtomkeen** [comment]
I'm not here to rush you (we are 1 week later now), just do you have any estimate for this fix?

**Comment by mhils** [comment]
No estimate. I don't think I will look into that before the next pyOpenSSL release with my changes ships.

I'd be more than happy to merge a PR that implements it directly on top of cryptography (the pyOpenSSL wrapper is minimal) if somebody wants to give it a stab.

**Comment by raboof** [comment]
So 'cryptography' has had the required change since version 3.0, but we're waiting for either:
* a post-19.1.0 release of pyOpenSSL
* someone to step up and build the feature directly on top of cryptography, side-stepping the missing pyOpenSSL release

**Comment by mhils** [comment]
Quick update: support for logging TLS 1.3 master secrets has landed on master and will be part of the next release. If you don't want to wait, you can use the snapshots from https://mitmproxy.org/downloads/#branches/master/. :)
