### ISSUE TITLE
Support for timeout generation

### ISSUE THREAD

**Issue by chapuzzo** [mitmproxy/mitmproxy#3997]
After digging in the documentation and code I have not found a proper way to generate a timeout.
so far the closer I got is this
`mitmproxy -p 8001 --mode reverse:http://localhost:8000 -s addon.py`

```python
def response(flow: http.HTTPFlow) -> None:
    if <some condition>:
        time.sleep(200)
```
which of course freezes the whole app making it unresponsive. 

Is there any other way to achieve that?

**Comment by mhils** [comment]
Take a look at https://github.com/mitmproxy/mitmproxy/blob/master/examples/complex/nonblocking.py! 😃

**Comment by chapuzzo** [comment]
thanks! you made my day 😄
