### ISSUE TITLE
API of getting length of http flow

### ISSUE THREAD

**Issue by mikesxf** [mitmproxy/mitmproxy#3999]
Hi, I am using mitmproxy to capture traffic and deal with it. And I notice that I can see the length of response using mitmproxy but I don't know how to get it by script. Anyone knows?
In addition, I am using mitmproxy 4.x now and I find that I can't find API docs that I can use in the script. I can only find the 2.x API. How could I find them now?
Thank you !

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
