### ISSUE TITLE
Option to serialize the event log

### ISSUE THREAD

**Issue by Fuzion24** [mitmproxy/mitmproxy#400]
It would be very nice to add an option to libmitmproxy to serialize the event log.

I have scripts that I run along with mitmdump. I use the context logging as meta data about the findings, it would be nice to get those stored alongside the traffic flows.

**Comment by cortesi** [comment]
A few comments.

- What goes to stdout for mitmdump is both the flow dump (dumper addon) and eventlog (termlog addon). 
- I think an addon that writes the eventlog specifically to a separate specified file would be a useful addition.
- I don't think putting the eventlog into the flow dump is the right move at this stage. We've been working on making sure that the dump format includes pretty much all the data you would get out of the core eventlog anyway, natively in the format. Anything "extra" is likely to be from addons or user scripts, and should probably not go in the dump format.
- That said, we do now have a general annotations mechanism for flows (flow.metadata), where scripts and addons can store additional data, which might satisfy some of the use case.

**Comment by Kriechi** [comment]
We have https://github.com/mitmproxy/mitmproxy/blob/0022c810e53eb0165abcdff2963100c78bcd4d7f/mitmproxy/addons/eventstore.py, which can be used to simply write event log entries to a text file or something similar.

**Comment by JohnTill123** [comment]
Are there any examples of how to export the event log using "eventstore.py"? It's not at all clear how to do that.

**Comment by sysraccoon** [comment]
For those who found this issue, but don't know how to make the corresponding addon:
https://gist.github.com/sysraccoon/50673fdd6c654791b6884faa2bb07228
