### ISSUE TITLE
Android emulator

### ISSUE THREAD

**Issue by syncgw** [mitmproxy/mitmproxy#4004]
I'm confused - I always get err_cert_authority_invalid on Android emulator.

1. Download AVD 28 (I tried 29, but there I could not get rw permission to install root certificate)
2. https://docs.mitmproxy.org/stable/howto-install-system-trusted-ca-android/
3. Double checked in emulator MITM root CA is installed
4. Started emulator -writable-system -http-proxy 192.168.10.100:8080
5. Some traffic showed up in MITM
6. Opened Chrome in emulator and tried to open page https://outlook.com

![grafik](https://user-images.githubusercontent.com/2334583/82187483-c8653080-98ec-11ea-9556-fd9024b19c7e.png)
![grafik](https://user-images.githubusercontent.com/2334583/82187650-03676400-98ed-11ea-9ac8-e29130169a53.png)

Mitmproxy: 5.1.1 binary
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Windows-10-10.0.18362-SP0

**Comment by sreejeet** [comment]
I think most probably your "MITM root certificate" is not installed as a "root certificate" on your virtual device. 

Just make sure you have followed step 3 of https://docs.mitmproxy.org/stable/howto-install-system-trusted-ca-android/ properly.

**Comment by syncgw** [comment]
Exactly what I did. And, as you can see. the outlook.com certificate is signed by mitmproxy. This would happen, if the certificate was not installed as root.

See the commands I used:
[MITM.cmd.txt](https://github.com/mitmproxy/mitmproxy/files/4673496/MITM.cmd.txt)

**Comment by mhils** [comment]
Are you using the latest mitmproxy version, and, if you have upgraded mitmproxy before, have you regenerated your CA certificate (delete ~/.mitmproxy, restart mitmproxy) and installed the new one?

**Comment by syncgw** [comment]
Hi, I use Windows version

> Mitmproxy: 5.1.1 binary
> Python:    3.7.6
> OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
> Platform:  Windows-10-10.0.18362-SP0

Unfortunately I cannot recreate certificates.  

- I tried to use [https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-windows.zip](url). There is no `mitmproxy.exe` file included and no certificates were created in `C:\Users\xxx\.mitmproxy`.

- Then I tried to use [https://snapshots.mitmproxy.org/5.1.1/mitmproxy-5.1.1-windows-installer.exe](url). Unfortunately no certificates were created as well.

- Finally I installed UBUNTU on Win10 and run `mitmproxy`. Now I got a certificate directory which I copied to `C:\Users\xxx\.mitmproxy`.

**Comment by mhils** [comment]
Sorry, I could have been more clear - any of our tools (mitmproxy/mitmweb/mitmdump) should regenerate certificates on startup. If you have current certificates, I'm not really sure what the issue is. mitmproxy works fine for me for my physical Pixel 3 (Android 10).

**Comment by syncgw** [comment]
OK, seems we found the issue. It's not a problem of communication - it is the issue, that mitm does not recreate new certificates under win10. How can I force mitm to create new certificates? New installation does not work. And I do not find any cmd line option to force recreation. May be this is an enhancement option...

**Comment by Kriechi** [comment]
After you delete your CA files from ~/.mitmproxy (or any similar config folder on Windows), mitmproxy/mitmdump/mitmweb will re-create the CA on the next launch. Then you can simply install the new CA on your phone/device/etc.

**Comment by syncgw** [comment]
**WARNING TO COMMUNITY**
I created this ticket, because on my Win10 the certificates were **NOT** recreated (even if I completely de install mitmproxy). I can delete files in C:\Users\Name\.mitmproxy or even the whole directory - nothing happens when restarting mitmproxsy.

Funny to see the suggested solution.

**Comment by Kriechi** [comment]
So what happens if you start mitmproxy AFTER deleting the files? Any errors? 
It probably should crash if what you are saying is true...

**Comment by syncgw** [comment]
I'm starting mitmweb.exe and Browser-Interface comes up (http://127.0.0.1:8081/#/flows). 
- Checking if certificate is imported in Win10 -> No
- Setting Win10 proxy to 127.0.0.1:8080
- Edge warns me about the certificate and I can view it (it is "mitmproxy")
- No glue from where mitmweb.exe is taking the certificate from

**Comment by Kriechi** [comment]
Certifcates are not imported automatically. They only get created at placed in `~/.mitmproxy/`.
https://docs.mitmproxy.org/stable/concepts-certificates/

Is this folder empty, or does it contain recently created files, e.g., `mitmproxy-ca.pem` ?

**Comment by syncgw** [comment]
This is also my understanding. I deleted this directory. directory does not exist - I deleted directory `C:\Users\Name\.mitmproxy` before I started the test I described. So it's a miracle where `mitmweb.exe` get's the certificate from... (as I stated - folder is not recreated during startup).

**Comment by Kriechi** [comment]
And after the test, after you stopped mitmweb.exe - the folder is still missing or empty?

**Comment by syncgw** [comment]
The folder is still missing.

**Comment by syncgw** [comment]
I found solution. I used "Process Explorer" to find location of certificates. `mitmweb.exe` is using environment variable `%HOME%` to locate directory where to create certificates in. This points in my system to a location which is not `C:\Users\name`... May be it would be a good idea to add this piece of information to documentation (for other users).

**Comment by mhils** [comment]
Our documentation consistently states `~/.mitmproxy`, `~` is generally considered to be `$HOME`/`%HOME%`.
