### ISSUE TITLE
[WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by justsouthern** [mitmproxy/mitmproxy#4007]
I am trying to run Reverse Proxy and I am getting the error message above. I found a couple of posts suggesting this was related to an out dated version of mitmproxy. I installed this fresh today on version 5.1.1 so I have the latest build that was published.

**Comment by mhils** [comment]
That's not a mitmproxy bug, that's a problem in your network configuration.

For further support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!
