### ISSUE TITLE
Hello. Are there plans for TLS 1.3 support? If so, when can one expect it to be implemented?

### ISSUE THREAD

**Issue by mansonami** [mitmproxy/mitmproxy#4008]
Tested on the newest version.

192.168.8.82:57954: CONNECT metrics1.data.hicloud.com:6447
 << Cannot establish TLS with client (sni: metrics1.data.hicloud.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')])")
192.168.8.82:57954: clientdisconnect
192.168.8.82:57964: clientconnect
192.168.8.82:57964: CONNECT sdkapiv2.bizport.cn:443
 << Cannot establish TLS with client (sni: sdkapiv2.bizport.cn): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')])")
192.168.8.82:57964: clientdisconnect

**Comment by mhils** [comment]
We support TLS 1.3 with the latest release. If you mitmproxy version doesn't have it, you are either using an outdated mitmproxy version or outdated dependencies (OpenSSL, cryptography, or pyOpenSSL).
