### ISSUE TITLE
mitmweb edit options: last option overflowing out of dialogue

### ISSUE THREAD

**Issue by FabianElsmer** [mitmproxy/mitmproxy#4010]
#### Problem Description
Opening the edit options in `mitmweb` shows the last option (websockets) mostly cut off.
The options dialogue opens all the way down to the bottom of the window, the last option overflows out of sight.

The option can still be seen and edited, by zooming out on the web page first.

![Screenshot from 2020-05-20 16-18-43](https://user-images.githubusercontent.com/9722121/82457607-e8941b80-9ab5-11ea-91fd-25cb0670df6c.png)

 
#### Steps to reproduce the behavior:
1. Run `mitmweb`
2. Go to http://127.0.0.1:8081/
3. Open edit options

#### System Information
Mitmproxy: 5.1.1 binary
Python:    3.7.6
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-4.20.8-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine

#### Browser
![Screenshot from 2020-05-20 16-44-51](https://user-images.githubusercontent.com/9722121/82460337-542bb800-9ab9-11ea-8798-f13bff9a5b6b.png)

**Comment by sreejeet** [comment]
Seems like a simple style issue. If can find a fix, I'll make a PR.
