### ISSUE TITLE
Script error:line 12: invalid syntax

### ISSUE THREAD

**Issue by vatsal245** [mitmproxy/mitmproxy#4015]
Whenever I open the sslstrip.py script it shows the error : "Script error:[Path Name]line 12: invalid syntax" and the connection is not established

**Comment by mhils** [comment]
You're using an outdated Python/mitmproxy version.

For further support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!
