### ISSUE TITLE
Traceback (most recent call last) problem fix

### ISSUE THREAD

**Issue by rashidh12** [mitmproxy/mitmproxy#4019]
![Screenshot_2020-06-03-03-56-59](https://user-images.githubusercontent.com/65683120/83575974-4dd41c00-a54e-11ea-876e-2ce3595f92e6.png)

**Comment by mhils** [comment]
Hi,

1. We don't support Python 2 anymore.
2. The error you are seeing is due to your script, not due to mitmproxy.
