### ISSUE TITLE
Migrate asynctest to stdlib's AsyncMock

### ISSUE THREAD

**Issue by rathann** [mitmproxy/mitmproxy#4020]
#### Problem Description
[test/mitmproxy/addons/test_readfile.py:5](https://github.com/mitmproxy/mitmproxy/blob/master/test/mitmproxy/addons/test_readfile.py#L5) imports `asynctest` which doesn't work with python 3.8 and above.

asynctest upstream is [aware](https://github.com/Martiusweb/asynctest/issues/132) of this breakage and recommends using the built-in [AsyncMock](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.AsyncMock) instead. See also [asynctest/issues/144](https://github.com/Martiusweb/asynctest/issues/144) and [asynctest/issues/126](https://github.com/Martiusweb/asynctest/issues/126) .

Fortunately, this is the only test that seems to be affected.

**Comment by Kriechi** [comment]
We do have a green CI test on Python 3.8:
https://github.com/mitmproxy/mitmproxy/runs/724843736?check_suite_focus=true

How is the test failing for you?

**Comment by mhils** [comment]
We probably want to migrate to the stdlib implementation here, but that requires us to drop Python 3.7 and below. I'd be fine doing this, but we're blocked by PyInstaller which does not support 3.8 yet (https://github.com/pyinstaller/pyinstaller/issues/4311).

**Comment by bnavigator** [comment]
You are using pytest-asyncio already. Replace the `asynctest.patch` calls with fixture from pytest-mock? https://github.com/pytest-dev/pytest-asyncio/issues/42

**Comment by mhils** [comment]
@bnavigator: works for me as well. If you would like to send a PR, that would be fabulous! 😃
