### ISSUE TITLE
"No internet connection" in Android's WIFI OS with mitmproxy, however interception works with other tools.

### ISSUE THREAD

**Issue by scramblr** [mitmproxy/mitmproxy#4022]
Steps to reproduce the problem:
mitmproxy

Install the mitmproxy certificate through http://mitm.it/
Start mitmproxy with mitmproxy -p 8080
Set proxy settings on Android Marshmallow or Nougat
Open the application
Get prompted with the error
Charles

Install the Charles proxy certificate through http://chls.pro/ssl
Start Charles
Set proxy settings on Android Marshmallow or Nougat
Open the application
See traffic in Charles
Any other comments?
I cannot see any traffic from the application in mitmproxy what so ever. Nothing. Could this be because the application blocks the mitmproxy certificate somehow?

System information
Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.1
Platform: Darwin-15.0.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0e 16 Feb 2017
Mac version: 10.11.1 ('', '', '') x86_64

Also installed and tried on an Ubuntu server.

-- Work around, which isnt a good fix, is to re-create a certificate manually and then re-import it, which is an advanced operation for many users. Since this definitely has something to do with the way mitmproxy is handling certs, I believe this bug is valid. 

Thanks.

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?
