### ISSUE TITLE
mitmweb: Rename File -> New to File -> Clear/Clear All/Clear Flows

### ISSUE THREAD

**Issue by GamiDPC** [mitmproxy/mitmproxy#4025]
There is not enough button to clear all requests

![image](https://user-images.githubusercontent.com/17031085/84072389-c405d200-a9d7-11ea-8c34-314206c654ac.png)

**Comment by mhils** [comment]
You can use File -> New, but we have now received enough bug reports to warrant renaming this option. :)

**Comment by yogeshojha** [comment]
Hi @mhils , I will be happy to take this up! Is the OP just asking for renaming Delete to the "Clear all" button or a separate "Clear all" button along with delete?

**Comment by mhils** [comment]
yeah this one is a duplicate. Let's just rename the existing button, otherwise one may reasonably ask what the difference between those two is.

**Comment by yogeshojha** [comment]
But @mhils, from a UX perspective, all other actions like replay, duplicate work for individual requests, and putting a "Clear All" button will be even more confusing, and chances are that the end-user may want to delete only one request for instance. The other time they may choose to delete everything. I think we should another button to clear all feature. What do say?

**Comment by mhils** [comment]
Maybe there is a misunderstanding: I'm proposing to rename File -> New to File -> Clear All.

**Comment by yogeshojha** [comment]
Awesome! I am clear now. Working on it!
