### ISSUE TITLE
Restructure Examples

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4031]
We currently have the following subdirectories in `examples/`:

- addons
- complex
- pathod
- simple

This structure is a bit weird because simple and complex actually contain addons as well. I propose the following changes:

1. Introduce an `examples/contrib` directory, which mostly contains most of the examples currently in `complex`. Most crucially, we add a README stating that we do _not_ maintain them, but welcome PRs to add/update. This allows us to be a bit liberal in what we accept here.
2. Merge `simple`, `addons`, and the remains of `complex` into a single `addons` folder.

@mitmproxy/devs, any opinions? :)

**Comment by Kriechi** [comment]
👍 with maybe one question / comment:
should we consider the difference of addons vs. scripts?
