### ISSUE TITLE
Allow mitmweb to be embedded

### ISSUE THREAD

**Issue by Poeschl** [mitmproxy/mitmproxy#4033]
#### Is your feature request related to a problem? Please describe.
I'm planing to integrate mitmweb into the smarthome system Home Assistant. For that I run it inside a docker container which gets all ports correctly and let `mitmweb` start as usual.

For a full integration it should be displayed inside the UI of Home Assistant as a panel. This is currently not possible since the `X-FRAME-OPTION` header is set to `DENY`.

#### Describe the solution you'd like
The direct solution would be configurable flag for the `X-FRAME-OPTION` header.

#### Describe alternatives you've considered
Add an option to set own headers for the `mitmweb` application.

#### Additional context
Screenshot how it looks right now.
![image](https://user-images.githubusercontent.com/5469257/84809937-ed8fb080-b00a-11ea-8292-666da93b202d.png)

**Comment by mhils** [comment]
I think you can easily work around this by running a reverse proxy in front of mitmweb which strips the x-frame-option header.

Such an option would only cover a very specific corner case but introduce 1) complexity and 2) a potential security issue.
