### ISSUE TITLE
Saving responses body to a json

### ISSUE THREAD

**Issue by aliasmicheal** [mitmproxy/mitmproxy#4034]
#### Is your feature request related to a problem? Please describe.
I am trying to scrape a website that uses ajax, there are hidden elements on every page that are not shown in the html elements. So the easiest place to look at all the information I need is in the network response body.

#### Describe the solution you'd like
If there was a way to create a json containing the response body of the filtered URL it would be much easier to extract the data.

#### Describe alternatives you've considered
I have filtered the URL and now trying to figure out how to extract all the responses to a json file.

#### Additional context
I am very new at programming and new to github, apologies if I missed some obvious solution.
I have created a question on stackoverflow to get a solution to my problem maybe it provides additional context
https://stackoverflow.com/questions/62414507/how-to-parse-a-mitmdump-file

**Comment by mhils** [comment]
See StackOverflow.
