### ISSUE TITLE
replay.client.stop crashes the client

### ISSUE THREAD

**Issue by Woolworths** [mitmproxy/mitmproxy#4037]
#### Problem Description
Running replay.client.stop (with or without pending replays) will crash the client and will require a full restart.

Versions:
MacOS 10.15.5 (19F96)
Python 3.7.7 (default, Mar 10 2020, 15:43:33)

The same also occurred on Ubuntu 20.04.

#### Steps to reproduce the behavior:
1. Launch mitmproxy with given version
2. Run :replay.client.stop
3. Whole client crashes

#### System Information
Mitmproxy: 5.1.1
Python:    3.7.7
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Darwin-19.5.0-x86_64-i386-64bit

**Comment by mhils** [comment]
Thanks for the straightforward repro!

**Comment by Woolworths** [comment]
@mhils No worries. I'll see if I can get to it in the near future (still a newbie to open source though).
