### ISSUE TITLE
Addons in mitmweb stops working when an addon adds a boolean option and that option is set in config.yml

### ISSUE THREAD

**Issue by andreas-wolf** [mitmproxy/mitmproxy#4047]
#### Problem Description
When an addon uses add_option to add a boolean and that boolean is set in config.yml all addons stop working.
I've tried the same with a string option, that was working ok. 
My assumption is that the yaml file is not parsed correctly. The following entries should be possible for a boolean: https://yaml.org/type/bool.html

Sample Addon optionstest.py:

```python
from mitmproxy import ctx
class OptionsTest:
    def load(self, loader):
        loader.add_option(
            name = "abool",
            typespec = bool,
            default = False,
            help = "A boolean",
        )

    def configure(self, updates):
        ctx.log.info('A boolean: %s' % ctx.options.abool)

    def response(self, flow):
        ctx.log.info('A boolean: %s' % ctx.options.abool)

addons = [
    OptionsTest()
]
```

sample config.yaml
`abool: true`

#### Steps to reproduce the behavior:
1. start mitmweb -s optionstest.py without a config.yaml -> see logmessages
2. add sample config.yaml
3. start mitmweb -s optionstest.py again -> no log messages

#### System Information
Mitmproxy: 5.1.1
Python:    3.8.3
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.4.0-39-generic-x86_64-with-glibc2.10

**Comment by mhils** [comment]
Thanks for the clean minimal example! This definitely looks like a bug. Is mitmdump/mitmproxy affected, too?

**Comment by andreas-wolf** [comment]
I assume so, since it is the config. I have no time to test more right now.

**Comment by mhils** [comment]
This should be fixed in mitmproxy 8! 😃
