### ISSUE TITLE
Can mitmproxy simulate weak network environment?

### ISSUE THREAD

**Issue by Pactortester** [mitmproxy/mitmproxy#4048]
Can mitmproxy simulate weak network environment?

I hope that we can use mitroxy to build weak network environment!

**Comment by Kriechi** [comment]
mitmproxy works on a higher level with HTTP requests, reponses, or Websocket. You can introduce a random sleep for these messages, or in streaming mode even for chunked body transfers.

mitmproxy does not support arbitrary TCP packet delays or packet loss, or any other form of traffic shaping.

**Comment by Sanmejie** [comment]
want to add this feature（weak network）+1
