### ISSUE TITLE
client certs - build for win32 like 4.0.4 instead of win64  add ecc compat

### ISSUE THREAD

**Issue by alexalwks** [mitmproxy/mitmproxy#4050]
1. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Can we get some client certs to be taken in consideration and exclude the rest?
Situation is like I added a client cert for 1 domain. The mitmproxy forwards the client cert. 
In some situations the client has more than 1 client certificates for multiple domains. 
Can we get an option where other client certificates are pulled directly from the clients browser if we do not add it to mitmproxy client certs folder? Even if the traffic cannot be intercepted, at least the client does not suffer of DoS because, like now, there is no option to let the client to select his certificate for some domain, or for any of them. If the client certificate does not exist selected in mitmproxy then the client has DoS because cannot authenticate in any way. Can an option be made to ignore mitm for any other domain where an client certificate is requested but does not exist selected in the folder of mitm client cert ?in case of client cert requests? Like no interception but, at least, the client does auth succesfully. 

2. Can there be builds for win32 instead of win64?
4.0.4 is only one build for win32 and works for both win32 and win64.
There is no effort in changing the build back to win32 and let all users enjoy an easy turnkey mitmproxy build.

3. Can we all get a Elliptic Curve certificates compatibility?

4. Question: If the default key size for RSA is 2048, could a 4096 RSA certificate work for some intercepted sites?

**Comment by alexalwks** [comment]
5. Can encrypted comms be dumped. Let's say if the client has a cert auth for SSL, can the traffic be dumped and tagged encrypted with host and client details?

**Comment by alexalwks** [comment]
6. Can a cipher be selected in the of encrypted traffic with an unknown client certificate? Most tricky question. It should be it would be a peak option

**Comment by mhils** [comment]
Hi, 

You're dumping a large list of questions and feature requests here, without putting too much effort into it. You kind of expect us to do your work for free, which is a bit rude. I'm closing this here because it's too much to answer and in many cases already discussed elsewhere. 

Please ask future questions on [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!
