### ISSUE TITLE
Inform the user when underscore-formatted options are used as a cli argument

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4054]
It might make sense to inform the user when underscore-formatted options are used as a cli argument, similar to the messages on deprecated commands.
At the moment it outputs: `mitmproxy: error: unrecognized arguments: --modify_body asdf`.

_Originally posted by @mplattner in https://github.com/mitmproxy/mitmproxy/pull/4046_

**Comment by MartinNuc** [comment]
Alright for all who ends up here like I do now :-) For CLI args you have to use dash: `--modify-body` instead of `--modify_body`
