### ISSUE TITLE
How to update options using python script without restart

### ISSUE THREAD

**Issue by hemantj** [mitmproxy/mitmproxy#4061]
I want to start mitmproxy, and later when I set option startInterception=True I should be able to record all the flows to a file, further when  I set option to startInterception=False, recording should stop.

I started mitmproxy using subprocess command and set option using
subprocess.Popen('mitmdump -s /Users/hemantj/PycharmProjects/OneRobot/record_script.py --set startInterception=True')

How can I set startInterception=False without stopping mitmproxy?

**Comment by mhils** [comment]
There is no `startInterception` setting in mitmproxy, `OneRobot/record_script.py` is not part of mitmproxy. Also, please don't cross-post between StackOverflow and here.

**Comment by hemantj** [comment]
record_script is my custom script in which I have created a new option using:
def load(loader):
    loader.add_option(
        "startInterception", bool, False,
        "start interception"
    )
