### ISSUE TITLE
mitmweb：show datetime with local timezone

### ISSUE THREAD

**Issue by FhyTan** [mitmproxy/mitmproxy#4071]
Is there a way to specify the timezone in mitmweb? It uses UTC time by default and I can't find a way to change it.

![image](https://user-images.githubusercontent.com/16273230/87008520-72c74900-c1f6-11ea-8a23-36026b50171b.png)

**Comment by lazyChan297** [comment]
i wanna use python script to get timing of flow，how can i get this value from api @mhils
