### ISSUE TITLE
I can't use WEBSOCKETS feature

### ISSUE THREAD

**Issue by danghuong18** [mitmproxy/mitmproxy#4077]
#### Problem Description
As mentioned in the title, I can't use the WEBSOCKETS feature, I tried everything but still couldn't catch the WEBSOCKETS packet via mitmproxy, could someone help me solve this problem? , I also tried it with transparent mode, but it made the phone I was using to debug can't connect to most websites.

Hope someone can help me with this.

#### System Information

> Mitmproxy: 5.1.1
> Python:    3.8.2
> OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
> Platform:  Windows-10-10.0.18362-SP0

**Comment by Kriechi** [comment]
Missing information on basically everything - closing.
