### ISSUE TITLE
Transparent mode on Linux

### ISSUE THREAD

**Issue by hinxx** [mitmproxy/mitmproxy#4079]
I can run regular mode just fine, but the target app on android is avoiding the proxy settings hence I wanted to use transparent proxying through my PC.

On the PC I executed:
```
sysctl -w net.ipv4.ip_forward=1
sysctl -w net.ipv6.conf.all.forwarding=1
sysctl -w net.ipv4.conf.all.send_redirects=0

iptables -t nat -A PREROUTING -i enx0 -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -t nat -A PREROUTING -i enx0 -p tcp --dport 443 -j REDIRECT --to-port 8080
iptables -t nat -I PREROUTING 1 -j LOG
iptables -t nat -I POSTROUTING 1 -j LOG
iptables -t nat -I OUTPUT 1 -j LOG

iptables -L -t nat 
```
The interface is wired (on PC), while the android uses wifi.
Then on android I've set the IP/netmask/DNS manually (static config) to the same values provided by my DHCP, and used PC IP for the gateway. Then I started the mitmproxy with: `mitmproxy --mode transparent --showhost` on the PC. I had the CA certs installed on the android already from using regular mode (I did remove the proxy server setting from the android).

Android says connected, but no internet access. I can ping local IPs (PC), but can not access any web address/IP; requests would time out.
On the PC, looking at the iptables logs, I can see lots of incoming packets from the android. I can get to mitm.it from android; I can see the requests for it in mitmproxy UI.

I'm doing this with a single Ethernet interface on the PC. Should I be doing this with two NICs? One for output traffic and another for input (android).
I have no other iptables rules defined. Should there be any in addition to those listed above?
DNS server IP address is public, providers DNS IP address, same ones as delivered by the modems DHCP server. Should I use local DNS IP from my subnet (not sure which one to use though)..

Not sure what is I going on?! Any help appreciated!

[BTW, this is with git code as of today.]

**Comment by Kriechi** [comment]
Do you see any traffic from your Android phone reach your PC?
Does mitmproxy show anything? Please also check the verbose / debug options.
Does Wireshark / tcpdump show incoming traffic?
Did you check https://docs.mitmproxy.org/stable/concepts-modes/#troubleshooting-transparent-mode ?

You might have more luck with further support and how-to questions on [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) - unless you get a mitmproxy crash or error that we can actually look into. Thanks!
