### ISSUE TITLE
PCAP support

### ISSUE THREAD

**Issue by kryptpt** [mitmproxy/mitmproxy#408]
Hi, 

I did something around this. It's a dummy script for mitmdump. 
Maybe with some help, I can integrate this into libmproxy.

**Comment by mhils** [comment]
Let me briefly summarize the current status of PCAP support in mitmproxy.

### Export

The recommended way to do this is to (1) log the TLS master secrets with mitmproxy and (2) use a normal PCAP tool for packet capture. mitmproxy works on TCP connections, we don't deal with raw packets internally.

### Import


@jbremer's [httpreplay](https://github.com/jbremer/httpreplay) comes with an `pcap2mitmproxy` binary. :smiley:

### Future Work

It would be nice to have a way to transform mitmproxy dumps into artifical PCAPs. We don't plan to implement this ourselves at the moment. External contributions are of course welcome. :smiley:

**Comment by mhils** [comment]
Closing this as there's we don't intend to work on PCAP export in the near future.

**Comment by jfunction** [comment]
If you just want to export to pcap without modification you can look into [PolarProxy](https://www.netresec.com/?page=Blog&month=2019-06&post=PolarProxy-Released). 

I have not used it before, just saw a post about it and eventually found my way to this issue so thought I'd share.
