### ISSUE TITLE
Turning on transparent mode made me unable to track on the phone.

### ISSUE THREAD

**Issue by danghuong18** [mitmproxy/mitmproxy#4082]
#### Problem Description
When I turned on transparent mode I could not track on the phone because I could not use the default port 8080 for the phone, instead the tracks were directly connected made on the desktop.

#### Steps to reproduce the behavior:
I run cmd with administrator privileges with the following command:

> mitmdump --mode transparent --ssl-insecure --rawtcp --flow-detail 5

#### System Information

> Mitmproxy: 5.1.1
> Python:    3.8.2
> OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
> Platform:  Windows-10-10.0.18362-SP0

Hope everyone help me solve this problem, thanks!

**Comment by mhils** [comment]
Hi,

You have opened three issues in four days now, mostly without any description that would we could use to help you.  
For support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!
