### ISSUE TITLE
MemoryError: mitmproxy has crashed

### ISSUE THREAD

**Issue by nikhil-dinesh** [mitmproxy/mitmproxy#4085]
#### Problem Description
**MemoryError: mitmproxy has crashed**

Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]: MemoryError
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]: mitmproxy has crashed!
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]: Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]: 192.168.50.117:60549: Traceback (most recent call last):
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:   File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:     root_layer()
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:   File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 19, in __call__
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:     layer()
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:   File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:     layer()
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:   File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:     layer()
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:   File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 190, in __call__
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:     if not self._process_flow(flow):
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:   File "/usr/local/lib/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 397, in _process_flow
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]:     self.read_response_body(f.request, f.response)
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]: MemoryError
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]: Exception in response:[Errno 12] Cannot allocate memory
Jul 16 13:02:40 cubedev-PowerEdge-R330 bash[21256]: message repeated 37 times: [ Exception in response:[Errno 12] Cannot allocate memory]
 

#### Steps to reproduce the behavior:
Issue observed when 2 clients are connected to mitmdump.The crash is observed within 10 minutes

#### System Information
 mitmdump --version
Mitmproxy: 5.1.1
Python:    3.6.0
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-4.15.0-45-generic-x86_64-with-debian-stretch-sid

**Comment by nikhil-dinesh** [comment]
When running mitmdump in transparent mode

**Comment by Kriechi** [comment]
Looks like your system is running out of memory. How much do you have? Please keep an eye on it and let us know how fast it grows.

**Comment by nikhil-dinesh** [comment]
total ram is 8GB and system free ram was around 3gb.The memory increase is observed within 10 minutes after clients are connected

**Comment by Kriechi** [comment]
Whats your CLI args? Are you trying to up-/download large files from your clients? mitmproxy keeps HTTP request & response bodies in memory (up to a certain limit), or you can configure it to stream directly to the client.

**Comment by nikhil-dinesh** [comment]
sudo mitmdump --mode transparent --showhost --set http2=false --ssl-insecure -s script.py

Do you know what is the memory limit for keeping the request-response body in the memory?

from clients probably streaming videos in youtube app.
Is it possible to delete the request-response body from the memory, once I consumed the data? or is there any settings for that?
Im simply reading the request-response and keeping it in my database.

**Comment by mhils** [comment]
1. Please don't use mitmproxy to proxy users who are unaware of that they are proxied.
2. Please read the docs regarding request/response streaming.

For further support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!

**Comment by nikhil-dinesh** [comment]
I'm not proxying my own devices. The setup is in a closed environment and streaming set of my own testing devices.
