### ISSUE TITLE
Problems with linux and transparent

### ISSUE THREAD

**Issue by fpusersuggest** [mitmproxy/mitmproxy#4090]
Hi,
I have some problems with ubuntu 19.10 and mitmproxy downloaded from the site.
I run mimtproxy on the same machine I want decrypt the traffic. The following are my iptables rules with **iptables -L -nv -t nat**:

```
Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:127.0.0.1:8080
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:127.0.0.1:8080
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8443 to:127.0.0.1:8080
```

and the following is the cm I use to run mitmproxy:

```
./mitmdump --mode transparent --showhost --listen-port 8080 --listen-host 127.0.0.1 --ssl-insecure
```

or

```
./mitmdump --mode transparent --showhost --listen-port 8080 --listen-host 127.0.0.1
```

but my firefox is unable to receive anything and in the mitmproxy console I have hundreds of the follwing errors:

```
172.27.142.115:44639: Certificate verification error for www.google.com: self signed certificate in certificate chain (errno: 19, depth: 1)
172.27.142.115:44639: Ignoring server verification error, continuing with connection
172.27.142.115:35677: Certificate verification error for www.google.com: self signed certificate in certificate chain (errno: 19, depth: 1)
172.27.142.115:35677: Ignoring server verification error, continuing with connection
```
About the certificate I have imported it by connecting to mitm.it, download the certificate for \*, copied in **/usr/share/ca-certificates/extra/**, then **dpkg-reconfigure ca-certicates** and activate the not active certificate. Then I take the certificate download with firefox and imported in ca autority on firefox after converting it with openssl.

**Comment by mhils** [comment]
The error you are seeing here is because mitmproxy encounters a self-signed certificate _upstream_, i.e. on the mitmproxy -- google.com connection. Given what you describe, it sounds like mitmproxy's own requests cannot escape your machine and are fed into mitmproxy itself again.
