### ISSUE TITLE
Proxyauth addon: LDAP tests are slow

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4091]
Our proxy auth LDAP tests seem to block on something. `test_configure` takes >5 seconds. We should track down where that comes from, my suspicion is that we don't mock sufficiently.

#### Steps to reproduce the behavior:
1. `pytest test_proxyauth.py`

**Comment by jrblixt** [comment]
I'm not able to reproduce this. Is it still an issue? All 22 tests run in about .52 seconds for me.

**Comment by mhils** [comment]
This indeed seems to be fixed, thanks @jrblixt!
