### ISSUE TITLE
Mitmproxy dont working on windows 10

### ISSUE THREAD

**Issue by Turkmen48** [mitmproxy/mitmproxy#4100]
#### Problem Description
Mitmproxy completely installed on windows10. But dont working. All of them is empty. There is no flow. Also ım using windows that's why "mitmproxy --version command" not working on cmd.
#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
windows 10 2004, wsl installed, mitmproxy version 5

**Comment by Turkmen48** [comment]
screenshot:
https://i.ibb.co/427SjGJ/Screenshot-2.png

**Comment by mhils** [comment]
You need to configure your browser/device/... to use mitmproxy. Are you doing that?

**Comment by Turkmen48** [comment]
yes ı did and solved. I used mozilla. But however ı dont sniff internet data of other devices of connect to same modem.

**Comment by mhils** [comment]
For further support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!
