### ISSUE TITLE
mitmweb: show tls/security details of connection/request (TLS protocol, cipher)

### ISSUE THREAD

**Issue by rugk** [mitmproxy/mitmproxy#4106]
#### Is your feature request related to a problem? Please describe.
It would be great to see which TLS protocol/things a connection uses to connect, to judge the security of that connection: https://github.com/mitmproxy/mitmproxy/issues/3326

#### Describe the solution you'd like
E.g. like the browser dev tools, here Firefox, shows it:

![grafik](https://user-images.githubusercontent.com/11966684/88668705-401cbc00-d0e3-11ea-9696-19aede17be1a.png)

#### Describe alternatives you've considered
Of course, you can wireshark the thing and look that up there, but that is inconvenient and cumbersome.

#### Additional context

BTW if you want to get inspiration, the Firefox devtools code is in https://github.com/firefox-devtools/

**Comment by mhils** [comment]
This should be easy to add in https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/tools/console/flowdetailview.py, I'd be happy to merge a PR!

**Comment by rugk** [comment]
Hmm, [I see it mentions the TLS version already there, e.g.](https://github.com/mitmproxy/mitmproxy/blob/1e5464a9e632b67df3d49d4e2e39e6b60eea5b0e/mitmproxy/tools/console/flowdetailview.py#L109), but I've never seen this in practice being shown. (v5.2 here)
But are you sure the linked part is about `mitmweb`? The filenames indicate it's about mitmproxy…

**Comment by rugk** [comment]
https://github.com/mitmproxy/mitmproxy/pull/4117 has been merged, so I'll close this here!

And thanks to @gorogoroumaru for implementing it. :smiley:
