### ISSUE TITLE
Arguments not recognized --console-focus-follow --stream-websockets

### ISSUE THREAD

**Issue by rugk** [mitmproxy/mitmproxy#4108]
#### Problem Description
The arguments ` --console-focus-follow --stream-websockets` are not recognized in my tests neither by `mitmproxy` nor by `mitmweb`.

Both options are documented on https://docs.mitmproxy.org/stable/concepts-options/ and you can enable in the web interface of `mitmweb`, but passing on the console fails. (And yes, I've triple-checked to get the rewrite from `_` to `-` correctly.)

#### Steps to reproduce the behavior:
1. With a saved file `mitmproxy --rfile ./mitmproxy-flow.cap -n  --console-focus-follow --stream-websockets`
2. OR, with `mitmweb`: `mitmweb --anticomp --anticache --mode transparent --web-port 1234 --save-stream-file "+$FLOWSAVE" --web-host 0.0.0.0 ` (where `$FLOWSAVE` is a file path)

#### System Information
```
$ mitmproxy --version
Mitmproxy: 5.2
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.4.51-v7l+-armv7l-with-debian-10.4
```

**Comment by gorogoroumaru** [comment]
It seems that we can't set --console-focus-follow and --stream-websockets directly.
Instead, we can do --set console_focus_follow=true --set stream_websockets=true.

"mitmproxy --rfile ./mitmproxy-flow.cap -n --console-focus-follow --stream-websockets" <- this doesn't work
=> "mitmproxy --rfile ./mitmproxy-flow.cap -n --set console_focus_follow=true --set stream_websockets=true" <- this works

**Comment by mhils** [comment]
What @gorogoroumaru said - that's also mentioned at the top of the page you linked. :)

**Comment by rugk** [comment]
Whaaat? By why does setting `--anticomp` work then – which is a boolean option??

IMHO this is not a good UX – if some options can be set in one way and other'S in another one… :thinking:

**Comment by rugk** [comment]
_If_ you really want to keep it that way, maybe adjust the error message to give a hint like "Do you possibly miss, using '--set'?"…
