### ISSUE TITLE
intercept_active toggle is not logical (and does not work)

### ISSUE THREAD

**Issue by rugk** [mitmproxy/mitmproxy#4109]
#### Problem Description
1. `intercept_active` has no documentation.
  It's documented [as](https://docs.mitmproxy.org/stable/concepts-options/):
   > Intercept toggle
   
   This is no doc, because it merely repeats the option's name.

   So I _guess_ it is supposed to disable all proxing and just forward requests (which is useful to do temporarily) – I do set `allow_hosts`  to `[*]` usually, because that works.

2. But when changing `intercept_active` to `true` in the web view, nothing visibly changes. It still intercepts everything and shows it to me…
3. The name is not logical – or the default value. If `intercept_active` defaults to _false_, it would mean it "intercept is not active", while `true` then is "intercept is active". As intercept is, however, _always active by default_ the default should be `true`, I guess…

## STR

transparent mode
`mitmweb --anticomp --anticache --mode transparent --web-port 1234 --save-stream-file "+$FLOWSAVE" --web-host 0.0.0.0 ` (where `$FLOWSAVE` is a file path)

#### System Information
```
$ mitmproxy --version
Mitmproxy: 5.2
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.4.51-v7l+-armv7l-with-debian-10.4
```

**Comment by mhils** [comment]
Thanks! That's definitely a documentation issue. `intercept_active` toggles if the `intercept` option is in effect, we need a better dosctring here. :)

**Comment by rugk** [comment]
I don't understand that explanation – yet again hehe, but I guess you mean the `intercept` filter (option `intercept`) documented one line before that actual option.
