### ISSUE TITLE
Many zeros lines/no secret data in SSLKEYLOGFILE?

### ISSUE THREAD

**Issue by rugk** [mitmproxy/mitmproxy#4110]
#### Problem Description
Sometimes, even when no connections yet show up in mitmweb IIRC, the `SSLKEYLOGFILE` already writes zeros?

If I [interpret the format correctly](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format) that means no secret data is saved. Thus, this makes the entry totally useless, I think…

Note that all entries that I need to decrypt, seem to be in there, so I don't see a problem.
Or are these possibly TLS 1.3 entries?? (see https://github.com/mitmproxy/mitmproxy/issues/3994)
-> If so, maybe you can still improve the error handling there. Possibly omit writing these useless values, and show an error/warning in the console for that, possibly…

#### Steps to reproduce the behavior:
1.  Start mitmweb with that variable?

What happens (an example file):
```
CLIENT_RANDOM eda2916696f45b75a2d728c9560050f7538a776ed01251baabf0c48cc289b286 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
CLIENT_RANDOM 3263fd6db1aa233f93d7cf6215fa6952aebb98ab55196c453509194b14d51fc8 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
CLIENT_RANDOM 6ae0c2a1a62377db612c359cc3c85a7c063b8e2301a0cfafbd55e06e2c9bf44e 88d02a778a3fc2c2[…]bd10237fbe450ab
```

#### System Information
```
$ mitmproxy --version
Mitmproxy: 5.2
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.4.51-v7l+-armv7l-with-debian-10.4
```

**Comment by mhils** [comment]
Not sure what's up here, but we can close this in favor of #3994. There's no point in spending additional cycles here instead of just using the new OpenSSL APIs. Thanks for the report anyways!
