### ISSUE TITLE
UDP Man-in-the-middle?

### ISSUE THREAD

**Issue by rugk** [mitmproxy/mitmproxy#4122]
#### Is your feature request related to a problem? Please describe.
UDP connections cannot be intercepted, I guess – [and your code says](https://github.com/mitmproxy/mitmproxy/blob/46fbba639dd3581fa427db6d26fa4775a991da59/test/mitmproxy/proxy/test_server.py#L491).

#### Describe the solution you'd like
Would it be possible to MITM UDP, too?

#### Describe alternatives you've considered
Looking around, Wireshark can of course MITM them, and [smithproxy](https://github.com/astibal/smithproxy) [seems to be able to do that](https://www.smithproxy.org/)…

#### Additional context
If you don't want that, due to some project idea, this is all fine.
I just found no rationale mentioned anywhere, that this explicitly mentions e.g. that mitmproxy cannot intercept UDP.
And it's said nowhere that this would be out-of-scope for this project.

Just saying this could be made more clearly in the docs, if you don't want it.
Or if you want, hmm, then this issue is an idea to track that, is not it?

I am looking forward to hear your opinion on this.

**Comment by Kriechi** [comment]
As clearly stated in multiple places:
> mitmproxy is a free and open source interactive HTTPS proxy.

> mitmproxy is an interactive, SSL/TLS-capable intercepting proxy with a console interface for HTTP/1, HTTP/2, and WebSockets.

All of these protocols are TCP-based. 

HTTP/3 will be using QUIC as transport layer, and therefore UDP - but we don't support this yet
.
I certainly would not reject a PR that clarifies some wordings in our docs - but I don't see any other action item on this for now.

**Comment by Manouchehri** [comment]
Would there be an easy way to pass some UDP traffic through without modifying it?

**Comment by mhils** [comment]
It's something we eventually want to support, but I'm not aware of any easy ways to do so at the moment.

**Comment by Manouchehri** [comment]
@mhils Hmm, how is `--rawtcp` implemented? I was thinking we could do something like that, but for `--rawudp`.

**Comment by mhils** [comment]
@Manouchehri, in a nutshell:

1. mitmproxy [spawns a regular TCP server](https://github.com/mitmproxy/mitmproxy/blob/50ae75aedf057b9e40ddcd82e7fbe772a29112b1/mitmproxy/addons/proxyserver.py#L101-L135).
2. The [NextLayer addon](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/next_layer.py) is asked by the [ConnectionHandler](https://github.com/mitmproxy/mitmproxy/blob/50ae75aedf057b9e40ddcd82e7fbe772a29112b1/mitmproxy/proxy/server.py#L91) which protocol layer should be used, it decides that [layers.TCPLayer](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/layers/tcp.py) should be used.
3. TCPLayer forwards messages as-is.

There are of course very simple ways to implement UDP forwarding, in particular if you are looking at rather stateless datagrams. We probably want to implement them in a similar manner using the sans-io architecture [I blogged about lately](https://mitmproxy.org/posts/new-proxy-core/). If you want to give this a go, don't hesistate to ask questions. I'd be happy to see a PR!

Things unfortunately become much more tricky when you look at stateful UDP, for example with QUIC. I haven't really spent too many brain cycles on this, but our end goal should certainly be to have HTTP/1 - HTTP/3 interop, which means it needs to be integrated in our existing layer architecture.
