### ISSUE TITLE
Cannot establish TLS with client (sni:***) 413 0b

### ISSUE THREAD

**Issue by kingkate** [mitmproxy/mitmproxy#4124]
hello! when i work with mitmproxy,i got an error with tls.
i have import the cert correctlly!
the detail is below:
for some reason i hide the real url; 
my mitmproxy version is 5.2 and platform is windows 10.

127.0.0.1:39200: GET https://8**/11/1 HTTP/2.0
              << 413  0b
127.0.0.1:39200: GET https://8**/11/1 HTTP/2.0
              << 413  0b
127.0.0.1:39200: GET https://8**/11/1 HTTP/2.0
              << 413  69b
127.0.0.1:39200: GET https://8**/11/1 HTTP/2.0
              << 413  0b
127.0.0.1:39208: GET https://8**/11/1 HTTP/2.0
              << 200  2.35k
127.0.0.1:39200: GET https://8**/11/1 HTTP/2.0
              << 413  0b
127.0.0.1:39200: GET https://8**/11/1 HTTP/2.0
              << 413  69b
127.0.0.1:39211: clientconnect
127.0.0.1:39211: GET https://8**/11/1 HTTP/2.0
              << 413  0b
and this

127.0.0.1:39201: CONNECT ***:443
 << Cannot establish TLS with client (sni: ***): TlsException("(-1, 'Unexpected EOF')")
127.0.0.1:39199: CONNECT ***:443
 << Cannot establish TLS with client (sni: ***): TlsException("SSL handshake error: SysCallError(10053, 'WSAECONNABORTED')")
127.0.0.1:39202: CONNECT ***:443
 << Cannot establish TLS with client (sni: ***): TlsException("SSL handshake error: SysCallError(10053, 'WSAECONNABORTED')")

can you tell me why? Thanks!!!

**Comment by magus0219** [comment]
I have the same issue and rollback to 5.1.1 resolve it

**Comment by mhils** [comment]
Not a mitmproxy bug, the client doesn't trust your proxy's certificate. You may be running into [Certificate Pinning](https://docs.mitmproxy.org/stable/concepts-certificates/#certificate-pinning)
