### ISSUE TITLE
get [Errno 92] Protocol not available when use --mode transparent

### ISSUE THREAD

**Issue by cw4t** [mitmproxy/mitmproxy#4128]
#### Steps to reproduce the behavior:
1. mitmdump --mode transparent --listen-host 10.1.10.160 --listen-port 8080
2. WebBrowser enterer: http://10.1.10.160:8080 
3. 10.1.10.160 Occured:  

```
csock.getsockopt(socket.SOL_IP, SO_ORIGINAL_DST, 16)
Traceback (most recent call last):
  File "/home/saicops/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
OSError: [Errno 92] Protocol not available
```

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 5.1.1
Python:    3.6.8
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-centos-7.6.1810-Core

**Comment by cw4t** [comment]
```
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
10.191.6.187:64479: Traceback (most recent call last):
  File "/opt/yearn/lib64/python3.6/site-packages/mitmproxy/proxy/server.py", line 121, in handle
    root_layer()
  File "/opt/yearn/lib64/python3.6/site-packages/mitmproxy/proxy/modes/transparent_proxy.py", line 22, in __call__
    layer()
  File "/opt/yearn/lib64/python3.6/site-packages/mitmproxy/proxy/protocol/tls.py", line 285, in __call__
    layer()
  File "/opt/yearn/lib64/python3.6/site-packages/mitmproxy/proxy/protocol/http1.py", line 83, in __call__
    layer()
  File "/opt/yearn/lib64/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 190, in __call__
    if not self._process_flow(flow):
  File "/opt/yearn/lib64/python3.6/site-packages/mitmproxy/proxy/protocol/http.py", line 321, in _process_flow
    f.request.host = self.__initial_server_address[0]
TypeError: 'NoneType' object is not subscriptable

10.191.6.187:64479: clientdisconnect
```

**Comment by Prinzhorn** [comment]
Well I'm getting an endless loop like this, which should definitely be fixed since it's essentially a DoS for the proxy when running in transparent mode.

```
192.168.0.6:55389: clientconnect
192.168.0.6:49659: clientconnect
192.168.0.6:34245: clientconnect
192.168.0.6:41959: clientconnect
192.168.0.6:55497: clientconnect
192.168.0.6:53023: clientconnect
192.168.0.6:41893: clientconnect
192.168.0.6:51987: clientconnect
192.168.0.6:59329: clientconnect
192.168.0.6:41083: clientconnect
192.168.0.6:46637: clientconnect
192.168.0.6:39395: clientconnect
192.168.0.6:37893: clientconnect
..................
..................
..................
192.168.0.6:40373: clientconnect
192.168.0.6:56579: clientconnect
192.168.0.6:35779: clientconnect
192.168.0.6:55115: clientconnect
192.168.0.6:41313: clientconnect
192.168.0.6:52161: clientconnect
192.168.0.6:33401: clientconnect
192.168.0.6:53179: clientconnect
192.168.0.6:34421: clientconnect
192.168.0.6:57131: clientconnect
192.168.0.6:57189: clientconnect
192.168.0.6:57653: clientconnect
Exception in thread ServerThread (('::', 8080, 0, 0)):
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/alex/.local/pipx/venvs/mitmproxy/lib/python3.8/site-packages/mitmproxy/master.py", line 37, in run
  File "/home/alex/.local/pipx/venvs/mitmproxy/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 619, in serve_forever
  File "/usr/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
```

But I don't think that's how transparent mode works. Why are you trying to open the proxy directly in your browser? What are you expecting to receive there?

https://docs.mitmproxy.org/stable/concepts-modes/#transparent-proxy

**Comment by cw4t** [comment]
I have fixed it, just list the iptables, amazing I aceess it directly just because I have account auth in the request function Thank you Chaserchasewater4truth@gmail.comSecurity Developer------------------ Original ------------------From: Alexander Prinzhorn  <notifications@github.com>Date: Wed,Aug 5,2020 5:35 PMTo: mitmproxy/mitmproxy <mitmproxy@noreply.github.com>Cc: cw4t <chasewater4truth@gmail.com>, Author <author@noreply.github.com>Subject: Re: [mitmproxy/mitmproxy] get [Errno 92] Protocol not available whenuse --mode transparent (#4128)
Well I'm getting an endless loop like this, which should definitely be fixed since it's essentially a DoS for the proxy when running in transparent mode.
192.168.0.6:55389: clientconnect
192.168.0.6:49659: clientconnect
192.168.0.6:34245: clientconnect
192.168.0.6:41959: clientconnect
192.168.0.6:55497: clientconnect
192.168.0.6:53023: clientconnect
192.168.0.6:41893: clientconnect
192.168.0.6:51987: clientconnect
192.168.0.6:59329: clientconnect
192.168.0.6:41083: clientconnect
192.168.0.6:46637: clientconnect
192.168.0.6:39395: clientconnect
192.168.0.6:37893: clientconnect
..................
..................
..................
192.168.0.6:40373: clientconnect
192.168.0.6:56579: clientconnect
192.168.0.6:35779: clientconnect
192.168.0.6:55115: clientconnect
192.168.0.6:41313: clientconnect
192.168.0.6:52161: clientconnect
192.168.0.6:33401: clientconnect
192.168.0.6:53179: clientconnect
192.168.0.6:34421: clientconnect
192.168.0.6:57131: clientconnect
192.168.0.6:57189: clientconnect
192.168.0.6:57653: clientconnect
Exception in thread ServerThread (('::', 8080, 0, 0)):
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/alex/.local/pipx/venvs/mitmproxy/lib/python3.8/site-packages/mitmproxy/master.py", line 37, in run
  File "/home/alex/.local/pipx/venvs/mitmproxy/lib/python3.8/site-packages/mitmproxy/net/tcp.py", line 619, in serve_forever
  File "/usr/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files

But I don't think that's how transparent mode works. Why are you trying to open the proxy directly in your browser? What are you expecting to receive there?
https://docs.mitmproxy.org/stable/concepts-modes/#transparent-proxy

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mitmproxy/mitmproxy/issues/4128#issuecomment-669090728",
"url": "https://github.com/mitmproxy/mitmproxy/issues/4128#issuecomment-669090728",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mhils** [comment]
@Prinzhorn: We already do this...

https://github.com/mitmproxy/mitmproxy/blob/49bc7d944a94f2e4bb0f7b9572234a5b67cb0fb2/mitmproxy/proxy/protocol/base.py#L103-L118

...which unfortuately doesn't cover all cases. If you have a better idea, I'm all ears. It's a bit of a tricky problem.

Other than that I'm closing here, it's a misconfiguration and the original author's problem is solved. :)

**Comment by Prinzhorn** [comment]
My first intuition would be to add `listen_host` to the list here `address[0] in ("localhost", "127.0.0.1", "::1") `? That would prevent the given case, right? But it wouldn't catch all cases either.

However, I'm not sure the code you've posted works at all in transparent mode. I don't know how mixins work but `server_address` is `None` in `ServerConnectionMixin`. So I don't know what I need to do to actually trigger an exception in `__check_self_connect`?

**Comment by mhils** [comment]
That's actually a good suggestion. Would you mind sending a PR? :)


> However, I'm not sure the code you've posted works at all in transparent mode. I don't know how mixins work but server_address is None in ServerConnectionMixin. So I don't know what I need to do to actually trigger an exception in __check_self_connect?

Yeah, please don't take `mitmproxy.proxy` as an example of good Python code. There is a reason why we want to replace it with a sans-io implementation 😄 The idea is that calls for `.set_server` are checked. It looks like you are actually right and we don't do that for transparent mode:
https://github.com/mitmproxy/mitmproxy/blob/49bc7d944a94f2e4bb0f7b9572234a5b67cb0fb2/mitmproxy/proxy/modes/transparent_proxy.py#L13

That line should probably use `self.set_server`. If you can repro that quickly on your local machine please feel free to include it in your PR. I will definitely copy over the self connect check, the mixin will be gone for good in sans-io.

**Comment by Prinzhorn** [comment]
>  There is a reason why we want to replace it with a sans-io implementation smile

There it is again :smile:

**Comment by cw4t** [comment]
the command to flush the iptables:` iptables -t nat -F`
