### ISSUE TITLE
Additional `text` property for WebSocketMessage or whatever

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4131]
#### Is your feature request related to a problem? Please describe.

Looking at the type declaration of `content` here

https://github.com/mitmproxy/mitmproxy/blob/b4bd1741eb48971a62b26d366bc6e2768350783e/mitmproxy/websocket.py#L19-L21

I was assuming `content` would always be of type `bytes`. However, it is of type `str` if the opcode is TEXT. The issue lies here
https://github.com/mitmproxy/mitmproxy/blob/70777a1b6ed64af9cafcdef223a8a260ecc96864/mitmproxy/proxy/protocol/websocket.py#L101-L110

I know it's kind of common to do that in a scripting language, but it's also harder to work with.

#### Describe the solution you'd like

I'm not sure if we should make a breaking change and introduce `text` similar to how it works with HTTP MessageData? And then keep `content` for the raw bytes? I'm open for anything, I was just irritated that the type is not consistent.

#### Describe alternatives you've considered

I'm using gRPC and had the type declared as `bytes`. I want the raw bytes. I guess I could do the conversion on my end and get the bytes of `content` if the opcode is TEXT. Working around it is not the issue, but I'd rather have consistency.

**Comment by mhils** [comment]
> I'm not sure if we should make a breaking change and introduce text similar to how it works with HTTP MessageData? And then keep content for the raw bytes? I'm open for anything, I was just irritated that the type is not consistent.

I really haven't looked at this for more than a second, but I remotely recall something about WebSocket TEXT frames having a very strictly defined encoding? It looks like we just forward what we get from wsproto. @Kriechi?

The second much simpler issue is that the type annotation is wrong in any case and needs to be fixed. :)

**Comment by Prinzhorn** [comment]
> I really haven't looked at this for more than a second, but I remotely recall something about WebSocket TEXT frames having a very strictly defined encoding? It looks like we just forward what we get from wsproto. @Kriechi?

I think so too (it looks it it's [strictly UTF-8](https://stackoverflow.com/a/43530268/1422124)) and wasn't implying that we need to do the encoding dance in the text getter/setter. I would be fine with keeping just `content` the way it currently is. It does make sense since it's _either_ text or binary and not like with HTTP bodies where you don't know for sure sometimes and want to string replace on jpeg meta data or whatever. I was just tired yesterday.

> The second much simpler issue is that the type annotation is wrong in any case and needs to be fixed. :)

I think I wouldn't have opened this issue with the correct typing, I was just digging into why gRPC was complaining that it was expecting bytes but received a string. It's all good :+1:
