### ISSUE TITLE
Downloading Cert

### ISSUE THREAD

**Issue by Vazza202** [mitmproxy/mitmproxy#4139]
When I go to mitm.it, it will not give me an option to download the certificates for windows or any other operating system.
Any suggestions?
![Capture](https://user-images.githubusercontent.com/49775722/89723064-831e3f80-d9bf-11ea-959f-378a72b92768.PNG)

**Comment by Vazza202** [comment]
Just found out how to do it my bad.

**Comment by Prinzhorn** [comment]
I was just about to ask for some details. I'd be curious what browser you were using since the website looks broken. How did you solve it?

**Comment by Wingysam** [comment]
@Vazza202 PLEASE tell me how! I have the same issue.

**Comment by Wingysam** [comment]
Switching from RPi to Macbook fixed the issue for me
