### ISSUE TITLE
TLS "invalid padding" error for transparently-proxied connections

### ISSUE THREAD

**Issue by avdi** [mitmproxy/mitmproxy#4149]
#### Problem Description
After following the directions for setting up transparent proxying, curl reports an "invalid padding" error:

```
curl -v https://icanhazdadjoke.com/ 
...
*   Trying 104.27.178.173...
* TCP_NODELAY set
* Expire in 149997 ms for 3 (transfer 0x55d8c4cd0f50)
* Expire in 200 ms for 4 (transfer 0x55d8c4cd0f50)
* Connected to icanhazdadjoke.com (104.27.178.173) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, decrypt error (563):
* error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
* Closing connection 0
curl: (35) error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
```

This worked for me a few months back. Now it's no longer working, in the same Debian Buster docker container. 

#### Steps to reproduce the behavior:
1. Follow the linux directions here: https://docs.mitmproxy.org/stable/howto-transparent/ with the modifications under "Work-around to redirect traffic originating from the machine itself".
2. Install root certificate in the OS as directed here: https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate/94861#94861
2. In another terminal on the same machine: `curl -v https://icanhazdadjoke.com/`
3. See error above

#### System Information
```
mitmproxy --version
Mitmproxy: 4.0.4
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-4.19.76-linuxkit-x86_64-with-debian-10.5
```

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by HoffmannP** [comment]
I can reproduce this error with 6.0.2 (no release in Github but download on homepage) and 6.0.1 (latest github release)
