### ISSUE TITLE
Apps work even when mitm proxy is offline

### ISSUE THREAD

**Issue by Keshvadi** [mitmproxy/mitmproxy#4151]
Hi, 

I set the proxy of the android smartphone to my PC IP address. But some apps like Likee or WhatsApp works even when my PC is turned off. 

I tried this on iPhone and they worked on iPhone too.

Is anybody explains to me how they work when network configuration is set to use proxy and proxy is offline?

**Comment by mhils** [comment]
In short:

1. Mobile data bypasses your home network.
2. Apps may ignore the proxy setting.

There unfortunately isn't much mitmproxy can do here.

**Comment by Keshvadi** [comment]
Why you close this topic?
My phone has not mobile data. It is without sim card.
