### ISSUE TITLE
mitmproxy on socket connections

### ISSUE THREAD

**Issue by ne0c0de** [mitmproxy/mitmproxy#4156]
Hi,

I'm trying to inspect data for an online game with mitmproxy

I can see the login request when I open the game but after login and getting token all the flow runs over the socket connection where I can't see them in the log anymore.

Is is possible to trace those kind of data which goes over socket connections?

I were searched the case in issues but couldn't find a proper answer to it.

Thanks for the helps

**Comment by mhils** [comment]
You can either 1) use mitmdump -vvv to dump message contents to the command line, 2) use mitmproxy (not mitmweb yet) to view TCP flows or 3) use SSKLEYLOGFILE logging to view contents in WireShark.

For further support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!
