### ISSUE TITLE
2 proxies in Transparent mode. Certificate verification error for IP: Hostname mismatch (errno: 62, depth: 0)

### ISSUE THREAD

**Issue by sJCCJs** [mitmproxy/mitmproxy#4157]
#### Problem Description:
Hi,
I'm using 2 proxies in transparent mode with http2=false set. 
The scheme is this: Client(Browser) <---->Mitmproxy Transparent 1 <----> Mitmproxy Transparent 2 <----> Internet.

In Mitmproxy 1, I start it with: `mitmproxy --mode transparent --showhost  -s Script1.py -p 8080`
The content of Script1.py is this: 
```
from mitmproxy import http
from mitmproxy import flow
def request(flow):
	flow.request.port = 8081
	flow.request.scheme = "http"
```

In Mimproxy 2, I start it with: `mitmproxy --mode transparent --showhost -s Script2.py  --listen-host 192.168.0.103 -p 8081 `
The content of Script2.py is this: 
```
from mitmproxy import http
from mitmproxy import flow

def request(flow):
    flow.request.port = 443 
    flow.request.scheme = "https"
```
My rules on iptables are: 
```
sysctl -w net.ipv4.ip_forward=1


iptables -t nat -A PREROUTING -i enp2s0f1 -p tcp --dport 443 -j REDIRECT --to-ports 8080
iptables -t nat -A PREROUTING -i enp2s0f1 -p tcp --dport 80 -j REDIRECT --to-ports 8080
iptables -t nat -A PREROUTING -p tcp --dport 8081 -j  DNAT --to-destination 192.168.0.103:8081
iptables -t nat -A OUTPUT -p tcp --dport 8081 -j DNAT --to-destination 192.168.0.103:8081
iptables -A OUTPUT -p tcp -m tcp --dport 8081 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --sport 8081 -j ACCEPT
iptables -t nat -A POSTROUTING -o wlx002401a70708 -j MASQUERADE

```
After that, if i try to enter any site on internet, what I will find in the browser and in the Mitmproxy1 is this
```
<html>
<head>
  <title>502 Bad Gateway</title>
</head>
<body>
  <h1>502 Bad Gateway</h1>
  <p>Certificate verification error for IP: Hostname mismatch (errno: 62, depth: 0)</p>
</body>
</html>
```
**IP is any IP,

and in the Mitmproxy 2 I will find this
`Certificate verification error for IP: Hostname mismatch (errno: 62, depth: 0)`

Everything works fine if i `set ssl_insecure=true` but i dont want this option.
The problem is with certification but i don't know how to resolve it.
Any suggestion?

#### Steps to reproduce the behavior:
1. Recreate the proxies scheme and iptables rules.
2. Try to enter any site on internet
3. Suggest how to resolve the problem with certification

#### System Information:
mitmproxy --version:
Mitmproxy: 5.2
Python:    3.6.9
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by mhils** [comment]
There is too much complexity in your setup for me to figure out what exactly is going on, and we don't have the time to reproduce this in its entirety.
