### ISSUE TITLE
Chrome/ium reports "(failed) net::ERROR_CONTENT_DECODING_FAILED"

### ISSUE THREAD

**Issue by c0d3z3r0** [mitmproxy/mitmproxy#4159]
#### Problem Description

I am not sure if there is a bug or my code is wrong. I guess the latter ;-) Hopefully someone has an idea what is wrong here.

I tried to implement a "transparent ntlmssp authentication proxy". This is not meant to be used with a NTLM-secured upstream proxy but to offload the authentication to mitmproxy/requests instead of having to type the credentials in the browser. (Not for productive use but for testing.)

~~~python
import requests                                                           
from requests_ntlm import HttpNtlmAuth                                    
from mitmproxy import http

class Proxy:
  def __init__(self):
    self.ses = requests.Session()
    self.ses.auth = HttpNtlmAuth('domain\\user', 'passw')

  def request(self, flow):
    headers = {name: value for name, value in flow.request.headers.fields}
    res=self.ses.request(flow.request.method, flow.request.url, headers=headers, data=flow.request.content)
    flow.response.content = res.content
    #flow.response.headers.update(res.headers) doesn't work...
    for name, value in res.headers.items():
      flow.response.headers[name] = value
 
addons = [
  Proxy()
]
~~~

~~~sh
mitmdump -m socks5 -p 1080 --listen-host 127.0.0.1 -s ntlmproxy.py
~~~

Chrome/ium sends the first GET request, then the authentication is done via requests, which works fine. When the response hits the browser, I get an error in the developer tools:  "(failed) net::ERROR_CONTENT_DECODING_FAILED".

**Comment by mhils** [comment]
This looks like an issue with the content type. Take a look at the HTTP headers you are setting. It may just be enough to assign `flow.response.content` after setting the headers.
