### ISSUE TITLE
display only script messages with mitmdump

### ISSUE THREAD

**Issue by baptx** [mitmproxy/mitmproxy#4161]
It would be nice if there is a built-in way to only display script messages with mitmdump.
Currently it looks like there is no feature like this, the `--flow-detail 0` option displays other messages as well so a workaround is to use grep to display the message we want to catch from a script, for example `mitmdump --flow-detail 0 -s script.py | grep MESSAGE`. The disadvantage is that it does filtering with unnecessary processing through a third-party tool like grep.

**Comment by Prinzhorn** [comment]
Can you combine `--quiet` with `print()` inside your script? mitmdump itself should then not print anything and all you get is the output of your script. Worked well for me so far.

**Comment by baptx** [comment]
@Prinzhorn thanks, this seems to be good idea but when using a script on a website like facebook.com, I can still see several error messages like `Error in WebSocket connection to edge-chat.facebook.com:443: WebSocket connection closed unexpectedly by client: TcpDisconnect(None)`. I don't know if this error is because I am using mitmproxy but shouldn't the quiet option hide this or is there another option to use?
What would be the advantage of using ctx.log.info() instead of print()?

**Comment by Prinzhorn** [comment]
> I don't know if this error is because I am using mitmproxy but shouldn't the quiet option hide this or is there another option to use?

I think these are on stderr, right? So that shouldn't be an issue for you. But maybe it's a bug, where do you see them? You're saying you're using mitmproxy now (not mitmdump?). Do these errors appear in the event log in the ui (E)?

>  What would be the advantage of using ctx.log.info() instead of print()?

I think for `mitmdump` the only benefit of `print` is that the verbosity level does not affect it. For `mitmproxy` the benefit of using the `ctx` logger is that the logs appear in the event log. `print` is just regular Python printing, which is why it "bypasses" `--quiet` in a mitmdump script.

**Comment by baptx** [comment]
@Prinzhorn it seems to be on stderr since it is printed in red. Isn't it possible to hide stderr to have a clean output by default?
It happens after logging in to Facebook. I used mitmdump but said mitmproxy since it is part of it. The issue happens with both mitmdump and mitmproxy commands even without using a script. I can see this error in Firefox web console when using the proxy but not without proxy: `The connection to wss://edge-chat.facebook.com/chat?region=odn&sid=6787743585665023 was interrupted while the page was loading.`. I guess I will have to report a separate issue for this WebSocket error.

**Comment by baptx** [comment]
@Prinzhorn it seems to be on stderr since it is printed in red. Isn't it possible to hide stderr to have a clean output by default?
It happens after logging in to Facebook. I used mitmdump but said mitmproxy since it is part of it. The issue happens with both mitmdump and mitmproxy commands even without using a script. I can see this error in Firefox web console when using the proxy but not without proxy: `The connection to wss://edge-chat.facebook.com/chat?region=odn&sid=XXX was interrupted while the page was loading.`. I guess I will have to report a separate issue for this WebSocket error.

**Comment by Prinzhorn** [comment]
> Isn't it possible to hide stderr to have a clean output by default?

Hiding errors by default doesn't sound like a good idea to me. It entirely depends on your use case. You want to work with stdout, others use `--save-stream-file` to record the flows and don't care about the output. But they might care about errors.

**Comment by mhils** [comment]
> Update: I am using the Ubuntu package version 4.0.4 but the error does not happen with the latest version 5.2.

Closing therefore. If you want to suppress errors, you can redirect stderr to a file our /dev/null. How to do that depends on your OS and shell. :)

**Comment by baptx** [comment]
@mhils Thanks. In a future version, would it be possible to have an option to use `ctx.log.info()` instead of `print()` to display only script messages with mitmdump? This would be useful in case we have a script that is already using `ctx.log.info()` but we don't want to change the code to use `print()`.
