### ISSUE TITLE
Can't Replay recorded traffic on Virtual machine

### ISSUE THREAD

**Issue by semarainc** [mitmproxy/mitmproxy#4166]
hi,
i don't know if this is bug or my mistake

i have slow internet connection on my basement so i want to try to record web traffic and bring to my VM, the web that i want to record the traffic is https://xodo.com/app-old/#/pdf, to do some web analysis

so in order to record the traffic i use this command in mitmdump version 5.1.1 for linux from WSL2 (my host pc is windows 10) i used this command from the documentation
Link Documentation: https://mitmproxy.readthedocs.io/en/v2.0.2/mitmdump.html
`mitmdump -w outfile`

after that i tested it on my host pc with offline connection by using this command
`mitmdump --set upstream_cert=false -p 8888  -k --server-replay-nopop -S outfile`

it worked well on my host pc

i moved the recorded traffic to my Virtual Machine then run the same command to replay the traffic and it gives me error

` << Server connection to ('www.xodo.com', 443) failed: Error connecting to "www.xodo.com": [Errno 11004] getaddrinfo failed`

My Virtual Machine Info:
VMware Player 15
Guest OS: windows 7 professional x64

before, when on host pc it runs well even when the connection offline

some additional info:
1. when im in host pc i already try to remove cache and also make new User-Data (chrome brower) to make sure everything worked properly
2. Virtual Machine is in clean state (After Installation)
3. i already add mitmproxy certificate generated from mitm.it (on host and VM)

sorry for my bad english,
and i hope that explanation could give some clue about my problem

Thank you

**Comment by mhils** [comment]
Your mitmproxy instance cannot connect to the upstream server, which is why you are seeing this:

> Error connecting to "www.xodo.com": [Errno 11004] getaddrinfo failed

In other words, your mitmproxy instance cannot connect to websites on the internet, you need to fix your VM config. 
For further support and how-to questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy). Thanks!
