### ISSUE TITLE
Host header shown in UI but missing in request

### ISSUE THREAD

**Issue by wchasekelley** [mitmproxy/mitmproxy#4167]
#### Problem Description
The Host header shows in the request flow UI but isn't in the raw request export

#### Steps to reproduce the behavior:
1. Capture a request to https://github.com for example
2. Host header appears in the flow view of request
3. Export as `raw_request` or `raw`
4. Host header is missing in the output file

#### System Information
Mitmproxy: 6.0.0.dev (+49, commit c48a2fc)
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.7.15-1-MANJARO-x86_64-with-glibc2.2.5

**Comment by zlowly** [comment]
I think in addons/export.py, function raw_request should not return cleanup_request(f)  , it should just return f.request.

**Comment by wchasekelley** [comment]
I think you're right, it looks like the relevant lines in `cleanup_request` is only meant for httpie and curl exports.

https://github.com/mitmproxy/mitmproxy/blob/c48a2fcc4fa057d45b630bc779ec7c392e94b3fa/mitmproxy/addons/export.py#L15-L24

**Comment by mhils** [comment]
Thanks @zlowly! If one of you could send a PR, that'd be fantastic. ✨
