### ISSUE TITLE
dependency error - can't start mitmproxy after pip3 update

### ISSUE THREAD

**Issue by MStrecke** [mitmproxy/mitmproxy#4168]
After updating `mitmproxy` using

```
sudo pip3 install -U mitmproxy
```

starting any flavour of `mitmproxy` resulted in

```
File "/usr/local/lib/python3.6/dist-packages/ldap3/operation/search.py", line 41, in <module>
    from pyasn1.error import PyAsn1UnicodeDecodeError
ImportError: cannot import name 'PyAsn1UnicodeDecodeError'
```

As mentioned in https://github.com/cannatag/ldap3/issues/794 this bug is being triggered by a lax version requirement for `pysan1`.  According to that issue installing `pyasn1` v0.4.8 will fix the issue.

Checking the installation log of `mitmproxy` I found:

```
...
Requirement already satisfied, skipping upgrade: pyasn1<0.5,>=0.3.1 in /usr/local/lib/python3.6/dist-packages (from mitmproxy) (0.4.5)
...
```

After forcing an update of `pyasn1` using 
```
sudo pip3 install pyasn1==0.4.8
```

`mitmproxy` (5.2) starts without the error.

**Comment by Kriechi** [comment]
This doesn't look like a mitmproxy-specific problem to my.
As you pointed out, this is a problem with the ldap3 package (which we include as dependency).

I just created a clean venv, ran `pip install mitmpoxy` and I ended with with `pyasn==0.4.8` and `ldap3==2.7` - which is perfectly valid and works as expected.


We could simply bump our minimum dependency of ldap3 to include their fix for this, but there is (should be) nothing wrong with our existing version specifiers. @mhils ?

**Comment by mhils** [comment]
Dependency management is just painful with Python. I agree though, if a clean. `pip install` works we are good. Thanks for the report, @MStrecke!

**Comment by MStrecke** [comment]
Yes dependencies are a pain. That's why it says **_update_** (not install) in the title.
On the other hand, if your program stops working after an update... I thought you should know.

**Comment by mhils** [comment]
@MStrecke: Do you have any intuition why `pip install -U` did not update your pyasn version? 

FWIW, I closed this because `pip install` version problems/incompatibilites/other issues are a constant pain and we don't have the resources to support it. The recommended approach is to use [pipx](https://docs.mitmproxy.org/stable/overview-installation/) if you want to install from PyPI.

**Comment by MStrecke** [comment]
@mhils: I presume the older version of `mitmproxy` installed `pyasn1` v0.4.5, which was current way back when `mitmproxy` was first installed.

When I updated `mitmproxy` yesterday the requirement `pyasn1<0.5,>=0.3.1` (in the new version of `mitmproxy`) was **still** satisfied and therefore the upgrade of `pyasn1`was skipped (as shown in the log snipped above).

Deleting `mitmproxy` wouldn't had helped, as I don't run it in _venv_. The "old" `pyasn1` version would still be there.
The "new" `mitmproxy` install would have found it, the current requirement of `pyasn1` would still be satisfied and the new `mitmproxy` would not run.

I don't know where the requirement `pyasn1<0.5,>=0.3.1` comes from and if you can change it in this project to `pyasn1<0.5,>=0.4.8` or if you have to rely on `ldap3` to correct it there.

**Comment by mhils** [comment]
Oh well - it looks like pip 10.0 switched the default upgrade strategy for dependencies from "eager" to "only-if-needed". I did not know that, thanks for the heads-up.

We will fix this particular issue by requiring the latest ldap3 release (#4171). Generally speaking, `pip install` remains unsupported in non-clean venvs. I'm happy to merge PRs, but we don't have the motivation to look into similar issues ourselves.
