### ISSUE TITLE
Ability to provide cert pass phrase from command line in mitmdump

### ISSUE THREAD

**Issue by mirosyn** [mitmproxy/mitmproxy#4178]
#### Is your feature request related to a problem? Please describe.
mitmdump allows us to define our own certs from command line using command `--cert`, but there isn't a command to provide the pass phrase. Currently, if I'm providing my own certs to mitmdump in format of:
```
-----BEGIN RSA PRIVATE KEY-----
<private key>
-----END RSA PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
<cert>
-----END CERTIFICATE-----
```

mitmdump asks the pass phrase after the start up, and I can capture HTTPS traffic using mitmdump just fine. Problem with current solution is that the pass phrase giving step cannot be scripted, and it always requires manual intervention.

Current command line behavior.
```
./mitmdump -s har_dump2file.py --set hardump=dump --cert *=certs/mycert.pem
> Enter PEM pass phrase:
> Enter PEM pass phrase:
> Enter PEM pass phrase:
> Enter PEM pass phrase:
> Enter PEM pass phrase:
```

Additionally, it asks the pass phrase multiple times. if you only start the mitmdump using only the `--cert` command, it asks the pass phrase only once.

#### Describe the solution you'd like
I would like to see new command line command, for example: `--cert-pass-phrase mypassword `

**Comment by mhils** [comment]
I'd be happy to merge a PR, but this is probably nothing we'll spend effort on anytime soon.

**Comment by mirosyn** [comment]
pull request created: https://github.com/mitmproxy/mitmproxy/pull/4184
