### ISSUE TITLE
proychains but not for some addons

### ISSUE THREAD

**Issue by aviau** [mitmproxy/mitmproxy#4198]
Hello!

I was wondering if there are ways to obtain better control over how addon are launched and their environement.

I am using a transparent proxy + proxychains setup but I would like for some of my addons to access the network without going trough proxychains. I only want the outgoing mitmproxy request to go trough proxychains.

Would it be possible to launch only the mitmproxy component that makes the final request inside the "proxychains scope" and the rest outside of it? Is there a way to configure mitmproxy that would allow for that?

Thanks for the amazing software, cheers!

**Comment by mhils** [comment]
TL;DR: No.

That sounds like a proxychains question and not so much of a mitmproxy question? I guess you could maybe flip your setup and have proxychains first and then mitmproxy in upstream mode? Mitmproxy addons are just launched within the mitmproxy Python process. I don't think there's anything you could do to escape a proxychains setup.

**Comment by aviau** [comment]
> That sounds like a proxychains question and not so much of a mitmproxy question?

I just wanted to make sure that I wasn't unaware of a mitmproxy feature allowing for this.

>  guess you could maybe flip your setup and have proxychains first and then mitmproxy in upstream mode

Yeah, I setup something similar to this.

Thanks for the response, I'll close this!
