### ISSUE TITLE
docker set ignore_hosts is not working

### ISSUE THREAD

**Issue by outsourcestudio** [mitmproxy/mitmproxy#4202]
#### Problem Description
when I run docker container with options in command line.
ignore_hosts option is blank when check that option via browser

#### Steps to reproduce the behavior:
1. run docker container
docker run -d --restart always --name mitm_name -p 8080:8080 -p 127.0.0.1:8081:8081  mitmproxy mitmweb --web-host 0.0.0.0 -s /home/mitmproxy/.mitmproxy/scripts/script.py --set block_global=false --set ignore_hosts="apple\.com"
or
docker run -d --restart always --name mitm_name -p 8080:8080 -p 127.0.0.1:8081:8081  mitmproxy mitmweb --web-host 0.0.0.0 -s /home/mitmproxy/.mitmproxy/scripts/script.py --set block_global=false --set ignore_hosts=apple\.com
or
docker run -d --restart always --name mitm_name -p 8080:8080 -p 127.0.0.1:8081:8081  mitmproxy mitmweb --web-host 0.0.0.0 -s /home/mitmproxy/.mitmproxy/scripts/script.py --set block_global=false --set ignore_hosts=[apple\.com]
or
docker run -d --restart always --name mitm_name -p 8080:8080 -p 127.0.0.1:8081:8081  mitmproxy mitmweb --web-host 0.0.0.0 -s /home/mitmproxy/.mitmproxy/scripts/script.py --set block_global=false --ignore_hosts apple\.com
or
docker run -d --restart always --name mitm_name -p 8080:8080 -p 127.0.0.1:8081:8081  mitmproxy mitmweb --web-host 0.0.0.0 -s /home/mitmproxy/.mitmproxy/scripts/script.py --set block_global=false --ignore_hosts 'apple\.com'
or
many other variants
but no luck

2. visit in broswer
localhost:8081

3. check Options
https://www.dropbox.com/s/ma4mm5ncnsnrawt/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202020-09-16%20%D0%B2%2019.24.05.png?dl=0

4. expected result 
apple\.com in ignore_hosts option

#### System Information
Paste the output of "mitmproxy --version" here.
5.2

maybe I set it incorrectly?
block_global works fine

**Comment by outsourcestudio** [comment]
Find out correct format from python script
It's not bug. Sorry.

**Comment by andrewleo** [comment]
> Find out correct format from python script It's not bug. Sorry.

what is the correct syntax?
