### ISSUE TITLE
LookupError('unknown encoding: snappy')

### ISSUE THREAD

**Issue by tomlabaude** [mitmproxy/mitmproxy#4203]
I have an error while listing flow content in a script, on URLs which contains HTTP header "Content-Encoding: snappy"

Here's the code to limit the content display :
```
 content_bytes_list = list(flow.request.content)
 content_bytes_list_limited = content_bytes_list[:length_of_content_view]
 content_bytes = "".join(map(chr, content_bytes_list_limited))
```

And the error:
```
Addon error: Traceback (most recent call last):
  File "mitmproxy/net/http/encoding.py", line 52, in decode
KeyError: 'snappy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mitmproxy/net/http/encoding.py", line 54, in decode
LookupError: unknown encoding: snappy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    content_bytes_list = list(flow.content)
  File "mitmproxy/net/http/message.py", line 95, in get_content
  File "mitmproxy/net/http/encoding.py", line 65, in decode
ValueError: LookupError when decoding b'\x94\x0e with 'snappy': LookupError('unknown encoding: snappy')
```

Apparently, the code is able to recover from a "KeyError", but the exception still occurs :
https://github.com/mitmproxy/mitmproxy/blob/fb0f41032e951c2620fc8faaf865c4870d6df5a0/mitmproxy/net/http/encoding.py#L76

I thought mitmdump would crash as well on this URL while displaying and decoding this URL (with --flow-detail 3), but it's fine, only my script is failing :

-> Is list(flow.request.content) and my code a correct way to limit my display ?

The URL which triggers sub-URLs with snappy is:
`https://www.leparisien.fr/video/video-emmanuel-macron-a-beyrouth-la-france-sera-la-06-08-2020-8364273.php`

```
192.168.1.40:55409: POST https://pebed.dm-event.net/
    Host: pebed.dm-event.net
    Connection: keep-alive
    Content-Length: 2857
    Pragma: no-cache
    Cache-Control: no-cache
    Accept: application/json, text/plain, */*
    Content-Encoding: snappy
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
    Content-Type: text/plain
    Origin: https://www.dailymotion.com
    Sec-Fetch-Site: cross-site
    Sec-Fetch-Mode: cors
    Sec-Fetch-Dest: empty
    Referer: https://www.dailymotion.com/embed/video/x7vfb0j?ads_params=videoposition%253Dhaut%2526pageSection%253Dvideo&api=postMessage&apiKey=9ebfe9d2e61926ab5517&apimode=json&autoplay=false&id=f31d1360141602c&mute=true&origin=https%3A%2F%2Fwww.leparisien.fr&pubtool=cpe-p1&queue-autoplay-next=true&queue-enable=true&ui-highlight=false
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-GB,en;q=0.9

    \xcfJ\xf0\x8a{"channel":"player","edward":"1.1","sent_ts":1600341482015,"events":[{"name":"advertising.adError","version":"1.0","data":{"settings":{"api\x01\x82\xf0JostMessage","controls":true,"prebid":false,"ima":"CTX","pubtool":"cpe-p1"},\x05?\x0cext"\x01j\x0ccree\x05\x81\x18280x777\x01\x96`isitor_group":51},"metada	\x9e8duration":143,"\x01y\x1c"x7vfb0j!\x14ttream_type":"recorded","owner_	.\x1032f7b\x01\x9e@rotected_delivery\x15\xc5\x0ccrea\x01\x19\x04ti!A\\1596707990,"is_password_\x15A
    8 },"ad_cli!\x9a\x04in!\x88\x08ory	vh1eidsi18a3sfoh560kl_VMAP_0_!}\x1d8\x10dx":0\x05J\x0cserv\x05\xb6\x15\x12\x1cpod_inde\x15\x11\x14buffetR\x14\x00\x10total\x11K\x18ima_loa!
...
```

#### System Information
Mitmproxy: 5.2 binary
Python:    3.7.8
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Darwin-18.7.0-x86_64-i386-64bit

**Comment by mhils** [comment]
We don't support `snappy` content encoding at the moment, raising an error when when that happens is intentional. You can either call `response.get_content(strict=False)` or access `response.raw_content` directly instead.

Here are the relevant sources: https://github.com/mitmproxy/mitmproxy/blob/fb0f41032e951c2620fc8faaf865c4870d6df5a0/mitmproxy/net/http/message.py#L99-L157

There are no stable snappy bindings for Python that either are pure Python or have recent compiled wheels. Until that situation changes I'll close this here. :)
