### ISSUE TITLE
Allow user agent by regex. Same logic as allow_hosts, just for user agent

### ISSUE THREAD

**Issue by outsourcestudio** [mitmproxy/mitmproxy#4204]
I think Mitmproxy has cool features ignore_hosts and allow_hosts
Need same logic for user agent?
is it possible?

I can try to develop it myself. Need support. Copy logic from allow_hosts or ignore_hosts is possible way??
Extend ignore_hosts and allow_hosts options?

**Comment by mhils** [comment]
This is not going to work easily. The point of ignore_hosts is to _not_ parse HTTP, so you don't have access to headers. Maybe you can get away filtering by client IP?

**Comment by outsourcestudio** [comment]
> This is not going to work easily. The point of ignore_hosts is to _not_ parse HTTP, so you don't have access to headers. Maybe you can get away filtering by client IP?

Thanks @mhils . Seems you're right.
