### ISSUE TITLE
In UI, clicking Details shows a blank page, console output attached

### ISSUE THREAD

**Issue by asheroto** [mitmproxy/mitmproxy#4205]
#### Problem Description
Using version 5.2 on Windows.

When on the UI page at localhost:8081, click on any entry and click "Details" on the right side and it takes me to a blank white page.

Page: http://localhost:8081/#/flows/<redacted>/details

![image](https://user-images.githubusercontent.com/49938263/93689194-c1644f80-fa91-11ea-8a86-e3b225b44627.png)

#### Steps to reproduce the behavior:
Explained above.

#### System Information
```
Mitmproxy: 5.2 binary
Python:    3.7.8
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Windows-10-10.0.17763-SP0
```

**Comment by mhils** [comment]
This seems to only affect flows which do not have a server address set, most prominently flows to `mitm.it`.

**Comment by Samhita-sopho** [comment]
I have been reproduce the behavior and I see this for the flows that include mitm.it static resources. I am working to see how or what would fix it. Where would I discuss this issue further? @mhils

**Comment by Yoshio123** [comment]
> #### Problem Description
> 
> Using version 5.2 on Windows.
> 
> 
> 
> When on the UI page at localhost:8081, click on any entry and click "Details" on the right side and it takes me to a blank white page.
> 
> 
> 
> Page: http://localhost:8081/#/flows/<redacted>/details
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/49938263/93689194-c1644f80-fa91-11ea-8a86-e3b225b44627.png)
> 
> 
> 
> #### Steps to reproduce the behavior:
> 
> Explained above.
> 
> 
> 
> #### System Information
> 
> ```
> 
> Mitmproxy: 5.2 binary
> 
> Python:    3.7.8
> 
> OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
> 
> Platform:  Windows-10-10.0.17763-SP0
> 
> ```
> 
>

**Comment by Yoshio123** [comment]
> #### Problem Description
> 
> Using version 5.2 on Windows.
> 
> 
> 
> When on the UI page at localhost:8081, click on any entry and click "Details" on the right side and it takes me to a blank white page.
> 
> 
> 
> Page: http://localhost:8081/#/flows/<redacted>/details
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/49938263/93689194-c1644f80-fa91-11ea-8a86-e3b225b44627.png)
> 
> 
> 
> #### Steps to reproduce the behavior:
> 
> Explained above.
> 
> 
> 
> #### System Information
> 
> ```
> 
> Mitmproxy: 5.2 binary
> 
> Python:    3.7.8
> 
> OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
> 
> Platform:  Windows-10-10.0.17763-SP0
> 
> ```
> 
>

**Comment by Yoshio123** [comment]
> #### Problem Description
> 
> Using version 5.2 on Windows.
> 
> 
> 
> When on the UI page at localhost:8081, click on any entry and click "Details" on the right side and it takes me to a blank white page.
> 
> 
> 
> Page: http://localhost:8081/#/flows/<redacted>/details
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/49938263/93689194-c1644f80-fa91-11ea-8a86-e3b225b44627.png)
> 
> 
> 
> #### Steps to reproduce the behavior:
> 
> Explained above.
> 
> 
> 
> #### System Information
> 
> ```
> 
> Mitmproxy: 5.2 binary
> 
> Python:    3.7.8
> 
> OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
> 
> Platform:  Windows-10-10.0.17763-SP0
> 
> ```
> 
>

**Comment by Yoshio123** [comment]
NT 5.1

**Comment by mhils** [comment]
@Samhita-sopho: Either here or on our developer Slack! :) 
You can find instructions for setting up the web client locally https://github.com/mitmproxy/mitmproxy/tree/master/web.

**Comment by Samhita-sopho** [comment]
So I got the error to disappear by literally assigning the address to an empty array . But it throws another error 
![image](https://user-images.githubusercontent.com/24493719/94748208-6874a100-0346-11eb-8726-26f173c7b99d.png)
so would the ideal path here be to remove the server address section when the address is null ?

**Comment by Samhita-sopho** [comment]
@mhils

**Comment by mhils** [comment]
Fixed, thanks again!
