### ISSUE TITLE
Addons/block.py can't be modified from within script, causing block_global failures

### ISSUE THREAD

**Issue by brummetj** [mitmproxy/mitmproxy#4208]
## The problem

Hello! I have been using the mitmproxy for a while now, in which i have built a REST wrapper around it providing interactive capabilities via HTTP. Apart of this program, i use your concept of addons to build dynamic classes and submit them to addons in which we call "rules". 

Recently we just moved into a new server room, where the proxy is now running on global IP addresses. From what i realized and debugged - is that we can change these values from the command line by `mitmdump --set block_global=False` but when it comes to the options provided in `from mitmproxy import options`, there is no option to change this value. 

From further understanding what is going on inside the dumpmaster (`from mitmproxy.tools.dump import DumpMaster`) there is a piece of code which is adding on all these default addons from 
`self.addons.add(*addons.default_addons())`

```
def default_addons():
    return [
        core.Core(),
        browser.Browser(),
        block.Block(),
        anticache.AntiCache(),
        anticomp.AntiComp(),
        check_ca.CheckCA(),
        clientplayback.ClientPlayback(),
        cut.Cut(),
        disable_h2c.DisableH2C(),
        export.Export(),
        onboarding.Onboarding(),
        proxyauth.ProxyAuth(),
        replace.Replace(),
        script.ScriptLoader(),
        serverplayback.ServerPlayback(),
        setheaders.SetHeaders(),
        stickyauth.StickyAuth(),
        stickycookie.StickyCookie(),
        streambodies.StreamBodies(),
        save.Save(),
        upstream_auth.UpstreamAuth(),
    ]
```

Here i have tried to replace the specific `block` class - so i can change this value `block_global`  to `False` since its hard coded to `True` - which from my understanding is True by default, but within the objects this isn't being mutated to whatever changes i'm making

*Example*:  

if i try to add my own `block` class to attempt to overwrite your `block` addon... nothing of the sort will get modified, and i will ultimately fail with a `killed by block_global`

```
class Block:
    def load(self, loader):
        loader.add_option(
            "block_global", bool, False,
            """
            Block connections from globally reachable networks, as defined in
            the IANA special purpose registries.
            """
        )
        loader.add_option(
            "block_private", bool, False,
            """
            Block connections from private networks, as defined in the IANA
            special purpose registries. This option does not affect loopback
            addresses.
            """
        )

    def clientconnect(self, layer):
        astr = layer.client_conn.address[0]

        parts = astr.rsplit("%", 1)
        address = ipaddress.ip_address(parts[0])
        if isinstance(address, ipaddress.IPv6Address):
            address = address.ipv4_mapped or address

        if address.is_loopback:
            return

        if ctx.options.block_private and address.is_private:
            ctx.log.warn("Client connection from %s killed by block_private" % astr)
            layer.reply.kill()
        if ctx.options.block_global and address.is_global:
            ctx.log.warn("Client connection from %s killed by block_global" % astr)
            layer.reply.kill()


addons = [Block()]

master = DumpMaster(self.opts)
master.server = proxy.server.ProxyServer(proxy_conf)
master.addons.add(addons)
```

this is just a small snippet - but i hope it helps with what Im seeing. Once i add this addon and start the proxy via python, it will ultimately end up with the same issue i've been describing.

## Solutions

If there is something I'm missing here, please let me know so i can make the necessary changes. 
Otherwise the solution that i have found to work is actually go into your `addons/block.py` file, and change this hard coded value to `False`. This is obviously not maintainable as any updates to your project will overwrite these changes i make to the `addons/block.py` , and would end up having to maintain my own fork for this simple issue. 

What I'm suggesting is adding a parameter to the DumpMaster for overwriting any default addons by passing in addons of the same name. I can fork and submit a PR if necessary. 

Cheers!

**Comment by Kriechi** [comment]
Did you try removing the existing block addon? Something like:
```
block_addon = master.addons.get("Block")
master.addons.remove(block_addon)
```

**Comment by brummetj** [comment]
thanks @Kriechi ... i totally spaced out on the idea of getting the addon and just removing it. Silly me. just a FYI its `block` and not `Block` ... took a little inspection there :) 

feel free to close this out.
