### ISSUE TITLE
where is api document in docs.mitmproxy.org

### ISSUE THREAD

**Issue by greper** [mitmproxy/mitmproxy#4214]
like this   https://mitmproxy.readthedocs.io/en/v2.0.2/scripting/api.html
but i can't find it  in  docs.mitmproxy.org

**Comment by Memenymous** [comment]
![image](https://user-images.githubusercontent.com/2840949/96791609-16ea9e00-143c-11eb-823e-866de08838b3.png)

**Comment by Kriechi** [comment]
We currently only expose and support the addon mechanism with event hooks:
https://docs.mitmproxy.org/stable/addons-overview/

**Comment by mhils** [comment]
To expands on this: We'll have a proper API documentation built with [pdoc](https://pdoc.dev) soon. :)
