### ISSUE TITLE
HTTPS request to site got ERROR 413 return

### ISSUE THREAD

**Issue by jedsadas** [mitmproxy/mitmproxy#4221]
#### Problem Description
On mitmproxy v5,
HTTP request to https://g.alicdn.com/kg/kmd-adapter/0.0.6/index.js returned ERROR 413 

#### Steps to reproduce the behavior:
1. with fresh install of Ubuntu 20.04.1 LTS
2. install mitmproxy 5.2 using command pip3 install mitmproxy
3. run mitmproxy
4. make a request to URL=https://g.alicdn.com/kg/kmd-adapter/0.0.6/index.js
5. got return 413

Tested without issue on v4. This happen on various urls on this domain too.

#### System Information
Mitmproxy: 5.2
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.4.0-45-generic-x86_64-with-glibc2.29

**Comment by Prinzhorn** [comment]
Can confirm. And it's working with 5.1.1, so it broke with 5.2.

It does work if you disable HTTP/2 via `--no-http2`

Here's the diff of `mitmdump --verbose` @Kriechi probably knows what's up :smile: . But from the logs I don't see what 5.2 does different that causes the server the close the connection. The only related thing I see from the CHANGELOG is "Add support for HTTP Trailers to the HTTP/2 protocol" unless you've upgraded some dependencies as well.

![Selection_672](https://user-images.githubusercontent.com/679144/95301190-8b401180-0880-11eb-9a3f-2daf64dd2bb9.png)

Differences in server response

![Selection_673](https://user-images.githubusercontent.com/679144/95301575-0ef9fe00-0881-11eb-9f56-8f4128417143.png)
![Selection_676](https://user-images.githubusercontent.com/679144/95301586-128d8500-0881-11eb-8862-a80eca87d778.png)

**Comment by Kriechi** [comment]
@Prinzhorn do you still have the full logs of your test?
I think the interesting bits got cropped off due to line lenght.
I'd like to see the `H2Conn server: Send headers` lines near the end. I'm suspecting a broken server implementation that cannot handle streams with HEADERS + a dedicated DATA+END_STREAM frame which 5.2 seems to send, whereas 5.1.1 seems to send a single HEADERS+END_STREAM frame... but that's just a guess at this point.

**Comment by Kriechi** [comment]
I'm having problem reproducing this on macOS, Python 3.8.5, mitmproxy 5.2 in a fresh virtualenv: I always get 200 success.

**Comment by Prinzhorn** [comment]
@Kriechi I was using docker

```
docker run --rm -it -p 8080:8080 mitmproxy/mitmproxy:5.2 mitmdump --verbose > 5.2.log
docker run --rm -it -p 8080:8080 mitmproxy/mitmproxy:5.1.1 mitmdump --verbose > 5.1.1.log

curl --verbose --insecure --proxy localhost:8080 https://g.alicdn.com/kg/kmd-adapter/0.0.6/index.js
```

https://gist.github.com/Prinzhorn/c0591fbac4021248739a5a75928ee86a

**Comment by Kriechi** [comment]
Thanks - while I can reproduce it with the 5.2 docker image, the most recent master seems to be already fixed. I suspect a minor or bugfix release of one of our dependencies took care of this.
The fix should therefore be included in the next release.
