### ISSUE TITLE
transparent mode driver check problem

### ISSUE THREAD

**Issue by alexalwks2** [mitmproxy/mitmproxy#4222]
#### Steps to reproduce the behavior:
1. Fresh windows 7 64 bit
2. all certificates installed correctly
3. all went good until we set transparent mode.

#### System Information
Paste the output of "mitmproxy --version" here.
mitmdump.exe --version
Mitmproxy: 4.0.4 binary
Python:    3.6.6
OpenSSL:   OpenSSL 1.1.0i  14 Aug 2018
Platform:  Windows-7-6.1.7601-SP1

command is mitmdump.exe" --mode transparent
error 577 means
Error starting proxy server: OSError(22, 'Windows cannot verify the digital sign
ature for this file. A recent hardware or software change might have installed a
 file that is signed incorrectly or damaged, or that might be malicious software
 from an unknown source.', None, 577)

We tried disabling signature enforcement
Enabled test mode for windows file checks
Still nothing worked well for us.

Kindly help somehow?

Niko Tadej
Open Source Dev at Freelancer DEV Poland
alex220247@hotmail.com
nikotadej@protonmail.com

![error 577](https://user-images.githubusercontent.com/68657675/95343318-3b0b8400-086d-11eb-8e5d-fb8fe2d5b810.png)

**Comment by Kriechi** [comment]
Please try with the most recent stable release of mitmproxy: https://mitmproxy.org/ 
currently v5.2: https://mitmproxy.org/posts/releases/mitmproxy52/
