### ISSUE TITLE
[Web] WebSocket connection to 'wss://updates' failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by taimaiduc** [mitmproxy/mitmproxy#4227]
#### Problem Description
[Web] WebSocket connection to 'wss://http.xxx.dev/updates' failed: Error during WebSocket handshake: Unexpected response code: 400
![image](https://user-images.githubusercontent.com/10907980/95647553-85556500-0afa-11eb-88c5-0030c3641311.png)

#### Steps to reproduce the behavior:
mitmweb --web-port=9091 --web-host=127.0.0.1 --listen-port=9090 --set block_global=false

####  Nginx config
```
server {
    #listen 80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate     /etc/letsencrypt/live/xxxx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxx/privkey.pem;
    server_name http.xxx.dev;
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/.htpasswd;
    #root /var/www/html/;
    #index index.php index.htm index.nginx-debian.html;
    #access_log /var/log/nginx/8888_tunnel custom;

    location / {
         proxy_pass http://localhost:9091;
    }
}
```
#### System Information
Version 5

**Comment by Kriechi** [comment]
Thanks for the report. Unfortunately it is not really clear what your environment looks like.

What role is the nginx playing? The ports seem to map to the mitmproxy web port - which should not be relevant in this case. Or is the nginx the actual server config you are trying to troubleshoot?

Does mitmproxy or mitmdump output anything about the broken Websocket connection?

It is important for us to know about your server and URL you are trying to connect to, so we can debug this. Feel free to share it privately if you want.

Please also try with `mitmdump --flow-detail 4 --verbose` with any custom parameters you might need and check with your browser again.

Please provide the full output of `mitmproxy --version`

**Comment by taimaiduc** [comment]
@Kriechi Sorry for the late reply
**mitmproxy --version**
```
Mitmproxy: 5.2 binary
Python:    3.7.8
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.3.0-1032-gcp-x86_64-with-debian-buster-sid
```

![image](https://user-images.githubusercontent.com/10907980/96359233-accfb180-113a-11eb-97b6-b46b966a6178.png)
![image](https://user-images.githubusercontent.com/10907980/96359241-c670f900-113a-11eb-8ebe-8718c1be8dd9.png)

**Comment by Kriechi** [comment]
The websocket protocol was re-implemented with our new sans-io proxy core - which should fix a lot of similar issues.
