### ISSUE TITLE
mitmdump unable to use classes with a script

### ISSUE THREAD

**Issue by LZC6244** [mitmproxy/mitmproxy#4228]
#### Problem Description
I't didn't work when i use class with mitmdump

#### Steps to reproduce the behavior:
1. Start an app of the Android emulator (Android  7)
2. Start mitmdump with a script
3. Start the 'drony' app
4. I can do something for response when i used a module-level script, but it faild when used class instance. 
    Nothing happened! Didn't even execute the response method
    what i did just like the docs https://mitmproxy.readthedocs.io/en/v2.0.2/scripting/overview.html#using-classes

#### System Information
Mitmproxy: 5.2
Python:    3.7.5
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-4.15.0-112-generic-x86_64-with-debian-buster-sid

**Comment by Kriechi** [comment]
Please use the mitmproxy documentation that matches your installed version:
https://docs.mitmproxy.org/stable/

**Comment by LZC6244** [comment]
> Please use the mitmproxy documentation that matches your installed version:
> https://docs.mitmproxy.org/stable/

Thanks 😀
