### ISSUE TITLE
Can't Setup Mitm's Certificate

### ISSUE THREAD

**Issue by TaThiTanDev96** [mitmproxy/mitmproxy#4241]
I need some help
When finished setup proxy to my macbook, then i open http://mitm.it page, but it's only show nginx page

Thanks all <3
![IMG_ECB0FE192CB0-1](https://user-images.githubusercontent.com/60084784/96542444-45496b80-12cc-11eb-8104-2916fedbdaf9.jpeg)

**Comment by Prinzhorn** [comment]
> When finished setup proxy to my macbook

How did you set that up? The page you're seeing doesn't make a lot of sense. Are you routing mitm.it to your own machine or something?

**Comment by Kriechi** [comment]
Please follow our docs to set up your proxy:
https://docs.mitmproxy.org/stable/concepts-modes/
and
https://docs.mitmproxy.org/stable/overview-getting-started/
