### ISSUE TITLE
Secure connection to mitmproxy

### ISSUE THREAD

**Issue by hazcod** [mitmproxy/mitmproxy#4242]
Hi, I want to setup a remote mitmproxy instance to test through so I can process all the endpoints (domain, path, parameters) that pass through my browser. However, I want to do this authenticated with a whitelist of endpoints and do not want plain HTTP websites to proxy as plain HTTP over the internet.

Is there a way to do this with mitmxproxy currently? e.g. mTLS to mitmproxy.
It's difficult to get tools installed on the tester PCs such as SSH for forwarding.

**Comment by mhils** [comment]
The easy fix is to setup a VPN for this.
We'll hopefully soon have support for TLS-over-TLS, which allows mitmproxy to run as a "Secure Web Proxy" (#1775). To only allow outgoing connections to specific hosts, you could write a simple mitmproxy addon. :)
