### ISSUE TITLE
har_dump is not readable in HttpWatchStudio with error on ssl timing greater than connect timing

### ISSUE THREAD

**Issue by frguerin** [mitmproxy/mitmproxy#4244]
#### Problem Description

Hello,

I record an Android apk using mitmdump with a client certificate:
mitmdump --set client_certs=client-certificat_withKey.pem --set ssl_insecure=true -w outfile

Then I convert the mitm flow using har_dump because i prefer using CharlesProxy and HttpWatchStudio to analyse:
mitmdump -n -r outfile -s ./har_dump.py --set hardump=./outfile.har

I am using latest version of har_dump.py included in mitmproxy-5.2/examples/contrib

I can import the har file in Charles but timing seems odd, for ex. 
_Duration 318ms 
DNS n/a 
Connect **-91ms** 
TLS Handshake 130ms 
Request 2ms 
Response 1ms 
Latency 276ms_

But when I look in mitm for the same request i get 
_Server conn. initiated: | 2020-10-21 17:25:59.740(-196ms)
Server conn. TCP handshake: | 2020-10-21 17:25:59.779(-156ms)
Client conn. established: | 2020-10-21 17:25:59.732(-203ms)
First request byte: | 2020-10-21 17:25:59.936
Request complete: | 2020-10-21 17:25:59.938(2ms)
First response byte: | 2020-10-21 17:26:00.215(279ms)
Response complete: | 2020-10-21 17:26:00.216(280ms)_

In HttpWatchStudio at the opening of the har file I receive a warning about sl timing being greater than connect timing which is not compliant with har specifications and the file does not open:

![image](https://user-images.githubusercontent.com/44432375/97031188-2fec6f80-1560-11eb-829b-659c16423a10.png)

#### Steps to reproduce the behavior:
1. record a mitmdump flow
2. export to har using har_dump.py
3. read the file in external tool Charles (check timings) or HttpWatchStudio

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 5.2
Python:    3.6.9
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-18.04-bionic

**Comment by mhils** [comment]
Thanks for the report! 😃 

I will close this issue here as we do not have the resources to maintain community-contributed addons (see [examples/contrib/README.md](https://github.com/mitmproxy/mitmproxy/blob/master/examples/contrib/README.md)), but I'd be more than happy to merge a PR that improves or fixes them.
