### ISSUE TITLE
v4 --replacements vs v5 --modify-headers

### ISSUE THREAD

**Issue by uvtzxpm** [mitmproxy/mitmproxy#4245]
I'm trying to replace the `User-Agent` request header if it contains a certain string.

This works with "mitmproxy-4.0.4-linux":

```
./mitmproxy --replacements ":~hq User-Agent:Mozilla(.+):CUSTOMAGENT"
```

With "mitmproxy-5.2-linux", this at least replaces the `User-Agent`, but is missing my "certain string condition":

```
./mitmproxy --modify-headers "|~hq .+|User-Agent|CUSTOMAGENT"
```

How do I add my `Mozilla` condition in v5?

None of these work:

```
./mitmproxy --modify-headers "|~hq ^(.*?)Mozilla(.*?)$|User-Agent|CUSTOMAGENT"

./mitmproxy --modify-headers "/~hq .*?Mozilla.*?/User-Agent/CUSTOMAGENT"

./mitmproxy --modify-headers "|~hq Mozilla|User-Agent|CUSTOMAGENT"

./mitmproxy --modify-headers "|~hq User-Agent: Mozilla|User-Agent|CUSTOMAGENT"

./mitmproxy --modify-headers "|~hq \"^(.*?)Mozilla(.*?)$\"|User-Agent|CUSTOMAGENT"
```

I've been trying for hours, and I feel like I've tried every variation under the sun. There's a very small chance it's a bug, but most likely I'm just doing it wrong. If it matters, this system is Ubuntu 16.04.

**Comment by Prinzhorn** [comment]
I've been digging into this and this is definitely a bug in the implementation. Will follow up with details.

**Comment by Prinzhorn** [comment]
https://github.com/mitmproxy/mitmproxy/blob/a203b69ba97eab47302edbb9b378eff353550132/mitmproxy/addons/modifyheaders.py#L83-L99

Given your example line 85 to 87 remove the `user-agent` header. Then line 91 tries to match the flow against the filter. But the header is gone, so it cannot match.

I'm not sure why it's implemented this way, but I think both loops (which on the first two level share the exact same code) should be combined into one. Essentially moving the whole first loop into the else block here

https://github.com/mitmproxy/mitmproxy/blob/a203b69ba97eab47302edbb9b378eff353550132/mitmproxy/addons/modifyheaders.py#L98-L99

**Comment by uvtzxpm** [comment]
Thanks for the fast response, I'm happy to see I wasn't crazy.

I haven't tried the fix from your pull request yet, but it looks good to me.
