### ISSUE TITLE
mitmdump: error: unrecognized arguments: --flow_detail

### ISSUE THREAD

**Issue by woshichuanqilz** [mitmproxy/mitmproxy#4247]
#### Problem Description
mitmdump --flow_detail 0

#### Steps to reproduce the behavior:
run command `mitmdump --flow_detail 0`

mitmdump: error: unrecognized arguments: --flow_detail

I read some post said the document havent been updated yet. 
How to solve this problem for me. And where can I get the newest manual? 

#### System Information
Paste the output of "mitmproxy --version" here.

Mitmproxy: 5.2
Python:    3.8.3
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-5.8.11-1-MANJARO-x86_64-with-glibc2.10

**Comment by Prinzhorn** [comment]
> For all tools, options can be set directly by name using the --set command-line option. Please see the command-line help (--help) for usage.


`mitmdump --flow_detail 0`

**Comment by Kriechi** [comment]
either `mitmdump --set flow_detail=0` or `mitmdump --flow-detail 0`
