### ISSUE TITLE
Windows version only works on the first boot for my pc app

### ISSUE THREAD

**Issue by frh16** [mitmproxy/mitmproxy#4250]
#### Problem Description
In fact, I want to use the python version and found that it does not work properly. I tried the windows version and found that only the first startup can work properly.

#### Steps to reproduce the behavior:
1. install windows version
2. check "Lauch mitmproxy ui now"
3. click "Finish", then the proxy start automatically
4. start my pc client app, click login, main page will be shown, everything is ok
5. but, close and restart proxy, double click mitmweb.exe, restart app, click login, main page can not be shown
6. if install with python and input mitmdump, can not work also for my app

If it’s not working correctly, only the red box will be shown
![1](https://user-images.githubusercontent.com/51506628/97316978-51719200-18a5-11eb-8cf8-f1be5058e543.png)

https://fl-01.vips100.com/v2/support 
request
![2](https://user-images.githubusercontent.com/51506628/97321020-64866100-18a9-11eb-8db8-d2da8578e1a2.png)
response
![3](https://user-images.githubusercontent.com/51506628/97321022-65b78e00-18a9-11eb-9d40-1db9f3b37058.png)

#### System Information
Mitmproxy: 5.2
Python:    3.7.0
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Windows-10-10.0.18362-SP0

window: mitmproxy-5.2-windows-installer 
my app：https://res.box.lenovo.com/client/window/6.0.0.49/bin/zBox_installer.exe

**Comment by mhils** [comment]
How do you close mitmweb? Are you closing the command line window as well?

**Comment by frh16** [comment]
> How do you close mitmweb? Are you closing the command line window as well?

I closed the browser and the command line window，and even restarted the computer.
I guess there may be any special parameters when the windows version starts.

**Comment by frh16** [comment]
> How do you close mitmweb? Are you closing the command line window as well?

![11](https://user-images.githubusercontent.com/51506628/97939051-0502e680-1dbe-11eb-8d9d-38fabd8ab5e8.gif)
![22](https://user-images.githubusercontent.com/51506628/97939065-0c29f480-1dbe-11eb-843f-d0deca1c5292.gif)
