### ISSUE TITLE
Create New Requests Inside mitmproxy

### ISSUE THREAD

**Issue by revintec** [mitmproxy/mitmproxy#426]
when mitmproxy opens, there is no request
then I want to issue a new request to the server to see how server responses
this seems can't be done

(why not set proxy and use curl ...)
because mitmproxy has a nice editor ...
(why I want this)
I think it's a valuable feature, sometimes you just want to provoke the server to see how
it responses, maybe try to squeeze some ajax api out of it, testing some variables
and the easy way is to make a new request instead of curl/browser/...

what I want:
could someone tell me is there a way to make new request right inside mitmproxy?
(I think it should have one, maybe I missed it?)
if not, could you add a shortcut "n" at main screen to start make and edit a new request?

**Comment by gato** [comment]
Hi Max,
I'm trying to implement this feature but runned into an issue with ssl https://github.com/tekii/mitmproxy/tree/feature-426
the code in that branch can create a new request from the flowlist (with or without previous flows) and also can resend http request and it works ok, but if created request is a https one SSL.py throws an exception. 
```
Exception in thread RequestReplayThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/gato/trabajos/mitmproxy/libmproxy/protocol/http.py", line 1467, in run
    self.flow.response = HTTPResponse.from_stream(server.rfile, r.method,
  File "/home/gato/trabajos/mitmproxy/libmproxy/proxy/connection.py", line 144, in send
    self.wfile.write(message)
  File "/home/gato/trabajos/mitmproxy/netlib/netlib/tcp.py", line 94, in write
    return self.o.sendall(v)
  File "/home/gato/.local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string
```
I must be missing some initialization in the creation of the request done here https://github.com/tekii/mitmproxy/blob/feature-426/libmproxy/flow.py#L767-L771
but i can't figure out what is missing, if you could point me in the right direction i could PR this soon.
Regards.
Marcelo

**Comment by mhils** [comment]
Hey Marcelo,

thanks for picking this up! :smiley:

I'll take a look at the specific issue once I have access to a debugger later today or tomorrow.

We expect all our flows to have a client_conn and server_conn attribute, so this is something we should probably keep for "artifical flows". I think you can just create ClientConnection and ServerConnection using `.from_state()` (which takes a dict of _stateattributes).

**Comment by mhils** [comment]
Ok, identified the issue: We get unicode into the request somewhere - `.assemble()` then returns unicode, which causes the crash. I'll fix that tomorrow. :smiley:

Cheers,
Max

**Comment by mhils** [comment]
Here's the culprit: https://github.com/tekii/mitmproxy/commit/ba42984b593246b0105a077311e16a2ca71f79eb#commitcomment-9707376

Cheers,
Max

**Comment by mhils** [comment]
Thanks to @gato, the next mitmproxy version will ship with this feature. :-)
