### ISSUE TITLE
No mitmproxy-5.3.0-windows-installer.exe?

### ISSUE THREAD

**Issue by brunoyb** [mitmproxy/mitmproxy#4261]
I just noticed there is no Windows installer for version 5.3.0. Did something went wrong with the release or will this be the normal moving forward (no more installers)?

Thanks!

**Comment by mhils** [comment]
Thanks for the heads-up. Definitely unintentional, let's take a look how that happened...

**Comment by mhils** [comment]
Installer is up now, thanks again! 😃

**Comment by brunoyb** [comment]
Awesome! Thanks! And thank you for working on this so fast!
