### ISSUE TITLE
Throttle a domain using mitmdump

### ISSUE THREAD

**Issue by StephanieCherian** [mitmproxy/mitmproxy#4264]
I want to throttle a particular domain at 1Mbps,2Mbps,5Mbps and 10Mbps when running mitmdump in transparent mode

**Comment by Prinzhorn** [comment]
I'm closing this in favor of #4264 (which should've been a duplicate of this one), which is newer but has been more active

**Comment by ericbeland** [comment]
Isn't **this** issue you closed #4264?  Was the wrong number was pasted?

**Comment by Prinzhorn** [comment]
Updated
