### ISSUE TITLE
Asgi addon destroys query parameters

### ISSUE THREAD

**Issue by jpstotz** [mitmproxy/mitmproxy#4270]
#### Problem Description

When using the ASGIApp addon from mitmproxy/mitmproxy/addons/asgiapp.py the request parameters are totally wrong. 

If you use for example the sample code from https://github.com/mitmproxy/mitmproxy/blob/master/examples/addons/wsgi-flask-app.py 
```
@app.route('/')
def hello_world() -> str:
    print(list(request.args.keys())) # added to demonstrate the problem
    return 'Hello World!'
```

and execute it using the URL `http://proxyapp/?test=123` this code will print `['test=D123']`.

The correct output would be `['test']`.

#### Potential bug source

Base don my analysis the reason for this problem is located in [asgiapp.py method make_scope](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/asgiapp.py#L47):

First the complete path is URL encoded:

`quoted_path = urllib.parse.quote_from_bytes(flow.request.data.path).split("%3F", maxsplit=1)`

And some lines later the query parameters are extracted from this `quoted_path`:

` query_string = quoted_path[1].encode()`

For testing I changed so that the url-escaping is undone, then it works correctly in my set-up:

` query_string = urllib.parse.unquote(quoted_path[1]).encode()`

I will provide a PR that includes my changes.

#### System Information
mitmproxy 5.3.0

**Comment by mhils** [comment]
Closed via #4271. Thanks again @jpstotz, model PR!
