### ISSUE TITLE
[Request For Comments] The future of pathod and pathoc libraries and CLI tools

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#4273]
The core maintainer team is considering phasing out the pathod and pathoc libraries and CLI tools which are currently part of this repository and part of every release. Installing mitmproxy via pip will give you additional tools for `pathod` and `pathod`.

Here are snippets of what these tools actually are:

> **Pathod** is a pathological HTTP daemon designed to let you craft almost any conceivable HTTP response, including ones that creatively violate the standards. 

> **Pathoc** is a perverse HTTP daemon designed to let you craft almost any conceivable HTTP request, including ones that creatively violate the standards.

We didn't ship documentation or made a big fuzz about their existing for quite some time now. The last time they got any public stage to be found was back in the v2 days - anno 2017 - over three years ago. For anyone interested in what they were actually doing, you can still peak at the [old docs](https://mitmproxy.readthedocs.io/en/v2.0.2/pathod/intro.html).

This issue is a *request for comments* or *call to action*:
* Are you an active user of pathod or pathoc?
* Do you rely on the provided command line tools shipped with the mitmproxy wheels?
* Do you import the pathod or pathoc python libraries in your projects?

We are working hard on a massiv overhaul of our protocol stack in mitmproxy, you might have heard about the not-so-secret **sans-io** efforts @mhils is driving. As such, the new stack will come with a new test harness as well, which renders pathod and pathoc mostly obsolete from their original purpose: being the core testing and fuzzing tool for mitmproxy itself.

Old releases, including our most recent one to date v5.3.0, still include everything - so if you rely on them, simply use the mitmproxy wheels of the version you need.

If we don't hear from you, the users of pathod & pathoc, we will end support with the next major release of mitmproxy. This means we will stop shipping the two CLI tools and remove most of the python library code from the mitmproxy repository.

**Comment by mhils** [comment]
We have decided that pathod and pathoc will be removed in the next release (mitmproxy 7). I'll keep this open until the PR is merged. 😃

**Comment by steve-chavez** [comment]
How can I use an equivalent syntax for pathod nowadays? I relied on https://2qwesgdhjuiytyrjhtgdbf.readthedocs.io/en/latest/pathod/intro.html#pathod for a project.

Is there a way to invoke this with the `mitmproxy` command?

**Comment by timmc-edx** [comment]
I used the _heck_ out of pathod back in the day when I was running simulations to test out a load balancer. Great tool, and I'm missing it now (when I want to test some nginx configs).

Is anyone aware of a replacement? I also might be interested in going back and extracting and releasing pathod as a standalone tool...

**Comment by steve-chavez** [comment]
In case it helps I ended up doing a basic Nginx module for my testing: https://github.com/steve-chavez/ngx_pathological.
