### ISSUE TITLE
Modifying or killing websocket message causes it to be delivered multiple times

### ISSUE THREAD

**Issue by dkasak** [mitmproxy/mitmproxy#4279]
#### Problem Description

I'm using mitmdump with an extension script to monitor and conditionally modify some WebSocket traffic.

Upon a `websocket_message` event, I retrieve the latest message by doing:

```python
msg = flow.messages[-1]
```

For each message I receive, I print whether it originated from the server or client and its content. Additionally, for messages of a certain shape, I replace them with another message. To achieve this, I either do

```python
msg.kill()
flow.inject_message(flow.server_conn, new_content)
```

Or

```python
msg.content = new_content
```

However, regardless of which method I use, two more `websocket_message` events happen *with the same message content as the original message*. All three messages have `msg.from_client` set to `True`. The message is also received by the destination WebSocket component three times instead of one. If I comment out the killing/modification of the message, this stops happening.

I additionally figured out that only *prepending* (as opposed to appending) content causes the anomalous behaviour. That is `msg.content = msg.content + "FOO"` will *not* cause the message to be received three times, but `msg.content = "FOO" + msg.content` will.

This is a relatively large script containing confidential stuff, so I'm not supplying it here. I tried producing a smaller, stripped down example, but I haven't succeeded since it worked as expected there.

This is driving me nuts, because I may be doing something obviously wrong. On the other hand, it's not obvious to me what that could be. Any ideas what could be causing this problem?

#### System Information

```
Mitmproxy: 5.2
Python:    3.8.6
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-5.4.73-1-lts-x86_64-with-glibc2.2.5
```

**Comment by dkasak** [comment]
Upon further experimentation, I doubt this is a mitmproxy bug. The content being sent is XML and I realized that the multiple spurious messages happen when the XML is malformed but not otherwise. I guess the client must really be resending the message multiple times (not under my control so hard to check), though it isn't obvious from the traffic what triggers it to do so.

**Comment by dkasak** [comment]
Actually, I'm not sure what to think. I started killing all server messages from mitmproxy to ensure that it is not the server that is somehow signalling the client to resend the message, but it still happens and only when I modify the message in mitmproxy. If the message itself was causing the client to send multiple times, then it shouldn't be influenced by what I'm doing in mitmproxy.

Is there a way to examine the WebSocket message framing from mitmproxy?

**Comment by Kriechi** [comment]
You could add a print statement somewhere around here: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/proxy/protocol/websocket.py#L202
This reads the raw bytes from the TCP socket and parses it into a Websocket frame.

**Comment by Prinzhorn** [comment]
Maybe you can also chain three mitmdump instances and do logging on the outer two (with a very simple addon) so you can see exactly what messages are going out and coming in without touching them.

**Comment by dkasak** [comment]
Thanks for the inspiration @Prinzhorn. The good news is that it's not a mitmproxy bug. Explanation follows if anyone falls into a similar trap.

It turned out the application's protocol has the ability to confirm the receipt of a websocket message by the server. My script inadvertently changed a crucial part of the message which prevented the client from correlating the server's confirmation with the message and so it tried to resend it twice more before giving up.

This also explains why killing messages originating from the server did not help. In this case, the confirmation is also never received, so the client again resends. But when my message modifications were turned off, the crucial part of the message was not modified, so these resends were idempotent on the server and thus without effect.
