### ISSUE TITLE
several helm charts can't be reached from mitmproxy

### ISSUE THREAD

**Issue by ngtuna** [mitmproxy/mitmproxy#4285]
#### Problem Description
We need mitmproxy for our internal environment. We installed it with a custom CA cert instead of the default mitm generated one. Now we face some errors with pulling helm charts through mitmproxy:

```
10.28.224.80:49390: CONNECT helm.elastic.co:443
 << Cannot establish TLS with client (sni: helm.elastic.co): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad certificate')])")
10.28.224.80:49390: clientdisconnect
10.28.224.80:49406: clientconnect
10.28.224.80:49406: CONNECT charts.helm.sh:443
 << Cannot establish TLS with client (sni: charts.helm.sh): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad certificate')])")
10.28.224.80:49406: clientdisconnect
10.28.224.80:49412: clientconnect
10.28.224.80:49414: clientconnect
10.28.224.80:49416: clientconnect
10.28.224.80:49412: CONNECT charts.bitnami.com:443
 << Cannot establish TLS with client (sni: charts.bitnami.com): TlsException("SSL handshake error: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad certificate')])")
10.28.224.80:49412: clientdisconnect
```

#### Steps to reproduce the behavior:
1. install latest mitmproxy docker image with custom CA cert, specified via `--set confdir=/tmp/mitmproxy`, custom CA cert injected at that folder, renamed to `mitmproxy-ca.pem`
2. set http_proxy, https_proxy point to mitm endpoint (both use http://)
3. then issue happens when do some helm deploy.

#### System Information
```
mitmproxy --version
Mitmproxy: 5.3.0
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020
Platform:  Linux-4.15.0-1098-azure-x86_64-with
```

**Comment by Kriechi** [comment]
I tested browsing https://helm.elastic.co through Firefox (with HTTP/2)  and mitmproxy with the auto-generated CA. It works just fine.
<img width="952" alt="Screenshot 2020-11-09 at 19 00 42" src="https://user-images.githubusercontent.com/114300/98578622-df924300-22bd-11eb-8b3e-530b8467d487.png">

Please try with the CA from mitmproxy instead of your custom one and let us know.

**Comment by Prinzhorn** [comment]
> We don't want to use the CA from mitmproxy.

@Kriechi wasn't suggesting switching to the CA as a solution. This is just part of the debugging process to understand the issue. If it works with the mitmproxy CA then this brings us closer to a solution.

**Comment by ngtuna** [comment]
I created it with terraform tls. It doesnt have problem with the cert as I could run mitmproxy in regular or transparent mode with that cert. I guess the problem here is with upstream mode setup. But I don't quite get it yet
