### ISSUE TITLE
Error starting proxy server: OSError(48, 'Address already in use')

### ISSUE THREAD

**Issue by Deja-vuuu** [mitmproxy/mitmproxy#4289]

**Comment by Deja-vuuu** [comment]
![image](https://user-images.githubusercontent.com/27748682/99238008-28a14480-2834-11eb-8eaa-d8cf9d68c48b.png)

**Comment by Deja-vuuu** [comment]
Which port does this program need to use?

**Comment by Prinzhorn** [comment]
> Which port does this program need to use?

8080

```
mitmdump --listen-port 8081
```
