### ISSUE TITLE
Error occurred in protobuf dumps and loads.

### ISSUE THREAD

**Issue by dragonforeverliu** [mitmproxy/mitmproxy#4290]
#### Problem Description
Error occurred when I call protobuf dumps and dumps.  Code like following:

    def response(self, flow: http.HTTPFlow):
        d = protobuf.dumps(flow)
        df = protobuf.loads(d)
        logger.info(df)

Addon error: Traceback (most recent call last):
...
    df = protobuf.loads(d)
  File "mitmproxy/io/protobuf.py", line 198, in loads
  File "mitmproxy/io/protobuf.py", line 182, in load_http
  File "mitmproxy/io/protobuf.py", line 117, in _load_http_request
TypeError: __init__() missing 2 required positional arguments: 'authority' and 'trailers'

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 5.3.0 binary
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-4.4.0-142-generic-x86_64-with-glibc2.4

**Comment by mhils** [comment]
Hi,

We do not maintain our protobuf implementation at the moment as we don't use it internally and the maintenance burden is too high. Feel free to submit PRs that fix this, but it's not part of our regular testing at the moment. I'll add a comment to the file pointing that out.
