### ISSUE TITLE
Request content missing

### ISSUE THREAD

**Issue by Forium777** [mitmproxy/mitmproxy#4291]
#### Problem Description
I've look through the web without finding a working solution (including stackoverflow). I've try to increase ``body_size_limit`` and ``stream_large_bodies`` to 10gb but nothing has changed. Any ideas ?

#### Steps to reproduce the behavior:
1. Throw a request with "big body"
2. Get "Request content missing." or "Response content missing."
3. 

#### System Information
``mitmdumb.exe --version`` (can't find ``mitmproxy``) :    
Mitmproxy: 5.3.0 binary
Python:    3.7.9
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Windows-10-10.0.18362-SP0

**Comment by Prinzhorn** [comment]
You didn't really include clear steps to reproduce it. So I'm throwing this one out: are you waiting long enough? Mitmproxy needs to download the full body before you can see/use it. Depending on your connection and the file size this might take multiple minutes.

**Comment by tamaker** [comment]
@Forium777 curious, did you ever resolve this? I'm having the same issue
