### ISSUE TITLE
Slackin revoked token 

### ISSUE THREAD

**Issue by omarmhaimdat** [mitmproxy/mitmproxy#4293]
#### Problem Description
Unable to get an invite to the mitmproxy slack. Probably due to Slackin

#### Steps to reproduce the behavior:
1. Go to -> https://slack.mitmproxy.org/
2. enter a valid email address
3. Finish the captcha
4. click on "Get my invite" button

#### Screenshot of the get an invite page
![image](https://user-images.githubusercontent.com/2160742/99389489-6acf9200-28d7-11eb-8923-81112110df4e.png)

**Comment by mhils** [comment]
Thanks! Pretty sure I screwed this up yesterday. :)

**Comment by mhils** [comment]
Looks like I deleted our "legacy" Slack API token and that can't be regenerated.

The workaround is that you can now share invite links to Slack:
https://join.slack.com/t/mitmproxy/shared_invite/zt-j6xka7h1-Un2RyRckXjqVFTtVOXutBg

This link need to be regenerated every 30 days (see https://github.com/integrations/slack/issues/1063). We'll do that as a workaround for a bit, but if there is no viable workaround soon we'll switch to another platform.

**Comment by mhils** [comment]
I have updated slack.mitmproxy.org to now redirect to the invite page.

If we forgot to refresh the link, please ping us here!
