### ISSUE TITLE
Using mitmproxy as a library

### ISSUE THREAD

**Issue by henryreed** [mitmproxy/mitmproxy#4297]
#### Is your feature request related to a problem? Please describe.
I'm trying to see if it is possible to use mitmproxy as a library, rather than an executable. The benefit of this is two-fold. The first is the ability to capture specific data and parse it within the larger project using objects. The second benefit is the ability to customize some of mitmproxy's capabilities. For example, I would like the option to disable `mitm.it` webpage and get the certificate in code, instead. This would theoretically allow someone to automatically initialize mitmproxy and embed the certificate into a specific browser without user interaction. 

#### Describe the solution you'd like
The support for the capability to use mitmproxy as a library, rather than using mitmproxy with add ons.

#### Describe alternatives you've considered
A viable but unideal solution right now is to launch mitmproxy with an add on that dumps data to stdout, then parsing it within the larger program. It is also possible to use interprocess communication methods described [here](https://docs.python.org/3/library/ipc.html). This solution is unideal because it forces the developer to create a parser for the data that is being printed by mitmproxy, as well as any exceptions that could come up. It would be better to be able to interact with the objects mitmproxy generates directly. 

I am unaware if it is possible to disable `mitm.it` and get the certificate through the add ons feature. (If it is, please let me know!)

#### Additional context
There have been previous threads on this idea. The [first](https://github.com/mitmproxy/mitmproxy/issues/3573), posted a year ago, stated that the feature to use mitmproxy as a library has been deprecated. Has this changed recently? Is there any plan to bring this capability back? The [other issue](https://github.com/mitmproxy/mitmproxy/issues/1717) could be solved with the add ons feature and hence was closed.

I may be completely off-base here and lack an understanding of the inner workings of mitmproxy. Please let me know if what I am suggesting is too far out of scope, impractical, or if another viable alternative exists.

**Comment by Kriechi** [comment]
The `mitm.it` site is just another addon: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/onboarding.py

You can simply remove it (via another addon or other code): https://github.com/mitmproxy/mitmproxy/issues/4208#issuecomment-716025794

We currently have no plans to make mitmproxy usable as library. The addon integration and the event hooks provide a powerful interface so you can stream the data to your system if you need to. If you are missing any hooks or metadata we are happy to look into adding them if available internally.
