### ISSUE TITLE
Inline scripts document has wrong reference for SSLCert object

### ISSUE THREAD

**Issue by michaeljau** [mitmproxy/mitmproxy#430]
The inline scripts document currently has the reference "libmproxy.certutils.SSLCert". It should be "netlib.certutils.SSLCert".

**Comment by mhils** [comment]
Hi there,

any updates on this? :smile: 

Cheers,
Max

**Comment by michaeljau** [comment]
Sorry about the slow reply Max. I just edited inlinescripts.html file to fix the reference to the certutills.SSLCert object.

 

I created a Pull Request after that to request the change be merged into the main branch.

 

Please let me know if that isn’t the correct way of doing it.

 

*  Michael

**Comment by mhils** [comment]
Excellent. Thanks! :smile:
