### ISSUE TITLE
How does one build the windows biniary

### ISSUE THREAD

**Issue by jpfeif** [mitmproxy/mitmproxy#4302]
I understand that it is a PITA, as I have seen in many sections in the old forum, github, and stackoverflow just saying it's a PITA and saying that I should find a different way but I need to build my own binary for my purposes.  I understand that we use Pyinstaller for this task, if someone could just give a small explainer and point me in the right direction with some of the commands, that's all I need, I don't need another person telling me not to try it and that it is a PITA. 
Thank you very much

**Comment by Prinzhorn** [comment]
Does this help?

https://github.com/mitmproxy/mitmproxy/blob/e36c790d5595c486f85f084239a8a60a64a63310/.github/workflows/main.yml#L95-L122

https://github.com/mitmproxy/mitmproxy/blob/e9a2a9c25a8d3809613a3b7aa282650b941f9d14/release/cibuild.py#L453-L502

**Comment by mhils** [comment]
https://stackoverflow.com/questions/62334867/how-are-the-pre-compiled-mitmproxy-binaries-actually-built/62335358#62335358
