### ISSUE TITLE
Upgrade to Python 3.8+

### ISSUE THREAD

**Issue by Kriechi** [mitmproxy/mitmproxy#4303]
similar to #2266

This issue tracks all roadblocks we need to overcome to make use of Python 3.8-exclusive features. There's not immediate need to upgrade right away, but it's useful to have an overview of what's left nonetheless.

### Windows
✔️ Windows users can just install Python 3.8
✔️ Windows Subsystem for Linux currently contains Ubuntu 20.04

### macOS
✔️ Homebrew and the mitmproxy formulae will work just fine with Python 3.8 or 3.9
✔️ macOS Catalina ships with Python 3.8.2

### Ubuntu
✔️ Groovy 20.10 has Python 3.8.6
✔️ Focal 20.04 LTS has Python 3.8.5
❌ Eoan 19.10 has Python 3.7.5
❌ Disco 19.04 has Python 3.7.3
❌ Cosmic 18.10 has Python 3.6.7
❌ Bionic 18.04 LTS has Python 3.6.9
❌ Artful 17.10 has Python 3.6.3
❌ Zesty 17.04 has Python 3.5.3
❌ Xenial 16.04 LTS has 3.5.1

### Debian
✔️ Debian bullseye has Python 3.8.6 - **unreleased as of 2020-11-21**
❌ Debian 10 (buster) has Python 3.7.3
❌ Debian 9 (stretch) has Python 3.5.3

### Arch Linux
✔️ rolling release: has Python 3.8.6 as _python_ package in _Extra_

### Fedora
✔️ Fedora 32 has Python 3.8.6 (released 2020-10)
✔️ Fedora 32 has Python 3.8.6 (released 2020-04)
❌ Fedora 31 has Python 3.7.9
...
❌ Fedora 27 has Python 3.6.3
❌ Fedora 26 has Python 3.6.3
❌ Fedora 25 has Python 3.5.4

### Kali Linux
✔️ kali-rolling has Python 3.8.6 (as of 2020-11-21) - rolling release since January 2016

### PyInstaller
✔️ PyInstaller supports Python 3.8 since PyInstaller 4.1.

**Comment by mhils** [comment]
This looks good enough to me, no? :)

**Comment by mhils** [comment]
- [ ] Update PyInstaller
 - [ ] Drop old Python versions from CI
