### ISSUE TITLE
@concurrent does not seem to work

### ISSUE THREAD

**Issue by hendychua** [mitmproxy/mitmproxy#4311]
#### Problem Description

Hi,

I was trying out the [nonblocking example](https://docs.mitmproxy.org/stable/addons-examples/#nonblocking) but I did not see any difference with or without the decorator.

Is this a bug or did I misunderstand what this decorator is supposed to do?

#### Steps to reproduce the behavior:
1. Duplicate the example into a file, for example `main.py`.
2. Run `mitmdump -s main.py`.
3. Run `curl --proxy http://127.0.0.1:8080 --insecure <any-url-to-test>`.
4. Notice that even with the decorator, the `curl` request pauses for 5 seconds before printing the response. In mitmdump's console, you can also see that the actual request from the proxy to the server happens after the `time.sleep()`. I was expecting the request to proceed **without** waiting for `time.sleep()`.

#### System Information
```
Mitmproxy: 5.3.0
Python:    3.9.0 (I'm not sure why this outputs 3.9.0. I'm using python 3.8.3.)
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  macOS-10.15.7-x86_64-i386-64bit
```

**Comment by mhils** [comment]
Hi,

You're misunderstanding the option. `@concurrent` will still delay the particular requests, but it allows other requests to pass through in the meantime. In your third step, try running `curl --proxy http://127.0.0.1:8080 --insecure <any-url-to-test>` two times in parallel with and without the decorator and it should become clear what the difference is.

If you want to run something in the background and not block the flow, you can spawn a new thread (`threading.Thread(target=thread_function).start()`)  or a new asyncio task. The decorator is doing nothing else, but additionally intercepts the flow until that thread has completed. 😃

**Comment by mhils** [comment]
Forgot to add: Thanks for the super clear issue description!

**Comment by hendychua** [comment]
Hi,

thank you! This becomes clearer after your explanation. Also managed to get my stuff working with both threading & asyncio approaches. Thanks for the guidance!
