### ISSUE TITLE
Transparently proxify don't work

### ISSUE THREAD

**Issue by lwgpshit** [mitmproxy/mitmproxy#4314]
#### Problem Description
transparently-proxify not work,em i just want to intercept quest of a dont support proxy’s local linux program.
I followed this [tutorial](https://docs.mitmproxy.org/stable/howto-transparent-vms/),but it didn't work.

#### Steps to reproduce the behavior:
1. sudo sysctl -w net.ipv4.ip_forward=1 
2. sudo iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j REDIRECT --to-port 8080 
3. sudo iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 443 -j REDIRECT --to-port 8080
4. mitmproxy --mode transparent

#### System Information
Mitmproxy: 5.3.0 binary
Python:    3.7.9
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-4.19.0-12-amd64-x86_64-with-debian-10.6

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
