### ISSUE TITLE
Is there any method for cashing Proxy ?

### ISSUE THREAD

**Issue by dev-chulbuji** [mitmproxy/mitmproxy#4316]
#### Is your feature request related to a problem? Please describe.
No. but i wanna any method for cashing proxy for any exceptions in `addons`

#### Describe the solution you'd like
I hope there is a way to stop the proxy itself when there is any problem in `addons`
```
class TestAddons:
    def __init__(self):
        test_env = os.environ.get('TEST_ENV', None)
        if test_env is None:
            raise exceptions.ProxyException("test_env is must set!")
```
This `mitmproxy.exceptions` just stops addon logic, not proxy itself.

#### Describe alternatives you've considered
i donot have any idea. but wanna ask to any proper method for me

**Comment by Kriechi** [comment]
How about just calling `sys.exit`?

**Comment by dev-chulbuji** [comment]
@Kriechi 
Thx, close issue.

**Comment by dev-chulbuji** [comment]
@Kriechi 
```
from mitmproxy import ctx, http
import re, json, sys, signal, os

class AwsApiCallProxy:
    def __init__(self):
        # graceful shutdown
        signal.signal(signal.SIGINT, self.signal_handler)

        test_env = os.environ.get('TEST_ENV', None)
        if kabang_env is None:
            self.print_log("TEST_ENV must be set!", None, None)
            sys.exit()
```

`sys.exit()` does not seem to kill the mitmproxy process.. :(

**Comment by Kriechi** [comment]
@dev-chulbuji please see https://github.com/mitmproxy/mitmproxy/blob/master/examples/addons/shutdown.py
