### ISSUE TITLE
ControlException in concurrent addons

### ISSUE THREAD

**Issue by divanorama** [mitmproxy/mitmproxy#4320]
#### Problem Description
Sometimes concurrent addon raises an exception
```
Addon error: Traceback (most recent call last):
  File "/nix/store/dwn3qncqpyk3xj2c7cijdwcwrm07dz79-python3.8-mitmproxy-5.3.0/lib/python3.8/site-packages/mitmproxy/script/concurrent.py", line 32, in _concurrent
    obj.reply.take()
  File "/nix/store/dwn3qncqpyk3xj2c7cijdwcwrm07dz79-python3.8-mitmproxy-5.3.0/lib/python3.8/site-packages/mitmproxy/controller.py", line 91, in take
    raise exceptions.ControlException(
mitmproxy.exceptions.ControlException: Reply is committed, but expected it to be start.

Addon error: Traceback (most recent call last):
  File "/nix/store/dwn3qncqpyk3xj2c7cijdwcwrm07dz79-python3.8-mitmproxy-5.3.0/lib/python3.8/site-packages/mitmproxy/script/concurrent.py", line 32, in _concurrent
    obj.reply.take()
  File "/nix/store/dwn3qncqpyk3xj2c7cijdwcwrm07dz79-python3.8-mitmproxy-5.3.0/lib/python3.8/site-packages/mitmproxy/controller.py", line 91, in take
    raise exceptions.ControlException(
mitmproxy.exceptions.ControlException: Reply is taken, but expected it to be start.
```
This doesn't completely break mitmproxy, as some requests still pass, in fact clients seem to be getting enough requests (either exception doesn't affect response, or client tolerates few failures).

#### Steps to reproduce the behavior:
Working on it, wasn't able to easily reproduce in a small setting. But stably observe in a bigger script, which runs a localhost-only network sandbox + addon similar to map_local but with @concurrent decorator (trying to do a sandboxed offline build).

Any hints on where to look debugging this?

#### System Information
Mitmproxy: 5.3.0
Python:    3.8.6
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-4.19.146-gentoo-x86_64-Intel-R-_Core-TM-_i7-4702MQ_CPU_@_2.20GHz-with-glibc2.2.5

**Comment by mhils** [comment]
Tricky - do you by chance have multiple addons with `@concurrent`?

**Comment by divanorama** [comment]
Yes, turns out I was accidentally using two concurrent scripts - "maplocal2" which should work ok, and at the same time a really hacky first attempt at making maplocal async
```python
from mitmproxy import http
from mitmproxy import ctx
from mitmproxy.addons import maplocal
from mitmproxy.script import concurrent

@concurrent
def request(flow):
    ctx.master.addons.get("maplocal").request(flow)
    if flow.response: # and flow.response.status_code() == 200:
        return
    flow.response = http.HTTPResponse.make(404)
```
So it is both - two async addons, and calling maplocal addon from another script. Keeping just maplocal2 (which is self-contained concurrent addon) fixed it.
