### ISSUE TITLE
Error starting proxy server

### ISSUE THREAD

**Issue by ashishpatel1992** [mitmproxy/mitmproxy#4321]
#### Problem Description
Getting following error on console while running in normal usermode as well as administrator mode on windows.
`Error starting proxy server: gaierror(11001, 'getaddrinfo failed')`
#### Steps to reproduce the behavior:
1.  Run command prompt as Administrator
2.  Tried `mitmweb` , `mitmweb -p 8999`, and other different ports

#### System Information
Mitmproxy: 5.3.0 binary
Python:    3.7.9
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Windows-10-10.0.19041-SP0

**Comment by mhils** [comment]
I can start mitmproxy on Windows just fine, both as Administrator and as non-administrator. Any other ideas what could cause this for you?

**Comment by ashishpatel1992** [comment]
I have tried everything. Downloaded stable release still doesn't work. After that I tried to clone the repo and run as admin still not working. I have no clue what could have gone wrong.
I am on Python 3.8.5

**Comment by mhils** [comment]
This doesn't look like a mitmproxy bug per se - are you maybe running into https://github.com/DjangoGirls/tutorial/issues/1669#issuecomment-660487654?

**Comment by ashishpatel1992** [comment]
My computer name is `Ashish-PCAzom` which seems to appear fine to me.
I am still clueless about this issue.

**Comment by mhils** [comment]
Does the first example [here](https://docs.python.org/3/library/socket.html#example) work for you?

**Comment by ashishpatel1992** [comment]
Its not working, the server code gets stuck cannot even terminate using ctrl+z
while client code returns error
```
Traceback (most recent call last):
  File "cli.py", line 6, in <module>
    s.connect((HOST, PORT))
socket.gaierror: [Errno 11001] getaddrinfo failed
```

**Comment by mhils** [comment]
Thanks. I'm not sure what's causing this, but if plain Python sockets are failing there is not much we can do. This seems to be a problem with your Python installation or network configuration?
