### ISSUE TITLE
mitmproxy backend problem with .exe

### ISSUE THREAD

**Issue by P-Leo10** [mitmproxy/mitmproxy#4322]
Hi! I made an executable of my python program with seleniumwire where it opens a chrome webdriver with mitmproxy backend. Initially it was not going on the other pc that does not have python installed and I saw that the problem was that it did not have mitmproxy installed. I did the installation in mitmproxy-5.3.0 now. When it tries to open with backend, it gives the following error:

proxy returned status 502 for http://seleniumwire/initialise

I need an answer as soon as possible to solve my problem. Thank you already

**Comment by Kriechi** [comment]
Please follow the bug report issue template.
