### ISSUE TITLE
"authority" Request header not showing for HTTP2 traffic in mitmproxy 5.3

### ISSUE THREAD

**Issue by StevenRoosa** [mitmproxy/mitmproxy#4327]
Mitmproxy 5.3 does not appear to show "authority" headers (i.e. host header) for HTTP version 2 traffic. I compared the same app I was testing by using mitmproxy 4.04, and it showed an "authority" Request header for each of the hosts for which the header was missing when using mitmproxy 5.3. 

Although I can't share my current test because it is for a client, and I can try to reproduce with another app and circle back on this thread with that.  However, please note, from my observations this should be readily observed in various contexts, because I don't see any HTTP 2 requests showing authority or host headers in Mitmproxy 5.3.

Version for mitmproxy 5.3 references above:
Mitmproxy: 5.3.0 binary
Python:    3.7.9
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-4.15.0-126-generic-x86_64-with-debian-buster-sid

Version for mitmproxy 4.04 comparison:
Mitmproxy: 4.0.4 binary
Python:    3.6.3
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Linux-4.15.0-126-generic-x86_64-with-debian-buster-sid

**Comment by mhils** [comment]
This was somewhat intentional because we also don't show `:path`, `:method`, and `:scheme`, which are all (including :authority) included in the header line (`GET https://example.com/`). Do you feel we should repeat them explicitly again in the headers section for HTTP/2?

**Comment by StevenRoosa** [comment]
This is somewhat selfish on my part, because I have parsers hooked up to mitmproxy that recognize them as part of the structure.  I definitely preferred those headers being explicitly set forth (as they were in 4.04).  Having said that though, if there are good reasons to exclude them, and it's better for the mitmproxy community to exclude them, I would totally understand.  Thanks again for all the wonderful work you and the other devs too, it is very much appreciated, and mitmproxy is wonderful software.

**Comment by baptx** [comment]
@mhils Showing the Host header in mitmproxy would be useful to modify the host header if we want to test host header injection (which cannot be tested by replaying the HTTP request with curl if there is a CAPTCHA).
How can we modify the Host header on an intercepted request if it is not displayed?
