### ISSUE TITLE
Error when replacing request file content using mitmweb/ui

### ISSUE THREAD

**Issue by yoganlava** [mitmproxy/mitmproxy#4328]
#### Problem Description
I cannot upload a file and replace the contents of a response using mitmproxy ui.
Probably a client side error as I see this in the console:
`Uncaught TypeError: i is not a function
    at onChange (app.js:143)
    at Object.cb (vendor.js:122)
    at Object.invokeGuardedCallback (vendor.js:122)
    at Object.invokeGuardedCallbackAndCatchFirstError (vendor.js:122)
    at gb (vendor.js:122)
    at Object.executeDispatchesInOrder (vendor.js:122)
    at Fb (vendor.js:122)
    at Hb (vendor.js:122)
    at Array.forEach (<anonymous>)
    at Db (vendor.js:122)`
#### Steps to reproduce the behavior:
1. Intercept a response
2. Try and change the file contents
3. Crash
#### System Information
Mitmproxy: 5.3.0
Python:    3.8.3
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Windows-10-10.0.19041-SP0

**Comment by Prinzhorn** [comment]
> * Intercept a response
> 
> * Try and change the file contents
> 
> * Crash

Cannot reproduce, I successfully replaced the response of www.example.com

![Selection_736](https://user-images.githubusercontent.com/679144/101803348-b230f300-3b10-11eb-9c4b-5c6b8c068db9.png)


This sounds like an issue with the application you are intercepting. Maybe your edited response is invalid and not what the application is expecting. It's impossible to help you with the information you've given.

**Comment by Prinzhorn** [comment]
Please ignore my previous comment, I wasn't really paying attention thought you said mitmproxy, not mitmweb.

However, I cannot reproduce it with mitmweb either. I can successfully edit a response.

What browser are you using? Can you record a screencast with the dev tools open so we can see the steps you take and the error message?
