### ISSUE TITLE
Exit Mitmproxy when CTRL+C pressed and running script

### ISSUE THREAD

**Issue by illera88** [mitmproxy/mitmproxy#4329]
I would like to know if there is anyway to close mitmproxy when pressing CTRL+C while running a script (addon). 
My script uses threads but I make sure to terminate them when CTRL+C gets used.

#### System Information
Mitmproxy: 5.3.0
Python:    3.8.6
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Windows-10-10.0.17763-SP0

**Comment by mhils** [comment]
I think the proper way to handle that is to act on the `done` event (see https://docs.mitmproxy.org/stable/addons-events/), would that work for you?

**Comment by illera88** [comment]
I'll try that.

Thanks
