### ISSUE TITLE
mitmweb:  header toggling via checkboxes

### ISSUE THREAD

**Issue by Granitosaurus** [mitmproxy/mitmproxy#4330]
Currently when replaying requests turning off/on headers is rather complicated: both name and value have to be deleted to skip sending the request. Would be great to have a checkbox next to each header that could toggle the sending of it.

Quick mockup:   
![image](https://user-images.githubusercontent.com/5476164/101443759-bf06e880-3950-11eb-8bdf-0ff04e0e671d.png)

**Comment by mhils** [comment]
Thanks for the suggestion! I think this is a sensible idea, but it doesn't really cross the threshold in terms of usefulness to be included in such a prominent position. 
When I need this kind of functionality I generally just rename the header, e.g. `user-agent` -> `user-agentx`, which usually has the same effect, but doesn't require additional UI knobs. Would that cover your use case as well?

**Comment by Granitosaurus** [comment]
> generally just rename the header, e.g. `user-agent` -> `user-agentx`

That's a great idea!   
However some targets behave differently when receiving unexpected headers so a checkmark would still be a preferred option. Many request GUIs do include checkmarks for headers: insomnia, postman, burpsuite etc.

**Comment by mhils** [comment]
I'd be generally open to having such a feature, but the problem is that it comes with a surprising amount of complexity. We need to introduce some new state for disabled headers somewhere that is synced between web front end and back end, making this quite complex. _Maybe_ we could get by abusing `flow.metadata` to store disabled headers, but that's not really ideal either. Long story short, this is nothing we're going to spend energy on. Sorry!

**Comment by Granitosaurus** [comment]
As an alternative solution for this I started using simple python addon:

```

class DisableHeaders:
    block_headers = [
        "accept",
        # "user-agent",
        "host",
    ]

    def request(self, flow: HTTPFlow):
        req = flow.request
        req.headers = Headers({
            k: v for k, v in req.headers.items()
            if k.lower() not in self.block_headers
        })


addons = [
    DisableHeaders()
]
```

Just comment/uncomment `block_headers` attribute and run it via `mitmweb -s myaddon.py`. mitmproxy addons hot reload so it's turning out to be much more convenient than editing the web page.

**Comment by mhils** [comment]
This looks good! You can probably achieve similar results with the builtin [Modify Headers](https://docs.mitmproxy.org/stable/overview-features/#modify-headers) feature.
