### ISSUE TITLE
I want native packets. How do I get them

### ISSUE THREAD

**Issue by divmid** [mitmproxy/mitmproxy#4331]
* Like this
```
HTTP/1.1 200 OK
Date: Tue, 08 Dec 2020 11:25:44 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.45
X-Powered-By: PHP/5.4.45
Content-Length: 7
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```
![1607426855(1)](https://user-images.githubusercontent.com/40823856/101478564-d7e0bf80-398b-11eb-8675-d79cf9841e46.png)

*  I use ``mitmdump  -p 6666  -s  proxy/test.py`` 
* The function response parameters ``flow``, How to get thenative packets through ``flow``.
```
class TrafficProxy(object):

    def response(self, flow):
        # print("request: ", flow.request)
        # print("response: ", flow.response)
        # print("headers: ", flow.response.headers)
        # print("content: ", flow.response.content)
        # print("__dict__: ", flow.response.__dict__)
        # print("flow.request.raw_content: ", flow.request.raw_content)
        # print("flow.response.raw_content: ", flow.response.raw_content)
        # print("dir: request: ", dir(flow.request))
        # print("dir: response: ", dir(flow.response))
        # print("dir: response.data: ", flow.response.data)
        # print("dir: request.data: ", flow.request.data)
        # print("flow: ", dir(flow))
        # print("flow.metadata: ", flow.metadata)
        # print("flow.__dict__:", flow.__dict__)
addons = [
    TrafficProxy(),
]
```

**Comment by mhils** [comment]
You can use the `raw_request` / `raw_response` methods defined in the exporter addon: https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/export.py#L88-L93

**Comment by divmid** [comment]
> 您可以使用在导出器插件中定义的`raw_request`/`raw_response`方法：[https](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/export.py#L88-L93) : [//github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/export.py#L88-L93](https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/addons/export.py#L88-L93)

thank you!
