### ISSUE TITLE
forward proxy without via-header

### ISSUE THREAD

**Issue by dkmbw** [mitmproxy/mitmproxy#4340]
#### Is your feature request related to a problem? Please describe.
i want to use mitm proxy as forward proxy but for certain reasons i want to omit the via-header so it is transparent to the destination.

#### Describe the solution you'd like
certain services do not like the via header and will block me if it is there. i cannot use the transparent proxy which might not do this, since it has to work on different plattforms, not only native linux

**Comment by mhils** [comment]
mitmproxy does not add a via header, so it looks like your problem is not related to mitmproxy?

**Comment by dkmbw** [comment]
ah, okay, i thought it would adhere to that standard. it's okay, if it does not do that :)
