### ISSUE TITLE
Display CONNECT method request in mitmproxy terminal.

### ISSUE THREAD

**Issue by bayanrasooly** [mitmproxy/mitmproxy#4347]
I am trying to view the CONNECT method connection that my device makes to my server. However, mitmproxy does not display any CONNECT method and its headers/domain. 

Is there a way to view this? If not, it would be a great addition to view the connect headers.

**Comment by mhils** [comment]
To clarify, you mean the HTTP CONNECT request from your client to mitmproxy? What would your use case be for this?

**Comment by alt-glitch** [comment]
I do believe @bayanrasooly refers to the HTTP CONNECT method. I believe being able to view the CONNECT method would allow us to see proxy tunnels? I would like to help out in this issue if possible.

**Comment by bayanrasooly** [comment]
Hello any reason for a close?

**Comment by mhils** [comment]
You opened this on December 13, I followed up with another question on the same day, you did not reply. :)

**Comment by bayanrasooly** [comment]
Ah sorry for the confusion. Yes I do mean the HTTP CONNECT from my client to mitmproxy and from mitmproxy to the site

**Comment by mhils** [comment]
Ok, but what would your use case be for this?

**Comment by bayanrasooly** [comment]
I would like to see proxy tunnels. I think it is a nice touch that fiddler and Charles have.

**Comment by mhils** [comment]
Thanks for the clarification. I agree that it would be a nice touch, but it's really nothing we plan on implementing anytime soon. Without going into details, this violates a lot of assumptions around server replay. If you really want to see CONNECT requests, I would recommend running mitmproxy with `--tcp-hosts .*` in reverse proxy mode to your other proxy server.

**Comment by choff** [comment]
Hello @mhils ,

I have a similar issue. I am trying to troubleshoot an issue with the OpenConnect VPN client, where the HTTP CONNECT request is rejected by the server (see [this issue](https://gitlab.com/openconnect/openconnect/-/issues/659)). For this, I am running mitmproxy in WireGuard transparent mode. I wanted to see the headers in the CONNECT requests, but unfortunately, the CONNECT request is not shown by mitmweb at all. I only see the following error message in the console:

`error establishing server connection: [Errno 110] Connect call failed ('XX.XX.XX.XX', 853)`

Is there anything I can do to see the headers of the CONNECT request, as well as the CONNECT response by the server? For example, could I write a script to dump this information? Any help would be very appreciated.

Kind regards.

**Comment by mhils** [comment]
You can 1) run mitmproxy with `--set proxy_debug -vvv`, or 2) inspect the CONNECT call in Wireshark.

**Comment by choff** [comment]
Thanks @mhils , that worked :-)
