### ISSUE TITLE
New Proxy Core: Vote on Feature Priority!

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4348]
mitmproxy 7 will ship with a completely rewritten proxy core, that has been merged into master today (see [CHANGELOG.md](https://github.com/mitmproxy/mitmproxy/blob/master/CHANGELOG.md)). However, a few features from the old proxy core did not make it to the new implementation yet.

 We want to get an idea what we should tackle first, so please vote on the comments below to indicate what we should focus on.

As always, we very much welcome pull requests on all of the features. Please feel free to ping me on our developer chat if you have implementation questions! 😃

**Comment by mhils** [comment]
# HTTP Trailers

**Comment by mhils** [comment]
### WebSocket/TCP Message Injection

**Comment by mhils** [comment]
### SOCKS 5 Proxy Mode

**Comment by mhils** [comment]
### HTTP/2 Push Promises

**Comment by mhils** [comment]
### body_size_limit option

**Comment by mhils** [comment]
### upstream_auth option

**Comment by mhils** [comment]
### upstream_bind_address option

**Comment by DiskGetor** [comment]
Translate to golang with fyne ui

**Comment by jenniejj** [comment]
The ability to easily configure/start/stop a mitmproxy while being able to get the requests/responses in real-time from within a python script without the need for running subprocesses of mitmdump would be lovely.

**Comment by mhils** [comment]
I intended this issue to only track regressions from 6.x here, so I've taken the liberty to mark some comments as off-topic. :)

**Comment by wildwind123** [comment]
https://github.com/mitmproxy/mitmproxy/issues/3457

**Comment by wildwind123** [comment]
Usefull
https://github.com/mitmproxy/mitmproxy/issues/3457

**Comment by mhils** [comment]
Thanks y'all for the feedback! With the exception of HTTP/2 push promises all missing parts have been implemented and I'm looking forward to shipping mitmproxy 7 soon! 😃
