### ISSUE TITLE
 Cannot establish TLS with client with no shared cipher error

### ISSUE THREAD

**Issue by thanhtan27081998** [mitmproxy/mitmproxy#4360]
#### Problem Description
I'm currently implementing an application that call to a https domain.
When I do a http request to my domain, I receive an error 
```
Cannot establish TLS with client (sni: mydomain.com): TlsException("SSL handshake error: Error([('SSL routines', 'tls_post_process_client_hello', 'no shared cipher')])")
```
#### Steps to reproduce the behavior:
1. Install server domain certificate on mobile device
2. Set up proxy on device 
3. Start mitmdump using: mitmdump --cert mydomain.com=domain_cert.pem
2. Do a http request using a native mobile app using my application ( I already verified that the application will work without mitmproxy interception )
3. 
#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 5.2
Python:    3.8.6
OpenSSL:   OpenSSL 1.1.1g  21 Apr 2020

**Comment by kendimce** [comment]
I'm getting the same error in a different situation where i'm trying mitm between my pc and IoT internet bridge device.  As far as I understand from the 'no shared cipher' error, it means mitmproxy does not have Cipher Suite that client would like to use.

**Comment by mhils** [comment]
Could you update to a snapshot from master (https://mitmproxy.org/downloads/#branches/master/) and try again please?
