### ISSUE TITLE
Automated installation does not work (Windows)

### ISSUE THREAD

**Issue by jpfeif** [mitmproxy/mitmproxy#4362]
The automated windows installation command does not work.  You run the command certutil.exe -importpfx Root mitmproxy-ca-cert.p12 and it errors out with the following errors:

CertUtil: -importPFX command FAILED: 0x80070056 (WIN32: 86 ERROR_INVALID_PASSWORD)
CertUtil: The specified network password is not correct.

The command asks for a PFX password, I enter nothing, it gives me that error.

Mitmproxy: 5.3.0 binary
Python:    3.7.9
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Windows-10-10.0.19041-SP0

**Comment by mhils** [comment]
Thanks! `certutil -addstore root mitmproxy-ca-cert.cer` does work for me, this will be fixed in the next release.
