### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by sinancetinkaya** [mitmproxy/mitmproxy#4364]
https://github.com/mitmproxy/mitmproxy/blob/61236759ce468268c58fed66a253df23c0447d62/mitmproxy/net/tcp.py#L620 infinite loop occurs when r=[]
This problem occurred when executing browser.close() twice by mistake

**Comment by Kriechi** [comment]
Please follow the bug report template when reporting a problem.

**Comment by sinancetinkaya** [comment]
I just searched the error on google and reported it on the first github result thinking I was reporting it on pyppeteer project... WOW, sorry...
It turns out that the result was correct but the error is not pyppeteer related.
Where's "the bug report template" ? I couldn't find it.

**Comment by mhils** [comment]
No need to open a bug. The code you are pointing at will be removed in the next release anyway.
