### ISSUE TITLE
OpenSSL.crypto.X509Name cannot be garbage collected

### ISSUE THREAD

**Issue by linw1995** [mitmproxy/mitmproxy#4368]
#### Problem Description

If run mitmdump for a long time, its memory will keep increasing. I manage to narrow down the suspected memory leak is, this line of code in the `dummy_cert` function from `mitmproxy/certs.py` file.

https://github.com/mitmproxy/mitmproxy/blob/554674f37c731d92b0c497611bceefe17c9c514d/mitmproxy/certs.py#L108 

This line will keep creating many `OpenSSL.crypto.X509Name` objects. And they are cannot be garbage collected.

#### Steps to reproduce the behavior:

Run the below script to reveal this problem quickly.

```python
import secrets

import objgraph

from mitmproxy.certs import CertStore

store = CertStore.from_store(path="~/.mitmproxy/", basename="mitmproxy", key_size=2048)

print("before")
objgraph.show_growth()

for _ in range(10000):
    random_string = secrets.token_hex(16)
    commonname = random_string.encode("utf-8") + b".com"
    store.get_cert(commonname=commonname, sans=[], organization=None)

print("after")
objgraph.show_growth()
```

**Output**

```
before
function                       5791     +5791
dict                           2809     +2809
tuple                          2571     +2571
builtin_function_or_method     2052     +2052
weakref                        1594     +1594
wrapper_descriptor             1283     +1283
getset_descriptor              1117     +1117
method_descriptor               953      +953
type                            850      +850
cell                            542      +542
after
dict                    13419    +10610
X509Name                10100    +10100
list                      537      +200
_X509NameInvalidator      202      +200
X509                      101      +100
__CDataGCP                103      +100
CertStoreEntry            100      +100
Cert                      100      +100
function                 5800        +9
weakref                  1599        +5
```

#### System Information

Mitmproxy: 7.0.0.dev (+221, commit 6123675)
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  macOS-10.15.7-x86_64-i386-64bit

#### Temporary Fix

`OpenSSL.crypto.X509` uses `self._issuer_invalidator = _X509NameInvalidator()` to invalidate `X509Name` object 
(in this problem it is issuer name). It holds them forever even the dummy certs are no longer in usage.

Use `X509.from_cryptography` and `X509.to_cryptography` to create a new `X509` object to resolve this problem.

https://github.com/mitmproxy/mitmproxy/blob/554674f37c731d92b0c497611bceefe17c9c514d/mitmproxy/certs.py#L108 

Replace this line of code with the below code.

```python
new_cacert = OpenSSL.crypto.X509.from_cryptography(cacert.to_cryptography())
cert.set_issuer(new_cacert.get_subject())
```

The `X509` and `X509Name` objects make references between themselves.
And they will be garbage collected if the dummy cert being garbage collected.

**Comment by mhils** [comment]
Thanks for the \*fantastic* work. 🍰 This is an exemplary issue again with a an excellent minimal example to reproduce the issue. I won't be able to look into this in the next few days due to Christmas festivities going on here, but be assured that it's at the top of my mitmproxy todo list.

**Comment by mhils** [comment]
And fixed. Thanks again! 🍰
