### ISSUE TITLE
sans-io is missing addon events: clientconnect, clientdisconnect, serverconnect, serverdisconnect

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4369]
#### Problem Description

First try of running sans-io with my addon. I think the connection events are missing completely.

The signature was also not working because

```py
def clientdisconnect(self, layer: mitmproxy.proxy.protocol.Layer):

def serverconnect(self, conn: mitmproxy.connections.ServerConnection):
```
> in script addon.py: No module named 'mitmproxy.connections'
> in script addon.py: module 'mitmproxy.proxy.protocol' has no attribute 'Layer'

While searching for the new names I couldn't find the hooks at all. Maybe they have been overlooked? They exist in tests `/test/mitmproxy/test_flow.py` and `/test/mitmproxy/tservers.py` but are never triggered I think. Are the tests even running?

#### Steps to reproduce the behavior:

Compare 6 vs master

`mitmdump --scripts conn.py --quiet`

```python
def clientconnect(layer):
    print("clientconnect")

def clientdisconnect(layer):
    print("clientdisconnect")

def serverconnect(conn):
    print("serverconnect")

def serverdisconnect(conn):
    print("serverdisconnect")
```

I couldn't test sans-io any further because the missing connection events make my foreign key constraints fail :shrug: 

#### System Information
```
Mitmproxy: 7.0.0.dev (+462, commit 554674f)
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.0-58-generic-x86_64-with-glibc2.29
```

**Comment by mhils** [comment]
It's `client_connected`, `server_connect`, and `server_connected` now. We do need to update the docs for this, and likely emit a warning if an addon is loaded that has one of the old hooks declared.

**Comment by Prinzhorn** [comment]
Nice, I'll play around with it after Christmas and see if everything works as expected. I'll close it then.

**Comment by mhils** [comment]
We really should warn if someone uses the old hooks, let's keep it open until this is resolved. :)

**Comment by Prinzhorn** [comment]
The docs also need the new event I was promised in #3884. Just linking this here so it's not forgotten.
