### ISSUE TITLE
Create a new API endpoint "/download-trafffic" which allows to download traffic on a specific start and end time.

### ISSUE THREAD

**Issue by bansalp004** [mitmproxy/mitmproxy#4371]
#### Problem Description
Currently there are few applications which integrates MITM to provide download traffic capture for a specific start and end time. Right now there is no such API which allows such time based  filtering and traffic download.

#### Proposal
Add a new endpoint /download-trafffic?startFrom=timestamp&endTime=timestamp.
use same mitm default port - so the API endpoint below can work 
http://mitm.it?downloadjson?startTimestamp=startTime&endTimestamp=endTime

**Comment by mhils** [comment]
Thanks again for the suggestion! I don't see this as something that is very much core to mitmproxy, so I'll close this here.

FYI, mitmweb already exposes `http://127.0.0.1:8081/flows.json`. 😃
