### ISSUE TITLE
Export OR extract decoded content

### ISSUE THREAD

**Issue by therealrooster** [mitmproxy/mitmproxy#4376]
First off, awesome project!!  

What I'd like to be able to do is either export or extract the flow content, in decoded (human readable) form to another file.  I do not see this mentioned in any of the documentation or in any examples that I can find.  My apologies if I missed it somewhere.. 

I've successfully exported flows to a separate file (-w).  I can open/read the file using python (io.FlowReader()), but when attempting to strip out the flow content.. the content is still appears to be encoded.  How can I then decode it into the lovely human readable format that mitmproxy displays??  Or is there a better way to accomplish this task?

Thanks in advance!

**Comment by Prinzhorn** [comment]
Can you give an example of how you're using `io.FlowReader()`? There's a difference between `raw_content`, `content` and `text` properties, maybe `text` does what you want?

If you open a flow and hit `e` you get export options, it will open `EDITOR`. Here's me exporting a response body.

I used `EDITOR=nano mitmproxy` as it defaulted to vim

![Selection_770](https://user-images.githubusercontent.com/679144/103444295-7bf61780-4c67-11eb-92d0-51dd0857c642.png)
![Selection_771](https://user-images.githubusercontent.com/679144/103444296-7c8eae00-4c67-11eb-9b39-fa260b7a966e.png)
![Selection_772](https://user-images.githubusercontent.com/679144/103444298-7dbfdb00-4c67-11eb-8d76-fb00da36d862.png)

**Comment by therealrooster** [comment]
I did notice that is an option and I appreciate you pointing that out.  Unfortunately, I don't want to have to do that manually for every single flow.  I'm doing a research project on a handful of apps on both iOS and Android, and would like to be able to automate this export somehow.

**Comment by Prinzhorn** [comment]
I can't really look into this now (and I have never used FlowReader), does `flow_data.get("request").get("text")` produce what you need? Or even `f.request.text`? Or what does "it appears encoded still." mean exactly?

Can you provide a sample recording and compare what you want with want you're actually getting? E.g. a screenshot of mitmproxy with the value you want and a screenshot of the output that your script produces with FlowReader? Maybe that makes it more clear what's happening.

**Comment by Prinzhorn** [comment]
Looking at this again and I think you don't want to work with the raw `get_state` but instead use the wrapper flow/message class, which does the magic you need. So `f.request.text` does what you want, while the raw state doesn't have a `text` property. So `flow_data.get('content')` is equivalent to `f.request.raw_content`

https://github.com/mitmproxy/mitmproxy/blob/ca455482891014d036657d34a2261d8ab66ac5d6/mitmproxy/net/http/message.py#L107-L144

https://github.com/mitmproxy/mitmproxy/blob/ca455482891014d036657d34a2261d8ab66ac5d6/mitmproxy/net/http/message.py#L218-L236

**Comment by therealrooster** [comment]
Sorry for the late response...

This worked and was exactly what I was looking for, thank you!!
