### ISSUE TITLE
Question about parallel client usage

### ISSUE THREAD

**Issue by gfrench17** [mitmproxy/mitmproxy#438]
Hi there,

I have on question for the following situation: I have two android devices connected to a running mitmdump process. Is there any chance for mitmdump to tell which request-response pair belongs to which device?
Similar question: looking at the dump/logfile that mitmdump is able to create, can you tell which response refers to which request? Is it a pure sequencial pattern, e. g. request no. 3 refers to response no. 3?
The usecase behind this is to be able to modify the responses and requests depending on which of the two (or more) devices has sent them.

Kind regards
Gordon

**Comment by mhils** [comment]
H Gordon,

> Is there any chance for mitmdump to tell which request-response pair belongs to which device?

Sure - You can use the client IP as the most deterministic property or fingerprint the clients by their headers.

> Similar question: looking at the dump/logfile that mitmdump is able to create, can you tell which response refers to which request?

Sure - mitmdump stores flows, which have request and (usually) response attributes.

Cheers,
Max
