### ISSUE TITLE
Adding full active row highlight

### ISSUE THREAD

**Issue by balazser** [mitmproxy/mitmproxy#4385]
#### Problem Description

Is this possible to highlight the whole active row instead of using the arrow indicator? :) I can get lost when I try to navigate through the flows to get the cursor to the right one in mitmproxy. 
It's even worse when I try to navigate my cursor to the flow that has a mark (that I use a lot) on the right side because the cursor and the mark are on the opposite sides that are sometimes too far.

![image](https://user-images.githubusercontent.com/20303564/103675257-04362e80-4f80-11eb-8193-a7b2f19cca5e.png) 

#### Proposal
Replace the left indicator arrow `>>` with a full row highlight and move the red dot mark to the place of the cursor. 

#### Alternatives
Leave everything as it is and only add a row highlight.

#### Additional context
I use the tool for development and love it. :heart:

**Comment by mhils** [comment]
I absolutely agree, in fact this has been proposed before in #3732. Unfortunately this is surprisingly tricky with urwid, the best way forward might even be to bypass most of urwid for this and call foreground-only control codes manually.

Closing this as a duplicate. That being said, contributions would be more than welcome!

**Comment by mhils** [comment]
Oh, and thanks for the kind words! :)
