### ISSUE TITLE
Any plans to create a helm chart for kubernetes?

### ISSUE THREAD

**Issue by botzill** [mitmproxy/mitmproxy#4392]
Would be great to have a helm chart for the Kubernetes faster tests. 

Does anyone work on it?

**Comment by mhils** [comment]
Excuse the ignorance, but I'm completely missing the context here. How is your question related to mitmproxy?

**Comment by Kriechi** [comment]
We are happy to accept PRs for this - but we currently do not have this on the roadmap for ourself.

**Comment by gberche-orange** [comment]
A 3rd party helm packaging seems available at https://github.com/relaymonkey/mitmproxy-helm, see within artifacthub at https://artifacthub.io/packages/helm/mitmproxy/mitmproxy
