### ISSUE TITLE
Missing support for encoding x-fb-dz

### ISSUE THREAD

**Issue by teobouvard** [mitmproxy/mitmproxy#4394]
#### Problem Description

Hi ! I'm using mitmproxy to intercept Facebook traffic from their Android app to https://graph.facebook.com/graphql, and they seem to have recently introduced a new encoding called `x-fb-dz` according to the `content-type` header. This encoding is unknown to mitmproxy and causes the following error, which prevents response bodies from being decoded.

```
Addon error: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mitmproxy/net/http/encoding.py", line 65, in decode
    decoded = custom_decode[encoding](encoded)
KeyError: 'x-fb-dz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mitmproxy/net/http/encoding.py", line 67, in decode
    decoded = codecs.decode(encoded, encoding, errors)  # type: ignore
LookupError: unknown encoding: x-fb-dz
```

This encoding might be [zstd](https://github.com/facebook/zstd) using a dictionary trained on a sample of their responses, judging by the presence of a `x-fb-dz-dict` header, but I might be wrong as I don't know much about encodings. 

Are there plans to support this encoding or is this out of scope for mitmproxy ?

#### Steps to reproduce the behavior:
1. Set up a [researcher profile](https://facebook.com/whitehat) to allow user installed certificates on Android device
2. Intercept a POST request to `https://graph.facebook.com/graphql` with header `x-fb-friendly-name` == `fresh_feed_new_data_fetch`
3. Observe that body cannot be decoded and that `content-type` == `x-fb-dz`

#### System Information
Paste the output of "mitmproxy --version" here.

```
Mitmproxy: 6.0.2
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.10.6-arch1-1-x86_64-with-glibc2.32
```

**Comment by mhils** [comment]
Hi @teobouvard,

We don't have formal criteria on which encodings are included. Generally speaking, I would ask the following questions:

1. Does it require additional dependencies?
2. Does it introduce additional code complexity?
3. Does it increase binary size in a meaningful way?
4. Is it useful only to a very small number of mitmproxy users?


Facebook should be big enough to barely pass the bar on question 4. We likely won't not looking into this ourselves, but if someone comes up with a PR, I'd be happy to merge that either directly into mitmproxy or into contrib/.

Does that answer your question?

**Comment by teobouvard** [comment]
Hi @mhils,

That answers my question. I'll briefly answer yours for the record.

1. *If* it turns out to be zstd, it would require a dependency on one of the Python libraries available to decode it
2. If it is plain compression, not at all. If the compression uses a dictionary, we have to capture it to be able to decode subsequent requests, so maybe a little complexity have to be introduced.
3. We'll have to try it to see.
4. I don't know the demographics of mitmproxy users, but I think investigating it might be useful because (again, if it turns out to actually be zstd), this compression scheme is likely to be more widely adopted by other websites in the future as it seems to have quite a lot of advantages over more conventional gzipped responses bodies.

I don't have much time as of now, but I will happily look more into this in a few months.

**Comment by mhils** [comment]
We already support zstd, so that's not a problem. :)
I'm closing this here as there's nothing actionable for us, but I'd be happy to take a look at a PR anytime! 😃

**Comment by mame82** [comment]
Ended up with the same problem for traffic directed to `graph.facebook.com/graphql` and agree that there is a high probability, that `zstd` with a custom dictionary is used. In fact the dictionary to use is indicated by the requesting client within the `accept- encoding` header.

Example (server gets advised to use dictionary `1` for zstd):

```
accept-encoding:      x-fb-dz;d=1, zstd, gzip, deflate
```

Server response indicates that dictionary `1` was used for compression:

```
x-fb-dz-dict:         1
content-encoding:     x-fb-dz
```

I found no indication, whatsoever, that the dictionary gets transmitted, it is likely hardcoded on the client-side (or there is a Facebook specific API request to fetch it). 

Obviously, it can not be the task of mitmproxy, to embed suiting dictionaries for all possible hosts using `zstd` compression. Yet, in the case of FB graphql traffic, `zstd` compression could safely be avoided, by removing it from the sequence of allowed compressions in the `accept-encoding` header.

Gonna leave this here, in case others struggle with the same problem:

Snippet of mitmproxy request hook which modifies `accept-encoding` headers to avoid `zstd` compression for Facebook GraphQL:

```
    def replace_x_fb_dz(self, flow: http.HTTPFlow):
        ae: Union[str, None] = flow.request.headers.get("accept-encoding")
        if ae is not None and ae.startswith("x-fb-dz"):
            # remove zstd compression with unknown dict in AE-headers like "x-fb-dz;d=1, zstd, gzip, deflate"
            flow.request.headers["accept-encoding"] = "x-fb-dz;gzip, deflate"

    def request(self, flow: http.HTTPFlow):
        self.replace_x_fb_dz(flow=flow)  # replace zstd encoding with unknown dict for FB traffic
```

**Comment by mame82** [comment]
I wrote an example add-on to showcase how to deal with 'x-fb-dz' encoding.

It also showcases, that my assumptions were right. The dictionary in use is hardcoded (and well hidden) in the Client within the Facebook app. This not only means that it never gets transmitted over the wire (and thus can't be grabbed by an interception proxy), it also depends on the client version in use, which cannot be determined based on 'x-fb-dz' traffic passing by.

So this ad-on only serves as example on "how not to do it". The better and easier way would be to adjust the `accept-encoding` request header, as described in the previous comment.

Yet, I drawed some conclusions on adjustmens for mitmproxy:

1) The "dump" function for response bodies crashes if one attempts to store 'x-fb-dz' encoded data. It would be better to dump the raw data, in case the `decode` function from `mitmproxy.net.encoding` raises an exception.
2) The aforementioned `decode` function (and the `encode` counterpart) could maybe use an additional overload, which allows to supply a custom dictionary for `zstd` encoded data. I am not sure if this makes too much sense - as my example addon shows, each custom dictionary requires a dedicated `ZstdDecompressor` instance

The addon:
https://github.com/mame82/misc/blob/master/fb-zstd.py

**Comment by mhils** [comment]
Thanks @mame82! This is interesting work. The easiest approach here is to just set mitmproxy's `anticomp` option to remove accept-encoding headers entirely. 

Putting my tinfoil hat hon, this of course makes your client stick out a bit and you kind of need to trust Facebook not to alter their behavior when they know that traffic is being watched. Practically speaking I think this is fine - I don't see much of a new problem here, a malicious adversary could already do that client-side based on the interception certificate (or server-side based on TLS fingerprinting).

**Comment by mame82** [comment]
A quick test with `set anticomp true` has immediate effect. Thx for the heads up on this.

For the Facebook specific case it should be noted, that `accept-encoding: gzip, deflate` is used initially by the App (haven't investigated what triggers the change to `x-fb-dz` encoding). So I agree, in the end it is a decision about "to appear suspicious" to FB graphql endpoints or not. IMHO, if traffic analysis is the goal, the risk that server responses contain other/less content without `zstd` encoding is very low.

Yet, diving into this was interesting. Especially as I wasn't aware of the fact, that this publicly available encoding could be "tuned" in a fashion that it bypasses automated monitoring systems (if they don't know about proper decompression dictionaries). 

There is always something to learn and I am still impressed that mitmproxy is able to do its job as first-hand-tool in each and every situation.

Thx for the project and your resposiveness

**Comment by 89z** [comment]
`set anticomp true` seems to do the trick for me as well. Thank you!
