### ISSUE TITLE
bug in windows 

### ISSUE THREAD

**Issue by ljlVink** [mitmproxy/mitmproxy#4397]
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "mitmproxy\proxy\server.py", line 121, in handle
TypeError: 'NoneType' object is not callable

**Comment by mhils** [comment]
Hi,

Thanks for the report. It looks like this is fixed on the master branch, please let us know if that's not the case.
