### ISSUE TITLE
flow.client_conn.ip_address shows proxy address not actual client address

### ISSUE THREAD

**Issue by michaelschem** [mitmproxy/mitmproxy#4401]
#### Problem Description
When I access the flow.client_conn.ip_address inside the request() method in a custom addon, it reveals the loopback address which is where I have my proxy running, but not the actual client IP.

#### Steps to reproduce the behavior:
1. Create addon
2. Access flow.client_conn.ip_address inside the request method.
3. Observe the IP of the proxy, not the actual client

#### System Information
Running from a python script.
5.3.0

**Comment by mhils** [comment]
Hi,

those parts have changed quite a bit on master, where you should be able to access `flow.client_conn.peername`. Can you try upgrading to master and trying that?

**Comment by crifan** [comment]
My here works fine:

code: `middleware/Save1.py`
```python
	def request(self, flow):
		flowClientConn = flow.client_conn
		print("mitmdump: flowClientConn id=%s,address=%s,ip_address=%s" % (flowClientConn.id, flowClientConn.address, flowClientConn.ip_address))
```

output:

```
mitmdump: flowClientConn id=6a7a21b1-75d0-4229-90c9-b9766c939e19,address=('::ffff:192.168.31.217', 35922, 0, 0),ip_address=('::ffff:192.168.31.217', 35922, 0, 0)
192.168.31.217:35922: POST http://szminorshort.weixin.qq.com/mmtls/0581ba17
                   << 200 OK 213b
```

in which, the `::ffff:192.168.31.217` is expected client address

My environment: 

```
~  mitmproxy --version
Mitmproxy: 5.0.1
Python:    3.8.0
OpenSSL:   OpenSSL 1.1.0j  20 Nov 2018
Platform:  macOS-10.14.6-x86_64-i386-64bit
```
