### ISSUE TITLE
TCP callbacks (`tcp_message`, `tcp_start`) not being called in addons.

### ISSUE THREAD

**Issue by kiturutin** [mitmproxy/mitmproxy#4402]
#### Problem Description
TCP callbacks (`tcp_message`, `tcp_start`) not being called in addons.

#### Steps to reproduce the behavior:
1. Add logging to one of the example addons, for example to `mitmproxy/addons/dumper.py` - to methods `tcp_message` and `response`
2. Run mitmdump with the addon specified: `./venv/bin/mitmdump -p 8200 -s <path-to-mitmproxy-repo>/mitmproxy/addons/dumper.py`
3. Run request using curl: `curl -x localhost:8200 http://httpstat.us/200`
4. In the logs I see that `response` was called but `tcp_message` was not. Same happens if I add `tcp_start` to the addon and check logs.

#### System Information
Mitmproxy: 6.0.2
Python:    3.8.7
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-4.15.0-128-generic-x86_64-with-glibc2.27

**Comment by mhils** [comment]
I think you are misunderstanding the TCP event hooks. These are only called for *TCP Flows*, that is for flows that are not processed by our normal HTTP logic. Here's an example:

```
mitmdump --tcp-hosts ".*" --set flow_detail=3
curl -x localhost:8080 -k https://api.github.com/robots.txt
```

Does that clear up things?

**Comment by kiturutin** [comment]
@mhils Thank you, yes, I understood the purpose of TCP event hooks now.
Could you please clarify a bit more -  so there're no 'tcp events' for HTTP flow and no way to listen to those events in addons?

**Comment by mhils** [comment]
Correct. Mitmproxy either treats connections as HTTP (triggering the respective HTTP hooks), WebSockets (triggering the respective WS hooks), or can fall back to TCP mode (triggering the TCP hooks).

FWIW, the master documentation is a bit more detailed on that at the moment: https://docs.mitmproxy.org/master/addons-events/ If you let me know what your use case is, I might have a few additional pointers.
