### ISSUE TITLE
Remove old documentation pages

### ISSUE THREAD

**Issue by HoffmannP** [mitmproxy/mitmproxy#4405]
#### Problem Description

There are three pages in the documentation that seem to be old as the menu bar on the left they contain differs from the rest of the page. These are https://docs.mitmproxy.org/stable/tools-mitmproxy/, https://docs.mitmproxy.org/stable/tools-mitmdump/ and https://docs.mitmproxy.org/stable/tools-mitmweb/. These three pages are the only ones that contain the "tools" section and the "feature" link in the "overview" secteion. I assume that they are just old.

**Comment by mhils** [comment]
Thanks, that needs to be fixed. Out of interest, how did you discover those pages?

**Comment by mhils** [comment]
refs https://github.com/gohugoio/hugo/issues/2389

**Comment by HoffmannP** [comment]
Google had the links in the cache

**Comment by mhils** [comment]
Ok, that's what I expected. Thanks again for confirming!
