### ISSUE TITLE
Malwarebytes reported trojan in MITMWEB.exe and MITMDUMP.exe

### ISSUE THREAD

**Issue by LouisBellinger** [mitmproxy/mitmproxy#4414]
Malwaresbytes reports 2 generic.trojan.malicious.DDS in mitm.exe as well as mitmdump.exe on Windows 10 (Home edition, 10.0.19042 build 19042). A malware may have corrupted the exe (very unlikely) but still, if this is a false positive, I thought you might be interested. 
 
Steps to reproduce the problem:
Install mitmweb 6.0.2 using the windows installer and run a full malwarebytes scan.

**Comment by Kriechi** [comment]
Thanks - indeed, https://www.virustotal.com/ reports 7 out of 68 scanners flag our binaries...
@mhils any ideas? might be a pyinstaller or installbuilder issue?

![mitmdump](https://user-images.githubusercontent.com/114300/105765654-083ee600-5f59-11eb-981a-4b8284e0e350.png)
![mitmweb](https://user-images.githubusercontent.com/114300/105765662-0aa14000-5f59-11eb-9c8d-f4e4abdf07e1.png)

**Comment by mhils** [comment]
The problem might be WinDivert, which is picked up by some signatures? https://www.virustotal.com/gui/file/88c1ea103719ca6127ccfb8f3b23c1e2c54e3ecb8858ff9b301d57017e85dc2d/community

**Comment by mhils** [comment]
I reported this to Malwarebytes: https://forums.malwarebytes.com/topic/269707-false-positive-mitmwebexe-and-mitmdumpexe/

Thanks for the heads-up, @LouisBellinger! :)

**Comment by mhils** [comment]
Oh and to confirm: I verified that the binaries are unchanged since they were generated by our CI servers in December. 
This is a false-positive.

**Comment by Prinzhorn** [comment]
@LouisBellinger can you confirm this is fixed? Malwaresbytes responded very quickly and this should be resolved.

**Comment by LouisBellinger** [comment]
Fixed indeed!
