### ISSUE TITLE
Occasionally, the HTTP request has no return value, causing the client to wait all the time

### ISSUE THREAD

**Issue by zhaoziming** [mitmproxy/mitmproxy#4417]
mitmproxy 5.3.0
![QQ截图20210201144523](https://user-images.githubusercontent.com/5771422/106423930-504f9280-649c-11eb-9a6c-b9c89737c29e.png)

**Comment by mhils** [comment]
Thanks for the report. This should be fixed on master where flows are timed out automatically after two minutes. Please upgrade and reopen if it persists.
