### ISSUE TITLE
Combine WebSocketFlow and HTTPFlow

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4425]
HTTPFlow and WebSocketFlow currently have a really ugly relation where one depends on the other, they appear separately in dumps, etc. To fix this madness, I would propose we merge WebSocketFlow and HTTPFlow: HTTPFlow just gets a `.websocket: Optional[WebSocketData]` attribute, which contains everything related to the websocket connection (messages, close reason, etc). There also is prior art for this approach: For example, the Chrome Devtools use exactly that data model.

@mitmproxy/devs, thoughts?

**Comment by Kriechi** [comment]
I do like the very clear separation of concerns with two classes and the distinction in the dump. They are two different protocols, where one happens to look like the other for the first couple of milliseconds. Pure coincidence. 🤞 

I'm open to being talked into making `WebSocketFlow` a subclass of `HTTPFlow`, but getting rid of it entirely is a step in the wrong direction IMO.

I don't accept the example of Chrome Devtools here. I think this happened out of convenience and backward-compatibility reasoning. We have a chance to do better - and I think we did, but having a dedicated Flow type.

**Comment by mhils** [comment]
Subclassing does not really help here, that only complicates flow instantiation etc. We can't really upgrade to a subclass in-situ.

I agree that separation would be nice. However, from a pragmatic perspective, we have two different flows for one WebSocket connection right now, which is quite unintuitive. It forces us to write quite a few weird workarounds: https://github.com/mitmproxy/mitmproxy/blob/50ae75aedf057b9e40ddcd82e7fbe772a29112b1/mitmproxy/master.py#L122-L131

Most importantly, a problem that is still unsolved: how do we want to display WebSocket flows in the flow list? As _two_ flows?? That feels very wrong. If we agree to only show one, body filters are super weird, because which flow do they apply to?

If we leave the "purity" argument aside, what's the benefit of the current design? Having a single `.websocket` attribute makes all practical implementation pretty much straightforward.

**Comment by Prinzhorn** [comment]
As someone who has mapped all these things into a relational database model all I can say is that an HTTPFlow can have zero or one WebSockets. From this standpoint I'd say HTTPFlow and WebSocketFlow exist on different levels. I think what I'm trying to say is that there is a hierarchy like a parent child relation. To me the natural way to display the WebSockets in the UI would be as a tab (or something) inside the details of an HTTPFlow. Currently there are Request / Response / Details tabs. Maybe we can rethink them and have dynamic tabs? And the flow overview tells you (in an extra column?) that there is a WebSocket. And we add a new flow filter `~wsm` (or `~websocket_messages` whatever) that will only show the HTTPFlows in the list that have a WebSocketFlow where at least one (or no) message contains the given regex.

Maybe this helps :smile:

**Comment by mhils** [comment]
@Prinzhorn, thanks - I think I agree on almost all of your points. For the filters, we would just adjust `~websocket` to detect HTTPFlows with a non-None websocket attribute.

@Kriechi, could we convince you a bit?

**Comment by Kriechi** [comment]
WebSocket is not HTTP.
WebSocketFlows should not be HTTPFlows.

I've raised my voice - and won't stop you if you send a green PR. 😄

**Comment by Prinzhorn** [comment]
I didn't mean to make an argument for either side :smile: . I don't know enough about the implications to do that. I agree with @Kriechi that they are separate concerns while at the same time a WebSocket cannot exist without the initial handshake. Right? Or would it be possible to construct a scenario where we want to have a WebSocket without HTTP (e.g. for mocking tests)?

Here are some practical questions for @mhils : What will the argument for the `websocket_*` hooks be? Just the `HTTPFlow`? That feels odd. Or the `WebSocketData`? Does it have a circular link back to the `HTTPFlow`? Because it needs to. Does `WebSocketData` have a uuid as well?

**Comment by mhils** [comment]
>  Or would it be possible to construct a scenario where we want to have a WebSocket without HTTP (e.g. for mocking tests)?

You cannot start a WebSocket connection without an opening HTTP handshake in practice. The HTTP parts are required to negotiate extensions. There've been some proposals do do negotiation via ALPN, but all that has been dismissed.

> What will the argument for the websocket_* hooks be? 

An HTTPFlow with a non-None `.websocket` attribute. This requires no circular links or any other complexity.
For display, we can do pretty much what you described: Check if `.websocket` is present, and if so, add a new tab next to Request/Response/Details.

> Does WebSocketData have a uuid as well?

No, not needed - it's part of the HTTPFlow.


Again, from a practical perspective, the alternatives are really quite ugly:

1.  In some ideal world we would have a WebSocketFlow class that's a subclass of HTTPFlow (with additional WebSocket-only attributes). However, we don't know initially if a HTTP Flow is going to end up as WebSocket connection, so we would need dynamically swap out a flow instance for a different kind, which is super super unexpected in a lot of ways. 
2. We could have _two_ flows (as we do right now): one for the handshake and one for the WebSocket contents. This is quite messy as well, see my previous comment: https://github.com/mitmproxy/mitmproxy/issues/4425#issuecomment-772842580. I'd like to avoid any interdependencies/linkes between flows as much as we can.

**Comment by Prinzhorn** [comment]
I'm sold
