### ISSUE TITLE
mitmdump uses an unexpectedly large amount of CPU while idle

### ISSUE THREAD

**Issue by lexelby** [mitmproxy/mitmproxy#443]
How to reproduce:

```$ mitmdump -P http://google.com -p 10001```

Then run top and see that it's using as much as 20% of a core.

`strace` yields a fast scroll of short sleeps:

```
select(0, NULL, NULL, NULL, {0, 2259})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 1000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 2000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 4000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 2301})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 1000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 2000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 4000})  = 0 (Timeout)
select(0, NULL, NULL, NULL, {0, 2401})  = 0 (Timeout)
```

`Master.tick` (in controller.py) calls `Queue.get` with a `timeout` of 0.01.  `Queue` in turn waits on a `threading.Condition` with that same timeout.  `Condition` waits in increasingly large increments starting at 500usec in an attempt to avoid making the program unresponsive (to what?  Probably KeyboardInterrupt?).  It'll wait 500usec, 1000, 2000, 4000, and then the remainder to get up to 10000usec.  End result: `select()` is called as often as 5000 times per second.  A far cry from the 100Hz that one might expect from a 0.01 timeout :)

**Comment by mhils** [comment]
Hi @lexelby,

thanks for the excellent report! Really appreciated. :smile: 
Your analysis is spot-on. I just commited a fix that mitigates this issue by setting `timeout` to 0.1. I'm not 100% happy with that, but it seems to be a good compromise that works on Linux and Windows. I now get about 1-2% CPU usage with a minor performance degradation. As soon as we move to Python 3, we should reconsider this decision - `Condition` does a single select call there. (see https://stackoverflow.com/questions/22146351/arbitrary-sleeping-in-threadings-wait-with-timeout)

**Comment by lexelby** [comment]
Oh!  I totally missed in my analysis that `_Condition.wait` will only check the semaphore between sleeps!  Suddenly your original implementation makes much more sense.  I will note that even with a high timeout, at least in python 2.7, the longest it'll sleep between checks is 0.05 seconds.  So it should still be fairly performant.

I'm glad python3 fixes this subtle gotcha, though.  I'd just sort of expect waiting on Queues/Conditions to be really computationally cheap, you know?

**Comment by mhils** [comment]
> I'd just sort of expect waiting on Queues/Conditions to be really computationally cheap, you know?

You name it. Thanks for digging into that :wink:
