### ISSUE TITLE
Display header capitalization

### ISSUE THREAD

**Issue by bayanrasooly** [mitmproxy/mitmproxy#4436]
#### Problem Description

I am trying to view the header casing made from my HTTP client. Mitmproxy displays all headers as lowercased.

#### Proposal
I would like mitmproxy to display the casing of headers as it is sent. (Authorization and not authorization)

#### Additional context
I have tested with fiddler to see that indeed my client sends headers with capital first letters but mitmproxy (ran in terminal) shows the headers as fully lowercased.

**Comment by mhils** [comment]
Which HTTP version are you using between client and mitmproxy?

**Comment by bayanrasooly** [comment]
I am using HTTP 2.

**Comment by mhils** [comment]
Yes, that explains it! 😃 

- HTTP/1 headers are case-insensitive. That means clients and servers should treat lower- or uppercase headers equally.
- HTTP/2 is a bit stricter here and mandates that clients send lower-case headers only:

  > However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed (Section 8.1.2.6).
  https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2

It looks like your client sends lowercase headers to mitmproxy (where it negotiated HTTP/2 and only lower case is permitted) and Mixed-Case headers to Fiddler (where it negotiated HTTP/1). If you disable HTTP/2 in mitmproxy (`--no-http2`), you should see capitalized headers as well, although implementations _should_ make no difference in practice.
