### ISSUE TITLE
transparent mode with custom script fails connecting to localhost

### ISSUE THREAD

**Issue by fp7** [mitmproxy/mitmproxy#4437]
#### Problem Description
When running a script that changes the host of the request and  transparent mode i can not connect to localhost

#### Steps to reproduce the behavior:
1. Use script mitm.py
```
"""Redirect HTTP requests to another server."""
from mitmproxy import http


def request(flow: http.HTTPFlow) -> None:
    flow.request.scheme = "https"
    flow.request.host = "www.google.com"
    flow.request.port = 443
```
2. `mitmproxy --mode transparent -s mitm.py`
3. `curl localhost:8080`

#### System Information
```
mitmproxy --version
Mitmproxy: 6.0.2
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.0-65-generic-x86_64-with-glibc2.29
```

**Comment by mhils** [comment]
Does this problem still persist on master? If yes, what exactly did you expect to happen, what do you see instead?

**Comment by fp7** [comment]
No, the problem is not in master. Thx.
