### ISSUE TITLE
Transparent proxy support for upstream proxies

### ISSUE THREAD

**Issue by na--** [mitmproxy/mitmproxy#444]
Is the following setup possible?

    Client <-> Transparent mimtproxy <-> Other upsteam proxies <-> HTTP/HTTPS Website

When I launch mitmproxy in transparent mode, both HTTP and HTTPS traffic is captured perfectly. However, when I try to use another http proxy from the client application, mitmproxy fails. This happens both when the final site is http and when it's https:
    
    HttpError('Invalid HTTP request form (expected: relative, got: absolute)',)

Is this supported or am I doing something wrong?

**Comment by mhils** [comment]
Hi @na--,

this is not supported out of the box at the moment, but it shouldn't be too hard to add - we recently had a thread on the mailing list discussing something similar: https://groups.google.com/forum/#!topic/mitmproxy/BjR-UR5outM (also read the further mails in the thread)

That being said, a PR adding transparent upstream mode would be welcome! Let me know if you'd be interested to add this, we're happy to help.

Cheers,
Max

**Comment by na--** [comment]
Thanks! If I can, I will give it a try this week.

**Comment by wf2004081522** [comment]
hello, I just want to ask what's going on for this thread, I want to get exactly same feature, any progress for it? I'm using 0.13.1, but it seems not support this feature yet.

**Comment by loxK** [comment]
I need it! Any alternative ?

I need

Client <-> mimtproxy on a different host <-> HTTP/HTTPS Website

I tried using IP tables DNAT to redirect request to the mitmproxy on remote host and I get "HttpError('Invalid HTTP request form (expected: absolute, got: relative)',)"

I tried using IP tables REDIRECT to a local mitmproxy in upstream mode to the remote mitmproxy and I get the same error ... 

Any workaround ?

**Comment by a-goryachev** [comment]
+1
Complex 'transparent+upstream' mode out of the box could be very useful. Especially if you want to redirect request to different regular proxy servers if HTTP header match condition.
