### ISSUE TITLE
How to use protoc for Python on manjaro

### ISSUE THREAD

**Issue by DiskGetor** [mitmproxy/mitmproxy#4440]
#### Problem Description

A clear and concise description of the problem you are trying to solve.

#### Additional context
Add any other context or screenshots about the proposal here.

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
