### ISSUE TITLE
How do i install mitmproxy-ca-cert.pem on wii u?

### ISSUE THREAD

**Issue by BluelyTASer** [mitmproxy/mitmproxy#4443]
#### Problem Description

Install mitmproxy-ca-cert.pem on wii u via FTPiiU and FileZilla

#### Proposal
Get Secret APIs on a lot of Wii U Games with it for undetected cheating.

#### Additional context
I don't know where the pem certificates are in Wii U Storage on FTPiiU and FileZilla, can you tell where is it so I can install mitmproxy-ca-cert.pem on Wii U? 🤔
![Image](https://cdn.discordapp.com/attachments/352944118864805889/810108501907996672/IMG_20210213_082040313.jpg)
![373](https://user-images.githubusercontent.com/59511669/107848802-16a05500-6dd5-11eb-9f48-24dddb9fce94.PNG)

**Comment by mhils** [comment]
I don't have a Wii U and I don't know - sorry! If you find a solution, please comment here or even better submit a PR to add it to https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually!
