### ISSUE TITLE
Error starting proxy server: OSError(99, 'Cannot assign requested address')

### ISSUE THREAD

**Issue by Stymix** [mitmproxy/mitmproxy#4453]
Hi
I'm trying to create a HTTP proxy server for playing on a video game. (Because they don't accept Socks5 proxy but only HTTP)
So I downloaded mitmproxy and used the command : 
mitmproxy --listen-host 195.x.x.x (my ip) -p 5002 --upstream-auth test:test

I used upstream-auth to create an authentification for the proxy, I don't know if that's the good way^^

But I have this error : 
Error starting proxy server: OSError(99, 'Cannot assign requested address')

I think it's because it's a virtual IP (My hosting gave me some IP)
Do you have a something to fix this ?

![Capture](https://user-images.githubusercontent.com/23586833/108090464-ed085780-707a-11eb-947c-7a58c67ee141.JPG)

here You can find one of my virtual IP (Obtained by doing ip a)

Thanks.

**Comment by r00t-** [comment]
there's surely lots of proxy server solutions more appropriate for your use-case than mitmproxy.
have you tried simply running without `--listen-host`? the default is (as with most server software) to listen on all available interfaces, which works fine for most situations.
also, `--upstream-auth` is for when mitmproxy itself is using a proxy, not for authentication of clients.

**Comment by mhils** [comment]
As @r00t- mentioned - mitmproxy is the wrong tool here.
