### ISSUE TITLE
Websocket frames not captured

### ISSUE THREAD

**Issue by finkandreas** [mitmproxy/mitmproxy#4455]
#### Problem Description
I was looking throught old issues here and to my understanding websockets should also be working to be captured with mitmproxy, but I cannot see any websocket message being captured. All I see is that the protocol upgrade and then the response body is 0bytes forever.

#### Steps to reproduce the behavior:
0. I will use chromium, but I have the same behavior with firefox.
1. Start as normal proxy with no special setup i.e. all options are set to their default values: `mitmproxy`
2. Open chromium with `chromium --proxy-server=http://localhost:8080`
3. Install mitmproxy certificate in chromium
4. Visit https://www.websocket.org/echo.html
5. Click on Connect --> This issues a 101 websocket upgrade within mitmproxy shell window
6. Click on Send 
       --> On the website the data seems to be sent correctly as I receive on the website in the log window also a reply. 
       --> In the mitmproxy shell window nothing happens. I would assume that the sent message and received response are being captured in mitmproxy.

#### System Information
```
$ mitmproxy --version
Mitmproxy: 6.0.2
Python:    3.8.7
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.10.14-gentoo-x86_64-Intel-R-_Core-TM-_i5-8250U_CPU_@_1.60GHz-with-glibc2.2.5
```

**Comment by mhils** [comment]
From https://docs.mitmproxy.org/stable/concepts-protocols/#websocket:

> mitmproxy currently does not display WebSocket messages in the console or web UI.

The progress is tracked in #1020. It should be a relatively straightforward endeavour after #4425, it just happens that noone gotten around to implement it yet. Contributions welcome!

**Comment by mhils** [comment]
I should add: you can view websocket messages in the event log, but they need to be properly integrated into the flow list.

**Comment by finkandreas** [comment]
Just for reference I would like to add that websocket message _contents_ are not logged, also not in the event log. Only the information that messages are sent/received is logged.
However your hint from the docs gave me the right idea to log the messages with the Event interface (that is absolutely amazing), and I can log with this also the _contents_:
```
from mitmproxy.websocket import WebSocketFlow
from mitmproxy.utils import human

class WsLog:
    def __init__(self, output_filepath: str) -> None:
        self._logfile = open(output_filepath, "w")

    def websocket_message(self, flow: WebSocketFlow):
        message = flow.messages[-1]
        client = human.format_address(flow.client_conn.address)
        server = human.format_address(flow.server_conn.address)
        direction = "->" if message.from_client else "<-"
        endpoint = flow.handshake_flow.request.path
        self._logfile.write(f'{message.timestamp}: {client} {direction} {server}{endpoint} >>{message.content}<<\n')
        self._logfile.flush()

addons = [
    WsLog("mitmproxy_websocket.log")
]
```
I am sure you know this trick, but I left it here for the next person, who is incapable of reading the docs in the first place.
