### ISSUE TITLE
mitmdump: temporarily running out of diskspace corrupts dumpfile

### ISSUE THREAD

**Issue by r00t-** [mitmproxy/mitmproxy#4460]
#### Problem Description
ofcourse the world would be a better place if everybody always responsibly managed their filesystem space,
but we have to face that fact that mitmdump, as a non-interactive dumping tool, is often going to be the program that fills up the last available block on a filesystem.

currently it deals with that situation very badly:
* it keeps running, and keeps *trying* to write to the file
  * which in part is good, because it will resume saving data when space becomes available again
* the last flow it tried to write is left in the file half-written and truncated, which due to the length-prefixed data format leads to the file being corrupt and not loadable with the provided tools.

due to this situation i already learned more about the file format than i ever wanted to ;)
the key to recovering data in such a corrupted file is:
```
grep -oE --binary-files=text --byte-offset '[0-9]+:7:version;'
```
(and i wrote a script that automates the process)

but it would be better to fix this in mitmdump itself.
suggestions:
* on a failed write, truncate the file back to it's previous length
* on a failed write, exit with an error
* maybe provide a tool to recover data from corrupted files

#### Steps to reproduce the behavior:
log more data than is good for you

#### System Information
any version i ever used

**Comment by mhils** [comment]
Good point - I think we should fail visibly and exit with an error on a failed write. 

Optionally we can also consider checking `shutil.disk_usage` on top and exit at 99% disk usage already, that should make recovery much easier in many cases. This is not available on all platforms, but we can just ignore the check if we don't get any stats.

**Comment by sw9719** [comment]
Is it good idea to show a warning when the filesystem is say 95% filled up?

**Comment by r00t-** [comment]
@sw9719: that might make sense for interactive usage of mitmproxy,
but for a non-interactive program like mitmdump (which this ticket explicitly mentions), a warning (most likely ending up in some logfile) is unlikely to be noticed.
(also, with today's mult-terabyte size disks, demanding 5% free space is excessive. - maybe create a metric from the rate of the free space, divided by the amount data being logged/time-unit, in relation to the time-units the process is running for? ("you've been logging for six hours, and in two more hours, available space will be exceeded") - wonder where the balance between sensible and excessively complicated lies.)

but really... the only critical part of the issue (that makes mitmdump's behaviour a bug) is that mitmdump's ignoring of the error leads to corrupt files that cannot be read back, as mentioned in the original description.
any further improvements would at best be nice-to-haves on top.

**Comment by sw9719** [comment]
Got it. For now, ill focus on exiting with an appropriate error.

**Comment by sw9719** [comment]
Created [PR](https://github.com/mitmproxy/mitmproxy/pull/4888) for this.

**Comment by r00t-** [comment]
i'm afraid what the code in #4888 does doesn't seem ready for production.
it does a fixed percentage diskspace check, which i argued against above,
and does that on every write (it seems), where it could also simply check if the write succeeds.
(fun sidenote: at that point you do know the exact amount of data to be written, and could compare that against available space.)

the root of the bug is that mitmdump will at some point call `write()`, which will return "no space left on device".
the bug is that that error return is ignored instead of being handled (typically programs print an error on exit).

**Comment by sw9719** [comment]
So If I understand correctly, Detecting failure to write to disk and exiting gracefully should work right?

**Comment by r00t-** [comment]
the baseline should be to not ignore the error and exit.
creating a warning in advance could be nice to have on top,
as also pointed out by mhils:
> Optionally we can also consider checking shutil.disk_usage on top and exit at 99% disk usage already

**Comment by mhils** [comment]
mitmproxy now at least exits on a full disk. Truncating the file back to its previous length isn't trivial unfortunately, calling `f.truncate(pos)` on a full disk just raises another `disk full` error. Not sure what's the best way to approach this as we can't easily reopen from within FlowWriter. 🙃
