### ISSUE TITLE
TLS-related errors ocurring periodically without any apparent reason

### ISSUE THREAD

**Issue by q2dg** [mitmproxy/mitmproxy#4465]
#### Problem Description
Hello. I'm running mitmproxy command in transparent mode and I've imported mitmproxy's root ca into "victim"'s Firefox.
It's all running ok but, from time to time, and without doing anything specific, some TLS-related errors are shown in mitmproxy's main screen. With "q" key I can clean these errors and keep going, but it's very ugly..

#### Steps to reproduce the behavior:
I don't do anything: simply having the victim's browser opened and Mitmproxy acting as a its transparent proxy, if waiting for some time (less than a minute, generally), these errors appears. I attach two screenshots about these errors from event log.

![errorMitmproxy](https://user-images.githubusercontent.com/7274874/108630063-51545e00-7463-11eb-8f7d-8f5c32321c87.png)

![errorMitmproxy2](https://user-images.githubusercontent.com/7274874/108630068-55807b80-7463-11eb-9e72-4704f2d0a0e3.png)

#### System Information
My mitmproxy's version is 6.0.2. My system is a Ubuntu 20.04 with kernel 5.8.0

Thanks

**Comment by mhils** [comment]
Hi @q2dg, does upgrading to master help? We have a completely new proxy core there that will be part of the next release.

**Comment by q2dg** [comment]
Yes, it helps! Screen is a lot cleaner now when there are tls-errors. 
Thanks a lot! I`ll close the issue.
