### ISSUE TITLE
how to configure mitmproxy to intercept http quest from other host

### ISSUE THREAD

**Issue by Haotian-Shi-cyber** [mitmproxy/mitmproxy#4467]
for example i have a web server running at 10.0.1.2 where mitmproxy is installed. i have a host running at 10.0.2.2 and it sends http request to web server. how can i intercept this kind of traffic?

**Comment by r00t-** [comment]
https://docs.mitmproxy.org/stable/howto-transparent/

**Comment by Haotian-Shi-cyber** [comment]
i think i did transparent proxy in web server. web is running at port 32770, i also use iptables to redirect traffic from 32770 to port 8080, but i saw nothing happened in mitmproxy flow when i refresh page like this
![image](https://user-images.githubusercontent.com/62081228/108720522-d64d7f00-7518-11eb-8fa4-68cefe50fa3e.png)
![image](https://user-images.githubusercontent.com/62081228/108720697-0ac13b00-7519-11eb-92f7-397aae35913c.png)

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
