### ISSUE TITLE
Mitmproxy - Certificate verification error-  Hostname mismatch

### ISSUE THREAD

**Issue by JacekStrzelecki** [mitmproxy/mitmproxy#4472]
Hi, 
I was trying to set up mitmproxy on Windows 10 with Chrome browser and have issues with a certificate. 
I can see traffic going through mitmproxy web interface and got certificate (mitmproxy-ca-cert.p12) imported to certificate manager to trusted root certificates authorities. However in Power Shell I encountered on such issue connected with certificate verification:

"Certificate verification error for 127.0.0.1: Hostname mismatch (errno: 62, depth: 0)
::ffff:127.0.0.1:62581: Ignoring server verification error, continuing with connection"

Can anybody help me with this issue?

**Comment by mhils** [comment]
This sounds like mitmproxy is encountering an invalid certificate when connecting upstream. mitmproxy does not use the OS certificate store, but you can configure a custom set of trusted certificates using `ssl_verify_upstream_trusted_ca` :-)
