### ISSUE TITLE
Proxy authentication available in reverse proxy mode

### ISSUE THREAD

**Issue by monelgordillo** [mitmproxy/mitmproxy#4473]
#### Problem Description

Currently, the proxy authentication feature is not available in reverse proxy mode.  Per documentation "Proxy Authentication
Asks the user for authentication before they are permitted to use the proxy. Authentication headers are stripped from the flows, so they are not passed to upstream servers. For now, only HTTP Basic authentication is supported. The proxy auth options are not compatible with the transparent, socks or reverse proxy mode."

#### Proposal
Proxy authentication for reverse proxy mode.

#### Additional context
Add any other context or screenshots about the proposal here.

**Comment by r00t-** [comment]
can you explain the use-case you see for this?

specifically, a reverse-proxy looks like a regular server to a client, so a would a client should never send `Proxy-Authorization` headers to it, even if asked to.
consider https://docs.mitmproxy.org/stable/concepts-modes/#reverse-proxy

i can  only guess that you are hoping to use mitmproxy to provide authentication for the service it's reverse-proxying?
in that case, proxy authentication is the wrong protocol to use.
it would probably be possible to write some code that has mitmproxy perform regular http authentication, if one really wanted to.

**Comment by mhils** [comment]
We do in fact support authentication in reverse proxy mode, mitmproxy automatically falls back to Basic Auth. I've updated the doc! 😃

**Comment by monelgordillo** [comment]
> We do in fact support authentication in reverse proxy mode, mitmproxy automatically falls back to Basic Auth. I've updated the doc! 😃

Thank you! I see it.
