### ISSUE TITLE
Please support Dockerimages for ARM Architecture/RaspberryPi

### ISSUE THREAD

**Issue by mwaskowski** [mitmproxy/mitmproxy#4475]
#### Problem Description

I can't run any provided Docker image from https://hub.docker.com/r/mitmproxy/mitmproxy/tags?page=1&ordering=last_updated&name=ARM  on a RPI4b 

Status: Downloaded newer image for mitmproxy/mitmproxy:latest-ARMv7
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

#### Proposal
Please release dockerimages for RaspberryPi/ARM Linux

**Comment by mhils** [comment]
This is probably more straightforward once #3712 is in.

**Comment by mhils** [comment]
We now build `linux/arm64` Docker images, see https://github.com/mitmproxy/mitmproxy/pull/4637 for details. :)
