### ISSUE TITLE
SSL handshake error with OSX binary installer

### ISSUE THREAD

**Issue by ssstofff** [mitmproxy/mitmproxy#450]
Hi guys

I installed on my Osx (Yosemite) with the binary installer, but getting those SSL handshake errors.
I deleted already once the certificates, but still the same.

How to resolve? Any extra install/tweek needed beside this binary install?

Thx! Kristof

**Comment by mhils** [comment]
Hi Kristof,

could you specify "those"?

Thanks,
Max

**Comment by ssstofff** [comment]
Ho Max, Yes, but I get a download failed (ios6 device).

**Comment by mhils** [comment]
I can perfectly install mitmproxy's CA certificate on iOS 6 by visiting mitm.it or transferring the CA to my device using other means. If you do not install the CA, you obviously get handshake errors.

Cheers,
Max

**Comment by ssstofff** [comment]
transferred the mitmproxy-ca-cert.pem via mail. working better now, see passing ssl communication. but still handshake errors, for example when using twitter app, or whatsapp

**Comment by mhils** [comment]
Twitter and WhatsApp both use certificate pinning, which we cannot work around: https://security.stackexchange.com/questions/29988/what-is-certificate-pinning

There are essentially two ways: (1) You may be able to use gotofail on iOS6 (2) if your device is rooted, https://github.com/iSECPartners/ios-ssl-kill-switch might be an option for you.

Cheers,
Max

**Comment by ssstofff** [comment]
Cool! thx a lot for your instant replies :-) Awesome insight proxy
My best, Kristof
