### ISSUE TITLE
Android 11 - KEY_USAGE_BIT_INCORRECT mitmproxy certificate

### ISSUE THREAD

**Issue by koh-osug** [mitmproxy/mitmproxy#4501]
I was trying to intercept some TLS with the modified version of the mitmproxy. I was not successful and created a [simple demo application](https://github.com/koh-osug/TestMITMProxy) executing a query with OkHttp. There seems to be an issue with the mitmproxy certificate.

The CA certificate has these key usages:

>             X509v3 Extended Key Usage: 
>                 TLS Web Server Authentication, TLS Web Client Authentication, E-mail Protection, Time Stamping, Microsoft Individual Code Signing, Microsoft Commercial Code Signing, Microsoft Trust List Signing, Microsoft Server Gated Crypto, Microsoft Encrypted File System, Netscape Server Gated Crypto
>             X509v3 Key Usage: critical
>                 Certificate Sign, CRL Sign
> 

Maybe it is also complaining about the generated server certificate. BoringSSL is failing at this line: https://github.com/google/boringssl/blob/master/ssl/ssl_cert.cc#L608

> 2021-03-12 03:02:26.785 30566-30621/com.gigsky.testmitmproxy E/com.gigsky.testmitmproxy.MainActivity: Error
>     javax.net.ssl.SSLHandshakeException: Read error: ssl=0x74b41d8058: Failure in SSL library, usually a protocol error
>     error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT (external/boringssl/src/ssl/ssl_cert.cc:610 0x740ee2505a:0x00000000)
>         at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
>         at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:919)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
>         at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
>         at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
>         at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
>         at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
>         at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
>         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
>         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
>         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
>         at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
>         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
>         at okhttp3.RealCall.execute(RealCall.java:81)
>         at com.gigsky.testmitmproxy.MainActivity.lambda$testCall$4$MainActivity(MainActivity.java:74)
>         at com.gigsky.testmitmproxy.-$$Lambda$MainActivity$bZPwyLI6MhGRb52InxteaVjycNk.run(Unknown Source:2)
>         at java.lang.Thread.run(Thread.java:923)
>      Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0x74b41d8058: Failure in SSL library, usually a protocol error
>     error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT (external/boringssl/src/ssl/ssl_cert.cc:610 0x740ee2505a:0x00000000)
>         at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
>         at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
>         	... 29 more

> Mitmproxy: 6.0.2
> Python:    3.8.5
> OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
> Platform:  Linux-5.4.0-66-generic-x86_64-with-glibc2.29

**Comment by mhils** [comment]
Yikes, that's definitely a fun one. Can you replicate this on mitmproxy master?

**Comment by mhils** [comment]
If this is still an issue on master, you can try the following: Delete your mitmproxy CA cert in ~/.mitmproxy, change all flags to True here:
https://github.com/mitmproxy/mitmproxy/blob/e40bf0251d9c31c4a22affe0837c869838b8264f/mitmproxy/certs.py#L179-L189
, restart mitmproxy to generate a new CA, install that CA, and try again.

**Comment by koh-osug** [comment]
I tried out to remove some unknowns and tested again the lastest master:

> Mitmproxy: 7.0.0.dev
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.0-67-generic-x86_64-with-glibc2.29

but it is still not working. The error is different. I have filed an issue, maybe the problem is more generic. See https://github.com/mitmproxy/mitmproxy/issues/4517

**Comment by koh-osug** [comment]
Closing this, it might be related to an error with my build environment.
