### ISSUE TITLE
HTTPS on non-standard port?

### ISSUE THREAD

**Issue by monelgordillo** [mitmproxy/mitmproxy#4503]
#### Problem Description

I'm looking at the documentation here: https://docs.mitmproxy.org/stable/concepts-modes/#reverse-proxy
I would like to use ssl on a port other than 443.  

![image](https://user-images.githubusercontent.com/36521543/111215362-14cadc80-85a1-11eb-817a-f8a87ec4342e.png)

#### Proposal
I would like to use ssl on a port other than 443.  The upstream (reverse) would be a local private site (http), but presents https://domain.io:41846.

mitmdump --set block_global=false --certs *.domain.io=/etc/letsencrypt/live/domain.io/fullchain.pem -p 41846 --mode reverse:http://127.0.0.1:52298 --proxyauth user:pass --set ssl_version_server=TLSv1 TLSv1.1 TLSv1.2

#### Additional context
Add any other context or screenshots about the proposal here.

**Comment by mhils** [comment]
mitmproxy should automatically pick up if a client connects via HTTPS, so that should just work? :) Of course it doesn't automatically send a redirect if you connect via HTTP, but you can do that in a custom addon I suppose :)
