### ISSUE TITLE
mitmproxy: Editting parameters accepting array of values is broken

### ISSUE THREAD

**Issue by greatvovan** [mitmproxy/mitmproxy#4507]
#### Steps to reproduce the behavior:
1. `mitmproxy`
2. Open Options (Shift-O) and scroll to any parameter accepting sequence of values (e.g. `server_replay`, `server_replay_ignore_content`).
3. See the problem.
  a. If the value was empty, you cannot enter anything.
  b. If there are some values (e.g. `mitmproxy --server-replay my_flow`) you can enter edit mode and successfully edit already existing values, but if you enter some new lines, when closing the window on Esc, the new lines will not transform into values, instead they will concatenate into a single string that will be stored as the last value of the sequence.

#### System Information
Mitmproxy: 6.0.2
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020

**Comment by mhils** [comment]
Editing parameters works as intended for me, but I suspect that's only because I am accustomed to some common shortcuts. Most notably, I can press `a` to add a row, and `d` to delete a row, `Enter` to edit, and `Esc` to finish editing. I think your report is very valid though - the help menu does not show up when I press `?`, so there's virtually no way to learn about this. 

Can you confirm that it "works" if you know what to do, or is there also another issue hidden here?
(to be clear again, in either case the current UX is terrible and needs to be fixed)

**Comment by greatvovan** [comment]
@mhils Indeed, adding/removing lines with the hotkeys does work.

From the UX perspective we need to make a decision here. You can either 1) post a hint on the top or bottom of the window (I don't see much point in `?` screen here), because, as you agreed, there is no way to learn this, **or** 2) we can allow only a single text input here and separate values by lines. The benefit of having rows (approach 1) is that you can have a multiline value, but I am not sure how worthy it is. At the same time this thing needs to be consistent with the web version, where at the moment you have a single text input per parameter. If you  go with approach 1, you can reuse the logic of parsing and user experience. In case of approach 2, you need to invent a web UI allowing to enter multiple values.

**Comment by mhils** [comment]
Yeah, your initial post did indeed inspire me to open #4515. :)

> we can allow only a single text input here and separate values by lines.

This editor is reused at a whole bunch of places and I'm sure we do have some instances where newlines would be somewhat realistic. More practically thinking, we may just want to have Shift+Enter as newline and Enter as complete/confirm.

**Comment by greatvovan** [comment]
Cool! Then I think the current issue can be closed, as it transforms into #4515 and a (not yet created) UI issue for sequence parameters in `mitmweb`.
