### ISSUE TITLE
Duplicate "running" event

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4511]
I might be crazy, but I couldn't find an existing issue but I swear I remember seeing this somewhere already.

#### Problem Description

```py
def running():
    print('running')
```

`mitmdump --quiet --scripts /tmp/running.py`

```
running
running
```

#### System Information

Both v6 release and latest master

```
Mitmproxy: 7.0.0.dev (+382, commit 0650f13)
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.8.0-45-generic-x86_64-with-glibc2.29
```

**Comment by mhils** [comment]
Yes, this one is super bad and just needs to be fixed. I know we have some addons in core that actually already work around this. 🙄

**Comment by Prinzhorn** [comment]
Thanks! I guess it's more complex than removing this line here? I thought that was the `ScriptLoader`s job.

https://github.com/mitmproxy/mitmproxy/blob/0650f132e9526a6ac881c2fb0cb3f53fba19ed1e/mitmproxy/master.py#L46

**Comment by mhils** [comment]
If I remember correctly the problem is we need "running" on startup (triggered by the master), and "running" when a module is live-reloaded. I haven't looked at it to deep though.

**Comment by Prinzhorn** [comment]
> If I remember correctly the problem is we need "running" on startup (triggered by the master), and "running" when a module is live-reloaded. I haven't looked at it to deep though.

Maybe we can cheat and introduce a new `reload` hook and call it a feature :smile:

**Comment by mhils** [comment]
yeah.. "feature" 😄. No, running() is good, fixing this should be doable. If you of anyone else can come up with simple modifications that work both normally and for reloads, please shoot a PR :)
