### ISSUE TITLE
Console: Add Quick Help Bar

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4515]
Some of my favorite command line tools display some sort of quick help at the bottom of the screen:

<details>
<summary>nano</summary>
<img src="https://user-images.githubusercontent.com/1019198/111744014-d841fe00-888a-11eb-9b02-bd208e2d3bef.png">
</details>
<details>
<summary>htop</summary>
<img src="https://user-images.githubusercontent.com/1019198/111744065-e55eed00-888a-11eb-8cfb-c8dd79f28bdf.png">
</details>

I feel that mitmproxy would greatly benefit from some more discoverability as well. The help menu lists a long list of keybindings, many of which just aren't too relevant when you are starting out. How would you all feel about adding a help bar similar to htop/nano? In particular, we could make that view-dependent, so that you get meaningful key shortcut help in flows and options editor as well 😃 

Maybe someone wants to come up with a first prototype? Implementation should't be too hard. You need to get some familiarity with [urwid](http://urwid.org/), and then it's probably enough to wrap the footer [here](https://github.com/mitmproxy/mitmproxy/blob/c5bd7b1ae1eb7b6280b77cab14f173d18a211062/mitmproxy/tools/console/window.py#L137) in an urwid.Pile which also displays the quick help.
I'm happy to help if you get stuck somewhere!

**Comment by alt-glitch** [comment]
@mhils: I'd like to work on this issue. Let me check urwid and window.py out :)

**Comment by greatvovan** [comment]
Additional thoughts:

1. I think it would be nice to utilize the bottom line of the TUI. Currently it is used for commands and messages, maybe we could display the Help Bar when there are no commands and messages (in all conditions when currently the line is empty). This would save one line for data and make the UI lighter (in my opinion).
2. Should we target 80 character width for terminal window? Or it is possible to put a dynamic content into the Help Bar (meaning the wider the window, the more hints we can put)?

**Comment by mhils** [comment]
@greatvovan: Good points. I think we can first start with a prototype that just appends itself at the bottom, that's easier to implement. It should be possible to get the current dimensions with urwid, at least we somehow do that to decide how to display the flow list. 😃

**Comment by aaron-tan** [comment]
Hi, I'd be happy to have a crack at this. Could anyone help point me in the right direction of which part of the code I should look into to implement this? Any pointers would be appreciated.

**Comment by mhils** [comment]
Our mitmproxy console UI lives in `mitmproxy/tools/console`. We use [urwid](http://urwid.org/) for rendering, which sometimes is a bit finicky. I think the easiest approach would be to hardcode something into https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/tools/console/statusbar.py. 😃

**Comment by aaron-tan** [comment]
@mhils Ok, thank you very much. I'll get right into it then. If I have any more questions perhaps I'll ask on slack instead.

**Comment by mhils** [comment]
@aaron-tan build a good first prototype over in #4743 that gave me some more ideas on what we need to think about. For reference, here's a screenshot of @aaron-tan's current state:

![image](https://user-images.githubusercontent.com/1019198/129904546-0e7cfa38-2b14-4290-b73e-8769148b0e85.png)

Before we talk about the actual implementation, let's talk about what we want mitmproxy to look like here. I think what becomes clear is that we need to clean up our footer, which right now is too crowded with three bars (statusbar, input prompt/alerts, help). I'll start this discussion with a relatively radical proposal on my own: How would you all feel if mitmproxy looks more like nano?

![image](https://user-images.githubusercontent.com/1019198/129907063-1c8030ae-304b-417c-9ec5-7c467857af6e.png)

The major benefit here is discoverability of important features for new users. We can put the most important keybindings right in front of their nose. We also ditch the statusbar entirely. Some parts are important and can move into the header (for example the `[2/3]` counter), others maybe just don't need to be visible at all times? Alternatively, we could also keep the bar above help: <details><summary>screenshot</summary><img src="https://user-images.githubusercontent.com/1019198/129907763-2de71651-9d2d-41b5-b7a7-ea0c12a10a5b.png"></details>

The second question is what happens when prompting. In this case we just overlay the help entirely. This even gives us an additional line to add prompt text:

![image](https://user-images.githubusercontent.com/1019198/129907581-6a98d853-6a6f-4b0f-8f54-132d8ea67237.png)

Finally, when we have alerts, we just display them above the help:

![image](https://user-images.githubusercontent.com/1019198/129907664-082ad200-96b1-4800-8761-ac729b4c9551.png)


@Prinzhorn, @Kriechi, @mitmproxy/devs, @aaron-tan: What do you think? I think this is a major part of mitmproxy's UI, my impression from playing around with this a bit is that we can make major improvements here. Critical comments welcome. 😃 

I've fiddled this with HTML at https://jsfiddle.net/kmz5qbwL/268/ if somone wants to make some further sketches. :)

**Comment by Kriechi** [comment]
Overall, I see this as an big improvement!
Since I currently don't have enough hands-on time to "experience" it, let me instead just nit-pick a few details and add ideas:
* Flow commands should be greyed out if not applicable for the currently selected flow (or can we resume an already finished flow?)
* probably a different discussion, but we have a weird mix of upper and lower case letters in these commands. If we deem them important enough to be permanently displayed, they should all also have a lower case letter (saves on key press)
* while almost obvious, how about adding the up/down-arrows to navigate the list?
* The top bar looks a bit empty right now - leaving room for alerts maybe?
* if we remove the listening config from the bottom-right corner, we should make sure it is prominently visible in either the options or help view. What does an empty flow view currently display? starting mitmproxy should have a big central info box, similar to what vim provides if started without a file.

**Comment by greatvovan** [comment]
@mhils I like the nano style and your design considerations. Overlaying when prompting and on-demand alert bar are apparently rational solutions.

We can actually combine status bar with the header line:
![image](https://user-images.githubusercontent.com/4903007/129950932-e56768d4-7605-451f-a355-628bccce7167.png)
Moreover, we can designate some fixed areas there, as it still seem to have a lot of space.

As for the help bar, I have a small suggestion to separate next key column with a minimum of two spaces:
![image](https://user-images.githubusercontent.com/4903007/129951351-ad17a0cb-a9ce-4791-a7b1-8c456389247d.png)

**Comment by greatvovan** [comment]
> Flow commands should be greyed out if not applicable

I even think that only relevant commands must be displayed, so if `Resume` is not applicable it must disappear (probably providing space for other relevant commands).

> how about adding the up/down-arrows to navigate the list?

I would save the precious space for less obvious things.

> The top bar looks a bit empty right now - leaving room for alerts maybe?

I like the idea, I even think it can be more radical: we can **convert** the top bar into alert bar for a while. What is the logic for alert messages now? Do they stay on the screen for a certain time? We can keep the same approach, or convert it back to the normal state once a key is pressed.

**Comment by Kriechi** [comment]
> I even think that only relevant commands must be displayed, so if `Resume` is not applicable it must disappear (probably providing space for other relevant commands).

I think there is a balance to be found. Having the same items at all times (but some disabled) provides two things:
* visual stability while navigating - nothing jumps around or suddenly changes
* discoverability of frequently used / important commands

The bigger question is though, which terminal size do we assume to estimate how many command we put there? Or do we want to do a graceful degradation approach where we simply chop off the right-most commands if the don't fit? Assuming we order them left-to-right about their importance / usefulness. I think @mhils' mocks already have a good set of commands.

**Comment by greatvovan** [comment]
> we simply chop off the right-most commands if the don't fit

I think it is a good option.

**Comment by mhils** [comment]
> if we remove the listening config from the bottom-right corner, we should make sure it is prominently visible in either the options or help view. What does an empty flow view currently display? starting mitmproxy should have a big central info box, similar to what vim provides if started without a file.

Yes, I agree. For now we can move them into the flow list header as @greatvovan proposed, but mid-term we want the info box you described. But let's keep that discussion out of here. :)

> The bigger question is though, which terminal size do we assume to estimate how many command we put there?

Let's go with chopping off, that's simple to implement and nano/htop/... do it as well.

> The top bar looks a bit empty right now - leaving room for alerts maybe?

Alerts are usually quite a bit of text, so they need to overlay a component entirely (in that case I would suggest the two help rows) or be squeezed in on-demand above the help rows.

Let's move the `[2/3]` counter thingy as well as the listen port info to the flow list top bar as @greatvovan suggested. 

> I even think that only relevant commands must be displayed, so if Resume is not applicable it must disappear (probably providing space for other relevant commands).

Either disappear as the last-in-row item or disabled, I have no particular preference here. But this brings up a more general point: We need to vary the help rows depending on the currently active view. e.g. display `e Edit Flow` when a flow is selected, and so on.

**Comment by aaron-tan** [comment]
I think also to provide users some flexibility we could implement like a toggle for the quick help feature particularly for experienced users that don't need to be handheld. I believe nano does this with their `--nohelp` flag where it doesn't show the two help lines. But that might be out of scope for now, it could be something to look into in the future.

**Comment by Prinzhorn** [comment]
> I think there is a balance to be found. Having the same items at all times (but some disabled) provides two things:

I agree with @Kriechi, from a ux point you don't want items to jump around

> I would save the precious space for less obvious things.

If we chop things off at the right we can just keep going and order by importance / relevance. I can't seem to make nano stop even with two 2k monitors :smile: 

![Selection_959](https://user-images.githubusercontent.com/679144/130428300-75a3584c-a559-455f-abcd-f792169438bc.png)

**Comment by koknaroglu** [comment]
Hello, the functionality of the help bar works fine, but I am having trouble adding the markup information to the header, how should I proceed?
![Ekran Alıntısı11](https://user-images.githubusercontent.com/56592714/148217096-3ae58182-02b7-4f46-bd8c-7b6e9d4890db.PNG)

**Comment by koknaroglu** [comment]
> @koknaroglu could you open a PR that shows your changes? I'm not sure what you mean by markup information :)

https://github.com/mitmproxy/mitmproxy/pull/5039

**Comment by mhils** [comment]
Thanks @fedosgad! 🍰
