### ISSUE TITLE
mitmproxy certificate is not accepted by curl RSA_padding_check_PKCS1_type_1:invalid padding

### ISSUE THREAD

**Issue by koh-osug** [mitmproxy/mitmproxy#4517]
#### Problem Description

The mitmproxy certificate is not accepted by curl (I also tried Firefox) with error

     curl: (35) error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding

#### Steps to reproduce the behavior:
1.  Start mitmproy: `mitmproxy -v -p 5678`
2. Start curl: `curl -x localhost:5678 https://www.google.com -v --cacert ~/.mitmproxy/mitmproxy-ca-cert.pem --tlsv1.2 --tls-max 1.2` (__NOTE:__ I was trying TLS v1.3 but this was also not working)

> *   Trying 127.0.0.1:5678...
> * TCP_NODELAY set
> * Connected to localhost (127.0.0.1) port 5678 (#0)
> * allocate connect buffer!
> * Establish HTTP proxy tunnel to www.google.com:443
> > CONNECT www.google.com:443 HTTP/1.1
> > Host: www.google.com:443
> > User-Agent: curl/7.68.0
> > Proxy-Connection: Keep-Alive
> > 
> < HTTP/1.1 200 Connection established
> < 
> * Proxy replied 200 to CONNECT request
> * CONNECT phase completed!
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /home/widerstand/.mitmproxy/mitmproxy-ca-cert.pem
>   CApath: /etc/ssl/certs
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * CONNECT phase completed!
> * CONNECT phase completed!
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (OUT), TLS alert, decrypt error (563):
> * error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
> * Closing connection 0
> curl: (35) error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
> 

#### System Information

Mitmproxy: 7.0.0.dev
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.0-67-generic-x86_64-with-glibc2.29

**Comment by mhils** [comment]
That works completely fine for me, both locally and using the Linux binaries from https://mitmproxy.org/downloads/#branches/master/. Are you using something other than the default CA generated by mitmproxy?

**Comment by mhils** [comment]
Also I should add: I can intercept my Pixel 3 with Android 11 just fine.

**Comment by koh-osug** [comment]
Indeed, after a fresh checkout curl works and also Chrome in a Pixel 3a XL with Chrome. I have to analyze what is causing the issue in the other checked out repository. I switched between the master and a different branch, maybe something was left over from the other branch to cause this error.

**Comment by koh-osug** [comment]
The differences I see are that I have opened the other repository with PyCharm which was creating a virtual environment. Also I was not cleaning the build directory, maybe `pip3 install .` is not smart enough to rebuild it and detect all changes. So, maybe this is just an build or python version issue. I will also close the other one.

**Comment by recolic** [comment]
I'm also experiencing the same error, on archlinux. 

I'm using `pacman -S mitmproxy` to install mitmproxy, and using `sudo trust anchor --store mitmproxy-ca-cert.cer` to install the CA cert.

**Comment by tonypony220** [comment]
in my case i isntalled cert generated for `root` not for `mitmproxyuser`
