### ISSUE TITLE
Forking / cloning / ad-hoc replay of requests

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4518]
I mentioned this in #4504

#### Problem Description

For finding certain types of vulnerabilities it is useful to automatically transparently make multiple slightly different versions of the same request. For example to find an IDOR vulnerability you browse the website with one session. Then you duplicate all requests that contain a certain uid (e.g. a document) that belongs to your session with the uid of a different account. If you hit a 200 status that's usually pretty nice. Another type of vulnerability this can help find are authentication issues. So you browse the website with a privileged session and automatically make a second request with a different session (e.g. replace the cookie header). There's for example a Burp add-on that allow exactly that https://github.com/nccgroup/AutoRepeater

#### Proposal

Inside the `request` event I want to `clone = flow.request.clone()`, then update `clone` and inject it / send a new request. This request will never reach an actual client, but it should also fire `response` event etc. But it has `flow.request.Source == MITMPROXY` or similar. You can create as many clones as you want and also clone the clones of course.

#### Alternatives

I guess you could already abuse the replay API inside the `request` event? Maybe this feature is already possible, but I think the different use-case justifies a proper API and also a different `flow.request.Source` than replays. Do replays even appear in the mitmproxy ui?

**Comment by mhils** [comment]
You are aware of https://github.com/mitmproxy/mitmproxy/blob/master/examples/addons/duplicate-modify-replay.py?

**Comment by Prinzhorn** [comment]
Nice, I guess I only know half of what mitmproxy is capable of. Thanks for pointing me in the right direction, I should've found that myself :wink:
