### ISSUE TITLE
Running mitmproxy on virtualboxed ubuntu-14.04.1-server-i386. 

### ISSUE THREAD

**Issue by megazhuk** [mitmproxy/mitmproxy#452]
mitmproxy runned by command: mitmproxy -T --host
on any connection to proxy host they throwing:
![image](https://cloud.githubusercontent.com/assets/1349939/5809543/b5c4f582-a04a-11e4-8582-ebf7fbb39f3e.png)
Exception in thread SlaveThread (0.0.0.0:8080):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/controller.py", line 77, in run
    self.server.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 488, in serve_forever
    t.start()
  File "/usr/lib/python2.7/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

If i try to do connection from Firefox:
![image](https://cloud.githubusercontent.com/assets/1349939/5809573/09dadbfa-a04b-11e4-9acc-36eb5da17007.png)
HttpError('Invalid HTTP request form (expected: relative, got: absolute)',) 

After crashed mitmproxy on execute: sudo netstat -ntap
i received (first section before mitmproxy, second after):
![image](https://cloud.githubusercontent.com/assets/1349939/5809624/a8c10262-a04b-11e4-9406-6fdc0faffa83.png)

As a result, no one successfully connection..

**Comment by mhils** [comment]
Hi there,

not sure where your thread error comes from, but the main problem I'm seeing is that you should not start mitmproxy in transparent mode if you configure your browser manually (see http://mitmproxy.org/doc/modes.html). If you leave out the -T switch, mitmprox should work.

Cheers,
Max

**Comment by tosiara** [comment]
Yeah, I confirm that if you start `mitmproxy` with "-T" switch and try to access it as an HTTP proxy - you will get that error: "error: can't start new thread"

**Comment by mhils** [comment]
This seems to be the same issue as #383 - we run in an infinite loop if a transparent mitmproxy instance receives regular traffic (the destination resolves to mitmproxy itself and we get infinite recursive connects). Will be mitigated in the next version - in the meantime, please remove `-T` if you use mitmproxy explicitly (see doc linked above).

**Comment by sethc23** [comment]
I ran into a similar issue that resulted in infinite recursion.  [This solution](http://serverfault.com/questions/662393/restrict-outgoing-network-traffic-by-domain-name-linux#answer-662394), with a couple tweaks, work well for me.
* `sudo useradd --create-home --shell /bin/bash --user-group mitmproxy`
* `id mitmproxy` 	# Noted the uid/gid, 1003 for me
* `sudo iptables -t nat -I OUTPUT 1 -o eth0 -m owner \! --gid-owner 1003 -p tcp --dport 80 -j REDIRECT --to-port 10052`
* `sudo -u mitmproxy mitmproxy --transparent --port 10052 --eventlog --intercept '.*'`
