### ISSUE TITLE
Using 3rd party VPN with mitmproxy

### ISSUE THREAD

**Issue by 74staz** [mitmproxy/mitmproxy#4524]
Hello, I have been trying to use mitmproxy to log requests from an app which is blocked in my country and for that I have to use a VPN to open i-e Windscribe, when I have mitm proxy enabled and VPN side by side, I cant log requests. Can someone help me on this. Thanks.

**Comment by mhils** [comment]
This needs way more details, how are we supposed to help you?

**Comment by 74staz** [comment]
> This needs way more details, how are we supposed to help you?

Okay so basically the app I am trying to record request from is banned in my country so I always use some VPN to load it. Now with mitmproxy, whenever I turn on the VPN, the requests are not recorded. Is there any way to use the VPN and log requests with mitmproxy?

**Comment by mhils** [comment]
Thanks for getting in touch. We're generally happy to help out, but can I please ask you to use [StackOverflow](https://stackoverflow.com/questions/tagged/mitmproxy) for all support and how-to questions? You can post the link to your question here so that people can follow up.

Thanks!
