### ISSUE TITLE
Support IRC protocol

### ISSUE THREAD

**Issue by ringeringeraja** [mitmproxy/mitmproxy#4526]
#### Problem Description
It's currently impossible to proxy IRC connections through mitmproxy.

#### Proposal
To support IRC proxying.

#### Additional context
![image](https://user-images.githubusercontent.com/80406377/112655340-a8649e80-8e26-11eb-8474-3a8ff18ca93b.png)

**Comment by Prinzhorn** [comment]
Have you looked into the `rawtcp` option?

**Comment by Kriechi** [comment]
Native support for IRC is out of scope for mitmproxy at the moment.
You can use rawtcp to transparently connect to IRC - but there is no deeper protocol support in mitmproxy right now.

**Comment by mhils** [comment]
To clarify: Starting with mitmproxy 7, rawtcp will be enabled by default, so it should "just work" over SOCKS/regular HTTP or as a reverse proxy. :)

**Comment by Nerixyz** [comment]
_For future visitors:_

You can add the IRC server host to `tcp_hosts` to make sure it doesn't get interpreted as HTTP - for example:

```yaml
tcp_hosts:
  - 'irc.chat.twitch.tv'
```
