### ISSUE TITLE
Certificate verification error for None: self signed certificate (errno: 18, depth: 0)

### ISSUE THREAD

**Issue by r4t31** [mitmproxy/mitmproxy#4536]
#### Problem Description
I can not connect to the TLS server through mitmproxy. Direct connection works normally. 

#### Steps to reproduce the behavior:
1. mitmweb.exe --mode socks5
error:
```
127.0.0.1:2675: clientdisconnect
127.0.0.1:2679: Cannot establish TLS with 192.168.0.1:443 (sni: None): TlsException('Cannot validate certificate hostname without SNI')
127.0.0.1:2679: clientdisconnect
```
2.  mitmweb.exe --mode socks5 --ssl-insecure
error:
```
127.0.0.1:3755: clientconnect
127.0.0.1:3751: Client Handshake failed. The client may not trust the proxy's certificate for ('192.168.0.1', 443).
127.0.0.1:3751: clientdisconnect
::ffff:127.0.0.1:3755: Certificate verification error for None: self signed certificate (errno: 18, depth: 0)
::ffff:127.0.0.1:3755: Ignoring server verification error, continuing with connection
127.0.0.1:3759: clientconnect
127.0.0.1:3755: Client Handshake failed. The client may not trust the proxy's certificate for ('192.168.0.1', 443).
127.0.0.1:3755: clientdisconnect
```
#### System Information
mitmproxy sertificate already added to trusted in windows. 
mitmweb.exe --version
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Windows-10-10.0.19041-SP0

**Comment by mhils** [comment]
It looks there are two factors coming into play here:

1. The server you're connecting to is using a self-signed certificate. That's not trusted by default, but `--ssl-insecure` skips mitmproxy's certificate verification. You could also use `ssl_verify_upstream_trusted_ca` if you need a secure long-term solution.
2. The client you are using seems to pin the server's certificate and does not use the Windows certificate store. You either need to obtain a copy of the server's certificate and then use mitmproxy's `certs` option, or disable the verification in the client (as a last resort, using reverse engineering).

Does that clear things up? There's unfortunately not much mitmproxy can do here.

**Comment by r4t31** [comment]
> It looks there are two factors coming into play here:
> 
> 1. The server you're connecting to is using a self-signed certificate. That's not trusted by default, but `--ssl-insecure` skips mitmproxy's certificate verification. You could also use `ssl_verify_upstream_trusted_ca` if you need a secure long-term solution.
> 2. The client you are using seems to pin the server's certificate and does not use the Windows certificate store. You either need to obtain a copy of the server's certificate and then use mitmproxy's `certs` option, or disable the verification in the client (as a last resort, using reverse engineering).
> 
> Does that clear things up? There's unfortunately not much mitmproxy can do here.

Now it starts to be a little bit more clear. Thanks. 
Can you please explain, how mitmproxy understand the destination IP address in transparent mode? 
For example, here writed that for Squid uses HTTP header (https://serverfault.com/questions/688477/how-does-squid-understand-the-destination-ip-address-in-transparent-mode).
