### ISSUE TITLE
pip install mitmproxy fails (SyntaxError)

### ISSUE THREAD

**Issue by leandroarndt** [mitmproxy/mitmproxy#454]
Command exits with the following dump:

    Downloading/unpacking mitmproxy                                                 
      Running setup.py egg_info for package mitmproxy                               
        Traceback (most recent call last):
          File "<string>", line 16, in <module>
          File "/tmp/pip-build-root/mitmproxy/setup.py", line 19
            "netlib>=%s, <%s" % (version.MINORVERSION, version.NEXT_MINORVERSION),
                                                                                 ^
        SyntaxError: invalid syntax
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
     
      File "<string>", line 16, in <module>
     
      File "/tmp/pip-build-root/mitmproxy/setup.py", line 19
     
        "netlib>=%s, <%s" % (version.MINORVERSION, version.NEXT_MINORVERSION),
     
                                                                             ^
     
    SyntaxError: invalid syntax
     
    ----------------------------------------
    Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-root
    /mitmproxy
    Storing complete log in /root/.pip/pip.log
    
This is inside the _deps_ dictionary (line 18) at setup.py. If I try to change it to a tuple or list (thus correcting syntax), I get an AttributeError (trying to access _deps.update_). The same happens at line 27, with another dict.

**Comment by mhils** [comment]
Hi there,

this looks like you're using Python 2.6. Could you upgrade to 2.7 please?

Cheers,
Max

**Comment by leandroarndt** [comment]
I'll try it. Thought pip checked this before trying to run the script.
