### ISSUE TITLE
Avira detects mitmdump

### ISSUE THREAD

**Issue by User5959** [mitmproxy/mitmproxy#4545]
Avira is detecting mitmdump as malware: "HEUR/AGEN.1140494" please fix this
![mitmdump false positive](https://user-images.githubusercontent.com/71342529/113656560-abb02380-968b-11eb-8168-18f462b06697.JPG)

**Comment by Prinzhorn** [comment]
Please provide the output of `mitmdump.exe --version`

**Comment by Prinzhorn** [comment]
And the full "threat name" and all information that Avira gives you

**Comment by User5959** [comment]
> 
> 
> Please provide the output of `mitmdump.exe --version`
I can't do that, but mitmproxy version was "6.0.2

**Comment by mhils** [comment]
Thanks again @User5959! This false positive seems to have been resolved: https://www.virustotal.com/gui/file/88c1ea103719ca6127ccfb8f3b23c1e2c54e3ecb8858ff9b301d57017e85dc2d/detection
