### ISSUE TITLE
Simplify Server.sni

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4547]
#### Problem Description

When a property has a mix of unrelated types it takes me more time than it should take to wrap my head around. To me this always smells like something could be simplified, but I guess that's something I have to get used to with Python? I'm talking about `Server.sni: Union[str, Literal[True], NoneType] = True` vs `Client.sni: Optional[str] = None`

> The Server Name Indication (SNI) sent in the ClientHello. For server connections, this value may also be set to True, which means "use Server.address".

Is this something that could be hidden under the hood? As a user I don't care. I just want the string that was used for sni. I don't want to replicate internal logic inside my addon.

#### Proposal

When SNI is used just duplicate `address[0]` into `sni`.

**Comment by mhils** [comment]
server.sni will be set to server.address during the handshake, it will only be set to True before that. Does that help?

**Comment by Prinzhorn** [comment]
> Does that help?

Somewhat I guess. So that means in later hooks (e.g. `server_disconnected`) it is guaranteed to be either a string or `None`? I've seen this pattern more than once in mitmproxy, where a property is used to either hold a value or a sort of flag that like has a side effect on the meaning later in some internal parts of the code. I find it confusing. Could there be a (private?) boolean flag that does that job and `sni` is kept clean?

Is it correct that both of the current `tls_` hooks are too early for that? So `sni` could still be `True`? Or does SNI happen between `tls_start` and `tls_clienthello`?

Wait a second, isn't `tls_start` ambiguous? Is it the TLS start between client<->mitmproxy or mitmproxy<->server? Or does it fire for both? Since `TlsStartData` holds a generic `connection.Connection` I assume both? Maybe there needs to be `tls_clientstart` and `tls_serverstart`?

**Comment by Prinzhorn** [comment]
Nice, thanks for the details. I'm interested in making the PRs, but not right now. I'll self-assign the issue once I do to avoid conflicts.

**Comment by Prinzhorn** [comment]
@mhils thanks! I've had this tab open for a couple of days now but I'm having a hard time getting anything done...but I _do_ want to look into separating tls_start into two event. So bear with me.
