### ISSUE TITLE
Improve Certificate Fingerprint Readability

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4549]
With v6 I'm currently storing both `cert.digest('sha256')` and `cert.digest('sha1')` (Chrome and Firefox list both in the cert details UI). In v7 `Cert` only has `fingerprint` hardwired to sha256. I'm not sure what the best approach is to restore the original functionality?

**Comment by mhils** [comment]
If you absolutely need SHA256, you can handwire it yourself: https://github.com/mitmproxy/mitmproxy/blob/438567f58c86ab13d721bd34f039fbddea52906f/mitmproxy/certs.py#L77-L78

What's the use-case to keep (insecure) SHA1 around?

**Comment by Prinzhorn** [comment]
> What's the use-case to keep (insecure) SHA1 around?

Replicating the Firefox/Chrome UI for ux, because people might be used to it or compare them with another using their eyes.

The format also changed from v6 to v7 (in the mitmproxy UI)

```
v6: 84:63:B3:A9:29:12:CC:FD:1D:31:47:05:98:9B:EC:13:99:37:D0:D7
v7: 0ae384bfd4dde9d13e50c5857c05a442c93f8e01445ee4b34540d22bd1e37f1b
Chrome: 0A E3 84 BF D4 DD E9 D1 3E 50 C5 85 7C 05 A4 42 C9 3F 8E 01 44 5E E4 B3 45 40 D2 2B D1 E3 7F 1B
```

I think it's much better to read with separators.

**Comment by mhils** [comment]
> Replicating the Firefox/Chrome UI for ux, because people might be used to it or compare them with another using their eyes.

 Unless there's evidence of popular clients only displaying SHA1 hashes, let's be good citizens and keep them out. :-) If you really have a need for SHA1, you can always access `._cert`.

-----------------

Format: I agree, it's more readable with spaces. Fixing this is quite straightforward and would be an excellent first PR for a new contributor. 😃 The relevant code is here: 

https://github.com/mitmproxy/mitmproxy/blob/438567f58c86ab13d721bd34f039fbddea52906f/mitmproxy/tools/console/flowdetailview.py#L58-L69

**Comment by Prinzhorn** [comment]
> If you really have a need for SHA1, you can always access `._cert`.

I guess my issue was

1. I thought in Python when it starts with an underscore it's not accessible from the outside
2. `x509` in v6 came from the OpenSSL package and in v7 `_cert` comes from cryptography, that's why I can't find the same nice API

**Comment by mhils** [comment]
> I thought in Python when it starts with an underscore it's not accessible from the outside

`_` indicates it's not the intended public API, but you sure can access it if you know what you are doing. There's really nothing wrong with it, especially if you control the mitmproxy version. 😃 

```python
from cryptography.hazmat.primitives import hashes

cert._cert.fingerprint(hashes.SHA1())
```

should work just fine. :)

**Comment by Prinzhorn** [comment]
> ```python
> cert._cert.fingerprint(hashes.SHA1())
> ```

```py
server.certificate_list[0]._cert.fingerprint(hashes.SHA1()).hex(':').upper()
```

:tada:
