### ISSUE TITLE
Add support for HSM/Smart Card/TPM ...

### ISSUE THREAD

**Issue by WoodsSooperDooperShop** [mitmproxy/mitmproxy#4550]
#### Problem Description

I think mitmproxy is mostly used for analysis of single websites/apps ... and not on  a broader scale like TLS interception for all traffic in an enterprise environment or from a complete device.  Though it would be a valuable alternative for current open source options (which mostly is squid)
In this case you also need to think more about the security of the proxy software itself.
In contrast to some ngfw solution, mitmproxy is dedicated to a single function and it is open source. Which I consider as an advantage.
The most valuable part is the private key of the proxy. When it gets stolen an attacker could read/modify traffic. Due to their capabilities and position in the network such proxies are a preferred target (see for example: https://www.schneier.com/blog/archives/2019/11/the_nsa_warns_o.html )
Ideally the key could be saved on some hardware token so it can only be stolen by physical access.
Various options exist for storing such keys exist like commercial HSMs, yubikey, nitrokey, (v)TPMs ...

#### Proposal

Does mitmproxy work in combination with a hardware token?
If not could this be added as an optional function?
A hardware token would be preferable like a YubiKey or Nitrokey. Alternatively a software solution like a virtual TPM.

**Comment by mhils** [comment]
> broader scale like TLS interception for all traffic in an enterprise environment

We think that broader scale TLS interception is usually wrong and misguided, and thus it's explicitly a non-goal for the project.

> Does mitmproxy work in combination with a hardware token?

If you have something that works with pyOpenSSL/cryptography and know what you are doing, you can probably wire up things in https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/addons/tlsconfig.py. I don't really have any other guidance.

As you mentioned, this really is mostly useful for broader scale interception. Which again is nothing we intend to support, so I'm closing this here. :)
