### ISSUE TITLE
Support pkcs11

### ISSUE THREAD

**Issue by johschmitz** [mitmproxy/mitmproxy#4553]
#### Problem Description

Currently usage of mitmproxy with a smartcard stored SSL/TLS client certificate is not possible.

#### Proposal
This feature request is a suggestion to support a pkcs11 provider in order to allow usage of the proxy with certificates stored on smartcards.

#### Alternatives
None.

#### Additional context
https://en.wikipedia.org/wiki/PKCS_11
https://github.com/OpenSC/OpenSC/wiki

**Comment by mhils** [comment]
I think I've briefly explained that in #4550 to you a few minutes ago... 😉

mitmproxy uses pyOpenSSL/cryptography under the hood, which currently don't support PKCS11. Adding PKCS11 support to mitmproxy - even if it were supported by pyOpenSSL - would be a significant effort and maintenance burden while not being useful for almost all users. If you have a specific need, you can probably patch addons/tlsconfig.py to get things working, but we won't be supporting that anytime soon. :)

**Comment by johschmitz** [comment]
@mhils #4550 was a request from a different person, not sure why you assume that I am the same guy?

Nevertheless, of course, it is up to the people who put in their time to decide which features will be implemented.
