### ISSUE TITLE
v7: Pass HTTPFlow to WebSocketData

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#4569]
#### Problem Description

There are at least two APIs that would benefit from having access to the flow and maybe more come up for a nicer ux:

1. `flow.websocket.inject()`
2. `flow.websocket.url` and friends (originally HTTPFlow would change scheme to `wss://` which I don't like at all. We could expose some of these things as getter properties on `websocketdata` so it's nicer to use)

#### Proposal

Have a `WebSocketData.__flow` that points back to the flow (it's only used internally and you cannot access it from the outside). I don't know about the implications of a circular reference here. Maybe this would benefit from weak references as well?

Hm, I guess that would cause trouble when loading saved flows? Or could the de-serialization put that back together? There are probably more problems I'm not aware of.

**Comment by mhils** [comment]
Didn't we discuss this somewhere else already? 🤔 

> Have a WebSocketData.__flow that points back to the flow (it's only used internally and you cannot access it from the outside).

I'd much rather have a `HTTPFlow.inject_websocket_message` API instead of having to deal with backreferences. Of course you can make backreferences work, but IMO it's a lot of complexity (you already mentioned serialization...) for very little benefit.

**Comment by Prinzhorn** [comment]
> Didn't we discuss this somewhere else already? thinking

I think it was spread across multiple things and inside PR comments or something. I wanted to make sure we're on the same page here.


> I'd much rather have a `HTTPFlow.inject_websocket_message` API instead of having to deal with backreferences

OK fair enough
