### ISSUE TITLE
mitmproxy not working with android emulator

### ISSUE THREAD

**Issue by AnnabelleMA** [mitmproxy/mitmproxy#457]
Hi,
I am trying to use mitmproxy with android emulator. But mitmproxy shows nothing. Here are the steps I followed:
1. Installed miltmproxy in laptop1
2. Enabled IP forwarding and port redirection in laptop 1 (redirected port 80 and 443 to 8080)
3. Installed miltmproxy CA certificate in the Android emulator running in laptop 2
4. Set laptop 1 as proxy in Android emulator (just enter the ip address of laptop 1, did not enter any port)
Then I tried to run mitmproxy and mitmproxy -T --host. But nothing works.
Anyone can tell me what's wrong?

Thanks

**Comment by mhils** [comment]
Hi there,

is there a reason why you use transparent mode while explicitly configuring a proxy? http://mitmproxy.org/doc/modes.html should clear some things up for you.

Cheers,
Max
