### ISSUE TITLE
mitmproxy sending ip.addr as CN in server hello for certain user-agents

### ISSUE THREAD

**Issue by michael-clarke** [mitmproxy/mitmproxy#4570]
#### Problem Description
When in transparent mode, for certain headless devices, mitmproxy is sending backing certificate CN being the ip address rather than the original request fqdn.  
For browser's it is returning a correct certificate with the CN being the original request fqdn.

In this request the user-agent is wget

User-Agent:  Wget/1.10.2 (Red Hat modified)                                                                                                                                  
Accept:      */*                                                                                                                                                             
Host:        some.domain.com                                                                                                                                        
Connection:  Keep-Alive  

See attached pcap to see this behaviour.

[wget-redhat.pcapng.zip](https://github.com/mitmproxy/mitmproxy/files/6349407/wget-redhat.pcapng.zip)

#### Steps to reproduce the behavior:
1. Send wget request using above user-agent
2. capture client/server hello

#### System Information
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.0-72-generic-x86_64-with-glibc2.31

**Comment by mhils** [comment]
Thanks for the super clear PCAP! Do you see anything interesting in mitmproxy's event log, perhaps some "failed to parse clienthello"-style errors?

**Comment by mhils** [comment]
After a quick inspection of the PCAP it looks like we are parsing this properly. Could I ask you to upgrade to our lastet development release and try again? The relevant bits have changed there, and that may just fix your issue.

https://mitmproxy.org/downloads/#branches/main/

**Comment by michael-clarke** [comment]
Tried the latest dev release and I don't see this now.  Thanks.
