### ISSUE TITLE
mitmproxy including it's own self-signed cert in the cert chain in server hello during https

### ISSUE THREAD

**Issue by michael-clarke** [mitmproxy/mitmproxy#4571]
#### Problem Description
For https connections, generally the server should not have to include the RootCA cert in the certificate chain in the server hello payload.  Mitmproxy is including it's own self-signed in the server hello and applications are rightly throwing an error.

Example below.

$ curl https://www.bbc.co.uk
curl: (60) SSL certificate problem: self signed certificate in certificate chain

The correct thing to do is to load this self-signed into the trusted store of the OS/browser.  During the server hello the self-signed need not be sent since the client (should) already have this in their trust store.

#### Steps to reproduce the behavior:
1. Use mitmproxy and connect to any https site.
2. Capture the client and server hello.
3. The mitmproxy self-signed cert can be seen in the server hello

#### System Information
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.0-72-generic-x86_64-with-glibc2.31

**Comment by mhils** [comment]
> Mitmproxy is including it's own self-signed in the server hello 

This is correct.

> and applications are rightly throwing an error.

I don't agree with the "rightly" here:


##### [RFC 5246 - TLS 1.2](https://tools.ietf.org/html/rfc5246#section-7.4.2)

>   This is a sequence (chain) of certificates.  The sender's
      certificate MUST come first in the list.  Each following
      certificate MUST directly certify the one preceding it.  Because
      certificate validation requires that root keys be distributed
      independently, **the self-signed certificate that specifies the root
      certificate authority MAY be omitted from the chain,** under the
      assumption that the remote end must already possess it in order to
      validate it in any case.

##### [RFC 8446 - TLS 1.3](https://tools.ietf.org/html/rfc8446#section-4.4.2)

>    Note: Prior to TLS 1.3, "certificate_list" ordering required each
   certificate to certify the one immediately preceding it; however,
   some implementations allowed some flexibility.  Servers sometimes
   send both a current and deprecated intermediate for transitional
   purposes, and others are simply configured incorrectly, but these
   cases can nonetheless be validated properly.  For maximum
   compatibility, all implementations SHOULD be prepared to handle
   potentially extraneous certificates and arbitrary orderings from any
   TLS version, with the exception of the end-entity certificate which
   MUST be first.

-------

> $ curl https://www.bbc.co.uk
curl: (60) SSL certificate problem: self signed certificate in certificate chain

It looks like your curl installation is just not trusting mitmproxy's CA in general here. It doesn't really matter if we include the root cert in the chain or not.

**Comment by michael-clarke** [comment]
Thanks.  I added the mitmproxy cert to the system store but you are correct in that curl seems to use something different.
I tried curl with the --cacert option and it loaded fine.
Is there a way to tell mitmproxy to not include it's own self-signed in the chain?

**Comment by mhils** [comment]
> Is there a way to tell mitmproxy to not include it's own self-signed in the chain?

I don't think there is at the moment. You can certainly patch out `CertStore.default_chain_file` which should fix this, but what is your use case? I primarily see this useful as a means to obfuscate that mitmproxy is used, which is nothing we want to encourage.

**Comment by michael-clarke** [comment]
I tried the latest dev release and I don't see this behaviour now.  Thanks
