### ISSUE TITLE
All requests become very slow after using mitmdump with defalut settings

### ISSUE THREAD

**Issue by ln90s** [mitmproxy/mitmproxy#4574]
#### Problem Description
Sorry, I am not very familiar with Python. When I use mitmdump to proxy my Android application, all requests become very slow (Android APP is chrome), I am sure that my network is well, because after I cancel the proxy The request became very fast. I did not modify any settings, only ran mitmdump. 
I tried to use the script to process the request separately, but it was also very slow.
Please help me .
#### Steps to reproduce the behavior:
1. modify android phone proxy to ip:8080
2. run mitmdump
3. run chrome at android phone 

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 6.0.2
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Windows-10-10.0.19041-SP0
Android Version : 11.0

Thanks a lot !

**Comment by ln90s** [comment]
No offense, I am very interested in the Mitmdump project and admire you, but when I use Fiddler, the request is very fast, I think Mitmdump can also achieve the same effect, please guide me how to operate

**Comment by mhils** [comment]
Can you upgrade to the latest development releases and try again please?
https://mitmproxy.org/downloads/#branches/main/

**Comment by ln90s** [comment]
Thanks for your reply and help, I downloaded "mitmproxy-main-windows.zip" from the link you provided and ran it, but the APP request in my Android phone is still very slow. 

> Can you upgrade to the latest development releases and try again please?
> https://mitmproxy.org/downloads/#branches/main/

**Comment by ln90s** [comment]
![image](https://user-images.githubusercontent.com/46208431/115808468-21064d00-a41d-11eb-9616-ae7d9ef08af9.png)

I uploaded a picture of the request situation when using mitmproxy.exe as a proxy. You can see that the request time for qq.com is 25s. Because I am in China, the request time is basically less than 1s without using a proxy.

Maybe I didn't describe it clearly or I used it improperly, please help me

**Comment by mhils** [comment]
Thanks for the clarification. 25s is indeed absymally slow. I really don't have a good explanation though. Does that also (occasionally) happen when you reply a request (select flow, press "r")?

**Comment by bizhen-yang** [comment]
I meet this problem as well，I use tool is mitmdump and tip 
` Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe')`

**Comment by ln90s** [comment]
按理说我已经收到你的邮件啦。会尽快回复你的！
