### ISSUE TITLE
Dump files not standard across versions

### ISSUE THREAD

**Issue by amoghbl1** [mitmproxy/mitmproxy#4576]
#### Problem Description

Dump files generated by mitmdump 5.2 aren't compatible with 5.3.x or 6.x.x.

Whats worse is that they're partially compatible, somehow the newer versions read one request in the file and not the rest of it.

#### Proposal

I get that maintaining backward compatibility is super hard and don't expect the project to start doing this.
It would be nice if users were informed of intricacies like this one.

#### Alternatives

Versioning info in Dump files and an error message when newer versions try to read them would be great.

Backward compatibility would be the best option of course, but trying to debug something like this is very hard.
Hopefully too many people haven't spent time trying to figure this out.

**Comment by mhils** [comment]
Old dumpfiles can generally be read with newer versions since mitmproxy 0.11 or so. If that doesn't work for a particular file it's a bug and we need more details. :)

**Comment by amoghbl1** [comment]
Sure!

[This](https://github.com/amoghbl1/mitm-dumps/blob/master/example.dump) dump works fine with mitmdump 5.2 but not with versions after it.

**Comment by mhils** [comment]
This will be fixed with the next release in about a week, thanks again! 😃

**Comment by amoghbl1** [comment]
Thanks a lot for looking into this, I see my initial post seemed more aggressive than I'd intended and I apologize.

Thanks again, this helps me with using latest versions to process old data :D
