### ISSUE TITLE
I install certificate，but use mitmweb and mitmdump ,sometime can`t get https package

### ISSUE THREAD

**Issue by bizhen-yang** [mitmproxy/mitmproxy#4577]
I install certificate，but use mitmweb and mitmdump ,sometime can`t get https package, I is reinstall certificate

**Comment by bizhen-yang** [comment]
version is 5.3.0

**Comment by Prinzhorn** [comment]
> sometime can`t get https package, I is reinstall certificate

I'm sorry, I don't know what that means.

Please:

1. Use a more recent mitmproxy, e.g. 6
2. Provide clear steps to reproduce the issue if you think there is a bug in mitmproxy
