### ISSUE TITLE
400 Bad Request and 502 Bad Gateway + Certificate Errors while connecting to the MITM Proxy server From a Linux Machine

### ISSUE THREAD

**Issue by gowthamsadasivam** [mitmproxy/mitmproxy#458]
I'm trying to setup a simple proxy server using MITM-Proxy, in such a way that a machine from the network can connect to the proxy and utilize the internet connection through it. This as simple as how a normal proxy server behaves. But I'm not able to get this working.
***I'm using iptables because, my requirement is to enforce any traffic originated in the client system (Including any software running inside the system like browser also) MUST use the proxy server as the only choice to communicate to the outside world.*** The current configuration is like as follows,

I have two Linux machines (Ubuntu) as follows, (Both are in the same network, Both of them have access to internet. Gateway is ***172.17.42.1***)

**1.)** MITM-Proxy Machine: ***172.17.0.4*** --> running proxy on port ***8080***

**2.)** Client Machine: ***172.17.0.6***

I need to accomplish that the client machine always send and receive any web traffic (80 and 443) through the MITM-Proxy only. To get this working I made "IPTABLES" configuration in the client machine. In such a way that,

**A.) All the originating traffic for port 80 and port 443 from the client machine will be DNAT to MITM-Proxy (i.e. 172.17.0.4:8080)**
**!#** sudo iptables -I OUTPUT -o eth0 -d 0.0.0.0/0 -j ACCEPT
**!#** sudo iptables -t nat -A OUTPUT -p tcp --dport 80 -j DNAT --to-destination 172.17.0.4:8080
**!#** sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -j DNAT --to-destination 172.17.0.4:8080

**B.) All the ESTABLISHED, RELATED traffic will be allowed in the machine.**
**!#** sudo iptables -I INPUT -i eth0 -m state --state ESTABLISHED,RELATED -j ACCEPT

**C.)** After I made the above settings in the client machine and now MITM-Proxy runs in the normal mode "mitmproxy" and waits for connections in port 8080.

Now, I tried "wget **http:**//google.com" in the client machine. It failed and shows the **ERROR** as follows,
***HTTP request sent, awaiting response... 400 Bad Request***

**Screenshot: Browser terminal is the client machine and terminal window is the MITM Proxy** ![mitm-mode](https://cloud.githubusercontent.com/assets/5887533/5916329/0bd0d63a-a636-11e4-8e8f-d0d3b3a49f3a.png)

***Is there way that I can install the http://mitm.it certificate to the Linux system?***
On the other hand if I try "wget **https:**//google.com" in the client machine, it failed with different **ERROR** as follows,
***OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Unable to establish SSL connection.***

Now, In the MITM-Proxy Machine if invoke the mitmproxy with -T --host (i.e. **mitmproxy -T --host**) I got a different problem. While the client was waiting for the response, MITM-Proxy screen ***it is flooding with requests and hangs. I have to broke it down using "Ctrl+C".***

**Screenshot: Browser terminal is the client machine and terminal window is the MITM Proxy** ![mitm-t-mode](https://cloud.githubusercontent.com/assets/5887533/5916328/0bcb8be4-a636-11e4-877c-8765957f0fa9.png)

I have also tried using a different **iptables** rules like below,
**!#** sudo iptables -I OUTPUT -o eth0 -d 0.0.0.0/0 -j ACCEPT
**!#** sudo iptables -t nat -A OUTPUT -p tcp --dport 80 -j DNAT --to-destination 172.17.0.4:80
**!#** sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -j DNAT --to-destination 172.17.0.4:80

In the above case I made transparent proxy configuration in the MITM-Proxy Machine using iptables as specified in this official documentation page. But still nothing changes all the same **ERRORs** are repeating like the above ones except, the "wget http://google.com" shows ***502 Bad Gateway, instead of 400 Bad Request.*** The "wget https://google.com" returns the same error as the previous one.

I also made a **TCPDUMP** of the requests in the MITM Machine. 
**Screenshot: Browser terminal is the client machine and terminal window is the MITM Proxy** ![tcpdump-mode](https://cloud.githubusercontent.com/assets/5887533/5916327/0bca6e26-a636-11e4-85e0-0e3340461a2a.png)

All I required is just a simple proxy server which another machine can use for (tcp) web traffic (both http and https).

**P.S: Without iptables** change if I ran MITM in one machine and If i use the proxy settings as IP:172.17.0.4:8080 in the browser of the Client Machine it **works very well.**

**Comment by mhils** [comment]
Hi Gowtham,

thanks for the detailed description. Your solution seems fairly complex and I admittedly didn't dig through it. There's probably a way easier way to accomplish what you want.

Did you take a look at the "Transparent Proxy" section on http://mitmproxy.org/doc/modes.html? You should be perfectly fine by setting a custom gateway on your client machine (no need to use iptables) and then run mitmproxy in transparent mode on the other machine.

Cheers,
Max

**Comment by gowthamsadasivam** [comment]
Hey mhils,

Thanks for the quick reply. I've looked into the link and got some ideas to solve the issue. At first I tried the "Custom Gateway" method, Which I expected to work with iptables OUTPUT chain. But unfortunately It doesn't work. So without any other choice I've installed redsocks in the Client Machine. The **combination of redsocks and iptables** works great to enforce the proxy for the complete outgoing traffic from client machine to the mitm proxy server.

Here is the configuration I made. (might help others with similar situation)

**# Create new chain for RedSocks**
`root# iptables -t nat -N REDSOCKS`

**# Ignore LANs and some other reserved addresses**
```
root# iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
root# iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
root# iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
root# iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
root# iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
root# iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
root# iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
root# iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN
```

**# Redirect all the http to redsocks local port**
`root# sudo iptables -t nat -A REDSOCKS -p tcp --dport 80 -j REDIRECT --to-ports 12345`
**# for https traffic just replace port 80 with 443**

**# Use all REDSOCKS chain for all the outgoing traffic at eth0**
`root# sudo iptables -t nat -A OUTPUT -p tcp -o eth0 -j REDSOCKS`

Now, configure redsocks to listen to the local port 12345 for the incoming traffic and forward it to the proxy server's IP and port. To do this **edit redsocks.conf** as like this,

```
redsocks {
local_ip = 127.0.0.1;
local_port = 12345;
ip = 172.17.0.4;
port = 8080;
type = http-relay;
}
```
just **save the conf and restart the redsocks service**. Now all the outgoing traffic originated from the 1st container will be enforced to use the proxy. (**NOTE:** I've used **iptables-persistent** to persist the rules over server reboots) Actually I have implemented the same for both http and https traffic by adding another line to the iptables configuration. Although it's not a transparent proxy, it does the job for me.

If anyone have alternative solution to this please suggest here or at my ServerFault question here: [ServerFault] (http://serverfault.com/questions/662297/transparent-proxying-a-single-docker-container-to-another-docker-container?stw=2)

**Comment by yael-lorenzo-olx** [comment]
Hey @gowthamsadasivam , I have faced the same situation where I need to do exactly what you did. Actually it took me a lot of hours to see if this was possible inside docker containers, and I still doubt it is possible. I have done your steps, updating my ip and I got an error on the redsocks

After trying to access a web page on SSL
Unable to establish SSL connection.

and the log

1513621776.009192 main.c:152 main(...) redsocks started
1513621781.650568 redsocks.c:707 redsocks_accept_client(...) [10.6.0.1:46842->178.32.226.88:443]: accepted
1513621781.650838 http-relay.c:408 httpr_toss_http_firstline(...) [10.6.0.1:46842->178.32.226.88:443]: malformed request came
1513621781.650854 http-relay.c:439 httpr_toss_http_firstline(...) [10.6.0.1:46842->178.32.226.88:443]: httpr_toss_http_firstline
1513621781.650871 redsocks.c:337 redsocks_drop_client(...) [10.6.0.1:46842->178.32.226.88:443]: dropping client

do you have an idea of what could this be or since this idea is an evolution?

Thanks in advanced.

**Comment by gowthamsadasivam** [comment]
Hello @yael-lorenzo-olx 

I worked on this solution almost 2 years ago. So I had to recreate everything above and It worked fine for me. I'm able to make http/https requests and capture them in mitmproxy.

**Making wget request from container terminal:**
![mitmproxy_new_2](https://user-images.githubusercontent.com/5887533/34357832-438662d0-ea70-11e7-8de9-551bb3d15b06.jpg)

**MITMProxy captured the requests in the other container:**
![mitmproxy_new](https://user-images.githubusercontent.com/5887533/34357823-2ee00bf6-ea70-11e7-9c9c-bfcaa5273c53.jpg)

If this is what you're looking for, it's working with the above configuration as I specified in the post. But, I'm not sure about those redsocks errors from your log.

Please check if you did these following steps:

- Installing custom/pre-generated _ca-certificates_ in both the containers by following the [steps in the official website](http://docs.mitmproxy.org/en/stable/certinstall.html).

-  Add iptables rule for https (443):
`# sudo iptables -t nat -A REDSOCKS -p tcp -m tcp --dport 443 -j REDIRECT --to-ports <LOCAL_PORT>`

- Create a new block for https in redsocks.conf file:
```
redsocks {
local_ip = 127.0.0.1;
local_port = <LOCAL_PORT>;
ip = <MITM_CONTAINER_IP>;
port = <MITM_REMOTE_PORT>;
type = http-connect;
}
```
This should work for you :)
