### ISSUE TITLE
Online documentation not updated with latest source

### ISSUE THREAD

**Issue by LazaroOnline** [mitmproxy/mitmproxy#4592]
The tutorial:
https://docs.mitmproxy.org/stable/howto-install-system-trusted-ca-android/#3-insert-certificate-into-system-certificate-store

is missing some required commands.
In GitHub it is updated, but the online docs are using an outdated version of:
https://github.com/mitmproxy/mitmproxy/blob/main/docs/src/content/howto-install-system-trusted-ca-android.md

Please re-deploy to update the online docs with the latest from GitHub.

**Comment by mhils** [comment]
The docs you are looking at are for the latest stable release. We are hosting the latest documentation from GitHub at https://docs.mitmproxy.org/dev. I guess you miss that bit of information if you come straight from Google. I'd be happy for a PR that adds something like a version selector if that makes it more obvious. :)
