### ISSUE TITLE
iOS 13 TLS server certificates must have a validity period of 825 days

### ISSUE THREAD

**Issue by loretoparisi** [mitmproxy/mitmproxy#4610]
#### Problem Description
Certificate installed via mitm.it is expired.

[This](https://alext.mail.at/?p=727) workaround proposes this approach

```
Starting with IOS 13, TLS server certificates must have a validity period of 825 days or fewer and MITMProxy generates certs with an expiration period of 1095 days.
Solution: I changed the py file of MITMProxy to shorten the cert validity, by changing the file /usr/lib/python2.7/dist-packages/netlib/certutils.py
# DEFAULT_EXP = 94608000  # = 24 * 60 * 60 * 365 * 3
DEFAULT_EXP = 31536000  # = 24 * 60 * 60 * 365
```

The problem is that I cannot follow this approach since I'm using the `mitmproxy` docker image (see below)

#### Steps to reproduce the behavior:
1.  docker pull mitmproxy/mitmproxy 
2.  docker run --rm -it -v ~/.mitmproxy:/home/mitmproxy/.mitmproxy -p 8080:8080 mitmproxy/mitmproxy
3.  Go to mitm.it from iOS device
4.  Go to General > Profiles > mitmproxy > the profile is expired 9 March 2020

#### System Information
Dockerhub image 

```
mitmproxy/mitmproxy   latest    37c70985d385   5 months ago   122MB
```

**Comment by mhils** [comment]
You are conflating two issues here:

1. iOS validity limitation: All recent versions of mitmproxy handle this properly.
2. Expired certificates. It looks like your mitmproxy certificate was generate too long ago. 

The fix for the second issue is to delete all CA-related files in your ~/.mitmproxy folder. The CA will be regenerated automatically after restarting mitmproxy (and then needs to be reinstalled on your devices).

There also should be a "The mitmproxy certificate authority has expired" message in your mitmproxy event log somewhere with these steps. :)

**Comment by loretoparisi** [comment]
@mhils thanks, for point 2), since I'm using `docker` I do not have any previous local folder with expired certificates:

```bash
docker run --rm -it -v ~/.mitmproxy:/home/mitmproxy/.mitmproxy -p 8080:8080 mitmproxy/mitmproxy
```

I mount this (new) volume with fresh certificates;
Then I go to mitmproxy.it and I install the (new) certificate, that should be valid, while it is expired.
So I assume in this config, I do not have any previously expired certificates on my host machine...

**Comment by mhils** [comment]
To be clear, you have tried deleting everything in your local `~/.mitmproxy` folder and then restarted the container? Does that cause new certificate files to be generated in that folder?

**Comment by loretoparisi** [comment]
@mhils let me check again

**Comment by loretoparisi** [comment]
So, in fact! It was tricky, but it worked in this way 

1. delete old PROFILES installed on iOS
2. delete that folder contents: `rm ~/.mitmproxy`
3. activate the docker image again `docker run --rm -it -v ~/.mitmproxy:/home/mitmproxy/.mitmproxy -p 8080:8080 mitmproxy/mitmproxy`
4. Browse to [mitmproxy.it](mitmproxy.it) and install certificate on iOS; be sure the expiration year is 2024 now
5. Check on iOS/General/Info/Certificates and enable the latest installed (first on the list)
6. It works!


In my case I had issue 2) and issue 5), hence only cleaning 2) did not work, but I need the enable the new Certificates as for step 5)...
