### ISSUE TITLE
Unable to edit multipart/form-data via mitmproxy UI

### ISSUE THREAD

**Issue by jhulme** [mitmproxy/mitmproxy#4613]
#### Problem Description
Changes made when editing multipart/form-data on an intercepted request are lost when returning to view the flow.

#### Steps to reproduce the behavior:

1. Set intercept for requests and multipart/form-data - `~q & ~t "multipart/form-data"`
![set_intercept_gh](https://user-images.githubusercontent.com/809451/119967488-4cdc9b80-bfa4-11eb-813c-18797040e164.JPG)
2. Generate simple request with multipart form (during testing used [httpie ](https://httpie.io/)tool)
3. Select flow within mitmproxy UI
![flow_details_gh](https://user-images.githubusercontent.com/809451/119967487-4c440500-bfa4-11eb-907f-099a7f41ac73.JPG)
4. Press 'e' to edit and select multipart
![edit_flow_gh](https://user-images.githubusercontent.com/809451/119967482-4c440500-bfa4-11eb-82fe-018eef0f6ca5.JPG)
5. Update some portion of the data
![editing_form_gh](https://user-images.githubusercontent.com/809451/119967479-4bab6e80-bfa4-11eb-8730-860943c6316e.JPG)
6. Press 'esc' to retain changes
7. Press 'q' to return to flow view. Expect to see edited data, instead no data is present and Content-Length is set to 0.
![missing_content_gh](https://user-images.githubusercontent.com/809451/119967476-4b12d800-bfa4-11eb-9691-827cfcce36f9.JPG)

I expect that I am following an incorrect process here in some manner that is resulting in the behaviour, so any guidance would be appreciated.

I have also tried rolling back and testing with v5.3.0 again with the same behaviour.

#### System Information
```
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.27
```

**Comment by roytu** [comment]
I'm running into this issue as well.  Seems a few places in the code are dropping the "boundary" field in the Content-Type when it comes to multipart packets.

I found three locations in the code where this assumption is made, and after adding those fixes it seems to (mostly) work.  There's still an issue where the multipart editor appends b'' to all the fields, and editing them runs into a bytes vs. string type error, but it's closer now.

[https://github.com/roytu/mitmproxy/commit/8641254cd55bb61f6da5df76237b7977d8f92122](commit)

**Comment by roytu** [comment]
Pull request is in progress for this issue. For the bytecode issue, I've found that [this](https://github.com/roytu/mitmproxy/commit/64d819663c0f5e56b8e64df5e10402d517a0e315) seems to work (though it's a hack currently so I'm not including it in the PR for now).
