### ISSUE TITLE
Change the way domains are encoded.

### ISSUE THREAD

**Issue by gndu91** [mitmproxy/mitmproxy#4622]
#### Problem Description
When setting the header "Host", you use the "ascii" encoding, which only works when the domain name is fully ascii.
  File "/directory/environment/lib/python3.8/site-packages/wsproto/handshake.py", line 327, in _initiate_connection
    (b"Host", request.host.encode("ascii")),
I suggest changing the encoding from ascii to idna to get the correct xn--... domain name instead

#### Steps to reproduce the behavior:
1. Open the proxy and configure the system proxy.
2. Open a website having non ascii character in its domain name
3. Look for the error in the logs

#### System Information
Mitmproxy: 6.0.2
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.11.0-7614-generic-x86_64-with-glibc2.29

**Comment by gndu91** [comment]
I edited the file in questions in lines 201, where the Host value is retrieved from the initial header, and in line 327, where is it encoded into the final header, now I don't see any errors, however I used this form instead of a pull request because I don't know if this change can break anything else, for instance maybe other part of the library expect ascii domains too.

**Comment by mhils** [comment]
@Kriechi: is this something you want to transfer to the wsproto issue tracker?

**Comment by Kriechi** [comment]
@gndu91 thanks for reporting! Yes, we should use IDNA encoding. I created a new issue in the wsproto repository which is a dependency library of mitmproxy.
https://github.com/python-hyper/wsproto/issues/160
