### ISSUE TITLE
Serve PAC file through mitmproxy HTTP service

### ISSUE THREAD

**Issue by igorgatis** [mitmproxy/mitmproxy#4623]
#### Problem Description
It would be nice if mitmproxy could serve PAC file. This makes life easier to setup proxy in clients (e.g. browsers) that support it.

#### Proposal
Think of a team of developers which would like to share the same mitmproxy settings. For instance, they can all use Chrome with Proxy Switcher and Manager which they can setup with `http://127.0.0.1:8080/myconfig.pac`. They can also run the scommand:
```
mitmdump -s myaddon.py
```

Where `myaddon.py` contains:
```python
from mitmproxy import pac

_PAC_CONTENT = '''
function FindProxyForURL(url, host) {
  if (shExpMatch(host, "mitm.it")) {
    return "PROXY 127.0.0.1:9080";
  }
  return "DIRECT";
}
'''
pac.serve('myconfig.pac', _PAC_CONTENT)
```

Or, the PAC content could be passed as a parameters:
```
mitmdump -s myaddon.py --pac myconfig.pac
```

#### Alternatives
Current workaround is to share the PAC file. If one tries to serve it from `myaddon.py you get:
```
 << Invalid HTTP request form (expected: authority or absolute, got: relative)
```

#### Additional context
NA

**Comment by mhils** [comment]
Thanks for the extensive suggestion! This works with the latest development snapshots (see https://github.com/mitmproxy/mitmproxy/issues/4632) by exposing a WSGI app from within mitmproxy. Adapted from [examples/addons/wsgi-flask-app.py](https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/wsgi-flask-app.py):

```python
from flask import Flask
from mitmproxy.addons import asgiapp

app = Flask("pacapp")


@app.route('/myconfig.pac')
def serve_pac() -> str:
    return 'function FindProxyForURL(url, host) { ... }'


addons = [
    asgiapp.WSGIApp(app, "localhost", 8080)
]

```

Thinking about it, you can also adapt [examples/addons/http-reply-from-proxy.py](https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/http-reply-from-proxy.py) now, which probably is even a bit simpler. 😄
