### ISSUE TITLE
HTTP/1.1 also have a problem about "Request content missing."

### ISSUE THREAD

**Issue by Chellane** [mitmproxy/mitmproxy#4627]
#### Problem Description
I user mitmweb to catch flows, and then some request of flows display "Request content missing."
Now，I find that, when content-length=0, the flow display "Request content missing."
#### System Information
Mitmproxy: 6.0.2
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Windows-10-10.0.19041-SP0

**Comment by KORraNpl** [comment]
It could be closely related to #4470 and it seems there has been some work already done on it! Let's keep our fingers crossed.

**Comment by mhils** [comment]
I've just fixed #4470 on main, please try out the latest dev snapshots and report back if there are any issues! 😃
