### ISSUE TITLE
Instagram TCP connections broken with HTTP2 enabled

### ISSUE THREAD

**Issue by Nerixyz** [mitmproxy/mitmproxy#4630]
#### Problem Description
Using the latest binary (v7) with HTTP2 enabled and in SOCKS mode, Instagram on Android can't use MQTT through TCP anymore.
Other Facebook apps might also be affected as they use a similar connection.

In an affected version, you can see a lot of TCP connections to two different hosts with the same port (443). If you look at the tcp messages, the last message is always `missing connection preface` (then the connection is closed).

This doesn't happen if mitmproxy has HTTP2 disabled (instagram uses http2, so you only see tcp connections but the MQTT connections mentioned at the start work fine; there are two persistent connections).

I beleive this was introduced in #4529 (commit `f94a9a3`) as the build for #4532 (commit `0e8dd73`) doesn't have this issue.

#### Steps to reproduce the behavior:
0. Have an Instagram account with [WhiteHat mode](https://www.facebook.com/whitehat) enabled (and enable no TLS 1.3 and allow user certificates in the app).
1. Fully close Instagram
2. Start mitmproxy in SOCKS mode
3. Open Instagram

#### System Information
```
Mitmproxy: 7.0.0.dev binary
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Windows-10-10.0.19041-SP0
```

**Comment by mhils** [comment]
Thanks! A few questions:

- Can you reproduce this with `--set connection_strategy=lazy`?
- Which version are you on exactly? Downloaded today/in the last few days?

Also, a `mitmdump --set proxy_debug -vvv` log would be fabulous. If you are unsure whether it contains private data feel free to shoot me an email. :)

**Comment by Nerixyz** [comment]
> Can you reproduce this with `--set connection_strategy=lazy`?

I can't. With this option (?) set, it works fine.


> Which version are you on exactly? Downloaded today/in the last few days?

The mitmdump logs I'll send you are on the latest build. The first occurence of this issue was after #4529 landed, so basically [this build](https://github.com/mitmproxy/mitmproxy/commit/f94a9a3c9dc6cc1ebfda7038676aa64560bd4f56). The previous build was fine.

I sent you the log via email.

**Comment by mhils** [comment]
Repro:
```
mitmdump -vvv --set proxy_debug --mode socks5
curl -x socks5h://localhost:8080 -k https://facebook.com -v --no-alpn
```

I'll have a fix out momentarily. 😃

**Comment by Nerixyz** [comment]
Thaks for the quick fix!
