### ISSUE TITLE
Upcoming 7.0 Release

### ISSUE THREAD

**Issue by yotamgod** [mitmproxy/mitmproxy#4632]
Hi,
I was wondering when the official 7.0.0 (sans-io) version is set to be released? I couldn't find any discussion on it..
Sorry for creating a proposal, but I couldn't find the right medium to ask this question.
Thanks!

**Comment by mhils** [comment]
We're tentatively planning to ship a release in the next few weeks unless any major regressions are reported. So I encourage everyone to test the [7.0 snapshots](https://mitmproxy.org/downloads/#branches/main/) now and report any bugs. 🐛 

The preliminary changeling is available at https://github.com/mitmproxy/mitmproxy/blob/main/CHANGELOG.md. I'll write a few more words on how to upgrade existing custom add-ons soon, but most should just work as-is.

**Comment by mhils** [comment]
Mitmproxy 7 is out! 😃 
https://mitmproxy.org/posts/releases/mitmproxy7/
