### ISSUE TITLE
mitmproxy.exceptions.ControlException: Reply is taken, but expected it to be start.

### ISSUE THREAD

**Issue by FreaxW** [mitmproxy/mitmproxy#4638]
#### Problem Description
Error occurs when addons contains multiple scripts and @ concurrent is used to decorate response or request, it will not appear when addons has only one script
![image](https://user-images.githubusercontent.com/46556817/122187716-e0c5c700-cec1-11eb-8662-76b255683da0.png)
![image](https://user-images.githubusercontent.com/46556817/122187610-c4c22580-cec1-11eb-8588-da6eb1016ccd.png)

#### Steps to reproduce the behavior:
1. use @concurrent
2. addons contains multiple scripts
#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 6.0.2
Python:    3.9.2
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Windows-10-10.0.19041-SP0

**Comment by mhils** [comment]
To clarify, you have multiple addons that make use `@concurrent` for the same event hook? I'm afraid that's currently not supported. We'll eventually fix this with #4207, I'd generally recommend to avoid `@concurrent` where possible.

**Comment by FreaxW** [comment]
> To clarify, you have multiple addons that make use `@concurrent` for the same event hook? I'm afraid that's currently not supported. We'll eventually fix this with #4207, I'd generally recommend to avoid `@concurrent` where possible.

Thanks, but how to use it in hook response or reuqest like that.

**Comment by FreaxW** [comment]
> > To clarify, you have multiple addons that make use `@concurrent` for the same event hook? I'm afraid that's currently not supported. We'll eventually fix this with #4207, I'd generally recommend to avoid `@concurrent` where possible.
> 
> Thanks, but how to use it in hook response or reuqest like that.

![image](https://user-images.githubusercontent.com/46556817/122715198-1f30fc80-d29b-11eb-937e-2900b4113098.png)
I use it like this, but it doesn't work

**Comment by mhils** [comment]
As mentioned in #4207, this is not supported yet. We will eventually implement it.
