### ISSUE TITLE
Can't decode reponse content by flow.response.get_content(False)

### ISSUE THREAD

**Issue by solderain** [mitmproxy/mitmproxy#4639]
#### Problem Description
Try to add  addons script to get server response , then  failure to  decode the response content . But found the mitmweb page  can present the correct response , pls refer to the following  script and snapshot :

**SCRIPT:**
def response(self, flow: mitmproxy.http.HTTPFlow):
   if  flow.request.path.startswith("xxxxxxxxx"):
       data = flow.response.get_content(False)
       print("############# THE RESPONSE : " + str(data))

response:
![image](https://user-images.githubusercontent.com/4144738/122404111-86a42f00-cfb1-11eb-84e9-3391e8c2f74e.png)

response content in mitmweb:
![image](https://user-images.githubusercontent.com/4144738/122404506-de429a80-cfb1-11eb-9275-a06f1eaaa1e9.png)

#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
mitmproxy version : 6.0.2 
python : 3.8.10
platform : macOS Catalina 10.15.5

**Comment by mhils** [comment]
This looks correct to me. What you are seeing in mitmweb is the pretty-printed version of a protobuf message. `flow.response.get_content(False)` just gets you the raw protobuf message. Does that clear up things?

**Comment by solderain** [comment]
Thanks to you quick reply .  Try to so much times  to decode the response , still cann't interpreter the content .

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/contentviews/protobuf.py should be the right place. :)
