### ISSUE TITLE
Outfile -w cannot be loaded

### ISSUE THREAD

**Issue by ErickBastiaannet** [mitmproxy/mitmproxy#4651]
#### Problem Description
When the dump file is getting bigger, about 100mb it's not loaded anymore.

#### Steps to reproduce the behavior:
Make a big outfile and try to open it with an new instance of mitmweb.

#### System Information
Mitmweb Windows 10 6.0.2

**Comment by mhils** [comment]
This report is not actionable. Which browser are you using? Are there any error messages, either in your browser's developer tools or in mitmweb's console window?

**Comment by huuck** [comment]
Still happening in the latest version even with the bigger buffer value.
