### ISSUE TITLE
Android blank page

### ISSUE THREAD

**Issue by uniwes23** [mitmproxy/mitmproxy#466]
hello
I have a problem. I installed mitmproxy without any problems on xubuntu 14.04. I have an Android smartphone and have set the gateway so that all data go to my Computer. What works well so far.
But when I type the two commands

iptables -t nat -A PREROUTING -i eth0 -p tcp -j REDIRECT --to --dport 80-port 8080
iptables -t nat -A PREROUTING -i eth0 -p tcp -j REDIRECT --to---dport 443 port 8080

I try to load a page on the phone and nothing happens. And also mitmproxy shows nothing.
According wireshark the Computer definitely  got requests from the mobile phone. The mitmproxy's CA is installed too.
Can someone help me?

**Comment by mhils** [comment]
Hi there,

first, your iptables rules seem to be broken (dashes moved around). Is that a copy & paste error or did you enter them wrongly in your console? Second, do you see clientconnect messages in mitmproxy event log? (press e to open)

Cheers,
Max

**Comment by uniwes23** [comment]
Hi.
Thank you for your very fast answer!!! 
Yes it's an copy & paste error.... But I found my error.
I had old firewall settings that caused the error.I'm sorry -_- mitmproxy works now like a charme. It's awesome. And thank you very much!!!!
