### ISSUE TITLE
Change the default validity of generated root-CA cert to more than 3 years

### ISSUE THREAD

**Issue by rob-X1** [mitmproxy/mitmproxy#4668]
When starting mitmproxy for the first time a new root-ca certificate is generated with a validity time of 3 years (tested on Linux and Windows)

This is pretty short for a root-CA certificate and requires additional work for long-term mitmproxy users as after three years the root-ca certificate have to be installed again on all used devices and programs. Especially on Android devices this requires a significant amount of work to install the certificate as system certificate.

Root-CA certificates typically have a validity time of 10-20 years therefore I don't see a reason why mitmproxy limits the validity to 3 years only.

**Comment by mhils** [comment]
Hi @rob-X1! I saw your StackOverflow answer a few minutes ago, thanks for helping out over there! 😃  You are absolutely right on this one, in fact I already increased it a few weeks ago in #4611. The next release will have this fixed. :)

Thanks again!
