### ISSUE TITLE
Transparent mode failure: ProtocolException("Invalid server address: ('127.0.0.1', 8082)\r\nThe proxy shall not connect to itself.")

### ISSUE THREAD

**Issue by afridi26** [mitmproxy/mitmproxy#4673]
#### Problem Description
 I already setup transparent proxy, it worked like a charm however, since yesterday I am getting the following error when I try to curl a page.
`Transparent mode failure: ProtocolException("Invalid server address: ('127.0.0.1', 8082)\r\nThe proxy shall not connect to itself.")`
```
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>
            <h1>502 Bad Gateway</h1>
            <p>ProtocolException(&#x27;Transparent mode failure: ProtocolException(&quot;Invalid server address: (\&#x27;127.0.0.1\&#x27;, 8082)\\r\\nThe proxy shall not connect to itself.&quot;)&#x27;)</p>
            </body>
</html>
```
I can see the error that the proxy shall not connect to itself but as per documentation I am redirecting traffic which originates for the machine itself. I search for this problem on StackOverflow and GitHub issues but there was no success. Is there something that I am messing up from my side?

#### Steps to reproduce the behavior:
1. follow setup 1 and 2  for linux https://docs.mitmproxy.org/stable/howto-transparent/
2.  then follow this https://docs.mitmproxy.org/stable/howto-transparent/#work-around-to-redirect-traffic-originating-from-the-machine-itself
3. curl --proxy http://127.0.0.1:8082 "http://wttr.in/newyork?0"

#### System Information
Mitmproxy: 6.0.2 binary
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.11.18-200.fc33.x86_64-x86_64-with-glibc2.32

Regards,
Afridi

**Comment by Prinzhorn** [comment]
I _think_ you don't need `--proxy` at all. You are basically telling curl to use this proxy and then curl is _also_ using the transparent proxy that you've configured. That's why it's trying to connect to itself.

**Comment by mhils** [comment]
@Prinzhorn is right here, thanks! :)
