### ISSUE TITLE
addon websocket_message broken in 7.0

### ISSUE THREAD

**Issue by jpfarias** [mitmproxy/mitmproxy#4686]
#### Problem Description

I have an addon that works on websocket connections and does some processing on the messages, upgrading to v7.0 broke the addon, it says the HTTPFlow has no attribute messages.

#### Steps to reproduce the behavior:
1.  Write an addon with:

```
class MyAddon:
    def websocket_message(self, flow):
        for msg in flow.messages:
            print(msg)
addons = [MyAddon()]
```
2. run mitmdump --mode=transparent -s myaddon.py

#### System Information
Paste the output of "mitmproxy --version" here.

Mitmproxy: 7.0.0
Python:    3.8.5
OpenSSL:   OpenSSL 1.1.1i  8 Dec 2020
Platform:  Linux-5.4.0-72-generic-x86_64-with-glibc2.29

**Comment by mhils** [comment]
Hi there!

Thanks for the report. There've been some API changes here with v7 which we tried to document at https://docs.mitmproxy.org/stable/addons-api-changelog/#websocket-flows. We've also updated the examples at https://github.com/mitmproxy/mitmproxy/tree/main/examples/addons. Let me know if that helps, otherwise we need to refine our upgrade docs. :)

**Comment by jpfarias** [comment]
Cool, does the messages in the websocket work the same as they used to before the new version?
I am asking just to make sure I can do something like:

````
class MyAddon:
    def websocket_message(self, flow):
        try:
            msgs = flow.messages
        except AttributeError:
            msgs = flow.websocket.messages
        for msg in msgs:
            print(msg)
            # the rest of my code would go here and process the msg
addons = [MyAddon()]
```

**Comment by mhils** [comment]
That addon seems like it should work. I would generally recommend to target 7.0+ only, for which we now have proper API docs (https://docs.mitmproxy.org/stable/api/mitmproxy/websocket.html). :)
