### ISSUE TITLE
Allow Selection of Upstream Cipher Suites

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#469]
Currently, a user can specify the ciphers presented to the client by using the `--ciphers` switch. As with `--ssl-version-client/--ssl-version-server`, we should introduce `--ciphers-server` and rename `--ciphers` to `--ciphers-client`. 

Relevant parts in the code:
- [libmproxy/proxy/config.py#L217](https://github.com/mitmproxy/mitmproxy/blob/c9240812d9239591915b521524e8a1dbbef05b0f/libmproxy/proxy/config.py#L217)
- [libmproxy/proxy/config.py#L58](https://github.com/mitmproxy/mitmproxy/blob/c9240812d9239591915b521524e8a1dbbef05b0f/libmproxy/proxy/config.py#L58)
- [libmproxy/proxy/server.py#L181-L218](https://github.com/mitmproxy/mitmproxy/blob/c9240812d9239591915b521524e8a1dbbef05b0f/libmproxy/proxy/server.py#L181-L218)

**Comment by yzninja** [comment]
It would be helpful if the "--ciphers-server" switch could inherit the cipher suite of the client device. Perhaps using "--ciphers-server inherit".

**Comment by yzninja** [comment]
Max - I did a search in the github repository to see where mitmproxy is analyzing "client hello" requests but couldn't find it. Could you point me in the right direction?

**Comment by mhils** [comment]
@yzninja, take a look at the last excerpt i posted. I calls [TCPClient.convert_to_ssl](https://github.com/mitmproxy/netlib/blob/b6af3fddf4ee2c45a722bd5087c86cee59b8cfa0/netlib/tcp.py#L293), which accepts a cipher_list argument.

**Comment by elitest** [comment]
I have been looking at how to implement this.  I can see how the client interacts with netlib as you referrenced, but I'm having trouble understanding how `self.server_conn.establish_ssl` interacts with it.    `convert_to_ssl` accepts `cipher_list` as a parameter, but `establish_ssl` does not.  Am I barking up the wrong tree?

**Comment by mhils** [comment]
Sorry for the confusion - this part is indeed a bit fiddly. In summary: `server_conn` is an instance of ServerConnection. ServerConnection.establish_ssl is defined [here](https://github.com/mitmproxy/mitmproxy/blob/dff70150f5197173c5534cd947d2824c166c4527/libmproxy/proxy/connection.py#L147-L153). It directly passes its keyword arguments to [TCPClient.convert_to_ssl](https://github.com/mitmproxy/netlib/blob/b6af3fddf4ee2c45a722bd5087c86cee59b8cfa0/netlib/tcp.py#L293), so you can use `server_conn.establish_ssl(cipher_list=...)`. Apologies for the badly named functions here.

(I corrected the previous post which originally stated TCPClient.establish_ssl, where it should have been TCPClient.convert_to_ssl)

Cheers,
Max

**Comment by mhils** [comment]
Thanks to @elitest, this will ship with the next version of mitmproxy. :smile: 

Thanks!
Max

**Comment by shreyas1989** [comment]
Is the option of specifying the ciphers available in the new version of mitmproxy?
