### ISSUE TITLE
mitmweb.exe detected as Trojan:Win32/Zpevdo.B by Windows Defender on Windows 10

### ISSUE THREAD

**Issue by edp0** [mitmproxy/mitmproxy#4698]
After installing mitmproxy 7.0.0 using the installer on Windows 10, Windows Defender detects mitmweb.exe as Trojan:Win32/Zpevdo.B

Windows Defender links to the following page : 
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fZpevdo.B&threatid=2147729093

I did not find a way to exclude the mitmproxy folder from scan on my professional workstation and Windows blocks any action on the file (like a sha1sum) because it "contains a virus".

The sha1sum of the installer is as follows :
d5a84d735b293d269da53a89366b27436cd9af61 *mitmproxy-7.0.0-windows-installer.exe

**Comment by mhils** [comment]
Thanks for the heads-up! This is a false-positive and needs to be submitted to Microsoft as such. I'm traveling at the moment, maybe you or someone else can fill the form. :) At the latest I will take care of it on the weekend.

**Comment by edp0** [comment]
I'll try to submit the file to Microsoft later today from my personal PC and I'll update this issue accordingly.

**Comment by edp0** [comment]
File submitted on Microsoft website :)

I'll update this issue as soon as I have feedback from them. I have a submission ID but the page is not public, I need to log into my account to see it.

**Comment by edp0** [comment]
I've heard back from Microsoft, everything is in the clear : 


mitmweb.exe

Submission ID: 3cc7dbdc-eb83-4a29-bb14-b020fe9c47ef

Status: Completed

Submitted by: *******************

Submitted: Jul 22, 2021 7:02:51 PM

User Opinion: Incorrect detection

Analyst comments:


                The file is not malware and we cannot reproduce any detection on the file.  If detection is still observed, please follow the steps below to capture support log files from the system reporting detection.

On Windows 10, from elevated command prompt, change to directory "%programfiles%\windows defender" and execute mpcmdrun.exe with option GetFiles:
    cd "%programfiles%\windows defender"
    mpcmdrun.exe -GetFiles

On Windows 7, from elevated command prompt, change to directory "%programfiles%\microsoft security client" and execute mpcmdrun.exe with option GetFiles:
    cd  "%programfiles%\microsoft security client"

**Comment by mhils** [comment]
Thank you very much, @edp0! 😃
