### ISSUE TITLE
socket.setdefaulttimeout crashes SSL connection.

### ISSUE THREAD

**Issue by F1ashhimself** [mitmproxy/mitmproxy#470]
```socket.setdefaulttimeout(60)``` crashes SSL connection and throws ```ERR_SSL_PROTOCOL_ERROR``` when trying to reach any of https sites. When using default value or ```socket.setdefaulttimeout(None)``` all works fine.

Using libmproxy (mitmproxy 0.11.3).

**Comment by mhils** [comment]
Sorry, but reading your report I have no idea what your issue is. Where/Why/How do you set socket.setdefaulttimeout? Please use our [bug report template](https://github.com/mitmproxy/mitmproxy/blob/master/CONTRIBUTING.md).

**Comment by F1ashhimself** [comment]
My bad.

I'm running custom implementation of ```controller.Master``` class with specified ```...-ca.pem``` certificate.
I'm trying to sniff my browser https traffic so I'have configured it to use this custom mitm proxy.

All was fine when I have used default values of socket timeouts, but when I changed default socket timeout value via ```socket.setdefaulttimeout``` method I start getting ```ERR_SSL_PROTOCOL_ERROR``` in my browser.

**Comment by mhils** [comment]
Sorry, but I cannot do anything here if you don't provide an example that I can reproduce. If you cannot share your custom implementation, you need to break it down to a minimum test case.

**Comment by F1ashhimself** [comment]
Please try -> [this](http://pastebin.com/H1jKeB22) <- example. You should do some steps manually, such as set up proxy in your browser or navigate to https site through it.

**Comment by mhils** [comment]
The root cause seems to be https://github.com/pyca/pyopenssl/issues/168. Sorry, this seems to involve too many changes to justify the effort at the moment.

**Comment by F1ashhimself** [comment]
It seems to be true. Thanks, I will be watching this issue.
