### ISSUE TITLE
Cannot install the latest version of mitmproxy with pipx

### ISSUE THREAD

**Issue by ppflower** [mitmproxy/mitmproxy#4700]
#### Problem Description
I would like to use the features in the latest version(7.0.0) of mitmproxy. Also, my addons require the installation of additional Python packages. It seems that I have to install mitmproxy with pipx. However, the latest version of mitmproxy I could install with pipx is 5.3.0. Would you please make the latest version available with pipx? Thanks.

#### Steps to reproduce the behavior:
Type the command 'pipx install mitmproxy==', and you will see that available versions

#### System Information
Mitmproxy: 7.0.0
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  macOS-11.1-x86_64-i386-64bit

**Comment by mhils** [comment]
pipx directly installs from PyPI, so everything should be available. You are likely using an older Python version which is incompatible with 7.0. The minimum Python requirement is listed in the badges in the repo readme, it's 3.8 at the moment.
