### ISSUE TITLE
Make it possible to enable TLS passthrough from `tls_clienthello` hook.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4702]
From Slack:

> given that I cannot decrypt the connection, I am  currently attempting to bypass the TLS connections altogether.
by doing the following:
```
def next_layer(self, nextlayer: layer.NextLayer):
    is_tls = is_tls_record_magic(nextlayer.data_client())
    if(is_tls):
        nextlayer.layer = layers.TCPLayer(nextlayer.context, ignore=True)
```
> This allows the device to function without breaking due to TLS cert errors, however if I do this, the tls_clienthello hook does not fire. Inversely, if it fires, I do get the SNI but the connection fails.

----

We should look into what it takes to add a `tls_clienthello.passthrough: bool` attribute, which when turned on, makes us not intercept the connection. I have an idea what to do here and will look into it.

**Comment by hazcod** [comment]
That's great @mhils ! Thanks.
