### ISSUE TITLE
`ciphers_client` option doesnt seem to work

### ISSUE THREAD

**Issue by PATAPOsha** [mitmproxy/mitmproxy#4703]
#### Problem Description
Set `ciphers_client` option doesnt seem to work.
After setting `ciphers_client` I cant see any difference between default mitmproxy "Cipher Suites" list in Wireshark.
![image](https://user-images.githubusercontent.com/14761219/126891869-bf3e6b53-b635-40b1-8f74-6eda91e48fb1.png)

Expected behaviour: "Cipher Suites" should contain only ciphers defigned in `ciphers_client` option.

#### Steps to reproduce the behavior:
1. Set `ciphers_client` option like: `mitmproxy --set ciphers_client="ECDHE-ECDSA-AES128-GCM-SHA256"`
2. Make any request using mitmproxy
3. Check "Cipher Suites" section in Wireshark

#### System Information
Mitmproxy: 7.0.0
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.27

**Comment by mhils** [comment]
Thanks! `ciphers_client` sets the supported ciphers for client connections, i.e. connections between client and proxy. I think you are actually looking for `ciphers_server`? Anyhow this is still useful feedback, we need to make the option help more clear. I see how this can be misread easily.

(for `ciphers_server`, see also https://github.com/mitmproxy/mitmproxy/issues/4260)
