### ISSUE TITLE
How can request header,"Content-Length" equal to 0, is set and mitmproxy don't split the request body

### ISSUE THREAD

**Issue by superboy-zjc** [mitmproxy/mitmproxy#4704]
#### Problem Description
I use mitmproxy to replay a particular request in order to prove whether the HTTP request  smuggling vulnerability exists . The particular request includes a header,"Content-Length" equal to  0, and  some payloads in request body.But when I replay request, mitmproxy ignore the request body.

#### Steps to reproduce the behavior:
1. modify a request and replay it .The Content-type = 0 and have some request body payloads
![image](https://user-images.githubusercontent.com/60600792/126893932-04cbc8e5-0f8a-40eb-8408-5a4f32c18c8a.png)
2. Look at wireshark, That request don't have request body.
![image](https://user-images.githubusercontent.com/60600792/126893983-7347fa2f-0f12-4aed-8559-7f585677b9e5.png)

#### System Information
Paste the output of "mitmproxy --version" here.
```
PS C:\Users\18265> mitmproxy --version
Mitmproxy: 7.0.0
Python:    3.9.0
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Windows-10-10.0.19041-SP0
```

**Comment by mhils** [comment]
Thanks for the detailed description! Unfortunately I cannot reproduce this. Here's a saved flow:

```
curl -o smuggling.mitm https://uploads.hi.ls/2021-08/smuggling.mitm
mitmdump -C smuggling.mitm --set flow_detail=4
```
which works as expected:
```
[replay] server connect localhost (127.0.0.1:8082)
127.0.0.1:54128: POST http://localhost:8082/
    Host: localhost:8082
    User-Agent: curl/7.68.0
    Accept: */*
    Proxy-Connection: Keep-Alive
    Content-Length: 0

    Test 123

 << 200 OK 0b
    Content-Length: 0
```
I get similar results with mitmweb. Does this example here work for you?
