### ISSUE TITLE
Doesn't properly check invalid input in tnetstring.parse

### ISSUE THREAD

**Issue by qingxp9** [mitmproxy/mitmproxy#4705]
#### Problem Description
In the [condiction branch](https://github.com/mitmproxy/mitmproxy/blob/0ca458fd6475ee48728147f3b529467a75e912a4/mitmproxy/io/tnetstring.py#L218) ```data_type == ord(b'}')```of tnetstring.parse(), it doesn't properly check invalid data in the parse loop.

#### Steps to reproduce the behavior:
```
from mitmproxy.io import tnetstring
t = b'51:11:12345678901#4:this,8:true!0:~,4:true!0:]4:\\x00,~}' 
tnetstring.loads(t)

TypeError: unhashable type: 'list'
```
![image](https://user-images.githubusercontent.com/2822242/126905571-521252a6-510a-4e8a-859f-e45fbc59dcbe.png)

#### System Information
Mitmproxy: 7.0.0
Python:    3.8.2
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.4.0-kali3-amd64-x86_64-with-glibc2.29

**Comment by mhils** [comment]
I'm not sure if I understand what's the problem here. Is there any way how you can trigger this issue from mitmproxy? Lists aren't supported as dictionary keys in our tnetstring implementation.

**Comment by qingxp9** [comment]
> I'm not sure if I understand what's the problem here. Is there any way how you can trigger this issue from mitmproxy? Lists aren't supported as dictionary keys in our tnetstring implementation.
> 
> It's somewhat expected that tnetstring.loads borks on invalid input, but I don't understand where that is a Denial-of-Service issue.

sorry for the misunderstood description, after testing now I do, I found this issue won't make the program down.

**Comment by mhils** [comment]
Thanks, that clears things up! 😃
