### ISSUE TITLE
in script ./Room.py:54 invalid syntax (simple.py, line 54)

### ISSUE THREAD

**Issue by matianhe3** [mitmproxy/mitmproxy#4707]
#### Steps to reproduce the behavior:
mitmdump -s Room.py

it shows:
`in script ./Room.py:54 invalid syntax (simple.py, line 54)`

#### System Information
Mitmproxy: 7.0.0
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Windows-10-10.0.19041-SP0

**Comment by Prinzhorn** [comment]
What is `Room.py`?
