### ISSUE TITLE
mitmproxy flagged as malware (Puamson.A!ml)

### ISSUE THREAD

**Issue by lolcat216** [mitmproxy/mitmproxy#4708]
#### Problem Description
Windows 11 Defender prevents execution of mitmproxy because it detects malware.
Detected: PUA:Win32/Puamson.A!ml

#### Steps to reproduce the behavior:
1. download and run the windows installer from:  https://mitmproxy.org/

#### System Information
mitmproxy did not execute due to malware prevention

**Comment by mhils** [comment]
Here we go again... see #4698.

**Comment by mhils** [comment]
I've rereported this as a false-positive, this should be resolved now. :)
