### ISSUE TITLE
Requests to Exchange servers with optional client certificate authentication fail

### ISSUE THREAD

**Issue by iragsdale** [mitmproxy/mitmproxy#472]
When I try to examine the conversation between an iPhone and an Exchange server configured with optional client certificate authentication, mitmproxy fails to make requests to the Exchange server.

I just see this error for the request: “← TCP connection closed unexpectedly”. However, if I disable the proxy in the iOS settings, requests succeed just fine.

If I attempt to make the same request with curl, I get "curl: (35) Server aborted the SSL handshake". If I connect to the server using openssl s_client, I can make valid requests.

If I change the server's authentication policy from "Accept client certificates" to "Ignore client certificates", mitmproxy works just fine.

So, it appears that mitmproxy (and curl) are doing something different in how they negotiate an SSL connection with the remote server. I'm not sure exactly what it might be, but it would be nice if it worked in that scenario.

**Comment by mhils** [comment]
Any way how we can reproduce that? Generally speaking, we're using OpenSSL in the backend, so it should usually work. The relevant code is  [netlib/tcp.py#L293-L321](https://github.com/mitmproxy/netlib/blob/b6af3fddf4ee2c45a722bd5087c86cee59b8cfa0/netlib/tcp.py#L293-L321).
Could it be possible that your server only supports SSLv3 or even v2? You need to pass `--ssl-version-server all/SSLv3` to enable that in mitmproxy.

Cheers,
Max

**Comment by iragsdale** [comment]
I was receiving this when attempting to watch requests for this URL: https://exchangedev.taskbox.co/Microsoft-Server-ActiveSync. 

Pretty sure it's not an SSL version issue, as I get the same error using the --ssl-version-server SSLv3 flag, but can connect just fine via 'openssl s_client -connect exchangedev.taskbox.co:443 -ssl3'.

That server is on the public internet, and you're welcome to try making some requests and see what happens.

**Comment by mhils** [comment]
Thanks for the quick response.
Not sure what's the issue here - once I remove the Host header from my request, it works. If I use openssl's s_client, it works everytime...

```python
from netlib.tcp import TCPClient

c = TCPClient(("exchangedev.taskbox.co",443))
c.connect()
c.convert_to_ssl()
c.wfile.write("""GET /Microsoft-Server-ActiveSync HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: exchangedev.taskbox.co

""")
c.wfile.flush()
print c.rfile.readline()
```

**Comment by iragsdale** [comment]
My guess is that requesting a different path on with the same host would also work. That host+path combo is set up to (in Exchange parlance) "Accept" client certificates, instead of "Ignore" or "Require" (in which case I believe this would be expected behavior).

So, I'm pretty sure there's something different about the TLS context being used, I'm just not sure what. I would imagine that the server is requesting a client certificate somehow and then ignoring an empty response, but I'm not an TLS expert.

**Comment by mhils** [comment]
This seems to be an issue with pyOpenSSL - I opened up a ticket there: https://github.com/pyca/pyopenssl/issues/190

Cheers,
Max

**Comment by iragsdale** [comment]
Thanks!

**Comment by GordonMcKinney** [comment]
I am experiencing this problem too... Is there any workaround?

**Comment by mhils** [comment]
@GordonMcKinney, this is not a mitmproxy bug and I don't see a way how we could work around this issue. :confused: For now, you can only ask the pyOpenSSL guys to look at it.

**Comment by GordonMcKinney** [comment]
Understood... I was hoping there was a workaround that I could implement... right now I'm tackling IIS and asking the server admin to disable "client certificate authentication". BTW. OSX Safari shows the same fault. So we're looking at IIS plus strict and non-strict compliance from client libraries.

**Comment by mhils** [comment]
Just discovered the root cause by accident (see the pyopenssl issue) - this is actually some really weird OpenSSL behaviour, but now that we know where it comes from I'll try to find a workaround tomorrow.

**Comment by GordonMcKinney** [comment]
I'm on OS X... if you build a beta binary I will test it over the weekend, just send me a private message.

**Comment by mhils** [comment]
We have a workaround for this in the latest netlib master now - if you install from master ([instructions](https://github.com/mitmproxy/mitmproxy#setting-up-a-dev-environment)), everything should work fine again. 0.11.4+ will ship with the workaround included.

**Comment by mhils** [comment]
@GordonMcKinney: I don't even have a Mac, so you need to install mitmproxy and netlib from source, as described above.

**Comment by GordonMcKinney** [comment]
Roger that. I'll respond later today with test results. I really appreciate your help getting a workaround in place.

**Comment by GordonMcKinney** [comment]
SUCCESS - I have run a very narrow test for a single IIS Client Cert URL... 0.11.4 works and 0.11.3 fails.

I tried building OS X binaries but the instructions and scripts fail. I'm not sure the docs are updated correctly. @mhils can you poke the volunteer that built the OS X bin? or put me in touch with him/her so I can learn what I'm doing wrong?

**Comment by mhils** [comment]
@cortesi does all of our builds. I'll push him to do a 0.11.4 rather quickly :wink:

**Comment by cortesi** [comment]
Chaps, I'm travelling at the moment, back in the office one week from now. The OSX builds are tricky and a bit time-consuming, mostly because there's a new pyinstaller bug to deal with every time. I'll try to make time to do a build in the next few days.

**Comment by GordonMcKinney** [comment]
@cortesi thanks! once you're back I'd like to learn why the packaged scripts don't build. Until then I can get our devs to repeat a dev-install and local build. I will have more rigorous testing completed this week once our Mon-Fri staff are online ;-)

**Comment by cortesi** [comment]
I've just adapted the codebase for the current PyInstaller master (see dfc1b391643d3e2d6b71d5844a48a197709ae469). Of course, nothing is that easy with PyInstaller, which delights in showing off at least one new bug every time I roll a release. The "develop" head is currently broken, so you'll have to check out the last known release, which is at 953f6e32fe50a60b9cfe343be2781db4a1d26418 to build.

I'm currently on the road, back in the office next Monday. I might not be able to roll a release before then, but it would be great if I could get a second pair of eyes over the builds using this process.

**Comment by mhils** [comment]
Speaking of a release - if we do one, we need to push a netlib release as well and fix the version in setup.py - there are some breaking API changes IIRC.

**Comment by cortesi** [comment]
Actually, zapping the PyInstaller caches has fixed the develop  branch for me - so a direct checkout of PyInstaller develop will work.
