### ISSUE TITLE
I cant sort the Timestamp column in web view

### ISSUE THREAD

**Issue by mellester** [mitmproxy/mitmproxy#4720]
#### Problem Description
I cant sort the Timestamp column in web view

#### Steps to reproduce the behavior:
1.   Add to the web_columns options `timestamp`
2.  Notice you can not sort the flow list by that Colum

#### System Information
Mitmproxy: 7.0.0
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29

**Comment by mhils** [comment]
This is fixed on main now, thanks for the report! 🍰
