### ISSUE TITLE
[docs] The section on upstream certificate sniffing is missing

### ISSUE THREAD

**Issue by hexagonrecursion** [mitmproxy/mitmproxy#4727]
#### Problem Description
I have found two dangling links in your documentation:
* On this page https://docs.mitmproxy.org/stable/overview-features there is an entry in the ToC named "Upstream Certificates"
* Here https://docs.mitmproxy.org/stable/concepts-howmitmproxyworks/#complication-1-whats-the-remote-hostname there is a link to "upstream certificate sniffing"

The target page exists, but the section about upstream certificates is missing.

**Comment by mhils** [comment]
Thanks, well-spotted!

**Comment by mhils** [comment]
https://docs.mitmproxy.org/stable/concepts-certificates/#upstream-certificate-sniffing, thanks again! 😃
