### ISSUE TITLE
Exception thrown during the WebSocket message processing.  "list index out of range.. src_ws.frame_buf[-1]"

### ISSUE THREAD

**Issue by jzlatov** [mitmproxy/mitmproxy#4732]
#### Problem Description
Exception thrown during WebSocket message processing.
This blocks additional processing of WS messages in the add-on because events are not fired.

#### Steps to reproduce the behavior:
1. Install latest version with pip (7.0.1) or from git
2. Run for example `mitmweb --listen-port 8085` (mitmdump has same issue)
3. Setup proxy `127.0.0.1:8085` in browser (latest Firefox in my case) and add certificate to trusted CA
4. Run WebSocket echo test on https://www.websocket.org/echo.html
5. Click Connect button
6. Click Send button more than once
7. You can see only one `RECEIVED` reply from the server
8. You can see exceptions in the console output of mitmweb:
```
site-packages/mitmproxy/proxy/layers/websocket.py", line 158, in relay_messages
    src_ws.frame_buf[-1] += ws_event.data.encode()
IndexError: list index out of range
```

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 7.0.1
Python:    3.8.8
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  macOS-11.5.1-x86_64-i386-64bit

**Comment by mhils** [comment]
Ooops - that's a regression in 7.0.1 :) I'll get this fixed right away.

**Comment by mhils** [comment]
7.0.2 is out, which fixes this. Thanks again! 😃
