### ISSUE TITLE
Transparent mode and DNS resolution

### ISSUE THREAD

**Issue by hinxx** [mitmproxy/mitmproxy#4739]
#### Problem Description

Intercepted flow URLs contain IP, not a DNS name.

#### Steps to reproduce the behavior:
1. Install mitmproxy on a local Linux machine acting as an AP and a router for wireless devices (i.e. Rpi3)
2. Tell the Android device to use Rpi3 as an AP
3. Configure iptables et.al as per instructions on mitmproxy docs
4. Start mitmproxy in transparent mode on Rpi3
5. Observe the URLs of the flows

#### System Information

root@raspberrypi:/home/pi# mitmproxy --version
Mitmproxy: 5.3.0
Python:    3.7.3
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.10.17-v7+-armv7l-with-debian-10.9

I've been using DNS names in my scripts while in proxy mode with much success. Now I'm playing with the transparent mode and are seeing that URLs captured by the `request(flow: http.HTTPFlow) ` all holds just IPs on which I can not apply my script logic anymore.

Is this expected or am I missing a configuration / cli switch here?

**Comment by mhils** [comment]
You want to use [`flow.request.pretty_host`](https://docs.mitmproxy.org/stable/api/mitmproxy/http.html#Request.pretty_host) and [`flow.request.pretty_url`](https://docs.mitmproxy.org/stable/api/mitmproxy/http.html#Request.pretty_url) if you want to consider HTTP host headers as well. This is not considered by default as the host header could be spoofed. To enable the same in the mitmproxy UI, set the `showhost` option to true.

**Comment by hinxx** [comment]
Nice. That works as expected. Thanks!
