### ISSUE TITLE
Warn when sending uppercase HTTP/2 headers

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#4746]
The following addon will make some requests fail with HTTP/2 protocol errors:

```python
def request(flow):
    flow.request.headers["Content-Type"] = "application/json"
```

It's not immediately obvious what's the problem here, but HTTP/2 headers may only be lowercase. We are smart enough to automatically fix that for requests that we received as HTTP/1, but otherwise we intentionally just keep things as-is. This is hard to debug for addon authors, we should emit a warning if we see uppercase HTTP/2 headers being sent.

**Comment by Kriechi** [comment]
Why do we *intentionally just keep things as-is*?
Why not apply the same smartness by default, and maybe provide a `--strict` mode or similar? Less surprises for most users, and for the advanced users, they can opt into a strict mode for tinkering with the protocols.

**Comment by mhils** [comment]
Fair point. Let's add an option and normalize by default.

**Comment by 89z** [comment]
https://github.com/mitmproxy/mitmproxy/issues/4793
