### ISSUE TITLE
[mitmweb] ft request: copy as curl

### ISSUE THREAD

**Issue by Mattwmaster58** [mitmproxy/mitmproxy#4749]
#### Problem Description

There's many a time (ok this just happened once but I think others may find this useful) where I want to copy a request in the format of a curl command for replay later.

#### Proposal

A simple button to 'copy as curl' added _somewhere_ in the GUI. I'm not sure how this would work in `mitmproxy` (if at all). 

I would be willing to look into implementing this as I could see myself using it in the future (if this is in the spirit of the project). _Depending_ on how requests are retained, this could be a little difficult (I admit I have little experience with the codebase). I opened this issue so that others could share how they think it should be implemented - any general ideas or implementation advice would be much appreciated!

#### Alternatives

copy relevant details and translate to a curl command by hand

**Comment by Mattwmaster58** [comment]
one immediate thing I could think of that would need dealing with is that very large requests - eg a POSTed file as this could result in the web UI stuttering as it tries to copy gigabytes of data to the OS'es clipboard. But perhaps I'm getting far ahead of myself here.

**Comment by mhils** [comment]
This is a good suggestion. In fact I have a local branch with massive mitmweb improvements locally that includes such a button. :) Please give it a few more days to appear, I'm in the middle of a major rewrite.

That being said, I generally really welcome contributions to mitmweb. We have instructions to set things up in ./web, if there are any questions please don't hesitate to ping me on Slack as well. :)

**Comment by Prinzhorn** [comment]
@mhils https://github.com/mitmproxy/mitmproxy/pull/4523 :eyes:

**Comment by mhils** [comment]
@Prinzhorn: yes, thanks - I'm aware. It's evolved a bit 😉 

![image](https://user-images.githubusercontent.com/1019198/129161533-60c0f78d-1eb8-424e-85c5-1c00ab2b59f2.png)

**Comment by Mattwmaster58** [comment]
Wow, that's fantastic. Eagerly await this feature.

**Comment by mhils** [comment]
This is available on main and in the development snapshots now (https://mitmproxy.org/downloads/#branches/main/). 😃🍰

**Comment by yangmeishu** [comment]
why 7.0 not have this feature 
![image](https://user-images.githubusercontent.com/20120067/149627396-5fecb7fe-1511-4b4f-834f-1bee566d4af6.png)

**Comment by mhils** [comment]
It will be part of the next release, 7.0 is older than the implementation.

**Comment by yangmeishu** [comment]
very very thanks

**Comment by xuyooo** [comment]
why 10.x not have this feature?
![image](https://github.com/mitmproxy/mitmproxy/assets/33961343/174db61a-fde7-42db-a42d-49990acdc40e)

**Comment by Prinzhorn** [comment]
This is what I see in 10.2.2

![image](https://github.com/mitmproxy/mitmproxy/assets/679144/0f755c96-a69a-4fe4-ba0e-7c4660f737e7)

Try clearing your cache, you might load old frontend code

**Comment by xuyooo** [comment]
already clear my cache，Still not seen that     How do I check the version?
