### ISSUE TITLE
Multipart Form: Modify part attributes

### ISSUE THREAD

**Issue by Bebras20** [mitmproxy/mitmproxy#4750]
#### Problem Description
In order to modify a file content upload operation on the fly, I use the following line 

flow.request.multipart_form["file".encode("utf-8")] = bytes.fromhex(st_file)

However the upload fails because it is not parsing my modifications correctly You can see below two figures that show two requests the first is the correct one seen from mitmproxy perspective and second one is the falty one that I copied from mitmproxy too .

![image](https://user-images.githubusercontent.com/83237585/129216473-a31d238a-a27f-463d-86e8-eb27b8bd76ce.png)

![image](https://user-images.githubusercontent.com/83237585/129216769-1fe74206-bf70-43e9-a2cf-2f30b84bef35.png)

As you can see, the only difference resides in the Content-Type header which is application/octet-stream in the correct one and text/plain; charset=utf-8 in the faulty one so how can I force flow.request.multipart_form to use the appropriate Content-Type

#### System Information
mitmproxy --version : 7.0.1

**Comment by mhils** [comment]
Thanks for raising this! It looks like we just apply rather dumb heuristics here:

https://github.com/mitmproxy/mitmproxy/blob/92518f3b67c4c91188eb0450012942790dae688f/mitmproxy/net/http/multipart.py#L21

_Ideally_ we need to do something similar to what we do for `set-cookie`, where we keep a separate dict of attributes around. But that's not that trivial. For now the best workaround probably is to manually do `flow.request.content = flow.request.content.replace(...)`.

**Comment by Bebras20** [comment]
Thx @mhils the trick you mentioned works like a charm ! 
I'm going to close this issue.
