### ISSUE TITLE
Cannot inject websocket with binary or string content.

### ISSUE THREAD

**Issue by TonicBoomerKewl** [mitmproxy/mitmproxy#4751]
#### Problem Description
mitmproxy attempts to parse the injected websocket binary data as text, and replaces the binary data if it cannot be decoded into text, changing the injected websocket message. Also, when a string is given instead, there is error:
File "\mitmproxy\proxy\layers\websocket.py", line 230, in msg
    data_str = data.decode(errors="replace")
AttributeError: 'str' object has no attribute 'decode'

#### Steps to reproduce the behavior:
1. from mitmproxy.ctx import master
2. master.commands.call("inject.websocket", flow, False, bytes([i for i in range(256)])) # No error, but message contents are changed
3. master.commands.call("inject.websocket", flow, False, "string") # AttributeError

#### System Information
Mitmproxy: 7.0.2
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Windows-10-10.0.19043-SP0

**Comment by Prinzhorn** [comment]
In both cases `bytes` is expected and the last argument `is_text` specifies what type of message you want to inject:

https://github.com/mitmproxy/mitmproxy/blob/ab6f1ebb4415620ce02d61d0ff1c72e6b84b5198/mitmproxy/addons/proxyserver.py#L193

In your first example the bytes are treated as TEXT frame, hence why "mitmproxy attempts to parse the injected websocket binary data as text". In the second example you are passing a string, but utf-8 bytes are expected.

I'm not even sure where this is in the docs, but I'll mark it as a docs issue

**Comment by TonicBoomerKewl** [comment]
The only place where I can find how to inject websocket in the docs is [websocket-inject-message.py example](https://docs.mitmproxy.org/stable/addons-examples/#websocket-inject-message). In the example, the string "ssssssh" is injected, which should result in error.

**Comment by Prinzhorn** [comment]
Yep, this was an oversight here https://github.com/mitmproxy/mitmproxy/pull/4650 The example needs to be fixed.

**Comment by mhils** [comment]
@Prinzhorn: Would you mind sending a quick PR? ❤️
