### ISSUE TITLE
start up  mitmproxy  error

### ISSUE THREAD

**Issue by 492456131** [mitmproxy/mitmproxy#4753]
![image](https://user-images.githubusercontent.com/16437314/129428219-462c12a6-8966-430d-9083-0475332ed1e7.png)
![image](https://user-images.githubusercontent.com/16437314/129428457-80a6cd17-3917-4b92-88fa-d3dba2d742e5.png)

**Comment by 492456131** [comment]
![image](https://user-images.githubusercontent.com/16437314/129428445-8f41faa0-8e79-4d12-ac88-1c85843738f4.png)

**Comment by Christsnatcher** [comment]
Hello, I'm facing the very same error when running mitmproxy.exe:

https://i.gyazo.com/a5dcdd07fa10a3961d1727a8e5eccf37.png

https://i.gyazo.com/dc30b5c98d58885f73a723dfe3f1bddc.png

mitmdump.exe and mitmprox.exe work properly, though.

**Comment by mhils** [comment]
Which command line she'll are you two using? PowerShell? CMD.exe? Windows Terminal?

**Comment by Christsnatcher** [comment]
For me the mitmproxy.exe gives the very same error when run directly (the process just terminates too quickly to get a proper picture), when being run in a cmd.exe or PowerShell terminal, no difference.

**Comment by 492456131** [comment]
Cmd running on window 7

**Comment by mhils** [comment]
Thanks for clarifying! We rely on some console improvements in Windows 10 for mitmproxy. You either need to upgrade or you need to restrict yourself to mitmdump and mitmweb.
