### ISSUE TITLE
Support change options like Web does in code.

### ISSUE THREAD

**Issue by scruel** [mitmproxy/mitmproxy#4757]
#### Proposal
Web page can change the mitmproxy options without restart the client, how to do it by python code?
![图片](https://user-images.githubusercontent.com/16933298/129473618-fcaa7992-ed67-4e46-81c1-7b41f8b87fa3.png)

**Comment by mhils** [comment]
mitmproxy's console interface offers the same capabilities from its options menu. Addons can modify `mitmproxy.ctx.options`, which also works without restart 😃

**Comment by scruel** [comment]
> 
> 
> mitmproxy's console interface offers the same capabilities from its options menu. Addons can modify `mitmproxy.ctx.options`, which also works without restart 😃

Thanks, found it here:
https://docs.mitmproxy.org/stable/addons-options/

Got work with the funtion:
ctx.options.update()
