### ISSUE TITLE
tls_early_post_process_client_hello, unsupported protocol 

### ISSUE THREAD

**Issue by nmweizi** [mitmproxy/mitmproxy#4758]
Mitmproxy: 7.0.2
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Windows-10-10.0.19043-SP0

```
127.0.0.1:53924: Client TLS handshake failed. The client may not trust the proxy's certificate for www.drumlinsecurity.co.uk (OpenSSL Error([('SSL routines', 'tls_early_post_process_client_hello', 'unsupported protocol')]))
```

but 6.0.2 is ok.

**Comment by mhils** [comment]
We need more info to reproduce this. Could you provide a PCAP?

**Comment by nmweizi** [comment]
> We need more info to reproduce this. Could you provide a PCAP?

thx.
Can it be sent by email?

**Comment by mhils** [comment]
Email is on my profile if you have sensitive data in there. :)

**Comment by nmweizi** [comment]
Sent mail, please check

**Comment by mhils** [comment]
Thanks for sending along the PCAP! Can you reproduce this with
```
mitmdump --set tls_version_client_min=SSL3
```
?

**Comment by nmweizi** [comment]
> Thanks for sending along the PCAP! Can you reproduce this with
> 
> ```
> mitmdump --set tls_version_client_min=SSL3 --set tls_version_server_min=SSL3
> ```
> 
> ?
After setting it is correct.
Thank you very much.

**Comment by mhils** [comment]
The version order is: SSLv3, TLS 1.0, TLS 1.1, TLS 1.2, TLS 1.3.

Your client only supports TLS 1.0. We had a bug in 7.0.2 which disabled the TLS 1.0 option, so I had to use SSL3, which is one lower.

**Comment by Juanpam** [comment]
@mhils Hey! I faced this same issue while trying to provide support for a client that uses TLS 1.0 to no avail. Setting the option to SSL3 doesn't work neither to TLS_1_2. Is this an issue? are you no longer supporting TLS_1_0? Or how can I use it?

**Comment by mhils** [comment]
TLS 1.0 should work fine with the command from https://github.com/mitmproxy/mitmproxy/issues/4758#issuecomment-903267079. Can you reproduce it with `curl --tlsv1.0`?

**Comment by Juanpam** [comment]
@mhils Sorry for the late response, but yes it still fails. The curl version I'm using is curl 7.19.7 (i486-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k zlib/1.2.3.3 libidn/1.15 (Pretty old, I know). Requests made with curl --tlsv1 (which is the option for my curl version) end up with the following error:

error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed.

I'm using a cert with the --certs option that I created by chaining the certificate, private key and the certificate chain. Although curl does not work, another software that is also performing requests is able to use the proxy without issue. 

wget fails tough.
