### ISSUE TITLE
response method behavior in case of get-request for large file. 

### ISSUE THREAD

**Issue by VishalJadhav90** [mitmproxy/mitmproxy#476]
Hello, 

I am trying to access fairly large mp3 file using http-get method. 
Description of response method says that call-back will happen when server response has been received. 

So my question is, will callback happen as soon as response to http-get is received (beginning of mp3 transfer) or after last byte of mp3 file has been transferred. 
 
def response(context, flow):
    """
       Called when a server response has been received.
    """
    context.log("response")

P.S: I am not sure whether this is right place to put query or not, if not sorry for the mess.

**Comment by mhils** [comment]
Hi there,

I think you could have answered that question by yourself if you just tried it out. Anyway, http://mitmproxy.org/doc/features/responsestreaming.html might be helpful.

Cheers,
Max
