### ISSUE TITLE
Multithreaded WSGI apps seem to block

### ISSUE THREAD

**Issue by zbuc** [mitmproxy/mitmproxy#477]
##### Steps to reproduce the problem:

In Netlib, it looks like multithreading is enabled on the WSGIAdaptor class that mitmproxy uses: https://github.com/mitmproxy/netlib/blob/master/netlib/wsgi.py#L53

However a simple Flask app that should be able to take advantage of thread switching seems to block on a single thread (_and_ block the main mitmproxy threads as well, making the console UI non-responsive): https://gist.github.com/zbuc/9ae9aed56914df70f462
##### What is the expected behavior?

You should be able to access the main index page while waiting on the thread running `/slow` to sleep.
##### What went wrong?

The main index (and the main mitmproxy UI) go non-responsive until `/slow` finishes loading

---

mitmproxy version: 0.11.4
Operating System: Mac OS X 10.10.2

**Comment by mhils** [comment]
Thanks for the excellent report. We currently have the `@concurrent` decorator for inline scripts, but as you pointed out, wsgi apps are still single-threaded. Wrapping [this code](https://github.com/mitmproxy/mitmproxy/blob/bd6c3f64c1f3102a4e91d4a964757821773781e0/libmproxy/flow.py#L909-L916) in a separate thread should be sufficient. We'll fix that for the next release, but it may take a bit as @cortesi and I are fairly busy at the moment. As always, PRs in the meantime are appreciated. :smiley:

Cheers,
Max

**Comment by mhils** [comment]
Fixed!
