### ISSUE TITLE
jsondump.py not working as expected

### ISSUE THREAD

**Issue by suntong** [mitmproxy/mitmproxy#4770]
Following

https://github.com/mitmproxy/mitmproxy/blob/a92eb1c4c8e300c38592d4044dee694d1b69b56b/examples/contrib/jsondump.py#L9-L11

I tried 

`mitmproxy -s /path/to/jsondump.py`

and with

```
  $ cat ~/.mitmproxy/config.yaml
  dump_destination: "/tmp/mitmproxy.log.json"
```

But I always get

`ls: cannot access '/tmp/mitmproxy.log.json': No such file or directory`

even when mitmproxy is closed.

Adding a "`-w`" option is not helping either.

**Comment by mhils** [comment]
Please check the maintenance section:

https://github.com/mitmproxy/mitmproxy/blob/main/examples/contrib/README.md#maintenance
