### ISSUE TITLE
Move check of recursive connection later in the pipeline

### ISSUE THREAD

**Issue by mario-purestake** [mitmproxy/mitmproxy#4775]
#### Problem Description

Using a `mode:reverse` configuration, the proxy always makes a connection to the endpoint set on the mode CLI parameter, even if later in the processing, on the addons, we set the host to another endpoint. This makes the proxy to connect to the first endpoint for **every** incoming request, which may incur on overloading that endpoint even when we are actively redirecting the traffic later in the processing.

#### Proposal

One workaround for this would be setting the `mode:reverse` CLI parameter endpoint as the endpoint of the proxy itself, assuming that the endpoint will be changed during the processing. However, this is not possible because the check of making a recursive connection is before the addons are executed. The proposal is to either move this check later, or make the proxy not kill the flow when attempting a recursive connection, and instead just avoid the connection.

#### Alternatives
Open for more ideas :)

#### Additional context
None.

**Comment by mhils** [comment]
Have you tried setting `connection_strategy` to `lazy`? That should solve exactly the problem of too early connects. :)

**Comment by mario-purestake** [comment]
Ouch! Didn't try that and it seems to completely solve my problem. Closing the issue then.

Thanks!
