### ISSUE TITLE
python print chinese language error

### ISSUE THREAD

**Issue by ctccaozhe** [mitmproxy/mitmproxy#4784]
#### Problem Description
When I get a web page with Chinese, I find that all Chinese in the html is abnormal

#### Steps to reproduce the behavior:
The screenshot of the problem is as follows. The Chinese displayed in the web output of mitmproxy is normal, but I use `flow.response.get()` in Python, print is error

The code snippet I used is as follows
- addons.py
```
import sys
# -*- coding: utf-8 -*-
sys.path.append("./venv/lib/python3.9/site-packages/")

addons = [
    counter.Counter(),
    joker.Joker(),
]
```
- joker.py
```
class Joker:
    def response(self, flow: mitmproxy.http.HTTPFlow):
        print("-------------------------------------")
        print("flow.request.url:")
        print(flow.request.url)
        print("uri:")
        print(uri)
        print("uri.path:")
        print(uri.path)
        print("uri.netloc:")
        print(uri.netloc)
        print(type(text))
        print("flow.response.headers:")
        print(type(flow.response.headers))
        print(flow.response.headers.get("Content-Type"))
        print(flow.response)
        print("flow.request.method:")
        print(flow.request.method)
        print("flow.request.headers:")
        print(type(flow.request.headers))
        print(flow.response.get_text())
```
- counter.py
```
import mitmproxy.http
from mitmproxy import ctx


class Counter:
    def __init__(self):
        self.num = 0

    def request(self, flow: mitmproxy.http.HTTPFlow):
        self.num = self.num + 1
        ctx.log.info("We've seen %d flows" % self.num)
```

- run shell
```sh
mitmweb -s addons.py
```

[![haY8KO.md.png](https://z3.ax1x.com/2021/08/31/haY8KO.md.png)](https://imgtu.com/i/haY8KO)
[![haYGrD.md.png](https://z3.ax1x.com/2021/08/31/haYGrD.md.png)](https://imgtu.com/i/haYGrD)

#### System Information

```
mitmproxy --version
Mitmproxy: 7.0.2
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  macOS-10.16-x86_64-i386-64bit
```

> English is not very good, sorry
> If there is anything unclear, let me add
> Thank you for helping me

**Comment by mhils** [comment]
Thanks for the detailed report! 😃 

The problem here is that mitmproxy did not pick up `<meta charSet="utf-8"/>` because our regex only matched on `charset` and not on `charSet`. #4785 fixes this. 

You can:

1. Wait for the next release.
2. Install a development snapshot from https://snapshots.mitmproxy.org/branches/main/ (should be updated in ~10mins)
3. Use `flow.request.content.decode("utf8")` for this specific instance.
