### ISSUE TITLE
Memory constantly growing when using mitmdump

### ISSUE THREAD

**Issue by mario-purestake** [mitmproxy/mitmproxy#4786]
Related to #4456, but this is for HTTP traffic.

#### Problem Description

We are using MITMProxy (`mitmdump`) as a reverse proxy, running in a container. We are processing lots of incoming HTTP requests, that we forward on the proxy to a pool of nodes, that serve the response to the client. As you can see in the graph below, the memory of this container is never freed, it either stays flat or grows constantly until reaching what we currently set as maximum (8GB). The flat lines are not related to traffic, that is constantly coming to the proxy.

![image](https://user-images.githubusercontent.com/66425016/131492463-a4084bc5-9f3d-4057-b956-f63b1a75fdb0.png)

Looking at the snippet on the related issue (https://github.com/mitmproxy/mitmproxy/issues/4456#issuecomment-780710897), we sent `SIGUSR1` to the same proxy configuration on another environment that has a limit of 2GB. These are the results when the memory was growing and around 980MB:

```
****************************************************
Summary
=======

Threads
=======
(...)

Memory
=======
51 <class 'mitmproxy.proxy.layers.modes.ReverseProxy'>
51 <class 'mitmproxy.proxy.layers.http.HttpLayer'>
51 <class 'mitmproxy.proxy.layers.http._http1.Http1Server'>
51 <class 'mitmproxy.proxy.server.TimeoutWatchdog'>
72 <class 'mitmproxy.optmanager._Option'>
102 <class 'mitmproxy.proxy.layer.NextLayer'>
175 <class 'mitmproxy.proxy.layers.http._http1.Http1Client'>
175 <class 'mitmproxy.proxy.layers.http.HttpClient'>
175 <class 'mitmproxy.proxy.server_hooks.ServerConnectionHookData'>
175 <class 'mitmproxy.proxy.commands.OpenConnection'>
226 <class 'mitmproxy.connection.Server'>
277 <class 'mitmproxy.proxy.server.ConnectionIO'>
44111 <class 'mitmproxy.proxy.context.Context'>
43834 <class 'mitmproxy.proxy.layers.http.HttpStream'>
43834 <class 'mitmproxy.http.HTTPFlow'>
43834 <class 'mitmproxy.http.Response'>
43834 <class 'mitmproxy.http.Request'>
43834 <class 'mitmproxy.http.ResponseData'>
43834 <class 'mitmproxy.http.RequestData'>
87668 <class 'mitmproxy.http.Headers'>
```

I don't think that the proxy has that amount of connections open, so there is something that is keeping these flows to be cleaned after they finish.

#### Steps to reproduce the behavior:
1. Run `mitmdump` in `mode:reverse`.
2. Send lots of HTTP requests to the proxy (a rate of 100req/s should be enough)
3. Wait for the container to reach the memory limit, being killed due to an OOM.
4. (opt) Send `SIGUSR1` to the process within the container to get a report of the memory contents.

#### System Information
Using a docker container and `mitmdump`:

```shell
Mitmproxy: 7.0.0
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.11.0-27-generic-x86_64-with-glibc2.28
```

Also, we're using custom addons to: redirect the traffic to a pool of nodes, expose Prometheus metrics and applying rate limiting to incoming requests.

**Comment by mhils** [comment]
Thanks for the excellent report! 🍰 

So there's obviously something holding references to these flows, we just need to figure out what it is! 😄 
What happened to the Flow References section from the script you posted? That code there may not be robust and need some tweaking, but it would be a first attempt at figuring out where references are held.

**Comment by mario-purestake** [comment]
So I'm having some trouble with that script. It's reporting `TypeError: issubclass() arg 1 must be a class` for the line where you evaluate the instance of the object:

```

print()
print("Flow References")
print("===============")
objs = gc.get_objects()
for i in range(len(objs)):
    if isinstance(objs[i], flow.Flow):  # <------------- HERE
        print(f"{objs[i]}")
        holder = {"val": objs[i]}

```

So I changed it for:

```
if isinstance(type(objs[i]), flow.Flow): 
```

And now it doesn't fail, but it's returning `No Flows!`, so I don't know if it's doing the right thing. This is the full report when the proxy is in a similar state:

```
Memory
=======
333710 <class 'mitmproxy.http.Headers'>
167261 <class 'mitmproxy.proxy.context.Context'>
166862 <class 'mitmproxy.http.Request'>
166862 <class 'mitmproxy.http.RequestData'>
166861 <class 'mitmproxy.proxy.layers.http.HttpStream'>
166861 <class 'mitmproxy.http.HTTPFlow'>
166848 <class 'mitmproxy.http.Response'>
166848 <class 'mitmproxy.http.ResponseData'>
400 <class 'mitmproxy.proxy.server.ConnectionIO'>
300 <class 'mitmproxy.connection.Server'>

Flow References
===============
No flows!

```

**Comment by mhils** [comment]
Not sure what's causing the TypeError, but let's just wrap the if clause with a big `try: if ... Except TypeError: pass`  clause. I guess you have some objects in there which `isinstance` doesn't like. Shouldn't matter for the actual Flows. Does that make sense?

**Comment by mario-purestake** [comment]
Okay, that made it work well :) It shows that there is only one active flow (I guess?). If that's the case, it's what is currently happening, we're sending all this test traffic from only one location. And doing it like this we have the same memory increase, so I would say is unrelated to the number of open flows.

```
Memory
=======
172922 <class 'mitmproxy.http.Headers'>
86871 <class 'mitmproxy.proxy.context.Context'>
86471 <class 'mitmproxy.proxy.layers.http.HttpStream'>
86471 <class 'mitmproxy.http.HTTPFlow'>
86471 <class 'mitmproxy.http.Request'>
86471 <class 'mitmproxy.http.RequestData'>
86451 <class 'mitmproxy.http.Response'>
86451 <class 'mitmproxy.http.ResponseData'>
400 <class 'mitmproxy.proxy.server.ConnectionIO'>
300 <class 'mitmproxy.connection.Server'>

Flow References
===============
<HTTPFlow
  client_conn = Client(w1.x1.y1.z1:57391, state=open)
  server_conn = Server(w2.x2.y2.z2:8080, state=open, src_port=47796)>
  len(referrers)=1 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.proxy.layers.http.HttpStream'>
  len(referrers)=4 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.proxy.layers.http.HttpLayer'>
  len(referrers)=886 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.proxy.layer.NextLayer'>
  len(referrers)=2 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.proxy.layers.modes.ReverseProxy'>
  len(referrers)=4 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.proxy.layer.NextLayer'>
  len(referrers)=1 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.addons.proxyserver.ProxyConnectionHandler'>
  len(referrers)=9 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.addons.proxyserver.Proxyserver'>
  len(referrers)=104 type(referrers[0])=<class 'list'>
  len(referrers)=2 type(referrers[0])=<class 'dict'>
  len(referrers)=1 type(referrers[0])=<class 'mitmproxy.addonmanager.AddonManager'>
  len(referrers)=2 type(referrers[0])=<class 'dict'>

```

**Comment by mhils** [comment]
There are 86471 flow objects if you look at the memory section, we just decide to print just one. 😅 Which.. in this case looks like one that is still ongoing, the reference being held here is to be expected. Do you have a way to stop all traffic, then wait a bit, then send SIGUSR1? Alternatively, remove the `break` and capture some of the later output?

FWIW if I stop sending stuff to mitmproxy I get the "No flows" message, I can't reproduce this at all so far.

**Comment by mario-purestake** [comment]
Oh, okay! My bad then, I didn't notice the HTTPFlow count :sweat_smile: 

I did the first and stopped and waited a bit between reports. The first report right before stopping the traffic was the same as before, with tons of flows open. I waited around 20s after stopping it to repeat and then the report came empty:

```
Memory
=======
72 <class 'mitmproxy.optmanager._Option'>
43 <class 'mitmproxy.command.Command'>
2 <class 'mitmproxy.types.Choice'>
2 <class 'mitmproxy.addons.script.Script'>
1 <class 'mitmproxy.types.TypeManager'>
1 <class 'mitmproxy.types._BoolType'>
1 <class 'mitmproxy.types._ChoiceType'>
1 <class 'mitmproxy.types._CmdType'>
1 <class 'mitmproxy.types._CutSpecType'>
1 <class 'mitmproxy.types._DataType'>

Flow References
===============
No flows!
```

This was also noticed on memory consumption, having a drop from 1.8GB to around 800MB, although having now the memory empty I would have expected to go lower :thinking: 

![image](https://user-images.githubusercontent.com/66425016/131569739-c9a0943d-d4b9-4c42-b746-47f70ddced62.png)

**Comment by mhils** [comment]
Oh, that is interesting. Let's first focus on why flows are disappearing now: Are you using HTTP keepalive for all requests, i.e. is there a bunch of persistent connections?

**Comment by mario-purestake** [comment]
Hey @mhils, sorry for the delay, I took some days off :sweat_smile: Continuing with the discussion, the requests don't have the Keep-Alive header, so I guess they're not having a persistent connection

**Comment by mhils** [comment]
Sorry, missed your reply in my inbox! :)

HTTP/1.1 and HTTP/2 default to keepalive. Could you test if adding a `Connection: close` header changes anything? The following addon should do the trick:

```python3
def request(flow):
    flow.request.headers["Connection"] = "close"

def response(flow):
    flow.response.headers["Connection"] = "close"
```

**Comment by mario-purestake** [comment]
No worries :) I'll give it a try and let you know :+1:

**Comment by mhils** [comment]
For the record, the problem here is that we currently keep flows in memory until the associated connection is closed. My workaround in https://github.com/mitmproxy/mitmproxy/issues/4786#issuecomment-928002790 makes sure that this happens after each request. What we need to do in the future is to clean up completed HTTP streams while the connection is still running.

**Comment by ericdraken** [comment]
> > 
> 
> > Sorry, missed your reply in my inbox! :)
> > HTTP/1.1 and HTTP/2 default to keepalive. Could you test if adding a `Connection: close` header changes anything? The following addon should do the trick:
> > ```python
> > def request(flow):
> >     flow.request.headers["Connection"] = "close"
> > 
> > def response(flow):
> >     flow.response.headers["Connection"] = "close"
> > ```
> 
> this resolve my problem, the mitmdump memory usage remain constant below 250M now. thanks!

With the above trick, RSS initially bounces between 170 MiB and ~280 MiB before the GC kicks in, but if enough time passes, the RSS still grows, but much more slowly. The effect is dramatic when watching 4K videos on youtube. For instance, now it takes 18 minutes to reach 400 MiB RSS whereas without the above trick it took 2 minutes. I sent a good chunk of the day profiling this and have no solution yet.

**Comment by bratao** [comment]
I confirm that https://github.com/mitmproxy/mitmproxy/issues/4786#issuecomment-928002790 workaround is not enough. The memory is still growing, just slower. 

I have a very long-lived mitmproxy instance to mitm all traffic of a network with high usage. I have to restart the process every couple of hours to avoid memory exhaustion in the machine 😢

**Comment by minofmax** [comment]
I wonder is there still a connection in memory when I kill a flow by flow.kill()?
I use flow.kill to drop some useless connctions, but the memroy is still growing. I am so confused.

**Comment by mhils** [comment]
Quick Update: We've just shipped 8.1.0, which greatly alleviates memory issues and renders the workaround posted above superfluous. There are some final parts that depend on a new cryptography release (https://github.com/mitmproxy/mitmproxy/pull/5340), which will make it into the next release. :)

**Comment by fuomag9** [comment]
This seems to be still happening with the latest release :(

**Comment by mhils** [comment]
@fuomag9: please feel free to open a new issue with a self-contained reproducible example.

**Comment by Srijan67** [comment]
> Sorry, missed your reply in my inbox! :)
> 
> HTTP/1.1 and HTTP/2 default to keepalive. Could you test if adding a `Connection: close` header changes anything? The following addon should do the trick:
> 
> ```python
> def request(flow):
>     flow.request.headers["Connection"] = "close"
> 
> def response(flow):
>     flow.response.headers["Connection"] = "close"
> ```

do we still need to add this as a workaround in version 10 as well ? Or is this bug fixed now @mhils
