### ISSUE TITLE
Set flow.request.headers["transfer-encoding"] = "chunked" in addon, transfer-encoding will be automatically deleted

### ISSUE THREAD

**Issue by nmweizi** [mitmproxy/mitmproxy#4787]
- version
Mitmproxy: 7.0.2
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.1.2-x86_64-i386-64bit

- mitmproxy -s s.py -p 9090 --mode upstream:http://127.0.0.1:8080
  Set flow.request.headers["transfer-encoding"] = "chunked" in addon,from the  proxy 8080,,after proxy 9090, transfer-encoding will be automatically deleted
- s.py
```
        elif flow.request.is_http11:
            if not flow.request.content:
                # Avoid sending a body on GET requests or a 0 byte chunked body with trailers.
                # Otherwise some servers return 400 Bad Request.
                return
            # HTTP 1.1 requires transfer-encoding: chunked to send trailers
            flow.request.headers["transfer-encoding"] = "chunked"
```

**Comment by mhils** [comment]
I can't reproduce this locally (excuse the crappy screenshot):

![image](https://user-images.githubusercontent.com/1019198/131517838-2998daa6-c725-4bad-94cb-dee4b89eac22.png)

`s.py`
```
def request(flow):
    flow.request.headers["transfer-encoding"] = "chunked"
```

**Comment by nmweizi** [comment]
Thank you very much.
The test found that the back-end proxy parsing problem.
