### ISSUE TITLE
win11 wsl crash on exit

### ISSUE THREAD

**Issue by Dragonphy** [mitmproxy/mitmproxy#4788]
#### Problem Description
I install the linux package in the wsl1, and put the binary in the /usr/local/bin/mitmproxy.
It runs `mitmproxy` well when I use the command `mitmproxy`, but it crashes when I quit the mitmproxy.
When I try to run any other commands like `mitmproxy --version`, the laptop crashes and the green screen appears

#### Steps to reproduce the behavior:
1.  Enter the wsl environment
2.  run `mitmproxy --version`

#### System Information
windows version: win11 dev 22000.168
mitmproxy: 7.0.2

**Comment by mhils** [comment]
I'm running mitmproxy under WSL1 and WSL2 just fine. What kind of crash are you seeing?
