### ISSUE TITLE
Problem forwarding iOS SSL requests?

### ISSUE THREAD

**Issue by mkonecny** [mitmproxy/mitmproxy#479]
Having a really strange issue. We have an app written for both Android and iOS.

I set mitmproxy to listen on port 443, and forward all requests to our nginx server on port 80. The following command is used:

`sudo mitmproxy -R https2http://localhost:80/ -p 443 --cert cert.pem`

Android requests are forwarded just fine. They are simple POST/GET requests. The equivalent requests in iOS do not work if mitmproxy is in the middle - and work fine otherwise.

Here is what I see:
a) in mitmproxy, the request is red, with reason
`HttpError("Invalid server response: '<head><title>400 Bad Request</title></head>\\r\\n'",)`
b) in nginx access.log, I see random hex values where I would normally see the HTTP verb and path. Example:

```
127.0.0.1 - - [19/Feb/2015:02:03:46 +0000] "\x16\x03\x01\x01L\x01\x00\x01H\x03\x03\x88#\xCE\x0F?\xD1\xC9\xBF\x8C\x0C:|*\x92{-\x96\x92\x8CM*\xA2\xF7)o\xBF\x9Cl\xDB\x953\xDA\x00\x00\x92\xC00\xC0,\xC0(\xC0$\xC0\x14\xC0" 400 166 "-" "-"
```

Any hints on where I should start poking around?

**Comment by mkonecny** [comment]
One additional note. I am able to get it working if I use

`sudo mitmproxy -R https://localhost:444/ -p 443 --cert cert.pem` 

That is, I don't "translate" the request from https to http.

**Comment by mhils** [comment]
Hm, I have no good idea yet why this could be happening. Could you post the output of `mitmdump -dd -vvv [+ your other parameters]` for a failing request?

**Comment by mkonecny** [comment]
Interestingly enough, Android and curl no longer work as well - this leads me to believe I may be doing something wrong?

`sudo mitmdump -dd -vvv -R https2http://localhost:80 -p 443 --cert cert.pem`

```
x.x.x.x:59346: clientconnect
x.x.x.x:59346: Set new server address: localhost:80
x.x.x.x:59346: serverconnect
  -> localhost:80
x.x.x.x:59346: Establish SSL
  -> with client
x.x.x.x:59346: SNI received: api-dev.example.com
x.x.x.x:59346: (server reconnect follows)
x.x.x.x:59346: serverdisconnect
  -> localhost:80
x.x.x.x:59346: Set new server address: localhost:80
x.x.x.x:59346: serverconnect
  -> localhost:80
x.x.x.x:59346: Establish SSL
  -> with server (sni: api-dev.example.com)
x.x.x.x:59346: Error in handle_sni:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 288, in handle_sni
    self.server_reconnect(sni)  # reconnect to upstream server with SNI
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 241, in server_reconnect
    self.establish_ssl(server=True, sni=sni)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 202, in establish_ssl
    raise e
ProxyError: NetLibError("SSL handshake error: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'unknown protocol')],)",)

x.x.x.x:59346: request
  -> GET / HTTP/1.1
x.x.x.x:59346: HttpError("Invalid server response: '<head><title>400 Bad Request</title></head>\\r\\n'",)
x.x.x.x GET http://localhost/
    User-Agent: curl/7.38.0
    Host: api-dev.example.com
    Accept: */*

 << HttpError("Invalid server response: '<head><title>400 Bad Request</title></head>\\r\\n'",)


x.x.x.x:59346: clientdisconnect
x.x.x.x:59346: serverdisconnect
  -> localhost:80
```
Corresponding entry in nginx log:

`127.0.0.1 - - [19/Feb/2015:03:38:20 +0000] "\x16\x03\x01\x01K\x01\x00\x01G\x03\x03\xC6 \x80j\xE2[\x0B\x90\xAAF\xBA\x94\x02\x22_\xE8\xE59\xEA\x96Oit\xB8)\xFB\xA3W\xB5\xA8xK\x00\x00\x92\xC00\xC0,\xC0(\xC0$\xC0\x14\xC0" 400 166 "-" "-"
`

From the same terminal I run mitmproxy, if I do `curl http://localhost` it works perfectly fine.

**Comment by mhils** [comment]
Thanks for the quick feedback - the log is definitely very helpful. We'll fix that for the next patch release, but it may take a while before I have some spare time.

Cheers,
Max

**Comment by mhils** [comment]
Hi Martin,

thanks again for the good report - I just commited a fix for the issue you were seeing. You can either install our development version for now or wait for the next release. :-)

Cheers,
Max
