### ISSUE TITLE
Mitmproxy crashes on startup when listen port is unavailable, should print a nicer error instead

### ISSUE THREAD

**Issue by OuterCloud** [mitmproxy/mitmproxy#4796]
#### Problem Description

![image](https://user-images.githubusercontent.com/16227179/132525810-ad4fcf7a-e9e9-4045-a51b-ac589bc9e7bb.png)

#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.

**Comment by Prinzhorn** [comment]
Please fill out the template (mitmproxy version, OS)

You have blurred out the listen_host, I assume it's the public IP address of the machine? Are you sure you can bind, e.g. does `nc -l -s THE_BLURRED_IP -p 8080` work?

**Comment by mhils** [comment]
The problem here is clearly that the port is already taken, but we shouldn't crash so violently in this case.

**Comment by mhils** [comment]
Fixed in mitmproxy 8!
