### ISSUE TITLE
Editing body results in an error for Windows

### ISSUE THREAD

**Issue by Vzurxy** [mitmproxy/mitmproxy#4798]
#### Problem Description
When trying to edit the body of either response or request on Windows, it will have failed to start the editor (vi) because vi is not pre-installed on Windows. Visual Studio Code and Sublime Text when put in the EDITOR variable fail to work (Sublime Text opens the file but does not show the file contents as it should), and the only alternative is NVIM, but some people prefer using their mouse to get around

GitHub link to file: https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/tools/console/master.py

#### Steps to reproduce the behavior:
1. Use Windows 10
2. Intercept any request
3. Attempt to edit response body/request body

#### System Information
Mitmproxy: 7.0.2 binary
Python:    3.9.6
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Windows-10-10.0.19043-SP0

**Comment by mhils** [comment]
Eh, good catch - thanks. We should:

- [ ] change the default fallback to `nano` (`vi` users can set $EDITOR, `nano` users don't need to know how to do that)
- [ ] figure out what we can do on Windows. Maybe save it as .txt and open the default editor for that?

**Comment by mhils** [comment]
Related work: https://github.com/pallets/click/blob/c1a42a1c545c138266be61c7b0fda02b9a423fe0/src/click/_termui_impl.py#L467-L479
