### ISSUE TITLE
Version 7.0.2 of the binary ships with and/or creates expired root cert on first install.  Event log: "warn: The mitmproxy certificate authority has expired"

### ISSUE THREAD

**Issue by StevenRoosa** [mitmproxy/mitmproxy#4804]
#### Problem Description

The mitmproxy certificate authority ships with, or creates on first install, an expired root cert.

#### Steps to reproduce the behavior:
1.   Download Version 7.0.2 of the binary.
2.   Start mitmproxy.
3.   Examine the Eventlog.

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 7.0.2 binary
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.4.0-84-generic-x86_64-with-glibc2.31

**Comment by Prinzhorn** [comment]
Did you by any chance had mitmproxy installed on that machine before (maybe years ago)? Then there might still be an old CA lingering in `~/.mitmproxy`. The warning should contain instructions on what to do.

https://github.com/mitmproxy/mitmproxy/blob/c90aaf55d96dc3f7722843b27fc9eb1034df3ac5/mitmproxy/addons/tlsconfig.py#L250-L256

Or does that happen on a clean machine?

**Comment by StevenRoosa** [comment]
You are absolutely right.  I so embarrassed!  Apologies for the distraction on this one....

**Comment by mhils** [comment]
No worries! :)
