### ISSUE TITLE
Uncaught TypeError: t.request is undefined

### ISSUE THREAD

**Issue by 89z** [mitmproxy/mitmproxy#4815]
#### Problem Description

Seems like Instagram app crashes mitmweb 

#### Steps to reproduce the behavior:
1. Click some items in the Instagram app
2. Type some keys into Google Search also, to add more requests
3. Try scrolling - entire screen goes white, and above error in console

#### System Information

~~~
Mitmproxy: 7.0.3 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Windows-10-10.0.18363-SP0
~~~

**Comment by mhils** [comment]
Could you please post a full stack trace?

**Comment by 89z** [comment]
I dont know how to do that

**Comment by mhils** [comment]
Where do you see the error message? There should be some more context. Are you seeing this in mitmproxy or mitmweb? For mitmweb, maybe open your browser's developer tools and check the JS console for a detailed error.

**Comment by 89z** [comment]
ok give me a minute - I have to set up the emulator again

**Comment by mhils** [comment]
Yes, thank you!

I believe this should be fixed in the latest development snapshots already, which you can get at https://mitmproxy.org/downloads/#branches/main/. Or alternatively you wait for the next release. 😃

**Comment by tarchive** [comment]
I do not believe this issue has been resolved in the latest release. 

I am running the latest official docker image (7.0.4) as mitmweb in reverse mode
The webpage initially loads fine at first but as soon as a client connects then the page goes white.
Refreshing the browser brings back the webpage for a split second then it immediately goes white again.

During this the proxy still functions as expected. It is just the web portion that is failing.

Let me know if you need more info or if this should be in it's own issue.

Console log on Firefox
![image](https://user-images.githubusercontent.com/26031707/156822301-0293222c-0d81-47b2-a765-492276a0ebd0.png)



Console log on Chrome
![image](https://user-images.githubusercontent.com/26031707/156821697-5c016242-6260-4384-b86d-1e23f0eed87d.png)

**Comment by tarchive** [comment]
Ah, actually i think there are multiple closed issues for this already. 
This one suggested that the fix would be in the next release, which would be 7.0.4, but in the other issues, it is said it is not released yet. Only available in main branch. 

Of course i read the _wrong_ previous issue ticket first and responded, heh
 
I will give the master branch a try and follow up if the problem still exists.
