### ISSUE TITLE
`mitmproxy` : Way to save decoded responses ?

### ISSUE THREAD

**Issue by lemonsqueeze** [mitmproxy/mitmproxy#4816]
Hi,
Hadn't checked on mitmproxy in a while, wonderful to see it's grown so much !

I'm sure there's a way to do this but i can't seem to find it :
How to save decoded responses in mitmproxy ?

Let's say for gzip'ed `application/json` content, after i press `f` the full response is pretty-printed very nicely, but how to save that to file as it's displayed ? Looks like `w` writes the raw response to file. Is there a way to save the whole window content instead ?

Many thanks

**Comment by Prinzhorn** [comment]
There's a `cut.save` command, command prompt opens with `:`. E.g. `cut.save @focus response.content /tmp/gh-4816.txt` will save `response.content` (which is decoded, in contrast to `response.raw_content`) to `gh-4816.txt`. If it's a text body you can also use `reponse.text`
