### ISSUE TITLE
SSL transparent proxying not working on ports other than 443

### ISSUE THREAD

**Issue by danhawkes** [mitmproxy/mitmproxy#482]
When proxying an android device, SSL connections to a non-443 port fail with the following error:

```
SSL handshake aborted: ssl=0xb4224e00: Failure in SSL library, usually a protocol error
error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number (external/openssl/ssl/s3_pkt.c:338 0xac4eae61:0x00000000)
```
mitmproxy shows this in the logs:

```
192.168.1.57:35340: Set new server address: 178.238.136.39:5555
192.168.1.57:35340: serverconnect
  -> 178.238.136.39:5555
192.168.1.57:35340: HttpError("Bad HTTP request line: '\\x16\\x03\\x01\\x00\\xdd\\x01\\x00\\x00\\xd9\\x03\\x03w\\xa7`\\x88\\x0b\\x16\\x82*\\
xde6\\xe6\\xfe\\xb3\\x11\\r\\x00>\\x12\\xf7S\\xdf\\xd3\\xe7-\\x94(;\\xb5\\xd4\\x9e\\xbe\\xa8 T\\xe7\\x11\\xbe\\xdf\\x90\\xea\\x01 \\x0fM\\xb
d^\\x1e\\x12n\\xf2\\xd4\\xa13H\\xd5\\xcf\\xefYB\\x02Q\\x8c\\xdf\\x87\\xf8\\x00,\\xc0+\\xc0,\\xc0/\\xc00\\x00\\x9e\\x00\\x9f\\xc0\\t\\xc0\\n'
",)
```

That traffic looks like an SSL handshake - is mitmproxy attempting to handle it as plain HTTP?

Please let me know if any more info is required.

**Comment by mhils** [comment]
If you have SSL traffic on a non-default port, you need to pass `--ssl-port PORT` to mitmproxy. Otherwise, mitmproxy assumes that it's plain HTTP.

Cheers,
Max

**Comment by hckrdan** [comment]
What version of mitmproxy was this option added in?

**Comment by mhils** [comment]
This is outdated. We now peek into the traffic and detect SSL/TLS automatically.

**Comment by hckrdan** [comment]
Thank you Max, we were using version 0.9.2 that didn't have the SSL option
and was not detecting SSL on high ports.
