### ISSUE TITLE
impossible to change upstream proxy using repository example

### ISSUE THREAD

**Issue by altieres-trackstreet** [mitmproxy/mitmproxy#4820]
#### Problem Description
the example on https://github.com/mitmproxy/mitmproxy/blob/v7.0.3/examples/contrib/change_upstream_proxy.py is broken, the function change_upstream_proxy does not exists in the code anymore

#### Steps to reproduce the behavior:
1. download https://github.com/mitmproxy/mitmproxy/blob/v7.0.3/examples/contrib/change_upstream_proxy.py
2. run mitmdump -q --mode upstream:http://some-proxy:8086 --listen-host 127.0.0.1 -p 9999 -s change_upstream_proxy.py
3. whatever other door it uses, it will not change

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 7.0.2 binary
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  Linux-5.11.0-36-generic-x86_64-with-glibc2.31

**Comment by mhils** [comment]
We don't have the capacity to maintain the examples in contrib/, so I'm closing this here (see https://github.com/mitmproxy/mitmproxy/tree/v7.0.3/examples/contrib#community-contributed-examples)

You may be able to do this with something like `flow.server_conn.via = ServerSpec("http", address=("other-proxy", 1234))`, but I haven't tested it. If it works, please send a PR that updates the example.
