### ISSUE TITLE
 ProxyServer and ProxyConfig is replace in mitmproxy7?

### ISSUE THREAD

**Issue by ody5sey** [mitmproxy/mitmproxy#4821]
#### Problem Description

Where is ProxyServer and ProxyConfig

`from mitmproxy.proxy.config import ProxyConfig
from mitmproxy.proxy.server import ProxyServer
`
is wrong

#### System Information
Mitmproxy: 7.0.3
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.6-x86_64-i386-64bit

**Comment by mhils** [comment]
ProxyConfig and ProxyServer were never part of the public API and have been removed in mitmproxy 7.

https://stackoverflow.com/a/68661172/934719 has some details on what you might be looking for.

**Comment by ody5sey** [comment]
I want start proxy server from python script and hasother way??

**Comment by sinancetinkaya** [comment]
> I want start proxy server from python script and has other way??

```python
from mitmproxy.tools import main
from mitmproxy.tools.dump import DumpMaster

options = main.options.Options(listen_host='127.0.0.1', listen_port=8081)
master = DumpMaster(options=options)
...
master.run()
```
