### ISSUE TITLE
Modify content shown in flow window

### ISSUE THREAD

**Issue by fisiognomico** [mitmproxy/mitmproxy#4823]
#### Problem Description
Hello everyone!
I am trying to write something similar to [AES Killer](https://github.com/Ebryx/AES-Killer) with mitmproxy as backend. As an example, I have an application which encrypts request/response body with an harcoded AES key in a TLS tunnel.
With mitmdump I am able to write a script that dumps the content in a text file, I was wondering if it could be possible to implement a method that modifies the content shown in the mitmproxy flow window, not just for the response (ie __set_text()__ method) but also for the request, without changing the data sent in the request body.

If it is not the case, I could think of doing it in another way.
Thank you so much!

**Comment by mhils** [comment]
You can implement a custom content view for this: https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/contentview.py. is that what you are looking for? :)

**Comment by fisiognomico** [comment]
That's great! Sorry for the incovenience.
