### ISSUE TITLE
Fallback to TCP Proxying on non-standard HTTP traffic

### ISSUE THREAD

**Issue by yoavfrancis** [mitmproxy/mitmproxy#483]
Hi,

Perhaps this is more of a feature enhancement - but say that I have mitmproxy running on port 80/443 in transparent mode (HTTP proxy mode), and suddenly I get a non-HTTP connection over that port (This can happen with various applications that use proprietary TCP-based protocol over 443/80)

It'd be absolutely neat if it'd be possible to fallback to TCP-proxying on a specific problematic connection - this way the client won't feel any problems whatsoever.

I don't mind giving it a look myself - do you have a recommendation of how to elegantly achieve this behavior in the code?

Thanks a bunch,
Yoav

**Comment by mhils** [comment]
Hey Yoav,

how would you define problematic connection? You can already filter by destination address using `--ignore` or `--tcp` (see [docs](http://mitmproxy.org/doc/features/tcpproxy.html)). Falling back to TCP if we can't parse it as HTTP is probably a bit tricker - we'd need to push the bytes we read back on the buffer somehow. Relevant parts:

- [mitmproxy architecture](http://mitmproxy.org/doc/dev/architecture.html)
- [ConnectionHandler (the generic part before HTTP comes into play)](https://github.com/mitmproxy/mitmproxy/blob/bd6c3f64c1f3102a4e91d4a964757821773781e0/libmproxy/proxy/server.py#L94-L99)
- [HTTPHandler.handle_flow](https://github.com/mitmproxy/mitmproxy/blob/bd6c3f64c1f3102a4e91d4a964757821773781e0/libmproxy/protocol/http.py#L1038-L1049)

Cheers,
Max

**Comment by yoavfrancis** [comment]
Thanks for the blazing fast reply.

Best example I can think of is Skype, that is using non-HTTP over an SSL connection on port 443.
The reasoning behind my question is that if I want to setup mitmproxy for a user in a totally transparent manner - then yes, I can predefine a specific subnet for example for, say, Skype connection and set them to use TCP proxying.

But let's say that some time later the user decides to install another such app, say, a Usenet client that connects on NNTP(s) over port 80(443) - a non-HTTP protocol. Again i'll have to define his Usenet server host in the exclusion list for TCP proxying.

Therefore what I'd like to do is, as I said - fallback to TCP proxying whenever HTTP proxying fails.
I'll give the a look over the code parts you mentioned and see if I can work something out.

Thanks again,
Yoav

**Comment by mhils** [comment]
Have fun! If there are any questions, feel free to ping me here or on IRC.
I probably forgot the most interesting portion of code - netlib's [FileLike, Reader and Writer](https://github.com/mitmproxy/netlib/blob/2a2402dfffc9f1a51869170793673eaf49207d0f/netlib/tcp.py#L29-L161) (interfaced as `client_conn.rfile, .wfile` etc. in mitmproxy). You may be able to add some functionality to read ahead of the cursor of the rfile.

```python
rfile.read_ahead_start()
try:
    req = HTTPRequest.from_stream(rfile, ...)
    rfile.read_ahead_ok()
except HTTPError:
    rfile.read_ahead_reset()
    TCPHandler(self.c, log=False).handle_messages()
    return False
```

Implementing this is not trivial (you actually need to read from the underlying socket for the "read ahead", but then keep the results in a temporary buffer, and check on any normal read if there's still something in the buffer), but would be useful for a bunch of other usecases as well (i.e. dynamically detecting SSL traffic, which is currently based on a port heuristic).

**Comment by mhils** [comment]
My last comment was possibly complicating things: If you pass the connection to _FileLike, you can use `socket.recv(n, socket.MSG_PEEK)` to peek into the socket.

**Comment by mhils** [comment]
Hey Yoav,

just curious - did you end up anywhere? :-)

Cheers,
Max

**Comment by yoavfrancis** [comment]
Hi Max,

Unfortunately I didn't have lots of time to give it a look, but a quick test showed me that MSG_PEEK didn't really work at all on PyOpenSSL sockets (on a Debian distro Linux with the newest OpenSSL version) - have you had any experience with that before?

Another weird phenomenon I found when playing with that is that calling select()->(partially) read from socket-> select() yields the result that the second "select()" call "waits" instead of returning immediately on PyOpenSSL sockets, while it does return immediately on a regular socket (which makes sense, as there is still data to read in the socket) - so this somewhat ugly (or maybe I'm missing something out) phenomenon also gets in the way.

Anyhow - I have a feeling that Wrapper "buffering" sockets are the way to go in that case, but the refactoring may a be bit "delicate" - upon an HTTPError exception, for example - we want to fallback to TCP - but also to send out to the client/server all the data we have buffered up to now.

I'll really do my best to give it a more thorough look when I get the time :)

Yoav

**Comment by mhils** [comment]
Ok, thanks! I think we have two distinct problems here:

### Peek into a non-SSL socket.
If we want to peek into a tcp socket (possibly to check if we receive a SSL handshake there), we must use `socket.MSG_PEEK`. To my knowledge, pyOpenSSL only operates on raw sockets. We cannot buffer on a higher level, because pyOpenSSL would then miss the bytes we would have read from the raw socket previously.

### Peek into a pyOpenSSL socket.
If we already have a pyOpenSSL socket, we need to manage our own buffer in Reader. pyOpenSSL does not support peeking (see [SSL.py#L1022](https://github.com/pyca/pyopenssl/blob/496f40dca9a47c0f1dfe0cd841256485708c8442/OpenSSL/SSL.py#L1022).

**Comment by mattes** [comment]
+1

**Comment by mhils** [comment]
I just submitted a PR to pyOpenSSL to support peeking into connections: https://github.com/pyca/pyopenssl/pull/294

**Comment by Kriechi** [comment]
We have `peek` support now. Whats the status here?

**Comment by mhils** [comment]
This works now, although we fall back to HTTP by default at the moment as there's no proper TCP UI. We should expose `next_layer` to inline scripts, once that's in I consider this issue done.

**Comment by Kriechi** [comment]
@mhils: does https://github.com/mitmproxy/mitmproxy/commit/d1bc966e5b7e2ef822443f3ad28a5f3d40965e75 fix this?

**Comment by mhils** [comment]
Yep, thanks!

**Comment by vitalyrepin** [comment]
I have installed laterst (0.13) mitmproxy and see the following error messages from mitmdump when skype is active and file transfer through skype is attempted:

10.57.247.168:57740: HttpError("Bad HTTP request line: '\\x7f-\\xee\\xa0TnA9\\x92?\\xd1\\xd2\\xfcCe\\xfcf\\x95\\xbfD\\xf2\\xaaufW\\xbe)\\xd8\\xef\\xf8\\xf8\\x94q{\\x81\\xf9\\x13\\xfdx\\x08\\\\'",)

And so on. 

Proxy is working in transparent mode and only http proxying is enabled.  Config:

# Use the Host header to construct URLs for display (in the logs)
host = true

# Set transparent proxy mode
transparent = true

# Set streaming mode
stream = 1k

Does this problem related to the issue discussed in this ticket? Why mitmproxy does not fall back?  Or does it fall back but I just do not see this in the logs?
