### ISSUE TITLE
URL shortened when --flow-detail 1

### ISSUE THREAD

**Issue by aoyama-val** [mitmproxy/mitmproxy#4832]
#### Problem Description

`mitmdump --help` reads:

```
  --flow-detail LEVEL   The display detail level for flows in mitmdump: 0 (almost quiet) to 3 (very verbose). 0: shortened request URL, response status code, WebSocket
                        and TCP message notifications. 1: full request URL with response status code 2: 1 + HTTP headers 3: 2 + truncated response content, content of
                        WebSocket and TCP messages 4: 3 + nothing is truncated
```

However, the request URLs are shortened like `https://firebaselogging-pa.googleapis.com/v1/firelog/le…` when specifying `--flow-detail 1`.

#### Steps to reproduce the behavior:
1. Dump flows with `w` command in `mitmproxy`
2. `mitmdump --no-server --flow-detail 1 -r mitmproxy-flows.dump`

#### System Information

```
Mitmproxy: 7.0.4
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.6-x86_64-i386-64bit
```

**Comment by mhils** [comment]
Good catch, thanks! Option description and implementation are clearly out of sync here, which we should fix. If anyone wants to tackle this, the relevant code is at https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/addons/dumper.py 😃 

Somewhat related, `-q` sets `flow_detail=0` and `-v` sets `flow_detail=2` unless overridden. :)
https://github.com/mitmproxy/mitmproxy/blob/7dbd171887ffd1f5eb2f73033133c0b0370ad984/mitmproxy/tools/main.py#L35-L42

**Comment by ingenious452** [comment]
I am new to open source I would like to contribute. Can you tell me what's the issue?

**Comment by brunopcarv** [comment]
Proposed PR: https://github.com/mitmproxy/mitmproxy/pull/4837

**Comment by brunopcarv** [comment]
hey @aoyama-val, would you mind assigning the issue to me?
Also, can you add Hacktoberfest to the project topic or hacktoberfest-accepted to the PR label
else this won't be counted in hacktobefest.
Thanks!

**Comment by aoyama-val** [comment]
@brunopcarv I don't seem to have permissions to add assignees/labels, sorry.

@mhils Can you do that?
