### ISSUE TITLE
Client TLS handshake failed

### ISSUE THREAD

**Issue by 89z** [mitmproxy/mitmproxy#4838]
#### Problem Description

APK traffic not logged.

#### Steps to reproduce the behavior:

I start MitmProxy, then using the Android Emulator, I set the proxy (192.168.0.4:8080 in my case), and Android Studio says Success. Then I install the MITM certificate. Then I install this APK:

https://apkpure.com/bandcamp/com.bandcamp.android

If I then browse pages in Android Chrome, I can see all the traffic in MitmProxy. However if I start the APK, I see no traffic, just this:

~~~
Warn: Client TLS handshake failed
~~~

To make sure I wasnt crazy, I then stop MitmProxy, and turn off the proxy in Android Studio. Then I start HTTP Toolkit, and upon starting the APK again, I can see all the traffic.

#### System Information

~~~
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Windows-10-10.0.18363-SP0
~~~

**Comment by Prinzhorn** [comment]
The app probably uses certificate pinning https://docs.mitmproxy.org/stable/concepts-certificates/#certificate-pinning

**Comment by 89z** [comment]
[out.txt](https://github.com/mitmproxy/mitmproxy/files/7285948/out.txt)

**Comment by mhils** [comment]
I suspect HTTP Toolkit is running some adb commands to inject the CA cert into `/system/etc/security/cacerts/` in your emulator? We should figure out if this is something we could do as well. :)

**Comment by Prinzhorn** [comment]
> I suspect HTTP Toolkit is running some adb commands to inject the CA cert into `/system/etc/security/cacerts/` in your emulator? We should figure out if this is something we could do as well. :)

Was just about to post this https://httptoolkit.tech/docs/guides/android/#intercepting-traffic-from-3rd-party-android-apps

**Comment by 89z** [comment]
Ok, so how do I fix it?

**Comment by Prinzhorn** [comment]
> We should figure out if this is something we could do as well. :)

@mhils a first step could be to add a section to mitm.it that walks you through the commands. We can prefill them with the cert path and hash so that's it's basically copy & paste-able (the user only needs to select the correct device id manually). Once these commands work we _could_ somehow automate it if we really wanted.

**Comment by 89z** [comment]
Hey this works too:

https://docs.mitmproxy.org/stable/howto-install-system-trusted-ca-android

No APK patch needed!

**Comment by 89z** [comment]
Based on the commands here [1], I came up with these commands:

~~~
adb shell mkdir /data/local/tmp/mitm/
adb shell cp /system/etc/security/cacerts/* /data/local/tmp/mitm/
adb push c8750f0d.0 /data/local/tmp/mitm/
adb root
adb shell mount -t tmpfs tmpfs /system/etc/security/cacerts
adb shell mv /data/local/tmp/mitm/* /system/etc/security/cacerts/
adb shell chcon u:object_r:system_file:s0 /system/etc/security/cacerts/*
~~~

This seems to fix MITM Proxy for Android Chrome, and also for an APK I tested (com.pbs.video). Good part is, you dont need `emulator -writable-system`.

1. https://github.com/httptoolkit/httptoolkit-server/blob/master/src/interceptors/android/adb-commands.ts

**Comment by 89z** [comment]
If youre interested, I wrote a program to streamline the process:

https://github.com/89z/googleplay/tree/master/cmd/mitmproxy-cert

**Comment by mhils** [comment]
Thanks for the pointer, this is super helpful! 🍰

**Comment by 89z** [comment]
Not sure why I closed this. I think this is something that should be included, similar to HTTP Toolkit
