### ISSUE TITLE
Memory leak / growth and constant CPU usage

### ISSUE THREAD

**Issue by skandragon** [mitmproxy/mitmproxy#484]
I am using mitmdump in a transparent mode.  Some requests are passed through a small script which takes the request data and stores it in a MongoDB collection.

I have noticed a fresh startup of mitmproxy sits at about 1 to 2% CPU usage, even before the first request comes in.  After running for a week or two, it will sit at about 3 to 4% CPU, and will accumulate a rather large memory footprint.

I am not sure what debugging info to provide for this sort of problem.

**Comment by mhils** [comment]
Hi Michael,

1. Could you define "rather large memory footprint"? 
2. Does the same behaviour occur if you don't run your MongoDB script?
3. Can you somehow provide a reproducible testcase (that ideally takes less than a week to run)?

Also, there are various Python memory profiling tools, e.g. https://pypi.python.org/pypi/memory_profiler . You may give them a run and see if you get any meaningful results (haven't tested that myself).
The 1-2% CPU load you're seeing are "normal" - the root cause is a Python 2 bug (https://github.com/mitmproxy/mitmproxy/issues/443).

**Comment by skandragon** [comment]
(1)  Around 1.5 GB of ram.
(2)  Untested.  Let me give it a go.

**Comment by mhils** [comment]
That's actually a bit too much memory. mitmdump's usage should stay constant over time.

**Comment by mhils** [comment]
Hi there,

any update on your issue?

Cheers,
Max

**Comment by skandragon** [comment]
It seems to grow without bounds both with and without the script, but it still seems to creep up rather than jump in huge leaps.  It might take a month or so to get to 1.5 GB, and I've not had time to debug where it is leaking.

I did notice an (unrelated probably) bug where my script gets only part of the JSON data from a request. That may indicate a bug where memory is leaked in C or C++, but since this is Python, it seems unlikely to be related.  I'll open up a ticket for that issue once I get more information, like ensuring the source server isn't being stupid and only sending part of the JSON.

**Comment by mhils** [comment]
@skandragon, how do you invoke mitmdump, which arguments/flags are you passing? Second, how many requests are passing through mitmproxy? Is it the time or the number of requests?

I'd love to seem some help from prospective GSoC students: Can anyone come up with a reproducible test case (one or two scripts that can be run) that increases mitmdump's RAM usage permanently? Ideally, you'd use Python's requests and a simple webserver for this, e.g. Flask.

**Comment by aldo-roman** [comment]
Hi @mhils

I'm targeting mitmproxy for a GSoC proposal, and wanted to give this bug a try. This is what I've done in the last hours. I set up a little lab and runned a simple script, with a few thousands requests all in my laptop. I did not achieved 1.5GB of RAM usage but constant growth of memory consumption can be verified.

**Lab description**
- Machine 1: 
    - Nginx backend (I already had one working, so Flask setup was not needed)
    - mitmproxy, transparent mode, no request interceptions
- Machine 2:
    - VM, CentOS 7, default gateway pointing to Machine 1
    - Python script requesting a wordpress home page (see below)

**First approach: using _top_**
3000 requests -  1.7% RAM - 27% CPU
5000 requests - 2.7% RAM - 28% CPU
runned twice, same results

From this results, I can see CPU is not affected in mid/long term execution, but RAM do is.

**Second approach: using _memory_profiler_**
Using external profile (without code annotations)
Results:
![figure_1](https://cloud.githubusercontent.com/assets/497197/6713730/4b7da92c-cd62-11e4-8543-15059b706431.png)

**Python script used**
```python
import urllib2
def main():
    for x in xrange(1,5000):
        request()
def request():
    u = urllib2.urlopen("http://10.100.100.8")
    u.read()
    u.close()
main()
````

**Future work**
I am about to read the mitmproxy source code so the `@profile` annotation from memory_profiler can be used and identify the memory leak. If you have any suggestion where should I start, please let me know.

Cheers!

**Comment by aldo-roman** [comment]
Hi @mhils

I'm targeting mitmproxy for a GSoC proposal, and wanted to give this bug a try. This is what I've done in the last hours. I set up a little lab and runned a simple script, with a few thousands requests all in my laptop. I did not achieved 1.5GB of RAM usage but constant growth of memory consumption can be verified.

**Lab description**
- Machine 1: 
  - 8GB RAM, for reference
  - Nginx backend (I already had one working, so Flask setup was not needed)
  - mitmproxy, transparent mode, no request interceptions
- Machine 2:
  - VM, CentOS 7, default gateway pointing to Machine 1
  - Python script requesting a wordpress home page (see below)

**First approach: using _top_**
3000 requests - 1.7% RAM - 27% CPU
5000 requests - 2.7% RAM - 28% CPU
Runned twice, same results

From this results, I can see CPU is not affected in mid/long term execution, but RAM do is.

**Second approach: using _memory_profiler_**
Using external profile (without code annotations)
Results:
![figure_1](https://cloud.githubusercontent.com/assets/497197/6713730/4b7da92c-cd62-11e4-8543-15059b706431.png)

**Python script used**
```python
import urllib2
def main():
  while True:
    request()
def request():
  u = urllib2.urlopen("http://10.100.100.8")
  u.read()
  u.close()
main()
````

**Third approach: long term execution**
At a long term execution, memory holds at 3.3%. So I instead launched many instances of the above script, up to 8 of them. I though this was easier and simpler than programming a multithread request script. Then the RAM starting growing again, up to 19%, which is the +1.5GB RAM consumption reported. I stoped some of the requesting scripts, cleared the mitmproxy screen, and memory never dropped. See graphic for details.

![figure_2](https://cloud.githubusercontent.com/assets/497197/6716259/18849c78-cd72-11e4-9c0e-c6746636429a.png)

Notice the 3.3% memory hold for a while, then was the time I started other threads. The last minutes with memory also holded represent the shutting down task and memory_profiler tasks. Also, as expected, with many threads working concurrently, CPU consumption did grow. At the end of the lab, `top` reported ~85% of CPU consumption for mitmproxy.

**Future work**
I am about to read the mitmproxy source code so the `@profile` annotation from memory_profiler can be used and identify the memory leak. If you have any suggestion where should I start, please let me know.

Cheers!

**Comment by cortesi** [comment]
It's worth pointing out explicitly here that there's a difference between mitmproxy and mitmdump in this respect. Mitmproxy spools everything in memory for display - something we plan to fix once we have a SQLite backing store. Mitmdump memory use should definitely not increase over time, though.

**Comment by lkwg82** [comment]
Is this already closed? I doubt. I see also increasing memory usage.

**Comment by llid3nlq** [comment]
Due to errors in the way Java handles some of the TLS connections I encounter, I have had to resort to pointing BurpSuite Professional through mitmproxy as a workaround. Mitmproxy memory consumption exceeds 7GB after approx. 30 minutes and around 2000 HTTPS requests. Happy to provide any diagnostic information if you require it. I'd certainly love to know why.

**Comment by lkwg82** [comment]
@llid3nlq see #620 I've made some version pinning. You can ask the author, if there are some progress ;)

**Comment by chrisgavinme** [comment]
I've noticed that the problem does not seem to occur when responses are being streamed. I think the result of calls to `Reader.read` in `netlib/tcp.py` are being stored somewhere and never released. This is backed up by the fact that larger requests seem to cause memory to be used up more quickly.

Fortunately for me, I'm not interested in inspecting response content, so running `mitmdump` with `--stream 0` works for me.

**Comment by kitech** [comment]
Here also has the memory leak problem,  I'm using upstream mode.
mitmdump -U  http://127.0.0.1:8118  -p 8119

Add when acess https://github.com/, the memory usage increase very quickly.
