### ISSUE TITLE
Method to share data between script calls

### ISSUE THREAD

**Issue by skandragon** [mitmproxy/mitmproxy#485]
I am currently doing a very brute force method of connecting to a MongoDB database, inserting one record, and then closing it all down.  Is there a method to store data to be shared among runs of the script?  I have to admit a lack of knowledge of Python.  I'm more of a Ruby person. :)

**Comment by mhils** [comment]
Hi Michael,

sure - two ways:

1) Just use a global variable, like this:
```python
f = open("example.db")

def request(context, flow):
    f.write("foo")
    f.flush()
``` 

2) Use mitmproxy's context object,which you can (de)initialize with the `start()` and `stop()` hooks. An example of this is [iframe_injector.py](https://github.com/mitmproxy/mitmproxy/blob/master/examples/iframe_injector.py).

Cheers,
Max
