### ISSUE TITLE
reverse proxy with multiple hosts as destination

### ISSUE THREAD

**Issue by chaserhkj** [mitmproxy/mitmproxy#486]
Hi, there

I wonder if mitmproxy could be used as a reverse proxy that accepts multiple destination which routes the request according to the `host: ` header of the request.

That is to say, it acts, like this:

1. mitmproxy listen on 80 port on the proxy machine
1. on the client machine, use some technique to let it point some domains (take `www.a.com` and `www.b.com` for examples) to the proxy machine (such as modifying hosts file or dns hijacking).
1. requests are made to the proxy machine, and mitmproxy uses `host: ` header to determine the destination.
    - requests with header `host: www.a.com` will be routed to `http://www.a.com`
    - requests with header `host: www.b.com` will be routed to `http://www.b.com`
1. mitmproxy could do interception on all requests

It's quite like setting up an apache httpd on virtualhost with `server www.a.com` and on virtualhost with `server www.b.com`, both of which virtualhosts are configured with proper reverse proxy settings.

I know that as the cert is delivered during the initialization of TLS connection, before any headers are transmitted, so it may cause cert issues while the cert hostname does not match with url hostname in https proxies. But let's assume that this will be used in http proxies or a wildcard cert would be used to match the hostnames.

Is it possible to do this in the mitmproxy framework by some already implemented feature, writing inline scripts or using libmitmproxy?

Thanks,
Happy Hacking!

**Comment by mhils** [comment]
Hi @chaserhkj,

this closely resembles the use case where someone is doing a DNS spoofing attack. In general, using transparent mode is the better option but I realize that this may not always be possible.
I just added an inline script to our examples that does exactly what you were specifying. There are two major limitations:

1. If there is SSL and the client doesn't send a Server Name Indication, it will probably fail. If there is no Host header, HTTP redirection won't work.
2. Getting this running on a single machine is tricky, as mitmproxy will resolve the IP to localhost as well.

Let me know how it works for you!

Cheers,
Max

**Comment by chaserhkj** [comment]
This is exactly what I want, the script works like a charm.

Thanks a lot !

Happy Hacking!

**Comment by felipekunzler** [comment]
Hi @mhils, is this still supported as of today? Was looking for something similar, but couldn't find the example.
Thanks!

**Comment by amm0nite** [comment]
Hi @felipekunzler ,
It works with the latest release 4.0.4 and the example is the file `mitmproxy/examples/complex/dns_spoofing.py`.

**Comment by felipekunzler** [comment]
Perfect! Thanks.
