### ISSUE TITLE
does mitmproxy forward the SSL decrypted traffic to NIDS , is possible?

### ISSUE THREAD

**Issue by scdit46** [mitmproxy/mitmproxy#4861]
does mitmproxy forward the SSL decrypted traffic to NIDS (for example to a suricata server) for analyze?
is possible?

<img width="402" alt="ssl-decrypt" src="https://user-images.githubusercontent.com/63736962/137184603-96e18e4e-0670-4406-a544-eb912bd026a7.png">
)?

**Comment by scdit46** [comment]
the traffic sends to NIDS Suricata is decrypted SSL Traffic.

**Comment by Jackson-Pollock** [comment]
@scdit46 Did you manage to achieve this? I am also looking for same requirement.

**Comment by dmuensterer** [comment]
Any updates? @Jackson-Pollock did you manage to achieve this using mitmproxy?
