### ISSUE TITLE
RuntimeWarning: coroutine 'BaseEventLoop._create_server_getaddrinfo' was never awaited

### ISSUE THREAD

**Issue by Smyja** [mitmproxy/mitmproxy#4908]
#### Problem Description
I get this error when i run the mitmproxy command
```

Traceback (most recent call last):
  File "mitmproxy\master.py", line 54, in run_loop
  File "urwid\main_loop.py", line 287, in run
  File "urwid\main_loop.py", line 377, in _run
  File "urwid\main_loop.py", line 338, in start
  File "urwid\display_common.py", line 813, in start
  File "mitmproxy\contrib\urwid\raw_display.py", line 263, in _start
AssertionError

mitmproxy has crashed!
Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
7[?47hsys:1: RuntimeWarning: coroutine 'BaseEventLoop._create_server_getaddrinfo' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```
#### Steps to reproduce the behavior:
1. Open CMD on windows and run mitmproxy

#### System Information
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Windows-10-10.0.10240-SP0

**Comment by mhils** [comment]
How do you run the mitmproxy command? In other words, which console are you using? cmd, powershell, something else?

**Comment by Smyja** [comment]
> How do you run the mitmproxy command? In other words, which console are you using? cmd, powershell, something else?

I am using CMD. I can't install windows terminal (my windows version is lower)

**Comment by mhils** [comment]
Which Windows version are you on? :)

**Comment by Smyja** [comment]
Windows-10 build 1024

**Comment by mhils** [comment]
Thanks for confirming. mitmproxy's console interface won't work before build 10586, which I think is the first build that includes ENABLE_VIRTUAL_TERMINAL_PROCESSING. mitmweb and mitmdump should be fine. I'll make sure that we have a better error message here.
