### ISSUE TITLE
Event type error says mitmproxy has crashed without actually crashing

### ISSUE THREAD

**Issue by elespike** [mitmproxy/mitmproxy#4931]
#### Problem Description
Some sort of event type error...? This happened when I was testing `modify_body` and `modify_headers` options (see reproduction steps) and it results in repeated error messages with really long tracebacks.

The error messages begin by saying that mitmproxy has crashed, but it doesn't actually crash.

```
[... lots more traceback before the below]
  File "/home/elespike/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/proxy/layer.py", line 144, inhandle_event
    command = command_generator.send(send)
  File
"/home/elespike/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py", line136, in _handle_event
    yield from self.client_state(event)
  File "/home/elespike/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy/proxy/utils.py", line 23, in
_check_event_type
    raise AssertionError(
AssertionError: Unexpected event type at HttpStream.state_done: Expected no events, got
RequestEndOfMessage(stream_id=1).
```

#### Steps to reproduce the behavior:
1. Start with default options
2. Set `modify_body` and `modify_headers` as follows:
```
modify_body:
  - :~u webhook.site ~q::<h1>hey</h1>

modify_headers:
  - :~u webhook.site ~s:content-type:text/html
```
3. Visit https://webhook.site

#### System Information
Mitmproxy: 7.0.4
Python:    3.9.2

**Comment by mhils** [comment]
Thanks! Your modifications triggered an interested  race condition in our protocol implementation. 
https://github.com/mitmproxy/mitmproxy/pull/4932 should fix this, could you please verify if that is true?

(the webhook.site website will still not work properly with your changes, but that is about to be expected I guess)

**Comment by elespike** [comment]
That did it! Thanks for looking into this. =)
