### ISSUE TITLE
[mitmweb] Combo all cookie headers to one Cookie header

### ISSUE THREAD

**Issue by zhangsean** [mitmproxy/mitmproxy#4939]
#### Problem Description

Usually, like Chrome, send a web request with only one cookie header to the server, but all cookie headers are split one by one in the mitmweb.
When exporting as curl and paste to Postman with raw text, Postman only imports one cookie header and value.

#### Proposal
Combo all cookie headers to one cookie header is more compatible with other apps, like Postman, etc.

#### Alternatives
Just combo all cookie values with '; ' into one Cookie header.

#### Additional context
![image](https://user-images.githubusercontent.com/2536402/142825046-3c681105-bc16-4848-9e31-e19774a232ac.png)

**Comment by mhils** [comment]
Thank you for the suggestion!
Maybe Chrome shows something else, but we are displaying the cookie headers _exactly_ as they are sent over the wire. I don't want to change that as sometimes these exact details matter.

If you would like to see the header concatenated, you can instruct mitmproxy to do it like this (see https://docs.mitmproxy.org/dev/api/mitmproxy/http.html#Headers):

`concat-headers.py`
```python
def requestheaders(flow):
    flow.request.headers["cookie"] = "; ".join(flow.request.headers.get_all("cookie"))
```

And then run `mitmweb -s concat-headers.py`. Does that help?

**Comment by zhangsean** [comment]
Yes, this just helps me.
Thanks very much!

**Comment by zhangsean** [comment]
I improve the script to fix request error when the request without cookie header.
`concat-headers.py`
```python
def requestheaders(flow):
    cookies = flow.request.headers.get_all("cookie")
    if len(cookies) > 0:
        flow.request.headers["cookie"] = "; ".join(cookies)
```
