### ISSUE TITLE
Paste

### ISSUE THREAD

**Issue by 89z** [mitmproxy/mitmproxy#4948]
I would like to paste this text:

~~~
HNK2IC
~~~

Into MITM Proxy, to be used as a filter, such as:

~~~
~bs HNK2IC
~~~

I copy the text from another program, then go back to MITM Proxy, press `f` to get the filter to come up, but then what do I do? If I press Ctrl+V, nothing happens. If I right click, I get C7C7 inputted. Am I doing something wrong?

**Comment by mhils** [comment]
This really depends on your console and not on mitmproxy. Generally speaking, your normal way to paste things should work.

**Comment by 89z** [comment]
I am using Windows 10 with Windows Terminal:

https://github.com/microsoft/terminal

**Comment by mhils** [comment]
I'm using Windows Terminal as well - Ctrl+V works fine for me both in WSL and PowerShell.

**Comment by 89z** [comment]
I just tested it now, and Ctrl+V works, but not with MITM Proxy.

If I try to paste into where it says `set view_filter`, nothing happens.

I am using PowerShell 6.2 and Windows Terminal 1.10.2383.

**Comment by mhils** [comment]
https://user-images.githubusercontent.com/1019198/143272497-f52afeb7-0455-4832-9354-46b9207a12e0.mp4

**Comment by 89z** [comment]
I figured it out. I am using a custom `settings.json`, and you must have this:

~~~json
{
   "actions": [
      {"command": "paste", "keys": "ctrl+v"}
   ]
}
~~~

otherwise that command is not recognized by Windows Terminal. Youd think they would have that hard coded

# 😔
