### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by 89z** [mitmproxy/mitmproxy#4949]
Running this command:

~~~
mitmdump --flow-detail 4 > nbc.txt
~~~

I get this result:

~~~
Addon error: Traceback (most recent call last):
  File "mitmproxy\addons\dumper.py", line 269, in response
  File "mitmproxy\addons\dumper.py", line 250, in echo_flow
  File "mitmproxy\addons\dumper.py", line 123, in _echo_message
  File "mitmproxy\addons\dumper.py", line 73, in echo
  File "click\termui.py", line 657, in secho
  File "click\utils.py", line 298, in echo
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 641064-641066: character maps to <undefined>
~~~

I just want the full responses, including the bodies, but only if body is plain text. I would guess from the error that even images and fonts are being output. So if someone has a command to just get the plain responses, it would fix the problem. Otherwise non text response should be escaped, or just output in binary rather than trying to encode to Unicode.

**Comment by 89z** [comment]
https://github.com/mitmproxy/mitmproxy/issues/4070

**Comment by mhils** [comment]
As a workaround, mitmdump takes an optional filter argument, you can also set the `dumper_filter` option if you still want flows to be saved but not printed to stdout.

On our end, we need the fix printing to stdout.

**Comment by 89z** [comment]
Do you have an example command? All I care about is plain text responses (HTML, JSON, etc). Anything binary (images, audio, video), I want the headers, but dont care about the response body.

**Comment by mhils** [comment]
Not really beautiful, but something like
```
$ mitmdump "! ~b [\\x00-\\x08]"
Only processing flows that match "! ~b [\x00-\x08]"
```
probably does a moderately good job.

**Comment by 89z** [comment]
Even if the response body is binary, I will want the response headers. Wouldnt the above command filter the entire response out?

**Comment by mhils** [comment]
The above command would filter out the entire response, yes. The dumper has no option to say "only some bodies", you would need to write a custom addon for this. :)

**Comment by 89z** [comment]
actually, if the response body is binary... maybe I dont care to see it. Hm. I suppose that command might work after all. If youre interested, I found this:

https://mimesniff.spec.whatwg.org/#binary-data-byte

maybe a "shortcut" for that could be added to MITM Proxy?

**Comment by mhils** [comment]
Maybe we need to start one step earlier: What are you trying to accomplish? 

mitmdump's stdout output is intended for human consumption. contents are pretty-printed, for example here's the output for a binary favicon.ico:

```
$ mitmdump --set flow_detail=4
Proxy server listening at http://*:8080
127.0.0.1:57072: client connect
127.0.0.1:57072: server connect github.com:443 (140.82.121.4:443)
127.0.0.1:57072: GET https://github.com/favicon.ico HTTP/2.0
    user-agent: curl/7.68.0
    accept: */*

 << HTTP/2.0 200 OK 6.4k
    server: GitHub.com
    [...]
    x-github-request-id: DEF1:E5E4:1CE7CD:1DF6FF:619E6883

    Format:           ICO
    Number of images: 2
    Image 1:          Size: 16 x 16
                  Bits per pixel: 32
                  PNG: False
    Image 2:          Size: 32 x 32
                  Bits per pixel: 32
                  PNG: False
```

**Comment by 89z** [comment]
> Maybe we need to start one step earlier: What are you trying to accomplish?

I want a log of every single request and response, including headers and body for both. If the response is binary, then I suppose the entire response (and possibly request) could be omitted. I thought this command would do that:

~~~
mitmdump --flow-detail 4 > nbc.txt
~~~

but running it produced the error above. So either the error should be fixed, or if I can run another command that avoids the error, then I will do that.

**Comment by mhils** [comment]
To be clear, I only proposed a workaround above; as mentioned in https://github.com/mitmproxy/mitmproxy/issues/4949#issuecomment-977585968 this definitely is a bug we need to fix.

**Comment by 89z** [comment]
I see, so your point is no need to add a shortcut for "binary stuff", because if the original error is fixed, then its no longer a problem

**Comment by 89z** [comment]
Closing for lack of interest

**Comment by mhils** [comment]
Fixed in mitmproxy 8, we don't use click here anymore.

**Comment by 89z** [comment]
> we don't use click here anymore.

what does that mean?

**Comment by mhils** [comment]
It should be fixed in mitmproxy 8, which does not use `click` to print to stdout anymore.

**Comment by 89z** [comment]
are you talking about this?

https://github.com/pallets/click

**Comment by mhils** [comment]
Yes. :)
