### ISSUE TITLE
flows > 1gb can be dumped but can't be loaded (tnetstring encoder/decoder)

### ISSUE THREAD

**Issue by r00t-** [mitmproxy/mitmproxy#4957]
#### Problem Description
the tnetstring decoder contains this:
https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/io/tnetstring.py#L174
```
        if len(data_length) > 9:
            raise ValueError("not a tnetstring: absurdly large length prefix")
```

which disallows loading single flows larger than about a gigabyte,
while the encoder will happily write such an object without considering any limits.

i agree that some kind of sanity limit is appropriate,
but ever since i encountered this (long ago)  i've been wondering if there shouldn't be a more elegant way to handle this.
any user encountering this is required to dive into the format's internals to manually fix this.

#### Steps to reproduce the behavior:
1. download a 1gb or larger file through mitmdump
2. try to load the resulting dump file

#### System Information
doesn't seem relevant

**Comment by mhils** [comment]
Thanks! 🍰
