### ISSUE TITLE
Use mitmproxy behind reverse proxy

### ISSUE THREAD

**Issue by DUOLabs333** [mitmproxy/mitmproxy#4963]
#### Problem Description

I currently have mitmproxy running on port 2010. However, I want to also be able to access under a host name, like `mitmproxy.test`

#### Proposal
Access mitmproxy from `https://$DOMAIN.$TLD`

#### Additional context
Add any other context or screenshots about the proposal here.

**Comment by CypherpunkSamurai** [comment]
Hello Sir, I had a few questions regarding this issue if you don't mind.

* Are you asking if mitmproxy supports capturing traffic pointed to it from a device? or are you asking if mitmproxy web interface is available from a reverse proxy
* Sir if its the second case and you're trying to access mitmproxy web interface, have you tried using nginx?

**Comment by DUOLabs333** [comment]
So basically I want to be able to have nginx redirect requests for https://mitm.proxy to https://127.0.0.1:$PORT, decrypting traffic

**Comment by CypherpunkSamurai** [comment]
> So basically I want to be able to have Nginx redirect requests for https://mitm.proxy to https://127.0.0.1:$PORT, decrypting traffic

Ok Sir, So the first case. I did a quick lookup in the docs and found [#reverse-proxy](https://docs.mitmproxy.org/stable/concepts-modes/#reverse-proxy) feature documentation. Does this meet your needs or is it that we are trying to use Nginx specifically?

**Comment by DUOLabs333** [comment]
Doesn't this mean that `mitmproxy` acts as a reverse proxy to some already existing site?

**Comment by CypherpunkSamurai** [comment]
Oh, Yes apparently. My bad.

I think I just understood what you're trying to achieve. You want all requests to `mitm.proxy` get logged as mitmproxy data, right?

You can achieve so using a simple hostfile addition / iptables rule so that `mitm.proxy` points to `localhost`. I don't think this would require a reverse proxy unless you're planning on deploying mitmproxy to a remote server (are we?)

**Comment by DUOLabs333** [comment]
No, the problem is, that mitmproxy is not running on port 80/443, but on 2222, so basically, I want to use mitmproxy in a virtual hosts, funneling data from port 80 to 2222 if the host name matches `mitm.proxy`.

**Comment by CypherpunkSamurai** [comment]
Ok. Please try if the below configuration works for you.

```nginx

server {
    listen 80 ssl http2;

    server_name mitm.proxy;
   # un-comment if using port 443 / SSL
    #also place certificates in target location
    #ssl_certificate /etc/nginx/mitm/certchain.pem;
    #ssl_certificate_key /etc/nginx/mitm/mycert.private.pem;

    location / {
        # SSL use case
        #proxy_pass https://localhost:2222;
        proxy_pass http://localhost:2222;
    }
}
```

This configuration runs nginx on port 80 with SSL and HTTP2 support (optional). We then proxy all requests (all locations `/`), to `http(s)://localhost:2222`.

**Comment by DUOLabs333** [comment]
This is exactly what I have, and it doesn't work.

**Comment by DUOLabs333** [comment]
For example, using `https://127.0.0.1.nip.io:2222`, fails as well.

**Comment by DUOLabs333** [comment]
Ah, figured it out: `mitmproxy` does not allow you to access it from anything other than `127.0.0.1` and `localhost`. This is the same with `mitmweb`.

**Comment by CypherpunkSamurai** [comment]
> Ah, figured it out: `mitmproxy` does not allow you to access it from anything other than `127.0.0.1` and `localhost`. This is the same with `mitmweb`.

Oh!, Great to hear that It's solved 😆. I think one of the reasons could be that SSL certs are made for 127.0.0.1 and not localhost.

You may now close the issue when you feel. Happy to help :)

**Comment by DUOLabs333** [comment]
Of course, this is a problem for me: I guess one way would be to basically move my virtual hosts to `nginx` away from `sniproxy`. Just one question, for `map $var1 $var2`, which var is depending on which var?

**Comment by CypherpunkSamurai** [comment]
> map $var1 $var2

For nginx `map` [documentaion](http://nginx.org/en/docs/http/ngx_http_map_module.html) explains this well, its basically `map source destination_variable`. You may also refer to this [Digital Ocean guide](https://www.digitalocean.com/community/tutorials/how-to-use-nginx-s-map-module-on-ubuntu-16-04) or this [BlueGrid guide](https://bluegrid.io/how-the-nginx-ngx_http_map_module-works/).

**Comment by DUOLabs333** [comment]
Perfect, just one last question: if I specify `proxy.*`, going to `proxy.test` does not work. It's only when I specify `proxy.test` does it work.

**Comment by CypherpunkSamurai** [comment]
> Perfect, just one last question: if I specify `proxy.*`, going to `proxy.test` does not work. It's only when I specify `proxy.test` does it work.

Do you intend to use `proxy.*` regex as a domain match?

**Comment by DUOLabs333** [comment]
No, just a wildcard.

**Comment by CypherpunkSamurai** [comment]
Ok, this should normally work on nginx. I'd need to have a look. could you please send me your nginx config please?

**Comment by CypherpunkSamurai** [comment]
Ok. I can't seem to find anything wrong with the Nginx config on a quick look. According to the [nginx wildcard names domain matching](http://nginx.org/en/docs/http/server_names.html#wildcard_names) documentation, Nginx supports wildcard domain matches.

I would suggest trying `proxy.` instead of `proxy.*` for the moment.

**Comment by DUOLabs333** [comment]
That also did not work -- I just gave up and put `.test` for each of them. However, I put in `https://proxy.history.test:443` into Firefox's proxy settings, and it failed.

**Comment by CypherpunkSamurai** [comment]
Ok. Do the other proxies except for that work?

**Comment by DUOLabs333** [comment]
If I use `localhost:2011` it works fine, so it's probably something in the redirection. Using curl works fine for `*.test`, but fails for `google.com`. Looking through the logs, for some reason, nginx is trying to act on `google.com`.

**Comment by CypherpunkSamurai** [comment]
have you configured Nginx to use SSL and SSL certs properly, cause it might be trying to reach https?

**Comment by DUOLabs333** [comment]
Yes, removing the proxy causes https to work perfectly fine.

**Comment by DUOLabs333** [comment]
Trying `server_name  ~^*.test$;` fails with `pcre_compile() failed: nothing to repeat in`

**Comment by DUOLabs333** [comment]
It seems that because mitmproxy is behind nginx, all requests are going through nginx. For some reason, nginx isn't just ignoring the requests though and let them go through.

**Comment by CypherpunkSamurai** [comment]
> It seems that because mitmproxy is behind nginx, all requests are going through nginx. For some reason, nginx isn't just ignoring the requests though and let them go through.

Firstly make sure Nginx is running. To run any server on port 80 / 443 you need to run with admin permissions. Turn on Nginx logging to stdout.

**Comment by DUOLabs333** [comment]
I already have NGINX running, that's why I'm able to see in the error
messages that the proxy requests are going through NGINX.

**Comment by DUOLabs333** [comment]
I recently changed my `nginx.conf` to set the `Host` header to the server name, rather than `localhost`. Maybe the `mitmproxy` developers can rethink allowing `mitmproxy` to only be accessed on `localhost`?

**Comment by tobtesting** [comment]
> I recently changed my `nginx.conf` to set the `Host` header to the server name, rather than `localhost`. Maybe the `mitmproxy` developers can rethink allowing `mitmproxy` to only be accessed on `localhost`?

Cam you send an example of this 'Host' configuration inside the nginx.conf ?  we encounter Error: tunneling socket could not be established, statusCode=400
when going via nginx( dns entry reverse proxy ) to mitm ( dump ) to requested backend.

**Comment by DUOLabs333** [comment]
Yeah, I realized that it's because nginx doesn't support forward proxing.

**Comment by tobtesting** [comment]
> Yeah, I realized that it's because nginx doesn't support forward proxing.

So it didn't works at all m or can you clarify more ?

**Comment by DUOLabs333** [comment]
It doesn't work at all -- I just gave up on it.

**Comment by DUOLabs333** [comment]
I have come back to this issue, because trying with Caddy's `forwardproxy` plugin also fails, so it could be because of mitmproxy limitation of only working on localhost. Where is it so I can test removing it?

**Comment by DUOLabs333** [comment]
I commented out some lines in `proxyserver.py`, and it started working on other hosts, as long as the port is equal to `listen-port`. However, I still can't access it behind nginx.

**Comment by DUOLabs333** [comment]
I got it to work by first compiling `https://github.com/chobits/ngx_http_proxy_connect_module`. Then, I added

```
server {
                    listen       127.0.0.1:80;
                    resolver 127.0.0.1;
                    server_name  *.test;
                    proxy_connect;
					proxy_connect_allow 80 443;
					if ($http_host ~ "(.*)\.test$"){
                    	return 302 https://$http_host$request_uri;
     				}
                    location / {
		
						proxy_set_header Host $host;
						proxy_pass http://$host;
		
					}


                }
```
