### ISSUE TITLE
Mitmproxy interferes with some downloads and streaming

### ISSUE THREAD

**Issue by DUOLabs333** [mitmproxy/mitmproxy#4965]
#### Problem Description
Using mitmproxy when streaming or downloading some things, like watching media from the Jellyfin demo server, downloading from Onedrive, uploading to Youtube and downloading from Github, causes the operations to stall.

#### Steps to reproduce the behavior:
1. Setup mitmproxy
2. Do any of the activities listed above
3. See that they can't be done

#### System Information
Mitmproxy: 7.0.4
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.15.1-1-ARCH-aarch64-with-glibc2.32

This can also be due to my script -- maybe there's an issue with it:

```
from mitmproxy import http
from datetime import datetime
from bs4 import BeautifulSoup

def response(flow: http.HTTPFlow):
    if flow.request.headers['accept'].startswith('text/html,application/xhtml+xml,application/xml'):
        soup=BeautifulSoup(flow.response.content)
        file=str(datetime.fromtimestamp(int(flow.response.timestamp_start))).split(' ')[0]
        with open('../logs/ '[:-1]+file,'a+') as f:
            f.write(str(datetime.fromtimestamp(int(flow.response.timestamp_start)))+ ' '+soup.title.string+' '+str(flow.request.url)+'\n\n')
```

**Comment by DUOLabs333** [comment]
Thanks to #3242, I've learned it's probably because of the fact that mitmproxy is trying to cache all requests -- for large requests or for that which is streamed, it will take a while to actually get it all, so it delays the sending. Setting `--set stream_large_bodies=1` fixed the problem.

**Comment by DUOLabs333** [comment]
Is there a way to set the proxy to stream the connection if it is a download or stream? I'm still running into issues at a few points.

**Comment by mhils** [comment]
See https://docs.mitmproxy.org/stable/overview-features/#streaming.
