### ISSUE TITLE
Migration of code 

### ISSUE THREAD

**Issue by shubhangi013** [mitmproxy/mitmproxy#4971]
#### Problem Description

In the `web` folder, some of the code is in typescript and some of it is in javascript. is there a reason for this?

#### Proposal
Maybe a migration of the complete frontend to typescript would be beneficial. 

#### Alternatives
none.

#### Additional context
Many open-source projects have done the complete migration to typescript. I'd like to take up a few files and migrate them. In the similar fashion other contributors can take up a few files as well.

**Comment by Prinzhorn** [comment]
The Typescript was added very recently https://github.com/mitmproxy/mitmproxy/pull/4763

```
$ find web/src/ -type f -name '*.js'
web/src/js/filt/command.js
web/src/js/filt/filt.js
```

These two are auto-generated.

```
$ find web/src/ -type f -name '*.jsx'
web/src/js/components/EventLog.jsx
web/src/js/components/FlowTable.jsx
web/src/js/components/Modal/Modal.jsx
web/src/js/components/Modal/Option.jsx
web/src/js/components/Modal/OptionModal.jsx
web/src/js/components/Modal/ModalLayout.jsx
```

I think these six are the only ones left? If there's benefit in migrating them PRs are welcome.

**Comment by shubhangi013** [comment]
> The Typescript was added very recently https://github.com/mitmproxy/mitmproxy/pull/4763
> 
> ```
> $ find web/src/ -type f -name '*.js'
> web/src/js/filt/command.js
> web/src/js/filt/filt.js
> ```
> 
> These two are auto-generated.
> 
> ```
> $ find web/src/ -type f -name '*.jsx'
> web/src/js/components/EventLog.jsx
> web/src/js/components/FlowTable.jsx
> web/src/js/components/Modal/Modal.jsx
> web/src/js/components/Modal/Option.jsx
> web/src/js/components/Modal/OptionModal.jsx
> web/src/js/components/Modal/ModalLayout.jsx
> ```
> 
> I think these six are the only ones left? If there's benefit in migrating them PRs are welcome.

I'd like to work on this and raise a PR. Could you please assign it to me?

**Comment by SuperSonicHub1** [comment]
Seems like this issue was handled.
@shubhangi013 Did you forget to close it?
