### ISSUE TITLE
Need SM mitm support

### ISSUE THREAD

**Issue by hi-unc1e** [mitmproxy/mitmproxy#4975]
#### Problem Description

1. Concept: GmSSL is an open source cryptographic toolkit that provide first level support of Chinese national cryptographic algorithms, 
2. The SM algorithms are becoming mandatory in China，you could find definition in [rfc8998](https://www.rfc-editor.org/rfc/rfc8998.html)
3. I encountered a situation that i need to intercept the netflow-traffic in HTTPs acted as SM4_CBC， plus SM2 for key-exchange
When i was trying to us mitmProxy to intercept the flow，here came the error:
```
OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])
```
So I leave this message to seek help，

#### Proposal
I would like to advise to add the support of intercepting TLS site based on `ShangMi (SM) Cipher Suites`, which you can find in
- [rfc8998](https://www.rfc-editor.org/rfc/rfc8998.html)
- https://github.com/guanzhi/GmSSL

#### Alternatives
I dont know，maybe I should fingure out a way of Browser-Based interception

#### Additional context / reference
- https://tools.ietf.org/id/draft-ribose-cfrg-sm4-09.html
- https://www.rfc-editor.org/rfc/rfc8998.html
- https://github.com/guanzhi/GmSSL , a repo where you can find the implementation of SM4

**Comment by mhils** [comment]
We use OpenSSL under the hood for all cryptography operations (via the excellent cryptography / pyOpenSSL packages). Your best bet would be to install cryptography with an OpenSSL version that supports these ciphers (if that exists).

**Comment by mhils** [comment]
It's nothing we can really fix in mitmproxy, so I'll be closing this here. If you or anyone else manages to get this working, please feel free to leave a comment with details nonetheless. :)

**Comment by emil246** [comment]
Hi! Thanks to @hi-unc1e, touched important question: support of the national crypto standards. @mhils according to your recommends, i took openssl with GOST support (russian national crypto standard) and compiled python3 with GOST support. pyOpenSSL understood these types of crypto algorithms, but i saw in source code of mitm that in some places you bind to specific crypto algorithms like RSA. Is it possible to provide an interface to support national crypto standards and how can i help the project to achieve these extra functionalities?

**Comment by mhils** [comment]
> Is it possible to provide an interface to support national crypto standards and how can i help the project to achieve these extra functionalities?

Your best bet here is to maintain your own fork, which is permitted by the mitmproxy license.
