### ISSUE TITLE
HAR does not get populated completely. 

### ISSUE THREAD

**Issue by rakayada** [mitmproxy/mitmproxy#4976]
#### Problem Description
We are trying to replace our existing browser mob proxy with mitm proxy, the issue is populated har contains less entries than existing setup i.e. har created from browser mob proxy has more entries while har created from mitm has less entries for the same url.

#### Steps to reproduce the behavior:
1. Running har script with ` mitmdump -p 8000 -s /home/seluser/test_center.py --ssl-insecure --set termlog_verbosity=debug --set flow_detail=1
`
2. hit webiste - staging.developer.kingfisher.com
3. collect har from mitmdump

#### Code for mitm har 
```py
class HarAddon:
    def __init__(self):
        self.har_file_name = None
        self.HAR: typing.Dict = {}
        # A list of server seen till now is maintained so we can avoid
        # using 'connect' time for entries that use an existing connection.
        self.SERVERS_SEEN: typing.Set[connection.Server] = set()

    def start_har(self, har_file_name):
        self.har_file_name = har_file_name
        self.HAR = {
            "log": {
                "version": "1.2",
                "creator": {
                    "name": "mitmproxy har_dump",
                    "version": "0.1",
                    "comment": version.MITMPROXY,
                },
                "entries": [],
            }
        }
        self.SERVERS_SEEN = set()

    def reset(self):
        self.har_file_name = None
        self.HAR = {}
        self.SERVERS_SEEN = set()

    # Mitmproxy event handler
    def response(self, flow: http.HTTPFlow):
        """
        Called when a server response has been received.
        """

        # Skip processing HAR for URLs that are not whitelisted, or if HAR file is not set (i.e. HAR capture is not enabled yet)
        if flow.metadata.get("whitelist_filtered", False) or not self.har_file_name:
            return

        # -1 indicates that these values do not apply to current request
        ssl_time = -1
        connect_time = -1

        if flow.server_conn and flow.server_conn not in self.SERVERS_SEEN:
            connect_time = (
                flow.server_conn.timestamp_tcp_setup - flow.server_conn.timestamp_start
            )

            if flow.server_conn.timestamp_tls_setup is not None:
                ssl_time = (
                    flow.server_conn.timestamp_tls_setup
                    - flow.server_conn.timestamp_tcp_setup
                )

            self.SERVERS_SEEN.add(flow.server_conn)

        # Calculate raw timings from timestamps. DNS timings can not be calculated
        # for lack of a way to measure it. The same goes for HAR blocked.
        # mitmproxy will open a server connection as soon as it receives the host
        # and port from the client connection. So, the time spent waiting is actually
        # spent waiting between request.timestamp_end and response.timestamp_start
        # thus it correlates to HAR wait instead.
        timings_raw = {
            "send": flow.request.timestamp_end - flow.request.timestamp_start,
            "receive": flow.response.timestamp_end - flow.response.timestamp_start,
            "wait": flow.response.timestamp_start - flow.request.timestamp_end,
            "connect": connect_time,
            "ssl": ssl_time,
        }

        # HAR timings are integers in ms, so we re-encode the raw timings to that format.
        timings = {k: int(1000 * v) if v != -1 else -1 for k, v in timings_raw.items()}

        # full_time is the sum of all timings.
        # Timings set to -1 will be ignored as per spec.
        full_time = sum(v for v in timings.values() if v > -1)

        started_date_time = datetime.fromtimestamp(
            flow.request.timestamp_start, timezone.utc
        ).isoformat(timespec="milliseconds")

        # Response body size and encoding
        response_body_size = (
            len(flow.response.raw_content) if flow.response.raw_content else 0
        )
        response_body_decoded_size = (
            len(flow.response.content) if flow.response.content else 0
        )
        response_body_compression = response_body_decoded_size - response_body_size

        entry = {
            "startedDateTime": started_date_time,
            "time": full_time,
            "request": {
                "method": flow.request.method,
                "url": flow.request.url,
                "httpVersion": flow.request.http_version,
                "cookies": [],
                "headers": self.__name_value_split_duplicates(flow.request.headers),
                "queryString": self.__name_value(flow.request.query or {}),
                "headersSize": len(str(flow.request.headers)),
                "bodySize": len(flow.request.content),
            },
            "response": {
                "status": flow.response.status_code,
                "statusText": flow.response.reason,
                "httpVersion": flow.response.http_version,
                "cookies": [],
                "headers": self.__name_value_split_duplicates(flow.response.headers),
                "content": {
                    "size": response_body_size,
                    "compression": response_body_compression,
                    "mimeType": flow.response.headers.get("Content-Type", ""),
                },
                "redirectURL": flow.response.headers.get("Location", ""),
                "headersSize": len(str(flow.response.headers)),
                "bodySize": response_body_size,
            },
            "cache": {},
            "timings": timings,
        }

        if flow.server_conn.connected:
            entry["serverIPAddress"] = str(flow.server_conn.peername[0])

        self.HAR["log"]["entries"].append(entry)
        print("Populated HAR")

    def stop_har(self):
        """
        Stops and saves HAR to file.
        """
        print("Saving HAR to file: ", self.har_file_name)
        if self.har_file_name:
            json_dump: str = json.dumps(self.HAR, indent=2)

            if self.har_file_name == "-":
                mitmproxy.ctx.log(json_dump)
            else:
                raw: bytes = json_dump.encode()
                if self.har_file_name.endswith(".zhar"):
                    raw = zlib.compress(raw, 9)

                with open(os.path.expanduser(self.har_file_name), "wb") as f:
                    print("Path", f)
                    f.write(raw)

                mitmproxy.ctx.log(
                    "HAR dump finished (wrote %s bytes to file)" % len(json_dump)
                )

    def __name_value(self, obj):
        """
        Convert (key, value) pairs to HAR format.
        """
        return [{"name": k, "value": v} for k, v in obj.items()]

    def __name_value_split_duplicates(self, obj):
        """
        Convert (key, value) pairs to HAR format, with duplicate keys added separately.
        Needed for headers so duplicate headers like X-Akamai-Session-Info aren't combined in HAR.
        """
        return [{"name": k, "value": v} for k, v in obj.items(multi=True)]
```

#### System Information
Mitmproxy: 7.0.4
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.10.47-linuxkit-x86_64-with-glibc2.29

We can provide har file for the url if required.

**Comment by Prinzhorn** [comment]
What entries are missing? It looks like you are using the example addon provided here https://github.com/mitmproxy/mitmproxy/blob/main/examples/contrib/har_dump.py . You are welcome to [add missing fields](https://github.com/mitmproxy/mitmproxy/blob/6997129bc07363a69a6414675b195e3e7416827e/examples/contrib/har_dump.py#L106-L136) and share the updated script as a PR. The addon itself is not part of core mitmproxy and as such this is not an issue with mitmproxy.

**Comment by rakayada** [comment]
Yes we are using the code from given link. I know this addon is not part of mitmproxy but is there any plan to include that and are we missing something here in this script. 

**Missing entries when we use mitm -** 
`[
    "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmEU9fBBc4.woff2",
    "https://staging.developer.kingfisher.com/content/home/landing/css/landing.css",
    "https://staging.developer.kingfisher.com/content/home/landing/index.htm?locale=browser",
    "https://staging.developer.kingfisher.com/resources/_VxOhqY7g5Jfh2GourcFlPRg/settings",
    "https://staging.developer.kingfisher.com/resources/style/base.css",
    "https://staging.developer.kingfisher.com/resources/style/global-all.css",
    "https://staging.developer.kingfisher.com/resources/style/reset.css",
    "https://staging.developer.kingfisher.com/resources/style/style.css",
    "https://staging.developer.kingfisher.com/resources/style/supplement.css",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_V-_HpjgJMU8o4PtUJUcarRA/resources/console/i18n/ApplicationResources.properties",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_V-_HpjgJMU8o4PtUJUcarRA/resources/theme/hermosa/SOA/CM/config/metadata.json",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_V-_HpjgJMU8o4PtUJUcarRA/resources/theme/hermosa/SOA/CM/dist/bundles/application-landing.js",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_V-_HpjgJMU8o4PtUJUcarRA/resources/theme/hermosa/SOA/CM/dist/bundles/application.js",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_V-_HpjgJMU8o4PtUJUcarRA/resources/theme/hermosa/i18n/ApplicationResources.properties",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/SOA/CM/extensions/init.js?property.theme=hermosa&property.tenant=kingfisher-staging",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/SOA/CM/extensions/metadata.json",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/SOA/CM/extensions/widget_factory.json",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/SOA/CM/header/views/header.ejs?_=1638851418737",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/SOA/CM/nav/views/nav.ejs?_=1638851418738",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/SOA/CM/search_filter/views/search_filter.ejs?_=1638851418740",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/SOA/CM/user_tools/views/user_tools.ejs?_=1638851418739",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/i18n/CustomApplicationResources.properties",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/i18n/CustomApplicationResources_en-US.properties",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/locales/custom_en-us.json",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/fonts/fontawesome-webfont.woff2?v=4.6.3",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/images/api-portal-logo.png",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/images/favicon.ico",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/images/favicon.ico",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/templates/Document.tmpl.htm",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/templates/footer/footer.htm?_=1638851418741",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/widgets/FooterWidget/FooterWidget.tmpl.htm?property.theme=hermosa&property.tenant=kingfisher-staging"
]`


**Loaded in both mitm and browser mob proxy-** 
`[
    "https://fonts.googleapis.com/css?family=Roboto:400,300,500,700|Roboto+Condensed:400,300,700",
    "https://fonts.gstatic.com/s/roboto/v29/KFOmCnqEu92Fr1Mu4mxK.woff2",
    "https://staging.developer.kingfisher.com/",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_V-_HpjgJMU8o4PtUJUcarRA/resources/console/global/upload.html?dynamic=true",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_V-_HpjgJMU8o4PtUJUcarRA/resources/theme/hermosa/SOA/CM/dist/bundles/init.js",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/SOA/CM/common/notifications/views/global_notifications.ejs",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/custom.css",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/images/loader_bar.gif",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/style.css",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/supplement.css",
    "https://staging.developer.kingfisher.com/ui/apps/atmosphere/_VxOhqY7g5Jfh2GourcFlPRg/resources/theme/hermosa/style/thirdparty.css",
    "https://www.google-analytics.com/analytics.js"
]`

**One Additional entry is present when mitm is used**
`["https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard"]`

**Comment by mhils** [comment]
refs #1477
