### ISSUE TITLE
Transparent mode failure: OSError(92, 'Protocol not available')

### ISSUE THREAD

**Issue by jkorinth** [mitmproxy/mitmproxy#4979]
#### Problem Description
Transparent mode proxying does not work, clients cannot connect to internet; frequent messages in log:

Dec 08 10:26:33 scarif-gw python[1905]: 10.0.0.132:49219: Transparent mode failure: OSError(92, 'Protocol not available')
Dec 08 10:26:33 scarif-gw python[1905]: 10.0.0.132:49219: CONNECT <some URL>:443
Dec 08 10:26:33 scarif-gw python[1905]:                << 502 Bad Gateway 198b

Q1) Is there any way to use transparent mode only on allow-listed URLs, like a hard bypass? I really only want to intercept a specific URL.

Q2) How do I run mitmproxy non-interactively? Is `mitmdump` the way to go?

Tried mitmproxy -k --mode transparent 

#### Steps to reproduce the behavior:
1. mitmproxy -k --mode transparent
2. set server as default gateway in client
3. errors pop up when visiting any website

#### System Information
Mitmproxy: 7.0.4
Python:    3.9.1
OpenSSL:   OpenSSL 1.1.1d  10 Sep 2019
Platform:  Linux-5.10.63-v7l+-armv7l-with-glibc2.28

**Comment by jkorinth** [comment]
Any news on this one?

**Comment by mhils** [comment]
> Transparent mode failure: OSError(92, 'Protocol not available')

This indicates that transparent mode options don't work on your system for some reason. Something in https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/platform/linux.py is throwing that error. Given that this is system specific and this issue is quite old, I'll close it.

**Comment by pmarkiewicz** [comment]
I'd like to reopen issue to understand what could be a problem, I see same message for transparent proxy
 Transparent mode failure: OSError(92, 'Protocol not available')
