### ISSUE TITLE
Improve PR #496

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#498]
PRs are not shown on the issues page, so this issue is just a placeholder. Please go to #496 for the details.

**Comment by Sentient07** [comment]
Hi @mhils . Shall I make those changes made by @gato and send a new PR ?

**Comment by mhils** [comment]
See #496 - if you want to pick this up, please briefly comment there, no need to ask for permission. :-)

**Comment by Sentient07** [comment]
@mhils I think it'd be a bit easier for me if you can merge this to a different branch so that I can pull from that branch and send a new PR ?

**Comment by mhils** [comment]
@Sentient07, I don't see any issues with working on @gato's branch, you can fork that as well.

**Comment by Sentient07** [comment]
@mhils https://github.com/mitmproxy/mitmproxy/pull/499 .
 I wasn't actually sure if there was any merge conflicts from gato's fork. That's why clarified with you on pulling from his branch :)
