### ISSUE TITLE
Google on chromium not detecting 

### ISSUE THREAD

**Issue by LeosSire** [mitmproxy/mitmproxy#4980]
When using MITMproxy on www.google.com in chromium, mitmproxy isn’t able to detect traffic. The work around is to clear cookies and F5 at which point it works. Then once the page is loaded it resorts to not detecting again. Firefox seems to work okay/consistently. 

A number of sub google domains (aa.) are detected but not the primary google search. 
 
I presume chromium uses a pinned certificate but there aren’t any tls errors thrown in the console. My next thought is it’s using a web socket but that feels extreme. 

Has anyone else faced this?

Using chromium on Linux Mint.

**Comment by Prinzhorn** [comment]
I assume it's cached and that's why you don't see it in mitmproxy? Please describe what exactly you're missing and provide steps to reproduce it. You say it's working in Firefox, can you share screenshots of Firefox vs Chromium?

**Comment by CypherpunkSamurai** [comment]
I agree with @Prinzhorn. Please try using the developer tools network tab with `Disable Cache` checked. If you observe the same issue again it then can be due to TLS.

**Comment by LeosSire** [comment]
Repo steps:
1. Go to google.com
2. clear cookies
3. Search a random term
4. [mitmproxy is able to interpret traffic and content]
5. Perform another search
6. [traffic doesn't hit mitmproxy and its off doing its own thing]

The below image shows me searching the term 'hello' and you can see the entry. After I searched another term and it doesn't show. 

As per @CypherpunkSamurai 's suggestion, I have checked `Disable Cache` in the network window of the inspector

![image](https://user-images.githubusercontent.com/1334981/145657354-726506d8-6462-4608-a695-4c73f54332b3.png)

And for good measure here is the response headers from the search. As you can see there isn't a HPKP header which would imply switching over to a pinned cert. 

![image](https://user-images.githubusercontent.com/1334981/145657633-5a8d11d3-5b81-4f28-924d-1da5f81d09a9.png)

Is there a header type I'm not aware of which is forcing the the pinning? I wouldn't have thought it would be in the body of the response, I would have thought that would be outside of the reach of a DOM object. 

Thoughts...?

**Comment by CypherpunkSamurai** [comment]
AFAIK Google uses protobuf for almost everything. Although I'm not sure if they switch protocols for Google search yet, but there's a possibility that they're switching to it because you're using a chome based browser.

Can you please provide us your system and browser info?

**Comment by mhils** [comment]
You cannot get traffic through mitmproxy without it also showing up in the interface. Google likely does some additional encoding here, for example protobuf. :)
