### ISSUE TITLE
Mitmweb cannot read properties of undefined (reading 'scheme') at TLSColumn

### ISSUE THREAD

**Issue by KevinLi-py** [mitmproxy/mitmproxy#4999]
#### Problem Description
I was trying to use mitmweb to capture the network traffic of my android phone.
I opened Wechat App on the phone and tried to send a message to my friend.
Suddenly the mitmweb interface crashed, everything disappeared. I opened the Chrome Devtools and saw the following error at the Console tab:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'scheme')
    at TLSColumn (app.js:50)
    at beginWork (vendor.js:122)
    at o (vendor.js:122)
    at u (vendor.js:122)
    at c (vendor.js:122)
    at f (vendor.js:122)
    at p (vendor.js:122)
    at Object.enqueueSetState (vendor.js:122)
    at i.v.setState (vendor.js:167)
    at i.onStateChange (vendor.js:128)
TLSColumn @ app.js:50
beginWork @ vendor.js:122
o @ vendor.js:122
u @ vendor.js:122
c @ vendor.js:122
f @ vendor.js:122
p @ vendor.js:122
enqueueSetState @ vendor.js:122
v.setState @ vendor.js:167
i.onStateChange @ vendor.js:128
notify @ vendor.js:155
t.notifyNestedSubs @ vendor.js:155
i.onStateChange @ vendor.js:128
notify @ vendor.js:155
t.notifyNestedSubs @ vendor.js:155
i.onStateChange @ vendor.js:128
c @ vendor.js:182
(anonymous) @ vendor.js:239
value @ app.js:8
(anonymous) @ app.js:8
```
But there was nothing at the terminal output of the server side.
I refreshed the page, and it crashed again:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'scheme')
    at TLSColumn (app.js:50)
    at beginWork (vendor.js:122)
    at o (vendor.js:122)
    at u (vendor.js:122)
    at c (vendor.js:122)
    at batchedUpdates (vendor.js:122)
    at qb (vendor.js:122)
    at ob (vendor.js:122)
    at Object.batchedUpdates (vendor.js:122)
    at dispatchEvent (vendor.js:122)
TLSColumn @ app.js:50
beginWork @ vendor.js:122
o @ vendor.js:122
u @ vendor.js:122
c @ vendor.js:122
batchedUpdates @ vendor.js:122
qb @ vendor.js:122
ob @ vendor.js:122
batchedUpdates @ vendor.js:122
dispatchEvent @ vendor.js:122
```
I have also tried other apps, and the same thing happened.
I don't know what this meant, but I think it's a bug of mitmweb. At least mitmweb shouldn't crash.

#### Steps to reproduce the behavior:
1. Open a terminal and execute 'mitmweb'
2. Use an android phone to connect to the mitmproxy.
3. Open an app like Wechat and perform some actions.
4. Mitmweb crashed.

#### System Information
Mitmproxy: 7.0.4
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1k  25 Mar 2021
Platform:  macOS-10.16-x86_64-i386-64bit

**Comment by KevinLi-py** [comment]
Chrome version:
```
Google Chrome | 96.0.4664.110 (Official Build) (x86_64)
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | macOS Version 11.3.1 (Build 20E241)
JavaScript | V8 9.6.180.21
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
```

**Comment by Prinzhorn** [comment]
https://github.com/mitmproxy/mitmproxy/search?q=Cannot+read+properties+of+undefined+%28reading+%27scheme%27%29&type=issues

Thanks, this is a duplicate and already fixed in the main branch but not released

https://github.com/mitmproxy/mitmproxy/issues/4581
https://github.com/mitmproxy/mitmproxy/issues/4844
