### ISSUE TITLE
Release v7.0.4 requires new version of glibc (GLIBC_v2.27)

### ISSUE THREAD

**Issue by s2504s** [mitmproxy/mitmproxy#5009]
#### Problem Description
Release v7.0.4 requires new version of glibc (GLIBC_v2.27)
Currenly I am using mitmproxy `v7.0.3` After the upgrading mitmproxy to the version `v7.0.4` I got the error
```
bash-4.2# mitmproxy --version
[76] Error loading Python lib '/tmp/_MEI31dNxN/libpython3.9.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/_MEI31dNxN/libpython3.9.so.1.0)
```

#### Steps to reproduce the behavior:
1.  Use OS `Amazon linux 2` or something with GLIBC_v2.26
2. Install or upgrade mitmproxy to the version v7.0.4

#### System Information
Paste the output of "mitmproxy --version" here.
```
bash-4.2# mitmproxy --version
Mitmproxy: 7.0.3 binary
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-4.15.0-140-generic-x86_64-with-glibc2.26
```

**Comment by mhils** [comment]
We're using PyInstaller to build binaries, which makes them require a glibc version greater or equal than what they were built with. To mitigate this, we're using the oldest Ubuntu version that is available on GitHub Actions. Unfortunately Ubuntu 16.04 was recently deprecated on GHA, so 7.0.4 now requires whatever is shipped with Ubuntu 18.04. 

There are a few other solutions (e.g. building binaries using Docker), but that adds quite a bit of maintenance as we then need to continuously get new Python versions running on old distros. Long story short, I'm afraid you need to work around this on your end for the forseeable future. We have alternative installation methods listed at https://docs.mitmproxy.org/dev/overview-installation/.
