### ISSUE TITLE
DLL load failed while importing _brotli

### ISSUE THREAD

**Issue by 89z** [mitmproxy/mitmproxy#5015]
If I install:

~~~
pip install mitmproxy
~~~

Then try to run:

~~~
mitmproxy
~~~

I get this:

~~~
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\python\Scripts\mitmproxy.exe\__main__.py", line 4, in <module>
  File "C:\python\lib\site-packages\mitmproxy\tools\main.py", line 8, in <module>
    from mitmproxy import exceptions, master
  File "C:\python\lib\site-packages\mitmproxy\master.py", line 10, in <module>
    from mitmproxy import eventsequence
  File "C:\python\lib\site-packages\mitmproxy\eventsequence.py", line 6, in <module>
    from mitmproxy import http
  File "C:\python\lib\site-packages\mitmproxy\http.py", line 28, in <module>
    from mitmproxy.net import encoding
  File "C:\python\lib\site-packages\mitmproxy\net\encoding.py", line 11, in <module>
    import brotli
  File "C:\python\lib\site-packages\brotli.py", line 8, in <module>
    import _brotli
ImportError: DLL load failed while importing _brotli: The specified module could not be found.
~~~

**Comment by mhils** [comment]
Which Windows version is this? Which Python version is this? What's the output of `pip freeze`?

**Comment by 89z** [comment]
> Which Windows version is this?

10

> Which Python version is this?

~~~
PS C:\> python.exe -V
Python 3.9.6
~~~

> What's the output of `pip freeze`?

~~~
asgiref==3.4.1
blinker==1.4
Brotli==1.0.9
certifi==2021.10.8
cffi==1.15.0
click==8.0.3
colorama==0.4.4
cryptography==3.4.8
Flask==2.0.2
h11==0.12.0
h2==4.1.0
hpack==4.0.0
hyperframe==6.0.1
itsdangerous==2.0.1
Jinja2==3.0.3
kaitaistruct==0.9
ldap3==2.9.1
MarkupSafe==2.0.1
mitmproxy==7.0.4
msgpack==1.0.3
passlib==1.7.4
protobuf==3.18.1
publicsuffix2==2.20191221
pyasn1==0.4.8
pycparser==2.21
pydivert==2.1.0
pyOpenSSL==20.0.1
pyparsing==2.4.7
pyperclip==1.8.2
ruamel.yaml==0.17.16
ruamel.yaml.clib==0.2.6
six==1.16.0
sortedcontainers==2.4.0
tornado==6.1
urwid==2.1.2
Werkzeug==2.0.2
wsproto==1.0.0
zstandard==0.15.2
~~~

This is strange, I dont seem to be getting the origin error anymore, but I found a new error. If I try to uninstall, I get this:

~~~
PS C:\> pip uninstall -y (pip freeze)
WARNING: Ignoring invalid distribution -rotli (c:\python\lib\site-packages)
Found existing installation: certifi 2021.10.8
Uninstalling certifi-2021.10.8:
  Successfully uninstalled certifi-2021.10.8
~~~

**Comment by 89z** [comment]
I tried upgrading my Python, but its even worse now:

~~~
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
~~~

It seems a bunch of the Python packages require a C++ compiler? Thats unfortunate as I dont have that and am not going to install it. I guess I will continue to use the prebuilt version here:

https://mitmproxy.org/downloads

**Comment by mhils** [comment]
You might be running into https://github.com/google/brotli/issues/782. The problem is that "import brotli" fails on your system, which really is a bit outside of what we control.

**Comment by 89z** [comment]
Yeah it seems Windows users need to install the Redistributable [1]. I think it would be helpful to document that here [2].

1. https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
2. https://docs.mitmproxy.org/stable/overview-installation/#advanced-installation

**Comment by mhils** [comment]
Ah, thanks for confirming this. May I add one more question: How did you install Python? Did you use the installer from python.org?

**Comment by 89z** [comment]
I use the embedded package, as it is small size (only 8 MB):

https://python.org/ftp/python/3.10.1/python-3.10.1-embed-amd64.zip

**Comment by mhils** [comment]
Ah, that explains it. The regular installer installs vcredist by default, which is why this issue normally does not come up.

 https://docs.python.org/3/using/windows.html#the-embeddable-package mentions that the embedded distribution is not intended to be directly accessed by end-users. I'm somewhat opposed to documenting that explicitly now, folks will run into it anyways and googling the error message should solve it.

**Comment by 89z** [comment]
https://github.com/mitmproxy/mitmproxy/issues/5141

**Comment by xtefluo** [comment]
很有用
