### ISSUE TITLE
"ConnectionTerminated error_code:ErrorCodes.PROTOCOL_ERROR" for some sites

### ISSUE THREAD

**Issue by DUOLabs333** [mitmproxy/mitmproxy#5018]
#### Problem Description
When connecting to some sites through mitmproxy, I can't connect, instead getting `ConnectionTerminated error_code:ErrorCodes.PROTOCOL_ERROR`

#### Steps to reproduce the behavior:
1. Run `mitmdump` with `LANG=en_US.UTF-8 mitmdump --listen-host 127.0.0.1 -p 2011  -s history.py --set stream_large_bodies="1m" --set stream_websockets=true`
`history.py`:
```
from mitmproxy import http
from datetime import datetime
from bs4 import BeautifulSoup

def responseheaders(flow):
    if not flow.request.headers['accept'].startswith('text/html,application/xhtml+xml,application/xml'):
        flow.response.stream = True

def response(flow: http.HTTPFlow):
    if flow.request.headers['accept'].startswith('text/html,application/xhtml+xml,application/xml'):
        try:
            title=BeautifulSoup(flow.response.content).title.string
        except:
            return
        file=str(datetime.fromtimestamp(int(flow.response.timestamp_start))).split(' ')[0]
        with open('../logs/ '[:-1]+file,'a+') as f:
            f.write(str(datetime.fromtimestamp(int(flow.response.timestamp_start)))+ ' '+title+' '+str(flow.request.url)+'\n\n')
```
2. Try to connect to `https://vladtalks.tech/vpn/how-to-turn-off-vpn-on-mac`
3. Fail with `HTTP/2 connection closed: <ConnectionTerminated error_code:ErrorCodes.PROTOCOL_ERROR, last_stream_id:0, additional_data:None>`

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 7.0.4
Python:    3.9.9
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.15.5-1-ARCH-aarch64-with-glibc2.32
```

**Comment by DUOLabs333** [comment]
This is solved with `--no-http2`

**Comment by mhils** [comment]
For the record, the problem here is a bug in the HTTP/2 implementation of the website in question (vladtalks.tech).

Upon connect, mitmproxy sends an initial HTTP/2 settings frame with ENABLE_CONNECT_PROTOCOL=0. vladtalks.tech does not understand that and closes the connection with a protocol error. If they would follow RFC 7540, they would ignore the setting instead:

> An endpoint that receives a SETTINGS frame with any unknown or unsupported identifier MUST ignore that setting.

As long as this only affects isolated websites, we are not going to work around their implementation bugs. For completion, here's the WireShark hex dump:

```
    00000000  00 00 0c 04 00 00 00 00  00                        ........ .
    00000009  00 03 00 00 00 fa 00 04  00 10 00 00 00 00 04 08   ........ ........
    00000019  00 00 00 00 00                                     .....
    0000001E  00 0f 00 01                                        ....
00000000  50 52 49 20 2a 20 48 54  54 50 2f 32 2e 30 0d 0a   PRI * HT TP/2.0..
00000010  0d 0a 53 4d 0d 0a 0d 0a  00 00 2a 04 00 00 00 00   ..SM.... ..*.....
00000020  00 00 01 00 00 10 00 00  02 00 00 00 00 00 04 00   ........ ........
00000030  00 ff ff 00 05 00 00 40  00 00 08 00 00 00 00 00   .......@ ........
00000040  03 00 00 00 64 00 06 00  01 00 00                  ....d... ...
0000004B  00 00 00 04 01 00 00 00  00                        ........ .
    00000022  00 00 08 07 00 00 00 00  00                        ........ .
    0000002B  00 00 00 00 00 00 00 01                            ........ 
```

**Comment by DUOLabs333** [comment]
So what does `--no-http2` do?

**Comment by mhils** [comment]
It disables HTTP/2, which makes mitmproxy fall back to HTTP/1 (where the bug is not present).

**Comment by DUOLabs333** [comment]
Update: it seems that vladtalks.tech fixed its problem, so the flag is no longer needed.
