### ISSUE TITLE
mitmweb: Fix sourcemaps

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#502]
We have a pretty cool [gulp](http://gulpjs.com/)-based build system for mitmweb. You'll find the web sources in `web/` and gulp copies the bundled files into `libmproxy/web/static/`. This works great, but the sourcemaps we're generating are still wrong:

![screenshot](https://maximilianhils.com/upload/2015-03/2015-03-05_01-55-54.png)

We should fix this, they are super handy when debugging/developing within the chrome devtools.

**Comment by sunu** [comment]
@mhils Is this a windows only issue? Can't reproduce on linux.

**Comment by legendtang** [comment]
@sunu nope. I cannot reproduce either.

**Comment by mhils** [comment]
Could be. This is what I'm seeing on Windows in the Chrome Sources View, sourcemaps enabled:

![screenshot](https://maximilianhils.com/upload/2015-03/2015-03-05_19-20-37.png)

The slashes should be forward-slashes rather than backward slashes and there shouldn't be absolute paths, but this might be a Windows issue so I could live with it. In any case, the first step should be to separate the sourcemap from the JS file. so that we have a dedicated `app.js.map` file - this probably means we simply need to configure gulp-sourcemaps properly. :smiley:
