### ISSUE TITLE
Make sure no Paket is ever sent to the real target in Server Replay mode

### ISSUE THREAD

**Issue by woozar** [mitmproxy/mitmproxy#5024]
I am using the server replay functionality to mock our hardware-token-validation service for our ui tests (so that we can log in for the tests). The idea is, that we use the recorded response and do never send the any request to the real server, because that would lock the account.

Getting the recorded answer is working properly, but my account was locked for the third time this week (since i am working on the mocking part), so i wondered if there was a chance, the proxy would send requests to the real endpoint. Sadly in our infrastructure, I cannot sniff the traffic or do any other analysis and also the IT team cannot tell me any details on why the accopunt was locked. 

i am starting the server with:

mitmproxy --listen-port 8082 --ssl-insecure --server-replay mytape --server-replay-kill-extra

**Comment by mhils** [comment]
`--server-replay-kill-extra` will make sure that no requests will reach the destination server. mitmproxy may however open a TCP connection and negotiate a TLS handshake with the upstream host. 
You can disable that by passing `--set upstream_cert=false --set connection_strategy=lazy`.

**Comment by woozar** [comment]
I did some testing with the IT department together and nothing reaches the token server. It must have been me being stupid or not carful enough or something. Thanks for your help!
