### ISSUE TITLE
Bug: overriding proxy auth still returns 401

### ISSUE THREAD

**Issue by hazcod** [mitmproxy/mitmproxy#5028]
#### Problem Description
If I override the SOCKS auth to be successful in the Addon `socks5_auth` hook, I still receive:
1. `www-authenticate: Basic realm="mitmproxy"` HTTP response header
2. 407 Unauthorized response

#### Steps to reproduce the behavior:
1. Load a plugin with:
```py
    def socks5_auth(self, data: mitmproxy.proxy.layers.modes.Socks5AuthData):
        data.valid = True
        return
```
2.  Run mitmproxy in `socks5` mode.
3. See it return:
```
< HTTP/2 401 
< www-authenticate: Basic realm="mitmproxy"
< content-length: 95
< 
* Connection #0 to host 127.0.0.1 left intact
<html><head><title>401 Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>%     
```

I did testing via:
```shell
% export ALL_PROXY='socks5h://foobar@127.0.0.1:8080'
% curl -v -k https://ifconfig.me
```

#### System Information
Main, commit ef8c88d

**Comment by mhils** [comment]
The builtin ProxyAuth addon is currently running before user addons. It checks if the SOCKSv5 credentials are valid and caches that state for the entire client connection:

https://github.com/mitmproxy/mitmproxy/blob/f8826b29a24b51ef8fe6b9dbf574477db007592b/mitmproxy/addons/proxyauth.py#L62-L65

If you override `.valid` afterwards, the SOCKSv5 authentication will pass, but the caching part in line 65 did not happen, so the proxyauth addon then expects HTTP authentication again. Not sure what's the best way to solve this in the long term, but one workaround would be to set proxyauth to `any` and then explicitly set `.valid` to False in your own addon. But then #5029 becomes even more relevant of course. :)

**Comment by hazcod** [comment]
@mhils Curious, so if I set `proxyauth` to `any` It'll still return a 407 🤔 
```
    def socks5_auth(self, data: proxy.layers.modes.Socks5AuthData):
        data.valid = False

        token = data.username or data.password
        if not token:
            ctx.log.debug('no socks auth detected')
            return

        tokenData = self.authCache.get(data.client_conn)
        if not tokenData:
            try:
                tokenData = self.decryptToken(token)
                self.authCache[data.client_conn] = tokenData
            except Exception as e:
                ctx.log.warn('invalid token in request: ' + str(e))
                return
        
        ctx.log.debug('socks authentication successful')
        data.valid = True
        return
```

**Comment by mhils** [comment]
`mitmdump --mode socks5 --proxyauth any` combined with the curl command you posted works fine for me.
