### ISSUE TITLE
Add a trusted CA

### ISSUE THREAD

**Issue by DUOLabs333** [mitmproxy/mitmproxy#5045]
#### Problem Description
I have my own self-signed CA, so it is not trusted by `mitmproxy`. I'm currently using `--ssl-insecure`, though this is obviously not best practice. The options currently available (`--set ssl_verify_upstream_trusted_ca`) replace the trusted CA's, so only my self-signed CA is trusted.

#### Proposal
Add some sort of option that can be repeated, like `--add-trused-ca`, which points to the path of a trusted CA.

#### Alternatives
Maybe a folder in `.mitmproxy`, where all of your custom CA's have to be in?

#### Additional context
Add any other context or screenshots about the proposal here.

**Comment by mhils** [comment]
refs #5019

There are the `ssl_verify_upstream_trusted_confdir` and `ssl_verify_upstream_trusted_ca`, which should be documented on https://docs.mitmproxy.org/dev/concepts-certificates/ (contributions welcome!).

If I understand https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_load_verify_locations.html correctly, OpenSSL expects one file and one file only. We could do some shenanigans where we securely copy the default file and append a user-added CA. If someone wants to give this a stab I'd be happy to review a PR.

**Comment by DUOLabs333** [comment]
I can try -- where is the default certificate loaded?

**Comment by DUOLabs333** [comment]
I'm willing to work on this -- where should I start?

**Comment by mhils** [comment]
We set the CA file here: https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/addons/tlsconfig.py#L223
I can't give you much more guidance at the moment, sorry.

**Comment by DUOLabs333** [comment]
I found it easier to just set `ssl_verify_upstream_trusted_confdir` to `/etc/ssl/certs`.
