### ISSUE TITLE
Send HTTP/2 PING frames to keep connections alive.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#5046]
### Discussed in https://github.com/mitmproxy/mitmproxy/discussions/5044

<div type='discussions-op-text'>

<sup>Originally posted by **EndUser509** January 10, 2022</sup>
I have noticed that for instance https://heise.de, when proxied, returns a '502' HTTP error to the client when I click on a link after not doing anything (=reading the page) for over 60 seconds. What I see on the outgoing interface is that the remote server resets the connection the moment the connection is used again (TCP RST). 
When not proxied I observe that the client sends a HTTP/2 PING after 60 seconds which seems to keep the connection alive. Varying the idle time from 60 to 120 seconds, I never manage to reset the connection and a link always loads. 
I wonder if there is a way to remedy the proxied behavior. I am not familiar enough with HTTP/2 to see if this PING interval is something that client and server agree to. Or if this is 'best practice' for browsers. Any ideas where to start? Would it make sense that the proxy sends regular PINGs for idle HTTP/2 connections? </div>

**Comment by EndUser509** [comment]
This ca be closed now, thanks for the final changes to the PR and merging it! :100:
