### ISSUE TITLE
can't import tls from mitmproxy

### ISSUE THREAD

**Issue by deadpool-liu** [mitmproxy/mitmproxy#5047]
#### Steps to reproduce the behavior:
1. i add a script form theproject to avide tls connection error
2. however an import error comes out ,cant import tls from mitmproxy
3. it works and the requests url will be show on shell,however the response didnot throuth from the way def response(self, flow)
4. here are the code
5. 

    1. import collections
       import random
       from abc import ABC, abstractmethod
       from enum import Enum
    
    from mitmproxy import connection, ctx, tls
    
    # from mitmproxy import tls
    
    from mitmproxy.utils import human
    
    
    
    #
    #
    #
    
    
    
    
    
    
    
    class InterceptionResult(Enum):
        SUCCESS = 1
        FAILURE = 2
        SKIPPED = 3
    
    
    class TlsStrategy(ABC):
        def __init__(self):
            # A server_address -> interception results mapping
            self.history = collections.defaultdict(lambda: collections.deque(maxlen=200))
    @abstractmethod
    def should_intercept(self, server_address: connection.Address) -> bool:
        raise NotImplementedError()
    
    def record_success(self, server_address):
        self.history[server_address].append(InterceptionResult.SUCCESS)
    
    def record_failure(self, server_address):
        self.history[server_address].append(InterceptionResult.FAILURE)
    
    def record_skipped(self, server_address):
        self.history[server_address].append(InterceptionResult.SKIPPED)

class ConservativeStrategy(TlsStrategy):
    """
    Conservative Interception Strategy - only intercept if there haven't been any failed attempts
    in the history.
    """

    def should_intercept(self, server_address: connection.Address) -> bool:
        return InterceptionResult.FAILURE not in self.history[server_address]

class ProbabilisticStrategy(TlsStrategy):
    """
    Fixed probability that we intercept a given connection.
    """

    def __init__(self, p: float):
        self.p = p
        super().__init__()
    
    def should_intercept(self, server_address: connection.Address) -> bool:
        return random.uniform(0, 1) < self.p

class MaybeTls:
    strategy: TlsStrategy

    def load(self, l):
        l.add_option(
            "tls_strategy", int, 0,
            "TLS passthrough strategy. If set to 0, connections will be passed through after the first unsuccessful "
            "handshake. If set to 0 < p <= 100, connections with be passed through with probability p.",
        )
    
    def configure(self, updated):
        if "tls_strategy" not in updated:
            return
        if ctx.options.tls_strategy > 0:
            self.strategy = ProbabilisticStrategy(ctx.options.tls_strategy / 100)
        else:
            self.strategy = ConservativeStrategy()
    
    def tls_clienthello(self, data: tls.ClientHelloData):
        server_address = data.context.server.peername
        if not self.strategy.should_intercept(server_address):
            ctx.log(f"TLS passthrough: {human.format_address(server_address)}.")
            data.ignore_connection = True
            self.strategy.record_skipped(server_address)
    
    def tls_established_client(self, data: tls.TlsData):
        server_address = data.context.server.peername
        ctx.log(f"TLS handshake successful: {human.format_address(server_address)}")
        self.strategy.record_success(server_address)
    
    def tls_failed_client(self, data: tls.TlsData):
        server_address = data.context.server.peername
        ctx.log(f"TLS handshake failed: {human.format_address(server_address)}")
        self.strategy.record_failure(server_address)

    class Counter(MaybeTls):
        def __init__(self):
            MaybeTls.__init__(self)
            # self.num = 0
            self.page_data = ""
            self.part_one = ""
            self.part_two = ""
            self.send = True
        def response(self, flow):
            print(f"===={flow.request.url}====")
    
            tik_data = "aid=1988"
            if tik_data in flow.request.url:
                text = flow.response.text
    
                with open("/mnt/sda/project/scraw/ads/ads/Log/PageView/data.txt", "w", encoding="u8") as f:
                    f.write(text)
#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 5.3.0
Python:    3.7.9
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core

**Comment by mhils** [comment]
You are using mitmproxy 5.3.0, the script you posted is for mitmproxy 7.

**Comment by deadpool-liu** [comment]
> You are using mitmproxy 5.3.0, the script you posted is for mitmproxy 7.

seems right,so where i can find the script fit my version?
for 5.3.0 is the newest version i can get in centos

**Comment by deadpool-liu** [comment]
> > You are using mitmproxy 5.3.0, the script you posted is for mitmproxy 7.
> 
> seems right,so where i can find the script fit my version? for 5.3.0 is the newest version i can get in centos

i tryed to find in site and github of this project,however,no result even up to now.

**Comment by mhils** [comment]
You can get a more recent version from https://mitmproxy.org/. We do not provide support for older releases. You may be able to find older examples at https://github.com/mitmproxy/mitmproxy/tree/main/examples (select the correct Git tag)

**Comment by deadpool-liu** [comment]
thankyou very much,it will help me a lot on my direction。and i even consider i will get replay severy days later. but your speed sprized me!
