### ISSUE TITLE
response.refresh() gives OSError on Windows

### ISSUE THREAD

**Issue by kimberlythegeek** [mitmproxy/mitmproxy#5054]
```
Navigating to secondary url:https://www.bing.com/search?q=barack+obama+quotes
Navigating to url https://www.bing.com/search?q=barack+obama+quotes iteration 25
Addon error: Traceback (most recent call last):'
Error: b'  File "C:\\Users\\task_1641995085\\build\\venv\\lib\\site-packages\\mozproxy\\backends\\mitm\\scripts\\alt-serverplayback.py", line 250, in request'
Error: b'    response.refresh()'
Error: b'  File "mitmproxy\\http.py", line 1188, in refresh'
Error: b'  File "email\\utils.py", line 147, in formatdate'
Error: b'OSError: [Errno 22] Invalid argument'
```
This error only occurs on windows. I have been able to run mitmproxy from source with our test harness, and added log statements to output the parameters being passed to `formatdate`. I've verified in a python terminal that the parameters are valid.

This did not occur until we updated from mitmproxy 5.1.1 to 7.0.4. I've checked the source code for the previous versions, and though the code has been moved around, there is no difference in the calls being made in `response.refresh()`

**Comment by mhils** [comment]
Thanks for the clear report! Could you share the concrete arguments passed to `formatdate` please?

**Comment by kimberlythegeek** [comment]
Well we know `usegmt` is always true, but when looking for examples of `new`, I've found the issue. Most of the time it prints valid values like `1641850717.0697627`, but the next value that was printed out was negative: `-11644030337.930237`, which returns the above `OSError` when run in a python prompt.

**Comment by kimberlythegeek** [comment]
could it be caused by this line? `delta = now - self.timestamp_start`

Unsure how else we'd end up with a negative value

**Comment by mhils** [comment]
Hm - this definitely is weird. Could you potentially add a
```python
print(f"{delta=} {self.timestamp_start=} {i=} {self.headers[i]=} {d=} {new=}")
```
log statement and report back what that yields for the offending flow?

**Comment by kimberlythegeek** [comment]
`delta=1133852.30330801 self.timestamp_start=1641407457.1147604 i='last-modified' self.headers[i]='Mon, 01 Jan 1601 00:00:00 GMT' d=(1601, 1, 1, 0, 0, 0, 0, 1, -1, 0) new=-11643339747.696692`

`delta=1133830.6156322956 self.timestamp_start=1641407480.3896403 i='last-modified' self.headers[i]='Mon, 01 Jan 1601 00:00:00 GMT' d=(1601, 1, 1, 0, 0, 0, 0, 1, -1, 0) new=-11643339769.384367`

two examples of flows with negative values

**Comment by kimberlythegeek** [comment]
every negative value has the same `last-modified` date of Jan 1, 1601

**Comment by mhils** [comment]
Excellent, that is a great repro. #5078 has the fix, thanks again! 😃

**Comment by kimberlythegeek** [comment]
awesome, thanks for getting on this so quickly!
