### ISSUE TITLE
Stream responses, but not requests

### ISSUE THREAD

**Issue by DUOLabs333** [mitmproxy/mitmproxy#5060]
#### Problem Description

I have a script that basically logs my browsing history. Thus, I only need to MITM the responses, rather than my requests. However, setting `stream_large_bodies=1` is for requests and responses.

#### Proposal
Maybe split up the option for streaming for both requests and responses?

#### Additional context
Add any other context or screenshots about the proposal here.

**Comment by mhils** [comment]
In this case I would just enable streaming manually: https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/http-stream-simple.py
