### ISSUE TITLE
Cannot be set ldap port

### ISSUE THREAD

**Issue by ingen2** [mitmproxy/mitmproxy#5068]
#### Problem Description:

My LDAP services is on custom port (not in 389) , I try to set port after url but this error has occourd:

'Invalid ldap specification'

How to set ldap port on mitm proxy?

my command:

mitmproxy --set proxyauth="ldap:11.11.11.11:_PORT_:cn=admin,ou=admins,dc=com:pass:ou=admins,dc=com"

**Comment by mhils** [comment]
It seems like that is simply not supported at the moment. The relevant code is at https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/addons/proxyauth.py.

**Comment by mhils** [comment]
Fixed by #5161! :)
