### ISSUE TITLE
Support intercept SMTP TLS traffic after STARTTLS command

### ISSUE THREAD

**Issue by guyskk** [mitmproxy/mitmproxy#5071]
#### Problem Description

I want to debug some SMTP TLS traffic by route SMTP traffic to mitmproxy socks5 proxy. But it seems mitmproxy not able to decrypt TLS messages after SMTP [STARTTLS](https://en.wikipedia.org/wiki/Opportunistic_TLS) command.

#### Proposal

Maybe auto detect TLS handshake flow, then intercept subsequent messages. https://stackoverflow.com/questions/3897883/how-to-detect-an-incoming-ssl-https-handshake-ssl-wire-format

#### Alternatives

Alternative solution is make mitmproxy understand SMTP protocol and STARTTLS command, but it's seems out of scope, and is not a general solution.

#### Additional context

```
mitmdump --version
Mitmproxy: 7.0.4
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-11.6.2-x86_64-i386-64bit
```

My usage:

```bash
mitmdump -p 8899 --mode socks5 -w mitmdumpfile
```

SMTP demo client:

```python
import smtplib
import socket

# pip install pysocks
import socks

socks.set_default_proxy(socks.SOCKS5, "127.0.0.1", 8899)
socket.socket = socks.socksocket

cli = smtplib.SMTP("test.mailu.io")
print(cli.ehlo("gmail.com"))
print(cli.noop())

print(cli.starttls())
print(cli.ehlo("gmail.com"))
print(cli.noop())
```

mitmdumpfile output:
```txt
8051:7:version;2:14#8:messages;6926:64:5:false!31:220 test.mailu.io ESMTP ready
,17:1642489793.321321^]48:4:true!16:ehlo gmail.com
,17:1642489793.335378^]165:5:false!130:250-test.mailu.io
250-PIPELINING
250-SIZE
250-2000000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 STARTTLS
,18:1642489793.6238441^]37:4:true!6:noop
,17:1642489793.633712^]47:5:false!14:250 2.0.0 OK
,17:1642489793.931099^]42:4:true!10:STARTTLS
,17:1642489793.935652^]54:5:false!21:220 2.0.0 Start TLS
,17:1642489794.237709^]550:4:true!517:������Ð����,ݲke�[��,VVV�b�� x��la/���2t��w��C?�N��dO��t>�,�0�̨̩̪�+�/��$�(k�#�'g�
�9�	�3��=<5/�u
test.mailu.io

#
```

**Comment by Prinzhorn** [comment]
Refs https://github.com/mitmproxy/mitmproxy/issues/4215

**Comment by guyskk** [comment]
Thank you @Prinzhorn! closed this as duplicated.
