### ISSUE TITLE
`Set-Cookie` header not set properly when cookies are modified 

### ISSUE THREAD

**Issue by Speedlulu** [mitmproxy/mitmproxy#5085]
#### Problem Description
Described here https://github.com/mitmproxy/mitmproxy/pull/5084

#### Steps to reproduce the behavior:
1. Have a server set a cookie with en empty attributes (`Secure`, `HttpOnly` ...)
2. Edit `CookieAttrs` object of said object
3. Assign `(value, CookieAttrs)` tuple to the `flow.response.cookies` object
4. Response header will now have empty attribute in `Set-Cookie` header set as `Secure=; HttpOnly=`

#### System Information
Mitmproxy: 7.0.4
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.11.0-46-generic-x86_64-with-glibc2.29

#### Pull request
I have created a pull request (https://github.com/mitmproxy/mitmproxy/pull/5084) to try to fix the issue, it works well for my use but it might break parts of the app that I'm not aware and/or don't use.

**Comment by mhils** [comment]
Thank you for the clear report. Your PR looks great on first sight, it just may take me a bit before I find some time to dig into the relevant parts of the codebase and see if this breaks anything. 👍

**Comment by Speedlulu** [comment]
Alrighty let met know if you need anything along the way :)

**Comment by Prinzhorn** [comment]
While searching for something entirely unrelated I randomly came across https://github.com/mitmproxy/mitmproxy/issues/1512 which I think refs this and can be closed after the PR is merged? It also points towrds HAR dump, so maybe the contrib example addon is affected by this change as well.

**Comment by Speedlulu** [comment]
@Prinzhorn This is indeed while working with `SameSite` cookies that I ran into this problem.

**Comment by Prinzhorn** [comment]
@mhils can this issue and https://github.com/mitmproxy/mitmproxy/issues/1512 be closed now?
