### ISSUE TITLE
Connection killed with client certificate

### ISSUE THREAD

**Issue by mrsiano** [mitmproxy/mitmproxy#5087]
#### Problem Description
we trying to use client certificate (.pem) and receiving  
Server TLS handshake failed. Certificate verify failed: unable to get local issuer certificate
We saw similiar issue and workaround suggestion https://github.com/mitmproxy/mitmproxy/issues/5019#issuecomment-1004168018 which almost works. 
the above hook fixed the Certificate issue, but then it leads to httpFlow.error 'Client Disconnect'
![image](https://user-images.githubusercontent.com/13570786/150775901-9cd679be-20a2-4b8d-8ab5-b864ddfd828f.png)

#### Steps to reproduce the behavior:
1. using client certificate (pem file)

#### System Information
Mitmproxy: 7.0.4 binary
Python: 3.9.7
OpenSSL: OpenSSL 1.1.1l 24 Aug 2021
Platform: macOS-10.15.7-x86_64-i386-64bit

**Comment by mhils** [comment]
See #5094.

To put it very nicely, please don't post twice.
