### ISSUE TITLE
Inconsistent type of Request.scheme

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#5090]
#### Problem Description

In the constructor `scheme` is typed as `bytes`

https://github.com/mitmproxy/mitmproxy/blob/83b43b93a7ac6cf2bfe557964fd63b376e158e25/mitmproxy/http.py#L545

But the property getter returns a string

https://github.com/mitmproxy/mitmproxy/blob/83b43b93a7ac6cf2bfe557964fd63b376e158e25/mitmproxy/http.py#L677-L682

Now I'm in a situation where I create a new Request using a bytes `scheme` variable. And then if I later compare `request.scheme` with `b'https'` it will be silently False because `'https' != b'https'`. This was kind of hard to catch and caused undefined behavior.

Looking at the constructor there is some code that seems to make it backwards compatible because it was str in earlier versions. Can we just pull the plug and make this consistently bytes? Or would that break other things?

**Comment by mhils** [comment]
The intention here is that most users only ever need to deal with `str` and not with `bytes` for what they are doing. Technically everything boils down to bytes, including  `path`, `url`, etc.; but folks will compare that to str and then run into the same bug you are describing (just the other way around). If you explicitly want that low-level unconverted access, I would recommend just accessing `request.data.scheme`.

**Comment by Prinzhorn** [comment]
Fair enough. I'll try to setup mypy for my addon so that I can hopefully just catch these issues in the future.

> then run into the same bug you are describing (just the other way around)

Yeah, that's what I figured
