### ISSUE TITLE
Wrong SNI hostname used for upstream HTTPS proxy

### ISSUE THREAD

**Issue by flowztul** [mitmproxy/mitmproxy#5109]
#### Problem Description
When using mitmproxy with an upstream HTTPS proxy, it will attempt to use the client connection's target host for SNI in the outer TLS connection, and will subsequently fail to validate that connection and return "502 Bad Gateway" -- "Certificate verify failed: Hostname mismatch"

#### Steps to reproduce the behavior:
1. Start mitmproxy with an HTTPS upstream proxy, e.g. `mitmproxy --mode upstream:https://example.com:1234 --upstream-auth user:pass`
2. Issue an HTTP request, e.g. `curl -ski -x http://127.0.0.1:8080 https://api.ipify.org`
3. mitmproxy will log `warn: 127.0.0.1:55584: Server TLS handshake failed. Certificate verify failed: Hostname mismatch` and return a `502 Bad Gateway` error with reason `Certificate verify failed: Hostname mismatch` to the client.
4. A packet capture of the upstream traffic shows that mitmproxy tried to use `api.ipify.org` for SNI in the TLS connection to the upstream proxy.

#### System Information
```
Mitmproxy: 7.0.4
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.4.0-26-generic-x86_64-with-glibc2.29
```

**Comment by mhils** [comment]
I haven't verified the issue yet, but thank you already for the clear report!

**Comment by johnwc** [comment]
@mhils  We are seeing this same issue with reverse proxy. The SNI name being sent to the origin server seems to be the hostname in the command line instead of the host given in the host header from the client.

**Comment by mhils** [comment]
@johnwc: Did you try https://docs.mitmproxy.org/dev/concepts/options/#keep_host_header ?

**Comment by johnwc** [comment]
@mhils yes. It seems the main issue is that the original request does not have a SNI in it. I created a hook for server_connect and manually set the SNI, it the connection worked for us. Can there be an option to enable using the host header for outbound SNI if the incoming request does not have a SNI set?
