### ISSUE TITLE
mitmproxy fails with 'You are using an outdated version of pyOpenSSL' on OS X 10.10.2

### ISSUE THREAD

**Issue by jirohori** [mitmproxy/mitmproxy#511]
I cannot start mitmproxy caused by the following failure:
You are using an outdated version of pyOpenSSL: mitmproxy requires pyOpenSSL 0.14 or greater.
Your pyOpenSSL 0.13.1 installation is located at /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL

But pyopenssl 0.14 is already installed. I also have tried to uninstall/install (again) mitmproxy and/or pyopenssl. Same result. I am using OS X 10.10.2.

**Comment by legendtang** [comment]
This means you had 0.13 installed via non-pip methods. Just uninstall pyOpenSSL by the means you previously using (easy_install, setuptools or distribute, etc), or simply remove / rename /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/OpenSSL folder.

I have the same issue on Ubuntu 14.10 before. It runs perfectly now

**Comment by mhils** [comment]
Exactly - the error message is the best we can do, you need to uninstall pyOpenSSL 0.13.1 first.

Cheers,
Max

**Comment by jirohori** [comment]
Many thanks for your help.
