### ISSUE TITLE
The modification of the "host" causes the establishment of two server connections

### ISSUE THREAD

**Issue by Devhercule** [mitmproxy/mitmproxy#5123]
#### Problem Description
I'm using the mitmproxy to redirect HTTP requests to another server by modifying the "host" of the request.
For such needs, I used the example provided in the doc  :
[https://docs.mitmproxy.org/stable/addons-examples/#http-redirect-requests](url)

Here is my code, which modifies the host of the requests ("www.example.com" to "www.google.com" for example) :

```
from mitmproxy import http
  
class LocalRedirect:

  def request(self, flow: http.HTTPFlow):
    flow.request.host = "www.google.com"
    print('---------------------------- HTTPEvents : request', flow.request.url)

  def response(self, flow):
    print('---------------------------- HTTPEvents : response', flow.request.url)

  def client_connected(self, client):
    print("------ client_connected - client:(%s, %s)" % (client.peername, client.sockname))

  def client_disconnected(self, client):
    print("------ client_disconnected - client:(%s, %s)" % (client.peername, client.sockname))
  
  def server_connect(self, data):
    print("------ server_connect - client:(%s, %s) server:(%s, %s)" % (data.client.peername, data.client.sockname, data.server.sockname, data.server.peername))

  def server_connected(self, data):
    print("------ server_connected - client:(%s, %s) server:(%s, %s)" % (data.client.peername, data.client.sockname, data.server.sockname, data.server.peername))

  def server_disconnected(self, data):
    print("------ server_disconnected - client:(%s, %s) server:(%s, %s)" % (data.client.peername, data.client.sockname, data.server.sockname, data.server.peername))

  def http_connect(self, flow):
    print('---------------------------- HTTPEvents : http_connect', flow.request.url)

addons = [
  LocalRedirect()
]
```

#### Steps to reproduce the behavior:
1. start up the mitmproxy : **mitmdump --set confdir=/root/MITMPYTHON/configDir/ --listen-port 85**
2. call "www.example.com" with curl : **curl --proxy localhost:85 https://www.example.com**

Here is the output :

_______________

Loading script ./redirect_test.py
Proxy server listening at http://172.26.14.113:85
------ client_connected - client:(('172.26.14.113', 46990), ('172.26.14.113', 85))
172.26.14.113:46990: client connect
---------------------------- HTTPEvents : http_connect www.example.com:443
------ server_connect - client:(('172.26.14.113', 46990), ('172.26.14.113', 85)) server:(None, None)
172.26.14.113:46990: **server connect www.example.com:443** (93.184.216.34:443)
------ server_connected - client:(('172.26.14.113', 46990), ('172.26.14.113', 85)) server:(('172.26.14.113', 39208), ('93.184.216.34', 443))
---------------------------- HTTPEvents : request https://www.google.com/
------ server_connect - client:(('172.26.14.113', 46990), ('172.26.14.113', 85)) server:(None, None)
172.26.14.113:46990: **server connect www.google.com:443** (216.58.214.68:443)
------ server_connected - client:(('172.26.14.113', 46990), ('172.26.14.113', 85)) server:(('172.26.14.113', 47712), ('216.58.214.68', 443))
---------------------------- HTTPEvents : response https://www.google.com/
172.26.14.113:46990: GET https://www.google.com/
                  << 200 OK 14.51k
------ client_disconnected - client:(('172.26.14.113', 46990), ('172.26.14.113', 85))
172.26.14.113:46990: client disconnect
------ **server_disconnected** - client:(('172.26.14.113', 46990), ('172.26.14.113', 85)) server:(('172.26.14.113', **39208**), ('93.184.216.34', 443))
------ **server_disconnected** - client:(('172.26.14.113', 46990), ('172.26.14.113', 85)) server:(('172.26.14.113', **47712**), ('216.58.214.68', 443))
172.26.14.113:46990: server disconnect www.example.com:443 (93.184.216.34:443)
172.26.14.113:46990: server disconnect www.google.com:443 (216.58.214.68:443)
_____________

#### Expected behaviour:
The mitmlproxy establishes a single server connection (which subsequently disconnects) with "www.google.com"

#### Current behaviour:
The mitmproxy establishes two connections with two different servers, each connection is listening on a different port (39208 and 47712 for our example). The first is for "www.example.com" server and the second is for "www.google.com" server.
NB: This behavior is only produced in the case of an https url redirection. In http, the proxy creates a single connection to the right server (www.google.com).

#### System Information
Mitmproxy: 7.0.4
Python:    3.9.5
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-3.10.0-1127.el7.x86_64-x86_64-with-glibc2.17

**Comment by mhils** [comment]
You need to set `upstream_cert` to false and `connection_strategy` to `lazy`. That should change the behavior to what you are expecting. :)

**Comment by Devhercule** [comment]
I am already in `connection_strategy: lazy`
I added the option `upstream_cert: False` and it works :+1: 
Thank you
