### ISSUE TITLE
Text with incorrect encoding in response(flow) method

### ISSUE THREAD

**Issue by naymkazp** [mitmproxy/mitmproxy#5152]
#### Problem Description
When you pass flow.response to response(flow) method the encoding breaks in the content.
Example:
https://github.com/naymkazp/mitmproxy-charset-issue

#### Steps to reproduce the behavior:
1. Clone example repo
2. Run in 1st terminal
```
mitmdump --ssl-insecure -p 8182 -s proxy.py --set block_global=false
```
3. Run in 2nd terminal
```
curl --insecure https://csdnimg.cn/release/cmsfe/public/js/chunk/tpl/www-index-new/index.b37193db.js --proxy "localhost:8182" 2>&1 | grep -ioE " e\}\)\(e\)\}s=function\(e\)\{\"use strict\";var t=\{1:(.{15})"
```

#### System Information
Mitmproxy: 6.0.2
Python:    3.9.10
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-12.1-x86_64-i386-64bit

**Comment by Prinzhorn** [comment]
@naymkazp do you get the expected result if you add this

```py
flow.response.headers["content-type"] = "application/x-javascript; charset=utf-8"
```

between here

https://github.com/naymkazp/mitmproxy-charset-issue/blob/ef7768f1c746b330b40783ca3a7f3fe26be0bbf3/proxy.py#L10-L11

**Comment by naymkazp** [comment]
@Prinzhorn 
Yes, that fixes the situation, thank you.

**Comment by mhils** [comment]
@Prinzhorn: is there something here we need to keep track of, or can this be closed?

**Comment by Prinzhorn** [comment]
I've linked it with that open PR, it's definitely a test case we don't want to miss when we refactor the encoding stuff
