### ISSUE TITLE
Send request replay to arbitrary connection

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#5154]
#### Problem Description

I'm using mitmproxy to make requests that did not originate from an actual client. The type of request I'm trying to make could never actually be made _through_ the proxy. For example I want to connect to an arbitrary host like "192.168.178.21:1337" (locally for testing) with an arbitrary Host header e.g. "www.example.com". I'm creating a new instance of `mitmproxy.http.Request` and also an instance of `mitmproxy.connection.Server`. But the problem is that the replay ignores `flow.server_conn` and constructs a new connection based on `Request`, which breaks what I'm trying to do. It will actually connect to `192.168.178.21:1337` (if I pass the host to the `Request` constructor) but the request ncat gets looks like this (which interestingly is missing the 1337 port):

```
GET http://192.168.178.21/ HTTP/1.1
Host: www.example.com


```

What I want is the following request made to 192.168.178.21:1337

```
GET / HTTP/1.1
Host: www.example.com


```

#### Proposal

I _think_ I found the right place?

https://github.com/mitmproxy/mitmproxy/blob/2d2a9f3c528166f04dba168f0adbe510eb74900f/mitmproxy/addons/clientplayback.py#L70-L76

But I wasn't able to patch it to make it work. Ideally we could check for `server_conn is None` and just clone it, but "those flows will still have a `server_conn` attribute with a `timestamp_start` set to `None`.".

So how can I make replay use my `flow.server_conn` while not breaking existing replay? I don't want replay to create a `server_conn` from `flow.request`, which is what's currently happening. I want to manually create a connection and have replay make the request to it.

#### Alternatives
A night of sleep, tomorrow probably brings the solution

#### Additional context
I'm tired.
I can provide a stripped down addon tomorrow, it goes like this (imagine there would be parameters :smirk:  )

```py
request = mitmproxy.http.Request()
client_conn = mitmproxy.connection.Client()

# I pass an address here that is not related to Request above
server_conn = mitmproxy.connection.Server()

flow = mitmproxy.http.HTTPFlow(client_conn, server_conn)
flow.request = request

ctx.master.commands.call("replay.client", [flow])
```

#### WTF are you even doing?

E.g. fuzzing for other vhosts on a given IP and other fun misconfigurations. I just realized that this refs some of those "allow custom DNS in mitmproxy". This is a subset I guess?

**Comment by mhils** [comment]
Look into the distinction between `.host` and `.pretty_host`. Mitmproxy should forward requests where the host header does not match the .host attribute just fine. FWIW it would also be feasible to do for external clients by supplying a different target in the HTTP CONNECT.

**Comment by Prinzhorn** [comment]
> A night of sleep, tomorrow probably brings the solution

Checks out.

> Look into the distinction between `.host` and `.pretty_host`. Mitmproxy should forward requests where the host header does not match the .host attribute just fine. FWIW it would also be feasible to do for external clients by supplying a different target in the HTTP CONNECT.

Thanks a lot. I think it's working now as expected, I was misunderstanding the `authority` argument too.

This appears to do what I want:

```py
import time

import mitmproxy
import mitmproxy.http
import mitmproxy.connection
import mitmproxy.net.http.headers

from mitmproxy import ctx


class MyAddon:
    def running(self):
        self.make_request()

    def make_request(self):
        headers = mitmproxy.http.Headers(
            [(b"Host", b"www.example.com"), (b"X-Foo", b"bar")]
        )

        request = mitmproxy.http.Request(
            host=b"192.168.178.21",
            port=1337,
            method=b"GET",
            scheme="http",
            authority=b"",
            path=b"/",
            http_version=b"HTTP/1.1",
            headers=headers,
            content=b"",
            trailers=None,
            timestamp_start=time.time(),
            timestamp_end=None,
        )

        client_conn = mitmproxy.connection.Client(
            ("", 0), ("", 0), request.timestamp_start - 0.0001
        )

        server_conn = mitmproxy.connection.Server(("", 0))

        flow = mitmproxy.http.HTTPFlow(client_conn, server_conn)
        flow.request = request

        ctx.master.commands.call("replay.client", [flow])


addons = [MyAddon()]

```

```sh
ncat -vkl 1337
mitmdump -s make-request.py
```

ncat gets

```
GET / HTTP/1.1
Host: www.example.com
X-Foo: bar

```

The only thing that's somewhat awkward is that the `server_conn` is not used at all and that it is instead created from the request. It's somewhat of a duplication, does this info really belong to the request object?

Turns out my patch to [clientplayback.py](https://github.com/mitmproxy/mitmproxy/blob/2d2a9f3c528166f04dba168f0adbe510eb74900f/mitmproxy/addons/clientplayback.py#L70-L76) _was_ working.
