### ISSUE TITLE
showhost should default to true

### ISSUE THREAD

**Issue by 89z** [mitmproxy/mitmproxy#5167]
#### Problem Description

Currently the output of MITM Proxy gives the IP address for the host in all URLs. I think most people expect the proper host name to be used here. I understand that host can come from different sources (HTTP header, SNI), but I think picking one of those, is better than picking neither. Even if the result is wrong sometimes, users can always set `showhost` to false to get the IP again.

#### System Information

~~~
Mitmproxy: 7.0.4 binary
Python:    3.9.7
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Windows-10-10.0.18363-SP0
~~~

**Comment by 89z** [comment]
https://github.com/mitmproxy/mitmproxy/issues/77

**Comment by 89z** [comment]
https://github.com/mitmproxy/mitmproxy/blob/3387dac679ee92ef127097c98455b4f229f4a307/mitmproxy/options.py#L20-L23

**Comment by mhils** [comment]
> Currently the output of MITM Proxy gives the IP address for the host in all URLs.

This depends on the mode you are using. If you are using mitmproxy as a regular proxy, odds are high that you will see full domains straight away. The reason why we show IP addresses in transparent mode is that host header/SNI could be spoofed. I agree that this is mostly inconvenient for the vast majority of users, but using host header info by default could be highly misleading for malware researchers for example. Long story short, it's a difficult tradeoff. Right now we are optimizing for correctness over usability.

One potential solution to this could be support for transparent DNS proxying (which we will hopefully get soon), in which case we could then verify that the IP matches the domain.

**Comment by 89z** [comment]
I respect your reasoning, neither solution is perfect. I think showing a possibly wrong host would be better for the average use case, I think most people using this tool are not running into a spoofing situation. However you would know better than me. But even if I am right, and the non-spoof case is way more popular, its still your decision what the default will be. Thanks either way.

**Comment by 89z** [comment]
closing for lack of interest
