### ISSUE TITLE
mitmproxy wont work on iOS 15 apps

### ISSUE THREAD

**Issue by vaibhavpacharya** [mitmproxy/mitmproxy#5174]
#### Problem Description

Was able to view my app logs in iOS 13 and earlier. After my company updated their app version to iOS 15, it blocks mitmproxy with below error.
Client handshake failed. Client may not trust the proxy's certificate. 
We have not installed any pinning to block any proxy.

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 7.0.4
Python:    3.9.10
OpenSSL:   OpenSSL 1.1.1m  14 Dec 2021
Platform:  macOS-12.2.1-x86_64-i386-64bit

**Comment by vaibhavpacharya** [comment]
![mitmproxy](https://user-images.githubusercontent.com/16417441/157922466-d312ebcb-33ed-4378-abe5-a74899d4ea63.png)

**Comment by mhils** [comment]
You are likely running into certificate pinning, see https://docs.mitmproxy.org/dev/concepts-certificates/#certificate-pinning. :)

**Comment by mhils** [comment]
Sorry - I didn't read our post properly. There are just a lot of "app doesn't work" issues that I defaulted to the usual answer. Sorry. 🙈 

In this case this likely is a duplicate of #5166 though. I've just tested Safari on a 15.3.1 device and that worked fine for me. Maybe someone can shed on which factor is the difference :)
