### ISSUE TITLE
Errors with implementing add-ons

### ISSUE THREAD

**Issue by Mitch0S** [mitmproxy/mitmproxy#5177]
#### Problem Description
Errors thrown when adding this add-on: https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/http-redirect-requests.py

I'm sure that there is an easy fix, I'm just not familiar with the MITMProxy add-on API

Errors:
When defining the function with "def request(flow: http.HTTPFlow) -> None:", this throws the following error: 
"TypeError: request() missing 1 required positional argument: 'flow'

To mitigate this issue, I used this function definition: "def request(flow=http.HTTPFlow) -> None:" which then throws the error: AttributeError: type object 'HTTPFlow' has no attribute 'request'

#### Steps to reproduce the behavior:
1. Implement the https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/http-redirect-requests.py addon
2. Run an instance of mitmdump (What I'm using)
3. Take note of error messages.

#### System Information
Mitmproxy: 7.0.4
Python:    3.10.2
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-12.1-arm64-arm-64bit

**Comment by Prinzhorn** [comment]
I'm not seeing any error when I run `mitmdump --scripts http-redirect-requests.py`. Are you doing anything else than using the exact script?

**Comment by Prinzhorn** [comment]
You're probably not using the verbatim add-on but wrapped it in a class? Then you need `self` as first argument, that would explain your error message.

**Comment by Mitch0S** [comment]
Hello, sorry for taking so long to get back to you. 

Right now, I have the mitmpython library in an actual file in my project directory, so I can edit parts of it more easily.

I have mitmdump running in the following code: https://pastebin.com/e1CsmHeE

I have the addon registered in the "default_addons" list in addons/__init__.py

The code of the addon is the exact same as what's on the github repo

It's still telling me:

TypeError: request() missing 1 required positional argument: 'flow'

I hope this helps.

**Comment by Prinzhorn** [comment]
> I have mitmdump running in the following code: https://pastebin.com/e1CsmHeE

If I understand correctly you are doing something that is neither documented nor supported, as said in #5171.

> I have the addon registered in the "default_addons" list in addons/**init**.py

In addition it sounds like you are working with your own local fork of mitmproxy.

If you cannot reproduce the issue in isolation using the unaltered official binaries then it's not a bug in mitmproxy. If you can, then please provide full steps to reproduce the issue without leaving any details out. Feel free to re-open this issue then.

**Comment by Mitch0S** [comment]
I did end up getting it working. I didn't alter/change anything to do with mitmproxy, other than just having it in a directory so I can access the scripts easier (Sorry for being unclear about that). It starts normally, I am still able to pass arguments into it when I start it via cli.

But yeah, working now. Thank you for your effort!

**Comment by delebash** [comment]
Mitch0S,

That fixed my problem as well.  TY.  Maybe this should be added to the docs.
