### ISSUE TITLE
more readable elements to http plugins api

### ISSUE THREAD

**Issue by Mitch0S** [mitmproxy/mitmproxy#5178]
#### Problem Description

I'm trying to make a content filter with MITMProxy. I have everything working, but I'm trying to see what IP is actually making the outbound request.

#### Proposal
It would be amazing if it would be possible to get the IP of the client making the request, think "flow.request.client_ip"

#### Alternatives
N/a

#### Additional context
I'm building the filter with https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/http-redirect-requests.py

Here is my current codesample for the function: https://pastebin.com/Pn3ZqU61

**Comment by mhils** [comment]
Please take a look at the API docs:
https://docs.mitmproxy.org/dev/api/mitmproxy/http.html - HTTP Flows (like all other flows) have a `client_conn` attribute.
https://docs.mitmproxy.org/dev/api/mitmproxy/flow.html#Flow.client_conn - ...that is a `Client` instance...
https://docs.mitmproxy.org/dev/api/mitmproxy/connection.html#Client.peername - ...that has a `peername` attribute.

In short: `flow.client_conn.peername`.

**Comment by Mitch0S** [comment]
My mistake, thank you!
