### ISSUE TITLE
Mitmproxy 8 Checklist

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#5185]
I plan to get the following thing into main before shipping 8.0 later this week/early next week. 
Please comment if I'm missing something urgent. We plan on having more frequent releases again after this, so it's not a big deal if something doesn't make the cut. It will be in the next one soon after. :)

 - https://github.com/mitmproxy/mitmproxy/pull/5105
 - https://github.com/mitmproxy/mitmproxy/pull/5097 (if reviewed by then)
 - https://github.com/mitmproxy/mitmproxy/pull/5067
 - A fix for an undisclosed security vulnerability (moderate impact)

**Comment by Prinzhorn** [comment]
Did you get a chance to look into that gist I've sent you in Slack?

**Comment by mhils** [comment]
Shipped! 🎉
