### ISSUE TITLE
mitmdump output format

### ISSUE THREAD

**Issue by raymontag** [mitmproxy/mitmproxy#521]
Hey,

it would be great if one could get (optional) an output format similar to the one of mitmproxy for POST data and response data. The hex dump is nice but I would like to see something which is more convenient for searching in the data.

Kind regards

**Comment by albertzaharovits** [comment]
Hi Max,

I would like to start working on this! At the moment I see two ways to go: 
1) write some classes similar to the View ones in libmproxy/console/contentiew.py
2) use the current urwid.Widget generation, and 'pretty print' the root urwid.ListBox widget
What do you think?

Albert

**Comment by mhils** [comment]
Hi Albert,

Looking at option 2, I'm afraid we can't really do that - urwid is Linux/OSX only, so we cannot use the console parts in mitmdump (which also runs on Windows). 
Option 1 sounds better here. It would be very cool if we could re-use the common bits for mitmproxy/mitmdump/mitmweb. For example, it would be useful to have common views which return simple data structures (for the time being, either `dict` or `list`), which are then processed by mitmdump for (raw) text output or by mitmproxy for limited/formatted output.

@cortesi, thoughts?

Cheers,
Max

**Comment by albertzaharovits** [comment]
Hi Max,

After a first attempt to rewrite (contentview)[https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/console/contentview.py], I realised it would imply quite a lot of duplicate code, trying to avoid urwid formating (or worse bloating code with if then/else).
Wouldn't it be more convenient to have an inline script for dump pretty printing?

**Comment by raymontag** [comment]
@albertzaharovits @mhils I received the permission of my employer to work on this issue, too. Is there any progress on this thing or some new thoughts? Are there other things that must happen before this one?

**Comment by cortesi** [comment]
I think content formatting would be a great addition to mitmdump, and I'd definitely pull patches that work towards this. If this happens, we'll have content views in 3 places - mitmproxy, mitmweb and mitmdump - so it's time to think about what we can share and how. 

For mitmproxy and mitmdump, I think it's clear that we can share a great deal. The mitmproxy content views basically produce line-by-line output, with a sprinkling of highlighting. I propose that:

- We move the contentview formatters into the top level of the project
- We refactor the current contentview module to remove reliance on urwid. Instead, contentviews yield lists of lists of (style, content) tuples, where each list of tuples represents a line. So, for hex view, it would look like this:

```
[
    [
        ("offset", "0000000000"), 
        ("text", " 7b 22 65 6e 2d 55 53 22 3a 20 5b 7b 22 62 67 43"),   
        ("ascii", "{xen-USx: [xxbgC")
    ]
    ....
]
```
- Inside the mitmproxy console subproject, we have a simple translator that picks the intermediate representation up and translates it to urwid.Text snippets.
- Inside the mitmdump project, we translate to a console representation. I think colour would be useful here too, so we could consider something like [blessings](https://pypi.python.org/pypi/blessings) for this if it degrades nicely for piping and on other platforms. I haven't evaluated the terminal colour libraries out there carefully, so we should do some research and ponder it a bit. 
- This is a separate discussion, really, but there are constraints that I'd like to maintain for mitmweb that mean it would be more appropriate to do the parsing and formatting in JavaScript, in the browser.

**Comment by raymontag** [comment]
OK, it seems there's is some work needed :) I'll try to get into the code and to implement some of your ideas. Is there some common contact address where I can ask questions if some are raised, so that I don't have to spam this issue?

**Comment by mhils** [comment]
@raymontag, asking here is completely ok. Alternatively, feel free to ping us on IRC (#mitmproxy on OFTC). :smiley: 

Cheers,
Max

**Comment by raymontag** [comment]
Ok, I gave a quick glance at blessings and it seems that it could be helpful to get rid of urwid. However it doesn't support colors on Windows. The developer suggests to use blessings together with [colorama](https://pypi.python.org/pypi/colorama/0.2.4) for this. I'll try to build something to replace the urwid's Text-widget with this.

**Comment by raymontag** [comment]
@cortesi Is [this](https://github.com/raymontag/mitmproxy/commit/9785a28d2a3c6317718fcebe663a5d7920828e53) something you thought of?

**Comment by cortesi** [comment]
@raymontag Sorry, didn't see this note until now. That's definitely on the right track - any plans to develop this further? :)

**Comment by mhils** [comment]
Mitmdump now has contentviews in 0.14! :smiley:

**Comment by fschrofner** [comment]
Sorry to post this here, but it seems like the best place to ask.
How can I actually apply content views to the output of mitmdump?
I looked through the documentation and the help output of mitmdump, but I couldn't find anything promising. 

I tried using `-s` with the `auto.py` content view, but that didn't work. So I guess I have to write a script, which applies the content view, right? If so, how can I do that? I have no experience in Python, so I'd be happy if you could guide me in the right direction.

Or is there a way to directly specify the content view to use?

Cheers,
Florian

**Comment by cpatulea** [comment]
--set dumper_default_contentview=hex
