### ISSUE TITLE
iOS 15.4 - kCFErrorDomainCFNetwork Code=310

### ISSUE THREAD

**Issue by knlr** [mitmproxy/mitmproxy#5219]
#### Problem Description
HTTPS is no longer working on iOS 15.4 - it seems iOS (CFNetworking?) is not accepting the certificate.

#### Steps to reproduce the behavior:
1. In Xcode 13.4, create a new simulator with iOS 15.4
2. Set machine up to proxy through mitmproxy
3. In simulator Safari, go to mitm.it and install certificate.
4. [Configure URLSession to use proxy ](https://stackoverflow.com/a/28101583/2378197)
5. Try to make https call in app

Result:
HTTPS calls will fail with this error:
<URL> Error Domain=kCFErrorDomainCFNetwork Code=310 "(null)" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <task id>.<1>, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2096, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <task id>.<1>"
), _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0}

Notes:
- It does work when proxying the host machine and not explicitly configuring the URL session
- it also seems to work with simulators that have had their certificate installed before upgrading to Xcode 13.4

#### System Information
Mitmproxy: 7.0.4
Python:    3.9.9
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  macOS-12.2.1-x86_64-i386-64bit

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by mhils** [comment]
refs https://github.com/mitmproxy/mitmproxy/issues/5166#issuecomment-1066122544
