### ISSUE TITLE
Drop Support For Python 3.9

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#5233]
TL;DR: Does anyone have objections against dropping support for older Python versions?

We don't have too many reasons to support a wide range of versions, and it would be nice to make use of the new 3.10 type annotations when cleaning up some option handling. With the upcoming release of Ubuntu 22.04, there will also be an Ubuntu LTS release that ships Python 3.10 out of the box. It's not a move we need to make urgently, but I figured I'd open this issue already now to give folks the opportunity to voice their concerns (if any).

**Comment by KORraNpl** [comment]
I'm not sure, if you consider such factors, but it seems that currently [only 5% of installs from PyPI uses Python 3.10](https://pypistats.org/packages/mitmproxy). Naturally, this number will grow over time, and personally I don't have a problem with an aggressive approach :)

**Comment by mhils** [comment]
> I'm not sure, if you consider such factors, but it seems that currently [only 5% of installs from PyPI uses Python 3.10](https://pypistats.org/packages/mitmproxy). Naturally, this number will grow over time, and personally I don't have a problem with an aggressive approach :)

Thanks for sharing, that's a really interesting statistic. 50% of downloads are on Python 3.7, which we dropped support for in mitmproxy 6 (December 2020). Oof. 😅 

I think we don't have to read too much into PyPI numbers as most users download our binaries, use Docker images, or use brew on macOS. For binaries and Docker we control the Python version, and 8.0 already ships with 3.10. But I share your point that it probably doesn't hurt to wait a bit. One very annoying part about pip is that it would silently install 8.0 if we ship a 8.1 that only supports a higher Python version than what is installed. I'd hope that 3.10 gains more adoption once Ubuntu 22.04 is out. :)

**Comment by EndUser509** [comment]
I use CentOS and the latest release is still using 3.9 so I personally would appreciate if 3.9 is still supported for a while. For the current CentOS 8 the version upgrades are tracked here: https://access.redhat.com/support/policy/updates/rhel8-app-streams-life-cycle

**Comment by mhils** [comment]
We're dropping support for Python 3.8 in #5296, but we'll try to keep 3.9 around at least until CentOS supports it.

**Comment by jpstotz** [comment]
@mhils  Sorry but I dislike installing essential software from third party repositories I can not estimate if they are trustworthy and if security updates are provided and if yes with what delay and for what time span.

**Comment by mhils** [comment]
I've dropped support for Python 3.9 in #5954. This change does not affect users using our precompiled binaries, Docker images, or Windows Store builds (all on Python 3.11 already). When installing mitmproxy from pip or source, Python 3.10+ is readily available on macOS, Windows, and Ubuntu 22.04+.

I'm sorry if this causes inconveniences for Debian 11 and CentOS users, but the project benefits more from unblocking core devs. :)
