### ISSUE TITLE
"RuntimeError: Cannot change server.via on open connection" when using duplicate-modify-replay.py with upstream mode enabled

### ISSUE THREAD

**Issue by riramar** [mitmproxy/mitmproxy#5241]
#### Problem Description
I was using mitmdump.exe 7.0.4 for windows with the example duplicate-modify-replay.py without any problems.
After migrating to mitmdump.exe 8.0.0 I started to get the error below.

```
Addon error: Traceback (most recent call last):
  File "duplicate-modify-replay.py", line 9, in request
    flow = flow.copy()
  File "mitmproxy\http.py", line 1254, in copy
  File "mitmproxy\flow.py", line 170, in copy
  File "mitmproxy\coretypes\serializable.py", line 39, in copy
  File "mitmproxy\flow.py", line 165, in from_state
  File "mitmproxy\flow.py", line 160, in set_state
  File "mitmproxy\stateobject.py", line 47, in set_state
  File "mitmproxy\stateobject.py", line 94, in make_object
  File "mitmproxy\stateobject.py", line 56, in _process
  File "mitmproxy\connection.py", line 331, in from_state
  File "mitmproxy\connection.py", line 353, in set_state
  File "mitmproxy\connection.py", line 299, in __setattr__
RuntimeError: Cannot change server.via on open connection.
```

#### Steps to reproduce the behavior:
1 - Create a script duplicate-modify-replay.py with the content below.
```
"""Take incoming HTTP requests and replay them with modified parameters."""
from mitmproxy import ctx


def request(flow):
    # Avoid an infinite loop by not replaying already replayed requests
    if flow.is_replay == "request":
        return
    flow = flow.copy()
    # Only interactive tools have a view. If we have one, add a duplicate entry
    # for our flow.
    if "view" in ctx.master.addons:
        ctx.master.commands.call("view.flows.add", [flow])
    flow.request.path = "/changed"
    ctx.master.commands.call("replay.client", [flow])
```
2 - Create a proxy (e.g. Burp Suite Proxy) running under port 8082
3 - Run mitmdump.exe 8.0.0 with the command below.
`mitmdump.exe --ssl-insecure --set add_upstream_certs_to_client_chain=true -s duplicate-modify-replay.py --mode upstream:http://127.0.0.1:8082`
4 - If some request get stucked press Control+C and check the output.

![image](https://user-images.githubusercontent.com/6748242/161570443-cfe8929f-3a2e-4214-a7ed-3438240a37f1.png)

#### System Information
Paste the output of "mitmproxy --version" here.
```
>mitmdump.exe --version
Mitmproxy: 8.0.0 binary
Python:    3.10.2
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Windows-10-10.0.19041-SP0
```

**Comment by riramar** [comment]
Seems to be related to this commit https://github.com/mitmproxy/mitmproxy/commit/0f5b8c88af4f860bc28a8dd7edb5df52fbbf77a7

**Comment by mhils** [comment]
Yeah - raising in `__setattr__` is good, we need to fix `copy()` to not trigger that I think. :)

**Comment by idb-** [comment]
Also having this issue.

**Comment by kvaidas** [comment]
Not sure if this is related but this happens when I try to read flows from a file - that has been recorded while using --set mode=upstream:http://<myproxy>
If I record the same request not using this parameter, everything just works.
I'm running 8.1.1

**Comment by idb-** [comment]
> Not sure if this is related but this happens when I try to read flows from a file - that has been recorded while using --set mode=upstream:http:// If I record the same request not using this parameter, everything just works. I'm running 8.1.1

In connection.py find the line 

```
if name in ("address", "via"):
```

and replace it with 

```
if name == 'address':
```

There may be side effects so make note of the edit in source so you can undo if necessary, but this allows you to re-load flows where an upstream proxy was in use.

**Comment by riramar** [comment]
I'm still having this issue on mitmproxy 9.0.1.

![image](https://user-images.githubusercontent.com/6748242/199827809-529c8fe7-9941-4f8a-af0a-fb4f3cf471ab.png)

**Comment by idb-** [comment]
> I'm still having this issue on mitmproxy 9.0.1.
> 
> ![image](https://user-images.githubusercontent.com/6748242/199827809-529c8fe7-9941-4f8a-af0a-fb4f3cf471ab.png)

Are you certain that you replaced properly, and all instances? I'm not sure if there's more than 1 instance of it. You may be having a completely different issue. Not sure.

**Comment by riramar** [comment]
It's the same error. I did the same test again from the past (using mitmproxy-9.0.1-windows.zip) with the same file and got the same error.

![image](https://user-images.githubusercontent.com/6748242/200125022-e8d3b8db-70b5-4886-a9f5-6f8984c40a14.png)

The same test using the version 7.0.4 it works properlly.

![image](https://user-images.githubusercontent.com/6748242/200124982-7ac44fba-3c32-483f-9d11-2f442f890a86.png)

This seems to be related to this commit https://github.com/mitmproxy/mitmproxy/commit/0f5b8c88af4f860bc28a8dd7edb5df52fbbf77a7

**Comment by Sim4n6** [comment]
![image](https://user-images.githubusercontent.com/13036531/225757995-739d9d9f-f996-4f29-9806-762f26b6a978.png)

**Comment by mhils** [comment]
> This issue is still occurring in v9.0.1

Probably because it's not fixed yet, PRs welcome. :)

> is there a pypi release/publishing schedule?

We aim to ship mitmproxy 10 relatively soon to get more HTTP/3 feedback. The HTTP/3 implementation is still very experimental and we intentionally let it sit on main for a bit to iron out the worst bugs. :)

**Comment by mhils** [comment]
Thanks for the triage, that's a great contribution in itself. 😄 🍰

**Comment by 3052** [comment]
confirming above comment - looks like https://mitmproxy.org/downloads/#10.0.0/ is the first working version
