### ISSUE TITLE
OSError: [WinError 121] The semaphore timeout period has expired

### ISSUE THREAD

**Issue by skanga** [mitmproxy/mitmproxy#5246]
#### Problem Description
mitmdump throws this exception on the console

```
Traceback (most recent call last):

  File "C:\bin\Python-3.10.4\lib\asyncio\proactor_events.py", line 771, in _loop_self_reading
    f.result()  # may raise

  File "C:\bin\Python-3.10.4\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)

  File "C:\bin\Python-3.10.4\lib\asyncio\windows_events.py", line 462, in finish_recv
    return ov.getresult()

OSError: [WinError 121] The semaphore timeout period has expired

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
```

#### Steps to reproduce the behavior:
mitmdump -s recordTraffic.py

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 8.0.0
Python:    3.10.4
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Windows-10-10.0.19043-SP0

**Comment by mhils** [comment]
I can't reproduce this on Windows, we need more context. FWIW I suspect that this may be a bug in Python itself, but if we can reproduce it reliably I'd be happy to trace it down and get it fixed there.
