### ISSUE TITLE
SSL Error HttpErrorConnClosed version 0.11

### ISSUE THREAD

**Issue by loretoparisi** [mitmproxy/mitmproxy#525]
I'm running nodejs listening at port 8181 on locahost
After last update from release 0.10 to 0.11 starting a upstream/forward proxy:

```
 mitmproxy -U http://localhost:8181 -p 11112
```

I get SSL errors when connecting to localhost:

```
>> CONNECT apic.musixmatch.com:443
           ← HttpErrorConnClosed('Server disconnect.',)
   CONNECT apic.musixmatch.com:443
           ← HttpErrorConnClosed('Server disconnect.',)

(Originating URI is over HTTPS)
```

The error happens in ```upstream -U```mode only.

**Comment by loretoparisi** [comment]
Adding that via script If I do via flows it works properly intercepting the host

```
def request(context, flow):
    if flow.request.pretty_host(hostheader=True).endswith("musixmatch.com"):
        flow.request.host = "localhost"
        flow.request.port = 9999
        flow.request.scheme = 'http'
        flow.request.update_host_header()
```

**Comment by mhils** [comment]
Hi @loretoparisi,

do you have a node proxy or a node web application running on 8181? `-U` is the upstream proxy mode, which expects another proxy upstream. You're probably looking for the regular proxy mode with the inline script you posted above?

Cheers,
Max

**Comment by loretoparisi** [comment]
Uhm right question! It's a nodejs api listening on 8181 i.e. 

```
server.listen(  process.env.PROXY_PORT || process.env.port || config.server_port);
```

**Comment by mhils** [comment]
If it's a regular application, you should not use upstream *proxy* mode. http://mitmproxy.org/doc/modes.html

**Comment by loretoparisi** [comment]
thanks that's correct.
