### ISSUE TITLE
"Access Denied" on Cloudflare-protected pages

### ISSUE THREAD

**Issue by DUOLabs333** [mitmproxy/mitmproxy#5257]
#### Problem Description
If I try to access invidious.kavin.rocks or alternativeto.net, I get blocked or CAPTCHA'd, respectively. Without mitmproxy, it works.
#### Steps to reproduce the behavior:
1. Run `mitmdump --listen-host 127.0.0.1 -p 2011  -s history.py --ssl-insecure --set stream_large_bodies='1m' --set stream_websockets=true --no-http2`
2. Go to any of the above pages
3. See problem.

#### System Information
```
Mitmproxy: 7.0.4
Python:    3.10.4
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.16.9-1-aarch64-ARCH-aarch64-with-glibc2.32
```

**Comment by DUOLabs333** [comment]
I narrowed this down to the use of `--no-http2` for invidious, it still does not work for alternativeto.net

**Comment by Prinzhorn** [comment]
https://github.com/mitmproxy/mitmproxy/issues/4575
