### ISSUE TITLE
frame-ancestors 'none' 

### ISSUE THREAD

**Issue by jiliu88** [mitmproxy/mitmproxy#5258]
When I use mitmdump to visit sephora.com, the page fails to load and displays 502 Bad Gateway

HTTP/2 protocol error: Received header value surrounded by whitespace b"frame-ancestors 'none' "
Other sites can be accessed normally

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by jiliu88** [comment]
thanks. I checked that my version is 8.0.0, downloaded through pip, I don't know what caused it

**Comment by mhils** [comment]
You can fix this error by specifying `--set validate_inbound_headers=false` when invoking mitmproxy. We should point that out in the error message :)

**Comment by jiliu88** [comment]
> 



> 您可以通过指定何时调用 mitmproxy 来修复此错误。我们应该在错误消息中指出这一点:)`--set validate_inbound_headers=false`



> 您可以通过指定何时调用 mitmproxy 来修复此错误。我们应该在错误消息中指出这一点:)`--set validate_inbound_headers=false`



> You can fix this error by specifying `--set validate_inbound_headers=false` when invoking mitmproxy. We should point that out in the error message :)

**Comment by jiliu88** [comment]
> You can fix this error by specifying when invoking mitmproxy. We should point that out in the error message :)`--set validate_inbound_headers=false`

Thank you so much, it helped me a lot
