### ISSUE TITLE
Tons of KeyError exceptions happening all at once

### ISSUE THREAD

**Issue by unsocial-bleach** [mitmproxy/mitmproxy#5273]
#### Problem Description
In `mitmdump` running with a modify_body in transparent mode, the following error happens. Note that the IP 5.2.75.218 is the server IP running `mitmdump`.

```
KeyError: ('5.2.75.218', 56088)

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
Traceback (most recent call last):

  File "/home/mitmproxyuser/.local/lib/python3.8/site-packages/mitmproxy/addons/proxyserver.py", line 177, in handle_connection
    del self._connections[peername]
```

Here is the output of grepping for that port number, up to the KeyError:
```
5.2.75.218:56088: client connect
5.2.75.218:56088: client connect
5.2.75.218:56088: server connect 5.2.75.218:8080
5.2.75.218:56088 -> tcp -> 5.2.75.218:8080
5.2.75.218:56088: client connect
5.2.75.218:56088: server connect 108.61.152.179:80
5.2.75.218:56088: error establishing server connection: [Errno 110] Connect call failed ('91.230.251.70', 80)
5.2.75.218:56088: client disconnect
5.2.75.218:56088: client disconnect
5.2.75.218:56088: server disconnect 108.61.152.179:80
KeyError: ('5.2.75.218', 56088)
```

The program appears to run fine despite the error, but there are hundreds of this KeyError happening.

#### Steps to reproduce the behavior:
1. Run the proxy in transparent mode with `sudo -u mitmproxyuser -H bash -c '$HOME/.local/bin/mitmdump --mode transparent --showhost --set block_global=false --set modify_body="..." ' &>> /home/main/mitmproxy.log`, following the Transparent Proxy for same-computer usage.
2. Make lots of requests to lots of servers, where some requests are to invalid servers/ports.

#### System Information
Paste the output of "mitmproxy --version" here.

```
Mitmproxy: 8.0.0
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Linux-5.4.0-104-generic-x86_64-with-glibc2.29
```

**Comment by mhils** [comment]
Thanks for the report! Looks like we are hitting port number reuse here. The proper way to handle this should be to use the full connection tuple in `proxyserver.py`

**Comment by mhils** [comment]
Fixed by https://github.com/mitmproxy/mitmproxy/pull/5232. :)
