### ISSUE TITLE
Connection refused for only http requests

### ISSUE THREAD

**Issue by itsyash** [mitmproxy/mitmproxy#528]
I set up mitmproxy on my mac and installed the certificate on my android device.

What I did was : I started the mitmproxy server on the system, and added manual proxy settings to the wifi settings in my android to point proxy server to my system's ip with port 8080.

I am facing a issue in accessing the internet on my phone through mitmproxy. For some reason, some of the requests are working perfectly (the https ones I guess) (see the image), but for all the http requests, I am getting connection refused error on my mitmproxy server.
Here is a screenshot with some example requests:

![screen shot 2015-03-19 at 23 15 55](https://cloud.githubusercontent.com/assets/2319525/6737049/013b526e-ce8f-11e4-83e5-01109222bd4e.png)

**Comment by itsyash** [comment]
I tried the same with a different phone , Xiomi Mi3. The problem still persists. So, I believe I am making some error in the configuration on my system.

![screen shot 2015-03-20 at 0 15 02](https://cloud.githubusercontent.com/assets/2319525/6738162/2371305e-ce96-11e4-93d2-4e1ef61192db.png)

**Comment by cortesi** [comment]
Hi there. This seems to indicate that mitmproxy is seeing a connection refused to the upstream server for these requests, which is weird. Are you passing any other options to mitmproxy? Could you please show us the output in the eventlog ("e" keyboard shortcut). Any chance there's something weird about the network you're using, like a transparent proxy in the way?
