### ISSUE TITLE
Not running on debian 9 (Stretch) glibc 2.25 minimum

### ISSUE THREAD

**Issue by thenoobtester** [mitmproxy/mitmproxy#5295]
#### Problem Description

I can't run the binaries on Debian 9 Stretch as it complains about needing glibc 2.25 (system has 2.24). I ask this because I read in the workflows/main.yml used to build the binaries (cf. snippet below) that it uses ubuntu-16.04 to cover for that (ubuntu-16.04 uses glibc 2.23 per my research)

` # Old Ubuntu version for old glibc
  os: [macos-latest, windows-latest, ubuntu-16.04]`

Thank you for your help and for this great and unvaluable piece of software.

#### Steps to reproduce the behavior:
1. Download the binaries
2. Run them on Debian stretch 9

#### System Information
My system is Debian stretch 9
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24

Paste the output of "mitmproxy --version" here.
[18601] Error loading Python lib '/tmp/_MEIoEpRkv/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIoEpRkv/libpython3.10.so.1.0)

**Comment by Prinzhorn** [comment]
Can confirm inside `docker run --rm -it debian:stretch` with `wget https://snapshots.mitmproxy.org/8.0.0/mitmproxy-8.0.0-linux.tar.gz`

> that it uses ubuntu-16.04 to cover for that (ubuntu-16.04 uses glibc 2.23 per my research)

It doesn't any longer? https://github.com/mitmproxy/mitmproxy/commit/b5de2d75b5aaa228f5d5d7c6c4cc0bcfb0d9adb5

Ubuntu 18.04 Docker gives me `ldd (Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27`, 16.04 gives `ldd (Ubuntu GLIBC 2.23-0ubuntu11.3) 2.23`

I guess we should still support stretch? I don't know what we try to support honestly.

>  stretch benefits from Long Term Support (LTS) until the end of June 2022

**Comment by mhils** [comment]
Same question (with an answer) here: https://github.com/mitmproxy/mitmproxy/issues/5009#issuecomment-998797185

**Comment by thenoobtester** [comment]
Thank you for the answer. You don't have to support Stretch now that I know that you don't use ubuntu-16.04 any longer. That's what misled me into thinking it should work, so I will close this. 

Sorry for the confusion :)
