### ISSUE TITLE
Add API to set a custom master secret logger function

### ISSUE THREAD

**Issue by emanuele-f** [mitmproxy/mitmproxy#5309]
#### Problem Description
For a plugin it would be useful to have an API to set a custom callback to be called with the master secrets data (the equivalent  of the OpenSSL `set_keylog_callback`)

#### Proposal
Add an API to set a custom master secret logger function from a plugin

#### Additional context
Currently the only way to do this is to set the `SSLKEYLOGFILE` environment variable to dump the keylog to a file (which is quite limiting), or manually override the `mitmproxy.net.tls.log_master_secret` callback as in https://github.com/emanuele-f/PCAPdroid-mitm/commit/c6ead01e982bbf003ea260b226f2dac94b0b6e83

**Comment by emanuele-f** [comment]
Background: mimtproxy provides my Android app ([PCAPdroid](https://github.com/emanuele-f/PCAPdroid)) the ability to decrypt traffic. For different reasons, mitmproxy is packaged into a separate app, [PCAPdroid-mitm](https://github.com/emanuele-f/PCAPdroid-mitm), which talks to the main app via IPC and sends back the decrypted data.

In this context, the `log_master_secret` callback gives me more flexibility on how secrets data can be handled. For example, I use the same IPC channel to send the master secrets to the main app as soon as it's available. Without this, due to the restrictions imposed by Android, which don't allow apps to access other apps files, I would need to manually read the SSLKEYLOGFILE. In short, `log_master_secret`, although not essential, is more programmer friendly, whereas the `SSLKEYLOGFILE` is mainly meant to be used as a user.

**Comment by mhils** [comment]
Makes sense, thanks. I think that's a fair use case, but also relatively niche. I'd recommend you just continue to overwrite `mitmproxy.net.tls.log_master_secret`. If we find that there's a much broader audience for this, I'm happy to reconsider and move this to a public API event hook. :)
