### ISSUE TITLE
Improper handling of Punycode

### ISSUE THREAD

**Issue by ZzZombo** [mitmproxy/mitmproxy#5316]
#### Problem Description
Can't open an address like `https://стопкоронавирус.рф/` through `mitmproxy` or other applications. My upstream proxy receives a CONNECT request to https://СЃС‚РѕРїРєРѕСЂРѕРЅР°РІРёСЂСѓСЃ.СЂС„:443 instead. As the current run of `mitmproxy` was supposed to be just a test, it was configured only to forward all requests as-is to the upstream proxy, so this rules out any and all issues that could arise from my tinkering. Note: the actual URL that the browser opens is `https://xn--80aesfpebagmfblc0a.xn--p1ai` in this case.

Did it fail to properly encode the resulting authority? My upstream proxy normally has no issues with opening Puny-encoded URLs. I can verify that by opening that URL bypassing `mitmproxy`. It looks like it uses the wrong encoding, as it reminds me of the time when Unicode was not widespread and so this is how text in Russian would display when the text encoding wasn't set correctly.

#### Steps to reproduce the behavior:
1. Configure `mitmproxy` to forward all requests as-is to the upstream proxy that optionally can report what requests it receives. This includes no HTTPS decryption.
2. Navigate your browser to `https://стопкоронавирус.рф/`.
3. Check what the authority part of the URL the upstream proxy gets, it should be mangled.

#### System Information
Paste the output of "mitmproxy --version" here.

```Mitmproxy: 8.0.0 binary
Python:    3.10.2
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Windows-10-10.0.19043-SP0
```

**Comment by mhils** [comment]
Repro:
```
mitmdump
mitmdump --mode upstream:https://localhost:8080 -p 8081 --set ssl_insecure
curl -x localhost:8081 -k https://стопкоронавирус.рф/
```
