### ISSUE TITLE
User interface video documentation - no sound on mac nor ios

### ISSUE THREAD

**Issue by EdmundsEcho** [mitmproxy/mitmproxy#5321]
Hello - Itried to listen to the video in the docs/interface. It looks like a great tutorial. However,  I tested it on 3 browsers (firefox, vivaldi (chrome) and safari).  Non of them could play the audio.  I also tried on my iPhone... to no avail.  Finally, I did confirm that sound does work by playing video from other sites.  This said, I could not confirm the underlying streaming tech (vimeo?), so could not fully confirm the issue.

**Comment by mhils** [comment]
Cloud you clarify which video you are referring to?
