### ISSUE TITLE
apt install mitmproxy ==> /usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:141: SyntaxWarning: str object is not callable; perhaps you missed a comma?

### ISSUE THREAD

**Issue by alex77g2** [mitmproxy/mitmproxy#5328]
#### Problem Description
sudo apt install mitmproxy # Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-109-generic x86_64)

Vorbereitung zum Entpacken von .../17-mitmproxy_4.0.4-6.1_all.deb ... # engl: Prepare Extract of
Entpacken von mitmproxy (4.0.4-6.1) ... # engl: Decompress
python3-tornado (6.0.3+really5.1.1-3) wird eingerichtet ...
python3-passlib (1.7.2-1) wird eingerichtet ...
python3-hyperframe (5.2.0-4) wird eingerichtet ...
python3-hpack (3.0.0-4) wird eingerichtet ...
python3-openssl (19.0.0-1build1) wird eingerichtet ...
python3-pyperclip (1.7.0-1) wird eingerichtet ...
python3-urwid (2.0.1-3) wird eingerichtet ...
/usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:141: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  assert result == expected, "got: %r expected: %r" (result, expected)
/usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:145: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  assert result == expected, "got: %r expected: %r" (result, expected)
/usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:149: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  assert result == expected, "got: %r expected: %r" (result, expected)
/usr/lib/python3/dist-packages/urwid/tests/test_canvas.py:232: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  assert result == expected, "got: %r expected: %r" (result, expected)
python3-sortedcontainers (2.1.0-2) wird eingerichtet ...

#### Steps to reproduce the behavior:
1. in Ubunbtu run: sudo apt install mitmproxy
2. wait for line "python3-urwid (2.0.1-3)" and see 4 times "SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?"
3. /usr/lib/python3/dist-packages/urwid/tests/test_canvas.py # seems to be still python 2, not 3 ??
 (sorry my language setting is german, but this only affect the log messages)

#### System Information
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-109-generic x86_64)
Mitmproxy: 4.0.4
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-5.4.0-109-generic-x86_64-with-glibc2.29

**Comment by mhils** [comment]
Thanks for the report!

https://docs.mitmproxy.org/stable/overview-installation/#linux:

> Some Linux distributions provide community-supported mitmproxy packages through their native package repositories (e.g., Arch Linux, Debian, Ubuntu, Kali Linux, OpenSUSE, etc.). We are not involved in the maintenance of downstream packaging efforts, and they often lag behind the current mitmproxy release. Please contact the repository maintainers directly for issues with native packages.
