### ISSUE TITLE
mitmproxy doesn't merge multiple Cookie headers when proxying HTTP/2 request to HTTP/1.1 server

### ISSUE THREAD

**Issue by rinsuki** [mitmproxy/mitmproxy#5337]
#### Problem Description

when mitmproxy running as reverse-proxy mode, mitmproxy accepts HTTP/2 connection, even upstream is plain HTTP server (w/ HTTP 1.1).

in HTTP/2, multiple cookie header is allowed, but old HTTP/1.x isn't. so we should merge multiple Cookie headers to one header when proxying to HTTP/1.1 server (see https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.5 https://www.rfc-editor.org/rfc/rfc6265#section-5.4 ), but mitmproxy isn't.

![image](https://user-images.githubusercontent.com/6533808/167728747-8e540cd4-acf7-40f1-b32f-4940782041b3.png)

and actually some servers doesn't handle multiple Cookie headers on HTTP/1.x; so it causes mysterious bug (in my case, breaks Mastodon's sign-in).

#### Steps to reproduce the behavior:
1. Run mitmproxy as reverse-proxy mode, like `mitmproxy --mode=reverse:http://localhost -p 443 --certs fullchain-and-privkey.pem --set keep_host_header --modify-header '/x-forwarded-proto/https'`
2. Access to mitmproxy port with HTTPS, `https://localhost` and add some cookies
3. Check actual HTTP request by Wireshark or something (note: some servers are automatically handles multiple cookie headers even HTTP/1.1, like Node.js)

#### System Information

```
$ mitmproxy --version
Mitmproxy: 8.0.0
Python:    3.10.4
OpenSSL:   OpenSSL 1.1.1o  3 May 2022
Platform:  macOS-12.3.1-arm64-arm-64bit
```

(installed from Homebrew)

**Comment by mhils** [comment]
Thanks for the clear report! The relevant code that handles h2 -> h1 conversion is here:
https://github.com/mitmproxy/mitmproxy/blob/01a772ed4ee673307ba6b1eebfdeb5df65b13e99/mitmproxy/proxy/layers/http/_http1.py#L342-L350

I'd be happy to merge a PR that fixes this. 😃
