### ISSUE TITLE
mitmproxy onboarding app HTTP 400

### ISSUE THREAD

**Issue by rubenvereecken** [mitmproxy/mitmproxy#534]
I was trying to fiddle with the onboarding app settings because I couldn't get the default `mitm.it` to work (while I easily could previously). To try it out on my pc I invoked it as such:

    mitmproxy --app-port 8080 --app-host localhost

After pointing my browser to `http://localhost:8080/` I got the following HTTP 400 error.

    HttpError('Invalid HTTP request form (expected: absolute, got: relative)',)

Not really sure whether this was indeed mitmproxy so I checked the header and indeed it was. It also says I'm running version 0.11: `Server:mitmproxy 0.11`.

Any idea why this may have occurred?

Slightly related there is another small issue. After restarting the app on port 80 (and confirming it was offline beforehand) it refused to restart on port 80 but in fact was alive on 8080 again. Maybe it somehow incorrectly remembers on which port it used to be?

**Comment by mhils** [comment]
Hey Ruben! :smile:

We start our proxy server on port 8080. You can access the onboarding app if you configure your client to use the proxy server and then visit `mitm.it` *through* the proxy. You cannot visit the onboarding app if you haven't configured your client to use mitmproxy, you'll see a `If you can see this, traffic is not passing through mitmproxy.` message then. As a last resort, you can of course copy the certificates manually from `~/.mitmproxy`.

Cheers,
Max

**Comment by rubenvereecken** [comment]
Hey Max, been a while ;)

Right I knew I forgot a bit in the setup, was just about to do that. Sigh, that was silly. Thanks for the quick reply!
