### ISSUE TITLE
onboarding behaviour/configuration in reverse proxy mode

### ISSUE THREAD

**Issue by asharpe** [mitmproxy/mitmproxy#5367]
Thanks all for a lovely piece of software!

#### Problem Description
Not a bug, just a gap in expectations for a newbie, and possibly documentation.  I couldn't see a more appropriate template for this kind of feedback.

There's kinda 3 separate issues I came across when getting my setup working, so I'll start with the basic layout then describe the issues.  All of them are about the onboarding app in reverse proxy mode,

In containerised reverse proxy mode a reasonable configuration is to map ports 80 and 443 to 8080, ala

```
docker run ... -p 80:8080 -p 443:8080 mitmproxy/mitmproxy mitmdump --mode reverse:http://my.upstream.server
```

and add hosts entries pointing the desired domains at 127.0.0.1 [like the suggestion in the docs](https://docs.mitmproxy.org/stable/concepts-modes/#host-header).

In this situation my expectation was that the domain and port for the onboarding app should match the _request as sent by the client_ (ie, incoming to mitmproxy), however it actually matches the _request as sent by mitmproxy_ (ie, outgoing from mitmproxy)!

This is important to understand because you need to

 1. set `onboarding_port` to match the port used for requests to your upstream server
 1. enable `keep_host_header`, _OR_ set `onboarding_host` to match the host used for requests to your upstream server

Finally, when actually getting to the onboarding app, I didn't expect a connection to be made to my upstream server, since none is needed to serve the onboarding app.

### Steps to reproduce the behavior:
I'm using curl with `--resolve` to mimic the hosts entry

#### Naive setup
1. `docker run --rm -it -p 443:8080 -p 80:8080 mitmproxy/mitmproxy:8.1.0 mitmdump --flow-detail 2 --mode reverse:http://www.asnt.org`
2. `curl --resolve mitm.it:80:127.0.0.1 http://mitm.it`
3. observe you don't get the onboarding app

#### Set the `onboarding_host`
1. `docker run --rm -it -p 443:8080 -p 80:8080 mitmproxy/mitmproxy:8.1.0 mitmdump --flow-detail 2 --mode reverse:http://www.asnt.org --set onboarding_host=www.asnt.org`
2. `curl --resolve mitm.it:80:127.0.0.1 http://mitm.it`
3. observe you get the onboarding app

#### Proxy to another (non-standard) port
1. `docker run --rm -it -p 443:8080 -p 80:8080 mitmproxy/mitmproxy:8.1.0 mitmdump --flow-detail 2 --mode reverse:http://www.asnt.org:8080 --set onboarding_host=www.asnt.org`
2. `curl --resolve mitm.it:80:127.0.0.1 http://mitm.it`
3. observe you don't get the onboarding app

### Set the `onboarding_port`
1. `docker run --rm -it -p 443:8080 -p 80:8080 mitmproxy/mitmproxy:8.1.0 mitmdump --flow-detail 2 --mode reverse:http://www.asnt.org:8080 --set onboarding_host=www.asnt.org --set onboarding_port=8080`
2. `curl --resolve mitm.it:80:127.0.0.1 http://mitm.it`
3. observe you get the onboarding app

For each of these scenarios you can see the connection made to the upstream server in the console of the docker process regardless of whether the onboarding app was served or not.

```
~/tmp $ docker run --rm -it -p 443:8080 -p 80:8080 mitmproxy/mitmproxy:8.1.0 mitmdump --flow-detail 2 --mode reverse:http://www.asnt.org
Proxy server listening at *:8080
172.17.0.1:55446: client connect
172.17.0.1:55446: server connect www.asnt.org:80 (64.132.177.13:80)
172.17.0.1:55446: GET http://www.asnt.org/
    Host: www.asnt.org
    User-Agent: curl/7.79.1
    Accept: */*
 << 301 Moved Permanently 144b
    Content-Type: text/html; charset=UTF-8
    Location: https://www.asnt.org/
    Server: Microsoft-IIS/7.5
    Date: Mon, 23 May 2022 13:09:35 GMT
    Content-Length: 144
172.17.0.1:55446: client disconnect
172.17.0.1:55446: server disconnect www.asnt.org:80 (64.132.177.13:80)
^C%
~/tmp $ docker run --rm -it -p 443:8080 -p 80:8080 mitmproxy/mitmproxy:8.1.0 mitmdump --flow-detail 2 --mode reverse:http://www.asnt.org --set onboarding_host=www.asnt.org
Proxy server listening at *:8080
172.17.0.1:55462: client connect
172.17.0.1:55462: server connect www.asnt.org:80 (64.132.177.13:80)
172.17.0.1:55462: GET http://www.asnt.org/
    Host: www.asnt.org
    User-Agent: curl/7.79.1
    Accept: */*
 << 200 OK 17.0k
    content-type: text/html; charset=utf-8
    content-length: 17459
172.17.0.1:55462: client disconnect
172.17.0.1:55462: server disconnect www.asnt.org:80 (64.132.177.13:80)
^C%
~/tmp $ docker run --rm -it -p 443:8080 -p 80:8080 mitmproxy/mitmproxy:8.1.0 mitmdump --flow-detail 2 --mode reverse:http://www.asnt.org:8080 --set onboarding_host=www.asnt.org
Proxy server listening at *:8080
172.17.0.1:55466: client connect
172.17.0.1:55466: server connect www.asnt.org:8080 (64.132.177.13:8080)
172.17.0.1:55466: GET http://www.asnt.org:8080/
    Host: www.asnt.org:8080
    User-Agent: curl/7.79.1
    Accept: */*
 << 200 OK 300b
    Server: Apache-Coyote/1.1
    Accept-Ranges: bytes
    ETag: W/"300-1543246023994"
    Last-Modified: Mon, 26 Nov 2018 15:27:03 GMT
    Content-Type: text/html
    Content-Length: 300
    Date: Mon, 23 May 2022 13:14:52 GMT
172.17.0.1:55466: client disconnect
172.17.0.1:55466: server disconnect www.asnt.org:8080 (64.132.177.13:8080)
^C%
~/tmp $ docker run --rm -it -p 443:8080 -p 80:8080 mitmproxy/mitmproxy:8.1.0 mitmdump --flow-detail 2 --mode reverse:http://www.asnt.org:8080 --set onboarding_host=www.asnt.org --set onboarding_port=8080
Proxy server listening at *:8080
172.17.0.1:55470: client connect
172.17.0.1:55470: server connect www.asnt.org:8080 (64.132.177.13:8080)
172.17.0.1:55470: GET http://www.asnt.org:8080/
    Host: www.asnt.org:8080
    User-Agent: curl/7.79.1
    Accept: */*
 << 200 OK 17.0k
    content-type: text/html; charset=utf-8
    content-length: 17459
172.17.0.1:55470: client disconnect
172.17.0.1:55470: server disconnect www.asnt.org:8080 (64.132.177.13:8080)
^C%
```

#### System Information
```
Mitmproxy: 8.1.0
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-5.10.76-linuxkit-aarch64-with-glibc2.31
```

Thanks again for the wonderful software :D

**Comment by mhils** [comment]
Thanks for the detailed write-up and sorry for the slow turnaround. This has been fixed in https://github.com/mitmproxy/mitmproxy/pull/5725 I think. :)
