### ISSUE TITLE
Extra empty chunk sent for HEAD request

### ISSUE THREAD

**Issue by jixunmoe** [mitmproxy/mitmproxy#5372]
#### Problem Description

When the upstream `HEAD` response included header `transfer-encoding: chunked`, `mitmproxy` inserts an extra empty chunk at the end of the http request, causing certain http client implementation (e.g. node's http header parser) to fail.

I believe this is a bug in `mitmproxy` because I can observe warning regarding this issue using `curl`.

#### Steps to reproduce the behavior:

1. Install `docker`, `docker-compose` and `curl`, then follow the shell script:

```sh
# Setup a temp workspace folder
mkdir -p /tmp/repro_mitmproxy_chunked_head
cd /tmp/repro_mitmproxy_chunked_head

# Setup files
cat > docker-compose.yml <<'EOF'
version: "3.9"
services:
  web:
    image: "node:16-alpine3.14"
    volumes: ["./server.js:/server.js:ro"]
    command: ["node", "/server.js"]
    stop_grace_period: 1s
  proxy:
    image: "mitmproxy/mitmproxy:8.1.0"
    ports: ["127.0.0.1:8080:8080"]
    command: ["mitmweb", "--listen-host=0.0.0.0"]
    stop_grace_period: 1s
EOF

cat > server.js <<'EOF'
const net = require('net');

const resp = Buffer.from([
  'HTTP/1.1 200 OK',
  'Transfer-Encoding: chunked',
  '\r\n'
].join('\r\n'), 'utf-8');

const server = net.createServer((c) => {
  c.end(resp);
});

server.listen(80);
EOF

# Run it in background
docker-compose up -d

# Do the test
http_proxy=http://localhost:8080 curl -vI http://web/

# Shutdown and clean up
docker-compose down
rm -rf /tmp/repro_mitmproxy_chunked_head
```

curl output:

```text
$ http_proxy=http://127.0.0.1:8080 curl -vI http://web/
* Uses proxy env variable http_proxy == 'http://127.0.0.1:8080'
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> HEAD http://web/ HTTP/1.1
> Host: web
> User-Agent: curl/7.74.0
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Transfer-Encoding: chunked
Transfer-Encoding: chunked

< 
* Excess found: excess = 5 url = / (zero-length body)
* Connection #0 to host 127.0.0.1 left intact
```

Note: If I ran this command several times in a row, there is a chance to not observe the warning.

#### System Information

```text
$ docker run --rm mitmproxy/mitmproxy:8.1.0 mitmproxy --version
Mitmproxy: 8.1.0
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-5.10.0-12-amd64-x86_64-with-glibc2.31
```

### Workaround for me

Change the following condition:

https://github.com/mitmproxy/mitmproxy/blob/cf655a664fda68de9f80de2056beabef95fafeb1/mitmproxy/proxy/layers/http/_http1.py#L247

... to the following so it doesn't send the empty chunk for `HEAD`:

```python
if self.request.method.lower() != "head" and "chunked" in self.response.headers.get("transfer-encoding", "").lower():
```

This workaround might break other things and does not apply to http2.

**Comment by mhils** [comment]
Thanks for catching this! 🍰 
Your proposal looks good to me. Do you want to send a PR with your changes? 
We should also add a test to make sure we don't regress. I think we can just adapt something like this: https://github.com/mitmproxy/mitmproxy/blob/8fce7c7fa3be59f5760653e9e6daccee7f13cee9/test/mitmproxy/proxy/layers/http/test_http.py#L935-L947

**Comment by jixunmoe** [comment]
> Thanks for catching this! 🍰 
> Your proposal looks good to me. Do you want to send a PR with your changes? 

I can create a PR today afterwork.

> We should also add a test to make sure we don't regress. I think we can just adapt something like this: https://github.com/mitmproxy/mitmproxy/blob/8fce7c7fa3be59f5760653e9e6daccee7f13cee9/test/mitmproxy/proxy/layers/http/test_http.py#L935-L947

I'll add some tests here as well.

**Comment by jixunmoe** [comment]
PR created, CI seems to be happy.

https://github.com/mitmproxy/mitmproxy/pull/5374
