### ISSUE TITLE
Faster startup

### ISSUE THREAD

**Issue by ZzZombo** [mitmproxy/mitmproxy#5375]
#### Problem Description
Currently, even on my NVMe SSD the proxy takes too long to start up, making it unsuitable for running at computer boot time, many applications will hit a timeout before it is ready.

#### Proposal
Instead of a single file PyInstaller executable, also upload a single folder version.

#### Alternatives
I don't know of any.

#### Additional context
A single folder version skips extracting the distribution, greatly speeding the startup process; it's the recommended way of bundling if speed is a concern.

**Comment by mhils** [comment]
Which OS are you on? The Windows Installer is precisely that for the reasons you mentioned. :)

**Comment by ZzZombo** [comment]
I'm on Windows. Are you saying using an installer and not archived binaries solve the issue? I can't access the downloads due to Internet censorship ATM, so I can't verify that myself.

**Comment by ZzZombo** [comment]
Great. Could you provide a direct link to the file? As I said, currently I can't access the downloads page. Thanks in advance.

**Comment by mhils** [comment]
Sure thing: https://snapshots.mitmproxy.org/8.1.0/mitmproxy-8.1.0-windows-installer.exe

**Comment by ZzZombo** [comment]
Thank you! Could this distinction be elaborated in the docs somehow?

**Comment by mhils** [comment]
Done!
