### ISSUE TITLE
Missing dll for windows 7

### ISSUE THREAD

**Issue by Bricio** [mitmproxy/mitmproxy#5380]
#### Problem Description
Clean install using last windows installer. 
After successful installation. When double click or execute exe on cmd, An error is popped

> "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

#### Steps to reproduce the behavior:
1.  Log on windows 7 environment. 
2.  Install last windows installer. (https://snapshots.mitmproxy.org/8.1.0/mitmproxy-8.1.0-windows-installer.exe)
3.  Execute mitmproxy 

#### System Information
Paste the output of "mitmproxy --version" here.
```
D:\Program Files (x86)\mitmproxy\bin>mitmproxy --version
Error loading Python DLL 'D:\Program Files (x86)\mitmproxy\bin\python310.dll'.
LoadLibrary: The specified module could not be found.

D:\Program Files (x86)\mitmproxy\bin>
```
![image](https://user-images.githubusercontent.com/216170/170621484-c0365ce1-a6d4-46b6-b194-cb77dad1cf17.png)

btw. pipx install works on win7

**Comment by mhils** [comment]
Windows 7 is not supported anymore. We're a volunteer -based project and maintaining compatibility with unsupported OS versions is out of scope.

**Comment by Bricio** [comment]
If it was not supported, say something in website docs or during
installation. I searched before open this issue and cant find any mention
of it.

I didn't oppen this issue hopping to get it fixed, but to get it notted on
website.

The only prerequisite mention is the python 3.8+ in pipx instalation method.

Pipx version works fine in win 7.

**Comment by hayden-t** [comment]
what is the last version that works with 7 ?
