### ISSUE TITLE
In reverse mode, keep_host_header option invalidates proxyauth option

### ISSUE THREAD

**Issue by ryanisn** [mitmproxy/mitmproxy#5390]
#### Problem Description
proxy always return 401 when keep_host_header is enabled in reverse mode

#### Steps to reproduce the behavior:
1. set mode to be reverse, requests are proxyed as expected
2. set proxy auth, http auth prompted and can login with the user/pass defined
3. turn on keep_host_header, host is kept, but http auth does not validate with the correct user/pass

#### System Information
Mitmproxy: 8.1.0
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-4.14.276-211.499.amzn2.x86_64-x86_64-with-glibc2.31

**Comment by mhils** [comment]
Could you please post a single mitmproxy/mitmdump + cURL (or Chrome/Firefox) invocation that shows the issue?
