### ISSUE TITLE
Upstream error: The remote server does not speak TLS.

### ISSUE THREAD

**Issue by PavelICS** [mitmproxy/mitmproxy#5399]
#### Problem Description

When I do a request to any site, a TLS error occurs: "The remote server does not speak TLS."

The error is reproducible using mitmproxy>=7.
There is no any errors on mitmproxy==6.0.2. Everything works fine.

#### Steps to reproduce the behavior:
1. start mitm in upstream mode
`mitmweb --mode=upstream=https://host:port --upstream-auth=login:password`
2. run a test script, I use that one
```
	def test_mitm_upstream(self) -> None:
		proxy_ip = ''  # TODO set an upstream proxy IP
		session = requests.Session()
		session.proxies = {
			"http": "http://127.0.0.1:8080",
			"https": "http://127.0.0.1:8080",
		}
		response = session.get("https://api.ipify.org?format=json")
		print(response, response.text)
		ip = response.json().get('ip')
		self.assertTrue(proxy_ip == ip)
```

If you need some debug info, you are welcome. Just say what you need.
If you haven't got a TLS error, I can make my upstream proxy available from the Internet temporally for a month.

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 8.1.0
Python:    3.10.0
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Windows-10-10.0.19044-SP0

**Comment by mhils** [comment]
Is the Upstream server a regular HTTP(S) proxy, or a ["Secure Web Proxy"](https://www.chromium.org/developers/design-documents/secure-web-proxy/)  which itself establishes TLS with the client upon connect? It sounds like it's the former, but you're specifying `https://host:port` in your mitmproxy invocation. Replacing that with `http://host:port` should be good enough.

**Comment by PavelICS** [comment]
Yeah, you're right. It's using HTTP protocol for connection. Even mitmproxy6.0.2 in wireshark shown to be HTTP instead of HTTPS... That's why it works. I just decided finally to migrate to a newest mitmproxy, and that's was a huge surprise.

Thank you!
It means the problem in my upstream proxy, not mitmproxy.
