### ISSUE TITLE
Transparent mode on Windows lacks any documentation

### ISSUE THREAD

**Issue by ZzZombo** [mitmproxy/mitmproxy#5402]
Transparent mode on Windows is supported, but no indication of that exists outside the issues. That should be added.

**Comment by delebash** [comment]
I would love to use this feature.  Can anyone give a description on setting it up before the official docs?

**Comment by delebash** [comment]
Found it is easy.  Just add `--mode transparent `as a command line argument to any of the mitm exe's.  Even though the documentation says it does not work for Windows I have found that it does.  Probably just outdated docs.

So far it just works!  Awesome job!!!!
