### ISSUE TITLE
--setheader removes header

### ISSUE THREAD

**Issue by myguelraton** [mitmproxy/mitmproxy#541]
##### Steps to reproduce the problem:

$ mitmdump --setheader '/~hs Server/Server/something'
$ curl -svo /dev/null -x 0:8080 google.com

or

$ mitmdump --setheader '/~hs gws/Server/something
$ curl -svo /dev/null -x 0:8080 google.com

##### What is the expected behavior?

the goal is to set a header (server) only if it exists.  replace
the server header (only if it exists) with "server: something".

##### What went wrong?

the header (server) ends up being removed from the response.  instead
of "server: something" there is no server header in the response at all.

##### Any other comments?

--setheader will remove a header if the filter matches either the name
or the value of the header to be set.

---
mitmproxy version: 0.11.3
Operating System: ubuntu/12.04

**Comment by elitest** [comment]
$ mitmdump --setheader :~hs:Server:something

Kind of accomplishes what you want, except it doesn't do it based on the name of the webserver, it does it for everything.  I thought we could specify a filter after the option as the usage is: "usage: mitmdump [options] [filter]", but "mitmdump --setheader :~hs:Server:something ~hs Server: gws" doesn't work either.

--setheader really does need to be documented better as it is very opaque at the moment, even to someone who kind of understands python regular expressions.  I'm working on it for #510 so other examples are welcome over there.  I'd be interested to hear if anyone else can figure out a way to do this, as being able to chain stuff like that together would be useful, and something like it might be a good example for the docs.
