### ISSUE TITLE
Getting a set your LANG environment variable error when LANG environment is set

### ISSUE THREAD

**Issue by aral** [mitmproxy/mitmproxy#5413]
#### Problem Description

mitmproxy is asking me to set the `LANG` environment variable to a UTF-8 language when it already is.

#### Steps to reproduce the behavior:

1. Start mitmproxy with `LANG` set
2. Look at the console output

#### What should happen

There should not be a warning/error.

#### What actually happens

```
mitmproxy expects a UTF-8 console environment, not ''. Set your LANG environment variable to something like en_US.UTF-8.
```

#### Screenshot

![Screenshot from 2022-06-14 08-33-20](https://user-images.githubusercontent.com/41798/173520574-7a550aeb-8121-4ab1-b238-aee699a8306b.png)

#### System Information

```
Mitmproxy: 8.1.0 binary
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-5.17.12-300.fc36.x86_64-x86_64-with-glibc2.35
```

(Ubuntu 22.04 running under Distrobox on Fedora Silverblue 36.)

**Comment by mhils** [comment]
Does it start nonetheless?
Could you share the output of printer (please make sure to censor any tokens/secrets)?

FWIW here's the relevant code path:

https://github.com/mitmproxy/mitmproxy/blob/3eab9f0856403c53871d258bba289dfcbeb6e0df/mitmproxy/tools/console/master.py#L198-L206
