### ISSUE TITLE
Rename "Limit" Feature

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#542]
In a nutshell, I feel that "filter" describes the limit/filter feature more accurately than "limit".  Also, `f` is not taken as a keyboard shortcut. There were a few users in #mitmproxy asking for said feature, not realizing that limit does provide this functionality.

**Comment by mhils** [comment]
Quick summary of our discussion on IRC: There seems to be a consensus to ditch *limit*, but *filter* is difficult in mitmproxy's case as one may assume that this means filtering on the wire. Also, we should consider the distinction between highlighting the flows that match and only showing the flows that match.

Current candidates:

1. Search input and a "show only search hits" checkbox.
> i think there's a lot of cognitive load there. we have two different things: search, coupled with "show me stuff that matches search". i think those go together naturally.

2. Search input (always only showing hits) and dedicated highlight input(s).
> Having multiple highlights would be very useful to colorize traffic based on arbitrary filters (for example to mimic Wireshark's "colorize conversation" feature). The idea of multiple highlights doesn't match very well with a single search input.

**Comment by mooring** [comment]
`f` param will be better than `l`
first of all, `l` let me think setting the flow rows ,  it makes me confusing

**Comment by mhils** [comment]
From Slack:


@cortesi:
> @mhils just saw your other question yesterday. lets go with “filter view” and “toggle marked flow view"

>associated with that, i’d like to change the command line and keybindings to maintain the mnemonic

>-f for filter on the commandline. currently this is an alias for —follow, but we don’t need a short option for that.

>then i can use -l which is currently limit for some renaming i’m doing associated with logs.

>add_event -> add_log
