### ISSUE TITLE
Mismatch between documentation's example and git repo's examples

### ISSUE THREAD

**Issue by PythonTryHard** [mitmproxy/mitmproxy#5420]
#### Problem Description
Some examples on https://docs.mitmproxy.org/stable does not match with those at `[repo root]/examples/`

#### Steps to reproduce the behavior:
1. Navigate to https://docs.mitmproxy.org/stable/addons-examples/#commands-flows. Save this as `docs_code.py`
2. Navigate to  `[repo root]/examples/commands-flows.py`. Save this as `repo_code.py`
3. Compare the two addons. Run both code with `mitmweb -s` (`mitmproxy` raises the same issue, however the bug was first encountered while I was testing `mitmweb`)

#### Expected behavior
Docs' example code and repo's example code is loaded fine.

#### Actual behavior
- When docs' example code is used:
```
Could not load command myaddon.addheader: Argument flows has an unknown type typing.Sequence[mitmproxy.flow.Flow] in <bound method MyAddon.addheader of <__mitmproxy_script__.mitmtest.MyAddon object at 0x000001F262108460>>.
```
- Git repo is loaded fine.

#### System Information
```
Mitmproxy: 8.1.0 binary
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Windows-10-10.0.19044-SP0
```

**Comment by mhils** [comment]
See https://github.com/mitmproxy/mitmproxy/blob/main/examples/README.md:

> If you are browsing this on GitHub, make sure to select the git tag matching your mitmproxy version.

**Comment by YeZhuxi** [comment]
I had the same problem with the following environment:
```
Mitmproxy: 11.0.0, installed with pip
Python:    3.12.5
Platform:  Windows 10 22H2 19045.5011
```
I tried Python 3.9.13, but not work.
