### ISSUE TITLE
HTTP/2 connection failing due to error code: ENHANCE_YOUR_CALM (11)

### ISSUE THREAD

**Issue by deeox** [mitmproxy/mitmproxy#5425]
#### Problem Description

I tried to route HTTP/2 API requests through mitmproxy 8.1.0 and 5.3.0 both. But when i do a `GET` on the API (cannot disclose URL), chrome returns a error page with error ERR_HTTP2_PROTOCOL_ERROR with status `500`. 

On debugging mitmdump and chrome net logs, I discovered that the HTTP/2 request is failing due to the error code: ENHANCE_YOUR_CALM with the block HTTP2_SESSION_RECV_GOAWAY. 

The strange thing is the web API is working with other proxy applications like [browsermob](https://github.com/lightbody/browsermob-proxy). The requests only fail when routed through mitmproxy.

Not really sure if this is a mitmproxy bug or a bug on the backend of the application. 

#### Steps to reproduce the behaviour:
Since the URL that is failing cannot be disclosed, listing down the steps in general way.

1. Set up a application on Azure Application Gateway with self-signed certificate and HTTP2 enabled
2. Set up mitmproxy.
3. Hit a request of the API through mitmproxy.

#### Debug Logs

Through MITMProxy 5.3.0 (Getting the same error code in v8.1.0 as well)
```
::ffff:xx.xx.xx.xx:48102: HTTP/2 connection terminated by server: error code: 11, last stream id: 0, additional data: None
```

Network Logs from Chrome
```
t=11385 [st=148]    HTTP2_SESSION_RECV_GOAWAY
                    --> active_streams = 1
                    --> debug_data = "[0 bytes were stripped]"
                    --> error_code = "11 (ENHANCE_YOUR_CALM)"
                    --> last_accepted_stream_id = 0
                    --> unclaimed_streams = 0
t=11386 [st=149]    HTTP2_SESSION_CLOSE
                    --> description = "Finished going away"
                    --> net_error = 0 (?)
t=11386 [st=149]    HTTP2_SESSION_POOL_REMOVE_SESSION
```

#### System Information
Setup: 
- Client: mitmproxy (5.3.0 and 8.1.0), macOS Big Sur/Android
```
Mitmproxy: 8.1.0
Python:    3.9.13
OpenSSL:   OpenSSL 1.1.1m  14 Dec 2021
Platform:  macOS-11.6-x86_64-i386-64bit
```
- Server: Served through Azure Application Gateway with self-signed certificate and HTTP2 enabled.

**Comment by mhils** [comment]
This sounds like the target server is actively refusing connections from mitmproxy (probably via fingerprinting). Hard to say more without details!

**Comment by axelu** [comment]
@mhils We have been told further, that the server closes the connection because mitmproxy sends 7 parameters in the Settings frame, and that per RFC the settings frame can only contain parameters in multiple of 6 and if not, it is treated as a connection error.  So, the spec actually states:  
```
A badly formed or incomplete SETTINGS frame MUST be treated as a connection error
(Section 5.4.1) of type PROTOCOL_ERROR.
A SETTINGS frame with a length other than a multiple of 6 octets MUST
be treated as a connection error (Section 5.4.1) of type FRAME_SIZE_ERROR.
…
The payload of a SETTINGS frame consists of zero or more parameters,
each consisting of an unsigned 16-bit setting identifier and a 
unsigned 32-bit value.
```
We have not seen a PROTOCOL_ERROR or a FRAME_SIZE_ERROR.
So what is meant by that multiple of **6 octets** is actually that each parameter must be 16bits + 32bits = 48bits, so settings frame lengths of 0,48,96,etc. are allowed. The spec defines 6 parameter types. So if in fact there are 7 parameters sent, then either one or more are dups and/or one or more unknown parameter types are sent.  In the latter case, the spec states to ignore any unknown parameter type.  
But we do see the ENHANCE_YOUR_CALM error as quoted by @deeox. The spec further states: 
```
The SETTINGS frame can be abused to cause a peer to expend additional 
processing time.  This might be done by pointlessly changing SETTINGS 
parameters, setting multiple undefined parameters, or changing the same 
setting multiple times in the same frame.  … An endpoint MAY treat activity 
that is suspicious as a connection error 
(Section 5.4.1) of type ENHANCE_YOUR_CALM.
```

So, if in fact mitmproxy sends 7 params in the settings frame, at least one double or one unknown and that is treated as described in the last quote from the spec, then receiving the ENHANCE_YOUR_CALM error might make sense.

Is there a way to see what is actually send by mitmproxy in the settings frame?  In debug mode it provides great detail on the data received, but in the log we get we see that two settings frames are sent but no details on them.  How can one find out what is sent in the settings frame?

Sanitized log excerpt:
```
127.0.0.1:54877: client connect
127.0.0.1:54877: server connect example.com:443 (xxx.xxx.xxx.xxx:443)
127.0.0.1:54877: Http2Server h2 (debug): Initializing connection
127.0.0.1:54877: Http2Server h2 (debug): Send Settings frame: <h2.settings.Settings object at 0x...>
127.0.0.1:54877: Http2Client h2 (debug): Initializing connection
127.0.0.1:54877: Http2Client h2 (debug): Send Settings frame: <h2.settings.Settings object at 0x...>
127.0.0.1:54877: Http2Client h2 (trace): Process received data on connection. Received data: b'\x...0'
127.0.0.1:54877: Http2Client h2 (trace): Received frame: SettingsFrame(stream_id=0, flags=[]): settings={3: 128, 4: 65536, 5: 16777215}
127.0.0.1:54877: Http2Client h2 (trace): Received frame: WindowUpdateFrame(stream_id=0, flags=[]): window_increment=2147418112
127.0.0.1:54877: Http2Server h2 (trace): Process received data on connection. Received data: b"PRI * HTTP/2.0\r\n\r\n...0"
127.0.0.1:54877: Http2Server h2 (trace): Received frame: SettingsFrame(stream_id=0, flags=[]): settings={1: 65536, 4: 131072, 5: 16384}
127.0.0.1:54877: Http2Server h2 (trace): Received frame: WindowUpdateFrame(stream_id=0, flags=[]): window_increment=12517377
127.0.0.1:54877: Http2Server h2 (trace): Received frame: PriorityFrame(stream_id=3, flags=[]): exclusive=False, depends_on=0, stream_weight=200
127.0.0.1:54877: Http2Server h2 (trace): Received frame: PriorityFrame(stream_id=5, flags=[]): exclusive=False, depends_on=0, stream_weight=100
127.0.0.1:54877: Http2Server h2 (trace): Received frame: PriorityFrame(stream_id=7, flags=[]): exclusive=False, depends_on=0, stream_weight=0
127.0.0.1:54877: Http2Server h2 (trace): Received frame: PriorityFrame(stream_id=9, flags=[]): exclusive=False, depends_on=7, stream_weight=0
127.0.0.1:54877: Http2Server h2 (trace): Received frame: PriorityFrame(stream_id=11, flags=[]): exclusive=False, depends_on=3, stream_weight=0
127.0.0.1:54877: Http2Server h2 (trace): Received frame: PriorityFrame(stream_id=13, flags=[]): exclusive=False, depends_on=0, stream_weight=240
127.0.0.1:54877: Http2Server h2 (trace): Received frame: HeadersFrame(stream_id=15, flags=['END_HEADERS', 'END_STREAM', 'PRIORITY']): exclusive=False, depends_on=13, stream_weight=41, data=<hex:...>
127.0.0.1:54877: Http2Server h2 (debug): Attempting to initiate stream ID 15
127.0.0.1:54877: Http2Server h2 (debug): Stream ID 15 created
127.0.0.1:54877: Http2Server h2 (debug): Current streams: dict_keys([15])
127.0.0.1:54877: Http2Server h2 (trace): Received frame: WindowUpdateFrame(stream_id=15, flags=[]): window_increment=12451840
127.0.0.1:54877: Http2Server h2 (debug): Receive Window Update on <H2Stream id:15 state:<StreamState.HALF_CLOSED_REMOTE: 4>> for increment of 12451840
127.0.0.1:54877: Http2Client h2 (debug): Next available stream ID 1
127.0.0.1:54877: Http2Client h2 (debug): Send headers on stream ID 1
127.0.0.1:54877: Http2Client h2 (debug): Attempting to initiate stream ID 1
127.0.0.1:54877: Http2Client h2 (debug): Stream ID 1 created
127.0.0.1:54877: Http2Client h2 (debug): Current streams: dict_keys([1])
127.0.0.1:54877: Http2Client h2 (debug): Send headers [(b':method', b'GET'), (b':scheme', b'https'), (b':path', b'/'), (b':authority', b'example.com'), (b'user-agent', ...), (b'sec-fetch-dest', b'document'), (b'sec-fetch-mode', b'navigate'), (b'sec-fetch-site', b'none'), (b'sec-fetch-user', b'?1'), (b'te', b'trailers')] on <H2Stream id:1 state:<StreamState.IDLE: 0>>
127.0.0.1:54877: Http2Server h2 (trace): Process received data on connection. Received data: b'\x...0'
127.0.0.1:54877: Http2Server h2 (trace): Received frame: SettingsFrame(stream_id=0, flags=['ACK']): settings={}
127.0.0.1:54877: Http2Client h2 (trace): Process received data on connection. Received data: b'\x0...b'
127.0.0.1:54877: Http2Client h2 (trace): Received frame: GoAwayFrame(stream_id=0, flags=[]): last_stream_id=0, error_code=11, additional_data=b''
127.0.0.1:54877: GET https://example.com/ HTTP/2.0
    user-agent: ...
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    accept-language: en-US,en;q=0.5
    accept-encoding: gzip, deflate, br
    upgrade-insecure-requests: 1
    sec-fetch-dest: document
    sec-fetch-mode: navigate
    sec-fetch-site: none
    sec-fetch-user: ?1
    te: trailers

 << HTTP/2 connection closed: <ConnectionTerminated error_code:ErrorCodes.ENHANCE_YOUR_CALM, last_stream_id:0, additional_data:None>
127.0.0.1:54877: Http2Server h2 (debug): Send headers on stream ID 15
127.0.0.1:54877: Http2Server h2 (debug): Send headers [(b':status', b'502'), (b'server', b'mitmproxy 8.1.0'), (b'content-type', b'text/html')] on <H2Stream id:15 state:<StreamState.HALF_CLOSED_REMOTE: 4>>
127.0.0.1:54877: Http2Server h2 (debug): Send data on stream ID 15 with len 254
127.0.0.1:54877: Http2Server h2 (debug): Frame size on stream ID 15 is 254
127.0.0.1:54877: Http2Server h2 (debug): Send data on <H2Stream id:15 state:<StreamState.HALF_CLOSED_REMOTE: 4>> with end stream set to True
127.0.0.1:54877: Http2Server h2 (debug): Outbound flow control window size is 12582658
127.0.0.1:54877: server disconnect example.com:443 (xxx.xxx.xxx.xxx:443)
```

**Comment by mhils** [comment]
> We have been told further, that the server closes the connection because mitmproxy sends 7 parameters in the Settings frame, and that per RFC the settings frame can only contain parameters in multiple of 6 and if not, it is treated as a connection error.

I think whoever told you this is misunderstanding the spec. You may have any number of SETTINGS Parameters, but each parameter occupies exactly six octets.

> The spec defines 6 parameter types. So if in fact there are 7 parameters sent, then either one or more are dups and/or one or more unknown parameter types are sent.

The HTTP/2 spec does indeed define an initial 6 parameter types, but there are more than that:

https://httpwg.org/specs/rfc7540.html#iana-settings
https://www.iana.org/assignments/http2-parameters/http2-parameters.xhtml#settings

----------------------------

You can enable SSLKEYLOGFILE and use Wireshark (https://docs.mitmproxy.org/dev/howto-wireshark-tls/) to see what's actually sent out. On my machine I see the following seven settings:

![image](https://user-images.githubusercontent.com/1019198/180236352-fa314086-2e8d-4ea7-ac4c-fa8fb9ad5d14.png)

where 0x08 is not recognized by WireShark but specified as SETTINGS_ENABLE_CONNECT_PROTOCOL ([RFC 8441](https://www.rfc-editor.org/rfc/rfc8441.html)). From what I'm seeing this is an upstream bug, not a mitmproxy error.
