### ISSUE TITLE
cannot get server connection to ilo3 (unsupported protocol version)

### ISSUE THREAD

**Issue by markusdd** [mitmproxy/mitmproxy#5449]
Hi, I am trying to use mitmdump to still access my HP ilo3 management interfaces. These stopped at supporting 
TLS v1.1 and essentially every Browser nowadays refuses to connect, even with the AES ciphers turned on.

From a CentOS 7 machine, I can successfully curl the login page like so:
` curl -k --tlsv1.1 <my ip>`

I start mitmdump like this (setting cipher_server to 'ALL' does not help):
`mitmdump --set tls_version_server_min=TLS1_1  --set tls_version_server_max=TLS1_1 --ssl-insecure -p 9443 --mode reverse:https://192.1xxxxxxxx/`

Wireshark shows this. Could it be, that the Ciphersuite is not supported by mitmdump? I tried setting 'ALL', but also with TLS I had to be very specific as mitmdump would first try TLSv1.0, that would fail and it would not retry the others.
![image](https://user-images.githubusercontent.com/25175069/178127761-063d3add-8308-4693-9629-17c00e5a86b6.png)

I can load the page in firefox after waiving the pinned cert, but then I get the same message as mitmdump prints on the commandline, so mitmdump won't talk to the server:
![image](https://user-images.githubusercontent.com/25175069/178127802-7bb19e0f-11a0-4fba-93b2-3a40c85c6eed.png)

To successfully ssh into the ilo port, I have to use this contraption, but it works:
`ssh -oKexAlgorithms=+diffie-hellman-group14-sha1 -oHostKeyAlgorithms=+ssh-dss -oCiphers=+aes256-ctr`

Any hints which syntax/cipher to use to make this work?

```
Mitmproxy: 8.1.1 binary
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-5.18.9-200.fc36.x86_64-x86_64-with-glibc2.35
```

**Comment by markusdd** [comment]
Ok, some more info:

if I add `--set ciphers_server=TLS_RSA_WITH_AES_128_CBC_SHA ` to the commandline what I get is this:

![image](https://user-images.githubusercontent.com/25175069/178128037-c8addd4d-e7f8-499b-896d-331ad577165f.png)

**Comment by markusdd** [comment]
ok, so I have it working now, albeit with mitmproxy 6.0.2, so an outdated version.

This is about the embedded OpenSSL. Mitmproxy claims it e.g. can do AES128-SHA (which ilo3 supports), but still the negotiation fails because the packaged OpenSSL 3 views this as a legacy cipher which is not 'on' anymore by default.
Question: How to enable this, so that an up-to-date mitmproxy version can be used?

**Comment by mhils** [comment]
You can adjust which ciphers are supported by setting https://docs.mitmproxy.org/stable/concepts-options/#ciphers_server. This value is directly fed into OpenSSL, so you need to look at their docs for details.

In some cases the necessary ciphers are so old that our OpenSSL version doesn't have them, in that case the best bet is a chain of proxies (or manually recompiling, which is super painful). 🤷‍♂️

**Comment by markusdd** [comment]
I know that this works via ciphers_server, but not in newer packaged OpenSSL versions which have another twist added to them.
They explicitly state that they still support legacy ciphers like AES128_SHA (which I can pass to mitmdump), but it also requires that you explicitly enable the legacy cipher support. I do not know how to do this through mitmproxy right now.

Right now mitmproxy behaves kind of erratic from version 7 upwards, because in your tls_options.py file you explicitly list AES128_SHA as a cipher which is accepted by ciphers_server, but handing it down without any additional legacy support enabled leads to the error above.

For curl, I was able to pull it off by providing a modified openssl_conf in the environment:
![image](https://user-images.githubusercontent.com/25175069/178154115-185b6600-4a2f-43f2-973b-76e42d422cc2.png)

And then calling curl like so:
![image](https://user-images.githubusercontent.com/25175069/178154151-71b8bcc3-f48d-4e42-8a19-5cf2f8ab501b.png)

**Comment by mhils** [comment]
Does cURL work if you remove the UnsafeLegacyRenegotiation thing? Then maybe it's a matter of calling setting the SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION option here: https://github.com/mitmproxy/mitmproxy/blob/af5be0b92817eebb534e05fa0cc45127a70fa113/mitmproxy/net/tls.py#L47

**Comment by markusdd** [comment]
nope, it fails:
![image](https://user-images.githubusercontent.com/25175069/178155931-3587203d-acf7-4d6d-81c8-5ef7defd0ca8.png)

So you are right, that could be it.

**Comment by mhils** [comment]
Closing this as it's not really a mitmproxy bug. :)

**Comment by markusdd** [comment]
Don't quite get this. Wasn't the discussion that mitmproxy should expose this unsaferenegotiation option?

**Comment by mhils** [comment]
I absolutely don't mind adding an additional option for this, but the last status update was that we weren't even sure if that solves it. If you have something that demonstratably fixes your case I'm more than happy to merge it. :)

**Comment by markusdd** [comment]
I thought that is what the curl call demonstrates^^
 if I apply the openssl conf above before calling curl it works, If I leave it I get  the error.

**Comment by markusdd** [comment]
I see. Yeah implementation wise this is out of my comfort zone unfortunately.

It is a bit of a bummer because on newer OSes this kind of destroys one major usecase of mitmproxy: acting as a bridge to outdated control webpages like HP iLO3, which cannot be updated to support newer ciphers
