### ISSUE TITLE
navigation features

### ISSUE THREAD

**Issue by Kidlike** [mitmproxy/mitmproxy#545]
Thanks for this awesome tool.

Something that would make it much more usable is these few key features of `less` (not the css pre-processor :neckbeard: )

Namely:
* `shift + .` or `g` to navigate to the end of the list
* `shift + ,` or `shift + g` to navigate to the start of the list
* `shift + f` to start following the list (auto scrolling) and then `ctrl + c` to cancel
* `/` and `shift + /` to search forwards and backwards respectively

**Comment by cortesi** [comment]
I've just added g/G shortcuts to go to the end/beginning in most contexts in commit 8e2e83a3c6d47e52a5398f851b2900dd042f3d6a. We already have shift+f to follow the list and autoscroll,   though you toggle that off with shift+f again as opposed to ctrl-c. We're rolling out search in most view contexts at the moment (/ to search, n to find next, N to find previous). 

This means that the remaining item on your wishlist is search in the flow list context. This is a bit more complicated, and is something we're pondering separately. 

I'll close this ticket for now - thanks for making the feature request that prompted me into action with g/G - it's been on my own wishlist for a while.

**Comment by Kidlike** [comment]
That is cool... :+1: 

Is it possible to start mitmproxy in "following" mode ?

**Comment by cortesi** [comment]
Not at the moment, but I'd merge a patch that adds a "--follow" flag to mitmproxy to do this.

**Comment by tacahiroy** [comment]
I've noticed shortcuts 'g' and 'G' are backward as less behaviour. Is there any reasons for this?
I'm bit confused whenever I use these keys.
Quoting from *man 1 less*:
```
g or < or ESC-<
        Go to line N in the file, default 1 (beginning of file).  (Warning: this may be slow if N is large.)

G or > or ESC->
        Go  to  line N in the file, default the end of the file.  (Warning: this may be slow if N is large, or if N is not speci-fied and standard input, rather than a file, is being read.)
```

**Comment by cortesi** [comment]
Huh. You're right, and I'd like to match people's expectations. I'd merge a patch that swaps these two bindings.
