### ISSUE TITLE
Help window doesn't appear, when changing cofing

### ISSUE THREAD

**Issue by EastHell** [mitmproxy/mitmproxy#5450]
#### Problem Description
While changing parameters in options (like allow_hosts or block_list), there is hint on the bottom of the window "No values - you should add some. Press `?` for help."

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/28960974/178137006-6180d972-967d-427b-b5df-4ba0a50ce1a9.png">

But after I'm pressing `?` - nothing happend. No help window appear.

Then when I'm quit parameter editing, help window for options appear (not for parameter changing window).

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/28960974/178137041-838bb861-574e-4059-a09c-43c526719f2c.png">

Looks like something went wrog, because I'm expext help window with hotkeys for adding new hosts.

#### Steps to reproduce the behavior:
1. Type `mitmproxy` in your terminal
2. Press `O`
3. Select `allow_hosts` and press `Enter`
4. Press `?`

**Expected**: Help window appear for `alliow_hosts` window
**Actual**: Nothing happend, help window for `Options` window appear after quit `allow_hosts` window.

#### System Information
Mitmproxy: 8.1.1
Python:    3.10.5
OpenSSL:   OpenSSL 1.1.1q  5 Jul 2022
Platform:  macOS-12.4-arm64-arm-64bit

**Comment by pradyotRanjan** [comment]
Can I work on this issue?

**Comment by i1v** [comment]
same problem here. I would prefer to add using the UI instead of the command line, but it seems its not currently possible

**Comment by i1v** [comment]
https://github.com/mitmproxy/mitmproxy/issues/2952

**Comment by i1v** [comment]
looks like once you are in the grid editor, you can hit `a` to add an entry
