### ISSUE TITLE
mitmproxy doesn't capture much if a site is already loaded

### ISSUE THREAD

**Issue by jj-007** [mitmproxy/mitmproxy#5453]
#### Problem Description
If you are already on a website on the client device and you start the mitmproxy on the server, it doesn't actually capture much activity of that website as you navigate through pages. It only seems to capture properly once you have closed the tab and visit the website again. For example if the client device is on Amazon.com and then the mitmproxy is started, other than a few .js libraries and other scripts, it won't capture much for that site as I navigate through different pages, unless I close the tab and reload Amazon.com. In other words I cannot see any subsequent pages that a user visits on Amazon.com.

#### Steps to reproduce the behavior:
1.  Visit Amazon.com on a client device.
2. Start mitmproxy: mitmproxy -p 2448
3. Navigate different pages on Amazon.com site that was previously loaded.

#### System Information
Mitmproxy: 8.0.0
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Linux-5.4.0-107-generic-x86_64-with-glibc2.29

**Comment by Prinzhorn** [comment]
I think the pages and resources are simply cached by the browser and hence the requests will never reach mitmproxy? There might also be some client side routing involved, so even if you expect to see HTML pages being served for each navigation, there aren't actually any being sent from the server. From the provided information I don't think this is an issue with mitmproxy.

**Comment by jj-007** [comment]
The proxy is already entered in the device using an auto config file. So in other words, when mitmproxy is started, then the device will default to that, if not then it will just connect directly. So in my example above, I visit Amazon.com with mitmproxy disabled and then I would start the proxy on my server, which would cause the device to use that instead. But because the page was already loaded, if I then start clicking any of the links on the page and navigate to other pages, it doesn't get picked up by the proxy

**Comment by Prinzhorn** [comment]
Can you somehow verify this by switching between two mitmproxy instances? I assume, if our theory is correct, you'll see the requests in the "old" mitmproxy that isn't actually used anylonger because the connection is kept open. If that's the case, this is not a bug in mitmproxy and nothing we can do.

**Comment by nguyenhoangdai** [comment]
Hi @Prinzhorn . I'm having same problem as @jj-007. ( I use Transparent Mode on mitmproxy and configure all the traffics to redirect to port 8080 as instructions). Moreover, Mitmproxy does not pick up all the traffics. 
One example is that if I access the page that also loads ReCAPTCHA from google. Mitmproxy does not pick up the request to google for the recaptcha which I see it is captured in the DEV tools. I'm also aware of --anticache option but it doesn't help either.
I guess my question is how can I actually pick up all HTTPS/HTTP traffics in mitmproxy? I'd appreciate any recommendation or explanation you could give.
