### ISSUE TITLE
 cannot import name 'HTTPResponse' from 'mitmproxy.http'

### ISSUE THREAD

**Issue by klaksik** [mitmproxy/mitmproxy#5464]
#### Problem Description
hi gyse, i`m usage pymultitor, and have 

Traceback (most recent call last):
  File "C:\Users\User\Desktop\pymultitor-3.1\pymultitor.py", line 14, in <module>
    from mitmproxy.http import HTTPResponse
ImportError: cannot import name 'HTTPResponse' from 'mitmproxy.http' (C:\Users\User\Python\lib\site-packages\mitmproxy\http.py)

#### Steps to reproduce the behavior:
1. 
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.

**Comment by klaksik** [comment]
Mitmproxy: 8.1.1
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  Windows-10-10.0.22000-SP0

**Comment by Prinzhorn** [comment]
Unless you can provide steps to reproduce this with just mitmproxy, then this is an issue with pymultitor https://github.com/realgam3/pymultitor/issues/33
