### ISSUE TITLE
Pressing X doesn't kill an intercepted request

### ISSUE THREAD

**Issue by kshitij86** [mitmproxy/mitmproxy#5484]
#### Problem Description
While intercepting a request, focusing on it and pressing `x` does nothing, while `a` allows it to go through.

#### Steps to reproduce the behavior:
1. Run mitmproxy
2. Make a request with the proxy flag, `curl --proxy http://127.0.0.1:8080 "http://wttr.in/Dunedin?0"` and intercept it.
3. Try to kill the flow by pressing `x`

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 8.1.1
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  Linux-5.4.0-122-generic-x86_64-with-glibc2.31
```

**Comment by Prinzhorn** [comment]
Are your steps missing the part where you define an intercepting patter via `i`?

Might be related to https://github.com/mitmproxy/mitmproxy/issues/4711

**Comment by kshitij86** [comment]
@Prinzhorn Yeah, sorry for that missed the interception step, but as the title says.

**Comment by Prinzhorn** [comment]
I just looked at it, did you use `x` or `X`? I can kill the intercepted flow with an upper case `X`, it fails with a `Connection killed.` error

**Comment by Prinzhorn** [comment]
Can you show a screenshot of the situation when you are pressing X?

**Comment by kshitij86** [comment]
Works now, I was entering the flow details and trying to kill it. Looks like it needs to be done from the flow list itself. Although it should be possible from the focused view/flow details view.

**Comment by Prinzhorn** [comment]
That's what I was guessing, hence the question.

As such this is a duplicate of https://github.com/mitmproxy/mitmproxy/issues/4515, the shortcuts should be clearer and more discoverable.

**Comment by SkylarYutz925** [comment]
hello，I use “SELECT citus.mitmproxy('conn.onQuery(query="DROP TABLE IF EXISTS move_shard.t CASCADE").kill()');” but i can not close connection,how can i do?
