### ISSUE TITLE
mitmproxy 8.1.1 is identified as malware by McAfee and other AV vendors

### ISSUE THREAD

**Issue by virtualwatt** [mitmproxy/mitmproxy#5486]
Please update the hash so it will not be detected as a malware by multiple Anti-Virus vendors as McAfee.

[Detection screenshot](https://1drv.ms/u/s!AhDwWd7wOGnLon4OSAOzToolcWbO)

### Discussed in https://github.com/mitmproxy/mitmproxy/discussions/5467

<div type='discussions-op-text'>

<sup>Originally posted by **CruzMarcio** July 19, 2022</sup>
McAfee Endpoint Security identifies mitmproxy.exe as malware:

Adaptive Threat Protection repaired C:\tools\mitmproxy\mitmweb.exe TargetType, because its reputation (Known Malicious) is below the configured Clean threshold.

Analyzer / Detector
--
Product name | McAfee Endpoint Security
Product version | 10.7.0.3183
Feature name | Real Protect Cloud
 
Threat
Action taken | Clean
Threat category | Malware Detected
Threat event ID | 35107
Threat handled | Yes
Threat name | Real Protect-peft7!4CF8F35B22D3
Threat severity | Critical
Threat timestamp | 7/19/2022 9:08 AM
Threat type | Trojan
 
Target
Target hash | 4cf8f35b22d371a1bebfa4bf4c5b03ee
Target name | mitmweb.exe</div>

**Comment by mhils** [comment]
I have already replied in the discussion you linked. There's no need to open a new issue.
