### ISSUE TITLE
I can't open Mitmproxy (ImportError: No module named main)

### ISSUE THREAD

**Issue by texom512** [mitmproxy/mitmproxy#550]
Hey everybody!

I want to open Mitmproxy, but if I type that in terminal:
    mitmproxy
I get that:
    Traceback (most recent call last):
      File "/usr/local/bin/mitmproxy", line 2, in <module>
        from libmproxy.main import mitmproxy
    ImportError: No module named main

I installed Mitmproxy like this:
    sudo pip2 install mitmproxy

Thanks for any help!

**Comment by mhils** [comment]
Hi @texom512,

looks like you have an outdated version of mitmproxy installed somewhere. If you uninstall mitmproxy completely (you may have installed using `apt-get` before?) and the reinstall, it should work.

Cheers,
Max
