### ISSUE TITLE
Unsupported SOCKS5 request: b'\x05\x03\x00\x01\x00\x00\x00\x00\x00\x00'

### ISSUE THREAD

**Issue by mu0gua** [mitmproxy/mitmproxy#5503]
1. mitmdump --mode socks5
2. There is no problem with the computer setting socks5 proxy
3. The following problems occur when the mobile phone sets socks5 proxy

````
Unsupported SOCKS5 request: b'\x05\x03\x00\x01\x00\x00\x00\x00\x00\x00'
.....
Probably not a SOCKS request but a regular HTTP request. Invalid SOCKS version. Expected 0x05, got 0x47
......
````

As I don't have enough logs, I can only provide the above information, if more is needed, please tell me how to do it.

**Comment by surbiks** [comment]
i have same issue

**Comment by Prinzhorn** [comment]
> please tell me how to do it.

`mitmdump --mode socks5 --set proxy_debug -vvv`

**Comment by mhils** [comment]
Closing this for a lack of information. :)

**Comment by recolic** [comment]
I'm having the same problem. The reason is: SOCKS5 client is sending UDP over SOCKS.
Try to disable UDP from your client, and problem would be resolved.

```
[19:33:08.606][127.0.0.1:46058] client connect
[19:33:08.645][127.0.0.1:46058] Unsupported SOCKS5 request: b'\x05\x03\x00\x01\x00\x00\x00\x00\x00\x00'
[19:33:08.645][127.0.0.1:46058] client disconnect
```
