### ISSUE TITLE
ZSTD-compressed content hook issue

### ISSUE THREAD

**Issue by slonopot** [mitmproxy/mitmproxy#5506]
#### Problem Description
I use mitmproxy in the socks5 mode with a plugin that hooks several client requests and sends them using the aiohttp/requests with a proxy and then returns the response using the `flow.response`. Consider it an alternative to the upstream mode. I had success with all the encodings except ZSTD: mitmproxy is unable to decrypt zstd after the mangle and the client fails afterwards as well. If I decrypt the content manually and return it (removing the `Content-Encoding` header and updating the `Content-Length`) then everything works fine.

#### Steps to reproduce the behavior:
1. Client sends a request with `Accept-Encoding: zstd`.
2. mitmproxy plugin receives it in the `async def request(self, flow: http.HTTPFlow) -> None`
3. Plugin replays the request and gets the response (or generates the response) with `Content-Encoding: zstd` and returns the response as `flow.response = http.Response.make(result.status, content, headers)`
4. mitmproxy is unable to decrypt zstd content in the viewer, client fails to handle the response as well

The fix that I came with is:
```
async with aiohttp.request(flow.request.method, flow.request.pretty_url, headers=dict(flow.request.headers), data=flow.request.content, proxy=PROXY, proxy_auth=aiohttp.BasicAuth(PROXY_USER, PROXY_PWD)) as result:
    content = await result.content.read()
    headers = dict(result.headers)
    if (enc := headers.get('Content-Encoding')) is not None and enc == 'zstd':
        decomp = zstandard.ZstdDecompressor()
        content = decomp.decompress(content)
        del headers['Content-Encoding']
        headers['Content-Length'] = str(len(content))
    flow.response = http.Response.make(result.status, content, headers)
```

#### System Information
Built it yesterday using the latest Python 3.10 (built from source right before building the mitmproxy)
```
Mitmproxy: 9.0.0.dev (+55, commit 6cfde13)
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  Linux-4.15.0-x86_64-with-glibc2.27
```

Let me know if you require any additional information.

**Comment by Prinzhorn** [comment]
This is an issue with `content` vs `raw_content`. `http.Response.make` expects the decompressed content. The client essentially receives the body as double compressed zstd.

https://github.com/mitmproxy/mitmproxy/blob/73c38f698d42002947e46294498b2166f3139cf4/mitmproxy/http.py#L1120-L1122

https://github.com/mitmproxy/mitmproxy/blob/73c38f698d42002947e46294498b2166f3139cf4/mitmproxy/http.py#L336-L338

https://github.com/mitmproxy/mitmproxy/blob/73c38f698d42002947e46294498b2166f3139cf4/mitmproxy/http.py#L355-L378

I suggest not using the `http.Response.make` helper and building the response yourself via `mitmproxy.http.Response`, following the `http.Response.make` logic but setting `raw_content` manually.
