### ISSUE TITLE
recording freezes for IIS server with client certificate

### ISSUE THREAD

**Issue by mrsiano** [mitmproxy/mitmproxy#5511]
#### Problem Description
recording freezes when trying to recored application on top of IIS server that uses client certificate.
but when using the same client certificate (same authority) on top of Apache server the recording passed as expected.

note: without mitmproxy we have normal behaviour on browser, we see the behaviour only when recording.

#### Steps to reproduce the behaviour:
1. install IIS server (IIS version 6.2 on windows 2012 R2)
2. generate some CA (authority).
3. configure the IIS server as following:
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/13570786/182633982-6230b56d-89a9-4d10-b9e9-aac5bad8014d.png">
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/13570786/182634079-8ee48f05-a6cc-454c-ab3a-10db73b012d8.png">
<img width="634" alt="image" src="https://user-images.githubusercontent.com/13570786/182634146-6faf1af9-3afb-4b96-a168-4399ec7b1f0f.png">

4. recored the IIS app by using client certificate.

#### System Information
Mitmproxy: 8.1.1 binary
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  macOS-10.15.7-x86_64-i386-64bit

**Comment by mhils** [comment]
We don't have any IIS servers here, so we can't reproduce this.
