### ISSUE TITLE
does not work on windows 10

### ISSUE THREAD

**Issue by spereg53** [mitmproxy/mitmproxy#5513]
#### Problem Description
installed on windows 10,configured on proxy :127.0.0.1:8080,but i can not get pages from internet
#### Steps to reproduce the behavior:
127.0.0.1:22968: Client TLS handshake failed. The client does not trust the proxy's certificate for vip2.fastcast4u.com (OpenSSL Error([('SSL routines', '', 'sslv3 alert certificate unknown')]))

#### System Information
Paste the output of "mitmproxy --8.1.1.

**Comment by Prinzhorn** [comment]
Visit `http://mitm.it` to install the required certificate. https://docs.mitmproxy.org/stable/concepts-certificates/
Feel free to re-open with more details if that doesn't fix your problem.

**Comment by spereg53** [comment]
ceets work for all pages ,but not for gmail.com,what can i do???
ING.SERGIO M.PEREZ GORDILLO
CALLE DE CHAMULA #21
COL.LA LOMITA;C.P.29060
TUXTLA GTZ.CHIAPAS,MEXICO
TEL:019612640373 y
019611214526
CELULAR:9612015537
***@***.***
***@***.***

**Comment by Prinzhorn** [comment]
> ceets work for all pages ,but not for gmail.com,what can i do???

1. Provide steps to reproduce the error
2. Explain what "does not work" mean. Is there an error message?
3. Follow the template for reporting bugs if you believe this is a bug. In your case more information about the system such as what browser you are using.

"Does not work for gmail.com" is nothing we can act on.

**Comment by jamesenh** [comment]
I have the same problem, but I have installed a CA root certificate and still cannot intercept HTTPS requests

**Comment by jamesenh** [comment]
I have the same problem, but I have installed a CA root certificate and still cannot intercept HTTPS requests
![企业微信截图_16614948551627](https://user-images.githubusercontent.com/57517615/186839570-91c0b244-0a49-4724-98d3-b946f6577b76.png)
![image](https://user-images.githubusercontent.com/57517615/186839685-dffa7447-e73c-4663-9cfa-d8f46a9cac9f.png)

mitmproxy --version
Mitmproxy: 8.0.0
Python:    3.8.6
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Windows-10-10.0.19041-SP0

**Comment by Prinzhorn** [comment]
> The client does not trust the proxy's certificate

What's the client? Some Python libraries don't use the Windows certificate store, that is unrelated to mitmproxy.

https://github.com/psf/requests/search?q=CERTIFICATE_VERIFY_FAILED&type=issues
https://github.com/psf/requests/blob/main/docs/user/advanced.rst#ssl-cert-verification
https://github.com/psf/requests/issues/5316

In the future when reporting bugs follow the template. You didn't provide steps to reproduce the error and didn't specify what client you were using. But I could somewhat guess form the error in the window behind mitmproxy.

**Comment by jamesenh** [comment]
> 

![image](https://user-images.githubusercontent.com/57517615/186842501-ca868264-986c-40f7-9630-e125b192420f.png)
However, using Firefox browser on Windows, accessing HTTPS page will also be regarded as invalid certificate, which I can not find where the problem is

**Comment by Prinzhorn** [comment]
We have very extensive documentation at https://docs.mitmproxy.org/stable/, you might want to check it out. Firefox doesn't use the system store either.

https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually
https://wiki.mozilla.org/MozillaRootCertificate#Mozilla_Firefox

**Comment by Frederick2001** [comment]
![IMG_20240103_081129_040](https://github.com/mitmproxy/mitmproxy/assets/80492682/98ed62bd-cd95-42b2-966d-228ee9377ee5)
After downloading mimproxy on my window 10 PC , then I typed the 'mitmproxy' command.  It displays 502 Bad Gateway
