### ISSUE TITLE
How to only monitor http traffic using libmproxy?

### ISSUE THREAD

**Issue by gygl09** [mitmproxy/mitmproxy#552]
How can I only monitor http traffic, and ignore all https traffic?

Thanks,
Yang

**Comment by mhils** [comment]
Hi @gygl09,

sure - check out http://mitmproxy.org/doc/features/passthrough.html.
`--ignore :443$` should just work.

Cheers,
Max

**Comment by gygl09** [comment]
hi @mhils,

I am attempting to using libproxy to do it, but I faced some problem. Here is part of my code:

**Comment by masind** [comment]
Try to use an ssl certificate
