### ISSUE TITLE
Mitmproxy can't resolve .local hostnames

### ISSUE THREAD

**Issue by DUOLabs333** [mitmproxy/mitmproxy#5523]
#### Problem Description
If you try to search for a .local hostname (I assume that this occurs for any mdns hostname), mitmproxy will error with 
```
[Errno -2] Name or service not known
```

#### Steps to reproduce the behavior:
1. Setup avahi/bonjour and see if you can connect to <your system's hostname>.local
1. Try to connect to  hostname.local through mitmproxy
2. See error

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 7.0.4
Python:    3.10.4
OpenSSL:   OpenSSL 1.1.1l  24 Aug 2021
Platform:  Linux-5.18.1-1-aarch64-ARCH-aarch64-with-glibc2.32
```

**Comment by Prinzhorn** [comment]
> `Mitmproxy: 7.0.4`

Please try with the latest 8.1.1 release. I can access `http://example.local/` that I've added to my `/etc/hosts` as `127.0.0.1 example.local`. If it doesn't work with 8.1.1 for you we need more information. What exactly does " .local hostname that exists" mean?

**Comment by DUOLabs333** [comment]
Oh, I meant one that is accessible with avahi, not one in `hosts`.

**Comment by Prinzhorn** [comment]
I've never heard of avahi and I'm not familiar with the semantics of `.local`. Can you please explain your setup? Your "Steps to reproduce the behavior:" clearly miss a couple of steps.

**Comment by DUOLabs333** [comment]
I have avahi setup so I can access MDNS hostnames, which is the error.

**Comment by DUOLabs333** [comment]
It works if I don't use mitmproxy, so there's nothing wrong with the setup.

**Comment by meitinger** [comment]
> It works if I don't use mitmproxy, so there's nothing wrong with the setup.

As @mhils already stated, name resolution in mitmproxy boils down to `getaddrinfo`, which on Linux uses NSS resolution. You are correct in pointing out that there are native solutions for Python that query mDNS directly, however, that's not implemented in mitmproxy. (And I doubt it will.)

Please run the following code in python: (replacing `msdn-hostname` with the appropriate name)
```python
import socket
print(socket.getaddrinfo("msdn-hostname.local", 80, proto=socket.IPPROTO_TCP))
```
If that returns an IP, there might be something wrong with mitmproxy.

If not, it's your local NSS configuration and there is nothing mitmproxy can do. In that case the question is, how does your `nsswitch.conf` look like? Did you configure avahi to respond to more than just the hostname? Check with the nss-mdns documentation for further guidance.
