### ISSUE TITLE
Running mitmdump on Windows from the Path requires file extension

### ISSUE THREAD

**Issue by elitest** [mitmproxy/mitmproxy#554]
I have been working on user installation documentation in regards to #516 and I'm recommending that when users install Python they "Add Python.exe to Path" which adds "C:\Python27\" and "C:\Python27\Scripts\" to %PATH%.  Then the user installs mitmproxy using "pip install mitmproxy".  Then when you try to run "mitmdump", it doesn't find it.  Turns out this is due to mitmdump being installed to "C:\Python27\Scripts\mitmdump" without a ".py" file extension.

The weird thing is that when I pull from master, and run setup.py manually mitmdump(and mitmweb) gets properly turned into an exe.  I looked through setup.py and there isn't anything obvious to me that is doing this.  Was this fixed on master and we are just waiting for 0.11.4 to be released and to be loaded onto PyPI or is pip introducing something into the mix?

**Comment by mhils** [comment]
Hi @elitest,

the exe is generated using setuptools entry_points, introduced in 355f9fc40799c88f413ca260dd93691074fd758e. 0.11.4 should just generate executables :smiley:

Cheers,
Max
