### ISSUE TITLE
magic domain mitm.it not working with allow-hosts in transparent mode

### ISSUE THREAD

**Issue by Bart274** [mitmproxy/mitmproxy#5552]
#### Problem Description
I run my mitmweb in transparent mode and want to only intercept the data from a few domains, so I used the allow-hosts option.
I can't figure out the ip to use to let mitm.it work in this setup.

#### Steps to reproduce the behavior:
1. Run mitmweb with this command: `mitmweb --allow-hosts <ip1> --allow-hosts <ip2> --allow-host <external ip of proxy server> --allow-host <local ip of proxy server> --set block_global=true --mode transparent`
2. connect to the proxy server and go to mitm.it and see the 'If you can see this, traffic is not passing through mitmproxy.' error.

#### System Information
Mitmproxy: 8.1.0
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-5.15.0-43-generic-x86_64-with-glibc2.35

**Comment by mhils** [comment]
You need to use whatever IP addresses `mitm.it` resolves to:
```
λ dig mitm.it
;; ANSWER SECTION:
mitm.it.                60      IN       A       18.66.17.68
mitm.it.                60      IN       A       18.66.17.51
mitm.it.                60      IN       A       18.66.17.62
mitm.it.                60      IN       A       18.66.17.166
```
```
mitmdump --allow-hosts "18.66.17.*" ...
```

**Comment by Bart274** [comment]
That didn't work for me, I added the listed ip's (the one dig said on my server) and when I load mitm.it now, it still says the traffic isn't routed through mitmproxy
