### ISSUE TITLE
Installation fails without coherent output on a system with python3 as default.

### ISSUE THREAD

**Issue by fake-name** [mitmproxy/mitmproxy#556]
Installing on Ubuntu 14.04, where `pip` links to `pip3`, and `python` to `python3`, the install process (e.g. running `./dev`) fails in a rather ugly manner.

Furthermore, the setup leaves a big mess when it fails, particularly if you don't have `virtualenv` installed already - The command to `virtualenv` fails, but because the script doesn't `set -e` (exit on first error), it continues and then wound up trying to install a whole pile of crap into my *system* python.

It'd probably be a good idea to preferentially use `python2` over `python`, since mitmproxy doesn't support `python3`, and you don't *really* know *what* `python` is actually pointing at.

Anyways:

`./dev` needs `set -e` somewhere.  
`python` shouldn't be assumed to be an alias for `python2`, particularly going forwards.

Python 3 support would be nice, but 2 will be around for a while.

**Comment by elitest** [comment]
I have a fully patched install of Ubuntu 14.04 and python still refers to Python 2.7:
```BASH
$ ll /usr/bin/ | grep python
****
lrwxrwxrwx  1 root root          9 Apr 11 08:44 python -> python2.7*
****
```

```BASH
pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```
I installed pip via "apt-get install python-pip", and DID NOT update it using pip's self updating capabilities, as I find that that tends to break pip.

Doesn't pip on Ubuntu require root privileges to clobber stuff on your system's python?

**Comment by mhils** [comment]
@fake-name is right - if virtualenv isn't installed, `pip` may still refer to the OS-level pip installation. I just commited a fix for this - thanks for the report and sorry for the inconveniences!

**Comment by fake-name** [comment]
@elitest - I pretty much never use the apt-get libraries for anything, I install pip from source, and I think that's why pip -> pip3. I have found the ubuntu python repo packages to be consistently miserably out of date.

Not sure how my python wound up pointing to python 3.4, that might have been me just making bad decisions.

Also, I didn't say it /succeeded/ in clobbering anything, just that it *tried*.

**Comment by mhils** [comment]
@fake-name,
assuming that the venv got activated properly (we'd exit otherwise now), `which pip` should always point to the virtualenv's pip.

**Comment by fake-name** [comment]
@mhils - Good to know. I haven't use venv stuff enough to really have any idea what behaviour can be relied on.
