### ISSUE TITLE
Cannot change web port

### ISSUE THREAD

**Issue by loranger** [mitmproxy/mitmproxy#5571]
#### Problem Description
I have a traefik running on port 8080 (and need to keep it running while I debug my app) and mitm failed to start.
I try to change the web port but failed too

#### Steps to reproduce the behavior:

```shell
$ mitmproxy
Error on startup: [Errno 48] error while attempting to bind on address ('::', 8080, 0, 0): address already in use
``` 

```shell
$ mitmweb --web-port 8081
Web server listening at http://127.0.0.1:8081/
[Errno 48] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
```

#### System Information
```shell
$ mitmweb --version
Mitmproxy: 8.1.1
Python:    3.10.6
OpenSSL:   OpenSSL 1.1.1q  5 Jul 2022
Platform:  macOS-12.5.1-arm64-arm-64bit
```

**Comment by mhils** [comment]
mitmproxy's HTTP proxy server listens on 8080 by default, so you need to change that option (and not the web interface port):
```
mitmproxy -p 8082
```

**Comment by loranger** [comment]
I sse, thanks
