### ISSUE TITLE
Trusted CAs

### ISSUE THREAD

**Issue by duese22** [mitmproxy/mitmproxy#558]
Hi,

by default mitmproxy trusts every given CA.
I use mitmproxy on a debian based router (as TLS-proxy). Is it possible to limit the trusted CAs to the given cert store in Debian?

Thank you for your great software!

**Comment by mhils** [comment]
Hi @duese22,

this is currently not supported. If you want to give it a try, we'd be happy to accept a pull request that optionally enables upstream certificate verification. The relevant parts of the code are [netlib.tcp](https://github.com/mitmproxy/netlib/blob/c53d89fd7fad6c46458ab3d0140528e344de605f/netlib/tcp.py#L481-L490) and [libmproxy.proxy.server](https://github.com/mitmproxy/mitmproxy/blob/7abaf3c3626a68a23233c3dc759ade32068f0462/libmproxy/proxy/server.py#L187-L193).

**Comment by mhils** [comment]
fixed by #69
