### ISSUE TITLE
Parse HTTP request/response from text files

### ISSUE THREAD

**Issue by Semyazz** [mitmproxy/mitmproxy#559]
Can I, using **libmproxy**, to load HTTP request from a text file, optionally same for the response and then process them as normal objects in mitmproxy world (modify headers/params, add cookies etc)?

I want to load a sitemap/requests from Burp to mitmproxy and then reply the whole conversation with additional stuff done by scripts. It's easy to dump stuff from Burp using a built-in export (output format is XML) or via custom few-lines of code plugin to dump everything directly to text files.

but I don't know how to parse those in mitmproxy

**Comment by mhils** [comment]
You could use `libmproxy.protocol.http.HTTPRequest.from_stream` to read request objects from a file. There are a couple of ways how you can get that into mitmproxy - either write a conversion script using a `libmproxy.flow.FlowWriter` or load them in an inline script on startup.

It will be way more easier to just record your flows with mitmproxy. You can use upstream mode and put mitmproxy in front of Burp or capture with mitmproxy and then create Burp files with mitmproxy's client replay.

Cheers,
Max
