### ISSUE TITLE
502 Bad Gateway - Certificate verify failed: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by gabrieldenoni** [mitmproxy/mitmproxy#5601]
#### Problem Description
I've started using MITMProxy recently and it's been amazing, MITM is extremely powerful and easily extensible 👏

However I'm having a problem using it in my work mac, all requests fail returning `502 Bad Gateway - Certificate verify failed: self-signed certificate in certificate chain`. If I turn off the corporate VPN, everything start working. 

At first, I thought it was a problem with how this VPN handles traffic, however testing with other proxy services, they keep working even when the VPN is active, even though they also use self-signed certificates.

I've tried to generate a custom certificate with `openssl` that mimics the root certificate that works and then provide it to MITM, but it also failed. I don't have deep knowledge in the subject, however what've concluded is that probably the issue is in how MITM generates the leaf(dummy certificates), perhaps some fields are missing. Does it make sense?

I've cloned the repo and modified [certs.py](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/certs.py) to see if I could make MITM generate dummy certificates with the additional fields, but due to my lack of knowledge about x509 I was not able to do it.

I've included below the fields that differ between the leaf certificate that works vs. the one that does not. If y'll have any idea of why the problem might be happening I'd be glad to hear back from you

**Certificate that works(Proxyman)**
```
www.google.com
    Certificate:
        - Issuer: OU, CN, O, L, C
        - Subject: ST, CN, O, L, C
        - Extension:
            - Certificate Key Usage: Not Critical, Signing, Non-repudiation, Key Encipherment, Data Encipherment
            - Certificate Authority Key ID: Not Critical
            - Certificate Basic Constraints: Critical, "Is not a Certification Authority"
            - Extended Key Usage: Not Critical, TLS WWW Server Authentication, TLS WWW Client Authentication
            - Certificate Subject Key ID: Not Critical, Key ID ...
            - Netscape Certificate Comment: Not Critical, ...
            - Certificate Subject Alternative Name: Not Critical, DNS Name: www.google.com
```

**MITMProxy Standard Certificate**
```
www.google.com
    Certificate:
        - Issuer: O=mitmproxy, CN=mitmproxy
        - Subject: CN=www.google.com
        - Extension:
            - Extended Key Usage: Not Critical, TLS WWW Server Authentication
            - Certificate Subject Alternative Name: Not Critical, DNS Name: www.google.com
```

#### System Information
Mitmproxy: 8.1.1
Python:    3.10.6
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  macOS-11.6-x86_64-i386-64bit

**Comment by mhils** [comment]
> However I'm having a problem using it in my work mac, all requests fail returning `502 Bad Gateway - Certificate verify failed: self-signed certificate in certificate chain`. If I turn off the corporate VPN, everything start working.

Can you clarify where exactly you are getting this error message? Does running `mitmproxy --ssl-insecure` change anything?

**Comment by gabrieldenoni** [comment]
Hey @mhils. You just solved my problem 😀.

Added the `--ssl-insecure` flag and now everything works like a charm!

MITMProxy is a fantastic tool btw, thanks a lot for the work that y'll been doing
Have a nice weekend 🚀
