### ISSUE TITLE
Add option to send certificate chain when intercepting HTTPS

### ISSUE THREAD

**Issue by weiyin** [mitmproxy/mitmproxy#5618]
#### Problem Description

We use mitmproxy in a "CA-like" way, where we keep the private key for the trusted root certificate offline. Instead, we have mitmproxy use an intermediate certificate + private key to do the SSL interception, which is what we put into `mitmproxy-ca.pem`.

This worked well in older versions of mitmproxy. The problem is that new versions of mitmproxy (I believe since v7) does not send the certificate in `mitmproxy-ca.pem` unless there are two: the root and the intermediate. In our use case, certificate validation fails because our clients are only getting the leaf cert from mitmproxy; there is nothing to link the root cert with the leaf cert.

#### Proposal
Add an option to send the certificate in `mitmproxy-ca.pem` with the leaf (dummy) certs.

#### Alternatives
We could add the root cert and key into `mitmproxy-ca.pem`, but would like to avoid it if possible.

**Comment by spencerwp** [comment]
You only need to add the root cert to `mitmproxy-ca.pem`, and not the key, to form the chain.

The `from_files` class method of certs.py looks for multiple certificate entries, and only sets (and tlsconfig.py uses) `chain_file` of the entry if there are multiple certificates found in the file.

**Comment by kghost** [comment]
I have managed to achieve this using following `mitmproxy-ca.pem` file

```
-----BEGIN RSA PRIVATE KEY-----
private key of intermediate CA
-----END RSA PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
cert of intermediate CA
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----                                                                                                                                                                                                                                                              
cert of root CA
-----END CERTIFICATE-----
```

**Comment by weiyin** [comment]
Thanks @spencerwp and @kghost, your suggestions worked for me. I still don't think that the root cert should be necessary, but this works for me now as is.
