### ISSUE TITLE
TLS handshake fails for apple.com

### ISSUE THREAD

**Issue by nibe** [mitmproxy/mitmproxy#5624]
#### Problem Description
When I visit apple.com, no traffic is logged and the following error appears. On any other website I tried mitmproxy works fine.

```
192.168.178.38:59384: client connect
192.168.178.38:59384: server connect www.apple.com:443 ([::1]:10011)
192.168.178.38:59384: Client TLS handshake failed. The client disconnected during the handshake. If this happens consistently for www.apple.com, this may indicate that the client does not trust the proxy's certificate.
192.168.178.38:59384: client disconnect
```

#### Steps to reproduce the behavior:
1. Enable `mitmproxy`
2. Visit apple.com
3. Client TLS handshake failed

#### System Information
```
Mitmproxy: 8.1.1
Python:    3.10.6
OpenSSL:   OpenSSL 1.1.1q  5 Jul 2022
Platform:  macOS-12.5-x86_64-i386-64bit
```

**Comment by Prinzhorn** [comment]
What browser are you using? It works for me with Ubuntu + Chromium

![image](https://user-images.githubusercontent.com/679144/193522795-8ea7bd82-2d2a-4158-a79a-4e57a438cf5a.png)

**Comment by nibe** [comment]
I am using Safari. It also does not work in my own app that uses [URLSession](https://developer.apple.com/documentation/foundation/urlsession) and has no certificate pinning added by me. Perhaps I have to override the default clientside certificate verification?

I believe I tried it in Firefox too before opening this issue and it did not work but now I can open apple.com in Firefox and the traffic is logged.

**Comment by Prinzhorn** [comment]
It's realistic that Safari and iOS apps (or more generally Apple products) pin apple.com, maybe you can find some information on that? If that's the case, then this doesn't look like a mitmproxy issue.

**Comment by nibe** [comment]
I added a `URLSessionDelegate` to my `URLSession` that accepts any certificate and now I can see the traffic of my own app in mitmproxy.
