### ISSUE TITLE
mitmdump does not support some website using https(ssl v3)?

### ISSUE THREAD

**Issue by leveryd** [mitmproxy/mitmproxy#563]
http://bbs.uc.cn,i can not login using mitmdump as a forward proxy.

**Comment by mhils** [comment]
Hi there,

I can visit http://bbs.uc.cn just fine using mitmproxy/mitmdump. If you still have issues, please provide more details (e.g. check out our bug report template: [CONTRIBUTING.md](https://github.com/mitmproxy/mitmproxy/blob/master/CONTRIBUTING.md#bug-reports)).

Cheers,
Max
