### ISSUE TITLE
mitmdump does not support some website using https(ssl v3)?

### ISSUE THREAD

**Issue by leveryd** [mitmproxy/mitmproxy#564]
http://bbs.uc.cn,i can not login in this website using mitmdump as forward proxy.
if you want to login,you can try my account for test.
username:*redacted*
password:*redacted*

**Comment by mhils** [comment]
Hi there,

I can perfectly log into this site using the latest version of mitmdump/mitmproxy (0.11.3) in regular mode. We do not have a forward proxy mode for a while anymore.  Check out http://mitmproxy.org/doc/modes.html for each mode and please reply to this ticket and do not open a new one every time.

Thanks,
Max

**Comment by leveryd** [comment]
Hi
i have install mitmdump(0.11.3) on ubuntu 14.04.
but i still can not login the site.
i run "mitmpdump" directly,so it shoud run in regular mode by default?
can you login in github.com using mitmdump?

**Comment by mhils** [comment]
> i run "mitmpdump" directly,so it shoud run in regular mode by default?

yes.

> can you login in github.com using mitmdump?

yes.
