### ISSUE TITLE
FreeBSD11 transparent mode not supported

### ISSUE THREAD

**Issue by mike-pt** [mitmproxy/mitmproxy#566]
I'm trying to use transparent mode on freebsd, but it doesn't seem supported:

```
# mitmproxy -T
usage: mitmproxy [options]
mitmproxy: error: Transparent mode not supported on this platform.
```

I wonder if its just because its not considered in libmproxy "platform", since OSX is supported, and maybe its easy to add FreeBSD support, or is it something more complex?

**Comment by mhils** [comment]
Which versions of FreeBSD are you running?
As far as I know, we do support FreeBSD 10 with the OSX module: See [libmproxy/platform/\_\_init\_\_.py](https://github.com/mitmproxy/mitmproxy/blob/1c5277b21fd283a3b58d145c5090f59d657b594d/libmproxy/platform/__init__.py#L11)

**Comment by mike-pt** [comment]
seems that the port version is outdated...

I'm using freebsd11 though so I changed it to:
elif sys.platform.startswith("freebsd"):

works fine now, only having problems with DNS (posted on an already opened issue).

Feel free to close this one

**Comment by mhils** [comment]
Just to verify: You set mitmproxy as the gateway, not as the target device? (see http://mitmproxy.org/doc/modes.html )

**Comment by mike-pt** [comment]
As refereed in #255 I get the "Transparent mode failure: could not resolve original destination" with any dns server, local or remote...

And yes FreeBSD is the gateway, and pf redirects 80,443 and 8443 to port 8080 (where mitmproxy is running)

**Comment by mhils** [comment]
mike-pt: Can you get on IRC? That would shorten the rundtrips significantly.
#mitmproxy on OFTC (irc://irc.oftc.net:6667).

**Comment by mike-pt** [comment]
not right now, but certainly later in the day :) 

I'm have to go out in 5mins and will only be on the smartphone (I do have remote access to the machine, If anything needs testing)

**Comment by mhils** [comment]
Ok, I'll probably be away later, so here for reference:

if your transparent setup is fine otherwise, I'd suspect there's an issue with `pf` on FreeBSD11 then (changed output format, ..whatever). You'd need to debug that yourself then, best by using mitmdump and well-placed print statements in [osx.py](https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/platform/osx.py) and [pf.py](https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/platform/pf.py).

Cheers,
Max

**Comment by mike-pt** [comment]
I was actually looking into pf.py just before I left, I'll look into it later and see what could be the issue.

pf version in freebsd is not really in sync with openbsd and neither is osx, so that might indeed be the issue.

I will keep you updated with any findings, tks

**Comment by mike-pt** [comment]
So I added a print line to get the output of "stxt"

```
      try:
            stxt = subprocess.check_output(self.STATECMD, stderr=subprocess.STDOUT)
            print stxt
```

It seems to be working since I get the output of the pf states table.

In any case before any further debugging I'll see if I can get the port in sync with the latest github version.

**Comment by mike-pt** [comment]
Ok all updated... a but more debugging...

I explicitly printed out "print self.resolver.original_addr(client_conn.connection)" which lead me to this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 73, in handle
    upstream_info = self.config.mode.get_upstream_server(self.client_conn)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/primitives.py", line 62, in get_upstream_server
    print self.resolver.original_addr(client_conn.connection)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/platform/osx.py", line 26, in original_addr
    return pf.lookup(peer[0], peer[1], stxt)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/platform/pf.py", line 26, in lookup
    raise RuntimeError("Could not resolve original destination.")
RuntimeError: Could not resolve original destination.
```

So clearly the issue is in the way it in the result of pf.lookup

The output of the "s" var is this:

all tcp 127.0.0.1:8080 (216.58.208.14:80) <- 10.10.50.172:34722       CLOSED:SYN_SENT
all tcp 127.0.0.1:8080 (176.32.99.28:80) <- 10.10.50.172:60734       FIN_WAIT_2:FIN_WAIT_2
all tcp 127.0.0.1:8080 (216.58.208.14:80) <- 10.10.50.172:54796       FIN_WAIT_2:ESTABLISHED
all tcp 127.0.0.1:8080 (216.58.208.14:80) <- 10.10.50.172:56553       FIN_WAIT_2:ESTABLISHED
all tcp 127.0.0.1:8080 (216.58.208.14:80) <- 10.10.50.172:51711       FIN_WAIT_2:ESTABLISHED
all tcp 127.0.0.1:8080 (216.58.208.14:80) <- 10.10.50.172:58336       FIN_WAIT_2:ESTABLISHED
all tcp 127.0.0.1:8080 (72.21.202.53:80) <- 10.10.50.172:48088       FIN_WAIT_2:FIN_WAIT_2
all tcp 127.0.0.1:8080 (216.58.208.14:80) <- 10.10.50.172:42529       FIN_WAIT_2:ESTABLISHED
all tcp 127.0.0.1:8080 (216.58.208.14:80) <- 10.10.50.172:33929       CLOSED:SYN_SENT
all tcp 127.0.0.1:8080 (176.32.99.28:80) <- 10.10.50.172:60733       ESTABLISHED:ESTABLISHED


Is this the expected output?

**Comment by mike-pt** [comment]
ah wait...

```
          if len(s) > 4:
                if sys.platform == "freebsd10":
                    # strip parentheses for FreeBSD pfctl
                    s = s[3][1:-1].split(":")
```

startswith("freebsd") fixed it :)

**Comment by mhils** [comment]
Excellent, thanks for digging in. Could you please send a PR with your
changes?

Cheers,
Max

Mike <notifications@github.com> schrieb am Fr., 24. Apr. 2015 03:15:

**Comment by mike-pt** [comment]
I cloned the repo yesterday, I'll send a PR in a few mins.

**Comment by mhils** [comment]
Just to be sure, we have not received a PR yet. :wink:

**Comment by mike-pt** [comment]
sorry I forgot to create the PR, just did it now :P
