### ISSUE TITLE
Incorrect docstring in consoleaddons

### ISSUE THREAD

**Issue by Zakyntha** [mitmproxy/mitmproxy#5671]
Inside mitmproxy/tools/console/consoleaddons.py line 311 you can see the following function:

```py
@command.command("console.view.eventlog")
def view_eventlog(self) -> None:
    """View the options editor."""
    self.master.switch_view("eventlog")
```

That is incorrect since the options editor is not related to the eventlog and are two seperate things. To fix that the docstring only has to be changed to this new docstring:
```py
@command.command("console.view.eventlog")
def view_eventlog(self) -> None:
    """View the event log."""
    self.master.switch_view("eventlog")
```

**Comment by mhils** [comment]
Thanks for catching this! Could you please open a pull request for this?
You should be able to do this right from the web interface. :)
