### ISSUE TITLE
CPU ramps up to 100% when using a search filter on mitmweb

### ISSUE THREAD

**Issue by BeeFox-sys** [mitmproxy/mitmproxy#5692]
#### Problem Description
When capturing while a filter is placed on the mitmweb interface, cpu ramps up and errors fill the console

#### Steps to reproduce the behavior:
1. start mitmweb
2. capture a loading, with a search paramater to filter the captured events
3. cpu ramps up to 95%, console fills with error
```
Uncaught DOMException: The operation is insecure. app.js:209
    updateUrlFromStore http://127.0.0.1:8081/static/app.js:209
    initialize http://127.0.0.1:8081/static/app.js:209
    c http://127.0.0.1:8081/static/vendor.js:182
    createThunkMiddleware http://127.0.0.1:8081/static/vendor.js:239
    [1]</< http://127.0.0.1:8081/static/app.js:2
```

#### System Information
```
itmproxy: 6.0.2
Python:    3.10.8
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  Linux-6.0.0-2-amd64-x86_64-with-glibc2.35
```

**Comment by BeeFox-sys** [comment]
[WithSearch-profile.json.gz](https://github.com/mitmproxy/mitmproxy/files/9894225/WithSearch-profile.json.gz)
[WithoutSearch-profile.json.gz](https://github.com/mitmproxy/mitmproxy/files/9894226/WithoutSearch-profile.json.gz)

Here are two firefox profiler profiles, one recorded while the search field was full, the other while it was empty.

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again? If the issue persists, can you reproduce it with Chromium-based browsers as well? We definitely intend to support Firefox equally, but this info helps with narrowing it down.

**Comment by BeeFox-sys** [comment]
huh i had just installed it, I'll do an update maybe i got unlucky and installed right before it updated, else the debian unstable package is outdated

**Comment by BeeFox-sys** [comment]
yep debian unstable's version is outdated

**Comment by BeeFox-sys** [comment]
Seems to be fixed in latest version! real issue seems that mitmproxy in deb bookworm is quite outdated
