### ISSUE TITLE
Excessive CPU consumption in WireGuard mode

### ISSUE THREAD

**Issue by dur-randir** [mitmproxy/mitmproxy#5694]
#### Problem Description
Mitmproxy uses 100% cpu even under light-to-moderate network activity with packets being dropped. This is a common picture
```
6568 root 20 0 7357216 3.2g 20072 R 109.6 1.3 6:10.60 mitmweb
```
#### Steps to reproduce the behavior:
1. mitmweb --mode wireguard --web-host 10.x.x.x
2. Set up mobile client with com.wireguard.android
3. Enable always-on vpn + block connections without vpn
4. Reboot phone to record it's activity from the start

#### System Information
Mitmproxy: 9.0.0
Python:    3.9.2
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  Linux-5.10.0-18-amd64-x86_64-with-glibc2.31

**Comment by mhils** [comment]
Thanks for the feedback! I was able to reproduce the "Dropping incoming packet" errors with heavy full-hd streaming. That's not quite what you described, but at least we have a repro. I've spent a bit of time looking into this now and came up with some fixes in https://github.com/decathorpe/mitmproxy_wireguard/pull/20, which should mitigate this. We should be able to get a patch release out quickly. :)

**Comment by dur-randir** [comment]
In order to check it earlier, I've tried to install it with
```
pip3 install git+https://github.com/decathorpe/mitmproxy_wireguard.git@refs/pull/20/merge
```
but it fails inside cargo with
```
   ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpydgfm_tr_in_process.py prepare_metadata_for_build_wheel /tmp/tmph8g1ditn
         cwd: /tmp/pip-req-build-lgpz_8l5
    Complete output (14 lines):
    💥 maturin failed
      Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
      Caused by: `cargo metadata` exited with an error: error: failed to select a version for `console-api`.
        ... required by package `console-subscriber v0.1.8`
        ... which satisfies dependency `console-subscriber = "=0.1.8"` of package `mitmproxy_wireguard v0.1.15 (/tmp/pip-req-build-lgpz_8l5)`
    versions that meet the requirements `=0.4.0` are: 0.4.0

    the package `console-subscriber` depends on `console-api`, with features: `tonic-build` but `console-api` does not have these features.


    failed to select a version for `console-api` which could resolve this conflict
    Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-7ngktbbv', '--interpreter', '/usr/bin/python3']' returned non-zero exit status 1.
```
toolchain info is
```
cargo --version
cargo 1.56.0
rustc --version
rustc 1.61.0
```
is there any simple fix, or should I just wait for a pip binary release, and test just it?

**Comment by mhils** [comment]
Hm, the command you posted works out of the box for me:
```
$ cargo --version
cargo 1.64.0 (387270bc7 2022-09-16)
(venv) ~/g/mitmproxy
$ rustc --version
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

**Comment by mhils** [comment]
Seems like you are hitting this: https://github.com/tokio-rs/console/issues/348

**Comment by dur-randir** [comment]
Maybe :) I've installed 1.64 from the ground up and it compiled all deps successfully. Testing now.

**Comment by dur-randir** [comment]
Works like magic :) No drops at all, though I was able to push CPU consumption up to 60%, it wasn't noticeable in the application. Even twitch streams smoothly.

**Comment by mhils** [comment]
Wonderful. Thank you again for the initial report and for testing the PR! 🍰

**Comment by Prinzhorn** [comment]
Released :partying_face:
