### ISSUE TITLE
Server TLS handshake failed. connection closed

### ISSUE THREAD

**Issue by liuwei000000** [mitmproxy/mitmproxy#5705]
#### Problem Description

in windows， it run ok ， default config
but in linux ，error：
 “Server TLS handshake failed. connection closed
Unable to establish TLS connection with server (connection closed). Trying to establish TLS with client anyway.
 server disconnect xxx.com:443 (xxx:443)”

#### System Information
Paste the output of "mitmproxy --version" here.
windows
Mitmproxy: 8.1.1 binary
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Windows-10-10.0.19044-SP0

linux
Mitmproxy: 8.1.1 binary
Python:    3.10.5
OpenSSL:   OpenSSL 3.0.3 3 May 2022
Platform:  Linux-4.18.0-372.19.1.an8_6.x86_64-x86_64-with-glibc2.28

**Comment by liuwei000000** [comment]
only this info：
......
: Server TLS handshake failed. connection closed
: Unable to establish TLS connection with server (connection closed). Trying to establish TLS with client anyway.
: server disconnect cq.tgovcloud.com:443 (134.175.76.79:443)
.....
I modify config.yaml, but fail ,noly print above info
I can't know how to config to print more info

by the way mitmproxy 9.0.0, 
"[26716] Error loading Python lib '/tmp/_MEIMtyIby/libpython3.11.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIMtyIby/libpython3.11.so.1.0)"
my glibc is 2.28

**Comment by Prinzhorn** [comment]
> I can't know how to config to print more info

`mitmproxy --set proxy_debug -vvv`

And then preferably make a single request that fails (to reduce noise).

**Comment by liuwei000000** [comment]
new report：
1. I use mitmproxy 9.0.0  by pip install
2. new test：local curl is ok，only iphone（iOS 15.1) is error， other window machine is ok
3. the error in python pdb trace：
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/tools/main.py(150)mitmweb()
-> run(web.master.WebMaster, cmdline.mitmweb, args)
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/tools/main.py(120)run()
-> return asyncio.run(main())
  /usr/lib64/python3.9/asyncio/runners.py(44)run()
-> return loop.run_until_complete(main)
  /usr/lib64/python3.9/asyncio/base_events.py(629)run_until_complete()
-> self.run_forever()
  /usr/lib64/python3.9/asyncio/base_events.py(596)run_forever()
-> self._run_once()
  /usr/lib64/python3.9/asyncio/base_events.py(1890)_run_once()
-> handle._run()
  /usr/lib64/python3.9/asyncio/events.py(80)_run()
-> self._context.run(self._callback, *self._args)
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/server.py(285)handle_connection()
-> self.server_event(events.ConnectionClosed(connection))
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/server.py(344)server_event()
-> for command in layer_commands:
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layer.py(144)handle_event()
-> command = command_generator.send(send)
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layer.py(257)handle_event()
-> yield from self._handle(event)
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layer.py(144)handle_event()
-> command = command_generator.send(send)
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py(896)_handle_event()
-> yield from self.event_to_child(handler, event)
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py(905)event_to_child()
-> for command in child.handle_event(event):
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layer.py(144)handle_event()
-> command = command_generator.send(send)
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layers/http/__init__.py(749)passthrough()
-> for command in self.child_layer.handle_event(event):
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layer.py(144)handle_event()
-> command = command_generator.send(send)
  /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/tunnel.py(88)_handle_event()
-> yield from self.on_handshake_error(err)
> /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layers/tls.py(496)on_handshake_error()
-> yield commands.Log(f"Server TLS handshake failed. {err}", level=WARNING)

**Comment by liuwei000000** [comment]
I add code in proxy/tunnel.py
 51     def _handle_event(self, event: events.Event) -> layer.CommandGenerator[None]:
 52         print(self)
 53         print(event)

then the logs are:

[17:16:59.883][113.204.21.218:49542] client connect
[17:16:59.901][113.204.21.218:49536] server connect xx.xxx.com:443 (134.175.76.79:443)
ServerTLSLayer(inactive None None)
Start({})
ClientTLSLayer(inactive None None)
Start({})
ServerTLSLayer(closed None None)
DataReceived(client, b"\x16\x03.....\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
ClientTLSLayer(establishing None None)
DataReceived(client, b"\x16\x03\....\x00")
ServerTLSLayer(closed None None)
Reply(TlsClienthelloHook(data=ClientHelloData(context=Context(
  Client({'id': '…ff55bc', 'peername': ('113.204.21.218', 49536), 'sockname': ('172.26.151.155', 8888), 'timestamp_start': 1667380619.8048112, 'state': <ConnectionState.OPEN: 3>, 'transport_protocol': 'tcp', 'proxy_mode': ProxyMode.parse('regular'), 'tls': True, 'sni': 'xx.xxx.com', 'alpn_offers': [b'h2', b'http/1.1']}),
  Server({'id': '…141ef2', 'address': ('xx.xxx.com', 443), 'state': <ConnectionState.OPEN: 3>, 'transport_protocol': 'tcp', 'sockname': ('172.26.151.155', 36018), 'timestamp_start': 1667380619.8090045, 'timestamp_tcp_setup': 1667380619.9014752, 'peername': ('134.175.76.79', 443), 'tls': True}),
  layers=[[HttpProxy(state: handle_event), HttpLayer(regular, conns: 2), HttpStream(id=1, passthrough), ServerTLSLayer(closed None None), ClientTLSLayer(establishing xx.xxx.com None)]]
), client_hello=ClientHello(sni: xx.xxx.com, alpn_protocols: [b'h2', b'http/1.1']), ignore_connection=False, establish_server_tls_first=True)), None)
ServerTLSLayer(establishing xx.xxx.com None)
ConnectionClosed(connection=Client({'id': '…ff55bc', 'peername': ('113.204.21.218', 49536), 'sockname': ('172.26.151.155', 8888), 'timestamp_start': 1667380619.8048112, 'state': <ConnectionState.CAN_WRITE: 2>, 'transport_protocol': 'tcp', 'proxy_mode': ProxyMode.parse('regular'), 'tls': True, 'sni': 'xx.xxx.com', 'alpn_offers': [b'h2', b'http/1.1']}))
[17:16:59.995][113.204.21.218:49542] server connect xx.xxx.com:443 (134.175.76.79:443)
ServerTLSLayer(establishing xx.xxx.com None)
DataReceived(server, b'\x16\x03....\x00\x00')
[17:17:00.040][113.204.21.218:49536] client disconnect
ServerTLSLayer(inactive None None)
Start({})
ClientTLSLayer(inactive None None)
Start({})
ServerTLSLayer(closed None None)
DataReceived(client, b'\x16\x03\....x00\x00')
ClientTLSLayer(establishing None None)
DataReceived(client, b'\x16\x03\....x00\x00')
ServerTLSLayer(establishing xx.xxx.com None)
ConnectionClosed(connection=Server({'id': '…141ef2', 'address': ('xx.xxx.com', 443), 'state': <ConnectionState.CLOSED: 0>, 'transport_protocol': 'tcp', 'sockname': ('172.26.151.155', 36018), 'timestamp_start': 1667380619.8090045, 'timestamp_tcp_setup': 1667380619.9014752, 'peername': ('134.175.76.79', 443), 'tls': True, 'sni': 'xx.xxx.com', 'alpn_offers': (b'h2', b'http/1.1')}))
> /root/mitm/lib64/python3.9/site-packages/mitmproxy/proxy/layers/tls.py(496)on_handshake_error()
-> yield commands.Log(f"Server TLS handshake failed. {err}", level=WARNING)

**Comment by mhils** [comment]
There are a bunch of unrelated issues interleaved in this thread and I'm not sure what's still current. Please open a new issue if this is still a problem.
