### ISSUE TITLE
Some request are not getting through

### ISSUE THREAD

**Issue by albin900** [mitmproxy/mitmproxy#571]
I have this script:

```python
from libmproxy.protocol.http import decoded
import pprint
import time

def response(context, flow):
    print('Path: ' + flow.request.path)
```

And im connected to the proxy with my android phone and using snapchat.
But some requests getting through...
Are the requests too big? They are 60-100kb.

![](http://i.gyazo.com/cd8bf715ecf9c3705b576c156ccd0080.png)

**Comment by mhils** [comment]
Hi there,

not sure what your issue is. FWIW, you should probably `context.log` and the inspect the eventlog (press `e`) or run mitmdump so that the console does not get in the way.

Cheers,
Max

**Comment by albin900** [comment]
@mhils Oh, thanks there is some errors there.

**Comment by albin900** [comment]
@mhils Is there any documentation for creating my own scripts?

**Comment by mhils** [comment]
https://mitmproxy.org/doc/scripting/inlinescripts.html
