### ISSUE TITLE
Mitm.it DOWN

### ISSUE THREAD

**Issue by MauricioRojasCareers** [mitmproxy/mitmproxy#5726]
#### Problem Description

Trying to install certificates on iOS, but when you go to http://mitm.it/ it returns: "If you can see this, traffic is not passing through mitmproxy." 

:(

#### Steps to reproduce the behavior:
1. Go to http://mitm.it/
2. 
3. 

#### System Information
Paste the output of "mitmproxy --version" here.

If you can see this, traffic is not passing through mitmproxy.

**Comment by mhils** [comment]
As the error message says: You have not configured your client correctly, the traffic is not passing through mitmproxy.
