### ISSUE TITLE
SyntaxError when running mitmproxy

### ISSUE THREAD

**Issue by nandaceg007** [mitmproxy/mitmproxy#573]
I get this error when running mitmproxy.
Not sure of what's wrong.
```
abc@abc-virtual-machine ~ $ mitmproxy
Traceback (most recent call last):
  File "/usr/local/bin/mitmproxy", line 2, in <module>
    from libmproxy.main import mitmproxy
  File "/usr/local/lib/python3.4/dist-packages/libmproxy/main.py", line 73
    except ProxyServerError, v:
                           ^
SyntaxError: invalid syntax
```

**Comment by mhils** [comment]
Hi there,

Please use Python 2.7 to run mitmproxy.

Cheers,
Max

Nanda Kumar <notifications@github.com> schrieb am Mi., 6. Mai 2015 17:33:

**Comment by nandaceg007** [comment]
Thanks Max. But I already seem to be using python 2.7.6 as my default.
```
abc@abc-virtual-machine ~ $ python --version
Python 2.7.6
```
Am I missing something else ?

**Comment by nandaceg007** [comment]
I installed mitmproxy using pip-2.7 and used 
```
> python2.7 /usr/local/bin/mitmproxy 
```
to run mitmproxy. I got it running. 

Thanks.
