### ISSUE TITLE
Windows Smart Screen "Unknown Publisher" notice

### ISSUE THREAD

**Issue by jparta** [mitmproxy/mitmproxy#5742]
#### Problem Description
When installing mitmprox by running the Windows installer downloaded from https://mitmproxy.org/, I got a warning about this software originating from an unknown source, an "unknown publisher". Is this expected? Is the package not signed?

#### Steps to reproduce the behavior:
1. Download installer
2. Run installer

#### System Information
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Windows-10-10.0.19044-SP0

**Comment by mhils** [comment]
The standalone installer is currently not signed, only the Microsoft Store version is (by Microsoft).

**Comment by jparta** [comment]
Okay. I'll close this. I think it's a good matter to document here.
