### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by maitouqwq** [mitmproxy/mitmproxy#5745]
error establishing server connection: [WinError 121] 信号灯超时时间已到
127.0.0.1:53792: CONNECT www.google.com:443
              << 502 Bad Gateway 80b
Traceback (most recent call last):

  File "asyncio\events.py", line 80, in _run

  File "asyncio\proactor_events.py", line 162, in _call_connection_lost

ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues

**Comment by mhils** [comment]
We need more details on how to reproduce this issue.
