### ISSUE TITLE
How to make SSL work *without* inline scripts?

### ISSUE THREAD

**Issue by cppisking** [mitmproxy/mitmproxy#575]
I tried the most basic example posted on mitmproxy.org: http://mitmproxy.org/doc/scripting/libmproxy.html of the sticky master.

Using this example and visiting mitmproxy.it it says that if you can see the message, the traffic is not passing through mitmproxy.  Obviously the traffic is passing through the proxy because otherwise no website would work at all.  But http websites work fine, just not https.  So there must be some additional magic happening in the inline scripts that make this all work.  I confirmed with a separate test program that if I use the `from libmproxy import mitmdump` followed by `mitmdump()` then browsing to mitmproxy.it does in fact show me the cert to download.  But I need to make this work without the inline scripts.  

Am I doing something wrong, or is this a bug in the library?

**Comment by mhils** [comment]
Using libmproxy directly is different from using inline scripts - you just get the proxy core without any of the mitmdump/mitmproxy features. In particular, you don't get the web app by default. Three ways to fix this:

1. Install the certificate manually (it is located in `~/.mitmproxy` by default)
2. Add the onboarding app to your libmproxy setup (read the source)
3. Write an actual inline script instead of interfacing libmproxy (read the docs)

**Comment by cppisking** [comment]
I can run two different apps on the same machine (one using libmproxy and one using mitmproxy) and the mitmproxy one works but the libmproxy one doesn't.  Since it works through mitmproxy, this suggests that the certificate is already installed.  My understanding (which could certainly be wrong) is that there is one certificate per installation of libmproxy/mitmproxy.  If that is the case, then mitmproxy working should imply that libmproxy shoudl also work.

Am I understanding incorrectly?

**Comment by mhils** [comment]
If you do not specify a custom certificate, mitmproxy (and libmproxy) will use the cert stored in `~/.mitmproxy`

**Comment by cppisking** [comment]
So if that's the case, then it suggests both of my apps -- the one using libmproxy and the one using mitmproxy -- were both using the same certificate, and only the mitmproxy one was working.  I will test again later and report back if this is correct.  Because based on what you're saying it sounds like both should be using the same certificate, and if one works the other should also work.

I *think* this is not what I experienced (one worked but not the other) but I will confirm.
