### ISSUE TITLE
How to intercept specific domain?

### ISSUE THREAD

**Issue by ryanzzff** [mitmproxy/mitmproxy#578]
I know I can filter the domain, or ignore other domain by:
```
mitmproxy -I google.com
```

but sometimes mitmproxy breaks other daily browsing. For example, Dropbox and Google Drive will not sync when mitmproxy is working. There are many other services not working, so I don't think it is a good idea to ignore all other domains one by one. 

Can I just intercept the http traffic on single site `abc.com`?

**Comment by mhils** [comment]
Check out #468.
