### ISSUE TITLE
Modify response body - insert content of new request

### ISSUE THREAD

**Issue by gfrench17** [mitmproxy/mitmproxy#579]
Hi Max,

maybe you can give me a hand regarding this tricky one:

I use a website which contains encrypted content. It tells me to upload my private key in order to decrypt the content server-side, but I do not want to expose my private key. What I want to do instead is the following:

1. Invoke the specific website address, e.g. https://example.com/view.php?msg=15
2. extract token ID etc. from the request content (this works already) to create the request for step 3.
3. In the background, request the raw source of the encrypted content (in a separate request, this works already)
4. Decrypt this source with my private key (this also works already)
4. Paste the result of step 4 in such a way that I see it inside the response of step 1.

So, my crucial step is no. 3. How can I perform a request in the background and then "inject" its response into the response of the originating request in step 1? The rest is feasible for me.

Kind regards
Gordon

**Comment by mhils** [comment]
Not sure if I get you right, but you can just .reply() with a HTTPResponse in the request() hook. See https://github.com/mitmproxy/mitmproxy/blob/master/examples/redirect_requests.py#L15-L19 for an example
