### ISSUE TITLE
View used SSL/TLS Version and Cipher Suite

### ISSUE THREAD

**Issue by raymontag** [mitmproxy/mitmproxy#582]
Hey,

is it possible to view the Cipher Suite used to encrypt the traffic? I think this could be interesting while testing some application without the need to set specific ciphers. E.g. this information could be saved as an attribute in the HTTPMessage class. Moreover this could be helpful to check if the something was really encrypted, e.g. by setting the attribute to None (or is this information already provided by the scheme attribute?).

**Comment by mhils** [comment]
> (or is this information already provided by the scheme attribute?)

yes. We also have the flow detail view (`X` in 0.11.3, more prominently on the current github master) to view the certificate.
Displaying the current cipher suite is useful, but we should keep in mind that the cipher suite may change at any point in time of the TLS connection, which makes displaying/storing it not entirely trivial.

**Comment by mhils** [comment]
From #1589: It would also be very useful to display the TLS version that has been used for the server and client connections. If anyone picks this up, let me know and I'm happy to help!
