### ISSUE TITLE
in script mitmproxy_logging_script.py: No module named 'logging.handlers'

### ISSUE THREAD

**Issue by kennyparsons** [mitmproxy/mitmproxy#5844]
#### Problem Description
I am using this script for mitmproxy to log mitmproxy traffic: https://github.com/kubistika/mitmproxy-logging-script

Upon launching mitmproxy, I get this error:

```
mitmdump -q -s mitmproxy_logging_script.py 
[05:36:34.003] in script mitmproxy_logging_script.py: No module named 'logging.handlers'
```

#### Steps to reproduce the behavior:
Use the unmodified script and config. I'm running as root currently for testing. 

#### System Information

```
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.10.0-20-amd64-x86_64-with-glibc2.31
```

As I understand it, mitmproxy uses its own virtual env, but the logging module should be installed by default.

**Comment by mhils** [comment]
We can't provide support for third-party scripts, sorry. At a first glance, it looks like this script is using some modules that don't ship with our precompiled binaries. In this case you want to install mitmproxy from PyPI.

**Comment by kennyparsons** [comment]
Ah. Makes sense. Thanks!

**Comment by kennyparsons** [comment]
@mhils when running mitmdump, how can i get the output of my addon to be the only output. for example, I want to suppress all the client connect message, all the server connects, etc. I only want what my script is logging to be shown. I tried the -q option, but it suppressed everything.
