### ISSUE TITLE
when redirecting https requests, mitmproxy still connects to original target

### ISSUE THREAD

**Issue by wiktortomczak** [mitmproxy/mitmproxy#5858]
#### Problem Description

When instructed to redirect an https request, mitmproxy still connects to the original target (server) of the request. The request itself is properly redirected, though (sent to the other server). By redirecting, I mean overwriting `flow.request.host` property, as in [examples/addons/http-redirect-requests.py](https://github.com/mitmproxy/mitmproxy/blob/main/examples/addons/http-redirect-requests.py).

#### Steps to reproduce the behavior:

1. `$ mitmdump -s examples/addons/http-redirect-requests.py`
2. `$ curl -vk -x http://localhost:8080  https://example.org`

##### Actual behavior

`mitmdump` terminal output:
```
127.0.0.1:53398: client connect
127.0.0.1:53398: server connect example.org:443 (93.184.216.34:443)
127.0.0.1:53398: server connect mitmproxy.org:443 (108.138.17.12:443)
127.0.0.1:53398: GET https://mitmproxy.org/ HTTP/2.0
     << HTTP/2.0 200 OK 23.0k
127.0.0.1:53398: client disconnect
127.0.0.1:53398: server disconnect example.org:443 (93.184.216.34:443)
127.0.0.1:53398: server disconnect mitmproxy.org:443 (108.138.17.12:443)
```

##### Expected behavior

Should not connect to `example.org`, as indicated by:

```
127.0.0.1:53398: server connect example.org:443 (93.184.216.34:443)
```

##### Note

No connection to the original target is made if the request is http:

1. `$ mitmdump -s examples/addons/http-redirect-requests.py`
2. `$ curl -vk -x http://localhost:8080  http://example.org`

`mitmdump` terminal output:

```
127.0.0.1:51168: client connect
127.0.0.1:51168: server connect mitmproxy.org:80 (108.138.17.51:80)
127.0.0.1:51168: GET http://mitmproxy.org/
              << 301 Moved Permanently 167b
127.0.0.1:51168: client disconnect
127.0.0.1:51168: server disconnect mitmproxy.org:80 (108.138.17.51:80)
```

#### System Information

```
$ mitmproxy --version
Mitmproxy: 8.0.0
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Linux-5.15.0-56-generic-x86_64-with-glibc2.29
$ mitmdump --version
Mitmproxy: 8.0.0
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Linux-5.15.0-56-generic-x86_64-with-glibc2.29
```

**Comment by mhils** [comment]
This sounds like you're looking for [`connection_strategy`](https://docs.mitmproxy.org/dev/concepts-options/#connection_strategy)?
