### ISSUE TITLE
502 Bad Gateway Connection killed

### ISSUE THREAD

**Issue by lwensveen** [mitmproxy/mitmproxy#5863]
#### Problem Description
502 Bad Gateway
Connection killed: Request destination unknown. Unable to figure out where this request should be forwarded to.

#### Steps to reproduce the behavior:
1. Configure proxy in gnome network manager as http://127.0.0.1:8080/
2. ./mitmproxy
3. Go to http://127.0.0.1:8080/

#### System Information
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-6.0.18-602.inttf.fc37.x86_64-x86_64-with-glibc2.36

**Comment by alainpannetier** [comment]
Proxy server does not serve pages.
You're asking the proxy server to serve it's own proxy URL.
