### ISSUE TITLE
stream waits perpetually for empty body

### ISSUE THREAD

**Issue by Puliyo** [mitmproxy/mitmproxy#5865]
#### Problem Description
When stream is programmatically enabled, ( `flow.<Message>.stream = True` )
and client sends or server responds with empty body, mitmproxy waits for data which will never arrive.

#### Steps to reproduce (client):
1. Create addon
```python
def requestheaders(flow):
  flow.request.stream = True
```
2. Send request with empty body (such as GET request)

#### Steps to reproduce (server):
1. Create addon
```python
def responseheaders(flow):
  flow.response.stream = True
```
2. Send request to http://httpbin.org/status/204
3. client receives response but connection with server remains open (no "server disconnect httpbin.org:80" log in mitmdump)

#### System Information
```bash
$ mitmproxy --version
Mitmproxy: 9.0.1
Python:    3.10.6
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.0-1025-oracle-aarch64-with-glibc2.35
```

#### Workaround
Determine if body will be empty by inspecting header.
````python
def requestheaders(flow):
    "Enables streaming for all requests when body is not empty."
    for k, v in flow.request.headers.items():
        _k = k.lower()
        _v = v.lower() if v else v
        if (_k == "content-length" and _v != "0") or (_k == "transfer-encoding" and _v == "chunked"):
            flow.request.stream = True
            break
```

**Comment by mhils** [comment]
The following works fine for me:

```python
def requestheaders(flow):
  flow.request.stream = True

def responseheaders(flow):
  flow.response.stream = True
```

```shell
mitmdump -s repro.py
curl -x localhost:8080 -k https://example.com
```

**Comment by Puliyo** [comment]
After further testing it might be glitch with the client tool i'm using, holding on to the connection.
Cannot reproduce using curl.

**Comment by Puliyo** [comment]
Re-opening as I am able to reproduce this with curl.

Example:

Addon:
```python
def requestheaders(flow):
  flow.request.stream = True
```

Curl:
```bash
curl -k https://www.yahoo.co.jp -x http://127.0.0.1:8080
```
