### ISSUE TITLE
Set Access-Control-Allow-Origin header to * when using --map-local

### ISSUE THREAD

**Issue by keeely** [mitmproxy/mitmproxy#5868]
#### Problem Description

When using --map-local I needed to add a small script to avoid CORS errors.  I wondered if it's appropriate to make this behaviour the default.

#### Proposal
Additional header by default when serving local files, e.g.:
![image](https://user-images.githubusercontent.com/11296296/212440483-9b3b25a2-9626-47dd-8973-92b112d38b38.png)

#### Alternatives
Obviously you can use a script to achieve the same thing which is not too hard.  For example:
```
from mitmproxy import http

def response(flow: http.HTTPFlow) -> None:
    if flow.request.host == “myhost.com”:
        flow.response.headers["Access-Control-Allow-Origin"] = "*"
```

#### Additional context
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by Prinzhorn** [comment]
> I wondered if it's appropriate to make this behaviour the default.

Not at all in my opinion.

You don't need the addon, you should be able to use `--modify-headers '/~s/Access-Control-Allow-Origin/*'` (add a host filter as required instead of just `~s`)
