### ISSUE TITLE
mitmdump fails with 502 error

### ISSUE THREAD

**Issue by yiannisy** [mitmproxy/mitmproxy#587]
Hi,

I run mitmdump as an HTTP proxy. After sometime all my requests fail with the following error : 
ProxyError(NetLibError('Error connecting to "www.cnn.com": [Errno -5] No address associated with hostname',),)
Is this a known issue? I haven't tried to debug DNS requests in detail yet...Restarting mitmdump solves the problem immediately.  I am running mitmproxy 0.11.4 on Ubuntu 12.04.

Thanks,
Yiannis

**Comment by mhils** [comment]
This is not a mitmproxy error - Python tries to resolve "www.cnn.com", which fails on the OS level. Not sure where this is coming from, but you may want to look into your DNS configuration.
