### ISSUE TITLE
trailing zeros trimmed before sending out

### ISSUE THREAD

**Issue by Muthuvel2019** [mitmproxy/mitmproxy#5876]
#### Problem Description
string body data having like "07" going out to target site as "7"
#### Steps to reproduce the behavior:
1. run a web  application to receive  a REST input as string alues
2. send through mitmproxy  values like "09"
3. find it in the received application
#### System Information
Paste the output of "mitmproxy --version" here.
mitmproxy==5.3.0
installed through pip install mitmproxy==5.3.0

**Comment by mhils** [comment]
First off this _very_ likely is a bug in either your client or your server (and not mitmproxy), second we don't support old releases.
