### ISSUE TITLE
mitmproxy alternate confdir behaviour

### ISSUE THREAD

**Issue by keeely** [mitmproxy/mitmproxy#5892]
When running
mitmproxy --set confdir=somedir 

The behaviour is to create the directory in the place specified by the setting.  But if you already created somedir, and then you mis-type it, you'll get another directory.  Your fault perhaps....

The automatic creation of ~/.mitmproxy, seems reasonable and consistent with other software.  But I don't think it's the same when you're giving your own directory explicitly so I think the former should be a special case.  It doesn't seem unreasonable to ask that the user creates the directory they specify first.  Many users will be specifying a directory because they want to supply an alternate CA for different instance.  I suspect a smaller portion are doing it to maintain isolation between multiple instances of mitmproxy, and if they did this as part of some automated system, I'd expect them to automate the management of instance directories as well, e.g. :

```
~/mitm_conf/<pid1>
~/mitm_conf/<pid2>
~/mitm_conf/<pid3>
...
```

So in that case, I don't really see the directory creation as being much of a benefit.

I discovered this when running a command on MacOs that I'd originally typed on Windows.

mitmproxy --set confdir=.\somedir 

That creates a directory ./.somedir, and it took me a while to figure out what had happened, it's another side-effect of this behaviour that would be solved by insisting confdir is pre-created.

**Comment by mhils** [comment]
If you feel strongly about this I'd be happy to merge a PR that changes the behavior here, but I think both behaviors are reasonable and I don't see me or anyone else of the core team spend any cycles on this. :)
