### ISSUE TITLE
WireGuard Mode: Spoof ICMP echo replies

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#5910]
Some apps check network connectivity by sending ICMP pings. ICMP traffic is currently swallowed by mitmproxy_rs, which makes them believe that there is no network connectivity.

Correctly forwarding ICMP in both directions is tricky, so a cheap mitigation that probably covers the majority of use cases would be to simply fake ICMP echo replies [somewhere around here](https://github.com/mitmproxy/mitmproxy_rs/blob/459bd9c1da29378b14e7f0230705c892f89668d1/src/network/task.rs#L68).

**Comment by chiragbiradar** [comment]
Hey @mhils I am interested in issue, can you assign this to me?

**Comment by mhils** [comment]
@chiragbiradar: if you read up on how ICMP "pings" work, the description above should make sense.

**Comment by wesolowski-gh** [comment]
@mhils is this issue intentionally left open? Looks like it's already resolved by https://github.com/mitmproxy/mitmproxy_rs/pull/28

**Comment by mhils** [comment]
Nope, thanks! :)
