### ISSUE TITLE
Small formatting issue with lists in the msgpack contentview

### ISSUE THREAD

**Issue by SapiensAnatis** [mitmproxy/mitmproxy#5911]
#### Problem Description

0s in arrays in the msgpack content view are not formatted with a comma at the end

![image](https://user-images.githubusercontent.com/5047192/216798188-55be0d80-07a9-4ecc-b542-408618c1ea0b.png)

This display quirk is not replicated in Cyberchef, so the msgpack is valid.

#### Steps to reproduce the behavior:

Open mitmweb, and press 'Replace' in the contentview, and provide the following file:

[debug_controller.txt](https://github.com/mitmproxy/mitmproxy/files/10610105/debug_controller.txt)

(sorry, I couldn't quite work out how to get the bytes to paste here and into Edit in the contentview)

#### System Information
Paste the output of "mitmproxy --version" here.

Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.14.21-150400.24.41-default-x86_64-with-glibc2.31

---

I am fully aware that I wrote the enhanced msgpack content view, so this is probably something I missed when I was testing it. More than happy to take a look when I get a chance, just noticed it today and thought I'd raise an issue before I forget.

**Comment by pradyotRanjan** [comment]
I would like to work on this issue.

**Comment by Prinzhorn** [comment]
Are you sure it's actually the zeros and not the fact that they're repeated? Because: 

https://github.com/mitmproxy/mitmproxy/blob/a7e50c793e9c6840d9f0fc162893e293477a358e/mitmproxy/contentviews/msgpack.py#L71-L72

@pradyotRanjan feel free to create a PR with a test and fix. @SapiensAnatis originally created that code, I'm sure he can help with any questions you have. Or did you want to submit a fix yourself?

**Comment by SapiensAnatis** [comment]
> Are you sure it's actually the zeros and not the fact that they're repeated? Because:
> 
> https://github.com/mitmproxy/mitmproxy/blob/a7e50c793e9c6840d9f0fc162893e293477a358e/mitmproxy/contentviews/msgpack.py#L71-L72

Oops! Well I can see what needs to be done now — should use enumerate and check the actual index. And add a test for this case of course. 

I don’t mind if someone else does it. It will probably only take a short while to fix, so if nobody else has submitted a fix in a week or so I’ll have a look.

**Comment by Prinzhorn** [comment]
Sounds like a great thing for a first contribution, so go ahead @pradyotRanjan if you want
