### ISSUE TITLE
Wrong message direction indicator in console raw TCP view

### ISSUE THREAD

**Issue by konradh** [mitmproxy/mitmproxy#5921]
#### Problem Description

In the flow view of the console tool, for raw TCP flows the `⇒` and `⇐` direction indicators (from client and to client) always alternate and don't represent the correct direction.

#### Steps to reproduce the behavior:

1. Start a TCP server: `ncat --listen localhost 2000`
2. Start mitmproxy: `mitmproxy --mode=reverse:tcp://localhost:2000@2001 --tcp-hosts='.*'`
3. Connect to the reverse proxy: `ncat localhost 2000`. Enter multiple lines, e.g. `a`, press enter,  `b`, press enter.
4. In mitmproxy, open the flow view for the new flow. There the two messages have different direction indicators even though they were both sent by the client.

#### System Information

```
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-6.1.9-arch1-2-x86_64-with-glibc2.37
```

#### Fix

The bug is in the function [`view_message_stream`](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/tools/console/flowview.py#L248) and was introduced in https://github.com/mitmproxy/mitmproxy/pull/3970/commits/fe75f14ea29d0654c3a688ecc4c3669a946ea2a8. The solution could be the same as in the similar function [`view_websocket_messages`](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/tools/console/flowview.py#L197).

I would like to contribute a fix for this issue.

**Comment by mhils** [comment]
Thanks for the clear description. And yes please, a fix would be very welcome! 😃
