### ISSUE TITLE
Logging verbosity impacts logs from a script

### ISSUE THREAD

**Issue by hakenmt** [mitmproxy/mitmproxy#5935]
#### Problem Description
When I set the log verbosity in the config file to `warn`, i.e.

```
console_eventlog_verbosity: warn
termlog_verbosity: warn
```

logs that I'm writing in a script at that log level or higher are not outputted to stdout, whereas they are if I leave the verbosity at `info`, they are.

#### Steps to reproduce the behavior:
1. Set the `eventlog` and `termlog` verbosity to `warn`
2. Run a script with something like the following:

```python
import logging

class Handler
  def __init__(self):
    logging.basicConfig(level=logging.WARNING, 
                        format='%(asctime)s %(levelname)s %(name)s %(message)s',
                        filename="/var/log/mitmproxy.log"
                       )
    self.logger = logging.getLogger(__name__)

  def request(self, flow: http.HTTPFlow):
    self.logger.warning("A warning here")
```

#### System Information
Mitmproxy: 9.0.1
Python:    3.10.10
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.10.162-141.675.amzn2.x86_64-x86_64-with

**Comment by mhils** [comment]
I can't reproduce this with what you provided. The following works as expected for me:

```python
import logging
from mitmproxy import http

class Handler:
  def __init__(self):
    logging.basicConfig(level=logging.WARNING, 
                        format='%(asctime)s %(levelname)s %(name)s %(message)s',
                        filename="/var/log/mitmproxy.log"
                       )
    self.logger = logging.getLogger(__name__)

  def request(self, flow: http.HTTPFlow):
    self.logger.warning("A warning here")

addons = [Handler()]
```
```shell
mitmdump -s foo.py --set termlog_verbosity=warn
```
```shell
curl -x localhost:8080 -k https://example.com
```

![image](https://user-images.githubusercontent.com/1019198/219645592-33c95649-b46d-477f-b361-d56846110a46.png)

<hr>

Mitmproxy: 10.0.0.dev (+217, commit 2663b42)
Python:    3.11.2
OpenSSL:   OpenSSL 3.0.8 7 Feb 2023
Platform:  Linux-4.4.0-22621-Microsoft-x86_64-with-glibc2.35

**Comment by hakenmt** [comment]
Sorry, I think my problem was stemming from a different behavior. If I call `self.logger.error("My error")`, it terminates the mitmproxy process. Is this intended, any logged error stops the process?

**Comment by mhils** [comment]
Absolutely not, except during startup. Again this needs a full repro. :)

**Comment by hakenmt** [comment]
```
#!/usr/bin/env python3

from mitmproxy import http
from mitmproxy import coretypes
import logging

class Throttling:
  
  def __init__(self):
    logging.basicConfig(level=logging.INFO, 
                        format='%(asctime)s %(levelname)s %(name)s %(message)s',
                        filename = "/var/log/mitmprox/mitmproxy.log",
                        filemode= "a"
                       )
    self.logger = logging.getLogger(__name__)
    self.logger.error("Init called")

  def request(self, flow: http.HTTPFlow):
    self.logger.warning("received request")

addons = [Throttling()]
```
Logging an error during ``__init__`` terminates the container I'm running this in.

**Comment by mhils** [comment]
Yes, errors during startup are intentionally fatal. The idea here is that those likely point to mistakes in the invocation, and it would be worse to silently swallow those.

**Comment by hakenmt** [comment]
Using `.warn` is acceptable, just wasn't expecting logging an error during init to be fatal.

**Comment by hakenmt** [comment]
An explicit message would definitely help, or even just a note in the documentation to expect this behavior, both would be ok for me.
