### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by friday654321** [mitmproxy/mitmproxy#5936]
#### Problem Description
Transparent mode failure: OSError(24, 'Too many open files')

#### Steps to reproduce the behavior:
1. Internet browsing via Chrome on Android device 
2. running 
mitmdump --mode transparent -k -v --showhost  \
--ignore-hosts 'ipinfo.io:' \
--ignore-hosts 'googleapis.com:' \
--ignore-hosts 'google.com:' \
--ignore-hosts '^www.google.com:' \
-w /tmp/proxytraffic.raw
3. get error "Transparent mode failure: OSError(24, 'Too many open files')"

#### System Information
Paste the output of "mitmproxy --version" here.
% mitmproxy --version
Mitmproxy: 9.0.1
Python:    3.11.0
OpenSSL:   OpenSSL 1.1.1t  7 Feb 2023
Platform:  macOS-13.0.1-x86_64-i386-64bit

**Comment by mhils** [comment]
I can't reproduce this, things work for for me.
