### ISSUE TITLE
The system detected an invalid pointer address in attempting to use a pointer argument in a call

### ISSUE THREAD

**Issue by JXRNO** [mitmproxy/mitmproxy#5937]
#### Problem Description
Keep getting this error when running mitmweb.

[16:55:02.607] Traceback (most recent call last):

  File "asyncio\proactor_events.py", line 839, in loop

  File "asyncio\windows_events.py", line 837, in _poll

  File "asyncio\windows_events.py", line 586, in finish_accept

OSError: [WinError 10014] The system detected an invalid pointer address in attempting to use a pointer argument in a call

[16:55:02.613] Traceback (most recent call last):

  File "asyncio\windows_events.py", line 591, in accept_coro

OSError: [WinError 10014] The system detected an invalid pointer address in attempting to use a pointer argument in a call

#### Steps to reproduce the behavior:
1. Open CMD, type 'mitmweb'
2. Go to Android 11 Settings > WiFi, Then my network name > Proxy > Put in local ip and port (192.168.2.9, 8080)
3. Wait for the error, or turn wifi off and back on.

#### System Information
Paste the output of "mitmproxy --version" here.

Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Windows-10-10.0.19044-SP0

**Comment by mhils** [comment]
Can you reproduce this consistently? This seems like a bug in Python's asyncio module.

**Comment by JXRNO** [comment]
> 

Yes, it keeps happening even after PC restart.

**Comment by JXRNO** [comment]
Tried Microsoft Store install aswell. same issue.

**Comment by mhils** [comment]
Not sure what' up here, but that very likely is not a mitmproxy bug.
