### ISSUE TITLE
Unable to decode application/vnd.wap.wbxml request/response

### ISSUE THREAD

**Issue by trimmytech** [mitmproxy/mitmproxy#5938]
Hello , Thank you for ths wonderful software , i have apk that i am using mitm software to analyse , i realised that any POST  body request to the server is always application/vnd.wap.wbxml and mitm is not decoding it. Below is the sample response frpm mitm :
PS:  i changed the type to wbxml , stll the same thing 

Couldn't parse: falling back to Raw

1n\x9dkB6*\xdd\x9a0Mf\xc7\x83\xd4\xd8\xdc0\xfbK\xdf\xcep\xba\xa2\x0b\x04/d\x9fo\x94\x9b$U\xdf\xd4\xef\xdf\x83,\xdc\x8a~\x9dK2\x01\x98\x8a^=\xcf=\xe5,eKb>\xd0b$\xb8:B\x14!C\x88z\x15\xfe\x19_\x0f\x83=~\x88l*\xe3\xf9\xe6\x8cfi\xdd;	\xef?\xc3k\x92\x07p\xf4\xa1]\xaacj\xe0\xd3\x99\xbcZ\x13\x1a\xd0d\x1bA\xfe\xa6\xb38\x90\x95\xf1\xfc\xe3
\x0fB\xb8/\x94\x84\x80$X\x1b?t(M\x8d~"\xc0R\xdc\x11\x03k\xb5\x02\x00\x05\xd2\xa7.\xb8[a\xa9QK\xcb\x06\x90\x1bOl*\x1e\x8d\xde2wc\xf5\x8c\xfe\x1cM\x80I\x86\x95\xe8%\xb0\x83\x00/
o~r\xd1\x0cA<\xfa\x866\xef\x84z.\x82_c\xef\xfe\x84\x10\x1e`\xb0\xa4\x02\x13\xf8lN\xa54(\xd9\x97\x81\xffs\xa9\xfc\xad\xc1\xdc\xf3\xf7\x11\xc2%\xa6\xf2\x89\xe7-\x18\x9c2g\xd5\xedV\x11"\x17\x85\xfe}\xe1\x9c\xa9\xf96)\xfc\xdfEl\x86\xccK!3#o\xef\xbd\xdb\xff^`\xb5\x8b\xdf\x84\xd7\xa7W\xe1\x18\xea\x08\xb8"m,\xe2\x84\xcd@p\xe8\xb84\xab\xb0v\xe2\xdd\xa5\x82\x02\x8e\xc7\xafz+\x92\x9b\xb6+w\xe7\xc9vz\x85To\xd4\xfd\x1a\xbc6 \x97\xd7\x0e\xfd31\xd0#c\xce\xe4\xaf\xdf0`\xb3\x80\xfc\xb1\x86\x95\xa3.\x8fq\xca '\xa2\xa2\xd9\xad|p6\x9a\x81\x93\x851\xf9\x8d\xd7\x93\x10\xd6\x87\x83\xef\x94!\xa9d\x9f\xbf%H \xdb\xd5\xdd8\x0c\x1d>\xcf
\xa6\xd2\xdbB\x07\xb0:\x19\xect\xa9\xe7\xed\xb8\x07f\xe9m\xef"\x98%<\xd4\xba)\xc6\x11\xd32#'\x8a\xb1\x93\xbd\xb3\xae\xb8^\x92\x12\xcc"\xa3J\xc7\x8f\x19!\x8f\x19\xa0\x19\xa2\xe3\xd8+\xacm\xf0\xb3\x17\x07\xe0W\xd0\xff\xab'\x9ah/3\xb9I\xca-\xadL\xf6bci,`e\xc2X15x5\xbc]+\xb6/
fQO\x15\xa1\xa4H \xa3\xa4\xbbA\xd7\x0f9\xa7!/\xf9>\x86r\xfb\x15\xd9i\x91\xd4\xb9\xc5\x9a\xea\x93\x0e\x81\xd7K\x02~\xd92\x03\xb3	\x01\xb2\xb9\xd8\x8d\xb8\xc1\x04\xa7z\xeb\x9at\x88`\\\x86\xc4\xa0\x84\x83\x0f(\x153\xf8(\xc0\x86q`\x8d\xb8\xfd\x1f\x0b[\xfc\xf9\x08\xc8\xa4\x0f\xc8\x8dk\x873\xaf&\xce\xe0i\xea\xd0hg\\\x04	\xbf<\xca\x881\xf9\x94\xd8\x86\x03\xb4\xa8\xf0IG\xc4\xa9\xcf\xae\xe9'\xdd\x82\xbf\xc3\xa4\xc86\xb1~&fQ^#c@Sa\x16j\xfe\x8a\xc7\x8a\xe4q\xf3t.\xce\x02u\xaaB\xac\xab\xfet$\xbd\x045\xda\xaa\xa7lq\xe1\xbcw6\x1b=\xea7\x01\xaeQ\xdbj8L\xcf\x18U_\xee\x8c\x9f\x87V\xf8\x8c\x87\x1d \x9c4\xf7~\xd2\xc9\x05\x10\xf2B)\xd1N.\x07\xea\xf6\x13\xa9\xaa\x12Q\x9b\x9aDj/$\x18@B$\xae\xd0iP\xdd&\xac>4\x08!\xea4\xc4\x10P\xd2\x935=-\xee\x05\xb7&\x95\xb2kv\xd2\xc0\x11\xce\xbd\xd8\x90\xdfWIxGY
\xafq.F\xed\xd5\x9b\x9d\x97\xaf\xff\x14\xde\xd1\x0f\x0c\xd7\xeby\\.\x8a\xad\xafS\x1d\xc3 \x8f\xc5V\xa1k'\xf5\xe8\xaf)\x19\x93<\x89\x16-\xc9]\xf7d\xb9l,\xb0\xa6Q\xb0f\xa0\xf2\xc6\x95>\xc2\x19\xcc\xc13\xfb\xdd\xf0\xee\xa60\xb8\x18#\xf9\xe8@\x02\x19\xc6~c\xceq20n\x88\xff\xc4\xef'\x18\xaeidtA\\T\xd1\xd1\xea\xb4JO\xb3I\xbeR\xe1t\x15\xe2\xfc\x01\x1e\xee\xec-%K\x028j{\xc8\xf4\xcc\x9f\x15fH\x83\x9eQx\x13\xb6\xdd\xca\xd5\xeb\xe1S\xdd`\xc0x\xd6i\xd0\x8c\x1b|\x16\xc4\x13\x97\xbe\x10\xdbM\x1fv\xf1\x8e\x01\x89\xb3\xed\x9e!\x83s\x07s\xce\xda[\xbe\xa0v\xe5_=+\xed\xdb\xfc\xa3\x06.j1(,\x90\x95O\xdb\xa6\xef\x8d\xf9\xb3
\xa9<\x14_\xaf\xb3\xb2\x93!\xfa\xb8+\x8cA\x9a\xa4%U\x90\xcfk\xd0uW9J!\xf2\xb8\xbf\x10':\x14$\xeb\xf3V\xdd\xf1b\xfe]\x02_\xc4\xdb0\xabv\x00\xde\xd3\x0b\xc6t\x06\xbc^\xf9P\x89:\xdb\x90\x87\xc3`\xbc\xf2\xec\xb8^\xb2h\x085t\x84\x8f\x01\xf69\xb9\x18\xcf\x89w&Ug \x06,\xe1KK\xe8\xb4\xa2\xf3I\x8a\x9a\x0cuK}m\xa9\xf4j\xefJ\xfc\xe6\xbd\xba\xcf6\xb2\xe9
\x8c\xd1\xd9\xe7\xfa'c\xff0K\x9de:\x8f9U\x9c\x7f\xcd\xa9(\x9b\xfe\xb8\xad\xbd\xc8\xc2\x82\x88\x19F\x96\xd0\xda@\x19\x7f\x82y\xf5{\x90"\xca\x83V\xbf\xd2\xa7!m0
\xae\x9f\xack\x89\x8f\x93\x9c\xfb\x8c\xb8\xe9 \x0e\x04\x90\xd9\xc9\xebH<_\x04\x85\x97\x13e\xce\x89L\x1f\xcfs\x83\xe0
\x1b\xfdp\xa2'\xdc"Y\xd0\x1a\xe6\xaa\xa9=%%\x1f\xfc\xb5\xcfE\xabrX`7\x06\x01s\x9c\x1a}9f\x18\xfdV~\xf4H\x7f
\xedp@:\xef\xff\xf2V\xe4 \x0c7\xa0J9c\x07\xeb)z\xeb\xf8.Q\x1e@\xbc\x94\x00{f\xdf\xa7\xd4\xa3\xc6\xce\x19\xfdS\xd3X\x16\xc3\x01$
\xd4'Y\xab\xb63M~\xa8\xb6\x03\xf3:\xd5\xfb\xb3\xc5\xd0\xc3\xeeE\xe0\x92\xfc\x1e[\xf3\x81\x8b\x97\x98\x0b\xe8\x1a\xbe*\xfe;\x15u\xdc\xc1\xce\x0e\x16g\xe6\x9av|]\xa3\x06U\x1a\xf5&gZ\x14\x1a*\xc8J?Q%~\xbe\xa7\x8f\xa1Vk.o\xbb\x01\x95\xb4p\xca>\xca4da\xcb\x9aF\xd5\xee\xeeKe\xb4t0+,\x84\x94\xa8\x0e\xb9#\x9c\xda\xe4\x11\x1e*\xbf]S\xc7w\xe1s]\xd8\xefL-\xdcm\x18\xaeE\xeb\x1a\xd8(\xa4\x02V1\x08\xae\xfah\x7f\xef,\xfa_\xcbx\x07\x90\x99\xab\x95"Y\x80\x88'p\xf1\x99\xa7\xe9\x01\xcc{Z\xa8R\x92\xb3\xbd\xb691\xd0\xb6 \x19p9\xa2\xfb\xdcw!\x06\x8c9D\x85\x00\x99\x948\xd2\xcf6I\xb5"\x15\xc6\xb0\xe3HR{\xa1\x8f\xfa\xf5oo\x93\xc7\xf9\x93\x83\xf9\xaekT\xdal\xfd\xb5&\xf3\xa6a\x01\xbd\x0c'\xeb\x14O\x03\x9b\xed\xb8\x962u\xdd\x19\xa6\xbe\x02\x052
'd\xfe\xfa\xc2\xaa\xb8\x7f\x1bu\x9beR\xb1\xa7\xeb\xe7@\xb9b\x84\xdc\xf2\x93\x81}\xcd\xbb0\xb9\xd5\xc1*\xc2\xa7\xf1H\xec\x0f\xcf\x17\xfcr\x9e%\x19<\xe9\xfb3A^\xdeQ]'\x95N#\x87\xf6-~\xc5\xfc\x10\xca\x94\x90d\xba\x19w\xa6\x11\xa1\x0f8L0D\xe0\xd0/D5\xf4.[\xe8\x93\xf9uY\xc1\x07\xdd\xed\x86b~f\xf0\x963l3\x9a\xa0\x81\x82\xba\x14\xe2\xa9\xa9\x9e\xf3}\xa1\xc5\x82
\xce5\xe5\xb7}\x12\xdcO\xb5\xd6\xea?\x8a\xbc/\x00Qi\x05\xd8I!eUM\xa2\xc6*1\x1e\xe1x\xfae\xed\xff\x1b\xd4\xa5W\x8c\x1b0\x10\xeek\x0e\xe5\xe6\xbd\xfe\x92\xdc\x81	k\xbc\xaaZK\x15\x1eh\x84\x98\x1d[c\x07~9\xb1\xc9\x02\xb2\xe6O\xffM&+\x1a\xfa\xb4\x00K\xd1\xcb\xa1\xf47\xe3\x80\xc4)\xcf
\\\xa6\x97\xb6\xe7\x9cp\x96s\xc4\x97q\xa2\xd8h\xa2'\x99\x8a\xc3\xc62\xfd\x03\x95\x12\x16\xd0\xcd5\xb2\xae\xf7\xf9XD\xbflE\xeb9\x17-\x10\xb7\x94{;\xa0\x84\x89\x18\x96f\xc2\x1eTh[j\x80\xb5\xd1\xf8'\x9b\xf6\xee\x1cp\x8a\x97L\x84\xabh\xd3\x0c\x90\x9b\x0b\x1a
\xc6\xb3\xcbQ\x00\xa8\x08/0\xaf\xfc\xe9`\x9dA]\x8f]R2H\xdb\xdd\\\xa9\x8b\xd6E\xb8\xf0/RQ\x8eW\xa3\xb8+\x8d\xb7\x16\xeb\xab\xf5\xe1\xc4\xf7\x0e\x15
\x879\x12\xf4E\xd9*gD\x0bP\xd5S\x01\x1d\xf6I<Q\x8cY\x0f\xfc3\xf0{\x0c\xa5\x93\xc3\x9e$g\xd4\xae\x00B\x0b\x07\xe5\x08\xc2!\xea\x98F\x16h\x96\xde\x01bR\xae&\x7f\xce*\xc5C\xf3\xae\xd7\xd0\x9a(\xf8\xce{$\xc1\xe6\x02t\xc5#+\xd6y\x1f\xb0\x1c\x1b"J\x04\xd1\x0e|\x18ae\xf7\xdd4!
L\x86\xacC\x85\xc6\xa3A{\x85\xc3>u\xb3\xe4\xeb\xd4\x02\xf7\x88\xe6\x9c=\xb8\x03^\xe0/\x7f\xa9\xf2'D:\x13\xd1\x0b\x0f\xe0I\x83\xfa\xb6\xd4\x8e\xc7\xb1+\xdb\x03nJ\x05\xf0\xb7\x95\x10\xdc\x9e]~\xf5\xfa'\x80\x8d\xb7o\xee\xd3\xa4\x88\x0b\x89Y\x8d\xb5\x16\xb3\x97\xc3n+\xf8
\x9dUQ\xcf(y\xcaS\xe3\x01\xcd\x01\xc3]\xce7\x05\x00\xca\xfe\xa7:N4\x9a\xdfR!\xeb
V\x01<\xda\xdb\xc5V\xd1\xc7x\xb3:\x129\xc0`*\xa4Dy'(iU\x0c\x1a\xd4#G\xa2\xfb\xf2\xbb5X\x08\xdc\xc2\xc1P\xf4\xb9\x8e\x9c\xdb\\s\xad\xe9{\xf8\xb80{\x0c\xa2\x9a+\xcd\xc5`\xdb^U\xf2m\xfe\x0c\xe3\x9f\xfcy\xba^\x89ck\xc3\x85\x1ac\x02\xe4\xe7\xccY~\x9a\xbd{j\x8b`Q\x1fLS\xc69\x7f\xabr\x89\xe1$\xfe6\x9a\xc3J\xfd\xec%F\xcb\x9f\x9e\xae9{,|\x15\x11!?#\xb2\xd3x\xe2\x80\xbd\xc4\xb3\xce\xad(\xe9\xb9n\x1a\x01\x8c\x91\xeeH\x07\xa0:\x11\x1d\x82\x14U\xff\x93\x16\x02:\x14\xa0
\xcb[u\x9a2,\xf0Rg\x1a<:c\xa4\xa7-0\x08\xde-\x921\xebuPq\xe8\xdb\x88\xca\x0ew$\x1a\xa3\xbd:\x82

Please kindly help

**Comment by Prinzhorn** [comment]
I think this is a duplicate of https://github.com/mitmproxy/mitmproxy/issues/3596

**Comment by trimmytech** [comment]
I have checked the duplicate , it didnt solve my problem , can you please help ? i dont  even mind dropping a tip to compensate you for your time , i would so much this wbxml decoded , it is important. Thank you , awaiting your response !

**Comment by Prinzhorn** [comment]
The wbxml support in mitmproxy is outdated and we don't have any official plans to update it. But we are more than happy to merge a PR that updates it.
