### ISSUE TITLE
UnicodeDecodeError in libmproxy

### ISSUE THREAD

**Issue by renebruns** [mitmproxy/mitmproxy#594]
While playing around with tamper (http://dutzi.github.io/tamper/) I ran into an issue with libmproxy. 

Error:
>mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 99, in handle
    protocol_handler(self.conntype)(self, **conn_kwargs).handle_messages()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 994, in handle_messages
    while self.handle_flow():
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 1098, in handle_flow
    self.send_response_to_client(flow)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 1344, in send_response_to_client
    self.c.client_conn.send(flow.response.assemble())
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 791, in assemble
    return head + self.content
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 4450: ordinal not in range(128)

Steps to reproduce:
1. Install latest mitmproxy via pip
2. Install tamper via pip
3. Install tamper Chrome extension (https://chrome.google.com/webstore/detail/tamper/mabhojhgigkmnkppkncbkblecnnanfmd)
4. Open Developer Console and switch to tamper tab
5. Restart tamper proxy by clicking on the settings wheel in the left box and choosing "Restart Proxy"
6. Open http://www.seat.de
7. Click on de.html in the appearing list (eventually you need to configure a text editor for this to work in tamper's settings)
8. Reload page (from this moment on it tries to serve the de.html file via mitmproxy)

Error can be seen if Chrome is started in debug mode
```
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-logging --v=1
```

Let me know if you need anything else!

**Comment by renebruns** [comment]
Small update: 
Tried the above steps with mitmproxy==0.11.3 and here the error does not occur. Seems to only affect 0.12.0

**Comment by mhils** [comment]
Thanks for the excellent report. I'm not sure why we don't see the error in 0.11, but this issue is caused by tamper itself. Tamper passes unicode headers to mitmproxy, which should be strings.

A simple workaround is changing `head + self.content` to `str(head) + self.content` in libmproxy/protocol/http.py, line 791; but that's more of a workaround. Could you please file the same issue on the tamper tracker? (cc @dutzi)

Cheers,
Max

**Comment by dutzi** [comment]
@renebruns thanks for the issue and @mhils thanks for cc'ing! 
Your idea worked, I casted the headers to strings and it's working. 

@renebruns, I published the fix to pip, you can upgrade tamper and it should run fine.
