### ISSUE TITLE
mitmproxy tools giving 502 Bad Gateway error on ubuntu 20.04 VM

### ISSUE THREAD

**Issue by ssheth7** [mitmproxy/mitmproxy#5949]
#### Problem Description
mitmproxy gives the following error when proxying traffic from my Android 9 device to my Ubuntu VM.

> ubuntu-vm $ ./mitmproxy
> [10:00:33.039][192.168.1.161:59394] client connect
> [10:00:33.059][192.168.1.161:59394] error establishing server connection: [Errno 111] Connect call failed ('0.0.0.0', 443)
> 192.168.1.161:59394: CONNECT 0.0.0.0:443
>                   << 502 Bad Gateway 209b
> [10:00:33.080][192.168.1.161:59394] client disconnect
> [10:00:33.171][192.168.1.161:59396] client connect
> [10:00:33.176][192.168.1.161:59396] error establishing server connection: [Errno 111] Connect call failed ('0.0.0.0', 443)
> 192.168.1.161:59396: CONNECT 0.0.0.0:443
>                   << 502 Bad Gateway 209b
> [10:00:33.199][192.168.1.161:59396] client disconnect
> [10:00:34.021][192.168.1.161:59400] client connect
> [10:00:34.024][192.168.1.161:59400] error establishing server connection: [Errno 111] Connect call failed ('0.0.0.0', 443)
> 192.168.1.161:59400: CONNECT 0.0.0.0:443
>                   << 502 Bad Gateway 209b
> [10:00:34.035][192.168.1.161:59400] client disconnect

My environment:
Host: MacOS Monterey
VM: Clean Ubuntu 20.04.5
Client: Rooted Android 9 device 

I am trying to create a setup where my android device's network traffic is routed through my Ubuntu VM on a bridged network. 

#### Steps to reproduce the behavior:
1. Set up clean ubuntu 20.04 VM with a bridged network
2. Downloaded linux mitm binaries from mitmproxy website
3. `ubuntu-vm $ sudo ufw allow 8080`
4. `ubuntu-vm $ ./mitmdump`
5. Installed mitmproxy's cert as a root cert in device (in /system/etc/security/cacerts/)
6. Set Android proxy to IP of ubuntu VM and port 8080 
7. When to a https/http website on the android device's browser (i.e. https://facebook.com or http://example.com), and the page doesn't load

#### Other Observations
1. I tried with my Mac host and had no issues. 
2. I tried running Burp Suite proxy on the ubuntu VM and had no issues
3. I proxied the Ubuntu VM's firefox browser to mitmdump and ran into the same issue (Couldn't load any sites) 
5. mitmproxy and mitmweb also don't work, but they just don't show the errors like mitmdump does

#### System Information
> Mitmproxy: 9.0.1 binary
> Python:    3.11.0
> OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
> Platform:  Linux-5.15.0-60-generic-x86_64-with-glibc2.31

**Comment by sujaldev** [comment]
Are you getting something like this in your traceback?
```python
[07:45:03.458] Traceback (most recent call last):

  File "/usr/lib/python3.10/asyncio/selector_events.py", line 159, in _accept_connection

  File "/usr/lib/python3.10/socket.py", line 293, in accept

OSError: [Errno 24] Too many open files

Please lodge a bug report at:
	https://github.com/mitmproxy/mitmproxy/issues
```

**Comment by mhils** [comment]
Not sure why, but this looks like your Android 9 device is sending malformed CONNECT request. It's not surprising that mitmproxy can't reach `0.0.0.0`. :)

**Comment by ssheth7** [comment]
Found a workaround to my solution! Using the mitmproxy docker container fixed whatever connection issues I was having

**Comment by phmg701** [comment]
Hello, afraid to report the same happend to me, with a possible solution.
- Clean VMWare Fusion VM with MacOS Monterey 12.6.7 + VMWare Tools + Homebrew + mitmproxy
- Installed certificate manually then (my fault!) set up permissission in Keychain to "always trust" for all items in the list. Certificate installed as System.
- Safari, trying to download from here https://helpx.adobe.com/download-install/kb/creative-cloud-desktop-app-download.html the file https://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/5_11_0/osx10/ACCCx5_11_0_522_1.dmg
Fail.

Then I tried the following:
- Deleted the certificate, rebooted, installed again this time with the automatic method "sudo ......"
- Now it seems to work like a charm

Thanks!

**Comment by ckcr4lyf** [comment]
Just another tip: Check if you have something like PiHole running! Most android apps have a lot of tracking etc. that PiHoles "block", by resolving the domain as `0.0.0.0` , which will fail to connect, and then show up as an error in mitmproxy.

**Comment by drupalista-br** [comment]
On ubuntu, mitmproxy 11, having the same issue with https://cav.receita.fazenda.gov.br/autenticacao/login specifically.

The thing is, it works most of the times. When 502 bad gateway comes up I have to turn off mitmproxy, access it outside mitmproxy and then turn mitmproxy back on again. That fixes it for a while until it comes up again. One more thing, the `--ssl-insecure` flag must be set otherwise `Server TLS handshake failed. Certificate verify failed: unable to get local issuer certificate` error occurs.

**Comment by ckcr4lyf** [comment]
> One more thing, the `--ssl-insecure` flag must be set otherwise `Server TLS handshake failed. Certificate verify failed: unable to get local issuer certificate` error occurs.

FYI: This is because the website in question does not offer it's whole certificate chain when you connect, so it can't be verified against your system's root CAs. (You can try `curl` or `openssl s_client` on it as well)
