### ISSUE TITLE
Export as curl command

### ISSUE THREAD

**Issue by Fuzion24** [mitmproxy/mitmproxy#596]
It would be very neat to have functionality in the UI to export as a curl command for a given http request

**Comment by cortesi** [comment]
Agreed - I'd find this very handy too. I'd definitely pull a patch for
this... ;)

On 29 May 2015 at 04:04, Ryan Welton <notifications@github.com> wrote:

> It would be very neat to have functionality in the UI to export as a curl
> command for a given http request
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitmproxy/mitmproxy/issues/596>.
>



-- 
Aldo Cortesi
blog: http://corte.si
twitter: @cortesi
work: www.nullcube.com
+64 210 718 900

**Comment by gato** [comment]
If nobody has taken this issue I will work on it this week end.

**Comment by cortesi** [comment]
:+1:

**Comment by dweinstein** [comment]
:+1: would love to see this!

**Comment by Fuzion24** [comment]
See pull req #619

**Comment by jeremyakers** [comment]
What version of mitmproxy did this get feature get added in?

**Comment by dufferzafar** [comment]
@jeremyakers 0.18.1 I guess. https://github.com/mitmproxy/mitmproxy/releases/tag/v0.18.1

**Comment by caioremedio** [comment]
I'm using 2.0.2 and can't find it. It was previously removed?

**Comment by ujjwal96** [comment]
@caioremedio in 2.0.2 you can use it by pressing <kbd>E</kbd> and then <kbd>r</kbd>

**Comment by baptx** [comment]
Is this feature available in mitmweb or should we create a new issue?

**Comment by paulerickson** [comment]
In case anyone else gets confused by this, I couldn't find anything from the web UI and the CLI command seems to have changed from `E` to `e`, from the Flows screen

**Comment by metalcamp** [comment]
I still can't get it to work. Any tips?

**Comment by baptx** [comment]
@metalcamp here is the web UI issue: https://github.com/mitmproxy/mitmproxy/issues/3457. By the way, I think I unassigned @gato by mistake on the command-line issue.
