### ISSUE TITLE
Upgrade to cryptography >= 39.0.1 because of CVEs.

### ISSUE THREAD

**Issue by jcamiel** [mitmproxy/mitmproxy#5966]
#### Problem Description
The current cryptography package dependency (38.0.4) has two CVEs:
- https://github.com/pyca/cryptography/security/advisories/GHSA-x4qr-2fvf-3mr5
- https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r

Would it be possible to plan an update on this dependency? [cryptography 39.0.0](https://cryptography.io/en/latest/changelog/#v39-0-0) is backward incompatible so it's maybe hard.

Thanks, 

#### System Information
Mitmproxy: 9.0.1
Python:    3.10.9
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  macOS-12.6-arm64-arm-64bit

**Comment by mhils** [comment]
The main branch already builds with the latest cryptography release. I don't think either of the posted vulnerabilities affects mitmproxy users in a significant way, so I don't think we will ship a patch release just for that. :)

**Comment by jcamiel** [comment]
Ok sorry for the issue, I didn't check the main branch 😓!
