### ISSUE TITLE
Facing Issues in performing host header injection test cases if I integrate my testing machine with mitmdump in regular mode

### ISSUE THREAD

**Issue by Akriti-S** [mitmproxy/mitmproxy#5975]
### Discussed in https://github.com/mitmproxy/mitmproxy/discussions/5974

<div type='discussions-op-text'>

<sup>Originally posted by **Akriti-S** March  8, 2023</sup>
hi, I have a setup where I have my host machine (which has burp)and through it I ssh or vnc to my testing machine in ec2 . Mitmdump is installed in another server which gets traffic forwarded from testing machine, it is working in regular proxy mode. In my burp suite (host machine)I provide upstream socks proxy as my testing ec2machine. Now if I try to test host header injection in target xyz.com from burpsuite. I get response from mitmproxy where I am not able to confirm whether my host header injection is working or not.

Also, I am not sure if in this setup I could test request smuggling. Please if someone could help here
![Uploading 2023-03-08 11_14_14-screenshot2.png…]()
</div>

**Comment by Prinzhorn** [comment]
> Discussed in #5974

Please don't open duplicate issues, this is what discussions are for.
