### ISSUE TITLE
mitmdump --quiet option not working

### ISSUE THREAD

**Issue by pwnstorm** [mitmproxy/mitmproxy#5979]
#### mitmdump --quiet option not working
I have tried everything to make mitmdump quiet but I still get info, warn logs.

#### Reproduce
I have run mitmdump using the below command
~/D/i/s/m/proxy [1]> mitmdump -s ./main.py --listen-port 8083 -q -k --flow-detail 0 --set flow_detail=0 --quiet
[08-03-23 14:57:02] [INFO] - HTTP(S) proxy listening at *:8083.
[08-03-23 14:57:09] [INFO] - client connect
[08-03-23 14:57:09] [INFO] - client connect
[08-03-23 14:57:09] [INFO] - client connect
[08-03-23 14:57:09] [INFO] - client connect
[08-03-23 14:57:09] [INFO] - server connect search16-normal-c-useast1a.tiktokv.com:443 (95.100.108.200:443)
[08-03-23 14:57:09] [INFO] - server connect api16-normal-c-useast1a.tiktokv.com:443 (95.100.108.200:443)

I have tried with all the options available to no avail.

#### System Information
Mitmproxy: 9.0.1
Python:    3.10.9
OpenSSL:   OpenSSL 3.0.8 7 Feb 2023
Platform:  Linux-6.1.12-arch1-1-x86_64-with-glibc2.37

**Comment by mhils** [comment]
`mitmdump -q` works as expected for me. Do you have anything in your `~/.mitmproxy/config.yaml`?

**Comment by pwnstorm** [comment]
No, I don't have that file. Here's my directory content for ~/mitmproxy/
~/.mitmproxy> ls -lah
total 32K
drwxr-xr-x  2 pwnstorm pwnstorm 4.0K Sep 12 08:07 ./
drwx------ 60 pwnstorm pwnstorm 4.0K Mar  8 11:08 ../
-rw-r--r--  1 pwnstorm pwnstorm 1.2K Sep 12 08:07 mitmproxy-ca-cert.cer
-rw-r--r--  1 pwnstorm pwnstorm 1015 Sep 12 08:07 mitmproxy-ca-cert.p12
-rw-r--r--  1 pwnstorm pwnstorm 1.2K Sep 12 08:07 mitmproxy-ca-cert.pem
-rw-------  1 pwnstorm pwnstorm 2.4K Sep 12 08:07 mitmproxy-ca.p12
-rw-------  1 pwnstorm pwnstorm 2.8K Sep 12 08:07 mitmproxy-ca.pem
-rw-r--r--  1 pwnstorm pwnstorm  770 Sep 12 08:07 mitmproxy-dhparam.pem

**Comment by mhils** [comment]
Thanks. Running exactly the command you posted (after `touch`ing main.py) produces absolutely no output for me, both on main and on 9.0.1...

**Comment by TrevorChan1** [comment]
-q is also not working for me

**Comment by Nowi5** [comment]
I have the same issue. I Although -q gives overall less output, it still shows the certificates errors which I like to ignore in my special case.

**Comment by RyanKung** [comment]
Same issue for me
```
./mitmproxy --version
Mitmproxy: 10.3.1 binary
```
