### ISSUE TITLE
webhook question

### ISSUE THREAD

**Issue by dweinstein** [mitmproxy/mitmproxy#598]
I'm interested in a webhook to auto build a docker container with mitmproxy in it. are you guys willing to create one for me so I can keep [this](https://github.com/dweinstein/dockerfile-mitmproxy) in sync? Other than setting up an rss reader to do this I'm not sure of another way to do this on github.

alternatively if you guys want to have an official docker image I'd bad glad to contribute to that as well! :-P

**Comment by dweinstein** [comment]
well I found an alternative way to do this using zapier (and the release.atom for the project) to trigger the docker auto builder. closing this.

but let me know if you guys want an official docker image :-)

**Comment by cortesi** [comment]
Hi David. Adding a Docker recipe and an official image in the registry has been on my todo list for ages - if you're happy to contribute this, I'd be delighted!

**Comment by cortesi** [comment]
To clarify, I'm suggesting that we bring that docker repo into the official mitmproxy repo, and support it as part of the base. :)

**Comment by johnmccabe** [comment]
There are already a number of build repos on docker hub for mitmproxy in command line mode, I'd added one for mitmweb for which I've just been updating the source github repo with the latest release tag to build - installs from the repos on github rather than PyPI.

https://registry.hub.docker.com/u/johnmccabe/mitmweb/

You're more than welcome to pull it in if you wish.

**Comment by dweinstein** [comment]
@cortesi that would be perfectly fine. if we do this I have some other suggestions like using the docker registry for auto builds and making sure we have tagged container builds so it's easy to use an older mitmproxy version to load flows exported by older mitmproxy versions...

would be happy to work with you on this

**Comment by cortesi** [comment]
@johnmccabe Great - that's very useful. We'll have an official docker repo in the organisation soon, at which points we'll unify all of the ideas people have been working on. Fun times.

**Comment by dweinstein** [comment]
#611
