### ISSUE TITLE
Add prettier to mitmweb

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#5984]
This came up in https://github.com/mitmproxy/mitmproxy/pull/5983 . I didn't realized how inconsistently formatted the mitmweb sources are.

Examples:

Mixed single/double quotes

https://github.com/mitmproxy/mitmproxy/blob/884fd60e26b8beaa3785ea3d708c2d4386707f93/web/src/js/components/FlowView.tsx#L36-L49

Inconsistent indentation:

https://github.com/mitmproxy/mitmproxy/blob/884fd60e26b8beaa3785ea3d708c2d4386707f93/web/src/js/flow.ts#L106-L115

https://prettier.io/ is the de facto standard nowadays and I think we should just let it run over the entire code once and then add it to autofix. Objections @mhils ?

**Comment by mhils** [comment]
Sounds good to me, happy to have that added to the autofix job. :)

**Comment by alexgershberg** [comment]
Hi, this seemed fairly straightforward, so I took a crack at it.

Do we want to run prettier on the entire repo, or just on files under `mtimproxy/web/`? (I would guess just the `web/`, but I noticed that some other parts of the repo have .js and .html files)

**Comment by alexgershberg** [comment]
Hi, I don't have much experience with open source, but this seemed fairly straightforward and I decided to take a crack at this.

You can assign this issue to me, I've already tried this locally and am almost finished with this. (Just need to test the change to autofix ci)

**Comment by chiragbiradar** [comment]
Hello @Prinzhorn  @mhils , I noticed this issue and I would be interested in working on it. Could you please assign it to me?
