### ISSUE TITLE
Changing proxy credentials for upstream proxy. Missing 'Proxy-Authorization' header in HTTPS request

### ISSUE THREAD

**Issue by PATAPOsha** [mitmproxy/mitmproxy#5998]
#### Problem Description
I want to dynamically change upstream proxy depending on auth data I connect to my MITM proxy server. Everything seem work, but only for HTTP requests, when I try same with HTTPS requests - there is no 'Proxy-Authorization' header inside request.

#### Steps to reproduce the behavior:
1. Create addon for reading and modifying request proxy auth data:
`my_addon.py`
```
import re
import base64
import mitmproxy.http
from mitmproxy.net.server_spec import ServerSpec


class MyAddon:
    def __init__(self):
        self.num = 0

    def requestheaders(self, flow: mitmproxy.http.HTTPFlow):
        # flow.server_conn.via = ServerSpec('http', ('127.0.0.1', 8994))
        
        # Read proxy auth data passed to connect to MITM proxy server - MITM_USER:MITM_PASS
        proxy_auth_b64 = flow.request.headers["Proxy-Authorization"]
        proxy_auth_b64 = proxy_auth_b64.split("Basic ")[1]
        proxy_auth = base64.b64decode(proxy_auth_b64).decode()
        username, password = proxy_auth.split(":")
        flow.metadata["mitm_auth"] = (username, password)
        print(f"requestheaders(): proxy_auth={proxy_auth}")

    def request(self, flow: mitmproxy.http.HTTPFlow):
        # Read proxy auth data passed to connect to UPSTREAM proxy server - UPSTREAM_USR:UPSTREAM_PASSW
        proxy_auth_b64 = flow.request.headers["Proxy-Authorization"]
        proxy_auth_b64 = proxy_auth_b64.split("Basic ")[1]
        proxy_auth = base64.b64decode(proxy_auth_b64)
        print(f"request(): proxy_auth={proxy_auth}")

        # Set another user/password for connecting to UPSTREAM proxy server
        new_proxy_auth = "UPSTREAM_USR_2:UPSTREAM_PASSW_2"
        new_proxy_auth_b64 = base64.b64encode(new_proxy_auth.encode()).decode()
        flow.request.headers["Proxy-Authorization"] = f"Basic {new_proxy_auth_b64}"
        return
 
 addons = [MyAddon()]
```
2. Start MITM proxy server using script
`run_debug.py`
```
from mitmproxy.tools.main import mitmdump

mitmdump(args=[
    "-s", "my_addon.py",
    "--mode", "upstream:http://UPSTREAM_HOST:UPSTREAM_PORT",
    "--upstream-auth", "UPSTREAM_USR_1:UPSTREAM_PASSW_1"
])
```
3. Test request for comparing final IP address
```
import requests

PROXY = "http://MITM_USER:MITM_PASSW@127.0.0.1:8080"
PROXIES = {
    "http": PROXY,
    "https": PROXY,
}

if __name__ == '__main__':
    r = requests.get("https://ipinfo.io/json", proxies=PROXIES, verify=False)
    print(r.status_code)
    print(r.text)
    print(r.headers["count"])
```

Everything works fine with "http://ipinfo.io/json". I can read and modify `flow.request.headers["Proxy-Authorization"]` and final IP is matching what I set inside `MyAddon.request()`.
But when I try to request "https://ipinfo.io/json" - there is no `flow.request.headers["Proxy-Authorization"]` header. Even if try to set it - it is ignored and final IP always matches what was set in `--upstream-auth` param of server start command.

Maybe there is another way for dynamically changing auth params for separate request inside addon for `HTTPS` requests?
Also, in my case I always have same UPSTREAM_HOST and UPSTREAM_PORT, but what if I need to change them from what I set in `--mode upstream:http://...`?

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 9.0.1
Python: 3.9.13
OpenSSL: OpenSSL 3.0.7 1 Nov 2022
Platform: macOS-12.4-arm64-arm-64bit

**Comment by PATAPOsha** [comment]
I finally found how to change UPSTREAM auth credentials both for HTTPS and HTTP requests inside addon.
First mistake was passing `--upstream-auth` param to start command.
So, my start command looks like:
```
mitmdump -s proxy_auth.py --set confdir=.mitmproxy --mode upstream:http://{UPSTREAM_HOST}:{UPSTREAM_PORT}
```

Then I had to split the logic for HTTP and HTTPS requests. 
For HTTP requests, you can read mitmproxy auth credentials (MITM_USER:MITM_PASSW) and override `flow.request.headers["Proxy-Authorization"]` with new UPSTREAM credentials inside `requestheaders()` event. `http_connect()` and `http_connect_upstream()` are not fired on HTTP requests, besides seems like documentation states that it should https://docs.mitmproxy.org/stable/api/events.html#HTTPEvents.http_connect_upstream. 

For HTTPS requests, you can read mitmproxy auth credentials (MITM_USER:MITM_PASSW) in `http_connect()` event. And set UPSTREAM auth credentials in `http_connect_upstream()`.
However, `flow.metada` is not shared between `http_connect()` and`http_connect_upstream()`, so it would be inconvenient to change UPSTREAM creds depending on MITM creds... Probably to create some additional structure/dict inside addon `__init__` and store mapping for `request` -> `initial MITM auth creds`.
 
proxy_auth.py:
```
import base64
import time

from mitmproxy.http import Response, Headers
import mitmproxy.http
from mitmproxy.exceptions import FlowReadException, AddonHalt


class ProxyAuthAddon:
    @staticmethod
    def _parse_proxy_auth_header(flow: mitmproxy.http.HTTPFlow):
        if not flow.request.headers.get("Proxy-Authorization"):
            return None, None
        proxy_auth_b64 = flow.request.headers["Proxy-Authorization"]
        proxy_auth_b64 = proxy_auth_b64.split("Basic ")[1]
        proxy_auth = base64.b64decode(proxy_auth_b64).decode()
        username, password = proxy_auth.split(":")
        return username, password

    def http_connect(self, flow: mitmproxy.http.HTTPFlow):
        # Only for HTTPS requests. Read auth credentials for connection to mitmproxy
        username, password = self._parse_proxy_auth_header(flow)
        if username and password:
            flow.metadata["mitm_auth"] = (username, password)
        print(f"http_connect(): mitm_proxy_auth={(username, password)}")

    def http_connect_upstream(self, flow: mitmproxy.http.HTTPFlow):
        # Only for HTTPS requests. Set another username/password for connecting to UPSTREAM proxy server
        new_proxy_auth = "MITM_USER_2:MITM_PASSW_2"
        new_proxy_auth_b64 = base64.b64encode(new_proxy_auth.encode()).decode()
        flow.request.headers["Proxy-Authorization"] = f"Basic {new_proxy_auth_b64}"

    def requestheaders(self, flow: mitmproxy.http.HTTPFlow):
        if flow.request.scheme == "http":
            # Only for HTTP requests. Read proxy auth credentials passed to connect to MITM proxy server - MITM_USER:MITM_PASS
            username, password = self._parse_proxy_auth_header(flow)
            if username and password:
                flow.metadata["mitm_auth"] = (username, password)
            print(f"requestheaders(): mitm_proxy_auth={(username, password)}")


            # Set another user/password for connecting to UPSTREAM proxy server
            new_proxy_auth = "MITM_USER_2:MITM_PASSW_2"
            new_proxy_auth_b64 = base64.b64encode(new_proxy_auth.encode()).decode()
            flow.request.headers["Proxy-Authorization"] = f"Basic {new_proxy_auth_b64}"



addons = [ProxyAuthAddon()]

```

**Comment by cubimon** [comment]
If you think about it, it makes totally sense, `http_connect_upstream` only works for CONNECT which is used for https, for http only the request goes directly to the proxy with the hostname of the target server, so you have to set the authorization header directly and the proxy ofc has to remove the header

**Comment by cubimon** [comment]
Here is my simplified example:
```python

proxy1_auth = <...>

def proxy_address(flow: http.HTTPFlow):
    # TODO: determine proxy on whatever condition you like
    if flow.request.host == '*.google':
        return None
    return ("<proxyhost>", 8081), proxy1_auth

def http_connect_upstream(flow: http.HTTPFlow):
    _, auth = proxy_address(flow)
    if auth:
        flow.request.headers["Proxy-Authorization"] = auth

def request(flow: http.HTTPFlow) -> None:
    result = proxy_address(flow)
    address = None
    auth = None
    if result:
        address, auth = result
    if address:
        flow.server_conn.via = ServerSpec(("http", address))
        if flow.request.scheme == 'http' and auth is not None:
            # for http only, set proxy authorization directly
            flow.request.headers["Proxy-Authorization"] = auth
    else:
        flow.server_conn = Server(address=flow.server_conn.address)
```

**Comment by J-Fellouse** [comment]
I wanted to do exactly the same as you, change the upstream proxy according to the authentication username of the mitmproxy proxy but the “Proxy-Authorization” header seemed non-existent when I tried to retrieve it.

I think mitmproxy removes it automatically to avoid transmitting a request with this header to the end server, as specified in the documentation: "Authentication headers are stripped from the flows, so they are not passed to upstream servers."

![Image](https://github.com/user-attachments/assets/b5275b95-58b9-4a81-8148-cc3f2bf6f1cc)

**To retrieve the authentication username and password, you can simply do**:
```python
def request(self, flow: http.HTTPFlow) -> None:
    proxyAuthUsername = flow.metadata["proxyauth"][0]
    proxyAuthPassword = flow.metadata["proxyauth"][1]
```

You also need to launch mitmproxy with these arguments "--proxyauth any".
