### ISSUE TITLE
Script in mitm-web won't unload

### ISSUE THREAD

**Issue by binbard** [mitmproxy/mitmproxy#6002]
#### Problem Description
We can't remove a loaded script in running mitm-web.
The scripts option for executing a script with mitm-web seems to have a bug.

Note: If we specify multiple scripts to be executed, then if we intend to remove them, one script remains present and cant be unloaded

#### Steps to reproduce the behavior:
1. In a running mitm-web instance, go to Options > Scripts > add path to script.
2. Try removing, the script, it won't remove. It simply says "no such script" even when removing.
3. Add more scripts. All can be removed except one.

Applying script
![chrome_Qy0rYZw6QZ](https://user-images.githubusercontent.com/28684962/226761750-cc220b58-2b5d-4af1-a5a2-cb4da8478ae9.png)

Error: No such script, on removing it
![chrome_tIZ1HoQ2Km](https://user-images.githubusercontent.com/28684962/226761900-fccc9584-515f-4165-9530-bb3e68f934ca.png)

Should be removed like this: no errors
![chrome_4FAF27syxE](https://user-images.githubusercontent.com/28684962/226761924-b72db2f3-2cdc-492c-8028-c633083975ae.png)

#### System Information
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Windows-10-10.0.22621-SP0

**Comment by lups2000** [comment]
@mhils I can have a look if possible! the problem here is just the string "No such script" that should be there when the input is empty?

**Comment by mhils** [comment]
Based on the error message I think we are currently telling the backend to load a script named `""` (empty string), and the backend rightfully complains about that. We shouldn't be telling the backend that. Does that make sense?

Editing options in mitmweb is quite a hack at the moment, don't expect that there is a lot of justification for any particular decision. 😄

**Comment by lups2000** [comment]
makes sense yes, okay I'll have a look! Yes I've noticed :)
