### ISSUE TITLE
Metadata is not passed from http_connect() and http_connect_upstream() HTTP Events.

### ISSUE THREAD

**Issue by PATAPOsha** [mitmproxy/mitmproxy#6006]
#### Problem Description
Metadata is not passed from `http_connect()` and `http_connect_upstream()` HTTP Events.

#### Steps to reproduce the behavior:
I hook every event from HTTP Events in the order they fire during the request. In every event, I modify `flow.metadata` and expect on every further step to read `metadata` from the previous event. This logic starts to work as expected only starting from `requestheaders()`. Metadata is not passed from `http_connect()` to `http_connect_upstream()`, and
from `http_connect_upstream()` to `requestheaders()`

I run mitmproxy in upstream mode using: 
`mitmdump -s test_meta.py --set confdir=.mitmproxy --set upstream_cert=false --mode upstream:http://$UPSTREAM_HOST:$UPSTREAM_PORT --upstream-auth $UPSTREAM_USERNAME:$UPSTREAM_PASSWORD`

Here is my addon for testing:
```
import mitmproxy.http
import mitmproxy.connection
import mitmproxy.proxy.server_hooks


class TestMetaAddon:
    def client_connected(self, client: mitmproxy.connection.Client, *args, **kwargs):
        print(f"client_connected")
        return

    def server_connect(self, data: mitmproxy.proxy.server_hooks.ServerConnectionHookData, *args, **kwargs):
        print(f"server_connect")
        return

    def http_connect(self, flow: mitmproxy.http.HTTPFlow):
        print(f"http_connect: {flow.metadata}")
        flow.metadata["http_connect()"] = 1

    def http_connect_upstream(self, flow: mitmproxy.http.HTTPFlow):
        print(f"http_connect_upstream: {flow.metadata}")
        # Comment failed asserts
        # assert flow.metadata["http_connect()"] == 1

        flow.metadata["http_connect_upstream()"] = 2

    def requestheaders(self, flow: mitmproxy.http.HTTPFlow):
        print(f"requestheaders: {flow.metadata}")
        # Comment failed asserts
        # assert flow.metadata["http_connect()"] == 1
        # assert flow.metadata["http_connect_upstream()"] == 2

        flow.metadata["requestheaders()"] = 3

    def request(self, flow: mitmproxy.http.HTTPFlow):
        print(f"request: {flow.metadata}")
        assert flow.metadata["requestheaders()"] == 3

        flow.metadata["request()"] = 4

    def responseheaders(self, flow: mitmproxy.http.HTTPFlow):
        print(f"responseheaders: {flow.metadata}")
        assert flow.metadata["request()"] == 4

        flow.metadata["responseheaders()"] = 5

    def response(self, flow: mitmproxy.http.HTTPFlow):
        print(f"response: {flow.metadata}")
        assert flow.metadata["requestheaders()"] == 3
        assert flow.metadata["request()"] == 4
        assert flow.metadata["responseheaders()"] == 5

        flow.metadata["response()"] = 6


addons = [TestMetaAddon()]
```

#### System Information
Mitmproxy: 9.0.1
Python:    3.10.4
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  macOS-12.4-arm64-arm-64bit

**Comment by mhils** [comment]
These two hooks work with a separate flow object, and metadata is not shared between them. See https://docs.mitmproxy.org/stable/api/events.html. That's kind of by design. What are you looking to accomplish?

**Comment by PATAPOsha** [comment]
And my described flow works with mitmproxy, but only for HTTP requests, not for HTTPS. As described here https://github.com/mitmproxy/mitmproxy/issues/5998

**Comment by PATAPOsha** [comment]
I ended up with patching `flow.cleint_connect` in `http_connect()`. It seems to be only one param that is same between `http_connect()` and `http_connect_upstream()`

```
    def http_connect(self, flow: mitmproxy.http.HTTPFlow):
        """
        Only for HTTPS requests.
        Read auth credentials for connection to mitmproxy

        :param flow:
        :return:
        """
        username, password = self._parse_proxy_auth_header(flow)
        if not self._validate_mitm_auth(username, password):
            return self.return_mitm_auth_required_response(flow)

        # patch `flow.client_conn` in order to pass `mitm_auth` to `http_connect_upstream()`event
        setattr(flow.client_conn, "mitm_auth", (username, password))
        logging.debug(f"http_connect(): mitm_auth={(username, password)}")
    
    def http_connect_upstream(self, flow: mitmproxy.http.HTTPFlow):
        # Only for HTTPS requests. Set another username/password for connecting to UPSTREAM proxy server
        if hasattr(flow.client_conn, "mitm_auth"):
            mitm_user, mitm_passw = getattr(flow.client_conn, "mitm_auth")
            self.set_upstream_proxy_auth(flow, mitm_user)
```

**Comment by iamkhalidbashir** [comment]
> These two hooks work with a separate flow object, and metadata is not shared between them. See https://docs.mitmproxy.org/stable/api/events.html. That's kind of by design. What are you looking to accomplish?

Wonder why is this by design
I want to pass some data from http_connect to requestheaders too

**Comment by iamkhalidbashir** [comment]
This should be open until this feature/fix is shipped

**Comment by mhils** [comment]
> Wonder why is this by design

Because it's a different request/response pair, and each flow corresponds to one request/response pair.

> I want to pass some data from http_connect to requestheaders too

As mentioned above, the recommended way to do this right now is to use a `WeakKeyDictionary` with `ClientConnection` as key (see the proxyauth addon above).
