### ISSUE TITLE
Broken command argument type parsing

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#6029]
#### Problem Description

It seems like our command argument type parsing does not like `from __future__ import annotations`.

#### Steps to reproduce the behavior:

1. `mitmproxy`
2. `[n] [enter] [r]`

**Comment by wesolowski-gh** [comment]
`from __future__ import annotations` breaks  `inspect.signature` More info details here: https://bugs.python.org/issue43355
Python 3.10 adds `eval_str=` argument to `inspect.signature()` that lets you evaluate string annotations.
I will submit a PR that fixes commands signature evaluation.

**Comment by wesolowski-gh** [comment]
@mhils Thanks for the quick reaction!

**Comment by mhils** [comment]
Thank you for the super quick fix, highly appreciated! 🍰
