### ISSUE TITLE
Compatibility with newer versions of `cryptography`.

### ISSUE THREAD

**Issue by MatrixManAtYrService** [mitmproxy/mitmproxy#6051]
Firstly, I just discovered `mitmproxy` and I'm pretty excited to make use of it.  Thank you for maintaining it.

#### Problem Description

I'm trying to use mitmproxy as part of an integration test in a project that depends on `cryptography`, specifically version `40.0.0`.  I see that mitmproxy requires cryptography at `<38.1`.  I can automate the creation of a separate venv for the mitmproxy stuff, but that's kind of clunky.  I'd rather just make it a dependency and let poetry handle it.  For that to happen, `mitmproxy` needs to be compatible with higher versions of cryptography.

I recognize that the `<38.1` constraint might be there for a good reason, but not knowing that reason I figured I'd file an issue and cross my fingers.  Thanks for at least considering it.

#### Steps to reproduce the behavior:

1. Have a `pyproject.toml` like this:
```
...

[tool.poetry.dependencies]
python = "^3.10"
cryptography = "^40.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

2. Run `poetry add mitmproxy`
3. See error:
```
Because no versions of mitmproxy match >9.0.1,<10.0.0
 and mitmproxy (9.0.1) depends on cryptography (>=38.0,<38.1), mitmproxy (>=9.0.1,<10.0.0) requires cryptography (>=38.0,<38.1).
So, because foo depends on both cryptography (^40.0.0) and mitmproxy (^9.0.1), version solving failed.
```

#### System Information
```
Mitmproxy: 9.0.1
Python:    3.10.9
OpenSSL:   OpenSSL 1.1.1s  1 Nov 2022
Platform:  Linux-5.15.86-x86_64-with-glibc2.35
```

**Comment by Prinzhorn** [comment]
We already upgraded, you have to wait for the next release.

https://github.com/mitmproxy/mitmproxy/blob/be02b1e298dfb1b218007f824c4cf345c53b0cee/pyproject.toml#L37
https://github.com/mitmproxy/mitmproxy/commit/8c6ec5cb56fbf4961806ed27b4974c440df59e87

https://github.com/search?q=repo%3Amitmproxy%2Fmitmproxy+cryptography&type=issues
https://github.com/mitmproxy/mitmproxy/issues/5966

Feel free to re-open if I miss something. I have no idea what `poetry` is.

**Comment by Prinzhorn** [comment]
https://github.com/mitmproxy/mitmproxy/issues/5966#issuecomment-1455045917

> I don't think either of the posted vulnerabilities affects mitmproxy users in a significant way, so I don't think we will ship a patch release just for that. :)

**Comment by FrugalGuy** [comment]
@Prinzhorn Do you have a target date for the next release?  Our customers in regulated industries (banking, federal, etc.) are prohibited by regulations from using s/w with known High and Critical severity vulnerabilities. I'm trying to formulate our case for waiting, but need some kind of target date.

**Comment by mhils** [comment]
@FrugalGuy: If you are interested in timely patch releases to fix your company's compliance requirements, I'm happy to set up a support contract. Email is on my profile. :-)

**Comment by zorrobyte** [comment]
> @Prinzhorn Do you have a target date for the next release? Our customers in regulated industries (banking, federal, etc.) are prohibited by regulations from using s/w with known High and Critical severity vulnerabilities. I'm trying to formulate our case for waiting, but need some kind of target date.

Yeah, no, also, welcome to the front page of Hacker News, IBM! It bet the optics look great with the controversy around Red Hat. I worked at IBM for seven years after my startup was acquired and can say; IBM has a terrible track record of monetizing FOSS and ruining it for the source projects.

May want to do some reflection and check into IBM's SLA agreements and support contracts before accusing others of "thinly veiled extortion".

Why don't you log back into ServiceNow and let these customers (and surely, the uncoordinated internal IBM teams fighting) know that IBM is at fault here and that `mitmproxy` awaits your team's PRs?

**Comment by mhils** [comment]
Since this has been picked up by some news sites I'd like to provide some additional context here: I don't mind the release question at all, it's valid! But the context should ideally be along the lines of "we have an interest in this, how can we help make it happen" (contributions or $) and not "you are causing problems for our customers". I don't want the requestor to have a miserable time because of a badly-worded comment, I want large companies to have a healthy relationship with FOSS.

**Comment by mhils** [comment]
@FrugalGuy has just sent me genuine apology, which I truly appreciate. Please be nice and assume good intentions. ❤
