### ISSUE TITLE
Disable mouse interactions (or allow selecting text)

### ISSUE THREAD

**Issue by gajus** [mitmproxy/mitmproxy#606]
Is there a way to disable mouse interactions? It makes it impossible to select the test displayed on the screen (iTerm2, OSX), e.g. I cannot perform simple operations, such as copying a URL.

**Comment by cortesi** [comment]
Hi there. Are you using a recent checkout from master (i.e. one from the last day)? You can select text with mouse interaction enabled by holding down a modifier key (different key for different platforms - command on my Mac). Yes, this is slightly obscure, but as of yesterday we detect attempts to select and actually give users a hint in the interface. I want to avoid including a special flag to turn off mouse interaction, if this is clear enough.

**Comment by gajus** [comment]
I don't that mouse interactions should be part of a CLI program to begin with. Most people running CLI program will never lift their hands from keyboard just to select something that would take few keyboard strokes.

That said, if there is a new build that at least allows to select screen on text using a modifier key, that at least is going to work. Nevertheless, I expect many people reporting this as an inconvenience.

Thank you

**Comment by cortesi** [comment]
You can use the modifier keys on any recent build - we've just added a hint to let you know that you need to use the modifier keys in the release that's on the way out the door. This release also includes things like being able to scroll with the scrollbar, click to select flows, and so forth - that is, some of the features we think justifies the inconvenience. 

As for wether a CLI program should include mouse interaction - I'm not so sure. Believe me, I'm as fanatical as anyone about keyboard interaction (to the extent that I wrote qtile.org specifically so I never needed to touch a mouse), but here I think it pays dividends. The truth is that most people use mitmproxy on their workstations, and being able to do things like scroll through flows with the scrollwheel is very convenient. Never fear - mitmproxy's keyboard interaction will always remain very strong.

**Comment by gajus** [comment]
This is surprisingly troublesome. I think that the right approach should have been to break the mitmproxy into two separate programs:

1. One acting as a mere API that encompasses all the mitmproxy functionality
2. Second a CLI tool as it has been using the underlying API

Then, suppose you insist to keep the mouse interactions, have a separate program using the latter API that provides UI. Added benefit is that it would allow community to build custom interfaces to mitmproxy. Now you have a quasi CLI tool and no proper UI for people who prefer pointer interactions. Both camps lose.

**Comment by cortesi** [comment]
Do you mean it's surprisingly troublesome that you have to press a modifier key to select, or have you found an issue that means it doesn't work? 

The architecture you describe is in fact exactly the one mitmproxy has - mitmproxy, mitmdump and the soon-to-be-released mitmweb are all just front-ends onto the same proxying back-end.

**Comment by mogui** [comment]
It's quite annoyning, beside the fact that I'm on OS X El capitain and no modifier key allows me to select :( don't know what could be?

**Comment by davidmoser** [comment]
Same for me, on OS X none of the listed modifiers work.

Instead you have to press the 'fn' button to be able to select and copy.

**Comment by kennytm** [comment]
In case anybody hit here from Google, you could disable mouse interaction temporarily via (#735):

```sh
mitmproxy --no-mouse
```

You could also write the option to the configuration file to permanently disable it.

```sh
echo no-mouse >> ~/.mitmproxy/mitmproxy.conf
```

cc #647.

**Comment by benpbolton** [comment]
`--no-mouse` is deprecated, can use `--set console_mouse=false` inline

**Comment by gslin** [comment]
Also, in the latest version (after https://github.com/mitmproxy/mitmproxy/pull/5393), the name of config file has been changed to `config.yaml` or `config.yml`, and you may set `console_mouse` to `false` accordingly:

```yaml
console_mouse: false
```
