### ISSUE TITLE
UI: Navigation: Additionally allow Esc-key to navigate back.

### ISSUE THREAD

**Issue by Semnodime** [mitmproxy/mitmproxy#6085]
#### Problem Description
First time using mitmproxy instead of mitmweb:
I intuitively tried navigating back to the flow list (initial view) after entering the view of a single flow using <kbd>Esc</kbd>.

#### Proposal
Additionally to <kbd>q</kbd> allow to use <kbd>Esc</kbd> to navigate back.

**Comment by mhils** [comment]
That's a good keybind suggestion. 👍
