### ISSUE TITLE
Toggling follow new option fails in single flow view.

### ISSUE THREAD

**Issue by Semnodime** [mitmproxy/mitmproxy#6086]
#### Problem Description
Toggling follow new flow option via <kbd>F</kbd> does not work while in the view of a single flow.

#### Steps to reproduce the behavior:
1. launch mitmproxy
2. continually generate new requests
3. activate `Follow new` option
4. enter a flow
5. try to deactivate `Follow new` option
6. error: the view still follows the new flows

#### System Information
mitmproxy version 9.0.1

**Comment by mhils** [comment]
Given that we don't use `F` for something else at the moment, I would be fine with also assigning it to `Follow new` in the individual flow view. PRs welcome!
