### ISSUE TITLE
mtimproxy Transparent mode failure: FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by shiwenThu** [mitmproxy/mitmproxy#6092]
#### Problem Description
I used iptables + mitmproxy transparent mode to listen to the network behavior of Linux 1. Mitmproxy is run on Linux2.

#### Steps to reproduce the behavior:
Linux1：
sudo iptables -t nat -A OUTPUT -p tcp --dport 80 -j DNAT --to 8.218.192.40:80
sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -j DNAT --to 8.218.192.40:443

Linux2 （where the mitmproxy works）:
sudo iptables -t nat -F
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -w net.ipv4.conf.all.send_redirects=0
nohup sudo mitmdump --mode transparent --set block_global=false -p 80 &
nohup sudo mitmdump --mode transparent --set block_global=false -p 443 &

Linux2 report：
Transparent mode failure: FileNotFoundError(2, 'No such file or directory’)

#### System Information
Mitmproxy: 5.3.0
Python:    3.7.16
OpenSSL:   OpenSSL 1.1.1h  22 Sep 2020
Platform:  Linux-5.4.0-137-generic-x86_64-with-debian-bullseye-sid

**Comment by Prinzhorn** [comment]
Please stop opening issues https://github.com/mitmproxy/mitmproxy/discussions/6089
