### ISSUE TITLE
mitmproxy transparent mode reports connection failed

### ISSUE THREAD

**Issue by shiwenThu** [mitmproxy/mitmproxy#6093]
Problem Description
I used iptables + mitmproxy transparent mode to listen to the network behavior of Linux 1. Mitmproxy is run on Linux2.

Linux1：
sudo iptables -t nat -A OUTPUT -p tcp --dport 80 -j DNAT --to 8.218.192.40:80
sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -j DNAT --to 8.218.192.40:443

Linux2 （where the mitmproxy works）:
sudo iptables -t nat -F
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv6.conf.all.forwarding=1
sudo sysctl -w net.ipv4.conf.all.send_redirects=0
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo ip6tables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8080
mitmdump --mode transparent --set block_global=false

Linux2 report：
116.62.227.220:35524: Server connection to ('172.25.143.177', 443) failed: Error connecting to "172.25.143.177": [Errno 111] Connection refused

where the 116.62.227.220 is the ip of linux1
8.218.192.40 is the ip of linux2
172.25.143.177 is the inet ip of linux2

System Information
Mitmproxy: 5.3.0
Python: 3.7.16
OpenSSL: OpenSSL 1.1.1h 22 Sep 2020
Platform: Linux-5.4.0-137-generic-x86_64-with-debian-bullseye-sid

**Comment by Prinzhorn** [comment]
Please stop opening issues https://github.com/mitmproxy/mitmproxy/discussions/6089

**Comment by shiwenThu** [comment]
I followed the instructions step by step but ran into these problems. It bothers me a lot in the past days and almost drives me crazy. Here I am asking for help, and you just close the issue and say "stops opening issues" without answering it?

Excuse me???

**Comment by shiwenThu** [comment]
Could you please give some hints before you closing the issue? @Prinzhorn

**Comment by Prinzhorn** [comment]
I haven't look into your issue at all, I was just cleaning up the duplicates you've opened (the discussion you've opened is still open). I would recommend trying with the latest version, 5.3.0 is very old. This doesn't look like a bug in mitmproxy to me, hence why discussions are the correct place to ask.
