### ISSUE TITLE
Install fails in Rocky Linux 9.1

### ISSUE THREAD

**Issue by ThomasBucaioni** [mitmproxy/mitmproxy#6111]
In a VM freshly installed with Rocky Linux 9.1 (blue onyx), the installation fails:
- `zipp-x.xx.x-py3-none-any.whl` is never compatible
- several `altgraph-0.x.y.tar.gz` fail: 
   - SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
   - FileNotFoundError: [Errno 2] No such file or directory: 'ReadMe.txt'
   - FileNotFoundError: [Errno 2] No such file or directory: 'doc/changelog.rst'

Connecting with `ssh -X`, firefox starts. The iso is the minimal one: https://rockylinux.org/download/

**Comment by ThomasBucaioni** [comment]
Same with the DVD iso image after graphical mode install

**Comment by ThomasBucaioni** [comment]
The install works on the `ubuntu-22.04.2-desktop-amd64` [iso image](https://ubuntu.com/download/desktop) and tox tests pass: `1595 passed, 25 warnings in 31.71s`

**Comment by mhils** [comment]
This is a development install? I don't know if we want to support RHEL and its derivatives here... Our precompiled binaries work on Rocky Linux, right?

**Comment by ThomasBucaioni** [comment]
The binaries work well indeed, as provided on the [main](https://mitmproxy.org/) page. The library `libstdc++.so.6` is not available for Firefox but nothing to do with mitmproxy
