### ISSUE TITLE
Its dependent component 'ruamel.yaml.clib' cannot be installed

### ISSUE THREAD

**Issue by huidaoweilai2024** [mitmproxy/mitmproxy#6112]
Building wheels for collected packages: ruamel.yaml.clib  Building wheel for ruamel.yaml.clib (pyproject.toml) ... error                                                  error: subprocess-exited-with-error                   
  × Building wheel for ruamel.yaml.clib (pyproject.toml) did not run successfully.                                │ exit code: 1                                          ╰─> [337 lines of output]                                   /data/data/com.termux/files/usr/tmp/pip-build-env-6rxxupp5/overlay/lib/python3.11/site-packages/setuptools/dist.py:955: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated.
      !!                                                
        Please replace its usage with implicit namespaces (PEP 420).                                                                                                            See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages for details.                                                               

      !!
        ep.load()(self, ep.name, value)
      /data/data/com.termux/files/usr/tmp/pip-build-env-6rxxupp5/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.

**Comment by boycy815** [comment]
ruamel.yaml version 0.17.21 is good for me.
run
```
pip install ruamel.yaml==0.17.21
``` 
before install mitmproxy

**Comment by huidaoweilai2024** [comment]
Install the latest version of python and its dependencies
'ruamel.yaml.clib' cannot be installed
environment Termux

**Comment by phanirithvij** [comment]
See https://sourceforge.net/p/ruamel-yaml-clib/tickets/22/
