### ISSUE TITLE
Warn new users about the lazy creation of connections (when requests are expected to be served in the script fully and only)

### ISSUE THREAD

**Issue by Semnodime** [mitmproxy/mitmproxy#6115]
#### Problem Description
The [example script](https://docs.mitmproxy.org/stable/addons-examples/#http-reply-from-proxy) for not sending any data to the server does not prevent mitmproxy from **establishing a connection** to the server.
For which reason is said connection established when no data has to be sent to this host right away and possibly never in the future?
I trusted mitmproxy to **not send _any_ data, as stated**, but I had to discover (the hard way) that **that's not the case**.
I used mitmproxy in an environment where it required to stay silent, but it wasn't compliant.

Could you please consider warning new users about this behavior?
<strike>Is there an easy way to prevent establishing connections?
Is it planned to do so on default in this case?</strike>
*EDIT*:  Trying to prevent connections by rerouting the connection to a closed port killed the flow for the client. Routing to a different host with invalid certificate worked though, warning me in the event log and suggesting setting connection strategy to lazy and it worked.

#### Steps to reproduce the behavior:
1. Load the example script
2. Have the client request examle.com
3. View the event log

#### System Information
Mitmproxy: 9.0.1
Python:    3.10.6
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.0-71-generic-x86_64-with-glibc2.35

**Comment by Prinzhorn** [comment]
You can use `--set connection_strategy=lazy` to prevent this behavior, see https://docs.mitmproxy.org/stable/concepts-options/#connection_strategy for more details

> Could you please consider warning new users about this behavior?

I think we could add a comment to the example script mentioning this? Not sure where else you would expect this warning.
