### ISSUE TITLE
Choose store/forward or streaming behavior for file download

### ISSUE THREAD

**Issue by Lingxi-Li** [mitmproxy/mitmproxy#6125]
#### Problem Description

mitmproxy buffers server (TCP) segments until a whole (HTTP) PDU has been received and then forward all segments to client in a burst. I understand this store and forward behavior is necessary for interception/modification at a higher PDU level. However, it creates an issue for file download that takes a considerable amount of time. Without proxy, browser would show a progress bar. With proxy, due to the store and forward behavior, browser will hang without progress bar, and then finish all at once. On mitmproxy side, UI shows "content missing" without any progress information before all data has been received. This is not ideal behavior, particularly for large file download.

#### Proposal

We should be able to turn off store and forward behavior for data part based on headers like `content-type` and `content-length`. That is, buffer and receive full header part, and then decide whether to store/forward or stream following data part based on the metadata in headers. It's unlikely that one will want to intercept/modify `content-type: application/octet-stream` with a large `content-length`. Streaming behavior should then be preferred for the data part and browser could show progress bar correctly. In either case (store/forward or streaming), mitmproxy UI should show progress instead of a constant "content missing" status.

#### Alternatives

N/A

#### Additional context

Store/forward behavior as demonstrated by Wireshark capture. Long leading time (25s) before `200 OK` was delivered to client, and then all ~10MB data was delivered to client in a burst of data packets.

![image](https://github.com/mitmproxy/mitmproxy/assets/11997203/4526415d-4d96-401a-ae25-fab079a6c478)

**Comment by Prinzhorn** [comment]
> We should be able to turn off store and forward behavior for data part based on headers like `content-type` and `content-length`. That is, buffer and receive full header part, and then decide whether to store/forward or stream following data part based on the metadata in headers. It's unlikely that one will want to intercept/modify `content-type: application/octet-stream` with a large `content-length`. Streaming behavior should then be preferred for the data part and browser could show progress bar correctly. In either case (store/forward or streaming), mitmproxy UI should show progress instead of a constant "content missing" status.

This sounds like multiple feature requests all at once. Most of what you describe can be solved via the ` stream_large_bodies` option or by writing an addon that conditionally sets `flow.response.stream = True` (https://github.com/mitmproxy/mitmproxy/blob/90686abe822634c0faf1eae7d7927e67bd46013f/examples/addons/http-stream-simple.py)

I _think_ the only thing left is that you are proposing to somehow expose streaming information in the UI. Please open a separate feature request for that detailing what exactly you are missing in the UI.

**Comment by Lingxi-Li** [comment]
Thank you for pointing out the `stream_large_bodies` option. It resolves my issue. Will open a feature request for the UI.
