### ISSUE TITLE
Version for Windows Server without desktop experience (GUI)

### ISSUE THREAD

**Issue by Lingxi-Li** [mitmproxy/mitmproxy#6131]
#### Problem Description

Current installer does not work for Windows Server without desktop experience (GUI).

#### Proposal

Provide a version that installs and works on CLI-only Windows Server installations.

#### Alternatives

I don't see any.

#### Additional context

I cannot install Windows Server with GUI due to constraints.

**Comment by mhils** [comment]
1. I believe the current installer should also work from the command line.
2. https://mitmproxy.org/downloads/ also has standalone binaries.

**Comment by Lingxi-Li** [comment]
The exe installer does not work. I didn't know about the zip version. Not mentioned on the [installation page](https://docs.mitmproxy.org/stable/overview-installation/). Will try the zip version and feedback.
