### ISSUE TITLE
Add a switch on webui for hiding image requests

### ISSUE THREAD

**Issue by NewUserHa** [mitmproxy/mitmproxy#6145]
#### Problem Description
On Webui, there're usually many requests for images, so it would be great to hide those by switch/option for better focus on important rows.

#### Proposal
Add a switch on webui for hiding image requests.

**Comment by mhils** [comment]
The intended approach right now is to use [filters](https://docs.mitmproxy.org/stable/concepts-filters/), e.g. `!~a`. I don't think we will add a more dedicated switch barring some major UX work, so this issue isn't actionable for now and I'll close it. :)

**Comment by NewUserHa** [comment]
Then maybe pin `!~a` in that filter list for just convenience?
