### ISSUE TITLE
Unable to scroll in mitmweb flow-table or flow-detail panes

### ISSUE THREAD

**Issue by johnmccabe** [mitmproxy/mitmproxy#615]
Currently its not possible to scroll either the in the flow-table or flow-detail panes. Observing the same behaviour in Chrome, Firefox and IE.

Been observing this in 0.12.0 and 0.12.1

![no_scroll](https://cloud.githubusercontent.com/assets/83862/8026394/a45642d6-0d6b-11e5-9dce-769940ce59a6.png)

**Comment by mhils** [comment]
Interesting bug - thanks for the report.
That being said - mitmweb is still work in progress and not an official feature yet. :wink: 
I'm super happy to see how many people somehow discover it and play around with what's there already, but please keep in mind that it's still very incomplete. :-)

Cheers,
Max

**Comment by johnmccabe** [comment]
Yep understood :)

I'm quite happy with its state at the moment, totally usable. Saves devs having to faff about with tcpdump/wireshark especially from systems where running them isn't feasible. Only thing not in it at the minute would be the ablity to export request/respones as a text file, that'd be awesome.

**Comment by mhils** [comment]
Interesting - works fine for me in Chrome 43, but both Canary and latest Firefox don't scroll.

**Comment by johnmccabe** [comment]
I'm running Chrome 44 on OSX and Win8.1

**Comment by johnmccabe** [comment]
Just tried Chrome 43 and yup its working fine there for me as well. I can see the scrollbars displayed (my hacky commit doesn't result in them getting displayed on 44 although you can indeed scroll).

**Comment by mhils** [comment]
Setting `height: 0` works fine for me and displays scrollbars as well?
