### ISSUE TITLE
Add set-cookie option for flow.response

### ISSUE THREAD

**Issue by D3SERTed** [mitmproxy/mitmproxy#6165]
#### Problem Description

Im trying to create a plugin that allows me to insert custom cookies into a browser using a modified response.
I need this for a bigger project wich requires me to edit the html and the cookies that are responded with. Wich means editing existing and adding new cookie values. (Setting the Set-Cookie header only allows me to set a single cookie in firefox.

#### Proposal
add a flow.response.add_cookie(name, value) function to set cookies.

#### Alternatives
Using Set-Cookie as a header in mitmproxy only allows me to set a singular cookie.
Using flow.response.cookies.add() didnt set the cookies and the modified response wasnt served at all.

**Comment by mhils** [comment]
Please take a look at the API docs for the `Header` class: https://docs.mitmproxy.org/stable/api/mitmproxy/http.html#Headers
There is no `cookies.add` method.

**Comment by drupalista-br** [comment]
@mhils yes there is flow.response.cookies.add(). The link you provided does not answer the issue raised cause it is not possible to add the header set-cookie multiple times.
