### ISSUE TITLE
mitmproxy crashes with multiple "list indices must be integers, not weakref"

### ISSUE THREAD

**Issue by rapucha** [mitmproxy/mitmproxy#617]
Domain: https://www.spb.velogorod.org/
mitmproxy version: v0.12.1

**Comment by mhils** [comment]
I cannot reproduce the error. Could you please provide a full traceback and steps how to reproduce the issue?

**Comment by rapucha** [comment]
Sorry, me neither. Maybe it was an interference with developing tools.. System is Linux Mint 17.1 KDE 64 bit, mitmproxy installed with pip. Browser Firefox, CA installed... won't bother you with the rest of my setup as I cannot reproduce it myself. Sorry.

**Comment by mhils** [comment]
No problem. Make sure to capture a traceback next time. :-)

Cheers,
Max
