### ISSUE TITLE
Container does not stop

### ISSUE THREAD

**Issue by kroese** [mitmproxy/mitmproxy#6176]
#### Problem Description
When stopping the container in Docker, it does not stop gracefully. It is killed by Docker using a SIGTERM signal after the timeout (by default 10 seconds). Even you set the timeout to 240 for example, it will not quit untill its hardkilled.

#### Steps to reproduce the behavior:
1. Stop the container
2. Wait forever

#### System Information
Version 9.0.1

**Comment by mhils** [comment]
Fixed in https://github.com/mitmproxy/mitmproxy/commit/5969f25db4cbbc3edc91947205b89edca58f0818.

**Comment by mhils** [comment]
9.0.1 was released before February. You can use mitmproxy/mitmproxy:latest.

**Comment by mhils** [comment]
Sorry, my bad. I meant to say `mitmproxy/mitmproxy:dev`. `latest` points (as expected) to the latest stable release.

**Comment by mhils** [comment]
Ah yes - that totally kills signal forwarding. What's the use case for that stty call? Ideally you'd just do `command: mitmweb --args...`

**Comment by mhils** [comment]
Fantastic, thanks! The post you linked is five years old, seems like things got fixed in the meantime. :)
