### ISSUE TITLE
how to use keep_host_header

### ISSUE THREAD

**Issue by Ariyankj** [mitmproxy/mitmproxy#6181]
Hi

I have tired to change url of a request with request header not being changed but i had no luck, the code that i came to is this:
```
def request(flow: http.HTTPFlow) -> None:
    if "ur1" in flow.request.host or "url2" in flow.request.host:
        h=flow.request.host
        flow.request.url="[url3]"
        flow.request.headers["Host"]=h #this shoulf be the reqest header
```
i found out that there is a keep_host_header but i found no way to use it as it changes the host header any way  i have tried :`--set keep_host_header=true`

**Comment by mhils** [comment]
`.url` updates the host header as well because that's typically the desired behavior. If you want to keep the host header, do exactly what you are already doing:

```python
host_header = flow.request.host_header
flow.request.url = "https://example.com/new"
flow.request.host_header = host_header 
```
