### ISSUE TITLE
WebSocket TLSv1.2 Closed by client with code 1002 (server received unexpected unmasked frame).

### ISSUE THREAD

**Issue by JackCarterSmith** [mitmproxy/mitmproxy#6195]
#### Problem Description
Using mitmproxy in transparent mode, I got some trouble with websocket with this error message at the first transaction:
`Closed by client with code 1002 (server received unexpected unmasked frame).`

It's through a TLSv1.2 connection, TLS handshake is success, but it's failed just after HTTP 101 protocol transmission.

Any idea of the cause?

#### System Information
Mitmproxy: 9.0.1
Python:    3.9.2
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.78-aarch64-with-glibc2.31

**Comment by mhils** [comment]
At the first glance this looks like a protocol violation from the server. Do you have a minimal reproducible example?

**Comment by JackCarterSmith** [comment]
Thanks for your support!

I'm not really familiar with the details of web protocols like websocket, so I don't really have any idea what to look at first.
I wanted to inspect raw traffic (without SSL) from a "blackbox app" to it's dedicated server (I suppose).
If I can understand those who can trigger this error (WebSocket specific error or mitmproxy internal error return?), that's can be a good point to start.

**Comment by mhils** [comment]
mitmproxy is aborting the connection because it believes that the client is sending invalid WebSocket frames. So the problem is a) that the communication you are looking at is a WebSockets-like protocol, but not correct WebSockets, or b) a bug in mitmproxy. I haven't heard of  anyone having similar issues, so my bet would be on a). If you are just interested in observing the traffic, setting `tcp_hosts` might be an option.

**Comment by JackCarterSmith** [comment]
Hmm... As far as I know about the protocol, it may not be a true websocket. So the a) can be valid.
I'll investigate further in this direction.
Thanks for help, I think it's not a issue with mitmproxy, you can close this issue if you want.
Otherwise, I can always put new details if I found something.

**Comment by JackCarterSmith** [comment]
With tcp_hosts options, the flow is restablished.
The raw datas is in JSON format, pushed through websocket after http protocol upgrade.
I can't say why the non-proxy mode break the link...

**Comment by mhils** [comment]
Thanks for the feedback! I'm pretty sure you're looking at an non-compliant WebSocket implementation, so there's nothing for us to do here. :)
