### ISSUE TITLE
Mitmdump increasing memory usage

### ISSUE THREAD

**Issue by inian** [mitmproxy/mitmproxy#620]
Hi,

I have noticed that the memory usage of mitmdump keeps increasing over time. It has grown to 2 GB on a Linux machine over a day. 

This is the command I am running
mitmdump -s "cookieinject.py cookies.txt" -p 9009 -z -q &

And here my [cookieinject.py](https://gist.github.com/inian/a294fd769215459fa798) script

Is this expected?
![image](https://cloud.githubusercontent.com/assets/2155545/8050535/d9f49a92-0ea0-11e5-9482-81f6b7b31164.png)

**Comment by cortesi** [comment]
Hi there. No, for mitmdump to grow without bounds is a bug, and I don't see anything that would cause this in your script either. Do you see the same behaviour over time without the script? Could you please give us more details about the exact mitmproxy version and your platform? Thanks for reporting this.

**Comment by inian** [comment]
I am using mitmdump version 0.12.0 on "Linux 3.13.0-37-generic #64-Ubuntu". I will try running mitmdump for sometime without the script and get back to you if the memory usage increases.

**Comment by inian** [comment]
This seems to be happening at random times. The memory usage does not increase when there are no requests to the proxy (with or without the script). I will re-open the issue when I can find a always re-producable example.
Thanks!

**Comment by lkwg82** [comment]
```bash
$ mitmdump --version
mitmdump 0.13
```

the simplest mode `mitmdump` results a memory increase

similiar #484

**Comment by mhils** [comment]
@lkwg82, if you can provide us with a reproducible test case, we'll look into it.

**Comment by lkwg82** [comment]
I just tested with `ab` from apache utils with a fresh install with docker.

TD;LR (my observation)
- same request many times repeated adds tiny amount of memory each time
- concurrency speeds up memory increase
- v0.13 is worse compared to previous

--

Dockerfile
```bash
FROM ubuntu:trusty

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends\
	software-properties-common python-software-properties bash-completion && apt-get clean

RUN	apt-get install -y --no-install-recommends python-pip gcc libpython2.7-dev libxml2-dev libxslt1-dev libffi-dev libssl-dev \
    && apt-get clean

# bad
RUN pip install netlib==0.13.1 mitmproxy==0.13; mitmdump  --version


# gut
#RUN version=0.12.1; pip install netlib==$version mitmproxy==$version; mitmdump  --version
#RUN version=0.11.2; pip install netlib==$version mitmproxy==$version; mitmdump  --version
#RUN version=0.10.1; pip install netlib==$version mitmproxy==$version; mitmdump  --version
ENV LANG=de_DE.UTF-8


RUN groupadd -r lars && useradd -r -g lars -m lars
USER lars

#ENTRYPOINT /bin/bash
ENTRYPOINT /bin/bash -c 'mitmdump -q & top -d 0.5'
```

`docker run -ti mitmproxy -p 8090:8080`

```bash
$ sudo apt install  apache2-utils
$ ab -X localhost:8090 -c10 -n100 http://www.lgohlke.de/mitmproxy_memory
```

**Comment by mhils** [comment]
@lkwg82: Thanks. Can you reproduce this with larger values, e.g. `ab -X localhost:8090 -c10 -n10000 http://www.lgohlke.de/mitmproxy_memory`? There are expected small increases until the Python GC kicks in, but I don't have long-term issues.

Cheers,
Max

**Comment by lkwg82** [comment]
I forked to https://github.com/lkwg82/mitmproxy/tree/issue-620-increasing-memory/bug and 'still running'.

**Comment by lkwg82** [comment]
I got it:

It is sth around the ssl handling introduced in version 0.13.1 in netlib. It can be observed with just a single ssl request.

See the Dockerfile and benchmark.sh for details (in the link above).

Cheers Lars

**Comment by mhils** [comment]
Thanks for the great work. I can reproduce the really big one, let's see where this comes from...

**Comment by nbdsp** [comment]
I also observe the memory leak and it seems more apparent with HTTPS connections. Maybe this is somehow linked to #831.  As a temporary workaround the automatic periodic restarting seems like the simplest one.

**Comment by mhils** [comment]
This one is really though to track down. The easiest way to reproduce it is running mitmproxy with `mitmdump -q --no-upstream-cert` and then point my browser to a nonexisting HTTPS domain. Few observations:

- The major (I don't know if there are minor ones besides that) leak stems from the connection. Multiple requests per connection do not cause any trouble.
- Briefly going through the RAM, I see quite a bit of SSL certificates, which points at pyOpenSSL - not good...

**Comment by mhils** [comment]
Getting closer:
![](https://maximilianhils.com/upload/2015-11/2015-11-26_22-46-12.png)

**Comment by mhils** [comment]
I fixed a pretty obvious memory leak concerning flows with failed connections, but now I'm stuck at a point where I do see a small memory leak but I don't know what's leaking. My feeling is that it's pyOpenSSL, but debugging that cffi stuff is really nasty. The only useful finding I have right now that removing the `context.load_verify_locations` calls in netlib.tcp seems to solve the major part of the problem. However, I don't see any leaked `SSL.Connection` objects in Python.
