### ISSUE TITLE
Document Scripting API

### ISSUE THREAD

**Issue by mgdelmonte** [mitmproxy/mitmproxy#621]
The `HTTPResponse` class seems tightly controlled.  It could use some more flexible constructors and it should be able to handle a wide variety of inputs.  It requires an `odict.ODictCaseless` for the `headers` param in the constructor.  The code implies that it will accept `None` but in fact this causes a crash.  It also prevents `__repr__` from functioning.

I'd be happy to add some convenience functions.  Being able easily to supply a wholly manufactured response in reply to certain requests is very valuable, but the documentation is very unhelpful.  Documentation and better HTTPResponse generation would be a good step.

**Comment by cortesi** [comment]
Hi there. Yes, one thing that we do poorly at the moment is to distinguish between those parts of our API that are internal and external (used by scripts and extenders). Cleaning up the API, documenting things, adding human conveniences, and generally raising our API game has long been on my todo list. I'd definitely welcome contributions along these lines!
