### ISSUE TITLE
Add pycryptodome library

### ISSUE THREAD

**Issue by copystring** [mitmproxy/mitmproxy#6215]
Hi,

I'd like to use mitmproxy in my existing project (https://github.com/copystring/ioBroker.roborock) for MQTT sniffing.
However, for this to work, I struggle implementing the needed pycryptodome library into it.

I tried building my own version but keep going from one problem to another with the build process, so I thought it'd be a lot easier if mitmproxy came with support for pycryptodome.

**Comment by mhils** [comment]
We're working hard to reduce the set of dependencies mitmproxy itself depends on, so we will 100% not adopt additional dependencies that are not used within mitmproxy itself.

**Comment by copystring** [comment]
OK. I understand.
I created a fork for my own purposes to add the library there. Could give me a hint how to add pycryptodome to my fork?
