### ISSUE TITLE
Both Edit and Export share the same key binding

### ISSUE THREAD

**Issue by superruzafa** [mitmproxy/mitmproxy#6225]
#### Problem Description

When in flow view, both `Edit` and `Export` commands are bound to the `e` key by default.

<img width="493" alt="imagen" src="https://github.com/mitmproxy/mitmproxy/assets/231822/362a928e-1634-4085-928a-b391b576fa37">

`Export` could use a different binding by default, like `x`.

#### System Information

Mitmproxy: 9.0.1
Python:    3.11.3
OpenSSL:   OpenSSL 1.1.1u  30 May 2023
Platform:  macOS-12.6.5-arm64-arm-64bit

**Comment by mhils** [comment]
Thanks for catching this! Definitely something we want to fix. Maybe we move export to `x` in all contexts? Does anyone have any other ideas/proposals?
