### ISSUE TITLE
Easier navigation to "favorite" flows

### ISSUE THREAD

**Issue by drahosj** [mitmproxy/mitmproxy#623]
It is common to want to save three or four flows for replays, such as JSON POST requests, for frequent use when using MITMProxy for web application debugging or analysis. The application, however, may be generating a lot of other traffic. This makes it difficult to find or navigate to the "favorite" flows.

Currently, the best solution is to write the desired flows to a file, clear the screen, and reload the flows. This can become quite cumbersome, and it is very inconvenient to add another saved flow to the file.

There are several possibilities. The easiest would be to allow vim-like navigation to a specific flow number by pressing a hotkey, then typing the flow number. A more complete option would be to allow flows to be marked as a "favorite" This would place a visual marker on the flow, and enable additional navigation options, such as "next favorite flow" and "previous favorite flow". Additionally, adding a "favorite flows" option to the "write flows to file" submenu would allow for an easy way to persist the "favorite" flows across clears, or the "Clear All Flows" command could default to not deleting favorite flows.

Overall, these features would vastly improve the experience of using MITMProxy for web application debugging, especially for debugging of applications which make frequent requests to REST endpoints.

**Comment by drahosj** [comment]
This was actually rather easy to implement. I created functionality for toggling a mark on flows and persisting those flows across clears and submitted a pull request here: https://github.com/mitmproxy/mitmproxy/pull/624

If this is popular, I can work on extending this functionality a bit more, but what I have so far has been a lifesaver for the project I'm working on right now.

**Comment by cortesi** [comment]
I've merged @drahosj's change that implements this. Thanks!
