### ISSUE TITLE
har_dump.py script not logging requests with certain 502 error responses

### ISSUE THREAD

**Issue by jonasxyz** [mitmproxy/mitmproxy#6230]
Using the [har_dump.py](https://github.com/mitmproxy/mitmproxy/blob/main/examples/contrib/har_dump.py) script, requests to URLs that return certain 502 errors generate no data in the exported .har 
So far I noticed these 2 cases:

- 502 'Connect call failed' on `163.com`
- 502 'No address associated with hostname'  on `a-msedge.net` or `windowsupdate.com`

Both generate no output in the HAR-file.

Reproduce:

Start up mitmdump inlcuding har_dump script:
`mitmdump --listen-host=127.0.0.1 --listen-port=3031 -s /path/to/har_dump.py --set=hardump=/path/to/dump/whereError.har`

Visit website with Firefox that returns specific error for example `a-msedge.net`

If Firefox is too chatty with their mozilla servers, wget reveals the same problem:
`wget 163.com  -e use_proxy=yes -e http_proxy=127.0.0.1:3031`

Looking into the generated file, nothing has been recorded

![163_comProxy2](https://github.com/mitmproxy/mitmproxy/assets/54746338/fcaedc9d-c7b3-414a-a987-e74aacacc20f)

Mitmproxy: 10.0.0.dev (+299, commit 1cb0cb1)
Python:    3.10.6
OpenSSL:   OpenSSL 3.1.1 30 May 2023
Platform:  Linux-5.19.0-46-generic-x86_64-with-glibc2.35

9.0.1 stable release same behavior

**Comment by zanieb** [comment]
Probably worth checking if this is resolved by https://github.com/mitmproxy/mitmproxy/pull/6368?

**Comment by mhils** [comment]
Pretty sure it is, because the builtin har functionality detects the `error` hook. Thanks!
