### ISSUE TITLE
HAR Import: Handle Request Content

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#6240]
#### Problem Description

Similar to the response content, we should als handle request bodies on import (if any). We should have a minimal HAR file from Chrome or so as a test case. :)

**Comment by stanleygvi** [comment]
Would this be considered the request body?
`          "postData": {
            "mimeType": "text/plain;charset=UTF-8",
            "text": "text was too long"
          }`
          
     I added support that sets the requests content to the text value in #6243

**Comment by mhils** [comment]
Yes :)
