### ISSUE TITLE
Foxtel Go And Play and removal of a

### ISSUE THREAD

**Issue by JPS46225** [mitmproxy/mitmproxy#626]
Hi Guys

I'm opening up this ticket specifically

**Comment by JPS46225** [comment]
because, my other ticket was closed down, because, well you guys can see for yourself. This ticket has been opened up regarding URL streaming on Foxtel Go and Play and removal of all Python/Pip packages

**Comment by JPS46225** [comment]
Anyway, here are the URLs for Foxtel Go and Foxtel Play

http://win-cdn220-is-7.se.fxmultihlslive6258.ngcdn.telstra.com/channel001/channel001215.m3u8

https://foxtelgo.d2.sc.omtrdc.net/b/ss/foxtelgoproduction/0/OIP-3.0.0/s34271842?AQB=1&ndh=1&t=11/5/2015%2019%3A39%3A45%204%20-600&c.&eVar48=News%20%26%20Documentaries&eVar19=14&eVar33=7200&eVar71=Joshua%20P%20Stokes%27%20iPad&eVar1=1434015586&eVar5=d41d8cd98f00b204e9800998ecf8427e&eVar9=8.4&eVar10=IOS&eVar12=NOT%20CELLULAR&eVar2=PLAY&eVar14=2015-04-23T19%3A50%3A15&eVar21=48&eVar16=5&eVar30=GoLive&eVar6=NOLOGIN&eVar25=livetab&eVar23=830cc6973aad7313ccd970ca869af7b71fbc3072&eVar18=45&eVar41=Streaming&eVar34=5&eVar43=SKY&eVar36=0&eVar38=true&eVar50=2015-06-11T18%3A00%3A00&eVar47=News%20%26%20Documentaries&eVar70=2.9.3&eVar49=NC&a.&DeviceName=iPad5%2C3&Resolution=2048x1536&OSVersion=iOS%208.4&CarrierName=%28null%29&.a&eVar32=Reporting%20LIVE%20with%20Stan%20Grant&eVar45=SKY67812077&eVar3=event25&eVar7=iPad5%2C3&c44=NOTASSET&c45=HWW5925502&eVar11=Wifi&eVar13=2.9.3&eVar20=1&eVar4=2&eVar15=19&eVar22=0&eVar17=14&eVar31=8ec12b4a2b3eb038eec102d365f68c10ecfd8880&eVar8=e3f5536a141811db40efd6400f1d0a4e&eVar40=LIVE&eVar24=e3100bcf903ab81ac3bb9df9adc1b5ba&eVar42=SD&eVar35=0&eVar44=NOTASSET&eVar37=5&eVar51=T02%3A00%3A00&eVar46=Reporting%20LIVE%20with%20Stan%20Grant&.c&vid=4DF6024E0F6D6045AE0A7A20085240F5E987&ce=UTF-8&events=event25&pe=lnk_o&cc=AUD&pev2=foxtel-go-iPad/2.9.3%20Event&pageName=foxtel-go-iPad/2.9.3&AQE=1​

http://win-cdn220-is-9.se.fxmultihlslive6258.ngcdn.telstra.com/c
hannel001/channel001290/02928/channel00129020150611T093900_00046.ts​

http://win-cdn220-is-9.se.fxmultihlslive6258.ngcdn.telstra.com/c
hannel001/channel001290.m3u8?SIGV=2&IS=0&ET=1434026109&KO=7&KN=2&US=445dfee6131d
468a6b5177dcfbe4bccc1e2c2f41

Please let me know what you guys think.

**Comment by JPS46225** [comment]
Last two URLs are split between c and hannell001

**Comment by cortesi** [comment]
Hi there. I'm still not sure what the issue is here. In general, could you please include: a) what the behaviour is you see, b) what you expected to see, c) how we can reproduce the issue, and d) what the exact platform and mitmproxy version is you're using. Please include all this information in the ticket description, and add a clear subject that describes the problem.

**Comment by JPS46225** [comment]
![image](https://cloud.githubusercontent.com/assets/12774655/8123313/689d8aea-110a-11e5-804a-9d2c9e8edba9.jpg)

**Comment by JPS46225** [comment]
Ok, regarding Foxtel go and play, this is one of the URLs detected by mitmproxy, however I can't play it. I'm not sure whether this is an authentication issue or something else
