### ISSUE TITLE
Handle HTTPS connections to mitm.it

### ISSUE THREAD

**Issue by MasterCarl** [mitmproxy/mitmproxy#6265]
#### Problem Description

When setting up mitmproxy, I inadvertently entered https://mitm.it/ instead of http://mitm.it/. When getting past the certificate warning, the site only shows

*502 Bad Gateway*

Certificate verify failed: hostname mismatch.

#### Proposal

I wonder if there's a way to serve the onboarding-app over HTTPS as well, or issue some kind of redirect to HTTP. Alternatively, an error message like "This site only supports HTTP" would be helpful.

**Comment by mhils** [comment]
This is already fixed on main, see https://github.com/mitmproxy/mitmproxy/blob/main/CHANGELOG.md#breaking-changes. Thanks! :)
