### ISSUE TITLE
Edit of HTML-Response-Body not working (Missing VIM)

### ISSUE THREAD

**Issue by 4DFuchs** [mitmproxy/mitmproxy#6267]
#### Problem Description
I can not edit the response of an request. 

#### Steps to reproduce the behavior:
1. Add Intercept-Filter (~all)
2. Make a request. For example http://www.google.de
3. Resume request
4. Press e and choose response-body
5. Nothing happens

#### System Information
Mitmproxy: 9.0.1
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
(I use the Docker-Image)

### Solution
It looks like  `vim`  is not installed in the Docker-Image

I created a new Docker-Image like this and then it will work

    FROM mitmproxy/mitmproxy:9.0.1

    RUN apt update
    RUN apt install vim -y

**Comment by mhils** [comment]
Thanks! We'll make this nano so that folks can escape, but either way now we have a way to edit! 🙌
