### ISSUE TITLE
Unable to install the https certificate on windows 10

### ISSUE THREAD

**Issue by dakar111** [mitmproxy/mitmproxy#6269]
I Visit http://mitm.it download the pk12 cert for windows.

Double-click it and it runs normally. 

when I reach the step where it asks for the password; I keep the password empty and press on ok as per the instructions; however, I am getting a wrong password messagebox. 

Please advise on solving this issue,

thanks

**Comment by mhils** [comment]
Could you please remove your `~/.mitmproxy` on your system, then download a binary from https://github.com/mitmproxy/mitmproxy/actions/workflows/main.yml?query=branch%3Amain, and try again? I believe this got fixed upstream in pyOpenSSL/cryptography.
