### ISSUE TITLE
Foxtel Go and Play URLs do not stream

### ISSUE THREAD

**Issue by JPS46225** [mitmproxy/mitmproxy#628]
![image](https://cloud.githubusercontent.com/assets/12774655/8123434/7dec8156-110c-11e5-9f2b-0089b25da351.jpg)

Ok, regarding Foxtel go and play, this is one of the URLs detected by mitmproxy, however I can't play it. I'm not sure whether this is an authentication issue or something else

I was expecting the stream to open, since I had the direct URL, also, when I tried to play it on my iPhone, I got the error message, 'The operation could not be completed'

How to reproduce the issue

Download Foxtel Go, analyse through mitmproxy and look for url's with Telstra in it's name

Platform is iOS

Will also work with Foxtel Play for Windows

**Comment by cortesi** [comment]
Thanks, this is a clear bug report! Quoting my previous response here:

The issue you're seeing is not a bug in mitmproxy. The way mitmproxy works by default is to buffer up an entire response in the proxy before relaying it downstream. This is meant to let you modify and tamper with the response. For very large responses (i.e. streaming responses), this means mitmproxy never receives the "complete" response, and nothing is ever relayed down tot he client. Please have a look at the response streaming documentation for some ideas of how to handle this in mitmproxy:

http://mitmproxy.org/doc/features/responsestreaming.html

**Comment by JPS46225** [comment]
Thanks for providing useful feedback. I really appreciate it!
