### ISSUE TITLE
Clarify procedure for setting a local transparent proxy

### ISSUE THREAD

**Issue by justincy** [mitmproxy/mitmproxy#630]
The docs are pretty good but they don't point out that setting up a transparent proxy on the same machine where the traffic originates is a bit different as [noted here](http://askubuntu.com/a/281645/91159). More specifically, the iptables commands are different.

```
sudo iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner root --dport 443 -j REDIRECT --to-port 8080
sudo iptables -t nat -A OUTPUT -p tcp -m owner ! --uid-owner root --dport 80 -j REDIRECT --to-port 8080
```

You have to run mitmproxy as a different user than the traffic you're trying to capture, otherwise that won't work. If you didn't have an expection for mitmproxy traffic then you'd end up with a loop (I ran out of open file descriptors when I did that). I'm not familiar enough with iptables to know whether there's any other match expression that could be used other than the process owner.

**Comment by cortesi** [comment]
Yes, I'd definitely support a patch that points out that both pf and iptables can filter based on UID for same-host setups.

**Comment by fxfactorial** [comment]
I just tried the iptables commands listed and had mitmproxy running as another user but I still wasn't able to get traffic through. curl on anything plain http would end with "transfer closed with xx bytes remaining to read". This is on Ubuntu 14.04 in a VM.
