### ISSUE TITLE
Allow Alternative Means of Providing upstream_auth

### ISSUE THREAD

**Issue by wbrawner** [mitmproxy/mitmproxy#6300]
#### Problem Description

[upstream_auth](https://docs.mitmproxy.org/stable/concepts-options/#upstream_auth) currently only takes in a string with the credentials in plain text, which means that your upstream credentials are either persisted in plain text on disk in the config file or clearly visible in the process list when passed via CLI flags.

#### Proposal
There should be some method of providing the upstream proxy credentials securely, such that they are not stored on disk in plaintext nor visible from the process list. OfflineIMAP for example allows users to provide a python script that can load the credentials from any source, e.g. [GPG](https://wiki.archlinux.org/title/OfflineIMAP#Using_GPG).

#### Alternatives
The user could opt into being prompted to enter their credentials upon launching mitmproxy. This could also be integrated with the system keychain so that the user can elect to have the password automatically unlocked when they login to their machine.

**Comment by mhils** [comment]
You could conceivably write a simple addon that fetches credentials and then updates the option. It's very unlikely that we will adopt a more elaborate scheme here.

**Comment by wbrawner** [comment]
I would argue that secure credential entry should be the default, but I can agree to disagree. Thank you for your consideration!
