### ISSUE TITLE
Build Failure: maturin - protoc binary not found on Android/Termux

### ISSUE THREAD

**Issue by AgentConDier** [mitmproxy/mitmproxy#6302]
#### Problem Description
I'm using the Termux environment to run mitmproxy on my Android phone, which uses a non-standard `/bin` directory.
When installing mitmproxy-rs throuth `pip`, `protoc` is not found despite being in the path.
Is there a way to explicitly tell the build system where to look for `protoc`?
<details><summary>Command Output:</summary><pre><code>~ $ RUST_BACKTRACE=1 pip install -U mitmproxy
Requirement already satisfied: mitmproxy in /data/data/com.termux/files/usr/lib/python3.11/site-packages (9.0.1)
Collecting mitmproxy
  Obtaining dependency information for mitmproxy from https://files.pythonhosted.org/packages/7a/3a/9ec933b3c556ea26690251c3928cddce4df3688ac37344b369db7975bb17/mitmproxy-10.0.0-
py3-none-any.whl.metadata
  Using cached mitmproxy-10.0.0-py3-none-any.whl.metadata (8.9 kB)
Collecting aioquic-mitmproxy<0.10,>=0.9.20 (from mitmproxy)
  Using cached aioquic_mitmproxy-0.9.20.3-py3-none-any.whl (80 kB)
Requirement already satisfied: asgiref<3.8,>=3.2.10 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (3.5.2)
Requirement already satisfied: Brotli<1.1,>=1.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (1.0.9)
Requirement already satisfied: certifi>=2019.9.11 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (2023.7.22)
Requirement already satisfied: cryptography<41.1,>=38.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (38.0.3)
Requirement already satisfied: flask<2.4,>=1.1.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (2.2.2)
Requirement already satisfied: h11<0.15,>=0.11 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (0.14.0)
Requirement already satisfied: h2<5,>=4.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (4.1.0)
Requirement already satisfied: hyperframe<7,>=6.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (6.0.1)
Requirement already satisfied: kaitaistruct<0.11,>=0.10 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (0.10)
Requirement already satisfied: ldap3<2.10,>=2.8 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (2.9.1)
Collecting mitmproxy-rs<0.3,>=0.2.0b1 (from mitmproxy)
  Using cached mitmproxy_rs-0.2.1.tar.gz (854 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: msgpack<1.1.0,>=1.0.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (1.0.4)
Requirement already satisfied: passlib<1.8,>=1.6.5 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (1.7.4)
Requirement already satisfied: protobuf<5,>=3.14 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (4.21.9)
Requirement already satisfied: pyOpenSSL<23.3,>=22.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (22.1.0)
Requirement already satisfied: pyparsing<3.2,>=2.4.2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (3.0.9)
Requirement already satisfied: pyperclip<1.9,>=1.6.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (1.8.2)
Requirement already satisfied: ruamel.yaml<0.18,>=0.16 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (0.17.21)
Requirement already satisfied: sortedcontainers<2.5,>=2.3 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (2.4.0)
Requirement already satisfied: tornado<7,>=6.2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (6.2)
Collecting urwid-mitmproxy<2.2,>=2.1.1 (from mitmproxy)
  Using cached urwid_mitmproxy-2.1.2.1-cp311-cp311-linux_aarch64.whl
Requirement already satisfied: wsproto<1.3,>=1.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (1.2.0)
Requirement already satisfied: publicsuffix2<3,>=2.20190812 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (2.20191221)
Requirement already satisfied: zstandard<0.22,>=0.11 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from mitmproxy) (0.19.0)
Collecting pylsqpack<0.4.0,>=0.3.3 (from aioquic-mitmproxy<0.10,>=0.9.20->mitmproxy)
  Using cached pylsqpack-0.3.17-cp311-cp311-linux_aarch64.whl
Requirement already satisfied: cffi>=1.12 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from cryptography<41.1,>=38.0->mitmproxy) (1.15.1)
Requirement already satisfied: Werkzeug>=2.2.2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from flask<2.4,>=1.1.1->mitmproxy) (2.2.2)
Requirement already satisfied: Jinja2>=3.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from flask<2.4,>=1.1.1->mitmproxy) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from flask<2.4,>=1.1.1->mitmproxy) (2.1.2)
Requirement already satisfied: click>=8.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from flask<2.4,>=1.1.1->mitmproxy) (8.1.3)
Requirement already satisfied: hpack<5,>=4.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from h2<5,>=4.1->mitmproxy) (4.0.0)
Requirement already satisfied: pyasn1>=0.4.6 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from ldap3<2.10,>=2.8->mitmproxy) (0.4.8)
Requirement already satisfied: pycparser in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from cffi>=1.12->cryptography<41.1,>=38.0->mitmproxy) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from Jinja2>=3.0->flask<2.4,>=1.1.1->mitmproxy) (2.1.1)
Using cached mitmproxy-10.0.0-py3-none-any.whl (1.6 MB)
Building wheels for collected packages: mitmproxy-rs
  Building wheel for mitmproxy-rs (pyproject.toml) ... error
  error: subprocess-exited-with-error

  Building wheel for mitmproxy-rs (pyproject.toml) did not run successfully.
   exit code: 1
   [180 lines of output]
      Running `maturin pep517 build-wheel -i /data/data/com.termux/files/usr/bin/python3.11 --compatibility off`
       Building a mixed python/rust project
       Found pyo3 bindings with abi3 support for Python e 3.10
 Not using a specific python interpreter
         Compiling autocfg v1.1.0
         Compiling proc-macro2 v1.0.66
         Compiling unicode-ident v1.0.11
         Compiling cfg-if v1.0.0
         Compiling libc v0.2.147
         Compiling quote v1.0.31
         Compiling syn v2.0.26
         Compiling getrandom v0.2.10
         Compiling version_check v0.9.4
         Compiling scopeguard v1.2.0
         Compiling typenum v1.16.0
         Compiling generic-array v0.14.7
         Compiling syn v1.0.109
         Compiling simd-adler32 v0.3.5
         Compiling rand_core v0.6.4
         Compiling semver v1.0.18
         Compiling target-lexicon v0.12.10
         Compiling lock_api v0.4.10
         Compiling crossbeam-utils v0.8.16
         Compiling memchr v2.5.0
         Compiling adler v1.0.2
         Compiling cc v1.0.79
         Compiling miniz_oxide v0.7.1
         Compiling crypto-common v0.1.6
         Compiling memoffset v0.9.0
         Compiling futures-core v0.3.28
         Compiling pyo3-build-config v0.18.3
         Compiling rustc_version v0.4.0
         Compiling crossbeam-epoch v0.9.15
         Compiling either v1.8.1
         Compiling subtle v2.5.0
         Compiling anyhow v1.0.72
         Compiling num_cpus v1.16.0
         Compiling once_cell v1.18.0
         Compiling futures-sink v0.3.28
         Compiling smallvec v1.11.0
         Compiling itertools v0.10.5
         Compiling zeroize_derive v1.4.2
         Compiling rayon-core v1.11.0
         Compiling pin-project-lite v0.2.10
         Compiling io-lifetimes v1.0.11
         Compiling parking_lot_core v0.9.8
         Compiling platforms v3.0.2
         Compiling prost-derive v0.11.9
         Compiling zeroize v1.6.0
         Compiling crossbeam-deque v0.8.3
         Compiling crossbeam-channel v0.5.8
         Compiling backtrace v0.3.68
         Compiling indexmap v1.9.3
         Compiling crc32fast v1.3.2
         Compiling gimli v0.27.3
         Compiling rustix v0.37.23
         Compiling addr2line v0.20.0
         Compiling pyo3-ffi v0.18.3
         Compiling errno v0.3.1
         Compiling object v0.31.1
         Compiling num-traits v0.2.15
         Compiling slab v0.4.8
         Compiling tempfile v3.6.0
         Compiling bytes v1.4.0
         Compiling prettyplease v0.1.25
         Compiling futures-task v0.3.28
         Compiling regex-syntax v0.7.4
         Compiling hashbrown v0.12.3
         Compiling futures-channel v0.3.28
         Compiling linux-raw-sys v0.3.8
         Compiling bitflags v1.3.2
         Compiling rustc-demangle v0.1.23
         Compiling regex-automata v0.3.3
         Compiling prost v0.11.9
         Compiling parking_lot v0.12.1
         Compiling curve25519-dalek v4.0.0-rc.3
         Compiling pin-project-internal v1.1.2
         Compiling inout v0.1.3
         Compiling block-buffer v0.10.4
         Compiling memoffset v0.8.0
         Compiling num-integer v0.1.45
         Compiling fixedbitset v0.4.2
         Compiling fastrand v1.9.0
         Compiling byteorder v1.4.3
         Compiling futures-util v0.3.28
         Compiling pin-project v1.1.2
         Compiling rayon v1.7.0
         Compiling petgraph v0.6.3
         Compiling digest v0.10.7
         Compiling cipher v0.4.4
         Compiling flate2 v1.0.26
         Compiling prost-types v0.11.9
         Compiling regex v1.9.1
         Compiling pyo3 v0.18.3
         Compiling which v4.4.0
         Compiling universal-hash v0.5.1
         Compiling heapless v0.7.16
         Compiling spin v0.9.8
         Compiling ring v0.16.20
         Compiling futures-macro v0.3.28
         Compiling pyo3-macros-backend v0.18.3
         Compiling nanorand v0.7.0
         Compiling num-rational v0.4.1
         Compiling tokio v1.29.1
         Compiling protoc-bin-vendored-linux-x86_32 v3.0.0
         Compiling protoc-bin-vendored-linux-ppcle_64 v3.0.0
         Compiling multimap v0.8.3
         Compiling log v0.4.19
         Compiling protoc-bin-vendored-linux-x86_64 v3.0.0
         Compiling futures-io v0.3.28
         Compiling heck v0.4.1
         Compiling pin-utils v0.1.0
         Compiling protoc-bin-vendored-linux-aarch_64 v3.0.0
         Compiling protoc-bin-vendored-macos-x86_64 v3.0.0
         Compiling opaque-debug v0.3.0
         Compiling protoc-bin-vendored-win32 v3.0.0
         Compiling lazy_static v1.4.0
         Compiling weezl v0.1.7
         Compiling pyo3-macros v0.18.3
         Compiling prost-build v0.11.9
         Compiling protoc-bin-vendored v3.0.0
         Compiling poly1305 v0.8.0
         Compiling flume v0.10.14
         Compiling jpeg-decoder v0.3.0
         Compiling chacha20 v0.9.1
         Compiling hash32 v0.2.1
         Compiling tracing-core v0.1.31
         Compiling aead v0.5.2
         Compiling zune-inflate v0.2.54
         Compiling fdeflate v0.3.0
         Compiling tracing-attributes v0.1.26
         Compiling tokio-macros v2.1.0
         Compiling mio v0.8.8
         Compiling socket2 v0.4.9
         Compiling unindent v0.1.11
         Compiling ip_network v0.4.1
         Compiling smoltcp v0.10.0
         Compiling spin v0.5.2
         Compiling half v2.2.1
         Compiling async-trait v0.1.71
         Compiling untrusted v0.7.1
         Compiling bit_field v0.10.2
         Compiling lebe v0.5.2
         Compiling stable_deref_trait v1.2.0
         Compiling color_quant v1.1.0
         Compiling ip_network_table-deps-treebitmap v0.5.0
         Compiling bytemuck v1.13.1
         Compiling indoc v1.0.9
         Compiling qoi v0.4.1
         Compiling ip_network_table v0.2.0
         Compiling gif v0.12.0
         Compiling exr v1.7.0
         Compiling tracing v0.1.37
         Compiling png v0.17.9
         Compiling chacha20poly1305 v0.10.1
         Compiling tiff v0.8.1
         Compiling x25519-dalek v2.0.0-rc.3
         Compiling futures-executor v0.3.28
         Compiling mitmproxy v0.2.1 (/data/data/com.termux/files/usr/tmp/pip-install-9luo25kk/mitmproxy-rs_37a9a2c7d7234dd5978ca23eb8a77232/local_dependencies/mitmproxy)
         Compiling hmac v0.12.1
         Compiling blake2 v0.10.6
         Compiling untrusted v0.9.0
         Compiling base64 v0.13.1
         Compiling managed v0.8.0
         Compiling hex v0.4.3
         Compiling boringtun v0.5.3
      error: failed to run custom build command for `mitmproxy v0.2.1 (/data/data/com.termux/files/usr/tmp/pip-install-9luo25kk/mitmproxy-rs_37a9a2c7d7234dd5978ca23eb8a77232/loca
l_dependencies/mitmproxy)`
      note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
Caused by:
process didn't exit successfully: `/data/data/com.termux/files/usr/tmp/pip-install-9luo25kk/mitmproxy-rs_37a9a2c7d7234dd5978ca23eb8a77232/target/release/build/mitmproxy-f99f34a699a95b13/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at 'protoc binary not found: Error { os: "android", arch: "aarch64" }', local_dependencies/mitmproxy/build.rs:6:48
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
maturin failed
Caused by: Failed to build a native library through cargo
Caused by: Cargo build finished with "exit status: 101": `PYTHON_SYS_EXECUTABLE="/data/data/com.termux/files/usr/bin/python3.11" "cargo" "rustc" "--release" "--manifest-p
ath" "/data/data/com.termux/files/usr/tmp/pip-install-9luo25kk/mitmproxy-rs_37a9a2c7d7234dd5978ca23eb8a77232/Cargo.toml" "--message-format" "json" "--lib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/data/data/com.termux/files/usr/bin/python3.11', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mitmproxy-rs
Failed to build mitmproxy-rs
ERROR: Could not build wheels for mitmproxy-rs, which is required to install pyproject.toml-based projects
~ $ which protoc
/data/data/com.termux/files/usr/bin/protoc
~ $ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/home/go/bin:/data/data/com.termux/files/home/go/bin
~ $
</pre></code></details>

#### Steps to reproduce the behavior:
1. Install https://f-droid.org/packages/com.termux/
2. `$ pkg install python-pip rust protobuf`
3. `$ pip install mitmproxy`

#### System Information
I'm trying to install `mitmproxy-10.0.0-py3-none-any.whl`
<pre>
~ $ mitmproxy --version
Mitmproxy: 9.0.1
Python:    3.11.4
OpenSSL:   OpenSSL 3.1.2 1 Aug 2023
Platform:  Linux-4.14.116-aarch64-with-libc
</pre>
<pre>
~ $ rustc --version
rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)
</pre>

**Comment by mhils** [comment]
Thanks for the detailed report! :)

cc @emanuele-em

**Comment by romanovj** [comment]
download sources and edit
mitmproxy_rs-0.2.1/local_dependencies/mitmproxy/build.rs

**Comment by emanuele-em** [comment]
Hi @AgentConDier, at the moment we are using [protoc_bin_vendored](https://github.com/stepancheg/rust-protoc-bin-vendored/): a crate in rust that incorporates the protoc binaries (to avoid installing it), everything is handled within the [build.rs](https://github.com/mitmproxy/mitmproxy_rs/blob/main/build.rs#L4-L6) file, as mentioned by @romanovj, for now you can specify from there where protoc is located, I will probably in the near future look into adding android as a target

**Comment by mhils** [comment]
Let's see if we can fall back to protoc on PATH is there is no vendored copy available on the current system? Manually patching build.rs is not really sustainable.

**Comment by AgentConDier** [comment]
Thank you for the quick replies!
Installing mitmproxy-rs from an edited tarball with [this line](https://github.com/mitmproxy/mitmproxy_rs/blob/822306a6d349738797515d72c1d29b0b88a4cc3d/build.rs#L6) replaced with the path to `protoc` worked like a charm, but I see there's a fix committed already.

**Comment by mhils** [comment]
This should be fixed with mitmproxy_rs 0.2.2! :)
