### ISSUE TITLE
Source Distributions for mitmproxy_rs

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#6303]
#### Problem Description

On Windows, mitmproxy_rs currently bundles [windows-redirector.exe](https://github.com/mitmproxy/mitmproxy_rs/tree/main/windows-redirector) for OS proxy mode. This executable is built as part of CI, and then copied over into the Python package in build.rs. @emanuele-em is in the process of introducing similar shenanigans on macOS for traffic redirection (where it's going to be a Swift app).

As part of https://github.com/mitmproxy/mitmproxy/issues/6299, I realized that this actually is a problem for source distributions (sdists): As we currently build sdists on Linux, windows-redirector.exe is not built during CI and the produced sdist is incomplete for Windows users. The same problem will appear on macOS. We need to fix that somehow.

Some proposals to address this:

1. We could somehow add the platform-specific sources to the sdist and have platforms-specific build steps in the sdist. The downside of this approach is that we would basically need to hijack `maturin build` to add custom steps around it. I'd outright reject this approach due to the complexity it brings.
1. We could make them mitmproxy_rs CI a two stage process: The first stage builds the platform-specific parts (windows-redirector.exe on Windows, macos-redirector.app on macOS, etc.), and then the second stage pulls in all these artifacts and includes them all in the sdist. One downside here is that the sdist is partially a binary distribution and not really a _source_ distribution. This would be the easiest approach for us, but downstream would rightfully complain I guess.
2. Another alternative would be to start producing `mitmproxy_rs_windows`/`mitmproxy_rs_macos` packages containing the platform-specific bits, and have `mitmproxy_rs` declare conditional dependencies on these. This would keep things nicely separated, and we could actually avoid the build.rs lets-copy-over-binaries nonsense. The downside is that we have more Python packages and more related compexity.

@mitmproxy/devs, @emanuele-em, any thoughts?

**Comment by emanuele-em** [comment]
I don't have a strong opinion but the most natural solution seems to be the third one, keeping things strictly separate sounds good even for future maintenance, more complexity (although they are actually quite isolated from each other) but also more clear and more clean

**Comment by mhils** [comment]
Yeah, that's probably the way to go. Let me see how that leads us on Windows before we fully commit. :)

**Comment by mhils** [comment]
Ok, turns out that building a windows-redirector Python package individually is more complex than expected:

1. maturin would support distributing binary applications (https://www.maturin.rs/bindings.html#bin).
   Unfortunately I don't think we can use this:
    1.  We need to place WinDivert.dll and friends in the same directory and there does not seem to be a good way to do that (maturin places the binary directly in Python's Scripts/bin directory). 
    3. PyInstaller does not include these scripts in its distribution (at least I think - haven't looked closer because of the WinDivert issue). 
    4. maturin won't help us for the (Swift-based) macOS redirector anyhow.
2. The next thing I looked at is Hatch with custom build hooks[^setuptools]: https://discuss.python.org/t/custom-build-steps-moving-bokeh-off-setup-py/16128/3. It's relatively straightforward to build a working bdist here. However, it is not as straightforward to build a working sdist because our Rust executables depend on local dependencies (the top-level "mitmproxy" crate) and Git dependencies (e.g. @emanuele-em's security-framework fork). We need to include at least the local dependencies in the sdist to build. I see two options here going forward:
    1. Only provide a bdist on PyPI and let downstream build manually from the Git repo.
    2. Run `cargo vendor`[^cargo-package] and then produce an sdist with that. The downside with this is that we will end up with a very manual build script...

I'm leaning towards only providing bdists for macOS and Windows. For the macOS redirector, the binaries need to be signed to work anyhow (so the sdist isn't very useful). For Windows, we don't have any downstream repackaging anyhow. For Linux, we don't have platform-specific stuff yet.

/cc @decathorpe - thoughts on this with your Fedora packaging background?

[^cargo-package]: We really don't want to ship a copy of crates.io in the sdist, but `cargo package` does not work for us because of the abovementioned Git dependencies which it refuses to handle.
[^setuptools]: Setuptools would probably work as well, but Hatch was more straightforward to get started with.

**Comment by mhils** [comment]
After pondering on this a bit more, I feel that the most useful approach for now would be to provide:

1. bdists for all major platforms,[^plats] 
2. an sdist that works on Linux[^change], and 
3. clear error messages in build.rs for all other platforms.

The reasoning behind that is as follows:

1. On macOS, `pip install --no-binary` will not work no matter what we do, because the redirector needs to be signed.[^oof]
2. On Linux, producing an sdist is still easy for us and it makes downstream's job easier.
3. On Windows, setting up working bdists would require a lot of complexity - and there is no real interest in building from source here anyways.

[^change]: This may change in the future similar to macOS/Windows if we require platform-specific external binaries.
[^plats]: Windows x64, Linux x64, Linux aarch64, macOS x64, macOS aarch64
[^oof]: We _could_ include the binary in the sdist to overcome that, but that defeats the purpose of a source distribution in the first place.

**Comment by mhils** [comment]
This has mostly been fixed now:

1. `mitmproxy-rs` now is a pure Rust crate again that can simply be built with maturin. We're shipping an sdist compatible with all platforms, there is no build.rs anymore.
2. `mitmproxy-rs` now conditionally depends on the new `mitmproxy-windows` and `mitmproxy-macos` Python packages, which contain the platform-specific resources.
3. `mitmproxy-windows` and `mitmproxy-macos` are distributed as binary wheels only on PyPI.
4. `mitmproxy-windows` is LGPL (because of WinDivert), everything else is MIT.
5. For security-framework, we'll wait a bit; it looks like upstream is figuring out things and they'll have a new release eventually. :)
