### ISSUE TITLE
Mitmdump cannot take keyboard input.

### ISSUE THREAD

**Issue by TularJahaj** [mitmproxy/mitmproxy#632]
I have installed mitmproxy latest version in windows 7 with command pip install mitmproxy.my pip and setuptools all are up to date.python version is 2.7.10.
but when i run mitmdump from cmd it successfully can trace all network data.but i cannot intercept on it because no keyboard input it takes after running.even i cannot stop it with -q command.
my installation process has some error shown bellow:

Collecting mitmproxy
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connec
tion broken by 'ProtocolError('Connection aborted.', gaierror(11004, 'getaddrinf
o failed'))': /simple/mitmproxy/
Using cached mitmproxy-0.12.1.tar.gz
Collecting pyperclip>=1.5.8 (from mitmproxy)
Using cached pyperclip-1.5.11.zip
Requirement already satisfied (use --upgrade to upgrade): pyasn1>0.1.2 in c:\pyt
hon27\lib\site-packages (from mitmproxy)
Collecting tornado>=4.0.2 (from mitmproxy)
Using cached tornado-4.2.tar.gz
Collecting netlib<0.13,>=0.12 (from mitmproxy)
Using cached netlib-0.12.1.tar.gz
Collecting blinker>=1.3 (from mitmproxy)
Downloading blinker-1.3.tar.gz (91kB)
100% |################################| 94kB 61kB/s
Collecting configargparse>=0.9.3 (from mitmproxy)
Downloading ConfigArgParse-0.9.3.tar.gz
Collecting pydivert>=0.0.7 (from mitmproxy)
Downloading pydivert-0.0.7.zip
Collecting backports.ssl-match-hostname (from tornado>=4.0.2->mitmproxy)
Downloading backports.ssl_match_hostname-3.4.0.2.tar.gz
Collecting certifi (from tornado>=4.0.2->mitmproxy)
Downloading certifi-2015.04.28-py2.py3-none-any.whl (373kB)
100% |################################| 376kB 70kB/s
Requirement already satisfied (use --upgrade to upgrade): cffi in c:\python27\li
b\site-packages (from netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL>=0.15.1 in c
:\python27\lib\site-packages (from netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.9 in c
:\python27\lib\site-packages (from netlib<0.13,>=0.12->mitmproxy)
Collecting passlib>=1.6.2 (from netlib<0.13,>=0.12->mitmproxy)
Downloading passlib-1.6.2.tar.gz (408kB)
100% |################################| 409kB 58kB/s
Collecting hpack>=1.0.1 (from netlib<0.13,>=0.12->mitmproxy)
Downloading hpack-1.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pycparser in c:\python
27\lib\site-packages (from cffi->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in c:\pytho
n27\lib\site-packages (from pyOpenSSL>=0.15.1->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\pytho
n27\lib\site-packages (from cryptography>=0.9->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): enum34 in c:\python27\
lib\site-packages (from cryptography>=0.9->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): idna in c:\python27\li
b\site-packages (from cryptography>=0.9->netlib<0.13,>=0.12->mitmproxy)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in c:\python
27\lib\site-packages (from cryptography>=0.9->netlib<0.13,>=0.12->mitmproxy)
Building wheels for collected packages: mitmproxy, pyperclip, tornado, netlib, b
linker, configargparse, pydivert, backports.ssl-match-hostname, passlib
Running setup.py bdist_wheel for mitmproxy
Stored in directory: C:\Users\TularJahaj\AppData\Local\pip\Cache\wheels\3d\e0\
00\9ce27bb0fd7ef8af39912ea95ea42ead5c7ab8dcce5e9a7f10
Running setup.py bdist_wheel for pyperclip
Stored in directory: C:\Users\TularJahaj\AppData\Local\pip\Cache\wheels\61\3e\
f8\f906ed5088f3a679725644a9b8860e42bac38ee7f607ae2dc3
Running setup.py bdist_wheel for tornado
Stored in directory: C:\Users\TularJahaj\AppData\Local\pip\Cache\wheels\bd\20\
c8\6bec1ed7ad88e2fb58333301e8d1f05610231441dcf4740cb5
Running setup.py bdist_wheel for netlib
Stored in directory: C:\Users\TularJahaj\AppData\Local\pip\Cache\wheels\31\43\
6d\d8965bf85110394a2536b6e11439d962f271f3fc4afdf2ab91
Running setup.py bdist_wheel for blinker
Stored in directory: C:\Users\TularJahaj\AppData\Local\pip\Cache\wheels\50\80\
79\716f1148d4a8f868755b05259988deccce37edbfb195ded724
Running setup.py bdist_wheel for configargparse
Stored in directory: C:\Users\TularJahaj\AppData\Local\pip\Cache\wheels\45\0e\
36\f2faf12912c3968ea911d45349b2271a31ca8f70f7865a0dbf
Running setup.py bdist_wheel for pydivert
Complete output from command C:\Python27\python.exe -c "import setuptools;fi
le='c:\users\tularj~1\appdata\local\temp\pip-build-bltjn\pydivert\set
up.py';exec(compile(open(file_).read().replace('\r\n', '\n'), file, 'exec
'))" bdist_wheel -d c:\users\tularj~1\appdata\local\temp\tmp9by11mpip-wheel-:
running bdist_wheel
running build
running build_py
creating build
creating build\lib
creating build\lib\pydivert
copying pydivert\decorators.py -> build\lib\pydivert
copying pydivert\enum.py -> build\lib\pydivert
copying pydivert\exception.py -> build\lib\pydivert
copying pydivert\install.py -> build\lib\pydivert
copying pydivert\models.py -> build\lib\pydivert
copying pydivert\windivert.py -> build\lib\pydivert
copying pydivert\winutils.py -> build\lib\pydivert
copying pydivert__init.py -> build\lib\pydivert
creating build\lib\pydivert\tests
copying pydivert\tests\test_installer.py -> build\lib\pydivert\tests
copying pydivert\tests\test_models.py -> build\lib\pydivert\tests
copying pydivert\tests\test_windivert.py -> build\lib\pydivert\tests
copying pydivert\tests\test_winutils.py -> build\lib\pydivert\tests
copying pydivert\tests__init__.py -> build\lib\pydivert\tests
installing to build\bdist.win32\wheel
running install
running install_lib
creating build\bdist.win32
creating build\bdist.win32\wheel
creating build\bdist.win32\wheel\pydivert
copying build\lib\pydivert\decorators.py -> build\bdist.win32\wheel\pydivert-0
.0.7.data..\pydivert
copying build\lib\pydivert\enum.py -> build\bdist.win32\wheel\pydivert-0.0.7.d
ata..\pydivert
copying build\lib\pydivert\exception.py -> build\bdist.win32\wheel\pydivert-0.
0.7.data..\pydivert
copying build\lib\pydivert\install.py -> build\bdist.win32\wheel\pydivert-0.0.
7.data..\pydivert
copying build\lib\pydivert\models.py -> build\bdist.win32\wheel\pydivert-0.0.7
.data..\pydivert
creating build\bdist.win32\wheel\pydivert\tests
copying build\lib\pydivert\tests\test_installer.py -> build\bdist.win32\wheel\
pydivert-0.0.7.data..\pydivert\tests
copying build\lib\pydivert\tests\test_models.py -> build\bdist.win32\wheel\pyd
ivert-0.0.7.data..\pydivert\tests
copying build\lib\pydivert\tests\test_windivert.py -> build\bdist.win32\wheel\
pydivert-0.0.7.data..\pydivert\tests
copying build\lib\pydivert\tests\test_winutils.py -> build\bdist.win32\wheel\p
ydivert-0.0.7.data..\pydivert\tests
copying build\lib\pydivert\tests__init__.py -> build\bdist.win32\wheel\pydive
rt-0.0.7.data..\pydivert\tests
copying build\lib\pydivert\windivert.py -> build\bdist.win32\wheel\pydivert-0.
0.7.data..\pydivert
copying build\lib\pydivert\winutils.py -> build\bdist.win32\wheel\pydivert-0.0
.7.data..\pydivert
copying build\lib\pydivert__init__.py -> build\bdist.win32\wheel\pydivert-0.0
.7.data..\pydivert
running install_egg_info
running egg_info
writing requirements to pydivert.egg-info\requires.txt
writing pydivert.egg-info\PKG-INFO
writing top-level names to pydivert.egg-info\top_level.txt
writing dependency_links to pydivert.egg-info\dependency_links.txt
warning: manifest_maker: standard file '-c' not found

reading manifest file 'pydivert.egg-info\SOURCES.txt'
writing manifest file 'pydivert.egg-info\SOURCES.txt'
Copying pydivert.egg-info to build\bdist.win32\wheel\pydivert-0.0.7.data..\py
divert-0.0.7-py2.7.egg-info
running install_scripts
Running WinDivert install task
Downloading https://github.com/basil00/Divert/releases/download/v1.1.7/WinDive
rt-1.1.7-WDDK.zip...
Uncompressing WinDivert-1.1.7-WDDK.zip...
Copying build\bdist.win32\wheel\pydivert-0.0.7.data..\WinDivert-1.1.7-WDDK\x8
6\WinDivert.dll to C:\Python27\DLLs
error: [Errno 2] No such file or directory: 'build\bdist.win32\wheel\pydive
rt-0.0.7.data..\WinDivert-1.1.7-WDDK\x86\WinDivert.dll'

Failed building wheel for pydivert
Running setup.py bdist_wheel for backports.ssl-match-hostname
Stored in directory: C:\Users\TularJahaj\AppData\Local\pip\Cache\wheels\81\3d\
36\f3c726a42caed585046d710e0e450bda1075c61c1c43443831
Running setup.py bdist_wheel for passlib
Stored in directory: C:\Users\TularJahaj\AppData\Local\pip\Cache\wheels\5f\53\
de\eec3f96594a49109cff49df308f6549486274df2d272c07754
Successfully built mitmproxy pyperclip tornado netlib blinker configargparse bac
kports.ssl-match-hostname passlib
Failed to build pydivert
Installing collected packages: pyperclip, backports.ssl-match-hostname, certifi,
tornado, passlib, hpack, netlib, blinker, configargparse, pydivert, mitmproxy
Running setup.py install for pydivert
Successfully installed backports.ssl-match-hostname-3.4.0.2 blinker-1.3 certifi-
2015.4.28 configargparse-0.9.3 hpack-1.0.1 mitmproxy-0.12.1 netlib-0.12.1 passli
b-1.6.2 pydivert-0.0.7 pyperclip-1.5.11 tornado-4.2

**Comment by cortesi** [comment]
Hi there. Mitmdump (as opposed to mitmproxy) is a non-interactive command-line program. The only keyboard interaction it accepts is termination - ctrl-c on most systems. You're probably after mitmproxy, which unfortunately is not supported on windows at the moment.

**Comment by TularJahaj** [comment]
One more question plz,
How can i intercept/alter connection with mitmdump without keyboard input?

**Comment by mhils** [comment]
You can modify requests/responses programatically using inline scripts.
