### ISSUE TITLE
how to set default view in mitmweb

### ISSUE THREAD

**Issue by Stephen0910** [mitmproxy/mitmproxy#6321]
### Discussed in https://github.com/mitmproxy/mitmproxy/discussions/6320

<div type='discussions-op-text'>

<sup>Originally posted by **Stephen0910** August 13, 2023</sup>
![image](https://github.com/mitmproxy/mitmproxy/assets/26613645/020f3285-8024-4927-9d41-8c25baf7d544)

I created a new view, but it's at the bottom.
May i move it up?
what's the better, it changes to the default view without selecting.
Thanks.
</div>

**Comment by mhils** [comment]
See https://github.com/mitmproxy/mitmproxy/discussions/6320
