### ISSUE TITLE
Associate log messages with flows

### ISSUE THREAD

**Issue by kolyuchiy** [mitmproxy/mitmproxy#6322]
#### Problem Description

I had an idea to write a script that would look at all responses of certain polling endpoint and print diffs between consecutive responses. My proposal also could be useful in other similar cases where your script parses some complex requests or responses or chains of flows and outputs some info based on that.

#### Proposal

So I thought that it would be useful to add a new tab in flow view on the same level with Request/Response/Detail. And add script APIs to log specificaly to some flow's log. 

#### Alternatives

I could output to console log or files on disk, but that would be inconvenient to look at and analyze and to associate different outputs with corresponding flows. 

#### Additional context

I use console UI.

**Comment by kolyuchiy** [comment]
Similar https://github.com/mitmproxy/mitmproxy/issues/5704

**Comment by Prinzhorn** [comment]
Does `flow.metadata` not suit your use-case? It's rendered in the "Detail" tab.

**Comment by kolyuchiy** [comment]
Thanks, I'll check this out.
