### ISSUE TITLE
mitmweb: Docker image does not load ~/.mitmproxy/config.yaml file

### ISSUE THREAD

**Issue by Valgard** [mitmproxy/mitmproxy#6326]
#### Problem Description
When I use the official docker image `mitmproxy/mitmproxy` and use `mitmweb` as an argument for the docker entrypoint `docker-entrypoint.sh`, the config.yaml file doesn't load. However, if I use `mitmweb` as an entry point, the config file is loaded.

If I pass all the parameters as addional arguments to the entry point (in addition to `mitmweb`), these are taken into account in contrast to the config file.

#### Steps to reproduce the behavior:
1. create a `config.yaml` file:
  ```
  listen_host: 0.0.0.0
  listen_port: 8888
  web_host: 0.0.0.0
  web_port: 8889
  ```

2. Start docker container with mounted `config.yaml` file and `mitmweb` as argument for `docker-entrypoint.sh` script:
  ```
  docker run -d -it --rm --name mitmproxy -p 8888:8888 -p 8889:8889 -v ${PWD}/config.yaml:/root/.mitmproxy/config.yaml mitmproxy/mitmproxy:10.0.0 docker-entrypoint.sh mitmweb
  ```

#### System Information
```
Mitmproxy: 10.0.0
Python:    3.11.4
OpenSSL:   OpenSSL 3.1.2 1 Aug 2023
Platform:  Linux-5.15.49-linuxkit-pr-aarch64-with-glibc2.31
```

**Comment by Prinzhorn** [comment]
Not an expert on the Docker version, but shouldn't it be `/home/mitmproxy/.mitmproxy/config.yaml` and not `/root/.mitmproxy/config.yaml`? Docker runs mitmproxy as `mitmproxy` user.

https://github.com/mitmproxy/mitmproxy/blob/7aa41a8467f73d86ad6ce5b95439c147a26896f9/release/docker/Dockerfile

https://github.com/mitmproxy/mitmproxy/blob/7aa41a8467f73d86ad6ce5b95439c147a26896f9/release/docker/docker-entrypoint.sh#L8

**Comment by Valgard** [comment]
Unfortunately not. There is no USER statement in the dockerfile, so the container runs as root. You can check it by connecting to container and running `id`.

**Comment by Valgard** [comment]
Okay, i see you set the path (`MITMPROXY_PATH`) in the entry point file. This of course explains that it doesn't load `/root/.mitmproxy/config.yaml`.

Nevertheless, mitmproxy runs as user `root` and not as `mitmproxy`.

**Comment by mhils** [comment]
Check the entrypoint script that @Prinzhorn linked. User depends on the arguments. :-)
