### ISSUE TITLE
uppercase breaks block_list

### ISSUE THREAD

**Issue by ghost** [mitmproxy/mitmproxy#6329]
#### Problem Description

using these values for `block_list`

~~~
/~u AccountsSignInUi/444
/~u accountssigninui/444
~~~

neither one is blocking the expected URL:

~~~
https://accounts.google.com/v3/signin/_/AccountsSignInUi/data/batchexecute
~~~

this works:

~~~
/~u .ccounts.ign.n.i/444
~~~

why is uppercase character breaking the search?

#### System Information

tried with both:

~~~
> mitmproxy --version
Mitmproxy: 8.0.0 binary
Python:    3.10.2
OpenSSL:   OpenSSL 1.1.1n  15 Mar 2022
Platform:  Windows-10-10.0.18363-SP0

> mitmproxy --version
Mitmproxy: 10.0.0 binary
Python:    3.11.4
OpenSSL:   OpenSSL 3.1.2 1 Aug 2023
Platform:  Windows-10-10.0.18363-SP0
~~~

**Comment by Prinzhorn** [comment]
I didn't verify this, but peeking at the code the issue should be here (I literally just ctrl+f for `lower`):

https://github.com/mitmproxy/mitmproxy/blob/7aa41a8467f73d86ad6ce5b95439c147a26896f9/mitmproxy/addons/blocklist.py#L27

If you are interested you can create a PR and add a case sensitive test here https://github.com/mitmproxy/mitmproxy/blob/7aa41a8467f73d86ad6ce5b95439c147a26896f9/test/mitmproxy/addons/test_blocklist.py

**Comment by 1268** [comment]
I am using a script like this as a workaround:

~~~py
from mitmproxy import http

def request(f: http.HTTPFlow) -> None:
   if f.request.path == '/v3/signin/_/AccountsSignInUi/data/batchexecute':
      f.kill()
~~~
