### ISSUE TITLE
map_remote and stream_large_bodies not working together

### ISSUE THREAD

**Issue by leaph** [mitmproxy/mitmproxy#6337]
#### Problem Description
The two options "map_remote" and "stream_large_bodies" do not seem to work together. I tried Proxyman for the same purpose, it has no issues with the same requirement, works flawlessly. As I need to run an MITM proxy with these capabilities on a Raspberry Pi, I am looking into mitmproxy.

#### Steps to reproduce the behavior:
1.  This is the full content of my config.yaml file (I am not allowed to share the concrete endpoints, therefore replaced with xxx)

map_remote:
  -"|~m POST|//api.xxx.com/|//xxx.cc/api/"
stream_large_bodies: 1k

2. The payload is empty: "content missing".
3. If I remove the "stream_large_bodies: 1k" part, then it is working fine, however, I get the full response in one chunk.

#### System Information
mitmproxy --version
Mitmproxy: 10.0.0
Python:    3.11.5
OpenSSL:   OpenSSL 3.1.2 1 Aug 2023
Platform:  macOS-13.5.1-x86_64-i386-64bit

**Comment by mhils** [comment]
This needs a better reproducer. The following works for me:
```
mitmdump \
  --set map_remote=#//example.com/#//example.org/ \
  --set stream_large_bodies=100

curl -x localhost:8080 -k https://example.com
```
