### ISSUE TITLE
Any Request or Response Time View

### ISSUE THREAD

**Issue by wulie88** [mitmproxy/mitmproxy#634]
Any option for detail timing, such as request sent, watting, content download?

**Comment by mhils** [comment]
There is a feature for this in mitmproxy 0.12:
![](https://maximilianhils.com/upload/2015-06/2015-06-17_02-08-53.png)

**Comment by cortesi** [comment]
As an aside, we need to improve the way that timing is displayed there - timestamp for connection established, and then time elapsed from there for everything else.

**Comment by mhils** [comment]
Yes, having something similar to what mitmweb has would be a good contribution.

**Comment by wulie88** [comment]
Looking forward to the new version, but I have modified the code and display the request time.
