### ISSUE TITLE
pip install broken FreeBSD amd64

### ISSUE THREAD

**Issue by guest1022** [mitmproxy/mitmproxy#6366]
Trying to 'pip install mitmproxy-10.0.0-py3-none-any.whl'

Can't compile boringtun for mitmproxy-rs.

> 
>       error: could not compile `boringtun` (lib) due to 15 previous errors
>       warning: build failed, waiting for other jobs to finish...
>       error: could not compile `smoltcp` (lib) due to 7 previous errors
>       💥 maturin failed
>         Caused by: Failed to build a native library through cargo
>         Caused by: Cargo build finished with "exit status: 101": `PYTHON_SYS_EXECUTABLE="/usr/local/bin/python3.11" "cargo" "rustc" "--release" "--manifest-path" "/tmp/pip-install-7q2ikgl5/mitmproxy-rs_45fb06fa56f04c798d29b4013f9ebad6/Cargo.toml" "--message-format" "json" "--lib"`
>       error[E0425]: cannot find value `BIOCSETIF` in this scope
>         --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoltcp-0.10.0/src/phy/sys/bpf.rs:79:29
>          |
>       79 |         try_ioctl!(self.fd, BIOCSETIF, &mut self.ifreq);
>          |                             ^^^^^^^^^ not found in this scope
>          |
>       help: consider importing one of these items
>          |
>       1  + use crate::phy::sys::bpf::libc::BIOCSETIF;
>          |
>       1  + use libc::BIOCSETIF;
>          |
> 
> 
>       error[E0425]: cannot find value `BIOCIMMEDIATE` in this scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoltcp-0.10.0/src/phy/sys/bpf.rs:107:29
>           |
>       107 |         try_ioctl!(self.fd, BIOCIMMEDIATE, &mut bufsize as *mut libc::c_int);
>           |                             ^^^^^^^^^^^^^ not found in this scope
>           |
>       help: consider importing one of these items
>           |
>       1   + use crate::phy::sys::bpf::libc::BIOCIMMEDIATE;
>           |
>       1   + use libc::BIOCIMMEDIATE;
>           |
> 
> 
>       error[E0425]: cannot find value `BIOCGBLEN` in this scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoltcp-0.10.0/src/phy/sys/bpf.rs:108:29
>           |
>       108 |         try_ioctl!(self.fd, BIOCGBLEN, &mut bufsize as *mut libc::c_int);
>           |                             ^^^^^^^^^ not found in this scope
>           |
>       help: consider importing one of these items
>           |
>       1   + use crate::phy::sys::bpf::libc::BIOCGBLEN;
>           |
>       1   + use libc::BIOCGBLEN;
>           |
> 
> 
>       error[E0425]: cannot find value `BPF_HDRLEN` in this scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoltcp-0.10.0/src/phy/sys/bpf.rs:121:35
>           |
>       121 |             if len == -1 || len < BPF_HDRLEN as isize {
>           |                                   ^^^^^^^^^^ not found in this scope
> 
> 
>       error[E0425]: cannot find value `BPF_HDRLEN` in this scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoltcp-0.10.0/src/phy/sys/bpf.rs:129:25
>           |
>       129 |                 &buffer[BPF_HDRLEN] as *const u8 as *const libc::c_void,
>           |                         ^^^^^^^^^^ not found in this scope
> 
> 
>       error[E0425]: cannot find value `BPF_HDRLEN` in this scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoltcp-0.10.0/src/phy/sys/bpf.rs:130:23
>           |
>       130 |                 len - BPF_HDRLEN,
>           |                       ^^^^^^^^^^ not found in this scope
> 
> 
>       error[E0432]: unresolved import `poll`
>         --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/mod.rs:47:5
>          |
>       47 | use poll::{EventPoll, EventRef, WaitResult};
>          |     ^^^^ use of undeclared crate or module `poll`
> 
> 
>       error[E0432]: unresolved import `tun`
>         --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/mod.rs:48:5
>          |
>       48 | use tun::{errno, errno_str, TunSocket};
>          |     ^^^ use of undeclared crate or module `tun`
> 
> 
>       error[E0308]: mismatched types
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/api.rs:67:57
>           |
>       67  |                         "set=1" => api_set(&mut reader, d),
>           |                                    -------              ^ types differ in mutability
>           |                                    |
>           |                                    arguments to this function are incorrect
>           |
>           = note: expected mutable reference `&mut LockReadGuard<'_, Device>`
>                              found reference `&Device`
>       note: function defined here
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/api.rs:202:4
>           |
>       202 | fn api_set(reader: &mut BufReader<&UnixStream>, d: &mut LockReadGuard<Device>) -> i32 {
>           |    ^^^^^^^                                      -----------------------------
> 
> 
>       error[E0308]: mismatched types
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/api.rs:97:57
>           |
>       97  |                         "set=1" => api_set(&mut reader, d),
>           |                                    -------              ^ types differ in mutability
>           |                                    |
>           |                                    arguments to this function are incorrect
>           |
>           = note: expected mutable reference `&mut LockReadGuard<'_, Device>`
>                              found reference `&Device`
>       note: function defined here
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/api.rs:202:4
>           |
>       202 | fn api_set(reader: &mut BufReader<&UnixStream>, d: &mut LockReadGuard<Device>) -> i32 {
>           |    ^^^^^^^                                      -----------------------------
> 
> 
>       error[E0599]: no method named `set_fwmark` found for struct `Arc<UDPSocket>` in the current scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/peer.rs:130:22
>           |
>       130 |             udp_conn.set_fwmark(fwmark)?;
>           |                      ^^^^^^^^^^ method not found in `Arc<UDPSocket>`
> 
> 
>       error[E0063]: missing field `sin_len` in initializer of `libc::sockaddr_in`
>         --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/udp_unix.rs:18:20
>          |
>       18 |         let addr = sockaddr_in {
>          |                    ^^^^^^^^^^^ missing `sin_len`
> 
> 
>       error[E0063]: missing field `sin_len` in initializer of `libc::sockaddr_in`
>         --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/udp_unix.rs:58:20
>          |
>       58 |         let addr = sockaddr_in {
>          |                    ^^^^^^^^^^^ missing `sin_len`
> 
> 
>       error[E0063]: missing field `sin_len` in initializer of `libc::sockaddr_in`
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/udp_unix.rs:102:20
>           |
>       102 |         let addr = sockaddr_in {
>           |                    ^^^^^^^^^^^ missing `sin_len`
> 
> 
>       error[E0063]: missing field `sin_len` in initializer of `libc::sockaddr_in`
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/udp_unix.rs:181:24
>           |
>       181 |         let mut addr = sockaddr_in {
>           |                        ^^^^^^^^^^^ missing `sin_len`
> 
> 
>       error[E0282]: type annotations needed for `Arc<T, A>`
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/mod.rs:231:17
>           |
>       231 |             let queue = Arc::clone(&device_lock.queue);
>           |                 ^^^^^
>       ...
>       234 |                 match queue.wait() {
>           |                             ---- type must be known at this point
>           |
>       help: consider giving `queue` an explicit type, where the type for type parameter `T` is specified
>           |
>       231 |             let queue: Arc<T, A> = Arc::clone(&device_lock.queue);
>           |                      +++++++++++
> 
> 
>       error[E0599]: no method named `set_fwmark` found for reference `&Arc<UDPSocket>` in the current scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/mod.rs:491:18
>           |
>       491 |             sock.set_fwmark(mark)?;
>           |                  ^^^^^^^^^^ method not found in `&Arc<UDPSocket>`
> 
> 
>       error[E0599]: no method named `set_fwmark` found for reference `&Arc<UDPSocket>` in the current scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/mod.rs:495:18
>           |
>       495 |             sock.set_fwmark(mark)?;
>           |                  ^^^^^^^^^^ method not found in `&Arc<UDPSocket>`
> 
> 
>       error[E0599]: no method named `set_fwmark` found for reference `&Arc<UDPSocket>` in the current scope
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/mod.rs:501:22
>           |
>       501 |                 sock.set_fwmark(mark)?
>           |                      ^^^^^^^^^^ method not found in `&Arc<UDPSocket>`
> 
> 
>       error[E0282]: type annotations needed
>          --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boringtun-0.5.3/src/device/mod.rs:802:38
>           |
>       802 | ...                   conn.write(packet);
>           |                            ^^^^^ cannot infer type for type parameter `T` declared on the enum `Option`
> 
> 
>       error: aborting due to 14 previous errors
> 
> 
>       Some errors have detailed explanations: E0063, E0282, E0308, E0432, E0599.
> 
>       For more information about an error, try `rustc --explain E0063`.
> 
>       error: aborting due to 6 previous errors
> 
> 
>       For more information about this error, try `rustc --explain E0425`.
> 
>       Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/usr/local/bin/python3.11', '--compatibility', 'off'] returned non-zero exit status 1
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for mitmproxy-rs

**Comment by fpusersuggest** [comment]
Hello, how did you solve it ?
