### ISSUE TITLE
Getting error - Couldn't parse: falling back to Raw

### ISSUE THREAD

**Issue by olezvinskyi** [mitmproxy/mitmproxy#6367]
#### Problem Description
 Mitmproxy couldn't parse request . 

#### Steps to reproduce the behavior:
1. Launch TuneIn app
2. Launch mitmweb
3. Find POST request https://ms4.applovin.com .....

<img width="777" alt="Screenshot 2023-09-14 at 23 08 54" src="https://github.com/mitmproxy/mitmproxy/assets/103524879/aee69a71-538c-4d53-80e9-fcb958cfc4f4">

#### System Information
Mitmproxy: 8.1.1
Python:    3.10.13
OpenSSL:   OpenSSL 3.0.5 5 Jul 2022
Platform:  macOS-13.4.1-arm64-arm-64bit

**Comment by mhils** [comment]
This is not a bug. "Couldn't parse" states that we couldn't parse it as HTML or such and display it without markup, the message body is exactly the random string you are seeing.

(You're also using an outdated mitmproxy version, which is generally unsupported)
