### ISSUE TITLE
mitmdump memory usage is always constantly growing

### ISSUE THREAD

**Issue by k0xxxx** [mitmproxy/mitmproxy#6371]
#### Problem Description
Hello dear. I'm using mitmdump for a websocket connection that sends a large and continuous stream of text data. I see how RAM consumption increases over time. And now it’s more than 1 gigabyte and continues to grow until I kill the process. I use binary precompiled version for linux. 
I only use "map_local" for one single url. The websocket traffic is a side connection that I cannot bypass the mitmproxy, since the application being attacked does not allow it to do so. I don't need to save any connection history.

Launch parameters:
./mitmdump -q --set map_local="|site.com|./map/site.txt" --set block_global="false" --flow-detail 0

#### System Information
Mitmproxy: 10.0.0 binary
Python:    3.11.4
OpenSSL:   OpenSSL 3.1.2 1 Aug 2023
Platform:  Linux-5.4.0-153-generic-x86_64-with-glibc2.31

**Comment by mhils** [comment]
mitmdump memory usage generally should not grow. Can you provide steps to reproduce please?

**Comment by k0xxxx** [comment]
Shure. I record video https://www.youtube.com/watch?v=xeiFie7NuNg (the video is still being processed, it will be in good quality later). Most of the traffic is websocket text messages

**Comment by mhils** [comment]
Thanks, that was helpful. For the WebSocket connection: Is this one continuous WebSocket connection that is kept alive? What happens if you stop the connection? Does that free memory?

**Comment by k0xxxx** [comment]
1. Yes, it is keep alive connections 
<img width="145" alt="Screenshot_222" src="https://github.com/mitmproxy/mitmproxy/assets/93264824/d161c745-ee84-4d9f-a9ef-5fe9a3119cbb">

2. After an active connection is interrupted, the memory is not cleared.

**Comment by k0xxxx** [comment]
Any ideas to solve this problem?

**Comment by mhils** [comment]
If this is a constant connection, I'm not surprised that memory usage keeps climbing. You could maybe mitigate this by implementing a small addon that clears out old WebSocket messages while the flow is still live:

```python
def websocket_message(flow):
    flow.websocket.messages = flow.websocket.messages[-1:]
```
This is untested, but may work? :)
