### ISSUE TITLE
HTTP/2 protocol error: Received header value surrounded by whitespace b'X-Client-Ip,X-Server-Ip,X-Upstream-Ip '

### ISSUE THREAD

**Issue by 010101fff** [mitmproxy/mitmproxy#6383]
#### Problem Description
find a bug,
When I visited www.qq.com, a bug appeared，
log:
HTTP/2 protocol error: Received header value surrounded by whitespace b'X-Client-Ip,X-Server-Ip,X-Upstream-Ip '

http response code : 502 Bad Gateway

**Comment by Prinzhorn** [comment]
Please follow the template that is provided when you create a new bug report. "Steps to reproduce the behavior" and "System Information" is missing.

**Comment by mhils** [comment]
You may need to set https://docs.mitmproxy.org/stable/concepts-options/#validate_inbound_headers

**Comment by 010101fff** [comment]
> You may need to set https://docs.mitmproxy.org/stable/concepts-options/#validate_inbound_headers

thx
