### ISSUE TITLE
Unable to connect to mitm.it

### ISSUE THREAD

**Issue by QwertyCoolMT** [mitmproxy/mitmproxy#6385]
#### Problem Description
no device can successfully connect to and reach http://mitm.it after entering proxy details, android, ios both tested, multiple devices, hosted on Mitmweb, windows 10.

ios device can ping the host pc, and connect to other webservers hosted on lan by the same pc.
I've tried this without the listen-host and listen port commands, i've tried this with different ports. 

#### Steps to reproduce the behavior:
1. mitmweb --listen-host 192.168.5.180 -p 5000 -v
2. enter http proxy settings on ios/android device as per above
3. attempt to connect to mitm.it 
4. timeout error. no chatter in terminal about any sort of connection attempt

#### System Information
```
C:\WINDOWS\system32>mitmweb --version
Mitmproxy: 3.0.3
Python:    3.6.4
OpenSSL:   OpenSSL 1.1.0h  27 Mar 2018
Platform:  Windows-10-10.0.19041-SP0
```

**Comment by Prinzhorn** [comment]
> Mitmproxy: 3.0.3

:eyes: :older_adult: 

This was released 5.5 years ago.

Feel free to open a new issue if this happens with mitmproxy 10 as well.
