### ISSUE TITLE
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

### ISSUE THREAD

**Issue by sobhan-m94** [mitmproxy/mitmproxy#6394]
#### Problem Description
![image](https://github.com/mitmproxy/mitmproxy/assets/44964722/109b9382-089e-44be-8b57-213d7c673cae)

#### System Information
Mitmproxy: 6.0.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.0.2 15 Mar 2022
Platform:  Linux-6.2.0-33-generic-x86_64-with-glibc2.35

**Comment by mhils** [comment]
1. You are using an outdated mitmproxy version, please upgrade.
2. The error you are seeing is likely an artifact from mitmproxy importing some Python packages. That's specific to your environment and not a mitmproxy bug. If you install mitmproxy in a clean venv, you should be fine.

**Comment by sobhan-m94** [comment]
@mhils 
![image](https://github.com/mitmproxy/mitmproxy/assets/44964722/b6aa3f64-ab01-4f7c-961a-0e800f746b69)
