### ISSUE TITLE
Mitmdump too slow response  when high traffic

### ISSUE THREAD

**Issue by NatNyt** [mitmproxy/mitmproxy#6406]
#### Problem Description
Mitmdump too slow response when high traffic like 1,000 - 5,000 per seconds

#### Steps to reproduce the behavior:
1. Setup Python script 
```py
from mitmproxy import http, ctx
import json

file_path = 'robloxClientAppSettings.json'
config_path = "config.json"
data = None
config = None
with open(file_path, 'r') as json_file:
    data = json.load(json_file)
with open(config_path, 'r') as json_file:
     config = json.load(json_file)
def response(flow: http.HTTPFlow) -> None:
        if flow.request.url == "https://www.roblox.com/mobileapi/check-app-version?appVersion=AppUWPV2.592.586":
             flow.response.content = '{"data":{"UpgradeAction":"None"}} '.encode("utf-8")
        if config["injectClientAppSettings"] == True:
            if flow.request.url == "https://clientsettingscdn.roblox.com/v2/settings/application/UWPApp":
                if flow.response.content:
                    content = json.loads(flow.response.content)
                    for key, value in data.items():
                            content["applicationSettings"][key] = value
                    flow.response.content = json.dumps(content).encode('utf-8')           
```
2. start process with this command line mitmdump -s ./changever.py --set body_size_limit=34000g --set stream_large_bodies=34000g --set websocket=false --set flow_detail=1 --set allow_hosts=["roblox.com"] --set block_global=false --set anticache=true --set anticomp=true
3. when traffic like 1000 per seconds too slow reply client is timeout 

#### System Information
Mitmproxy: 10.1.1 binary
Python:    3.11.5
OpenSSL:   OpenSSL 3.1.3 19 Sep 2023
Platform:  Windows-10-10.0.19045-SP0

**Comment by mhils** [comment]
1000 req/s is out of scope for the project, sorry. Performance would request significant investment, and there's very little benefit to the average mitmproxy user. At the same time it opens the door for large-scale interception, which may not always have the best intentions. Long story short, you either need to load-balance between mitmproxy instances or use something else. I'd recommend the latter. :)
