### ISSUE TITLE
Can we have a homebrew tap for the latest mitmproxy

### ISSUE THREAD

**Issue by moonfruit** [mitmproxy/mitmproxy#6409]
#### Problem Description

From @mhils's Homebrew/homebrew-core#145547, I know that `mitmproxy` will be migrating from `formula` to `cask` in order to provide the latest version. But I do not want a `cask` because it needs to package with all dependencies in it. This increases disk space usage significantly and will not benefit from upgrading some Python dependencies packaged in `formula`.

#### Proposal
Please provide a `mitmproxy` maintained `homebrew` tap. It would be nice to include the bottle you built, but it doesn't matter.

#### Alternatives
For now, I just copied the code from Homebrew/homebrew-core#145547 to my own tap [moonfruit/homebrew-tap](https://github.com/moonfruit/homebrew-tap/blob/main/Formula/mitmproxy.rb) with some updated resources. It worked fine. I can maintain this myself for simple version upgrades. But I was worried that if something like `mitmproxy-macos` was introduced, I wouldn't be able to handle it. So a tap maintained by `mitmproxy` would be nice.

**Comment by mhils** [comment]
Thank you for the feedback, that's immensely useful! Is ~40mb an issue for you in practice?

**Comment by moonfruit** [comment]
I have a 256GB MacBook, but I don't think it's enough. Every byte counts. I use python frequently for coding and also utilize various third-party python development tools. The 40mb space difference can be used for other formulas.

**Comment by mhils** [comment]
We've shipped an app bundle with the latest patch release now, which is the basis for the Cask. We unfortunately don't want to maintain a separate formula going forward. If you have space constraints, I recommend `pip install`ing into your Homebrew Python env. :)
