### ISSUE TITLE
Couldn't parse: falling back to Raw

### ISSUE THREAD

**Issue by ciger7** [mitmproxy/mitmproxy#6413]
Hello, when I was checking the http packets of the Android Instagram application, I noticed that mitmproxy could not decode them.
I encountered the error: [cannot decode] Couldn't parse: falling back to Raw (i.instagram.com)
While the decoding of Instagram web (www.instagram.com) was done without any problem
I downloaded Instagram Android without protection from here: [https://github.com/itsMoji/Instagram_SSL_Pinning]

response headers file(id & ip is hidden): [body.txt](https://github.com/mitmproxy/mitmproxy/files/13069503/body.txt)

![Untitled](https://github.com/mitmproxy/mitmproxy/assets/98751866/26fdf461-404a-4aba-8b0d-2dce1ac57792)

**Comment by mhils** [comment]
See https://github.com/mitmproxy/mitmproxy/issues/4394
