### ISSUE TITLE
Better transparent proxying support

### ISSUE THREAD

**Issue by kuza55** [mitmproxy/mitmproxy#642]
I spent a little bit of time looking at how redsocks supports transparent proxying of all TCP to a SOCKS proxy, and the code is really quite straight forward: https://github.com/darkk/redsocks/blob/2e3f648809e27cc19cb7a8702f19b553a7ef9a81/base.c#L102

I was hoping this could be integrated into mitmproxy to allow better transparent proxying.

I'm looking to use mitmproxy to see/alter the data that malware running inside a VM gets (with the MITM script being different for each of my 25 VMs) and at the moment the only real way I can do this is to setup 25 separate ip tables, run 25 instances of redsocks and 25 instances of mitmproxy.

This is all doable, but I would much rather configure 1 iptable, run 1 instance of mitmproxy and have a script that alters its behaviour based on the source IP.

I'm happy to write the patch myself is anyone has any pointers on how to integrate it with the existing codebase.

**Comment by cortesi** [comment]
Hi there. It sounds like you have a very interesting project going there. Let me try to understand exactly what the limitation is that you're working around, here. If you're using NAT, we already have a set of platform modules that will extract the original address from the host translation table:

https://github.com/mitmproxy/mitmproxy/tree/master/libmproxy/platform

The particular function you linked to above is for ipf - if you're using iptables, the matching redsocks function is here: 

https://github.com/darkk/redsocks/blob/2e3f648809e27cc19cb7a8702f19b553a7ef9a81/base.c#L211

You can see from our host module, that we do almost exactly the same thing:

https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/platform/linux.py

So, if you have a set of VMs with traffic redirected into mitmproxy, and mitmproxy is run in transparent mode, you should already have all the pieces to have a single script that alters behaviour based on the source address. 

I'm sure I'm missing something here, but what? :)

**Comment by kuza55** [comment]
You know, I think I just missed that in the docs, sorry about that. This looks like it solves my problem perfectly.

**Comment by cortesi** [comment]
Great. Let me know if you hit any other hurdles.
