### ISSUE TITLE
Insufficient flexibility of LDAP Proxy Auth

### ISSUE THREAD

**Issue by outlaws-bai** [mitmproxy/mitmproxy#6426]
Insufficient flexibility of LDAP Proxy Auth

I noticed that in the Ldap Validator object, the username passed in during authentication queries will be set to cn. However, in our AD, CN is highly likely to be a Chinese name. Is there a solution to pass in other keys, such as SamAccountName

https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/addons/proxyauth.py#L212

![image](https://github.com/mitmproxy/mitmproxy/assets/80510016/a3b0eb31-2d9b-4fc9-8756-43fe0272d973)

**Comment by mhils** [comment]
Not our focus right now, but happy to look at a PR for this. :)
