### ISSUE TITLE
https websites don't load

### ISSUE THREAD

**Issue by whatsdis** [mitmproxy/mitmproxy#643]
I went to mitm.it and downloaded and added the CA for it on chrome.

when I go to https://github.com, the padlock is green but the website is blank.

I am getting back 403.

Upon inspection, it's having some trouble with Proxy-Authenticate.

I already provide a setHeader argument for Proxy Authroization.

please help.

**Comment by cortesi** [comment]
Hi there. Could you please give us some more information on what you're seeing, including:

- what version of mitmproxy you're using
- what the command-line arguments you're starting mitmproxy with are
- how you're setting the setHeader argument

From your description, I'm suspecting that there's some confusion regarding the proxy authentication and how it works.

**Comment by whatsdis** [comment]
mitmproxy 0.12.1

mitmproxy -U http://me:pwd@23.23.23.23:8080 --setheader :~q:Proxy-Authorization:'Basic bHWEOHbhzjSFUYZPQPBzxhnsxodihew':

when I navigate to any HTTPS page, it will just load blank screen, and mitmproxy reports 403 .

HTTP works fine.

I downloaded the mitm.it .pem file and added it in chrome as well....

the padlock beside the url is green too...I don't know why its not working, do I need to use the same certificate file on the mitmproxy side as well?

thank you.

**Comment by cortesi** [comment]
Ah, OK. So, to clarify - in that command, 23.23.23.23 is an upstream proxy (not mitmproxy) that requires authentication. You've installed the certs (padlock == green means this worked), you've set the proxy auth header, but you still get an authentication failure when visiting pages. Correct?

Do you see the failure for both HTTP and HTTPS pages?

**Comment by whatsdis** [comment]
I no longer get the auth failure but just a blank page with a green padlock, and checking mitmproxy it says 403....

I've tried --cert-forward, --no-upstream-cert, I get 200 but no content.

I've running out of ideas here....

HTTP works fine. only https won't load.

**Comment by cortesi** [comment]
Hi. So, 403 is an Forbidden response code, which probably still has to do with your proxy auth process. Just repeating the question before - in your command, 23.23.23.23 is an upstream proxy (not mitmproxy) that requires authentication?

**Comment by whatsdis** [comment]
yes that is the upstream proxy requiring authentication. 

when I use --cert-forward it gives me 200 but with no content returned and I get SSL connection error.

when I use --no-upstream-cert, it gives me 403, green padlock

ProxyError: Cannot establish SSL connection with upstream proxy: ?
Proxy-Authenticate: Basic realm="Proxymesh"
Content-Length: 0?

**Comment by cortesi** [comment]
OK, thanks for your help tracking this down. I can see exactly what's going on now. When you specify extra headers on the command line, those are set on the HTTP request, but NOT the CONNECT request  to the proxy that establishes the SSL connection to upstream hosts ([see here](https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/protocol/http.py#L26)). 

The cleanest way to tackle this is to add a command-line flag to specify the upstream proxy authentication credentials, which are then set on both HTTP and CONNECT requests (but not HTTPS requests. That would also mean that we can avoid you having to specifically set the auth header in the way you do.

I won't have time to work on this immediately - if you wanted to take a crack at it, please do! If not, watch this ticket for updates.

**Comment by whatsdis** [comment]
can I see an example of how its modifies the http request and can I apply it to the connect request?

when would you be able to fix this?

**Comment by cortesi** [comment]
If you want to hand-hack this, the authentication header needs to be injected in the header dictionary here: 

https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/protocol/http.py#L35

Unfortunately I can't give a timeline for a fix to this, other than to say that the issue is clear, and someone will definitely get to it at some point.

**Comment by whatsdis** [comment]
yeah will try and hack it....how do I inject the header...can I just
specify a key like odict['proxy-authentication'] = 'Basic fjvsj3'?
odict.ODictCaseless()


ᐧ

**Comment by cortesi** [comment]
Yep, except that the value here is a list. See the following example script that illustrates:

https://github.com/mitmproxy/mitmproxy/blob/master/examples/add_header.py

**Comment by whatsdis** [comment]
gotcha....so just edit https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/protocol/http.py#L35 with something like

    odict.ODictCaseless().headers["Proxy-Authentication"] = ["Basic fjsijoijbisjebase64here"]

**Comment by whatsdis** [comment]
odictcaseless object has no attribute 'headers'

**Comment by whatsdis** [comment]
I think it's working now!!!! wow that fix seemed to have worked.

 but sometimes I see:

Event log
191.54:55519: clientdisconnect
191.54:55518: clientdisconnect
91.54:55522: clientdisconnect
.63.217:50235: clientconnect
.63.217:50235: clientdisconnect
191.54:55480: clientdisconnect
191.54:55524: clientdisconnect
.191.54:55470: Error in handle_sni:?
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 339, in handle_sni
    self.server_reconnect(sni)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 272, in server_reconnect
    protocol_handler(s[0])(self).handle_server_reconnect(s[1])
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 1192, in handle_server_reconnect
    update_state=False
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 41, in send_connect_request
    resp = HTTPResponse.from_stream(conn.rfile, upstream_request.method)                                                                                                                                                                       File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 767, in from_stream
    include_body=include_body)
  File "/usr/local/lib/python2.7/dist-packages/netlib/http.py", line 558, in read_response
    raise HttpErrorConnClosed(502, "Server disconnect.")
HttpErrorConnClosed: Server disconnect.

191.54:55470: SSL handshake error: The client may not trust the proxy's certificate.
191.54:55470: clientdisconnect
63.217:15074: clientconnect
63.217:17203: clientconnect
63.217:17203: clientdisconnect
63.217:15074: clientdisconnect

and at first saw on my browser screen:

SSL Handshake Error:

SSL Connection Error

ERR_SSL_PROTOCOL_ERROR

but now seems to load https sites without any issue at all!!!!
