### ISSUE TITLE
mitmweb fails to connect to ws://127.0.0.1/updates

### ISSUE THREAD

**Issue by Antoniossss** [mitmproxy/mitmproxy#6452]
#### Problem Description
WebUI fails to connect to ws://127.0.0.1:8081/updates
 
on the console I am keep getting
[10:59:18.946] 403 GET //updates (127.0.0.1) 0.64ms

mitm works fine 

#### Steps to reproduce the behavior:
1. Do a fresh install via PIP
2. execute mitmweb
3. observe the failure

#### System Information
Mitmproxy: 10.1.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-6.2.0-34-generic-x86_64-with-glibc2.35

**Comment by mhils** [comment]
Thanks! Downgrading to 10.1.1 should resolve this, we'll ship a hotfix later today.

**Comment by Antoniossss** [comment]
Confirmed, ws works in 10.1.1

**Comment by karl-police** [comment]
> Thanks! Downgrading to 10.1.1 should resolve this, we'll ship a hotfix later today.
> 
> https://mitmproxy.org/downloads/#10.1.1/

oh

**Comment by karl-police** [comment]
I got that issue and I just installed it now LUL

**Comment by karl-police** [comment]
> Reference in

Wait no, I still have the issue, even after I downgraded.

**Comment by karl-police** [comment]
![image](https://github.com/mitmproxy/mitmproxy/assets/12023782/b89a28af-723a-42bd-a55f-cfa7cfed5933)

@mhils 🤷

**Comment by mhils** [comment]
@karl-police: you likey need to clear your browser cache or hard-reload mitmweb (Ctrl+Shift+R).

**Comment by karl-police** [comment]
> @karl-police: you likey need to clear your browser cache or hard-reload mitmweb (Ctrl+Shift+R).

oh that worked

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/pull/6454 has a fix, release should be out in an hour or so. Thanks for bearing with us. :)

**Comment by karl-police** [comment]
What do I have to do to read WebSocket stuff though? @mhils

**Comment by mhils** [comment]
@karl-police: mitmweb does support WebSockets, as well a raw TCP and UDP. Depends a bit on the proxy mode what you are getting.

**Comment by karl-police** [comment]
> @karl-police: mitmweb does support WebSockets, as well a raw TCP and UDP. Depends a bit on the proxy mode what you are getting.

Before I just got ``Client closed connection before completing request headers`` which shows something that would be in that WebSocket message. But I don't know where I can find those messages. I don't know where mitmweb is logging them.

**Comment by mhils** [comment]
@karl-police: We're getting off-topic here. I'd suggest you open a new discussion for that where you describe what you are doing. :)

**Comment by karl-police** [comment]
I also got ``Server TLS handshake failed. Certificate verify failed: unable to get local issuer certificate`` even though I installed the certificate on the latest version. Not sure, I don't believe the certificates change, right?

**Comment by karl-police** [comment]
@mhils is this an issue https://github.com/mitmproxy/mitmproxy/discussions/6455

regarding certificates for websockets?
