### ISSUE TITLE
Windows Certificate doesn't work on things that aren't a Browser

### ISSUE THREAD

**Issue by karl-police** [mitmproxy/mitmproxy#6456]
#### Problem Description
Interceptions on things that is not from a browser, does not work. (note that you'd have to restart ``mitmweb`` after installing the certificate), _any on-going session may be still tied to the previous certificate or something, and don't go through the proxy if that can even make sense, but that explanation would make sense to me_, toggling the internet should ensure that everything now is _trying_ to go through the proxy.

When I uninstall the certificate completly, things do not work at all, even on the browser while on the proxy. This is resolved by installing the certificate. However, it only solves the stuff that are from the browser.

When I tried Fiddler Classic or trial Fiddler Everywhere, I wouldn't get this issue, though I didn't find WebSocket stuff anywhere, but application stuff would work. However, this isn't working for mitmproxy.
Which is confusing and I see it as a issue without explanation.

I think there's an issue with the certificate or the instructions to install the certificate. Maybe there's something that can be done to fix this.

Saying that _"You just have to make it trust"_ is not a valid answer, because the steps required to make something trust something, is not provided.

#### Steps to reproduce the behavior:
1. I installed mitmproxy version 10.1.1
2. I installed the Windows certificate, and ensured it's under the Trust Certificate Root thing. _(Other languages have it named differently, so you'd check on https://learn.microsoft.com/en-us/windows-hardware/drivers/install/trusted-root-certification-authorities-certificate-store to see how it's named)_
3. Tried testing various Applications that aren't browsers, such as [Chatterino](https://github.com/Chatterino/chatterino2) vs twitch.tv
4. I set the proxy to ``127.0.0.1:8080``
5. I ran ``mitmweb``
6. I can see the WebSocket that is from the browser and read the messages. But not from Chatterino, even though it's connecting to the same thing as twitch.tv, with the only exception that it isn't from a browser.

This is not a Chatterino specific issue. I provided it as an example Application.

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 10.1.1 binary
Python:    3.11.5
OpenSSL:   OpenSSL 3.1.3 19 Sep 2023
Platform:  Windows-10-10.0.19045-SP0
```

**Comment by mhils** [comment]
Applications may decide not to use the system CA store - in that case only installing the CA into the system store is not enough. You basically need to teach those applications to accept the mitmproxy certificate anyways. How that works is really application-specific, see https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually for some community-contributed examples.

I'd like mitmproxy to eventually try a few tricks here, but we're not there yet.

**Comment by karl-police** [comment]
> Applications may decide not to use the system CA store - in that case only installing the CA into the system store is not enough. You basically need to teach those applications to accept the mitmproxy certificate anyways. How that works is really application-specific, see https://docs.mitmproxy.org/stable/concepts-certificates/#installing-the-mitmproxy-ca-certificate-manually for some community-contributed examples.
> 
> I'd like mitmproxy to eventually try a few tricks here, but we're not there yet.

Can try, I was looking at that already, though I'd have to use ``.p12`` and I don't think I can provide a website, if it's an application? Idk it's a bit weird. twitch.tv and Chatterino use the same WebSocket URL, just from a different application source.

Fiddler's Certificate is called Root Certificate Authority and is a ``.crt`` file.


How can I run ``mitmweb`` and provide a certificate file? I could try and provide Fiddler's one.

**Comment by mhils** [comment]
As explained on the documentation page linked above, you can find the certs on disk in `~/.mitmproxy` (~ is your users home directory). :)

**Comment by karl-police** [comment]
> As explained on the documentation page linked above, you can find the certs on disk in `~/.mitmproxy` (~ is your users home directory). We also have a bunch of options to use custom CAs/certs. :)

Look:

``curl --proxy 127.0.0.1:8080 --cacert .mitmproxy/mitmproxy-ca-cert.p12 https://example.com/``


```
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by mhils** [comment]
```
curl --cacert ~/.mitmproxy/mitmproxy-ca-cert.pem -x localhost:8080 https://example.com 
```
works as expect on my machine. This likely is a problem with your cURL version, not with mitmproxy.

**Comment by karl-police** [comment]
> > ```
> > curl --cacert ~/.mitmproxy/mitmproxy-ca-cert.pem -x localhost:8080 https://example.com 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > works as expected on my machine. This likely is a problem with your cURL version, not with mitmproxy.
> 
> which curl is yours?
> 
> mine is `curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN`

Tried again. Works with ``.pem`` on ``8.4.0``. I am not exactly sure though what the purpose of this should be, does it initialize something? @mhils

**Comment by karl-police** [comment]
Otherwise running with default certificate, I get ``SSL certificate problem: unable to get local issuer certificate``

**Comment by karl-police** [comment]
@mhils Fiddler Everywhere's proxy gets set to ``http=127.0.0.1:8866;https=127.0.0.1:8866``
with ``<-loopback>`` in the box

however, if "Capture HTTPS traffic" is toggled on, Chatterino also fails.

Is it possible that mitmproxy always captures HTTPS traffic or something? Maybe setting it to http could solve it

Maybe the certificate is not valid for HTTPS

**Comment by karl-police** [comment]
```
Addon error: [('x509 certificate routines', '', 'key values mismatch')]
Traceback (most recent call last):
  File "mitmproxy\addons\tlsconfig.py", line 207, in tls_start_client
  File "OpenSSL\SSL.py", line 1929, in use_privatekey
  File "OpenSSL\SSL.py", line 1102, in _raise_passphrase_exception
  File "OpenSSL\_util.py", line 57, in exception_from_error_queue
OpenSSL.SSL.Error: [('x509 certificate routines', '', 'key values mismatch')]
```

**Comment by lingszz** [comment]
> 正如上面链接的文档页面上所解释的那样，您可以在磁盘上的`~/.mitmproxy`（~是您的用户主目录）中找到证书。我们也有很多选择来使用自定义CA/证书。：）

I had the same problem with curl on Windows, curl didn't trust the certificate I installed

**Comment by yuliu** [comment]
> > 正如上面链接的文档页面上所解释的那样，您可以在磁盘上的`~/.mitmproxy`（~是您的用户主目录）中找到证书。我们也有很多选择来使用自定义CA/证书。：）
> 
> I had the same problem with curl on Windows, curl didn't trust the certificate I installed

You might be using the the builtin version of curl from Windows which is 8.4.0 iirc, and it's true that it doesn't trust mitmproxy's generated CA. Try a newer version of curl, e.g., the latest curl for Windows 8.7.1.
