### ISSUE TITLE
Probabilistic TLS pass-through

### ISSUE THREAD

**Issue by Fuzion24** [mitmproxy/mitmproxy#646]
https://github.com/google/nogotofail/blob/dev/docs/design.md#why-attack-probabilistically

It would be neat to have a few different modes for this:

1) Randomly pass through TLS connections
2) After TLS failure, add it to a pass-through / white list
3) A set time period where everything is passed through, then everything is intercepted

**Comment by mhils** [comment]
Very cool idea. It'd be great if we could specify strategies for `--ignore` in inline scripts. As always, pull requests are very welcome and we're happy to help!
