### ISSUE TITLE
Can no longer highlight text to copy/paste

### ISSUE THREAD

**Issue by giantpune** [mitmproxy/mitmproxy#647]
I've just updated to mitmproxy 0.12.1 on Linux using KDE desktop environment (kubuntu 14.04).  On previous versions of mitmproxy, I was able to use my mouse to select text and then copy/paste it into other programs.  Now that mitmproxy responds to mouse clicks, I am not able to select text.   

Most programs wait for a mouse press+release in the same spot before considering it a click.  Mitmproxy just sees the press and doesnt wait for the release, so I cannot click my mouse and drag it to select text.  

I see that there is a message "hold down alt or ctrl to select text" but this does not work in my terminal.  Holding alt while clicking and dragging makes the whole terminal window drag around the desktop.  Holding ctrl has no affect, and holding both of them does not help.

Is there an option to disable the mouse in mitmproxy and have it work like it did in previous versions?

**Comment by mhils** [comment]
Thanks for the report. Which terminal app are you using? The default one on kubuntu?

**Comment by giantpune** [comment]
Yes, the default terminal in kubuntu.  Its named 'konsole' in the menu and lives at /usr/bin/konsole.

**Comment by cortesi** [comment]
Hi there. Just a quick question - can you select text if you hold down "shift"?

I'm sympathetic to the idea that this breaks user expectations and that we should have an option to turn mouse control off.

**Comment by giantpune** [comment]
Yes, holding shift, I can select text again :)

**Comment by cortesi** [comment]
@giantpune Great. :) So, if we amend the hint message to include shift (sadly it seems to be different on every platform), would that satisfy you, or do you still feel a "mouse-less" command line option is needed?

**Comment by giantpune** [comment]
I'm happy just being able to hold shift and select text.  I bet somewhere out there, there's another desktop environment where none of shift/alt/ctrl allows them to select text.  It doesn't seem like a bad idea to let these users type a certain letter to disable the mouse, or pass in a --no-mouse sort of parameter.  Otherwise you might find yourself with a message like "try pressing alt, shift, ctrl, windows key, alt+gr, numlock, or printscr button to select text."

**Comment by Crazometer** [comment]
Wasn't working for me with putty on windows either. Shift did the trick though!

**Comment by lxyu** [comment]
+1 for holding shift (archlinux + urxvt)

**Comment by babakgh** [comment]
same problem here, even when I set `EDITOR=vim` and open body in vim, still can't select text

I am using Term2 on mac

**Comment by bluecrowbar** [comment]
On the Mac, in Terminal.app, the best option seems to hold fn-command.

**Comment by foadsaliba** [comment]
+1 for holding fn on mac

**Comment by ganguera** [comment]
@mhils The "--no-mouse" options is already implemented, unless you want to improve the message provided depending on the OS that is running MITMProxy, I think we can close it. What do you think?

**Comment by jschwalbe** [comment]
Came here searching for an answer why I couldn't highlite text. Found out that on my MacBook the "fn" key is the only thing that works. Using Terminal.app. Frustrating when the help text was wrong :(

**Comment by mhils** [comment]
As a temporary workaround, I'd immediately merge a PR that fixes the help text :smiley:

**Comment by loretoparisi** [comment]
I'm on El Capitan, and even if I hold down shift | alt | ctrl and move the mouse the select I cannot select anything since I don't see the selection area.

**Comment by rknell** [comment]
Hey hey all - if you are on OSX use Fn instead of shift, alt or ctrl

**Comment by dufferzafar** [comment]
I think this is about which terminal application you're using and then which keys you've set to send escape codes etc.

I'm currently on El Capitan, running iTerm2 but have set the `Alt` key to send escape codes - so I'm able to select text using `Alt` and `Fn` does NOT work for me.

On the default Terminal.app however, I'm able to select text using `Fn` and `Alt` doesn't work.

**Comment by jschwalbe** [comment]
Frankly I find this more annoying than useful. Is there a flag to disable the "GUI" part of this? Terminal apps != GUI in my opinion and should not care where I click.

**Comment by dufferzafar** [comment]
@jschwalbe There sure is. Just run: `mitmproxy --no-mouse` 😄

**Comment by jschwalbe** [comment]
I'll add that as an alias to my bash_profile! Thanks

**Comment by dufferzafar** [comment]
@jschwalbe Or you could add it to mitmproxy's config file :wink:

**Comment by donileo** [comment]
mitmproxy 0.17.1 macOS Sierra Terminal none of Fn, Alt, Shit, Ctrl work. Is there a trick to getting text selection work to work?
