### ISSUE TITLE
Warn if both `stream_large_bodies` and `modify_body` are set

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#6479]
See below for a user report - we should print a warning if stream_large_bodies and modify_body are set. Contributions welcome! 😃 

--------------------

I found this and a few other links looking for information on this topic.  Several attempts were not producing the expected results.  I was using stream_large_bodies=1 and after rereading the docs more https://docs.mitmproxy.org/stable/concepts-options/#stream_large_bodies found that when using stream_large_bodies=1 the body is not stored and hence cannot be modified.

_Originally posted by @rosydawn6 in https://github.com/mitmproxy/mitmproxy/discussions/5151#discussioncomment-7537706_

**Comment by rosydawn6** [comment]
I can do this.  My initial thought was to add some warning/notice to the options in the documentation.  You seemed to imply printing a warning message upon startup if stream_large_bodies flag is set?  Which would you like me to do - or both?

**Comment by mhils** [comment]
I think it makes most sense to 1) mention it in the docstring for `stream_large_bodies`, and 2) log with ALERT level in the affected addons. Thanks! :)

**Comment by rosydawn6** [comment]
Few comments on the attached PR:
I log with alert in both stream_large_modies addon and in modify_body addon.  If both options are set it will basically duplicate the log message.  Did you envision something else @mhils?

**Comment by mhils** [comment]
Thanks, see PR. :)
