### ISSUE TITLE
Cache requests/response.

### ISSUE THREAD

**Issue by gajus** [mitmproxy/mitmproxy#648]
I use `mitmproxy` a lot for developing scripts that scrap external content. I often find that it takes a long time to test script because it needs to repeat all the HTTP requests. It would be nice if it was able to select HTTP requests that `mitmproxy` would cache and use cached version to reply to the user.

The most common use case scenario is GET requests because those are supposed to be immutable.

I have built a node [web-proxy](https://github.com/gajus/web-proxy) script to do this for me, using it as a forward proxy together with `mitmproxy`, though it would be nice if `mitmproxy` supported this natively.

**Comment by mhils** [comment]
Hi @gajus,

are you aware of the server replay feature? How would that be different from it?

**Comment by gajus** [comment]
I was not. It is an awesome feature. I have looked at `?:help` page hundreds of times. Maybe it would be worth adding a description next to the name of the option?, e.g.

```
S server replay – Enables server-side replay of saved HTTP conversation.
```

**Comment by gajus** [comment]
Is there a way to enable reply for all requests as they appear? i.e. all identical requests within a session would be served from a replay.

**Comment by colin-dev** [comment]
@gajus, it sounds like I'm looking at mitmproxy to solve the exact same problem as you. Did you ever find a good way to get the server-side proxy to serve the same response repeatedly?

**Comment by gajus** [comment]
Ended up building our in-house software at the end. Might open-source it as some point, but it isn't ready yet for public use.

**Comment by gajus** [comment]
I am sure you are able to do it using mitmproxy with a bit of Python skills, though.

**Comment by colin-dev** [comment]
@gajus, I recorded a session into a file and was able to repeatedly return the results using the `--no-pop` parameter
`mitmproxy -S /sites/dsi.site --no-pop`
The responses live in a queue, which is why the responses are only replayed once, the `--no-pop` command tells mitmproxy to leave the responses in a queue so they can be returned ad-infinitum
