### ISSUE TITLE
crash on 32 bit systems

### ISSUE THREAD

**Issue by Nerudifus** [mitmproxy/mitmproxy#649]
This problem was viewed in version 0.11.1, I think. I am currently not able to test it with the current version but the corresponding source code did not change in 0.12.1 thus I think it is still a problem.

I am using mitmdump as transparent proxy. After changing the system mitmdump was running on, it crashes after some time with
```
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/protocol/http.py", line 813, in _refresh_cookie
    i["expires"] = formatdate(d)
  File "/usr/lib/python2.7/email/utils.py", line 161, in formatdate
    now = time.gmtime(timeval)
ValueError: timestamp out of range for platform time_t
```
After some time I realised that the problem occurs after the change from 64 bit to 32 bit and disappeared after another change to 64 bit again.
Looking at libmproxy/protocol/http.py:810 or in 0.12.1 at libmproxy/protocol/http.py:842
```
            d = parsedate_tz(i["expires"])
                if d:
                    d = mktime_tz(d) + delta
                    i["expires"] = formatdate(d)
```
The documentation for email.utils.formatdate mentioned for the first parameter ```Optional timeval if given is a floating point time value as accepted by time.gmtime() and time.localtime(), otherwise the current time is used.``` 
Internally time.gmtime is used. The documentation for time mentioned ```The functions in this module do not handle dates and times before the epoch or far in the future. The cut-off point in the future is determined by the C library; for Unix, it is typically in 2038.```
Under 32 bit Ubuntu python crashes with ```time.gmtime(sys.maxint+1)``` but with ```time.gmtime(sys.maxint)``` you will get 2038-01-19 and some hours. 
Thus under 32 bit this code will only work with expiration dates previous to 2038-01-19. But unfortunately there are site setting cookies with expiration dates far in the future. Different advertiser set it 30 years in future thus in 2045. But I also see dates after year 2080.

**Comment by mhils** [comment]
I'm rarely convinced by bug reports from old versions, but this sounds like a very good find. I'd be super happy if someone could step up and provide a fix + test case!

**Comment by bcopos** [comment]
This problem is known as the [Year 2038 Problem](https://en.wikipedia.org/wiki/Year_2038_problem) (similar to the infamous Y2K problem). IMO this is not an bug with mitmproxy but rather Python and the  `time.gmtime()` function specifically. You could submit a bug report with them. One suggestion would be for Python to not use POSIX `time.h` but rather build and use an external version into their project, such as `time64.h` (from [here](https://github.com/schwern/y2038)).

**Comment by dufferzafar** [comment]
I am not sure if this is correctly marked as a "good first contribution". It's more of an upstream issue. :smile:

**Comment by Nerudifus** [comment]
The used library documented the internal used structures and the documentation of these structures mentioned that it can "typically" only handle dates up to 2038. This is good enough for many python programs. But it seems it is not for use of uncontrolled data of third party.

You can say it is a bug of python. You can say it's an upstream issue. But you could also say that an unsuitable library is used. It's your decision to call it unfixable, a third party issue, to revoke the use of mitmproxy under 32 bit or to fix it, e.g. by writing the necessary code or using another library. But I am not able to tell you a better one, sorry.

**Comment by Kriechi** [comment]
We are using the Python standard library in many places - if this already fails to handle timestamps (far) in the future, then we have a more general problem anyway.
I'm closing this for now, since there is very little we can do - and eventually going to 64bit will solve this by itself.

**Comment by fattestpanda726271343274438476327362718** [comment]
apparently there is no x86 version available, is it because of this issue?
