### ISSUE TITLE
Android apps like google apps, chess.com etc not working 

### ISSUE THREAD

**Issue by nandish486** [mitmproxy/mitmproxy#6490]
#### Steps to reproduce the behavior:
1. mitmdump -s adblock.py --ssl-insecure  --set stream_large_bodies=1000k --no-http2 -p 9443 -q 
2. proxy starts
3. connect proxy to android, certificates installed to it in correct way.

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 9.0.1
Python:    3.9.13
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Windows-10-10.0.18363-SP0

**_some apps like youtube, google lens, chess.com app is not loading in android ,
where chess.com gives error java.security.cert.CertPathValidatorException: Trust anchor for certification path not found._**

**_On  youtube it never loads screen, and google lens shows something went wrong error_**

**_facebook shows no internet connection._**

I also tried --ssl-insecure, --no-http2 etc...

**Certificate is installed to correct path.**

**Error :** 
       _Client TLS handshake failed. The client does not trust the proxy's certificate for (apps mentioned here). 
Note : certificate is installed to correct path_

**Comment by Prinzhorn** [comment]
Search the web for "certificate pinning", there is nothing mitmproxy can do about that. But there are tools https://docs.mitmproxy.org/stable/concepts-certificates/#certificate-pinning
