### ISSUE TITLE
datetime/time in output of mitmdump

### ISSUE THREAD

**Issue by Nerudifus** [mitmproxy/mitmproxy#650]
I am saving the output of mitmdump in a file as a log file. If an error occurs it could help finding it. But after some hours it is a problem to know which line is of interest. Thus I asked for a way to optionally add a time or date and time at the beginning of every output line.

Up to now I modify ```add_event``` of dump.py but this only modifies some of the line, which is still better than nothing.

**Comment by mhils** [comment]
I think the best way to solve this is https://unix.stackexchange.com/questions/26728/prepending-a-timestamp-to-each-line-of-output-from-a-command. Closing for now.
