### ISSUE TITLE
Add an option to store CA certificates somewhere other than `confidr`

### ISSUE THREAD

**Issue by Speedlulu** [mitmproxy/mitmproxy#6528]
#### Problem Description

I need a way to tell mitmdump to generate it's certificates somewhere other than in `confdir`

#### Proposal
A new option to tell mitm* commands where to create their CA.
The behaviour is unchanged if the option is not passed.

#### Alternatives
I tried using `--cert *=` but it does not do what I need.

#### Additional context
I already created a [PR for this feature](https://github.com/mitmproxy/mitmproxy/pull/6527)

**Comment by mhils** [comment]
What's your use case for this? I'm not totally opposed, but flexibility in these sorts of things quickly leads to breakage in edge cases. I'd rather have people specify a custom confdir maybe?

**Comment by mhils** [comment]
> I thought it would be a nice option to have, but if it's too much hassle for you I'll keep maintaining our fork.

I think I'd prefer that for now. This touches a few hard-to-test cases (e.g. the mitm.it web app) that can break in subtle ways, so I'd like to prioritize stability here. Thanks! 🍰
