### ISSUE TITLE
@concurrent decorator broken

### ISSUE THREAD

**Issue by Calpicow** [mitmproxy/mitmproxy#653]
Using the below command and code to intercept requests. I would expect all requests to return "Test", but it will occasionally bypass to the reverse proxy target. Using 0.12.1.

`mitmdump -R http://localhost -p 8080 -s leak.py`

```
from libmproxy.protocol.http import HTTPResponse
from libmproxy.script import concurrent
from netlib.odict import ODictCaseless


@concurrent
def request(context, flow):
    resp = HTTPResponse([1, 1], 200, "OK", ODictCaseless([["Content-Type", "text/html"]]), "Test")
    flow.reply(resp)
```

**Comment by mhils** [comment]
Thanks for the report. I can reproduce this on my machine and will take a closer look later today.

**Comment by m4rienf** [comment]
+1 same experience. FYI: There's probably some shared resource that gets overwritten, in a short time window just after request begins executing. If I add e.g. time.sleep(.05) as the first line of my @concurrent-decorated request method, or even a context.log() or print() behaviour becomes as expected. This does not appear to depend upon the time taken by anything afterwards.

**Comment by mhils** [comment]
Thanks for the hint. As a general rule of thumb, you should only use the concurrent-decorator if you have blocking behaviour in your script (e.g. a HTTP request). If you don't have blocking code in there, it's actually a performance penalty (we need to spawn a new thread). We'll try to fix the bug anyway of course :smiley:

**Comment by m4rienf** [comment]
> As a general rule of thumb, you should only use the concurrent-decorator if you have blocking behaviour in your script (e.g. a HTTP request)
Thanks for that ; Yesterday was my first go at mitmproxy, and I didn't realize that. And although my request and response methods will eventually involve slow system calls into the filesystem, they do not, in this expermiental stage. It's just dict lookups now. The fact that this is actually a degenerate case is quite likely why you haven't noticed it. Most excellent work, BTW. Wish I'd searched better and found this project sooner.

**Comment by mhils** [comment]
Fixed. Thanks again for the report.
