### ISSUE TITLE
[mitmweb] Add SVG response preview support.

### ISSUE THREAD

**Issue by Jean-Daniel** [mitmproxy/mitmproxy#6544]
#### Problem Description

Some sites are using image in the `image/svg+xml` format. While mitmweb propose an `image` format in the response preview format, it fails to display the svg image (while the browser support SVG and can show it natively) with the message `Image Format: unknown`.

#### Proposal
mitmweb should recognize the mime-type `image/svg+xml` as an image format and show the image in the response content panel.

**Comment by Thanush19** [comment]
@Jean-Daniel 
![added-SVG-image-preview-format-support-by-Thanush19-·-Pull-Request-6545-·-mitmproxy-mitmproxy](https://github.com/mitmproxy/mitmproxy/assets/110150744/02aa532b-8607-47dc-8879-18a289bd55c2)
i'm stuck , i need help

**Comment by Thanush19** [comment]
@Jean-Daniel  kindly look over the PR #6551  that i 've submitted
