### ISSUE TITLE
ignore_hosts and allow_hosts not working as documented

### ISSUE THREAD

**Issue by micheljung** [mitmproxy/mitmproxy#6554]
#### Problem Description

The [documentation of `ignore_hosts`](https://docs.mitmproxy.org/stable/concepts-options/#ignore_hosts) states:

> Ignore host and forward all traffic without processing it. In transparent mode, it is recommended to use an IP address (range), not the hostname. In regular mode, only SSL traffic is ignored and the hostname should be used.

But instead of "forward all traffic without processing it", it closes the connection. Similarly, `allow_hosts` only allows traffic for the specified host but closes the connection for all others.

#### Steps to reproduce the behavior:

```
mitmproxy --set ignore_hosts=mitmproxy.org
```

```
$ curl -x localhost:8080 -k https://mitmproxy.org
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Proxy CONNECT aborted
```

#### System Information

```
Mitmproxy: 10.1.6 binary
Python:    3.12.0
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Windows-11-10.0.22621-SP0
```

**Comment by Prinzhorn** [comment]
Thanks, this is indeed a bug and not an issue with the docs. If you're interesting in helping and bisecting this further, this broke somewhere between 10.0.0 and 10.1.6 (I can't narrow it down any further right now). Event logs say:

> Cannot open connection, no hostname given.

https://github.com/mitmproxy/mitmproxy/blob/c0f81a8542c210765484e379fe7058b66ee24c16/mitmproxy/proxy/server.py#L179-L187

Here's how you can contribute if you're interested: https://github.com/mitmproxy/mitmproxy/blob/main/CONTRIBUTING.md

**Comment by mhils** [comment]
Thanks! Bisected to 558b0b664277769310ce99c7d8136eca1ba74658.
