### ISSUE TITLE
mitmproxy crashed in socks5 mode

### ISSUE THREAD

**Issue by Sfinx** [mitmproxy/mitmproxy#656]
Hello,

Trying to dump the HTTP headers with "mitmproxy -p 1080 -b 127.0.0.1 --socks" on ubuntu 15.04. Got :

```
.......
mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
127.0.0.1:36043: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/server.py", line 88, in handle
    self.client_conn)
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/proxy/primitives.py", line 115, in get_upstream_server
    connect_request = socks.Message.from_file(client_conn.rfile)
  File "/usr/local/lib/python2.7/dist-packages/netlib/socks.py", line 102, in from_file
    ver, msg, rsv, atyp = struct.unpack("!BBBB", f.safe_read(4))
  File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 229, in safe_read
    raise NetLibDisconnect()
NetLibDisconnect
.........
```

The other side is tun2socks (badvpn package) it is printing :

```
NOTICE(BSocksClient): reply has unknown address type
```

**Comment by mhils** [comment]
Thanks for the report. Could I get a pcap of the handshake?

**Comment by Sfinx** [comment]
Sure : 

http://sfinxsoft.com/downloads/bad.pcap

So I've captured the normal session where the socks5 proxy was made using ordinary ssh client (-D option)

http://sfinxsoft.com/downloads/good.pcap

The badvpn was launched with the following args : 

```
badvpn-tun2socks --tundev tun0 --netif-ipaddr 10.0.0.2 --netif-netmask 255.255.255.0 --socks-server-addr 127.0.0.1:1080
```

The mitmdump was launched as `mitmdump -p 1080 --socks`

Thanks !

**Comment by mhils** [comment]
Thanks for the pcap - I just commited a patch that should fix the issue.

**Comment by Sfinx** [comment]
Thanks ! Now it is working ;)
