### ISSUE TITLE
encoding error : input conversion failed due to input error

### ISSUE THREAD

**Issue by byt3bl33d3r** [mitmproxy/mitmproxy#657]
Hi,
I'm constantly getting the following error when using the the ```decoded``` context manager (from ```libmproxy.protocol.http```) in combination with BeautifulSoup and libmproxy:
```
encoding error : input conversion failed due to input error, bytes 0x8F 0x0B 0xFC 0x61
```
I tried to figure out the source of this error but was unable to track it down, it sometimes impedes certain sites from displaying correctly (which would make sense since it's an encoding issue).
Was just wondering if I'm doing something wrong, you can find an example of the code I'm using here https://github.com/byt3bl33d3r/MITMf/blob/mitmproxy/plugins/inject.py

**Comment by cortesi** [comment]
HI there. This seems to be an error that originates in libxml2, which is used by lxml, which is used by BeautifulSoup. So, I don't think this is a mitmproxy issue. 

That said, we _do_ use lxml for our content views in mitmproxy console. Not relevant to this script, but I'd still be interested if you could boil this down to a test case, just in case there's something we need to look at.

**Comment by Najmee** [comment]
Hi,
 Libxml2 does not support the GB2312 encoding so a way to get around this problem is to convert it to utf-8. I did it and it works for me:

with decoded(flow.response):  
        html = BeautifulSoup(flow.response.content)
        html = BeautifulSoup(flow.response.content.decode('utf-8', 'ignore'))
        if html.body:
            script_html = '<script> alert(/hey/)</script>'
            snippet = BeautifulSoup(script_html).script.extract()
            html.body.insert(0, snippet)

**Comment by byt3bl33d3r** [comment]
@Najmee thanks man! this resolves the issue completely :+1:

**Comment by aiweiyang521** [comment]
nice！ thanks
