### ISSUE TITLE
SSL handshake error with libmproxy

### ISSUE THREAD

**Issue by jeffgortmakerquovo** [mitmproxy/mitmproxy#660]
Hi,

I've been using libmproxy in conjunction with Python's requests module, and I've run into a problem with certain websites.

One of these websites is [https://www.401save.com](https://www.401save.com). Trying to access it through libmproxy results in: 
> `SSL handshake error: The client may not trust the proxy's certificate.`

Here's a short script that demonstrates my problem:
```
import threading
from libmproxy import controller, proxy
from libmproxy.proxy.server import ProxyServer
import requests

config = proxy.ProxyConfig(port=8888)
server = ProxyServer(config)
mitm = controller.Master(server)
t = threading.Thread(target=mitm.run)
t.daemon = True
t.start()

requests.get('https://www.401save.com', proxies={'https': 'http://localhost:8888'}, verify=False)

mitm.shutdown()
```
Printing the server's logs, this is what comes up:
```
127.0.0.1:58270: clientconnect
127.0.0.1:58270: request
  -> CONNECT www.401save.com:443 HTTP/1.0
127.0.0.1:58270: Set new server address: www.401save.com:443
127.0.0.1:58270: serverconnect
  -> www.401save.com:443
127.0.0.1:58270: Received CONNECT request to SSL port. Upgrading to SSL...
127.0.0.1:58270: Establish SSL
  -> with client
  -> with server (sni: None)
127.0.0.1:58270: SSL handshake error: The client may not trust the proxy's certificate.
127.0.0.1:58270: ProxyError('NetLibError("SSL handshake error: SysCallError(-1, \'Unexpected EOF\')",)',)
127.0.0.1:58270: clientdisconnect
127.0.0.1:58270: serverdisconnect
```
Could this be related to #427?

Best,
Jeff

**Comment by mhils** [comment]
Thanks for the report - https://www.401save.com/ does not work with mitmproxy at the moment. Firefox says `ssl_error_rx_record_too_long`.

**Comment by mhils** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=401save.com - their server does not offer any cipher suites which are compatible with OpenSSL 1.0.2. There's not much we can do here (despite providing a better error message), sorry. If you're on Linux/OSX, you can use cryptography with OpenSSL 1.0.1, that should work - fixing the server is probably easier though.

Cheers,
Max

**Comment by mhils** [comment]
We cannot really provide a better error message, OpenSSL fails with `Unexpected EOF`, which is too generic.
