### ISSUE TITLE
`Couldn't parse: falling back to Raw` for empty JSON array

### ISSUE THREAD

**Issue by verhovsky** [mitmproxy/mitmproxy#6603]
#### Problem Description
The following response packet:

```
HTTP/2.0 200 
date: Sun, 14 Jan 2024 23:30:12 GMT
content-type: application/json; charset=utf-8
content-length: 2
server: nginx/1.18.0 (Ubuntu)
cache-control: no-store
x-amzn-trace-id: [REDACTED]
x-frame-options: DENY
set-cookie: [REDACTED]
strict-transport-security: max-age=31536000

[]
```

is displayed as "Couldn't parse: falling back to Raw", but it's clearly JSON from the content type and an empty array is a normal JSON response that shouldn't trigger this warning. In fact, top level `null`, booleans, numbers and strings should be just fine as well, I don't know if they do or don't.

#### Steps to reproduce the behavior:
Set up a JSON endpoint that returns `[]` with a `content-type: application/json; charset=utf-8` header and open it in mitmproxy

#### System Information
```
Mitmproxy: 10.2.1 binary
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  macOS-14.2.1-x86_64-arm-64bit
```

**Comment by Prinzhorn** [comment]
Thanks! Looks like an edge case for the empty array, the following all work: `[1]`, `"foo"` and `null`

**Comment by haanhvu** [comment]
@Prinzhorn I would like to fix this. Could you show me the part(s) of the codebase where this is handled?

**Comment by Prinzhorn** [comment]
@haanhvu sure, it's probably somewhere in https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/contentviews/json.py . I don't think the parsing of the JSON is failing but the algorithm that colorizes it (`format_json`).

I'd start with adding a failing test to https://github.com/mitmproxy/mitmproxy/blob/main/test/mitmproxy/contentviews/test_json.py

**Comment by haanhvu** [comment]
> I'd start with adding a failing test to https://github.com/mitmproxy/mitmproxy/blob/main/test/mitmproxy/contentviews/test_json.py

@Prinzhorn I meant to add failing tests but somehow they all passed^^ Could you take a look at #6619 to see if I wrote the tests correctly?
