### ISSUE TITLE
AttributeError: 'ClientPlayback' object has no attribute 'options'

### ISSUE THREAD

**Issue by chrisvis** [mitmproxy/mitmproxy#6604]
#### Problem Description
Client playback does not seem to work anymore, since 10.2.0. 
On 10.1.6 it still works.

I am getting the following error:
>Traceback (most recent call last):
  File "mitmproxy/addons/clientplayback.py", line 177, in playback
AttributeError: 'ClientPlayback' object has no attribute 'options'

#### Steps to reproduce the behavior:
1. Save a recorded flow
2. Replay it using `mitmdump -C stored.flow` 
3. See error

#### System Information
Mitmproxy: 10.2.1 binary
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  macOS-14.2.1-x86_64-i386-64bit

**Comment by mhils** [comment]
Thanks for the report! This will be fixed with the next release.

**Comment by chrisvis** [comment]
Wow, that's a quick fix :) Thanks
