### ISSUE TITLE
Mitmdump: invalid mode specification

### ISSUE THREAD

**Issue by SultanSagi** [mitmproxy/mitmproxy#6606]
#### Problem Description
I'm gettting the error with Mitmpdump mode operation

#### Steps to reproduce the behavior:
1. When running the command: mitmdump --mode regular@8888
2. receive Invalid mode specification: regular:http://localhost:8888
or mitmdump --mode regular@8888 =>  Invalid mode specification: regular@8888

#### System Information
Mitmproxy: 8.1.1

**Comment by mhils** [comment]
Thanks. It looks like your mitmproxy is outdated. Could you please upgrade an try again?

**Comment by mhils** [comment]
https://docs.mitmproxy.org/stable/overview-installation/
