### ISSUE TITLE
mitmdump can't handle example.com?

### ISSUE THREAD

**Issue by 664566173** [mitmproxy/mitmproxy#6612]
#### Problem Description
Hi there, I found this interesting thing. And Could anyone explain for me?
What's so special about example.com? It seems to be aware of mitmproxy..

#### Steps to reproduce the behavior:
1. docker run --rm -it -p 8080:8080 mitmproxy/mitmproxy mitmdump
2. http_proxy=http://localhost:8080/ curl http://example.com/  [not work]
3. curl http://example.com/  [work]
4. http_proxy=http://localhost:8080/ curl http://google.com/ [work]

**Comment by mhils** [comment]
All commands (including the second one) work for me as expected.

**Comment by 664566173** [comment]
@mhils Thank you.

But that's weird...Could you guess what happened?

**Comment by 664566173** [comment]
![image](https://github.com/mitmproxy/mitmproxy/assets/127160480/6544c14f-a0b6-420e-92d4-3577e8205d62)

![image](https://github.com/mitmproxy/mitmproxy/assets/127160480/742b55d3-3053-456a-b8ef-62d680a473ae)

stucked..

**Comment by mhils** [comment]
Can you run with mitmproxy with `-vvv --set proxy_debug` and post the output as text (not as a screenshot)?

**Comment by 664566173** [comment]
@mhils here you are:

```bash
curl -x localhost:8080 http://example.com -v
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET http://example.com/ HTTP/1.1
> Host: example.com
> User-Agent: curl/8.4.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>

```

```bash
mitmdump -vvv --set proxy_dubug
[09:14:02.788] HTTP(S) proxy listening at *:8080.
[09:14:29.471][192.168.65.1:17172] client connect
[09:14:29.490][192.168.65.1:17172] server connect example.com:80 (93.184.216.34:80)
```

**Comment by 664566173** [comment]
@mhils I found the reason...
My computer is running the global proxy(clash).
Everything work fine when clash closed.

Thank you again!
