### ISSUE TITLE
Unable to `brew install mitmproxy` on MacOS

### ISSUE THREAD

**Issue by alicescfernandes** [mitmproxy/mitmproxy#6627]
#### Problem Description
It seems that `brew` cannot download the binary (https://downloads.mitmproxy.org/10.2.2/mitmproxy-10.2.2-macos-x86_64.tar.gz) for installation on MacOS. 
I also cannot access the https://docs.mitmproxy.org/stable 

https://formulae.brew.sh/api/cask/mitmproxy.json

#### Steps to reproduce the behavior:
1. Run `brew install mitmproxy`
<img width="1059" alt="image" src="https://github.com/mitmproxy/mitmproxy/assets/15971182/d19aaba5-86f7-43f6-b9aa-ae133591e156">

#### System Information
Paste the output of "mitmproxy --version" here.
Unable to do this

**Comment by emanuele-em** [comment]
This seems to be a problem not related to mitmproxy but maybe to your network or settings:
- try to `brew update` and then `brew upgrade`
- try to `curl [https://docs.mitmproxy.org/stable/](https://docs.mitmproxy.org/stable/)` and check if it works correctly (Brew downloads stuffs with curl)
- check the Curl _version_ and _path_ that Homebrew actually uses with `brew config`
- try if `brew install --cask mitmproxy` works

**Comment by alicescfernandes** [comment]
hey @emanuele-em! thanks for the reply!
So it turns out that it was my firewall that was blocking the domain 😓. It usually shows a screen saying that the domain has been blocked but for this domain it was only showing chrome's error with "ERR_CONNECTION_RESET"

I managed to install over python
