### ISSUE TITLE
Tutorial audio is not working

### ISSUE THREAD

**Issue by EdmundsEcho** [mitmproxy/mitmproxy#6629]
Great resource and documentation!

FYI on a macos using either Firefox or Vivaldi (chrome based browser), the video [in docs page](https://docs.mitmproxy.org/stable/mitmproxytutorial-userinterface/) does not play the audio.  I could not find a volume control either.

**Comment by mhils** [comment]
There is no audio for these tutorials. 🙃

We'd like to improve the presentation ideally, but audio is tricky to maintain and thus not really desirable for us right now.

**Comment by EdmundsEcho** [comment]
Ah... good to know (in a way).  Perhaps let the viewer know not to expect audio?
