### ISSUE TITLE
--ignore '! www\.google\.com' does not work

### ISSUE THREAD

**Issue by Gritch666** [mitmproxy/mitmproxy#663]
Setup:
mitmproxy version: 0.12.1
Ubuntu 14.04.02 LTS 

Problem description:
With command:
# mitmproxy -I 'www.google.com'
(should ignores www.google.com, right ?)

For www.google.com/ncr URL mitmproxy ignores https as expected
![ignore_google_with_google_url](https://cloud.githubusercontent.com/assets/13146723/8471936/3b392d8c-209d-11e5-9819-458d37de45e4.png)

For www.yahoo.com URL mitmproxy intercept https as expected
![ignore_google_with_yahoo_url](https://cloud.githubusercontent.com/assets/13146723/8471938/3b3c328e-209d-11e5-8500-5e39ba609dc9.png)

With command:
# mitmproxy -I '!www.google.com'
(should ignores everything but www.google.com, If this regex is correct ?)

For www.google.com/ncr URL mitmproxy intercept https as expected
![ignore_everything_but_google_with_google_url](https://cloud.githubusercontent.com/assets/13146723/8471937/3b39fc94-209d-11e5-8219-646529d6ea22.png)

For www.yahoo.com URL mitmproxy intercept https, NOT as expected
![ignore_everything_but_google_with_yahoo_url](https://cloud.githubusercontent.com/assets/13146723/8471935/3b384692-209d-11e5-8d3c-4459dee858c2.png)

Wrong regex or bug ?

**Comment by mhils** [comment]
The regex is wrong - check out https://mitmproxy.org/doc/features/passthrough.html, there's an example for ignoring everything but a selected set of domains.

Cheers,
Max
