### ISSUE TITLE
CONNECT request triggers `response` hook

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#6632]
https://github.com/mitmproxy/mitmproxy/pull/6599#issuecomment-1912689476 has a repro. This line here makes us trigger the `response` hook for failed flows, which we don't want to do:

https://github.com/mitmproxy/mitmproxy/blob/c49c38e4c80fd4ad491986a2a7f8a18e75e16b2f/mitmproxy/proxy/layers/http/__init__.py#L760

The correct fix here is probably not to call `send_response` here but mirror what we do for the happy path. And then this needs a test.

**Comment by haanhvu** [comment]
Where should the test be added?

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/blob/main/test/mitmproxy/proxy/layers/http/test_http.py
would be a good fit.
