### ISSUE TITLE
mitmdump --ignore '^(?!google\.com)(?!yahoo\.com)' behaviour is wrong

### ISSUE THREAD

**Issue by Gritch666** [mitmproxy/mitmproxy#664]
Hello,

Following the example in the documentation:
Ignore everything but example.com and mitmproxy.org:
--ignore '^(?!example\.com)(?!mitmproxy\.org)'

to ignore https interception for all sites but google.com and yahoo.com.

Then I use the command:
mitmdump --ignore '^(?!google\.com)(?!yahoo\.com)' 

(For testing I use URL google.com/ncr to stick to .com,  if it matters)

Both sites should NOT be ignored (use of ?! in the regular expression), but mitmdump log shows:

![mitmdump_log](https://cloud.githubusercontent.com/assets/13146723/8477149/416dc4d0-20c8-11e5-9cca-8c587626e7dd.png)

Seems that this regular expression leads to ignore everything !?

Many thanks

**Comment by mhils** [comment]
The pattern is behaving as expected, your issue is that `www.google.com` is not `google.com`. 

You can insert a wildcard in the negative lookahead: `^(?!.*example.com)(?!.*mitmproxy.org)`. 
The strict version (without false-positives) would be `^(?!(.+\.)?example\.com:)`.

Cheers,
Max

**Comment by Gritch666** [comment]
Hello,
You are right, I did not realize that the site returned an other value.
Sorry for the basic question
and many thanks for the kind answer. Of course you can close the ticket.

Cheers
Sam



2015-07-03 0:19 GMT+02:00 Maximilian Hils <notifications@github.com>:
