### ISSUE TITLE
Transparent proxy not working on macOS

### ISSUE THREAD

**Issue by hallboav** [mitmproxy/mitmproxy#6642]
Due to a missing extra config?

#### Steps to reproduce the behavior:
1. `brew install mitmproxy`
2. `sudo sysctl -w net.inet.ip.forwarding=1`
3. `echo "rdr pass on en0 inet proto tcp to any port {80, 443} -> 127.0.0.1 port 8080" > ~/Desktop/pf.conf`
4. `sudo pfctl -f ~/Desktop/pf.conf`
5. `sudo pfctl -e`
6. `mitmproxy --mode transparent --showhost`
7. On my iPhone: manual IP addr `192.168.1.250`, netmask `255.255.255.0`, gw `192.168.1.254` (laptop IP) dns `192.168.1.1` and tried to access `mitm.it`, but the page doesn't load

#### System Information
```
% ifconfig en0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        options=6460<TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
        ether 6c:7e:67:c3:6c:e4
        inet 192.168.1.254 netmask 0xffffff00 broadcast 192.168.1.255
        inet6 fe80::10b0:326b:244c:a3d%en0 prefixlen 64 secured scopeid 0xf 
        inet6 2804:57f4:2100:4b75:42e:10b8:55df:67bc prefixlen 64 autoconf secured 
        inet6 2804:57f4:2100:4b75:6dde:bc98:b9e:5255 prefixlen 64 autoconf temporary 
        nd6 options=201<PERFORMNUD,DAD>
        media: autoselect
        status: active
```

```
% mitmproxy --version
Mitmproxy: 10.2.2 binary
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  macOS-14.2.1-x86_64-i386-64bit
```

**Comment by mhils** [comment]
Did you see https://docs.mitmproxy.org/stable/howto-transparent/?

Alternatively, WireGuard mode might be easier to set up. :)
