### ISSUE TITLE
Duplicate answers in DNS queries

### ISSUE THREAD

**Issue by sujaldev** [mitmproxy/mitmproxy#6647]
#### Problem Description

Two duplicate records are returned for each unique A/AAAA record in a DNS query when using DNS mode.

##### Without mitmproxy

1. Run `dig +short google.com`
2. Correct output: `142.250.193.206`

##### With mitmproxy

1. Start mitmproxy `mitmproxy --mode dns@53535`
2. Run `dig @127.0.0.1 -p 53535 +short google.com`
3. Output with duplicates:
    ```
    142.250.193.206
    142.250.193.206
    142.250.193.206
    ```

#### System Information

```
Mitmproxy: 11.0.0.dev (+19, commit d638213)
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-6.6.14-200.fc39.x86_64-x86_64-with-glibc2.38
```

#### Additional Notes

This is happening because the `dns_resolver` addon calls `getaddrinfo` here:

https://github.com/mitmproxy/mitmproxy/blob/1a02ebb89f6765d827f2fe0086dfe5960eb6e093/mitmproxy/addons/dns_resolver.py#L29

Which is returning one tuple each for UDP, TCP and a raw socket.

We could just do the following since I assume all requests are currently using UDP:
```python
addrinfos = await loop.getaddrinfo(host=question.name, port=0, family=family, type=socket.SOCK_DGRAM)
```

What do you think?

**Comment by mhils** [comment]
Yes, please send a PR! We eventually should really support DNS-over-TCP, but this is a good mitigation for now.
