### ISSUE TITLE
can't use by https

### ISSUE THREAD

**Issue by hhhaiai** [mitmproxy/mitmproxy#665]
hi:
 Ihas a problem; show you:
environment:window+android phone + cygwin
network:  connection wifi by  "CA Certificate"
problem: browser can connect to network by https ,alway warring the "CA Certificate Abnormal".
the app can't connect to network by https.

 so it is.

**Comment by hhhaiai** [comment]
and  I see the mitm  in cmd. response is  succes , status is 200.
but  toast "happen error, please check network!". why

**Comment by mhils** [comment]
Sorry, but I have no idea what your issue could be. Did you install the mitmproxy CA certificate on the phone?

Maybe you can clarify your issue by using the bug report template in [CONTRIBUTING.md](https://github.com/mitmproxy/mitmproxy/blob/master/CONTRIBUTING.md)

**Comment by hhhaiai** [comment]
my mean:
browser can connect by my CA
app can't connect.

phone need mitmproxy CA? what  need to do?

**Comment by hhhaiai** [comment]
I install mitmproxy by easy_install:

python setup.py install 

.........................................
window + cygwin  install error has processed. now can use, but begin  a litter slow

**Comment by mhils** [comment]
You need to install the CA certificate using the web app (visit [mitm.it](http://mitm.it)). If it still does not work, your app may employ certificate pinning (e.g. twitter does this).

**Comment by hhhaiai** [comment]
hi
dear mhils , my english is so.. 。。  Laughed
before my app can connect network  by http, now change to https ,can't connect nework.
mitm 's CA certificate  can install to phone ? what can i do?  setup ..   

thx

**Comment by milesrichardson** [comment]
Hello

Is it completely impossible to circumvent certificate pinning?  Are there any clever solutions to this?  Where can I read more?

Thanks

**Comment by mhils** [comment]
It's usually a process that is specific to the application you're analyzing. There are a few off-the-shelf solution for mobile devices though:
https://github.com/Fuzion24/JustTrustMe
https://github.com/iSECPartners/ios-ssl-kill-switch
https://github.com/iSECPartners/Android-SSL-TrustKiller
Other than that, you can reverse-engineer the application and patch out the certificate pinning.

**Comment by milesrichardson** [comment]
Thank you. 

Is there any way for an upstream server to detect something like SSL kill switch?

**Comment by milesrichardson** [comment]
I have access to what I presume are the certificate files. They are called COMODORSADomainValidationSecureServerCA.crt and COMODORSACertificationAuthority.crt. How do I provide these as a certificate for mitmproxy to use?

**Comment by mhils** [comment]
`.crt` = the public certificate. You'd need to private key if you want to sign something.

**Comment by hhhaiai** [comment]
ok  I fexed it. see https://www.kidozen.com/httphttps-debugging-on-mobile-apps-with-man-in-the-middle/    
thx.
