### ISSUE TITLE
 ChatGPT The CPU usage issue with Mitmproxy 10.

### ISSUE THREAD

**Issue by wlfzsd** [mitmproxy/mitmproxy#6651]
When using the same Python script, the CPU usage of Mitmproxy 9 remains below 20%, while Mitmproxy 10 has a usage rate exceeding 90%, and it is a continuous upward

**Comment by Prinzhorn** [comment]
Is this a bug report? We have a template you are presented with here https://github.com/mitmproxy/mitmproxy/issues/new?assignees=&labels=kind%2Ftriage&projects=&template=bug_report.md&title=
