### ISSUE TITLE
UI doesn't work on a port different than `8081`

### ISSUE THREAD

**Issue by mieciu** [mitmproxy/mitmproxy#6652]
#### Problem Description

When running Mitmproxy in Docker `mitmproxy/mitmproxy:10.1.5` like this:
```
mitmweb --set termlog_verbosity=warn --no-web-open-browser --listen-port 6666 --web-host 0.0.0.0 --web-port=6667 --mode reverse:http://${HOST_IP}:8080/
```
I'd expect the UI to be accessible at port number `6667`. However, there's just a blank page, `curl` reports:
```
curl localhost:6667

<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8" />
<title>mitmproxy</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="stylesheet" href="static/vendor.css" />
<link rel="stylesheet" href="static/app.css" />
<link rel="icon" href="static/images/favicon.ico" type="image/x-icon" />
<script src="static/app.js"></script>
</head>
<body>
<div id="mitmproxy"></div>
</body>
</html>
```

#### System Information
```
# mitmproxy --version
Mitmproxy: 10.1.5
Python:    3.11.6
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-6.5.11-linuxkit-aarch64-with-glibc2.31
```

**Comment by sujaldev** [comment]
Seems to be working fine, are you sure you've mapped the ports 6666 and 6667 from the host to the container?

**Comment by Prinzhorn** [comment]
This is what I'm getting in Firefox and Chromium:

![image](https://github.com/mitmproxy/mitmproxy/assets/679144/f5eb757c-2086-45d6-bd1b-3c430a3eeb18)
![image](https://github.com/mitmproxy/mitmproxy/assets/679144/3af46e0b-ceb5-483d-8946-0a784b0fcb34)

6667 appears to be blocked https://neo4j.com/developer/kb/list-of-restricted-ports-in-browsers/

**Comment by Prinzhorn** [comment]
Since it works with curl, I assume this is a browser issue. Choose a different port.
