### ISSUE TITLE
Wireguard config has wrong endpoint when two active NICs

### ISSUE THREAD

**Issue by cybacoffee** [mitmproxy/mitmproxy#6656]
#### Problem Description
When running `mitmweb`in `wireguard` mode with more then one active network interface (two IPs/subnets), and running the `--listen-host` flag with fixing the IP from NIC2, the wireguard config (and QR) is generated with `endpoint <NIC1>`.
One has two manually modify the wireguard config after importing via e.g. QR code.
But the `listening` on NIC2 works as it should, only the config is generated wrong.

#### Steps to reproduce the behavior:
1. Run two network interfaces (e.g. primary NIC1=192.168.1.10/24, NIC2=192.168.2.10/24)
2. mitmweb --mode wireguard --listen-host 192.168.2.10/24
3. mitm wireguard config is generated with endpoint 192.168.1.10/32.

#### System Information
```
~ mitmweb --version
Mitmproxy: 10.2.2
Python:    3.12.1
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  macOS-14.3.1-arm64-arm-64bit
```

**Comment by mhils** [comment]
Thanks for the report! The relevant code is [here](https://github.com/mitmproxy/mitmproxy/blob/10.2.2/mitmproxy/proxy/mode_servers.py#L390), contributions welcome! :)
