### ISSUE TITLE
dummy server cert key size does not match upstream

### ISSUE THREAD

**Issue by abbbe** [mitmproxy/mitmproxy#6657]
#### Problem Description

Mitmproxy runs in a transparent mode, with traffic being redirected via iptables. It is invoked as following
```
mitmweb -- --mode transparent --listen-port 8020 --ssl-insecure --no-web-open-browser --web-host 0.0.0.0 --web-port 58020 --set confdir=/tmp/mitmproxy-sas-ca
```

The client is Chromium browser, embedded into a proprietary appliance.
The problem is mitmproxy drops connection with the following error:
```
[22:56:38.715][10.xxx.yyy.zzz:44554] Client TLS handshake failed. The client may not trust the proxy's certificate for login.xyz (OpenSSL Error([('SSL routines', '', 'no suitable signature algorithm')]))
```

When comparing certificates generated by the legit server and mitmproxy (as seen by a standard openssl s_client), I have noticed that mitmproxy uses different public key size than the original one:
```
$ diff /tmp/orig /tmp/mitm
...
<    a:PKEY: id-ecPublicKey, 256 (bit); sigalg: ecdsa-with-SHA256
---
>    a:PKEY: id-ecPublicKey, 521 (bit); sigalg: ecdsa-with-SHA256
...
< Peer signing digest: SHA256
---
> Peer signing digest: SHA512
...
< Server public key is 256 bit
---
> Server public key is 521 bit
```

I suspect this makes me hit this issue: https://security.stackexchange.com/questions/100991/why-is-secp521r1-no-longer-supported-in-chrome-others.

#### Steps to reproduce the behavior:

Unfortunately an access to a proprietary system is required to reproduce...

#### System Information

```
$ mitmproxy --version
Mitmproxy: 10.2.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-6.5.0-15-generic-x86_64-with-glibc2.35
```

**Comment by mhils** [comment]
We don't mirror attributes such as key size or algorithms because we don't want to mirror insecure configurations. So this is kind of expected behavior. 

The other part is the incompatibility with your client - 'no suitable signature algorithm' makes me think that you need to widen the allowed ciphers?

**Comment by abbbe** [comment]
@mhils sorry I was moved to another project and did not follow up on this issue. Thank you for the feedback you have provided. I will try your suggestion to widen the list of allowed ciphers and back to you with more details.
