### ISSUE TITLE
The issue of app stuttering or lagging when mitmproxy captures data from a mobile app

### ISSUE THREAD

**Issue by yaomoshen520** [mitmproxy/mitmproxy#6674]
In my mobile device, I have installed ProxyDroid to forward SOCKS5 traffic to mitmproxy. However, during the packet capturing process, videos fail to play smoothly and the overall app experiences lagging. Additionally, pages that require network loading do not load properly.

**Comment by Prinzhorn** [comment]
If you want to report a bug, there is a template you can fill out https://github.com/mitmproxy/mitmproxy/issues/new?assignees=&labels=kind%2Ftriage&projects=&template=bug_report.md&title=

> However, during the packet capturing process, videos fail to play smoothly and the overall app experiences lagging

mitmproxy is not optimized for throughput, that's not the goal. If you can provide clear steps to reproduce a specific issue or even a regression (e.g. it was faster in previous versions) we are more than happy to look into it.

You can also look into the many options we provide such as [` stream_large_bodies`](https://docs.mitmproxy.org/stable/concepts-options/#stream_large_bodies) to improve perceived performance.

> Additionally, pages that require network loading do not load properly.

"Do not load properly" is nothing we can act on.
