### ISSUE TITLE
Switch from light only to dark only mode

### ISSUE THREAD

**Issue by KaKi87** [mitmproxy/mitmproxy#6686]
#### Problem Description

Cf. #3886

#### Proposal

Add a dark mode like #3886 requested, but as a replacement instead of a complement to light mode, in order to solve this :

> Dark mode has constant maintenance cost if you don't want to let it perish, and I don't want to maintain that.

If dark is the only mode then the maintenance cost remains unchanged compared to the current light mode's maintenance cost.

#### Alternatives

Refactoring the current light mode colors into variables, so that dark mode as a complement instead of a replacement would be a simple as providing alternative variables, resulting in a minimal additional maintenance cost, compared to doubling selectors.

#### Additional context

Dark mode for the web UI is only natural considering that the terminal UI also has one.

**Comment by mhils** [comment]
Light mode is here to stay, sorry. I've given longer explanations in https://github.com/mitmproxy/mitmproxy/issues/3886 and https://github.com/mitmproxy/mitmproxy/pull/5650.

If anyone wants to step up and show some commitment to maintaining and extending the web UI (not just dark mode), I'd be more than happy to accommodate their favorite features. I don't want to touch dark mode while we still have some tech debt in the form of an impending Bootstrap 3 -> Bootstrap 5 upgrade.
