### ISSUE TITLE
[Off-Topic?] Is there a community/forum where I can ask about *usage*?

### ISSUE THREAD

**Issue by jjarava** [mitmproxy/mitmproxy#670]
Hi!

I understand this is likely **not** the place to ask "*How do I do X?*" questions about mitmproxy, but I'm wondering if there's a specific place/community where to ask those kinds of questions

Googling around I've seen questions about mitmproxy in many different places, but there's not a place that looks like the "natural" place to send those questions.

Thanks a lot and sorry if it's a pretty obvious question - I believe that if there is such a place it should be more "advertised" on the project's home page

Thanks!

**Comment by jjarava** [comment]
I looked better and found the link to the Google Groups (https://groups.google.com/forum/#!forum/mitmproxy). Sorry!

**Comment by mhils** [comment]
Also, IRC - don't hesistate to ping us there. :wink:
