### ISSUE TITLE
Render `flow.comment` in mitmweb as column and also in the sidebar

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#6708]
#### Problem Description

Via https://github.com/mitmproxy/mitmproxy/discussions/6699#discussioncomment-8648228

`flow.comment` is currently not rendered in mitmweb (I swear there was a feature request a while ago, at least for `flow.metadata`)

#### Proposal

1. Implement a renderer for `comment` column (single line with `text-overflow: ellipsis`) so you can see short comments in full or at least a preview
2. Render `comment` in the sidepanel when a flow is selected

#### Alternatives

\*no comment\*

**Comment by lups2000** [comment]
@Prinzhorn @mhils I am working on this! Where do you think the best place to put the comment is in the side panel? And are we also missing the possibility to add a comment through the web GUI, or am I mistaken?

**Comment by malwareinfosec** [comment]
> @Prinzhorn @mhils I am working on this! Where do you think the best place to put the comment is in the side panel? (new tab?) And are we also missing the possibility to add a comment through the web GUI, or am I mistaken?

Thanks! Add/Edit a comment in the web UI would be great to have as well. For context, here are some previous implementations of this kind of functionality:

On Fidder, I only ever used a custom column called 'Comments'

![image](https://github.com/mitmproxy/mitmproxy/assets/25351665/b03c260b-2c40-4b14-b94b-a48556a220d0)

In the new Fiddler Everywhere, they introduced a separate functionality called 'Rules':

![image](https://github.com/mitmproxy/mitmproxy/assets/25351665/be797ae8-6f17-46ce-a83c-8ba517f1d22a)

On ZAP proxy, they had something a little different geared towards what they call 'Alerts'. So I used the existing fields that they had already.

![image](https://github.com/mitmproxy/mitmproxy/assets/25351665/7601385d-04db-4fa2-8314-3ecea1fa6c62)

I am a long time user of Fiddler, but the legacy version of the application is no longer updated with new features. Their multi OS application Fiddler Everywhere improves on a lot of things but removes the customization from the user experience. One of the great things about the original Fiddler was the ability to write custom extensions. This is no longer possible on the updated version.

ZAP proxy is a solid application but is written in Java and while addons are supported, it is more complicated to write them and get support.

I think mitmproxy combines a lot of things that those others don't: multi-OS, Python scripting, etc.

**Comment by malwareinfosec** [comment]
Not sure if the feature has been released yet (tested build 10.2.4) and mitmweb.

Do you need to add the column via Edit options, web_columns and enter the text 'comment'? Or does it appear automatically when a comment is triggered?

**Comment by lups2000** [comment]
> Not sure if the feature has been released yet (tested build 10.2.4) and mitmweb.
> 
> Do you need to add the column via Edit options, web_columns and enter the text 'comment'? Or does it appear automatically when a comment is triggered?

I think it hasn't been released yet! Once released yes, you write "comment" and it appears automatically :)
