### ISSUE TITLE
Problem with multipart upload and content view

### ISSUE THREAD

**Issue by jlhonora** [mitmproxy/mitmproxy#671]
I'm facing an issue when trying to view the details of a multipart POST request using mitmproxy. 

##### Steps to reproduce the problem:

- `mitmproxy --port 8888`
- Make the request:

```
curl -F filename=597fee54-2682-42c1-a87f-9ae55b1bf402.zip \
       -F 597fee54-2682-42c1-a87f-9ae55b1bf402.zip=@597fee54-2682-42c1-a87f-9ae55b1bf402.zip \
       --proxy 192.168.2.92:8888 http://192.168.2.92:3000/api/v1/upload
```

The zip file can be found [here](https://s3.amazonaws.com/beetrack/test/597fee54-2682-42c1-a87f-9ae55b1bf402.zip). Sorry, can't expose the backend but I guess it is not really necessary.

- The request is correctly processed in mitmproxy:

```
>> POST http://192.168.2.92:3000/api/v1/upload
        ← 200 application/json 29B 114ms
```

- Press enter key to see the request's info and contents

##### What is the expected behavior?

mitmproxy shouldn't hang and it should display the request's contents.

##### What went wrong?

The process gets stuck, eating most of the CPU:

```
PID    COMMAND      %CPU
25376  python       95.8 
```

##### Any other comments?

I browsed the source code for a bit, tried to get the stacktrace with lldb, search for log files but didn't get much far. If anyone can point me in the right direction to debug this I'd be glad to help.

---
mitmproxy version: mitmproxy 0.12.1
Operating System: Darwin [edited].local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by jlhonora** [comment]
The program gets stuck when rendering the text. It seems to have trouble handling non-ascii characters. This patch "fixes" it, but I think it is far from optimal:

```
diff --git a/libmproxy/utils.py b/libmproxy/utils.py
index a29a53f..dbc0c77 100644
--- a/libmproxy/utils.py
+++ b/libmproxy/utils.py
@@ -98,7 +98,7 @@ def multipartdecode(hdrs, content):
                 if match:
                     key = match.group(1)
                     value = "".join(parts[3 + parts[2:].index(""):])
-                    r.append((key, value))
+                    r.append((key, value.encode("ascii", "ignore")))
         return r
     return []
 ```

though when rendering the text the following message appears:

```
Couldn't parse: falling back to Raw
```

Any clues on how this should be treated?

**Comment by rrbauer** [comment]
No suggestions for a better way to handle this, but thanks for the patch.  For me, I'm not so much interested in the non-ascii data (a jpeg image)  as I am the structure of the multipart post and other metadata.  This patch did the trick!

**Comment by mhils** [comment]
Thanks for the report. This is fixed on master now.

**Comment by jlhonora** [comment]
Thanks!
