### ISSUE TITLE
export websocket messages

### ISSUE THREAD

**Issue by 3052** [mitmproxy/mitmproxy#6715]
#### Problem Description

it seems websocket messages can be viewed, but I am not seeing a way to export them or even search for requests containing some text in a websocket message

**Comment by Prinzhorn** [comment]
This sounds like a mix of multiple independent feature requests?

1. Add new filters in addition to `~websocket` like `~websocket_message` that matches all flows where at least one message matches
2. Some sort of `export` command specifically for websockets? What format?

Could you please open multiple issues for each of them and actually follow the [template](https://github.com/mitmproxy/mitmproxy/issues/new?assignees=&labels=kind%2Ffeature&projects=&template=feature_request.md&title=)?
