### ISSUE TITLE
The mitmproxy program failed to start because the default port 8080 was occupied.

### ISSUE THREAD

**Issue by optor666** [mitmproxy/mitmproxy#6716]
#### Problem Description
Because the default port 8080 is occupied, the mitmproxy program fails to start, and there is no output reason for the failure.

#### Steps to reproduce the behavior:
1. Listen on port 8080 using the nc command in a terminal window.
2. Start the mitmproxy program in another terminal window.
3. The mitmproxy program failed to start, and there was no output reason for the failure, and the normal terminal configuration was not restored.
![image](https://github.com/mitmproxy/mitmproxy/assets/32811372/e8333100-fceb-4fdb-b781-829a9ce89945)

#### System Information
Mitmproxy: 10.2.3 binary
Python:    3.12.2
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  macOS-14.2.1-arm64-arm-64bit

**Comment by mhils** [comment]
That's bad, thanks. Possibly refs https://github.com/mitmproxy/mitmproxy/issues/6707

**Comment by mhils** [comment]
bisected to 6e38a56f4c399551c3fe3d399bddfa8083ccd0f1
