### ISSUE TITLE
Fresh installed mitmproxy 10.2.3 gives a warning from cryptography 42.0.x on startup

### ISSUE THREAD

**Issue by thisisgk** [mitmproxy/mitmproxy#6717]
#### Problem Description
Fresh installed mitmproxy 10.2.3 gives a warning from cryptography 42.0.x on startup:
`.../pipx/venvs/mitmproxy/lib/python3.12/site-packages/mitmproxy/certs.py:111: CryptographyDeprecationWarning: Properties that return a naïve datetime object have been deprecated. Please switch to not_valid_after_utc.`
`  return self._cert.not_valid_after.replace(tzinfo=datetime.timezone.utc)`
May not be a big problem, but feel anxious.

#### Steps to reproduce the behavior:
1. pipx uninstall mitmproxy
2. pipx install mitmproxy
3. run mitmproxy or mitmdump or mitmweb

#### System Information
Mitmproxy: 10.2.3
Python:    3.12.2
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  macOS-10.13.6-x86_64-i386-64bit

cryptography:  42.0.5

**Comment by mhils** [comment]
Thanks for the report!
