### ISSUE TITLE
search websocket messages

### ISSUE THREAD

**Issue by 3052** [mitmproxy/mitmproxy#6722]
#### Problem Description
cannot search the content of websocket message, like you can for HTTP request/response bodies

#### Steps to reproduce the behavior:
1. if you try `~b` it only searches HTTP request/response bodies, and not similar option is available for websocket messages that I am aware of

#### System Information

mitmproxy 10.2.4

**Comment by txrp0x9** [comment]
By search, I assume you mean the filter command, however, that seems to work with filtering WebSocket messages on my machine (https://websocketking.com/)

**Comment by 3052** [comment]
the previous comment its helpful, because you didn't give an example filter expression.

**Comment by txrp0x9** [comment]
Apologies, let me show my testing flow as an example:
Use to generate example wss connection to echo.websocket.org
![image](https://github.com/mitmproxy/mitmproxy/assets/41499871/a9c7eadb-6870-4c06-97e5-40eb12250657)
![image](https://github.com/mitmproxy/mitmproxy/assets/41499871/eab08124-479d-49c2-80bf-12a4e6edd1e4)
Here's the result with using '~b testing99' as a filter expression:
![image](https://github.com/mitmproxy/mitmproxy/assets/41499871/a88de3c9-faee-42e9-99ec-2d4e04d0b9f4)
The expression correctly filtered out the wss connection based on its body (ws messages)

**Comment by 3052** [comment]
OK I think this was my mistake
