### ISSUE TITLE
--replace-from-file not working properly (escaping issue?) Option to save/load Replacemets via editor?

### ISSUE THREAD

**Issue by jjarava** [mitmproxy/mitmproxy#674]
Hi all!!

I'm trying to use the `--replace-from-file` syntax as shown in https://mitmproxy.org/doc/features/replacements.html and I'm hitting a wall.

I've got a set of replacement data (Filter, Regex, Replacement) that work fine via the editor:

![mitmproxy-replacements-cli-not-working-2015-07-09_17-10-15](https://cloud.githubusercontent.com/assets/2682444/8598913/cba7ec3a-265d-11e5-99ce-e5eb861cf3b6.jpg)
 
And they're pretty "simple":

- Filter: `~u wwww\.example\.com/loginurl`
- Regex: `sello-pa_e.js"></script>`
- Replacement: 
```html
sello-pa_e.js"></script>
<script type="text/javascript"> (function(){ ... long JavaScript code ...})(); </script>
```

Basically I want to add the specific JS in the next line to the element I'm looking for with the regex.

So, to avoid having to manually enter the replacements in the editor, I'd like to either "save" them or load them from the CLI.

Looking at the help, I've tried to do it via the `--replace-from-file` option but I can't get it to work.

I've tried several things, in case it's an issue of how to "escape" the command:

### First attempt - mimic the example in the docs

```bash
ITSDev:test testuser$ mitmproxy --replace-from-file :~u wwww\.example\.com/loginurl:sello-pa_e.js"></script>:./mitmproxy-repl.txt
>
>
>
```
The example above keeps "waiting on input" (every `↩` or `⌅` press gets a new line), so I changed the way to escape the command:

### Second attempt - single comma escape

```bash
ITSDev:test testuser$ mitmproxy --replace-from-file :~u wwww\.example\.com/loginurl:'sello-pa_e.js"></script>':./mitmproxy-repl.txt
usage: mitmproxy [options]
mitmproxy: error: unrecognized arguments: wwww.example.com/loginurl:sello-pa_e.js"></script>:./mitmproxy-repl.txt
```
This was a bit more promising, as after hitting `↩` there was a pause of about a second before I got the error message...

### Third attempt - use a different separator

Thinking that maybe the `:` has some special meaning in OSX; I've used a different separator:

```bash
ITSDev:test testuser$ mitmproxy --replace-from-file ,~u wwww\.example\.com/loginurl,'sello-pa_e.js"></script>',./mitmproxy-repl.txt
usage: mitmproxy [options]
mitmproxy: error: unrecognized arguments: wwww.example.com/loginurl,sello-pa_e.js"></script>,./mitmproxy-repl.txt
ITSDev:test testuser$
```

but the result is the same...

I have the feeling that I'm missing something but I can't see what.

What it would really make my life easier would be a "replacement" file format where I could specify the 3 parameters (Filter, Regex, Replacement) and then pass it on as a single parameter to the program... Or a way to "save" the Replacement expressions that are loaded in the editor at a given moment...

Any tips will be more than welcome!

**Comment by mhils** [comment]
If your filter contains spaces, you need to surround it with quotes: `mitmdump --replace-from-file ':~u wwww\.example\.com/loginurl:sello-pa_e.js"></script>:./mitmproxy-repl.txt'`. On Windows, this is sufficient and it works as intended. Otherwise you may need to escape `<>` as well.

Cheers,
Max
