### ISSUE TITLE
Random SIGPIPE  error when writing to a closed socket on a surge of requests

### ISSUE THREAD

**Issue by changsin** [mitmproxy/mitmproxy#6744]
#### Problem Description
We are using mitmproxy's wrapper DumpMaster to process user's internet requests.
When there is a sudden surge of requests, mitmproxy will hit SIGPIPE (broken pipe) error because it was trying to write to a closed socket.

#### Steps to reproduce the behavior:
1.  Quickly open 15~20 youtube videos in different tabs (you can keep clicking the same link multiple times)
2. While the tabs are loading, quickly close the tabs one by one
3. SIGPIPE error occurs - especially if you have a limited number of file descriptor count

Below is the stack trace and the offending line of the source code:

  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 629, in run_until_complete
  File "asyncio/base_events.py", line 596, in run_forever
  File "asyncio/base_events.py", line 1890, in _run_once
  File "asyncio/events.py", line 80, in _run
  File "mitmproxy/proxy/server.py", line 272, in handle_connection
  File "mitmproxy/proxy/server.py", line 371, in server_event

server.py:
                elif isinstance(command, commands.SendData):
                    writer = self.transports[command.connection].writer
                    assert writer
                    if not writer.is_closing():
                        writer.write(command.data)   <-- line 371

#### System Information
Mitmproxy: 9.0.1
Python:    3.9.6
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  macOS-14.4-arm64-arm-64bit

**Comment by mhils** [comment]
Can you please verify if that still reproduces with the latest mitmproxy release, and also provide the full traceback including the SIGPIPE error message?

**Comment by changsin** [comment]
I upgraded to the latest build and it still repros.
The offending line is still the same. Just the line numbers are different.
Would it make sense to put a lock for a fix?

 File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 636, in run_until_complete
  File "asyncio/base_events.py", line 603, in run_forever
  File "asyncio/base_events.py", line 1909, in _run_once
  File "asyncio/events.py", line 80, in _run
  File "mitmproxy/proxy/server.py", line 294, in handle_connection
  File "mitmproxy/proxy/server.py", line 407, in server_event
  File "asyncio/streams.py", line 325, in write
  File "asyncio/selector_events.py", line 924, in write


## mitmproxy version info:
Mitmproxy: 10.2.4
Python:    3.10.11
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  macOS-14.4-arm64-arm-64bit

Here is how we are capturing the SIGPIPE signal
###Received signal: 13, printing stack trac

```
def signal_handler(signal_received, frame):
    logger.error(f"###Received signal: {signal_received}, printing stack trace:")
    traceback.print_stack(frame)


def hookup_signal_handler():
    signal.signal(signal.SIGPIPE, signal_handler)
```

**Comment by mhils** [comment]
After looking at this for a bit -- I'm all but an expert on unix signals --, it sounds like mitmproxy should run `signal(SIGPIPE, SIG_IGN)` on startup. Can you confirm that this would fix the issue for you (for testing you can run that from an addon)? If yes, can you please send a PR that add this call [here](https://github.com/mitmproxy/mitmproxy/blob/d4200a7c0d2f4efd77c44651645b59662a29a54a/mitmproxy/tools/main.py#L123)? Thanks!

**Comment by changsin** [comment]
You mean like this, right?
        signal.signal(signal.SIGINT, _sigint)
        signal.signal(signal.SIGTERM, _sigterm)
        signal.signal(signal.SIGPIPE, SIG_IGN) <-- added

This just ignores SIGPIPE signal, right? Would it make the bad connection stay bad?
How is it different from the signal handler that I had earlier?

How about adding this to server.py? In the signal_handler, we close the bad connection.
This seems to work better in our internal testing.

```
        # workaround for https://bugs.python.org/issue40124 / https://bugs.python.org/issue29930
        self._drain_lock = asyncio.Lock()
        signal.signal(signal.SIGPIPE, self.signal_handler)

    def signal_handler(self, signal_received, frame):
        self.log(f"###Received signal1: {signal_received}, printing stack trace:", logging.ERROR)
        traceback.print_stack(frame)
        self.log("client kill connection")
        writer = self.transports.pop(self.client).writer
        assert writer
        writer.close()
```

**Comment by hans-at-strac** [comment]
We added `signal.signal(signal.SIGPIPE, SIG_IGN)` but that did not resolve the issue.

The symptoms on my machine:
* If you open Slack the next day, Slack is not able to connect
* Intermittently, some websites won't load up but after 30 seconds, it will automatically retry and connect.

**Comment by mhils** [comment]
@hans-at-strac: To confirm, the patch posted by @changsin does definitely fix the issue, but just setting SIG_IGN doesn't? 

We're seeing one error message here (SIGPIPE) and some particular networking issues. But I'd like to make sure that there also is causality between these two.

Can you send SIGUSR1 / SIGUSR2 to the mitmproxy process when this Slack issue occurs? Ideally on an otherwise silent network.

**Comment by changsin** [comment]
Actually, after some extensive expriments and use, SIG_IGN seems to have fixed the issue. I'll submit a PR.
