### ISSUE TITLE
Async `client_connected` hook is broken in 10.2.4

### ISSUE THREAD

**Issue by Prinzhorn** [mitmproxy/mitmproxy#6745]
#### Problem Description

I  finally got around upgrading to mitmproxy 10 and things didn't work at all. I was able to track it down to the async `client_connected` hook not working. It does work in 10.0.0 and broken in 10.2.4. Not sure about other hooks, this one starts the entire chain and hence that's where all connections end.

#### Steps to reproduce the behavior:

addon.py

```py
import asyncio


async def client_connected(client):
    print("client_connected...")
    await asyncio.sleep(1)
    print("...client_connected")
```

1. `mitmdump --scripts addon.py`
2. `curl --insecure --proxy localhost:8080 https://example.com/`

Mitmproxy 9.0.1 output:

```
[10:02:00.891] Loading script addon.py
[10:02:00.892] HTTP(S) proxy listening at *:8080.
[10:02:03.639][[::1]:37674] client connect
client_connected...
...client_connected
[10:02:04.746][[::1]:37674] server connect example.com:443 ([2606:2800:220:1:248:1893:25c8:1946]:443)
[::1]:37674: GET https://example.com/ HTTP/2.0
 << HTTP/2.0 200 OK 1.2k
[10:02:05.091][[::1]:37674] client disconnect
[10:02:05.092][[::1]:37674] server disconnect example.com:443 ([2606:2800:220:1:248:1893:25c8:1946]:443)
```

Mitmproxy 10.0.0 output:

```
[10:06:17.770] Loading script addon.py
[10:06:17.771] HTTP(S) proxy listening at *:8080.
[10:06:19.790][[::1]:33394] client connect
client_connected...
...client_connected
[10:06:20.898][[::1]:33394] server connect example.com:443 ([2606:2800:220:1:248:1893:25c8:1946]:443)
[::1]:33394: GET https://example.com/ HTTP/2.0
 << HTTP/2.0 200 OK 1.2k
[10:06:21.241][[::1]:33394] client disconnect
[10:06:21.241][[::1]:33394] server disconnect example.com:443 ([2606:2800:220:1:248:1893:25c8:1946]:443)
```

Mitmproxy 10.2.4 output:

```
[10:03:04.389] Loading script addon.py
[10:03:04.389] HTTP(S) proxy listening at *:8080.
[10:03:07.451][[::1]:35406] client connect
client_connected...
...client_connected
[10:03:08.452][[::1]:35406] mitmproxy has crashed!
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 381, in server_event
  File "mitmproxy/proxy/layer.py", line 148, in handle_event
  File "mitmproxy/proxy/utils.py", line 27, in _check_event_type
AssertionError: Unexpected event type at HttpProxy._handle_event: Expected Start, got DataReceived(client, b'CONNECT example.com:443 HTTP/1.1\r\nHost: example.com:443\r\nUser-Agent: curl/8.2.1\r\nProxy-Connection: Keep-Alive\r\n\r\n').
```

#### System Information

```
Mitmproxy: 10.2.4 binary
Python:    3.12.2
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  Linux-6.5.0-25-generic-x86_64-with-glibc2.38
```

**Comment by Prinzhorn** [comment]
Broke with `>=10.2.0`

**Comment by mhils** [comment]
Thanks for the super nice report.

Bisected to 6e38a56f4c399551c3fe3d399bddfa8083ccd0f1 - this is very likely caused by eager task execution as well.

**Comment by Prinzhorn** [comment]
@mhils continuation from Discord: were you able to reproduce this locally? I can't repro this with 10.2.4 when launching from the venv, only with the downloaded binary. I don't understand why that would make a difference. I'd need to repro it in order to properly evaluate the stderr flushing situation.

**Comment by mhils** [comment]
@Prinzhorn: You can get precompiled binaries for branches from https://github.com/mitmproxy/mitmproxy/actions/workflows/main.yml?query=branch%3Amain. Does that help?

**Comment by Prinzhorn** [comment]
I mean it might somewhat help, but I'm just confused as to why I can't trigger the async `client_connected` bug locally. I need to look into this again next week.

**Comment by Prinzhorn** [comment]
1. `git clone git@github.com:mitmproxy/mitmproxy.git`
2. `cd mitmproxy`
3. `git checkout bc3367cce6d45f18348f33b5025ba2bc65362610` (one before https://github.com/mitmproxy/mitmproxy/commit/d4200a7c0d2f4efd77c44651645b59662a29a54a)
4. `python3 -m venv venv`
5. `venv/bin/pip install -e ".[dev]"`
6. `source venv/bin/activate`
7. `mitmdump --scripts addon.py` (addon from above)
8. `curl --insecure --proxy localhost:8080 https://example.com/`

@mhils can you explain why the above _works_ (no `AssertionError`)? But downloading a build from before the fix (https://github.com/mitmproxy/mitmproxy/actions/runs/8366491404) does not?

**Comment by mhils** [comment]
Fundamentally this is a race condition, so I'm not surprised that it works in some environment but not in others. For example, the Python version is different. :)

**Comment by Prinzhorn** [comment]
I was not aware that it's a race condition, it does indeed repro consistently with Python 3.12. So now i can finally look into the stderr flushing thing ;)
