### ISSUE TITLE
Implement Scrolling

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#678]
I'm using Terminal on OS/X. I'd like to have auto-scrolling such that the most recent request is always at the bottom of the screen.

This seems like such an obvious feature that I'm guessing there's a technical reason why it wasn't done.

**Comment by mhils** [comment]
You can press `F` to follow the flow list.

Cheers,
Max

**Comment by vhaupert** [comment]
Or just pass the `--follow` command line option.

**Comment by BSalita** [comment]
Nice tip. I wasn't aware of the flag. 

    On Monday, August 1, 2016 6:13 PM, Vincent Haupert <notifications@github.com> wrote:
 

 Or just pass the --follow command line option.—

**Comment by TomasHubelbauer** [comment]
I do not think `F` works in the latest version of MITMproxy anymore. For me it enters a mode where I can type view filter. What is the equivalent of `F` in the latest version?

**Comment by mhils** [comment]
`F` works fine for me, are you confusing it with `f` (without shift)? You can also change the `console_focus_follow` option to true, which achieves the same thing.

**Comment by TomasHubelbauer** [comment]
I thought I was using Shift, but I guess I mistyped, because I just tried again and it works fine now. Sorry for the noise.
