### ISSUE TITLE
fatal error: 'libxml/xmlversion.h' file not found

### ISSUE THREAD

**Issue by lardissone** [mitmproxy/mitmproxy#68]
I'm getting this error when trying to install it with pip in Mac OS X Mountain Lion.

This is the complete pip.log:  
https://gist.github.com/4125461

I've all the latest XCode Command Line Tools installed.

**Comment by orukusaki** [comment]
I know this is an old issue, but I've been experiencing a very similar one recently (though it was actually the Nokogiri Ruby gem that I was trying to install), and Googling brought me here.

I got past it by symlinking the Homebrew install of libxml2 to the usual include path:

    sudo ln -s /usr/local/opt/libxml2/include/libxml2/libxml /usr/local/include/libxml

This might not be ideal for all situations, but works for me for now.

**Comment by devchenpy** [comment]
@cirosantilli it works for me, thanks!

**Comment by aratic** [comment]
libxslt do works for freebsd v10.3, python27, here i try pip install lxml and got such error, thanks @cirosantilli

**Comment by mcclayac** [comment]
I am still having these problems.  I have tried 

1.  brew install libxml2
2.  pip install lxml  ( Same Error : see below )
3.  sudo ln -s /usr/local/opt/libxml2/include/libxml2/libxml /usr/local/include/libxml

I still have this error on my Macbook Pro.  Can anyone offer another suggestion?


$ **brew list libxml2**
/usr/local/Cellar/libxml2/2.9.4_3/bin/xml2-config
/usr/local/Cellar/libxml2/2.9.4_3/bin/xmlcatalog
/usr/local/Cellar/libxml2/2.9.4_3/bin/xmllint
/usr/local/Cellar/libxml2/2.9.4_3/include/libxml2/ (47 files)
/usr/local/Cellar/libxml2/2.9.4_3/lib/libxml2.2.dylib
/usr/local/Cellar/libxml2/2.9.4_3/lib/cmake/libxml2/libxml2-config.cmake
/usr/local/Cellar/libxml2/2.9.4_3/lib/pkgconfig/libxml-2.0.pc
/usr/local/Cellar/libxml2/2.9.4_3/lib/python2.7/ (4 files)
/usr/local/Cellar/libxml2/2.9.4_3/lib/ (3 other files)
/usr/local/Cellar/libxml2/2.9.4_3/share/aclocal/libxml.m4
/usr/local/Cellar/libxml2/2.9.4_3/share/doc/ (153 files)
/usr/local/Cellar/libxml2/2.9.4_3/share/gtk-doc/ (55 files)
/usr/local/Cellar/libxml2/2.9.4_3/share/man/ (4 files)

Error Message
==========================
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/mf/k3gwf7795b594fkvb64vbz_r0000gn/T/xmlXPathInitmvgtwwy3.c -o var/folders/mf/k3gwf7795b594fkvb64vbz_r0000gn/T/xmlXPathInitmvgtwwy3.o
    /var/folders/mf/k3gwf7795b594fkvb64vbz_r0000gn/T/xmlXPathInitmvgtwwy3.c:1:10: fatal error: 'libxml/xpath.h' file not found
    #include "libxml/xpath.h"
             ^
    1 error generated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    Perhaps try: xcode-select --install
    *********************************************************************************
    error: command '/usr/bin/clang' failed with exit status 1

**Comment by mhils** [comment]
The latest mitmproxy release does not depend on lxml anymore.

**Comment by linkdesu** [comment]
If you are MacOS , rerun `xcode-select --install` this problem may be fixed.

**Comment by guidoilbaldo** [comment]
Hi, update on this with macOS Mojave: I still had the problem after installing both CLI tools with `xcode-select --install` and libxml2 / libxslt with brew.
The only thing that fixed the problem was installing missing legacy headers as pointed out here: https://silvae86.github.io/sysadmin/mac/osx/mojave/beta/libxml2/2018/07/05/fixing-missing-headers-for-homebrew-in-mac-osx-mojave.html

Simply run 
`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`
and there you go!

**Comment by ynsgnr** [comment]
> I know this is an old issue, but I've been experiencing a very similar one recently (though it was actually the Nokogiri Ruby gem that I was trying to install), and Googling brought me here.
> 
> I got past it by symlinking the Homebrew install of libxml2 to the usual include path:
> 
> ```
> sudo ln -s /usr/local/opt/libxml2/include/libxml2/libxml /usr/local/include/libxml
> ```
> This might not be ideal for all situations, but works for me for now.

Solved for me libxml2 and libxlst installed with brew

**Comment by asahiko** [comment]
> Simply run
> `sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`
> and there you go!

If you couldn't find `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` in your system like me, go to https://developer.apple.com/download/more/ , log in, look for "Command Line Tools (macOS 10.14) for Xcode 10.x" (where 10.x is your Xcode version), download and install it. After installing that you'll find the pkg file in the aforementioned directory. Double-click on it to install.

**Comment by tibastral** [comment]
> > Simply run
> > `sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`
> > and there you go!
> 
> If you couldn't find `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` in your system like me, go to https://developer.apple.com/download/more/ , log in, look for "Command Line Tools (macOS 10.14) for Xcode 10.x" (where 10.x is your Xcode version), download and install it. After installing that you'll find the pkg file in the aforementioned directory. Double-click on it to install.

Worked for me ! 

Thank you very much for that comment !!!
