### ISSUE TITLE
Request to Add the Word "Scroll" to F Key Explanation

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#680]
The term "flow" has no meaning to a noobie. I read Help several times but never associated my desire to have the screen scroll up with the explanation of the "F" key. If the word "scroll" simply appeared in the explanation of the "F" key, I would have happily used "F" instead of posting scrolling issues.

**Comment by mhils** [comment]
refs #678

**Comment by BSalita** [comment]
I'm too much of a noobie to be helpful with a better term. I can say that "flow" is a feature or algorithmic term, whereas "scroll" is the physical implementation of the feature. Anyone who works with terminals or (n)curses thinks in terms of "scroll" .. and perhaps expects that as the default behavior as is done by Fiddler proxy's "timeline" window.

**Comment by mhils** [comment]
Closed for now. If anyone finds a better name, we're happy to accept patches.
