### ISSUE TITLE
Request to add a "clear all" button to the web interface

### ISSUE THREAD

**Issue by ihunna** [mitmproxy/mitmproxy#6808]
#### Problem Description

The web interface needs a button to clear all previous requests in the console.

#### Proposal
Request to add a "clear all" button to the web interface. It's diffcult to clear the requests individually as they may be in the thousands.

Just a button next to the "delete" button to delete everything.

<img width="960" alt="Screenshot 2024-04-18 160852" src="https://github.com/mitmproxy/mitmproxy/assets/60521548/da26fac4-ca91-421f-a801-e6d0d58ef4b3">

Like in the image above, it's not easy to clearthe whole requests log except if I close this and start a new session.

**Comment by mhils** [comment]
Are you aware that you can go for File -> New?

**Comment by ihunna** [comment]
> Are you aware that you can go for File -> New?

My bad, I see a "clear all" button in the File menu.
