### ISSUE TITLE
replay HTTPS connections without doing the SSL negotiation with upstream

### ISSUE THREAD

**Issue by dedsm** [mitmproxy/mitmproxy#681]
I'm trying to replay a HTTPS request with mitmproxy without needing to be connected to the internet, this fails because in the CONNECT call mitmproxy tries to make the tcp connection and SSL negotiation with the upstream proxy, is there a way to avoid this?

**Comment by mhils** [comment]
Thanks for the report. This is indeed an issue we're working on to fix!

refs #548

**Comment by mhils** [comment]
Thanks, this is fixed on master now. :smile:
