### ISSUE TITLE
(trapped) error reading bcrypt version

### ISSUE THREAD

**Issue by D3vil0p3r** [mitmproxy/mitmproxy#6814]
#### Problem Description
I am using Arch Linux and I installed mitmproxy from [Arch Linux repository](https://archlinux.org/packages/extra/any/mitmproxy/).

When I run `mitproxy`, it works but I get the error message:
```
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
```

#### Steps to reproduce the behavior:
1. Run Arch Linux
2. `sudo pacman -S mitmproxy`
3. `mitmproxy`

#### System Information
Paste the output of "mitmproxy --version" here.
```
Mitmproxy: 10.2.4
Python:    3.11.8
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  Linux-6.8.5-arch1-1-x86_64-with-glibc2.39
```

**Comment by mhils** [comment]
https://docs.mitmproxy.org/stable/overview-installation/#linux
