### ISSUE TITLE
In Transparent Mode, How to Redirect to Charles or Fiddler?

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#682]
I want to inspect HTTP(S) API calls. I have transparent mode working fine on OS/X. Is it possible to redirect HTTP(S) to Charles or Fiddler reverse proxies. I see there are some switches on mitmproxy that suggest to me that this can be done.

**Comment by BSalita** [comment]
I see that Transparent mode is incompatible with -R and -U. However, just using -R specifying the ip:port of the Charles or Fiddler proxy system works for HTTP, not HTTPS. I'm assuming there's no solution for HTTPS.

**Comment by mhils** [comment]
If you want to redirect some parts of the traffic to a reverse proxy, just adjust the hostname in an inline script. Apart from that take a look at https://mitmproxy.org/doc/modes.html, that may clarify your thoughts.
