### ISSUE TITLE
ImportError: `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by ricrug** [mitmproxy/mitmproxy#6831]
#### Problem Description
The tool does not start and shows a specific version problem on my raspberry pi.

#### Steps to reproduce the behavior:
1. pipx install mitmproxy
2. mitmweb

#### System Information
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/user/.local/share/pipx/venvs/mitmproxy/lib/python3.9/site-packages/mitmproxy_wireguard/mitmproxy_wireguard.abi3.so)

$ ldd --version
ldd (Debian GLIBC 2.31-13+rpt2+rpi1+deb11u9) 2.31

**Comment by Prinzhorn** [comment]
> Paste the output of "mitmproxy --version" here.

**Comment by ricrug** [comment]
I hope so... It doesn't run even if I just asked for the version.
Is there a procedure to build binaries on rPi?

**Comment by mhils** [comment]
You're using an outdated Python version, we're 3.10+. For RPis, I'd recommend looking at the Docker images we provide. There's also an arm64 image.

**Comment by ricrug** [comment]
OK, I try to look at the docker image but I don't understand how I can use it to tap the traffic.
Where can I find guidelines for building from scratch?

**Comment by mhils** [comment]
https://docs.mitmproxy.org/stable/overview-installation/#advanced-installation

The issue in your specific case is a Python version that's too old (mitmproxy_wireguard is not a dependency of mitmproxy anymore), and then potentially also an outdated glibc version.
