### ISSUE TITLE
HTTP/2 protocol error: Invalid input ConnectionInputs.RECV_DATA

### ISSUE THREAD

**Issue by xzhacker123** [mitmproxy/mitmproxy#6834]
#### HTTP/2 protocol error
1. HTTP/2 protocol error: Invalid input ConnectionInputs.RECV_DATA in state ConnectionState.CLOSED

#### System Information
Mitmproxy: 10.0.0
Python:    3.11.2
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  macOS-12.2.1-x86_64-i386-64bit

**Comment by Prinzhorn** [comment]
Please:

1. Use the latest version, if it still happens:
2. Provide steps to reproduce the error (e.g. a simple curl command for a specific website?)

**Comment by ZhangTongXiang** [comment]
sure i have the same problem
➜ mitmproxy --version
Mitmproxy: 10.3.0
Python:    3.10.14
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  macOS-10.16-x86_64-i386-64bi

**Comment by Prinzhorn** [comment]
Feel free to provide steps to reproduce the error or at least a URL that does not work

**Comment by ZhangTongXiang** [comment]
i send email to you deers thanksyou

**Comment by Prinzhorn** [comment]
Please don't send e-mails, we need all information in this issue. I also don't understand your e-mail. What steps are necessary to trigger the error? Does this only happen for specific websites/URLs?
