### ISSUE TITLE
httpauth is not attached to replay request 

### ISSUE THREAD

**Issue by ryanisn** [mitmproxy/mitmproxy#6836]
#### Problem Description
I set mitmproxy to run in reverse mode as a proxy to real server, and then protect mitmproxy with a pair of user:pass in the proxyauth option. A regular request would go through, but a reply of that same request would return 401 Unauthorized

#### Steps to reproduce the behavior:
1. turn on reverse mode in mitmweb
2. set basic auth in proxyauth in 'username:pass' format
3. initiate a success request
4. replay the request

#### System Information
Mitmproxy: 10.1.5
Python:    3.11.6
OpenSSL:   OpenSSL 3.1.4 24 Oct 2023
Platform:  Linux-4.14.276-211.499.amzn2.x86_64-x86_64-with-glibc2.31

**Comment by 3052** [comment]
https://github.com/mitmproxy/mitmproxy/pull/6866
