### ISSUE TITLE
Clicks on empty space can unintentionally open a new view

### ISSUE THREAD

**Issue by ender672** [mitmproxy/mitmproxy#685]
I often click on the terminal window to activate keyboard focus.

The new click feature in mitmproxy often causes my click to open an unwanted view.

This issue is especially problematic on the flow list screen where a click almost anywhere on the screen takes you to a flow view. Even clicks on empty space surrounding the flow causes navigation.

Is there a way to ignore clicks on empty spaces? Alternatively, can the mouse events be turned off?

**Comment by cortesi** [comment]
The click zone is the entirety of the flow widget, which can extend beyond the visible text. I would merge a patch to add a command-line switch to turn off mouse support. It would be a very simple patch, and a great first contribution to the project.
