### ISSUE TITLE
 attrs = self._cert.subject.get_attributes_for_oid

### ISSUE THREAD

**Issue by djallalzoldik** [mitmproxy/mitmproxy#6850]
in the version 10.3.0

there is errors : /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mitmproxy/certs.py:146: UserWarning: Country names should be two characters, but the attribute is 0 characters in length.
  attrs = self._cert.subject.get_attributes_for_oid(x509.NameOID.COMMON_NAME)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mitmproxy/certs.py:153: UserWarning: Country names should be two characters, but the attribute is 0 characters in length.
  attrs = self._cert.subject.get_attributes_for_oid(

**Comment by mhils** [comment]
Can you please provide a reproducer?
