### ISSUE TITLE
Running Mitmproxy on a iMac

### ISSUE THREAD

**Issue by JPS46225** [mitmproxy/mitmproxy#687]
Hi

I've just installed Mitmproxy on my iMac, but can't figure out how to run/execute it

Thanks

**Comment by Kriechi** [comment]
mitmproxy provides three tools - which can be run from the command line
To start mitmproxy itself:
`$ mitmproxy`

To start mitmdump (similar to tcpdump, but for HTTP):
`$ mitmdump`

To start the web application:
`$ mitmweb`
