### ISSUE TITLE
Mitmproxy unusably slow with large responses in reverse mode

### ISSUE THREAD

**Issue by aib** [mitmproxy/mitmproxy#6873]
Thanks for everyone's work on this amazing piece of software!

#### Problem Description
Returning a large (tens of megabytes) response in reverse mode is _very_ slow, getting ~exponentially worse with the body size.

#### Steps to reproduce the behavior:
1. `git clone https://github.com/mitmproxy/mitmproxy.git && cd mitmproxy`
2. `python3 -m venv venv && source venv/bin/activate`
3. `pip install . && pip uninstall -y mitmproxy`
4.
```
cat <<EOF >/tmp/big.py

import mitmproxy

def request(flow):
    flow.response = mitmproxy.http.Response.make(200, "A" * (50 * 1048576))

EOF
```
5. `python -c 'from mitmproxy.tools.main import mitmproxy; mitmproxy(["--mode", "reverse:https://duckduckgo.com", "-s", "/tmp/big.py"])'`
7. `curl https://localhost:8080/big -o /dev/null`

#### System Information
Mitmproxy: 11.0.0.dev (+17, commit 552c320)
Python:    3.10.12
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  Linux-5.15.0-107-generic-x86_64-with-glibc2.35
HEAD is 552c320fadb13a5068f45f34a4f0b30e7430a3a0

Possibly related to https://github.com/mitmproxy/mitmproxy/issues/6301 ?
I will investigate further and try to find the cause.

**Comment by aib** [comment]
Ah! HTTPS/1.0 and 1.1 (as with curl's `--http1.0` and `--http1.1` parameters) respond instantly as well.
So does wget (HTTPS/1.1).

**Comment by aib** [comment]
Profiler (cProfile) output:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1420/1    0.036    0.000   34.349   34.349 {built-in method builtins.exec}
        1    0.000    0.000   34.349   34.349 run.py:1(<module>)
        1    0.000    0.000   33.810   33.810 main.py:134(mitmproxy)
        1    0.000    0.000   33.718   33.718 main.py:45(run)
        1    0.000    0.000   33.718   33.718 runners.py:8(run)
        3    0.000    0.000   33.717   11.239 base_events.py:613(run_until_complete)
        3    0.000    0.000   33.717   11.239 base_events.py:589(run_forever)
      182    0.006    0.000   33.717    0.185 base_events.py:1832(_run_once)
      242    0.001    0.000   30.130    0.125 events.py:78(_run)
      242    0.001    0.000   30.129    0.125 {method 'run' of '_contextvars.Context' objects}
       18    0.003    0.000   29.763    1.654 server.py:376(server_event)
        8    0.005    0.001   29.745    3.718 server.py:355(hook_task)
 1730/836    0.001    0.000   29.735    0.036 layer.py:131(handle_event)
      834    0.000    0.000   29.734    0.036 layer.py:268(handle_event)
      829    0.000    0.000   29.733    0.036 tunnel.py:55(_handle_event)
      825    0.000    0.000   29.730    0.036 tunnel.py:146(event_to_child)
8329/7491    0.002    0.000   29.678    0.004 {built-in method builtins.next}
    66/22    0.000    0.000   29.647    1.348 {method 'send' of 'generator' objects}
       23    0.000    0.000   29.633    1.288 __init__.py:861(_handle_event)
    30/21    0.000    0.000   29.632    1.411 __init__.py:931(event_to_child)
       19    0.000    0.000   29.632    1.560 _http2.py:386(_handle_event)
       17    0.000    0.000   29.632    1.743 _http2.py:120(_handle_event)
   3201/2   29.427    0.009   29.574   14.787 _http_h2.py:55(send_data)
      182    0.002    0.000    3.577    0.020 selectors.py:452(select)
      182    3.574    0.020    3.574    0.020 {method 'poll' of 'select.epoll' objects}
      114    0.002    0.000    1.497    0.013 __init__.py:1(<module>)
[snip]
```

Looking at `send_data`, the culprit seems to be `max_outbound_frame_size`. There's a `DEFAULT_MAX_OUTBOUND_FRAME_SIZE = 65535` somewhere in h2.

**Comment by mhils** [comment]
Do you have some numbers on what constitutes "very slow" for you? In particular, I'd be interested to hear whether it's truly exponential or whether it's linear.

**Comment by aib** [comment]
Yep. In `send_data`, `max_outbound_frame_size` is 16384 and the loop runs some 3000+ times.

Setting it to a large number fixes the slowdown, but of course breaks the protocol. I'm not versed enough in HTTP/2 to know what the proper fix might be. I'll keep investigating...

> Do you have some numbers on what constitutes "very slow" for you? In particular, I'd be interested to hear whether it's truly exponential or whether it's linear.

It's hard to tell the complexity, but here's some rough timing data:

Megabytes seconds
10	0.6
20	1.9
30	4.2
40	11.6
50	31
60	55.8
80	104.1
120	261.3

Looks like it starts out exponential/loglinear but later linear dominates?

**Comment by mhils** [comment]
The following line in your cProfile output sticks out to me:

```
   3201/2   29.427    0.009   29.574   14.787 _http_h2.py:55(send_data)
```

This part here looks indeed a bit suspicious to me:
https://github.com/mitmproxy/mitmproxy/blob/552c320fadb13a5068f45f34a4f0b30e7430a3a0/mitmproxy/proxy/layers/http/_http_h2.py#L71-L76

Repeatedly cutting off a few bits from the front of the buffer means we allocate O(N^2) bytes. Would you like to attempt a fix and see if that helps? 😃

**Comment by aib** [comment]
> This part here looks indeed a bit suspicious to me:

Thinking the same thing!

> Would you like to attempt a fix and see if that helps? 😃

Of course! I'm on this :)

**Comment by aib** [comment]
So it was all about mutating `data`. After the [fix](#6875) , every size tested above takes less than a second. I'm able to test GB-length data! (~4 seconds on this computer)

**Comment by mhils** [comment]
Thank you again! 🍰

**Comment by aib** [comment]
Thank _you_. :confetti_ball:
