### ISSUE TITLE
Transparent mode on Windows Server 2022 (AWS)

### ISSUE THREAD

**Issue by Osherz5** [mitmproxy/mitmproxy#6878]
#### Problem Description
It seems like transparent mode works well on most Windows machines, but I have encountered an issue where it does not work at all with Windows Server 2022.

The tool just shows that it's listening but the log stays empty, and in that state I get time outs when trying to browse any URL that should be intercepted (even for mitm.it)

![image](https://github.com/mitmproxy/mitmproxy/assets/9659763/af1d0394-b6b2-4a83-93aa-6f7120d4ae7f)

In addition, using Wireshark I can see there isn't any traffic going over the local API port 8085 after it's initial writing of the PID (at https://github.com/mitmproxy/mitmproxy/blob/8cf0cca70240b232b15c8b972c2d8fa32d73f964/mitmproxy/platform/windows.py#L69)

After some debugging it looks like the packets are modified and re-injected with pydivert, but then the proxy does not receive them for some reason.

Currently I'm trying to debug the issue further and get some more information about it, I'd love if anyone can shed more light on this.

#### Steps to reproduce the behavior:
1. Set up a Windows Server 2022 Datacenter on AWS
2. Install mitmproxy
3. Set up transparent mode according to the instructions [here](https://docs.mitmproxy.org/stable/howto-transparent/)
4. Start `mitmproxy --mode transparent`

#### System Information
"mitmproxy --version" output:

Mitmproxy: 10.3.0 binary
Python:    3.12.3
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  Windows-2022Server-10.0.20348-SP0

Some info about the machine:
OS Name:                   Microsoft Windows Server 2022 Datacenter
OS Version:                10.0.20348 N/A Build 20348

It's also worth noting that this machine is set up as a Domain Controller and has the server roles: "AD DS" and "DNS" (although it does not seem like a DNS issue)

**Comment by mhils** [comment]
Have you tried running local redirect mode? 

https://mitmproxy.org/posts/local-redirect/windows/

**Comment by Osherz5** [comment]
I was not aware of that mode, but it seems to be working well for my case! It also seems to be capturing all traffic, as opposed to transparent mode which only captured TLS and web traffic.
Would be nice to add it to the "Modes of operation" page in the docs.
Is this mode planned to replace the current transparent mode?

Also thanks for the heads up!
