### ISSUE TITLE
allow_hosts doesnt work

### ISSUE THREAD

**Issue by ItsBean** [mitmproxy/mitmproxy#6899]
#### Problem Description
The `allow_hosts` directive doesn't work, but the `ignore_hosts` directive works effectively.

#### Steps to reproduce the behavior:
this is the config.yaml content:
```
mode: upstream:https://localhost:xxxx
allow_hosts:
- ".*github.com.*"
```
When I visit `github.com`, the mitmweb doesn't show the relevant information.

#### System Information
Mitmproxy: 6.0.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.0.2 15 Mar 2022
Platform:  Linux-6.5.0-35-generic-x86_64-with-glibc2.35

**Comment by Prinzhorn** [comment]
> Mitmproxy: 6.0.2

Please upgrade to the latest version, this is 3.5 years old. Feel free to re-open if the issue persists.
