### ISSUE TITLE
upstream:https failed!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by ItsBean** [mitmproxy/mitmproxy#6900]
#### Problem Description
in two proxy mode, if I set `upstream:http`, it works. If I set `upstream:https`, the web will return bad gateway.
#### Steps to reproduce the behavior:
1. open mitmweb
2. set mode in option to `upstream:https://xxx:xxx`
3. visit any website, it returns `bad gateway error` or `error_proxy_connection`

#### System Information
Mitmproxy: 10.3.0 binary
Python:    3.12.3
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  Linux-6.5.0-35-generic-x86_64-with-glibc2.35

**Comment by mhils** [comment]
Is your upstream proxy an regular HTTP proxy, or is it an HTTP proxy with TLS termination in front (i.e. a "Secure Web Proxy")?

**Comment by mhils** [comment]
I think everything is working as expected here. If `upstream:http://...` works but `upstream:https://...` doesn't, then your proxy server is a normal HTTP proxy and not a Secure Web Proxy.

**Comment by mhils** [comment]
You will still be able to access HTTPS sites through the HTTP proxy. `upstream:http://...` indicates that the proxy protocol between mitmproxy and upstream proxy is plain HTTP, but you can still have HTTPS inside of a CONNECT tunnel (which should happen all automatically).
