### ISSUE TITLE
MacOS reduce disk space

### ISSUE THREAD

**Issue by Shnitzelil** [mitmproxy/mitmproxy#6904]
#### Problem Description
I would like to use mitmdump only on MacOS.
If I remove mitmweb and mitmproxy the OS says that the mitmdump is damaged...

#### Steps to reproduce the behavior:
1. Download the macos tar.gz
2. extract the downloaded file
3. Remove the mitmweb and mitmproxy 
4. Try launch mitmdump

#### System Information
10.3.0

**Comment by emanuele-em** [comment]
First advice is to install mitmproxy via brew:
```brew install --cask mitmproxy```

Second advice is that you don't have to physically delete `mitmproxy` and `mitmweb`, just use `mitmdump`

**Comment by Shnitzelil** [comment]
Thank you for your input.
But, I need only the mitmdump executable... so again...
How can I keep the mitmdump executable and remove the mitmweb and mitmproxy from the downloaded archive?

**Comment by mhils** [comment]
This works, but it's nothing we would ever recommend and something we don't provide support for:

```
> tar xzf mitmproxy-10.3.0-macos-arm64.tar.gz
> cd mitmproxy.app/Contents/MacOS
> ll
total 51744
-rwxr-xr-x@ 1 mhils  primarygroup   8.4M Apr 17 13:32 mitmdump*
-rwxr-xr-x@ 1 mhils  primarygroup   8.4M Apr 17 13:32 mitmproxy*
-rwxr-xr-x@ 1 mhils  primarygroup   8.4M Apr 17 13:32 mitmweb*
> rm mitmproxy mitmweb
> ./mitmdump
[11:10:25.696] HTTP(S) proxy listening at *:8080.
```

**Comment by Shnitzelil** [comment]
I did exactly the same and got message that mitmdump is corrupted.
Maybe it's related to signing/notarize ?
