### ISSUE TITLE
Export tab not working on Safari

### ISSUE THREAD

**Issue by canyesilyurt** [mitmproxy/mitmproxy#6909]
#### Problem Description
Hello, 

When I was using Mitmproxy, I encountered the following problem in Safari; The Export field 

Copy raw request
Copy raw response
Copy raw request and response
Copy as cURL
Copy as HTTPie

None of the options work. I think this is because Safari's Clipboard access is not set properly. 

The console error message that appears directly when I copy: 

![image](https://github.com/mitmproxy/mitmproxy/assets/36952967/58796ae9-2662-427c-9c9e-66d24d0d3a5e)

I don't know exactly how to solve this problem, but I think it can be solved with an update. Thank you, good work.

#### System Information
Mitmproxy: 10.3.0 binary
Python:    3.12.2
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  macOS-14.5-arm64-arm-64bit

**Comment by mhils** [comment]
Likely relevant:

https://github.com/mitmproxy/mitmproxy/blob/fa8b8998d7131e270e0778e820dc37c9b52323a8/web/src/js/contrib/clipboard.tsx#L5
https://stackoverflow.com/questions/73077159/safari-clipboard-read-permission (untested whether that works)

**Comment by canyesilyurt** [comment]
I haven't checked it yet, but maybe this will solve it.

`
export function copyToClipboard(text: string): Promise<void> {
    // Check if navigator.clipboard is available and if the context is secure
    if (navigator.clipboard && window.isSecureContext) {
        return navigator.clipboard.writeText(text).catch(err => {
            console.error('Failed to copy using navigator.clipboard:', err);
            // Fallback to execCommand in case of an error
            return fallbackCopyToClipboard(text);
        });
    } else {
        // Fallback for Safari and other browsers
        return fallbackCopyToClipboard(text);
    }
}

function fallbackCopyToClipboard(text: string): Promise<void> {
    let t = document.createElement("textarea");
    t.value = text;
    t.style.position = "absolute";
    t.style.opacity = "0";
    t.style.left = "-9999px";
    document.body.appendChild(t);

    return new Promise((resolve, reject) => {
        try {
            t.focus();
            t.select();
            if (document.execCommand("copy")) {
                resolve();
            } else {
                reject(new Error("Copy command was unsuccessful"));
            }
        } catch (err) {
            console.error('Fallback: Oops, unable to copy', err);
            reject(err);
        } finally {
            t.remove();
        }
    });
}
`

**Comment by mhils** [comment]
We should probably just make the entire function async and then use
```javascript
export async function writeClipboardText(text: string) {
  try {
    await navigator.clipboard.writeText(text);
  } catch (error) {
    // fallback
  }
}
```

Contributions are welcome!

**Comment by canyesilyurt** [comment]
I downloaded the project to test it, but I don't know how to compile it for macOS. If I can, I will update the project according to whether it works or not.

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/tree/main/web#quick-start has instructions on how to get started. Let me know if you run into any issues!

**Comment by canyesilyurt** [comment]
It is very interesting that I could not solve this problem in safari. I had this idea and I implemented it. In all browsers that support it, the code is copied automatically. For Safari it is shown as a alert.

![image](https://github.com/mitmproxy/mitmproxy/assets/36952967/97f430a3-c511-498f-9136-fc41c35b9353)


```js
export function copyToClipboard(text: string): Promise<void> {
    // navigator clipboard requires a security context such as https
    if (navigator.clipboard && window.isSecureContext) {
        return navigator.clipboard.writeText(text).catch(err => {
            console.error("Navigator clipboard failed:", err);
            return fallbackCopyTextToClipboard(text);
        });
    } else {
        return fallbackCopyTextToClipboard(text);
    }
}

function fallbackCopyTextToClipboard(text: string): Promise<void> {
    return new Promise((resolve, reject) => {
        const textArea = document.createElement("textarea");
        textArea.value = text;
        
        // Ensure textarea is not visible and doesn't scroll the page
        textArea.style.position = "fixed"; // or absolute
        textArea.style.top = "0";
        textArea.style.left = "0";
        textArea.style.width = "2em";
        textArea.style.height = "2em";
        textArea.style.padding = "0";
        textArea.style.border = "none";
        textArea.style.outline = "none";
        textArea.style.boxShadow = "none";
        textArea.style.background = "transparent";
        
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();

        try {
            const successful = document.execCommand('copy');
            if (successful) {
                resolve();
            } else {
                console.error("Fallback copy was unsuccessful");
                alert(text);
                reject(new Error('Fallback copy failed'));
            }
        } catch (err) {
            console.error("Fallback copy error:", err);
            alert(text);
            reject(err);
        } finally {
            textArea.remove();
        }
    });
}
```
