### ISSUE TITLE
zstd decompression failure

### ISSUE THREAD

**Issue by zendai** [mitmproxy/mitmproxy#6914]
Dear Mitm team,

If the response content-encoding is zstd and the response has multiple frames (larger payloads), Response.content will only return the first frame up to 65536 bytes. This is really annoying as it silently "corrupts" the response. It doesn't raise an exception nor changing the max_output_size makes any difference.

The problem is that the python zstd package mitm is using (zstandard version 0.22, latest) has the decompress function which hasn't implemented yet handling multiple frames, which is [documented](https://python-zstandard.readthedocs.io/en/latest/decompressor.html#zstandard.ZstdDecompressor.decompress). They recommend to use stream_reader() instead (their link in the doc is wrong, it points to the Compressor's stream_reader()).

Currently, this is the [code](https://github.com/mitmproxy/mitmproxy/blob/460789b7beadebfdf3a99fd50c3c1e6004bc47be/mitmproxy/net/encoding.py#L178) we're using:

```python
def decode_zstd(content: bytes) -> bytes:
    if not content:
        return b""
    zstd_ctx = zstd.ZstdDecompressor()
    try:
        return zstd_ctx.decompress(content)
    except zstd.ZstdError:
        # If the zstd stream is streamed without a size header,
        # try decoding with a 10MiB output buffer
        return zstd_ctx.decompress(content, max_output_size=10 * 2**20)
```

Proposed solution is to use either pyzstd (works, tested):
```python
pyzstd.decompress(content)
```

or stick with zstandard and use stream_reader() like this, for example (also works, tested):
```python
dctx = zstd.ZstdDecompressor()
return dctx.stream_reader(io.BytesIO(content)).read()
```

Both of these will return the full payload.

I tested this with the following payload (can't attach the payload itself):

```bash
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
    16      0   188.87 KB     971.52 KB  5.144   None  /tmp/1.zstd
```

sendai

**Comment by mhils** [comment]
> or stick with zstandard and use stream_reader() like this, for example (also works, tested):
> 
> ```python
> dctx = zstd.ZstdDecompressor()
> return dctx.stream_reader(io.BytesIO(content)).read()
> ```

This sounds great to me, thanks for looking into things! A PR would be most welcome. Ideally we could have some sort of test payload to make sure we don't regress in the future. :)

**Comment by zendai** [comment]
Thank you @mhils , will raise a PR soon.

**Comment by zendai** [comment]
@mhils raised a PR, also added test which would fail without the current fix (it wouldn't decompress the second frame, while the current fix it does).

For the reference, I'll include here a standalone python test to check this type of errors as well:
```python
#!/usr/bin/env python

import zstandard
import pyzstd
import io

# Create 1024b payload
test_content = 'a' * 1024

# Compress it
test_compressed = zstandard.compress(test_content.encode())  # 1 frame zstd

# Concat compressed frame, it'll result two frames, total size of 2048b payload
two_frames_zstd = test_compressed + test_compressed          # 2 frames zstd

# Save 2 frames payload to verify with zstd binary later
with open('test.zst', 'wb') as f:

    f.write(two_frames_zstd)


# Now, we're going uncompress the 2 frames payload using 3 different methods
dctx = zstandard.ZstdDecompressor()

print('zstandard.decomporess():')
print(len(zstandard.decompress(two_frames_zstd)))

print('pyzstd.decomporess():')
print(len(pyzstd.decompress(two_frames_zstd)))

print('zstandard.ZstdDecompressor().stream_reader()')
print(len(dctx.stream_reader(io.BytesIO(two_frames_zstd)).read()))
```

Currently, this will result the following:
```
zstandard.decomporess():
1024
pyzstd.decomporess():
2048
zstandard.ZstdDecompressor().stream_reader()
2048
```
Showing that zstandard.decomporess() only decompresses the first frame, while the two other alternatives the full payload. (I wrote the unit test based on this) This PR includes the 2nd option as you requested, using zstandard and stream_reader().

Also, running `zstd -l test.zst` will confirm that our compressed payload has two frames and the total uncompressed size of 2048b:
```bash
$ zstd -l test.zst 
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
     2      0     0.04 KB       2.00 KB  53.895   None  test.zst
```

sendai
