### ISSUE TITLE
The CPU of mitmproxy deployed by docker is too high, reaching 100%!

### ISSUE THREAD

**Issue by tl31707chy** [mitmproxy/mitmproxy#6919]
#### Problem Description
I used docker to deploy mitmproxy, and when the client connected to the server, there would be a wx request that kept transmitting data, causing the server CPU to quickly reach 100%.

#### Steps to reproduce the behavior:
Dockerfile
```shell
FROM python:3.10

ENV LANG C.UTF-8

WORKDIR /workspace
RUN mkdir "/workspace/mitmproxy"

COPY main.py /workspace/mitmproxy

EXPOSE 8080
EXPOSE 8081

RUN pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ mitmproxy
```
Execute commands in the container
```shell
mitmweb
```
I have tried ```mitmproxy``` and ```mitmdump``` both have this situation

![20240612233201](https://github.com/mitmproxy/mitmproxy/assets/44464033/0068adc5-6036-4c65-8248-07f07492b737)

**Comment by mhils** [comment]
This looks like you are capturing traffic to mitmweb itself as well, which creates an infinite loop (WS message about new traffic causes another new message, etc.)

**Comment by tl31707chy** [comment]
> This looks like you are capturing traffic to mitmweb itself as well, which creates an infinite loop (WS message about new traffic causes another new message, etc.)

Yes, I have tried mitmproxy/mitmproxy mirror with the same problem, which has been bothering me for a few days.

**Comment by mhils** [comment]
This is a misconfiguration on your end, not a mitmproxy bug. You need to make it so that accessing the web does not go through the proxy.
