### ISSUE TITLE
CONTENT_MISSING is not serialized correctly.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#692]
CONTENT_MISSING is serialized as a `"0"`` str rather than an int. This is due to the conversion caused by https://github.com/mitmproxy/mitmproxy/blob/9b3fe806974b6c6595a2afc01bbf1ee7dd739dfd/libmproxy/protocol/http.py#L99

@cortesi, shall we just make it `None`?

**Comment by Kriechi** [comment]
closed by #1055
