### ISSUE TITLE
mitm.it not being replaced

### ISSUE THREAD

**Issue by ryantheleach** [mitmproxy/mitmproxy#695]
I can't get the intercepted mitm.it page to appear when running mitmproxy -p 8088 and configuring an iPhone to use the machine running mitmproxy.

I've disabled cell data on the iPhone, and I can see the responses are being passed through mitmproxy and can be accepted or rejected. 

So it's clear I have the proxy configured correctly, but mitmproxy is just not showing the magic page for some reason.

**Comment by mhils** [comment]
Works fine for me. Can you see requests to "mitm.it" in the proxy? Which version of mitmproxy are you running?

**Comment by ryantheleach** [comment]
I could see requests to mitm.it in the proxy. to my knowledge it was running 0.13 (only just installed it today using sudo pip install mitmproxy) but I've just nuked the VM I had it in to try again due to messing up my configuration settings for my network. Will reply with more detailed version information once I  update the old VM snapshot I had.

**Comment by ryantheleach** [comment]
Can't replicate, assume it had something to do with either an un-updated VM or botching the install or various combinations of the two.

**Comment by luxflow** [comment]
I encounter similar problem after installing 0.9.2 with `apt-get install mitmproxy`.
But after install 0.13 with `pip install mitmproxy` command. 
I can now see mitm.it

Maybe there is bug in 0.9.2 version which is in ubuntu package repo ..

**Comment by mhils** [comment]
0.9.2. is *really* outdated. You should not use that in any case.
