### ISSUE TITLE
Show More Not working

### ISSUE THREAD

**Issue by Botytec** [mitmproxy/mitmproxy#6951]
I'm trying to look at this WebSocket data in mitmweb, after I click Show More 2 times and the button no longer works. How do I fix this?

**Comment by lups2000** [comment]
Hi, thank you! Could you please be more precise, perhaps with a screenshot? Did you get any errors in the console?

**Comment by Botytec** [comment]
https://streamable.com/yv3f14
here's a video of it happening

**Comment by Prinzhorn** [comment]
Can confirm, second click on button does nothing. No error in JS console.

**Comment by Prinzhorn** [comment]
For some reason it is hardcoded to double the lines once and then that's it:

https://github.com/mitmproxy/mitmproxy/blob/7f7cb28d32cac2752bf00cfdb8343156855425e6/web/src/js/components/FlowView/Messages.tsx#L26-L29

PRs welcome

**Comment by mhils** [comment]
This Math.max should probably have been a Math.min. 🫣

**Comment by lups2000** [comment]
> This Math.max should probably have been a Math.min. 🫣

I quickly tried to change that, and apparently, it's not the only problem 😅 It's weird since, in other cases, the button seems to work fine, while with web socket messages, it doesn't 🤔

**Comment by Prinzhorn** [comment]
> This Math.max should probably have been a Math.min. 🫣

I don't think that's it, with `Math.min()` it would never grow over 1024. I think the `Math.max()` was meant for cases where someone defined a very small `content_view_lines_cutoff` and clicking the button would then only give you a few lines. This makes sure you get _at least_ 1024 when clicking the button.

Why is this line mutating state directly?

https://github.com/mitmproxy/mitmproxy/blob/7f7cb28d32cac2752bf00cfdb8343156855425e6/web/src/js/components/FlowView/Messages.tsx#L81

**Comment by Prinzhorn** [comment]
I've fixed it locally
