### ISSUE TITLE
Downloading OSX binary results in empty file

### ISSUE THREAD

**Issue by bcopos** [mitmproxy/mitmproxy#696]
Just a heads up. I attempted downloading the OSX binary from the [link](https://mitmproxy.org/download/osx-mitmproxy-0.12.0.tar.gz) on the [mitmproxy](https://mitmproxy.org) page and got an empty file. I can try to install via pip or build from source but wanted to let you know.

**Comment by mhils** [comment]
Whoops, thanks for letting us know - apparently we broke this earlier today. I'll have to wait for @cortesi to update the website; in the meantime you can download the binaries here: https://maximilianhils.com/upload/2015-07/osx-mitmproxy-0.12.1.tar.gz

**Comment by bcopos** [comment]
Great, thanks!

Keep up the good work :)

**Comment by mhils** [comment]
Should be fixed now, thanks again.
