### ISSUE TITLE
Upstream Proxy Mode generates certs with bad subjectAltName/CN

### ISSUE THREAD

**Issue by hubert3** [mitmproxy/mitmproxy#697]
Running mitmproxy -p 8081 and making a request to https://pentest.com, the cert that mitmproxy generates has the following properties:

       Subject: CN=www.pentest.com
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DNS:www.pentest.com, DNS:pentest.com, DNS:pentest.com

Cert is accepted by IE8 WinXP since mitmproxy CA cert is trusted.

Running mitmproxy -U "http://localhost:8080" pointing to Burp as an upstream proxy, the cert mitmproxy generates has the following properties:

      Subject: CN=pentest.com
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DNS:localhost

Cert is _rejected_ by IE8 WinXP despite mitmproxy CA cert being trusted.

It seems that IE doesn't like the invalid DNS:localhost subjectAltName despite the main CN being OK.

I can see no reason why 'localhost' should be added as a subjectAltName? This just seems incorrect.

The cert returned by Burp for the upstream proxy case only has the following:

        Subject: C=PortSwigger, O=PortSwigger, OU=PortSwigger CA, CN=pentest.com

With no subjectAltNames.

I would suggest the following changes. When constructing certs on the fly:

1) Don't add subjectAltNames that already match the CN, or preceding subjectAltNames
2) Don't add 'localhost' as a subjectAltName or CN unless this is actually the CN or subjectAltName returned by the upstream server.

**Comment by hubert3** [comment]
When I run

  mitmproxy -p 8081 -U "http://localhost:8080" --no-upstream-cert

And request https://pentest.com with IE8, the generated cert ONLY contains CN=localhost and no mention of pentest.com, which IE8 also rejects.

**Comment by mhils** [comment]
Thanks for the report and sorry for not providing any feedback yet. This'll be fixed by #741.

**Comment by mhils** [comment]
Thanks, this is fixed on master now. :smile:
