### ISSUE TITLE
Some APKs get stuck while using android-unpinner

### ISSUE THREAD

**Issue by lostdusty** [mitmproxy/mitmproxy#7009]
hey :), i'm creating this issue here because on the [`mitmproxy/android-unpinner`](https://github.com/mitmproxy/android-unpinner) repo the issues tab is disabled.

#### Problem Description
Some android apks get stuck when starting (after injecting Frida gadget). The app in particular I'm testing is built using .NET Xamarin. I tried regular MITM without the pinner, but the app refused to make any http requests.

#### Steps to reproduce the behavior:
1. Have a buggy/unsupported(?) apk
2. Run `android-unpinner all -f -v -l /path/to/the/app.apk`
3. Unpinner gets stuck after `Inject Frida gadget...`
![image](https://github.com/mitmproxy/mitmproxy/assets/47502554/07a66e0c-7e5f-45aa-adba-e5977f5ed569)

#### System Information
Mitmproxy: 10.3.1 binary
Python:    3.12.3
OpenSSL:   OpenSSL 3.2.2 4 Jun 2024
Platform:  Windows-10-10.0.19045-SP0
(Installed via scoop)
Package ID: [br.com.henkoti.empresa1.smpay](https://apkpure.net/si-go/br.com.henkoti.empresa1.smpay)
Phone: Xiaomi Redmi 10 (selene; android 13; miui global 14.0.2)

#### Debug (`-vv`) information: 
[debug.log, 113KB](https://github.com/user-attachments/files/16121097/a.log)

**Comment by mhils** [comment]
https://github.com/mitmproxy/android-unpinner/discussions/15#discussion-5362424
