### ISSUE TITLE
Unable to verify response if event-stream

### ISSUE THREAD

**Issue by worwornf** [mitmproxy/mitmproxy#7010]
#### Problem Description
When I redirect a specific url to localhost, if it is an event-stream, it comes out as content missing in mitmproxy response tab.
```
def responseheaders(flow):
    flow.response.stream = flow.response.headers.get('content-type', '').startswith('text/event-stream')
```

#### Steps to reproduce the behavior:
1. setup responseheaders in my script
2. redirect www.example.com --> localhost:8081 in my script

#### System Information
9.0.1

**Comment by Prinzhorn** [comment]
> 9.0.1

Please try with the latest version

**Comment by worwornf** [comment]
same problem in 10.3.1
I resolved it with a temporary workaround.

```
def is_stream(flow):
    return "text/event-stream" in flow.response.headers.get("content-type", "")


def responseheaders(flow):
    def stream_handler(data: bytes):
        if not hasattr(flow, "buffer"):
            flow.buffer = b""
        flow.buffer += data
        flow.response.content = flow.buffer
        return data

    if is_stream(flow):
        flow.response.stream = stream_handler
```

**Comment by worwornf** [comment]
I am running a development server locally. When accessing [www.example.com](http://www.example.com/), I redirect only specific parts to localhost for testing.

**Comment by Prinzhorn** [comment]
> redirect

Via 301? 302? Where's the relevant script?

Please provide **full steps** to reproduce this with every detail. You also didn't answer what you are trying to achieve.

> it comes out as content missing in mitmproxy response tab.

I'm tempted to close this as a dupicate of https://github.com/mitmproxy/mitmproxy/issues/6126, feel free to re-open if you disagree and can provide necessary details.

**Comment by worwornf** [comment]
I am handling the redirect as follows:
```
def request(flow: http.HTTPFlow) -> None:
    if flow.request.url.startswith("https://www.example.com/api"):
        flow.request.host = "localhost"
        flow.request.scheme = "http"
        flow.request.port = 8081
```

This implementation works fine except for http://www.example.com.

For response content-type: text/event-stream:

When I set flow.response.stream = True:
- The stream is processed correctly on the screen.
- The flow response shows "content missing."

When flow.response.stream = False:
- The entire data comes at once on the screen instead of streaming.
- The flow response shows the data.
 
I want the stream to be processed correctly on the screen while the flow response also shows the data.

**Comment by Prinzhorn** [comment]
Can you clarify what "on the screen" means? In the console UI? Maybe you can share a screenshot.

> When I set flow.response.stream = True:
> 
>     * The stream is processed correctly on the screen.
> 
>     * The flow response shows "content missing."
> 
> 
> When flow.response.stream = False:
> 
>     * The entire data comes at once on the screen instead of streaming.
> 
>     * The flow response shows the data.

I think what you're seeing is expected behavior and a combination of #6126 and https://github.com/mitmproxy/mitmproxy/discussions/6996 (@mhils am I correct?)

**Comment by worwornf** [comment]
@Prinzhorn 
For example, in a chat service like ChatGPT where the response is output as a stream, the behavior is similar to cases #6126 and #6996.
