### ISSUE TITLE
CONNECT request does not include Host header

### ISSUE THREAD

**Issue by petsneakers** [mitmproxy/mitmproxy#7019]
#### Problem Description
When proxying https in upstream mode, the CONNECT request initiated by mitmproxy does not include the Host header.  This is in violation of [RFC2616  14.23](https://datatracker.ietf.org/doc/html/rfc2616#section-14.23), which states
```
A client MUST include a Host header field in all HTTP/1.1 request
   messages . If the requested URI does not include an Internet host
   name for the service being requested, then the Host header field MUST
   be given with an empty value. An HTTP/1.1 proxy MUST ensure that any
   request message it forwards does contain an appropriate Host header
   field that identifies the service being requested by the proxy. All
   Internet-based HTTP/1.1 servers MUST respond with a 400 (Bad Request)
   status code to any HTTP/1.1 request message which lacks a Host header
   field.
```
This causes the `CONNECT` request to fail when connecting to upstream proxies that enforce this, such as nginx.

Edit:  updated description to reference the correct RFC.

**Comment by mhils** [comment]
IIRC sending a host header also breaks some proxies. We probably need a setting for that.

**Comment by petsneakers** [comment]
In a perfect world it would be on those proxies to get into compliance . . . not sure where mitmproxy lands in terms of accommodating nonstandard proxies/clients, but I hear ya ;-)

**Comment by mhils** [comment]
The correct place to fix this is here: https://github.com/mitmproxy/mitmproxy/blob/f77327634c9a2796ee67f48d5725802661ccbf31/mitmproxy/proxy/layers/http/_upstream_proxy.py#L64

**Comment by petsneakers** [comment]
@mhils I have a patch but it isn't behind a setting.  If you'd like me to submit a PR, let me know, and if you would prefer I add a setting, what name (suggest: `include_host_header_in_connect`) and what default (suggest `True`)

**Comment by mhils** [comment]
@petsneakers: Thanks! We already have https://docs.mitmproxy.org/stable/concepts-options/#http2_ping_keepalive to adjust HTTP/2 protocol details, so maybe something starting with `http_` to match that. How about `http_connect_with_host_header`? Or `http_connect_send_host_header`? Pick what you like best and we'll go with that! 😃

**Comment by petsneakers** [comment]
PR: https://github.com/mitmproxy/mitmproxy/pull/7021
