### ISSUE TITLE
SSL Error On Windows Only

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#703]
I'm running "mitmdump -T --host" (v0.13) on Windows 10. HTTPS/SSL works fine with Android and iOS devices after the certificate is accepted via mitm.it. However, I'm unable to get HTTPS/SSL working on the same Windows 10 system or even on remote Windows 10 systems connecting in. I don't recall running into this issue with mitmdump v0.12 and Windows 8.1. Is something broken in v0.13 or Windows 10?

**Comment by mhils** [comment]
What kind of connections are you intercepting? 0.13 works fine for me on Win8.1, we ideally need something reproducible.

**Comment by BSalita** [comment]
I see that https is working, but not always. I'll have to look into it more. I think what may be happening is that mitmdump (v0.13, Windows 10) is crashing or getting zombied. All this is preliminary so don't be concerned. I'll try to get back in a few days.

**Comment by mhils** [comment]
Win10 works fine for me. We need a reproducible test case please.
