### ISSUE TITLE
Cannot modify headers on requests with bodies (POST etc) when stream_large_bodies is enabled

### ISSUE THREAD

**Issue by austin-autify** [mitmproxy/mitmproxy#7030]
#### Problem Description
When `stream_large_bodies` is set to any value above 0, any flow that modifies headers on requests that have bodies will stop working. This is unexpected because while the documentation and code [warns about this](https://github.com/mitmproxy/mitmproxy/blob/460789b7beadebfdf3a99fd50c3c1e6004bc47be/mitmproxy/addons/modifybody.py#L51-L52) when it comes to modifying **bodies** (as expected), it does not warn that modifying **headers** won't work.

In my case, I am adding a header for basic auth and had `stream_large_bodies=0` because I don't need to modify any request or response bodies and this is much better for performance on any page with video, etc. However, I noticed that all POST requests (with a body) stopped working because they were missing the auth header, even though GET requests (without a body) still had it.

#### Steps to reproduce the behavior:
1. Set `stream_large_bodies=0`
2. Add a flow like `modify_headers=/~d ^example.com$/authorization/Basic credsgohere`
3. Send both a GET and a POST (with a body) request through the proxy
4. See that the GET request has the header added, the POST request does not

#### System Information
```
Mitmproxy: 10.3.0 binary
Python:    3.12.3
OpenSSL:   OpenSSL 3.2.1 30 Jan 2024
Platform:  Linux-6.1.0-21-amd64-x86_64-with-glibc2.36
```

**Comment by mhils** [comment]
I think this is a bug of the [ModifyHeaders](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/addons/modifyheaders.py) addon, not a general limitation. We probably should be using the `requestheaders` hook there, not the `request` hook (and the same for responses).
