### ISSUE TITLE
Is support x86 systems?

### ISSUE THREAD

**Issue by linuxlin365** [mitmproxy/mitmproxy#7034]
#### Problem Description

I installed the python 312 x86 environment and compiled mitmproxy, and the following message appears

![image](https://github.com/user-attachments/assets/5f323592-413d-438c-b396-00a30c21632d)

mitmproxy Is support x86 systems?

#### Steps to reproduce the behavior:
1.  python -m venv venv
2.  pip install -e .
3.  build error

**Comment by mhils** [comment]
I don't think there's a fundamental reason why it wouldn't work, but we don't officially support it.

**Comment by mhils** [comment]
The error message you posted has instructions on how to get past it. :)
