### ISSUE TITLE
pip command for previous release?

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#704]
I'm trying to rule in/out whether an issue is particular to a release. I understand the pip command for the current release is "pip install mitmproxy", which downloads and installs the current release.

What is the pip command to install a previous version of mitmproxy?

What is the pip command to install from downloaded source code?

**Comment by mhils** [comment]
https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip
https://github.com/mitmproxy/mitmproxy#hacking
