### ISSUE TITLE
unknown or unsupported macOS version: :dunno

### ISSUE THREAD

**Issue by Kingson** [mitmproxy/mitmproxy#7040]
#### Problem Description
unknown or unsupported macOS version: :dunno

#### Steps to reproduce the behavior:
1.Run brew install mitmproxy 
2. prompt  ‘Error: mitmproxy: unknown or unsupported macOS version: :dunno’

#### System Information

![image](https://github.com/user-attachments/assets/64632c41-4af3-42f3-bddb-de4b77a51aae)

**Comment by Prinzhorn** [comment]
1. What macOS version _are_ you using?
2. Make sure to upgrade to the latest homebrew
