### ISSUE TITLE
When downloading large files, the CPU is fully occupied, resulting in slow download speed

### ISSUE THREAD

**Issue by liuhao111418** [mitmproxy/mitmproxy#7075]
When downloading large files, the CPU is fully occupied, resulting in slow download speed

**Comment by mhils** [comment]
Please use the bug report template from https://github.com/mitmproxy/mitmproxy/issues/new?assignees=&labels=kind%2Ftriage&projects=&template=bug_report.md&title= and edit your post accordingly.
