### ISSUE TITLE
Download large file with CPU full

### ISSUE THREAD

**Issue by liuhao111418** [mitmproxy/mitmproxy#7076]
#### Problem Description
When downloading large files, the CPU is fully occupied, causing the download speed to slow down

#### Steps to reproduce the behavior:
1. Enable mitmproxy
2. Download large files using browser links
3. The quad core CPU machine only uses one CPU and this CPU is fully occupied, resulting in slower download speeds

#### System Information
Mitmproxy: 10.3.1
Python:    3.12.3
OpenSSL:   OpenSSL 3.2.2 4 Jun 2024
Platform:  Windows-10-10.0.19044-SP0

**Comment by mhils** [comment]
The changelog for 10.4 explicitly lists improvements in that regard: https://github.com/mitmproxy/mitmproxy/blob/main/CHANGELOG.md#25-july-2024-mitmproxy-1040
