### ISSUE TITLE
mitmweb: command line switches are ignored

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#708]
When I use "mitmweb -T --host" (v0.13, Windows 10), no domain names ever appear, just ip numbers. Is that expected? OTOH "mitmdump -T --host" works fine.

**Comment by mhils** [comment]
Thanks for the report. `mitmweb` is still not an official features and many command line switches are not implemented.

**Comment by BSalita** [comment]
Once you nail down the software, it will be a totally awesome tool. Bravo! 


     On Tuesday, August 4, 2015 4:07 PM, Maximilian Hils <notifications@github.com> wrote:
   

 Thanks for the report. mitmweb is still not an official features and many command line switches are not implemented.—

**Comment by cortesi** [comment]
mitmweb should now handle all the common mitmproxy options.

**Comment by BSalita** [comment]
Fantastic!
