### ISSUE TITLE
mitmweb Not Working with Microsoft Edge Browser

### ISSUE THREAD

**Issue by BSalita** [mitmproxy/mitmproxy#709]
Using  "mitmweb -T --host" (v0.13, Windows 10) on Microsoft Edge browser, the page is always rendered completely blank. Chrome and FIrefox work fine.

**Comment by mhils** [comment]
Thanks for the report. Does this apply to both HTTP and HTTPS?

**Comment by BSalita** [comment]
The screen is complete blank i.e. nothing is rendered, not even UI boxes and such. 


     On Tuesday, August 4, 2015 4:07 PM, Maximilian Hils <notifications@github.com> wrote:
   

 Thanks for the report. Does this apply to both HTTP and HTTPS?—

**Comment by mhils** [comment]
mitmproxy + Edge works fine for me. If this issue still occurs, please provide us with a reproducible test case.
