### ISSUE TITLE
ssl_verify_upstream_trusted_ca replaces default certificates

### ISSUE THREAD

**Issue by ih8Gh** [mitmproxy/mitmproxy#7096]
#### Problem Description
The ssl_verify_upstream_trusted_ca option, instead of adding a new trusted certificate, makes mitmproxy only trust that certificate, breaking any sites not using it.

#### Steps to reproduce the behavior:
1. mitmproxy --set ssl_verify_upstream_trusted_ca=path/to/cert
2. mitmproxy does not trust system certificates

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 10.4.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.3.1 4 Jun 2024
Platform:  Linux-5.15.0-113-generic-x86_64-with-glibc2.35

**Comment by mhils** [comment]
This is intended behavior, and matches the behavior of other tools (e.g. cURL's `--cacert`).
