### ISSUE TITLE
UnicodeDecodeError when dumping with read_dumpfile

### ISSUE THREAD

**Issue by FreeArtMan** [mitmproxy/mitmproxy#710]
Used example script  flowwriter.py to collect some data
Then tryed to run it with example script read_dumpfile 

getting :
```
...
        "code": 200, 
        "content": Traceback (most recent call last):
  File "read_dumpfile", line 16, in <module>
    json.dump(f.get_state(), sys.stdout, indent=4)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
...
```

Example file that was collected with flowwrite.py is attached. I filltered out one http response that causes this bug

 
![logfile](https://cloud.githubusercontent.com/assets/214155/9064656/7a4207f0-3ac5-11e5-8599-5536580ae3fc.png)

>md5sum logfile
fc0285d300cccc88b757e4ff70bf128b  logfile

Tested with mitmproxy commit adf2877020c563fa9dc9a4df26bfd8b243e8e41a

**Comment by cortesi** [comment]
Hi there,

Could you please test with a recent checkout of mitmproxy? Reading the dumpfile you attached works with no error in the latest master.

If the issue is still there, please re-open and specify your platform, mitmproxy version and any other details that could help us reproduce.


Aldo

**Comment by FreeArtMan** [comment]
Hi, ofcourse it works without "no error". There is just try/catch used. Problem was I think becouse 
if you have some binary file like image then it contains non printable characters. While json.dump couldnt
dump it it stil valid file/packet. This error happened with files that have in headers Contet-Type specified compression format and in content compressed content. Probably now some one will expirience non-dump valid packets.

**Comment by cortesi** [comment]
Hi Arthur. Further to our email just now, base64 encoding to make binary data JSON-safe is the way to go. Let's get a working test case up and running here, so we can see exactly what we're dealing with. Using the test dump you provided, and the example script in the repo, I don't see the error. The output is as expected, and an error is not hidden by a try/catch block.

**Comment by FreeArtMan** [comment]
How yo provide more info that you may need to debug here i collected what I think could help you need:

````
mitmproxy commit 9286f5b5b4d9483d0d8e7fa0fb4c27961cd236be
Python 2.7.10
3a38ff399b634c4fa6393cc8a4df9db1  log.txt
```

```
git branch -a
* master
  remotes/origin/0.10
  remotes/origin/0.8
  remotes/origin/HEAD -> origin/master
  remotes/origin/conn-management
  remotes/origin/integrate_honeyproxy
  remotes/origin/master
  remotes/origin/mitmconvert
  remotes/origin/mouse
  remotes/origin/multiple_views
  remotes/origin/proxy-refactor
  remotes/origin/proxy-refactor-cb

export LANG=en_US.UTF-8
python2 ./read_dumpfile log.txt


...    
    "error": null, 
    "id": "fcb5ecbf-0503-4a9f-8a87-adb9d9889ffd", 
    "type": "http", 
    "response": {
        "code": 200, 
        "content": Traceback (most recent call last):
  File "./read_dumpfile", line 18, in <module>
    json.dump( state, sys.stdout, indent=4, ensure_ascii=True)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Here is file with 3 packets that fails with that error.
![log](https://cloud.githubusercontent.com/assets/214155/9325494/a5e054c8-458a-11e5-8106-75f2455e23da.png)

Could it be helpfull to collect much more data?

**Comment by mhils** [comment]
I think we should just change the example script to use pprint - JSON does not support binary contents, so we should leave an explanatory comment and use something else.
