### ISSUE TITLE
from Crypto.Cipher import AES ModuleNotFoundError: No module named 'Crypto'.

### ISSUE THREAD

**Issue by HuanYues** [mitmproxy/mitmproxy#7101]
I wrote a Python script that always reports errors when using the library "Crypto". However, I have installed "Python \ Python 38 \ Lib \ site packages \ Crypto", which does not report errors when writing code normally. But when using the tool mitmdump.exe to start the Python script, it will report an error: mitmdump.exe - p 7070- s \downstream.py  --mode upstream: http://127.0.0.1:8080  --ssl-insecure
[19:27:26.705] Loading script . \downstream.py
[19:27:26.720] error in script . \downstream.py
Traceback (most recent call last):
File ". \downstream.py", line 2, in <module>
from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'.
Note that mitmproxy's binaries include their own Python environment. If your addon requires the installation of additional dependencies, please install mitmproxy from PyPI ( https://docs.mitmproxy.org/stable/overview-installation/#installation -from-the-python-package-index-pypi).
[19:27:26.720] HTTP(S) proxy (upstream mode) listening at *:7070.
Error logged during startup, exiting...

**Comment by mhils** [comment]
Note that mitmproxy's binaries include their own Python environment. If your addon requires the installation of additional dependencies, please install mitmproxy from PyPI ( https://docs.mitmproxy.org/stable/overview-installation/#installation-from-the-python-package-index-pypi).
