### ISSUE TITLE
tcp-simple.py example still working? How to intercept raw TCP traffic

### ISSUE THREAD

**Issue by osown** [mitmproxy/mitmproxy#7103]
#### Problem Description
Is the tcp-simple.py example still correct? I would expect the tcp_message function to be called when sending stuff to mitmdump?
Or did I miss something? Why does it say HTTP(S) proxy listening at ... when I just want to intercept raw TCP

```
mitmdump --tcp-hosts ".*" -s tcp-simple.py --listen-host 10.0.3.100 --listen-port 8083
[17:17:51.247] Loading script tcp-simple.py
[17:17:51.247] HTTP(S) proxy listening at 10.0.3.100:8083.
[17:17:54.905][192.168.13.6:64255] client connect
[17:18:04.904][192.168.13.6:64255] Client closed connection before completing request headers: b'<asd>\n'
[17:18:04.905][192.168.13.6:64255] client disconnect
```
#### Steps to reproduce the behavior:
1.  python -m venv venv
2.  source venv/bin/activate
3.  pip install mitmproxy
4. Take https://docs.mitmproxy.org/stable/addons-examples/#tcp-simple example
5. mitmdump --tcp-hosts ".*" -s tcp-simple.py --listen-host 10.0.3.100 --listen-port 8083
6. nc 10.0.3.100 8083 and type in some stuff, press CTRL-D, CTRL-C

#### System Information
Mitmproxy: 10.4.2
Python:    3.12.0
OpenSSL:   OpenSSL 3.3.1 4 Jun 2024
Platform:  Linux-6.8.11-amd64-x86_64-with-glibc2.38

**Comment by mhils** [comment]
You're running mitmproxy in regular HTTP proxy mode. As a regular HTTP proxy, mitmproxy expects an `HTTP CONNECT` first so that it knows where to forward data to (https://docs.mitmproxy.org/stable/concepts-modes/).

Simple example with a reverse proxy instead:
```
mitmdump -s examples/addons/tcp-simple.py --mode reverse:tcp://towel.blinkenlights.nl:23
```
and then
```
nc localhost:8080
```
