### ISSUE TITLE
clientconnect loop

### ISSUE THREAD

**Issue by n0way0ut** [mitmproxy/mitmproxy#711]
hi,

I am running the mitpdump in trasparent mode and when I start it on my gateway it prints a lot of:
127.0.0.1:35358: clientconnect
127.0.0.1:35342: clientdisconnect
127.0.0.1:35359: clientconnect
127.0.0.1:35345: clientdisconnect
127.0.0.1:35360: clientconnect
127.0.0.1:35347: clientdisconnect
127.0.0.1:35361: clientconnect
127.0.0.1:35350: clientdisconnect
127.0.0.1:35352: clientdisconnect
127.0.0.1:35362: clientconnect
127.0.0.1:35351: clientdisconnect

on sequential port, I never seen this behaviour, what can be?

**Comment by mhils** [comment]
Outgoing ports are assigned sequentially by most Unix systems - this is normal behaviour. What you're seeing is probably a non-HTTP client.

**Comment by n0way0ut** [comment]
maybe the problem is another, I have the same on SSLsplit too. I need to filter out the ip where proxy is running from iptables, because the proxy request itself passes through PREROUTING rule and it goes in loop.


if you confirm that the problem is not this, mitmproxy doesn't support non-HTTP client, so is it possible to skip these connect directly?

**Comment by mhils** [comment]
> maybe the problem is another, I have the same on SSLsplit too. I need to filter out the ip where proxy is running from iptables, because the proxy request itself passes through PREROUTING rule and it goes in loop.

That's of course something you have to avoid as well. Not sure what exactly the cause for the issue you're seeing is, so fix that first.
