### ISSUE TITLE
Endless loop when processing very large tnetstring 

### ISSUE THREAD

**Issue by mik1904** [mitmproxy/mitmproxy#7120]
#### Problem Description

The loading of flows stored in mitmdump capture files can get stuck endlessly (manually terminated after 10+ hours). This happens for capture files that contain very large `tnetstring` for dict and/or list objects. The issue originates from the recursive slicing performed in the `pop` function while parsing (`parse` function) a tnetstring using the [tnetstring](https://github.com/mitmproxy/mitmproxy/blob/6bb536e0ff9e4abe940cdd0f17ee76851e38bb2f/mitmproxy/io/tnetstring.py#L229) module. 

I solved this issue by using `memoryview` to represent the data to be parsed in the `tnetstring` module. In the following archive
[tnet.zip](https://github.com/user-attachments/files/16661981/tnet.zip), you can find the modified tnetstring module and code  + data to test it.

Env:
- python 3.10.13
- mitmproxy 10.2.4

#### Steps to reproduce the behavior:
1. Unzip [tnet.zip](https://github.com/user-attachments/files/16661981/tnet.zip)
2. run `python test_tnetstring.py`

The test script will try to parse a large tnetstring (100+ MB), stored in the file part of the .zip, using both the original and the modified tnetstring module. On my machine the modified code ends in ~ 7 seconds while the original runs for hours (I have never seen the end of it). To avoid waiting forever, the script kills the execution of the original code after a timeout 120 seconds.
 
In the `test_tnetstring.py` script there is also code to check that the result produced by the original code and the modified one are the same. The call to this test function is commented out; you can specify the path of a not-problematic mitmdump capture and run it.

#### System Information
- python 3.10.13
- mitmproxy 10.2.4

**Comment by mhils** [comment]
Thank you for investigating this! Could you please open a PR with your changes? Thanks!
