### ISSUE TITLE
mitmproxy doesn't exit without connection to web UI

### ISSUE THREAD

**Issue by catap** [mitmproxy/mitmproxy#7128]
#### Problem Description
Mitmproxy doesn't exit on Ctrl-C inside commond line without connection to web UI

#### Steps to reproduce the behavior:
1. Run `mitmweb`
2. Close tab or window which was open to visit http://127.0.0.1:8081/
3. Press `Ctrl - C` in terminal
4. Nothing happens
5. Open http://127.0.0.1:8081/ in browser
6. It exists

#### System Information
```
Mitmproxy: 10.4.2
Python:    3.11.9
OpenSSL:   LibreSSL 3.9.0
Platform:  OpenBSD-7.6-amd64-64bit-ELF
```

**Comment by mhils** [comment]
This issue is likely specific to (Open)BSD. At least I can't reproduce it on Linux and macOS.

**Comment by catap** [comment]
@mhils quite probably. Special that I had worked on port for OpenBSD for mitmproxy for a few moths, and this was imported last week.

Any suggestion how can I debug it future to provide some useful traces?

**Comment by mhils** [comment]
Here's our SIGTERM handling:
https://github.com/mitmproxy/mitmproxy/blob/332f222994deb27bb0ab68618b23f270b3bdfe2d/mitmproxy/tools/main.py#L116-L128

I would assume the handler is never called?

**Comment by Prinzhorn** [comment]
What happens when you `--no-web-open-browser`? My guess is that's a focus issue with the terminal and you need to manually click into it or seomthing.

**Comment by catap** [comment]
@Prinzhorn when I run `mitmweb --no-web-open-browser` it indeed doesn't open web browser, and it ignores `Ctrl - C`. But if I go to http://127.0.0.1:8081/ after I had pressed `C-c`, it exists. Without visiting the web UI it stucks.

@mhils yeah, signal never fire the callback. But if I use `loop.add_signal_handler` it works like a charm.

**Comment by mhils** [comment]
Thanks! Do you want to send a patch that tries `loop.add_signal_handler` first and then falls back to `signal.signal` on exception? :)
