### ISSUE TITLE
When I launch the dump program using Python, I am unable to set the validate_inbound_headers parameter.

### ISSUE THREAD

**Issue by mhpsy** [mitmproxy/mitmproxy#7133]
#### Problem Description

    raise KeyError("Unknown options: %s" % ", ".join(u.keys()))
KeyError: 'Unknown options: validate_inbound_headers, stream_large_bodies'

> Where should I set this parameter?

#### Steps to reproduce the behavior:
```python
    opts = Options(
        mode=["upstream:http://127.0.0.1:7890"],
        validate_inbound_headers=False,
        stream_large_bodies="32k"
    )
    
    async def create_master():
        master = DumpMaster(opts, with_termlog=False)
        
        master.addons.add(*addons)
        await master.run()
    
    loop = asyncio.get_event_loop()
    if loop.is_running():
        asyncio.create_task(create_master())
    else:
        loop.run_until_complete(create_master())
```

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 10.4.2
Python:    3.11.4
OpenSSL:   OpenSSL 3.3.1 4 Jun 2024
Platform:  Windows-10-10.0.22631-SP0

**Comment by mhils** [comment]
https://stackoverflow.com/a/68661172/934719
