### ISSUE TITLE
Errors when IPv6 is disabled

### ISSUE THREAD

**Issue by ghost** [mitmproxy/mitmproxy#7137]
#### Problem Description
I have IPv6 disabled globally in the kernel with ipv6.disable=1, and on every request, I get this error in the events log (but mitmproxy still works):
info: [16:07:51.221][127.0.0.1:57196] error establishing server connection:
Multiple exceptions: [Errno 111] Connect call failed ('0.0.0.0', 443), [Errno
97] Address family not supported by protocol

The error does not occur when IPv6 is enabled.

#### Steps to reproduce the behavior:
1. Run `mitmproxy`
2. Press `E`
3. Go to a website

#### System Information
Paste the output of "mitmproxy --version" here.
Mitmproxy: 10.4.2
Python:    3.10.12
OpenSSL:   OpenSSL 3.3.1 4 Jun 2024
Platform:  Linux-5.15.0-113-generic-x86_64-with-glibc2.35

**Comment by mhils** [comment]
This needs better reproduction steps, e.g. with a docker container. I can't repro this at the moment.
