### ISSUE TITLE
error installing mitmproxy using easy_install

### ISSUE THREAD

**Issue by karneaud** [mitmproxy/mitmproxy#715]
pHad problems installing mitmproxy on my OSX Yosemite with python 2.7 using easy_install and got this error

> Running cryptography-0.9.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rauMRA/cryptography-0.9.3/egg-dist-tmp-zlKfoq
error: Not a directory

installing using pip gives me

> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-qjWm6R/cffi

What does that mean?

**Comment by mhils** [comment]
https://cryptography.readthedocs.org/en/stable/installation/

**Comment by karneaud** [comment]
Sorry,

No go! keep getting the latter error

> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-qjWm6R/cffi

**Comment by karneaud** [comment]
Tried using `easy_install` to install the cryptography and got this

````
Running cryptography-0.9.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rPsfk2/cryptography-0.9.3/egg-dist-tmp-4IcAjD
error: Not a directory
````
