### ISSUE TITLE
Document possible options for `web_columns`

### ISSUE THREAD

**Issue by nikhilweee** [mitmproxy/mitmproxy#7152]
#### Problem Description

The current [documentation](https://github.com/mitmproxy/mitmproxy/blob/a5b5963d8ca06ba70462082eed5ab595f14d8d56/mitmproxy/tools/web/webaddons.py#L17) about `web_columns` only lists the defaults. 

![image](https://github.com/user-attachments/assets/31f95d0f-cf73-4889-963a-48aa9cff5f49)

I recently discovered that there are [other columns](https://github.com/mitmproxy/mitmproxy/blob/a5b5963d8ca06ba70462082eed5ab595f14d8d56/web/src/js/components/FlowTable/FlowColumns.tsx#L196-L209) as well, and it would be great to include them as "possible options"

#### Proposal
Add a list of [possible columns](https://github.com/mitmproxy/mitmproxy/blob/a5b5963d8ca06ba70462082eed5ab595f14d8d56/web/src/js/components/FlowTable/FlowColumns.tsx#L196-L209).

#### Alternatives
Don't document additional columns.

**Comment by mhils** [comment]
Yes, 💯 . We should add a script in https://github.com/mitmproxy/mitmproxy/tree/main/web/gen that generates a Python file with all column names. We can then use that for the option description. Contributions welcome!
