### ISSUE TITLE
mitmproxy user in Docker container assigned UID/GID 0 by default

### ISSUE THREAD

**Issue by dr-yd** [mitmproxy/mitmproxy#7156]
#### Problem Description
By default, the `mitmproxy` process and user run as UID/GID 0. This seems unintentional and like an implementation artifact.

#### Steps to reproduce the behavior:
1. `docker run --rm -it --entrypoint /bin/bash mitmproxy/mitmproxy -c "ls -la /home/mitmproxy"`
3. Observe that `.mitmproxy` is owned by `root:root`
4. Observe that the entrypoint changes the UID/GID of `mitmproxy` to the UID/GID of this directory

#### Note
This is caused by the `VOLUME` declaration in the Dockerfile - it creates the directory with the current `USER` which is `root`. Subsequently chowning it to `mitmproxy` would fix this.

#### System Information
Mitmproxy: 10.4.2
Python:    3.11.9
OpenSSL:   OpenSSL 3.3.1 4 Jun 2024
Platform:  Linux-6.10.0-linuxkit-aarch64-with-glibc2.31

**Comment by mhils** [comment]
Thanks for pointing this out! Would you mind sending a PR with a fix? 😃

**Comment by dr-yd** [comment]
Oh, sorry for the lack of feedback, looks like the previous notification passed by me. Thanks @jasonstultz for making the change!
