### ISSUE TITLE
Bad HTTP request line for IPv6 address in CONNECT request

### ISSUE THREAD

**Issue by jpstotz** [mitmproxy/mitmproxy#7176]
#### Problem Description
When intercepting traffic of on iPhone running iOS 17.6 I am getting errors like `Bad HTTP request line: b'CONNECT 2a01:b740:a30:f000::199:443 HTTP/1.1'` 

The requests seem to come from the OS itself. When connecting to the mentioned IPv6 address the server certificate mentions server names like `images.apple.com`.

#### System Information
Mitmproxy: 10.4.2
Python:    3.11.9

**Comment by mhils** [comment]
I'm tempted to say this is a bug in the HTTP client - `2a01:b740:a30:f000::199:443` should really be `[2a01:b740:a30:f000::199]:443`. It's a bit more nuanced here as the authority _must_ have a port in CONNECT requests, so we could conceivably work around it. The relevant code is here: https://github.com/mitmproxy/mitmproxy/blob/65db82f4cf0c294a3e9de103c4789ba4b9b19a41/mitmproxy/net/http/http1/read.py#L233-L237

Note that we can't just blindly change `parse_authority` as that's used in other contexts as well where a port is not mandatory.

**Comment by jpstotz** [comment]
Thanks for clarifying that this is a mistake on Apple side. 

I am not sure which iPhone service causes those requests. I noticed that those error only occurs directly after the iPhone has been rebooted. And it seems to be only one component or service that uses this defect http client as I see a lot of other CONNECT requests also with IPv6 addresses that are correctly formatted.
