### ISSUE TITLE
ImportError GLIBC_2.33 round two

### ISSUE THREAD

**Issue by ckpt-martin** [mitmproxy/mitmproxy#7209]
#### Problem Description
I have run into the same issue as:
https://github.com/mitmproxy/mitmproxy/issues/6831

But, the proposed root cause (wrong python version) is not the issue.
I am also trying to run Mitmproxy on a Raspberry Pi Zero W with Rasbpian Bullseye. As Raspian Bullseye comes with python 3.9 it typically would no longer be supported. But, I upgraded my python version with pyenv to 3.10.15 and I am still getting this GLIBC version error stating it is required by mitmproxy_rs.abi3.so. All of the release notes for Mitmproxy only state a minimum GLIBC version of 2.31, which is the version on the Pi zero with Rasbpian Bullseye. Since GLIBC affects the entire system it is not possible to upgrade from 2.31 to 2.33.

Any ideas why the requirement of GLIBC 2.33 is never mentioned in the release notes and what specific Mitmproxy version would not require 2.33 and would run on 2.31? I could tell pipx to install that specific version instead of the newest.

#### Steps to reproduce the behavior:
1.  Install Raspbain Bullseye on Pi Zero W
2. Upgrade Python to 3.10+
3. Install mitmproxy
4. Run any Mitmproxy binary

#### System Information
"mitmproxy --version" doesn't run and also outputs the same ImportError.
But here's the output from the install that shows the Mitmproxy and Python version.

> admin@viessmann-gw:~ $ pipx install mitmproxy
>   installed package mitmproxy 10.4.2, installed using Python 3.10.15
>   These apps are now globally available
>     - mitmdump
>     - mitmproxy
>     - mitmweb
> done! ✨ 🌟 ✨

Python version from prompt:

> admin@viessmann-gw:~ $ python -V
> Python 3.10.15

GLIBC Version:

> admin@viessmann-gw:~ $ ldd --version
> ldd (Debian GLIBC 2.31-13+rpt2+rpi1+deb11u11) 2.31
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.

Traceback from Mitmproxy:

> admin@viessmann-gw:~ $ mitmproxy --version
> Traceback (most recent call last):
>   File "/home/admin/.local/bin/mitmproxy", line 5, in <module>
>     from mitmproxy.tools.main import mitmproxy
>   File "/home/admin/.local/share/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/tools/main.py", line 15, in <module>
>     from mitmproxy import master
>   File "/home/admin/.local/share/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/master.py", line 5, in <module>
>     from .addons import termlog
>   File "/home/admin/.local/share/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/addons/__init__.py", line 3, in <module>
>     from mitmproxy.addons import block
>   File "/home/admin/.local/share/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/addons/block.py", line 5, in <module>
>     from mitmproxy.proxy import mode_specs
>   File "/home/admin/.local/share/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy/proxy/mode_specs.py", line 34, in <module>
>     import mitmproxy_rs
>   File "/home/admin/.local/share/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy_rs/__init__.py", line 1, in <module>
>     from .mitmproxy_rs import *
> ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/admin/.local/share/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so)

**Comment by ckpt-martin** [comment]
After looking into the mitmproxy_rs project, I notice that is basically for the Wireguard and Local Redirect Modes, both of which I do not need on my Raspberry Pi. So, any way to install mitmproxy without requiring mitmproxy_rs?
My last resort could potentially be to just install a version of mitmproxy prior to the introduction of these two redirection modes. As far as I can tell, that would be version 8 since WireGuard Mode was introduced in v9.
That's pretty old and missing a lot of functionality I suppose. So, any way of telling which version of mitmproxy_rs doesn't require GLIBC 2.33 and would work with 2.31?

**Comment by mhils** [comment]
> So, any way to install mitmproxy without requiring mitmproxy_rs?

No, mitmproxy_rs is a hard dependency. It's heavily integrated already (e.g., everything UDP-based depends on it), and will be more heavily integrated going forward.

> ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by /home/admin/.local/share/pipx/venvs/mitmproxy/lib/python3.10/site-packages/mitmproxy_rs/mitmproxy_rs.abi3.so)

I'm curious why this is happening. Supposedly we should build with `manylinux2024` compatibility [here](https://github.com/mitmproxy/mitmproxy_rs/blob/15731b5e466e37da4aa164e30c1d98072c1c5b46/.github/workflows/ci.yml#L68C35-L68C48), which would be glibc 2.17. Something in that process clearly is not working.

**Comment by mhils** [comment]
Hm - this here - from https://pypi.org/project/mitmproxy-rs/0.6.3/#files - looks correct:

```shell
$ objdump -p mitmproxy_rs.abi3.so

mitmproxy_rs.abi3.so:     file format elf64-little

[...]

Version References:
  required from libm.so.6:
    0x06969197 0x00 04 GLIBC_2.17
  required from libpthread.so.0:
    0x06969197 0x00 03 GLIBC_2.17
  required from libc.so.6:
    0x06969197 0x00 02 GLIBC_2.17
  required from libdl.so.2:
    0x06969197 0x00 05 GLIBC_2.17
  required from ld-linux-aarch64.so.1:
    0x06969197 0x00 06 GLIBC_2.17
```

**Comment by ckpt-martin** [comment]
OK, so the issue is actually that mitmproxy_rs requires the system to be 64bit. Raspberry pi zero W (not v2) is 32bit only. 
I had read something about this in another thread, but the wording did not sound like mitmproxy_rs is a requirement.
Can you say what version of mitmproxy introduced mitmproxy_rs? Maybe a very early version prior to this requirement could still accomplish what I want. I basically only want to decipher a specific API communication that is of course over HTTPS. I have confirmed that the app does not do certificate pinning and will work if the client trusts the certificate of the proxy. So, there may be a chance that a very early version of mitmproxy still fits my needs.
Thanks.

**Comment by mhils** [comment]
The last release without Rust should be mitmproxy 8 I think. Happy for you
if that works for you, just for the record it's unsupported otherwise. :)

My general Raspi recommendation would be to use our arm docker images,
although the Zero in your case is armv6 only, which won't work AFAIK.

**Comment by ckpt-martin** [comment]
OK, I'll try 8.1.1. If that still doesn't work then I'll have to try to do this via a different system hosted separate to the pi zero. Basically I am using the pi zero as a Wifi access point for the application that is doing the API communication. So, I thought it would be great if I could do TLS interception right on the access point since it is physically between the client and the server. But, if it doesn't work on the pi, then I'll have to either intercept on the client itself (e.g. via HTTP Catcher) or redirect the traffic on the pi zero to another system that can run mitmproxy.
