### ISSUE TITLE
Mitmproxy with Browsermob functionality

### ISSUE THREAD

**Issue by AlexIzydorczyk** [mitmproxy/mitmproxy#723]
Hi,

Just wondering about the feasibility of using mitmproxy as a Browsermob sort of proxy (https://github.com/AutomatedTester/browsermob-proxy-py)

Essentially, I'd like to route "bundles" of requests to a running mitmdump session (ie. request my webpage that executes Javascript / makes other realted calls) and get back a HAR or JSON record of all requests made in that bundle (ie. requests that the original request referred or redirected to).

The challenge I'm seeing is that there doesn't appear to be a clear way right now to keep track of a single bundle of requests (I suppose I could be checking the referer head?). Further, mitmdump inline scripts give the ability to edit/ alter responses in realtime, but again, no as a "bundle". 

A simple solution would be to write every response to a some sort of database with a key that identifies the request (and hopefully initial request/bundle) that made it and then to retrieve that later. That's not as convenient as having just HAR come back though... 

Has anyone implemented or thought about something like this?

**Comment by mhils** [comment]
Hi @AlexIzydorczyk,

sorry for the late reply. As an idea, you could send special requests to the proxy that act as signals for your inline scripts (i.e. you request "http://mitmproxy/new-bundle?name=foo" to signal that a new bundle is started) or you restart the proxy for each bundle. We do have a HAR export script in the examples directory. 

I don't think "browsermob functionality" is a feature which is currently in scope for mitmproxy, so I'm closing this issue for now.
