### ISSUE TITLE
Add Support for Specifying Local Applications in mitmdump for Traffic Capture

### ISSUE THREAD

**Issue by cschy** [mitmproxy/mitmproxy#7231]
#### Problem Description

I would like to capture the traffic of specific local applications using mitmdump. Currently, there doesn't seem to be a straightforward way to specify which local processes to intercept directly from the command line or configuration.

#### Proposal
I propose adding an option in mitmdump to allow users to specify local applications for traffic capture. For example, it could be implemented like this:
main.mitmdump(['-s', __file__, '--application', 'D:/demo.exe'])

#### Alternatives
Currently, users have to manually select local processes through the web interface, which is not very convenient for automation. Another alternative could be to use environment variables or configuration files, but these options may still not be as direct as specifying the local application in the command line.

#### Additional context
This feature would greatly enhance the usability of mitmdump for users who want to automate the interception of specific local applications without having to manually select them each time through the web interface.

**Comment by mhils** [comment]
For local redirect mode, you can do `--mode local:demo.exe`, see https://mitmproxy.org/posts/local-redirect/windows/ for examples. We haven't integrated it into the main docs yet (but that's something we should do). Does this solve your problem?

**Comment by cschy** [comment]
However, it doesn't work on mitmdump. Could you implement it for mitmdump?

**Comment by mhils** [comment]
mitmproxy, mitmweb, and mitmdump all work the same.

**Comment by cschy** [comment]
Thank you very much. I forgot to disable the global network proxy, now it's working well!
