### ISSUE TITLE
"Bad HTTP request line" with non-ASCII URL path

### ISSUE THREAD

**Issue by lilydjwg** [mitmproxy/mitmproxy#724]
It's rather uncommon to see a URL with non-ASCII sent to a server, but they do exist and the server seems to be fine with them. I come across this while capturing traffic from Internet Explorer 6 (Yes that browser is damn too old, but I can't change that). You can get the error with this command:

```
http_proxy=localhost:8080 curl http://localhost/测试
```

**Comment by mhils** [comment]
Thanks for the report.
If you want non-ascii symbols in the path, they need to be percentage-encoded.  Everything else is not valid HTTP. Unless there's a somewhat substantial portion of our users affected by this issue or there is a very easy fix, I think we won't handle this case.

Cheers,
Max
