### ISSUE TITLE
AttributeError: module 'mitmproxy_rs' has no attribute 'DnsResolver'

### ISSUE THREAD

**Issue by sagisar1** [mitmproxy/mitmproxy#7240]
#### Problem Description
When I am trying to start mitmproxy as a default command in kali linux, I get the following error:
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 5, in <module>
    from mitmproxy.tools.main import mitmproxy
  File "/usr/lib/python3/dist-packages/mitmproxy/tools/main.py", line 15, in <module>
    from mitmproxy import master
  File "/usr/lib/python3/dist-packages/mitmproxy/master.py", line 5, in <module>
    from .addons import termlog
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/__init__.py", line 12, in <module>
    from mitmproxy.addons import dns_resolver
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/dns_resolver.py", line 22, in <module>
    class DnsResolver:
  File "/usr/lib/python3/dist-packages/mitmproxy/addons/dns_resolver.py", line 44, in DnsResolver
    def resolver(self) -> mitmproxy_rs.DnsResolver:
                          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'mitmproxy_rs' has no attribute 'DnsResolver'

I have python 3.12.6 installed, so I don't understand why this is happening. Also I checked the module mitmproxy_rs and it seems that it does have this class DnsResolver in this path:
/usr/lib/python3/dist-packages/mitmproxy_rs/dns.pyi

#### Steps to reproduce the behavior:
1. write mitmproxy in the shell of kali linux

#### System Information
kali linux 2024.3.1

dpkg --list | grep mitmproxy
ii  mitmproxy                              10.4.2-0kali1                            all          SSL-capable man-in-the-middle HTTP proxy
ii  python3-mitmproxy-rs                   0.9.2-0kali2                             amd64        mitmproxy's Rust bits (Python 3)
ii  python3-mitmproxy-wireguard            0.1.23-0kali1                            amd64        proxy any device that can be configured as a WireGuard client (Python 3)

**Comment by mhils** [comment]
mitmproxy 10.4.2 is incompatible with mitmproxy_rs 0.9.2: https://github.com/mitmproxy/mitmproxy/blob/v10.4.2/pyproject.toml#L45

You need to upgrade your mitmproxy install as well.
