### ISSUE TITLE
AttributeError: module 'bcrypt' has no attribute '__about__'

### ISSUE THREAD

**Issue by sagisar1** [mitmproxy/mitmproxy#7250]
#### Problem Description
When I am trying to start mitmproxy as a default command in kali linux, I get the following error:

(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/passlib/handlers/bcrypt.py", line 619, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'

#### Steps to reproduce the behavior:
1. write mitmproxy in the shell of kali linux

#### System Information
Mitmproxy: 11.0.0
Python:    3.12.6
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  Linux-6.10.11-amd64-x86_64-with-glibc2.40

**Comment by mhils** [comment]
https://docs.mitmproxy.org/stable/overview-installation/#linux
