### ISSUE TITLE
Provide binaries for linux/arm64

### ISSUE THREAD

**Issue by pablochacin** [mitmproxy/mitmproxy#7255]
#### Problem Description

There are no binaries for linux on arm64 architecture. 

#### Proposal

Provide said binaries

#### Alternatives
build binary locally

#### Additional context

When building multi-architecture docker image based on Alpine there are no official packages available.
Downloading the binary instead of installing from source would be convenient

**Comment by mhils** [comment]
Duplicate of https://github.com/mitmproxy/mitmproxy/issues/6756
