### ISSUE TITLE
Support for 422 Unprocessable Content in block_list

### ISSUE THREAD

**Issue by alfrol** [mitmproxy/mitmproxy#7269]
#### Problem Description

[`422 Unprocessable Content`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) is a valid HTTP status code. Currently it is not possible to use it in `block_list` option because it is missing [in this list of status codes](https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/net/http/status_codes.py#L54). Doing so results in an error:
```shell
mitmproxy: Cannot parse block_list option :~d google-analytics.com:422: Invalid HTTP status code: 422
```

#### Proposal
Add `422 Unprocessable Content` to the list of valid status codes.

**Comment by Prinzhorn** [comment]
Needs to be added here https://github.com/mitmproxy/mitmproxy/blob/main/mitmproxy/net/http/status_codes.py similar to https://github.com/mitmproxy/mitmproxy/commit/00a190221d4a61950aeb5c8b8e4f40fc7942ac24

I think that's all that needs to be done, looking at the blocklist addon:

https://github.com/mitmproxy/mitmproxy/blob/ae882ffb006af8644673ba3df03dd265c16ba7b8/mitmproxy/addons/blocklist.py#L36-L37

PRs welcome!
