### ISSUE TITLE
Client Certificate is `None`

### ISSUE THREAD

**Issue by Sirack** [mitmproxy/mitmproxy#727]
Hi,

Am looking to see the certificate of the client. That way I can identify device x from device y while looking at the traffic. Inside the flow object there is a client connection which contains `clientcert` variable. But this variable is None. 

flow.client_conn.clientcert --- gives none?

Any ideas on why? Am I missing a concept here?

**Comment by mhils** [comment]
Did you actually configure your client to send a client certificate?

**Comment by Sirack** [comment]
I have installed a certificate on IOS device. A profile which has one certificate. Will that be the right?

**Comment by mhils** [comment]
Just to clarify: Did you just install the mitmproxy CA certificate on the device or a specific client certificate?

**Comment by Sirack** [comment]
mitmproxy CA certificate

**Comment by mhils** [comment]
`clientcert` contains the SSL client certificate used to authenticate the client. You need to configure this on the client explicitly. This is not a mitmproxy-specific question, so please use Google and inform yourself on this. :-)
