### ISSUE TITLE
How can I change mitmweb style?

### ISSUE THREAD

**Issue by Stephen0910** [mitmproxy/mitmproxy#7279]
1、How can I change "comment" style in mitmweb, such as put the value in the center or color it red?

![image](https://github.com/user-attachments/assets/fb2cf06d-8bf6-4a0a-ac9d-fc1c54eb3f37)

2、May I add a new web column in mitmweb? So I can easily notice the error response.

**Comment by mhils** [comment]
https://github.com/mitmproxy/mitmproxy/discussions/7274
