### ISSUE TITLE
ctx options is not tested

### ISSUE THREAD

**Issue by LordByku** [mitmproxy/mitmproxy#7321]
#### Problem Description
Trying to understand how ctx.options works, but found empty tests (test/mitmproxy/test_ctx.py)

#### Proposal
Add tests

#### Additional context
[# TODO: write tests](https://github.com/mitmproxy/mitmproxy/blob/e1f6e2c8127cd16edc579de30e3a55d9a728f7bc/test/mitmproxy/test_ctx.py#L1)

**Comment by mhils** [comment]
It's an `Options` instance (see the type annotation). The "meat" is tested in https://github.com/mitmproxy/mitmproxy/blob/main/test/mitmproxy/test_optmanager.py. I agree that more test coverage would be nice, but we typically don't track that in extra issues.
