### ISSUE TITLE
Raw TCP Connection in Reverse Mode is forwarded with TLS

### ISSUE THREAD

**Issue by SimonLyke** [mitmproxy/mitmproxy#7324]
#### Problem Description
Im running mitmproxy on an ubuntu 20.04 VM
Mitmproxy is running in reverse mode with the following command
`mitmproxy --tcp-hosts "." --mode reverse:192.168.122.1:5000`
the idea is using netcat on my host to open a tcp connection with mitmproxy which should forward that connection back to my host on port 5000.

Host -> VM mitmproxy -> Host 

however whatever mitmproxy is forwarding the host isnt the raw message i sent over the tcp connection which should just be "hello"

its like its recreating the tcp connection over TLS which is not what i want. 

Are there any flags that force raw tcp forwarding or is this not working as intended

Apologies if im missing something obvious, not super familiar with networking :(

#### System Information
Mitmproxy: 4.0.4
Python:    3.8.10
OpenSSL:   OpenSSL 1.1.1f  31 Mar 2020
Platform:  Linux-5.15.0-125-generic-x86_64-with-glibc2.29

**Comment by 8192bytes** [comment]
mitmproxy will enforce TLS by default if the protocol is not specified. Use `tcp://` in url to specify a raw connection. In your case;
```
 mitmproxy --tcp-hosts "." --mode reverse:tcp://192.168.122.1:5000
```
More info : https://docs.mitmproxy.org/stable/concepts-modes/#protocol-specification

**Comment by SimonLyke** [comment]
Hi, I tried that but i get an error, will post the error tomorrow

**Comment by mhils** [comment]
Your mitmproxy version is outdated and unsupported. You want to try this
with the latest release. :)

**Comment by SimonLyke** [comment]
quite possibly, i installed with apt i believe

**Comment by SimonLyke** [comment]
Yep outdated installation from apt. used the binaries provided on the website and the syntax now works. cheers and apologies for silly questions!
