### ISSUE TITLE
mitmproxy incorrectly upgrades http to https

### ISSUE THREAD

**Issue by m7Rahm** [mitmproxy/mitmproxy#7340]
#### Problem Description

I have the following use case:
* If a request made to a certain domain, then return a static webpage.
* All other HTTP traffic should be forwarded to an upstream proxy through mitmproxy. 

I use the following command to start the proxy:

`mitmproxy -m upstream:https://<upstream-proxy-IP>:<upstream-proxy-port> -p 8080 -s override_domain.py`

I specify mitmproxy address as a proxy for Chrome. Chrome automatically upgrades http to https whenever possible. I can see it in proxy logs:

`
Request(CONNECT example.com:443)
`

I also see the response from the upstream proxy that connection over https failed:

`GetHttpConnectionCompleted(command=GetHttpConnection(address=('example.com', 443), tls=True, via=('https', (<upstream-proxy-IP>, <upstream-proxy-port>)), transport_protocol='tcp'), reply=(None, 'Upstream proxy <upstream-proxy-IP>:<upstream-proxy-port> refused HTTP CONNECT request: 502 Could not resolve host example.com'))
`

However, the connection between mitmproxy and the browser is made over https. This causes an issue because some of the content in the returned static page contains http:// URLs. All such requests fail, because the main page was served over https.
This is observed *only* when using an upstream proxy. Without upstream proxy (using the following command), the page is correctly served over http:

`mitmproxy -p 8080 -s override_domain.py`

This was not an issue in mitmproxy 5.0.0 version. It looks like mitmproxy upgrades http to https based on the connection with the upstream proxy.

I have already tried to use `connection_strategy=lazy`. No success :(

#### Steps to reproduce the behavior:
1. A small script to return a static webpage when request is made to a certain domain (example.com).
2. Start the mitmproxy in upstream mode and connect to a HTTPS upstream proxy.
3. Navigate to http://example.com on Chrome using mitmproxy as a proxy.
4. http will be upgraded incorrectly to https, even though the webpage does not support https requests. 

#### System Information
mitmproxy: 11.0.0
Python: 3.10.0
Platform: Windows Server 2022

**Comment by mhils** [comment]
Can you please provide a minimal reproducer using two mitmproxy instances, `python -m http.server` as the server, and cURL as the client to demonstrate the issue?

**Comment by m7Rahm** [comment]
I should have mentioned in the description earlier, but I missed one important piece of information. When the static page is returned, the scheme of a request is not checked, whether it was http or https.

When I run it with connection_strategy=lazy with no upstream proxy, I see additional requests in the HAR file that were missing when running in eager mode. 

As I mentioned, the website is accessed using HTTP, and these additional requests were HTTPS connection requests, which failed with "client disconnected" error. It looks like Chrome is trying to establish a connection using HTTPS and quickly falls back to HTTP.

I have fixed the script to return the web page only while the scheme is HTTP. Now, the response is 502 from the upstream proxy. I thought with connection_strategy=lazy, the flow should have been shortcircuted before connecting to the upstream proxy. 

Either way, I think this *is not* a mitmproxy issue. My assumption is that it was working fine on version 5.0 because mitmproxy was slow, and Chrome was falling back to HTTP without mitmproxy noticing. 

I would appreciate it if you could help me with rejecting the TLS connection from a client. I tried using client_connected, but it does not contain any information such as SNI. I see this information in tls_start_client, but I don't know how to fail the connection at this point. 

Sorry for the huge message!
