### ISSUE TITLE
NotImplementedError: active_executables is only available on Windows

### ISSUE THREAD

**Issue by catap** [mitmproxy/mitmproxy#7347]
#### Problem Description
During work with web UI I had encounter wired stacktraces:
```
[03:10:01.966] Uncaught exception GET /processes (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8081', method='GET', uri='/processes', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/tools/web/app.py", line 679, in get
    self.write(ProcessList.get_json())
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitmproxy/tools/web/app.py", line 667, in get_json
    processes = mitmproxy_rs.process_info.active_executables()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: active_executables is only available on Windows
[03:10:01.970] 500 GET /processes (127.0.0.1) 5.15ms
```

#### Steps to reproduce the behavior:
1. run `mitmweb -q`
2. Switch to tab `Capture`
3. Enjoy the stacktrace.

#### System Information
Mitmproxy: 11.0.1
Python:    3.11.10
OpenSSL:   LibreSSL 4.0.0
Platform:  OpenBSD-7.6-amd64-64bit-ELF

**Comment by lups2000** [comment]
> @lups2000 from my limited understanding of the code this:
> 
> https://github.com/mitmproxy/mitmproxy/blob/e7c5e904f6d7370f16998e687cc18bbf5d893ea7/web/src/js/components/Modes.tsx#L24
> 
> is missing a check for "freebsd" / "openbsd"? Maybe reverse the logic and check for platforms we know support local mode? Or doesn't this entire logic belong to the server? But I don't know how the mitmweb client architecture is separated. It feels like this leaks implementation details into the client, which shouldn't bother with these things?

Yes, we're missing those platforms. I implemented a general check just for **Linux** to disable local mode. Since the supported ones are Windows and macOS, I can simply invert the check. Thanks, @Prinzhorn and @catap, for pointing this out!

**Comment by lups2000** [comment]
@Prinzhorn @catap I've opened a small PR for this :) Let me know if I should add anything else! Thanks :)
