### ISSUE TITLE
Error with mitmweb - crashing it

### ISSUE THREAD

**Issue by leowilkin** [mitmproxy/mitmproxy#7351]
#### Problem Description
Not really sure why mitm crashed - was using mitmweb locally as a proxy.

Here's the error code:
Is@http://127.0.0.1:8081/static/app.js:8:34515
JN</Ty.enqueueSetState<@http://127.0.0.1:8081/static/app.js:6:27728
Db</Ad.prototype.setState@http://127.0.0.1:8081/static/app.js:1:1774
onViewportUpdate@http://127.0.0.1:8081/static/app.js:64:53808
componentDidUpdate@http://127.0.0.1:8081/static/app.js:64:53202
GT@http://127.0.0.1:8081/static/app.js:8:32412
zN@http://127.0.0.1:8081/static/app.js:8:32083
B3@http://127.0.0.1:8081/static/app.js:8:31610
$3@http://127.0.0.1:8081/static/app.js:8:41831
tf@http://127.0.0.1:8081/static/app.js:8:41178
QT@http://127.0.0.1:8081/static/app.js:8:37636
Uu@http://127.0.0.1:8081/static/app.js:6:3541
JN</Yi/<@http://127.0.0.1:8081/static/app.js:8:34947

Component Stack:
V_@http://127.0.0.1:8081/static/app.js:64:52683
q@http://127.0.0.1:8081/static/app.js:57:10727
div
bE@http://127.0.0.1:8081/static/app.js:64:71646
div
$E@http://127.0.0.1:8081/static/app.js:68:3040
q@http://127.0.0.1:8081/static/app.js:57:10727
eB@http://127.0.0.1:8081/static/app.js:61:571

#### Steps to reproduce the behavior:
1. use it to intercept network traffic locally

#### System Information
Mitmproxy: 11.0.1 binary
Python:    3.12.7
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  Windows-11-10.0.22631-SP0

**Comment by lups2000** [comment]
Hi, thanks! Did you get any errors in the terminal? I assume this error was shown in the console, right?

**Comment by leowilkin** [comment]
Nope! It crashed the program and mitmproxy powershell window auto-closed.

**Comment by lups2000** [comment]
> Nope! It crashed the program and mitmproxy powershell window auto-closed.

Okay, I see! Could you please provide more specific details about the steps to reproduce the bug? Which proxy mode were you using? Was it the local mode? 
Did you click on something in particular? Adding a quick demo would be really helpful! (Unfortunately, I don’t have access to a Windows machine to test it myself, so I’m trying to narrow down the possible causes.) Thank you! :)
