### ISSUE TITLE
sysctl config changes

### ISSUE THREAD

**Issue by hrdwdmrbl** [mitmproxy/mitmproxy#7353]
#### Problem Description

The documentation [here](https://docs.mitmproxy.org/stable/howto-transparent/) is now out of date due to changes in the structure of the configs. 

The following are all deprecated and will give the error "unknown oid"

1. `net.ipv4.ip_forward`
2. `net.ipv6.conf.all.forwarding`
3. `net.ipv4.conf.all.send_redirects`

#### Steps to reproduce the behavior:
1. Run `sysctl -w net.ipv6.conf.all.forwarding=1`

#### System Information
Paste the output of "mitmproxy --version" here.

```
Mitmproxy: 11.0.1 binary
Python:    3.12.7
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  macOS-15.1-arm64-arm-64bit
```

#### What I already learned

The new config structure is all `net.inet` and `net.inet6`. 

I believe that the new config for one is:

1. `net.ipv4.ip_forward` -> `net.inet.ip.forwarding`

**Comment by mhils** [comment]
Contributions arre welcome! :)
