### ISSUE TITLE
Https traffic is not capturing

### ISSUE THREAD

**Issue by Rexota** [mitmproxy/mitmproxy#736]
Hello

I installed Root.crt and Class3.crt files on an Android 4.0.3 device. And I'm running mitmproxy from console.

However it's not capturing https traffic (http is ok). What is the problem?

Thanks.

**Comment by mhils** [comment]
Are there any messages in the event log? Did you install the mitmproxy CA on the client? We usually don't have files called Root.crt and Class3.crt.

**Comment by Rexota** [comment]
I followed this steps for Android to install CA: 
http://wiki.cacert.org/FAQ/ImportRootCert#Android_Phones_.26_Tablets.

Also there is no message in event log.

**Comment by mhils** [comment]
If there is not even a `clientconnect` message in the eventlog, mitmproxy does not receive any traffic - you need to look into your network configuration then.
