### ISSUE TITLE
Implement Cache-Busting for mitmweb

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#7381]
#### Problem Description
mitmweb's web interface is currently served from a static path, and browsers like to cache that. We should add some cache busting [here](https://github.com/mitmproxy/mitmproxy/blob/e0c40b1beb8f9fc2460962aa89c231cec50b10d3/mitmproxy/tools/web/templates/index.html#L10). A simple implementation would be to add `?hash` to the URL, and calculate the actual file hash once on demand.

#### Steps to reproduce the behavior:
1. Use old mitmweb version.
2. Update mitmproxy.
3. Open web interface again: Version number in the status bar has updated (comes from the backend), but functionality has not.

#### System Information

```
Mitmproxy: 12.0.0.dev (+20, commit d51df5f)
Python:    3.12.8
OpenSSL:   OpenSSL 3.3.2 3 Sep 2024
Platform:  macOS-15.1.1-arm64-arm-64bit
```

**Comment by Prinzhorn** [comment]
This would also close https://github.com/mitmproxy/mitmproxy/issues/4973#issuecomment-996660053

**Comment by Prinzhorn** [comment]
> A simple implementation would be to add `?hash` to the URL, and calculate the actual file hash once on demand.

Even simpler: when doing a release we could append the current version:

```html
<!doctype html>
<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>mitmproxy</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="static/vendor.css?v=11.0.2" />
        <link rel="stylesheet" href="static/app.css?v=11.0.2" />
        <link rel="icon" href="static/images/favicon.ico" type="image/x-icon" />
        <script src="static/app.js?v=11.0.2"></script>
    </head>
    <body>
        <div id="mitmproxy"></div>
    </body>
</html>
```

And locally during dev we could just have:

```html
<!doctype html>
<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>mitmproxy</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="static/vendor.css?v=VERSION" />
        <link rel="stylesheet" href="static/app.css?v=VERSION" />
        <link rel="icon" href="static/images/favicon.ico" type="image/x-icon" />
        <script src="static/app.js?v=VERSION"></script>
    </head>
    <body>
        <div id="mitmproxy"></div>
    </body>
</html>
```

So  it's trivial to replace?
