### ISSUE TITLE
heres what contrib.md should say for installing

### ISSUE THREAD

**Issue by jamieduk** [mitmproxy/mitmproxy#7384]
heres what contrib.md should say for installing
```

python3 --version
python3 -m pip --help
python3 -m venv --help
# 2) Install:
git clone https://github.com/mitmproxy/mitmproxy.git
cd mitmproxy
python3 -m venv venv
source venv/bin/activate
venv/bin/pip install -e ".[dev]"

```

**Comment by jamieduk** [comment]
where do i find the compiled binary for arm 64 ? i ran the ```

python3 --version
python3 -m pip --help
python3 -m venv --help
# 2) Install:
git clone https://github.com/mitmproxy/mitmproxy.git
cd mitmproxy
python3 -m venv venv
source venv/bin/activate
venv/bin/pip install -e ".[dev]"
pip install --upgrade pip
```

**Comment by jamieduk** [comment]
where do i find the binaries i want mitmdump binary i compiled on arm 64 bit rpi on ubuntu and now what ?

**Comment by mhils** [comment]
Please continue in https://github.com/mitmproxy/mitmproxy/discussions/7383, use the search functionality, and do not open new issues.

**Comment by jamieduk** [comment]
your instructions were incomplete hence i started a new thing here for a reason now help me with my query here so i can get on with my day!

**Comment by jamieduk** [comment]
So fa i found this maybe the answer am i correct?

```
cd mitmdump/mitmproxy-main/release/
venv
pip install pyinstaller
python build.py standalone-binaries
```
