### ISSUE TITLE
【11.0.x】 a problem opening mitmweb with Edge browser

### ISSUE THREAD

**Issue by DyLenpOki** [mitmproxy/mitmproxy#7394]
#### Problem Description
Edge browser keeps displaying 'fetching data' in the upper right corner and some features are unavailable, but Chrome browser works normally
![image](https://github.com/user-attachments/assets/490b90df-67aa-437b-b4f5-c3ed78d10344)

**Comment by Prinzhorn** [comment]
Can you open the JavaScript console (`Ctrl + Shift + I`) and check if there are any errors? Have you used an older version of mitmweb with the same browser? If so, then try clearing your cache.

**Comment by DyLenpOki** [comment]
is cache，Thanks
