### ISSUE TITLE
How do you disable HTTP/2 for all domains except for google.com?

### ISSUE THREAD

**Issue by ofirc** [mitmproxy/mitmproxy#7412]
### Discussed in https://github.com/mitmproxy/mitmproxy/discussions/7411

<div type='discussions-op-text'>

<sup>Originally posted by **ofirc** December 24, 2024</sup>
mitmproxy allows to block all HTTP/2.0 traffic globally by passing:
`mitmproxy --set http2=false
`

However, that's too coarse-grained.
I'm looking for a fine-grained approach that would allow me to enable HTTP/2.0 traffic only to a certain domain, e.g. based on the SNI.
How can I do that? Is it even possible with mitmproxy?

I tried to do the following:
```
from mitmproxy import http
from mitmproxy import ctx

def request(flow: http.HTTPFlow) -> None:
    # Force mitmproxy to intercept and terminate TLS for all requests
    if "google.com" in flow.request.pretty_host:
        ctx.log.info(f"Allowing HTTP/2 for {flow.request.pretty_host}")
        flow.server_conn.alpn = b"h2"
    else:
        ctx.log.info(f"Downgrading to HTTP/1.1 for {flow.request.pretty_host}")
        flow.server_conn.alpn = b"http/1.1"

def tls_clienthello(client_hello):
    # Intercept TLS handshake and set ALPN based on domain
    target_host = client_hello.client_hello.sni
    if "google.com" in target_host:
        ctx.log.info(f"Allowing HTTP/2 for {target_host}")
        client_hello.client_hello.alpn_protocols = [b"h2"]
    else:
        ctx.log.info(f"Downgrading to HTTP/1.1 for {target_host}")
        client_hello.client_hello.alpn_protocols = [b"http/1.1"]
```

Then run:
`mitmproxy -s custom_alpn.py
`

Then:
`curl --cacert ~/.mitmproxy/mitmproxy-ca-cert.pem  -x http://localhost:8080 -v https://example.com -d '{secretkey: secretvalue}'
`

I expected example.com to use only HTTP/1.1 and not HTTP/2, however I still see that the server accepted it in the curl output:
`* ALPN: server accepted h2`

What could be the reason?</div>

**Comment by mhils** [comment]
Closing in favor of https://github.com/mitmproxy/mitmproxy/discussions/7411, please don't double-post.

**Comment by ofirc** [comment]
My apologies and thank you.
