### ISSUE TITLE
MacOS Local Redirect Mode: too many open files

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#7416]
### Discussed in https://github.com/mitmproxy/mitmproxy/discussions/7415

<div type='discussions-op-text'>

<sup>Originally posted by **SenberHu** December 27, 2024</sup>
Mitmproxy: 11.0.2 binary
Python:    3.12.7
OpenSSL:   OpenSSL 3.4.0 22 Oct 2024
Platform:  macOS-15.1-arm64-arm-64bit

I started mimtproxy with mitmproxy --mode local:"Google Chrome", and after a few hours, my Chrome couldn't access the network, I saw the extension error "open too many files" on the Mac console. I execute `lsof -p {org.mitmproxy.macos-redirector.network-extension}`, and saw that the open fd has reached the maximum limit, so when a new flow arrives in the extension, it can't be send to mitmproxy_rs via unix socket, please let me know if there is a problem with my setup or a bug in the program? Looking forward to your reply
<img width="1133" alt="image" src="https://github.com/user-attachments/assets/e316407f-b500-49fe-8763-218d787aa576" />
</div>

**Comment by mhils** [comment]
I don't have the capacity to look into this closer right now, but for anyone interested here are the two ends of the unix socket:

https://github.com/mitmproxy/mitmproxy_rs/blob/6028f0b83d39773eda269c709e26612a116e2827/src/packet_sources/macos.rs#L138

https://github.com/mitmproxy/mitmproxy_rs/blob/6028f0b83d39773eda269c709e26612a116e2827/mitmproxy-macos/redirector/network-extension/TransparentProxyProvider.swift#L113-L116

It's supposed to be one Unix socket per TCP connection, but they should be closed once the TCP connection is closed.

**Comment by wgreenberg** [comment]
I also seem to get a `too many open files` error when running in wireguard mode on macOS. Within a second or two of enabling my wireguard client, mitmproxy starts printing

```
[12:26:41.936][10.0.0.1:59513] error establishing server connection: [Errno 24] Too many open files
```

and once I ctrl+c mitmproxy, I see a ton of these:
```
Caused by:
    Too many open files (os error 24)
Task exception was never retrieved
future: <Task finished name="server connection handler ('17.248.245.230', 443)" coro=<ConnectionHandler.open_connection() done, defined at mitmproxy/proxy/server.py:183> exception=RuntimeError('unable to bind to 12
7.0.0.1:0\n\nCaused by:\n    Too many open files (os error 24)')>
Traceback (most recent call last):
  File "mitmproxy/proxy/server.py", line 218, in open_connection
RuntimeError: unable to bind to 127.0.0.1:0
```

Happy to open another issue if you think that makes the most sense. Here's my version info:
```
» mitmproxy --version
Mitmproxy: 11.0.2 binary
Python:    3.12.7
OpenSSL:   OpenSSL 3.4.0 22 Oct 2024
Platform:  macOS-15.2-arm64-arm-64bit
```

**Comment by wgreenberg** [comment]
Actually, I think my issue was using wireguard mode on the same device as the client, causing an infinite loop. Disregard!

**Comment by SenberHu** [comment]
I wonder why close this issue? It doesn't seem to be resolved

**Comment by dmitryskorbovenko** [comment]
https://github.com/mitmproxy/mitmproxy/issues/7675
