### ISSUE TITLE
Merge of Set-Cookie response headers in reverse mode causes Firefox browser to not recognize all cookies

### ISSUE THREAD

**Issue by yinsel** [mitmproxy/mitmproxy#7423]
#### Steps to reproduce the behavior:

In anti proxy mode, the source server response contains multiple Set Cookie headers, but mitmproxy automatically merges them, resulting in some websites only recognizing the first cookie.

The website server uses HTTP/2.

#### System Information
Paste the output of "mitmproxy --version" here.

Mitmproxy: 11.0.2
Python:    3.10.16
OpenSSL:   OpenSSL 3.4.0 22 Oct 2024
Platform:  Windows-10-10.0.26100-SP0

**Comment by mhils** [comment]
Can you please provide a full reproducer? What HTTP version is used between client and proxy, what version between proxy and server, and what do the cookies look like?

**Comment by yinsel** [comment]
> Can you please provide a full reproducer? What HTTP version is used between client and proxy, what version between proxy and server, and what do the cookies look like?

This is the Set Cookie of the original website

![image](https://github.com/user-attachments/assets/0eca1807-db6b-4a76-97ae-8365bfaeda46)

This is the response header after mitmproxy is reversed

![image](https://github.com/user-attachments/assets/46aefe9c-e591-4928-bc52-9ca7acdb00bd)

所有通信均使用HTTP/2

**Comment by yinsel** [comment]
I have identified the issue and replaced the domain with flow.response. headers ["set-cookie"], which resulted in all set-cookie headers being merged.

```
rsp.headers["set-cookie"] = re.sub(r"domain=[a-zA-Z0-9\.\-]+", f"domain={SERVER}", rsp.headers["set-cookie"])
```

**Comment by mhils** [comment]
For future reference, headers have a `get_all`/`set_all` API: https://docs.mitmproxy.org/stable/api/mitmproxy/http.html#Headers.get_all
