### ISSUE TITLE
Add Inline Script Hooks to TCP mode

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#747]
Adding inline script hooks to the raw tcp mode ([libmproxy.protocol.rawtcp](https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/protocol/rawtcp.py)) would be an excellent addition to mitmproxy. There could be one hook on start and another one per message.

**Comment by bazzinotti** [comment]
@mhils I'd like to help catalyze and motivate the upbringing of this feature request.

If you enjoyed the process we took with my first PR, please consider similarly providing insights on accomplishing this task and I will pursue the implementation.

Consider the following key points from #866:

- [ ] The TCP layer should emit events per message
- [ ] we need some form of container format at some point that also provides access to the client and server connection (see Flow and HTTPFlow).

Pertinent files
```
(Flow)
models/flow.py
models/http.py

protocol/rawtcp.py
```

Do you think it would be too difficult to steer me in the right direction?

**Comment by mhils** [comment]
Great to hear you want to give this a shot! :smiley:

I think we should first focus on getting the events piped to inline scripts. The container/flow thing is a bit more abstract and we should leave that for a later PR (We really haven't wrapped our minds around this either).

You'll get the brief version as I'm on holiday, so please don't refrain from asking further questions:

- Every HTTP/TCP/... connection is handled in an isolated connection thread. You can communicate with the (single-threaded) FlowMaster over a channel. The FlowMaster then calls the inline script and hands a return value over to the channel.
- You can create a "handle_tcpmessage" method in the FlowMaster and then call `self.channel.ask("tcpmessage", obj)` in the TcpLayer to invoke the function on the master. In handle_tcpmessage, you just call the inline script stuff and return the result. https://github.com/mitmproxy/mitmproxy/commit/d002371d30e4b0ab7d1d23023236a9446d4c2396 is pretty similar to what you want to do.
- You can only pass a single object to `.ask`, but we probably want to transmit more than just the actual message. For now, I think it's perfectly okay if we polyfill this and just create a data class that holds everything we want:
```python
class TcpMessage(object): 
    def __init__(self, layer, message):
        self.layer = layer
        self.message = message
```
We can then just transmit this class thingie. Later on, we'd use the actual flow for this (as we do for HTTP).

if there's anything unclear, let me know. :smile: By the way, you're more than welcome to join us on Slack if you'd like - this usually shortens the turnaround times considerably.

[1]) There no need to understand how that works internally, but it's actually not much magic:
https://github.com/mitmproxy/mitmproxy/blob/f8d8a80bd07fe1e40577a2090ba47e3cc5abd3d3/libmproxy/controller.py#L40
https://github.com/mitmproxy/mitmproxy/blob/f8d8a80bd07fe1e40577a2090ba47e3cc5abd3d3/libmproxy/controller.py#L99
https://github.com/mitmproxy/mitmproxy/blob/f8d8a80bd07fe1e40577a2090ba47e3cc5abd3d3/libmproxy/controller.py#L126

**Comment by bazzinotti** [comment]
Questions:

1. Can you provide a clear example of what an inline script that uses this new feature will look like? (See 4)

2. WHERE to call `self.channel.ask("tcpmessage", obj)` in the TcpLayer to invoke the function on the master? I assume here-ish: https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/protocol/rawtcp.py#L54
Based on your `TcpMessage` class definition, would something like this be appropriate?
`self.channel.ask("tcpmessage", TcpMessage(self, buf[:size]))`

3. What would be the appropriate file and location-in-file to house the new `TcpMessage` class?

4. Does any of what you've mentioned cover splitting the TCP messages into distinguishable parts? I'm speaking from the perspective of an inline script writer, who may want log specific connections, msg from client, msg from server, or all of the above.

5. Attempted crafting of `handle_tcpmessage`
```
def handle_tcpmessage(self, m):
        # call the inline script stuff and return the result.
        # see  d002371 https://github.com/mitmproxy/mitmproxy/commit/d002371d30e4b0ab7d1d23023236a9446d4c2396
        self.run_script_hook("tcpmessage", m)
        m.reply()
        return m
```
I actually have no understanding in what I've done here :dizzy_face: It may be completely wrong.

I'm curious as to why some handle_*** functions do not return anything, and the ones that do, seem to just return their argument back. My lack of understanding caused me to simply mimic the same behavior. I made a similar assumption to call `run_script_hook`

**Comment by mhils** [comment]
Answers:

1. The snippet from #866 is pretty close, but you'd have a TcpMessage/Flow object as input, so the very short example would be [1].
2. Yes. Probably before the sendall so that users can modify messages at some point.
3. Just throw it in rawtcp, no other class should need knowledge of it - the rest is duck-typed.
4. The TcpMessage class should probably have "client_conn", "server_conn", "sender" and "receiver" attributes (client_conn and server_conn are available as attributes on the layer, see [rawtcp.py#L28](https://github.com/mitmproxy/mitmproxy/blob/f8d8a80bd07fe1e40577a2090ba47e3cc5abd3d3/libmproxy/protocol/rawtcp.py#L28)). This provides basic context info for each message. The state of the connection (i.e. access to previously transferred messages) are due with the TCPFlow.
5. This is correct so far (you can omit the `return` though). `.reply()` pushes things back to the connection thread. The methods which return the object (instead of `.reply()`ing) are overridden by DumpMaster (mitmdump) and ConsoleMaster (mitmproxy), where a reply happens - your question is more than legitimate, we're missing documentation here, sorry :see_no_evil: .


[1])
```python
def tcp_message(ctx, flow):
    print(flow.sender)
    print(flow.message)
```

**Comment by bazzinotti** [comment]
I've got it working! But, it's not yet complete. We need to work some kinks out together. Please address the following:

1) You've used both `tcpmessage` and `tcp_message` in your past dialogue -- which one do you prefer to officialize?

2) I've modified the TcpMessage initializer to identify sender/receiver. Take a look
```
class TcpMessage(object): 
    def __init__(self, layer, sender, receiver, message):
        self.layer = layer
        self.client_conn = layer.client_conn
        self.server_conn = layer.server_conn
        self.sender = sender
        self.receiver = receiver
        self.message = message
....
...
...
    # inline scripting TcpMessage
    self.channel.ask("tcpmessage", TcpMessage(self, conn, dst, buf[:size]))
```

Of course, it is possible to reduce the number of arguments to TcpMessage by one, by not explicitly providing both sender/receiver arguments, but only one of them and inferring the other in the initializer. Please guide the correct approach.

3) In 2, is it pointless to create the `client_conn` and `server_conn` attributes since they are already a part of the `layer` attribute?

### Inline Script Tests

The following details how I am running my particular testing of the new feature.

inline script - `tcp_message.py`

```
def tcpmessage(ctx, m):
    print(m.layer)
    print(m.client_conn)
    print(m.server_conn)
    print(m.sender)
    print(m.receiver)
    print(m.message)
```

my particular mitmdump cmdline invocation: `mitmdump -T --host --client-certs clientcert.pem --raw-tcp -s tcp_message.py`

Example output (IP info removed):
```
RawTCPLayer
<ClientConnection: [ssl] [IP removed]:48784>
<ServerConnection: [ssl] [IP removed]:443>
<OpenSSL.SSL.Connection object at 0x7f58a4245d50>
<OpenSSL.SSL.Connection object at 0x7f58a4245990>
<memory at 0x7f58a424e218>
```

#### Binary dump test

tcp_dump.py
```
filename = ""
filehandle = None

def start(context, argv):
    global filename, filehandle
    if len(argv) != 2:
        raise ValueError("Usage: -s '%s filename'" % argv[0])
    filename = argv[1]
    filehandle = open(filename, "wb")

def clientconnect(ctx, root_layer):
    print("Client connected!!! XDXD")

def clientdisconnect(ctx, root_layer):
    print("Client disconnected~~ XDXD")

def tcpmessage(ctx, m):
    global filehandle
    print(m.sender)
    print(m.receiver)
    print(m.message)
    filehandle.write(m.message)
```

`mitmdump -T --host --client-certs clientcert.pem --raw-tcp -s 'tcp_dump.py /tmp/tcpdump.bin'`

I can confirm that the above test produces a proper full bidirectional decrypted SSL conversation in binary to the specified dump-file

**Comment by bazzinotti** [comment]
I've just made major edits to the previous post. Be sure to read on Github

**Comment by mhils** [comment]
Great work! :smiley:

1) I think `tcp_message` is more Pythonic.
2) `sender` and `receiver` should be ClientConnection/ServerConnection objects. In other words, they should be identical to `layer.server_conn`, not `layer.server_conn.connection` (so that a user can just check `sender == client` in his inline script).
For the message, it's probably best to just send `buf[:size].tobytes()`. Dealing with memoryviews/bytearrays is a bit of a PITA, we should not expose that to users.

>  I thought it best to explicitly provide both

Yes. No "smart" code please. :-)

3) The flow object we're ultimately aiming for will have `client_conn` and `server_conn` attributes, but won't expose direct access to the layer. Now that we have this nice TcpMessage class, we can remove the layer from it completely I think.

Other than that, this looks very good. Don't be scared of sending an early PR! :relaxed:

**Comment by dequis** [comment]
Since #872 got merged, is this considered done?

**Comment by mhils** [comment]
Yes, thanks for the heads-up.
