### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by ryoqun** [mitmproxy/mitmproxy#757]

**Comment by mhils** [comment]
Works, but not out of the box.

**Comment by ianobermiller** [comment]
@mhils is there a guide somewhere to enabling IPV6 support? Specifically, I want to reverse proxy to an IPV6 only server.

**Comment by mhils** [comment]
Unfortunately no. I hacked something together about a year ago, but I haven't seen a significant number of ipv6-only users yet to make it work properly - sorry! 
I believe you can get a long way by fixing [`netlib.tcp.TCPClient.connect`](https://github.com/mitmproxy/netlib/blob/master/netlib/tcp.py) to just use Python's `socket.create_connection`. The listening part in [`netlib.tcp.TCPServer.__init__`](https://github.com/mitmproxy/netlib/blob/master/netlib/tcp.py) seems to be a bit more difficult to fix (https://bugs.python.org/issue17561) - I haven't really looked into it, but I'm happy to help if you want to pick this up.

Cheers,
Max

**Comment by ianobermiller** [comment]
Thanks for the update, @mhils!

**Comment by thenewguy** [comment]
+1
