### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by sonicjh36** [mitmproxy/mitmproxy#763]
I use the script "redirect_requests.py" and it got an error:

Script load error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/script.py", line 99, in load
    execfile(self.argv[0], ns, ns)
  File "/root/Desktop/redirect.py", line 4, in <module>
    from libmproxy.models import HTTPResponse
ImportError: No module named models

**Comment by mhils** [comment]
You're using mitmproxy 0.13 with the examples from master - please use the examples on the 0.13 branch instead.

Cheers,
Max
