### ISSUE TITLE
Issue on MacOSX 10.10.5 (Mavericks) and iOS9.0: Host is Down

### ISSUE THREAD

**Issue by loretoparisi** [mitmproxy/mitmproxy#767]
I have some issue with MacOS X 10.10.5 / iOS9.0 GM.
The python script starts with no errors, but it seems the device is not connecting to the proxy (I can see no logs on the Mac). On the iPhone the error is

```Shell
Sep 16 11:20:05 iPhone6Loreto[1671] <Error>: tcp_connection_destination_perform_socket_connect 125 connectx to 192.168.2.188:11112@0 failed: [64] Host is down
```

If I do telnet locally

```Shell
macbookproloreto:~ admin$ telnet 192.168.2.188 11112
Trying 192.168.2.188...
Connected to 192.168.2.188.
Escape character is '^]'.
```

This happens on WiFi interface only. Using Ethernet it works fine.

**Comment by mhils** [comment]
Thanks for the report. Did it work for you with iOS8?

**Comment by loretoparisi** [comment]
It worked fine with iOS8. I was also trying mitmproxy on a Raspberry Pi 2 in a local network. It worked fine when it was connected to the cable. Adding a USB  WiFi module, I had the same issue on the iOS9 client ```tcp_connection_destination_perform_socket_connect```.

In that case we have discovered the issue. This raspberry had a IPTables rule, since it was running the  ```Facebook Augmented Traffic Control (fatc)``` - https://github.com/facebook/augmented-traffic-control.

We didn't tested yet, maybed a better IPTables rule with mitmproxy IP and port and running ```mitmproxy``` like

```Shell
macbookproloreto:tvOS admin$ mitmproxy -b 192.168.2.164 -p 11112
```

could let connection to go through.

**Comment by mhils** [comment]
Thanks. I don't have any iOS 9 (or OSX) devices, so I can't test this unfortunately. If you don't observe `clientconnect` messages in mitmproxy's event log, mitmproxy does not even get a TCP connection and the issue is somewhere on your stack.
