### ISSUE TITLE
Host name in URL not shown for https requests

### ISSUE THREAD

**Issue by leoluk** [mitmproxy/mitmproxy#77]
The current release displays the URL just fine:

```
https://encrypted.google.com/search?q=foo
```

The current development version, however, only displays the IP:

```
https://173.194.70.101/search?q=foo
```

HTTP requests are not affected. The issue appears first in 9130cd6.

**Comment by sheldoncoupeheure** [comment]
Note to future readers: the cli option is now `--showhost` 

It can also be activated under the option menu (press uppercase `O` while in terminal mode) next to "showhost" (options are alphabetically sorted).

**Comment by yinguohang** [comment]
If you are using python script and try to get the url, you might try `request.pretty_host` instead of `request.host`.

**Comment by ogion** [comment]
hi, how can we do this in Java?
