### ISSUE TITLE
upgrading tnetstring from 0.2.0 to 0.2.1

### ISSUE THREAD

**Issue by MetaMemoryT** [mitmproxy/mitmproxy#771]
The embedded tnetstring is 0.2.0

https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/tnetstring.py#L71

The latest is 0.2.1

https://github.com/rfk/tnetstring/blob/master/tnetstring/__init__.py#L51

Perhaps we should consider depending on the package rather than embedding the library.

I encountered an obscure tnetstring error and I thought I should spend my effort working on the tnetstring library rather that some obsolete embedded version.

Also, depending on the library will allow some users to use the _tnetstring.c performance improvements.

Maybe, if necessary we could host a forked version of the library at 
https://github.com/mitmproxy/tnetstring if there are mitmproxy specific changes, and that is why the library was embedded in the first place.

Thoughts?

**Comment by mhils** [comment]
Thanks for the suggestion!

> The latest is 0.2.1

There are no code changes between 0.2.1 and 0.2.0 for the Python version: https://github.com/rfk/tnetstring/compare/v0.2.0...master

> Perhaps we should consider depending on the package rather than embedding the library.

I would do that immediately, but there's no binary wheel on PyPI and the installation does not degrade gracefully if no compiler is present. Thus, you wouldn't be able to `pip install mitmproxy` (on Windows) without having a compiler installed

> Also, depending on the library will allow some users to use the _tnetstring.c performance improvements.

See above.

> Maybe, if necessary we could host a forked version of the library at 
https://github.com/mitmproxy/tnetstring if there are mitmproxy specific changes, and that is why the library was embedded in the first place.

Casually diffing against the official 0.2.0, the only additions seems to be a `file.flush()`, which we could certainly move out of the library.

Another thing to keep in mind is that there's no Python 3.5-compatible tnetstring version available. So, we probably need to switch (or fix the existing implementation) at some point.

You're very welcome to tackle any of the issues mentioned above. :smiley: 
If someone provides OSX and Windows wheels (or gracefully degrading source distributions) that maybe would even be Py3-compatible, I'd be happy to switch to that.

**Comment by mhils** [comment]
I'm closing this for now because we (as the core dev team) don't intend to make any changes here rather soon. Nonetheless, we welcome external contributions for this! :smiley:
