### ISSUE TITLE
no replay is printed in mitmdump

### ISSUE THREAD

**Issue by Nerudifus** [mitmproxy/mitmproxy#775]
I try to keep it short.
Up to version 0.13 I was used that mitmdump tells me when a site was replayed with a line include `<<` and `[replay]`. If the site was not replayed but loaded from the original server than it printed something with `<<` but without `[replay]`. But this was not done with the master version from yesterday. Thus it was harder to find #774. 
The output from mitmdump was moved to click instead of print, I think. After a search I found out that the ```handle_request``` function of dump.py is the point of my ambition. It response on a request but did not print anything. Thus I added the line
```
self.echo_flow(f)
```
after ```f.reply()``` and the replay output is back.
I think this is a bug and that it affects the option `-d`, too. If neither is true, I'm sorry for this report.

**Comment by mhils** [comment]
Well, you have to make sacrifices for getting colors :smile: 
This should be a bug, thanks for reporting.
