### ISSUE TITLE
dev closes terminal or session

### ISSUE THREAD

**Issue by Nerudifus** [mitmproxy/mitmproxy#778]
I forgot one little problem. In the documentation in part Hacking it is said to call ```source ./dev```. Thus the script is running in the current shell session. If virtualenv is not installed than ```exit``` is called closing the current shell session. Thus in a terminal the terminal is closed and in a virtual console the whole session is terminated and user is logged out. In both cases the printed error message is not visible. The user only see that the terminal is closed or they are logged out.

**Comment by mhils** [comment]
Thanks. I haven't found a way yet to reliably activate the virtualenv without using source, so it looks like we need stick with `./dev` and then have instructions for manual activation.

**Comment by Nerudifus** [comment]
Maybe another way is to remember the error, something like:
```
#!/bin/bash
set -e
VENV=../venv.mitmproxy

noerror=1
python -m virtualenv $VENV --always-copy || { echo 'virtualenv is not installed. Exiting.' ; noerror=0; }
if [ $noerror -gt 0 ] ; then
  . $VENV/bin/activate
  pip install --src .. -r requirements.txt
  
  echo ""
  echo "* Created virtualenv environment in $VENV."
  echo "* Installed all dependencies into the virtualenv."
  echo "* Activated virtualenv environment."
fi
```
or
```
#!/bin/bash
set -e
VENV=../venv.mitmproxy

noerror=1
python -m virtualenv $VENV --always-copy || noerror=0
if [ $noerror -gt 0 ] ; then
  . $VENV/bin/activate
  pip install --src .. -r requirements.txt
  
  echo ""
  echo "* Created virtualenv environment in $VENV."
  echo "* Installed all dependencies into the virtualenv."
  echo "* Activated virtualenv environment."
else
  echo 'virtualenv is not installed. Exiting.'
fi
```

I haven't tested it. I am not familiar with such an environment so I do not know if this is a bad idea.

**Comment by mhils** [comment]
That'd work, but you still get the shell exit if `activate` or `pip install` fails. I feel this is getting too complicated for what it should do - it might be useful do document the activation anyways.
