### ISSUE TITLE
ImportError: No module named 'urlparse'

### ISSUE THREAD

**Issue by jadedevin13** [mitmproxy/mitmproxy#781]
Not running

![screenshot from 2015-09-22 06 56 40](https://cloud.githubusercontent.com/assets/6671182/10007365/27f9fe82-60f7-11e5-9cdf-605b312eda83.png)

**Comment by mhils** [comment]
mitmproxy only runs on Python 2.7 at the moment. We're in the process of fixing this, with netlib being Python 3.5 compatible. For now, you have to downgrade to Python 2.7 though.

Cheers,
Max
