### ISSUE TITLE
mitmproxy doesn't works with Android Emulator + SSL

### ISSUE THREAD

**Issue by cybersecurity7** [mitmproxy/mitmproxy#783]
0. Mitmproxy package on Kali Linux 2.0 (mitmproxy 0.13)
1. Mitmproxy CA cert installed on Android Emulator 5.0.1 (API 21) / 4.4.2 (API 19) [SDK 24.3.4]
2. mitmproxy -e -vvv
3. From Android Emulator Browser->https://www.google.com/

...
127.0.0.1:50899: Received CONNECT request to SSL port. Upgrading to SSL...
127.0.0.1:50899: Establish SSL
  -> with client
  -> with server (sni: None)
127.0.0.1:50899: SSL handshake error: The client may not trust the proxy's certificate.
127.0.0.1:50899: ProxyError('NetLibError("SSL handshake error: SysCallError(-1, \'Unexpected EOF\')",)',)
127.0.0.1:50897: SSL handshake error: The client may not trust the proxy's certificate.
127.0.0.1:50897: ProxyError('NetLibError("SSL handshake error: SysCallError(-1, \'Unexpected EOF\')",)',)
127.0.0.1:50899: clientdisconnect
127.0.0.1:50897: clientdisconnect
127.0.0.1:50899: serverdisconnect
  -> 64.15.126.59:443
...

**Comment by mhils** [comment]
Thanks for the report. Can you visit other HTTPS websites, e.g. https://mitmproxy.org/ ? How did you install the root certificate?

**Comment by cybersecurity7** [comment]
Hi,

- The CA certificate was installed via http://mitm.it (certificate in settings and popup "Network may be monitored" is showed)
- No connection to other httpS websites.

Thanks

**Comment by mhils** [comment]
Did you take a look at https://github.com/mitmproxy/mitmproxy/issues?utf8=%E2%9C%93&q=is%3Aissue+android+emulator?

**Comment by cybersecurity7** [comment]
Hi, yes I took it but no answer to this problem.
My previous emulator 4.2.2 (API 17) has worked fine with a previous mitmproxy version (I think was 0.10).
From new mitmproxy version (0.13) also my previous emulator 4.2.2 (API 17) has stopped to work with interception.

Thanks

**Comment by ErikWittern** [comment]
I am having the same issue when trying to use mitmproxy 0.13 when running an emulator with API 23. Similar to cybersecurity7, I have the CA certificate installed via http://mitm.it ("Network may be monitored" is shown on starting the device) and cannot access any HTTPS site.

**Comment by skorokithakis** [comment]
I have the same problem here. The browser just freezes when accessing https pages with mitmproxy 0.15.

**Comment by skorokithakis** [comment]
Looks like this comment is relevant: https://github.com/mitmproxy/mitmproxy/issues/362#issuecomment-60320525

**Comment by mhils** [comment]
This has just been fixed by @fimad - thanks again!
