### ISSUE TITLE
HTTP header parameters encoding

### ISSUE THREAD

**Issue by R1kk3r** [mitmproxy/mitmproxy#784]
I tried to use mitmproxy between a client and a server in HTTPS. The server is a tomcat server configured in French with a Java web application running. When I use mitmproxy, I got a HttpSyntaxException.

HttpSyntaxException('Non-ascii characters in first line: HTTP/1.1 401 Non-Autoris\xe9',) 

This is because the Response-Phrase of the HTTP response is "Non-Autoris**é**".
I read some RFC related to HTTP but I found nothing related to the allowed encoding for HTTP header parameters. Because web browser doesn't seem to encounter a problem with this, I guess it is a mitmproxy (or netlib) issue. Converting all source files into utf-8 encoding and using the "# coding: utf-8" should solve this case.

EDIT:
I have located the issue in netlib/http/http1/read.py line 223:

line.decode("ascii")

My fix is to do a .decode("latin1"), if it fails do a .decode("ascii"), if it fails, raise the error.

Don't know if it's correct...

**Comment by mhils** [comment]
IIRC it must be ASCII, but I should have known that the French would spoil us :wink: 
Thanks for the report, will fix that. :smile:
