### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Quach90** [mitmproxy/mitmproxy#795]
Hi
I'm trying to run one of the examples but I keep getting an error from: upsidedownternet.py

mitmdump: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/script.py", line 99, in load
    execfile(self.argv[0], ns, ns)
  File "upsidedownternet.py", line 3, in <module>
    from libmproxy.models import decoded
ImportError: No module named models

Since I couldn't find version 0.13 in any of the branches I assumed it was the master branch. (I'm looking to get the decoded to work, so that I can work with gzipped)

Thanks!

**Comment by mhils** [comment]
This looks like you're using an example from master but running 0.13. Please use the 0.13 _tag_ on Github.
