### ISSUE TITLE
installing mitmproxy in Ubuntu 

### ISSUE THREAD

**Issue by ra7bi** [mitmproxy/mitmproxy#798]
hello all, i installed ubunut last V and when i tried to install mitmproxy always faild can you give us any bash script with all installation instructions because i followed your read me and not working . 

for the errors most of them is module not found

**Comment by mhils** [comment]
Please use the instructions from http://docs.mitmproxy.org/en/latest/install.html - they work perfectly fine on a clean Ubuntu installation.
