### ISSUE TITLE
mitmweb - possibility to add username / password for web interface

### ISSUE THREAD

**Issue by fliespl** [mitmproxy/mitmproxy#802]
Hi everyone,
I am not sure if it's possible or not. I went through docs and couldn't find it. Is there an easy way to protect web port access (not proxy).

**Comment by mhils** [comment]
Not yet, contributions are welcome!

**Comment by ganguera** [comment]
We can close this issue as this feature is included in 0.16.

**Comment by joar** [comment]
This feature seems to have been removed in mitmproxy 3.0.3.

**Comment by Kriechi** [comment]
This feature wasn't available since at least v1.0
https://github.com/mitmproxy/mitmproxy/commit/9b08279c7c3384f716b66329fefbe97a368189a2
https://github.com/mitmproxy/mitmproxy/commit/40f0193dda992960b9836482425cd45329f240af
