### ISSUE TITLE
Export/copy request as raw text

### ISSUE THREAD

**Issue by areichow** [mitmproxy/mitmproxy#807]
A feature I've been using in Fiddler is the ability to export the request as raw text. Once saved, the raw request easily replayed (with or without manual or programmatic modification) with netcat with a command like this:

```
nc api.host.com 80 < raw-request.txt > response.txt
```

**Comment by mhils** [comment]
refs #799

**Comment by gato** [comment]
Will add this to #799 in the next couple of days

**Comment by mhils** [comment]
:+1:

**Comment by dufferzafar** [comment]
@mhils I think this can be closed, since #884 was merged!
