### ISSUE TITLE
Export/copy request as code

### ISSUE THREAD

**Issue by areichow** [mitmproxy/mitmproxy#808]
It would be great if mitmproxy allowed you to generate a snippet of code, presumably in Python, that would issue the same request. 

Related to the following two requests:
* [Export/copy request as raw text](https://github.com/mitmproxy/mitmproxy/issues/807)
* [Export as curl command](https://github.com/mitmproxy/mitmproxy/issues/596)

**Comment by mhils** [comment]
Thanks for the suggestion. We'd be super happy to accept a PR for this!

**Comment by nurav** [comment]
@mhils Hi, I'd like to work on this. Could you give me a few pointers so that I know how to go about it?

**Comment by mhils** [comment]
@nurav: Great to hear that! @gato has openend PR #799 for curl export (which I still didn't get to review properly, sorry :see_no_evil: ). Maybe it's best if you set up a dev environment (see the README), take a look at Marcelos PR and work on based on that. :smiley:

**Comment by nurav** [comment]
I'll do that. Thanks!

**Comment by dufferzafar** [comment]
#884 only added support for copying [GET requests](https://github.com/mitmproxy/mitmproxy/pull/884/files#diff-9641efb691a86154d6143b6ec654f8f7R307) as Python code. I am working on adding others.

**Comment by Kriechi** [comment]
closed by #916

**Comment by Buff-r** [comment]
Downloaded the latest mitmproxy version can't find a way to export as curl command! its annoying! was it removed?

**Comment by ujjwal96** [comment]
@Buff-r It can be done by pressing <kbd>e</kbd>
