### ISSUE TITLE
Broken link "Hacking"

### ISSUE THREAD

**Issue by arnau** [mitmproxy/mitmproxy#812]
Hi, links in https://mitmproxy.org/doc/install.html pointing to `https://github.com/mitmproxy/mitmproxy/blob/master/README.mkd#hacking` are broken. The `README` extension should be `.rst`

**Comment by mhils** [comment]
This is already fixed in https://github.com/mitmproxy/mitmproxy/blob/master/docs/install.rst and on http://docs.mitmproxy.org - we're planning to fade out the old docs ASAP. Thanks a lot for the report anyway, always appreciated!

**Comment by arnau** [comment]
Nice :+1: it looks much better
