### ISSUE TITLE
Docs: Link to repo should match version of the docs

### ISSUE THREAD

**Issue by arnau** [mitmproxy/mitmproxy#813]
The [`add_header`](https://github.com/mitmproxy/mitmproxy/blob/master/examples/add_header.py) example fails to run. For convenience showed here:

```python
def response(context, flow):
    flow.response.headers["newheader"] = "foo"
```

##### Steps to reproduce the problem:

1. Start the proxy
```sh
mitmdump --script add_header.py
```
(tested with `mitmproxy --script add_header.py` as well)

2. Make a request
```sh
curl -I --proxy http://localhost:8080 -XGET http://github.com
```

##### What is the expected behavior?

To get back something like:

```
HTTP/1.1 302 Found
Connection: close
Pragma: no-cache
cache-control: no-cache
Location: /
newheader: foo
Content-Length: 0
```

##### What went wrong?

See the trace:

```python
Script error:
Traceback (most recent call last):
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/lib/python2.7/site-packages/libmproxy/script.py", line 123, in run
    return (True, f(self.ctx, *args, **kwargs))
  File "/Users/arnau/kitchen/me/proxyswitch/example.py", line 4, in response
    flow.response.headers['newheader'] = 'foo'
  File "/usr/local/Cellar/mitmproxy/0.13/libexec/vendor/lib/python2.7/site-packages/netlib/odict.py", line 72, in __setitem__
    "Expected list of values instead of string. "
ValueError: Expected list of values instead of string. Example: odict['Host'] = ['www.example.com']
```

##### Any other comments?

The following example works:

```python
def response(context, flow):
    flow.response.headers["newheader"] = ["foo"]
```
```
HTTP/1.1 302 Found
Connection: close
Pragma: no-cache
cache-control: no-cache
Location: /
newheader: foo
Content-Length: 0
```

Although not directly related to the issue the following surprised me:

```python
def response(context, flow):
    flow.response.headers["newheader"] = ["foo", "bar"]
```
```
HTTP/1.1 302 Found
Connection: close
Pragma: no-cache
cache-control: no-cache
Location: /
newheader: foo
newheader: bar
Content-Length: 0
```
I expected to have just one `newheader`.  Is it intended to be this way?

**Comment by arnau** [comment]
Just now I've seen the example under the tag 0.13 uses the form `["foo"]` so it does not fail.  Then the issue seems to be with http://docs.mitmproxy.org/en/latest/scripting/inlinescripts.html (inline example) and the links that point to `master` instead of the latest release.

**Comment by mhils** [comment]
Thanks for the report! We're currently in the process of transitioning our docs from our custom system (http://mitmproxy.org/doc/) to Readthedocs (http://docs.mitmproxy.org), which now already hosts the docs for our next release. I'd be super super happy if someone could take a look how we can link to the Github branch matching the version of the docs. http://docs.readthedocs.org/en/latest/vcs.html#github sounds like it's possible, but I haven't really looked in to it yet. Contributions are very welcome!

**Comment by arnau** [comment]
Happy to take a look on this one although I never worked with readthedocs before.

**Comment by arnau** [comment]
Looking at https://docs.readthedocs.org/en/latest/versions.html seems to me that adding the tag `stable` to match the current stable version would bring that version to the documentation.

On top of that, it seems to assume that versions are tagged using semver **without** a prefixed `v`.

**Comment by mhils** [comment]
There is really no good way to fix this, unless we want to add custom JS. Let's close this for now.
