### ISSUE TITLE
Not working for streaming audio

### ISSUE THREAD

**Issue by programmin1** [mitmproxy/mitmproxy#814]
When I connect my phone to Mitmproxy it seems I can't access streaming audio file (through MediaElement.js player) until disconnecting the proxy.

While the phone usually plays the audio (garbled and awful-sounding, unfortunately) it didn't start when connected to mitmproxy, and I saw 0 byte responses. Oddly enough I see the complete, normal file on reading the file back.

**Comment by mhils** [comment]
Did you take a look at http://docs.mitmproxy.org/en/latest/features/responsestreaming.html?
