### ISSUE TITLE
Add/Remove scripts on a running proxy

### ISSUE THREAD

**Issue by arnau** [mitmproxy/mitmproxy#816]
Is there a way to do the same `|` does in `mitmproxy` but using `mitmdump`?

**Comment by mhils** [comment]
mitmdump is completely non-interactive - not sure what you envision here? You can spawn a second instance in the background and then kill the first one.

**Comment by arnau** [comment]
Yes, I was trying to avoid having to do that :)

I guess I'm trying to do something weird:  I'm thinking in using mitmproxy with my unit tests against an API so I can intercept and "mock" it when necessary without having to change or specialise my app.

**Comment by mhils** [comment]
IMO restarting isn't that bad. Alternatively, you can either send special "command" requests through the proxy which are processed by your inline script, e.g. your inline script acts on `GET http://mitmproxy.local/set-server-replay-file/foo` or you can spawn a web server in your inline script and expose an API.

Closing this for now as I don't see a way how else it should work. :-)

**Comment by arnau** [comment]
Thanks for the suggestions!
