### ISSUE TITLE
HTTP whitelist based on Host field

### ISSUE THREAD

**Issue by chumaitoe** [mitmproxy/mitmproxy#818]
(this is a companion to https://github.com/mitmproxy/mitmproxy/issues/817, HTTPS whitelist based on SNI)

I have a transparent proxy interposed between an android device and the internet, such that all traffic runs through the proxy. I want to sort the traffic such that connections to our servers (i.e. from our app) go through the proxy (i.e., display), while other traffic (from the device) goes through a RawTCPLayer so that they are not shown in the proxy display.

I would like to have a flag that would take a list of domains, each of which would be compared to the value of the Host header.  Requests that match would be sent through the proxy, while those that do not match can go through a RawTCPLayer so they do not display.

The potential sticky bit is that the bytes with the Host header may not have arrived yet when the flow is being examined for routing... I did not quite get a clear enough picture of the internals to know either way.

**Comment by mhils** [comment]
I'm sorry, but this does not really fit into mitmproxy's architecture - when we read headers, we are already in the HTTP layer. (Also, this obviously does not work for SSL, which we need to intercept before seeing the Host header, but based on the SNI issue I assume you are aware of that :-) ). You can use mitmproxy's limit feature or mitmdump's filter to hide flows to certain hosts in the UI. Does that satisfy your use case?

**Comment by chumaitoe** [comment]
I wasn't looking to have the header checked at the HTTP level.  Rather, I think the same peekahead mechanism being used for SNI can be used here, even though it requires peeking a bit further ahead.  Since the HTTP session cannot properly start until the Host header is sent, it should npt cause any trouble to pend until we can sniff those bytes, then make the decision on the type of the second (or is it third?) level.

For our purposes, this is really the only way to do this.  Our servers are deployed in the cloud, and thus do not have A records, rather they use CNAMEs, which cannot reasonably be discovered based on IP address (and even if they were, timeliness requirements would render the technique unusable), so we must rely on the client to tell us which host they are sending to.

Limit feature?   Dude... https://github.com/mitmproxy/mitmproxy/issues/542 !  No wonder I hadn't heard of it.  Is this what is now called filters?

Filtering HTTP traffic may be an option, yes.  I will look into that.
