### ISSUE TITLE
Proxy keeps asking for authentication all the time

### ISSUE THREAD

**Issue by Antonn1** [mitmproxy/mitmproxy#824]
Hello,

I successfully setup mitmproxy and it's dependencies and when I run the proxy with a password, it just keeps asking for the password. Even though the password entered is correct.

This only started happening after I reinstalled the server and installed mitmproxy again.

Am I missing something?

**Comment by mhils** [comment]
I'm not quite sure what your issue is based on what you are writing. Could you please describe your issue using the template at https://github.com/mitmproxy/mitmproxy/blob/master/CONTRIBUTING.md?

**Comment by Antonn1** [comment]
Hello,

Apologies.

Basically, what I'm trying to say is that the device which connects to the proxy is always prompted for authentication details even if the authentication provided is correct.

On a previous installation (~2 months ago) it worked fine on Ubuntu 14.10. Now after formatting the server to 14.10 again and reinstalling mitmproxy and it's dependencies, it installs like before but when I start the proxy and connect my device to it, it just keeps asking for authentication details no matter what I insert in the user & pass box.

If I run the proxy without authentication it works as it should but with authentication, it's giving me issues. So I was thinking maybe I'm missing something?

**Comment by mhils** [comment]
Thanksfor the clarification.

1. How do you start mitmproxy (which parameters?)?
2. Which client do you use? How did you configure it to use the proxy?

**Comment by Antonn1** [comment]
I use screen to keep it running in the background so:

screen mitmproxy --singleuser user:password -s file.py

-

I haven't done any configurations. Just installed and started the proxy. :)

**Comment by mhils** [comment]
Which client do you use? Firefox? Chrome? Your-Random-App?
If it's a browser: Does this happen for all websites or only for HTTP, only for HTTPS, ...?

**Comment by Antonn1** [comment]
I use an iOS & Android device. And it happens for all websites apparently.

**Comment by Antonn1** [comment]
Any ideas?

On a previous fresh install, it never used to ask for the authentication password all the time. I will format the server and retry again.

**Comment by Antonn1** [comment]
Nothing yet.

Can I install an older version of mitmproxy? Maybe an updated version is causing the issue for me. Because on the old server, I never updated packages.

**Comment by mhils** [comment]
I just commited a fix that affected HTTPS connections only. You can install mitmproxy from master using
```
pip install git+https://github.com/mitmproxy/netlib.git@master
pip install git+https://github.com/mitmproxy/mitmproxy.git@master
```

You mentioned HTTP connections are affected as well - does this fix your issue though?

**Comment by Antonn1** [comment]
I'm not sure how to install it that way. Got an error.

Sorry.

**Comment by mhils** [comment]
Sorry about that. I think we have plenty of installation instructions out there.
