### ISSUE TITLE
support for netlib >= 0.14.0

### ISSUE THREAD

**Issue by colemickens** [mitmproxy/mitmproxy#825]
Updated my Arch box. I now get this in `mitmproxy`:

```
sudo mitmproxy
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'netlib<0.14,>=0.13' distribution was not found and is required by mitmproxy
```

I've downgraded `python2-netlib` down to `python2-netlib-0.13.1-1-any`. Mitmproxy is working again.

Folks in #archlinux recommended I file an upstream bug and then an Arch bug with a link to the upstream bug. This is the first step of that process.

**Comment by colemickens** [comment]
Downstream (Arch Linux) bug report: https://bugs.archlinux.org/task/47007

**Comment by mhils** [comment]
Thanks. If you run mitmproxy 0.14, you need a matching 0.14.x version of netlib. If you run mitmproxy 0.13, you need mitmproxy >=0.13, < 0.14. Your issue looks like you updated netlib only (but not mitmproxy). You should either install both using your package manger (so that both get updated) or both using pip (which I'd recommend, YMMV). As I see it, there's nothing we could fix here (we specify our requirements in [setup.py#17](https://github.com/mitmproxy/mitmproxy/blob/master/setup.py#L17) - this code seems to be working as intended)

**Comment by mhils** [comment]
Looking at https://www.archlinux.org/packages/?sort=&q=mitmproxy, looks like someone updated the netlib package, but not the mitmproxy one. Whoever does this stuff should specify the same upper and lower bound for version compatibility as we do (i.e., same minor version).

**Comment by colemickens** [comment]
Thanks for taking a look, I didn't realize there was already a new release of mitmproxy. Excellent! The upstream bug was triaged today so hopefully it's resolved soon. Cheers.

**Comment by mhils** [comment]
You're welcome. If you happen to be in touch with the maintainers, please kindly ask them to specify version bounds for the same minor version. :smiley:

**Comment by felixonmars** [comment]
Sorry, I missed mitmproxy from my watcher script migration, and updated only netlib and pathod. Won't happen next time :P

**Comment by mhils** [comment]
No problem. Thanks for the quick fix, really appreciate it! :smiley:
