### ISSUE TITLE
[Question][Help] Reverse Proxy a google website

### ISSUE THREAD

**Issue by daw1012345** [mitmproxy/mitmproxy#827]
I'm trying to Reverse Proxy www.google.com. Every time I recive a "Location: www.google.com ". I keep reciving the "Location:" header even if I change the "Location:" header to back to my website.

**Comment by mhils** [comment]
You can probably fix your specific issue by looking at http://docs.mitmproxy.org/en/stable/features/reverseproxy.html#host-header, but see the warning at http://docs.mitmproxy.org/en/stable/modes.html#reverse-proxy - you can't really "mirror" google by just specifying `-R`.

Cheers,
Max
