### ISSUE TITLE
[Question]Mitmproxy, google and cookies don't get along

### ISSUE THREAD

**Issue by daw1012345** [mitmproxy/mitmproxy#828]
I'm trying to reverse-proxy the accounts.google.com website, but every time I try to log in, it says "it seems that you have disabled cookies...". Any help would be greatly appreciated.

**Comment by mhils** [comment]
I think I already explained in #827 that this doesn't work as you intend it to do? Reverse Proxy mode is not sufficient to create a copy of an interactive website at a different URL. You may try using a transparent or a regular proxy.
