### ISSUE TITLE
mitmproxy 0.14 is too vocal about timeouts and disconnects.

### ISSUE THREAD

**Issue by nbdsp** [mitmproxy/mitmproxy#831]
I installed today the current version of mitm (v0.14) on ArchLinuxARM on Raspberry Pi and installed certificates in FireFox browser on other ArchLinux machine by opening the "mitm.it" site and clicking the "Other" icon. I start `mitmdump` with the command:

`mitmdum -b localhost -p 12345 -q`

When I open various sites, I get in stodut on Raspberry Pi many error messages like these:

```
192.168.1.1:40142: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40148: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40150: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40158: ProtocolException("Error in HTTP connection: HttpSyntaxException('Bad HTTP request line: \\x81\\xc1\\xcd~z\\x90\\xb1/\\x0f\\xf5\\xbe',)",)
192.168.1.1:40176: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40184: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40186: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40188: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40192: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40198: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40102: ProtocolException("Error in HTTP connection: TcpDisconnect('[Errno 32] Broken pipe',)",)
192.168.1.1:40206: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40208: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40210: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40216: ProtocolException("Error in HTTP connection: TlsException('',)",)
192.168.1.1:40218: ProtocolException("Error in HTTP connection: TlsException('',)",)
```

I searched the web but there is no results for such error messages. Is this problem a known one and there is some standard solution to it?

**Comment by mhils** [comment]
Thanks for the report. Just to clarify - the websites you open work normally, you're only wondering why there are error messages?

**Comment by nbdsp** [comment]
The sites seem to work normally, but I supposed that if error messages are reported, then something 'under the hood' may be not normal.

**Comment by mhils** [comment]
Thanks. These errors indicate timeouts, SSL errors or disconnects, so if you don't observe any obvious issues there's nothing to worry about. 

It looks like we accidentally increased the error verbosity with the latest release - that is something we should fix, so I'll leave this issue open.

**Comment by mhils** [comment]
This should be fixed now. If I missed something, please let me know!
