### ISSUE TITLE
Serialization of traffic flows

### ISSUE THREAD

**Issue by Fuzion24** [mitmproxy/mitmproxy#840]
Reading and instrumenting traffic flows at a later point has a been painful for us.  They are very fragile between releases.

I'd love to open a discussion about some way(s) to make the serialized flows more resilient to mitmproxy updates.

Cheers,
Ryan

**Comment by mhils** [comment]
Thanks for bringing that up. I feel your pain - we currently have a [very aggressive policy](https://github.com/mitmproxy/mitmproxy/blob/57cd9022d9253c7873ff3bd1d7943296bdf90268/libmproxy/flow.py#L1115-L1119) in place when it comes to deprecation. However, the serialized format didn't really change that much between the latest releases and we absolutely don't want users to stay on old releases.

I wrote a [small tool](https://gist.github.com/mhils/c69c599a40c61b596c7a) that converts 0.9 flows to 0.13 flows for a specific use case a while ago, but didn't get around implementing it properly in mitmproxy. If you look at the script, you'll see that's is actually not that much magic. I'd love to see someone taking this further and integrating it into mitmproxy. If you are interested, just ping me on Slack and I'm happy to help. :smiley:

**Comment by mhils** [comment]
Good news: We have a 0.13 -> 0.14 converter on master now. :cake: 
Our plan is to continue providing converters for upcoming versions, but I can't make any final commitments on this.

If you are interested in older versions, please take a look at [libmproxy/flow_format_compat.py](https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/flow_format_compat.py) and [test/tools/inspect_dumpfile.py](https://github.com/mitmproxy/mitmproxy/blob/master/test/tools/inspect_dumpfile.py) to see how it's done and submit a PR! :smile: 

If you cannot build from source and don't want to wait for the next release, you can grab the latest binary from http://snapshots.mitmproxy.org/ (should be there in a few mins) and run `mitmdump -n -r oldfile -w newfile`.

**Comment by dweinstein** [comment]
@mhils I'm thinking about embarking on an adventure to convert some older 0.11 dumps to 0.17... before I go down that rabbit hole I thought about trying to use the existing converters between versions to see if I could use the intermediary migrations (11 -> 12 -> 13 ...). Does that have the potential to work or should I aim for a straight conversion to 17?

**Comment by dweinstein** [comment]
oh sweet it was much easier that I thought.... I grabbed the missing converters from the current master to backport to my 0.17 release and that worked great! nicely done on those migrations!
