### ISSUE TITLE
Multipart viewer slow with large files

### ISSUE THREAD

**Issue by danhawkes** [mitmproxy/mitmproxy#842]
This seems to be a new issue in 0.14:

Uploading a ~1MB file via multipart post, then attempting to view the request causes the UI to block for a long period of time.

Sample flow here: 
[upload.txt](https://github.com/mitmproxy/mitmproxy/files/40063/upload.txt)

**Comment by mhils** [comment]
Thanks for the report. I started tracing this down today - The major issue seems to be urwid's rendering of large text objects, the content view is _relatively_ quick.

**Comment by mhils** [comment]
Seems like rendering unicode is damn slow:
```python
>>> import urwid, time
>>> t = urwid.Text([('text', u'x' * 1024*1024)])
>>> print(time.time()); t.render((100,)); print(time.time())
1448545029.68
<urwid.canvas.TextCanvas object at 0x0310FED0>
1448545087.21
```

```python
>>> import urwid, time
>>> t = urwid.Text([('text', 'x' * 1024*1024)])
>>> print(time.time()); t.render((100,)); print(time.time())

1448545106.41
<urwid.canvas.TextCanvas object at 0x026E22B0>
1448545111.29
```

**Comment by mhils** [comment]
We now calculate the current number of lines properly. Thanks for the report!

**Comment by danhawkes** [comment]
Awesome, thanks for the response!
