### ISSUE TITLE
Setting streaming causes some responses to report empty Content-Length even when response size does not exceed the threshold

### ISSUE THREAD

**Issue by jvillacorta** [mitmproxy/mitmproxy#856]
When streaming is enabled, multiple request that do not exceed the threshold are reported without content.

**WITH stream 50m**

```
GET https://impact.applifier.com/mobile/campaigns?platform=ios&gameId=5555&sdkVersion=1020&rawAdvertisingTrackingId=B18B33A9-C13A-4686-8B3B-A11B6CF227D4&advertisingTrackingId=c4c97e23f6d64dec7f42a553aefc889c&trackingEnabled=0&softwareVersion=9.0.1&deviceType=iPad5,3&connectionType=wifi&encrypted=false
   ← 200 application/json [content missing] 887ms
```

**WITHOUT stream**

```
GET https://impact.applifier.com/mobile/campaigns?platform=ios&gameId=5555&sdkVersion=1020&rawAdvertisingTrackingId=B18B33A9-C13A-4686-8B3B-A11B6CF227D4&advertisingTrackingId=c4c97e23f6d64dec7f42a553aefc889c&trackingEnabled=0&softwareVersion=9.0.1&deviceType=iPad5,3&connectionType=wifi&encrypted=false
   ← 200 application/json 6.88kB 1.52s
```

I was also trying to implement streaming on video files on my libmproxy implementation but seems to be failing for some hosts.

```
def handle_responseheaders(self, f):
    if f.request.method == 'GET':
        for _file_extension in STREAMING_FILE_LIST:
            if str(f.request.path).endswith(_file_extension):
                f.response.stream = True
```

**Comment by mhils** [comment]
Thanks for the report. This is a documentation issue - if we cannot determine the content length after the headers have been sent (chunked encoding and no content-length header), we always fall back to streaming if `--stream` has been passed. 

Your code looks correct so far - my bet would be on video files served without extension of with a query string.

**Comment by jvillacorta** [comment]
You may be right, some videos may not actually have an implicit extension, my best bet will be to check for the Content-Type instead.

The biggest problem I have with streaming is that it seems that it arbitrarily sets content-length to 0 if I use your implementation of streaming based on size for some requests to our API, without streaming they are fine. We are talking about requests less than 50 Kb. This happens while using mitmdump or my implementation of the proxy based on FlowMaster, I set the streaming part [here](https://github.com/mitmproxy/mitmproxy/blob/master/libmproxy/flow.py#L633)

I use [assemble_request, assemble_response](https://github.com/jvillacorta/netlib/blob/master/netlib/http/http1/assemble.py#L23-L28) to output some specific requests and responses to a log but they throw an exception if content-length is 0. In this case the content is not empty but the header indicates otherwise, which stops my output thread from reporting this response.

**Comment by mhils** [comment]
This sounds like it's very likely related to https://github.com/mitmproxy/mitmproxy/issues/659. I won't have the time to look into this currently, but we'll certainly fix that for the next release. If you want to give it a stab yourself, feel free to join us on Slack if you have any questions regarding the code base.
