### ISSUE TITLE
encoding error to outfile

### ISSUE THREAD

**Issue by tdyhacker** [mitmproxy/mitmproxy#858]
when I use '-w' option to store the flow to file, it display error content, just as following:
```
[x§‡:ÖáHi4GÐL¿¤Ìé4ÎæyùÍ§q¼<µYÂ&É‹¶Mñ+GÒ‡i8
avÅÆdT£<_‰»ÚÀ—æÏÂÓSòo“çˆ$B6KƒßÛVÚ¼rq{”2w.®NÉRhÔ…x)¥qÕ¾0‡8éÙOøóŸüÍ—òÛ_þãnñ—‡"Ä‚NqiŠ¬@JÔî"œE§"CJ&0‡Í*NCBé	r:G£O1yùè“æRQB4
```
how to record the utf8 content to file?

**Comment by mhils** [comment]
`mitmproxy -w` writes a serialized (not primarily human-readable) dump file that can be read again using `-r`. If the content of a message are e.g. gzip-encoded, you'll see gzip-encoded data in the dumpfile. If you want human-readable output to a text file, I'd suggest running 

`mitmdump -r ~/Desktop/aaa.txt -n -dd`

Explanation:

`-r`: Read an existing dump file
`-n`: Do not start a proxy server
`-d`: increase output details/verbosity (`-ddd` if you don't want contents to be cut off)
