### ISSUE TITLE
Mitmproxy using python3 instead of python2

### ISSUE THREAD

**Issue by wjchua06** [mitmproxy/mitmproxy#860]
Hi, I am using mitmproxy now and I realized that when i run the command 

mitmproxy --host -T -s pythonscript.py

the mitmproxy is running python3 instead of python2, it throws me an error message that there is a syntax error when I included the line [print "Downloading file"] in my python script. If I modify my script to be [print ("Downloading file")] it does not return any error messages.

May I know how can I fix my mitmproxy to run python2 instead of python3.

My ubuntu machine is running python2 by default.

**Comment by mhils** [comment]
How did you install mitmproxy? This looks like you used Python 3's pip.

**Comment by wjchua06** [comment]
I installed with "pip install mitmproxy"

**Comment by mhils** [comment]
If you only installed python3-pip, pip will be working for Python 3. If you have python2-pip, `pip uninstall mitmproxy && pip2 install mitmpoxy` should do it.

**Comment by wjchua06** [comment]
Sorry after performing `pip uninstall mitmproxy && pip2 install mitmproxy` i am still getting the same error. Looks like it is still registering python3 instead of python2

**Comment by mhils** [comment]
Oh, sorry - looks like I did not read the initial post correctly. We do `from __future__ import print_statement`, which causes this. Using `print()` works on both Python 2 and 3, so please just do that.

**Comment by baptx** [comment]
@mhils The command `pip2 install mitmproxy` was using Python 2 for me also. To use Python 2, I have to use the command `sudo python2 -m pip install mitmproxy` but I get this error:
```
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                                                                                             
  ----------------------------------------                                                                                                                                                    
  ERROR: Failed building wheel for cryptography
```
Any idea how to fix the issue? I would like to use a Python 2 script with mitmdump.

**Comment by mhils** [comment]
We don't support Python 2 anymore since 2016.

**Comment by baptx** [comment]
@mhils thanks for the information, I am using small scripts that are working with Python 2 but not with Python 3. Maybe you have an idea how to fix the issue, so I can use them with mitmproxy / mitmdump: https://github.com/sigalor/whatsapp-web-reveng/issues/303
