### ISSUE TITLE
mitmproxy crashes: AttributeError: 'NoneType' object has no attribute 'host'

### ISSUE THREAD

**Issue by colemickens** [mitmproxy/mitmproxy#861]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/lib/python2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 398, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/usr/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 497, in _find_cert
    host = self.server_conn.address.host
AttributeError: 'NoneType' object has no attribute 'host'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

**Comment by colemickens** [comment]
```
$ mitmproxy --version
mitmproxy 0.15
```

```
$ yaourt -Ss python2-netlib | grep installed
community/python2-netlib 0.15-1 [installed]
```

**Comment by colemickens** [comment]
It's a bit hard to repro. It doesn't occur if I `wget https://www.google.com` or `wget https://www.yahoo.com` but it does occur when using Azure's "azure-xplat-cli" tool.

**Comment by mhils** [comment]
Thanks. This looks like your client just connects to the proxy's IP and immediately starts to negotiate TLS. If you are running an explicit proxy (http://docs.mitmproxy.org/en/stable/howmitmproxy.html, http://docs.mitmproxy.org/en/stable/modes.html), your client should send a `CONNECT` request first. So, this is looks like a misbehaving client to me?

(We should not raise an exception nonetheless, but that won't fix your client I'm afraid)

**Comment by colemickens** [comment]
Thanks for the information. I've asked around and it seems that github.com/Azure/azure-xplat-cli
is using node's request library (https://www.npmjs.com/package/request).

According to their docs, they send a CONNECT:

>If you specify a proxy option, then the request (and any subsequent redirects) will be sent via a connection to the proxy server.

>If your endpoint is an https url, and you are using a proxy, then request will send a CONNECT request to the proxy server first, and then use the supplied connection to connect to the endpoint.

**Comment by colemickens** [comment]
I think this was entirely user error actually.

I was doing:

```
export HTTPS_PROXY=https://localhost:8080
export https_proxy=https://localhost:8080
```

when I should have been:


```
export HTTPS_PROXY=http://localhost:8080
export https_proxy=http://localhost:8080
```

Sorry for the noise and thank you for the support!

**Comment by mhils** [comment]
Thanks for clearing this up! :smiley: I'll reopen this as we don't want to raise an exception here nonetheless.

**Comment by mankalamanishkumar** [comment]
Hi All,
         when i am running following command
mitmdump -s add_header.py
i am getting following issue
Traceback (most recent call last):
  File "/root/Downloads/mitmproxy/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/root/Downloads/mitmproxy/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/root/Downloads/mitmproxy/libmproxy/protocol/tls.py", line 267, in __call__
    self._establish_tls_with_client_and_server()
  File "/root/Downloads/mitmproxy/libmproxy/protocol/tls.py", line 392, in _establish_tls_with_client_and_server
    six.reraise(*sys.exc_info())
  File "/root/Downloads/mitmproxy/libmproxy/protocol/tls.py", line 389, in _establish_tls_with_client_and_server
    self._establish_tls_with_client()
  File "/root/Downloads/mitmproxy/libmproxy/protocol/tls.py", line 398, in _establish_tls_with_client
    cert, key, chain_file = self._find_cert()
  File "/root/Downloads/mitmproxy/libmproxy/protocol/tls.py", line 497, in _find_cert
    host = self.server_conn.address.host
AttributeError: 'NoneType' object has no attribute 'host'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy

Following is my system configuration and setup.
1. # uname -a
Linux tn646-OptiPlex-745 4.2.3 #2 SMP Fri Oct 9 14:59:32 IST 2015 x86_64 x86_64 x86_64 GNU/Linux

2. $mitmdump --version
 mitmdump 0.15

3 Setup

Linux1_host-------------|Linux2_host with mitmdump|-------------Internet

When i am trying to open http websites from Linux1_host(firefox 28.0) i observed above mentioned trace in Linux2_host and here both Linux host are ubuntu.
Please help me here.

**Comment by Leseratte10** [comment]
I have the same issue. I use a device which does not support proxies so I've set up mitmproxy to listen on port 443 and use a DNS server to make the device connect to my computer instead of the website it wants to connect to. This raises this error on mitmproxy - why doesn't this work without proxying?

**Comment by mhils** [comment]
Take a look at http://docs.mitmproxy.org/en/stable/modes.html#transparent-proxy - what you're doing (DNS redirection) does not work, as mitmproxy is unable to figure out the original destination (as in the red illustration).

You can usually customize the standard gateway on the device, so I'd suggest doing that.

**Comment by Leseratte10** [comment]
Setting the default gateway to my computers IP resulted in the device not connecting at all (error) and mitmproxy doesn't show anything. 

Can't I just tell mitmproxy the correct destination host to forward all requests to? The device just connects to one single HTTPS site.

**Comment by mhils** [comment]
If you only have a single target address, just setup mitmproxy as a reverse proxy (see same docs page) and you should be good. :smiley:
