### ISSUE TITLE
Add domains using HSTS & HPKP as not to be touched

### ISSUE THREAD

**Issue by enesunal** [mitmproxy/mitmproxy#871]
The domains using HSTS & HPKP are available[1] in chromium source code. Is it possible to make these domains not to be touched by mitmproxy while processing HTTPS connections? 

 [1] : https://code.google.com/p/chromium/codesearch#chromium/src/net/http/transport_security_state_static.json

**Comment by mhils** [comment]
You can add this as a strategy to the conditional TLS interception inline
script (in the examples folder). FWIW, pinning is ignored by Chrome and
Firefox if the cert is signed by a CA that has been added manually to the
trust store (as it's usually the case with mitmproxy's CA). Besides, hosts
can manually mandate HPKP, the list in Chromium only contains the preloaded
ones.

enesunal <notifications@github.com> schrieb am Do., 31. Dez. 2015 09:57:

**Comment by enesunal** [comment]
I'll be using it with fresh clients, I assumed. Forgot to check examples folder. I'll modify and use that script. Thanks!
