### ISSUE TITLE
Export all the json responses from a domain name to a file?

### ISSUE THREAD

**Issue by medyagh** [mitmproxy/mitmproxy#873]
I tried to read the docs as much as I can and read the blogs, still didn't figure out how I can,
export all the Json resonses from a specific domain name to a file (ideally a CSV file so can I anayalze them or put them in a database)

**Comment by mhils** [comment]
Does http://docs.mitmproxy.org/en/stable/mitmdump.html#filtering-saved-traffic satisfy your needs?

**Comment by medyagh** [comment]
not really, I wanna export the recieved json to a human readable CSV ... that output just writes in a way mitmproxy can read it

**Comment by mhils** [comment]
If you need a custom output format, I'd recommend to just write an inline script for this: Just open a file in `start()` and write your csv line in `response()`.

https://github.com/mitmproxy/mitmproxy/blob/master/examples/modify_response_body.py
https://github.com/mitmproxy/mitmproxy/blob/master/examples/filt.py

**Comment by medyagh** [comment]
Thanks for response, so how can I make the script say only do it if it is a json response, for example I dont want to export the JPG or other Non-Json responses to a file?

**Comment by mhils** [comment]
My previous comment should have you covered how you can use mitmproxy filters :wink: 
Apart from that, you can of course check the response object manually. http://docs.mitmproxy.org/en/stable/dev/models.html#netlib.http.Response

**Comment by medyagh** [comment]
thanks I appreciate it, I will study it, is there a way I can get more real-life examples? other than those in the examples folder, any other documents I can study?

**Comment by mhils** [comment]
There's http://docs.mitmproxy.org/en/stable/scripting/inlinescripts.html, http://docs.mitmproxy.org/en/stable/dev/models.html and the examples in the example folder. Those should cover the mitmproxy-specific parts, everything else should be normal Python.

**Comment by medyagh** [comment]
Where is Slack ?

**Comment by Kriechi** [comment]
@medyagh see https://github.com/mitmproxy/mitmproxy/#documentation--help
or just go to http://slack.mitmproxy.org/ to join our Slack channel.
