### ISSUE TITLE
How to get whole decrypted packet.

### ISSUE THREAD

**Issue by mankalamanishkumar** [mitmproxy/mitmproxy#880]
By using assemble_request i was able to get decrypted payload, but how to get entire decrypted packet where i can able to access src, dst ip address, mark field etc.,

**Comment by mhils** [comment]
mitmproxy works on Layer 4 - there's no access to individual TCP packets. You can however access src/dst ip addresses on the flow (`flow.client.conn/server_conn`).

**Comment by mankalamanishkumar** [comment]
Hi Max,
            Thank you. How can i drop the request using inline script.

**Comment by mhils** [comment]
We have an example for this. Please read the docs and examples.

mankalamanishkumar <notifications@github.com> schrieb am Di., 12. Jan. 2016
12:39:
