### ISSUE TITLE
mitmweb --help should mention the default port

### ISSUE THREAD

**Issue by dufferzafar** [mitmproxy/mitmproxy#897]
I had to search the code to find the [default web port](https://github.com/dufferzafar/mitmproxy/blob/export/libmproxy/cmdline.py#L738) mitmweb listens on.

Shouldn't this value (and other defaults) be a part of the help output?

Perhaps something like?

```diff
diff --git a/libmproxy/cmdline.py b/libmproxy/cmdline.py
index 99b76e6..f93f482 100644
--- a/libmproxy/cmdline.py
+++ b/libmproxy/cmdline.py
@@ -737,7 +737,7 @@ def mitmweb():
         "--wport",
         action="store", type=int, dest="wport", default=8081,
         metavar="PORT",
-        help="Mitmweb port."
+        help="Mitmweb port. (default: 8081)"
     )
     group.add_argument(
         "--wiface",
```

**Comment by mhils** [comment]
The plan is to use Electron (or something along those lines) for mitmweb, which should solve this issue.

**Comment by lilydjwg** [comment]
I used lsof to find that :-)

**Comment by mhils** [comment]
Closing this for now, mitmweb usability is generally not tackled yet.
