### ISSUE TITLE
mitmproxy 0.15 breaks python 2 scripts

### ISSUE THREAD

**Issue by martinbilles** [mitmproxy/mitmproxy#903]
I have the following python2 script to run with mitmproxy:

```python
print "This is an " + "error"
```

I use the following bash command:

```bash
mitmdump -q --anticache -s ../script.py
```

`mitmproxy` version 0.14 correctly prints out the string.

`mitmproxy` version 0.15 gives me:

```
mitmdump: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libmproxy/script/script.py", line 65, in load
    execfile(self.args[0], self.ns, self.ns)
  File "../script.py", line 1
    print "This is an " + "error"
                      ^
SyntaxError: invalid syntax
```

**Comment by mhils** [comment]
Thanks for the report. This happend because we had a 

```python
from __future__ import print_function
```

statement in `libmproxy/script/script.py`, which was transitively applied to your inline script. Adding this to your script as well (and then using `print()` should work fine as a workaround.
