### ISSUE TITLE
Support for Interpreting Header Field Host

### ISSUE THREAD

**Issue by Cnly** [mitmproxy/mitmproxy#911]
Hi,

is it possible for mitmproxy to run in a mode where it reads the `Host` field in request headers and determine which server to send requests to?

For example, in the request
```
GET / HTTP/1.1
Host: bing.com     <-------
Connection: keep-alive
Accept: nothing
User-Agent: Apple II Chrome/0.46.0.2490.80 Safari/0.537.36
Accept-Encoding: 7z
Accept-Language: en-MARS
Cookie: toothpaste_flavour
```
it could be seen that the host is bing.com. So mitmproxy would just need to send this request to bing.com, and then log and return the reply to the victim.

**Comment by mhils** [comment]
You can just use an inline script for this - take a look at https://github.com/mitmproxy/mitmproxy/blob/master/examples/dns_spoofing.py.
