### ISSUE TITLE
--port doesn't seem to work?

### ISSUE THREAD

**Issue by colemickens** [mitmproxy/mitmproxy#912]
`mitmproxy --port 9000` and `mitmproxy --port=9000` both don't seem to have the desired effect.

http://docs.mitmproxy.org/en/stable/config.html contains the quote

>Note that `--port` is an option supported by all tools.

**Comment by dufferzafar** [comment]
@colemickens  For me, both of those commands work!

What error does it give you?

**Comment by colemickens** [comment]
Well, it tells me the port is in use because I'm already running it on the
default port elsewhere.

Does it actually do anything with the argument? Does it say that it's
listening on the port you passed in?

**Comment by dufferzafar** [comment]
Yeah, the `--port` argument does work. I've just tested running 3 instances of mitmproxy simultaneously with different ports specified. `mitmproxy --port 8080`, `mitmproxy --port 9000`, `mitmproxy --port 9080` and I don't see any errors.

**Comment by colemickens** [comment]
Oh boy, I'm sorry folks. I forgot that I wrote a wrapper function for mitmproxy and of course called it mitmproxy, which is why my args are being eaten. Totally my fault. Closing this.

Thanks for catching me.
