### ISSUE TITLE
proxy asks for authentication over LTE, but NOT over Wifi

### ISSUE THREAD

**Issue by sethgw** [mitmproxy/mitmproxy#915]
##### Steps to reproduce the problem:
1. install mitmproxy
2. turn off wifi on sprint device
3. make an http request

##### What is the expected behavior?
proxy should authenticate

##### What went wrong?
proxy won't authenticate over LTE on sprint iphones

##### Any other comments?

I have mitmproxy set up and working, but I'm experiencing strange issues.  Each device has a VPN profile we install containing the certificate.  On Att and Verizon phones there are no issues, but on Sprint phones the authentication only works over wifi.  When wifi is turned off and the request goes over LTE the proxy doesn't authenticate.

---
mitmproxy version: 0.13
Operating System:  ubuntu 14.04

**Comment by mhils** [comment]
I'm sorry, but I don't see how this is a mitmproxy issue?
