### ISSUE TITLE
Support for forward proxy with relative request form

### ISSUE THREAD

**Issue by strtok** [mitmproxy/mitmproxy#918]
As far as I can tell, there's no way to put mitmproxy in a mode where it's 
operating as a forward proxy without transparent interception and expects 
to receive requests in relative form.

Is there a way to override the relative vs. absolute check?

**Comment by mhils** [comment]
What is your definition of a forward proxy?

http://docs.mitmproxy.org/en/stable/modes.html

**Comment by strtok** [comment]
If I were to answer the questions on your diagram, my first answer would lead me left. But there is still a missing answer :)

I am using DNS as a method of interception. It's like using DNS to send traffic to a reverse proxy, but the proxy will frontend an arbitrary number of destinations.

**Comment by mhils** [comment]
So, you are using DNS-spoofing to redirect clients to your transparent (i.e. not explicitly configured on the client) proxy?

**Comment by strtok** [comment]
No. That's using a script to pull out the SNI field so that https continues to work, and then using -R as a workaround to treat the request as a reverse proxy request. I assume this doesn't work if you're spoofing millions of domains, since all requests would be forwarded to example.com regardless of the host header.

All I need is mitmproxy to ignore the fact I'm sending it a relative style request when it expects an absolute (explicit) proxy style request, and to forward to the OCS indicated in the host header instead of the domain that would have been in the absolute URL. 

Sounds like there's no switch to do this?

**Comment by mhils** [comment]
Looks like the docstring in the script above isn't particularly good. The script takes an incoming (relative) request and routes it to the host indicated by (1) the SNI value or the (2) Host header. The location specified in `-R` is taken if neither Host header nor SNI are present (you can just set it to a localhost:$randomclosedport).

**Comment by strtok** [comment]
Oh. That sounds like it might do it. I'll play around with it.

Thanks!

**Comment by mhils** [comment]
If you feel like you can make the documentation more clear here, we'd be happy to accept a PR. :-)
