### ISSUE TITLE
login.live.com crashing mitmproxy with bus error 10 on OS X 

### ISSUE THREAD

**Issue by mynamewasgone** [mitmproxy/mitmproxy#922]
##### Steps to reproduce the problem:
1. Run proxy on OS X El Capitan 10.11.4 Beta (pretty sure it happened with earlier stable versions)
2.Set up proxy on IOS 9.3 (and again earlier versions)
3. Request https://www.bungie.net/en/User/SignIn/Xuid?bru=%252f
4. mitmproxy crashes with Bus Error 10, and terminal is corrupted

##### What is the expected behavior?

Not crashing

##### Any other comments?

The bungie url redirects to login.live.com to do an OAuth login, it looks like the redirect is received by safari, and the next request/response crashes mitmproxy

---
mitmproxy version: 0.15

**Comment by mhils** [comment]
Thanks for the structured report. I just tried to reproduce this on Linux or Windows, but with no success - the requests just go through fine for me. Can you provide more details on the "Bus Error 10"?

**Comment by rbrown** [comment]
Not really, sorry. Here's the screen output with ./mitmproxy -ev -wfile output.txt
<img width="767" alt="screen shot 2016-02-09 at 09 16 44" src="https://cloud.githubusercontent.com/assets/233384/12912762/96be9e0c-cf12-11e5-9521-93ad13b30721.png">

doesn't write anything to output.txt though.

That is with the downloaded binary. I tried to get it up and running with the system python and brew python, but didn't have any luck. There's some stuff on google about it, but it wasn't particularly enlightening for me. I guess I can run it in a VM.

**Comment by mynamewasgone** [comment]
I ran it with ./mitmproxy -ev -wfile output.txt, it didn't write anything to output.txt though, this was the screen output:

<img width="767" alt="screen shot 2016-02-09 at 09 16 44" src="https://cloud.githubusercontent.com/assets/16834389/12912903/83be2ede-cf13-11e5-9a9c-1528bcf4225a.png">

That is with the downloaded binary. I tried to get it up and running with the system python and brew python, but didn't have any luck. There's some stuff on google about it, but it wasn't particularly enlightening for me. I guess I can run it in a VM.

**Comment by sztupy** [comment]
happens for me as well with OSX 10.10.5

**Comment by Kriechi** [comment]
@mynamewasgone could you explain a bit more? I'm not sure I understand your test setup.

So I just tried the following:
OSX 10.11 with latest mitmproxy running.
iOS 9.2.1 joined on the same Wifi & Network. In WiFi settings I set the IP+port of mitmproxy.
Then I started Safari on iOS and visited `https://www.bungie.net/en/User/SignIn/Xuid?bru=%252f`.
I got two SSL cert warnings, which I accepted/continued.
Then I only got a blank screen.

mitmproxy shows successful requests - and didn't crash.
<img width="1270" alt="screen shot 2016-02-12 at 18 31 42" src="https://cloud.githubusercontent.com/assets/114300/13015073/5ff99cda-d1b7-11e5-8238-b78d2824a3a6.png">

**Comment by mynamewasgone** [comment]
Yes, you've pretty much described the same action as me, except I have the mitmproxy on my phone so I don't get certificate prompts. Also on my screenshot I think I just refreshed safari, which had already been redirected to live.com.

**Comment by mhils** [comment]
If you are affected by this bugt, can you please post the output of  `openssl version` and `pip freeze`?

**Comment by mynamewasgone** [comment]
pip freeze: https://gist.github.com/anonymous/bc20459d774e3c242129
OpenSSL 0.9.8zh 14 Jan 2016

**Comment by kiancheong** [comment]
Just encountered this same issue myself, I'm running mitmproxy with a self-signed server
pip freeze: https://gist.github.com/kiancheong/584e18f3a7e01fdf759b
OpenSSL 0.9.8zh 14 Jan 2016

**Comment by mhils** [comment]
Thank you very much. Could you please check if you can reproduce the same bug with the binaries from mitmproxy.org or a newer OpenSSL release?

**Comment by ntulele** [comment]
I'm also encountering "mitmproxy crashes with Bus Error 10, and terminal is corrupted"  on OSX 10.11.4, with both Chrome and Safari when the website under test is performing an authentication redirect of some sort (passing off auth to a thirdparty, I beleive).

My openssl was version 0.9.8zh,  so I upgraded to OpenSSL 1.0.2g
But the issue still reproduces.

**Comment by mhils** [comment]
Thanks @ntulele. 
I'm closing this for now then. :-)

**Comment by ntulele** [comment]
Also: On a separate Mac with same OSX, OpenSSL, and mitmproxy versions where this issue was occurring, **I upgraded only mitmproxy to 0.17.1 and that resolved the issue.**

So upgrading OpenSSL from 0.9.8zh is _not necessary to resolve this issue._
