### ISSUE TITLE
Question on analyzing saved flows

### ISSUE THREAD

**Issue by joyofdata** [mitmproxy/mitmproxy#926]
Hello!

First of all - great software! Just what I need - not being a networking expert leaves me with a number of issues though. It seems that this issues section is used a forum - so I ask here. If there is some IRC channel or Google group I missed - please let me know.

Okay, so I capture traffic - works smoothly. Now I want to store the captured requests so I can analyze them tomorrow. Am I correct that the proper workflow is:

- [w]
- specify file path "~/mitmproxy_traffic"
- tomorrow: `mitmproxy -r ~/mitmproxy_traffic`

This seems to work - but there are at least three aspects about it that make me wonder if this is the optimal way to do it:

1. I cannot choose a file format (XML, CSV, ...) - **would like to**
2. it seems that I cannot store the unencrypted traffic (which I see in the console) - **would like to**
3. if I open the file with `mitmproxy -r` then mitmproxy is in active mode and new (completely unrelated) traffic is added to the loaded traffic - **would not like that**

Essentially my question is - is it possible to solve the issues described in a,b and c or are those indicators at missing features?

Kind Regards

Raffael

**Comment by mhils** [comment]
Hi Raffael,

Slack channel, IRC and mailing list are all listed on http://mitmproxy.org/, but posting here is perfectly fine as well. :wink: 

1. mitmproxy stores flows in its own serialization format. If you need a CSV export or something along those lines, take a look at [examples/read_dumpfile](https://github.com/mitmproxy/mitmproxy/blob/master/examples/read_dumpfile) and build your own ([see also](http://docs.mitmproxy.org/en/stable/dev/models.html)).
2. Traffic is stored unencrypted but raw, which is required in some forensic contexts. What you see is HTTP Content-Encoding (gzip, deflate, ...), not encryption. :-)
3. `  -n, --no-server       Don't start a proxy server.` should do the job. :smiley:

Questions answered?

**Comment by joyofdata** [comment]
> Slack channel, IRC and mailing list are all listed on http://mitmproxy.org/

stupid me - was just checking on http://docs.mitmproxy.org/

Thanks
