### ISSUE TITLE
Improve snapshots.mitmproxy.org

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#927]
Linking this here because most people won't see the release repo: We'd love to have help on https://github.com/mitmproxy/release/issues/3 - this is a really nice task for new contributors and I'm happy to help with getting things going.

Let's continue further discussion in the linked repo! :smiley:

**Comment by Kriechi** [comment]
closed by d3a9a6ba9520c5c80de3433697a8f5f30fa33c67
