### ISSUE TITLE
Use authentic certificates? (Not self signed)

### ISSUE THREAD

**Issue by jschwalbe** [mitmproxy/mitmproxy#930]
I stumbled across LetsEncrypt.org, they offer valid signed certificates for free, for your (sub)domain. Can this be used along with some dns spoofing to allow mp to not need to generate self signed certs? I'm thinking of those few apps that refuse to accept my self generated cert even if I accepted it earlier. 
Sorry if this is not the correct forum to discuss this. 

Thanms

**Comment by nashe** [comment]
It's not possible, since Let's Encrypt is checking that you owns the domain for which you are asking them to sign the certificate (see https://community.letsencrypt.org/t/how-do-you-confirm-the-person-asking-for-the-certificate-actually-owns-the-domain/30).

**Comment by jschwalbe** [comment]
You're correct about letsencrypt, but I think you misunderstand my idea. 

Let's say I own example.com. I get cert for example.com and forward traffic to another.com to mitm.example.com via dns hack then present a valid certificate. 

Doesn't this work?

**Comment by Kriechi** [comment]
It might - but then you need to run a DNS server and spoof everything.
I guess this is out of the scope of mitmproxy then, or did I miss something?

**Comment by jschwalbe** [comment]
See https://github.com/mitmproxy/mitmproxy/blob/master/examples/dns_spoofing.py

**Comment by mhils** [comment]
> Let's say I own example.com. I get cert for example.com and forward traffic to another.com to mitm.example.com via dns hack then present a valid certificate.

This does not work, as your client will still expect "another.com" as the certificate subject.
