### ISSUE TITLE
support for chunked transfer encoding

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#942]
_From @durin42 on May 4, 2012 21:25_

It'd be nice to be able to have pathod use chunked transfer encoding for responses and then be able to do drops and hangs partway through chunks.

_Copied from original issue: mitmproxy/pathod#1_

**Comment by Kriechi** [comment]
Closing, as pathod and pathoc command line tools and their libraries inside mitmproxy are deprecated. See #4273.
