### ISSUE TITLE
support for 100 CONTINUE

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#943]
_From @durin42 on May 4, 2012 21:26_

Would be lovely to support sending the continue status line both early and after a delay.

_Copied from original issue: mitmproxy/pathod#2_

**Comment by mhils** [comment]
_From @ghazel on March 2, 2013 23:47_

And not at all. "d0" still sends the 100 Continue response first before dropping the connection.

**Comment by alinpopa** [comment]
Any update on this? Really needed for mitmproxy to handle this properly, but instead, it looks it just strips out the `Expect:` header. If adding it back, using a script, it hangs in a 100-Continue request.

**Comment by mhils** [comment]
Are you referring to mitmproxy or pathod? mitmproxy handles 100-continue requests.

**Comment by alinpopa** [comment]
I'm referring to mitmproxy: have a script with two methods:
```
def request(flow):
    ctx.log.info(str(flow.request.headers))

def requestheaders(flow):
    ctx.log.info(str(flow.request.headers))
```

Looks that for the `requestheaders` method, I do have the `Expect` header, but it's missing within the request method; I guess that's the desired design?
Anyway, so after doing a proper request, using curl, and sniffing the network, not able to see any `100 Continue` requests, as opposed to when I'm doing a direct (i.e. no `mitmproxy`) request to my server. Not sure what I'm missing, but something doesn't work properly, or at least according to my expectations.
Thanks.

**Comment by mhils** [comment]
Ok, this is unrelated to this issue here (which is about pathod - sorry, that's not quite clear).

Can you please open a new issue describing your problem? FWIW, our code for handling 100-continue is here: https://github.com/mitmproxy/mitmproxy/blob/c0882496e37bbe6985b67ad94bdff72524b5b668/mitmproxy/proxy/protocol/http.py#L263-L285

**Comment by Kriechi** [comment]
Closing, as pathod and pathoc command line tools and their libraries inside mitmproxy are deprecated. See #4273.
