### ISSUE TITLE
support for invalid line endings

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#944]
_From @durin42 on May 4, 2012 21:26_

I've seen bad servers in the wild that respond with \n or \r (yes, \r) line endings instead of \r\n. It'd be great to be able to test that.

_Copied from original issue: mitmproxy/pathod#3_

**Comment by Kriechi** [comment]
Closing, as pathod and pathoc command line tools and their libraries inside mitmproxy are deprecated. See #4273.
