### ISSUE TITLE
language.parse_request: incorrect conversion between double and single quotes.

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#946]
_From @mhils on February 7, 2014 4:3_

In a nutshell,

get:**'http://127.0.0.1:52428/p/200:d0:h"Date"="Sun, 03 Mar 2013 04:00:00 GMT"'**
is converted to
get:<b>"http://127.0.0.1:52428/p/200:d0:h"</b>Date"="Sun, 03 Mar 2013 04:00:00 GMT""
which doesn't work for obvious reasons.

Code:
<pre>
>>> spec = 'get:\'http://127.0.0.1:52428/p/200:d0:h"Date"="Sun, 03 Mar 2013 04:00:00 GMT"\''
>>> language.parse_request(settings, spec)
get:"http://127.0.0.1:52428/p/200:d0:h"Date"="Sun, 03 Mar 2013 04:00:00 GMT""
</pre>

_Copied from original issue: mitmproxy/pathod#14_

**Comment by dufferzafar** [comment]
I'm not sure that I'm doing this correctly, but I ran this piece of code:

```python
from pathod import language

def parse_request(s):
    return language.parse_pathoc(s).next()

spec = 'get:\'http://127.0.0.1:52428/p/200:d0:h"Date"="Sun, 03 Mar 2013 04:00:00 GMT"\'')
print(parse_request(spec))
```

It gives the output:

`'GET':'http://127.0.0.1:52428/p/200:d0:h"Date"="Sun, 03 Mar 2013 04:00:00 GMT"'`

Which looks correct to me. :/

@mhils Can you please look into this?

**Comment by mhils** [comment]
Ok, looks like things are fixed. Thanks for investigating!
