### ISSUE TITLE
Scripts set in config files are cleared when passing scripts on the command line

### ISSUE THREAD

**Issue by fimad** [mitmproxy/mitmproxy#953]
In my config file I have several scripts that provide content views and do other miscellaneous things that I would like to apply to all my sessions. If I invoke `mitmproxy` with any scripts on the command line then all the scripts I defined in my config file are overridden and only the scripts on the command line are used.

Is this the intended behavior? If it is, would it be possible to add a new flag for scripts that are not intended to be overridden by scripts passed on the command line?

**Comment by mhils** [comment]
Happy to see what kind of power users we have :smile: 
This looks more like a silly limitation of ConfigArgParse than intended behavior.

**Comment by dufferzafar** [comment]
I feel this is a legitimate feature request mitmproxy and have created an upstream issue over at ConfigArgParse. If they are willing to add this to the library, I'd be happy to work on it and send them a pull. :smile:

**Comment by cortesi** [comment]
See #1699
