### ISSUE TITLE
fix for missing openssl/aes.h when building on osx

### ISSUE THREAD

**Issue by rtoma** [mitmproxy/mitmproxy#955]
Hi, just running ./dev.sh does not work on osx. It gives an error about clang and openssl/aes.h not found.

This can be fixed by setting vars before executing dev.sh:

```
$ LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" ./dev.sh
```

**Comment by Kriechi** [comment]
Actually this should not happen. cryptography ships a precompiled wheel with openssl included for OSX.

**Comment by Kriechi** [comment]
@rtoma: Which OSX version are you using? Could you try upgrading your cryptography from pip and try again without the additional flags? It should work out of the box - at least it does so on my OSX10.11 with python2.7 from homebrew and no openssl installed.
