### ISSUE TITLE
ServerConnection.source_address is now empty

### ISSUE THREAD

**Issue by crutledge** [mitmproxy/mitmproxy#956]
##### Steps to reproduce the problem:
1. Access a Flow object in handle_response or handle_request
2. Print source_address property from the Flow's server_conn (ServerConnection object)

##### What is the expected behavior?
Should see a display of tcp.Address when ServerConnection is not None and only ('', 0) when ServerConnection is None.

##### What went wrong?
Only shows ('', 0) even when a valid ServerConnection is not None

##### Any other comments?
This does not seem to be affecting ClientConnection.address at all.

---
mitmproxy version: 0.16
Operating System: OS X 10.10.5

**Comment by mhils** [comment]
Thanks. What do you expect to find in source_address?

**Comment by crutledge** [comment]
As of v0.15 it contained a map of the IP and port of the client connection that served the request to the target server. After the update to v0.16 I noticed that it was no longer being populated. I wasn't entirely sure if this was intentional (possibly phasing out source_address eventually?).

**Comment by mhils** [comment]
Thanks for clarifying. Looks like we introduced this regression in #879.
