### ISSUE TITLE
workaround for empty reponse header value

### ISSUE THREAD

**Issue by rtoma** [mitmproxy/mitmproxy#957]
Hi, I hit a site that responds with a Pragma header without a value:
```
Pragma:
```

Mitmproxy 0.14.0 (from homebrew) is unable to handle this and throws this to the client:
```
<html>
            <head>
                <title>502 Bad Gateway</title>
            </head>
            <body>HttpSyntaxException('Invalid headers',)</body>
```

My workaround in netlib/http/http1/read.py
```
--- read.py.original	2016-02-17 20:57:32.000000000 +0100
+++ netlib-http-http1-read.py	2016-02-17 20:59:46.000000000 +0100
@@ -321,7 +321,7 @@ def _read_headers(rfile):
             try:
                 name, value = line.split(b":", 1)
                 value = value.strip()
-                if not name or not value:
+                if not name:
                     raise ValueError()
                 ret.append([name, value])
             except ValueError:
```

ymmv

**Comment by Kriechi** [comment]
Could you please try with the latest release 0.16 - this might already be fixed.
Thanks.

**Comment by Kriechi** [comment]
Actually, I think an empty HTTP header value for `pragma` is against the spec, as it expects exactly one token as value - so returning an error "Invalid headers" is perfectly fine.

Now, we might have the issue that empty values should be allowed in general, according to the spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
/cc @mhils

**Comment by mhils** [comment]
Let's take the new RFC: https://tools.ietf.org/html/rfc7230#section-3.2

```
header-field   = field-name ":" OWS field-value OWS       // OWS is optional white space
field-value    = *( field-content / obs-fold )
```
According to the [ABNF](https://tools.ietf.org/html/rfc5234#section-3.6) used, `*` indicates zero or more repetitions. So yes, it looks like empty values are allowed and we should fix this. ¯\_(ツ)_/¯

**Comment by mhils** [comment]
Looks like this is already fixed...
https://github.com/mitmproxy/mitmproxy/blob/e8611acb76fcd4d6e06659cbb0ff36c4449d5c35/netlib/http/http1/read.py#L324
