### ISSUE TITLE
Error in setting dev environment

### ISSUE THREAD

**Issue by anchitjain1234** [mitmproxy/mitmproxy#972]
##### Steps to reproduce the problem:

1. Did steps as described in ``README``, cloned the project and then used ``./dev.sh``. When ``dev.sh`` script executes it gives error ``TypeError: find_packages() got an unexpected keyword argument 'include'``

##### What is the expected behavior?
Virtualenv should set up.

##### What went wrong?
Unexpected error while installing ``TypeError: find_packages() got an unexpected keyword argument 'include'``

##### Any other comments?
Full error log
```
New python executable in ./venv/bin/python
Installing setuptools, pip...done.
Obtaining file:///home/ubuntu/workspace/mitmproxy (from -r requirements.txt (line 1))
  Running setup.py (path:/home/ubuntu/workspace/mitmproxy/setup.py) egg_info for package from file:///home/ubuntu/workspace/mitmproxy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/ubuntu/workspace/mitmproxy/setup.py", line 47, in <module>
        "netlib", "netlib.*"
    TypeError: find_packages() got an unexpected keyword argument 'include'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/ubuntu/workspace/mitmproxy/setup.py", line 47, in <module>

    "netlib", "netlib.*"

TypeError: find_packages() got an unexpected keyword argument 'include'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/ubuntu/workspace/mitmproxy
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

---

Mitmproxy Version:
Operating System: Ubuntu 14.04

**Comment by Kriechi** [comment]
@anchitjain1234 thanks for the nice bug report - a single search on the internet points to an outdated pip/setuptools.
See https://stackoverflow.com/questions/29477456/find-package-errors-during-installing-package-via-pip

**Comment by anchitjain1234** [comment]
@Kriechi Sorry if I sounded silly. I already have uptodate setuptools and pip but than also I am getting same error. Thats why I opened this issue.

**Comment by Kriechi** [comment]
Can you show us your pip version? Run `pip -V` and `python -V`

**Comment by anchitjain1234** [comment]
Pip version ``pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)``
Python version ``Python 2.7.6``

**Comment by Kriechi** [comment]
Well, as said - you need to update your pip & setuptools. I guess at least 6.x is required.

**Comment by anchitjain1234** [comment]
Thanks @Kriechi.

**Comment by mhils** [comment]
Meh - This is the same problem as with `~=` compatibility specifiers - it doesn't work on the old Ubuntu LTSes. Looks like this was introduced in [setuptools 3.3](https://pythonhosted.org/setuptools/history.html#id134). We need to use a list comprehension here instead.

**Comment by mhils** [comment]
Ok, scratch that - it should just work if we fix the dev script.
