### ISSUE TITLE
Flow Export Improvements

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#976]
There are currently three ways to export flows in mitmproxy:

- `b` "save request/response body"
- `E` "export"
- `P` "copy request/response (content/headers) to clipboard"

This is kind of confusing - in particular, there's a lot of overlap between `E` and `P`. Having `b` separately isn't too bad I think, this probably the most-popular action you want to do. I'd propose we do something like this:

![image](https://cloud.githubusercontent.com/assets/1019198/13254233/cda4effa-da40-11e5-96e9-830d9ab55c24.png)

Thoughts?

**Comment by dufferzafar** [comment]
This is certainly better than what we currently have. Apart from the `b` key duplicating things a little bit, I can't see anything wrong with it. 

I'll start working on this as soon as possible! :smile_cat: 

P.S: What tool did you use to create that neat chart?

**Comment by mhils** [comment]
Great, happy to hear that! :smiley:

Chart is made in 5 minutes with Microsoft Visio. :stuck_out_tongue:

**Comment by Dutchy-** [comment]
Do you think it's possible to account for marked flows? I have the occasional use case where I export multiple raw requests/responses to include them in a report. For example, to document a login or redirect sequence.

**Comment by mhils** [comment]
I think we want to limit this export feature to single flows for now. The semantics of the whole feature get too complex otherwise I'm afraid.

**Comment by dufferzafar** [comment]
These hotkeys should be available in both `flowlist` and `flowview` right?

In `flowview`, the key `p` is already bound to previous flow!

**Comment by dufferzafar** [comment]
Also, [`Headers+Content`](https://github.com/dufferzafar/mitmproxy/blob/flow-export/mitmproxy/console/common.py#L263-265) is the same as [`Raw Request`](https://github.com/dufferzafar/mitmproxy/blob/flow-export/mitmproxy/flow/export.py#L97-100)

**Comment by mhils** [comment]
> These hotkeys should be available in both flowlist and flowview right?

Yes! :smiley:

> In flowview, the key p is already bound to previous flow!

Hm - unless there are better options, we can probably remove this?

> So, having them both doesn't make much sense.

Agreed - let's just keep one of these :+1:

**Comment by dufferzafar** [comment]
The `Up/Down` arrow keys seem to free in flowview. I could bind Prev/Next to them?
