### ISSUE TITLE
./dev.sh script no longer works

### ISSUE THREAD

**Issue by fimad** [mitmproxy/mitmproxy#977]
##### Steps to reproduce the problem:

1. git clone https://github.com/mitmproxy/mitmproxy.git
2. cd mitmproxy
2. ./dev.sh

##### What is the expected behavior?

A working virtual environment is created.

##### What went wrong?

pip fails with the following error:
```
New python executable in ./venv/bin/python
Installing setuptools, pip...done.
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-8.0.2-py2.py3-none-any.whl#md5=2056f553d5b593d3a970296f229c1b79
  Downloading pip-8.0.2-py2.py3-none-any.whl (1.2MB): 1.2MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...
Obtaining file:///home/willcoster/Code/mitmproxy (from -r requirements.txt (line 1))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/willcoster/Code/mitmproxy/setup.py", line 47, in <module>
        "netlib", "netlib.*"
    TypeError: find_packages() got an unexpected keyword argument 'include'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/willcoster/Code/mitmproxy
```
##### Any other comments?

---

Mitmproxy Version: 02ec4c820743f98f3145820979bedad26a3c85e8
Operating System: Linux

**Comment by geekman** [comment]
I was about to file this bug. The error is due to an old version of *setuptools*, which I found out from Stackoverflow here: http://stackoverflow.com/questions/29477456/find-package-errors-during-installing-package-via-pip

I would advise adding the line `pip install -U setuptools` after upgrading `pip` in `dev.sh`.
