### ISSUE TITLE
Add Icon for Binaries

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#981]
The OSX and Windows binaries we currently generate have the default PyInstaller Icon:
![image](https://cloud.githubusercontent.com/assets/1019198/13373067/3240ee18-dd5d-11e5-922f-bd806c651765.png)

It would be super cool if we could have our mitmproxy icon there. The icon is in the [mitmproxy.org repo](https://github.com/mitmproxy/mitmproxy.org) (favicon version in ./src, raw logo in ./logo).

**Comment by adityadivekar03** [comment]
Hi!
I would like to work on this issue. I'm trying to understand the codebase and think this will be a good way to start. I'll revert with any queries.

**Comment by Kriechi** [comment]
fixed by https://github.com/mitmproxy/mitmproxy/pull/1023
