### ISSUE TITLE
Ignore HTTP traffic

### ISSUE THREAD

**Issue by arnau** [mitmproxy/mitmproxy#982]
This is question about `--ignore` I'm not able to solve by reading http://docs.mitmproxy.org/en/stable/features/passthrough.html

##### Steps to reproduce the problem:

1. Run `mitmdump -I google.com -s foo.py` (see below for `foo.py`'s content).
2. Run `curl --proxy http://localhost:8080 http://google.com`.

```python
# foo.py
def request(context, flow):
  print("url", flow.request.url)
```

##### What is the expected behavior?

I expect the script to not handle the request.

##### What went wrong?

The requests is handled by the script. The STDOUT shows:

```
127.0.0.1:65318: clientconnect
('url', 'http://google.com/')
127.0.0.1 GET http://google.com/
 << 302 Found 261B
127.0.0.1:65318: clientdisconnect
```

##### Any other comments?

When I run the same but using HTTPS, the request is not handled by the script as I expected.

1. Run `mitmdump -I google.com -s foo.py`.
2. Run `curl --proxy http://localhost:8080 https://google.com`.

Results in:

```
127.0.0.1:65318: clientconnect
127.0.0.1:65318: clientdisconnect
```

If `--ignore` is only intended to ignore HTTPS traffic, the question is: How do I ignore HTTP traffic too?

Thanks,

---

Mitmproxy Version: 0.16, 0.15
Operating System: OSX 10.11
Python: 2.7

I tested it with a dockerised Debian 8, Python 2.7 and mitmproxy 0.15 as well with the same result.

**Comment by mhils** [comment]
Thanks for the strong report.
This is a known limitation we can't fix unfortunately. From http://docs.mitmproxy.org/en/stable/features/passthrough.html:

> In regular mode, explicit HTTP requests are never ignored. [1] The ignore pattern is applied on CONNECT requests, which initiate HTTPS or clear-text WebSocket connections.

What's your final goal? Setting a filter or passing `--raw-tcp` may be what you are actually after.

Cheers,
Max

**Comment by arnau** [comment]
Hi, ugh I missed this paragraph :(  Thanks for the quick answer!

Well, I'm making a tool on top of mitmdump to do API mocking via mitm.  Because my main use cas involves iOS simulator I cannot set a proxy in this device and I have to use a OSX proxy setting which applies to all requests happening with other http clients (e.g. browsers).  My idea was to make the proxy be the least intrusive as possible.
