### ISSUE TITLE
Update examples to reflect new location of 'decoded'

### ISSUE THREAD

**Issue by ironhokie** [mitmproxy/mitmproxy#985]
##### Steps to reproduce the problem:

1. Several current examples use "from mitmproxy.models import decoded"
2. We should use "from libmproxy.models import decoded"

##### Any other comments?

---

Mitmproxy Version: 0.16
Operating System: CentOS

**Comment by dufferzafar** [comment]
@ironhokie I think you have a version mismatch. You must be having mitmproxy 0.16 but are looking at examples (perhaps from the Github repo) that have now been modified!

These changes were made in https://github.com/mitmproxy/mitmproxy/commit/d95a1f9819ded642174fad789a8fb0c595ca0840 following a repo restructure.
