### ISSUE TITLE
har_extractor.py usage example

### ISSUE THREAD

**Issue by colemickens** [mitmproxy/mitmproxy#986]
I don't know if I'm just looking in the wrong place, but I've been trying to convert a flow to a har for hours and am hitting road block after road block (largely due to python acquisition/package management). Now I have everything in place and I still don't really have any idea how to "use" `har_extractor.py`.

**Comment by colemickens** [comment]
If I figure it out, I'll send a PR adding some notes somewhere...

**Comment by colemickens** [comment]
So, it was me looking in the wrong place. I needed to be looking at the mitmdump documentation. I thought the script was loaded into mitmproxy.

This was the relevant page, in case someone winds up here via Google in the future:
http://mitmproxy.org/doc/mitmdump.html

Full instructions:

```
apt-get update
apt-get install python-pip mitmproxy
pip install setuptools
pip install harparser
wget https://raw.githubusercontent.com/mitmproxy/mitmproxy/master/examples/har_extractor.py
mitmdump -ns "har_extractor.py bugreport.har" -r ./bugreport.flow
```

**Comment by mhils** [comment]
Sorry for the confusion :-/

What did you try to install stuff and how did it fail?
`pip install mitmproxy[examples]` should install everything that is needed, so we may just need to document that better.

You should be able to use the har_extractor like so: 
`mitmdump -n -r dumpfile -s "har_extractor.py harfile.har"`

**Comment by mhils** [comment]
Ah, happy to hear that things cleared up - if you happen to struggle with something like that again, please don't refrain and ask on Slack. :relaxed:

**Comment by colemickens** [comment]
Hehe, thanks Maximilian. I will definitely keep Slack in mind. Cheers.

**Comment by dune73** [comment]
Mitmproxy with this functionality is exactly what I have been looking for! However, I can't get it to work:

```
$> mitmdump -n -r dumpfile -s "har_extractor.py harfile.har"
mitmdump: No such file: har_extractor.py harfile.har
$> mitmdump -n -r dumpfile -s har_extractor.py harfile.har
mitmdump: Error in script start:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/libmproxy/script.py", line 51, in run
    return (True, f(self.ctx, *args, **kwargs))
TypeError: start() takes exactly 2 arguments (1 given)

```

mitmproxy version is 0.9.2-2 from Ubuntu 14.04. (Latest mitmproxy installed via pip fails with mitmdump)

Am I doing something wrong?

**Comment by kimsangsoo** [comment]
I have error 
- Script error: TypeError: done() takes exactly 1 argument (0 given) -

cmd : mitmdump -n -r test.dump  -s "har_extractor.py test.har"

**Comment by itaibh** [comment]
For anyone reading this, as for mitmproxy version 6.0.2, this worked for me:

```
mitmdump -n -r test.dump -s har_dump.py --set hardump=test.har
```

You can find `har_dump.py` on a Linux installation in this directory: `/usr/share/doc/mitmproxy/examples/complex`, or just get it here: https://github.com/mitmproxy/mitmproxy/blob/master/examples/contrib/har_dump.py
