### ISSUE TITLE
[linux/ubuntu] Bad request: expected: relative, got: authority 

### ISSUE THREAD

**Issue by ahmetalpbalkan** [mitmproxy/mitmproxy#996]
##### Steps to reproduce the problem:

2. `cp ~/.mitmproxy/mitmproxy-ca-cert.pem /usr/share/ca-certificates/extra`
3. `sudo dpkg-reconfigure ca-certificates` (approve prompts)
4. `sysctl -w net.ipv4.ip_forward=1`
5. `echo 0 | sudo tee /proc/sys/net/ipv4/conf/*/send_redirects`
5. `sudo iptables -t nat -A PREROUTING -i eth0 -p tcp -m multiport --dports 80,443,9000,9443 -j REDIRECT --to-port 8080`
6. Start as `mitmproxy -T --host`
7. `curl -x localhost:8080 http://mitm.it` --> bad request.

##### What went wrong?

My intercepted queries are responded with Bad Request and in the event log I see:

```
127.0.0.1:34824: clientconnect
127.0.0.1:34824: ProtocolException("Error in HTTP connection: HttpException('Invalid HTTP request form (expected: relative, got: authority)',)",)
127.0.0.1:34824: clientdisconnect
```

Any ideas what might be going wrong?

---
Mitmproxy Version: 0.15
Operating System: Ubuntu Server 14.04.3 LTS

**Comment by mhils** [comment]
Sorry for the slow response. This sounds like you have set up mitmproxy in transparent mode but also configured your client to use a proxy?

http://docs.mitmproxy.org/en/stable/modes.html
